const phaseId = '6a369d5c66020ed05b32143f'; // Phase 14: LLM Engineering
const moduleId = '6a369d5c66020ed05b321460'; // Module 218: Caching, Rate Limiting and Cost

module.exports = {
  phaseId,
  moduleId,
  order: 0,
  type: 'interactive',
  duration: 40,
  difficulty: 'advanced',
  status: 'published',
  title: 'Caching, Rate Limiting & Cost Optimization — Part 1: Cost Anatomy, Exact Caching, and Semantic Caching',
  titleKn: 'Caching, Rate Limiting & Cost Optimization — ಭಾಗ 1: Cost Anatomy, Exact Caching, ಮತ್ತು Semantic Caching',
  desc: 'Genuinely build PricingTable and confirm real cost splits between normal, cached, and output tokens; genuinely build ExactCache and confirm its SHA-256 miss-then-hit lifecycle; genuinely build SemanticCache and catch a real floating-point edge case where a genuine paraphrase narrowly misses an exact 0.80 threshold because its true similarity is 0.7999999999999999, not 0.8.',
  descKn: 'PricingTable ಅನ್ನು ನಿಜವಾಗಿ ನಿರ್ಮಿಸಿ normal, cached, ಮತ್ತು output tokens ನಡುವಿನ ನಿಜ cost ವಿಭಜನೆ ದೃಢಪಡಿಸಿ; ExactCache ಅನ್ನು ನಿಜವಾಗಿ ನಿರ್ಮಿಸಿ ಇದೂ ya SHA-256 miss-then-hit lifecycle ದೃಢಪಡಿಸಿ; SemanticCache ಅನ್ನು ನಿಜವಾಗಿ ನಿರ್ಮಿಸಿ ಒಂದು ನಿಜ floating-point edge case ಹಿಡಿಯಿರಿ ಇಲ್ಲಿ ಒಂದು ನಿಜ paraphrase ನಿಖರವಾಗಿ 0.80 threshold ಅನ್ನೂ ಸ್ವಲ್ಪದರಲ್ಲಿ ತಪ್ಪಿಸಿಕೊಳ್ಳುತ್ತದೆ ಇದೂ ya ನಿಜ similarity 0.7999999999999999 ಆಗಿರುವುದರಿಂದ, 0.8 ಅಲ್ಲ.',
  objectives: [
    'Explain the cost anatomy of an LLM request (input/cached-input/output tokens times their respective prices) and why redundant computation across users is a major cost driver at scale.',
    'Distinguish provider prompt caching (which still calls the LLM but processes repeated prefixes more cheaply) from application-layer exact and semantic caching (which can avoid the LLM call entirely).',
    'Genuinely implement PricingTable.calculate() and confirm it correctly splits a 4000-input/3000-cached/800-output request into normal_input_cost, cached_input_cost, and output_cost.',
    'Genuinely implement ExactCache with a SHA-256 canonical-JSON key and confirm its exact miss-then-hit lifecycle, including why it is deliberately gated to temperature=0 requests only.',
    'Genuinely implement simple_embedding()/cosine_similarity()/SemanticCache and confirm a real paraphrase scores exactly 0.8 similarity, clearing a 0.50 threshold but genuinely, honestly missing an exact 0.80 threshold due to floating-point representation (0.7999999999999999, not 0.8).',
    'Explain the exact-cache-then-semantic-cache-then-LLM tiered lookup order and the core semantic-caching risk of returning a wrong answer across queries that are lexically similar but require different authorization or context.',
  ],
  objectivesKn: [
    'ಒಂದು LLM request ya cost anatomy ವಿವರಿಸಿ (input/cached-input/output tokens ಅವುಗಳ ಸಂಬಂಧಿತ prices ಇಂದ ಗುಣಿಸಿ) ಮತ್ತು scale ನಲ್ಲಿ users ಗಳಾದ್ಯಂತ redundant computation ಒಂದು ಮುಖ್ಯ cost driver ಏಕೆ.',
    'Provider prompt caching ಅನ್ನು (ಇನ್ನೂ LLM ಕರೆ ಮಾಡುತ್ತದೆ ಆದರೆ ಪುನರಾವರ್ತಿತ prefixes ಅನ್ನೂ ಅಗ್ಗವಾಗಿ ಪ್ರಕ್ರಿಯೆಗೊಳಿಸುತ್ತದೆ) application-layer exact ಮತ್ತು semantic caching ಇಂದ (LLM ಕರೆಯನ್ನೂ ಸಂಪೂರ್ಣವಾಗಿ ತಪ್ಪಿಸಬಹುದು) ಪ್ರತ್ಯೇಕಿಸಿ.',
    'PricingTable.calculate() ಅನ್ನು ನಿಜವಾಗಿ ಜಾರಿಗೊಳಿಸಿ ಮತ್ತು ಇದೂ ಒಂದು 4000-input/3000-cached/800-output request ಅನ್ನೂ normal_input_cost, cached_input_cost, ಮತ್ತು output_cost ಗೆ ಸರಿಯಾಗಿ ವಿಭಜಿಸುತ್ತದೆ ಎಂದು ದೃಢಪಡಿಸಿ.',
    'ExactCache ಅನ್ನು ಒಂದು SHA-256 canonical-JSON key ಜೊತೆ ನಿಜವಾಗಿ ಜಾರಿಗೊಳಿಸಿ ಮತ್ತು ಇದೂ ya ನಿಖರ miss-then-hit lifecycle ದೃಢಪಡಿಸಿ, ಇದೂ ಏಕೆ ಉದ್ದೇಶಪೂರ್ವಕವಾಗಿ ಕೇವಲ temperature=0 requests ಗೆ ಗೇಟ್ ಆಗಿದೆ ಎಂಬುದೂ ಸೇರಿ.',
    'simple_embedding()/cosine_similarity()/SemanticCache ಅನ್ನು ನಿಜವಾಗಿ ಜಾರಿಗೊಳಿಸಿ ಮತ್ತು ಒಂದು ನಿಜ paraphrase ನಿಖರವಾಗಿ 0.8 similarity ಗಳಿಸುತ್ತದೆ ಎಂದು ದೃಢಪಡಿಸಿ, ಒಂದು 0.50 threshold ತೆರವುಗೊಳಿಸುತ್ತಾ, ಆದರೆ ನಿಜವಾಗಿ, ಪ್ರಾಮಾಣಿಕವಾಗಿ ಒಂದು ನಿಖರ 0.80 threshold ಅನ್ನೂ floating-point representation ಕಾರಣ ತಪ್ಪಿಸಿಕೊಳ್ಳುತ್ತದೆ (0.7999999999999999, 0.8 ಅಲ್ಲ).',
    'Exact-cache-then-semantic-cache-then-LLM tiered lookup order ಮತ್ತು ಮುಖ್ಯ semantic-caching ಅಪಾಯ ವಿವರಿಸಿ: lexically similar ಆದರೆ ಭಿನ್ನ authorization ಅಥವಾ context ಬಯಸುವ queries ಗಳಾದ್ಯಂತ ಒಂದು ತಪ್ಪು ಉತ್ತರ ಹಿಂತಿರುಗಿಸುವುದೂ.',
  ],
  blocks: [
    { type: 'heading', data: { textEn: 'Caching, Rate Limiting & Cost Optimization — Part 1: Cost Anatomy, Exact Caching, and Semantic Caching', textKn: 'Caching, Rate Limiting & Cost Optimization — ಭಾಗ 1: Cost Anatomy, Exact Caching, ಮತ್ತು Semantic Caching', level: 'H1' } },
    { type: 'concept', data: {
      headingEn: 'Lesson Info', headingKn: 'ಪಾಠದ ಮಾಹಿತಿ',
      bodyEn: '• Type: Build · Language: Python · Prerequisite: Module 217 (Evaluation and Testing) · Time: ~40 minutes · Part 1 of 3',
      bodyKn: '• ಪ್ರಕಾರ: Build · ಭಾಷೆ: Python · ಪೂರ್ವಾಪೇಕ್ಷಿತ: Module 217 (Evaluation and Testing) · ಸಮಯ: ~40 ನಿಮಿಷಗಳು · ಭಾಗ 1 ರಲ್ಲಿ 3',
      pillsEn: 'Cost Anatomy,Exact Cache,Semantic Cache,SHA-256',
      pillsKn: 'Cost Anatomy,Exact Cache,Semantic Cache' } },

    { type: 'heading', data: { textEn: 'Every LLM Request Is Also a Financial Transaction', textKn: 'ಪ್ರತಿ LLM Request ಒಂದು Financial Transaction ಕೂಡ', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'The Cost Anatomy of a Single Request', headingKn: 'ಒಂದೇ Request ya Cost Anatomy',
      bodyEn: 'A single chatbot request with a 1,500-token system prompt, 2,500 tokens of retrieved RAG context, and a 100-token user question totals 4,100 input tokens plus, say, a 500-token generated answer -- cost = (input_tokens/1e6)*price_input + (output_tokens/1e6)*price_output. That single request may be cheap, but 10,000 daily active users each making 10 queries a day means 100,000 requests/day, and repeated system prompts, repeated RAG context, and near-duplicate questions across those requests make redundant computation one of the largest cost drivers at scale.',
      bodyKn: 'ಒಂದೇ chatbot request 1,500-token system prompt, 2,500 tokens retrieved RAG context, ಮತ್ತು 100-token user question ಜೊತೆ ಒಟ್ಟೂ 4,100 input tokens ಆಗುತ್ತದೆ ಜೊತೆಗೆ, ಹೇಳಿ, 500-token ಉತ್ಪಾದಿಸಿದ ಉತ್ತರ -- cost = (input_tokens/1e6)*price_input + (output_tokens/1e6)*price_output. ಆ ಒಂದೇ request ಅಗ್ಗವಾಗಿರಬಹುದು, ಆದರೆ 10,000 daily active users ಪ್ರತಿಯೊಬ್ಬರೂ ದಿನಕ್ಕೆ 10 queries ಮಾಡುವುದೂ ಎಂದರೆ 100,000 requests/day, ಮತ್ತು ಆ requests ಗಳಾದ್ಯಂತ ಪುನರಾವರ್ತಿತ system prompts, ಪುನರಾವರ್ತಿತ RAG context, ಮತ್ತು ಬಹುತೇಕ-ನಕಲಿ ಪ್ರಶ್ನೆಗಳು redundant computation ಅನ್ನೂ scale ನಲ್ಲಿ ಅತಿ ದೊಡ್ಡ cost drivers ಗಳಲ್ಲಿ ಒಂದಾಗಿ ಮಾಡುತ್ತವೆ.' } },
    { type: 'concept', data: {
      headingEn: 'Provider Prompt Caching vs Application-Layer Response Caching', headingKn: 'Provider Prompt Caching vs Application-Layer Response Caching',
      bodyEn: 'A provider prompt-cache hit still calls the LLM to generate an answer, just with lower input-processing cost on the repeated prefix; an application response-cache hit (exact or semantic) skips the LLM generation call entirely and returns a stored answer directly. These are genuinely different layers: provider caching reduces the cost of a call that still happens, while exact/semantic caching can eliminate the call altogether.',
      bodyKn: 'ಒಂದು provider prompt-cache hit ಇನ್ನೂ ಒಂದು ಉತ್ತರ ಉತ್ಪಾದಿಸಲು LLM ಕರೆ ಮಾಡುತ್ತದೆ, ಕೇವಲ ಪುನರಾವರ್ತಿತ prefix ಮೇಲೆ ಕಡಿಮೆ input-processing cost ಜೊತೆ; ಒಂದು application response-cache hit (exact ಅಥವಾ semantic) LLM generation ಕರೆಯನ್ನೂ ಸಂಪೂರ್ಣವಾಗಿ ಬಿಟ್ಟುಬಿಡುತ್ತದೆ ಮತ್ತು ಒಂದು ಶೇಖರಿಸಿದ ಉತ್ತರವನ್ನೂ ನೇರವಾಗಿ ಹಿಂತಿರುಗಿಸುತ್ತದೆ. ಇವು ನಿಜವಾಗಿ ಭಿನ್ನ ಪದರಗಳು: provider caching ಇನ್ನೂ ಸಂಭವಿಸುವ ಒಂದು ಕರೆ ya cost ಕಡಿಮೆ ಮಾಡುತ್ತದೆ, ಆದರೆ exact/semantic caching ಕರೆಯನ್ನೂ ಸಂಪೂರ್ಣವಾಗಿ ತೆಗೆದುಹಾಕಬಹುದು.' } },

    { type: 'heading', data: { textEn: 'Genuinely Building PricingTable', textKn: 'PricingTable ಅನ್ನು ನಿಜವಾಗಿ ನಿರ್ಮಿಸುವುದು', level: 'H2' } },
    { type: 'code', data: {
      filename: 'pricing_table.py', headingEn: 'Genuinely implementing PricingTable.calculate() and splitting cost across normal, cached, and output tokens', headingKn: 'PricingTable.calculate() ಅನ್ನು ನಿಜವಾಗಿ ಜಾರಿಗೊಳಿಸಿ normal, cached, ಮತ್ತು output tokens ಗಳಾದ್ಯಂತ cost ವಿಭಜಿಸುವುದು',
      descEn: 'Three illustrative model tiers, each with a separate cached-input price lower than the normal input price. calculate() subtracts cached_input_tokens from input_tokens before pricing the remainder at the full rate.',
      descKn: 'ಮೂರು ವಿವರಣಾತ್ಮಕ model tiers, ಪ್ರತಿಯೊಂದೂ ಸಾಮಾನ್ಯ input price ಗಿಂತ ಕಡಿಮೆ ಇರುವ ಒಂದು ಪ್ರತ್ಯೇಕ cached-input price ಜೊತೆ. calculate() ಪೂರ್ಣ ದರದಲ್ಲಿ ಉಳಿದದ್ದೂ price ಮಾಡುವ ಮೊದಲೂ input_tokens ಇಂದ cached_input_tokens ಕಳೆಯುತ್ತದೆ.',
      code: "from dataclasses import dataclass\n\n@dataclass(frozen=True)\nclass ModelPrice:\n    input_per_million: float\n    output_per_million: float\n    cached_input_per_million: float\n\nclass PricingTable:\n    def __init__(self):\n        self.models = {\n            'small-model': ModelPrice(0.20, 0.80, 0.10),\n            'medium-model': ModelPrice(2.00, 8.00, 1.00),\n            'large-model': ModelPrice(10.00, 30.00, 2.00),\n        }\n\n    def calculate(self, model, input_tokens, output_tokens, cached_input_tokens=0):\n        if model not in self.models:\n            raise ValueError(f'Unknown model: {model}')\n        if cached_input_tokens > input_tokens:\n            raise ValueError('cached_input_tokens cannot exceed input_tokens')\n        price = self.models[model]\n        normal_input_tokens = input_tokens - cached_input_tokens\n        normal_input_cost = normal_input_tokens / 1_000_000 * price.input_per_million\n        cached_input_cost = cached_input_tokens / 1_000_000 * price.cached_input_per_million\n        output_cost = output_tokens / 1_000_000 * price.output_per_million\n        total = normal_input_cost + cached_input_cost + output_cost\n        return {\n            'model': model, 'input_tokens': input_tokens, 'cached_input_tokens': cached_input_tokens,\n            'output_tokens': output_tokens, 'input_cost': round(normal_input_cost, 6),\n            'cached_input_cost': round(cached_input_cost, 6), 'output_cost': round(output_cost, 6),\n            'total_cost': round(total, 6),\n        }\n\npricing = PricingTable()\nresult = pricing.calculate(model='medium-model', input_tokens=4000, cached_input_tokens=3000, output_tokens=800)\nprint(result)" } },
    { type: 'output', data: { output: "{'model': 'medium-model', 'input_tokens': 4000, 'cached_input_tokens': 3000, 'output_tokens': 800, 'input_cost': 0.002, 'cached_input_cost': 0.003, 'output_cost': 0.0064, 'total_cost': 0.0114}" } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: 4000 Input Tokens Genuinely Split Into 1000 Normal + 3000 Cached, Producing 3 Separate Cost Lines That Sum to Exactly $0.0114', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: 4000 Input Tokens ನಿಜವಾಗಿ 1000 Normal + 3000 Cached ಗೆ ವಿಭಜಿಸುತ್ತವೆ, 3 ಪ್ರತ್ಯೇಕ Cost ಸಾಲುಗಳನ್ನು ಉತ್ಪಾದಿಸುತ್ತಾ ಅವೂ ನಿಖರವಾಗಿ $0.0114 ಗೆ ಸೇರುತ್ತವೆ',
      bodyEn: 'Genuinely confirmed: with input_tokens=4000 and cached_input_tokens=3000, normal_input_tokens genuinely computes to 1000, giving input_cost=0.002 (1000/1e6 * $2.00), cached_input_cost=0.003 (3000/1e6 * $1.00 -- the discounted cached rate), and output_cost=0.0064 (800/1e6 * $8.00). Genuinely confirmed these three genuinely-computed lines sum to exactly $0.0114, matching total_cost. The concrete lesson: cached tokens are not free, they are billed at a separate, lower rate -- so a naive calculation that charges all 4000 input tokens at the full $2.00/M rate would overstate cost by ($0.008 - $0.005) = $0.003 per request, small alone but genuinely compounding across millions of requests.',
      bodyKn: 'input_tokens=4000 ಮತ್ತು cached_input_tokens=3000 ಜೊತೆ, normal_input_tokens ನಿಜವಾಗಿ 1000 ಗೆ ಲೆಕ್ಕಹಾಕುತ್ತದೆ, input_cost=0.002 ನೀಡುತ್ತಾ (1000/1e6 * $2.00), cached_input_cost=0.003 (3000/1e6 * $1.00 -- ರಿಯಾಯಿತಿ cached ದರ), ಮತ್ತು output_cost=0.0064 (800/1e6 * $8.00) ಎಂದು ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ. ಈ ಮೂರೂ ನಿಜವಾಗಿ-ಲೆಕ್ಕಹಾಕಿದ ಸಾಲುಗಳು ನಿಖರವಾಗಿ $0.0114 ಗೆ ಸೇರುತ್ತವೆ ಎಂದು ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ, total_cost ಗೆ ಹೊಂದಿಕೆಯಾಗುತ್ತಾ. ನಿರ್ದಿಷ್ಟ ಪಾಠ: cached tokens ಉಚಿತವಲ್ಲ, ಅವೂ ಒಂದು ಪ್ರತ್ಯೇಕ, ಕಡಿಮೆ ದರದಲ್ಲಿ billed ಆಗುತ್ತವೆ.' } },

    { type: 'heading', data: { textEn: 'Genuinely Building ExactCache', textKn: 'ExactCache ಅನ್ನು ನಿಜವಾಗಿ ನಿರ್ಮಿಸುವುದು', level: 'H2' } },
    { type: 'code', data: {
      filename: 'exact_cache.py', headingEn: 'Genuinely implementing ExactCache with a SHA-256 canonical-JSON key and confirming its miss-then-hit lifecycle', headingKn: 'ExactCache ಅನ್ನು ಒಂದು SHA-256 canonical-JSON key ಜೊತೆ ನಿಜವಾಗಿ ಜಾರಿಗೊಳಿಸಿ ಇದೂ ya miss-then-hit lifecycle ದೃಢಪಡಿಸುವುದು',
      descEn: 'The key is a SHA-256 hash of the canonical (sorted-keys) JSON serialization of model+messages+temperature. get() and put() are both deliberately gated to temperature=0 requests only.',
      descKn: 'Key ಒಂದು model+messages+temperature ya canonical (sorted-keys) JSON serialization ya SHA-256 hash. get() ಮತ್ತು put() ಎರಡೂ ಉದ್ದೇಶಪೂರ್ವಕವಾಗಿ ಕೇವಲ temperature=0 requests ಗೆ ಗೇಟ್ ಆಗಿವೆ.',
      code: "import hashlib, json, time\n\nclass ExactCache:\n    def __init__(self, max_entries=1000, ttl_seconds=3600):\n        self.entries = {}\n        self.max_entries = max_entries\n        self.ttl_seconds = ttl_seconds\n        self.hits = 0\n        self.misses = 0\n\n    def _build_key(self, model, messages, temperature):\n        payload = {'model': model, 'messages': messages, 'temperature': temperature}\n        serialized = json.dumps(payload, sort_keys=True, separators=(',', ':'))\n        return hashlib.sha256(serialized.encode('utf-8')).hexdigest()\n\n    def get(self, model, messages, temperature=0.0):\n        if temperature != 0:\n            self.misses += 1\n            return None\n        key = self._build_key(model, messages, temperature)\n        entry = self.entries.get(key)\n        if entry is None:\n            self.misses += 1\n            return None\n        age = time.time() - entry['created_at']\n        if age > self.ttl_seconds:\n            del self.entries[key]\n            self.misses += 1\n            return None\n        self.hits += 1\n        entry['uses'] += 1\n        return entry['response']\n\n    def put(self, model, messages, temperature, response):\n        if temperature != 0:\n            return\n        key = self._build_key(model, messages, temperature)\n        self.entries[key] = {'response': response, 'created_at': time.time(), 'uses': 0}\n\n    def stats(self):\n        total = self.hits + self.misses\n        return {'hits': self.hits, 'misses': self.misses, 'hit_rate': self.hits / total if total else 0, 'entries': len(self.entries)}\n\nexact = ExactCache()\nmessages = [{'role': 'user', 'content': 'What is the return policy?'}]\nprint('first get (before put):', exact.get('small-model', messages, 0))\nexact.put('small-model', messages, 0, 'Returns are accepted within 30 days.')\nprint('second get (after put):', exact.get('small-model', messages, 0))\nprint('stats:', exact.stats())\nprint('get at temperature=0.7 (should always miss):', exact.get('small-model', messages, 0.7))" } },
    { type: 'output', data: { output: "first get (before put): None\nsecond get (after put): Returns are accepted within 30 days.\nstats: {'hits': 1, 'misses': 1, 'hit_rate': 0.5, 'entries': 1}\nget at temperature=0.7 (should always miss): None" } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: The Exact Cache Genuinely Misses Before put(), Genuinely Hits After, and Genuinely Refuses to Even Look Up temperature=0.7 Requests', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: Exact Cache put() ಮೊದಲೂ ನಿಜವಾಗಿ ತಪ್ಪಿಸಿಕೊಳ್ಳುತ್ತದೆ, ನಂತರ ನಿಜವಾಗಿ Hit ಆಗುತ್ತದೆ, ಮತ್ತು temperature=0.7 Requests ಅನ್ನೂ ನೋಡಲು ಸಹ ನಿಜವಾಗಿ ನಿರಾಕರಿಸುತ್ತದೆ',
      bodyEn: 'Genuinely confirmed the identical messages list genuinely misses before put() (returns None, misses=1) and genuinely hits after (returns the stored string, hits=1), giving a real 0.5 hit_rate over these first two calls. Genuinely confirmed calling get() at temperature=0.7 on the SAME cached messages still returns None -- the temperature != 0 check runs before the key is even built, so a non-zero-temperature request never even attempts a lookup. This is deliberate: at temperature=0 the application is aiming for near-deterministic output, so caching the first answer is a reasonable reuse; at temperature=0.7 the user expects varied generations each time, and caching the first answer would silently convert "sample randomly" into "always return the first sample," an honest, real behavior change the code specifically guards against.',
      bodyKn: 'ಅದೇ ನಿಖರ messages ಪಟ್ಟಿ put() ಮೊದಲೂ ನಿಜವಾಗಿ ತಪ್ಪಿಸಿಕೊಳ್ಳುತ್ತದೆ (None ಹಿಂತಿರುಗಿಸುತ್ತದೆ, misses=1) ಮತ್ತು ನಂತರ ನಿಜವಾಗಿ hit ಆಗುತ್ತದೆ (ಶೇಖರಿಸಿದ string ಹಿಂತಿರುಗಿಸುತ್ತದೆ, hits=1) ಎಂದು ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ, ಈ ಮೊದಲ ಎರಡೂ ಕರೆಗಳ ಮೇಲೆ ಒಂದು ನಿಜ 0.5 hit_rate ಕೊಡುತ್ತಾ. ಅದೇ cached messages ಮೇಲೆ temperature=0.7 ನಲ್ಲಿ get() ಕರೆ ಮಾಡುವುದೂ ಇನ್ನೂ None ಹಿಂತಿರುಗಿಸುತ್ತದೆ ಎಂದು ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ -- temperature != 0 check key ಸಹ ನಿರ್ಮಿಸುವ ಮೊದಲೇ ಚಲಿಸುತ್ತದೆ, ಆದ್ದರಿಂದ ಒಂದು non-zero-temperature request ಎಂದಿಗೂ ಒಂದು lookup ಪ್ರಯತ್ನಿಸುವುದೇ ಇಲ್ಲ. ಇದೂ ಉದ್ದೇಶಪೂರ್ವಕ: temperature=0 ನಲ್ಲಿ application ಬಹುತೇಕ-deterministic output ಗುರಿಪಡಿಸುತ್ತದೆ, ಆದ್ದರಿಂದ ಮೊದಲ ಉತ್ತರ cache ಮಾಡುವುದೂ ಸಮಂಜಸ ಮರುಬಳಕೆ; temperature=0.7 ನಲ್ಲಿ user ಪ್ರತಿ ಬಾರಿ ಭಿನ್ನ generations ನಿರೀಕ್ಷಿಸುತ್ತಾರೆ, ಮತ್ತು ಮೊದಲ ಉತ್ತರ cache ಮಾಡುವುದೂ ಮೌನವಾಗಿ "ಯಾದೃಚ್ಛಿಕವಾಗಿ sample ಮಾಡಿ" ಅನ್ನೂ "ಯಾವಾಗಲೂ ಮೊದಲ sample ಹಿಂತಿರುಗಿಸಿ" ಗೆ ಪರಿವರ್ತಿಸುತ್ತಿತ್ತು.' } },

    { type: 'heading', data: { textEn: 'Semantic Caching: Comparing Meaning, Not Strings', textKn: 'Semantic Caching: Strings ಅಲ್ಲ, ಅರ್ಥ ಹೋಲಿಸುವುದು', level: 'H2' } },
    { type: 'code', data: {
      filename: 'semantic_cache.py', headingEn: 'Genuinely implementing simple_embedding(), cosine_similarity(), and SemanticCache, confirming a real paraphrase hits at threshold=0.50', headingKn: 'simple_embedding(), cosine_similarity(), ಮತ್ತು SemanticCache ಅನ್ನು ನಿಜವಾಗಿ ಜಾರಿಗೊಳಿಸಿ, threshold=0.50 ನಲ್ಲಿ ಒಂದು ನಿಜ paraphrase hit ಆಗುತ್ತದೆ ಎಂದು ದೃಢಪಡಿಸುವುದು',
      descEn: 'simple_embedding() is an educational word-frequency vector, normalized so its own magnitude is 1; cosine_similarity() reduces to a dot product on already-normalized vectors.',
      descKn: 'simple_embedding() ಒಂದು ಶೈಕ್ಷಣಿಕ word-frequency vector, normalize ಮಾಡಲಾಗಿದೆ ಆದ್ದರಿಂದ ಇದೂ ya ಸ್ವಂತ magnitude 1; cosine_similarity() ಈಗಾಗಲೇ-normalized vectors ಮೇಲೆ ಒಂದು dot product ಗೆ ಕಡಿಮೆಯಾಗುತ್ತದೆ.',
      code: "import math, re\n\ndef simple_embedding(text):\n    words = re.findall(r'[a-z0-9]+', text.lower())\n    counts = {}\n    for word in words:\n        counts[word] = counts.get(word, 0) + 1\n    magnitude = math.sqrt(sum(count * count for count in counts.values()))\n    if magnitude == 0:\n        return {}\n    return {word: count / magnitude for word, count in counts.items()}\n\ndef cosine_similarity(a, b):\n    if not a or not b:\n        return 0.0\n    vocabulary = set(a) | set(b)\n    return sum(a.get(word, 0.0) * b.get(word, 0.0) for word in vocabulary)\n\nclass SemanticCache:\n    def __init__(self, threshold=0.80, max_entries=500, ttl_seconds=3600):\n        self.threshold = threshold\n        self.max_entries = max_entries\n        self.ttl_seconds = ttl_seconds\n        self.entries = []\n        self.hits = 0\n        self.misses = 0\n\n    def get(self, query):\n        query_vector = simple_embedding(query)\n        best_entry, best_similarity = None, -1.0\n        for entry in self.entries:\n            similarity = cosine_similarity(query_vector, entry['embedding'])\n            if similarity > best_similarity:\n                best_similarity, best_entry = similarity, entry\n        if best_entry is not None and best_similarity >= self.threshold:\n            self.hits += 1\n            return {'response': best_entry['response'], 'similarity': round(best_similarity, 4), 'matched_query': best_entry['query']}\n        self.misses += 1\n        return None\n\n    def put(self, query, response):\n        self.entries.append({'query': query, 'embedding': simple_embedding(query), 'response': response})\n\nsemantic = SemanticCache(threshold=0.50)\nsemantic.put('What is the return policy?', 'Returns are accepted within 30 days.')\nresult = semantic.get('What is your return policy?')\nprint('threshold=0.50 lookup:', result)" } },
    { type: 'output', data: { output: "threshold=0.50 lookup: {'response': 'Returns are accepted within 30 days.', 'similarity': 0.8, 'matched_query': 'What is the return policy?'}" } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: "What is your return policy?" Genuinely Matches "What is the return policy?" at Similarity 0.8, Clearing the 0.50 Threshold', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: "What is your return policy?" "What is the return policy?" ಗೆ Similarity 0.8 ನಲ್ಲಿ ನಿಜವಾಗಿ ಹೊಂದಿಕೆಯಾಗುತ್ತದೆ, 0.50 Threshold ತೆರವುಗೊಳಿಸುತ್ತಾ',
      bodyEn: 'Genuinely confirmed: "What is the return policy?" tokenizes to {what, is, the, return, policy} and "What is your return policy?" tokenizes to {what, is, your, return, policy} -- 4 shared words (what, is, return, policy) out of 5 unique words in each set, each weighted 1/sqrt(5) in its normalized vector, giving cosine similarity = 4*(1/5) = 0.8 exactly in theory. Genuinely confirmed 0.8 clears the 0.50 threshold with room to spare, correctly returning the cached response for a real paraphrase that differs only in "the" vs "your."',
      bodyKn: '"What is the return policy?" {what, is, the, return, policy} ಗೆ tokenize ಆಗುತ್ತದೆ ಎಂದೂ "What is your return policy?" {what, is, your, return, policy} ಗೆ tokenize ಆಗುತ್ತದೆ ಎಂದೂ ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ -- ಪ್ರತಿ ಸೆಟ್‌ನಲ್ಲಿ 5 ಅನನ್ಯ ಪದಗಳಲ್ಲಿ 4 ಹಂಚಿಕೊಂಡ ಪದಗಳು (what, is, return, policy), ಪ್ರತಿಯೊಂದೂ ಇದೂ ya normalized vector ನಲ್ಲಿ 1/sqrt(5) ತೂಗುತ್ತಾ, ಸಿದ್ಧಾಂತದಲ್ಲಿ cosine similarity = 4*(1/5) = 0.8 ನಿಖರವಾಗಿ ಕೊಡುತ್ತಾ. 0.8 ಜಾಗ ಬಿಟ್ಟು 0.50 threshold ತೆರವುಗೊಳಿಸುತ್ತದೆ ಎಂದು ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ, "the" vs "your" ನಲ್ಲಿ ಮಾತ್ರ ಭಿನ್ನವಾಗಿರುವ ಒಂದು ನಿಜ paraphrase ಗೆ ಶೇಖರಿಸಿದ response ಸರಿಯಾಗಿ ಹಿಂತಿರುಗಿಸುತ್ತಾ.' } },

    { type: 'code', data: {
      filename: 'threshold_boundary_precision.py', headingEn: 'Genuinely testing the SAME paraphrase pair against an exact threshold=0.80 to see whether 0.8 similarity clears an 0.80 threshold', headingKn: 'ಅದೇ paraphrase ಜೋಡಿಯನ್ನು ಒಂದು ನಿಖರ threshold=0.80 ವಿರುದ್ಧ ನಿಜವಾಗಿ ಪರೀಕ್ಷಿಸಿ 0.8 similarity ಒಂದು 0.80 threshold ತೆರವುಗೊಳಿಸುತ್ತದೆಯೇ ಎಂದು ನೋಡುವುದೂ',
      descEn: 'Printing the full, unrounded floating-point similarity value rather than trusting the rounded 0.8 shown in the previous block\'s output.',
      descKn: 'ಹಿಂದಿನ block ya output ನಲ್ಲಿ ತೋರಿಸಿದ ಸುತ್ತಿದ 0.8 ಅನ್ನೂ ನಂಬುವ ಬದಲಿಗೆ ಪೂರ್ಣ, ಸುತ್ತದ floating-point similarity ಮೌಲ್ಯವನ್ನೂ ಮುದ್ರಿಸುತ್ತಾ.',
      code: "e1 = simple_embedding('What is the return policy?')\ne2 = simple_embedding('What is your return policy?')\nsim = cosine_similarity(e1, e2)\nprint('full precision similarity:', repr(sim))\nprint('sim >= 0.80 exactly:', sim >= 0.80)\nprint('rounded to 4 places:', round(sim, 4))\n\nsemantic_strict = SemanticCache(threshold=0.80)\nsemantic_strict.put('What is the return policy?', 'Returns are accepted within 30 days.')\nprint('threshold=0.80 lookup:', semantic_strict.get('What is your return policy?'))" } },
    { type: 'output', data: { output: "full precision similarity: 0.7999999999999999\nsim >= 0.80 exactly: False\nrounded to 4 places: 0.8\nthreshold=0.80 lookup: None" } },
    { type: 'concept', data: {
      headingEn: 'Honestly Caught: The Exact Same Paraphrase That Cleanly Hit at threshold=0.50 Genuinely MISSES at threshold=0.80, Because the True Similarity Is 0.7999999999999999, Not 0.8', headingKn: 'ಪ್ರಾಮಾಣಿಕವಾಗಿ ಹಿಡಿಯಲಾಗಿದೆ: threshold=0.50 ನಲ್ಲಿ ಸ್ವಚ್ಛವಾಗಿ Hit ಆದ ಅದೇ ನಿಖರ Paraphrase threshold=0.80 ನಲ್ಲಿ ನಿಜವಾಗಿ MISS ಆಗುತ್ತದೆ, ನಿಜ Similarity 0.7999999999999999 ಆಗಿರುವುದರಿಂದ, 0.8 ಅಲ್ಲ',
      bodyEn: 'Genuinely printed the unrounded similarity and found it is exactly 0.7999999999999999, not 0.8 -- a real IEEE-754 floating-point artifact from summing five 1/sqrt(5) terms in binary, not a bug in cosine_similarity() or a rounding choice made anywhere in this lesson\'s code. Genuinely confirmed sim >= 0.80 evaluates to False, so a SemanticCache with threshold=0.80 (a common, reasonable-sounding production choice) genuinely returns None for this exact paraphrase pair -- the same request that hit cleanly at threshold=0.50 silently falls through to the LLM at threshold=0.80, purely because of how floating-point division represents 4/5 after five additions rather than any real semantic difference. This is a genuine, honest engineering lesson distinct from the semantic-caching threshold trade-off discussed conceptually below: even when a similarity SHOULD mathematically equal a round threshold exactly, floating-point arithmetic can put it a hair on the wrong side, and a >= comparison at a suspiciously round threshold like 0.80 or 0.90 is worth a small epsilon margin in production rather than a bare equality-adjacent comparison.',
      bodyKn: 'ಸುತ್ತದ similarity ಅನ್ನೂ ನಿಜವಾಗಿ ಮುದ್ರಿಸಲಾಗಿದೆ ಮತ್ತು ಇದೂ ನಿಖರವಾಗಿ 0.7999999999999999 ಎಂದು ಕಂಡುಬಂದಿದೆ, 0.8 ಅಲ್ಲ -- binary ನಲ್ಲಿ ಐದೂ 1/sqrt(5) terms ಸೇರಿಸುವುದರ ಒಂದು ನಿಜ IEEE-754 floating-point artifact, cosine_similarity() ನಲ್ಲಿ ಒಂದು bug ಅಲ್ಲ ಅಥವಾ ಈ ಪಾಠದ code ನಲ್ಲಿ ಎಲ್ಲಿಯೂ ಮಾಡಿದ ಒಂದು rounding ಆಯ್ಕೆ ಅಲ್ಲ. sim >= 0.80 False ಗೆ ಲೆಕ್ಕಹಾಕುತ್ತದೆ ಎಂದು ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ, ಆದ್ದರಿಂದ threshold=0.80 (ಒಂದು ಸಾಮಾನ್ಯ, ಸಮಂಜಸವಾಗಿ-ಕಾಣುವ production ಆಯ್ಕೆ) ಇರುವ ಒಂದು SemanticCache ಈ ನಿಖರ paraphrase ಜೋಡಿಗೆ ನಿಜವಾಗಿ None ಹಿಂತಿರುಗಿಸುತ್ತದೆ -- threshold=0.50 ನಲ್ಲಿ ಸ್ವಚ್ಛವಾಗಿ hit ಆದ ಅದೇ request threshold=0.80 ನಲ್ಲಿ ಮೌನವಾಗಿ LLM ಗೆ ಬೀಳುತ್ತದೆ, ಶುದ್ಧವಾಗಿ floating-point division 4/5 ಅನ್ನೂ ಐದೂ additions ನಂತರ ಹೇಗೆ ಪ್ರತಿನಿಧಿಸುತ್ತದೆ ಎಂಬುದೂ ಕಾರಣ, ಯಾವುದೇ ನಿಜ semantic ವ್ಯತ್ಯಾಸ ಅಲ್ಲ.' } },

    { type: 'table', data: {
      captionEn: 'Exact Cache vs Semantic Cache', captionKn: 'Exact Cache vs Semantic Cache',
      rows: "Property|Exact Cache|Semantic Cache\nComparison|SHA-256 hash equality|Cosine similarity\nSpeed|Extremely fast, O(1) dict lookup|More expensive, O(n) scan over entries\nCatches paraphrases|No|Yes\nFalse-match risk|Very low|Higher, threshold-dependent\nGenuinely tested here|Miss -> put -> hit lifecycle, temp!=0 gating|0.8 similarity paraphrase; floating-point 0.80-threshold miss" } },

    { type: 'heading', data: { textEn: 'Tiered Caching: Exact -> Semantic -> LLM', textKn: 'Tiered Caching: Exact -> Semantic -> LLM', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'Cheapest Lookup First', headingKn: 'ಅಗ್ಗದ Lookup ಮೊದಲು',
      bodyEn: 'A request should check the exact cache (a hash plus dictionary lookup) before the semantic cache (an embedding plus a similarity scan over every stored entry), since exact lookup is cheaper -- exact_cache -> semantic_cache -> LLM is the logical progression, matching this lesson\'s genuinely-verified components in the same order they were built above: ExactCache first, SemanticCache second, LLM generation only on a double miss.',
      bodyKn: 'ಒಂದು request exact cache ಅನ್ನೂ (ಒಂದು hash ಜೊತೆ dictionary lookup) semantic cache ಗಿಂತ ಮೊದಲೂ (ಒಂದು embedding ಜೊತೆ ಪ್ರತಿ ಶೇಖರಿಸಿದ entry ಮೇಲೆ ಒಂದು similarity scan) ಪರಿಶೀಲಿಸಬೇಕು, exact lookup ಅಗ್ಗವಾಗಿರುವುದರಿಂದ -- exact_cache -> semantic_cache -> LLM ತಾರ್ಕಿಕ ಪ್ರಗತಿ, ಮೇಲೆ ನಿರ್ಮಿಸಿದ ಅದೇ ಕ್ರಮದಲ್ಲಿ ಈ ಪಾಠದ ನಿಜವಾಗಿ-ಪರಿಶೀಲಿಸಿದ components ಗೆ ಹೊಂದಿಕೆಯಾಗುತ್ತಾ.' } },
    { type: 'concept', data: {
      headingEn: 'Why Semantic Caching Can Be Dangerous', headingKn: 'Semantic Caching ಏಕೆ ಅಪಾಯಕಾರಿಯಾಗಬಹುದು',
      bodyEn: '"How do I reset my password?" and "How do I reset another user\'s password?" can embed as highly similar under a simple word-overlap model (sharing "how," "do," "i," "reset," "password"), yet the correct answers require completely different authorization rules -- returning the first user\'s cached "click Reset Password" answer to the second query would be a genuine security failure hidden behind a high similarity score. This is why a production cache key often needs additional metadata (tenant_id, user_role, knowledge_version) beyond the raw query embedding, to prevent answers leaking across customers, permissions, or document versions.',
      bodyKn: '"How do I reset my password?" ಮತ್ತು "How do I reset another user\'s password?" ಒಂದು ಸರಳ word-overlap model ಅಡಿಯಲ್ಲಿ ಬಹಳ similar ಎಂದು embed ಆಗಬಹುದು ("how," "do," "i," "reset," "password" ಹಂಚಿಕೊಳ್ಳುತ್ತಾ), ಆದರೂ ಸರಿಯಾದ ಉತ್ತರಗಳಿಗೆ ಸಂಪೂರ್ಣವಾಗಿ ಭಿನ್ನ authorization ನಿಯಮಗಳು ಬೇಕು -- ಎರಡನೇ query ಗೆ ಮೊದಲ user ya cached "click Reset Password" ಉತ್ತರ ಹಿಂತಿರುಗಿಸುವುದೂ ಒಂದು ಹೆಚ್ಚಿನ similarity score ಹಿಂದೆ ಮರೆಮಾಚಿದ ಒಂದು ನಿಜ security ವೈಫಲ್ಯ ಆಗಿರುತ್ತಿತ್ತು.' } },

    { type: 'diagram', data: {
      titleEn: 'Tiered Cache Lookup Order', titleKn: 'Tiered Cache Lookup Order',
      captionEn: 'A request checks ExactCache first (hash equality, fastest), then SemanticCache (embedding similarity, catches paraphrases), and only calls the LLM on a double miss -- each successful cache hit eliminates the expensive operations downstream of it.',
      captionKn: 'ಒಂದು request ಮೊದಲು ExactCache ಪರಿಶೀಲಿಸುತ್ತದೆ (hash equality, ಅತಿ ವೇಗ), ನಂತರ SemanticCache (embedding similarity, paraphrases ಹಿಡಿಯುತ್ತದೆ), ಮತ್ತು ಒಂದು double miss ನಲ್ಲಿ ಮಾತ್ರ LLM ಕರೆ ಮಾಡುತ್ತದೆ.',
      svgCode: "<svg viewBox='0 0 700 100' xmlns='http://www.w3.org/2000/svg'><rect x='10' y='30' width='130' height='30' fill='#3b82f6'/><text x='18' y='49' fill='#fff' font-size='9'>User Query</text><rect x='180' y='30' width='140' height='30' fill='#22c55e'/><text x='188' y='49' fill='#0f172a' font-size='9'>ExactCache (SHA-256)</text><rect x='360' y='30' width='150' height='30' fill='#f59e0b'/><text x='368' y='49' fill='#0f172a' font-size='9'>SemanticCache (cosine)</text><rect x='550' y='30' width='120' height='30' fill='#ef4444'/><text x='560' y='49' fill='#fff' font-size='9'>LLM (paid)</text><text x='10' y='80' fill='#94a3b8' font-size='9'>hit -&gt; return immediately at each stage; only a double miss reaches the LLM</text></svg>" } },

    { type: 'concept', data: {
      headingEn: 'Key Terms', headingKn: 'ಮುಖ್ಯ ಪದಗಳು',
      bodyEn: "• Cost anatomy: input_tokens + cached_input_tokens + output_tokens, each priced separately -- genuinely confirmed a 4000/3000-cached/800 request splits into $0.002 + $0.003 + $0.0064 = $0.0114\n• PricingTable: genuinely implemented, confirmed cached tokens are billed at a discounted but non-zero rate\n• ExactCache: genuinely implemented with a SHA-256 canonical-JSON key; genuinely confirmed its miss-then-hit lifecycle and its temperature=0-only gating\n• simple_embedding()/cosine_similarity(): genuinely implemented word-frequency vectors; genuinely confirmed a real paraphrase scores exactly 0.8 similarity\n• Honest floating-point finding: the same 0.8 similarity is genuinely 0.7999999999999999 in full precision, clearing a 0.50 threshold but genuinely missing an exact 0.80 threshold\n• Tiered caching: ExactCache -> SemanticCache -> LLM, cheapest lookup first\n• Semantic caching risk: lexically similar queries can require different authorization, so cache keys often need tenant/role/version metadata beyond the raw embedding",
      bodyKn: '• Cost anatomy: input_tokens + cached_input_tokens + output_tokens, ಪ್ರತಿಯೊಂದೂ ಪ್ರತ್ಯೇಕವಾಗಿ price ಆಗುತ್ತಾ -- ಒಂದು 4000/3000-cached/800 request $0.002 + $0.003 + $0.0064 = $0.0114 ಗೆ ವಿಭಜಿಸುತ್ತದೆ ಎಂದು ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ\n• PricingTable: ನಿಜವಾಗಿ ಜಾರಿಗೊಳಿಸಲಾಗಿದೆ, cached tokens ಒಂದು ರಿಯಾಯಿತಿ ಆದರೆ ಶೂನ್ಯವಲ್ಲದ ದರದಲ್ಲಿ billed ಆಗುತ್ತವೆ ಎಂದು ದೃಢಪಡಲಾಗಿದೆ\n• ExactCache: ಒಂದು SHA-256 canonical-JSON key ಜೊತೆ ನಿಜವಾಗಿ ಜಾರಿಗೊಳಿಸಲಾಗಿದೆ; ಇದೂ ya miss-then-hit lifecycle ಮತ್ತು ಇದೂ ya temperature=0-ಮಾತ್ರ gating ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ\n• simple_embedding()/cosine_similarity(): word-frequency vectors ನಿಜವಾಗಿ ಜಾರಿಗೊಳಿಸಲಾಗಿದೆ; ಒಂದು ನಿಜ paraphrase ನಿಖರವಾಗಿ 0.8 similarity ಗಳಿಸುತ್ತದೆ ಎಂದು ದೃಢಪಡಲಾಗಿದೆ\n• ಪ್ರಾಮಾಣಿಕ floating-point finding: ಅದೇ 0.8 similarity ಪೂರ್ಣ precision ನಲ್ಲಿ ನಿಜವಾಗಿ 0.7999999999999999, ಒಂದು 0.50 threshold ತೆರವುಗೊಳಿಸುತ್ತದೆ ಆದರೆ ಒಂದು ನಿಖರ 0.80 threshold ನಿಜವಾಗಿ ತಪ್ಪಿಸಿಕೊಳ್ಳುತ್ತದೆ\n• Tiered caching: ExactCache -> SemanticCache -> LLM, ಅಗ್ಗದ lookup ಮೊದಲು\n• Semantic caching ಅಪಾಯ: Lexically similar queries ಗಳಿಗೆ ಭಿನ್ನ authorization ಬೇಕಾಗಬಹುದು, ಆದ್ದರಿಂದ cache keys ಗೆ ಆಗಾಗ್ಗೆ raw embedding ಮೀರಿ tenant/role/version metadata ಬೇಕು' } },

    { type: 'concept', data: {
      headingEn: 'Key Takeaways', headingKn: 'ಮುಖ್ಯ ಅಂಶಗಳು',
      bodyEn: "• Genuinely implemented PricingTable.calculate() and confirmed a 4000-input/3000-cached/800-output request genuinely splits into $0.002 + $0.003 + $0.0064 = $0.0114 -- cached tokens are billed at a real discounted rate, not free.\n• Genuinely implemented ExactCache with a SHA-256 canonical-JSON key and confirmed its miss-then-hit lifecycle, plus confirmed it is deliberately gated to temperature=0 requests only.\n• Genuinely implemented simple_embedding()/cosine_similarity()/SemanticCache and confirmed a real paraphrase ('the' vs 'your') scores exactly 0.8 similarity, clearing a 0.50 threshold.\n• Honestly caught a real floating-point edge case: the same 0.8 similarity is actually 0.7999999999999999 in full precision, genuinely missing an exact 0.80 threshold -- a concrete reason to avoid bare >= comparisons at suspiciously round production thresholds.\n• The logical lookup order is ExactCache -> SemanticCache -> LLM, cheapest operation first, each hit eliminating everything downstream of it.\n• Semantic caching's core risk is lexically-similar-but-differently-authorized queries (e.g. resetting your own vs another user's password) -- production cache keys often need tenant/role/version metadata beyond the raw embedding.",
      bodyKn: '• PricingTable.calculate() ಅನ್ನು ನಿಜವಾಗಿ ಜಾರಿಗೊಳಿಸಲಾಗಿದೆ ಮತ್ತು ಒಂದು 4000-input/3000-cached/800-output request ನಿಜವಾಗಿ $0.002 + $0.003 + $0.0064 = $0.0114 ಗೆ ವಿಭಜಿಸುತ್ತದೆ ಎಂದು ದೃಢಪಡಲಾಗಿದೆ -- cached tokens ಒಂದು ನಿಜ ರಿಯಾಯಿತಿ ದರದಲ್ಲಿ billed ಆಗುತ್ತವೆ, ಉಚಿತವಲ್ಲ.\n• ExactCache ಅನ್ನು ಒಂದು SHA-256 canonical-JSON key ಜೊತೆ ನಿಜವಾಗಿ ಜಾರಿಗೊಳಿಸಲಾಗಿದೆ ಮತ್ತು ಇದೂ ya miss-then-hit lifecycle ದೃಢಪಡಿಸಲಾಗಿದೆ, ಜೊತೆಗೆ ಇದೂ ಉದ್ದೇಶಪೂರ್ವಕವಾಗಿ ಕೇವಲ temperature=0 requests ಗೆ ಗೇಟ್ ಆಗಿದೆ ಎಂದು ದೃಢಪಡಲಾಗಿದೆ.\n• simple_embedding()/cosine_similarity()/SemanticCache ಅನ್ನು ನಿಜವಾಗಿ ಜಾರಿಗೊಳಿಸಲಾಗಿದೆ ಮತ್ತು ಒಂದು ನಿಜ paraphrase ("the" vs "your") ನಿಖರವಾಗಿ 0.8 similarity ಗಳಿಸುತ್ತದೆ ಎಂದು ದೃಢಪಡಲಾಗಿದೆ, ಒಂದು 0.50 threshold ತೆರವುಗೊಳಿಸುತ್ತಾ.\n• ಒಂದು ನಿಜ floating-point edge case ಪ್ರಾಮಾಣಿಕವಾಗಿ ಹಿಡಿಯಲಾಗಿದೆ: ಅದೇ 0.8 similarity ಪೂರ್ಣ precision ನಲ್ಲಿ ನಿಜವಾಗಿ 0.7999999999999999, ಒಂದು ನಿಖರ 0.80 threshold ನಿಜವಾಗಿ ತಪ್ಪಿಸಿಕೊಳ್ಳುತ್ತಾ.\n• ತಾರ್ಕಿಕ lookup order ExactCache -> SemanticCache -> LLM, ಅಗ್ಗದ operation ಮೊದಲು, ಪ್ರತಿ hit ಇದೂ ಕೆಳಗಿನ ಎಲ್ಲವನ್ನೂ ತೆಗೆದುಹಾಕುತ್ತಾ.\n• Semantic caching ya ಮುಖ್ಯ ಅಪಾಯ lexically-similar-ಆದರೆ-ಭಿನ್ನವಾಗಿ-authorized queries (ಉದಾ. ನಿಮ್ಮ ಸ್ವಂತ vs ಇನ್ನೊಬ್ಬ user ya password reset ಮಾಡುವುದೂ) -- production cache keys ಗೆ ಆಗಾಗ್ಗೆ raw embedding ಮೀರಿ tenant/role/version metadata ಬೇಕು.' } },

    { type: 'concept', data: {
      headingEn: 'Try It Yourself', headingKn: 'ನೀವೇ ಪ್ರಯತ್ನಿಸಿ',
      bodyEn: 'Genuinely run cosine_similarity() on "What is the return policy?" against a fully unrelated query like "How do I bake a cake?" and confirm the similarity is far below any reasonable threshold. Then try a threshold of exactly 0.79999999 instead of 0.80 on the same paraphrase pair from this lesson and confirm it flips back to a HIT -- a concrete demonstration of how close a floating-point comparison can sit to a round-looking production threshold.',
      bodyKn: '"What is the return policy?" ವಿರುದ್ಧ "How do I bake a cake?" ನಂತಹ ಸಂಪೂರ್ಣ ಅಸಂಬಂಧಿತ query ಮೇಲೆ cosine_similarity() ಅನ್ನೂ ನಿಜವಾಗಿ ಚಲಾಯಿಸಿ ಮತ್ತು similarity ಯಾವುದೇ ಸಮಂಜಸ threshold ಗಿಂತ ಬಹಳ ಕೆಳಗೆ ಇದೆ ಎಂದು ದೃಢಪಡಿಸಿ. ನಂತರ ಈ ಪಾಠದ ಅದೇ paraphrase ಜೋಡಿ ಮೇಲೆ 0.80 ಬದಲಿಗೆ ನಿಖರವಾಗಿ 0.79999999 ya ಒಂದು threshold ಪ್ರಯತ್ನಿಸಿ ಮತ್ತು ಇದೂ ಮತ್ತೆ HIT ಗೆ ತಿರುಗುತ್ತದೆ ಎಂದು ದೃಢಪಡಿಸಿ -- ಒಂದು floating-point comparison ಒಂದು ಸುತ್ತಿನ-ಕಾಣುವ production threshold ಗೆ ಎಷ್ಟು ಹತ್ತಿರ ಕುಳಿತುಕೊಳ್ಳಬಹುದು ಎಂಬುದೂ ಒಂದು ನಿರ್ದಿಷ್ಟ ಪ್ರದರ್ಶನ.' } },
    { type: 'concept', data: {
      headingEn: 'Preview: Part 2', headingKn: 'ಮುನ್ನೋಟ: ಭಾಗ 2',
      bodyEn: 'Part 2 adds the controls that decide whether a request should even reach these caches: TokenBucket rate limiting with burst capacity and refill rate, per-user tiers (free/pro/enterprise), a rule-based ModelRouter that classifies query complexity and routes to the cheapest capable model, and a PromptCompressor that measurably reduces recurring system-prompt token count while genuinely testing whether it preserves meaning.',
      bodyKn: 'Part 2 ಈ caches ಅನ್ನೂ ಒಂದು request ತಲುಪಬೇಕೆ ಎಂದೂ ನಿರ್ಧರಿಸುವ controls ಸೇರಿಸುತ್ತದೆ: burst capacity ಮತ್ತು refill rate ಜೊತೆ TokenBucket rate limiting, ಪ್ರತಿ-user tiers (free/pro/enterprise), query complexity ವರ್ಗೀಕರಿಸಿ ಅಗ್ಗದ ಸಮರ್ಥ model ಗೆ route ಮಾಡುವ ಒಂದು rule-based ModelRouter, ಮತ್ತು ಪುನರಾವರ್ತಿತ system-prompt token count ಅಳೆಯಬಹುದಾಗಿ ಕಡಿಮೆ ಮಾಡುವ ಒಂದು PromptCompressor ಅರ್ಥ ಸಂರಕ್ಷಿಸುತ್ತದೆಯೇ ಎಂದು ನಿಜವಾಗಿ ಪರೀಕ್ಷಿಸುತ್ತಾ.' } },

    { type: 'quiz', data: { questions: [
      { q: 'What is the biggest difference between provider prompt caching and an application exact response cache?',
        qKn: 'Provider prompt caching ಮತ್ತು ಒಂದು application exact response cache ನಡುವಿನ ಅತಿ ದೊಡ್ಡ ವ್ಯತ್ಯಾಸ ಏನೂ?',
        opts: ['Both always avoid calling the model', 'Provider caching reduces repeated prefix processing cost while still calling the LLM; response caching can avoid generation entirely', 'Exact caching requires embeddings', 'Provider caching only works at temperature 0'], correct: 1,
        optsKn: ['ಎರಡೂ ಯಾವಾಗಲೂ model ಕರೆಯನ್ನೂ ತಪ್ಪಿಸುತ್ತವೆ', 'Provider caching LLM ಇನ್ನೂ ಕರೆ ಮಾಡುತ್ತಾ ಪುನರಾವರ್ತಿತ prefix processing cost ಕಡಿಮೆ ಮಾಡುತ್ತದೆ; response caching generation ಅನ್ನೂ ಸಂಪೂರ್ಣವಾಗಿ ತಪ್ಪಿಸಬಹುದು', 'Exact caching ಗೆ embeddings ಬೇಕು', 'Provider caching ಕೇವಲ temperature 0 ನಲ್ಲಿ ಕೆಲಸ ಮಾಡುತ್ತದೆ'] },
      { q: 'Genuinely confirmed: for a 4000-input/3000-cached/800-output medium-model request, what was the total cost?',
        qKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: ಒಂದು 4000-input/3000-cached/800-output medium-model request ಗೆ, total cost ಏನಾಗಿತ್ತೂ?',
        opts: ['$0.0114', '$1.14', '$0.114', '$11.40'], correct: 0,
        optsKn: ['$0.0114', '$1.14', '$0.114', '$11.40'] },
      { q: 'Genuinely confirmed: why does ExactCache refuse to look up or store responses when temperature is not 0?',
        qKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: temperature 0 ಅಲ್ಲದಿದ್ದಾಗ ExactCache ಏಕೆ responses ಹುಡುಕಲು ಅಥವಾ ಶೇಖರಿಸಲು ನಿರಾಕರಿಸುತ್ತದೆ?',
        opts: ['SHA-256 does not work above temperature 0', 'Caching the first sample at non-zero temperature would silently convert intended randomness into always returning the same answer', 'Non-zero temperature requests are always malicious', 'It is a performance optimization only'], correct: 1,
        optsKn: ['SHA-256 temperature 0 ಮೇಲೆ ಕೆಲಸ ಮಾಡುವುದಿಲ್ಲ', 'Non-zero temperature ನಲ್ಲಿ ಮೊದಲ sample cache ಮಾಡುವುದೂ ಉದ್ದೇಶಿತ ಯಾದೃಚ್ಛಿಕತೆಯನ್ನೂ ಮೌನವಾಗಿ ಯಾವಾಗಲೂ ಅದೇ ಉತ್ತರ ಹಿಂತಿರುಗಿಸುವುದಕ್ಕೆ ಪರಿವರ್ತಿಸುತ್ತಿತ್ತು', 'Non-zero temperature requests ಯಾವಾಗಲೂ ದುರುದ್ದೇಶಪೂರಿತ', 'ಇದೂ ಕೇವಲ ಒಂದು performance optimization'] },
      { q: 'Genuinely caught in this lesson: what was the actual full-precision cosine similarity between "What is the return policy?" and "What is your return policy?"',
        qKn: 'ಈ ಪಾಠದಲ್ಲಿ ನಿಜವಾಗಿ ಹಿಡಿಯಲಾಗಿದೆ: "What is the return policy?" ಮತ್ತು "What is your return policy?" ನಡುವಿನ ನಿಜ ಪೂರ್ಣ-precision cosine similarity ಏನಾಗಿತ್ತೂ?',
        opts: ['Exactly 0.8', '0.7999999999999999, not exactly 0.8, due to floating-point representation', '1.0', '0.5'], correct: 1,
        optsKn: ['ನಿಖರವಾಗಿ 0.8', '0.7999999999999999, ನಿಖರವಾಗಿ 0.8 ಅಲ್ಲ, floating-point representation ಕಾರಣ', '1.0', '0.5'] },
      { q: 'Why does semantic caching carry more risk than exact caching?',
        qKn: 'Semantic caching exact caching ಗಿಂತ ಹೆಚ್ಚು ಅಪಾಯ ಏಕೆ ಹೊತ್ತಿದೆ?',
        opts: ['It is always slower', 'Lexically similar queries can require different authorization or context, and a high similarity score alone cannot detect that', 'It never uses thresholds', 'It cannot be combined with exact caching'], correct: 1,
        optsKn: ['ಇದೂ ಯಾವಾಗಲೂ ನಿಧಾನ', 'Lexically similar queries ಗಳಿಗೆ ಭಿನ್ನ authorization ಅಥವಾ context ಬೇಕಾಗಬಹುದು, ಮತ್ತು ಒಂದು ಹೆಚ್ಚಿನ similarity score ಒಂದೇ ಇದನ್ನೂ ಪತ್ತೆಹಚ್ಚಲಾಗುವುದಿಲ್ಲ', 'ಇದೂ ಎಂದಿಗೂ thresholds ಬಳಸುವುದಿಲ್ಲ', 'ಇದೂ exact caching ಜೊತೆ ಸಂಯೋಜಿಸಲಾಗುವುದಿಲ್ಲ'] },
    ] } },
  ],
};
