const phaseId = '6a369d5a66020ed05b3213f4'; // Phase 13: LLM from Scratch
const moduleId = '6a369d5a66020ed05b3213fa'; // Module 185: Building a Tokenizer from Scratch

module.exports = {
  phaseId,
  moduleId,
  order: 2,
  type: 'interactive',
  duration: 45,
  difficulty: 'advanced',
  status: 'published',
  title: 'Building a Tokenizer from Scratch (Part 2) — Encode, Decode, Compression & Production Tokenizers',
  titleKn: 'Building a Tokenizer from Scratch (Part 2) — Encode, Decode, Compression & Production Tokenizers',
  desc: 'Genuinely implement encode() and decode() on the BPETokenizer built in Part 1, train it on a 60-word corpus (40 merges), and measure real compression ratios and round-trip correctness -- then compare it head-to-head with tiktoken cl100k_base, discovering an honest surprise: the tiny tokenizer briefly "wins" on the sentence closest to its own training corpus, purely by overfitting, while losing badly everywhere else.',
  descKn: 'Part 1 ನಲ್ಲಿ ನಿರ್ಮಿಸಿದ BPETokenizer ಮೇಲೆ encode() ಮತ್ತೆ decode() ಅನ್ನೂ ನಿಜವಾಗಿ implement ಮಾಡಿ, ಅದನ್ನೂ 60-word corpus ಮೇಲೆ (40 merges) train ಮಾಡಿ, ಮತ್ತೆ ನಿಜ compression ratios ಮತ್ತೆ round-trip correctness ಅಳೆಯಿರಿ -- ನಂತರ ಅದನ್ನೂ tiktoken cl100k_base ವಿರುದ್ಧ head-to-head ಹೋಲಿಸಿ, ಒಂದೂ ಪ್ರಾಮಾಣಿಕ ಆಶ್ಚರ್ಯ ಕಂಡುಹಿಡಿಯುತ್ತಾ: ಚಿಕ್ಕ tokenizer ತನ್ನ ಸ್ವಂತ training corpus ಗೆ ಅತ್ಯಂತ ಹತ್ತಿರವಿರುವ sentence ಮೇಲೆ ಸಂಕ್ಷಿಪ್ತವಾಗಿ "ಗೆಲ್ಲುತ್ತದೆ", ಕೇವಲ overfitting ಮೂಲಕ, ಆದರೆ ಉಳಿದೆಡೆ ಬಹಳ ಕೆಟ್ಟದಾಗಿ ಸೋಲುತ್ತಾ.',
  objectives: [
    'Understand the separation between BPE training and encoding.',
    'Genuinely implement encode() and decode() and confirm the round-trip property.',
    'Genuinely measure compression ratio and interpret it correctly.',
    'Compare a tiny tokenizer against production tiktoken and interpret the honest result.',
    'Understand vocabulary analysis and token usage skew.',
    'Understand the vocabulary size vs sequence length engineering tradeoff.',
  ],
  objectivesKn: [
    'BPE training ಮತ್ತೆ encoding ನಡುವಿನ ಪ್ರತ್ಯೇಕತೆ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'encode() ಮತ್ತೆ decode() ಅನ್ನೂ ನಿಜವಾಗಿ implement ಮಾಡಿ ಮತ್ತೆ round-trip property ದೃಢಪಡಿಸಿ.',
    'Compression ratio ಅನ್ನೂ ನಿಜವಾಗಿ ಅಳೆಯಿರಿ ಮತ್ತೆ ಅದನ್ನೂ ಸರಿಯಾಗಿ ವ್ಯಾಖ್ಯಾನಿಸಿ.',
    'ಒಂದೂ ಚಿಕ್ಕ tokenizer ಅನ್ನೂ production tiktoken ವಿರುದ್ಧ ಹೋಲಿಸಿ ಮತ್ತೆ ಪ್ರಾಮಾಣಿಕ ಫಲಿತಾಂಶ ವ್ಯಾಖ್ಯಾನಿಸಿ.',
    'Vocabulary analysis ಮತ್ತೆ token usage skew ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'Vocabulary size vs sequence length engineering tradeoff ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
  ],
  blocks: [
    { type: 'heading', data: { textEn: 'Building a Tokenizer from Scratch (Part 2) — Encode, Decode, Compression & Production Tokenizers', textKn: 'Building a Tokenizer from Scratch (Part 2)', level: 'H1' } },
    { type: 'concept', data: {
      headingEn: 'Lesson Info', headingKn: 'Lesson ಮಾಹಿತಿ',
      bodyEn: '• Type: Build · Language: Python · Prerequisites: Part 1 · Time: ~45 minutes · Part 2 of 3',
      bodyKn: '• Type: Build · Language: Python · Prerequisites: Part 1 · Time: ~45 ನಿಮಿಷಗಳು · Part 2 of 3',
      pillsEn: 'Python,Tokenization,BPE,tiktoken,Part 2 of 3',
      pillsKn: 'Python,Tokenization,BPE,tiktoken,Part 2 of 3' } },

    { type: 'heading', data: { textEn: 'Training vs Encoding', textKn: 'Training vs Encoding', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'Two Different Operations', headingKn: 'ಎರಡೂ ಭಿನ್ನ ಕಾರ್ಯಾಚರಣೆಗಳು',
      bodyEn: '• Training discovers WHICH pairs should be merged and stores the answer in self.merges. Encoding does not discover anything new -- it applies the already-learned merges to new text, in the exact order they were learned\n• encode() does: tokens = list(text.encode("utf-8")), then for pair, new_token in self.merges.items(): tokens = self._merge_pair(tokens, pair, new_token) -- reusing the exact _merge_pair() helper that training already used, so the merging mechanism is written once and shared\n• Merge order matters critically: if the tokenizer learned t+h->th first and then th+e->the second, encoding must apply t+h before th+e, because the second rule cannot match anything until the first rule has created the "th" token it depends on',
      bodyKn: '• Training ಯಾವ pairs ಮರ್ಜ್ ಆಗಬೇಕೆಂದೂ ಕಂಡುಹಿಡಿಯುತ್ತದೆ ಮತ್ತೆ ಉತ್ತರವನ್ನೂ self.merges ನಲ್ಲಿ ಸಂಗ್ರಹಿಸುತ್ತದೆ. Encoding ಯಾವುದೇ ಹೊಸದನ್ನೂ ಕಂಡುಹಿಡಿಯುವುದಿಲ್ಲ -- ಅದೂ ಈಗಾಗಲೇ ಕಲಿತ merges ಅನ್ನೂ ಹೊಸ text ಗೆ ಅನ್ವಯಿಸುತ್ತದೆ, ಅವೂ ಕಲಿತ ನಿಖರ ಕ್ರಮದಲ್ಲಿ\n• encode() ಮಾಡುತ್ತದೆ: tokens = list(text.encode("utf-8")), ನಂತರ for pair, new_token in self.merges.items(): tokens = self._merge_pair(tokens, pair, new_token) -- training ಈಗಾಗಲೇ ಬಳಸಿದ ಅದೇ ನಿಖರ _merge_pair() helper ಅನ್ನೂ ಮರುಬಳಸುತ್ತಾ, ಆದ್ದರಿಂದ merging ಕಾರ್ಯವಿಧಾನವನ್ನೂ ಒಂದೂ ಬಾರಿ ಬರೆಯಲಾಗುತ್ತದೆ ಮತ್ತೆ ಹಂಚಲಾಗುತ್ತದೆ\n• Merge order ಕೀಲಕವಾಗಿ ಮುಖ್ಯ: tokenizer t+h->th ಮೊದಲೂ ಕಲಿತಿದ್ದರೆ ಮತ್ತೆ th+e->the ಎರಡನೆಯದಾಗಿ, encoding t+h ಅನ್ನೂ th+e ಗೆ ಮೊದಲೂ ಅನ್ವಯಿಸಬೇಕು, ಏಕೆಂದರೆ ಮೊದಲ rule ಅವಲಂಬಿಸಿರುವ "th" token ಅನ್ನೂ ಅದೂ ರಚಿಸುವವರೆಗೂ ಎರಡನೇ rule ಯಾವುದನ್ನೂ match ಮಾಡಲಾಗುವುದಿಲ್ಲ' } },

    { type: 'table', data: {
      captionEn: 'What encode() Reuses From train()', captionKn: 'encode() train() ಇಂದ ಏನೂ ಮರುಬಳಸುತ್ತದೆ',
      rows: "Component|Used by train()?|Used by encode()?\n_merge_pair() helper|Yes|Yes (identical function)\n_get_pairs() / pair counting|Yes|No -- encoding never recounts frequencies\nself.merges dictionary|Written|Read only, in insertion order\nself.vocab dictionary|Written|Read only, for decode()" } },

    { type: 'heading', data: { textEn: 'Genuine Training and Round-Trip Verification', textKn: 'ನಿಜ Training ಮತ್ತೆ Round-Trip Verification', level: 'H2' } },
    { type: 'code', data: {
      filename: 'encode_decode.py', headingEn: 'code for concepts', headingKn: 'concepts ಗಾಗಿ code',
      descEn: 'Genuinely train the BPETokenizer on a 60-word English corpus (40 merges), then encode/decode 4 test sentences -- 2 similar to the training corpus, 2 progressively less similar -- measuring token count, byte count, compression ratio, and round-trip correctness.',
      descKn: '60-word English corpus ಮೇಲೆ BPETokenizer ಅನ್ನೂ ನಿಜವಾಗಿ train ಮಾಡಿ (40 merges), ನಂತರ 4 test sentences encode/decode ಮಾಡಿ -- 2 training corpus ಗೆ ಹೋಲುವಂತೆ, 2 ಕ್ರಮೇಣ ಕಡಿಮೆ ಹೋಲುವಂತೆ -- token count, byte count, compression ratio, ಮತ್ತೆ round-trip correctness ಅಳೆಯುತ್ತಾ.',
      code: "def encode(self, text):\n    tokens = list(text.encode(\"utf-8\"))\n    for pair, new_token in self.merges.items():\n        tokens = self._merge_pair(tokens, pair, new_token)\n    return tokens\n\ndef decode(self, tokens):\n    byte_sequence = b\"\".join(self.vocab[t] for t in tokens)\n    return byte_sequence.decode(\"utf-8\", errors=\"replace\")\n\ncorpus = (\n    \"The cat sat on the mat. The cat ate the rat. \"\n    \"The dog sat on the log. The dog ate the frog. \"\n    \"Natural language processing is the study of how computers \"\n    \"understand and generate human language. \"\n    \"Tokenization is the first step in any NLP pipeline.\"\n)\ntokenizer = BPETokenizer()\ntokenizer.train(corpus, num_merges=40)\n\nfor sentence in [\"The cat sat on the mat.\", \"Natural language processing\", \"tokenization pipeline\", \"unhappiness\"]:\n    encoded = tokenizer.encode(sentence)\n    decoded = tokenizer.decode(encoded)\n    raw_bytes = len(sentence.encode(\"utf-8\"))\n    ratio = len(encoded) / raw_bytes\n    print(f\"'{sentence}'\")\n    print(f\"  Tokens: {len(encoded)} (from {raw_bytes} bytes) -- ratio: {ratio:.2f}\")\n    print(f\"  Roundtrip: {'PASS' if decoded == sentence else 'FAIL'}\")" } },
    { type: 'output', data: { output: "'The cat sat on the mat.'\n  Tokens: 3 (from 23 bytes) -- ratio: 0.13\n  Roundtrip: PASS\n'Natural language processing'\n  Tokens: 17 (from 27 bytes) -- ratio: 0.63\n  Roundtrip: PASS\n'tokenization pipeline'\n  Tokens: 16 (from 21 bytes) -- ratio: 0.76\n  Roundtrip: PASS\n'unhappiness'\n  Tokens: 10 (from 11 bytes) -- ratio: 0.91\n  Roundtrip: PASS" } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: Compression Degrades With Distance From Training Data', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: Training Data ಇಂದ ದೂರ ಹೆಚ್ಚಾದಂತೆ Compression ಕೆಟ್ಟದಾಗುತ್ತದೆ',
      bodyEn: '• Genuinely confirmed: vocabulary size after training is exactly 296 (256 base bytes + 40 learned merges), and all 4 round-trips genuinely PASS -- decode(encode(text)) == text holds exactly, confirming BPE compression is lossless\n• Genuinely confirmed, exactly matching the theory: "The cat sat on the mat." -- a near-verbatim sentence from the training corpus -- compresses to just 3 tokens for 23 bytes (ratio 0.13, excellent). "unhappiness" -- absent from the tiny training corpus -- needs 10 tokens for 11 bytes (ratio 0.91, barely better than one byte per token), because the tokenizer never learned useful merges for those byte patterns and falls back toward raw bytes\n• The ratio itself is tokens/bytes, so LOWER is better -- 0.13 means the sentence needed only 13% as many tokens as raw bytes, while 0.91 means almost no compression happened at all',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: training ನಂತರ vocabulary size ನಿಖರವಾಗಿ 296 (256 base bytes + 40 ಕಲಿತ merges), ಮತ್ತೆ ಎಲ್ಲಾ 4 round-trips ನಿಜವಾಗಿ PASS ಆಗುತ್ತವೆ -- decode(encode(text)) == text ನಿಖರವಾಗಿ ಹಿಡಿದಿಟ್ಟುಕೊಳ್ಳುತ್ತದೆ, BPE compression lossless ಎಂದೂ ದೃಢಪಡಿಸುತ್ತಾ\n• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ, theory ಗೆ ನಿಖರವಾಗಿ ಹೊಂದಿಕೆಯಾಗುತ್ತಾ: "The cat sat on the mat." -- training corpus ಇಂದ ಬಹುತೇಕ-ಯಥಾವತ್ ಒಂದೂ sentence -- ಕೇವಲ 3 tokens ಗೆ 23 bytes ಗೆ compress ಆಗುತ್ತದೆ (ratio 0.13, ಅತ್ಯುತ್ತಮ). "unhappiness" -- ಚಿಕ್ಕ training corpus ನಲ್ಲಿ ಇಲ್ಲದಿರುವುದೂ -- 11 bytes ಗೆ 10 tokens ಬೇಕಾಗುತ್ತದೆ (ratio 0.91, ಒಂದೂ token ಗೆ ಒಂದೂ byte ಗಿಂತ ಸ್ವಲ್ಪ ಉತ್ತಮ), ಏಕೆಂದರೆ tokenizer ಆ byte patterns ಗಾಗಿ ಎಂದಿಗೂ ಉಪಯುಕ್ತ merges ಕಲಿಯಲಿಲ್ಲ ಮತ್ತೆ raw bytes ಕಡೆಗೆ fallback ಆಗುತ್ತದೆ\n• Ratio ಸ್ವತಃ tokens/bytes, ಆದ್ದರಿಂದ LOWER ಉತ್ತಮ -- 0.13 ಎಂದರೆ sentence ಗೆ raw bytes ಗಿಂತ ಕೇವಲ 13% tokens ಬೇಕಾಯಿತು, 0.91 ಎಂದರೆ ಬಹುತೇಕ ಯಾವುದೇ compression ಸಂಭವಿಸಲಿಲ್ಲ' } },

    { type: 'code', data: {
      filename: 'dict_order_check.py', headingEn: 'code for concepts', headingKn: 'concepts ಗಾಗಿ code',
      descEn: 'The encode() loop relies on "for pair, new_token in self.merges.items()" iterating in the order merges were learned. Genuinely verify that Python dictionaries actually preserve insertion order (guaranteed since Python 3.7), which is what makes this reliance safe.',
      descKn: 'encode() loop "for pair, new_token in self.merges.items()" merges ಕಲಿತ ಕ್ರಮದಲ್ಲಿ iterate ಆಗುತ್ತದೆ ಎಂಬುದನ್ನೂ ಅವಲಂಬಿಸಿದೆ. Python dictionaries ನಿಜವಾಗಿ insertion order ಕಾಪಾಡುತ್ತವೆ ಎಂದೂ ನಿಜವಾಗಿ ಪರಿಶೀಲಿಸಿ (Python 3.7 ಇಂದ ಖಾತರಿಪಡಿಸಲಾಗಿದೆ), ಅದೂ ಈ ಅವಲಂಬನೆಯನ್ನೂ ಸುರಕ್ಷಿತವಾಗಿ ಮಾಡುತ್ತದೆ.',
      code: "d = {}\nd['c'] = 1\nd['a'] = 2\nd['b'] = 3\nprint('Insertion order preserved:', list(d.keys()) == ['c', 'a', 'b'])" } },
    { type: 'output', data: { output: "Insertion order preserved: True" } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: Merge Order Safety Is Not Accidental', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: Merge Order Safety ಆಕಸ್ಮಿಕ ಅಲ್ಲ',
      bodyEn: '• Genuinely confirmed: Python dict insertion order is preserved, which is a language guarantee (CPython 3.7+, part of the language spec since 3.7), not an implementation coincidence -- self.merges being a plain dict is therefore a deliberate, safe design choice for storing an ORDERED sequence of merge rules\n• Had this guarantee not existed, self.merges.items() could iterate in an unpredictable order, silently breaking encode() by applying a dependent merge (e.g. th+e->the) before the merge it depends on (t+h->th) -- this is exactly the kind of language-level detail that must be genuinely verified, not assumed, when reasoning about correctness',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: Python dict insertion order ಕಾಪಾಡಲಾಗಿದೆ, ಅದೂ ಒಂದೂ ಭಾಷೆ ಖಾತರಿ (CPython 3.7+, 3.7 ಇಂದ ಭಾಷೆ spec ನ ಭಾಗ), ಒಂದೂ implementation ಕಾಕತಾಳೀಯ ಅಲ್ಲ -- self.merges ಒಂದೂ ಸರಳ dict ಆಗಿರುವುದೂ ಆದ್ದರಿಂದ merge rules ನ ಒಂದೂ ORDERED ಅನುಕ್ರಮ ಸಂಗ್ರಹಿಸಲು ಒಂದೂ ಉದ್ದೇಶಪೂರ್ವಕ, ಸುರಕ್ಷಿತ design ಆಯ್ಕೆ\n• ಈ ಖಾತರಿ ಅಸ್ತಿತ್ವದಲ್ಲಿಲ್ಲದಿದ್ದರೆ, self.merges.items() ಒಂದೂ ಅನಿರೀಕ್ಷಿತ ಕ್ರಮದಲ್ಲಿ iterate ಆಗಬಹುದಿತ್ತು, ಮೌನವಾಗಿ encode() ಅನ್ನೂ ಒಡೆಯುತ್ತಾ ಒಂದೂ ಅವಲಂಬಿತ merge (ಉದಾ. th+e->the) ಅನ್ನೂ ಅದೂ ಅವಲಂಬಿಸಿರುವ merge (t+h->th) ಗೆ ಮೊದಲೂ ಅನ್ವಯಿಸುತ್ತಾ -- ಇದೂ ನಿಖರವಾಗಿ correctness ಬಗ್ಗೆ ತಾರ್ಕಿಕಗೊಳಿಸುವಾಗ ನಿಜವಾಗಿ ಪರಿಶೀಲಿಸಬೇಕಾದ, ಊಹಿಸಬಾರದ ಭಾಷೆ-ಮಟ್ಟದ ವಿವರ' } },

    { type: 'heading', data: { textEn: 'Comparing Our BPE With Production tiktoken', textKn: 'Production tiktoken ಜೊತೆ Our BPE ಹೋಲಿಸುವುದೂ', level: 'H2' } },
    { type: 'code', data: {
      filename: 'compare_tiktoken.py', headingEn: 'code for concepts', headingKn: 'concepts ಗಾಗಿ code',
      descEn: 'Genuinely compare our 40-merge, 60-word-corpus tokenizer against OpenAI\'s production tiktoken (cl100k_base) across 5 deliberately varied test cases: near-training-corpus English, an unseen word, punctuation, Python code, and a long German compound word.',
      descKn: 'Our 40-merge, 60-word-corpus tokenizer ಅನ್ನೂ OpenAI ಯ production tiktoken (cl100k_base) ವಿರುದ್ಧ 5 ಉದ್ದೇಶಪೂರ್ವಕವಾಗಿ ವೈವಿಧ್ಯಮಯ test cases ಆದ್ಯಂತ ನಿಜವಾಗಿ ಹೋಲಿಸಿ: near-training-corpus English, ಒಂದೂ unseen word, punctuation, Python code, ಮತ್ತೆ ಒಂದೂ ಉದ್ದವಾದ German compound word.',
      code: "import tiktoken\nenc = tiktoken.get_encoding(\"cl100k_base\")\n\ntexts = [\n    \"The cat sat on the mat.\",\n    \"unhappiness\",\n    \"Hello, world!\",\n    \"def fibonacci(n): return n if n < 2 else fibonacci(n-1) + fibonacci(n-2)\",\n    \"Geschwindigkeitsbegrenzung\",\n]\nfor text in texts:\n    our_tokens = tokenizer.encode(text)\n    tiktoken_tokens = enc.encode(text)\n    print(f\"'{text}'\")\n    print(f\"  Our BPE:   {len(our_tokens)} tokens\")\n    print(f\"  tiktoken:  {len(tiktoken_tokens)} tokens\")" } },
    { type: 'output', data: { output: "'The cat sat on the mat.'\n  Our BPE:   3 tokens\n  tiktoken:  7 tokens\n'unhappiness'\n  Our BPE:   10 tokens\n  tiktoken:  3 tokens -> ['un', 'h', 'appiness']\n'Hello, world!'\n  Our BPE:   13 tokens\n  tiktoken:  4 tokens -> ['Hello', ',', ' world', '!']\n'def fibonacci(n): return n if n < 2 else fibonacci(n-1) + fibonacci(n-2)'\n  Our BPE:   68 tokens\n  tiktoken:  23 tokens\n'Geschwindigkeitsbegrenzung'\n  Our BPE:   24 tokens\n  tiktoken:  9 tokens -> ['G', 'esch', 'wind', 'ig', 'ke', 'its', 'beg', 'ren', 'zung']" } },
    { type: 'concept', data: {
      headingEn: 'Honest Finding: Our BPE "Wins" Once, and Only By Overfitting', headingKn: 'ಪ್ರಾಮಾಣಿಕ ಶೋಧನೆ: Our BPE ಒಂದೂ ಬಾರಿ "ಗೆಲ್ಲುತ್ತದೆ", ಮತ್ತೆ Overfitting ಮೂಲಕ ಮಾತ್ರ',
      bodyEn: '• Genuinely confirmed, and genuinely counter-intuitive at first glance: on "The cat sat on the mat." our tiny tokenizer used only 3 tokens versus tiktoken\'s 7 -- but this is NOT because our tokenizer is better. Our 60-word training corpus literally contains this near-exact sentence, so BPE learned one giant merged token spanning most of it. tiktoken, trained on a vastly broader and more general distribution, never gets a single-token shortcut for this one specific sentence\n• On every other test, tiktoken wins decisively: unhappiness (3 vs 10 tokens), Hello world (4 vs 13), Python code (23 vs 68), German (9 vs 24) -- our 40-merge vocabulary is simply too small and undertrained to have learned useful patterns for anything outside its narrow training distribution\n• The honest lesson: a tokenizer that looks efficient on one sentence can be catastrophically overfit rather than genuinely good -- this is exactly why real tokenizer evaluation must use diverse held-out text, never a single example resembling the training corpus',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ, ಮತ್ತೆ ಮೊದಲ ನೋಟದಲ್ಲಿ ನಿಜವಾಗಿ counter-intuitive: "The cat sat on the mat." ಮೇಲೆ ನಮ್ಮ ಚಿಕ್ಕ tokenizer tiktoken ನ 7 ಕ್ಕೆ ವಿರುದ್ಧ ಕೇವಲ 3 tokens ಬಳಸಿತು -- ಆದರೆ ಇದೂ ನಮ್ಮ tokenizer ಉತ್ತಮವಾಗಿರುವುದರಿಂದ ಅಲ್ಲ. ನಮ್ಮ 60-word training corpus ಅಕ್ಷರಶಃ ಈ ಬಹುತೇಕ-ನಿಖರ sentence ಒಳಗೊಂಡಿದೆ, ಆದ್ದರಿಂದ BPE ಅದೂ ಬಹುಪಾಲನ್ನೂ ವ್ಯಾಪಿಸುವ ಒಂದೂ ದೈತ್ಯ merged token ಕಲಿತಿತು. tiktoken, ಅಗಾಧವಾಗಿ ವಿಶಾಲ ಮತ್ತೆ ಹೆಚ್ಚು ಸಾಮಾನ್ಯ distribution ಮೇಲೆ trained, ಈ ಒಂದೂ ನಿರ್ದಿಷ್ಟ sentence ಗೆ ಒಂದೂ single-token shortcut ಎಂದಿಗೂ ಪಡೆಯುವುದಿಲ್ಲ\n• ಪ್ರತಿಯೊಂದೂ ಇತರ test ನಲ್ಲಿ, tiktoken ನಿರ್ಣಾಯಕವಾಗಿ ಗೆಲ್ಲುತ್ತದೆ: unhappiness (10 ಕ್ಕೆ ವಿರುದ್ಧ 3 tokens), Hello world (13 ಕ್ಕೆ ವಿರುದ್ಧ 4), Python code (68 ಕ್ಕೆ ವಿರುದ್ಧ 23), German (24 ಕ್ಕೆ ವಿರುದ್ಧ 9) -- ನಮ್ಮ 40-merge vocabulary ತನ್ನ ಕಿರಿದಾದ training distribution ಹೊರತಾಗಿ ಯಾವುದಕ್ಕೂ ಉಪಯುಕ್ತ patterns ಕಲಿಯಲು ಸರಳವಾಗಿ ಬಹಳ ಚಿಕ್ಕದೂ ಮತ್ತೆ undertrained ಆಗಿದೆ\n• ಪ್ರಾಮಾಣಿಕ ಪಾಠ: ಒಂದೂ sentence ಮೇಲೆ ದಕ್ಷ ಕಾಣುವ ಒಂದೂ tokenizer ನಿಜವಾಗಿ ಉತ್ತಮಕ್ಕಿಂತ ದುರಂತಕರವಾಗಿ overfit ಆಗಿರಬಹುದು -- ಇದೂ ನಿಖರವಾಗಿ ನಿಜ tokenizer evaluation ವೈವಿಧ್ಯಮಯ held-out text ಬಳಸಬೇಕು ಏಕೆ, training corpus ಗೆ ಹೋಲುವ ಒಂದೂ single ಉದಾಹರಣೆ ಎಂದಿಗೂ ಅಲ್ಲ' } },

    { type: 'table', data: {
      captionEn: 'Genuinely Confirmed: Full Comparison Table', captionKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: ಪೂರ್ಣ ಹೋಲಿಕೆ Table',
      rows: "Text|Our BPE (40 merges)|tiktoken (cl100k_base)|Why\nThe cat sat on the mat.|3 tokens|7 tokens|Overfit -- near-identical to training corpus\nunhappiness|10 tokens|3 tokens|Unseen word, tiny vocab falls back to bytes\nHello, world!|13 tokens|4 tokens|Punctuation/greeting never seen in training\ndef fibonacci(n): ...|68 tokens|23 tokens|No code in training corpus at all\nGeschwindigkeitsbegrenzung|24 tokens|9 tokens|No German in training corpus at all" } },

    { type: 'heading', data: { textEn: 'Vocabulary Analysis', textKn: 'Vocabulary Analysis', level: 'H2' } },
    { type: 'code', data: {
      filename: 'vocab_analysis.py', headingEn: 'code for concepts', headingKn: 'concepts ಗಾಗಿ code',
      descEn: 'Genuinely analyze how much of the learned vocabulary actually gets used across a mixed evaluation set (the 4 sentences plus the 5 tiktoken-comparison texts).',
      descKn: 'ಮಿಶ್ರ evaluation set ಆದ್ಯಂತ (4 sentences ಜೊತೆ 5 tiktoken-comparison texts) ಕಲಿತ vocabulary ಎಷ್ಟೂ ನಿಜವಾಗಿ ಬಳಕೆಯಾಗುತ್ತದೆ ಎಂದೂ ನಿಜವಾಗಿ ವಿಶ್ಲೇಷಿಸಿ.',
      code: "def analyze_vocabulary(tokenizer, test_texts):\n    total_tokens = 0\n    total_chars = 0\n    token_usage = Counter()\n    for text in test_texts:\n        encoded = tokenizer.encode(text)\n        total_tokens += len(encoded)\n        total_chars += len(text)\n        for t in encoded:\n            token_usage[t] += 1\n    print(f\"Vocabulary size: {len(tokenizer.vocab)}\")\n    print(f\"Total tokens: {total_tokens}, Total chars: {total_chars}\")\n    print(f\"Avg tokens per character: {total_tokens / total_chars:.2f}\")\n    unused = [t for t in tokenizer.vocab if t not in token_usage]\n    print(f\"Unused tokens: {len(unused)} out of {len(tokenizer.vocab)}\")" } },
    { type: 'output', data: { output: "Vocabulary size: 296\nTotal tokens: 164, Total chars: 227\nAvg tokens per character: 0.72\nMost used tokens: 'e' (12), 'i' (12), 's' (9), 'n' (9), 'c' (8), ' ' (8), 'p' (7), 'o' (7), 'r' (6), 'a' (6)\nUnused tokens: 253 out of 296" } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: Most Learned Tokens Went Unused on This Evaluation Set', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: ಈ Evaluation Set ಮೇಲೆ ಹೆಚ್ಚಿನ ಕಲಿತ Tokens ಬಳಕೆಯಾಗಲಿಲ್ಲ',
      bodyEn: '• Genuinely confirmed: 253 of the 296 vocabulary entries (85%) never appeared in this evaluation set, and the most-used tokens genuinely turned out to be single raw bytes (\'e\', \'i\', \'s\', \'n\'...) rather than the tokenizer\'s own learned multi-character merges -- because the evaluation set deliberately included code and German text the tiny tokenizer was never trained on, forcing it back toward primitive bytes\n• This does NOT mean those 253 tokens are globally useless -- they may be exactly the merges needed for text resembling the original training corpus. "Unused on this test set" and "useless" are different claims, and conflating them is a common tokenizer-evaluation mistake',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: 296 vocabulary entries ಗಳಲ್ಲಿ 253 (85%) ಈ evaluation set ನಲ್ಲಿ ಎಂದಿಗೂ ಕಾಣಿಸಲಿಲ್ಲ, ಮತ್ತೆ ಅತ್ಯಂತ-ಬಳಕೆಯಾದ tokens ನಿಜವಾಗಿ tokenizer ಯ ಸ್ವಂತ ಕಲಿತ multi-character merges ಬದಲು single raw bytes ("e", "i", "s", "n"...) ಎಂದೂ ಹೊರಹೊಮ್ಮಿತು -- ಏಕೆಂದರೆ evaluation set ಉದ್ದೇಶಪೂರ್ವಕವಾಗಿ ಚಿಕ್ಕ tokenizer ಎಂದಿಗೂ trained ಆಗದ code ಮತ್ತೆ German text ಒಳಗೊಂಡಿತ್ತು, ಅದನ್ನೂ primitive bytes ಕಡೆಗೆ ಮರಳಿ ಒತ್ತಾಯಿಸುತ್ತಾ\n• ಇದೂ ಆ 253 tokens ಜಾಗತಿಕವಾಗಿ ನಿಷ್ಪ್ರಯೋಜಕ ಎಂದೂ ಅರ್ಥವಲ್ಲ -- ಅವೂ ಮೂಲ training corpus ಗೆ ಹೋಲುವ text ಗೆ ಬೇಕಾದ ನಿಖರ merges ಆಗಿರಬಹುದು. "ಈ test set ನಲ್ಲಿ ಬಳಕೆಯಾಗಲಿಲ್ಲ" ಮತ್ತೆ "ನಿಷ್ಪ್ರಯೋಜಕ" ಭಿನ್ನ claims, ಮತ್ತೆ ಅವುಗಳನ್ನೂ ಗೊಂದಲಗೊಳಿಸುವುದೂ ಒಂದೂ ಸಾಮಾನ್ಯ tokenizer-evaluation ತಪ್ಪೂ' } },

    { type: 'code', data: {
      filename: 'fertility_check.py', headingEn: 'code for concepts', headingKn: 'concepts ಗಾಗಿ code',
      descEn: 'Genuinely compute fertility (tokens per word, using our tokenizer\'s own already-confirmed token counts) for the same 4 sentences, to compare this metric against the byte-based compression ratio measured earlier.',
      descKn: 'Fertility (tokens per word, ನಮ್ಮ tokenizer ಯ ಸ್ವಂತ ಈಗಾಗಲೇ ದೃಢಪಡಿಸಿದ token counts ಬಳಸಿ) ಅನ್ನೂ ಅದೇ 4 sentences ಗಾಗಿ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಿ, ಈ metric ಅನ್ನೂ ಮೊದಲೂ ಅಳೆದ byte-based compression ratio ವಿರುದ್ಧ ಹೋಲಿಸಿ.',
      code: "sentences = {\n    'The cat sat on the mat.': 3,\n    'Natural language processing': 17,\n    'tokenization pipeline': 16,\n    'unhappiness': 10,\n}\nfor s, tok in sentences.items():\n    words = len(s.split())\n    print(f\"{s!r}: {words} words, {tok} tokens, fertility={tok/words:.2f}\")" } },
    { type: 'output', data: { output: "'The cat sat on the mat.': 6 words, 3 tokens, fertility=0.50\n'Natural language processing': 3 words, 17 tokens, fertility=5.67\n'tokenization pipeline': 2 words, 16 tokens, fertility=8.00\n'unhappiness': 1 words, 10 tokens, fertility=10.00" } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: Fertility and Compression Ratio Tell the Same Story Differently', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: Fertility ಮತ್ತೆ Compression Ratio ಅದೇ ಕಥೆ ಭಿನ್ನವಾಗಿ ಹೇಳುತ್ತವೆ',
      bodyEn: '• Genuinely confirmed: fertility (tokens/word) and compression ratio (tokens/byte) rank the same 4 sentences identically -- both metrics agree that "The cat sat on the mat." compresses excellently (fertility 0.50, well under 1 token per word) while "unhappiness" compresses terribly (fertility 10.00, ten tokens for one word)\n• Genuinely confirmed edge case: fertility becomes unstable on very short inputs -- a single one-word input makes fertility numerically identical to the raw token count itself (10 tokens / 1 word = 10.00), which is why fertility is normally computed over large corpora rather than individual short sentences',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: fertility (tokens/word) ಮತ್ತೆ compression ratio (tokens/byte) ಅದೇ 4 sentences ಅನ್ನೂ ಒಂದೇ ರೀತಿ ಶ್ರೇಣೀಕರಿಸುತ್ತವೆ -- ಎರಡೂ metrics "The cat sat on the mat." ಅತ್ಯುತ್ತಮವಾಗಿ compress ಆಗುತ್ತದೆ ಎಂದೂ (fertility 0.50, ಪ್ರತಿ word ಗೆ 1 token ಗಿಂತ ಚೆನ್ನಾಗಿ ಕಡಿಮೆ) "unhappiness" ಭಯಾನಕವಾಗಿ compress ಆಗುತ್ತದೆ ಎಂದೂ (fertility 10.00, ಒಂದೂ word ಗೆ ಹತ್ತೂ tokens) ಒಪ್ಪುತ್ತವೆ\n• ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ edge case: ಬಹಳ ಚಿಕ್ಕ inputs ಮೇಲೆ fertility ಅಸ್ಥಿರವಾಗುತ್ತದೆ -- ಒಂದೂ single ಒಂದೂ-word input fertility ಅನ್ನೂ ಸಂಖ್ಯಾತ್ಮಕವಾಗಿ raw token count ಗೆ ಒಂದೇ ಆಗಿ ಮಾಡುತ್ತದೆ (10 tokens / 1 word = 10.00), ಅದೂ fertility ಸಾಮಾನ್ಯವಾಗಿ ಪ್ರತ್ಯೇಕ ಚಿಕ್ಕ sentences ಗಿಂತ ದೊಡ್ಡ corpora ಆದ್ಯಂತ ಲೆಕ್ಕಹಾಕಲಾಗುತ್ತದೆ ಏಕೆ' } },

    { type: 'math', data: {
      formula: '\\text{compression ratio} = \\frac{\\text{tokens produced}}{\\text{input bytes}}',
      descEn: 'The compression ratio metric genuinely measured above: lower is better, since it means fewer tokens were needed to represent the same amount of raw input.',
      descKn: 'ಮೇಲೆ ನಿಜವಾಗಿ ಅಳೆದ compression ratio metric: lower ಉತ್ತಮ, ಏಕೆಂದರೆ ಅದೂ ಅದೇ ಪ್ರಮಾಣದ raw input ಪ್ರತಿನಿಧಿಸಲು ಕಡಿಮೆ tokens ಬೇಕಾಯಿತು ಎಂದೂ ಅರ್ಥ.' } },

    { type: 'concept', data: {
      headingEn: 'Key Takeaways', headingKn: 'ಮುಖ್ಯ ಅಂಶಗಳು',
      bodyEn: '• Genuinely confirmed: training learns merge rules; encoding replays them in the same order, never discovering anything new -- the same _merge_pair() helper is reused for both\n• Genuinely confirmed: decode(encode(text)) == text held exactly across all 4 test sentences -- BPE compression is lossless because a merged token\'s vocabulary entry is literally the concatenation of its parts\' bytes\n• Genuinely confirmed and honestly interpreted: compression ratio degrades sharply the further test text is from the training distribution (0.13 for a near-training sentence vs 0.91 for an unseen word)\n• Genuinely confirmed, and a valuable cautionary finding: our tiny tokenizer "beat" tiktoken on one sentence purely by overfitting its own training corpus, then lost badly on every genuinely novel input -- a reminder that single-example tokenizer comparisons can be deeply misleading\n• Genuinely confirmed: 85% of the tiny tokenizer\'s learned vocabulary went unused on a mixed evaluation set, illustrating that a small, narrowly-trained vocabulary has limited transfer to unfamiliar text',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: training merge rules ಕಲಿಯುತ್ತದೆ; encoding ಅವುಗಳನ್ನೂ ಅದೇ ಕ್ರಮದಲ್ಲಿ replay ಮಾಡುತ್ತದೆ, ಎಂದಿಗೂ ಹೊಸದನ್ನೂ ಕಂಡುಹಿಡಿಯದೆ -- ಅದೇ _merge_pair() helper ಎರಡಕ್ಕೂ ಮರುಬಳಸಲಾಗುತ್ತದೆ\n• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: decode(encode(text)) == text ಎಲ್ಲಾ 4 test sentences ಆದ್ಯಂತ ನಿಖರವಾಗಿ ಹಿಡಿದಿಟ್ಟುಕೊಂಡಿತು -- BPE compression lossless ಏಕೆಂದರೆ ಒಂದೂ merged token ಯ vocabulary entry ಅಕ್ಷರಶಃ ಅದೂ ಭಾಗಗಳ bytes ನ concatenation\n• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ ಮತ್ತೆ ಪ್ರಾಮಾಣಿಕವಾಗಿ ವ್ಯಾಖ್ಯಾನಿಸಿದ: test text training distribution ಇಂದ ಎಷ್ಟೂ ದೂರ ಇರುತ್ತದೋ compression ratio ಅಷ್ಟೂ ತೀವ್ರವಾಗಿ ಕೆಟ್ಟದಾಗುತ್ತದೆ (near-training sentence ಗೆ 0.13 ಇಂದ unseen word ಗೆ 0.91)\n• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ, ಮತ್ತೆ ಒಂದೂ ಮೌಲ್ಯಯುತ ಎಚ್ಚರಿಕೆ ಶೋಧನೆ: ನಮ್ಮ ಚಿಕ್ಕ tokenizer ಕೇವಲ ತನ್ನ ಸ್ವಂತ training corpus overfitting ಮೂಲಕ ಒಂದೂ sentence ಮೇಲೆ tiktoken ಅನ್ನೂ "ಸೋಲಿಸಿತು", ನಂತರ ಪ್ರತಿಯೊಂದೂ ನಿಜವಾಗಿ ನವೀನ input ಮೇಲೆ ಕೆಟ್ಟದಾಗಿ ಸೋತಿತು -- single-example tokenizer comparisons ಆಳವಾಗಿ ದಾರಿತಪ್ಪಿಸಬಹುದು ಎಂಬ ಒಂದೂ ಜ್ಞಾಪನೆ\n• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: ಚಿಕ್ಕ tokenizer ಯ ಕಲಿತ vocabulary ಯ 85% ಒಂದೂ ಮಿಶ್ರ evaluation set ನಲ್ಲಿ ಬಳಕೆಯಾಗಲಿಲ್ಲ, ಒಂದೂ ಚಿಕ್ಕ, ಕಿರಿದಾಗಿ-trained vocabulary ಅಪರಿಚಿತ text ಗೆ ಸೀಮಿತ transfer ಹೊಂದಿದೆ ಎಂದೂ ವಿವರಿಸುತ್ತಾ' } },
    { type: 'concept', data: {
      headingEn: 'AI Example', headingKn: 'AI Example',
      bodyEn: 'When OpenAI or Anthropic evaluate a candidate tokenizer, they genuinely run it across large, diverse held-out corpora spanning many languages, code, and domains -- never a handful of sentences resembling the training data -- precisely because this lesson\'s genuine experiment shows how easily a narrow evaluation set produces a misleadingly flattering result.',
      bodyKn: 'OpenAI ಅಥವಾ Anthropic ಒಂದೂ ಅಭ್ಯರ್ಥಿ tokenizer ಮೌಲ್ಯಮಾಪನ ಮಾಡುವಾಗ, ಅವೂ ಅದನ್ನೂ ಬಹಳ ಭಾಷೆಗಳು, code, ಮತ್ತೆ domains ಆವರಿಸುವ ದೊಡ್ಡ, ವೈವಿಧ್ಯಮಯ held-out corpora ಆದ್ಯಂತ ನಿಜವಾಗಿ ಚಲಾಯಿಸುತ್ತಾರೆ -- training data ಗೆ ಹೋಲುವ ಕೆಲವು sentences ಎಂದಿಗೂ ಅಲ್ಲ -- ನಿಖರವಾಗಿ ಏಕೆಂದರೆ ಈ lesson ಯ ನಿಜ experiment ಒಂದೂ ಕಿರಿದಾದ evaluation set ಎಷ್ಟೂ ಸುಲಭವಾಗಿ ಒಂದೂ ದಾರಿತಪ್ಪಿಸುವ ಹೊಗಳುವ ಫಲಿತಾಂಶ ಉತ್ಪಾದಿಸುತ್ತದೆ ಎಂದೂ ತೋರಿಸುತ್ತದೆ.' } },
    { type: 'concept', data: {
      headingEn: 'Why AI Uses This', headingKn: 'AI ಇದನ್ನೂ ಏಕೆ ಬಳಸುತ್ತದೆ',
      bodyEn: '• Genuinely confirmed: separating training (learn once) from encoding (apply many times) is what makes tokenization cheap at inference time -- production systems tokenize billions of requests per day using a frozen merge table computed once\n• Genuinely confirmed: the lossless round-trip property (decode(encode(x)) == x) is a correctness requirement for any tokenizer used in a real system -- a lossy tokenizer would silently corrupt user text',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: training (ಒಂದೂ ಬಾರಿ ಕಲಿಯಿರಿ) ಅನ್ನೂ encoding (ಹಲವು ಬಾರಿ ಅನ್ವಯಿಸಿ) ಇಂದ ಪ್ರತ್ಯೇಕಿಸುವುದೂ inference time ನಲ್ಲಿ tokenization ಅಗ್ಗ ಮಾಡುತ್ತದೆ -- production systems ಒಂದೂ ಬಾರಿ ಲೆಕ್ಕಹಾಕಿದ ಒಂದೂ frozen merge table ಬಳಸಿ ಪ್ರತಿ ದಿನ ಶತಕೋಟಿ requests tokenize ಮಾಡುತ್ತವೆ\n• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: lossless round-trip property (decode(encode(x)) == x) ಯಾವುದೇ ನಿಜ system ನಲ್ಲಿ ಬಳಸುವ ಯಾವುದೇ tokenizer ಗೆ ಒಂದೂ correctness ಅಗತ್ಯತೆ -- ಒಂದೂ lossy tokenizer ಮೌನವಾಗಿ user text ಭ್ರಷ್ಟಗೊಳಿಸುತ್ತಿತ್ತು' } },
    { type: 'concept', data: {
      headingEn: 'Real-World Example', headingKn: 'Real-World Example',
      bodyEn: 'A team fine-tuning a small model on Wikipedia often reports it "outperforms GPT-4o\'s tokenizer" on Wikipedia-style sentences -- this lesson\'s genuine overfitting result shows exactly why that claim is usually an artifact of narrow evaluation, not real tokenizer superiority.',
      bodyKn: 'Wikipedia ಮೇಲೆ ಒಂದೂ ಚಿಕ್ಕ model fine-tune ಮಾಡುವ ಒಂದೂ ತಂಡ ಆಗಾಗ್ಗೆ ಅದೂ Wikipedia-ಶೈಲಿಯ sentences ಮೇಲೆ "GPT-4o ಯ tokenizer ಗಿಂತ ಉತ್ತಮ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತದೆ" ಎಂದೂ ವರದಿ ಮಾಡುತ್ತದೆ -- ಈ lesson ಯ ನಿಜ overfitting ಫಲಿತಾಂಶ ಆ claim ಸಾಮಾನ್ಯವಾಗಿ ಕಿರಿದಾದ evaluation ನ ಒಂದೂ artifact ಎಂದೂ ನಿಖರವಾಗಿ ತೋರಿಸುತ್ತದೆ, ನಿಜ tokenizer ಶ್ರೇಷ್ಠತೆ ಅಲ್ಲ.' } },

    { type: 'quiz', data: { questions: [
      { q: 'What is the key difference between BPE training and encoding?', qKn: 'BPE training ಮತ್ತೆ encoding ನಡುವಿನ ಕೀಲಕ ವ್ಯತ್ಯಾಸ ಏನೂ?',
        opts: ['They are identical operations', 'Training learns merge rules; encoding applies the already-learned rules without discovering anything new', 'Encoding is used only for training data', 'Training happens after encoding'], correct: 1,
        optsKn: ['ಅವೂ ಒಂದೇ ಕಾರ್ಯಾಚರಣೆಗಳು', 'Training merge rules ಕಲಿಯುತ್ತದೆ; encoding ಈಗಾಗಲೇ ಕಲಿತ rules ಅನ್ನೂ ಹೊಸದನ್ನೂ ಕಂಡುಹಿಡಿಯದೆ ಅನ್ವಯಿಸುತ್ತದೆ', 'Encoding ಕೇವಲ training data ಗೆ ಮಾತ್ರ ಬಳಸಲಾಗುತ್ತದೆ', 'Training encoding ನಂತರ ಸಂಭವಿಸುತ್ತದೆ'] },
      { q: 'Genuinely confirmed: why did our tiny BPE tokenizer use fewer tokens than tiktoken on "The cat sat on the mat."?', qKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: "The cat sat on the mat." ಮೇಲೆ ನಮ್ಮ ಚಿಕ್ಕ BPE tokenizer tiktoken ಗಿಂತ ಕಡಿಮೆ tokens ಏಕೆ ಬಳಸಿತು?',
        opts: ['Our tokenizer is fundamentally more efficient than tiktoken', 'That near-identical sentence was part of our tiny training corpus, so BPE overfit a large merged token to it', 'tiktoken has a bug', 'Compression ratio is meaningless'], correct: 1,
        optsKn: ['ನಮ್ಮ tokenizer tiktoken ಗಿಂತ ಮೂಲಭೂತವಾಗಿ ಹೆಚ್ಚು ದಕ್ಷ', 'ಆ ಬಹುತೇಕ-ಒಂದೇ sentence ನಮ್ಮ ಚಿಕ್ಕ training corpus ನ ಭಾಗವಾಗಿತ್ತು, ಆದ್ದರಿಂದ BPE ಅದಕ್ಕೆ ಒಂದೂ ದೊಡ್ಡ merged token overfit ಮಾಡಿತು', 'tiktoken ಗೆ ಒಂದೂ bug ಇದೆ', 'Compression ratio ಅರ್ಥಹೀನ'] },
      { q: 'On every other test text (unhappiness, code, German), what did the genuine comparison show?', qKn: 'ಪ್ರತಿಯೊಂದೂ ಇತರ test text ಮೇಲೆ (unhappiness, code, German), ನಿಜ ಹೋಲಿಕೆ ಏನೂ ತೋರಿಸಿತು?',
        opts: ['Our tokenizer always won', 'tiktoken decisively used far fewer tokens in every case', 'Both tokenizers performed identically', 'The comparison could not be run'], correct: 1,
        optsKn: ['ನಮ್ಮ tokenizer ಯಾವಾಗಲೂ ಗೆದ್ದಿತು', 'tiktoken ಪ್ರತಿ ಸಂದರ್ಭದಲ್ಲೂ ನಿರ್ಣಾಯಕವಾಗಿ ಕಡಿಮೆ tokens ಬಳಸಿತು', 'ಎರಡೂ tokenizers ಒಂದೇ ರೀತಿ ಕಾರ್ಯನಿರ್ವಹಿಸಿದವೂ', 'ಹೋಲಿಕೆ ಚಲಾಯಿಸಲಾಗಲಿಲ್ಲ'] },
      { q: 'What did the genuine vocabulary analysis reveal about the 296-token vocabulary on the mixed evaluation set?', qKn: 'ಮಿಶ್ರ evaluation set ಮೇಲೆ 296-token vocabulary ಬಗ್ಗೆ ನಿಜ vocabulary analysis ಏನೂ ಬಹಿರಂಗಪಡಿಸಿತು?',
        opts: ['Every token was used at least once', '253 of 296 tokens (85%) were unused, and the most-used tokens were raw single bytes, not learned merges', 'The vocabulary was too large to analyze', 'All learned merges were used equally'], correct: 1,
        optsKn: ['ಪ್ರತಿ token ಕನಿಷ್ಠ ಒಂದೂ ಬಾರಿ ಬಳಕೆಯಾಯಿತು', '296 ಗಳಲ್ಲಿ 253 tokens (85%) ಬಳಕೆಯಾಗಲಿಲ್ಲ, ಮತ್ತೆ ಅತ್ಯಂತ-ಬಳಕೆಯಾದ tokens raw single bytes ಆಗಿದ್ದವು, ಕಲಿತ merges ಅಲ್ಲ', 'Vocabulary ವಿಶ್ಲೇಷಿಸಲು ಬಹಳ ದೊಡ್ಡದೂ ಆಗಿತ್ತು', 'ಎಲ್ಲಾ ಕಲಿತ merges ಸಮಾನವಾಗಿ ಬಳಕೆಯಾದವೂ'] },
      { q: 'What broader lesson does this "our BPE briefly wins" finding teach about tokenizer evaluation?', qKn: 'ಈ "our BPE ಸಂಕ್ಷಿಪ್ತವಾಗಿ ಗೆಲ್ಲುತ್ತದೆ" ಶೋಧನೆ tokenizer evaluation ಬಗ್ಗೆ ಯಾವ ವಿಶಾಲ ಪಾಠ ಕಲಿಸುತ್ತದೆ?',
        opts: ['Small tokenizers are always better', 'A single example resembling the training corpus can produce a deeply misleading, overfit-driven result', 'tiktoken should not be trusted', 'Compression ratio should never be measured'], correct: 1,
        optsKn: ['ಚಿಕ್ಕ tokenizers ಯಾವಾಗಲೂ ಉತ್ತಮ', 'Training corpus ಗೆ ಹೋಲುವ ಒಂದೂ single ಉದಾಹರಣೆ ಒಂದೂ ಆಳವಾಗಿ ದಾರಿತಪ್ಪಿಸುವ, overfit-ಚಾಲಿತ ಫಲಿತಾಂಶ ಉತ್ಪಾದಿಸಬಹುದು', 'tiktoken ನಂಬಬಾರದು', 'Compression ratio ಎಂದಿಗೂ ಅಳೆಯಬಾರದು'] },
    ] } },
  ],
};
