const phaseId = '6a369d5c66020ed05b32143f'; // Phase 14: LLM Engineering
const moduleId = '6a369d5c66020ed05b321442'; // Module 208: Prompt Engineering: Techniques and Patterns

module.exports = {
  phaseId,
  moduleId,
  order: 0,
  type: 'interactive',
  duration: 40,
  difficulty: 'advanced',
  status: 'published',
  title: 'Prompt Engineering — Part 1: Foundations, Prompt Anatomy, and Prompt Patterns',
  titleKn: 'Prompt Engineering — ಭಾಗ 1: Foundations, Prompt Anatomy, ಮತ್ತು Prompt Patterns',
  desc: 'Genuinely compute how temperature reshapes a softmax distribution and how top-p nucleus sampling selects a candidate pool, genuinely build and render the PROMPT_PATTERNS dictionary with real .format() calls, and confirm why JSON braces inside a substituted value never break template rendering.',
  descKn: "Temperature ಒಂದೂ softmax distribution ಅನ್ನೂ ಹೇಗೆ ಮರುರೂಪಿಸುತ್ತದೆ ಮತ್ತೆ top-p nucleus sampling ಒಂದೂ candidate pool ಅನ್ನೂ ಹೇಗೆ ಆಯ್ಕೆ ಮಾಡುತ್ತದೆ ಎಂದೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಿ, PROMPT_PATTERNS dictionary ಅನ್ನೂ ನಿಜ .format() ಕರೆಗಳ ಜೊತೆ ನಿಜವಾಗಿ ನಿರ್ಮಿಸಿ ರೆಂಡರ್ ಮಾಡಿ, ಮತ್ತೆ ಒಂದೂ substituted value ಒಳಗಿನ JSON braces ಎಂದಿಗೂ template rendering ಮುರಿಯುವುದಿಲ್ಲ ಎಂದೂ ದೃಢಪಡಿಸಿ.",
  objectives: [
    'Explain prompting as reducing the valid output space: Prompt = Role + Context + Constraints + Output Format.',
    'Distinguish system, user, and assistant-prefill roles in an LLM interaction, and explain why prefill changes the generation distribution.',
    'Genuinely compute how temperature reshapes a softmax token distribution, confirming it sharpens at low T and flattens at high T.',
    'Genuinely compute a top-p nucleus example, confirming which tokens are included in the sampling pool at p=0.80.',
    'Explain why more context is not automatically better, genuinely computing signal-to-noise ratios for two example prompts.',
    'Genuinely build and render the PROMPT_PATTERNS registry, confirming missing-variable failures and that JSON braces inside a value never interfere with template rendering.',
  ],
  objectivesKn: [
    'Prompting ಅನ್ನೂ valid output space ಕಡಿಮೆ ಮಾಡುವುದೂ ಆಗಿ ವಿವರಿಸಿ: Prompt = Role + Context + Constraints + Output Format.',
    'Ondu LLM interaction ನಲ್ಲಿ system, user, ಮತ್ತೆ assistant-prefill ಪಾತ್ರಗಳನ್ನೂ ಪ್ರತ್ಯೇಕಿಸಿ, ಮತ್ತೆ prefill generation distribution ಅನ್ನೂ ಏಕೆ ಬದಲಾಯಿಸುತ್ತದೆ ಎಂದೂ ವಿವರಿಸಿ.',
    'Temperature ಒಂದೂ softmax token distribution ಅನ್ನೂ ಹೇಗೆ ಮರುರೂಪಿಸುತ್ತದೆ ಎಂದೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಿ, ಕಡಿಮೆ T ನಲ್ಲಿ ಇದೂ ಚೂಪಾಗುತ್ತದೆ ಮತ್ತೆ ಹೆಚ್ಚೂ T ನಲ್ಲಿ ಚಪ್ಪಟೆಯಾಗುತ್ತದೆ ಎಂದೂ ದೃಢಪಡಿಸಿ.',
    'Ondu top-p nucleus ಉದಾಹರಣೆಯನ್ನೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಿ, p=0.80 ನಲ್ಲಿ sampling pool ನಲ್ಲಿ ಯಾವ tokens ಸೇರಿಸಲಾಗಿದೆ ಎಂದೂ ದೃಢಪಡಿಸಿ.',
    'ಹೆಚ್ಚೂ context ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಉತ್ತಮ ಅಲ್ಲ ಎಂದೂ ವಿವರಿಸಿ, ಎರಡೂ ಉದಾಹರಣೆ prompts ಗಾಗಿ signal-to-noise ratios ಅನ್ನೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಿ.',
    'PROMPT_PATTERNS registry ಅನ್ನೂ ನಿಜವಾಗಿ ನಿರ್ಮಿಸಿ ರೆಂಡರ್ ಮಾಡಿ, missing-variable failures ಮತ್ತೆ ಒಂದೂ value ಒಳಗಿನ JSON braces ಎಂದಿಗೂ template rendering ಗೆ ಅಡ್ಡಿಪಡಿಸುವುದಿಲ್ಲ ಎಂದೂ ದೃಢಪಡಿಸಿ.',
  ],
  blocks: [
    { type: 'heading', data: { textEn: 'Prompt Engineering — Part 1: Foundations, Prompt Anatomy, and Prompt Patterns', textKn: 'Prompt Engineering — ಭಾಗ 1: Foundations, Prompt Anatomy, ಮತ್ತು Prompt Patterns', level: 'H1' } },
    { type: 'concept', data: {
      headingEn: 'Lesson Info', headingKn: 'ಪಾಠದ ಮಾಹಿತಿ',
      bodyEn: '• Type: Build · Language: Python · Prerequisite: Module 190 (Instruction Tuning), Module 196 (Inference Optimization) · Time: ~40 minutes · Part 1 of 3',
      bodyKn: '• ಪ್ರಕಾರ: Build · ಭಾಷೆ: Python · ಪೂರ್ವಾಪೇಕ್ಷಿತ: Module 190, Module 196 · ಸಮಯ: ~40 ನಿಮಿಷಗಳು · ಭಾಗ 1 ರಲ್ಲಿ 3',
      pillsEn: 'Prompt Engineering,Role Prompting,Temperature,Top-p,Prompt Patterns,Part 1 of 3',
      pillsKn: 'Prompt Engineering,Temperature,Top-p,Part 1 of 3' } },

    { type: 'heading', data: { textEn: 'Prompting as Search-Space Reduction', textKn: 'Search-Space Reduction ಆಗಿ Prompting', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'A Vague Prompt Leaves Many Interpretations; a Precise One Narrows Them', headingKn: 'ಒಂದು Vague Prompt ಬಹು Interpretations ಬಿಡುತ್ತದೆ; ಒಂದು Precise Prompt ಅವುಗಳನ್ನು ಕಿರಿದುಗೊಳಿಸುತ್ತದೆ',
      bodyEn: 'The model generates from P(y|x) where x is the prompt and y is a possible response. "Write a marketing email" leaves a huge set of plausible y (formal/casual, 50 or 800 words, consumer or B2B, aggressive sales copy or newsletter -- the model must guess). Adding role, audience, product, tone, length, a required metric, a required CTA, and an explicit exclusion shrinks the valid response space: |Y_precise| << |Y_vague|. The mental model the whole module builds on: Prompt = Role + Context + Constraints + Output Format -- each component targets a different kind of uncertainty (who the model should behave like, what information it needs, what may/may not happen, how the answer should be represented).',
      bodyKn: 'Model x prompt ಮತ್ತೆ y ಒಂದೂ ಸಂಭವನೀಯ response ಇರುವ P(y|x) ಇಂದ ಉತ್ಪಾದಿಸುತ್ತದೆ. "Write a marketing email" ಒಂದೂ ಬೃಹತ್ ಸಂಭವನೀಯ y set ಬಿಡುತ್ತದೆ (formal/casual, 50 ಅಥವಾ 800 words, consumer ಅಥವಾ B2B, ಆಕ್ರಮಣಕಾರಿ sales copy ಅಥವಾ newsletter -- model ಊಹಿಸಬೇಕು). Role, audience, product, tone, length, ಒಂದೂ ಅಗತ್ಯ metric, ಒಂದೂ ಅಗತ್ಯ CTA, ಮತ್ತೆ ಒಂದೂ ಸ್ಪಷ್ಟ exclusion ಸೇರಿಸುವುದೂ valid response space ಅನ್ನೂ ಕುಗ್ಗಿಸುತ್ತದೆ: |Y_precise| << |Y_vague|. ಇಡೀ module ನಿರ್ಮಿಸುವ mental model: Prompt = Role + Context + Constraints + Output Format -- ಪ್ರತಿ component ಭಿನ್ನ ರೀತಿಯ uncertainty ಗುರಿಪಡಿಸುತ್ತದೆ (model ಯಾರಂತೆ ವರ್ತಿಸಬೇಕು, ಅದೂ ಗೆ ಯಾವ ಮಾಹಿತಿ ಬೇಕು, ಏನೂ ಆಗಬಹುದು/ಆಗಬಾರದೂ, ಉತ್ತರ ಹೇಗೆ ಪ್ರತಿನಿಧಿಸಬೇಕು).' } },

    { type: 'heading', data: { textEn: 'Anatomy of an LLM Prompt: System, User, Assistant Prefill', textKn: 'ಒಂದು LLM Prompt ಯ Anatomy: System, User, Assistant Prefill', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'Three Roles, Different Responsibilities', headingKn: 'ಮೂರು ಪಾತ್ರಗಳು, ಭಿನ್ನ ಜವಾಬ್ದಾರಿಗಳು',
      bodyEn: 'System message sets identity, rules, and constraints -- relatively persistent policy that continues applying across multiple user turns. User message contains the current task. Assistant prefill begins the assistant\'s response with initial tokens so generation continues from a desired structure -- e.g. seeding the response with just "{" so the model continues INSIDE a JSON object rather than starting with "Sure! Here is the information you requested:". Mathematically this changes P(y_1|x) into P(y_k|x,y_1,...,y_{k-1}) since the first few output tokens are already supplied -- this is why prefill can strongly influence formatting even without an explicit format instruction.',
      bodyKn: 'System message identity, rules, ಮತ್ತೆ constraints ಸ್ಥಾಪಿಸುತ್ತದೆ -- ಸಾಪೇಕ್ಷವಾಗಿ ಸ್ಥಿರ policy ಇದೂ ಬಹು user turns ಗಳಾದ್ಯಂತ ಅನ್ವಯಿಸುತ್ತಲೇ ಇರುತ್ತದೆ. User message ಪ್ರಸ್ತುತ task ಒಳಗೊಂಡಿದೆ. Assistant prefill assistant ya response ಅನ್ನೂ ಆರಂಭಿಕ tokens ಜೊತೆ ಆರಂಭಿಸುತ್ತದೆ ಆದ್ದರಿಂದ generation ಒಂದೂ ಬಯಸಿದ structure ಇಂದ ಮುಂದುವರಿಯುತ್ತದೆ -- ಉದಾ. ಕೇವಲ "{" ಜೊತೆ response seed ಮಾಡುವುದೂ ಆದ್ದರಿಂದ model "Sure! Here is the information you requested:" ಜೊತೆ ಆರಂಭಿಸುವ ಬದಲಿಗೆ JSON object ಒಳಗೆ ಮುಂದುವರಿಯುತ್ತದೆ. ಗಣಿತೀಯವಾಗಿ ಇದೂ P(y_1|x) ಅನ್ನೂ P(y_k|x,y_1,...,y_{k-1}) ಆಗಿ ಬದಲಾಯಿಸುತ್ತದೆ ಏಕೆಂದರೆ ಮೊದಲೂ ಕೆಲವೂ output tokens ಈಗಾಗಲೇ ಒದಗಿಸಲಾಗಿದೆ -- ಸ್ಪಷ್ಟ format instruction ಇಲ್ಲದೆಯೂ prefill formatting ಮೇಲೆ ಬಲವಾಗಿ ಪ್ರಭಾವ ಬೀರಬಹುದೂ ಎಂಬುದೂ ಗೆ ಇದೇ ಕಾರಣ.' } },

    { type: 'heading', data: { textEn: 'Genuinely Computing How Temperature Reshapes Probabilities', textKn: 'Temperature Probabilities ಅನ್ನು ಹೇಗೆ ಮರುರೂಪಿಸುತ್ತದೆ ಎಂದು ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕುವುದು', level: 'H2' } },
    { type: 'math', data: {
      equation: 'P(i) = \\frac{e^{z_i/T}}{\\sum_j e^{z_j/T}}',
      captionEn: 'Temperature T divides logits before softmax -- lower T sharpens the distribution toward the highest-logit token, higher T flattens it toward uniform.',
      captionKn: 'Temperature T softmax ಮೊದಲೂ logits ಅನ್ನೂ ಭಾಗಿಸುತ್ತದೆ -- ಕಡಿಮೆ T distribution ಅನ್ನೂ ಅತ್ಯುನ್ನತ-logit token ಕಡೆಗೆ ಚೂಪಾಗಿಸುತ್ತದೆ, ಹೆಚ್ಚೂ T ಇದನ್ನೂ uniform ಕಡೆಗೆ ಚಪ್ಪಟೆಯಾಗಿಸುತ್ತದೆ.' } },
    { type: 'code', data: {
      filename: 'temperature_softmax.py', headingEn: 'Genuinely computing softmax at three temperatures for the same logits', headingKn: 'ಅದೇ logits ಗಾಗಿ ಮೂರೂ temperatures ನಲ್ಲಿ softmax ಅನ್ನೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕುವುದೂ',
      descEn: 'For five candidate tokens with fixed logits, compute the resulting probability distribution at low (T=0.3), neutral (T=1.0), and high (T=2.0) temperature.',
      descKn: 'Aidu candidate tokens ಗಾಗಿ ಸ್ಥಿರ logits ಜೊತೆ, ಕಡಿಮೆ (T=0.3), ತಟಸ್ಥ (T=1.0), ಮತ್ತೆ ಹೆಚ್ಚೂ (T=2.0) temperature ನಲ್ಲಿ ಫಲಿತಾಂಶ probability distribution ಲೆಕ್ಕಹಾಕಿ.',
      code: "import numpy as np\n\ndef softmax(logits, T=1.0):\n    z = np.array(logits) / T\n    z = z - z.max()\n    e = np.exp(z)\n    return e / e.sum()\n\nlogits = [2.0, 1.0, 0.5, 0.2, -0.5]\nlabels = ['Python', 'Java', 'C++', 'Rust', 'banana']\n\nfor T in [0.3, 1.0, 2.0]:\n    probs = softmax(logits, T)\n    rounded = {l: round(float(p), 4) for l, p in zip(labels, probs)}\n    print(f'T={T}: {rounded}')" } },
    { type: 'output', data: { output: "T=0.3: {'Python': 0.9568, 'Java': 0.0341, 'C++': 0.0064, 'Rust': 0.0024, 'banana': 0.0002}\nT=1.0: {'Python': 0.544, 'Java': 0.2001, 'C++': 0.1214, 'Rust': 0.0899, 'banana': 0.0447}\nT=2.0: {'Python': 0.3608, 'Java': 0.2188, 'C++': 0.1704, 'Rust': 0.1467, 'banana': 0.1034}" } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: T=0.3 Nearly Collapses to One Token, T=2.0 Nearly Flattens', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: T=0.3 Bahutēka Ondu Token Ge Kucchikolluttade, T=2.0 Bahutēka Chappateyaguttade',
      bodyEn: 'Genuinely computed: at T=0.3, "Python" captures 95.68% of the probability mass (nearly deterministic); at T=1.0 the same logits give a more moderate 54.4%; at T=2.0 "Python" drops to just 36.08%, with "banana" -- the least likely token at T=0.3 (0.02%) -- rising to a real 10.34% chance. This genuinely confirms the source\'s qualitative table: low temperature suits classification/extraction/structured tasks (consistency matters), high temperature suits brainstorming/creative writing (diversity matters) -- the same underlying logits, only the sharpness of the resulting distribution changes.',
      bodyKn: 'Nijavagi ಲೆಕ್ಕಹಾಕಲಾಗಿದೆ: T=0.3 ನಲ್ಲಿ, "Python" probability mass ya 95.68% ಸೆರೆಹಿಡಿಯುತ್ತದೆ (ಬಹುತೇಕ deterministic); T=1.0 ನಲ್ಲಿ ಅದೇ logits ಒಂದೂ ಹೆಚ್ಚೂ ಸಾಧಾರಣ 54.4% ನೀಡುತ್ತವೆ; T=2.0 ನಲ್ಲಿ "Python" ಕೇವಲ 36.08% ಗೆ ಇಳಿಯುತ್ತದೆ, "banana" -- T=0.3 ನಲ್ಲಿ ಅತ್ಯಂತ ಕಡಿಮೆ ಸಂಭವನೀಯ token (0.02%) -- ಒಂದೂ ನಿಜ 10.34% ಸಾಧ್ಯತೆಗೆ ಏರುತ್ತದೆ. ಇದೂ source ya ಗುಣಾತ್ಮಕ table ಅನ್ನೂ ನಿಜವಾಗಿ ದೃಢಪಡಿಸುತ್ತದೆ: ಕಡಿಮೆ temperature classification/extraction/structured tasks ಗೆ ಸೂಕ್ತ (consistency ಮುಖ್ಯ), ಹೆಚ್ಚೂ temperature brainstorming/creative writing ಗೆ ಸೂಕ್ತ (diversity ಮುಖ್ಯ) -- ಅದೇ ಆಧಾರವಾಗಿರುವ logits, ಫಲಿತಾಂಶ distribution ya ಚೂಪುತನ ಮಾತ್ರ ಬದಲಾಗುತ್ತದೆ.' } },

    { type: 'heading', data: { textEn: 'Genuinely Computing Top-p Nucleus Sampling', textKn: 'Top-p Nucleus Sampling ಅನ್ನೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕುವುದೂ', level: 'H2' } },
    { type: 'code', data: {
      filename: 'top_p_nucleus.py', headingEn: 'Genuinely computing the top-p=0.80 candidate pool for the lesson\'s six-token example', headingKn: 'Lesson ya ಆರೂ-token ಉದಾಹರಣೆಗೆ top-p=0.80 candidate pool ಅನ್ನೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕುವುದೂ',
      descEn: 'For six sorted token probabilities, accumulate probability mass until reaching the p=0.80 threshold and confirm exactly which tokens make it into the nucleus.',
      descKn: 'Aaru sorted token probabilities ಗಾಗಿ, p=0.80 threshold ತಲುಪುವವರೆಗೆ probability mass ಸಂಗ್ರಹಿಸಿ ಮತ್ತೆ ನಿಖರವಾಗಿ ಯಾವ tokens nucleus ಗೆ ಸೇರುತ್ತವೆ ಎಂದೂ ದೃಢಪಡಿಸಿ.',
      code: "probs = {'A': 0.40, 'B': 0.25, 'C': 0.15, 'D': 0.10, 'E': 0.06, 'F': 0.04}\nprint('sum of all probs:', sum(probs.values()))\n\np_threshold = 0.80\nnucleus, cum = [], 0.0\nfor tok, p in probs.items():\n    if cum >= p_threshold:\n        break\n    cum += p\n    nucleus.append(tok)\n\nprint(f'nucleus at p={p_threshold}: {nucleus}, cumulative={cum:.2f}')" } },
    { type: 'output', data: { output: "sum of all probs: 1.0\nnucleus at p=0.80: ['A', 'B', 'C'], cumulative=0.80" } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: The Tail (D, E, F = 20% of mass) Is Excluded From Sampling', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: Bala (D, E, F = 20% Mass) Sampling Inda Horagide',
      bodyEn: 'Genuinely computed the nucleus is exactly {A, B, C}, with cumulative mass reaching precisely 0.80 -- confirming the source\'s worked example exactly. Temperature and top-p work differently: temperature RESHAPES the whole distribution (every token\'s probability changes, genuinely shown above), while top-p CUTS OFF the low-probability tail (tokens D/E/F are removed from the pool entirely, not merely made less likely) -- reshape then select is the conceptual pipeline: temperature first, then top-p narrows the surviving candidates. The source recommends adjusting one at a time rather than aggressively tuning both simultaneously, since their combined effect is harder to reason about.',
      bodyKn: 'Nijavagi ಲೆಕ್ಕಹಾಕಲಾಗಿದೆ nucleus ನಿಖರವಾಗಿ {A, B, C}, cumulative mass ನಿಖರವಾಗಿ 0.80 ತಲುಪುತ್ತದೆ -- source ya worked example ಅನ್ನೂ ನಿಖರವಾಗಿ ದೃಢಪಡಿಸುತ್ತದೆ. Temperature ಮತ್ತೆ top-p ಭಿನ್ನವಾಗಿ ಕೆಲಸ ಮಾಡುತ್ತವೆ: temperature ಇಡೀ distribution ಅನ್ನೂ RESHAPE ಮಾಡುತ್ತದೆ (ಪ್ರತಿ token ya probability ಬದಲಾಗುತ್ತದೆ, ಮೇಲೆ ನಿಜವಾಗಿ ತೋರಿಸಲಾಗಿದೆ), ಆದರೆ top-p ಕಡಿಮೆ-probability ಬಾಲ CUTS OFF ಮಾಡುತ್ತದೆ (tokens D/E/F pool ಇಂದ ಸಂಪೂರ್ಣವಾಗಿ ತೆಗೆದುಹಾಕಲಾಗಿದೆ, ಕೇವಲ ಕಡಿಮೆ ಸಂಭವನೀಯ ಮಾಡಲಾಗಿಲ್ಲ) -- reshape ನಂತರ select ಪರಿಕಲ್ಪನಾತ್ಮಕ pipeline: ಮೊದಲೂ temperature, ನಂತರ top-p ಉಳಿದುಕೊಂಡ candidates ಕಿರಿದುಗೊಳಿಸುತ್ತದೆ. Source ಎರಡನ್ನೂ ಆಕ್ರಮಣಕಾರಿಯಾಗಿ ಒಟ್ಟಿಗೆ ಟ್ಯೂನ್ ಮಾಡುವ ಬದಲಿಗೆ ಒಂದೂ ಸಮಯದಲ್ಲಿ ಒಂದನ್ನೂ ಹೊಂದಿಸಲು ಶಿಫಾರಸು ಮಾಡುತ್ತದೆ, ಅವುಗಳ ಸಂಯೋಜಿತ ಪರಿಣಾಮ ತಾರ್ಕಿಕವಾಗಿ ಗ್ರಹಿಸಲು ಕಷ್ಟ.' } },

    { type: 'heading', data: { textEn: 'Context Window: More Context Is Not Automatically Better', textKn: 'Context Window: ಹೆಚ್ಚು Context ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಉತ್ತಮ ಅಲ್ಲ', level: 'H2' } },
    { type: 'code', data: {
      filename: 'signal_ratio.py', headingEn: 'Genuinely computing the signal-to-noise ratio for two example prompts', headingKn: 'Erdu ಉದಾಹರಣೆ prompts ಗಾಗಿ signal-to-noise ratio ಅನ್ನೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕುವುದೂ',
      descEn: 'Prompt A has 10,000 tokens with 9,000 useful; Prompt B has 100,000 tokens with 10,000 useful (more total useful content, but more total tokens too). Compute the signal ratio for each.',
      descKn: 'Prompt A ಗೆ 10,000 tokens 9,000 ಉಪಯುಕ್ತ; Prompt B ಗೆ 100,000 tokens 10,000 ಉಪಯುಕ್ತ (ಹೆಚ್ಚೂ ಒಟ್ಟೂ ಉಪಯುಕ್ತ content, ಆದರೆ ಹೆಚ್ಚೂ ಒಟ್ಟೂ tokens ಕೂಡ). ಪ್ರತಿಯೊಂದೂ ಗಾಗಿ signal ratio ಲೆಕ್ಕಹಾಕಿ.',
      code: "prompt_a = {'total': 10_000, 'useful': 9_000}\nprompt_b = {'total': 100_000, 'useful': 10_000}\n\nfor name, p in [('Prompt A', prompt_a), ('Prompt B', prompt_b)]:\n    ratio = p['useful'] / p['total']\n    print(f\"{name}: {p['useful']}/{p['total']} useful = {ratio:.2%} signal ratio\")" } },
    { type: 'output', data: { output: 'Prompt A: 9000/10000 useful = 90.00% signal ratio\nPrompt B: 10000/100000 useful = 10.00% signal ratio' } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: Prompt B Has More Total Useful Content but a Far Worse Signal Ratio', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: Prompt B Ge Hecchu Total Useful Content Ide Adare Bahala Ketta Signal Ratio',
      bodyEn: 'Genuinely computed Prompt A has 90% signal versus Prompt B\'s 10% -- even though Prompt B contains MORE useful tokens in absolute terms (10,000 vs 9,000). This is the concrete numeric basis for the source\'s distinction between prompt engineering (crafting the wording of what enters context) and the broader problem of context engineering (deciding what should enter the model\'s working context in the first place) -- dumping in more retrieved documents or history is not free, since irrelevant tokens dilute the signal the model must find, everything competing for a finite context budget (system instructions, conversation history, user query, few-shot examples, retrieved documents, tool results, and the generated continuation itself).',
      bodyKn: 'Nijavagi ಲೆಕ್ಕಹಾಕಲಾಗಿದೆ Prompt A ಗೆ 90% signal ಇದೆ Prompt B ya 10% ಎದುರೂ -- Prompt B ಸಂಪೂರ್ಣ ಪದಗಳಲ್ಲಿ ಹೆಚ್ಚೂ ಉಪಯುಕ್ತ tokens ಒಳಗೊಂಡಿದ್ದರೂ (10,000 vs 9,000). ಇದೂ prompt engineering (context ಗೆ ಏನೂ ಪ್ರವೇಶಿಸುತ್ತದೆ ಎಂಬುದೂ ya ಪದಗಳನ್ನೂ ರೂಪಿಸುವುದೂ) ಮತ್ತೆ context engineering ya ವಿಶಾಲ ಸಮಸ್ಯೆ (model ya working context ಗೆ ಮೊದಲೂ ಏನೂ ಪ್ರವೇಶಿಸಬೇಕು ಎಂದೂ ನಿರ್ಧರಿಸುವುದೂ) ನಡುವಿನ source ya ವ್ಯತ್ಯಾಸಕ್ಕೆ ನಿರ್ದಿಷ್ಟ numeric ಆಧಾರ -- ಹೆಚ್ಚೂ retrieved documents ಅಥವಾ history ಸುರಿಯುವುದೂ ಉಚಿತ ಅಲ್ಲ, ಅಪ್ರಸ್ತುತ tokens model ಕಂಡುಹಿಡಿಯಬೇಕಾದ signal ಅನ್ನೂ ದುರ್ಬಲಗೊಳಿಸುತ್ತವೆ, ಎಲ್ಲವೂ ಒಂದೂ ಸೀಮಿತ context budget ಗಾಗಿ ಸ್ಪರ್ಧಿಸುತ್ತವೆ (system instructions, conversation history, user query, few-shot examples, retrieved documents, tool results, ಮತ್ತೆ ಉತ್ಪಾದಿಸಿದ continuation ಸ್ವತಃ).' } },

    { type: 'heading', data: { textEn: 'Constraints as a Program: Negative, Positive, Conditional', textKn: 'ಒಂದು Program ಆಗಿ Constraints: Negative, Positive, Conditional', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'Prompts Can Express Branching Logic in Natural Language', headingKn: 'Prompts ಸ್ವಾಭಾವಿಕ ಭಾಷೆಯಲ್ಲಿ Branching Logic ವ್ಯಕ್ತಪಡಿಸಬಹುದು',
      bodyEn: 'Negative constraints specify forbidden output regions ("Do NOT include code," "Do NOT exceed 200 words"). Positive constraints specify required behavior ("Always include one example," "Always cite the document"). Conditional constraints act almost like program branches ("If information is unavailable, say Unknown," "If the input contains code, perform a code review") -- structurally identical to if/else in ordinary code (if unsupported: return "Unknown"). This "prompt as a program" analogy is genuinely useful: you are defining inputs, state, constraints, branches, expected output, and error handling in natural language instead of a programming language.',
      bodyKn: 'Negative constraints ನಿಷೇಧಿತ output ಪ್ರದೇಶಗಳನ್ನೂ ನಿರ್ದಿಷ್ಟಪಡಿಸುತ್ತವೆ ("Do NOT include code," "Do NOT exceed 200 words"). Positive constraints ಅಗತ್ಯ ವರ್ತನೆ ನಿರ್ದಿಷ್ಟಪಡಿಸುತ್ತವೆ ("Always include one example," "Always cite the document"). Conditional constraints ಬಹುತೇಕ program branches ನಂತೆ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತವೆ ("If information is unavailable, say Unknown," "If the input contains code, perform a code review") -- ಸಾಮಾನ್ಯ code ನಲ್ಲಿ if/else ಗೆ ರಚನಾತ್ಮಕವಾಗಿ ಒಂದೇ (if unsupported: return "Unknown"). ಈ "prompt as a program" ಸಾದೃಶ್ಯ ನಿಜವಾಗಿ ಉಪಯುಕ್ತ: ನೀವೂ inputs, state, constraints, branches, expected output, ಮತ್ತೆ error handling ಅನ್ನೂ ಒಂದೂ programming language ಬದಲಿಗೆ ಸ್ವಾಭಾವಿಕ ಭಾಷೆಯಲ್ಲಿ ವ್ಯಾಖ್ಯಾನಿಸುತ್ತಿದ್ದೀರಿ.' } },

    { type: 'heading', data: { textEn: 'Ten Reusable Prompt Patterns', textKn: 'ಹತ್ತು ಮರುಬಳಕೆಯೋಗ್ಯ Prompt Patterns', level: 'H2' } },
    { type: 'table', data: {
      captionEn: 'The Ten Patterns and Their Purpose', captionKn: 'ಹತ್ತು Patterns ಮತ್ತು ಅವುಗಳ ಉದ್ದೇಶ',
      rows: "Pattern|Main purpose\nPersona|Establish domain role/style\nFew-shot|Teach with examples\nChain-of-thought|Structure multi-step reasoning\nTemplate fill|Force named fields\nCritique|Generate -> evaluate -> improve\nGuardrail|Define behavioral boundaries\nMeta-prompt|Generate another prompt\nDecomposition|Split complex problems\nAudience adaptation|Change depth/style\nBoundary|Restrict domain scope" } },
    { type: 'concept', data: {
      headingEn: 'Patterns Are Compositional, Not Mutually Exclusive', headingKn: 'Patterns Compositional, Mutually Exclusive ಅಲ್ಲ',
      bodyEn: 'A single production prompt often combines several: a medical-document extraction pipeline might stack Role + Boundary + Guardrail + Few-shot + Template all together (role: "document extraction engine"; boundary: "only extract information explicitly present"; guardrail: "never infer missing values"; few-shot: worked examples; template: a fixed output schema). Two patterns deserve special attention: meta-prompting uses a model to construct a better prompt (instead of directly asking "Analyze customer feedback," you ask an LLM to "Write an LLM prompt for analyzing customer feedback" including role/constraints/schema/examples/edge cases -- the output is not the analysis, it is a prompt that PERFORMS the analysis, a two-level architecture: Human objective -> Meta-prompt -> LLM -> Generated prompt -> Another LLM call -> Actual task result). Decomposition breaks a difficult problem into subproblems solved independently, then combined and verified, rather than forcing one undifferentiated operation.',
      bodyKn: 'Ondu ಒಂಟಿ production prompt ಆಗಾಗ್ಗೆ ಹಲವೂ ಸಂಯೋಜಿಸುತ್ತದೆ: ಒಂದೂ medical-document extraction pipeline Role + Boundary + Guardrail + Few-shot + Template ಎಲ್ಲಾ ಒಟ್ಟಿಗೆ ಸ್ಟ್ಯಾಕ್ ಮಾಡಬಹುದು (role: "document extraction engine"; boundary: "only extract information explicitly present"; guardrail: "never infer missing values"; few-shot: worked examples; template: ಒಂದೂ ಸ್ಥಿರ output schema). Erdu patterns ವಿಶೇಷ ಗಮನಕ್ಕೆ ಯೋಗ್ಯ: meta-prompting ಒಂದೂ ಉತ್ತಮ prompt ನಿರ್ಮಿಸಲು ಒಂದೂ model ಬಳಸುತ್ತದೆ (ನೇರವಾಗಿ "Analyze customer feedback" ಕೇಳುವ ಬದಲಿಗೆ, ನೀವೂ ಒಂದೂ LLM ಗೆ role/constraints/schema/examples/edge cases ಸೇರಿ "Write an LLM prompt for analyzing customer feedback" ಕೇಳುತ್ತೀರಿ -- output ವಿಶ್ಲೇಷಣೆ ಅಲ್ಲ, ಇದೂ ವಿಶ್ಲೇಷಣೆ PERFORM ಮಾಡುವ ಒಂದೂ prompt, ಒಂದೂ ಎರಡೂ-ಹಂತದ architecture: Human objective -> Meta-prompt -> LLM -> Generated prompt -> Innondu LLM call -> Nija task result). Decomposition ಒಂದೂ ಕಷ್ಟಕರ ಸಮಸ್ಯೆಯನ್ನೂ ಸ್ವತಂತ್ರವಾಗಿ ಬಗೆಹರಿಸಿದ subproblems ಗೆ ವಿಭಜಿಸುತ್ತದೆ, ನಂತರ ಸಂಯೋಜಿಸಿ ಪರಿಶೀಲಿಸುತ್ತದೆ, ಒಂದೂ ಅವಿಭಜಿತ operation ಆಗಿ ಒತ್ತಾಯಿಸುವ ಬದಲಿಗೆ.' } },

    { type: 'heading', data: { textEn: 'Genuinely Building and Rendering PROMPT_PATTERNS', textKn: 'PROMPT_PATTERNS ಅನ್ನೂ ನಿಜವಾಗಿ ನಿರ್ಮಿಸಿ ರೆಂಡರ್ ಮಾಡುವುದೂ', level: 'H2' } },
    { type: 'code', data: {
      filename: 'prompt_patterns.py', headingEn: 'Genuinely building two pattern entries and rendering the persona template', headingKn: 'Erdu pattern entries ಅನ್ನೂ ನಿಜವಾಗಿ ನಿರ್ಮಿಸಿ persona template ಅನ್ನೂ ರೆಂಡರ್ ಮಾಡುವುದೂ',
      descEn: 'Build the persona and few_shot entries from the source\'s PROMPT_PATTERNS dictionary exactly as specified, then genuinely render the persona template with real variable values.',
      descKn: "Source ya PROMPT_PATTERNS dictionary ಇಂದ persona ಮತ್ತೆ few_shot entries ಅನ್ನೂ ನಿಖರವಾಗಿ ನಿರ್ದಿಷ್ಟಪಡಿಸಿದಂತೆ ನಿರ್ಮಿಸಿ, ನಂತರ ನಿಜ variable values ಜೊತೆ persona template ಅನ್ನೂ ನಿಜವಾಗಿ ರೆಂಡರ್ ಮಾಡಿ.",
      code: "PROMPT_PATTERNS = {\n    'persona': {\n        'name': 'Persona Pattern',\n        'template': (\n            'You are {role} with {experience}.\\n'\n            'Your communication style is {style}.\\n'\n            'You prioritize {priority}.\\n\\n'\n            '{task}'\n        ),\n        'variables': ['role', 'experience', 'style', 'priority', 'task'],\n        'temperature': 0.7,\n        'description': \"Activates a specific expert distribution in the model's training data\",\n    },\n}\n\nvariables = {\n    'role': 'a senior ML engineer',\n    'experience': '10 years building recommendation systems',\n    'style': 'precise and practical',\n    'priority': 'correctness over cleverness',\n    'task': 'Explain embedding tables.',\n}\n\nrendered = PROMPT_PATTERNS['persona']['template'].format(**variables)\nprint(rendered)" } },
    { type: 'output', data: { output: 'You are a senior ML engineer with 10 years building recommendation systems.\nYour communication style is precise and practical.\nYou prioritize correctness over cleverness.\n\nExplain embedding tables.' } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: A Pattern Is Template + Variables + SamplingConfig + Metadata', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: Ondu Pattern = Template + Variables + SamplingConfig + Metadata',
      bodyEn: 'Genuinely rendered the exact source template with real values and confirmed the output matches the source\'s worked example precisely. The dictionary schema (name, template, variables, temperature, description) is what makes a prompt a structured object rather than a raw string -- notice the "variables" list is not used by .format() itself, it exists purely for validation, letting later code check required inputs BEFORE attempting to render, rather than discovering a missing field only when .format() throws a KeyError deep in the pipeline (genuinely demonstrated next).',
      bodyKn: 'Nija values ಜೊತೆ ನಿಖರ source template ಅನ್ನೂ ನಿಜವಾಗಿ ರೆಂಡರ್ ಮಾಡಲಾಗಿದೆ ಮತ್ತೆ output source ya worked example ಗೆ ನಿಖರವಾಗಿ ಹೊಂದಿಕೆಯಾಗುತ್ತದೆ ಎಂದೂ ದೃಢಪಡಿಸಲಾಗಿದೆ. Dictionary schema (name, template, variables, temperature, description) ಒಂದೂ prompt ಅನ್ನೂ ಒಂದೂ ಕಚ್ಚಾ string ಬದಲಿಗೆ ಒಂದೂ structured object ಆಗಿ ಮಾಡುತ್ತದೆ -- "variables" list .format() ಸ್ವತಃ ಬಳಸುವುದಿಲ್ಲ ಎಂದೂ ಗಮನಿಸಿ, ಇದೂ ಶುದ್ಧವಾಗಿ validation ಗಾಗಿ ಅಸ್ತಿತ್ವದಲ್ಲಿದೆ, ನಂತರದ code ಅಗತ್ಯ inputs ಅನ್ನೂ ರೆಂಡರ್ ಮಾಡುವ ಮೊದಲೂ ಪರಿಶೀಲಿಸಲು ಬಿಡುತ್ತದೆ, pipeline ನಲ್ಲಿ ಆಳವಾಗಿ .format() ಒಂದೂ KeyError ಎಸೆದಾಗ ಮಾತ್ರ ಒಂದೂ ಕಾಣೆಯಾದ field ಕಂಡುಹಿಡಿಯುವ ಬದಲಿಗೆ (ಮುಂದೆ ನಿಜವಾಗಿ ಪ್ರದರ್ಶಿಸಲಾಗಿದೆ).' } },

    { type: 'code', data: {
      filename: 'missing_variable_and_json_braces.py', headingEn: 'Genuinely confirming a missing-variable failure and that JSON braces in a VALUE never break rendering', headingKn: 'Ondu missing-variable failure ಮತ್ತೆ VALUE ಒಳಗಿನ JSON braces ಎಂದಿಗೂ rendering ಮುರಿಯುವುದಿಲ್ಲ ಎಂದೂ ನಿಜವಾಗಿ ದೃಢಪಡಿಸುವುದೂ',
      descEn: 'First, attempt to render the persona template with an incomplete variables dict and confirm the exact KeyError. Second, render the few_shot template with a value that itself contains JSON braces, confirming this does NOT break .format().',
      descKn: "Modalu, ಒಂದೂ ಅಪೂರ್ಣ variables dict ಜೊತೆ persona template ರೆಂಡರ್ ಮಾಡಲು ಪ್ರಯತ್ನಿಸಿ ಮತ್ತೆ ನಿಖರ KeyError ದೃಢಪಡಿಸಿ. Erdaneyadagi, JSON braces ಸ್ವತಃ ಒಳಗೊಂಡ ಒಂದೂ value ಜೊತೆ few_shot template ರೆಂಡರ್ ಮಾಡಿ, ಇದೂ .format() ಮುರಿಯುವುದಿಲ್ಲ ಎಂದೂ ದೃಢಪಡಿಸಿ.",
      code: "persona_template = PROMPT_PATTERNS['persona']['template']\n\ntry:\n    incomplete = {'role': 'a Python instructor', 'task': 'Explain generators'}\n    persona_template.format(**incomplete)\nexcept KeyError as e:\n    print('KeyError on missing variable:', e)\n\nfew_shot_template = (\n    'Here are examples of the expected input/output format:\\n\\n'\n    '{examples}\\n\\n'\n    'Now process this input:\\n{input}'\n)\nfs_vars = {\n    'examples': 'Input: \"Great product\"\\nOutput: {\"sentiment\": \"positive\"}',\n    'input': 'Terrible customer service',\n}\nrendered = few_shot_template.format(**fs_vars)\nprint('\\nfew_shot rendered fine despite JSON braces in the value:')\nprint(rendered)" } },
    { type: 'output', data: { output: "KeyError on missing variable: 'experience'\n\nfew_shot rendered fine despite JSON braces in the value:\nHere are examples of the expected input/output format:\n\nInput: \"Great product\"\nOutput: {\"sentiment\": \"positive\"}\n\nNow process this input:\nTerrible customer service" } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: .format() Only Parses Braces in the Template String, Never Inside a Substituted Value', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: .format() Kevala Template String Nalliruva Braces Parse Maduttade, Substituted Value Olage Alla',
      bodyEn: 'Genuinely confirmed: rendering with an incomplete dict raises KeyError: \'experience\' -- exactly the failure the source\'s validation logic (covered in Part 2) is designed to catch early with a clearer message. Separately, genuinely confirmed the JSON braces {"sentiment": "positive"} inside the examples VALUE render through completely unaffected -- .format() only interprets {placeholder} syntax that is literally written in the TEMPLATE STRING, not text that arrives through a substituted argument. This is an important practical distinction Part 2 will build on: the dangerous braces are ones written directly inside a template meant to also contain literal JSON output (which need escaping as {{ }}), not JSON that flows in through a variable\'s value.',
      bodyKn: 'Nijavagi ದೃಢಪಡಿಸಲಾಗಿದೆ: ಒಂದೂ ಅಪೂರ್ಣ dict ಜೊತೆ render ಮಾಡುವುದೂ KeyError: \'experience\' ಎಸೆಯುತ್ತದೆ -- Part 2 ಒಳಗೊಂಡ source ya validation logic ಸ್ಪಷ್ಟ ಸಂದೇಶದೊಂದಿಗೆ ಮೊದಲೂ ಹಿಡಿಯಲು ವಿನ್ಯಾಸಗೊಳಿಸಿದ ವೈಫಲ್ಯ ಇದೇ ನಿಖರವಾಗಿ. ಪ್ರತ್ಯೇಕವಾಗಿ, examples VALUE ಒಳಗಿನ JSON braces {"sentiment": "positive"} ಸಂಪೂರ್ಣವಾಗಿ ಪ್ರಭಾವಿತವಾಗದೆ render ಆಗುತ್ತವೆ ಎಂದೂ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ -- .format() ಕೇವಲ TEMPLATE STRING ನಲ್ಲಿ ಅಕ್ಷರಶಃ ಬರೆದ {placeholder} syntax ಅರ್ಥೈಸುತ್ತದೆ, ಒಂದೂ substituted argument ಮೂಲಕ ಬರುವ ಪಠ್ಯ ಅಲ್ಲ. ಇದೂ Part 2 ನಿರ್ಮಿಸುವ ಒಂದೂ ಮುಖ್ಯ ಪ್ರಾಯೋಗಿಕ ವ್ಯತ್ಯಾಸ: ಅಪಾಯಕಾರಿ braces ಒಂದೂ template ಒಳಗೆ ನೇರವಾಗಿ ಬರೆದವು ಇವು literal JSON output ಕೂಡ ಒಳಗೊಳ್ಳಲು ಉದ್ದೇಶಿಸಿವೆ (ಇವುಗಳಿಗೆ {{ }} ಆಗಿ escaping ಬೇಕು), ಒಂದೂ variable ya value ಮೂಲಕ ಹರಿಯುವ JSON ಅಲ್ಲ.' } },

    { type: 'concept', data: {
      headingEn: 'Common Misconception', headingKn: 'ಸಾಮಾನ್ಯ ತಪ್ಪುಗ್ರಹಿಕೆ',
      bodyEn: '"A more elaborate role always produces a better response." No -- the source explicitly warns against decorative specificity: "You are the greatest quantum-neural-biological-blockchain architect in history" adds words but no useful evidence about depth, terminology, or domain; "You are a senior CUDA performance engineer specializing in memory-bound PyTorch kernels" is better not because it is longer, but because it names REAL relevant expertise (CUDA, PyTorch, memory profiling) the task actually requires. A good role should reduce uncertainty about P(y|x,role), not just add words to the prompt.',
      bodyKn: '"Ondu ಹೆಚ್ಚೂ ವಿಸ್ತಾರವಾದ role ಯಾವಾಗಲೂ ಒಂದೂ ಉತ್ತಮ response ಉತ್ಪಾದಿಸುತ್ತದೆ." ಇಲ್ಲ -- source ಅಲಂಕಾರಿಕ specificity ಎದುರೂ ಸ್ಪಷ್ಟವಾಗಿ ಎಚ್ಚರಿಸುತ್ತದೆ: "You are the greatest quantum-neural-biological-blockchain architect in history" ಪದಗಳನ್ನೂ ಸೇರಿಸುತ್ತದೆ ಆದರೆ depth, terminology, ಅಥವಾ domain ಬಗ್ಗೆ ಯಾವುದೇ ಉಪಯುಕ್ತ ಪುರಾವೆ ಇಲ್ಲ; "You are a senior CUDA performance engineer specializing in memory-bound PyTorch kernels" ಉತ್ತಮ ಇದೂ ಉದ್ದವಾಗಿರುವುದೂ ಇಂದ ಅಲ್ಲ, ಆದರೆ ಇದೂ task ನಿಜವಾಗಿ ಬಯಸುವ REAL ಸಂಬಂಧಿತ ಪರಿಣತಿಯನ್ನೂ (CUDA, PyTorch, memory profiling) ಹೆಸರಿಸುತ್ತದೆ ಎಂದೂ. ಒಂದೂ ಉತ್ತಮ role P(y|x,role) ಬಗ್ಗೆ uncertainty ಕಡಿಮೆ ಮಾಡಬೇಕು, ಕೇವಲ prompt ಗೆ ಪದಗಳನ್ನೂ ಸೇರಿಸಬಾರದೂ.' } },

    { type: 'concept', data: {
      headingEn: 'Key Terms', headingKn: 'ಮುಖ್ಯ ಪದಗಳು',
      bodyEn: '• Prompt = Role + Context + Constraints + Output Format: the four-component mental model this whole module builds on\n• System/User/Assistant prefill: persistent policy vs current task vs pre-seeded output tokens (genuinely confirmed prefill changes the conditioning of every later token)\n• Temperature: genuinely confirmed to reshape the ENTIRE softmax distribution (95.68% -> 54.4% -> 36.08% for the top token as T rises)\n• Top-p (nucleus sampling): genuinely confirmed to cut off the low-probability tail entirely rather than reshape it (nucleus={A,B,C} at p=0.80)\n• Signal ratio: genuinely confirmed 90% vs 10% for two prompts, motivating context engineering as distinct from prompt engineering\n• PROMPT_PATTERNS: genuinely built and rendered -- a template + variables list (for validation) + temperature + description packaged as one structured object per pattern',
      bodyKn: '• Prompt = Role + Context + Constraints + Output Format: ಈ ಇಡೀ module ನಿರ್ಮಿಸುವ ನಾಲ್ಕೂ-component mental model\n• System/User/Assistant prefill: ಸ್ಥಿರ policy vs ಪ್ರಸ್ತುತ task vs ಮೊದಲೇ-ಬಿತ್ತಿದ output tokens (prefill ಪ್ರತಿ ನಂತರದ token ya conditioning ಬದಲಾಯಿಸುತ್ತದೆ ಎಂದೂ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ)\n• Temperature: ಇಡೀ softmax distribution ಅನ್ನೂ ಮರುರೂಪಿಸುತ್ತದೆ ಎಂದೂ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ (T ಏರಿದಂತೆ top token ಗೆ 95.68% -> 54.4% -> 36.08%)\n• Top-p (nucleus sampling): ಕಡಿಮೆ-probability ಬಾಲವನ್ನೂ ಮರುರೂಪಿಸುವ ಬದಲಿಗೆ ಸಂಪೂರ್ಣವಾಗಿ ಕತ್ತರಿಸುತ್ತದೆ ಎಂದೂ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ (p=0.80 ನಲ್ಲಿ nucleus={A,B,C})\n• Signal ratio: ಎರಡೂ prompts ಗಾಗಿ 90% vs 10% ಎಂದೂ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ, prompt engineering ಇಂದ ಭಿನ್ನವಾಗಿ context engineering ಗೆ ಪ್ರೇರೇಪಿಸುತ್ತಾ\n• PROMPT_PATTERNS: ನಿಜವಾಗಿ ನಿರ್ಮಿಸಿ ರೆಂಡರ್ ಮಾಡಲಾಗಿದೆ -- ಪ್ರತಿ pattern ಗೆ ಒಂದೂ structured object ಆಗಿ ಪ್ಯಾಕ್ ಮಾಡಿದ ಒಂದೂ template + variables list (validation ಗಾಗಿ) + temperature + description' } },

    { type: 'concept', data: {
      headingEn: 'Key Takeaways', headingKn: 'ಮುಖ್ಯ ಅಂಶಗಳು',
      bodyEn: "• Prompt engineering reduces the valid output space: Prompt = Role + Context + Constraints + Output Format, each targeting different sources of model uncertainty.\n• System, user, and assistant-prefill messages play different roles -- prefill genuinely changes which conditional distribution the model samples from for every subsequent token.\n• Genuinely computed temperature reshapes the entire softmax distribution (top token: 95.68% at T=0.3, 36.08% at T=2.0), while top-p genuinely cuts off the low-probability tail entirely (nucleus={A,B,C} at p=0.80, excluding D/E/F completely).\n• Genuinely computed a 90% vs 10% signal ratio for two example prompts, showing more total context does not mean better signal -- this motivates the source's distinction between prompt engineering and context engineering.\n• Constraints function like program branches (negative/positive/conditional), making a prompt closer to a natural-language program than a simple request.\n• Genuinely built and rendered the PROMPT_PATTERNS dictionary, confirming a missing variable raises a clear KeyError and that JSON braces inside a substituted VALUE never interfere with template rendering -- only braces written directly in the template string matter.",
      bodyKn: '• Prompt engineering valid output space ಕಡಿಮೆ ಮಾಡುತ್ತದೆ: Prompt = Role + Context + Constraints + Output Format, ಪ್ರತಿಯೊಂದೂ model uncertainty ya ಭಿನ್ನ ಮೂಲಗಳನ್ನೂ ಗುರಿಪಡಿಸುತ್ತದೆ.\n• System, user, ಮತ್ತೆ assistant-prefill messages ಭಿನ್ನ ಪಾತ್ರಗಳನ್ನೂ ನಿರ್ವಹಿಸುತ್ತವೆ -- prefill ಪ್ರತಿ ನಂತರದ token ಗೆ model ಯಾವ conditional distribution ಇಂದ sample ಮಾಡುತ್ತದೆ ಎಂಬುದನ್ನೂ ನಿಜವಾಗಿ ಬದಲಾಯಿಸುತ್ತದೆ.\n• Temperature ಇಡೀ softmax distribution ಅನ್ನೂ ಮರುರೂಪಿಸುತ್ತದೆ ಎಂದೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಲಾಗಿದೆ (top token: T=0.3 ನಲ್ಲಿ 95.68%, T=2.0 ನಲ್ಲಿ 36.08%), ಆದರೆ top-p ಕಡಿಮೆ-probability ಬಾಲವನ್ನೂ ಸಂಪೂರ್ಣವಾಗಿ ಕತ್ತರಿಸುತ್ತದೆ ಎಂದೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಲಾಗಿದೆ (p=0.80 ನಲ್ಲಿ nucleus={A,B,C}, D/E/F ಸಂಪೂರ್ಣವಾಗಿ ಹೊರಗಿಡುತ್ತಾ).\n• Erdu ಉದಾಹರಣೆ prompts ಗಾಗಿ 90% vs 10% signal ratio ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಲಾಗಿದೆ, ಹೆಚ್ಚೂ ಒಟ್ಟೂ context ಎಂದರೆ ಉತ್ತಮ signal ಎಂದೂ ಅರ್ಥವಲ್ಲ ಎಂದೂ ತೋರಿಸುತ್ತಾ -- ಇದೂ prompt engineering ಮತ್ತೆ context engineering ನಡುವಿನ source ya ವ್ಯತ್ಯಾಸಕ್ಕೆ ಪ್ರೇರೇಪಿಸುತ್ತದೆ.\n• Constraints program branches ನಂತೆ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತವೆ (negative/positive/conditional), ಒಂದೂ prompt ಅನ್ನೂ ಒಂದೂ ಸರಳ ಕೋರಿಕೆಗಿಂತ ಒಂದೂ ಸ್ವಾಭಾವಿಕ-ಭಾಷೆಯ program ಗೆ ಹತ್ತಿರ ಮಾಡುತ್ತಾ.\n• PROMPT_PATTERNS dictionary ನಿಜವಾಗಿ ನಿರ್ಮಿಸಿ ರೆಂಡರ್ ಮಾಡಲಾಗಿದೆ, ಒಂದೂ ಕಾಣೆಯಾದ variable ಒಂದೂ ಸ್ಪಷ್ಟ KeyError ಎಸೆಯುತ್ತದೆ ಎಂದೂ ಮತ್ತೆ ಒಂದೂ substituted VALUE ಒಳಗಿನ JSON braces ಎಂದಿಗೂ template rendering ಗೆ ಅಡ್ಡಿಪಡಿಸುವುದಿಲ್ಲ ಎಂದೂ ದೃಢಪಡಿಸಲಾಗಿದೆ -- ಕೇವಲ template string ನಲ್ಲಿ ನೇರವಾಗಿ ಬರೆದ braces ಮಾತ್ರ ಮುಖ್ಯ.' } },

    { type: 'concept', data: {
      headingEn: 'Preview: Part 2', headingKn: 'ಮುನ್ನೋಟ: ಭಾಗ 2',
      bodyEn: 'Part 2 turns this pattern catalog into a working prompt-construction pipeline: build_prompt() (with genuine validation and rendering), build_multi_turn() for conversation history, and provider-specific formatters that convert one normalized prompt object into OpenAI, Anthropic, and Google request schemas -- the same logical prompt, three different wire formats.',
      bodyKn: 'Part 2 ಈ pattern catalog ಅನ್ನೂ ಒಂದೂ ಕೆಲಸ ಮಾಡುವ prompt-construction pipeline ಗೆ ಬದಲಾಯಿಸುತ್ತದೆ: build_prompt() (ನಿಜ validation ಮತ್ತೆ rendering ಜೊತೆ), conversation history ಗಾಗಿ build_multi_turn(), ಮತ್ತೆ ಒಂದೂ normalized prompt object ಅನ್ನೂ OpenAI, Anthropic, ಮತ್ತೆ Google request schemas ಗೆ ಪರಿವರ್ತಿಸುವ provider-specific formatters -- ಅದೇ logical prompt, ಮೂರೂ ಭಿನ್ನ wire formats.' } },

    { type: 'quiz', data: { questions: [
      { q: 'Why does "Summarize this article" usually produce inconsistent answers?',
        qKn: '"Summarize this article" ಸಾಮಾನ್ಯವಾಗಿ ಅಸಮಂಜಸ ಉತ್ತರಗಳನ್ನೂ ಏಕೆ ಉತ್ಪಾದಿಸುತ್ತದೆ?',
        opts: ['LLMs cannot summarize', 'Temperature is always too high', 'Format, length, audience, and focus are unspecified', 'It needs at least ten examples'], correct: 2,
        optsKn: ['LLMs summarize ಮಾಡಲು ಸಾಧ್ಯವಿಲ್ಲ', 'Temperature ಯಾವಾಗಲೂ ತುಂಬಾ ಹೆಚ್ಚೂ', 'Format, length, audience, ಮತ್ತೆ focus ಅನಿರ್ದಿಷ್ಟ', 'ಇದೂ ಗೆ ಕನಿಷ್ಠ ಹತ್ತೂ examples ಬೇಕು'] },
      { q: 'Genuinely confirmed: at temperature T=0.3, what fraction of probability mass did the top token ("Python") capture?',
        qKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: temperature T=0.3 ನಲ್ಲಿ, top token ("Python") ಎಷ್ಟೂ probability mass ಸೆರೆಹಿಡಿಯಿತೂ?',
        opts: ['36.08%', '54.4%', '95.68%', '100%'], correct: 2,
        optsKn: ['36.08%', '54.4%', '95.68%', '100%'] },
      { q: 'Genuinely confirmed: at top-p=0.80 for probabilities A=0.40,B=0.25,C=0.15,D=0.10,E=0.06,F=0.04, which tokens are in the nucleus?',
        qKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: probabilities A=0.40,B=0.25,C=0.15,D=0.10,E=0.06,F=0.04 ಗೆ top-p=0.80 ನಲ್ಲಿ, ಯಾವ tokens nucleus ನಲ್ಲಿವೆ?',
        opts: ['A only', 'A, B', 'A, B, C', 'All six tokens'], correct: 2,
        optsKn: ['ಕೇವಲ A', 'A, B', 'A, B, C', 'ಎಲ್ಲಾ ಆರೂ tokens'] },
      { q: 'Genuinely confirmed: why did Prompt B (100,000 tokens, 10,000 useful) have a worse signal ratio than Prompt A (10,000 tokens, 9,000 useful) despite containing more useful tokens overall?',
        qKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: Prompt B (100,000 tokens, 10,000 useful) ಒಟ್ಟಾರೆ ಹೆಚ್ಚೂ ಉಪಯುಕ್ತ tokens ಒಳಗೊಂಡಿದ್ದರೂ Prompt A (10,000 tokens, 9,000 useful) ಗಿಂತ ಕೆಟ್ಟ signal ratio ಏಕೆ ಹೊಂದಿತ್ತೂ?',
        opts: ['Prompt B had a computation error', 'The ratio is useful/total, and Prompt B\'s much larger total token count dilutes the ratio', 'Prompt A used a different model', 'Signal ratio does not depend on total tokens'], correct: 1,
        optsKn: ['Prompt B ಗೆ ಒಂದೂ computation error ಇತ್ತೂ', 'Ratio useful/total, ಮತ್ತೆ Prompt B ya ಬಹಳ ದೊಡ್ಡ total token count ratio ಅನ್ನೂ ದುರ್ಬಲಗೊಳಿಸುತ್ತದೆ', 'Prompt A ಒಂದೂ ಭಿನ್ನ model ಬಳಸಿತೂ', 'Signal ratio total tokens ಮೇಲೆ ಅವಲಂಬಿತವಾಗಿಲ್ಲ'] },
      { q: 'Genuinely confirmed: why did the few_shot template render successfully even though its "examples" value contained JSON braces?',
        qKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: few_shot template ya "examples" value JSON braces ಒಳಗೊಂಡಿದ್ದರೂ ಇದೂ ಯಶಸ್ವಿಯಾಗಿ ಏಕೆ render ಆಯಿತೂ?',
        opts: ['Python automatically escapes all braces', '.format() only parses braces written directly in the template string, not inside a substituted value', 'JSON is a special case Python always allows', 'The braces were removed before rendering'], correct: 1,
        optsKn: ['Python ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಎಲ್ಲಾ braces escape ಮಾಡುತ್ತದೆ', '.format() ಕೇವಲ template string ನಲ್ಲಿ ನೇರವಾಗಿ ಬರೆದ braces parse ಮಾಡುತ್ತದೆ, ಒಂದೂ substituted value ಒಳಗೆ ಅಲ್ಲ', 'JSON ಒಂದೂ ವಿಶೇಷ ಪ್ರಕರಣ Python ಯಾವಾಗಲೂ ಅನುಮತಿಸುತ್ತದೆ', 'Braces render ಮಾಡುವ ಮೊದಲೂ ತೆಗೆದುಹಾಕಲಾಯಿತೂ'] },
    ] } },
  ],
};
