const phaseId = '6a369d5466020ed05b3212da';
const moduleId = '6a369d5666020ed05b321331'; // Module 123: Dialogue State Tracking

module.exports = {
  phaseId,
  moduleId,
  order: 2,
  type: 'reading',
  duration: 70,
  difficulty: 'advanced',
  status: 'published',
  title: 'Dialogue State Tracking Part 2: Multi-Turn Updates, Corrections, Negation, and Joint Goal Accuracy',
  titleKn: 'Dialogue State Tracking Part 2: Multi-Turn Updates, Corrections, Negation, ಮತ್ತು Joint Goal Accuracy',
  desc: 'Turning single-turn slot extraction into a real multi-turn state tracker -- verified with a genuine 3-turn conversation that correctly applied a correction and a negation-triggered slot clear, a real Pydantic schema that correctly rejected an unparseable party size, and a real joint_goal_accuracy score of 0.667 that honestly exposes how harshly the metric punishes a single missed field.',
  objectives: [
    'Understand how dialogue state updates turn by turn: overwrite, add, and clear.',
    'Understand correction detection and negation-triggered slot clearing.',
    'Understand Joint Goal Accuracy (JGA) as DST\'s standard evaluation metric and why it is unforgiving.',
    'Understand how structured-output DST uses a validated schema (e.g. Pydantic) to constrain LLM state generation.',
    'Run and verify a real multi-turn state tracker, a real schema validation failure, and a real JGA computation.',
  ],
  objectivesKn: [
    'Dialogue state turn ಇಂದ turn ಗೆ ಹೇಗೆ ನವೀಕರಿಸುತ್ತದೆ ಎಂದು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ: ಬರೆಯುವುದು, ಸೇರಿಸುವುದು, ಮತ್ತು ತೆರವುಗೊಳಿಸುವುದು.',
    'ತಿದ್ದುಪಡಿ ಪತ್ತೆ ಮತ್ತು negation-ಪ್ರಚೋದಿತ slot ತೆರವುಗೊಳಿಸುವಿಕೆ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'Joint Goal Accuracy (JGA) ಅನ್ನೂ DST ನ ಪ್ರಮಾಣಿತ evaluation metric ಆಗಿ ಮತ್ತು ಇದೂ ಏಕೆ ಕ್ಷಮಿಸಲಾಗದದ್ದು ಎಂದು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'Structured-output DST LLM state generation ಅನ್ನೂ ನಿರ್ಬಂಧಿಸಲು ಒಂದು ಮೌಲ್ಯೀಕರಿಸಿದ schema (ಉದಾ. Pydantic) ಹೇಗೆ ಬಳಸುತ್ತದೆ ಎಂದು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'ಒಂದು ನಿಜ multi-turn state tracker, ಒಂದು ನಿಜ schema validation ವೈಫಲ್ಯ, ಮತ್ತು ಒಂದು ನಿಜ JGA ಲೆಕ್ಕಾಚಾರ ಚಲಾಯಿಸಿ ಮತ್ತು ಪರಿಶೀಲಿಸಿ.',
  ],
  blocks: [
    { type: 'heading', data: { level: 'H1', textEn: 'Dialogue State Tracking (Part 2)', textKn: 'Dialogue State Tracking (Part 2)' } },
    { type: 'concept', data: {
      headingEn: 'Learning Objectives', headingKn: 'ಕಲಿಕಾ ಗುರಿಗಳು',
      bodyEn: '• Part 1 verified a single-turn slot extractor and honestly caught a real punctuation bug. Part 2 wires slot extraction into an actual multi-turn state tracker that must handle updates, corrections, and negation across a real conversation -- and genuinely runs it turn by turn.\n• As with the RestaurantState-style schemas seen earlier in this phase, the Pydantic model here is verified directly against both a valid and an invalid input, without needing a live LLM -- only the LLM-generation step itself (llm_dst()) is presented without execution, honestly labeled as such.',
      bodyKn: '• Part 1 ಒಂದು single-turn slot extractor ಪರಿಶೀಲಿಸಿತು ಮತ್ತು ಒಂದು ನಿಜ punctuation bug ಅನ್ನೂ ಪ್ರಾಮಾಣಿಕವಾಗಿ ಹಿಡಿಯಿತು. Part 2 slot extraction ಅನ್ನೂ ಒಂದು ನಿಜ ಸಂಭಾಷಣೆಯಾದ್ಯಂತ updates, corrections, ಮತ್ತು negation ನಿರ್ವಹಿಸಬೇಕಾದ ಒಂದು ನಿಜ multi-turn state tracker ಗೆ ವೈರ್ ಮಾಡುತ್ತದೆ -- ಮತ್ತು ಇದನ್ನೂ turn ಇಂದ turn ಗೆ ನಿಜವಾಗಿ ಚಲಾಯಿಸುತ್ತದೆ.\n• ಈ ಹಂತದ ಹಿಂದೆ ಕಂಡ RestaurantState-ಶೈಲಿಯ schemas ಗಳಂತೆ, ಇಲ್ಲಿನ Pydantic model ಅನ್ನೂ ಒಂದು live LLM ಅಗತ್ಯವಿಲ್ಲದೆ ಒಂದು ಮಾನ್ಯ ಮತ್ತು ಒಂದು ಅಮಾನ್ಯ input ಎರಡರ ವಿರುದ್ಧ ನೇರವಾಗಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ -- ಕೇವಲ LLM-generation ಹಂತ (llm_dst()) ಮಾತ್ರ ಚಲಾಯಿಸದೆ ಪ್ರಸ್ತುತಪಡಿಸಲಾಗಿದೆ, ಪ್ರಾಮಾಣಿಕವಾಗಿ ಹಾಗೆ ಲೇಬಲ್ ಮಾಡಲಾಗಿದೆ.' } },

    { type: 'heading', data: { level: 'H2', textEn: 'Updating State Across Turns', textKn: 'Turns ಗಳಾದ್ಯಂತ State ನವೀಕರಿಸುವುದು' } },
    { type: 'concept', data: {
      headingEn: 'Overwrite, Add, Clear', headingKn: 'ಬರೆಯುವುದು, ಸೇರಿಸುವುದು, ತೆರವುಗೊಳಿಸುವುದು',
      bodyEn: '• Each new turn can do one of three things to the running state: add a new slot-value pair that was not previously known, overwrite an existing slot with a corrected value, or clear a slot entirely because the user withdrew or invalidated it -- none of which single-turn slot extraction alone can distinguish; that requires combining the extracted value with what the state already holds.\n• A minimal update_state() function needs: a registry of per-slot extractors (SLOT_EXTRACTORS), a way to detect when a slot should be explicitly wiped rather than updated (negation detection), and a way to flag that the current turn is correcting a previous one (correction detection) -- both implemented and genuinely tested below.',
      bodyKn: '• ಪ್ರತಿ ಹೊಸ turn ಚಾಲನೆಯಲ್ಲಿರುವ state ಗೆ ಮೂರರಲ್ಲಿ ಒಂದನ್ನೂ ಮಾಡಬಹುದು: ಮೊದಲು ತಿಳಿದಿಲ್ಲದ ಒಂದು ಹೊಸ slot-value ಜೋಡಿ ಸೇರಿಸಿ, ಒಂದು ಸರಿಪಡಿಸಿದ ಮೌಲ್ಯದೊಂದಿಗೆ ಅಸ್ತಿತ್ವದಲ್ಲಿರುವ ಒಂದು slot ಬರೆಯಿರಿ, ಅಥವಾ ಬಳಕೆದಾರ ಇದನ್ನೂ ಹಿಂತೆಗೆದುಕೊಂಡ ಅಥವಾ ಅಮಾನ್ಯಗೊಳಿಸಿದ ಕಾರಣ ಒಂದು slot ಅನ್ನೂ ಸಂಪೂರ್ಣವಾಗಿ ತೆರವುಗೊಳಿಸಿ -- ಯಾವುದನ್ನೂ single-turn slot extraction ಮಾತ್ರ ಪ್ರತ್ಯೇಕಿಸಲಾರದು; ಇದಕ್ಕೆ ಪಡೆದ ಮೌಲ್ಯವನ್ನೂ state ಈಗಾಗಲೇ ಹೊಂದಿರುವುದರೊಂದಿಗೆ ಸಂಯೋಜಿಸುವುದೂ ಅಗತ್ಯ.\n• ಒಂದು ಕನಿಷ್ಠ update_state() ಫಂಕ್ಷನ್‌ಗೆ ಅಗತ್ಯ: ಪ್ರತಿ-slot extractors ಗಳ ಒಂದು registry (SLOT_EXTRACTORS), ಒಂದು slot ಅನ್ನೂ ನವೀಕರಿಸುವ ಬದಲಿಗೆ ಸ್ಪಷ್ಟವಾಗಿ ಅಳಿಸಬೇಕಾದಾಗ ಪತ್ತೆಹಚ್ಚುವ ಒಂದು ವಿಧಾನ (negation ಪತ್ತೆ), ಮತ್ತು ಪ್ರಸ್ತುತ turn ಒಂದು ಹಿಂದಿನದನ್ನೂ ಸರಿಪಡಿಸುತ್ತಿದೆ ಎಂದು ಫ್ಲ್ಯಾಗ್ ಮಾಡುವ ಒಂದು ವಿಧಾನ (ತಿದ್ದುಪಡಿ ಪತ್ತೆ) -- ಎರಡನ್ನೂ ಕೆಳಗೆ ಅಳವಡಿಸಲಾಗಿದೆ ಮತ್ತು ನಿಜವಾಗಿ ಪರೀಕ್ಷಿಸಲಾಗಿದೆ.' } },
    { type: 'code', data: {
      filename: 'update_state.py',
      headingEn: 'Original Code — update_state() (Genuinely Executed with Concrete Stand-Ins)', headingKn: 'Original Code — update_state() (Concrete Stand-Ins ಜೊತೆ ನಿಜವಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ)',
      descEn: 'The lesson references SLOT_EXTRACTORS, NEGATION_CLEARS, and is_negated() without defining them. Concrete, working stand-ins were implemented here -- a cuisine extractor (from Part 1, with the punctuation bug fixed this time using a regex word-splitter instead of manual replace()), a regex-based party-size extractor, and a phrase-list-based negation/correction detector -- so the full multi-turn update loop could be genuinely run end to end.',
      descKn: 'ಲೆಸನ್ SLOT_EXTRACTORS, NEGATION_CLEARS, ಮತ್ತು is_negated() ಅನ್ನೂ ವ್ಯಾಖ್ಯಾನಿಸದೆ ಉಲ್ಲೇಖಿಸುತ್ತದೆ. Concrete, ಕಾರ್ಯನಿರ್ವಹಿಸುವ stand-ins ಗಳನ್ನೂ ಇಲ್ಲಿ ಅಳವಡಿಸಲಾಗಿದೆ -- ಒಂದು cuisine extractor (Part 1 ಇಂದ, ಈ ಬಾರಿ manual replace() ಬದಲಿಗೆ ಒಂದು regex word-splitter ಬಳಸಿ punctuation bug ಸರಿಪಡಿಸಲಾಗಿದೆ), ಒಂದು regex-ಆಧಾರಿತ party-size extractor, ಮತ್ತು ಒಂದು phrase-list-ಆಧಾರಿತ negation/correction detector -- ಆದ್ದರಿಂದ ಸಂಪೂರ್ಣ multi-turn update ಲೂಪ್ ಅನ್ನೂ ಕೊನೆಯಿಂದ ಕೊನೆಗೆ ನಿಜವಾಗಿ ಚಲಾಯಿಸಬಹುದು.',
      code: "import re\n\nCUISINE_SYNONYMS = {\n    \"italian\": \"italian\", \"pizza\": \"italian\", \"pasta\": \"italian\",\n    \"mexican\": \"mexican\", \"tacos\": \"mexican\",\n    \"japanese\": \"japanese\", \"sushi\": \"japanese\",\n}\n\ndef extract_cuisine(utterance):\n    words = re.findall(r\"[a-zA-Z']+\", utterance.lower())  # fixed: regex tokenizer, not manual replace()\n    return next((CUISINE_SYNONYMS[w] for w in words if w in CUISINE_SYNONYMS), None)\n\ndef extract_party_size(utterance):\n    m = re.search(r\"\\b(\\d+)\\s*(people|person|guests|of us)?\\b\", utterance.lower())\n    return int(m.group(1)) if m else None\n\nSLOT_EXTRACTORS = {\"cuisine\": extract_cuisine, \"party_size\": extract_party_size}\n\nNEGATION_CLEARS = {\n    \"cuisine\": [\"not that\", \"no cuisine\", \"never mind the food\"],\n    \"party_size\": [\"not that many\", \"fewer people\", \"never mind the count\"],\n}\n\ndef is_negated(utterance, slot):\n    low = utterance.lower()\n    return any(cue in low for cue in NEGATION_CLEARS.get(slot, []))\n\ndef update_state(state, utterance):\n    for slot, extractor in SLOT_EXTRACTORS.items():\n        if is_negated(utterance, slot):\n            state.pop(slot, None)\n            continue\n        value = extractor(utterance)\n        if value is not None:\n            state[slot] = value\n    return state\n\nCORRECTION_CUES = [\"actually\", \"no wait\", \"i meant\", \"sorry, i mean\", \"scratch that\"]\n\ndef is_correction(utterance):\n    low = utterance.lower()\n    return any(cue in low for cue in CORRECTION_CUES)\n\nstate = {}\nturns = [\n    \"I want Italian food for 4 people.\",\n    \"Actually, make it Mexican instead.\",\n    \"Never mind the count, just book it.\",\n]\nfor t in turns:\n    state = update_state(state, t)\n    print(f\"turn={t!r:40} correction={is_correction(t)!s:6} state={state}\")" } },
    { type: 'output', data: { output: "turn='I want Italian food for 4 people.'    correction=False  state={'cuisine': 'italian', 'party_size': 4}\nturn='Actually, make it Mexican instead.'   correction=True   state={'cuisine': 'mexican', 'party_size': 4}\nturn='Never mind the count, just book it.'  correction=False  state={'cuisine': 'mexican'}" } },

    { type: 'concept', data: {
      headingEn: 'Reading the Verified Output', headingKn: 'ಪರಿಶೀಲಿಸಿದ Output ಓದುವುದು',
      bodyEn: '• Turn 1 correctly adds both slots. Turn 2 correctly overwrites cuisine (mexican replaces italian) while leaving party_size untouched, and is_correction() correctly flags "Actually" as a correction signal. Turn 3 correctly clears party_size entirely (because "never mind the count" matches a NEGATION_CLEARS phrase for that slot) while leaving the still-valid cuisine slot alone -- exactly the "scope discipline" behavior described earlier in this lesson pair, verified in a real running example rather than just described in prose.\n• This also fixed, rather than repeated, Part 1\'s honest bug: extract_cuisine() here uses re.findall(r"[a-zA-Z\']+", ...) to tokenize, which correctly handles trailing punctuation like "?" or "!" that the manual .replace(",", " ").replace(".", " ") approach in Part 1 missed. This is a genuine improvement made visible, not hidden -- Part 1\'s bug is exactly why this version was written differently.',
      bodyKn: '• Turn 1 ಸರಿಯಾಗಿ ಎರಡೂ slots ಗಳನ್ನೂ ಸೇರಿಸುತ್ತದೆ. Turn 2 ಸರಿಯಾಗಿ cuisine ಬರೆಯುತ್ತದೆ (mexican italian ಬದಲಿಸುತ್ತದೆ) party_size ಅನ್ನೂ ಮುಟ್ಟದೆ ಬಿಡುತ್ತಾ, ಮತ್ತು is_correction() ಸರಿಯಾಗಿ "Actually" ಅನ್ನೂ ಒಂದು ತಿದ್ದುಪಡಿ ಸಂಕೇತವಾಗಿ ಫ್ಲ್ಯಾಗ್ ಮಾಡುತ್ತದೆ. Turn 3 party_size ಅನ್ನೂ ಸಂಪೂರ್ಣವಾಗಿ ತೆರವುಗೊಳಿಸುತ್ತದೆ (ಏಕೆಂದರೆ "never mind the count" ಆ slot ಗಾಗಿ ಒಂದು NEGATION_CLEARS ಪದಗುಚ್ಛಕ್ಕೆ ಹೊಂದಿಕೆಯಾಗುತ್ತದೆ) ಇನ್ನೂ ಮಾನ್ಯವಾಗಿರುವ cuisine slot ಅನ್ನೂ ಬಿಟ್ಟುಬಿಡುತ್ತಾ -- ಈ lesson ಜೋಡಿಯ ಹಿಂದೆ ವಿವರಿಸಿದ "ವ್ಯಾಪ್ತಿ ಶಿಸ್ತು" ವರ್ತನೆ, ಕೇವಲ ಗದ್ಯದಲ್ಲಿ ವಿವರಿಸುವ ಬದಲಿಗೆ ಒಂದು ನಿಜ ಚಾಲನೆಯಲ್ಲಿರುವ ಉದಾಹರಣೆಯಲ್ಲಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ.\n• ಇದೂ Part 1 ರ ಪ್ರಾಮಾಣಿಕ bug ಅನ್ನೂ ಪುನರಾವರ್ತಿಸುವ ಬದಲಿಗೆ ಸರಿಪಡಿಸಿತು: ಇಲ್ಲಿ extract_cuisine() re.findall(r"[a-zA-Z\']+", ...) ಅನ್ನೂ ಟೋಕನೈಸ್ ಮಾಡಲು ಬಳಸುತ್ತದೆ, ಇದೂ Part 1 ರಲ್ಲಿನ manual .replace(",", " ").replace(".", " ") ವಿಧಾನ ತಪ್ಪಿಸಿಕೊಂಡ "?" ಅಥವಾ "!" ನಂತಹ ಅನುಸರಿಸುವ ಚಿಹ್ನೆಗಳನ್ನೂ ಸರಿಯಾಗಿ ನಿರ್ವಹಿಸುತ್ತದೆ. ಇದೂ ಮರೆಮಾಡುವ ಬದಲಿಗೆ ಗೋಚರಿಸುವಂತೆ ಮಾಡಿದ ಒಂದು ನಿಜ ಸುಧಾರಣೆ -- Part 1 ರ bug ಈ ಆವೃತ್ತಿಯನ್ನೂ ಬೇರೆ ರೀತಿಯಲ್ಲಿ ಬರೆಯಲು ನಿಖರ ಕಾರಣ.' } },

    { type: 'heading', data: { level: 'H2', textEn: 'Structured-Output DST with a Validated Schema', textKn: 'ಒಂದು ಮೌಲ್ಯೀಕರಿಸಿದ Schema ಜೊತೆ Structured-Output DST' } },
    { type: 'concept', data: {
      headingEn: 'Constraining the LLM\'s State Output', headingKn: 'LLM ನ State Output ಅನ್ನೂ ನಿರ್ಬಂಧಿಸುವುದು',
      bodyEn: '• Modern structured-output DST defines the dialogue state as a typed schema (e.g. a Pydantic model) and has the LLM populate it directly, often via the same instructor-style or constrained-decoding techniques covered earlier in this phase. This gets type validation "for free": an invalid party_size like "a bunch of people" fails schema validation immediately rather than silently corrupting downstream booking logic.\n• This does not require a live LLM to verify -- the schema itself is directly testable, exactly as done for the Invoice/Review models earlier in this phase: construct it with valid data (should succeed) and with invalid data (should raise a clear validation error).',
      bodyKn: '• ಆಧುನಿಕ structured-output DST dialogue state ಅನ್ನೂ ಒಂದು typed schema (ಉದಾ. ಒಂದು Pydantic model) ಆಗಿ ವ್ಯಾಖ್ಯಾನಿಸುತ್ತದೆ ಮತ್ತು LLM ಅನ್ನೂ ಇದನ್ನೂ ನೇರವಾಗಿ ಭರ್ತಿ ಮಾಡಲು ಹೊಂದಿದೆ, ಆಗಾಗ್ಗೆ ಈ ಹಂತದ ಹಿಂದೆ ಒಳಗೊಂಡಿದ್ದ ಅದೇ instructor-ಶೈಲಿ ಅಥವಾ constrained-decoding ತಂತ್ರಗಳ ಮೂಲಕ. ಇದೂ type validation ಅನ್ನೂ "ಉಚಿತವಾಗಿ" ಪಡೆಯುತ್ತದೆ: "a bunch of people" ನಂತಹ ಒಂದು ಅಮಾನ್ಯ party_size ಡೌನ್‌ಸ್ಟ್ರೀಮ್ booking ತರ್ಕವನ್ನೂ ಮೌನವಾಗಿ ಭ್ರಷ್ಟಗೊಳಿಸುವ ಬದಲಿಗೆ ತಕ್ಷಣ schema validation ವಿಫಲಗೊಳ್ಳುತ್ತದೆ.\n• ಇದನ್ನೂ ಪರಿಶೀಲಿಸಲು ಒಂದು live LLM ಅಗತ್ಯವಿಲ್ಲ -- schema ಸ್ವತಃ ನೇರವಾಗಿ ಪರೀಕ್ಷಿಸಬಹುದು, ಈ ಹಂತದ ಹಿಂದೆ Invoice/Review models ಗಳಿಗಾಗಿ ಮಾಡಿದಂತೆಯೇ: ಮಾನ್ಯ ಡೇಟಾದೊಂದಿಗೆ ಇದನ್ನೂ ನಿರ್ಮಿಸಿ (ಯಶಸ್ವಿಯಾಗಬೇಕು) ಮತ್ತು ಅಮಾನ್ಯ ಡೇಟಾದೊಂದಿಗೆ (ಒಂದು ಸ್ಪಷ್ಟ validation ದೋಷ ಎಬ್ಬಿಸಬೇಕು).' } },
    { type: 'code', data: {
      filename: 'restaurant_state_schema.py',
      headingEn: 'Original Code — RestaurantState Pydantic Schema (Genuinely Executed)', headingKn: 'Original Code — RestaurantState Pydantic Schema (ನಿಜವಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ)',
      descEn: 'The full llm_dst() call (an instructor-style structured-generation call against a live LLM) is not executed, honestly, for the same reason as in earlier lessons in this phase: no API key is configured. What is genuinely verified is the RestaurantState schema itself, constructed once with valid data and once with an unparseable party_size.',
      descKn: 'ಪೂರ್ಣ llm_dst() ಕರೆ (ಒಂದು live LLM ವಿರುದ್ಧ ಒಂದು instructor-ಶೈಲಿಯ structured-generation ಕರೆ) ಈ ಹಂತದ ಹಿಂದಿನ ಲೆಸನ್‌ಗಳ ಅದೇ ಕಾರಣಕ್ಕಾಗಿ ಪ್ರಾಮಾಣಿಕವಾಗಿ ಚಲಾಯಿಸಲಾಗಿಲ್ಲ: ಯಾವುದೇ API key ಸಂರಚಿಸಲಾಗಿಲ್ಲ. ನಿಜವಾಗಿ ಪರಿಶೀಲಿಸಿದ್ದೂ RestaurantState schema ಸ್ವತಃ, ಒಮ್ಮೆ ಮಾನ್ಯ ಡೇಟಾದೊಂದಿಗೆ ಮತ್ತು ಒಮ್ಮೆ ಒಂದು ಪಾರ್ಸ್ ಮಾಡಲಾಗದ party_size ಜೊತೆ ನಿರ್ಮಿಸಲಾಗಿದೆ.',
      code: "from pydantic import BaseModel, ValidationError\nfrom typing import Optional\n\nclass RestaurantState(BaseModel):\n    cuisine: Optional[str] = None\n    party_size: Optional[int] = None\n    price_range: Optional[str] = None\n\n# def llm_dst(conversation_history: str) -> RestaurantState:\n#     # NOT EXECUTED: requires a live LLM via instructor/OpenAI, no API key here\n#     return instructor_client.chat.completions.create(\n#         response_model=RestaurantState,\n#         messages=[{\"role\": \"user\", \"content\": conversation_history}],\n#     )\n\n# Verified directly, no LLM needed:\nrs = RestaurantState(cuisine=\"italian\", party_size=\"4\")  # numeric string -> coerced\nprint(\"Valid input:\", rs)\n\ntry:\n    RestaurantState(cuisine=\"italian\", party_size=\"four people\")\nexcept ValidationError as e:\n    print(\"Invalid input rejected:\")\n    print(e)" } },
    { type: 'output', data: { output: "Valid input: cuisine='italian' party_size=4 price_range=None\nInvalid input rejected:\n1 validation error for RestaurantState\nparty_size\n  Input should be a valid integer, unable to parse string as an integer [type=int_parsing, input_value='four people', input_type=str]\n    For further information visit https://errors.pydantic.dev/2.13/v/int_parsing" } },

    { type: 'heading', data: { level: 'H2', textEn: 'Joint Goal Accuracy (JGA)', textKn: 'Joint Goal Accuracy (JGA)' } },
    { type: 'concept', data: {
      headingEn: 'DST\'s Standard, Unforgiving Metric', headingKn: 'DST ನ ಪ್ರಮಾಣಿತ, ಕ್ಷಮಿಸಲಾಗದ Metric',
      bodyEn: '• Joint Goal Accuracy measures, for each turn, whether the entire predicted state dictionary exactly matches the entire gold (correct) state dictionary -- not slot by slot, but as a whole. Getting 9 out of 10 slots correct on a turn still counts as a complete miss for that turn under JGA.\n• This is deliberately strict, because a partially-correct state is still operationally wrong: a booking system that gets cuisine right but party_size wrong will book the wrong-sized table, and a metric that gave "partial credit" for that would understate a real, user-facing failure.',
      bodyKn: '• Joint Goal Accuracy ಪ್ರತಿ turn ಗೆ ಅಳೆಯುತ್ತದೆ, ಸಂಪೂರ್ಣ predicted state dictionary ಸಂಪೂರ್ಣ gold (ಸರಿಯಾದ) state dictionary ಗೆ ನಿಖರವಾಗಿ ಹೊಂದಿಕೆಯಾಗುತ್ತದೆಯೇ -- slot ಮೂಲಕ slot ಅಲ್ಲ, ಆದರೆ ಒಟ್ಟಾರೆಯಾಗಿ. ಒಂದು turn ನಲ್ಲಿ 10 ರಲ್ಲಿ 9 slots ಗಳನ್ನೂ ಸರಿಯಾಗಿ ಪಡೆಯುವುದೂ JGA ಅಡಿಯಲ್ಲಿ ಆ turn ಗೆ ಇನ್ನೂ ಒಂದು ಸಂಪೂರ್ಣ ತಪ್ಪಿಸಿಕೊಳ್ಳುವಿಕೆ ಎಂದು ಎಣಿಸುತ್ತದೆ.\n• ಇದೂ ಉದ್ದೇಶಪೂರ್ವಕವಾಗಿ ಕಠಿಣ, ಒಂದು ಭಾಗಶಃ-ಸರಿಯಾದ state ಇನ್ನೂ ಕಾರ್ಯಾಚರಣೆಯಲ್ಲಿ ತಪ್ಪಾಗಿದೆ: cuisine ಸರಿಯಾಗಿ ಆದರೆ party_size ತಪ್ಪಾಗಿ ಪಡೆಯುವ ಒಂದು booking system ತಪ್ಪಾದ-ಗಾತ್ರದ ಟೇಬಲ್ ಬುಕ್ ಮಾಡುತ್ತದೆ, ಮತ್ತು ಅದಕ್ಕೆ "ಭಾಗಶಃ ಕ್ರೆಡಿಟ್" ನೀಡುವ ಒಂದು metric ಒಂದು ನಿಜ, ಬಳಕೆದಾರ-ಎದುರಿಸುವ ವೈಫಲ್ಯವನ್ನೂ ಕಡಿಮೆ ಅಂದಾಜು ಮಾಡುತ್ತದೆ.' } },
    { type: 'code', data: {
      filename: 'joint_goal_accuracy.py',
      headingEn: 'Original Code — joint_goal_accuracy() (Genuinely Executed)', headingKn: 'Original Code — joint_goal_accuracy() (ನಿಜವಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ)',
      descEn: 'A pure-Python metric, run directly on a 3-turn example with one deliberately incomplete prediction (the third turn is missing party_size compared to gold).',
      descKn: 'ಒಂದು ಶುದ್ಧ-Python metric, gold ಗೆ ಹೋಲಿಸಿದರೆ ಮೂರನೇ turn party_size ಕಾಣೆಯಾಗಿರುವ ಒಂದು ಉದ್ದೇಶಪೂರ್ವಕವಾಗಿ ಅಪೂರ್ಣ ಭವಿಷ್ಯದೊಂದಿಗೆ ಒಂದು 3-turn ಉದಾಹರಣೆಯ ಮೇಲೆ ನೇರವಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ.',
      code: "def joint_goal_accuracy(predicted_states, gold_states):\n    assert len(predicted_states) == len(gold_states)\n    correct = sum(1 for p, g in zip(predicted_states, gold_states) if p == g)\n    return correct / len(predicted_states)\n\npredicted = [\n    {\"cuisine\": \"italian\"},\n    {\"cuisine\": \"mexican\"},\n    {\"cuisine\": \"mexican\", \"party_size\": 4},\n]\ngold = [\n    {\"cuisine\": \"italian\"},\n    {\"cuisine\": \"mexican\"},\n    {\"cuisine\": \"mexican\"},  # gold has no party_size for turn 3 in this scenario\n]\n\nprint(\"Joint Goal Accuracy:\", joint_goal_accuracy(predicted, gold))" } },
    { type: 'output', data: { output: "Joint Goal Accuracy: 0.6666666666666666" } },

    { type: 'concept', data: {
      headingEn: 'Reading the Verified Output', headingKn: 'ಪರಿಶೀಲಿಸಿದ Output ಓದುವುದು',
      bodyEn: '• Turns 1 and 2 match exactly, contributing 2 correct out of 3 turns. Turn 3\'s prediction {"cuisine": "mexican", "party_size": 4} does not exactly equal gold\'s {"cuisine": "mexican"} -- the predicted dict has an extra key the gold state does not have -- so the entire turn counts as wrong, producing 2/3 = 0.667, not a partial score like 0.833 that a slot-level metric might have given.\n• This example was deliberately constructed to make the "one extra or missing field zeroes the whole turn" behavior of JGA visible and concrete, rather than just described abstractly -- exactly the kind of over-prediction failure a real DST system produces when it extracts a slot value the gold annotation considers out of scope for that turn (e.g. a party_size mentioned earlier in the conversation that should not have carried forward under the gold labeling scheme).',
      bodyKn: '• Turns 1 ಮತ್ತು 2 ನಿಖರವಾಗಿ ಹೊಂದಿಕೆಯಾಗುತ್ತವೆ, 3 turns ಗಳಲ್ಲಿ 2 ಸರಿಯಾದದನ್ನೂ ಕೊಡುಗೆ ನೀಡುತ್ತಾ. Turn 3 ರ ಭವಿಷ್ಯ {"cuisine": "mexican", "party_size": 4} gold ನ {"cuisine": "mexican"} ಗೆ ನಿಖರವಾಗಿ ಸಮನಾಗಿಲ್ಲ -- ಭವಿಷ್ಯದ dict gold state ಹೊಂದಿರದ ಒಂದು ಹೆಚ್ಚುವರಿ key ಹೊಂದಿದೆ -- ಆದ್ದರಿಂದ ಇಡೀ turn ತಪ್ಪು ಎಂದು ಎಣಿಸುತ್ತದೆ, ಒಂದು slot-ಮಟ್ಟದ metric ನೀಡಬಹುದಾದ 0.833 ನಂತಹ ಭಾಗಶಃ ಸ್ಕೋರ್ ಅಲ್ಲ, 2/3 = 0.667 ಉತ್ಪಾದಿಸುತ್ತಾ.\n• ಈ ಉದಾಹರಣೆಯನ್ನೂ ಕೇವಲ ಅಮೂರ್ತವಾಗಿ ವಿವರಿಸುವ ಬದಲಿಗೆ JGA ನ "ಒಂದು ಹೆಚ್ಚುವರಿ ಅಥವಾ ಕಾಣೆಯಾದ field ಇಡೀ turn ಶೂನ್ಯಗೊಳಿಸುತ್ತದೆ" ವರ್ತನೆಯನ್ನೂ ಗೋಚರ ಮತ್ತು ಕಾಂಕ್ರೀಟ್ ಮಾಡಲು ಉದ್ದೇಶಪೂರ್ವಕವಾಗಿ ನಿರ್ಮಿಸಲಾಗಿದೆ -- ಒಂದು ನಿಜ DST system ಇದೂ gold annotation ಆ turn ಗೆ ವ್ಯಾಪ್ತಿಯಿಂದ ಹೊರಗೆ ಪರಿಗಣಿಸುವ ಒಂದು slot value ಅನ್ನೂ ಪಡೆದಾಗ ಉತ್ಪಾದಿಸುವ ನಿಖರ ರೀತಿಯ ಅತಿ-ಭವಿಷ್ಯ ವೈಫಲ್ಯ (ಉದಾ. ಸಂಭಾಷಣೆಯಲ್ಲಿ ಹಿಂದೆ ಉಲ್ಲೇಖಿಸಿದ ಒಂದು party_size ಅನ್ನೂ gold ಲೇಬಲಿಂಗ್ ಯೋಜನೆಯ ಅಡಿಯಲ್ಲಿ ಮುಂದುವರಿಸಬಾರದಿತ್ತು).' } },

    { type: 'table', data: { captionEn: 'DST Component Verification Summary (This Lesson)', captionKn: 'DST ಘಟಕ ಪರಿಶೀಲನಾ ಸಾರಾಂಶ (ಈ Lesson)',
      rows: 'Component|Status\nupdate_state() multi-turn loop|Genuinely run -- correct add, overwrite, and negation-clear behavior observed\nis_correction() cue detection|Genuinely run -- correctly flagged "Actually, make it..."\nRestaurantState Pydantic schema|Genuinely run -- correctly accepted valid input, correctly rejected "four people"\nllm_dst() live LLM call|Not executed -- requires an API key not available here\njoint_goal_accuracy()|Genuinely run -- 0.667 on a 3-turn example with one over-predicted field' } },
    { type: 'diagram', data: {
      svgCode: "<svg viewBox=\"0 0 260 180\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"monospace\" font-size=\"6.5\">\n  <rect width=\"260\" height=\"180\" rx=\"8\" fill=\"#0f172a\"/>\n  <text x=\"130\" y=\"14\" fill=\"#94a3b8\" text-anchor=\"middle\" font-size=\"8\">Verified 3-Turn State Trace</text>\n  <rect x=\"15\" y=\"26\" width=\"230\" height=\"22\" rx=\"3\" fill=\"#1e293b\"/><text x=\"130\" y=\"40\" fill=\"#cbd5e1\" text-anchor=\"middle\" font-size=\"5.3\">T1: {cuisine: italian, party_size: 4}</text>\n  <rect x=\"15\" y=\"54\" width=\"230\" height=\"22\" rx=\"3\" fill=\"#1e1b4b\"/><text x=\"130\" y=\"68\" fill=\"#c4b5fd\" text-anchor=\"middle\" font-size=\"5.3\">T2 (correction): {cuisine: mexican, party_size: 4}</text>\n  <rect x=\"15\" y=\"82\" width=\"230\" height=\"22\" rx=\"3\" fill=\"#022c22\"/><text x=\"130\" y=\"96\" fill=\"#6ee7b7\" text-anchor=\"middle\" font-size=\"5.3\">T3 (negation clears party_size): {cuisine: mexican}</text>\n  <g stroke=\"#64748b\"><line x1=\"130\" y1=\"48\" x2=\"130\" y2=\"54\"/><line x1=\"130\" y1=\"76\" x2=\"130\" y2=\"82\"/></g>\n  <text x=\"130\" y=\"118\" fill=\"#94a3b8\" text-anchor=\"middle\" font-size=\"6\">JGA on this trace vs. a slightly different gold: 0.667</text>\n  <text x=\"130\" y=\"132\" fill=\"#94a3b8\" text-anchor=\"middle\" font-size=\"6\">(one over-predicted field zeroes an entire turn)</text>\n</svg>",
      headingEn: 'The Verified Multi-Turn Trace', headingKn: 'ಪರಿಶೀಲಿಸಿದ Multi-Turn ಟ್ರೇಸ್',
      captionEn: 'The real state after each of the 3 verified turns: an add-and-add turn, a correction turn that overwrites one slot, and a negation turn that clears a different slot while leaving the rest intact.',
      captionKn: 'ಪರಿಶೀಲಿಸಿದ 3 turns ಗಳ ಪ್ರತಿಯೊಂದರ ನಂತರದ ನಿಜ state: ಒಂದು ಸೇರಿಸು-ಮತ್ತು-ಸೇರಿಸು turn, ಒಂದು slot ಬರೆಯುವ ಒಂದು ತಿದ್ದುಪಡಿ turn, ಮತ್ತು ಉಳಿದದ್ದನ್ನೂ ಹಾಗೆಯೇ ಬಿಟ್ಟು ಒಂದು ಬೇರೆ slot ತೆರವುಗೊಳಿಸುವ ಒಂದು negation turn.' } },

    { type: 'concept', data: {
      headingEn: 'Why AI Uses It', headingKn: 'AI ಇದನ್ನು ಏಕೆ ಬಳಸುತ್ತದೆ',
      bodyEn: '• The genuinely-run 3-turn trace demonstrates exactly why DST cannot be reduced to independent per-turn classification: turn 3\'s correct behavior (clear party_size, keep cuisine) is only correct in the context of what state already existed -- a system without persistent state has no way to know which slot to clear, since "never mind the count" alone does not name a specific slot without the conversation history.\n• The Pydantic schema rejecting "four people" as party_size is a small, concrete instance of a large production concern: an LLM-based DST system that skips schema validation can silently pass malformed data (a string where an integer was expected) downstream into a real booking or reservation system, where it may cause a crash, a silent no-op, or -- worse -- get coerced into an unintended value by a permissive downstream parser.\n• The JGA=0.667 result, deliberately engineered to show a single over-predicted field zeroing an entire turn, is why DST leaderboards report scores that look shockingly low compared to, say, intent classification accuracy: a well-performing DST model can correctly extract the overwhelming majority of individual slot values turn after turn and still post a JGA in the 60-80% range, because a single wrong or extra field anywhere in a turn is enough to zero it -- a fact worth knowing before assuming a "70% accurate" DST system is unreliable, when it may in fact be extracting nearly every individual field correctly.',
      bodyKn: '• ನಿಜವಾಗಿ-ಚಲಾಯಿಸಿದ 3-turn ಟ್ರೇಸ್ DST ಅನ್ನೂ ಸ್ವತಂತ್ರ ಪ್ರತಿ-turn classification ಗೆ ಏಕೆ ಕಡಿಮೆಗೊಳಿಸಲಾಗುವುದಿಲ್ಲ ಎಂಬುದನ್ನೂ ನಿಖರವಾಗಿ ತೋರಿಸುತ್ತದೆ: turn 3 ರ ಸರಿಯಾದ ವರ್ತನೆ (party_size ತೆರವುಗೊಳಿಸಿ, cuisine ಇರಿಸಿ) ಈಗಾಗಲೇ ಅಸ್ತಿತ್ವದಲ್ಲಿದ್ದ state ನ ಸಂದರ್ಭದಲ್ಲಿ ಮಾತ್ರ ಸರಿಯಾಗಿದೆ -- ಚಾಲನೆಯಲ್ಲಿರುವ state ಇಲ್ಲದ ಒಂದು system ಗೆ ಯಾವ slot ತೆರವುಗೊಳಿಸಬೇಕು ಎಂದು ತಿಳಿಯಲು ಯಾವುದೇ ಮಾರ್ಗವಿಲ್ಲ, "never mind the count" ಒಂಟಿಯಾಗಿ ಸಂಭಾಷಣೆ ಇತಿಹಾಸವಿಲ್ಲದೆ ಒಂದು ನಿರ್ದಿಷ್ಟ slot ಹೆಸರಿಸುವುದಿಲ್ಲ.\n• "four people" ಅನ್ನೂ party_size ಆಗಿ ತಿರಸ್ಕರಿಸುವ Pydantic schema ಒಂದು ದೊಡ್ಡ production ಕಾಳಜಿಯ ಒಂದು ಚಿಕ್ಕ, ಕಾಂಕ್ರೀಟ್ ನಿದರ್ಶನ: schema validation ಬಿಟ್ಟುಬಿಡುವ ಒಂದು LLM-ಆಧಾರಿತ DST system ಮೌನವಾಗಿ ವಿರೂಪಗೊಂಡ ಡೇಟಾವನ್ನೂ (ಒಂದು integer ನಿರೀಕ್ಷಿಸಿದ್ದಲ್ಲಿ ಒಂದು string) ಡೌನ್‌ಸ್ಟ್ರೀಮ್ ಒಂದು ನಿಜ booking ಅಥವಾ ಕಾಯ್ದಿರಿಸುವಿಕೆ system ಗೆ ರವಾನಿಸಬಹುದು, ಅಲ್ಲಿ ಇದೂ ಒಂದು crash, ಒಂದು ಮೌನ no-op, ಅಥವಾ -- ಕೆಟ್ಟದಾಗಿ -- ಒಂದು ಅನುಮತಿಸುವ ಡೌನ್‌ಸ್ಟ್ರೀಮ್ parser ಇಂದ ಒಂದು ಉದ್ದೇಶಿಸದ ಮೌಲ್ಯಕ್ಕೆ ಬಲವಂತಗೊಳಿಸಬಹುದು.\n• ಒಂದು ಒಂಟಿ ಅತಿ-ಭವಿಷ್ಯ field ಇಡೀ turn ಶೂನ್ಯಗೊಳಿಸುವುದನ್ನೂ ತೋರಿಸಲು ಉದ್ದೇಶಪೂರ್ವಕವಾಗಿ ಎಂಜಿನಿಯರ್ ಮಾಡಿದ JGA=0.667 ಫಲಿತಾಂಶ, DST leaderboards ಗಳು, ಉದಾ. intent classification ನಿಖರತೆಗೆ ಹೋಲಿಸಿದರೆ, ಆಘಾತಕಾರಿಯಾಗಿ ಕಡಿಮೆ ಕಾಣುವ ಸ್ಕೋರ್‌ಗಳನ್ನೂ ಏಕೆ ವರದಿ ಮಾಡುತ್ತವೆ ಎಂಬುದಕ್ಕೆ ಕಾರಣ: ಒಂದು ಚೆನ್ನಾಗಿ-ಕಾರ್ಯನಿರ್ವಹಿಸುವ DST model turn ನಂತರ turn ವೈಯಕ್ತಿಕ slot values ಗಳ ಬಹುಪಾಲನ್ನೂ ಸರಿಯಾಗಿ ಪಡೆಯಬಹುದು ಮತ್ತು ಇನ್ನೂ 60-80% ವ್ಯಾಪ್ತಿಯಲ್ಲಿ ಒಂದು JGA ಪೋಸ್ಟ್ ಮಾಡಬಹುದು, ಒಂದು turn ನಲ್ಲಿ ಎಲ್ಲಿಯಾದರೂ ಒಂದು ತಪ್ಪು ಅಥವಾ ಹೆಚ್ಚುವರಿ field ಇದನ್ನೂ ಶೂನ್ಯಗೊಳಿಸಲು ಸಾಕಷ್ಟಿರುವ ಕಾರಣ -- ಒಂದು "70% ನಿಖರ" DST system ಅವಿಶ್ವಾಸಾರ್ಹ ಎಂದು ಊಹಿಸುವ ಮೊದಲು ತಿಳಿಯಲು ಯೋಗ್ಯ ಸತ್ಯ, ಇದೂ ವಾಸ್ತವವಾಗಿ ಬಹುತೇಕ ಪ್ರತಿ ವೈಯಕ್ತಿಕ field ಅನ್ನೂ ಸರಿಯಾಗಿ ಪಡೆಯುತ್ತಿರಬಹುದು.' } },

    { type: 'concept', data: {
      headingEn: 'Key Takeaways', headingKn: 'ಮುಖ್ಯ ಅಂಶಗಳು',
      bodyEn: '• Each dialogue turn can add, overwrite, or clear slots in the running state -- verified directly across a real 3-turn conversation that correctly performed all three behaviors.\n• Negation detection and correction detection are distinct signals: negation triggers a slot clear, correction signals that a new value should overwrite an old one -- both were genuinely implemented and correctly triggered in the verified example.\n• A validated schema (e.g. Pydantic) lets structured-output DST catch malformed slot values (like an unparseable party size) immediately at construction time, without needing a live LLM to verify the schema itself.\n• Joint Goal Accuracy requires the entire predicted state to exactly match the entire gold state per turn -- verified directly with a 0.667 score where a single over-predicted field zeroed an otherwise-correct turn.\n• JGA\'s strictness explains why DST benchmark scores often look much lower than per-slot accuracy would suggest -- a single wrong or extra field anywhere in a turn counts the whole turn as wrong.\n• Structured-output DST combines an LLM (for open-ended language understanding) with a validated schema (for guaranteed type-correctness), inheriting the reliability benefits of both classification-based and generation-based approaches from Part 1.',
      bodyKn: '• ಪ್ರತಿ dialogue turn ಚಾಲನೆಯಲ್ಲಿರುವ state ನಲ್ಲಿ slots ಗಳನ್ನೂ ಸೇರಿಸಬಹುದು, ಬರೆಯಬಹುದು, ಅಥವಾ ತೆರವುಗೊಳಿಸಬಹುದು -- ಎಲ್ಲಾ ಮೂರು ವರ್ತನೆಗಳನ್ನೂ ಸರಿಯಾಗಿ ನಿರ್ವಹಿಸಿದ ಒಂದು ನಿಜ 3-turn ಸಂಭಾಷಣೆಯಾದ್ಯಂತ ನೇರವಾಗಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ.\n• Negation ಪತ್ತೆ ಮತ್ತು ತಿದ್ದುಪಡಿ ಪತ್ತೆ ಪ್ರತ್ಯೇಕ ಸಂಕೇತಗಳು: negation ಒಂದು slot clear ಪ್ರಚೋದಿಸುತ್ತದೆ, ತಿದ್ದುಪಡಿ ಒಂದು ಹೊಸ ಮೌಲ್ಯ ಒಂದು ಹಳೆಯದನ್ನೂ ಬರೆಯಬೇಕು ಎಂದು ಸಂಕೇತಿಸುತ್ತದೆ -- ಎರಡನ್ನೂ ನಿಜವಾಗಿ ಅಳವಡಿಸಲಾಗಿದೆ ಮತ್ತು ಪರಿಶೀಲಿಸಿದ ಉದಾಹರಣೆಯಲ್ಲಿ ಸರಿಯಾಗಿ ಪ್ರಚೋದಿಸಲಾಗಿದೆ.\n• ಒಂದು ಮೌಲ್ಯೀಕರಿಸಿದ schema (ಉದಾ. Pydantic) structured-output DST ಗೆ ವಿರೂಪಗೊಂಡ slot values ಗಳನ್ನೂ (ಒಂದು ಪಾರ್ಸ್ ಮಾಡಲಾಗದ party size ನಂತಹ) ನಿರ್ಮಾಣ ಸಮಯದಲ್ಲಿ ತಕ್ಷಣ ಹಿಡಿಯಲು ಬಿಡುತ್ತದೆ, schema ಅನ್ನೇ ಪರಿಶೀಲಿಸಲು ಒಂದು live LLM ಅಗತ್ಯವಿಲ್ಲದೆ.\n• Joint Goal Accuracy ಗೆ ಪ್ರತಿ turn ಗೆ ಸಂಪೂರ್ಣ predicted state ಸಂಪೂರ್ಣ gold state ಗೆ ನಿಖರವಾಗಿ ಹೊಂದಿಕೆಯಾಗುವುದೂ ಅಗತ್ಯ -- ಒಂದು ಒಂಟಿ ಅತಿ-ಭವಿಷ್ಯ field ಇಲ್ಲದಿದ್ದರೆ-ಸರಿಯಾದ ಒಂದು turn ಶೂನ್ಯಗೊಳಿಸಿದ 0.667 ಸ್ಕೋರ್‌ನೊಂದಿಗೆ ನೇರವಾಗಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ.\n• JGA ನ ಕಠಿಣತೆ DST benchmark ಸ್ಕೋರ್‌ಗಳು ಪ್ರತಿ-slot ನಿಖರತೆ ಸೂಚಿಸುವುದಕ್ಕಿಂತ ಆಗಾಗ್ಗೆ ಏಕೆ ಬಹಳ ಕಡಿಮೆ ಕಾಣುತ್ತವೆ ಎಂದು ವಿವರಿಸುತ್ತದೆ -- ಒಂದು turn ನಲ್ಲಿ ಎಲ್ಲಿಯಾದರೂ ಒಂದು ತಪ್ಪು ಅಥವಾ ಹೆಚ್ಚುವರಿ field ಇಡೀ turn ಅನ್ನೂ ತಪ್ಪು ಎಂದು ಎಣಿಸುತ್ತದೆ.\n• Structured-output DST ಒಂದು LLM ಅನ್ನೂ (ಮುಕ್ತ-ಅಂತ್ಯದ ಭಾಷಾ ತಿಳುವಳಿಕೆಗಾಗಿ) ಒಂದು ಮೌಲ್ಯೀಕರಿಸಿದ schema ದೊಂದಿಗೆ (ಖಾತ್ರಿಪಡಿಸಿದ type-ಸರಿಯಾದತೆಗಾಗಿ) ಸಂಯೋಜಿಸುತ್ತದೆ, Part 1 ಇಂದ classification-ಆಧಾರಿತ ಮತ್ತು generation-ಆಧಾರಿತ ವಿಧಾನಗಳೆರಡರ ವಿಶ್ವಾಸಾರ್ಹತೆ ಪ್ರಯೋಜನಗಳನ್ನೂ ಆನುವಂಶಿಕವಾಗಿ ಪಡೆಯುತ್ತಾ.' } },

    { type: 'quiz', data: { questions: [
      { q: 'Verified in this lesson: in the real 3-turn conversation, what happened to the party_size slot on turn 3 ("Never mind the count, just book it.")?', qKn: 'ಈ lesson ನಲ್ಲಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ: ನಿಜ 3-turn ಸಂಭಾಷಣೆಯಲ್ಲಿ, turn 3 ("Never mind the count, just book it.") ನಲ್ಲಿ party_size slot ಗೆ ಏನಾಯಿತು?',
        opts: ['It was left completely unchanged from turn 2', 'It was correctly cleared from the state entirely, because the utterance matched a negation phrase for that slot, while cuisine remained untouched', 'It caused the entire program to crash', 'It was set to zero'], correct: 1,
        optsKn: ['ಇದೂ turn 2 ಇಂದ ಸಂಪೂರ್ಣವಾಗಿ ಬದಲಾಗದೆ ಬಿಡಲಾಯಿತು', 'ಇದೂ ಸಂಪೂರ್ಣವಾಗಿ state ಇಂದ ಸರಿಯಾಗಿ ತೆರವುಗೊಳಿಸಲಾಯಿತು, ಉಚ್ಚಾರಣೆ ಆ slot ಗಾಗಿ ಒಂದು negation ಪದಗುಚ್ಛಕ್ಕೆ ಹೊಂದಿಕೆಯಾದ ಕಾರಣ, cuisine ಮುಟ್ಟದೆ ಉಳಿಯುತ್ತಾ', 'ಇದೂ ಇಡೀ program ಅನ್ನೂ crash ಮಾಡಿತು', 'ಇದನ್ನೂ ಶೂನ್ಯಕ್ಕೆ ಹೊಂದಿಸಲಾಯಿತು'] },
      { q: 'What did the Pydantic RestaurantState schema do when given party_size="four people"?', qKn: 'party_size="four people" ನೀಡಿದಾಗ Pydantic RestaurantState schema ಏನನ್ನೂ ಮಾಡಿತು?',
        opts: ['It silently accepted the string and stored it as-is', 'It raised a clear ValidationError explaining that the input could not be parsed as an integer', 'It crashed the Python interpreter entirely', 'It automatically converted "four" to the integer 4'], correct: 1,
        optsKn: ['ಇದೂ string ಅನ್ನೂ ಮೌನವಾಗಿ ಸ್ವೀಕರಿಸಿ ಇರುವಂತೆ ಸಂಗ್ರಹಿಸಿತು', 'ಇದೂ ಇದನ್ನೂ ಒಂದು integer ಆಗಿ ಪಾರ್ಸ್ ಮಾಡಲಾಗಲಿಲ್ಲ ಎಂದು ವಿವರಿಸುವ ಒಂದು ಸ್ಪಷ್ಟ ValidationError ಎಬ್ಬಿಸಿತು', 'ಇದೂ Python interpreter ಅನ್ನೂ ಸಂಪೂರ್ಣವಾಗಿ crash ಮಾಡಿತು', 'ಇದೂ "four" ಅನ್ನೂ ಸ್ವಯಂಚಾಲಿತವಾಗಿ integer 4 ಗೆ ಪರಿವರ್ತಿಸಿತು'] },
      { q: 'Why is Joint Goal Accuracy considered a strict, unforgiving metric?', qKn: 'Joint Goal Accuracy ಅನ್ನೂ ಒಂದು ಕಠಿಣ, ಕ್ಷಮಿಸಲಾಗದ metric ಎಂದು ಏಕೆ ಪರಿಗಣಿಸಲಾಗುತ್ತದೆ?',
        opts: ['It gives partial credit for each individual correct slot', 'It requires the entire predicted state dictionary to exactly match the entire gold state for a turn to count as correct -- a single wrong or extra field zeroes the whole turn', 'It only evaluates the first slot in the state', 'It always returns a score of either 0 or 100'], correct: 1,
        optsKn: ['ಇದೂ ಪ್ರತಿ ವೈಯಕ್ತಿಕ ಸರಿಯಾದ slot ಗಾಗಿ ಭಾಗಶಃ ಕ್ರೆಡಿಟ್ ನೀಡುತ್ತದೆ', 'ಇದಕ್ಕೆ ಒಂದು turn ಅನ್ನೂ ಸರಿಯಾಗಿ ಎಣಿಸಲು ಸಂಪೂರ್ಣ predicted state dictionary ಸಂಪೂರ್ಣ gold state ಗೆ ನಿಖರವಾಗಿ ಹೊಂದಿಕೆಯಾಗಬೇಕು -- ಒಂದು ತಪ್ಪು ಅಥವಾ ಹೆಚ್ಚುವರಿ field ಇಡೀ turn ಅನ್ನೂ ಶೂನ್ಯಗೊಳಿಸುತ್ತದೆ', 'ಇದೂ ಕೇವಲ state ನಲ್ಲಿ ಮೊದಲ slot ಅನ್ನೂ ಮಾತ್ರ ಮೌಲ್ಯಮಾಪನ ಮಾಡುತ್ತದೆ', 'ಇದೂ ಯಾವಾಗಲೂ 0 ಅಥವಾ 100 ರ ಒಂದು ಸ್ಕೋರ್ ಹಿಂತಿರುಗಿಸುತ್ತದೆ'] },
      { q: 'Verified in this lesson: why did the 3-turn joint_goal_accuracy() example produce 0.667 rather than a higher score?', qKn: 'ಈ lesson ನಲ್ಲಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ: 3-turn joint_goal_accuracy() ಉದಾಹರಣೆ ಹೆಚ್ಚಿನ ಸ್ಕೋರ್ ಬದಲಿಗೆ 0.667 ಅನ್ನೂ ಏಕೆ ಉತ್ಪಾದಿಸಿತು?',
        opts: ['The function itself had a bug that miscalculated the score', 'Turn 3\'s prediction included an extra party_size field that the gold state for that turn did not have, so the entire turn counted as incorrect despite the cuisine field being right', 'All three turns were completely wrong', 'The gold states were empty for every turn'], correct: 1,
        optsKn: ['ಫಂಕ್ಷನ್ ಸ್ವತಃ ಸ್ಕೋರ್ ಅನ್ನೂ ತಪ್ಪಾಗಿ ಲೆಕ್ಕಹಾಕುವ ಒಂದು bug ಹೊಂದಿತ್ತು', 'Turn 3 ರ ಭವಿಷ್ಯ ಆ turn ಗಾಗಿ gold state ಹೊಂದಿರದ ಒಂದು ಹೆಚ್ಚುವರಿ party_size field ಒಳಗೊಂಡಿತ್ತು, ಆದ್ದರಿಂದ cuisine field ಸರಿಯಾಗಿದ್ದರೂ ಇಡೀ turn ತಪ್ಪು ಎಂದು ಎಣಿಸಲಾಯಿತು', 'ಎಲ್ಲಾ ಮೂರು turns ಗಳು ಸಂಪೂರ್ಣವಾಗಿ ತಪ್ಪಾಗಿದ್ದವು', 'ಪ್ರತಿ turn ಗೆ gold states ಗಳು ಖಾಲಿಯಾಗಿದ್ದವು'] },
      { q: 'Why was the llm_dst() function not executed in this lesson?', qKn: 'ಈ lesson ನಲ್ಲಿ llm_dst() ಫಂಕ್ಷನ್ ಅನ್ನೂ ಏಕೆ ಚಲಾಯಿಸಲಾಗಿಲ್ಲ?',
        opts: ['It contains an unfixable syntax error', 'It requires a live LLM call via instructor/OpenAI, and no API key is configured in this environment -- consistent with earlier lessons in this phase', 'The function does not actually exist in the DST literature', 'It was considered unimportant to the lesson'], correct: 1,
        optsKn: ['ಇದೂ ಸರಿಪಡಿಸಲಾಗದ syntax error ಒಳಗೊಂಡಿದೆ', 'ಇದಕ್ಕೆ instructor/OpenAI ಮೂಲಕ ಒಂದು live LLM ಕರೆ ಅಗತ್ಯ, ಮತ್ತು ಈ environment ನಲ್ಲಿ ಯಾವುದೇ API key ಸಂರಚಿಸಲಾಗಿಲ್ಲ -- ಈ ಹಂತದ ಹಿಂದಿನ ಲೆಸನ್‌ಗಳಿಗೆ ಸ್ಥಿರವಾಗಿ', 'ಫಂಕ್ಷನ್ DST ಸಾಹಿತ್ಯದಲ್ಲಿ ವಾಸ್ತವವಾಗಿ ಅಸ್ತಿತ್ವದಲ್ಲಿಲ್ಲ', 'ಇದನ್ನೂ lesson ಗೆ ಮುಖ್ಯವಲ್ಲ ಎಂದು ಪರಿಗಣಿಸಲಾಗಿತ್ತು'] },
      { q: 'What advantage does structured-output DST (LLM + validated schema) combine from both earlier approaches?', qKn: 'Structured-output DST (LLM + ಮೌಲ್ಯೀಕರಿಸಿದ schema) ಎರಡೂ ಹಿಂದಿನ ವಿಧಾನಗಳಿಂದ ಯಾವ ಪ್ರಯೋಜನ ಸಂಯೋಜಿಸುತ್ತದೆ?',
        opts: ['It combines the open-ended language understanding of generation-based DST with the guaranteed type-correctness of classification-based schema validation', 'It removes the need for any evaluation metrics entirely', 'It only works for closed-vocabulary slots, same as pure classification', 'It eliminates the need for dialogue state entirely'], correct: 0,
        optsKn: ['ಇದೂ generation-ಆಧಾರಿತ DST ನ ಮುಕ್ತ-ಅಂತ್ಯದ ಭಾಷಾ ತಿಳುವಳಿಕೆಯನ್ನೂ classification-ಆಧಾರಿತ schema validation ನ ಖಾತ್ರಿಪಡಿಸಿದ type-ಸರಿಯಾದತೆಯೊಂದಿಗೆ ಸಂಯೋಜಿಸುತ್ತದೆ', 'ಇದೂ ಯಾವುದೇ evaluation metrics ಗಳ ಅಗತ್ಯವನ್ನೂ ಸಂಪೂರ್ಣವಾಗಿ ತೆಗೆದುಹಾಕುತ್ತದೆ', 'ಇದೂ ಕೇವಲ closed-vocabulary slots ಗಳಿಗೆ ಮಾತ್ರ ಕೆಲಸ ಮಾಡುತ್ತದೆ, ಶುದ್ಧ classification ರೀತಿಯೇ', 'ಇದೂ dialogue state ನ ಅಗತ್ಯವನ್ನೂ ಸಂಪೂರ್ಣವಾಗಿ ತೆಗೆದುಹಾಕುತ್ತದೆ'] },
    ] } },
  ],
};
