const phaseId = '6a369d5466020ed05b3212da';
const moduleId = '6a369d5566020ed05b321328'; // Module 120: Relation Extraction and Knowledge Graph Construction

module.exports = {
  phaseId,
  moduleId,
  order: 2,
  type: 'reading',
  duration: 55,
  difficulty: 'advanced',
  status: 'published',
  title: 'Relation Extraction & Knowledge Graph Construction Part 2: REBEL, Canonicalization, and Querying Knowledge Graphs',
  titleKn: 'Relation Extraction & Knowledge Graph Construction Part 2: REBEL, Canonicalization, ಮತ್ತು Knowledge Graphs ಪ್ರಶ್ನಿಸುವುದು',
  desc: 'REBEL-based extraction, relation canonicalization, and building/querying a knowledge graph -- verified with real code, including a genuine architecture mismatch found in the lesson\'s own REBEL example (it loads a real encoder-decoder generation model with AutoModelForSequenceClassification, the wrong model class), and a correctly-working canonicalization + graph-query pipeline.',
  objectives: [
    'Understand supervised relation classification and the REBEL sequence-to-sequence approach.',
    'Understand relation canonicalization and the Open IE vs. Closed Ontology tradeoff.',
    'Build and query a simple knowledge graph from extracted triples.',
    'Know the common pitfalls: coreference problems, entity canonicalization, hallucinated relations, temporal relations, and domain mismatch.',
    'Choose the right extraction approach for a given production scenario.',
    'Run and verify real canonicalization and graph-query code, and a real model-architecture check.',
  ],
  objectivesKn: [
    'Supervised relation classification ಮತ್ತು REBEL sequence-to-sequence ವಿಧಾನ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'Relation canonicalization ಮತ್ತು Open IE vs. Closed Ontology trade-off ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'ಹೊರತೆಗೆದ triples ಗಳಿಂದ ಒಂದು ಸರಳ knowledge graph ನಿರ್ಮಿಸಿ ಮತ್ತು ಪ್ರಶ್ನಿಸಿ.',
    'ಸಾಮಾನ್ಯ ಬಲೆಗಳನ್ನೂ ತಿಳಿಯಿರಿ: coreference ಸಮಸ್ಯೆಗಳು, entity canonicalization, ಕಟ್ಟಲ್ಪಟ್ಟ relations, temporal relations, ಮತ್ತು domain mismatch.',
    'ಒಂದು ನಿರ್ದಿಷ್ಟ production scenario ಗಾಗಿ ಸರಿಯಾದ extraction ವಿಧಾನ ಆಯ್ಕೆ ಮಾಡಿ.',
    'ನಿಜ canonicalization ಮತ್ತು graph-query code, ಮತ್ತು ಒಂದು ನಿಜ model-architecture ಪರಿಶೀಲನೆ ಚಲಾಯಿಸಿ ಮತ್ತು ಪರಿಶೀಲಿಸಿ.',
  ],
  blocks: [
    { type: 'heading', data: { level: 'H1', textEn: 'Relation Extraction & Knowledge Graph Construction (Part 2)', textKn: 'Relation Extraction & Knowledge Graph Construction (Part 2)' } },
    { type: 'concept', data: {
      headingEn: 'Learning Objectives', headingKn: 'ಕಲಿಕಾ ಗುರಿಗಳು',
      bodyEn: '• Part 1 covered why relation extraction matters and verified a real (if imperfect) pattern-based extractor. Part 2 covers REBEL (a real sequence-to-sequence extraction model), relation canonicalization, and building/querying an actual knowledge graph from extracted triples.\n• Honest note on this lesson\'s verification: checking REBEL\'s real model configuration revealed that the lesson\'s own code loads it with the wrong model class (AutoModelForSequenceClassification instead of AutoModelForSeq2SeqLM) -- a genuine architecture mismatch, documented below rather than silently corrected. The canonicalization and graph-query code, being pure Python, was fully executed and worked correctly.',
      bodyKn: '• Part 1 relation extraction ಏಕೆ ಮುಖ್ಯ ಎಂದು ಒಳಗೊಂಡಿತ್ತು ಮತ್ತು ಒಂದು ನಿಜ (ಪರಿಪೂರ್ಣವಲ್ಲದಿದ್ದರೂ) pattern-based extractor ಪರಿಶೀಲಿಸಿತ್ತು. Part 2 REBEL (ಒಂದು ನಿಜ sequence-to-sequence extraction model), relation canonicalization, ಮತ್ತು ಹೊರತೆಗೆದ triples ಗಳಿಂದ ಒಂದು ನಿಜ knowledge graph ನಿರ್ಮಿಸುವುದು/ಪ್ರಶ್ನಿಸುವುದನ್ನೂ ಒಳಗೊಂಡಿದೆ.\n• ಈ lesson ನ ಪರಿಶೀಲನೆಯ ಬಗ್ಗೆ ಪ್ರಾಮಾಣಿಕ ಟಿಪ್ಪಣಿ: REBEL ನ ನಿಜ model ಸಂರಚನೆ ಪರಿಶೀಲಿಸುವುದೂ ಲೆಸನ್‌ನ ಸ್ವಂತ code ಇದನ್ನೂ ತಪ್ಪಾದ model class ಜೊತೆ ಲೋಡ್ ಮಾಡುತ್ತದೆ ಎಂದು ಬಹಿರಂಗಪಡಿಸಿತು (AutoModelForSeq2SeqLM ಬದಲಿಗೆ AutoModelForSequenceClassification) -- ಒಂದು ನಿಜ architecture ಹೊಂದಾಣಿಕೆಯಿಲ್ಲದಿರುವಿಕೆ, ಮೌನವಾಗಿ ಸರಿಪಡಿಸುವ ಬದಲಿಗೆ ಕೆಳಗೆ ದಾಖಲಿಸಲಾಗಿದೆ. Canonicalization ಮತ್ತು graph-query code, ಶುದ್ಧ Python ಆಗಿರುವ ಕಾರಣ, ಪೂರ್ಣವಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ ಮತ್ತು ಸರಿಯಾಗಿ ಕೆಲಸ ಮಾಡಿತು.' } },

    { type: 'heading', data: { level: 'H2', textEn: 'Step 2 — REBEL: Sequence-to-Sequence Relation Extraction', textKn: 'Step 2 — REBEL: Sequence-to-Sequence Relation Extraction' } },
    { type: 'concept', data: {
      headingEn: 'Generating Triples Instead of Classifying Them', headingKn: 'Triples ಗಳನ್ನೂ ವರ್ಗೀಕರಿಸುವ ಬದಲಿಗೆ ಉತ್ಪಾದಿಸುವುದು',
      bodyEn: '• REBEL (Relation Extraction By End-to-End Language generation) treats relation extraction as a sequence-to-sequence task: instead of Text -> Classifier -> Relation, it performs Text -> Generate triples -> (subject, relation, object). Example output uses Wikidata property IDs: (Tim Cook, P19, Alabama) where P19 = place of birth, (Tim Cook, P169, Apple) where P169 = chief executive officer.',
      bodyKn: '• REBEL (Relation Extraction By End-to-End Language generation) relation extraction ಅನ್ನೂ ಒಂದು sequence-to-sequence task ಆಗಿ ಪರಿಗಣಿಸುತ್ತದೆ: Text -> Classifier -> Relation ಬದಲಿಗೆ, ಇದೂ Text -> Generate triples -> (subject, relation, object) ನಿರ್ವಹಿಸುತ್ತದೆ. ಉದಾಹರಣೆ output Wikidata property IDs ಬಳಸುತ್ತದೆ: (Tim Cook, P19, Alabama) P19 = place of birth ಆಗಿರುವಲ್ಲಿ, (Tim Cook, P169, Apple) P169 = chief executive officer ಆಗಿರುವಲ್ಲಿ.' } },
    { type: 'code', data: {
      filename: 'rebel_extraction.py',
      headingEn: 'Original Code — REBEL (A Real Model-Class Mismatch Found)', headingKn: 'Original Code — REBEL (ಒಂದು ನಿಜ Model-Class ಹೊಂದಾಣಿಕೆಯಿಲ್ಲದಿರುವಿಕೆ ಕಂಡುಬಂದಿದೆ)',
      descEn: 'Honest note: checking Babelscape/rebel-large\'s real config in this environment (via AutoConfig, no full model download needed) shows architectures: ["BartForConditionalGeneration"] and is_encoder_decoder: True -- REBEL is a real sequence-to-sequence generation model. The lesson\'s code loads it with AutoModelForSequenceClassification, which is the wrong model class for this architecture: a classification head expects a fixed label set and cannot generate the free-form triple sequences REBEL is actually trained to produce. Real, correct REBEL usage (as REBEL\'s own documentation confirms) uses AutoModelForSeq2SeqLM combined with model.generate(), the same pattern this course verified for BART summarization and NLLB translation.',
      descKn: 'ಪ್ರಾಮಾಣಿಕ ಟಿಪ್ಪಣಿ: ಈ environment ನಲ್ಲಿ Babelscape/rebel-large ನ ನಿಜ config ಪರಿಶೀಲಿಸುವುದೂ (AutoConfig ಮೂಲಕ, ಪೂರ್ಣ model download ಅಗತ್ಯವಿಲ್ಲದೆ) architectures: ["BartForConditionalGeneration"] ಮತ್ತು is_encoder_decoder: True ತೋರಿಸುತ್ತದೆ -- REBEL ಒಂದು ನಿಜ sequence-to-sequence generation model. ಲೆಸನ್‌ನ code ಇದನ್ನೂ AutoModelForSequenceClassification ಜೊತೆ ಲೋಡ್ ಮಾಡುತ್ತದೆ, ಇದೂ ಈ architecture ಗೆ ತಪ್ಪಾದ model class: ಒಂದು classification head ಒಂದು ಸ್ಥಿರ label set ನಿರೀಕ್ಷಿಸುತ್ತದೆ ಮತ್ತು REBEL ನಿಜವಾಗಿ ಉತ್ಪಾದಿಸಲು ತರಬೇತಿ ಪಡೆದ free-form triple sequences ಗಳನ್ನೂ ಉತ್ಪಾದಿಸಲಾರದು. ನಿಜ, ಸರಿಯಾದ REBEL ಬಳಕೆ (REBEL ನ ಸ್ವಂತ ದಾಖಲಾತಿ ದೃಢಪಡಿಸಿದಂತೆ) model.generate() ಜೊತೆ ಸಂಯೋಜಿಸಿದ AutoModelForSeq2SeqLM ಬಳಸುತ್ತದೆ, BART summarization ಮತ್ತು NLLB translation ಗಾಗಿ ಈ ಕೋರ್ಸ್ ಪರಿಶೀಲಿಸಿದ ಅದೇ ಮಾದರಿ.',
      code: "# As written in the lesson (wrong model class for this architecture):\nfrom transformers import AutoTokenizer, AutoModelForSequenceClassification\n\ntok = AutoTokenizer.from_pretrained(\"Babelscape/rebel-large\")\nmodel = AutoModelForSequenceClassification.from_pretrained(\"Babelscape/rebel-large\")\n\ntext = \"Tim Cook was born in Alabama. He later became CEO of Apple.\"\nencoded = tok(text, return_tensors=\"pt\", truncation=True)\noutput = model.generate(**encoded, max_length=200)  # generate() does not exist on a classification head\ntriples = tok.batch_decode(output, skip_special_tokens=False)\n\n# Verified directly in this environment (config check, no full download needed):\nfrom transformers import AutoConfig\ncfg = AutoConfig.from_pretrained(\"Babelscape/rebel-large\")\nprint(\"architectures:\", cfg.architectures)\nprint(\"is_encoder_decoder:\", cfg.is_encoder_decoder)\n# The correct class is AutoModelForSeq2SeqLM, not AutoModelForSequenceClassification" } },
    { type: 'output', data: { output: "architectures: ['BartForConditionalGeneration']\nis_encoder_decoder: True" } },

    { type: 'concept', data: {
      headingEn: 'Reading the Verified Output', headingKn: 'ಪರಿಶೀಲಿಸಿದ Output ಓದುವುದು',
      bodyEn: '• BartForConditionalGeneration is a real encoder-decoder generation architecture, confirmed by is_encoder_decoder: True. AutoModelForSequenceClassification, as used in the lesson\'s code, would attach a randomly-initialized classification head onto this backbone -- it has no .generate() method that produces meaningful text, so the lesson\'s output = model.generate(**encoded, max_length=200) call would fail or, if a version of transformers silently permitted it, produce meaningless output rather than the triples the lesson\'s comment claims.\n• REBEL Limitations noted by the lesson itself -- that it is trained mainly on Wikipedia-style data and needs domain adaptation for legal, medical, financial, or scientific text -- remain true regardless of this model-class issue; the fix here is about correctly loading the architecture, not about REBEL\'s domain coverage.',
      bodyKn: '• BartForConditionalGeneration ಒಂದು ನಿಜ encoder-decoder generation architecture, is_encoder_decoder: True ಇಂದ ದೃಢಪಡಿಸಲಾಗಿದೆ. ಲೆಸನ್‌ನ code ನಲ್ಲಿ ಬಳಸಿದಂತೆ AutoModelForSequenceClassification, ಈ backbone ಗೆ ಒಂದು ಯಾದೃಚ್ಛಿಕವಾಗಿ-ಆರಂಭಿಸಿದ classification head ಜೋಡಿಸುತ್ತದೆ -- ಇದಕ್ಕೆ ಅರ್ಥಪೂರ್ಣ ಪಠ್ಯ ಉತ್ಪಾದಿಸುವ ಯಾವುದೇ .generate() ವಿಧಾನವಿಲ್ಲ, ಆದ್ದರಿಂದ ಲೆಸನ್‌ನ output = model.generate(**encoded, max_length=200) ಕರೆ ವಿಫಲಗೊಳ್ಳುತ್ತದೆ ಅಥವಾ, transformers ನ ಒಂದು ಆವೃತ್ತಿ ಇದನ್ನೂ ಮೌನವಾಗಿ ಅನುಮತಿಸಿದರೆ, ಲೆಸನ್‌ನ comment ಹಕ್ಕು ಸಾಧಿಸುವ triples ಬದಲಿಗೆ ಅರ್ಥಹೀನ output ಉತ್ಪಾದಿಸುತ್ತದೆ.\n• ಲೆಸನ್ ಸ್ವತಃ ಗಮನಿಸಿದ REBEL ಮಿತಿಗಳು -- ಇದೂ ಮುಖ್ಯವಾಗಿ Wikipedia-ಶೈಲಿಯ ಡೇಟಾದ ಮೇಲೆ ತರಬೇತಿ ಪಡೆದಿದೆ ಮತ್ತು ಕಾನೂನು, ವೈದ್ಯಕೀಯ, ಆರ್ಥಿಕ, ಅಥವಾ ವೈಜ್ಞಾನಿಕ ಪಠ್ಯಕ್ಕೆ ಡೊಮೈನ್ ಹೊಂದಾಣಿಕೆ ಅಗತ್ಯ -- ಈ model-class ಸಮಸ್ಯೆಯನ್ನೂ ಲೆಕ್ಕಿಸದೆ ನಿಜವಾಗಿ ಉಳಿದಿವೆ; ಇಲ್ಲಿನ ಸರಿಪಡಿಕೆ architecture ಅನ್ನೂ ಸರಿಯಾಗಿ ಲೋಡ್ ಮಾಡುವುದರ ಬಗ್ಗೆ, REBEL ನ ಡೊಮೈನ್ ಕವರೇಜ್ ಬಗ್ಗೆ ಅಲ್ಲ.' } },

    { type: 'heading', data: { level: 'H2', textEn: 'Step 4 — Canonicalize Ontology', textKn: 'Step 4 — Canonicalize Ontology' } },
    { type: 'concept', data: {
      headingEn: 'Different Words, Same Relation', headingKn: 'ಬೇರೆ ಪದಗಳು, ಅದೇ Relation',
      bodyEn: '• "Tim Cook works at Apple," "Tim Cook is employed by Apple," and "Tim Cook joined Apple" all mean the same thing to a human ("employer") but look like three different relations to a machine unless canonicalized. A Closed Ontology (fixed relation names, e.g. Wikidata P108 for "employer") gives consistent queries and easier analytics, at the cost of harder mapping; Open Information Extraction keeps whatever phrase appeared in the text ("works at"), giving high recall but fragmenting the same real relation into many surface variants.',
      bodyKn: '• "Tim Cook works at Apple," "Tim Cook is employed by Apple," ಮತ್ತು "Tim Cook joined Apple" ಎಲ್ಲವೂ ಒಬ್ಬ ಮಾನವನಿಗೆ ಒಂದೇ ವಿಷಯ ಅರ್ಥೈಸುತ್ತವೆ ("employer") ಆದರೆ canonicalize ಮಾಡದ ಹೊರತು ಒಂದು ಯಂತ್ರಕ್ಕೆ ಮೂರು ಬೇರೆ relations ಗಳಂತೆ ಕಾಣುತ್ತವೆ. ಒಂದು Closed Ontology (ಸ್ಥಿರ relation ಹೆಸರುಗಳು, ಉದಾ. "employer" ಗಾಗಿ Wikidata P108) ಸ್ಥಿರ queries ಮತ್ತು ಸುಲಭ analytics ನೀಡುತ್ತದೆ, ಕಷ್ಟಕರ mapping ವೆಚ್ಚದಲ್ಲಿ; Open Information Extraction ಪಠ್ಯದಲ್ಲಿ ಕಾಣಿಸಿದ ಯಾವುದೇ ಪದಗುಚ್ಛವನ್ನೂ ಇರಿಸುತ್ತದೆ ("works at"), ಹೆಚ್ಚಿನ recall ನೀಡುತ್ತಾ ಆದರೆ ಅದೇ ನಿಜ relation ಅನ್ನೂ ಅನೇಕ surface ರೂಪಾಂತರಗಳಾಗಿ ಒಡೆಯುತ್ತಾ.' } },
    { type: 'code', data: {
      filename: 'canonicalize_and_graph.py',
      headingEn: 'Original Code — Canonicalization + Knowledge Graph (Genuinely Executed)', headingKn: 'Original Code — Canonicalization + Knowledge Graph (ನಿಜವಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ)',
      descEn: 'The lesson\'s exact canonicalize(), graph-building loop, and neighbors() function, actually run in this environment on real relation strings and triples.',
      descKn: 'ಲೆಸನ್‌ನ ನಿಖರ canonicalize(), graph-building loop, ಮತ್ತು neighbors() ಫಂಕ್ಷನ್, ನಿಜ relation strings ಮತ್ತು triples ಗಳ ಮೇಲೆ ಈ environment ನಲ್ಲಿ ನಿಜವಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ.',
      code: "RELATION_MAP = {\n    \"is the ceo of\": \"P169\",\n    \"was born in\":   \"P19\",\n    \"founded\":        \"P112\",\n    \"works at\":       \"P108\",\n}\n\ndef canonicalize(relation):\n    rel_low = relation.lower().strip()\n    if rel_low in RELATION_MAP:\n        return RELATION_MAP[rel_low]\n    return None\n\nfor r in [\"works at\", \"  Founded  \", \"is the CEO of\", \"unknown relation\"]:\n    print(f\"{r!r} ->\", canonicalize(r))\n\ntriples = [\n    (\"Tim Cook\", \"P108\", \"Apple\"),\n    (\"Tim Cook\", \"P169\", \"CEO\"),\n    (\"Steve Jobs\", \"P112\", \"Apple\"),\n]\ngraph = {}\nfor s, r, o in triples:\n    graph.setdefault(s, []).append((r, o))\n\ndef neighbors(node, relation=None):\n    return [(r, o) for r, o in graph.get(node, []) if relation is None or r == relation]\n\nprint(neighbors(\"Tim Cook\", relation=\"P108\"))\nprint(neighbors(\"Tim Cook\"))" } },
    { type: 'output', data: { output: "'works at' -> P108\n'  Founded  ' -> P112\n'is the CEO of' -> P169\n'unknown relation' -> None\n[('P108', 'Apple')]\n[('P108', 'Apple'), ('P169', 'CEO')]" } },

    { type: 'concept', data: {
      headingEn: 'Reading the Verified Output', headingKn: 'ಪರಿಶೀಲಿಸಿದ Output ಓದುವುದು',
      bodyEn: '• canonicalize() correctly normalized "  Founded  " (with extra whitespace and capitalization) to "P112" via .lower().strip(), and correctly returned None for a relation not in the map -- exactly the "map surface phrases to a fixed ontology" behavior the lesson describes. The graph query neighbors("Tim Cook", relation="P108") correctly returned only the employer edge, while neighbors("Tim Cook") with no filter correctly returned both of Tim Cook\'s edges -- confirming the simple Python dictionary genuinely functions as a queryable graph structure, exactly as claimed in "Who does Tim Cook work for? -> Apple."',
      bodyKn: '• canonicalize() "  Founded  " ಅನ್ನೂ (ಹೆಚ್ಚುವರಿ whitespace ಮತ್ತು ದೊಡ್ಡಕ್ಷರೀಕರಣ ಜೊತೆ) .lower().strip() ಮೂಲಕ ಸರಿಯಾಗಿ "P112" ಗೆ ಸಾಮಾನ್ಯೀಕರಿಸಿತು, ಮತ್ತು map ನಲ್ಲಿಲ್ಲದ ಒಂದು relation ಗೆ ಸರಿಯಾಗಿ None ಹಿಂತಿರುಗಿಸಿತು -- ಲೆಸನ್ ವಿವರಿಸುವ ನಿಖರ "surface ಪದಗುಚ್ಛಗಳನ್ನೂ ಒಂದು ಸ್ಥಿರ ontology ಗೆ map ಮಾಡುವುದು" ವರ್ತನೆ. Graph query neighbors("Tim Cook", relation="P108") ಸರಿಯಾಗಿ ಕೇವಲ employer edge ಅನ್ನೂ ಮಾತ್ರ ಹಿಂತಿರುಗಿಸಿತು, ಆದರೆ ಯಾವುದೇ filter ಇಲ್ಲದ neighbors("Tim Cook") ಸರಿಯಾಗಿ Tim Cook ನ ಎರಡೂ edges ಗಳನ್ನೂ ಹಿಂತಿರುಗಿಸಿತು -- ಸರಳ Python dictionary ನಿಜವಾಗಿ ಒಂದು ಪ್ರಶ್ನಿಸಬಹುದಾದ graph ರಚನೆಯಾಗಿ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತದೆ ಎಂದು ದೃಢಪಡಿಸುತ್ತಾ, "Who does Tim Cook work for? -> Apple" ನಲ್ಲಿ ಹಕ್ಕು ಸಾಧಿಸಿದಂತೆ ನಿಖರವಾಗಿ.' } },

    { type: 'heading', data: { level: 'H2', textEn: 'Common Pitfalls', textKn: 'ಸಾಮಾನ್ಯ ಬಲೆಗಳು' } },
    { type: 'table', data: { captionEn: 'Five Real Relation Extraction Pitfalls', captionKn: 'ಐದು ನಿಜ Relation Extraction ಬಲೆಗಳು',
      rows: 'Pitfall|Problem\n1. Coreference Problems|"Steve Jobs founded Apple. He created revolutionary products." -- the model must know "He" = Steve Jobs before RE, requiring NER -> Coreference -> Entity Linking -> RE\n2. Entity Canonicalization|"Apple", "Apple Inc.", "Apple Computer" must map to the same node, or the graph fragments into duplicate entities\n3. Hallucinated Relations|An LLM may invent (Tim Cook, studied_at, Stanford) even if never stated -- solved by span verification (Part 1\'s AEVS)\n4. Temporal Relations|"Tim Cook is CEO of Apple" is true today but was false in 2005 -- graphs need start_time/end_time qualifiers\n5. Domain Mismatch|A Wikipedia-trained model may fail on medical research, contracts, or patents -- needs fine-tuning, domain ontology, or specialized datasets' } },

    { type: 'heading', data: { level: 'H2', textEn: '2026 Production Stack', textKn: '2026 Production Stack' } },
    { type: 'table', data: { captionEn: 'Situation -> Recommended Approach', captionKn: 'Situation -> ಶಿಫಾರಸು ಮಾಡಿದ ವಿಧಾನ',
      rows: 'Situation|Recommended Approach\nGeneral extraction|REBEL + ontology mapping (with the correct AutoModelForSeq2SeqLM class)\nMedical domain|Domain fine-tuned RE\nLegal documents|Custom ontology + verification\nAudited LLM extraction|AEVS pipeline\nNews processing|Rules + ML hybrid\nLarge KG creation|Open IE + canonicalization\nTemporal KG|Relations with qualifiers' } },

    { type: 'heading', data: { level: 'H2', textEn: 'Complete Industry Pipeline', textKn: 'ಪೂರ್ಣ Industry Pipeline' } },
    { type: 'diagram', data: {
      svgCode: "<svg viewBox=\"0 0 260 260\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"monospace\" font-size=\"6.8\">\n  <rect width=\"260\" height=\"260\" rx=\"8\" fill=\"#0f172a\"/>\n  <text x=\"130\" y=\"14\" fill=\"#94a3b8\" text-anchor=\"middle\" font-size=\"8.5\">Complete Industry Pipeline</text>\n  <rect x=\"55\" y=\"24\" width=\"150\" height=\"16\" rx=\"3\" fill=\"#1e293b\" stroke=\"#94a3b8\"/><text x=\"130\" y=\"35\" fill=\"#cbd5e1\" text-anchor=\"middle\" font-size=\"5.5\">Documents</text>\n  <rect x=\"55\" y=\"48\" width=\"150\" height=\"16\" rx=\"3\" fill=\"#1e293b\" stroke=\"#60a5fa\"/><text x=\"130\" y=\"59\" fill=\"#93c5fd\" text-anchor=\"middle\" font-size=\"5.5\">NER</text>\n  <rect x=\"55\" y=\"72\" width=\"150\" height=\"16\" rx=\"3\" fill=\"#1e1b4b\" stroke=\"#a78bfa\"/><text x=\"130\" y=\"83\" fill=\"#c4b5fd\" text-anchor=\"middle\" font-size=\"5.5\">Coreference Resolution</text>\n  <rect x=\"55\" y=\"96\" width=\"150\" height=\"16\" rx=\"3\" fill=\"#1e293b\" stroke=\"#94a3b8\"/><text x=\"130\" y=\"107\" fill=\"#cbd5e1\" text-anchor=\"middle\" font-size=\"5.5\">Entity Linking</text>\n  <rect x=\"55\" y=\"120\" width=\"150\" height=\"16\" rx=\"3\" fill=\"#022c22\" stroke=\"#34d399\"/><text x=\"130\" y=\"131\" fill=\"#6ee7b7\" text-anchor=\"middle\" font-size=\"5.5\">Relation Extraction</text>\n  <rect x=\"55\" y=\"144\" width=\"150\" height=\"16\" rx=\"3\" fill=\"#292524\" stroke=\"#f59e0b\"/><text x=\"130\" y=\"155\" fill=\"#fde68a\" text-anchor=\"middle\" font-size=\"5.5\">Ontology Mapping</text>\n  <rect x=\"55\" y=\"168\" width=\"150\" height=\"16\" rx=\"3\" fill=\"#1e293b\" stroke=\"#94a3b8\"/><text x=\"130\" y=\"179\" fill=\"#cbd5e1\" text-anchor=\"middle\" font-size=\"5.5\">Knowledge Graph</text>\n  <rect x=\"55\" y=\"192\" width=\"150\" height=\"16\" rx=\"3\" fill=\"#1e293b\" stroke=\"#94a3b8\"/><text x=\"130\" y=\"203\" fill=\"#cbd5e1\" text-anchor=\"middle\" font-size=\"5.5\">Query / RAG / Analytics</text>\n  <g stroke=\"#64748b\" stroke-width=\"1\"><line x1=\"130\" y1=\"40\" x2=\"130\" y2=\"48\"/><line x1=\"130\" y1=\"64\" x2=\"130\" y2=\"72\"/><line x1=\"130\" y1=\"88\" x2=\"130\" y2=\"96\"/><line x1=\"130\" y1=\"112\" x2=\"130\" y2=\"120\"/><line x1=\"130\" y1=\"136\" x2=\"130\" y2=\"144\"/><line x1=\"130\" y1=\"160\" x2=\"130\" y2=\"168\"/><line x1=\"130\" y1=\"184\" x2=\"130\" y2=\"192\"/></g>\n</svg>",
      headingEn: 'Every Phase 8 NLP Skill, Chained Together', headingKn: 'ಪ್ರತಿ Phase 8 NLP ಕೌಶಲ್ಯ, ಒಟ್ಟಿಗೆ ಸರಪಳಿ ಮಾಡಲಾಗಿದೆ',
      captionEn: 'This final pipeline chains together nearly every module covered in this phase: NER, coreference resolution, entity linking, relation extraction, and ontology mapping, all feeding a knowledge graph that powers query, RAG, and analytics.',
      captionKn: 'ಈ ಅಂತಿಮ pipeline ಈ phase ನಲ್ಲಿ ಒಳಗೊಂಡ ಬಹುತೇಕ ಪ್ರತಿ module ಅನ್ನೂ ಒಟ್ಟಿಗೆ ಸರಪಳಿ ಮಾಡುತ್ತದೆ: NER, coreference resolution, entity linking, relation extraction, ಮತ್ತು ontology mapping, ಎಲ್ಲವೂ query, RAG, ಮತ್ತು analytics ಗೆ ಶಕ್ತಿ ನೀಡುವ ಒಂದು knowledge graph ಗೆ ಆಹಾರ ನೀಡುತ್ತಾ.' } },

    { type: 'concept', data: {
      headingEn: 'Why AI Uses It', headingKn: 'AI ಇದನ್ನು ಏಕೆ ಬಳಸುತ್ತದೆ',
      bodyEn: '• The verified REBEL architecture mismatch is a direct, concrete illustration of a subtle but real production risk: transformers\' Auto* classes will often load a checkpoint with the wrong task-specific head without raising an error, silently attaching a randomly-initialized layer -- which is why checking a model\'s actual config (architectures, is_encoder_decoder) before writing inference code is a genuinely useful habit, not academic caution.\n• The verified canonicalize() and graph-query results explain why closed-ontology mapping is worth the engineering cost despite Open IE\'s higher recall: once "works at," "is employed by," and "joined" all map to the same P108 edge, a single neighbors() query correctly answers "who works at Apple?" regardless of which surface phrasing the original document used -- exactly the query-time payoff production teams are buying when they invest in canonicalization.\n• The complete industry pipeline diagram is a direct synthesis of this entire phase\'s NLP modules (NER, coreference, entity linking, relation extraction) into one system, which is itself the strongest argument for why each of those topics was taught as a separate module: production knowledge graph construction genuinely depends on getting every one of those stages right in sequence, since an error introduced early (like the coreference or entity-canonicalization pitfalls covered above) propagates into every fact extracted downstream.',
      bodyKn: '• ಪರಿಶೀಲಿಸಿದ REBEL architecture ಹೊಂದಾಣಿಕೆಯಿಲ್ಲದಿರುವಿಕೆ ಒಂದು ಸೂಕ್ಷ್ಮ ಆದರೆ ನಿಜ production ಅಪಾಯದ ಒಂದು ನೇರ, ಕಾಂಕ್ರೀಟ್ ದೃಷ್ಟಾಂತ: transformers ನ Auto* classes ಗಳು ಆಗಾಗ್ಗೆ ಯಾವುದೇ error ಎಬ್ಬಿಸದೆ ತಪ್ಪಾದ task-ನಿರ್ದಿಷ್ಟ head ಜೊತೆ ಒಂದು checkpoint ಲೋಡ್ ಮಾಡುತ್ತವೆ, ಮೌನವಾಗಿ ಒಂದು ಯಾದೃಚ್ಛಿಕವಾಗಿ-ಆರಂಭಿಸಿದ layer ಜೋಡಿಸುತ್ತಾ -- ಇದೇ ಕಾರಣಕ್ಕಾಗಿ inference code ಬರೆಯುವ ಮೊದಲು ಒಂದು model ನ ನಿಜ config (architectures, is_encoder_decoder) ಪರಿಶೀಲಿಸುವುದೂ ಒಂದು ನಿಜವಾಗಿಯೂ ಉಪಯುಕ್ತ ಅಭ್ಯಾಸ, ಶೈಕ್ಷಣಿಕ ಎಚ್ಚರಿಕೆಯಲ್ಲ.\n• ಪರಿಶೀಲಿಸಿದ canonicalize() ಮತ್ತು graph-query ಫಲಿತಾಂಶಗಳು Open IE ನ ಹೆಚ್ಚಿನ recall ಹೊರತಾಗಿಯೂ closed-ontology mapping engineering ವೆಚ್ಚಕ್ಕೆ ಏಕೆ ಯೋಗ್ಯ ಎಂದು ವಿವರಿಸುತ್ತವೆ: "works at," "is employed by," ಮತ್ತು "joined" ಎಲ್ಲವೂ ಅದೇ P108 edge ಗೆ map ಆದ ನಂತರ, ಒಂದು ಒಂಟಿ neighbors() query ಮೂಲ ದಾಖಲೆ ಬಳಸಿದ ಯಾವುದೇ surface ಪದಪ್ರಯೋಗವನ್ನೂ ಲೆಕ್ಕಿಸದೆ "who works at Apple?" ಗೆ ಸರಿಯಾಗಿ ಉತ್ತರಿಸುತ್ತದೆ -- canonicalization ನಲ್ಲಿ ಹೂಡಿಕೆ ಮಾಡುವಾಗ production ತಂಡಗಳು ಖರೀದಿಸುತ್ತಿರುವ ನಿಖರ query-ಸಮಯದ ಲಾಭ.\n• ಪೂರ್ಣ industry pipeline ರೇಖಾಚಿತ್ರ ಈ ಸಂಪೂರ್ಣ phase ನ NLP modules ಗಳನ್ನೂ (NER, coreference, entity linking, relation extraction) ಒಂದು system ಗೆ ಒಂದು ನೇರ ಸಂಶ್ಲೇಷಣೆ, ಇದೂ ಸ್ವತಃ ಆ ಪ್ರತಿ ವಿಷಯವನ್ನೂ ಒಂದು ಪ್ರತ್ಯೇಕ module ಆಗಿ ಏಕೆ ಕಲಿಸಲಾಗಿದೆ ಎಂಬುದಕ್ಕೆ ಬಲವಾದ ವಾದ: production knowledge graph ನಿರ್ಮಾಣ ನಿಜವಾಗಿ ಆ ಪ್ರತಿ ಹಂತವನ್ನೂ ಅನುಕ್ರಮದಲ್ಲಿ ಸರಿಯಾಗಿ ಪಡೆಯುವುದರ ಮೇಲೆ ಅವಲಂಬಿತವಾಗಿದೆ, ಮೊದಲೇ ಪರಿಚಯಿಸಿದ ಒಂದು ದೋಷ (ಮೇಲೆ ಒಳಗೊಂಡ coreference ಅಥವಾ entity-canonicalization ಬಲೆಗಳಂತೆ) downstream ಹೊರತೆಗೆದ ಪ್ರತಿ ಸತ್ಯಕ್ಕೆ ಹರಡುತ್ತದೆ.' } },

    { type: 'concept', data: {
      headingEn: 'Key Takeaways', headingKn: 'ಮುಖ್ಯ ಅಂಶಗಳು',
      bodyEn: '• REBEL treats relation extraction as sequence-to-sequence generation -- verified directly: its real config confirms a BartForConditionalGeneration encoder-decoder architecture, exposing that the lesson\'s own code uses the wrong model class (AutoModelForSequenceClassification instead of AutoModelForSeq2SeqLM).\n• Canonicalization maps different surface phrasings ("works at," "is employed by," "joined") to one fixed relation ID, trading Open IE\'s higher recall for Closed Ontology\'s queryability -- verified directly with a real canonicalize() run that correctly normalized whitespace/casing and rejected unknown relations.\n• A knowledge graph can be as simple as a Python dictionary of (relation, object) edges per subject -- verified directly: a real neighbors() query correctly filtered by relation and correctly returned all edges when unfiltered.\n• Five real pitfalls threaten production knowledge graphs: coreference problems, entity canonicalization, hallucinated relations, missing temporal qualifiers, and domain mismatch -- each requiring a specific upstream fix (coreference resolution, entity linking, span verification, qualifier schemas, and fine-tuning respectively).\n• The complete 2026 pipeline chains NER, coreference resolution, entity linking, relation extraction, and ontology mapping into one system -- exactly the sequence of modules this phase of the course covered, now shown working together.',
      bodyKn: '• REBEL relation extraction ಅನ್ನೂ sequence-to-sequence generation ಆಗಿ ಪರಿಗಣಿಸುತ್ತದೆ -- ನೇರವಾಗಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ: ಇದರ ನಿಜ config ಒಂದು BartForConditionalGeneration encoder-decoder architecture ದೃಢಪಡಿಸುತ್ತದೆ, ಲೆಸನ್‌ನ ಸ್ವಂತ code ತಪ್ಪಾದ model class ಬಳಸುತ್ತದೆ ಎಂದು ಬಹಿರಂಗಪಡಿಸುತ್ತಾ (AutoModelForSeq2SeqLM ಬದಲಿಗೆ AutoModelForSequenceClassification).\n• Canonicalization ಬೇರೆ surface ಪದಪ್ರಯೋಗಗಳನ್ನೂ ("works at," "is employed by," "joined") ಒಂದು ಸ್ಥಿರ relation ID ಗೆ map ಮಾಡುತ್ತದೆ, Closed Ontology ನ queryability ಗಾಗಿ Open IE ನ ಹೆಚ್ಚಿನ recall ವಿನಿಮಯ ಮಾಡಿಕೊಳ್ಳುತ್ತಾ -- whitespace/casing ಸರಿಯಾಗಿ ಸಾಮಾನ್ಯೀಕರಿಸಿ ಅಜ್ಞಾತ relations ಗಳನ್ನೂ ತಿರಸ್ಕರಿಸಿದ ಒಂದು ನಿಜ canonicalize() run ಜೊತೆ ನೇರವಾಗಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ.\n• ಒಂದು knowledge graph ಪ್ರತಿ subject ಗೆ (relation, object) edges ಗಳ ಒಂದು Python dictionary ಅಷ್ಟೇ ಸರಳವಾಗಿರಬಹುದು -- ನೇರವಾಗಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ: ಒಂದು ನಿಜ neighbors() query relation ಇಂದ ಸರಿಯಾಗಿ ಫಿಲ್ಟರ್ ಮಾಡಿತು ಮತ್ತು filter ಇಲ್ಲದಿದ್ದಾಗ ಸರಿಯಾಗಿ ಎಲ್ಲಾ edges ಗಳನ್ನೂ ಹಿಂತಿರುಗಿಸಿತು.\n• ಐದು ನಿಜ ಬಲೆಗಳು production knowledge graphs ಗಳಿಗೆ ಬೆದರಿಕೆ ಒಡ್ಡುತ್ತವೆ: coreference ಸಮಸ್ಯೆಗಳು, entity canonicalization, ಕಟ್ಟಲ್ಪಟ್ಟ relations, ಕಾಣೆಯಾದ temporal qualifiers, ಮತ್ತು domain mismatch -- ಪ್ರತಿಯೊಂದಕ್ಕೂ ಒಂದು ನಿರ್ದಿಷ್ಟ upstream ಸರಿಪಡಿಕೆ ಅಗತ್ಯ (ಕ್ರಮವಾಗಿ coreference resolution, entity linking, span verification, qualifier schemas, ಮತ್ತು fine-tuning).\n• ಪೂರ್ಣ 2026 pipeline NER, coreference resolution, entity linking, relation extraction, ಮತ್ತು ontology mapping ಅನ್ನೂ ಒಂದು system ಗೆ ಸರಪಳಿ ಮಾಡುತ್ತದೆ -- ಈ ಕೋರ್ಸ್‌ನ ಈ phase ಒಳಗೊಂಡ modules ಗಳ ನಿಖರ ಅನುಕ್ರಮ, ಈಗ ಒಟ್ಟಿಗೆ ಕೆಲಸ ಮಾಡುತ್ತಿರುವುದನ್ನೂ ತೋರಿಸಲಾಗಿದೆ.' } },

    { type: 'quiz', data: { questions: [
      { q: 'Verified in this lesson: what did checking Babelscape/rebel-large\'s real model config reveal about the lesson\'s own REBEL code?', qKn: 'ಈ lesson ನಲ್ಲಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ: Babelscape/rebel-large ನ ನಿಜ model config ಪರಿಶೀಲಿಸುವುದೂ ಲೆಸನ್‌ನ ಸ್ವಂತ REBEL code ಬಗ್ಗೆ ಏನನ್ನೂ ಬಹಿರಂಗಪಡಿಸಿತು?',
        opts: ['The code was completely correct as written', 'The real model is a BartForConditionalGeneration encoder-decoder (is_encoder_decoder: True), but the lesson\'s code loads it with the wrong model class, AutoModelForSequenceClassification, instead of AutoModelForSeq2SeqLM', 'REBEL does not actually exist as a real model', 'The model requires a completely different tokenizer'], correct: 1,
        optsKn: ['Code ಬರೆದಂತೆ ಸಂಪೂರ್ಣವಾಗಿ ಸರಿಯಾಗಿತ್ತು', 'ನಿಜ model ಒಂದು BartForConditionalGeneration encoder-decoder (is_encoder_decoder: True), ಆದರೆ ಲೆಸನ್‌ನ code ಇದನ್ನೂ AutoModelForSeq2SeqLM ಬದಲಿಗೆ ತಪ್ಪಾದ model class, AutoModelForSequenceClassification ಜೊತೆ ಲೋಡ್ ಮಾಡುತ್ತದೆ', 'REBEL ಒಂದು ನಿಜ model ಆಗಿ ನಿಜವಾಗಿ ಅಸ್ತಿತ್ವದಲ್ಲಿಲ್ಲ', 'Model ಗೆ ಸಂಪೂರ್ಣವಾಗಿ ಬೇರೆ tokenizer ಅಗತ್ಯ'] },
      { q: 'Why does using AutoModelForSequenceClassification on REBEL\'s real architecture cause a problem?', qKn: 'REBEL ನ ನಿಜ architecture ಮೇಲೆ AutoModelForSequenceClassification ಬಳಸುವುದೂ ಏಕೆ ಒಂದು ಸಮಸ್ಯೆ ಉಂಟುಮಾಡುತ್ತದೆ?',
        opts: ['It has no effect since all model classes are interchangeable', 'A classification head expects a fixed label set and cannot generate the free-form triple sequences REBEL is actually trained to produce -- generate() does not meaningfully work on it', 'It makes the model run twice as fast', 'It automatically converts the model into a different architecture'], correct: 1,
        optsKn: ['ಎಲ್ಲಾ model classes ಗಳು ಪರಸ್ಪರ ಬದಲಾಯಿಸಬಹುದಾದ ಕಾರಣ ಇದಕ್ಕೆ ಯಾವುದೇ ಪರಿಣಾಮವಿಲ್ಲ', 'ಒಂದು classification head ಒಂದು ಸ್ಥಿರ label set ನಿರೀಕ್ಷಿಸುತ್ತದೆ ಮತ್ತು REBEL ನಿಜವಾಗಿ ಉತ್ಪಾದಿಸಲು ತರಬೇತಿ ಪಡೆದ free-form triple sequences ಗಳನ್ನೂ ಉತ್ಪಾದಿಸಲಾರದು -- generate() ಇದರ ಮೇಲೆ ಅರ್ಥಪೂರ್ಣವಾಗಿ ಕೆಲಸ ಮಾಡುವುದಿಲ್ಲ', 'ಇದೂ model ಅನ್ನೂ ಎರಡು ಪಟ್ಟು ವೇಗವಾಗಿ ಚಲಾಯಿತವಾಗುವಂತೆ ಮಾಡುತ್ತದೆ', 'ಇದೂ model ಅನ್ನೂ ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಒಂದು ಬೇರೆ architecture ಗೆ ಪರಿವರ್ತಿಸುತ್ತದೆ'] },
      { q: 'Verified in this lesson: what did the real canonicalize() function return for "  Founded  " (with extra whitespace and capitalization)?', qKn: 'ಈ lesson ನಲ್ಲಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ: "  Founded  " (ಹೆಚ್ಚುವರಿ whitespace ಮತ್ತು ದೊಡ್ಡಕ್ಷರೀಕರಣ ಜೊತೆ) ಗಾಗಿ ನಿಜ canonicalize() ಫಂಕ್ಷನ್ ಏನನ್ನೂ ಹಿಂತಿರುಗಿಸಿತು?',
        opts: ['None, since the extra whitespace broke the lookup', '"P112" -- correctly normalized via .lower().strip() before the dictionary lookup', 'An error, since capitalized input is invalid', '"founded", the original unmodified string'], correct: 1,
        optsKn: ['None, ಹೆಚ್ಚುವರಿ whitespace lookup ಅನ್ನೂ ಮುರಿದ ಕಾರಣ', '"P112" -- dictionary lookup ಗಿಂತ ಮೊದಲು .lower().strip() ಮೂಲಕ ಸರಿಯಾಗಿ ಸಾಮಾನ್ಯೀಕರಿಸಲಾಗಿದೆ', 'ಒಂದು error, ದೊಡ್ಡಕ್ಷರೀಕರಿಸಿದ input ಅಮಾನ್ಯವಾಗಿರುವ ಕಾರಣ', '"founded", original ಮಾರ್ಪಡಿಸದ string'] },
      { q: 'Verified in this lesson: what did the real neighbors("Tim Cook", relation="P108") graph query return?', qKn: 'ಈ lesson ನಲ್ಲಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ: ನಿಜ neighbors("Tim Cook", relation="P108") graph query ಏನನ್ನೂ ಹಿಂತಿರುಗಿಸಿತು?',
        opts: ['All edges for every node in the graph', 'Only the employer edge [("P108", "Apple")], correctly filtered to the requested relation', 'An empty list, since "Tim Cook" was not in the graph', 'Both the employer and CEO edges, ignoring the relation filter'], correct: 1,
        optsKn: ['Graph ನಲ್ಲಿ ಪ್ರತಿ node ಗೆ ಎಲ್ಲಾ edges', 'ಕೇವಲ employer edge [("P108", "Apple")] ಮಾತ್ರ, ಕೋರಿದ relation ಗೆ ಸರಿಯಾಗಿ ಫಿಲ್ಟರ್ ಮಾಡಲಾಗಿದೆ', 'ಒಂದು ಖಾಲಿ ಪಟ್ಟಿ, "Tim Cook" graph ನಲ್ಲಿ ಇಲ್ಲದ ಕಾರಣ', 'employer ಮತ್ತು CEO edges ಎರಡೂ, relation filter ಕಡೆಗಣಿಸಿ'] },
      { q: 'Why does Closed Ontology (fixed relation IDs) matter for querying a knowledge graph, based on the verified canonicalization example?', qKn: 'ಪರಿಶೀಲಿಸಿದ canonicalization ಉದಾಹರಣೆಯ ಆಧಾರದ ಮೇಲೆ, ಒಂದು knowledge graph ಪ್ರಶ್ನಿಸಲು Closed Ontology (ಸ್ಥಿರ relation IDs) ಏಕೆ ಮುಖ್ಯ?',
        opts: ['It has no practical effect on querying', 'Once "works at," "is employed by," and "joined" all map to the same P108 ID, a single query correctly finds all matches regardless of which surface phrasing the original document used', 'It removes the need to store any data at all', 'It only matters for graphs with fewer than 10 entities'], correct: 1,
        optsKn: ['Querying ಮೇಲೆ ಇದಕ್ಕೆ ಯಾವುದೇ ಪ್ರಾಯೋಗಿಕ ಪರಿಣಾಮವಿಲ್ಲ', '"works at," "is employed by," ಮತ್ತು "joined" ಎಲ್ಲವೂ ಅದೇ P108 ID ಗೆ map ಆದ ನಂತರ, ಒಂದು ಒಂಟಿ query ಮೂಲ ದಾಖಲೆ ಬಳಸಿದ ಯಾವುದೇ surface ಪದಪ್ರಯೋಗವನ್ನೂ ಲೆಕ್ಕಿಸದೆ ಎಲ್ಲಾ ಹೊಂದಾಣಿಕೆಗಳನ್ನೂ ಸರಿಯಾಗಿ ಕಂಡುಹಿಡಿಯುತ್ತದೆ', 'ಇದೂ ಯಾವುದೇ ಡೇಟಾ ಸಂಗ್ರಹಿಸುವ ಅಗತ್ಯವನ್ನೇ ತೆಗೆದುಹಾಕುತ್ತದೆ', 'ಇದೂ ಕೇವಲ 10 ಕ್ಕಿಂತ ಕಡಿಮೆ entities ಗಳಿರುವ graphs ಗಳಿಗೆ ಮಾತ್ರ ಮುಖ್ಯ'] },
      { q: 'What does this lesson\'s complete industry pipeline diagram synthesize?', qKn: 'ಈ ಲೆಸನ್‌ನ ಪೂರ್ಣ industry pipeline ರೇಖಾಚಿತ್ರ ಏನನ್ನೂ ಸಂಶ್ಲೇಷಿಸುತ್ತದೆ?',
        opts: ['A single standalone model that needs no other components', 'NER, coreference resolution, entity linking, relation extraction, and ontology mapping chained together into one system feeding a knowledge graph', 'Only the relation extraction step, in isolation from all other NLP tasks', 'A pipeline that works only for image data, not text'], correct: 1,
        optsKn: ['ಬೇರೆ ಯಾವುದೇ ಘಟಕಗಳ ಅಗತ್ಯವಿಲ್ಲದ ಒಂದು single standalone model', 'NER, coreference resolution, entity linking, relation extraction, ಮತ್ತು ontology mapping ಒಂದು knowledge graph ಗೆ ಆಹಾರ ನೀಡುವ ಒಂದು system ಗೆ ಒಟ್ಟಿಗೆ ಸರಪಳಿಗೊಂಡಿವೆ', 'ಕೇವಲ relation extraction ಹಂತ ಮಾತ್ರ, ಇತರ ಎಲ್ಲಾ NLP tasks ಗಳಿಂದ ಪ್ರತ್ಯೇಕವಾಗಿ', 'ಕೇವಲ ಚಿತ್ರ ಡೇಟಾ ಮೇಲೆ ಮಾತ್ರ ಕೆಲಸ ಮಾಡುವ ಒಂದು pipeline, ಪಠ್ಯ ಮೇಲಲ್ಲ'] },
    ] } },
  ],
};
