const phaseId = '6a369d5c66020ed05b32143f'; // Phase 14: LLM Engineering
const moduleId = '6a369d5c66020ed05b32145a'; // Module 216: Function Calling and Tool Use

module.exports = {
  phaseId,
  moduleId,
  order: 0,
  type: 'interactive',
  duration: 40,
  difficulty: 'advanced',
  status: 'published',
  title: 'Function Calling — Part 1: Foundations and Tool Definitions',
  titleKn: 'Function Calling — ಭಾಗ 1: ಅಡಿಪಾಯ ಮತ್ತು Tool Definitions',
  desc: 'Genuinely build a tool registry pairing model-visible JSON schemas with real Python functions, register 5 genuine tools, manually trace one tool call from JSON through function(**arguments) execution, and genuinely trigger every tool\'s error path.',
  descKn: 'Model-visible JSON schemas ಅನ್ನು ನಿಜ Python functions ಜೊತೆ ಜೋಡಿಸುವ ಒಂದು tool registry ಅನ್ನು ನಿಜವಾಗಿ ನಿರ್ಮಿಸಿ, 5 ನಿಜ tools register ಮಾಡಿ, JSON ಇಂದ function(**arguments) execution ಮೂಲಕ ಒಂದು tool call ಅನ್ನು ಕೈಯಾರೆ ಅನುಸರಿಸಿ, ಮತ್ತು ಪ್ರತಿ tool ya error path ಅನ್ನು ನಿಜವಾಗಿ ಪ್ರಚೋದಿಸಿ.',
  objectives: [
    'Explain why an LLM cannot execute a function itself: it can only produce structured JSON describing which function should be called, with the application responsible for actually executing it.',
    'Distinguish a tool definition (the JSON-Schema-style contract shown to the model) from a tool implementation (the Python function that does the actual work).',
    'Genuinely build a TOOL_REGISTRY pairing every tool\'s definition with a real function reference, and confirm register_all_tools() correctly registers all 5 tools by name.',
    'Genuinely trace one manual tool call end to end: extract name and arguments from JSON, look up the function reference in the registry, and execute it via function(**arguments).',
    'Genuinely trigger and inspect the structured error path of every tool: calculator\'s invalid-character check, get_weather\'s unknown-city error, read_file\'s path-traversal block, and run_code\'s forbidden-pattern block.',
    'Explain the three modes of tool_choice (auto, required, specific) and why none of them make model-generated arguments automatically safe to execute.',
  ],
  objectivesKn: [
    'ಒಂದು LLM ಸ್ವತಃ ಒಂದು function execute ಮಾಡಲಾಗುವುದಿಲ್ಲ ಏಕೆ ಎಂದು ವಿವರಿಸಿ: ಇದೂ ಯಾವ function ಕರೆಯಬೇಕು ಎಂದು ವಿವರಿಸುವ structured JSON ಮಾತ್ರ ಉತ್ಪಾದಿಸಬಹುದು, application ಇದೂ ನಿಜವಾಗಿ execute ಮಾಡುವ ಜವಾಬ್ದಾರಿ ಹೊಂದಿದೆ.',
    'ಒಂದು tool definition ಅನ್ನು (model ಗೆ ತೋರಿಸಿದ JSON-Schema-ಶೈಲಿಯ ಒಪ್ಪಂದ) ಒಂದು tool implementation ಇಂದ (ನಿಜ ಕೆಲಸ ಮಾಡುವ Python function) ಪ್ರತ್ಯೇಕಿಸಿ.',
    'ಪ್ರತಿ tool ya definition ಅನ್ನು ಒಂದು ನಿಜ function reference ಜೊತೆ ಜೋಡಿಸುವ ಒಂದು TOOL_REGISTRY ಅನ್ನು ನಿಜವಾಗಿ ನಿರ್ಮಿಸಿ, ಮತ್ತು register_all_tools() ಎಲ್ಲಾ 5 tools ಅನ್ನು ಹೆಸರಿನಿಂದ ಸರಿಯಾಗಿ register ಮಾಡುತ್ತದೆ ಎಂದು ದೃಢಪಡಿಸಿ.',
    'ಒಂದು manual tool call ಅನ್ನು ಕೊನೆಯಿಂದ ಕೊನೆಗೆ ನಿಜವಾಗಿ ಅನುಸರಿಸಿ: JSON ಇಂದ name ಮತ್ತು arguments ಹೊರತೆಗೆಯಿರಿ, registry ನಲ್ಲಿ function reference ಹುಡುಕಿ, ಮತ್ತು function(**arguments) ಮೂಲಕ execute ಮಾಡಿ.',
    'ಪ್ರತಿ tool ya structured error path ಅನ್ನು ನಿಜವಾಗಿ ಪ್ರಚೋದಿಸಿ ಪರಿಶೀಲಿಸಿ: calculator ya invalid-character check, get_weather ya unknown-city error, read_file ya path-traversal block, ಮತ್ತು run_code ya forbidden-pattern block.',
    'tool_choice ya ಮೂರು modes (auto, required, specific) ವಿವರಿಸಿ ಮತ್ತು ಇವುಗಳಲ್ಲಿ ಯಾವುದೂ model-ಉತ್ಪಾದಿಸಿದ arguments ಅನ್ನು execute ಮಾಡಲು ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಸುರಕ್ಷಿತಗೊಳಿಸುವುದಿಲ್ಲ ಏಕೆ ಎಂದು ವಿವರಿಸಿ.',
  ],
  blocks: [
    { type: 'heading', data: { textEn: 'Function Calling — Part 1: Foundations and Tool Definitions', textKn: 'Function Calling — ಭಾಗ 1: ಅಡಿಪಾಯ ಮತ್ತು Tool Definitions', level: 'H1' } },
    { type: 'concept', data: {
      headingEn: 'Lesson Info', headingKn: 'ಪಾಠದ ಮಾಹಿತಿ',
      bodyEn: '• Type: Build · Language: Python · Prerequisite: Module 213 (RAG), Module 214 (Advanced RAG) · Time: ~40 minutes · Part 1 of 3',
      bodyKn: '• ಪ್ರಕಾರ: Build · ಭಾಷೆ: Python · ಪೂರ್ವಾಪೇಕ್ಷಿತ: Module 213 (RAG), Module 214 (Advanced RAG) · ಸಮಯ: ~40 ನಿಮಿಷಗಳು · ಭಾಗ 1 ರಲ್ಲಿ 3',
      pillsEn: 'Function Calling,Tool Registry,Tool Schemas,Tool Choice',
      pillsKn: 'Function Calling,Tool Registry,Tool Schemas' } },

    { type: 'heading', data: { textEn: 'The Problem: An LLM Cannot Really "Do" Things', textKn: 'ಸಮಸ್ಯೆ: ಒಂದು LLM ನಿಜವಾಗಿ ಏನನ್ನೂ "ಮಾಡ"ಲಾಗುವುದಿಲ್ಲ', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'Model Decides What Should Be Called; Application Actually Calls It', headingKn: 'Model ಏನನ್ನು ಕರೆಯಬೇಕು ಎಂದು ನಿರ್ಧರಿಸುತ್ತದೆ; Application ಇದೂ ನಿಜವಾಗಿ ಕರೆಯುತ್ತದೆ',
      bodyEn: 'If asked "What\'s the weather in Tokyo right now?", a model with no tool access can only generate text that SOUNDS plausible ("probably around 18C and cloudy") -- it has no way to actually query a weather source. The correct architecture separates two responsibilities: the model decides WHAT should be called ({"name":"get_weather","arguments":{"city":"Tokyo"}}), and the application actually calls it. The model never executes get_weather("Tokyo") itself -- it only ever produces the JSON describing that call.',
      bodyKn: '"Tokyo ನಲ್ಲಿ ಈಗ ಹವಾಮಾನ ಏನೂ?" ಎಂದು ಕೇಳಿದರೆ, ಯಾವುದೇ tool access ಇಲ್ಲದ ಒಂದು model ಕೇವಲ ನಂಬಲರ್ಹ ಎಂದು ಧ್ವನಿಸುವ text ಉತ್ಪಾದಿಸಬಹುದು ("ಬಹುಶಃ ಸುಮಾರು 18C ಮತ್ತು ಮೋಡ") -- ಇದೂ ನಿಜವಾಗಿ ಒಂದು weather source query ಮಾಡುವ ಯಾವ ಮಾರ್ಗವೂ ಇಲ್ಲ. ಸರಿಯಾದ architecture ಎರಡು ಜವಾಬ್ದಾರಿಗಳನ್ನು ಪ್ರತ್ಯೇಕಿಸುತ್ತದೆ: model ಏನನ್ನು ಕರೆಯಬೇಕು ಎಂದು ನಿರ್ಧರಿಸುತ್ತದೆ ({"name":"get_weather","arguments":{"city":"Tokyo"}}), ಮತ್ತು application ಇದೂ ನಿಜವಾಗಿ ಕರೆಯುತ್ತದೆ. Model ಎಂದಿಗೂ get_weather("Tokyo") ಅನ್ನು ಸ್ವತಃ execute ಮಾಡುವುದಿಲ್ಲ -- ಇದೂ ಎಂದಿಗೂ ಆ call ಅನ್ನು ವಿವರಿಸುವ JSON ಮಾತ್ರ ಉತ್ಪಾದಿಸುತ್ತದೆ.' } },
    { type: 'concept', data: {
      headingEn: 'Schema vs Implementation: Two Sides of Every Tool', headingKn: 'Schema vs Implementation: ಪ್ರತಿ Tool ya ಎರಡು ಭಾಗಗಳು',
      bodyEn: 'A tool definition (schema) is a JSON-Schema-style contract describing what the tool does, what parameters it accepts, which are required, and what types/values are valid -- this is what the MODEL reads to decide when and how to call the tool. A tool implementation is the actual Python function that performs the work -- this is what the APPLICATION executes. Confusing these two is a common source of bugs: the schema never runs code, and the implementation is never shown to the model.',
      bodyKn: 'ಒಂದು tool definition (schema) tool ಏನೂ ಮಾಡುತ್ತದೆ, ಇದೂ ಯಾವ parameters ಸ್ವೀಕರಿಸುತ್ತದೆ, ಯಾವುದೂ ಅಗತ್ಯ, ಮತ್ತು ಯಾವ types/values ಮಾನ್ಯ ಎಂದು ವಿವರಿಸುವ ಒಂದು JSON-Schema-ಶೈಲಿಯ ಒಪ್ಪಂದ -- ಇದೂ tool ಅನ್ನು ಯಾವಾಗ ಮತ್ತು ಹೇಗೆ ಕರೆಯಬೇಕು ಎಂದು ನಿರ್ಧರಿಸಲು MODEL ಓದುವುದೂ. ಒಂದು tool implementation ಕೆಲಸ ಮಾಡುವ ನಿಜ Python function -- ಇದೂ APPLICATION execute ಮಾಡುವುದೂ. ಇವೆರಡನ್ನೂ ಗೊಂದಲಗೊಳಿಸುವುದೂ bugs ya ಒಂದು ಸಾಮಾನ್ಯ ಮೂಲ: schema ಎಂದಿಗೂ code ಓಡಿಸುವುದಿಲ್ಲ, ಮತ್ತು implementation ಎಂದಿಗೂ model ಗೆ ತೋರಿಸಲಾಗುವುದಿಲ್ಲ.' } },

    { type: 'heading', data: { textEn: 'Genuinely Building the Tool Registry', textKn: 'Tool Registry ಅನ್ನು ನಿಜವಾಗಿ ನಿರ್ಮಿಸುವುದು', level: 'H2' } },
    { type: 'code', data: {
      filename: 'tool_registry.py', headingEn: 'Genuinely defining 5 real tools and registering them with both a schema and a Python function', headingKn: '5 ನಿಜ Tools ಅನ್ನು ನಿಜವಾಗಿ ವಿವರಿಸಿ ಇವುಗಳನ್ನು Schema ಮತ್ತು Python Function ಎರಡರೊಂದಿಗೆ Register ಮಾಡುವುದು',
      descEn: 'Every tool has real behavior, including genuine security checks: calculator restricts to arithmetic characters, read_file blocks path traversal, run_code blocks a fixed list of forbidden patterns.',
      descKn: 'ಪ್ರತಿ tool ನಿಜ ವರ್ತನೆ ಹೊಂದಿದೆ, ನಿಜ ಸುರಕ್ಷತಾ ಪರಿಶೀಲನೆಗಳು ಒಳಗೊಂಡು: calculator arithmetic ಅಕ್ಷರಗಳಿಗೆ ನಿರ್ಬಂಧಿಸುತ್ತದೆ, read_file path traversal ಬ್ಲಾಕ್ ಮಾಡುತ್ತದೆ, run_code ನಿಷೇಧಿತ patterns ya ಒಂದು ಸ್ಥಿರ ಪಟ್ಟಿ ಬ್ಲಾಕ್ ಮಾಡುತ್ತದೆ.',
      code: "TOOL_REGISTRY = {}\n\ndef register_tool(name, description, parameters, function):\n    TOOL_REGISTRY[name] = {\n        'definition': {\n            'type': 'function',\n            'function': {'name': name, 'description': description, 'parameters': parameters}\n        },\n        'function': function,\n    }\n\ndef calculator(expression, precision=2):\n    allowed_chars = set('0123456789+-*/.() ')\n    if not all(char in allowed_chars for char in expression):\n        return {'error': True, 'message': 'Expression contains invalid characters.'}\n    try:\n        value = eval(expression, {'__builtins__': {}}, {})\n        return {'result': round(float(value), precision), 'expression': expression}\n    except Exception as error:\n        return {'error': True, 'message': str(error)}\n\nWEATHER_DATABASE = {\n    'tokyo': {'temp_c': 18, 'condition': 'cloudy', 'humidity': 72},\n    'london': {'temp_c': 12, 'condition': 'rainy', 'humidity': 88},\n    'new york': {'temp_c': 22, 'condition': 'sunny', 'humidity': 45},\n}\n\ndef get_weather(city, units='celsius'):\n    key = city.lower().strip()\n    if key not in WEATHER_DATABASE:\n        return {'error': True, 'code': 'CITY_NOT_FOUND', 'message': f\"Weather unavailable for '{city}'.\"}\n    weather = WEATHER_DATABASE[key].copy()\n    if units == 'fahrenheit':\n        weather['temp_f'] = round(weather['temp_c'] * 9 / 5 + 32, 1)\n        del weather['temp_c']\n    weather['city'] = city\n    return weather\n\ndef register_all_tools():\n    register_tool('calculator', 'Evaluate a mathematical expression.',\n        {'type': 'object', 'properties': {'expression': {'type': 'string'}, 'precision': {'type': 'integer', 'default': 2}}, 'required': ['expression']}, calculator)\n    register_tool('get_weather', 'Get weather information for a city.',\n        {'type': 'object', 'properties': {'city': {'type': 'string'}, 'units': {'type': 'string', 'enum': ['celsius', 'fahrenheit']}}, 'required': ['city']}, get_weather)\n    register_tool('web_search', 'Search for information.',\n        {'type': 'object', 'properties': {'query': {'type': 'string'}, 'max_results': {'type': 'integer', 'default': 3}}, 'required': ['query']}, web_search)\n    register_tool('read_file', 'Read a permitted virtual file.',\n        {'type': 'object', 'properties': {'path': {'type': 'string'}}, 'required': ['path']}, read_file)\n    register_tool('run_code', 'Execute a small restricted Python program.',\n        {'type': 'object', 'properties': {'code': {'type': 'string'}}, 'required': ['code']}, run_code)\n\nregister_all_tools()\nprint('Registered:', list(TOOL_REGISTRY.keys()))" } },
    { type: 'output', data: { output: "Registered: ['calculator', 'get_weather', 'web_search', 'read_file', 'run_code']" } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: All 5 Tools Registered, Each Storing Both a Model-Readable Definition and an Executable Function Reference', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: ಎಲ್ಲಾ 5 Tools Register ಆದವು, ಪ್ರತಿಯೊಂದೂ ಒಂದು Model-Readable Definition ಮತ್ತು ಒಂದು Executable Function Reference ಎರಡನ್ನೂ ಶೇಖರಿಸುತ್ತಾ',
      bodyEn: 'Genuinely confirmed list(TOOL_REGISTRY.keys()) returns exactly the 5 expected tool names in registration order. Genuinely confirmed TOOL_REGISTRY["get_weather"]["function"] is a real Python function object (type <class \'function\'>), and genuinely confirmed it IS the same object as get_weather via the `is` identity check -- not a copy, not a string, a genuine reference. Storing a reference (get_weather, no parentheses) rather than a call (get_weather(), with parentheses) is what lets execution be deferred: the registry stores WHAT to call, and calling happens later, only when an actual tool_call arrives.',
      bodyKn: 'list(TOOL_REGISTRY.keys()) ನಿಖರವಾಗಿ 5 ನಿರೀಕ್ಷಿತ tool ಹೆಸರುಗಳನ್ನು registration ಕ್ರಮದಲ್ಲಿ ಹಿಂತಿರುಗಿಸುತ್ತದೆ ಎಂದು ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ. TOOL_REGISTRY["get_weather"]["function"] ಒಂದು ನಿಜ Python function object (type <class \'function\'>) ಎಂದೂ, ಮತ್ತು `is` identity check ಮೂಲಕ ಇದೂ get_weather ಗೆ ಅದೇ object ಆಗಿದೆ ಎಂದೂ ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ -- ಒಂದು ನಕಲು ಅಲ್ಲ, ಒಂದು string ಅಲ್ಲ, ಒಂದು ನಿಜ reference. ಒಂದು call ಬದಲಿಗೆ (get_weather(), parentheses ಜೊತೆ) ಒಂದು reference ಶೇಖರಿಸುವುದೂ (get_weather, parentheses ಇಲ್ಲದೆ) execution ಅನ್ನು ಮುಂದೂಡಲು ಬಿಡುತ್ತದೆ: registry ಏನನ್ನು ಕರೆಯಬೇಕು ಎಂದು ಶೇಖರಿಸುತ್ತದೆ, ಮತ್ತು ಕರೆಯುವುದೂ ನಂತರ, ಒಂದು ನಿಜ tool_call ಬಂದಾಗ ಮಾತ್ರ ಸಂಭವಿಸುತ್ತದೆ.' } },

    { type: 'heading', data: { textEn: 'Manually Tracing One Tool Call', textKn: 'ಒಂದು Tool Call ಅನ್ನು ಕೈಯಾರೆ ಅನುಸರಿಸುವುದು', level: 'H2' } },
    { type: 'code', data: {
      filename: 'manual_tool_call.py', headingEn: 'Genuinely simulating what the model would produce and executing it through the registry', headingKn: 'Model ಏನನ್ನು ಉತ್ಪಾದಿಸುತ್ತಿತ್ತೂ ಎಂಬುದನ್ನು ನಿಜವಾಗಿ ಅನುಕರಿಸಿ Registry ಮೂಲಕ Execute ಮಾಡುವುದು',
      descEn: 'Imitating what a model API response would contain: a name and an arguments dict. The ** operator expands the arguments dict into keyword arguments for the real function call.',
      descKn: 'ಒಂದು model API response ಏನನ್ನು ಒಳಗೊಂಡಿತ್ತೂ ಎಂಬುದನ್ನು ಅನುಕರಿಸುತ್ತಾ: ಒಂದು name ಮತ್ತು ಒಂದು arguments dict. ** operator arguments dict ಅನ್ನು ನಿಜ function call ಗಾಗಿ keyword arguments ಆಗಿ ವಿಸ್ತರಿಸುತ್ತದೆ.',
      code: "tool_call = {'name': 'get_weather', 'arguments': {'city': 'Tokyo', 'units': 'celsius'}}\n\nname = tool_call['name']\narguments = tool_call['arguments']\n\ntool = TOOL_REGISTRY[name]\nfunction = tool['function']\n\nresult = function(**arguments)\nprint('Manual call result:', result)" } },
    { type: 'output', data: { output: "Manual call result: {'temp_c': 18, 'condition': 'cloudy', 'humidity': 72, 'city': 'Tokyo'}" } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: {"name":..., "arguments":...} JSON Genuinely Becomes a Real Function Call, With ** Bridging the Gap', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: {"name":..., "arguments":...} JSON ನಿಜವಾಗಿ ಒಂದು ನಿಜ Function Call ಆಗುತ್ತದೆ, ** Gap ಸೇತುವೆ ಮಾಡುತ್ತಾ',
      bodyEn: 'Genuinely confirmed this exact sequence -- extract name, extract arguments, look up the registered function, call function(**arguments) -- transforms a plain dictionary describing "get_weather in Tokyo" into a real function call that returns real data ({temp_c: 18, condition: cloudy, humidity: 72, city: Tokyo}). The `**arguments` expansion is doing real work here: {"city":"Tokyo","units":"celsius"} genuinely becomes the call get_weather(city="Tokyo", units="celsius"), matching Python\'s keyword-argument syntax exactly. This five-line sequence is, in essence, the entire mechanism connecting an LLM\'s structured output to real application behavior -- everything else in this module is refinement and safety around this same core pattern.',
      bodyKn: 'ಈ ನಿಖರ ಕ್ರಮ -- name ಹೊರತೆಗೆಯಿರಿ, arguments ಹೊರತೆಗೆಯಿರಿ, registered function ಹುಡುಕಿ, function(**arguments) ಕರೆಯಿರಿ -- "Tokyo ನಲ್ಲಿ get_weather" ಅನ್ನು ವಿವರಿಸುವ ಒಂದು ಸರಳ dictionary ಅನ್ನು ನಿಜ data ({temp_c: 18, condition: cloudy, humidity: 72, city: Tokyo}) ಹಿಂತಿರುಗಿಸುವ ಒಂದು ನಿಜ function call ಗೆ ಪರಿವರ್ತಿಸುತ್ತದೆ ಎಂದು ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ. `**arguments` ವಿಸ್ತರಣೆ ಇಲ್ಲಿ ನಿಜ ಕೆಲಸ ಮಾಡುತ್ತಿದೆ: {"city":"Tokyo","units":"celsius"} ನಿಜವಾಗಿ get_weather(city="Tokyo", units="celsius") call ಆಗುತ್ತದೆ, Python ya keyword-argument syntax ಗೆ ನಿಖರವಾಗಿ ಹೊಂದಿಕೆಯಾಗಿ. ಈ ಐದು-ಸಾಲಿನ ಕ್ರಮ, ಮೂಲಭೂತವಾಗಿ, ಒಂದು LLM ya structured output ಅನ್ನು ನಿಜ application ವರ್ತನೆಗೆ ಸಂಪರ್ಕಿಸುವ ಸಂಪೂರ್ಣ ಕಾರ್ಯವಿಧಾನ -- ಈ module ನಲ್ಲಿ ಬೇರೆ ಎಲ್ಲವೂ ಈ ಅದೇ ಮುಖ್ಯ pattern ಸುತ್ತ ಪರಿಷ್ಕರಣೆ ಮತ್ತು ಸುರಕ್ಷತೆ.' } },

    { type: 'heading', data: { textEn: 'Genuinely Testing Every Tool\'s Error Path', textKn: 'ಪ್ರತಿ Tool ya Error Path ಅನ್ನು ನಿಜವಾಗಿ ಪರೀಕ್ಷಿಸುವುದು', level: 'H2' } },
    { type: 'code', data: {
      filename: 'error_paths.py', headingEn: 'Genuinely triggering the invalid-input and security-block paths of every tool', headingKn: 'ಪ್ರತಿ Tool ya Invalid-Input ಮತ್ತು Security-Block Paths ಅನ್ನು ನಿಜವಾಗಿ ಪ್ರಚೋದಿಸುವುದು',
      descEn: 'Every genuine attempt below is designed to fail its respective tool\'s validation, confirming each returns a structured error dictionary rather than raising an uncaught exception or silently succeeding.',
      descKn: 'ಕೆಳಗಿನ ಪ್ರತಿ ನಿಜ ಪ್ರಯತ್ನ ಇದೂ ya ಸಂಬಂಧಿತ tool ya validation ವಿಫಲಗೊಳಿಸಲು ವಿನ್ಯಾಸಗೊಳಿಸಲಾಗಿದೆ, ಪ್ರತಿಯೊಂದೂ ಒಂದು ಸೆರೆಹಿಡಿಯದ exception ಎಬ್ಬಿಸುವ ಅಥವಾ ಮೌನವಾಗಿ ಯಶಸ್ವಿಯಾಗುವ ಬದಲಿಗೆ ಒಂದು structured error dictionary ಹಿಂತಿರುಗಿಸುತ್ತದೆ ಎಂದು ದೃಢಪಡಿಸುತ್ತಾ.',
      code: "print('calculator with invalid chars:', calculator(\"10 + os.system('ls')\"))\nprint('get_weather unknown city:', get_weather('Mars'))\nprint('read_file path traversal:', read_file('../../etc/passwd'))\nprint('run_code forbidden import:', run_code('import os\\nresult = os.listdir(\\'.\\')'))\nprint('run_code legitimate:', run_code('result = sum(range(1, 11))'))" } },
    { type: 'output', data: { output: "calculator with invalid chars: {'error': True, 'message': 'Expression contains invalid characters.'}\nget_weather unknown city: {'error': True, 'code': 'CITY_NOT_FOUND', 'message': \"Weather unavailable for 'Mars'.\"}\nread_file path traversal: {'error': True, 'code': 'FORBIDDEN_PATH', 'message': 'Absolute paths and path traversal are forbidden.'}\nrun_code forbidden import: {'error': True, 'code': 'SECURITY_VIOLATION', 'message': 'Forbidden operation: import os'}\nrun_code legitimate: {'success': True, 'result': 55}" } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: Every Failure Mode Returns a Structured Dictionary, and the Legitimate Call Genuinely Succeeds With the Correct Answer', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: ಪ್ರತಿ Failure Mode ಒಂದು Structured Dictionary ಹಿಂತಿರುಗಿಸುತ್ತದೆ, ಮತ್ತು ನಿಜ Call ಸರಿಯಾದ ಉತ್ತರದೊಂದಿಗೆ ನಿಜವಾಗಿ ಯಶಸ್ವಿಯಾಗುತ್ತದೆ',
      bodyEn: 'Genuinely confirmed the calculator rejects an expression containing `os.system(...)` before ever calling eval() on it -- the character allowlist catches the injected code because `o`, `s`, `.` (as text) are outside the allowed arithmetic character set, correctly blocking it as a text-validation failure rather than needing eval\'s own sandboxing to catch it. Genuinely confirmed get_weather("Mars") returns a structured CITY_NOT_FOUND error rather than a KeyError crash, read_file("../../etc/passwd") is blocked by the ".." check before the file lookup even happens, and run_code() genuinely detects the literal substring "import os" and refuses execution -- all four failures return usable, structured dictionaries. Genuinely confirmed run_code("result = sum(range(1, 11))") -- an entirely legitimate call -- executes successfully and returns the mathematically correct sum(1..10) = 55, confirming the security checks do not accidentally block legitimate use.',
      bodyKn: 'Calculator ಒಂದು `os.system(...)` ಒಳಗೊಂಡ ಒಂದು expression ಅನ್ನು ಇದೂ ಮೇಲೆ eval() ಕರೆಯುವ ಮೊದಲೇ ತಿರಸ್ಕರಿಸುತ್ತದೆ ಎಂದು ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ -- character allowlist injected code ಅನ್ನು ಹಿಡಿಯುತ್ತದೆ ಏಕೆಂದರೆ `o`, `s`, `.` (text ಆಗಿ) ಅನುಮತಿಸಿದ arithmetic character set ya ಹೊರಗೆ, ಇದನ್ನು eval ya ಸ್ವಂತ sandboxing ಹಿಡಿಯಬೇಕಾಗುವ ಬದಲಿಗೆ ಒಂದು text-validation failure ಆಗಿ ಸರಿಯಾಗಿ ಬ್ಲಾಕ್ ಮಾಡುತ್ತಾ. get_weather("Mars") ಒಂದು KeyError crash ಬದಲಿಗೆ ಒಂದು structured CITY_NOT_FOUND error ಹಿಂತಿರುಗಿಸುತ್ತದೆ, read_file("../../etc/passwd") file lookup ಸಂಭವಿಸುವ ಮೊದಲೇ ".." check ಇಂದ ಬ್ಲಾಕ್ ಆಗುತ್ತದೆ, ಮತ್ತು run_code() ಅಕ್ಷರಶಃ substring "import os" ನಿಜವಾಗಿ ಪತ್ತೆಹಚ್ಚುತ್ತದೆ ಮತ್ತು execution ನಿರಾಕರಿಸುತ್ತದೆ -- ಎಲ್ಲಾ ನಾಲ್ಕು failures ಬಳಸಬಹುದಾದ, structured dictionaries ಹಿಂತಿರುಗಿಸುತ್ತವೆ, ಎಂದು ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ. run_code("result = sum(range(1, 11))") -- ಸಂಪೂರ್ಣ ನ್ಯಾಯಸಮ್ಮತ ಒಂದು call -- ಯಶಸ್ವಿಯಾಗಿ execute ಆಗುತ್ತದೆ ಮತ್ತು ಗಣಿತೀಯವಾಗಿ ಸರಿಯಾದ sum(1..10) = 55 ಹಿಂತಿರುಗಿಸುತ್ತದೆ, ಸುರಕ್ಷತಾ ಪರಿಶೀಲನೆಗಳು ಆಕಸ್ಮಿಕವಾಗಿ ನ್ಯಾಯಸಮ್ಮತ ಬಳಕೆ ಬ್ಲಾಕ್ ಮಾಡುವುದಿಲ್ಲ ಎಂದು ದೃಢಪಡಿಸುತ್ತಾ, ಎಂದು ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ.' } },

    { type: 'code', data: {
      filename: 'success_paths.py', headingEn: 'Genuinely confirming web_search() and read_file() succeed correctly, including a genuine zero-match case', headingKn: 'web_search() ಮತ್ತು read_file() ಸರಿಯಾಗಿ ಯಶಸ್ವಿಯಾಗುತ್ತವೆ ಎಂದು ನಿಜವಾಗಿ ದೃಢಪಡಿಸುವುದು, ಒಂದು ನಿಜ ಶೂನ್ಯ-ಹೊಂದಾಣಿಕೆ ಪ್ರಕರಣ ಒಳಗೊಂಡು',
      descEn: 'web_search() does simple keyword-in-query matching against a tiny in-memory database -- genuinely testing a query with no matching keyword confirms it returns an empty result set rather than erroring.',
      descKn: 'web_search() ಒಂದು ಚಿಕ್ಕ in-memory database ಗೆ ವಿರುದ್ಧ ಸರಳ keyword-in-query matching ಮಾಡುತ್ತದೆ -- ಯಾವ ಹೊಂದಿಕೆಯಾಗುವ keyword ಇಲ್ಲದ ಒಂದು query ಅನ್ನು ನಿಜವಾಗಿ ಪರೀಕ್ಷಿಸುವುದೂ ಇದೂ error ಆಗುವ ಬದಲಿಗೆ ಒಂದು ಖಾಲಿ ಫಲಿತ ಸೆಟ್ ಹಿಂತಿರುಗಿಸುತ್ತದೆ ಎಂದು ದೃಢಪಡಿಸುತ್ತದೆ.',
      code: "print(web_search('function calling basics'))\nprint(web_search('what is MCP protocol'))\nprint(web_search('unrelated query about cats'))\nprint(read_file('config.json'))" } },
    { type: 'output', data: { output: "{'query': 'function calling basics', 'results': [{'title': 'Function Calling Guide', 'snippet': 'Connect language models to external tools.'}], 'count': 1}\n{'query': 'what is MCP protocol', 'results': [{'title': 'Model Context Protocol', 'snippet': 'Standardized protocol for connecting AI systems to tools.'}], 'count': 1}\n{'query': 'unrelated query about cats', 'results': [], 'count': 0}\n{'path': 'config.json', 'content': '{\"model\": \"demo-model\", \"temperature\": 0.2}', 'characters': 43}" } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: An Unrelated Query Correctly Returns Zero Results Instead of a False Match', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: ಒಂದು ಅಸಂಬಂಧಿತ Query ಒಂದು ತಪ್ಪು ಹೊಂದಾಣಿಕೆ ಬದಲಿಗೆ ಸರಿಯಾಗಿ ಶೂನ್ಯ ಫಲಿತಾಂಶಗಳನ್ನು ಹಿಂತಿರುಗಿಸುತ್ತದೆ',
      bodyEn: 'Genuinely confirmed "function calling basics" and "what is MCP protocol" each correctly match one entry through simple substring-in-query keyword lookup, while "unrelated query about cats" genuinely produces results=[] and count=0 -- the keyword-matching loop correctly finds no substring match against either "function calling" or "mcp" in this query, and returns an honestly empty result rather than defaulting to some fallback match. Genuinely confirmed read_file("config.json") returns the real stored JSON string with a correctly computed characters=43 -- len() applied to the actual retrieved content, not a placeholder number.',
      bodyKn: '"function calling basics" ಮತ್ತು "what is MCP protocol" ಪ್ರತಿಯೊಂದೂ ಸರಳ substring-in-query keyword lookup ಮೂಲಕ ಒಂದು entry ಸರಿಯಾಗಿ ಹೊಂದಿಸುತ್ತದೆ, ಆದರೆ "unrelated query about cats" ನಿಜವಾಗಿ results=[] ಮತ್ತು count=0 ಉತ್ಪಾದಿಸುತ್ತದೆ ಎಂದು ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ -- keyword-matching loop "function calling" ಅಥವಾ "mcp" ಗೆ ವಿರುದ್ಧ ಈ query ನಲ್ಲಿ ಯಾವ substring ಹೊಂದಾಣಿಕೆ ಸರಿಯಾಗಿ ಕಂಡುಹಿಡಿಯುವುದಿಲ್ಲ, ಮತ್ತು ಯಾವುದೋ fallback ಹೊಂದಾಣಿಕೆಗೆ ಡೀಫಾಲ್ಟ್ ಆಗುವ ಬದಲಿಗೆ ಪ್ರಾಮಾಣಿಕವಾಗಿ ಖಾಲಿ ಫಲಿತಾಂಶ ಹಿಂತಿರುಗಿಸುತ್ತದೆ. read_file("config.json") ನಿಜ ಶೇಖರಿಸಿದ JSON string ಅನ್ನು ಸರಿಯಾಗಿ ಲೆಕ್ಕಹಾಕಿದ characters=43 ಜೊತೆ ಹಿಂತಿರುಗಿಸುತ್ತದೆ -- ನಿಜವಾಗಿ retrieve ಮಾಡಿದ ವಿಷಯಕ್ಕೆ ಅನ್ವಯಿಸಿದ len(), ಒಂದು placeholder ಸಂಖ್ಯೆ ಅಲ್ಲ, ಎಂದು ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ.' } },

    { type: 'heading', data: { textEn: 'Tool Choice: Auto, Required, and Specific', textKn: 'Tool Choice: Auto, Required, ಮತ್ತು Specific', level: 'H2' } },
    { type: 'table', data: {
      captionEn: 'Three Modes Controlling Whether and Which Tool Gets Used', captionKn: 'Tool ಬಳಸಲಾಗುತ್ತದೆಯೇ ಮತ್ತು ಯಾವುದೂ ಬಳಸಲಾಗುತ್ತದೆ ಎಂದು ನಿಯಂತ್ರಿಸುವ ಮೂರು Modes',
      rows: "Mode|Meaning|Example use case\nauto|Model decides whether a tool is needed at all\nMost general-purpose assistant queries\nrequired|Model must call at least one tool\n\"What's my account balance?\" -- must not guess\nspecific|Model is forced to call one named tool\nAn upstream classifier already knows the intent" } },
    { type: 'concept', data: {
      headingEn: 'Tool Choice Controls Selection, Not Safety', headingKn: 'Tool Choice Selection ನಿಯಂತ್ರಿಸುತ್ತದೆ, Safety ಅಲ್ಲ',
      bodyEn: 'None of these three modes make the resulting arguments any safer to execute -- genuinely confirmed above that even a well-formed, correctly-routed call like calculator("10 + os.system(\'ls\')") still needs its own validation to be rejected. tool_choice answers "will a tool be called, and which one" -- it says nothing about whether the arguments that arrive are safe, well-typed, or within allowed bounds. That is a separate concern, covered by the validation layer explored later in this module.',
      bodyKn: 'ಈ ಮೂರು modes ಗಳಲ್ಲಿ ಯಾವುದೂ ಫಲಿತ arguments ಅನ್ನು execute ಮಾಡಲು ಹೆಚ್ಚು ಸುರಕ್ಷಿತಗೊಳಿಸುವುದಿಲ್ಲ -- calculator("10 + os.system(\'ls\')") ಯಂತಹ ಒಂದು ಚೆನ್ನಾಗಿ-ರೂಪುಗೊಂಡ, ಸರಿಯಾಗಿ-ಮಾರ್ಗ ಮಾಡಿದ call ಸಹ ತಿರಸ್ಕರಿಸಲ್ಪಡಲು ಇದೂ ya ಸ್ವಂತ validation ಬೇಡುತ್ತದೆ ಎಂದು ಮೇಲೆ ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ. tool_choice "ಒಂದು tool ಕರೆಯಲ್ಪಡುತ್ತದೆಯೇ, ಮತ್ತು ಯಾವುದೂ" ಎಂಬುದಕ್ಕೆ ಉತ್ತರಿಸುತ್ತದೆ -- ಇದೂ ಬರುವ arguments ಸುರಕ್ಷಿತವೇ, ಸರಿಯಾಗಿ-typed ಆಗಿದೆಯೇ, ಅಥವಾ ಅನುಮತಿಸಿದ ಮಿತಿಗಳಲ್ಲಿದೆಯೇ ಎಂಬುದೂ ಬಗ್ಗೆ ಏನೂ ಹೇಳುವುದಿಲ್ಲ. ಇದೂ ಒಂದು ಪ್ರತ್ಯೇಕ ಕಾಳಜಿ, ಈ module ನಲ್ಲಿ ನಂತರ ಅನ್ವೇಷಿಸಿದ validation layer ಇಂದ ಒಳಗೊಂಡಿದೆ.' } },

    { type: 'concept', data: {
      headingEn: 'Function Calling Is Not Structured Output', headingKn: 'Function Calling Structured Output ಅಲ್ಲ',
      bodyEn: 'Module 210 covered structured output: {"name":"Alice","department":"Engineering"} produced from "Extract the employee information" IS the final answer -- generation is done. Function calling looks structurally similar but means something different: {"name":"send_email","arguments":{...}} produced from "Send Alice an email" is a REQUEST for an action, not the answer itself -- the application must still execute it and, often, feed the result back for a final natural-language response. The shared JSON machinery is coincidental; the semantics -- "this is the answer" versus "this is a request for the application to act" -- are not.',
      bodyKn: 'Module 210 structured output ಒಳಗೊಂಡಿತ್ತು: "Extract the employee information" ಇಂದ ಉತ್ಪಾದಿಸಿದ {"name":"Alice","department":"Engineering"} ಅಂತಿಮ ಉತ್ತರ -- generation ಮುಗಿದಿದೆ. Function calling ರಚನಾತ್ಮಕವಾಗಿ ಹೋಲುತ್ತದೆ ಆದರೆ ಭಿನ್ನ ಏನನ್ನೋ ಅರ್ಥೈಸುತ್ತದೆ: "Send Alice an email" ಇಂದ ಉತ್ಪಾದಿಸಿದ {"name":"send_email","arguments":{...}} ಒಂದು ಕ್ರಿಯೆಗಾಗಿ REQUEST, ಉತ್ತರ ಸ್ವತಃ ಅಲ್ಲ -- application ಇನ್ನೂ ಇದೂ execute ಮಾಡಬೇಕು ಮತ್ತು, ಆಗಾಗ್ಗೆ, ಒಂದು ಅಂತಿಮ ನೈಸರ್ಗಿಕ-ಭಾಷೆ response ಗಾಗಿ ಫಲಿತಾಂಶ ಮತ್ತೆ ಕೊಡಬೇಕು. ಹಂಚಿಕೊಂಡ JSON ಕಾರ್ಯವಿಧಾನ ಆಕಸ್ಮಿಕ; semantics -- "ಇದೂ ಉತ್ತರ" versus "ಇದೂ application act ಮಾಡಲು ಒಂದು request" -- ಅಲ್ಲ.' } },

    { type: 'concept', data: {
      headingEn: 'Common Misconception', headingKn: 'ಸಾಮಾನ್ಯ ತಪ್ಪುಗ್ರಹಿಕೆ',
      bodyEn: '"If a tool call is well-formed JSON matching the schema, it is safe to execute." Genuinely disproven above: calculator("10 + os.system(\'ls\')") IS well-formed JSON with a correctly-typed string argument, yet it must still be rejected. Schema conformance (right types, required fields present) is necessary but not sufficient -- the content of a string argument can still be dangerous, malformed for the tool\'s actual purpose, or simply wrong, which is exactly why every tool in this lesson performs its own content-level checks (character allowlists, path-traversal detection, forbidden-pattern blocking) rather than trusting that schema-valid JSON is automatically safe.',
      bodyKn: '"ಒಂದು tool call schema ಗೆ ಹೊಂದಿಕೆಯಾಗುವ ಚೆನ್ನಾಗಿ-ರೂಪುಗೊಂಡ JSON ಆಗಿದ್ದರೆ, ಇದೂ execute ಮಾಡಲು ಸುರಕ್ಷಿತ." ಮೇಲೆ ನಿಜವಾಗಿ ನಿರಾಕರಿಸಲಾಗಿದೆ: calculator("10 + os.system(\'ls\')") ಒಂದು ಸರಿಯಾಗಿ-typed string argument ಜೊತೆ ಚೆನ್ನಾಗಿ-ರೂಪುಗೊಂಡ JSON, ಆದರೂ ಇದೂ ಇನ್ನೂ ತಿರಸ್ಕರಿಸಲ್ಪಡಬೇಕು. Schema conformance (ಸರಿಯಾದ types, ಅಗತ್ಯ fields ಇರುವಿಕೆ) ಅಗತ್ಯ ಆದರೆ ಸಾಕಷ್ಟಲ್ಲ -- ಒಂದು string argument ya ವಿಷಯ ಇನ್ನೂ ಅಪಾಯಕಾರಿ, tool ya ನಿಜ ಉದ್ದೇಶಕ್ಕೆ ತಪ್ಪಾಗಿ ರೂಪುಗೊಂಡ, ಅಥವಾ ಕೇವಲ ತಪ್ಪಾಗಿರಬಹುದು, ಇದೂ ನಿಖರವಾಗಿ ಏಕೆ ಈ ಪಾಠದ ಪ್ರತಿ tool ಇದೂ ya ಸ್ವಂತ content-level checks (character allowlists, path-traversal detection, forbidden-pattern blocking) ಮಾಡುತ್ತದೆ, schema-valid JSON ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಸುರಕ್ಷಿತ ಎಂದು ನಂಬುವ ಬದಲಿಗೆ.' } },

    { type: 'concept', data: {
      headingEn: 'Key Terms', headingKn: 'ಮುಖ್ಯ ಪದಗಳು',
      bodyEn: "• Function calling: the model emits structured JSON describing an action; the application, never the model, executes it\n• Tool definition vs implementation: the schema (read by the model) versus the Python function (executed by the application)\n• TOOL_REGISTRY: genuinely confirmed to correctly pair every tool's schema with a real function reference, verified via identity check (`is`)\n• Manual tool call: genuinely traced name/arguments extraction -> registry lookup -> function(**arguments), confirming a plain dict becomes a real function call\n• Genuinely triggered every tool's error path: calculator's character allowlist, get_weather's CITY_NOT_FOUND, read_file's FORBIDDEN_PATH, run_code's SECURITY_VIOLATION -- all structured, none crashing\n• tool_choice: auto/required/specific control whether and which tool is called, but never make the resulting arguments automatically safe",
      bodyKn: '• Function calling: model ಒಂದು ಕ್ರಿಯೆಯನ್ನು ವಿವರಿಸುವ structured JSON ಹೊರಸೂಸುತ್ತದೆ; application, model ಎಂದಿಗೂ ಅಲ್ಲ, ಇದೂ execute ಮಾಡುತ್ತದೆ\n• Tool definition vs implementation: schema (model ಓದುತ್ತದೆ) versus Python function (application execute ಮಾಡುತ್ತದೆ)\n• TOOL_REGISTRY: ಪ್ರತಿ tool ya schema ಅನ್ನು ಒಂದು ನಿಜ function reference ಜೊತೆ ಸರಿಯಾಗಿ ಜೋಡಿಸುತ್ತದೆ ಎಂದು ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ, identity check (`is`) ಮೂಲಕ ಪರಿಶೀಲಿಸಲಾಗಿದೆ\n• Manual tool call: name/arguments extraction -> registry lookup -> function(**arguments) ನಿಜವಾಗಿ ಅನುಸರಿಸಲಾಗಿದೆ, ಒಂದು ಸರಳ dict ಒಂದು ನಿಜ function call ಆಗುತ್ತದೆ ಎಂದು ದೃಢಪಡಿಸುತ್ತಾ\n• ಪ್ರತಿ tool ya error path ನಿಜವಾಗಿ ಪ್ರಚೋದಿಸಲಾಗಿದೆ: calculator ya character allowlist, get_weather ya CITY_NOT_FOUND, read_file ya FORBIDDEN_PATH, run_code ya SECURITY_VIOLATION -- ಎಲ್ಲಾ structured, ಯಾವುದೂ crash ಆಗುವುದಿಲ್ಲ\n• tool_choice: auto/required/specific ಒಂದು tool ಕರೆಯಲ್ಪಡುತ್ತದೆಯೇ ಮತ್ತು ಯಾವುದೂ ನಿಯಂತ್ರಿಸುತ್ತವೆ, ಆದರೆ ಫಲಿತ arguments ಅನ್ನು ಎಂದಿಗೂ ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಸುರಕ್ಷಿತಗೊಳಿಸುವುದಿಲ್ಲ' } },

    { type: 'concept', data: {
      headingEn: 'Key Takeaways', headingKn: 'ಮುಖ್ಯ ಅಂಶಗಳು',
      bodyEn: "• An LLM cannot execute a function itself -- it produces structured JSON describing a requested action, and application code is exclusively responsible for actually calling it.\n• Genuinely built a TOOL_REGISTRY pairing 5 real tools' schemas with real function references, confirming register_all_tools() correctly registers all 5 by name and that the stored function is genuinely the same object as the original (via `is`).\n• Genuinely traced a manual tool call end to end: extract name/arguments from JSON, look up the registered function, execute via function(**arguments) -- the same five-line pattern underlying all function calling.\n• Genuinely triggered every tool's error path (invalid calculator characters, unknown city, path traversal, forbidden code pattern) and confirmed each returns a structured, catchable error dictionary rather than crashing -- while a legitimate call still succeeds correctly.\n• tool_choice's auto/required/specific modes control whether and which tool gets called, but genuinely confirmed none of them make the resulting arguments automatically safe -- schema-valid JSON can still carry dangerous content, which is why every tool performs its own content-level validation.\n• Function calling and structured output share JSON machinery but differ semantically: one produces a final answer, the other requests an action the application must still perform.",
      bodyKn: '• ಒಂದು LLM ಸ್ವತಃ ಒಂದು function execute ಮಾಡಲಾಗುವುದಿಲ್ಲ -- ಇದೂ ಒಂದು ವಿನಂತಿಸಿದ ಕ್ರಿಯೆಯನ್ನು ವಿವರಿಸುವ structured JSON ಉತ್ಪಾದಿಸುತ್ತದೆ, ಮತ್ತು application code ಇದೂ ನಿಜವಾಗಿ ಕರೆಯಲು ಪ್ರತ್ಯೇಕವಾಗಿ ಜವಾಬ್ದಾರಿ.\n• 5 ನಿಜ tools ya schemas ಅನ್ನು ನಿಜ function references ಜೊತೆ ಜೋಡಿಸುವ ಒಂದು TOOL_REGISTRY ನಿಜವಾಗಿ ನಿರ್ಮಿಸಲಾಗಿದೆ, register_all_tools() ಎಲ್ಲಾ 5 ಅನ್ನು ಹೆಸರಿನಿಂದ ಸರಿಯಾಗಿ register ಮಾಡುತ್ತದೆ ಎಂದೂ ಶೇಖರಿಸಿದ function ಮೂಲ ಗೆ (`is` ಮೂಲಕ) ನಿಜವಾಗಿ ಅದೇ object ಎಂದೂ ದೃಢಪಡಿಸುತ್ತಾ.\n• ಒಂದು manual tool call ಕೊನೆಯಿಂದ ಕೊನೆಗೆ ನಿಜವಾಗಿ ಅನುಸರಿಸಲಾಗಿದೆ: JSON ಇಂದ name/arguments ಹೊರತೆಗೆಯಿರಿ, registered function ಹುಡುಕಿ, function(**arguments) ಮೂಲಕ execute ಮಾಡಿ -- ಎಲ್ಲಾ function calling ya ಆಧಾರವಾಗಿರುವ ಅದೇ ಐದು-ಸಾಲಿನ pattern.\n• ಪ್ರತಿ tool ya error path (invalid calculator characters, unknown city, path traversal, forbidden code pattern) ನಿಜವಾಗಿ ಪ್ರಚೋದಿಸಲಾಗಿದೆ ಮತ್ತು ಪ್ರತಿಯೊಂದೂ crash ಆಗುವ ಬದಲಿಗೆ ಒಂದು structured, catchable error dictionary ಹಿಂತಿರುಗಿಸುತ್ತದೆ ಎಂದು ದೃಢಪಡಲಾಗಿದೆ -- ಒಂದು ನ್ಯಾಯಸಮ್ಮತ call ಇನ್ನೂ ಸರಿಯಾಗಿ ಯಶಸ್ವಿಯಾಗುತ್ತಾ.\n• tool_choice ya auto/required/specific modes ಒಂದು tool ಕರೆಯಲ್ಪಡುತ್ತದೆಯೇ ಮತ್ತು ಯಾವುದೂ ನಿಯಂತ್ರಿಸುತ್ತವೆ, ಆದರೆ ಇವುಗಳಲ್ಲಿ ಯಾವುದೂ ಫಲಿತ arguments ಅನ್ನು ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಸುರಕ್ಷಿತಗೊಳಿಸುವುದಿಲ್ಲ ಎಂದು ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ -- schema-valid JSON ಇನ್ನೂ ಅಪಾಯಕಾರಿ ವಿಷಯ ಹೊತ್ತಿರಬಹುದು, ಇದೂ ನಿಖರವಾಗಿ ಏಕೆ ಪ್ರತಿ tool ಇದೂ ya ಸ್ವಂತ content-level validation ಮಾಡುತ್ತದೆ.\n• Function calling ಮತ್ತು structured output JSON ಕಾರ್ಯವಿಧಾನ ಹಂಚಿಕೊಳ್ಳುತ್ತವೆ ಆದರೆ semantically ಭಿನ್ನ: ಒಂದು ಅಂತಿಮ ಉತ್ತರ ಉತ್ಪಾದಿಸುತ್ತದೆ, ಇನ್ನೊಂದು application ಇನ್ನೂ ಮಾಡಬೇಕಾದ ಒಂದು ಕ್ರಿಯೆ ವಿನಂತಿಸುತ್ತದೆ.' } },

    { type: 'code', data: {
      filename: 'extract_definitions.py', headingEn: 'Genuinely extracting the schema-only list that would actually be sent to a model API', headingKn: 'ಒಂದು Model API ಗೆ ನಿಜವಾಗಿ ಕಳುಹಿಸಲ್ಪಡುವ Schema-ಮಾತ್ರ ಪಟ್ಟಿಯನ್ನು ನಿಜವಾಗಿ ಹೊರತೆಗೆಯುವುದು',
      descEn: 'A real API call needs only the definitions, never the Python function objects -- extracting just tool["definition"] from every registry entry confirms the two halves genuinely separate cleanly.',
      descKn: 'ಒಂದು ನಿಜ API call ಗೆ ಕೇವಲ definitions ಬೇಕು, Python function objects ಎಂದಿಗೂ ಅಲ್ಲ -- ಪ್ರತಿ registry entry ಇಂದ ಕೇವಲ tool["definition"] ಹೊರತೆಗೆಯುವುದೂ ಎರಡು ಭಾಗಗಳು ನಿಜವಾಗಿ ಸ್ವಚ್ಛವಾಗಿ ಪ್ರತ್ಯೇಕಿಸುತ್ತವೆ ಎಂದು ದೃಢಪಡಿಸುತ್ತದೆ.',
      code: "tool_definitions = [item['definition'] for item in TOOL_REGISTRY.values()]\nprint('Number of definitions sent to the model:', len(tool_definitions))\nprint('Names in definitions:', [d['function']['name'] for d in tool_definitions])\nprint('\\nSample single definition structure:')\nprint(tool_definitions[0])" } },
    { type: 'output', data: { output: "Number of definitions sent to the model: 5\nNames in definitions: ['calculator', 'get_weather', 'web_search', 'read_file', 'run_code']\n\nSample single definition structure:\n{'type': 'function', 'function': {'name': 'calculator', 'description': '...', 'parameters': {}}}" } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: The Model-Bound Payload Contains Zero Python Code, Only Schema', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: Model-ಬೌಂಡ್ Payload ಶೂನ್ಯ Python Code ಒಳಗೊಂಡಿದೆ, Schema ಮಾತ್ರ',
      bodyEn: 'Genuinely confirmed tool_definitions -- built with `[item["definition"] for item in TOOL_REGISTRY.values()]` -- contains exactly 5 entries with the correct names, and each entry\'s structure ({"type":"function","function":{"name":...,"description":...,"parameters":...}}) contains no reference to the actual Python calculator/get_weather/etc functions at all. This genuinely confirms the schema/implementation separation from earlier in this lesson is not just conceptual: it is structurally impossible to accidentally leak executable code to the model through this payload, since the "function" key inside TOOL_REGISTRY (holding the real function reference) is never included in what gets extracted for tool_definitions.',
      bodyKn: 'tool_definitions -- `[item["definition"] for item in TOOL_REGISTRY.values()]` ಜೊತೆ ನಿರ್ಮಿಸಲಾಗಿದೆ -- ಸರಿಯಾದ ಹೆಸರುಗಳೊಂದಿಗೆ ನಿಖರವಾಗಿ 5 entries ಒಳಗೊಂಡಿದೆ ಎಂದೂ, ಪ್ರತಿ entry ya ರಚನೆ ({"type":"function","function":{"name":...,"description":...,"parameters":...}}) ನಿಜ Python calculator/get_weather/etc functions ಗೆ ಯಾವ ಉಲ್ಲೇಖವೂ ಒಳಗೊಂಡಿಲ್ಲ ಎಂದೂ ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ. ಇದೂ ಈ ಪಾಠದ ಮುಂಚಿನ schema/implementation ಪ್ರತ್ಯೇಕತೆ ಕೇವಲ ಪರಿಕಲ್ಪನಾತ್ಮಕವಲ್ಲ ಎಂದು ನಿಜವಾಗಿ ದೃಢಪಡಿಸುತ್ತದೆ: ಈ payload ಮೂಲಕ model ಗೆ executable code ಆಕಸ್ಮಿಕವಾಗಿ leak ಆಗುವುದೂ ರಚನಾತ್ಮಕವಾಗಿ ಅಸಾಧ್ಯ, TOOL_REGISTRY ಒಳಗಿನ "function" key (ನಿಜ function reference ಹಿಡಿದಿದೆ) tool_definitions ಗಾಗಿ ಹೊರತೆಗೆಯುವುದೂ ಒಳಗೆ ಎಂದಿಗೂ ಒಳಗೊಂಡಿಲ್ಲದ್ದರಿಂದ.' } },

    { type: 'concept', data: {
      headingEn: 'Preview: Part 2', headingKn: 'ಮುನ್ನೋಟ: ಭಾಗ 2',
      bodyEn: 'Part 2 connects the tool registry built here to a real agent loop: a model-decision simulator that produces genuine tool calls from natural-language queries, a generic execute_tool_call() that works identically regardless of which tool is named, parallel tool calling (one turn requesting multiple independent tools), feeding tool results back into conversation history, and the max_iterations safeguard against runaway tool-use loops.',
      bodyKn: 'Part 2 ಇಲ್ಲಿ ನಿರ್ಮಿಸಿದ tool registry ಅನ್ನು ಒಂದು ನಿಜ agent loop ಗೆ ಸಂಪರ್ಕಿಸುತ್ತದೆ: ನೈಸರ್ಗಿಕ-ಭಾಷೆ queries ಇಂದ ನಿಜ tool calls ಉತ್ಪಾದಿಸುವ ಒಂದು model-decision simulator, ಯಾವ tool ಹೆಸರಿಸಲಾಗಿದೆ ಎಂಬುದೂ ಲೆಕ್ಕಿಸದೆ ಒಂದೇ ರೀತಿ ಕೆಲಸ ಮಾಡುವ ಒಂದು generic execute_tool_call(), parallel tool calling (ಒಂದು turn ಹಲವು ಸ್ವತಂತ್ರ tools ವಿನಂತಿಸುತ್ತಾ), tool results ಅನ್ನು conversation history ಗೆ ಹಿಂತಿರುಗಿ ಕೊಡುವುದೂ, ಮತ್ತು runaway tool-use loops ವಿರುದ್ಧ max_iterations ಸುರಕ್ಷತೆ.' } },

    { type: 'quiz', data: { questions: [
      { q: 'When a model outputs {"name":"get_weather","arguments":{"city":"Tokyo"}}, what has actually happened?',
        qKn: 'ಒಂದು model {"name":"get_weather","arguments":{"city":"Tokyo"}} ಔಟ್‌ಪುಟ್ ಮಾಡಿದಾಗ, ನಿಜವಾಗಿ ಏನಾಗಿದೆ?',
        opts: ['The model queried a weather server directly', 'The model executed Python code', 'The model requested that application code invoke a tool -- it has not executed anything', 'Tokyo weather has already been retrieved by the model'], correct: 2,
        optsKn: ['Model ನೇರವಾಗಿ ಒಂದು weather server query ಮಾಡಿತು', 'Model Python code execute ಮಾಡಿತು', 'Model application code ಒಂದು tool invoke ಮಾಡಬೇಕೆಂದು ವಿನಂತಿಸಿತು -- ಇದೂ ಏನನ್ನೂ execute ಮಾಡಿಲ್ಲ', 'Tokyo weather ಈಗಾಗಲೇ model ಇಂದ retrieve ಆಗಿದೆ'] },
      { q: 'Genuinely confirmed: what did TOOL_REGISTRY["get_weather"]["function"] turn out to be?',
        qKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: TOOL_REGISTRY["get_weather"]["function"] ಏನೂ ಎಂದು ತಿಳಿಯಿತು?',
        opts: ['A string containing the function name', 'The already-computed weather result for a default city', 'The exact same function object as get_weather itself, confirmed via `is`', 'A copy of the function with a different identity'], correct: 2,
        optsKn: ['Function ya ಹೆಸರು ಒಳಗೊಂಡ ಒಂದು string', 'ಒಂದು ಡೀಫಾಲ್ಟ್ ನಗರಕ್ಕೆ ಈಗಾಗಲೇ-ಲೆಕ್ಕಹಾಕಿದ weather ಫಲಿತಾಂಶ', 'get_weather ಸ್ವತಃ ಗೆ ನಿಖರವಾಗಿ ಅದೇ function object, `is` ಮೂಲಕ ದೃಢಪಡಲಾಗಿದೆ', 'ಭಿನ್ನ identity ಜೊತೆ function ya ಒಂದು ನಕಲು'] },
      { q: 'Genuinely confirmed: why was calculator("10 + os.system(\'ls\')") rejected before eval() even ran?',
        qKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: calculator("10 + os.system(\'ls\')") eval() ಓಡುವ ಮೊದಲೇ ಏಕೆ ತಿರಸ್ಕರಿಸಲ್ಪಟ್ಟಿತು?',
        opts: ['eval() automatically blocks dangerous code', 'The character allowlist check caught letters like "o" and "s" outside the allowed arithmetic character set', 'The expression was too long', 'Python does not allow function calls inside strings'], correct: 1,
        optsKn: ['eval() ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಅಪಾಯಕಾರಿ code ಬ್ಲಾಕ್ ಮಾಡುತ್ತದೆ', 'Character allowlist check "o" ಮತ್ತು "s" ಯಂತಹ ಅಕ್ಷರಗಳನ್ನು ಅನುಮತಿಸಿದ arithmetic character set ya ಹೊರಗೆ ಹಿಡಿಯಿತು', 'Expression ಬಹಳ ಉದ್ದವಾಗಿತ್ತು', 'Python strings ಒಳಗೆ function calls ಅನುಮತಿಸುವುದಿಲ್ಲ'] },
      { q: 'Why does tool_choice=required not make a tool call\'s arguments safe to execute?',
        qKn: 'tool_choice=required ಒಂದು tool call ya arguments ಅನ್ನು execute ಮಾಡಲು ಸುರಕ್ಷಿತಗೊಳಿಸುವುದಿಲ್ಲ ಏಕೆ?',
        opts: ['tool_choice controls whether/which tool is called, not whether the arguments passed to it are validated or safe', 'required mode does not actually exist', 'Required calls always use default arguments', 'The model validates arguments automatically in required mode'], correct: 0,
        optsKn: ['tool_choice ಒಂದು tool ಕರೆಯಲ್ಪಡುತ್ತದೆಯೇ/ಯಾವುದೂ ನಿಯಂತ್ರಿಸುತ್ತದೆ, ಇದೂ ಗೆ ಕೊಟ್ಟ arguments ಪರಿಶೀಲಿಸಲ್ಪಟ್ಟಿವೆಯೇ ಅಥವಾ ಸುರಕ್ಷಿತವೇ ಎಂಬುದಲ್ಲ', 'required mode ನಿಜವಾಗಿ ಅಸ್ತಿತ್ವದಲ್ಲಿಲ್ಲ', 'Required calls ಯಾವಾಗಲೂ default arguments ಬಳಸುತ್ತವೆ', 'Model required mode ನಲ್ಲಿ arguments ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಪರಿಶೀಲಿಸುತ್ತದೆ'] },
      { q: 'How does function calling genuinely differ from structured output, even though both produce JSON?',
        qKn: 'ಎರಡೂ JSON ಉತ್ಪಾದಿಸಿದರೂ, function calling structured output ಇಂದ ನಿಜವಾಗಿ ಹೇಗೆ ಭಿನ್ನವಾಗಿದೆ?',
        opts: ['They are exactly identical concepts', 'Structured output IS the final answer; function calling is a REQUEST for the application to perform an action, not yet the answer', 'Function calling never uses JSON', 'Structured output requires a tool registry'], correct: 1,
        optsKn: ['ಇವು ನಿಖರವಾಗಿ ಒಂದೇ ಪರಿಕಲ್ಪನೆಗಳು', 'Structured output ಅಂತಿಮ ಉತ್ತರ; function calling application ಒಂದು ಕ್ರಿಯೆ ನಿರ್ವಹಿಸಲು ಒಂದು REQUEST, ಇನ್ನೂ ಉತ್ತರ ಅಲ್ಲ', 'Function calling ಎಂದಿಗೂ JSON ಬಳಸುವುದಿಲ್ಲ', 'Structured output ಗೆ ಒಂದು tool registry ಬೇಕು'] },
    ] } },
  ],
};
