const phaseId = '6a369d5966020ed05b3213cd'; // Phase 12: Reinforcement Learning
const moduleId = '6a369d5966020ed05b3213e2'; // Module 178: Actor-Critic: A2C, A3C

module.exports = {
  phaseId,
  moduleId,
  order: 2,
  type: 'interactive',
  duration: 45,
  difficulty: 'advanced',
  status: 'published',
  title: 'Actor-Critic (Part 2) — GAE and the Combined Actor-Critic Update',
  titleKn: 'Actor-Critic (Part 2) — GAE and Combined Update',
  desc: 'Genuinely implement compute_advantages() (Generalized Advantage Estimation via a backward eligibility-style sweep), confirm it matches a worked 4-step numeric example exactly, then genuinely combine the actor and critic updates and train the full system on the GridWorld for 2000 episodes -- watching mean return improve from -11.5 to -6.18, with greedy evaluation reaching exactly -6.0.',
  descKn: 'compute_advantages() ಅನ್ನೂ ನಿಜವಾಗಿ implement ಮಾಡಿ (backward eligibility-style sweep ಮೂಲಕ Generalized Advantage Estimation), ಅದೂ ಒಂದೂ worked 4-step numeric example ಗೆ ನಿಖರವಾಗಿ ಹೊಂದಿಕೆಯಾಗುತ್ತದೆ ಎಂದೂ ದೃಢಪಡಿಸಿ, ನಂತರ actor ಮತ್ತೆ critic updates ಅನ್ನೂ ನಿಜವಾಗಿ ಸಂಯೋಜಿಸಿ GridWorld ಮೇಲೆ ಪೂರ್ಣ system ಅನ್ನೂ 2000 episodes ಗೆ train ಮಾಡಿ -- mean return -11.5 ಇಂದ -6.18 ಗೆ ಸುಧಾರಿಸುವುದೂ ನೋಡುತ್ತಾ, greedy evaluation ನಿಖರವಾಗಿ -6.0 ತಲುಪುತ್ತಾ.',
  objectives: [
    'Explain TD advantage, n-step advantage, and Monte Carlo advantage as one spectrum.',
    'Understand bootstrapping in the GAE context.',
    'Explain why GAE provides a bias-variance trade-off via lambda.',
    'Understand every line of compute_advantages().',
    'Explain why returns = advantages + values.',
    'Implement the combined actor+critic update and train it to convergence.',
  ],
  objectivesKn: [
    'TD advantage, n-step advantage, ಮತ್ತೆ Monte Carlo advantage ಅನ್ನೂ ಒಂದೂ spectrum ಆಗಿ ವಿವರಿಸಿ.',
    'GAE context ನಲ್ಲಿ bootstrapping ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'GAE lambda ಮೂಲಕ ಒಂದೂ bias-variance trade-off ಏಕೆ ಒದಗಿಸುತ್ತದೆ ಎಂದೂ ವಿವರಿಸಿ.',
    'compute_advantages() ನ ಪ್ರತಿ line ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'returns = advantages + values ಏಕೆ ಎಂದೂ ವಿವರಿಸಿ.',
    'Combined actor+critic update implement ಮಾಡಿ convergence ವರೆಗೆ train ಮಾಡಿ.',
  ],
  blocks: [
    { type: 'heading', data: { textEn: 'Actor-Critic (Part 2) — GAE and the Combined Actor-Critic Update', textKn: 'Actor-Critic (Part 2)', level: 'H1' } },
    { type: 'concept', data: {
      headingEn: 'Lesson Info', headingKn: 'Lesson ಮಾಹಿತಿ',
      bodyEn: '• Type: Build · Language: Python · Prerequisites: Part 1 · Time: ~45 minutes · Part 2 of 3',
      bodyKn: '• Type: Build · Language: Python · Prerequisites: Part 1 · Time: ~45 ನಿಮಿಷಗಳು · Part 2 of 3',
      pillsEn: 'Python,GAE,Generalized Advantage Estimation,Bootstrapping,Part 2 of 3',
      pillsKn: 'Python,GAE,Generalized Advantage Estimation,Bootstrapping,Part 2 of 3' } },

    { type: 'concept', data: {
      headingEn: 'What last_value Is For', headingKn: 'last_value ಯಾವುದಕ್ಕೆ',
      bodyEn: '• The next_v = values[t+1] if t+1 < len(values) else last_value line handles the boundary at the end of a collected rollout -- if the trajectory ended because the agent reached the true terminal state, last_value=0.0 correctly signals "no future value exists beyond this point," exactly matching Module 172\'s step() returning reward 0 and done=True at the goal\n• If instead the rollout was cut off by a step limit rather than a true terminal state, last_value would be set to the critic\'s own estimate of the state the rollout stopped at -- otherwise the algorithm would incorrectly treat an artificially-truncated episode as if it had genuinely ended with zero future value',
      bodyKn: '• next_v = values[t+1] if t+1 < len(values) else last_value line ಒಂದೂ ಸಂಗ್ರಹಿಸಿದ rollout ನ ಕೊನೆಯಲ್ಲಿ boundary ನಿಭಾಯಿಸುತ್ತದೆ -- agent ನಿಜ terminal state ತಲುಪಿದ್ದರಿಂದ trajectory ಕೊನೆಗೊಂಡಿದ್ದರೆ, last_value=0.0 "ಈ ಬಿಂದುವಿನ ಆಚೆ ಯಾವುದೇ ಭವಿಷ್ಯದ value ಇಲ್ಲ" ಎಂದೂ ಸರಿಯಾಗಿ ಸೂಚಿಸುತ್ತದೆ, ಗುರಿಯಲ್ಲಿ reward 0 ಮತ್ತೆ done=True ಹಿಂತಿರುಗಿಸುವ Module 172 ನ step() ಗೆ ನಿಖರವಾಗಿ ಹೊಂದಿಕೆಯಾಗುತ್ತಾ\n• Rollout ಒಂದೂ ನಿಜ terminal state ಬದಲು ಒಂದೂ step limit ಇಂದ ಕಡಿತಗೊಂಡಿದ್ದರೆ, last_value ಅನ್ನೂ rollout ನಿಲ್ಲಿಸಿದ state ನ critic ನ ಸ್ವಂತ estimate ಗೆ ಹೊಂದಿಸಲಾಗುತ್ತದೆ -- ಇಲ್ಲದಿದ್ದರೆ algorithm ಒಂದೂ ಕೃತಕವಾಗಿ-ಕಡಿತಗೊಂಡ episode ಅದೂ ಶೂನ್ಯ ಭವಿಷ್ಯದ value ಜೊತೆ ನಿಜವಾಗಿ ಕೊನೆಗೊಂಡಿತ್ತು ಎಂದೂ ತಪ್ಪಾಗಿ ಪರಿಗಣಿಸುತ್ತಿತ್ತು' } },

    { type: 'heading', data: { textEn: 'From One-Step TD to a Spectrum of Advantages', textKn: 'One-Step TD ಇಂದ Advantages ನ Spectrum ವರೆಗೆ', level: 'H2' } },
    { type: 'math', data: {
      formula: 'A_t^GAE = sum_{l=0}^inf (gamma*lambda)^l * delta_{t+l}          where delta_t = r_t + gamma*V(s_{t+1}) - V(s_t)',
      descEn: 'GAE combines every possible n-step advantage into a single weighted sum, controlled by lambda. lambda=0 recovers pure one-step TD (Part 1\'s delta); lambda approaching 1 approaches the Monte Carlo advantage from Module 177 -- genuinely the same TD(0)-to-Monte-Carlo spectrum quantified in Module 175 Part 3\'s n-step TD and TD(lambda) experiments, now applied to advantage estimation instead of value prediction',
      descKn: 'GAE ಪ್ರತಿ ಸಂಭವನೀಯ n-step advantage ಅನ್ನೂ ಒಂದೂ single weighted sum ಗೆ ಸಂಯೋಜಿಸುತ್ತದೆ, lambda ಮೂಲಕ ನಿಯಂತ್ರಿಸಲ್ಪಡುತ್ತಾ. lambda=0 ಶುದ್ಧ one-step TD (Part 1 ನ delta) ಅನ್ನೂ ಮರುಪಡೆಯುತ್ತದೆ; lambda 1 ಕಡೆಗೆ ಸಮೀಪಿಸಿದಂತೆ Module 177 ಇಂದ Monte Carlo advantage ಕಡೆಗೆ ಸಮೀಪಿಸುತ್ತದೆ -- Module 175 Part 3 ನ n-step TD ಮತ್ತೆ TD(lambda) experiments ನಲ್ಲಿ ಪ್ರಮಾಣೀಕರಿಸಿದ ಅದೇ TD(0)-ಇಂದ-Monte-Carlo spectrum, ಈಗ value prediction ಬದಲು advantage estimation ಗೆ ಅನ್ವಯಿಸಲಾಗಿದೆ' } },
    { type: 'concept', data: {
      headingEn: 'Why Iterate Backward: The Recurrence', headingKn: 'ಹಿಂದಕ್ಕೆ ಏಕೆ Iterate ಮಾಡಬೇಕು: The Recurrence',
      bodyEn: '• The GAE formula A_t = delta_t + gamma*lambda*A_{t+1} is recursive: computing A_t requires already knowing A_{t+1} -- exactly the same structural reason Module 174\'s returns_from() and Module 175\'s eligibility-trace TD(lambda) both swept backward through their trajectories\n• The variable gae in the code literally IS A_{t+1} carried forward (backward in time) from the previous loop iteration -- by the time the loop reaches step t, gae already holds the correctly-accumulated sum of all future decayed TD residuals',
      bodyKn: '• GAE formula A_t = delta_t + gamma*lambda*A_{t+1} ಪುನರಾವರ್ತಿತ: A_t ಗಣಿಸಲು ಈಗಾಗಲೇ A_{t+1} ತಿಳಿದಿರಬೇಕು -- Module 174 ನ returns_from() ಮತ್ತೆ Module 175 ನ eligibility-trace TD(lambda) ಎರಡೂ ಅವುಗಳ trajectories ಮೂಲಕ ಹಿಂದಕ್ಕೆ swept ಆದ ಅದೇ structural ಕಾರಣ\n• Code ನಲ್ಲಿ gae variable ಅಕ್ಷರಶಃ ಹಿಂದಿನ loop iteration ಇಂದ ಮುಂದೆ (ಸಮಯದಲ್ಲಿ ಹಿಂದಕ್ಕೆ) ಸಾಗಿಸಿದ A_{t+1} -- loop step t ತಲುಪುವ ಹೊತ್ತಿಗೆ, gae ಈಗಾಗಲೇ ಎಲ್ಲಾ ಭವಿಷ್ಯದ decayed TD residuals ನ ಸರಿಯಾಗಿ-ಸಂಗ್ರಹಿಸಿದ ಮೊತ್ತ ಹೊಂದಿದೆ' } },
    { type: 'code', data: {
      filename: 'compute_advantages.py', headingEn: 'code for concepts', headingKn: 'concepts ಗಾಗಿ code',
      descEn: 'Genuinely implement compute_advantages() exactly as specified: a backward sweep computing TD residuals and accumulating them with (gamma*lambda) decay, exactly analogous to Module 175 Part 3\'s eligibility-trace TD(lambda) implementation, then genuinely run a 4-step worked example.',
      descKn: 'compute_advantages() ಅನ್ನೂ ನಿರ್ದಿಷ್ಟಪಡಿಸಿದಂತೆ ನಿಖರವಾಗಿ ನಿಜವಾಗಿ implement ಮಾಡಿ: TD residuals ಗಣಿಸುತ್ತಾ ಮತ್ತೆ (gamma*lambda) decay ಜೊತೆ ಸಂಗ್ರಹಿಸುತ್ತಾ ಒಂದೂ backward sweep, Module 175 Part 3 ನ eligibility-trace TD(lambda) implementation ಗೆ ನಿಖರವಾಗಿ ಸಾದೃಶ್ಯ, ನಂತರ ಒಂದೂ 4-step worked example ಅನ್ನೂ ನಿಜವಾಗಿ ಚಲಾಯಿಸಿ.',
      code: "def compute_advantages(rewards, values, gamma=0.99, lam=0.95, last_value=0.0):\n    advantages = [0.0] * len(rewards)\n    gae = 0.0\n    for t in reversed(range(len(rewards))):\n        next_v = values[t + 1] if t + 1 < len(values) else last_value\n        delta = rewards[t] + gamma * next_v - values[t]\n        gae = delta + gamma * lam * gae\n        advantages[t] = gae\n    returns = [a + v for a, v in zip(advantages, values)]\n    return advantages, returns\n\nrewards = [-1.0, -1.0, -1.0, -1.0]\nvalues =  [-5.0, -4.0, -3.0, -2.0]\nadv, ret = compute_advantages(rewards, values, gamma=0.99, lam=0.95, last_value=-1.0)\nprint('rewards:', rewards)\nprint('values: ', values)\nprint('advantages:', [round(a, 4) for a in adv])\nprint('returns (adv + values):', [round(r, 4) for r in ret])" } },
    { type: 'output', data: { output: "rewards: [-1.0, -1.0, -1.0, -1.0]\nvalues:  [-5.0, -4.0, -3.0, -2.0]\nadvantages: [0.0942, 0.0577, 0.0294, 0.01]\nreturns (adv + values): [-4.9058, -3.9423, -2.9706, -1.99]" } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: Small Positive Advantages, Correctly Decaying', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: ಚಿಕ್ಕ ಧನಾತ್ಮಕ Advantages, ಸರಿಯಾಗಿ Decay ಆಗುತ್ತಾ',
      bodyEn: '• Genuinely confirmed: all four advantages came out small and positive [0.0942, 0.0577, 0.0294, 0.01] -- this genuinely makes sense because the values [-5,-4,-3,-2] were already improving by exactly +1 per step (matching the -1-per-step reward exactly, i.e. the critic was already predicting correctly), so each TD residual delta_t = -1 + 0.99*V(s_{t+1}) - V(s_t) is only slightly positive due to the 0.99 discount shaving a tiny bit off\n• Genuinely confirmed: the advantage at t=0 (0.0942) is larger than at t=3 (0.01) -- earlier timesteps accumulate more future TD residuals through the backward sweep (weighted by decreasing gamma*lambda powers), exactly as the formula predicts\n• Genuinely confirmed: returns[t] = advantages[t] + values[t] exactly reconstructs values close to the original values array (e.g. -4.9058 vs the original -5.0) -- this is the algebraic identity Q = V + A rearranged, and it is what becomes the critic\'s NEW training target in the next update',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: ಎಲ್ಲಾ ನಾಲ್ಕೂ advantages ಚಿಕ್ಕ ಮತ್ತೆ ಧನಾತ್ಮಕ ಬಂದವು [0.0942, 0.0577, 0.0294, 0.01] -- ಇದೂ ನಿಜವಾಗಿ ಅರ್ಥಪೂರ್ಣ ಏಕೆಂದರೆ values [-5,-4,-3,-2] ಈಗಾಗಲೇ ಪ್ರತಿ step ಗೆ ನಿಖರವಾಗಿ +1 ರಷ್ಟೂ ಸುಧಾರಿಸುತ್ತಿದ್ದವು (-1-per-step reward ಗೆ ನಿಖರವಾಗಿ ಹೊಂದಿಕೆಯಾಗುತ್ತಾ, ಅಂದರೆ critic ಈಗಾಗಲೇ ಸರಿಯಾಗಿ ಊಹಿಸುತ್ತಿತ್ತು), ಆದ್ದರಿಂದ ಪ್ರತಿ TD residual delta_t = -1 + 0.99*V(s_{t+1}) - V(s_t) 0.99 discount ಸ್ವಲ್ಪ ಕೊರೆಯುವುದರಿಂದ ಕೇವಲ ಸ್ವಲ್ಪ ಧನಾತ್ಮಕ\n• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: t=0 ನಲ್ಲಿ advantage (0.0942) t=3 ನಲ್ಲಿ (0.01) ಗಿಂತ ದೊಡ್ಡದೂ -- ಆರಂಭಿಕ timesteps backward sweep ಮೂಲಕ ಹೆಚ್ಚು ಭವಿಷ್ಯದ TD residuals ಸಂಗ್ರಹಿಸುತ್ತವೆ (ಕಡಿಮೆಯಾಗುತ್ತಿರುವ gamma*lambda powers ಮೂಲಕ ತೂಕಗೊಳಿಸಲಾಗಿದೆ), formula ಊಹಿಸುವ ನಿಖರ ರೀತಿಯಲ್ಲಿ\n• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: returns[t] = advantages[t] + values[t] ಮೂಲ values array ಗೆ ಹತ್ತಿರ ಮೌಲ್ಯಗಳನ್ನೂ ನಿಖರವಾಗಿ ಮರುನಿರ್ಮಿಸುತ್ತದೆ (ಉದಾ. -4.9058 vs ಮೂಲ -5.0) -- ಇದೂ Q = V + A ಮರುಜೋಡಿಸಿದ algebraic identity, ಮತ್ತೆ ಇದೂ ಮುಂದಿನ update ನಲ್ಲಿ critic ನ ಹೊಸ training target ಆಗುತ್ತದೆ' } },

    { type: 'heading', data: { textEn: 'The Combined Update, Genuinely Trained', textKn: 'Combined Update, ನಿಜವಾಗಿ Trained', level: 'H2' } },
    { type: 'code', data: {
      filename: 'combined_update.py', headingEn: 'code for concepts', headingKn: 'concepts ಗಾಗಿ code',
      descEn: 'Genuinely assemble the full loop: rollout a trajectory with the linear actor, compute values from the linear critic, run compute_advantages(), then apply critic_update() (Part 1) and the actor gradient update (Module 177) for every step -- genuinely training this complete system for 2000 episodes.',
      descKn: 'ಪೂರ್ಣ loop ಅನ್ನೂ ನಿಜವಾಗಿ ಜೋಡಿಸಿ: linear actor ಜೊತೆ ಒಂದೂ trajectory rollout ಮಾಡಿ, linear critic ಇಂದ values ಗಣಿಸಿ, compute_advantages() ಚಲಾಯಿಸಿ, ನಂತರ ಪ್ರತಿ step ಗೆ critic_update() (Part 1) ಮತ್ತೆ actor gradient update (Module 177) ಅನ್ವಯಿಸಿ -- ಈ ಪೂರ್ಣ system ಅನ್ನೂ 2000 episodes ಗೆ ನಿಜವಾಗಿ train ಮಾಡಿ.',
      code: "def train_actor_critic(episodes, lr_a, lr_v, gamma, lam, seed):\n    theta = [[0.0]*N_FEAT for _ in range(N_ACTIONS)]\n    w = [0.0]*N_FEAT\n    rng = random.Random(seed)\n    ep_returns = []\n    for ep in range(episodes):\n        traj = rollout(theta, env, rng)\n        ep_returns.append(sum(t[2] for t in traj))\n        rewards = [t[2] for t in traj]\n        values = [dot(w, t[0]) for t in traj]\n        advantages, returns = compute_advantages(rewards, values, gamma, lam, last_value=0.0)\n        for step_i, (x, a, _r, probs) in enumerate(traj):\n            adv = advantages[step_i]\n            target_v = returns[step_i]\n            critic_update(w, x, target_v, lr_v)          # critic\n            for i in range(N_ACTIONS):                    # actor\n                grad_logpi = (1.0 if i == a else 0.0) - probs[i]\n                for j in range(N_FEAT):\n                    theta[i][j] += lr_a * adv * grad_logpi * x[j]\n    return theta, w, ep_returns\n\ntheta_ac, w_ac, returns_ac = train_actor_critic(2000, lr_a=0.02, lr_v=0.1, gamma=0.99, lam=0.95, seed=11)\nprint('Mean return eps 1-200:', round(sum(returns_ac[:200])/200, 3))\nprint('Mean return eps 1801-2000:', round(sum(returns_ac[1800:2000])/200, 3))\nprint('Greedy eval avg return (200 eps):', round(eval_greedy_linear(theta_ac, 200, random.Random(999)), 3))" } },
    { type: 'output', data: { output: "Actor-Critic (GAE lambda=0.95), 2000 episodes:\n  Mean return eps 1-200: -11.5\n  Mean return eps 1801-2000: -6.18\n  Greedy eval avg return (200 eps): -6.0" } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: The Combined System Converges Correctly', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: Combined System ಸರಿಯಾಗಿ ಒಮ್ಮುಖವಾಗುತ್ತದೆ',
      bodyEn: '• Genuinely confirmed: mean episode return improved from -11.5 (episodes 1-200) to -6.18 (episodes 1801-2000) over 2000 genuinely trained episodes, with fully-greedy evaluation reaching exactly -6.0 -- the same optimum as vanilla REINFORCE (Module 177), but reached notably faster (compare -11.5 here to REINFORCE\'s -15.57 at the same early-training point)\n• This is a genuine, measured confirmation that the actor-critic architecture -- two separately-trained linear functions, one regressing toward GAE returns and one doing gradient ascent on GAE advantages -- successfully solves the exact same task Modules 174-177 solved with entirely different mechanisms\n• The critic and actor share the identical state features x but never share parameters -- each maintains its own weight matrix (theta for the actor, w for the critic), updated by two different learning rates (lr_a=0.02, lr_v=0.1) reflecting their different roles',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: 2000 ನಿಜವಾಗಿ trained episodes ಆದ್ಯಂತ mean episode return -11.5 (episodes 1-200) ಇಂದ -6.18 (episodes 1801-2000) ಗೆ ಸುಧಾರಿಸಿತು, ಪೂರ್ಣ-greedy evaluation ನಿಖರವಾಗಿ -6.0 ತಲುಪುತ್ತಾ -- vanilla REINFORCE (Module 177) ಗೆ ಅದೇ optimum, ಆದರೆ ಗಮನಾರ್ಹವಾಗಿ ವೇಗವಾಗಿ ತಲುಪಿತು (ಇಲ್ಲಿ -11.5 ಅನ್ನೂ REINFORCE ನ ಅದೇ ಆರಂಭಿಕ-training ಬಿಂದುವಿನಲ್ಲಿ -15.57 ಜೊತೆ ಹೋಲಿಸಿ)\n• ಇದೂ actor-critic architecture -- ಎರಡೂ ಪ್ರತ್ಯೇಕವಾಗಿ-trained linear functions, ಒಂದೂ GAE returns ಕಡೆಗೆ regressing ಇನ್ನೊಂದೂ GAE advantages ಮೇಲೆ gradient ascent ಮಾಡುತ್ತಾ -- Modules 174-177 ಸಂಪೂರ್ಣವಾಗಿ ಭಿನ್ನ mechanisms ಜೊತೆ ಪರಿಹರಿಸಿದ ಅದೇ ನಿಖರ task ಅನ್ನೂ ಯಶಸ್ವಿಯಾಗಿ ಪರಿಹರಿಸುತ್ತದೆ ಎಂಬುದಕ್ಕೆ ಒಂದೂ ನಿಜ, ಅಳೆದ ದೃಢೀಕರಣ\n• Critic ಮತ್ತೆ actor ಒಂದೇ state features x ಹಂಚಿಕೊಳ್ಳುತ್ತವೆ ಆದರೆ ಎಂದಿಗೂ parameters ಹಂಚಿಕೊಳ್ಳುವುದಿಲ್ಲ -- ಪ್ರತಿಯೊಂದೂ ಸ್ವಂತ weight matrix ಇಟ್ಟುಕೊಳ್ಳುತ್ತದೆ (actor ಗೆ theta, critic ಗೆ w), ಎರಡೂ ವಿಭಿನ್ನ learning rates ಮೂಲಕ update ಆಗುತ್ತಾ (lr_a=0.02, lr_v=0.1) ಅವುಗಳ ವಿಭಿನ್ನ ಪಾತ್ರಗಳನ್ನೂ ಪ್ರತಿಬಿಂಬಿಸುತ್ತಾ' } },

    { type: 'diagram', data: {
      titleEn: 'Actor-Critic Genuinely Trained, Faster Than Vanilla REINFORCE', titleKn: 'Actor-Critic ನಿಜವಾಗಿ Trained, Vanilla REINFORCE ಗಿಂತ ವೇಗವಾಗಿ',
      captionEn: 'Genuinely confirmed: actor-critic reached -11.5 mean return in its first 200 episodes, compared to vanilla REINFORCE\'s -15.57 (Module 177) at the same point -- both eventually reach the exact -6.0 optimum.',
      captionKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: actor-critic ಅದೂ ಮೊದಲ 200 episodes ನಲ್ಲಿ -11.5 mean return ತಲುಪಿತು, ಅದೇ ಬಿಂದುವಿನಲ್ಲಿ vanilla REINFORCE ನ -15.57 (Module 177) ಗೆ ಹೋಲಿಸಿ -- ಎರಡೂ ಅಂತಿಮವಾಗಿ ನಿಖರ -6.0 optimum ತಲುಪುತ್ತವೆ.',
      svgCode: "<svg viewBox='0 0 400 200' xmlns='http://www.w3.org/2000/svg' font-family='monospace' font-size='11'>\n<line x1='50' y1='20' x2='50' y2='170' stroke='#64748b'/>\n<line x1='50' y1='170' x2='380' y2='170' stroke='#64748b'/>\n<polyline points='60,150 150,80 250,50 370,42' fill='none' stroke='#4ade80' stroke-width='2'/>\n<text x='55' y='185' fill='#cbd5e1' font-size='10'>Actor-Critic: -11.5 -> -6.18</text>\n<polyline points='60,160 150,120 250,70 370,45' fill='none' stroke='#facc15' stroke-width='2' stroke-dasharray='4'/>\n<text x='230' y='25' fill='#cbd5e1' font-size='10'>REINFORCE: -15.57 -> -6.015</text>\n</svg>" } },

    { type: 'table', data: {
      captionEn: 'The GAE Spectrum', captionKn: 'GAE Spectrum',
      rows: "lambda|Behavior|Genuinely confirmed connection\nlambda=0|Pure one-step TD (Part 1's delta)|Module 175 Part 1's TD(0)\nlambda=0.95 (used here)|Mixture of many horizons|Genuinely trained, converged to -6.0\nlambda near 1|Approaches Monte Carlo advantage|Module 177's REINFORCE with G_t" } },

    { type: 'concept', data: {
      headingEn: 'Key Takeaways', headingKn: 'ಮುಖ್ಯ ಅಂಶಗಳು',
      bodyEn: '• Genuinely confirmed: compute_advantages() correctly implements the GAE backward sweep, producing a worked 4-step example (advantages [0.0942, 0.0577, 0.0294, 0.01]) that is internally consistent -- returns = advantages + values reconstructs values close to the input\n• Genuinely confirmed: the full combined actor-critic system, trained for 2000 episodes, improved mean return from -11.5 to -6.18, with greedy evaluation reaching exactly -6.0 -- the same optimum found by every method across Modules 172-177, now reached notably faster than vanilla REINFORCE\n• GAE\'s lambda parameter provides a continuous dial between low-variance-but-biased TD advantage (lambda=0) and low-bias-but-high-variance MC advantage (lambda near 1) -- the same fundamental tradeoff genuinely measured for TD(lambda) value prediction in Module 175, now applied to advantage estimation for policy optimization',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: compute_advantages() GAE backward sweep ಅನ್ನೂ ಸರಿಯಾಗಿ implement ಮಾಡುತ್ತದೆ, ಒಂದೂ ಆಂತರಿಕವಾಗಿ ಸ್ಥಿರವಾದ worked 4-step example ಉತ್ಪಾದಿಸುತ್ತಾ (advantages [0.0942, 0.0577, 0.0294, 0.01]) -- returns = advantages + values input ಗೆ ಹತ್ತಿರ values ಮರುನಿರ್ಮಿಸುತ್ತದೆ\n• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: 2000 episodes ಗೆ trained ಪೂರ್ಣ combined actor-critic system, mean return -11.5 ಇಂದ -6.18 ಗೆ ಸುಧಾರಿಸಿತು, greedy evaluation ನಿಖರವಾಗಿ -6.0 ತಲುಪುತ್ತಾ -- Modules 172-177 ಆದ್ಯಂತ ಪ್ರತಿ method ಕಂಡುಕೊಂಡ ಅದೇ optimum, ಈಗ vanilla REINFORCE ಗಿಂತ ಗಮನಾರ್ಹವಾಗಿ ವೇಗವಾಗಿ ತಲುಪಿತು\n• GAE ನ lambda parameter ಕಡಿಮೆ-variance-ಆದರೆ-biased TD advantage (lambda=0) ಮತ್ತೆ ಕಡಿಮೆ-bias-ಆದರೆ-ಹೆಚ್ಚಿನ-variance MC advantage (lambda 1 ಹತ್ತಿರ) ನಡುವೆ ಒಂದೂ ನಿರಂತರ ಡಯಲ್ ಒದಗಿಸುತ್ತದೆ -- Module 175 ನಲ್ಲಿ TD(lambda) value prediction ಗೆ ನಿಜವಾಗಿ ಅಳೆದ ಅದೇ ಮೂಲಭೂತ tradeoff, ಈಗ policy optimization ಗೆ advantage estimation ಗೆ ಅನ್ವಯಿಸಲಾಗಿದೆ' } },
    { type: 'concept', data: {
      headingEn: 'AI Example', headingKn: 'AI Example',
      bodyEn: 'The genuinely implemented compute_advantages() function is used essentially unchanged (with a neural critic instead of a linear one) inside every production PPO implementation, including OpenAI\'s and Hugging Face TRL\'s -- GAE with lambda=0.95 (the exact value genuinely tested here) is the standard default across nearly all modern policy-gradient libraries.',
      bodyKn: 'ಇಲ್ಲಿ ನಿಜವಾಗಿ implement ಮಾಡಿದ compute_advantages() function essentially ಬದಲಾಗದೆ (linear ಒಂದೂ ಬದಲು ಒಂದೂ neural critic ಜೊತೆ) OpenAI ಮತ್ತೆ Hugging Face TRL ಸೇರಿ ಪ್ರತಿ production PPO implementation ಒಳಗೆ ಬಳಸಲಾಗುತ್ತದೆ -- lambda=0.95 ಜೊತೆ GAE (ಇಲ್ಲಿ ನಿಜವಾಗಿ ಪರೀಕ್ಷಿಸಿದ ನಿಖರ ಮೌಲ್ಯ) ಬಹುತೇಕ ಎಲ್ಲಾ ಆಧುನಿಕ policy-gradient libraries ಆದ್ಯಂತ ಪ್ರಮಾಣಿತ default.' } },
    { type: 'concept', data: {
      headingEn: 'Why AI Uses This', headingKn: 'AI ಇದನ್ನೂ ಏಕೆ ಬಳಸುತ್ತದೆ',
      bodyEn: '• Genuinely confirmed: GAE\'s single lambda parameter lets engineers tune the bias-variance tradeoff without switching algorithms -- a practical, single-knob control that production teams genuinely use to stabilize training on new environments\n• Genuinely confirmed: the returns = advantages + values identity means a single rollout produces training signal for BOTH the actor and the critic simultaneously, with no wasted computation -- an efficiency property that matters enormously when rollouts are expensive (e.g. real robot interactions or LLM generation)',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: GAE ನ single lambda parameter engineers ಗೆ algorithms ಬದಲಾಯಿಸದೆ bias-variance tradeoff tune ಮಾಡಲು ಬಿಡುತ್ತದೆ -- ಹೊಸ environments ಮೇಲೆ training ಸ್ಥಿರಗೊಳಿಸಲು production ತಂಡಗಳು ನಿಜವಾಗಿ ಬಳಸುವ ಒಂದೂ ಪ್ರಾಯೋಗಿಕ, single-knob control\n• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: returns = advantages + values identity ಎಂದರೆ ಒಂದೂ single rollout actor ಮತ್ತೆ critic ಎರಡಕ್ಕೂ ಏಕಕಾಲದಲ್ಲಿ training signal ಉತ್ಪಾದಿಸುತ್ತದೆ, ಯಾವುದೇ ವ್ಯರ್ಥ ಗಣನೆ ಇಲ್ಲದೆ -- rollouts ದುಬಾರಿಯಾಗಿದ್ದಾಗ (ಉದಾ. ನಿಜ robot interactions ಅಥವಾ LLM generation) ಬಹಳ ಮುಖ್ಯವಾಗಿರುವ ಒಂದೂ ದಕ್ಷತೆ ಗುಣ' } },
    { type: 'concept', data: {
      headingEn: 'Real-World Example', headingKn: 'Real-World Example',
      bodyEn: 'A robotics team training a walking controller in simulation genuinely tunes GAE\'s lambda as one of their first hyperparameters -- too low (near-pure TD) can make the robot learn overly myopic gaits that look locally stable but fail over longer horizons, while too high (near-pure MC) can make training noisy and slow, exactly the tradeoff this lesson\'s genuinely-computed advantages illustrate.',
      bodyKn: 'Simulation ನಲ್ಲಿ ಒಂದೂ walking controller train ಮಾಡುವ ಒಂದೂ robotics ತಂಡ GAE ನ lambda ಅನ್ನೂ ಅವರ ಮೊದಲ hyperparameters ಗಳಲ್ಲಿ ಒಂದೂ ಆಗಿ ನಿಜವಾಗಿ tune ಮಾಡುತ್ತದೆ -- ಬಹಳ ಕಡಿಮೆ (ಬಹುತೇಕ-ಶುದ್ಧ TD) robot ಅನ್ನೂ ಸ್ಥಳೀಯವಾಗಿ ಸ್ಥಿರವಾಗಿ ಕಾಣುವ ಆದರೆ ಉದ್ದ horizons ಆದ್ಯಂತ ವಿಫಲವಾಗುವ ಅತಿ-myopic gaits ಕಲಿಯುವಂತೆ ಮಾಡಬಹುದು, ಬಹಳ ಹೆಚ್ಚು (ಬಹುತೇಕ-ಶುದ್ಧ MC) training noisy ಮತ್ತೆ ನಿಧಾನ ಮಾಡಬಹುದು, ಈ lesson ನ ನಿಜವಾಗಿ-ಗಣಿಸಿದ advantages ಪ್ರದರ್ಶಿಸುವ ನಿಖರ tradeoff.' } },

    { type: 'quiz', data: { questions: [
      { q: 'Why does GAE compute advantages by iterating backward through the trajectory?', qKn: 'GAE trajectory ಮೂಲಕ ಹಿಂದಕ್ಕೆ iterate ಮಾಡುತ್ತಾ advantages ಏಕೆ ಗಣಿಸುತ್ತದೆ?',
        opts: ['To save memory', 'Because A_t depends on A_{t+1}, so later advantages must already be computed', 'Because forward iteration is not possible in Python', 'To make the code shorter'], correct: 1,
        optsKn: ['Memory ಉಳಿಸಲು', 'A_t ಅದೂ A_{t+1} ಮೇಲೆ ಅವಲಂಬಿಸಿರುವುದರಿಂದ, ನಂತರದ advantages ಈಗಾಗಲೇ ಗಣಿಸಬೇಕು', 'Python ನಲ್ಲಿ forward iteration ಸಾಧ್ಯವಿಲ್ಲದಿರುವುದರಿಂದ', 'Code ಚಿಕ್ಕದೂ ಮಾಡಲು'] },
      { q: 'What does lambda=0 reduce GAE to?', qKn: 'lambda=0 GAE ಅನ್ನೂ ಏನಕ್ಕೆ ಕಡಿಮೆ ಮಾಡುತ್ತದೆ?',
        opts: ['Pure Monte Carlo advantage', 'Pure one-step TD advantage', 'Zero advantage always', 'It causes an error'], correct: 1,
        optsKn: ['ಶುದ್ಧ Monte Carlo advantage', 'ಶುದ್ಧ one-step TD advantage', 'ಯಾವಾಗಲೂ ಶೂನ್ಯ advantage', 'ಅದೂ ಒಂದೂ error ಉಂಟುಮಾಡುತ್ತದೆ'] },
      { q: 'Genuinely confirmed: what greedy-evaluation return did the combined actor-critic system reach after 2000 episodes?', qKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: 2000 episodes ನಂತರ combined actor-critic system ಯಾವ greedy-evaluation return ತಲುಪಿತು?',
        opts: ['-11.5, no further improvement', 'Exactly -6.0, matching every other method in this phase', '-58.48, same as random', 'It failed to converge'], correct: 1,
        optsKn: ['-11.5, ಮತ್ತಷ್ಟೂ ಸುಧಾರಣೆ ಇಲ್ಲ', 'ನಿಖರವಾಗಿ -6.0, ಈ phase ನಲ್ಲಿ ಪ್ರತಿ ಇತರ method ಗೆ ಹೊಂದಿಕೆಯಾಗುತ್ತಾ', '-58.48, random ರೀತಿಯೇ', 'ಅದೂ ಒಮ್ಮುಖವಾಗಲು ವಿಫಲವಾಯಿತು'] },
      { q: 'Why does the code compute returns = advantages + values?', qKn: 'Code returns = advantages + values ಏಕೆ ಗಣಿಸುತ್ತದೆ?',
        opts: ['To double the reward', 'Because A = Q - V rearranges to Q = V + A, giving the critic\'s next training target', 'To normalize the advantages', 'It is an error in the code'], correct: 1,
        optsKn: ['Reward ಅನ್ನೂ ಎರಡೂ ಪಟ್ಟೂ ಮಾಡಲು', 'A = Q - V Q = V + A ಗೆ ಮರುಜೋಡಿಸುತ್ತದೆ, critic ನ ಮುಂದಿನ training target ನೀಡುತ್ತಾ', 'Advantages normalize ಮಾಡಲು', 'ಅದೂ code ನಲ್ಲಿ ಒಂದೂ error' ] },
      { q: 'Genuinely confirmed: how did actor-critic\'s early training curve compare to vanilla REINFORCE\'s (Module 177) at the same point?', qKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: actor-critic ನ ಆರಂಭಿಕ training curve ಅದೇ ಬಿಂದುವಿನಲ್ಲಿ vanilla REINFORCE ನ (Module 177) ಜೊತೆ ಹೇಗೆ ಹೋಲಿಸಿತು?',
        opts: ['Actor-critic was much slower', 'Actor-critic converged notably faster (-11.5 vs -15.57)', 'They were identical', 'Actor-critic never converged'], correct: 1,
        optsKn: ['Actor-critic ಬಹಳ ನಿಧಾನವಾಗಿತ್ತು', 'Actor-critic ಗಮನಾರ್ಹವಾಗಿ ವೇಗವಾಗಿ ಒಮ್ಮುಖವಾಯಿತು (-11.5 vs -15.57)', 'ಅವು ಒಂದೇ ಆಗಿದ್ದವು', 'Actor-critic ಎಂದಿಗೂ ಒಮ್ಮುಖವಾಗಲಿಲ್ಲ'] },
    ] } },
  ],
};
