const phaseId = '6a369d5c66020ed05b32143f'; // Phase 14: LLM Engineering
const moduleId = '6a369d5c66020ed05b321442'; // Module 208: Prompt Engineering: Techniques and Patterns

module.exports = {
  phaseId,
  moduleId,
  order: 2,
  type: 'interactive',
  duration: 40,
  difficulty: 'advanced',
  status: 'published',
  title: 'Prompt Engineering — Part 3: Testing, Scoring, and Comparing Models',
  titleKn: 'Prompt Engineering — ಭಾಗ 3: Testing, Scoring, ಮತ್ತು Models Comparison',
  desc: 'Genuinely build simulate_llm_call() with a real MD5 prompt hash, genuinely implement and test score_response() across keyword/format/violation criteria, and genuinely compute a discount-vs-coupon math example that exposes exactly where surface-level scoring diverges from actual correctness.',
  descKn: "Ondu nija MD5 prompt hash jote simulate_llm_call() ಅನ್ನೂ ನಿಜವಾಗಿ ನಿರ್ಮಿಸಿ, keyword/format/violation criteria ಗಳಾದ್ಯಂತ score_response() ಅನ್ನೂ ನಿಜವಾಗಿ ಜಾರಿಗೊಳಿಸಿ ಪರೀಕ್ಷಿಸಿ, ಮತ್ತೆ surface-level scoring ನಿಜ correctness ಇಂದ ನಿಖರವಾಗಿ ಎಲ್ಲಿ ಭಿನ್ನವಾಗುತ್ತದೆ ಎಂದೂ ಬಹಿರಂಗಪಡಿಸುವ ಒಂದೂ discount-vs-coupon math ಉದಾಹರಣೆಯನ್ನೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಿ.",
  objectives: [
    'Genuinely implement simulate_llm_call() and confirm its MD5-based prompt hash is deterministic for identical requests.',
    'Genuinely implement run_prompt_test() and explain the difference between API-reported latency and locally-measured wall time.',
    'Genuinely implement and test score_response() across word_count, keyword_coverage, no_violations, format_valid (json/bullet/numbered), and composite_score.',
    'Genuinely implement compare_models() and confirm its ranking logic via sorted() with a lambda key.',
    'Genuinely compute a discount-vs-coupon arithmetic example, confirming order of operations changes the final price by a real, checkable amount.',
    'Explain why a perfect composite_score does not guarantee semantic correctness, and connect this back to Part 1\'s Common Misconception about decorative prompt engineering.',
  ],
  objectivesKn: [
    'simulate_llm_call() ಅನ್ನೂ ನಿಜವಾಗಿ ಜಾರಿಗೊಳಿಸಿ ಮತ್ತೆ ಒಂದೇ requests ಗಾಗಿ ಇದೂ ya MD5-based prompt hash deterministic ಎಂದೂ ದೃಢಪಡಿಸಿ.',
    'run_prompt_test() ಅನ್ನೂ ನಿಜವಾಗಿ ಜಾರಿಗೊಳಿಸಿ ಮತ್ತೆ API-reported latency ಮತ್ತೆ locally-measured wall time ನಡುವಿನ ವ್ಯತ್ಯಾಸ ವಿವರಿಸಿ.',
    'word_count, keyword_coverage, no_violations, format_valid (json/bullet/numbered), ಮತ್ತೆ composite_score ಗಳಾದ್ಯಂತ score_response() ಅನ್ನೂ ನಿಜವಾಗಿ ಜಾರಿಗೊಳಿಸಿ ಪರೀಕ್ಷಿಸಿ.',
    'compare_models() ಅನ್ನೂ ನಿಜವಾಗಿ ಜಾರಿಗೊಳಿಸಿ ಮತ್ತೆ sorted() ಮತ್ತೆ ಒಂದೂ lambda key ಮೂಲಕ ಇದೂ ya ranking logic ದೃಢಪಡಿಸಿ.',
    'Ondu discount-vs-coupon arithmetic ಉದಾಹರಣೆಯನ್ನೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಿ, operations ya ಕ್ರಮ ಅಂತಿಮ ಬೆಲೆಯನ್ನೂ ಒಂದೂ ನಿಜ, ಪರಿಶೀಲಿಸಬಹುದಾದ ಮೊತ್ತದಿಂದ ಬದಲಾಯಿಸುತ್ತದೆ ಎಂದೂ ದೃಢಪಡಿಸಿ.',
    'Ondu perfect composite_score semantic correctness ಗ್ಯಾರಂಟಿ ನೀಡುವುದಿಲ್ಲ ಎಂದೂ ವಿವರಿಸಿ, ಇದನ್ನೂ Part 1 ya decorative prompt engineering Common Misconception ಗೆ ಮರುಸಂಪರ್ಕಿಸಿ.',
  ],
  blocks: [
    { type: 'heading', data: { textEn: 'Prompt Engineering — Part 3: Testing, Scoring, and Comparing Models', textKn: 'Prompt Engineering — ಭಾಗ 3: Testing, Scoring, ಮತ್ತು Comparison', level: 'H1' } },
    { type: 'concept', data: {
      headingEn: 'Lesson Info', headingKn: 'ಪಾಠದ ಮಾಹಿತಿ',
      bodyEn: '• Type: Build · Language: Python · Prerequisite: Parts 1-2 of this module · Time: ~40 minutes · Part 3 of 3',
      bodyKn: '• ಪ್ರಕಾರ: Build · ಭಾಷೆ: Python · ಪೂರ್ವಾಪೇಕ್ಷಿತ: ಈ module ಯ ಭಾಗ 1-2 · ಸಮಯ: ~40 ನಿಮಿಷಗಳು · ಭಾಗ 3 ರಲ್ಲಿ 3',
      pillsEn: 'simulate_llm_call,score_response,compare_models,MD5 Hash,Composite Score',
      pillsKn: 'simulate_llm_call,score_response,compare_models,Composite Score' } },

    { type: 'heading', data: { textEn: 'Simulating a Model Call Without a Real API', textKn: 'ಒಂದು ನಿಜ API ಇಲ್ಲದೆ ಒಂದು Model Call Simulate ಮಾಡುವುದು', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'A Test Harness Needs a Deterministic Stand-In for the Real Network Call', headingKn: 'ಒಂದು Test Harness ಗೆ ನಿಜ Network Call ಗೆ Deterministic Stand-In ಬೇಕಾಗುತ್ತದೆ',
      bodyEn: 'Parts 1-2 built build_prompt() and the three format_*_request() functions, producing a real, provider-specific request body -- but running this lesson\'s tests against a live API would cost money, require API keys, and make output non-reproducible across runs. simulate_llm_call(model_name, request) stands in for the network call: it sleeps briefly (time.sleep(0.01)) to mimic latency, computes an MD5 hash of the request via hashlib.md5(json.dumps(request, sort_keys=True).encode()).hexdigest()[:8], and returns a per-model canned response string that embeds that hash. sort_keys=True is what makes the hash deterministic regardless of dict insertion order -- two logically identical requests built through different code paths still hash identically.',
      bodyKn: 'Parts 1-2 build_prompt() ಮತ್ತೆ ಮೂರೂ format_*_request() functions ಅನ್ನೂ ನಿರ್ಮಿಸಿದವು, ಒಂದೂ ನಿಜ, provider-specific request body ಉತ್ಪಾದಿಸುತ್ತಾ -- ಆದರೆ ಈ lesson ya tests ಅನ್ನೂ ಒಂದೂ live API ಎದುರೂ ಓಡಿಸುವುದೂ ಹಣ ಖರ್ಚಾಗುತ್ತದೆ, API keys ಬೇಕಾಗುತ್ತದೆ, ಮತ್ತೆ ಓಟಗಳಾದ್ಯಂತ output ಅನ್ನೂ non-reproducible ಮಾಡುತ್ತದೆ. simulate_llm_call(model_name, request) network call ಗೆ ಬದಲಿಯಾಗಿ ನಿಲ್ಲುತ್ತದೆ: ಇದೂ latency ಅನ್ನೂ ಅನುಕರಿಸಲು ಸಂಕ್ಷಿಪ್ತವಾಗಿ ನಿದ್ರಿಸುತ್ತದೆ (time.sleep(0.01)), hashlib.md5(json.dumps(request, sort_keys=True).encode()).hexdigest()[:8] ಮೂಲಕ request ya ಒಂದೂ MD5 hash ಲೆಕ್ಕಹಾಕುತ್ತದೆ, ಮತ್ತೆ ಆ hash ಅನ್ನೂ ಒಳಗೊಂಡ ಒಂದೂ per-model canned response string ಹಿಂತಿರುಗಿಸುತ್ತದೆ. sort_keys=True ಎಂಬುದೂ dict insertion order ಏನೇ ಇರಲಿ hash ಅನ್ನೂ deterministic ಮಾಡುತ್ತದೆ -- ಎರಡೂ ತಾರ್ಕಿಕವಾಗಿ ಒಂದೇ ರೀತಿಯ requests ಭಿನ್ನ code paths ಮೂಲಕ ನಿರ್ಮಿಸಲಾಗಿದ್ದರೂ ಒಂದೇ ರೀತಿ hash ಆಗುತ್ತವೆ.' } },
    { type: 'code', data: {
      filename: 'simulate_llm_call.py', headingEn: 'Genuinely implementing and testing simulate_llm_call()', headingKn: 'simulate_llm_call() ಅನ್ನೂ ನಿಜವಾಗಿ ಜಾರಿಗೊಳಿಸಿ ಪರೀಕ್ಷಿಸುವುದೂ',
      descEn: 'Build the function and confirm the MD5 hash is deterministic and per-model responses embed it.',
      descKn: 'Function ನಿರ್ಮಿಸಿ ಮತ್ತೆ MD5 hash deterministic ಎಂದೂ ಮತ್ತೆ per-model responses ಇದೂ ಒಳಗೊಂಡಿವೆ ಎಂದೂ ದೃಢಪಡಿಸಿ.',
      code: "import hashlib, json, time\n\ndef simulate_llm_call(model_name, request):\n    time.sleep(0.01)\n    prompt_hash = hashlib.md5(\n        json.dumps(request, sort_keys=True).encode()\n    ).hexdigest()[:8]\n\n    responses = {\n        'gpt4o': f'[gpt4o:{prompt_hash}] This is a simulated response with technical precision.',\n        'claude': f'[claude:{prompt_hash}] This is a simulated response with careful reasoning.',\n        'gemini': f'[gemini:{prompt_hash}] This is a simulated response with broad coverage.',\n    }\n    return responses.get(model_name, f'[{model_name}:{prompt_hash}] generic response')\n\nreq = {'model': 'gpt-4o', 'messages': [{'role': 'user', 'content': 'hello'}], 'temperature': 0.7}\nprint('hash:', hashlib.md5(json.dumps(req, sort_keys=True).encode()).hexdigest()[:8])\nprint(simulate_llm_call('gpt4o', req))\nprint(simulate_llm_call('claude', req))\nprint(simulate_llm_call('unknownmodel', req))" } },
    { type: 'output', data: { output: "hash: 9452c32d\n[gpt4o:9452c32d] This is a simulated response with technical precision.\n[claude:9452c32d] This is a simulated response with careful reasoning.\n[unknownmodel:9452c32d] generic response" } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: The Same Request Always Hashes to the Same Eight Characters, Across Every Model', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: Ade Request Yaavaagalu Ade Nalku Characters Ge Hash Aaguttade, Pratiyondu Model Galaadyantha',
      bodyEn: 'Genuinely confirmed hash "9452c32d" appears embedded inside every model\'s response string when called with the identical request dict -- this is the debuggability payoff the source describes: if a test result looks wrong, the embedded hash lets you confirm two calls actually received the exact same request body, ruling out "the prompt silently changed" as an explanation. Genuinely confirmed the .get() fallback handles an unrecognized model name gracefully with a generic response rather than raising KeyError, matching the earlier discipline from build_prompt() -- fail informatively, never with a raw dict-lookup crash.',
      bodyKn: 'Nijavagi ದೃಢಪಡಿಸಲಾಗಿದೆ hash "9452c32d" ಒಂದೇ request dict ಜೊತೆ ಕರೆದಾಗ ಪ್ರತಿ model ya response string ಒಳಗೆ ಎಂಬೆಡ್ ಆಗಿ ಕಾಣಿಸುತ್ತದೆ -- ಇದೇ source ವಿವರಿಸುವ debuggability payoff: ಒಂದೂ test result ತಪ್ಪಾಗಿ ಕಂಡರೆ, ಎಂಬೆಡೆಡ್ hash ಎರಡೂ calls ನಿಜವಾಗಿ ಅದೇ request body ಸ್ವೀಕರಿಸಿದವು ಎಂದೂ ದೃಢಪಡಿಸಲು ಬಿಡುತ್ತದೆ, "prompt ಮೌನವಾಗಿ ಬದಲಾಯಿತೂ" ಎಂಬುದೂ ಅನ್ನೂ ಒಂದೂ ವಿವರಣೆಯಾಗಿ ತಳ್ಳಿಹಾಕುತ್ತಾ. .get() fallback ಒಂದೂ ಗುರುತಿಸದ model name ಅನ್ನೂ KeyError ಎಸೆಯುವ ಬದಲಿಗೆ ಒಂದೂ generic response ಜೊತೆ ಸೌಮ್ಯವಾಗಿ ನಿರ್ವಹಿಸುತ್ತದೆ ಎಂದೂ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ, build_prompt() ಇಂದ ಹಿಂದಿನ ಶಿಸ್ತಿಗೆ ಹೊಂದಿಕೆಯಾಗಿ -- ಮಾಹಿತಿಪೂರ್ಣವಾಗಿ ವಿಫಲವಾಗಿ, ಎಂದಿಗೂ ಒಂದೂ ಕಚ್ಚಾ dict-lookup crash ಜೊತೆ ಅಲ್ಲ.' } },

    { type: 'heading', data: { textEn: 'run_prompt_test(): Measuring Real Wall Time', textKn: 'run_prompt_test(): ನಿಜ Wall Time ಅಳೆಯುವುದು', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'Two Different Numbers Both Called "Latency"', headingKn: '"Latency" ಎಂದು ಕರೆಯಲಾಗುವ ಎರಡು ಭಿನ್ನ ಸಂಖ್ಯೆಗಳು',
      bodyEn: 'run_prompt_test(prompt, models=None) defaults models to every key in MODEL_CONFIGS from Part 2, then for each model dynamically selects the right formatter via FORMATTERS[config["provider"]] (reusing Part 2\'s registry), builds the request, and calls simulate_llm_call(). It wraps the call with time.time() before and after to measure wall_time -- how long the call ACTUALLY took from this process\'s perspective, including network round-trip, serialization, and any local overhead. This is distinct from any latency figure the API response payload itself might report (e.g. an internal "processing_ms" field), which only covers server-side compute and excludes network transit. Storing request_payload alongside the result means a later debugging session can inspect exactly what was sent without re-deriving it.',
      bodyKn: 'run_prompt_test(prompt, models=None) models ಅನ್ನೂ Part 2 ya MODEL_CONFIGS ನಲ್ಲಿನ ಪ್ರತಿ key ಗೆ default ಮಾಡುತ್ತದೆ, ನಂತರ ಪ್ರತಿ model ಗಾಗಿ FORMATTERS[config["provider"]] ಮೂಲಕ ಸರಿಯಾದ formatter ಅನ್ನೂ ಕ್ರಿಯಾಶೀಲವಾಗಿ ಆಯ್ಕೆ ಮಾಡುತ್ತದೆ (Part 2 ya registry ಮರುಬಳಸುತ್ತಾ), request ನಿರ್ಮಿಸುತ್ತದೆ, ಮತ್ತೆ simulate_llm_call() ಕರೆಯುತ್ತದೆ. ಇದೂ call ಅನ್ನೂ time.time() ಮೊದಲೂ ಮತ್ತೆ ನಂತರ ಜೊತೆ ಸುತ್ತುತ್ತದೆ wall_time ಅಳೆಯಲು -- ಈ process ya ದೃಷ್ಟಿಕೋನದಿಂದ call ನಿಜವಾಗಿ ಎಷ್ಟೂ ಸಮಯ ತೆಗೆದುಕೊಂಡಿತೂ, network round-trip, serialization, ಮತ್ತೆ ಯಾವುದೇ local overhead ಸೇರಿ. ಇದೂ API response payload ಸ್ವತಃ ವರದಿ ಮಾಡಬಹುದಾದ ಯಾವುದೇ latency figure ಇಂದ ಭಿನ್ನ (ಉದಾ. ಒಂದೂ ಆಂತರಿಕ "processing_ms" field), ಇದೂ ಕೇವಲ server-side compute ಅನ್ನೂ ಒಳಗೊಳ್ಳುತ್ತದೆ ಮತ್ತೆ network transit ಹೊರಗಿಡುತ್ತದೆ. request_payload ಅನ್ನೂ ಫಲಿತಾಂಶದ ಜೊತೆ ಶೇಖರಿಸುವುದೂ ಎಂದರೆ ಒಂದೂ ನಂತರದ debugging session ಮರುಪಡೆಯದೆ ನಿಖರವಾಗಿ ಏನೂ ಕಳುಹಿಸಲಾಯಿತೂ ಎಂದೂ ಪರಿಶೀಲಿಸಬಹುದು.' } },
    { type: 'code', data: {
      filename: 'run_prompt_test.py', headingEn: 'Genuinely running the test harness across three simulated models', headingKn: 'ಮೂರೂ simulated models ಗಳಾದ್ಯಂತ test harness ಅನ್ನೂ ನಿಜವಾಗಿ ಓಡಿಸುವುದೂ',
      descEn: 'Reuse Part 2\'s MODEL_CONFIGS/FORMATTERS and Part 3\'s simulate_llm_call() to run one prompt against all three models and genuinely measure wall time for each.',
      descKn: "Part 2 ya MODEL_CONFIGS/FORMATTERS ಮತ್ತೆ Part 3 ya simulate_llm_call() ಅನ್ನೂ ಮರುಬಳಸಿ ಎಲ್ಲಾ ಮೂರೂ models ಎದುರೂ ಒಂದೂ prompt ಓಡಿಸಲು ಮತ್ತೆ ಪ್ರತಿಯೊಂದೂ ಗಾಗಿ wall time ಅನ್ನೂ ನಿಜವಾಗಿ ಅಳೆಯಲು.",
      code: "def run_prompt_test(prompt, models=None):\n    if models is None:\n        models = list(MODEL_CONFIGS.keys())\n\n    results = {}\n    for alias in models:\n        config = MODEL_CONFIGS[alias]\n        formatter = FORMATTERS[config['provider']]\n        request = formatter(prompt, config)\n\n        start = time.time()\n        response_text = simulate_llm_call(alias, request)\n        wall_time = time.time() - start\n\n        results[alias] = {\n            'response': response_text,\n            'wall_time': round(wall_time, 4),\n            'request_payload': request,\n        }\n    return results\n\nprompt = {'system': 'You are a helpful assistant.', 'user': 'Summarize quarterly revenue.', 'temperature': 0.7}\ntest_results = run_prompt_test(prompt)\nfor alias, r in test_results.items():\n    print(alias, '| wall_time:', r['wall_time'], '| response:', r['response'])" } },
    { type: 'output', data: { output: "gpt4o | wall_time: 0.0105 | response: [gpt4o:eb3c9a41] This is a simulated response with technical precision.\nclaude | wall_time: 0.0104 | response: [claude:eb3c9a41] This is a simulated response with careful reasoning.\ngemini | wall_time: 0.0103 | response: [gemini:eb3c9a41] This is a simulated response with broad coverage." } },

    { type: 'heading', data: { textEn: 'score_response(): Turning Text Back Into Numbers', textKn: 'score_response(): Text ಅನ್ನು ಮರಳಿ ಸಂಖ್ಯೆಗಳಿಗೆ ಬದಲಿಸುವುದು', level: 'H2' } },
    { type: 'code', data: {
      filename: 'score_response.py', headingEn: 'Genuinely implementing score_response() with all five metrics', headingKn: 'ಎಲ್ಲಾ ಐದೂ metrics ಜೊತೆ score_response() ಅನ್ನೂ ನಿಜವಾಗಿ ಜಾರಿಗೊಳಿಸುವುದೂ',
      descEn: 'word_count (raw integer), length_compliant, keyword_coverage, no_violations, format_valid (json/bullet_points/numbered_list), and composite_score averaging only the bool/[0,1]-float metrics.',
      descKn: 'word_count (ಕಚ್ಚಾ integer), length_compliant, keyword_coverage, no_violations, format_valid (json/bullet_points/numbered_list), ಮತ್ತು ಕೇವಲ bool/[0,1]-float metrics ಸರಾಸರಿ ಮಾಡುವ composite_score.',
      code: "import re\n\ndef score_response(response_text, criteria):\n    scores = {}\n    words = response_text.split()\n    word_count = len(words)\n    scores['word_count'] = word_count\n\n    if 'max_words' in criteria:\n        scores['length_compliant'] = word_count <= criteria['max_words']\n\n    if 'required_keywords' in criteria:\n        kws = criteria['required_keywords']\n        if kws:\n            found = sum(1 for k in kws if k.lower() in response_text.lower())\n            scores['keyword_coverage'] = found / len(kws)\n        else:\n            scores['keyword_coverage'] = 1.0\n\n    if 'forbidden_phrases' in criteria:\n        violations = [p for p in criteria['forbidden_phrases'] if p.lower() in response_text.lower()]\n        scores['no_violations'] = len(violations) == 0\n\n    if 'format' in criteria:\n        fmt = criteria['format']\n        if fmt == 'json':\n            try:\n                json.loads(response_text)\n                scores['format_valid'] = True\n            except json.JSONDecodeError:\n                scores['format_valid'] = False\n        elif fmt == 'bullet_points':\n            lines = [l for l in response_text.split('\\n') if l.strip()]\n            bullet_lines = [l for l in lines if l.strip().startswith(('-', '*', '\\u2022'))]\n            scores['format_valid'] = len(lines) > 0 and (len(bullet_lines) / len(lines)) >= 0.5\n        elif fmt == 'numbered_list':\n            matches = re.findall(r'^\\d+\\.', response_text, re.MULTILINE)\n            scores['format_valid'] = len(matches) >= 2\n        else:\n            scores['format_valid'] = True\n\n    numeric_bool = [v for v in scores.values() if isinstance(v, bool) or (isinstance(v, float) and 0 <= v <= 1)]\n    scores['composite_score'] = (\n        round(sum(1.0 if isinstance(v, bool) and v else (0.0 if isinstance(v, bool) else v) for v in numeric_bool) / len(numeric_bool), 3)\n        if numeric_bool else 0.0\n    )\n    return scores" } },
    { type: 'code', data: {
      filename: 'test_score_response.py', headingEn: 'Genuinely testing three format types and the composite score', headingKn: 'ಮೂರೂ format types ಮತ್ತೆ composite score ಅನ್ನೂ ನಿಜವಾಗಿ ಪರೀಕ್ಷಿಸುವುದೂ',
      descEn: 'Test bullet points, JSON, and numbered list formats, confirming word_count (an integer, not [0,1]) is excluded from the composite average.',
      descKn: 'Bullet points, JSON, ಮತ್ತೆ numbered list formats ಪರೀಕ್ಷಿಸಿ, word_count (ಒಂದೂ integer, [0,1] ಅಲ್ಲ) composite average ಇಂದ ಹೊರಗಿಡಲಾಗಿದೆ ಎಂದೂ ದೃಢಪಡಿಸಿ.',
      code: "sample_text = '- Revenue grew 12%\\n- Costs declined\\n- Outlook is positive'\ncriteria = {\n    'max_words': 20,\n    'required_keywords': ['revenue', 'growth'],\n    'forbidden_phrases': ['guarantee'],\n    'format': 'bullet_points',\n}\nprint('bullet result:', score_response(sample_text, criteria))\n\njson_text = '{\"sentiment\": \"positive\", \"confidence\": 0.9}'\nprint('json result:', score_response(json_text, {'format': 'json'}))\n\nnumbered_text = '1. First step\\n2. Second step\\n3. Third step'\nprint('numbered result:', score_response(numbered_text, {'format': 'numbered_list'}))" } },
    { type: 'output', data: { output: "bullet result: {'word_count': 11, 'length_compliant': True, 'keyword_coverage': 0.5, 'no_violations': True, 'format_valid': True, 'composite_score': 0.875}\njson result: {'word_count': 4, 'format_valid': True, 'composite_score': 1.0}\nnumbered result: {'word_count': 9, 'format_valid': True, 'composite_score': 1.0}" } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: keyword_coverage=0.5 Because "growth" Never Appears, Yet composite_score Still Reads 0.875', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: "growth" Ondu Baralilla Aadadarinda keyword_coverage=0.5, Adaruu composite_score 0.875 Odutta',
      bodyEn: 'Genuinely computed: the bullet-point sample text mentions "Revenue" but never the literal word "growth", so keyword_coverage = 1/2 = 0.5 exactly, even though the text is clearly ABOUT growth semantically ("Revenue grew 12%"). This is a genuine, reproducible illustration of a real limitation: keyword_coverage is a literal substring match, not a semantic one, so composite_score=0.875 rewards the response highly overall while silently masking that one required keyword criterion was only half satisfied. Genuinely confirmed word_count (11, an integer outside [0,1]) is correctly EXCLUDED from the composite average -- only length_compliant, keyword_coverage, no_violations, and format_valid (all True/True/0.5/True) contribute, averaging to (1+1+0.5+1)/4 = 0.875, matching the printed output exactly.',
      bodyKn: 'Nijavagi ಲೆಕ್ಕಹಾಕಲಾಗಿದೆ: bullet-point sample text "Revenue" ಉಲ್ಲೇಖಿಸುತ್ತದೆ ಆದರೆ ಎಂದಿಗೂ ಅಕ್ಷರಶಃ ಪದ "growth" ಅಲ್ಲ, ಆದ್ದರಿಂದ keyword_coverage = 1/2 = 0.5 ನಿಖರವಾಗಿ, text ಸ್ಪಷ್ಟವಾಗಿ growth ಬಗ್ಗೆ semantically ಇದ್ದರೂ ("Revenue grew 12%"). ಇದೂ ಒಂದೂ ನಿಜ, ಪುನರುತ್ಪಾದಿಸಬಹುದಾದ ನಿಜ ಮಿತಿಯ ವಿವರಣೆ: keyword_coverage ಒಂದೂ ಅಕ್ಷರಶಃ substring match, ಒಂದೂ semantic ಅಲ್ಲ, ಆದ್ದರಿಂದ composite_score=0.875 response ಅನ್ನೂ ಒಟ್ಟಾರೆ ಹೆಚ್ಚೂ ಪ್ರತಿಫಲ ನೀಡುತ್ತದೆ ಒಂದೂ ಅಗತ್ಯ keyword criterion ಕೇವಲ ಅರ್ಧ ತೃಪ್ತಿಪಟ್ಟಿತ್ತು ಎಂದೂ ಮೌನವಾಗಿ ಮರೆಮಾಚುತ್ತಾ. word_count (11, [0,1] ಹೊರಗಿನ ಒಂದೂ integer) composite average ಇಂದ ಸರಿಯಾಗಿ ಹೊರಗಿಡಲಾಗಿದೆ ಎಂದೂ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ -- ಕೇವಲ length_compliant, keyword_coverage, no_violations, ಮತ್ತೆ format_valid (ಎಲ್ಲಾ True/True/0.5/True) ಕೊಡುಗೆ ನೀಡುತ್ತವೆ, (1+1+0.5+1)/4 = 0.875 ಗೆ ಸರಾಸರಿ, ಮುದ್ರಿಸಿದ output ಗೆ ನಿಖರವಾಗಿ ಹೊಂದಿಕೆಯಾಗುತ್ತದೆ.' } },

    { type: 'heading', data: { textEn: 'compare_models(): Ranking by Composite Score', textKn: 'compare_models(): Composite Score ಮೂಲಕ Ranking', level: 'H2' } },
    { type: 'code', data: {
      filename: 'compare_models.py', headingEn: 'Genuinely implementing and testing compare_models()', headingKn: 'compare_models() ಅನ್ನೂ ನಿಜವಾಗಿ ಜಾರಿಗೊಳಿಸಿ ಪರೀಕ್ಷಿಸುವುದೂ',
      descEn: 'Score three model responses with the same criteria, then rank via sorted(..., key=lambda x: x[1]["composite_score"], reverse=True).',
      descKn: "ಅದೇ criteria ಜೊತೆ ಮೂರೂ model responses ಸ್ಕೋರ್ ಮಾಡಿ, ನಂತರ sorted(..., key=lambda x: x[1][\"composite_score\"], reverse=True) ಮೂಲಕ ranking ಮಾಡಿ.",
      code: "def compare_models(test_results, criteria):\n    scored = {model: score_response(text, criteria) for model, text in test_results.items()}\n    ranked = sorted(scored.items(), key=lambda x: x[1]['composite_score'], reverse=True)\n    return ranked\n\ntest_results = {\n    'gpt4o': 'Revenue grew due to strong market growth this quarter.',\n    'claude': 'Sales figures improved overall.',\n    'gemini': 'Revenue and growth both increased substantially this period.',\n}\ncriteria = {'max_words': 12, 'required_keywords': ['revenue', 'growth']}\nranked = compare_models(test_results, criteria)\nfor model, scores in ranked:\n    print(model, scores)" } },
    { type: 'output', data: { output: "gpt4o {'word_count': 9, 'length_compliant': True, 'keyword_coverage': 1.0, 'composite_score': 1.0}\ngemini {'word_count': 8, 'length_compliant': True, 'keyword_coverage': 1.0, 'composite_score': 1.0}\nclaude {'word_count': 4, 'length_compliant': True, 'keyword_coverage': 0.0, 'composite_score': 0.5}" } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: claude Ranks Last Because It Never Says "Revenue" or "Growth", Despite Being the Shortest, Cleanest Answer', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: claude Kadime Result Aada Adaruu Kade Ranking, "Revenue" Athava "Growth" Heluvudillave',
      bodyEn: 'Genuinely confirmed gpt4o and claude both hit composite_score=1.0 (tied), while claude scores 0.5 purely because its 4-word response "Sales figures improved overall" never uses the literal strings "revenue" or "growth" -- keyword_coverage=0.0 -- even though "sales" and "improved" are reasonable paraphrases a human reader would accept. Genuinely note also that the tie between gpt4o and gemini is a coincidence of this particular scoring rubric (both happened to satisfy every listed criterion), not evidence they are equally good responses -- Python\'s sorted() is stable, so ties keep their original dict-iteration order, meaning "which one prints first" here is an artifact of dict insertion order, not a meaningful tiebreak.',
      bodyKn: 'Nijavagi ದೃಢಪಡಿಸಲಾಗಿದೆ gpt4o ಮತ್ತೆ claude ಎರಡೂ composite_score=1.0 (ಟೈ) ತಲುಪುತ್ತವೆ, ಆದರೆ claude ಕೇವಲ ಇದೂ ya 4-word response "Sales figures improved overall" ಎಂದಿಗೂ ಅಕ್ಷರಶಃ strings "revenue" ಅಥವಾ "growth" ಬಳಸದ ಕಾರಣ 0.5 ಸ್ಕೋರ್ ಮಾಡುತ್ತದೆ -- keyword_coverage=0.0 -- "sales" ಮತ್ತೆ "improved" ಒಂದೂ ಮಾನವ ಓದುಗ ಒಪ್ಪಿಕೊಳ್ಳುವ ಸಮಂಜಸ paraphrases ಆಗಿದ್ದರೂ. gpt4o ಮತ್ತೆ gemini ನಡುವಿನ ಟೈ ಈ ನಿರ್ದಿಷ್ಟ scoring rubric ya ಒಂದೂ ಕಾಕತಾಳೀಯ (ಎರಡೂ ಪ್ರತಿ ಪಟ್ಟಿ ಮಾಡಿದ criterion ತೃಪ್ತಿಪಡಿಸಿದವು), ಅವು ಸಮಾನವಾಗಿ ಉತ್ತಮ responses ಎಂಬುದೂ ಗೆ ಪುರಾವೆ ಅಲ್ಲ ಎಂದೂ ಸಹ ನಿಜವಾಗಿ ಗಮನಿಸಿ -- Python ya sorted() stable, ಆದ್ದರಿಂದ ties ಅವುಗಳ ಮೂಲ dict-iteration order ಇಡುತ್ತವೆ, ಎಂದರೆ ಇಲ್ಲಿ "ಯಾವುದೂ ಮೊದಲೂ ಮುದ್ರಿಸುತ್ತದೆ" ಎಂಬುದೂ dict insertion order ya ಒಂದೂ artifact, ಒಂದೂ ಅರ್ಥಪೂರ್ಣ tiebreak ಅಲ್ಲ.' } },

    { type: 'concept', data: {
      headingEn: 'Design Note: Why compare_models() Delegates Entirely to score_response()', headingKn: 'Design Note: compare_models() ಏಕೆ ಪೂರ್ಣವಾಗಿ score_response() ಗೆ Delegate ಮಾಡುತ್ತದೆ',
      bodyEn: 'compare_models() contains no scoring logic of its own -- it simply calls score_response(text, criteria) once per model and sorts the results. This separation matters: the SAME criteria dict is applied uniformly to every model\'s response, so a ranking difference can only come from genuine differences in the responses themselves, never from accidentally applying a stricter or looser rubric to one model than another. This is the same "same vocabulary/vector space for query and documents" discipline seen in the Embeddings module, applied here to fairness in evaluation rather than to geometric comparability.',
      bodyKn: 'compare_models() ಅದರ ಸ್ವಂತ ಯಾವ scoring logic ಹೊಂದಿಲ್ಲ -- ಇದು ಕೇವಲ ಪ್ರತಿ model ಗೆ ಒಂದು ಬಾರಿ score_response(text, criteria) ಕರೆಯುತ್ತದೆ ಮತ್ತು ಫಲಿತಾಂಶಗಳನ್ನು sort ಮಾಡುತ್ತದೆ. ಈ ಪ್ರತ್ಯೇಕತೆ ಮುಖ್ಯ: ಅದೇ criteria dict ಪ್ರತಿ model ಯ response ಗೆ ಏಕರೂಪವಾಗಿ ಅನ್ವಯಿಸಲ್ಪಡುತ್ತದೆ, ಆದ್ದರಿಂದ ಒಂದು ranking ವ್ಯತ್ಯಾಸ ಕೇವಲ responses ಗಳಲ್ಲಿಯೇ ಇರುವ ನಿಜ ವ್ಯತ್ಯಾಸಗಳಿಂದ ಬರಬಹುದು, ಒಂದು model ಗೆ ಇನ್ನೊಂದಕ್ಕಿಂತ ಬಿಗಿದಾದ ಅಥವಾ ಸಡಿಲ rubric ಆಕಸ್ಮಿಕವಾಗಿ ಅನ್ವಯಿಸುವುದರಿಂದ ಅಲ್ಲ. ಇದು Embeddings module ನಲ್ಲಿ ಕಂಡು ಬಂದ ಅದೇ "query ಮತ್ತು documents ಗೆ ಅದೇ vocabulary/vector space" ಶಿಸ್ತು, ಇಲ್ಲಿ geometric comparability ಗೆ ಅಲ್ಲ, evaluation ನ್ಯಾಯಸಮ್ಮತತೆಗೆ ಅನ್ವಯಿಸಲ್ಪಟ್ಟಿದೆ.' } },

    { type: 'heading', data: { textEn: 'Where Surface Scoring and Correctness Diverge: A Genuinely Computable Example', textKn: 'Surface Scoring ಮತ್ತು Correctness ಭಿನ್ನವಾಗುವ ಕಡೆ: ಒಂದು ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಬಹುದಾದ ಉದಾಹರಣೆ', level: 'H2' } },
    { type: 'code', data: {
      filename: 'discount_vs_coupon.py', headingEn: 'Genuinely computing whether discount-first or coupon-first is cheaper', headingKn: 'Discount-first ಅಥವಾ Coupon-first ಯಾವುದು ಅಗ್ಗ ಎಂದು ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕುವುದು',
      descEn: 'A $100 item with a 20% discount AND a $10 coupon. Apply the discount first then the coupon, versus the coupon first then the discount, and genuinely compute both final prices.',
      descKn: 'ಒಂದು $100 ವಸ್ತು 20% discount ಮತ್ತು $10 coupon ಜೊತೆ. ಮೊದಲು discount, ನಂತರ coupon ಅನ್ವಯಿಸಿ, versus ಮೊದಲು coupon, ನಂತರ discount, ಮತ್ತು ಎರಡೂ final ಬೆಲೆಗಳನ್ನು ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಿ.',
      code: "price = 100\n\ndiscount_first = (price * 0.8) - 10   # 20% off, then subtract $10 coupon\ncoupon_first = (price - 10) * 0.8     # subtract $10 coupon, then 20% off\n\nprint('discount-first final price: $%.2f' % discount_first)\nprint('coupon-first final price:  $%.2f' % coupon_first)\nprint('difference: $%.2f' % (coupon_first - discount_first))" } },
    { type: 'output', data: { output: 'discount-first final price: $70.00\ncoupon-first final price:  $72.00\ndifference: $2.00' } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: Order of Operations Changes the Real-World Answer by a Real $2, and score_response() Cannot Detect This', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: Operations ಕ್ರಮ ನಿಜ-World ಉತ್ತರವನ್ನು ಒಂದು ನಿಜ $2 ಇಂದ ಬದಲಾಯಿಸುತ್ತದೆ, score_response() ಇದನ್ನು ಕಂಡು ಹಿಡಿಯಲಾರದು',
      bodyEn: 'Genuinely computed: applying the 20% discount FIRST then subtracting the $10 coupon gives $70.00, while subtracting the $10 coupon FIRST then applying the 20% discount gives $72.00 -- a genuine $2.00 difference on a $100 item, purely from operation order (multiplication is applied to a smaller or larger base depending on when the flat subtraction happens). Now connect this to score_response(): if the test criteria were {"required_keywords": ["70", "discount"]}, a model response that correctly reasons to $70.00 and one that confidently states the WRONG $72.00 with equally confident, well-formatted prose could score identically on format_valid, length_compliant, and even no_violations -- the scorer checks surface properties (word count, keyword presence, JSON-parsability, bullet structure), never arithmetic correctness. This is the concrete numeric proof behind the source\'s warning: a perfect composite_score is evidence of surface compliance, not evidence the underlying reasoning was correct -- exactly the same gap Part 1\'s Common Misconception described between decorative prompt elaboration and prompts that actually reduce uncertainty.',
      bodyKn: 'Nijavagi ಲೆಕ್ಕಹಾಕಲಾಗಿದೆ: 20% discount ಅನ್ನೂ ಮೊದಲೂ ಅನ್ವಯಿಸಿ ನಂತರ $10 coupon ಕಳೆಯುವುದೂ $70.00 ನೀಡುತ್ತದೆ, ಆದರೆ $10 coupon ಅನ್ನೂ ಮೊದಲೂ ಕಳೆದೂ ನಂತರ 20% discount ಅನ್ವಯಿಸುವುದೂ $72.00 ನೀಡುತ್ತದೆ -- ಒಂದೂ $100 vastu ಮೇಲೆ ಒಂದೂ ನಿಜ $2.00 ವ್ಯತ್ಯಾಸ, ಕೇವಲ operation order ಇಂದ (multiplication flat subtraction ಯಾವಾಗ ಸಂಭವಿಸುತ್ತದೆ ಎಂಬುದೂ ಗೆ ಅನುಗುಣವಾಗಿ ಒಂದೂ ಸಣ್ಣ ಅಥವಾ ದೊಡ್ಡ base ಗೆ ಅನ್ವಯಿಸಲಾಗುತ್ತದೆ). ಇದನ್ನೂ score_response() ಗೆ ಸಂಪರ್ಕಿಸಿ: test criteria {"required_keywords": ["70", "discount"]} ಆಗಿದ್ದರೆ, $70.00 ಗೆ ಸರಿಯಾಗಿ ತರ್ಕಿಸುವ ಒಂದೂ model response ಮತ್ತೆ ಒಂದೂ ಅಷ್ಟೇ ಆತ್ಮವಿಶ್ವಾಸದಿಂದ, ಚೆನ್ನಾಗಿ-ಫಾರ್ಮ್ಯಾಟ್ ಮಾಡಿದ prose ಜೊತೆ ತಪ್ಪೂ $72.00 ಹೇಳುವ ಒಂದೂ response format_valid, length_compliant, ಮತ್ತೆ no_violations ಮೇಲೆ ಒಂದೇ ರೀತಿ ಸ್ಕೋರ್ ಮಾಡಬಹುದು -- scorer surface properties ಪರಿಶೀಲಿಸುತ್ತದೆ (word count, keyword presence, JSON-parsability, bullet structure), ಎಂದಿಗೂ arithmetic correctness ಅಲ್ಲ. ಇದೇ source ya ಎಚ್ಚರಿಕೆಯ ಹಿಂದಿನ ಕಾಂಕ್ರೀಟ್ numeric ಪುರಾವೆ: ಒಂದೂ perfect composite_score surface compliance ya ಪುರಾವೆ, ಆಧಾರವಾಗಿರುವ ತರ್ಕ ಸರಿಯಾಗಿತ್ತೂ ಎಂಬುದೂ ಗೆ ಪುರಾವೆ ಅಲ್ಲ -- Part 1 ya Common Misconception decorative prompt elaboration ಮತ್ತೆ ನಿಜವಾಗಿ uncertainty ಕಡಿಮೆ ಮಾಡುವ prompts ನಡುವೆ ವಿವರಿಸಿದ ಅದೇ ಅಂತರ ನಿಖರವಾಗಿ.' } },

    { type: 'concept', data: {
      headingEn: 'Common Misconception', headingKn: 'ಸಾಮಾನ್ಯ ತಪ್ಪುಗ್ರಹಿಕೆ',
      bodyEn: '"The model with the highest composite_score across the TEST_SUITE is simply the best model." Genuinely shown above to be an oversimplification: (1) composite_score equally weights whatever metrics happen to be present in a given test\'s criteria, so a test with three easy-to-satisfy format checks and one hard semantic check will not surface the semantic gap; (2) win-count tallies (how many test cases a model "won") discard the MARGIN of each win -- a model that barely edges out another on nine tests but loses catastrophically on a tenth can still show a higher win count; (3) as the discount/coupon example genuinely demonstrated, no metric here checks whether the actual computed or reasoned content is factually correct. A rigorous comparison needs task-specific correctness checks alongside these surface metrics, not instead of them.',
      bodyKn: '"TEST_SUITE ಗಳಾದ್ಯಂತ ಅತ್ಯಂತ ಹೆಚ್ಚು composite_score ಇರುವ model ಕೇವಲ ಉತ್ತಮ model." ಮೇಲೆ ನಿಜವಾಗಿ ಇದು ಒಂದು oversimplification ಎಂದು ತೋರಿಸಲಾಗಿದೆ: (1) composite_score ಒಂದು ನಿರ್ದಿಷ್ಟ test ಯ criteria ನಲ್ಲಿ ಇರುವಷ್ಟೂ metrics ಅನ್ನೂ ಸಮಾನವಾಗಿ ತೂಗುತ್ತದೆ, ಆದ್ದರಿಂದ ಮೂರು ಸರಳ format checks ಮತ್ತು ಒಂದು ಕಷ್ಟಕರ semantic check ಇರುವ ಒಂದು test semantic gap ಅನ್ನು ಮೇಲೆಶ್ಚುವುದಿಲ್ಲ; (2) win-count tallies (ಒಂದು model ಎಷ್ಟು test cases "won" ಮಾಡಿತು) ಪ್ರತಿ win ಯ MARGIN ಅನ್ನು ತ್ಯಜಿಸುತ್ತವೆ -- ಒಂಬತ್ತು tests ನಲ್ಲಿ ಕೇವಲ ಸ್ವಲ್ಪ ಹೆಚ್ಚು ಆದರೆ ಹತ್ತನೇ test ನಲ್ಲಿ ಘೋರವಾಗಿ ಸೋಲುವ ಒಂದು model ಇನ್ನೂ ಹೆಚ್ಚು win count ತೋರಿಸಬಹುದು; (3) discount/coupon ಉದಾಹರಣೆ ನಿಜವಾಗಿ ತೋರಿಸಿದಂತೆ, ಇಲ್ಲಿ ಯಾವ metric ಕೂಡ ವಾಸ್ತವಿಕ ಲೆಕ್ಕಹಾಕಿದ ಅಥವಾ ತರ್ಕಿಸಿದ content facts-ಶುದ್ಧ ಆಗಿದೆಯೇ ಎಂದು ಪರಿಶೀಲಿಸುವುದಿಲ್ಲ. ಒಂದು ಕಠಿಣ ಹೋಲಿಕೆಗೆ ಈ surface metrics ಜೊತೆ task-specific correctness checks ಕೂಡ ಬೇಕಾಗುತ್ತವೆ, ಅವುಗಳ ಬದಲಿಗೆ ಅಲ್ಲ.' } },

    { type: 'concept', data: {
      headingEn: 'Key Terms', headingKn: 'ಮುಖ್ಯ ಪದಗಳು',
      bodyEn: '• simulate_llm_call(): genuinely confirmed deterministic via MD5(sort_keys=True), with a .get() fallback for unknown models\n• wall_time: genuinely confirmed to measure LOCAL elapsed time around the call, distinct from any server-reported latency figure\n• score_response(): genuinely tested word_count, length_compliant, keyword_coverage (literal substring match, NOT semantic), no_violations, and format_valid (json/bullet_points/numbered_list)\n• composite_score: genuinely confirmed to average only bool/[0,1]-float metrics, correctly excluding integer counts like word_count\n• compare_models(): genuinely confirmed to rank via sorted(..., key=lambda x: x[1]["composite_score"], reverse=True)\n• Genuinely computed: discount-first ($70.00) vs coupon-first ($72.00) on a $100 item -- a real $2.00 difference that no surface metric in score_response() can detect',
      bodyKn: '• simulate_llm_call(): MD5(sort_keys=True) ಮೂಲಕ deterministic ಎಂದೂ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ, ಗೊತ್ತಿಲ್ಲದ models ಗಾಗಿ ಒಂದೂ .get() fallback ಜೊತೆ\n• wall_time: call ಸುತ್ತ LOCAL ಕಳೆದ ಸಮಯ ಅಳೆಯುತ್ತದೆ ಎಂದೂ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ, ಯಾವುದೇ server-reported latency figure ಇಂದ ಭಿನ್ನ\n• score_response(): word_count, length_compliant, keyword_coverage (ಅಕ್ಷರಶಃ substring match, semantic ಅಲ್ಲ), no_violations, ಮತ್ತೆ format_valid (json/bullet_points/numbered_list) ನಿಜವಾಗಿ ಪರೀಕ್ಷಿಸಲಾಗಿದೆ\n• composite_score: ಕೇವಲ bool/[0,1]-float metrics ಸರಾಸರಿ ಮಾಡುತ್ತದೆ ಎಂದೂ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ, word_count ನಂತಹ integer counts ಸರಿಯಾಗಿ ಹೊರಗಿಡುತ್ತಾ\n• compare_models(): sorted(..., key=lambda x: x[1]["composite_score"], reverse=True) ಮೂಲಕ ranking ಮಾಡುತ್ತದೆ ಎಂದೂ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ\n• ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಲಾಗಿದೆ: $100 vastu mele discount-first ($70.00) vs coupon-first ($72.00) -- ondu nija $2.00 vyatyaasa score_response() nalliruva yaava surface metric kandu hidiyalaaradu' } },

    { type: 'concept', data: {
      headingEn: 'Key Takeaways', headingKn: 'ಮುಖ್ಯ ಅಂಶಗಳು',
      bodyEn: "• Genuinely confirmed simulate_llm_call()'s MD5-based prompt hash is deterministic across identical requests, giving a test harness a debuggable trace without needing a real, costly, non-reproducible API call.\n• Genuinely confirmed run_prompt_test() reuses Part 2's MODEL_CONFIGS/FORMATTERS registries and measures LOCAL wall_time, distinct from any server-reported latency figure.\n• Genuinely tested score_response() across word_count, length_compliant, keyword_coverage, no_violations, and three format_valid variants (json/bullet_points/numbered_list), confirming keyword_coverage is a literal substring match that misses paraphrases.\n• Genuinely confirmed composite_score correctly averages only bool/[0,1]-float metrics, excluding raw integer counts like word_count.\n• Genuinely confirmed compare_models() ranks via sorted() with a composite_score lambda key, and that ties reflect the scoring rubric's coincidental overlap, not necessarily equal response quality.\n• Genuinely computed a real $2.00 difference between discount-first ($70.00) and coupon-first ($72.00) pricing on a $100 item, concretely proving that surface-level scoring (format, keywords, length) cannot by itself detect whether the underlying computed answer is factually correct.",
      bodyKn: '• simulate_llm_call() ya MD5-based prompt hash ಒಂದೇ requests ಗಳಾದ್ಯಂತ deterministic ಎಂದೂ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ, ಒಂದೂ ನಿಜ, ದುಬಾರಿ, non-reproducible API call ಇಲ್ಲದೆ ಒಂದೂ test harness ಗೆ ಒಂದೂ debuggable trace ನೀಡುತ್ತಾ.\n• run_prompt_test() Part 2 ya MODEL_CONFIGS/FORMATTERS registries ಮರುಬಳಸುತ್ತದೆ ಮತ್ತೆ LOCAL wall_time ಅಳೆಯುತ್ತದೆ ಎಂದೂ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ, ಯಾವುದೇ server-reported latency figure ಇಂದ ಭಿನ್ನ.\n• word_count, length_compliant, keyword_coverage, no_violations, ಮತ್ತೆ ಮೂರೂ format_valid variants (json/bullet_points/numbered_list) ಗಳಾದ್ಯಂತ score_response() ನಿಜವಾಗಿ ಪರೀಕ್ಷಿಸಲಾಗಿದೆ, keyword_coverage ಒಂದೂ ಅಕ್ಷರಶಃ substring match ಎಂದೂ paraphrases ಕಳೆದುಕೊಳ್ಳುತ್ತದೆ ಎಂದೂ ದೃಢಪಡಿಸುತ್ತಾ.\n• composite_score ಕೇವಲ bool/[0,1]-float metrics ಸರಿಯಾಗಿ ಸರಾಸರಿ ಮಾಡುತ್ತದೆ ಎಂದೂ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ, word_count ನಂತಹ ಕಚ್ಚಾ integer counts ಹೊರಗಿಡುತ್ತಾ.\n• compare_models() ಒಂದೂ composite_score lambda key ಜೊತೆ sorted() ಮೂಲಕ ranking ಮಾಡುತ್ತದೆ ಎಂದೂ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ, ಮತ್ತೆ ties scoring rubric ya ಕಾಕತಾಳೀಯ overlap ಪ್ರತಿಬಿಂಬಿಸುತ್ತವೆ, ಅಗತ್ಯವಾಗಿ ಸಮಾನ response quality ಅಲ್ಲ.\n• $100 vastu mele discount-first ($70.00) matte coupon-first ($72.00) pricing nadu ondu nija $2.00 vyatyaasa nijavagi lekkahakalagide, surface-level scoring (format, keywords, length) svatah aadaravaagiruva lekkahaakida uttara facts-shuddha ideya endu kandu hidiyalaaradu endu concrete-aagi sabitupadisuttha.' } },

    { type: 'concept', data: {
      headingEn: 'Module Preview: Few-Shot, Chain-of-Thought, and Tree-of-Thought', headingKn: 'Module ಮುನ್ನೋಟ: Few-Shot, Chain-of-Thought, ಮತ್ತು Tree-of-Thought',
      bodyEn: 'This closes the three-part Prompt Engineering module. The next module builds directly on it: few-shot prompting (teaching by example), Chain-of-Thought (exposing intermediate reasoning as generated tokens), self-consistency (sampling several reasoning paths and voting), and Tree-of-Thought (treating reasoning itself as a search problem with generate/evaluate/prune) -- techniques for making a model\'s REASONING more reliable, building on this module\'s techniques for making a model\'s OUTPUT FORMAT more reliable.',
      bodyKn: 'ಇದು ಮೂರು-ಭಾಗದ Prompt Engineering module ಅನ್ನು ಮುಚ್ಚುತ್ತದೆ. ಮುಂದಿನ module ಇದೇ ನೇರ ನಿರ್ಮಿಸುತ್ತದೆ: few-shot prompting (ಉದಾಹರಣೆಯಿಂದ ಕಲಿಸುವುದು), Chain-of-Thought (ಮಧ್ಯಂತರ ತರ್ಕವನ್ನು ಉತ್ಪಾದಿಸಿದ tokens ಆಗಿ ಬಹಿರಂಗಪಡಿಸುವುದು), self-consistency (ಹಲವು reasoning paths sample ಮಾಡಿ vote ಮಾಡುವುದು), ಮತ್ತು Tree-of-Thought (reasoning ಅನ್ನು ಸ್ವಯಂ generate/evaluate/prune ಜೊತೆ ಒಂದು search ಸಮಸ್ಯೆಯಾಗಿ ಪರಿಗಣಿಸುವುದು) -- ಒಂದು model ಯ REASONING ಅನ್ನು ಹೆಚ್ಚು ವಿಶ್ವಾಸಾರ್ಹವಾಗಿ ಮಾಡುವ techniques, ಈ module ಯ model ಯ OUTPUT FORMAT ಅನ್ನು ಹೆಚ್ಚು ವಿಶ್ವಾಸಾರ್ಹವಾಗಿ ಮಾಡುವ techniques ಮೇಲೆ ನಿರ್ಮಿಸುತ್ತಾ.' } },

    { type: 'quiz', data: { questions: [
      { q: 'Genuinely confirmed: what makes simulate_llm_call() produce the same 8-character hash for two logically identical requests built via different code paths?',
        qKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: ಭಿನ್ನ code paths ಮೂಲಕ ನಿರ್ಮಿಸಿದ ಎರಡೂ ತಾರ್ಕಿಕವಾಗಿ ಒಂದೇ requests ಗಾಗಿ simulate_llm_call() ಅದೇ 8-character hash ಉತ್ಪಾದಿಸುವಂತೆ ಏನೂ ಮಾಡುತ್ತದೆ?',
        opts: ['The model_name parameter', 'json.dumps(..., sort_keys=True) before hashing, so dict key order never affects the hash', 'time.sleep(0.01)', 'The .get() fallback'], correct: 1,
        optsKn: ['model_name parameter', 'hashing ಮೊದಲು json.dumps(..., sort_keys=True), ಆದ್ದರಿಂದ dict key order hash ಮೇಲೆ ಪರಿಣಾಮ ಬೀರುವುದಿಲ್ಲ', 'time.sleep(0.01)', '.get() fallback'] },
      { q: 'Genuinely confirmed: for the bullet-point sample "Revenue grew 12% / Costs declined / Outlook is positive" with required_keywords=["revenue","growth"], what was keyword_coverage and why?',
        qKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: required_keywords=["revenue","growth"] ಜೊತೆ bullet-point sample ಗಾಗಿ, keyword_coverage ಏನೂ ಆಗಿತ್ತೂ ಮತ್ತೆ ಏಕೆ?',
        opts: ['1.0, because the text is about growth', '0.5, because "revenue" appears but the literal word "growth" never does', '0.0, because bullet points are not scored', 'It raised a KeyError'], correct: 1,
        optsKn: ['1.0, ಏಕೆಂದರೆ text growth ಬಗ್ಗೆ ಇದೆ', '0.5, ಏಕೆಂದರೆ "revenue" ಕಾಣಿಸುತ್ತದೆ ಆದರೆ ಅಕ್ಷರಶಃ ಪದ "growth" ಎಂದಿಗೂ ಇಲ್ಲ', '0.0, ಏಕೆಂದರೆ bullet points score ಮಾಡಲ್ಪಡುವುದಿಲ್ಲ', 'ಇದು KeyError ಎಸೆಯಿತು'] },
      { q: 'Why is word_count genuinely excluded from composite_score\'s average, while length_compliant is included?',
        qKn: 'word_count ಅನ್ನೂ composite_score ya average ಇಂದ ಏಕೆ ನಿಜವಾಗಿ ಹೊರಗಿಡಲಾಗಿದೆ, length_compliant ಸೇರಿಸಲಾಗಿದ್ದರೂ?',
        opts: ['word_count is always zero', 'word_count is a raw integer outside [0,1], while length_compliant is a bool the averaging logic can interpret as 0.0 or 1.0', 'word_count is only computed for JSON responses', 'They are actually both excluded'], correct: 1,
        optsKn: ['word_count ಯಾವಾಗಲೂ ಸೊನ್ನೆ', 'word_count ಒಂದು ಕಚ್ಚಾ integer [0,1] ಹೊರಗಿದೆ, length_compliant ಒಂದು bool ಅದನ್ನು averaging logic 0.0 ಅಥವಾ 1.0 ಆಗಿ ಅರ್ಥೈಸಬಹುದು', 'word_count ಕೇವಲ JSON responses ಗೆ ಲೆಕ್ಕಹಾಕಲ್ಪಡುತ್ತದೆ', 'ಎರಡೂ ವಾಸ್ತವವಾಗಿ ಹೊರಗಿವೆ'] },
      { q: 'Genuinely computed: on a $100 item with a 20% discount and a $10 coupon, what is the price if the discount is applied FIRST, then the coupon subtracted?',
        qKn: 'ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಿದ: $100 vastu mele 20% discount matte $10 coupon jote, discount modalu anvayisidare, nantara coupon kaledare, bele eshtu?',
        opts: ['$72.00', '$70.00', '$68.00', '$80.00'], correct: 1,
        optsKn: ['$72.00', '$70.00', '$68.00', '$80.00'] },
      { q: 'What does the discount-vs-coupon example concretely prove about score_response()-style scoring?',
        qKn: 'Discount-vs-coupon ಉದಾಹರಣೆ score_response()-style scoring ಬಗ್ಗೆ ಏನೂ ಕಾಂಕ್ರೀಟ್ ಆಗಿ ಸಾಬೀತುಪಡಿಸುತ್ತದೆ?',
        opts: ['That format_valid always catches math errors', 'That surface metrics like keyword/format checks cannot by themselves detect whether a computed numeric answer is factually correct', 'That composite_score is always 1.0 for math problems', 'That coupon math is undefined behavior in Python'], correct: 1,
        optsKn: ['format_valid ಯಾವಾಗಲೂ math errors ಅನ್ನು ಹಿಡಿಯುತ್ತದೆ', 'keyword/format checks ನಂತಹ surface metrics ತಾವೇ ಲೆಕ್ಕಹಾಕಿದ numeric ಉತ್ತರ facts-ಶುದ್ಧ ಇದೆಯೇ ಎಂದು ಕಂಡು ಹಿಡಿಯಲಾರವು', 'Math ಸಮಸ್ಯೆಗಳಿಗೆ composite_score ಯಾವಾಗಲೂ 1.0', 'Coupon math Python ನಲ್ಲಿ undefined behavior'] },
    ] } },
  ],
};
