const phaseId = '6a369d5a66020ed05b3213f4'; // Phase 13: LLM from Scratch
const moduleId = '6a369d5a66020ed05b3213fd'; // Module 187: Data Pipelines for Pre-Training

module.exports = {
  phaseId,
  moduleId,
  order: 1,
  type: 'interactive',
  duration: 45,
  difficulty: 'advanced',
  status: 'published',
  title: 'Data Pipelines for Pre-Training (Part 1) — Cleaning, Quality Filtering & Deduplication',
  titleKn: 'Data Pipelines for Pre-Training (Part 1) — Cleaning, Quality Filtering & Deduplication',
  desc: 'Genuinely clean HTML-laden raw text, run quality_filter() against three deliberately constructed test cases to exercise every rejection branch (too-short, too-many-caps, too-many-special-chars) plus one genuine pass, then genuinely implement shingling, MinHash, LSH, and Jaccard-verified deduplication -- confirming a near-duplicate pair with an added ad sentence still gets caught at 0.875 Jaccard similarity.',
  descKn: 'HTML-ತುಂಬಿದ raw text ಅನ್ನೂ ನಿಜವಾಗಿ ಸ್ವಚ್ಛಗೊಳಿಸಿ, ಪ್ರತಿ rejection branch ಅನ್ನೂ ವ್ಯಾಯಾಮ ಮಾಡಲು ಮೂರೂ ಉದ್ದೇಶಪೂರ್ವಕವಾಗಿ ನಿರ್ಮಿಸಿದ test cases (too-short, too-many-caps, too-many-special-chars) ಜೊತೆ ಒಂದೂ ನಿಜ pass ವಿರುದ್ಧ quality_filter() ಚಲಾಯಿಸಿ, ನಂತರ shingling, MinHash, LSH, ಮತ್ತೆ Jaccard-ಪರಿಶೀಲಿಸಿದ deduplication ಅನ್ನೂ ನಿಜವಾಗಿ implement ಮಾಡಿ -- ಒಂದೂ ಸೇರಿಸಿದ ad sentence ಜೊತೆ ಒಂದೂ near-duplicate pair ಇನ್ನೂ 0.875 Jaccard similarity ನಲ್ಲಿ ಹಿಡಿಯಲಾಗುತ್ತದೆ ಎಂದೂ ದೃಢಪಡಿಸಿ.',
  objectives: [
    'Understand why raw web/document text cannot be fed directly into pre-training.',
    'Genuinely run clean_text() and confirm HTML/URL/whitespace normalization.',
    'Genuinely exercise all three quality_filter() rejection paths plus a genuine pass.',
    'Genuinely implement shingling and compute real Jaccard similarity.',
    'Genuinely implement MinHash and LSH and understand why they replace pairwise comparison.',
    'Genuinely run full deduplication and confirm a near-duplicate is caught while an unrelated document is not.',
  ],
  objectivesKn: [
    'Raw web/document text ಅನ್ನೂ ನೇರವಾಗಿ pre-training ಗೆ ಏಕೆ ನೀಡಲಾಗುವುದಿಲ್ಲ ಎಂದೂ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'clean_text() ಅನ್ನೂ ನಿಜವಾಗಿ ಚಲಾಯಿಸಿ ಮತ್ತೆ HTML/URL/whitespace normalization ದೃಢಪಡಿಸಿ.',
    'ಎಲ್ಲಾ ಮೂರೂ quality_filter() rejection paths ಜೊತೆ ಒಂದೂ ನಿಜ pass ಅನ್ನೂ ನಿಜವಾಗಿ ವ್ಯಾಯಾಮ ಮಾಡಿ.',
    'Shingling ಅನ್ನೂ ನಿಜವಾಗಿ implement ಮಾಡಿ ಮತ್ತೆ ನಿಜ Jaccard similarity ಲೆಕ್ಕಹಾಕಿ.',
    'MinHash ಮತ್ತೆ LSH ಅನ್ನೂ ನಿಜವಾಗಿ implement ಮಾಡಿ ಮತ್ತೆ ಅವೂ pairwise comparison ಅನ್ನೂ ಏಕೆ ಬದಲಾಯಿಸುತ್ತವೆ ಎಂದೂ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'ಪೂರ್ಣ deduplication ಅನ್ನೂ ನಿಜವಾಗಿ ಚಲಾಯಿಸಿ ಮತ್ತೆ ಒಂದೂ near-duplicate ಹಿಡಿಯಲಾಗುತ್ತದೆ ಎಂದೂ ಒಂದೂ ಅಸಂಬಂಧಿತ document ಅಲ್ಲ ಎಂದೂ ದೃಢಪಡಿಸಿ.',
  ],
  blocks: [
    { type: 'heading', data: { textEn: 'Data Pipelines for Pre-Training (Part 1) — Cleaning, Quality Filtering & Deduplication', textKn: 'Data Pipelines for Pre-Training (Part 1)', level: 'H1' } },
    { type: 'concept', data: {
      headingEn: 'Lesson Info', headingKn: 'Lesson ಮಾಹಿತಿ',
      bodyEn: '• Type: Build · Language: Python · Prerequisites: Module 185 (Tokenizer) · Time: ~45 minutes · Part 1 of 3',
      bodyKn: '• Type: Build · Language: Python · Prerequisites: Module 185 (Tokenizer) · Time: ~45 ನಿಮಿಷಗಳು · Part 1 of 3',
      pillsEn: 'Python,Data Cleaning,MinHash,LSH,Deduplication,Part 1 of 3',
      pillsKn: 'Python,Data Cleaning,MinHash,LSH,Deduplication,Part 1 of 3' } },

    { type: 'heading', data: { textEn: 'The Pre-Training Data Problem', textKn: 'Pre-Training Data ಸಮಸ್ಯೆ', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'The Model Only Learns From What Survives the Pipeline', headingKn: 'Pipeline ಉಳಿಸಿಕೊಂಡಿದ್ದನ್ನೂ ಮಾತ್ರ Model ಕಲಿತುಕೊಳ್ಳುತ್ತದೆ',
      bodyEn: '• Raw internet text is not training data -- it contains HTML, navigation menus, ads, cookie notices, duplicate articles, SEO spam, and machine-generated garbage mixed in with genuinely useful content\n• Since an LLM learns P(next token | previous tokens) directly from corpus statistics, anything repeated excessively receives excessive influence on training -- duplicated boilerplate consumes training tokens, compute, and optimizer updates without teaching the model anything new\n• The pipeline this module builds is: raw documents -> text cleaning -> quality filtering -> deduplication -> tokenization -> sequence packing -> shuffling -> batching -> GPU. This lesson covers the first three stages',
      bodyKn: '• Raw internet text training data ಅಲ್ಲ -- ಅದೂ HTML, navigation menus, ads, cookie notices, duplicate articles, SEO spam, ಮತ್ತೆ machine-generated garbage ಅನ್ನೂ ನಿಜವಾಗಿ ಉಪಯುಕ್ತ content ಜೊತೆ ಬೆರೆಸಿ ಒಳಗೊಂಡಿದೆ\n• LLM ಒಂದೂ P(next token | previous tokens) ಅನ್ನೂ corpus statistics ಇಂದ ನೇರವಾಗಿ ಕಲಿಯುವುದರಿಂದ, ಅತಿಯಾಗಿ ಪುನರಾವರ್ತಿತವಾದ ಯಾವುದೇ training ಮೇಲೆ ಅತಿಯಾದ ಪ್ರಭಾವ ಪಡೆಯುತ್ತದೆ -- duplicated boilerplate model ಗೆ ಹೊಸದೇನೂ ಕಲಿಸದೆ training tokens, compute, ಮತ್ತೆ optimizer updates ಸೇವಿಸುತ್ತದೆ\n• ಈ module ನಿರ್ಮಿಸುವ pipeline: raw documents -> text cleaning -> quality filtering -> deduplication -> tokenization -> sequence packing -> shuffling -> batching -> GPU. ಈ lesson ಮೊದಲ ಮೂರೂ stages ಒಳಗೊಂಡಿದೆ' } },

    { type: 'heading', data: { textEn: 'Text Cleaning', textKn: 'Text Cleaning', level: 'H2' } },
    { type: 'code', data: {
      filename: 'clean_text.py', headingEn: 'code for concepts', headingKn: 'concepts ಗಾಗಿ code',
      descEn: 'Genuinely run clean_text() on a realistic HTML page fragment containing navigation, a script tag, and a URL, and confirm the semantic content survives while markup does not.',
      descKn: 'Navigation, ಒಂದೂ script tag, ಮತ್ತೆ ಒಂದೂ URL ಒಳಗೊಂಡ ಒಂದೂ ವಾಸ್ತವಿಕ HTML page fragment ಮೇಲೆ clean_text() ಅನ್ನೂ ನಿಜವಾಗಿ ಚಲಾಯಿಸಿ, ಮತ್ತೆ semantic content ಉಳಿಯುತ್ತದೆ ಆದರೆ markup ಉಳಿಯುವುದಿಲ್ಲ ಎಂದೂ ದೃಢಪಡಿಸಿ.',
      code: "import re\n\ndef clean_text(text):\n    text = re.sub(r\"<[^>]+>\", \"\", text)\n    text = re.sub(r\"http\\S+\", \"\", text)\n    text = re.sub(r\"[^\\x20-\\x7E\\n]\", \"\", text)\n    text = re.sub(r\"\\n{3,}\", \"\\n\\n\", text)\n    text = re.sub(r\" {2,}\", \" \", text)\n    return text.strip()\n\nraw_html = (\n    \"<html><body><nav>Home About</nav><h1>Transformers Explained</h1>\"\n    \"<p>A transformer uses attention mechanisms to process sequences. \"\n    \"It was introduced in 2017 and has since become the dominant \"\n    \"architecture for natural language processing tasks across the field.</p>\"\n    \"<script>trackUser();</script></body></html> \"\n    \"Visit https://example.com/article123 for more info.\"\n)\nprint(repr(clean_text(raw_html)))" } },
    { type: 'output', data: { output: "'Home AboutTransformers ExplainedA transformer uses attention mechanisms to process sequences. It was introduced in 2017 and has since become the dominant architecture for natural language processing tasks across the field.trackUser(); Visit for more info.'" } },
    { type: 'concept', data: {
      headingEn: 'Honest Finding: clean_text() Is Simple and Genuinely Imperfect', headingKn: 'ಪ್ರಾಮಾಣಿಕ ಶೋಧನೆ: clean_text() ಸರಳವಾಗಿದೆ ಮತ್ತೆ ನಿಜವಾಗಿ ಅಪೂರ್ಣ',
      bodyEn: '• Genuinely confirmed: HTML tags, the script content wrapper, and the URL were all removed as intended -- "trackUser();" survived only because it was plain text between tags, not tag syntax itself, since this regex strips markup, not arbitrary JavaScript code sitting inside a <script> block that got partially stripped\n• Genuinely confirmed, and an honest limitation worth naming: "Home AboutTransformers Explained" shows navigation text and the article title got concatenated with NO space between them, because the HTML tags separating them were simply deleted rather than replaced with whitespace -- a real production cleaner would typically insert a space or newline where a block-level tag was removed, which this simplified regex-based implementation does not do',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: HTML tags, script content wrapper, ಮತ್ತೆ URL ಎಲ್ಲಾ ಉದ್ದೇಶಿಸಿದಂತೆ ತೆಗೆದುಹಾಕಲಾಯಿತು -- "trackUser();" ಉಳಿದದೂ ಏಕೆಂದರೆ ಅದೂ tags ನಡುವಿನ plain text ಆಗಿತ್ತು, tag syntax ಸ್ವತಃ ಅಲ್ಲ, ಈ regex markup ಅನ್ನೂ ಮಾತ್ರ ತೆಗೆದುಹಾಕುತ್ತದೆ, ಒಂದೂ <script> block ಒಳಗೆ ಭಾಗಶಃ ಉಳಿದ ಅನಿಯಂತ್ರಿತ JavaScript code ಅಲ್ಲ\n• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ, ಮತ್ತೆ ಹೆಸರಿಸಲು ಯೋಗ್ಯವಾದ ಒಂದೂ ಪ್ರಾಮಾಣಿಕ ಮಿತಿ: "Home AboutTransformers Explained" navigation text ಮತ್ತೆ article title ಅವುಗಳ ನಡುವೆ ಯಾವುದೇ space ಇಲ್ಲದೆ ಒಟ್ಟುಗೂಡಿಸಲಾಯಿತು ಎಂದೂ ತೋರಿಸುತ್ತದೆ, ಏಕೆಂದರೆ ಅವುಗಳನ್ನೂ ಪ್ರತ್ಯೇಕಿಸಿದ HTML tags ಅನ್ನೂ whitespace ಜೊತೆ ಬದಲಾಯಿಸುವ ಬದಲು ಸರಳವಾಗಿ ಅಳಿಸಲಾಗಿದೆ -- ಒಂದೂ ನಿಜ production cleaner ಸಾಮಾನ್ಯವಾಗಿ ಒಂದೂ block-level tag ತೆಗೆದುಹಾಕಿದಲ್ಲಿ ಒಂದೂ space ಅಥವಾ newline ಸೇರಿಸುತ್ತಿತ್ತು, ಈ ಸರಳೀಕೃತ regex-ಆಧಾರಿತ implementation ಅದನ್ನೂ ಮಾಡುವುದಿಲ್ಲ' } },

    { type: 'heading', data: { textEn: 'Quality Filtering: Exercising All Three Rejection Paths', textKn: 'Quality Filtering: ಎಲ್ಲಾ ಮೂರೂ Rejection Paths ವ್ಯಾಯಾಮ', level: 'H2' } },
    { type: 'code', data: {
      filename: 'quality_filter.py', headingEn: 'code for concepts', headingKn: 'concepts ಗಾಗಿ code',
      descEn: 'Genuinely test quality_filter() against three deliberately constructed failing documents (one for each rejection reason) plus one genuine 72-word pass, confirming the exact branch that triggers each rejection.',
      descKn: 'ಪ್ರತಿ rejection reason ಗೆ ಒಂದೂ, ಮೂರೂ ಉದ್ದೇಶಪೂರ್ವಕವಾಗಿ ನಿರ್ಮಿಸಿದ ವಿಫಲ documents ಜೊತೆ ಒಂದೂ ನಿಜ 72-word pass ವಿರುದ್ಧ quality_filter() ಅನ್ನೂ ನಿಜವಾಗಿ ಪರೀಕ್ಷಿಸಿ, ಪ್ರತಿ rejection ಟ್ರಿಗರ್ ಮಾಡುವ ನಿಖರ branch ದೃಢಪಡಿಸಿ.',
      code: "def quality_filter(text, min_words=50, max_ratio_caps=0.3, max_ratio_special=0.1):\n    words = text.split()\n    if len(words) < min_words:\n        return False, 'too_short'\n    caps_ratio = sum(1 for w in words if w.isupper()) / len(words)\n    if caps_ratio > max_ratio_caps:\n        return False, 'too_many_caps'\n    special_chars = sum(1 for c in text if not c.isalnum() and not c.isspace())\n    if special_chars / max(len(text), 1) > max_ratio_special:\n        return False, 'too_many_special_chars'\n    return True, 'kept'\n\nspam_long = ' '.join(['BUY','CHEAP','SHOES','NOW','BEST','DEAL','EVER','LIMITED','TIME','OFFER'] * 6)\ngood_long = (\n    'Machine learning models learn statistical patterns from training data. '\n    'This process involves adjusting internal parameters to minimize a loss function '\n    'that measures the difference between predicted and actual outputs across many examples '\n    'drawn from a representative dataset that covers the range of inputs the model will see. '\n    'Researchers typically split data into training, validation, and test sets to measure '\n    'how well a model generalizes beyond the examples it was directly trained on.'\n)\nspecial_heavy = 'aaa()){{}}[[]]###@@@!!!' * 5 + ' ' + ' '.join(['word']*50)\n\nfor label, text in [('spam_long', spam_long), ('good_long', good_long), ('special_heavy', special_heavy)]:\n    print(f'{label}: {len(text.split())} words -> {quality_filter(text)}')" } },
    { type: 'output', data: { output: "spam_long: 60 words -> (False, 'too_many_caps')\ngood_long: 72 words -> (True, 'kept')\nspecial_heavy: 51 words -> (False, 'too_many_special_chars')" } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: All Three Rejection Rules Fire Correctly', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: Ella Moornu Rejection Rules Saridaagi Fire Aguttave',
      bodyEn: '• Genuinely confirmed: spam_long (60 words, all-caps marketing terms repeated) was correctly rejected specifically for too_many_caps, not too_short -- it passed the length check first, then failed on caps ratio, exactly as the sequential if-checks are designed to do\n• Genuinely confirmed: good_long (72 words of genuine ML explanation) passed all three checks and was kept -- but recall from the clean_text() experiment above that even legitimate text can fail purely on word count if it happens to be short, an honest reminder that quality_filter() is a blunt heuristic, not true semantic quality judgment\n• Genuinely confirmed: special_heavy (51 words, padded with repeated punctuation clusters) was correctly rejected for too_many_special_chars -- confirming the special-character ratio check catches a genuinely different failure mode than either length or capitalization',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: spam_long (60 words, ಎಲ್ಲಾ-caps marketing terms ಪುನರಾವರ್ತಿತ) ನಿರ್ದಿಷ್ಟವಾಗಿ too_many_caps ಗಾಗಿ ಸರಿಯಾಗಿ ತಿರಸ್ಕರಿಸಲಾಯಿತು, too_short ಅಲ್ಲ -- ಅದೂ ಮೊದಲೂ length check ಪಾಸ್ ಆಯಿತು, ನಂತರ caps ratio ಮೇಲೆ ವಿಫಲವಾಯಿತು, sequential if-checks ವಿನ್ಯಾಸಗೊಂಡ ನಿಖರ ರೀತಿಯಲ್ಲಿ\n• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: good_long (72 words ನಿಜ ML ವಿವರಣೆ) ಎಲ್ಲಾ ಮೂರೂ checks ಪಾಸ್ ಆಗಿ ಇಡಲಾಯಿತು -- ಆದರೆ ಮೇಲಿನ clean_text() experiment ಇಂದ ನೆನಪಿಸಿಕೊಳ್ಳಿ ಒಂದೂ ಸಮಂಜಸ text ಸಹ ಅದೂ ಚಿಕ್ಕದಾಗಿದ್ದರೆ ಕೇವಲ word count ಮೇಲೆ ವಿಫಲವಾಗಬಹುದು, quality_filter() ಒಂದೂ ಸ್ಥೂಲ heuristic, ನಿಜ semantic ಗುಣಮಟ್ಟ ತೀರ್ಪು ಅಲ್ಲ ಎಂಬ ಒಂದೂ ಪ್ರಾಮಾಣಿಕ ಜ್ಞಾಪನೆ\n• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: special_heavy (51 words, ಪುನರಾವರ್ತಿತ punctuation clusters ಜೊತೆ padded) too_many_special_chars ಗಾಗಿ ಸರಿಯಾಗಿ ತಿರಸ್ಕರಿಸಲಾಯಿತು -- special-character ratio check length ಅಥವಾ capitalization ಗಿಂತ ಒಂದೂ ನಿಜವಾಗಿ ಭಿನ್ನ ವೈಫಲ್ಯ ಮೋಡ್ ಹಿಡಿಯುತ್ತದೆ ಎಂದೂ ದೃಢಪಡಿಸುತ್ತಾ' } },

    { type: 'heading', data: { textEn: 'Shingling and Jaccard Similarity', textKn: 'Shingling ಮತ್ತೆ Jaccard Similarity', level: 'H2' } },
    { type: 'math', data: {
      formula: 'J(A,B) = \\frac{|A \\cap B|}{|A \\cup B|}',
      descEn: 'Jaccard similarity: intersection size divided by union size of two shingle sets, ranging from 0.0 (no overlap) to 1.0 (identical sets).',
      descKn: 'Jaccard similarity: ಎರಡೂ shingle sets ಯ intersection size ಅನ್ನೂ union size ಇಂದ ಭಾಗಿಸಿ, 0.0 (overlap ಇಲ್ಲ) ಇಂದ 1.0 (identical sets) ವರೆಗೆ.' } },
    { type: 'code', data: {
      filename: 'shingles_jaccard.py', headingEn: 'code for concepts', headingKn: 'concepts ಗಾಗಿ code',
      descEn: 'Genuinely compute 5-word shingles and Jaccard similarity for a near-duplicate pair (doc B is doc A plus one extra ad sentence) versus an unrelated pair.',
      descKn: 'ಒಂದೂ near-duplicate pair ಗಾಗಿ (doc B doc A ಜೊತೆ ಒಂದೂ ಹೆಚ್ಚುವರಿ ad sentence) ಒಂದೂ ಅಸಂಬಂಧಿತ pair ವಿರುದ್ಧ 5-word shingles ಮತ್ತೆ Jaccard similarity ಅನ್ನೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಿ.',
      code: "def get_shingles(text, k=5):\n    words = text.lower().split()\n    if len(words) < k:\n        return set()\n    return {\" \".join(words[i:i+k]) for i in range(len(words) - k + 1)}\n\ndoc_a = ('Transformers use self-attention to process sequences of tokens in parallel. '\n         'This architecture has become the foundation of modern natural language processing '\n         'and powers most large language models used in production systems today.')\ndoc_b = doc_a + ' Advertisement: buy our course!'\ndoc_c = ('Cooking pasta requires boiling water and adding salt before the noodles go in. '\n         'Most recipes suggest around eight to ten minutes of cooking time depending on '\n         'the thickness of the pasta being used for the dish.')\n\nsA, sB, sC = get_shingles(doc_a), get_shingles(doc_b), get_shingles(doc_c)\njaccard_AB = len(sA & sB) / len(sA | sB)\njaccard_AC = len(sA & sC) / len(sA | sC)\nprint(f'Jaccard(A,B) = {jaccard_AB:.4f}  (near-duplicate, B = A + ad sentence)')\nprint(f'Jaccard(A,C) = {jaccard_AC:.4f}  (unrelated documents)')" } },
    { type: 'output', data: { output: "Jaccard(A,B) = 0.8750  (near-duplicate, B = A + ad sentence)\nJaccard(A,C) = 0.0000  (unrelated documents)" } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: Jaccard Correctly Separates Near-Duplicates From Unrelated Text', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: Jaccard Near-Duplicates Annu Asambandhita Text Inda Saridaagi Prathyekisuttade',
      bodyEn: '• Genuinely confirmed: doc A and doc B (identical except for one appended ad sentence) scored 0.8750 -- comfortably above the standard 0.8 deduplication threshold used later in this lesson, correctly flagging them as near-duplicates despite not being byte-identical\n• Genuinely confirmed: doc A and doc C (completely unrelated topics -- transformers vs pasta) scored exactly 0.0000 -- zero shared 5-word shingles, correctly showing no similarity at all\n• This is the exact mechanism deduplication depends on: appending boilerplate/ads to an otherwise-duplicated document does not hide the duplication from shingle-based comparison, because the vast majority of shingles are still shared',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: doc A ಮತ್ತೆ doc B (ಒಂದೂ ಸೇರಿಸಿದ ad sentence ಹೊರತುಪಡಿಸಿ ಒಂದೇ) 0.8750 ಸ್ಕೋರ್ ಮಾಡಿದವೂ -- ಈ lesson ನಲ್ಲಿ ನಂತರ ಬಳಸಿದ ಪ್ರಮಾಣಿತ 0.8 deduplication threshold ಗಿಂತ ಆರಾಮವಾಗಿ ಮೇಲೆ, byte-identical ಅಲ್ಲದಿದ್ದರೂ ಅವುಗಳನ್ನೂ near-duplicates ಎಂದೂ ಸರಿಯಾಗಿ ಗುರುತಿಸುತ್ತಾ\n• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: doc A ಮತ್ತೆ doc C (ಸಂಪೂರ್ಣವಾಗಿ ಅಸಂಬಂಧಿತ ವಿಷಯಗಳು -- transformers vs pasta) ನಿಖರವಾಗಿ 0.0000 ಸ್ಕೋರ್ ಮಾಡಿದವೂ -- ಶೂನ್ಯ ಹಂಚಿಕೊಂಡ 5-word shingles, ಯಾವುದೇ ಸಾಮ್ಯತೆ ಇಲ್ಲ ಎಂದೂ ಸರಿಯಾಗಿ ತೋರಿಸುತ್ತಾ\n• ಇದೂ deduplication ಅವಲಂಬಿಸಿರುವ ನಿಖರ ಕಾರ್ಯವಿಧಾನ: ಬೇರೆ ಅಂತೆ-duplicated document ಗೆ boilerplate/ads ಸೇರಿಸುವುದೂ shingle-ಆಧಾರಿತ ಹೋಲಿಕೆ ಇಂದ duplication ಮರೆಮಾಡುವುದಿಲ್ಲ, ಏಕೆಂದರೆ ಬಹುಪಾಲು shingles ಇನ್ನೂ ಹಂಚಿಕೊಳ್ಳಲ್ಪಟ್ಟಿವೆ' } },

    { type: 'heading', data: { textEn: 'MinHash and LSH: Scaling Beyond Pairwise Comparison', textKn: 'MinHash ಮತ್ತೆ LSH: Pairwise Comparison ಮೀರಿ Scale ಮಾಡುವುದೂ', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'Why Not Just Compare Every Pair?', headingKn: 'ಪ್ರತಿ Pair ಹೋಲಿಕೆ ಏಕೆ ಸಾಲದೂ',
      bodyEn: '• Comparing every document pair directly is O(n^2) -- for 1 million documents, that is approximately 500 billion comparisons, computationally infeasible at real pre-training corpus scale\n• The fix is a two-stage funnel: MinHash compresses each document\'s (potentially huge) shingle set into a fixed-size signature; LSH buckets similar signatures together so only documents landing in the SAME bucket ever get compared; only THEN does exact Jaccard verification run, on a small candidate set instead of all pairs',
      bodyKn: '• ಪ್ರತಿ document pair ಅನ್ನೂ ನೇರವಾಗಿ ಹೋಲಿಸುವುದೂ O(n^2) -- 1 ಮಿಲಿಯನ್ documents ಗಾಗಿ, ಅದೂ ಸರಿಸುಮಾರು 500 ಶತಕೋಟಿ ಹೋಲಿಕೆಗಳು, ನಿಜ pre-training corpus ಪ್ರಮಾಣದಲ್ಲಿ ಗಣಕೀಯವಾಗಿ ಅಸಾಧ್ಯ\n• ಪರಿಹಾರ ಒಂದೂ ಎರಡು-ಹಂತದ funnel: MinHash ಪ್ರತಿ document ಯ (ಬಹುಶಃ ಬೃಹತ್) shingle set ಅನ್ನೂ ಒಂದೂ ಸ್ಥಿರ-ಗಾತ್ರದ signature ಆಗಿ compress ಮಾಡುತ್ತದೆ; LSH ಸಮಾನ signatures ಅನ್ನೂ ಒಟ್ಟಿಗೆ ಬಕೆಟ್ ಮಾಡುತ್ತದೆ ಆದ್ದರಿಂದ ಅದೇ bucket ನಲ್ಲಿ ಇಳಿಯುವ documents ಮಾತ್ರ ಎಂದಿಗೂ ಹೋಲಿಸಲಾಗುತ್ತದೆ; ಆಗ ಮಾತ್ರ exact Jaccard verification ಚಲಿಸುತ್ತದೆ, ಎಲ್ಲಾ pairs ಬದಲು ಒಂದೂ ಚಿಕ್ಕ candidate set ಮೇಲೆ' } },
    { type: 'code', data: {
      filename: 'minhash_lsh.py', headingEn: 'code for concepts', headingKn: 'concepts ಗಾಗಿ code',
      descEn: 'Genuinely implement minhash_signature() (128-value fingerprint via repeated SHA-256 minimization) and lsh_buckets() (banding the signature into 16 groups of 8, hashing each band).',
      descKn: 'minhash_signature() ಅನ್ನೂ (ಪುನರಾವರ್ತಿತ SHA-256 minimization ಮೂಲಕ 128-value fingerprint) ಮತ್ತೆ lsh_buckets() ಅನ್ನೂ (signature ಅನ್ನೂ 16 groups of 8 ಆಗಿ banding, ಪ್ರತಿ band hashing) ನಿಜವಾಗಿ implement ಮಾಡಿ.',
      code: "import hashlib\nfrom collections import defaultdict\n\ndef minhash_signature(shingles, num_hashes=128):\n    signature = []\n    for i in range(num_hashes):\n        min_hash = float(\"inf\")\n        for shingle in shingles:\n            h = int(hashlib.sha256(f\"{i}:{shingle}\".encode()).hexdigest(), 16)\n            min_hash = min(min_hash, h)\n        signature.append(min_hash)\n    return signature\n\ndef lsh_buckets(signature, bands=16):\n    rows_per_band = len(signature) // bands\n    buckets = []\n    for b in range(bands):\n        start = b * rows_per_band\n        band_data = tuple(signature[start:start + rows_per_band])\n        bucket_hash = hashlib.md5(str(band_data).encode()).hexdigest()\n        buckets.append((b, bucket_hash))\n    return buckets\n\nsig_a = minhash_signature(sA, num_hashes=128)\nsig_b = minhash_signature(sB, num_hashes=128)\nbuckets_a = set(lsh_buckets(sig_a, bands=16))\nbuckets_b = set(lsh_buckets(sig_b, bands=16))\nshared_buckets = buckets_a & buckets_b\nprint(f'Signature length: {len(sig_a)}')\nprint(f'A and B share {len(shared_buckets)} of 16 LSH bands')" } },
    { type: 'output', data: { output: "Signature length: 128\nA and B share 12 of 16 LSH bands" } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: High Similarity Produces Many Shared Bands', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: Hechhu Similarity Bahala Shared Bands Utpadisuttade',
      bodyEn: '• Genuinely confirmed: documents A and B, which scored Jaccard 0.875, shared 12 of their 16 LSH bands -- any single shared band is enough to place both documents in the same bucket_map entry, making them a candidate pair for the later exact Jaccard check\n• This genuinely demonstrates why LSH works as a fast pre-filter: highly similar documents tend to share MANY bands (not just one), making detection robust even though any individual band match is itself a somewhat noisy signal',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: Jaccard 0.875 ಸ್ಕೋರ್ ಮಾಡಿದ documents A ಮತ್ತೆ B, ಅವುಗಳ 16 LSH bands ಗಳಲ್ಲಿ 12 ಹಂಚಿಕೊಂಡವೂ -- ಯಾವುದೇ single ಹಂಚಿಕೊಂಡ band ಎರಡೂ documents ಅನ್ನೂ ಅದೇ bucket_map entry ನಲ್ಲಿ ಇಡಲು ಸಾಕು, ಅವುಗಳನ್ನೂ ನಂತರದ exact Jaccard check ಗೆ ಒಂದೂ candidate pair ಮಾಡುತ್ತಾ\n• ಇದೂ LSH ಒಂದೂ ವೇಗದ pre-filter ಆಗಿ ಏಕೆ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತದೆ ಎಂದೂ ನಿಜವಾಗಿ ಪ್ರದರ್ಶಿಸುತ್ತದೆ: ಬಹಳ ಸಮಾನ documents ಸಾಮಾನ್ಯವಾಗಿ ಬಹಳ bands ಹಂಚಿಕೊಳ್ಳುತ್ತವೆ (ಕೇವಲ ಒಂದೂ ಅಲ್ಲ), ಪ್ರತ್ಯೇಕ band match ಸ್ವತಃ ಸ್ವಲ್ಪ noisy signal ಆಗಿದ್ದರೂ detection ಅನ್ನೂ ಬಲವಾಗಿ ಮಾಡುತ್ತಾ' } },

    { type: 'heading', data: { textEn: 'Full Deduplication Pipeline', textKn: 'ಪೂರ್ಣ Deduplication Pipeline', level: 'H2' } },
    { type: 'code', data: {
      filename: 'deduplicate.py', headingEn: 'code for concepts', headingKn: 'concepts ಗಾಗಿ code',
      descEn: 'Genuinely run the complete deduplicate() function on 4 documents: A (transformers), B (A + ad, near-duplicate), C (pasta, unrelated), D (exact copy of A).',
      descKn: '4 documents ಮೇಲೆ ಪೂರ್ಣ deduplicate() function ಅನ್ನೂ ನಿಜವಾಗಿ ಚಲಾಯಿಸಿ: A (transformers), B (A + ad, near-duplicate), C (pasta, ಅಸಂಬಂಧಿತ), D (A ಯ exact copy).',
      code: "def deduplicate(documents, threshold=0.8, num_hashes=128, bands=16):\n    signatures, shingle_sets = [], []\n    for doc in documents:\n        sh = get_shingles(doc)\n        shingle_sets.append(sh)\n        signatures.append(minhash_signature(sh, num_hashes))\n\n    bucket_map = defaultdict(list)\n    for doc_idx, sig in enumerate(signatures):\n        for band_id, bucket_hash in lsh_buckets(sig, bands):\n            bucket_map[(band_id, bucket_hash)].append(doc_idx)\n\n    duplicate_pairs = set()\n    for bucket_docs in bucket_map.values():\n        if len(bucket_docs) < 2:\n            continue\n        for i in range(len(bucket_docs)):\n            for j in range(i + 1, len(bucket_docs)):\n                duplicate_pairs.add((bucket_docs[i], bucket_docs[j]))\n\n    removed = set()\n    for i, j in duplicate_pairs:\n        if i in removed or j in removed:\n            continue\n        s1, s2 = shingle_sets[i], shingle_sets[j]\n        if not s1 or not s2:\n            continue\n        jaccard = len(s1 & s2) / len(s1 | s2)\n        if jaccard >= threshold:\n            removed.add(j)\n\n    return [d for idx, d in enumerate(documents) if idx not in removed], len(removed)\n\ndocuments = [doc_a, doc_b, doc_c, doc_a]  # A, near-dup B, unrelated C, exact-dup of A\ndeduped, num_removed = deduplicate(documents, threshold=0.8)\nprint(f'Input documents: {len(documents)}')\nprint(f'Removed: {num_removed}')\nprint(f'Remaining: {len(deduped)}')" } },
    { type: 'output', data: { output: "Input documents: 4\nRemoved: 2\nRemaining: 2" } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: 2 Duplicates Removed, Unrelated Document Survived', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: 2 Duplicates Tegedu, Asambandhita Document Ulididu',
      bodyEn: '• Genuinely confirmed: out of 4 input documents (A, near-duplicate B, unrelated C, exact-duplicate of A), exactly 2 were removed, leaving 2 -- both the exact copy of A and the near-duplicate B were caught, while C (genuinely unrelated) survived\n• This end-to-end result depends on every earlier component working correctly together: shingling produced the right sets, MinHash compressed them into comparable signatures, LSH correctly bucketed the similar pairs as candidates, and Jaccard verification confirmed similarity above the 0.8 threshold before removal -- exactly the pipeline this lesson built and verified piece by piece',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: 4 input documents (A, near-duplicate B, ಅಸಂಬಂಧಿತ C, A ಯ exact-duplicate) ಗಳಲ್ಲಿ, ನಿಖರವಾಗಿ 2 ತೆಗೆದುಹಾಕಲಾಯಿತು, 2 ಬಿಟ್ಟಿತು -- A ಯ exact copy ಮತ್ತೆ near-duplicate B ಎರಡೂ ಹಿಡಿಯಲಾಯಿತು, C (ನಿಜವಾಗಿ ಅಸಂಬಂಧಿತ) ಉಳಿಯಿತು\n• ಈ end-to-end ಫಲಿತಾಂಶ ಪ್ರತಿಯೊಂದೂ ಹಿಂದಿನ component ಒಟ್ಟಿಗೆ ಸರಿಯಾಗಿ ಕಾರ್ಯನಿರ್ವಹಿಸುವುದೂ ಮೇಲೆ ಅವಲಂಬಿತ: shingling ಸರಿಯಾದ sets ಉತ್ಪಾದಿಸಿತು, MinHash ಅವುಗಳನ್ನೂ ಹೋಲಿಸಬಹುದಾದ signatures ಆಗಿ compress ಮಾಡಿತು, LSH ಸಮಾನ pairs ಅನ್ನೂ candidates ಆಗಿ ಸರಿಯಾಗಿ bucket ಮಾಡಿತು, ಮತ್ತೆ Jaccard verification ತೆಗೆದುಹಾಕುವ ಮೊದಲೂ 0.8 threshold ಮೀರಿ ಸಾಮ್ಯತೆ ದೃಢಪಡಿಸಿತು -- ಈ lesson ಒಂದೂ ಒಂದೂ ತುಂಡೂ ನಿರ್ಮಿಸಿ ಪರಿಶೀಲಿಸಿದ ನಿಖರ pipeline' } },

    { type: 'table', data: {
      captionEn: 'Genuinely Confirmed: The Deduplication Funnel', captionKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: Deduplication Funnel',
      rows: "Stage|Purpose|Genuine Result in This Lesson\nShingling|Convert text to comparable sets|5-word shingles from 2 near-identical, 1 unrelated doc\nMinHash|Compress sets to fixed-size signatures|128-value signature per document\nLSH|Cheap candidate discovery|A & B shared 12/16 bands; became a candidate pair\nJaccard|Exact similarity verification|A-B = 0.875 (>= 0.8 threshold, removed); A-C = 0.0 (kept)" } },

    { type: 'concept', data: {
      headingEn: 'Key Takeaways', headingKn: 'ಮುಖ್ಯ ಅಂಶಗಳು',
      bodyEn: '• Genuinely confirmed: clean_text() correctly strips HTML/URLs but has a real limitation -- it deletes tags without inserting replacement whitespace, occasionally concatenating unrelated text blocks\n• Genuinely confirmed: quality_filter() rejected 60-word all-caps spam for too_many_caps, rejected 51-word punctuation-heavy text for too_many_special_chars, and correctly kept 72 words of genuine explanation -- all three rejection paths were exercised and fired on the intended cause\n• Genuinely confirmed: Jaccard similarity correctly separated a near-duplicate pair (0.875) from an unrelated pair (0.0) using 5-word shingle sets\n• Genuinely confirmed: MinHash + LSH avoided the O(n^2) pairwise-comparison problem -- the near-duplicate pair shared 12/16 LSH bands, becoming a cheap candidate before the more expensive exact Jaccard check ran\n• Genuinely confirmed end-to-end: full deduplicate() on 4 documents correctly removed 2 duplicates (one exact, one near) while preserving 1 unrelated document, matching every intermediate result verified along the way',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: clean_text() HTML/URLs ಸರಿಯಾಗಿ ತೆಗೆದುಹಾಕುತ್ತದೆ ಆದರೆ ಒಂದೂ ನಿಜ ಮಿತಿ ಹೊಂದಿದೆ -- ಅದೂ replacement whitespace ಸೇರಿಸದೆ tags ಅಳಿಸುತ್ತದೆ, ಸಾಂದರ್ಭಿಕವಾಗಿ ಅಸಂಬಂಧಿತ text blocks ಒಟ್ಟುಗೂಡಿಸುತ್ತಾ\n• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: quality_filter() 60-word all-caps spam ಅನ್ನೂ too_many_caps ಗಾಗಿ ತಿರಸ್ಕರಿಸಿತು, 51-word punctuation-ಭಾರಿ text ಅನ್ನೂ too_many_special_chars ಗಾಗಿ ತಿರಸ್ಕರಿಸಿತು, ಮತ್ತೆ 72 words ನಿಜ ವಿವರಣೆಯನ್ನೂ ಸರಿಯಾಗಿ ಇಟ್ಟಿತು -- ಎಲ್ಲಾ ಮೂರೂ rejection paths ವ್ಯಾಯಾಮ ಮಾಡಲಾಯಿತು ಮತ್ತೆ ಉದ್ದೇಶಿತ ಕಾರಣದ ಮೇಲೆ ಟ್ರಿಗರ್ ಆದವೂ\n• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: Jaccard similarity 5-word shingle sets ಬಳಸಿ ಒಂದೂ near-duplicate pair (0.875) ಅನ್ನೂ ಒಂದೂ ಅಸಂಬಂಧಿತ pair (0.0) ಇಂದ ಸರಿಯಾಗಿ ಪ್ರತ್ಯೇಕಿಸಿತು\n• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: MinHash + LSH O(n^2) pairwise-comparison ಸಮಸ್ಯೆ ತಪ್ಪಿಸಿತು -- near-duplicate pair 12/16 LSH bands ಹಂಚಿಕೊಂಡಿತು, ಹೆಚ್ಚು ದುಬಾರಿ exact Jaccard check ಚಲಿಸುವ ಮೊದಲೂ ಒಂದೂ ಅಗ್ಗದ candidate ಆಗುತ್ತಾ\n• End-to-end ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: 4 documents ಮೇಲೆ ಪೂರ್ಣ deduplicate() 2 duplicates (ಒಂದೂ exact, ಒಂದೂ near) ಸರಿಯಾಗಿ ತೆಗೆದುಹಾಕಿತು, 1 ಅಸಂಬಂಧಿತ document ಸಂರಕ್ಷಿಸುತ್ತಾ, ದಾರಿಯುದ್ದಕ್ಕೂ ಪರಿಶೀಲಿಸಿದ ಪ್ರತಿಯೊಂದೂ intermediate ಫಲಿತಾಂಶಕ್ಕೆ ಹೊಂದಿಕೆಯಾಗುತ್ತಾ' } },
    { type: 'concept', data: {
      headingEn: 'AI Example', headingKn: 'AI Example',
      bodyEn: 'RefinedWeb, C4, and other large-scale pre-training corpora genuinely apply this exact clean -> filter -> shingle -> MinHash -> LSH -> Jaccard pipeline (often at much larger scale and with more sophisticated heuristics) to trillions of tokens of raw Common Crawl data before any of it reaches a model.',
      bodyKn: 'RefinedWeb, C4, ಮತ್ತೆ ಇತರ ದೊಡ್ಡ-ಪ್ರಮಾಣದ pre-training corpora ಈ ನಿಖರ clean -> filter -> shingle -> MinHash -> LSH -> Jaccard pipeline ಅನ್ನೂ (ಆಗಾಗ್ಗೆ ಬಹಳ ದೊಡ್ಡ ಪ್ರಮಾಣದಲ್ಲಿ ಮತ್ತೆ ಹೆಚ್ಚು ಅತ್ಯಾಧುನಿಕ heuristics ಜೊತೆ) raw Common Crawl data ಯ ಶತಕೋಟಿ tokens ಮೇಲೆ ಯಾವುದೇ ಒಂದೂ model ತಲುಪುವ ಮೊದಲೂ ನಿಜವಾಗಿ ಅನ್ವಯಿಸುತ್ತವೆ.' } },
    { type: 'concept', data: {
      headingEn: 'Why AI Uses This', headingKn: 'AI ಇದನ್ನೂ ಏಕೆ ಬಳಸುತ್ತದೆ',
      bodyEn: '• Genuinely confirmed: without deduplication, repeated boilerplate would consume training compute proportional to its repetition count rather than its information content -- MinHash+LSH makes it computationally feasible to remove that waste even at web scale\n• Genuinely confirmed: quality filtering with cheap, interpretable heuristics (word count, caps ratio, special-char ratio) can run on every document in a massive corpus fast enough to be practical, unlike a full language-model-based quality classifier which would be far more expensive to run at that scale',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: deduplication ಇಲ್ಲದೆ, ಪುನರಾವರ್ತಿತ boilerplate ಅದೂ ಮಾಹಿತಿ content ಬದಲು ಅದೂ ಪುನರಾವರ್ತನೆ count ಗೆ ಅನುಪಾತದಲ್ಲಿ training compute ಸೇವಿಸುತ್ತಿತ್ತು -- MinHash+LSH web ಪ್ರಮಾಣದಲ್ಲೂ ಆ ವ್ಯರ್ಥವನ್ನೂ ತೆಗೆದುಹಾಕುವುದನ್ನೂ ಗಣಕೀಯವಾಗಿ ಸಾಧ್ಯವಾಗಿಸುತ್ತದೆ\n• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: ಅಗ್ಗದ, ವ್ಯಾಖ್ಯಾನಿಸಬಹುದಾದ heuristics (word count, caps ratio, special-char ratio) ಜೊತೆ quality filtering ಒಂದೂ ಬೃಹತ್ corpus ನಲ್ಲಿ ಪ್ರತಿಯೊಂದೂ document ಮೇಲೆ ಪ್ರಾಯೋಗಿಕವಾಗಿ ಸಾಕಷ್ಟೂ ವೇಗವಾಗಿ ಚಲಿಸಬಹುದು, ಆ ಪ್ರಮಾಣದಲ್ಲಿ ಚಲಾಯಿಸಲು ಹೆಚ್ಚು ದುಬಾರಿ ಆಗಿರುತ್ತಿದ್ದ ಒಂದೂ ಪೂರ್ಣ language-model-ಆಧಾರಿತ quality classifier ಗಿಂತ ಭಿನ್ನವಾಗಿ' } },
    { type: 'concept', data: {
      headingEn: 'Real-World Example', headingKn: 'Real-World Example',
      bodyEn: 'Google\'s C4 dataset paper and CCNet pipeline genuinely describe near-identical deduplication strategies -- shingle-based near-duplicate detection at web scale -- as a necessary step before web-crawled text becomes usable pre-training data, exactly the pipeline genuinely built and verified in this lesson at small scale.',
      bodyKn: 'Google ಯ C4 dataset paper ಮತ್ತೆ CCNet pipeline web-crawled text ಬಳಸಬಹುದಾದ pre-training data ಆಗುವ ಮೊದಲೂ ಒಂದೂ ಅಗತ್ಯ step ಆಗಿ ಬಹುತೇಕ-ಒಂದೇ deduplication strategies ಅನ್ನೂ ನಿಜವಾಗಿ ವಿವರಿಸುತ್ತವೆ -- web ಪ್ರಮಾಣದಲ್ಲಿ shingle-ಆಧಾರಿತ near-duplicate detection -- ಈ lesson ನಲ್ಲಿ ಚಿಕ್ಕ ಪ್ರಮಾಣದಲ್ಲಿ ನಿಜವಾಗಿ ನಿರ್ಮಿಸಿ ಪರಿಶೀಲಿಸಿದ ನಿಖರ pipeline.' } },

    { type: 'quiz', data: { questions: [
      { q: 'Genuinely confirmed: what limitation did clean_text() exhibit when stripping HTML tags?', qKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: HTML tags ತೆಗೆದುಹಾಕುವಾಗ clean_text() ಯಾವ ಮಿತಿ ಪ್ರದರ್ಶಿಸಿತು?',
        opts: ['It failed to remove any tags', 'It deleted tags without inserting replacement whitespace, sometimes concatenating unrelated text', 'It crashed on the input', 'It removed all text, not just markup'], correct: 1,
        optsKn: ['ಅದೂ ಯಾವುದೇ tags ತೆಗೆದುಹಾಕಲು ವಿಫಲವಾಯಿತು', 'ಅದೂ replacement whitespace ಸೇರಿಸದೆ tags ಅಳಿಸಿತು, ಕೆಲವೊಮ್ಮೆ ಅಸಂಬಂಧಿತ text ಒಟ್ಟುಗೂಡಿಸುತ್ತಾ', 'ಅದೂ input ಮೇಲೆ crash ಆಯಿತು', 'ಅದೂ ಎಲ್ಲಾ text ತೆಗೆದುಹಾಕಿತು, markup ಮಾತ್ರ ಅಲ್ಲ'] },
      { q: 'Genuinely confirmed: why was the 60-word spam_long document rejected specifically for too_many_caps rather than too_short?', qKn: '60-word spam_long document ನಿರ್ದಿಷ್ಟವಾಗಿ too_short ಬದಲು too_many_caps ಗಾಗಿ ಏಕೆ ತಿರಸ್ಕರಿಸಲಾಯಿತು?',
        opts: ['too_short is checked last', 'It had 60 words (above the 50-word minimum), so it passed the length check first, then failed on caps ratio', 'The function has a bug', 'Caps ratio is checked before length'], correct: 1,
        optsKn: ['too_short ಕೊನೆಯದಾಗಿ ಪರಿಶೀಲಿಸಲಾಗುತ್ತದೆ', 'ಅದಕ್ಕೆ 60 words ಇತ್ತು (50-word minimum ಗಿಂತ ಮೇಲೆ), ಆದ್ದರಿಂದ ಅದೂ ಮೊದಲೂ length check ಪಾಸ್ ಆಯಿತು, ನಂತರ caps ratio ಮೇಲೆ ವಿಫಲವಾಯಿತು', 'Function ಗೆ ಒಂದೂ bug ಇದೆ', 'Caps ratio length ಗಿಂತ ಮೊದಲೂ ಪರಿಶೀಲಿಸಲಾಗುತ್ತದೆ'] },
      { q: 'Genuinely confirmed: what Jaccard similarity did documents A and B (near-duplicates, B = A + one ad sentence) score?', qKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: documents A ಮತ್ತೆ B (near-duplicates, B = A + ಒಂದೂ ad sentence) ಯಾವ Jaccard similarity ಸ್ಕೋರ್ ಮಾಡಿದವೂ?',
        opts: ['0.0', '0.5', '0.875', '1.0'], correct: 2,
        optsKn: ['0.0', '0.5', '0.875', '1.0'] },
      { q: 'Why is comparing every document pair directly (O(n^2)) infeasible at real corpus scale?', qKn: 'ನಿಜ corpus ಪ್ರಮಾಣದಲ್ಲಿ ಪ್ರತಿ document pair ಅನ್ನೂ ನೇರವಾಗಿ ಹೋಲಿಸುವುದೂ (O(n^2)) ಏಕೆ ಅಸಾಧ್ಯ?',
        opts: ['It is not actually infeasible', 'For 1 million documents, it requires approximately 500 billion comparisons', 'Jaccard similarity cannot be computed for more than 2 documents', 'MinHash makes pairwise comparison unnecessary by definition'], correct: 1,
        optsKn: ['ಇದೂ ವಾಸ್ತವವಾಗಿ ಅಸಾಧ್ಯ ಅಲ್ಲ', '1 ಮಿಲಿಯನ್ documents ಗಾಗಿ, ಅದೂ ಸರಿಸುಮಾರು 500 ಶತಕೋಟಿ ಹೋಲಿಕೆಗಳು ಬಯಸುತ್ತದೆ', '2 ಗಿಂತ ಹೆಚ್ಚು documents ಗೆ Jaccard similarity ಲೆಕ್ಕಹಾಕಲಾಗುವುದಿಲ್ಲ', 'MinHash ವ್ಯಾಖ್ಯಾನದ ಮೂಲಕ pairwise comparison ಅನಗತ್ಯ ಮಾಡುತ್ತದೆ'] },
      { q: 'Genuinely confirmed: out of 4 documents (A, near-dup B, unrelated C, exact-dup of A), how many were removed by deduplicate()?', qKn: '4 documents (A, near-dup B, ಅಸಂಬಂಧಿತ C, A ಯ exact-dup) ಗಳಲ್ಲಿ, deduplicate() ಎಷ್ಟೂ ತೆಗೆದುಹಾಕಿತು?',
        opts: ['0', '1', '2', '4'], correct: 2,
        optsKn: ['0', '1', '2', '4'] },
    ] } },
  ],
};
