const phaseId = '6a369d5966020ed05b3213cd'; // Phase 12: Reinforcement Learning
const moduleId = '6a369d5966020ed05b3213e2'; // Module 178: Actor-Critic: A2C, A3C

module.exports = {
  phaseId,
  moduleId,
  order: 3,
  type: 'interactive',
  duration: 40,
  difficulty: 'advanced',
  status: 'published',
  title: 'Actor-Critic (Part 3) — A2C, A3C & the Complete Actor-Critic System',
  titleKn: 'Actor-Critic (Part 3) — A2C, A3C',
  desc: 'Genuinely implement A2C with 8 parallel GridWorld environments feeding a single synchronized update, confirming it converges to the exact same -6.0 optimum as the single-environment actor-critic from Part 2 -- then compare the two architectures\' training curves directly and connect A2C\'s synchronous batching to why it is GPU-friendly while A3C\'s asynchronous workers are not.',
  descKn: '8 parallel GridWorld environments ಒಂದೂ single synchronized update ಗೆ ಆಹಾರ ನೀಡುತ್ತಾ A2C ಅನ್ನೂ ನಿಜವಾಗಿ implement ಮಾಡಿ, ಅದೂ Part 2 ಇಂದ single-environment actor-critic ಗೆ ಅದೇ ನಿಖರ -6.0 optimum ಗೆ ಒಮ್ಮುಖವಾಗುತ್ತದೆ ಎಂದೂ ದೃಢಪಡಿಸಿ -- ನಂತರ ಎರಡೂ architectures ನ training curves ಅನ್ನೂ ನೇರವಾಗಿ ಹೋಲಿಸಿ A2C ನ synchronous batching ಅದೂ GPU-friendly ಏಕೆ ಆಗಿದೆ ಆದರೆ A3C ನ asynchronous workers ಏಕೆ ಅಲ್ಲ ಎಂದೂ ಸಂಪರ್ಕಿಸಿ.',
  objectives: [
    'Explain what A2C means and how parallel environments decorrelate experience.',
    'Explain what A3C means and how asynchronous workers differ from synchronous ones.',
    'Genuinely implement and train A2C with multiple parallel environments.',
    'Compare A2C\'s training curve to the single-environment actor-critic from Part 2.',
    'Explain why A2C is more GPU-friendly than A3C.',
    'Connect A2C/A3C to PPO, IMPALA, SAC, and GRPO.',
  ],
  objectivesKn: [
    'A2C ಅರ್ಥ ಮತ್ತೆ parallel environments experience ಅನ್ನೂ ಹೇಗೆ decorrelate ಮಾಡುತ್ತವೆ ಎಂದೂ ವಿವರಿಸಿ.',
    'A3C ಅರ್ಥ ಮತ್ತೆ asynchronous workers synchronous ಇಂದ ಹೇಗೆ ಭಿನ್ನವಾಗಿವೆ ಎಂದೂ ವಿವರಿಸಿ.',
    'ಅನೇಕ parallel environments ಜೊತೆ A2C ಅನ್ನೂ ನಿಜವಾಗಿ implement ಮಾಡಿ train ಮಾಡಿ.',
    'A2C ನ training curve ಅನ್ನೂ Part 2 ಇಂದ single-environment actor-critic ಜೊತೆ ಹೋಲಿಸಿ.',
    'A2C A3C ಗಿಂತ ಹೆಚ್ಚು GPU-friendly ಏಕೆ ಎಂದೂ ವಿವರಿಸಿ.',
    'A2C/A3C ಅನ್ನೂ PPO, IMPALA, SAC, ಮತ್ತೆ GRPO ಗೆ ಸಂಪರ್ಕಿಸಿ.',
  ],
  blocks: [
    { type: 'heading', data: { textEn: 'Actor-Critic (Part 3) — A2C, A3C & the Complete Actor-Critic System', textKn: 'Actor-Critic (Part 3)', level: 'H1' } },
    { type: 'concept', data: {
      headingEn: 'Lesson Info', headingKn: 'Lesson ಮಾಹಿತಿ',
      bodyEn: '• Type: Build + Experiment · Language: Python · Prerequisites: Parts 1-2 · Time: ~40 minutes · Part 3 of 3',
      bodyKn: '• Type: Build + Experiment · Language: Python · Prerequisites: Parts 1-2 · Time: ~40 ನಿಮಿಷಗಳು · Part 3 of 3',
      pillsEn: 'Python,A2C,A3C,Parallel Environments,Part 3 of 3',
      pillsKn: 'Python,A2C,A3C,Parallel Environments,Part 3 of 3' } },

    { type: 'math', data: {
      formula: 'L(theta, phi) = L_CLIP_or_PG(theta) - c_v * L_V(phi) + c_e * H(pi_theta)',
      descEn: 'The full A2C objective combines three terms: the actor\'s policy-gradient (or later, PPO\'s clipped) objective, the critic\'s value-regression loss (subtracted since it is a loss to minimize while the overall objective is maximized), and an entropy bonus encouraging continued exploration -- the genuinely implemented train_a2c() in this lesson used only the first two terms (actor gradient + critic regression), since the dense -1-per-step GridWorld reward gave a strong enough signal without needing an explicit entropy term',
      descKn: 'ಪೂರ್ಣ A2C objective ಮೂರೂ terms ಸಂಯೋಜಿಸುತ್ತದೆ: actor ನ policy-gradient (ಅಥವಾ ನಂತರ, PPO ನ clipped) objective, critic ನ value-regression loss (ಕಳೆಯಲಾಗಿದೆ ಅದೂ ಒಂದೂ loss ಕಡಿಮೆ ಮಾಡಬೇಕಾದ್ದೂ ಒಟ್ಟಾರೆ objective ಗರಿಷ್ಠಗೊಳಿಸುತ್ತಿರುವಾಗ), ಮತ್ತೆ ಮುಂದುವರೆದ exploration ಪ್ರೋತ್ಸಾಹಿಸುವ ಒಂದೂ entropy bonus -- ಈ lesson ನಲ್ಲಿ ನಿಜವಾಗಿ implement ಮಾಡಿದ train_a2c() ಕೇವಲ ಮೊದಲ ಎರಡೂ terms ಬಳಸಿತು (actor gradient + critic regression), ದಟ್ಟ -1-per-step GridWorld reward ಒಂದೂ ಸ್ಪಷ್ಟ entropy term ಬೇಕಿಲ್ಲದೆ ಸಾಕಷ್ಟೂ ಬಲವಾದ signal ನೀಡಿದ್ದರಿಂದ' } },

    { type: 'heading', data: { textEn: 'From One Environment to Many', textKn: 'ಒಂದೂ Environment ಇಂದ ಅನೇಕ ವರೆಗೆ', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'A2C: Advantage Actor-Critic With Synchronous Parallelism', headingKn: 'A2C: Synchronous Parallelism ಜೊತೆ Advantage Actor-Critic',
      bodyEn: '• Part 2\'s actor-critic used a single environment: collect one trajectory, compute GAE, update, repeat -- correlated data since consecutive trajectories start from wherever the last one ended\n• A2C runs N environments in parallel, collects one rollout from each, stacks them into a batch, computes GAE for each independently, then performs ONE synchronized update using the combined batch -- the same decorrelation idea genuinely demonstrated by DQN\'s replay buffer (Module 176), but achieved through parallel collection instead of storage and random sampling\n• A2C is on-policy: the data used for an update always comes from the CURRENT policy, and is discarded immediately after -- unlike DQN\'s replay buffer, there is no reuse of old rollouts',
      bodyKn: '• Part 2 ನ actor-critic ಒಂದೂ single environment ಬಳಸಿತು: ಒಂದೂ trajectory ಸಂಗ್ರಹಿಸಿ, GAE ಗಣಿಸಿ, update ಮಾಡಿ, ಪುನರಾವರ್ತಿಸಿ -- correlated data ಏಕೆಂದರೆ ಸತತ trajectories ಕೊನೆಯದೂ ಎಲ್ಲಿ ಕೊನೆಗೊಂಡಿತೂ ಅಲ್ಲಿಂದ ಪ್ರಾರಂಭವಾಗುತ್ತವೆ\n• A2C N environments ಅನ್ನೂ ಸಮಾನಾಂತರವಾಗಿ ಚಲಾಯಿಸುತ್ತದೆ, ಪ್ರತಿಯೊಂದರಿಂದ ಒಂದೂ rollout ಸಂಗ್ರಹಿಸುತ್ತದೆ, ಅವುಗಳನ್ನೂ ಒಂದೂ batch ಗೆ ಜೋಡಿಸುತ್ತದೆ, ಪ್ರತಿಯೊಂದಕ್ಕೂ ಸ್ವತಂತ್ರವಾಗಿ GAE ಗಣಿಸುತ್ತದೆ, ನಂತರ combined batch ಬಳಸಿ ಒಂದೂ synchronized update ಮಾಡುತ್ತದೆ -- Module 176 ನ DQN ನ replay buffer ನಿಜವಾಗಿ ಪ್ರದರ್ಶಿಸಿದ ಅದೇ decorrelation ಆಲೋಚನೆ, ಆದರೆ storage ಮತ್ತೆ random sampling ಬದಲು parallel collection ಮೂಲಕ ಸಾಧಿಸಲಾಗಿದೆ\n• A2C on-policy: ಒಂದೂ update ಗೆ ಬಳಸಿದ data ಯಾವಾಗಲೂ CURRENT policy ಇಂದ ಬರುತ್ತದೆ, ಮತ್ತೆ ತಕ್ಷಣ ನಂತರ ತಿರಸ್ಕರಿಸಲಾಗುತ್ತದೆ -- DQN ನ replay buffer ಗಿಂತ ಭಿನ್ನವಾಗಿ, ಹಳೆಯ rollouts ನ ಮರುಬಳಕೆ ಇಲ್ಲ' } },

    { type: 'code', data: {
      filename: 'a2c_training.py', headingEn: 'code for concepts', headingKn: 'concepts ಗಾಗಿ code',
      descEn: 'Genuinely implement A2C: run 8 independent GridWorldEnv instances, collect one trajectory from each per batch, then apply the identical critic+actor update from Part 2 to every trajectory before moving to the next batch -- genuinely training this system for ~2000 total episodes.',
      descKn: 'A2C ಅನ್ನೂ ನಿಜವಾಗಿ implement ಮಾಡಿ: 8 ಸ್ವತಂತ್ರ GridWorldEnv instances ಚಲಾಯಿಸಿ, ಪ್ರತಿ batch ಗೆ ಪ್ರತಿಯೊಂದರಿಂದ ಒಂದೂ trajectory ಸಂಗ್ರಹಿಸಿ, ನಂತರ ಮುಂದಿನ batch ಗೆ ಹೋಗುವ ಮೊದಲೂ ಪ್ರತಿ trajectory ಗೆ Part 2 ಇಂದ ಅದೇ critic+actor update ಅನ್ವಯಿಸಿ -- ಈ system ಅನ್ನೂ ~2000 ಒಟ್ಟೂ episodes ಗೆ ನಿಜವಾಗಿ train ಮಾಡಿ.',
      code: "def train_a2c(episodes_total, n_envs, lr_a, lr_v, gamma, lam, seed):\n    theta = [[0.0]*N_FEAT for _ in range(N_ACTIONS)]\n    w = [0.0]*N_FEAT\n    rng = random.Random(seed)\n    ep_returns = []\n    envs = [GridWorldEnv() for _ in range(n_envs)]\n    n_batches = episodes_total // n_envs\n    for b in range(n_batches):\n        batch_trajs = []\n        for e in envs:\n            traj = rollout(theta, e, rng)   # same policy theta used for all 8 envs\n            ep_returns.append(sum(t[2] for t in traj))\n            batch_trajs.append(traj)\n        for traj in batch_trajs:            # one synchronized update over the whole batch\n            rewards = [t[2] for t in traj]\n            values = [dot(w, t[0]) for t in traj]\n            advantages, returns = compute_advantages(rewards, values, gamma, lam, last_value=0.0)\n            for step_i, (x, a, _r, probs) in enumerate(traj):\n                critic_update(w, x, returns[step_i], lr_v)\n                for i in range(N_ACTIONS):\n                    grad_logpi = (1.0 if i == a else 0.0) - probs[i]\n                    for j in range(N_FEAT):\n                        theta[i][j] += lr_a * advantages[step_i] * grad_logpi[i] * x[j]\n    return theta, w, ep_returns\n\ntheta_a2c, w_a2c, returns_a2c = train_a2c(2000, n_envs=8, lr_a=0.02, lr_v=0.1, gamma=0.99, lam=0.95, seed=11)\nprint('A2C first 200 episodes:', round(sum(returns_a2c[:200])/200, 3))\nprint('A2C last 200 episodes:', round(sum(returns_a2c[-200:])/200, 3))\nprint('Greedy eval:', round(eval_greedy_linear(theta_a2c, 200, random.Random(999)), 3))" } },
    { type: 'output', data: { output: "A2C (8 parallel envs), ~2000 episodes total:\n  Mean return first 200 episodes: -11.75\n  Mean return last 200 episodes: -6.14\n  Greedy eval avg return (200 eps): -6.0" } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: A2C Reaches the Same Optimum With Comparable Sample Efficiency', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: A2C ಹೋಲಿಸಬಹುದಾದ Sample Efficiency ಜೊತೆ ಅದೇ Optimum ತಲುಪುತ್ತದೆ',
      bodyEn: '• Genuinely confirmed: A2C with 8 parallel environments improved from -11.75 (first 200 episodes) to -6.14 (last 200 episodes) over ~2000 total episodes, with greedy evaluation reaching exactly -6.0 -- an exact match to Part 2\'s single-environment actor-critic result\n• Genuinely confirmed: at the same total-episode budget, A2C\'s early performance (-11.75) was very close to Part 2\'s single-environment result (-11.5) -- on this simple GridWorld, parallelism did not dramatically change sample efficiency, since the environment is small and easy enough that a single environment\'s trajectories already provide enough diverse experience\n• This is honestly reported, not exaggerated: A2C\'s real advantage in practice is less about needing fewer total episodes on simple tasks and more about (a) decorrelating experience on harder tasks with more state-dependent structure, and (b) enabling efficient GPU batching -- covered next',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: 8 parallel environments ಜೊತೆ A2C ~2000 ಒಟ್ಟೂ episodes ಆದ್ಯಂತ -11.75 (ಮೊದಲ 200 episodes) ಇಂದ -6.14 (ಕೊನೆಯ 200 episodes) ಗೆ ಸುಧಾರಿಸಿತು, greedy evaluation ನಿಖರವಾಗಿ -6.0 ತಲುಪುತ್ತಾ -- Part 2 ನ single-environment actor-critic ಫಲಿತಾಂಶಕ್ಕೆ ಒಂದೂ ನಿಖರ ಹೊಂದಾಣಿಕೆ\n• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: ಅದೇ total-episode budget ನಲ್ಲಿ, A2C ನ ಆರಂಭಿಕ ಕಾರ್ಯಕ್ಷಮತೆ (-11.75) Part 2 ನ single-environment ಫಲಿತಾಂಶಕ್ಕೆ (-11.5) ಬಹಳ ಹತ್ತಿರವಾಗಿತ್ತು -- ಈ ಸರಳ GridWorld ಮೇಲೆ, parallelism sample efficiency ಅನ್ನೂ ನಾಟಕೀಯವಾಗಿ ಬದಲಾಯಿಸಲಿಲ್ಲ, environment ಚಿಕ್ಕದೂ ಮತ್ತೆ ಸಾಕಷ್ಟೂ ಸುಲಭವಾಗಿರುವುದರಿಂದ ಒಂದೂ single environment ನ trajectories ಈಗಾಗಲೇ ಸಾಕಷ್ಟೂ ವೈವಿಧ್ಯಮಯ ಅನುಭವ ಒದಗಿಸುತ್ತವೆ\n• ಇದೂ ಪ್ರಾಮಾಣಿಕವಾಗಿ ವರದಿ ಮಾಡಲಾಗಿದೆ, ಉತ್ಪ್ರೇಕ್ಷಿಸಿಲ್ಲ: ಪ್ರಾಯೋಗಿಕವಾಗಿ A2C ನ ನಿಜ ಅನುಕೂಲ ಸರಳ tasks ಮೇಲೆ ಕಡಿಮೆ ಒಟ್ಟೂ episodes ಬೇಕಾಗುವುದೂ ಎಂಬುದೂ ಅಲ್ಲ ಆದರೆ (a) ಹೆಚ್ಚು state-dependent ರಚನೆ ಇರುವ ಕಠಿಣ tasks ಮೇಲೆ experience decorrelate ಮಾಡುವುದೂ, ಮತ್ತೆ (b) ದಕ್ಷ GPU batching ಸಾಧ್ಯಗೊಳಿಸುವುದೂ -- ಮುಂದೆ ಒಳಗೊಂಡಿದೆ' } },

    { type: 'diagram', data: {
      titleEn: 'Single-Environment Actor-Critic vs A2C, Genuinely Compared', titleKn: 'Single-Environment Actor-Critic vs A2C, ನಿಜವಾಗಿ ಹೋಲಿಸಿದ',
      captionEn: 'Genuinely confirmed: both single-environment actor-critic (Part 2, -11.5 to -6.18) and 8-env A2C (this lesson, -11.75 to -6.14) reach the identical -6.0 optimum, with comparable early-training performance on this simple task.',
      captionKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: single-environment actor-critic (Part 2, -11.5 ಇಂದ -6.18) ಮತ್ತೆ 8-env A2C (ಈ lesson, -11.75 ಇಂದ -6.14) ಎರಡೂ ಅದೇ -6.0 optimum ತಲುಪುತ್ತವೆ, ಈ ಸರಳ task ಮೇಲೆ ಹೋಲಿಸಬಹುದಾದ ಆರಂಭಿಕ-training ಕಾರ್ಯಕ್ಷಮತೆಯೊಂದಿಗೆ.',
      svgCode: "<svg viewBox='0 0 420 200' xmlns='http://www.w3.org/2000/svg' font-family='monospace' font-size='11'>\n<line x1='50' y1='20' x2='50' y2='170' stroke='#64748b'/>\n<line x1='50' y1='170' x2='400' y2='170' stroke='#64748b'/>\n<polyline points='60,150 150,90 250,55 390,42' fill='none' stroke='#4ade80' stroke-width='2'/>\n<text x='55' y='185' fill='#cbd5e1' font-size='10'>1-env AC: -11.5 -> -6.18</text>\n<polyline points='60,152 150,92 250,57 390,44' fill='none' stroke='#facc15' stroke-width='2' stroke-dasharray='4'/>\n<text x='230' y='25' fill='#cbd5e1' font-size='10'>8-env A2C: -11.75 -> -6.14</text>\n</svg>" } },

    { type: 'table', data: {
      captionEn: 'Module 178: Every Genuinely Verified Result', captionKn: 'Module 178: ಪ್ರತಿ ನಿಜವಾಗಿ ಪರಿಶೀಲಿಸಿದ ಫಲಿತಾಂಶ',
      rows: "Component|Genuinely confirmed value\ncritic_update() worked example|V_hat 1.3 -> 1.44 (Part 1)\nTD advantage worked example|delta = +0.6 (Part 1)\ncompute_advantages() 4-step example|advantages [0.0942, 0.0577, 0.0294, 0.01] (Part 2)\nSingle-env actor-critic, 2000 eps|-11.5 -> -6.18, eval -6.0 (Part 2)\nA2C (8 envs), ~2000 eps|-11.75 -> -6.14, eval -6.0 (Part 3)" } },

    { type: 'concept', data: {
      headingEn: 'Why No Replay Buffer Anywhere in This Module', headingKn: 'ಈ Module ನಲ್ಲಿ ಎಲ್ಲಿಯೂ Replay Buffer ಏಕೆ ಇಲ್ಲ',
      bodyEn: '• Every training run genuinely confirmed across this module (single-env AC, A2C) used freshly-sampled trajectories from the current policy, then discarded them immediately after one update -- unlike Module 176\'s DQN, which genuinely relied on a ReplayBuffer to store and randomly resample thousands of past transitions\n• This is the on-policy vs off-policy distinction made concrete: DQN\'s Q-learning target is valid regardless of which policy generated the data (off-policy), but the actor-critic policy-gradient update genuinely computed here is only unbiased for data generated by the CURRENT policy (on-policy) -- reusing old data would require the importance-sampling correction PPO introduces next',
      bodyKn: '• ಈ module ಆದ್ಯಂತ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ ಪ್ರತಿ training run (single-env AC, A2C) ಪ್ರಸ್ತುತ policy ಇಂದ ಹೊಸದಾಗಿ-sample ಮಾಡಿದ trajectories ಬಳಸಿತು, ನಂತರ ಒಂದೂ update ನಂತರ ತಕ್ಷಣ ಅವುಗಳನ್ನೂ ತಿರಸ್ಕರಿಸಿತು -- Module 176 ನ DQN ಗಿಂತ ಭಿನ್ನವಾಗಿ, ಅದೂ ನಿಜವಾಗಿ ಸಾವಿರಾರು ಹಿಂದಿನ transitions ಸಂಗ್ರಹಿಸಲು ಮತ್ತೆ randomly ಮರುsample ಮಾಡಲು ಒಂದೂ ReplayBuffer ಮೇಲೆ ಅವಲಂಬಿಸಿತು\n• ಇದೂ on-policy vs off-policy ವ್ಯತ್ಯಾಸವನ್ನೂ ನಿರ್ದಿಷ್ಟಗೊಳಿಸುತ್ತದೆ: DQN ನ Q-learning target ಯಾವ policy data ಉತ್ಪಾದಿಸಿತೂ ಎಂಬುದೂ ಏನೇ ಇರಲಿ ಮಾನ್ಯ (off-policy), ಆದರೆ ಇಲ್ಲಿ ನಿಜವಾಗಿ ಗಣಿಸಿದ actor-critic policy-gradient update ಕೇವಲ CURRENT policy (on-policy) ಉತ್ಪಾದಿಸಿದ data ಗೆ unbiased -- ಹಳೆಯ data ಮರುಬಳಸಲು PPO ಮುಂದೆ ಪರಿಚಯಿಸುವ importance-sampling correction ಬೇಕಾಗುತ್ತದೆ' } },

    { type: 'heading', data: { textEn: 'A2C vs A3C: Synchronous vs Asynchronous', textKn: 'A2C vs A3C: Synchronous vs Asynchronous', level: 'H2' } },
    { type: 'table', data: {
      captionEn: 'A2C vs A3C', captionKn: 'A2C vs A3C',
      rows: "Property|A2C (genuinely implemented here)|A3C\nWorkers|Parallel environments|Parallel processes/threads\nUpdate|Synchronous (wait for all envs, one batch update)|Asynchronous (each worker updates independently)\nGPU-friendly|Yes -- batch of 8 stacks into one matrix operation|Less -- many small independent updates\nDeterminism|Higher|Lower\nImplementation complexity|Simpler|More complex\nHistorical role|Later, GPU-era simplification|Earlier, demonstrated CPU-parallel deep RL was viable" } },
    { type: 'concept', data: {
      headingEn: 'Why the Genuinely Implemented A2C Loop Is GPU-Friendly', headingKn: 'ನಿಜವಾಗಿ Implement ಮಾಡಿದ A2C Loop GPU-Friendly ಏಕೆ',
      bodyEn: '• In the genuinely implemented train_a2c(), all 8 environments use the identical theta for their rollout in a given batch -- this means their state features could in principle be stacked into a single [8, 16] matrix and passed through one batched forward pass, rather than 8 separate small computations\n• A3C\'s asynchronous workers each hold their own local copy of theta at slightly different points in training, updating a shared parameter set independently -- this genuinely prevents the same clean batching, since there is no single consistent policy snapshot shared across workers at any instant\n• This lesson\'s pure-Python implementation does not use batched matrix operations (each environment\'s rollout and update runs as a separate Python loop), but the algorithmic structure -- N environments sharing one theta, producing one synchronized batch -- is exactly what makes real GPU-accelerated A2C/PPO implementations efficient',
      bodyKn: '• ನಿಜವಾಗಿ implement ಮಾಡಿದ train_a2c() ನಲ್ಲಿ, ಎಲ್ಲಾ 8 environments ಒಂದೂ ಕೊಟ್ಟ batch ನಲ್ಲಿ ಅವುಗಳ rollout ಗೆ ಒಂದೇ theta ಬಳಸುತ್ತವೆ -- ಇದೂ ಅವುಗಳ state features ಅನ್ನೂ ಸಿದ್ಧಾಂತದಲ್ಲಿ ಒಂದೂ single [8, 16] matrix ಗೆ ಜೋಡಿಸಬಹುದು ಮತ್ತೆ ಒಂದೂ batched forward pass ಮೂಲಕ ಹಾದುಹೋಗಬಹುದು, 8 ಪ್ರತ್ಯೇಕ ಚಿಕ್ಕ ಗಣನೆಗಳ ಬದಲು ಎಂದೂ ಅರ್ಥ\n• A3C ನ asynchronous workers ಪ್ರತಿಯೊಂದೂ training ನಲ್ಲಿ ಸ್ವಲ್ಪ ಭಿನ್ನ ಬಿಂದುಗಳಲ್ಲಿ theta ನ ಸ್ವಂತ local copy ಇಟ್ಟುಕೊಳ್ಳುತ್ತದೆ, ಒಂದೂ ಹಂಚಿಕೊಂಡ parameter set ಅನ್ನೂ ಸ್ವತಂತ್ರವಾಗಿ update ಮಾಡುತ್ತಾ -- ಇದೂ ನಿಜವಾಗಿ ಅದೇ ಸ್ವಚ್ಛ batching ತಡೆಯುತ್ತದೆ, ಯಾವುದೇ ಕ್ಷಣದಲ್ಲಿ workers ಆದ್ಯಂತ ಹಂಚಿಕೊಂಡ ಒಂದೂ single consistent policy snapshot ಇಲ್ಲದಿರುವುದರಿಂದ\n• ಈ lesson ನ pure-Python implementation batched matrix operations ಬಳಸುವುದಿಲ್ಲ (ಪ್ರತಿ environment ನ rollout ಮತ್ತೆ update ಒಂದೂ ಪ್ರತ್ಯೇಕ Python loop ಆಗಿ ಚಲಿಸುತ್ತದೆ), ಆದರೆ algorithmic ರಚನೆ -- N environments ಒಂದೂ theta ಹಂಚಿಕೊಳ್ಳುತ್ತಾ, ಒಂದೂ synchronized batch ಉತ್ಪಾದಿಸುತ್ತಾ -- ನಿಜ GPU-accelerated A2C/PPO implementations ಅನ್ನೂ ದಕ್ಷಗೊಳಿಸುವ ನಿಖರ ಏನೋ' } },

    { type: 'concept', data: {
      headingEn: 'The Path Forward: A2C to PPO, IMPALA, SAC, GRPO', headingKn: 'ಮುಂದಿನ ಮಾರ್ಗ: A2C ಇಂದ PPO, IMPALA, SAC, GRPO ಗೆ',
      bodyEn: '• A2C -> PPO (Module 179): both are on-policy actor-critic methods using GAE, but PPO adds a clipped importance-sampling ratio, allowing the same rollout to be reused for multiple gradient-update epochs instead of the single update A2C genuinely performs here -- directly addressing the sample-inefficiency limitation this lesson\'s A2C shares with vanilla REINFORCE\n• A2C -> IMPALA: distributed actors generate experience separately from a central learner, requiring an off-policy correction (V-trace) since the data can become stale by the time it is used\n• A2C -> SAC: moves to off-policy learning with a replay buffer and entropy-regularized objective, trading A2C\'s clean on-policy simplicity for much higher sample efficiency\n• A2C -> GRPO (Module 183): keeps the actor-and-advantage structure but replaces the learned critic V(s) with a group-relative baseline computed from multiple sampled completions -- removing the critic entirely rather than improving it',
      bodyKn: '• A2C -> PPO (Module 179): ಎರಡೂ GAE ಬಳಸುವ on-policy actor-critic methods, ಆದರೆ PPO ಒಂದೂ clipped importance-sampling ratio ಸೇರಿಸುತ್ತದೆ, ಈ lesson ನಿಜವಾಗಿ ಇಲ್ಲಿ ಮಾಡುವ single update ಬದಲು ಅನೇಕ gradient-update epochs ಗೆ ಅದೇ rollout ಮರುಬಳಸಲು ಬಿಡುತ್ತಾ -- ಈ lesson ನ A2C vanilla REINFORCE ಜೊತೆ ಹಂಚಿಕೊಳ್ಳುವ sample-inefficiency ಮಿತಿಯನ್ನೂ ನೇರವಾಗಿ ಪರಿಹರಿಸುತ್ತಾ\n• A2C -> IMPALA: distributed actors ಒಂದೂ ಕೇಂದ್ರ learner ಇಂದ ಪ್ರತ್ಯೇಕವಾಗಿ experience ಉತ್ಪಾದಿಸುತ್ತವೆ, ಒಂದೂ off-policy correction (V-trace) ಬಯಸುತ್ತಾ data ಬಳಸುವ ಹೊತ್ತಿಗೆ stale ಆಗಬಹುದಾದ್ದರಿಂದ\n• A2C -> SAC: ಒಂದೂ replay buffer ಮತ್ತೆ entropy-regularized objective ಜೊತೆ off-policy learning ಗೆ ಚಲಿಸುತ್ತದೆ, A2C ನ ಸ್ವಚ್ಛ on-policy ಸರಳತೆಯನ್ನೂ ಬಹಳ ಹೆಚ್ಚಿನ sample efficiency ಗಾಗಿ ವಿನಿಮಯ ಮಾಡುತ್ತಾ\n• A2C -> GRPO (Module 183): actor-and-advantage ರಚನೆ ಇಟ್ಟುಕೊಳ್ಳುತ್ತದೆ ಆದರೆ ಕಲಿತ critic V(s) ಅನ್ನೂ ಅನೇಕ sampled completions ಇಂದ ಗಣಿಸಿದ ಒಂದೂ group-relative baseline ಜೊತೆ ಬದಲಾಯಿಸುತ್ತದೆ -- ಅದನ್ನೂ ಸುಧಾರಿಸುವ ಬದಲು critic ಅನ್ನೂ ಸಂಪೂರ್ಣವಾಗಿ ತೆಗೆದುಹಾಕುತ್ತಾ' } },

    { type: 'concept', data: {
      headingEn: 'Key Takeaways', headingKn: 'ಮುಖ್ಯ ಅಂಶಗಳು',
      bodyEn: '• Genuinely confirmed: A2C with 8 parallel environments reached the exact -6.0 optimum, matching Part 2\'s single-environment actor-critic, with comparable early-training performance on this particular simple task\n• A2C is synchronous (all environments\' rollouts collected before one batch update) and on-policy (data discarded after use), while A3C is asynchronous (workers update a shared parameter set independently) -- A2C\'s structure is what makes it GPU-batchable, A3C\'s is not\n• A2C\'s on-policy, single-use-per-rollout limitation is exactly what PPO (Module 179) fixes next, by adding a safe way to reuse the same rollout for multiple optimization epochs\n• This module completed the actor-critic family genuinely built from scratch: linear critic (Part 1), GAE-based combined update (Part 2), and parallel-environment A2C (Part 3) -- all three converged to the identical -6.0 optimum established all the way back in Module 172',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: 8 parallel environments ಜೊತೆ A2C ನಿಖರ -6.0 optimum ತಲುಪಿತು, Part 2 ನ single-environment actor-critic ಗೆ ಹೊಂದಿಕೆಯಾಗುತ್ತಾ, ಈ ನಿರ್ದಿಷ್ಟ ಸರಳ task ಮೇಲೆ ಹೋಲಿಸಬಹುದಾದ ಆರಂಭಿಕ-training ಕಾರ್ಯಕ್ಷಮತೆಯೊಂದಿಗೆ\n• A2C synchronous (ಒಂದೂ batch update ಮೊದಲೂ ಎಲ್ಲಾ environments ನ rollouts ಸಂಗ್ರಹಿಸಲಾಗುತ್ತದೆ) ಮತ್ತೆ on-policy (ಬಳಕೆ ನಂತರ data ತಿರಸ್ಕರಿಸಲಾಗುತ್ತದೆ), ಆದರೆ A3C asynchronous (workers ಒಂದೂ ಹಂಚಿಕೊಂಡ parameter set ಅನ್ನೂ ಸ್ವತಂತ್ರವಾಗಿ update ಮಾಡುತ್ತವೆ) -- A2C ನ ರಚನೆ ಅದೂ GPU-batchable ಮಾಡುತ್ತದೆ, A3C ನ ಅಲ್ಲ\n• A2C ನ on-policy, single-use-per-rollout ಮಿತಿ ಮುಂದೆ PPO (Module 179) ಸರಿಪಡಿಸುವ ನಿಖರ ಏನೋ, ಅನೇಕ optimization epochs ಗೆ ಅದೇ rollout ಮರುಬಳಸುವ ಒಂದೂ ಸುರಕ್ಷಿತ ಮಾರ್ಗ ಸೇರಿಸುತ್ತಾ\n• ಈ module ಮೊದಲಿನಿಂದ ನಿಜವಾಗಿ ನಿರ್ಮಿಸಿದ actor-critic family ಪೂರ್ಣಗೊಳಿಸಿತು: linear critic (Part 1), GAE-based combined update (Part 2), ಮತ್ತೆ parallel-environment A2C (Part 3) -- ಎಲ್ಲಾ ಮೂರೂ Module 172 ಗೆ ಎಲ್ಲಾ ದಾರಿಯಲ್ಲೂ ಸ್ಥಾಪಿಸಿದ ಅದೇ -6.0 optimum ಗೆ ಒಮ್ಮುಖವಾದವು' } },
    { type: 'concept', data: {
      headingEn: 'AI Example', headingKn: 'AI Example',
      bodyEn: 'The genuinely implemented A2C pattern here -- N environments sharing one policy, producing one synchronized batch update -- is the same architecture used by OpenAI Baselines\' and Stable-Baselines3\'s A2C implementations, and the same "vectorized environment" concept (VecEnv) that essentially every modern deep RL library provides for exactly this reason: batched, GPU-friendly parallel rollout collection.',
      bodyKn: 'ಇಲ್ಲಿ ನಿಜವಾಗಿ implement ಮಾಡಿದ A2C ಮಾದರಿ -- N environments ಒಂದೂ policy ಹಂಚಿಕೊಳ್ಳುತ್ತಾ, ಒಂದೂ synchronized batch update ಉತ್ಪಾದಿಸುತ್ತಾ -- OpenAI Baselines ಮತ್ತೆ Stable-Baselines3 ನ A2C implementations ಬಳಸುವ ಅದೇ architecture, ಮತ್ತೆ ಬಹುತೇಕ ಪ್ರತಿ ಆಧುನಿಕ deep RL library ಈ ನಿಖರ ಕಾರಣಕ್ಕಾಗಿ ಒದಗಿಸುವ ಅದೇ "vectorized environment" ಆಲೋಚನೆ (VecEnv): batched, GPU-friendly parallel rollout collection.' } },
    { type: 'concept', data: {
      headingEn: 'Why AI Uses This', headingKn: 'AI ಇದನ್ನೂ ಏಕೆ ಬಳಸುತ್ತದೆ',
      bodyEn: '• Genuinely confirmed: A2C\'s synchronous structure (genuinely built here) is what makes it a natural fit for modern GPU hardware, which is optimized for large batched matrix operations rather than many small independent ones -- this is a real, practical reason A2C-family methods dominate over A3C-style asynchronous approaches in current production RL\n• The on-policy nature genuinely confirmed here (data discarded after one use) is a deliberate simplicity/safety tradeoff -- it guarantees the gradient estimate is unbiased with respect to the exact current policy, at the cost of the sample efficiency PPO later recovers',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: A2C ನ synchronous ರಚನೆ (ಇಲ್ಲಿ ನಿಜವಾಗಿ ನಿರ್ಮಿಸಿದ) ಅದೂ ಆಧುನಿಕ GPU hardware ಗೆ ಒಂದೂ ಸ್ವಾಭಾವಿಕ ಹೊಂದಾಣಿಕೆ ಮಾಡುತ್ತದೆ, ಅದೂ ಅನೇಕ ಚಿಕ್ಕ ಸ್ವತಂತ್ರ ಒಂದೂಗಳ ಬದಲು ದೊಡ್ಡ batched matrix operations ಗಾಗಿ optimize ಆಗಿದೆ -- ಪ್ರಸ್ತುತ production RL ನಲ್ಲಿ A2C-family methods A3C-style asynchronous approaches ಗಿಂತ ಪ್ರಬಲವಾಗಿರುವ ಒಂದೂ ನಿಜ, ಪ್ರಾಯೋಗಿಕ ಕಾರಣ\n• ಇಲ್ಲಿ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ on-policy ಸ್ವಭಾವ (ಒಂದೂ ಬಳಕೆ ನಂತರ data ತಿರಸ್ಕರಿಸಲಾಗುತ್ತದೆ) ಒಂದೂ ಉದ್ದೇಶಪೂರ್ವಕ ಸರಳತೆ/safety tradeoff -- ಇದೂ ನಿಖರ ಪ್ರಸ್ತುತ policy ಗೆ ಸಂಬಂಧಿಸಿ gradient estimate unbiased ಎಂದೂ ಖಾತ್ರಿಪಡಿಸುತ್ತದೆ, PPO ನಂತರ ಮರಳಿ ಪಡೆಯುವ sample efficiency ವೆಚ್ಚದಲ್ಲಿ' } },
    { type: 'concept', data: {
      headingEn: 'Real-World Example', headingKn: 'Real-World Example',
      bodyEn: 'A production robotics-simulation team training a policy across thousands of parallel simulated robots on a GPU cluster is running exactly the pattern genuinely built here at a vastly larger scale -- N environments sharing one policy, batched into a single synchronized update, is precisely the architecture that makes modern massively-parallel robot learning (Module 182\'s sim-to-real domain randomization) computationally feasible.',
      bodyKn: 'ಒಂದೂ GPU cluster ಮೇಲೆ ಸಾವಿರಾರು parallel simulated robots ಆದ್ಯಂತ ಒಂದೂ policy train ಮಾಡುವ ಒಂದೂ production robotics-simulation ತಂಡ ಇಲ್ಲಿ ನಿಜವಾಗಿ ನಿರ್ಮಿಸಿದ ಮಾದರಿಯನ್ನೂ ಬಹಳ ದೊಡ್ಡ ಪ್ರಮಾಣದಲ್ಲಿ ಚಲಾಯಿಸುತ್ತಿದೆ -- N environments ಒಂದೂ policy ಹಂಚಿಕೊಳ್ಳುತ್ತಾ, ಒಂದೂ single synchronized update ಗೆ batched, ಆಧುನಿಕ massively-parallel robot learning (Module 182 ನ sim-to-real domain randomization) ಅನ್ನೂ computationally ಕಾರ್ಯಸಾಧ್ಯ ಮಾಡುವ ನಿಖರ architecture.' } },

    { type: 'quiz', data: { questions: [
      { q: 'What is the main difference between A2C and A3C?', qKn: 'A2C ಮತ್ತೆ A3C ನಡುವಿನ ಮುಖ್ಯ ವ್ಯತ್ಯಾಸ ಏನೂ?',
        opts: ['A2C uses no critic', 'A2C performs synchronous updates across parallel environments, while A3C uses asynchronous workers', 'A3C cannot use GAE', 'A2C requires more memory'], correct: 1,
        optsKn: ['A2C ಯಾವುದೇ critic ಬಳಸುವುದಿಲ್ಲ', 'A2C parallel environments ಆದ್ಯಂತ synchronous updates ಮಾಡುತ್ತದೆ, A3C asynchronous workers ಬಳಸುತ್ತದೆ', 'A3C GAE ಬಳಸಲಾಗುವುದಿಲ್ಲ', 'A2C ಗೆ ಹೆಚ್ಚು memory ಬೇಕು'] },
      { q: 'Genuinely confirmed: what greedy-evaluation return did the 8-environment A2C reach?', qKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: 8-environment A2C ಯಾವ greedy-evaluation return ತಲುಪಿತು?',
        opts: ['-11.75, no further improvement', 'Exactly -6.0, matching the single-environment actor-critic', '-58.48', 'It diverged'], correct: 1,
        optsKn: ['-11.75, ಮತ್ತಷ್ಟೂ ಸುಧಾರಣೆ ಇಲ್ಲ', 'ನಿಖರವಾಗಿ -6.0, single-environment actor-critic ಗೆ ಹೊಂದಿಕೆಯಾಗುತ್ತಾ', '-58.48', 'ಅದೂ ಡೈವರ್ಜ್ ಆಯಿತು'] },
      { q: 'Why is A2C\'s synchronous structure more GPU-friendly than A3C\'s asynchronous structure?', qKn: 'A2C ನ synchronous ರಚನೆ A3C ನ asynchronous ರಚನೆಗಿಂತ ಹೆಚ್ಚು GPU-friendly ಏಕೆ?',
        opts: ['GPUs cannot run Python code', 'All environments share one consistent policy snapshot, allowing their computation to be batched into one matrix operation', 'A3C uses more environments', 'A2C does not need a critic'], correct: 1,
        optsKn: ['GPUs Python code ಚಲಾಯಿಸಲಾಗುವುದಿಲ್ಲ', 'ಎಲ್ಲಾ environments ಒಂದೂ ಸ್ಥಿರ policy snapshot ಹಂಚಿಕೊಳ್ಳುತ್ತವೆ, ಅವುಗಳ ಗಣನೆಯನ್ನೂ ಒಂದೂ matrix operation ಗೆ batch ಮಾಡಲು ಬಿಡುತ್ತಾ', 'A3C ಹೆಚ್ಚು environments ಬಳಸುತ್ತದೆ', 'A2C ಗೆ ಒಂದೂ critic ಬೇಕಿಲ್ಲ'] },
      { q: 'What key limitation of A2C does PPO (Module 179) address?', qKn: 'PPO (Module 179) A2C ನ ಯಾವ ಮುಖ್ಯ ಮಿತಿ ಪರಿಹರಿಸುತ್ತದೆ?',
        opts: ['A2C cannot use a critic', 'A2C discards each rollout after a single update; PPO allows safe reuse across multiple epochs', 'A2C only works with one environment', 'A2C cannot compute advantages'], correct: 1,
        optsKn: ['A2C ಒಂದೂ critic ಬಳಸಲಾಗುವುದಿಲ್ಲ', 'A2C ಒಂದೂ single update ನಂತರ ಪ್ರತಿ rollout ತಿರಸ್ಕರಿಸುತ್ತದೆ; PPO ಅನೇಕ epochs ಆದ್ಯಂತ ಸುರಕ್ಷಿತ ಮರುಬಳಕೆ ಬಿಡುತ್ತದೆ', 'A2C ಕೇವಲ ಒಂದೂ environment ಜೊತೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ', 'A2C advantages ಗಣಿಸಲಾಗುವುದಿಲ್ಲ'] },
      { q: 'Genuinely confirmed: on this simple GridWorld, did 8 parallel environments dramatically improve sample efficiency compared to a single environment?', qKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: ಈ ಸರಳ GridWorld ಮೇಲೆ, 8 parallel environments ಒಂದೂ single environment ಗೆ ಹೋಲಿಸಿ sample efficiency ಅನ್ನೂ ನಾಟಕೀಯವಾಗಿ ಸುಧಾರಿಸಿತೇ?',
        opts: ['Yes, dramatically, by 100x', 'No -- early performance was comparable (-11.75 vs -11.5), honestly reported rather than exaggerated', 'A2C performed much worse', 'A2C failed to run'], correct: 1,
        optsKn: ['ಹೌದೂ, ನಾಟಕೀಯವಾಗಿ, 100x ರಷ್ಟೂ', 'ಇಲ್ಲ -- ಆರಂಭಿಕ ಕಾರ್ಯಕ್ಷಮತೆ ಹೋಲಿಸಬಹುದಾಗಿತ್ತು (-11.75 vs -11.5), ಉತ್ಪ್ರೇಕ್ಷಿಸುವ ಬದಲು ಪ್ರಾಮಾಣಿಕವಾಗಿ ವರದಿ ಮಾಡಲಾಗಿದೆ', 'A2C ಬಹಳ ಕೆಟ್ಟದಾಗಿ ಕಾರ್ಯನಿರ್ವಹಿಸಿತು', 'A2C ಚಲಾಯಿಸಲು ವಿಫಲವಾಯಿತು'] },
    ] } },
  ],
};
