const phaseId = '6a369d5466020ed05b3212da';
const moduleId = '6a369d5566020ed05b321325'; // Module 119: Entity Linking and Disambiguation

module.exports = {
  phaseId,
  moduleId,
  order: 2,
  type: 'reading',
  duration: 55,
  difficulty: 'advanced',
  status: 'published',
  title: 'Entity Linking & Disambiguation Part 2: Context-Based Disambiguation, Embedding Models, Evaluation, and Production Systems',
  titleKn: 'Entity Linking & Disambiguation Part 2: Context-Based Disambiguation, Embedding Models, Evaluation, ಮತ್ತು Production Systems',
  desc: 'Lexical (Jaccard) and embedding-based (BLINK-style) disambiguation, AIDA-CoNLL evaluation, and production pitfalls -- verified with real, genuinely-executed code: a Jaccard-similarity disambiguator that correctly chose Apple Inc. vs. the fruit based on context, and a real sentence-transformer BLINK-style embedding that correctly ranked Apple Inc. above the fruit by cosine similarity.',
  objectives: [
    'Understand context-based disambiguation using lexical overlap.',
    'Understand BLINK-style embedding-based entity linking.',
    'Understand generative entity linking with structured prompts.',
    'Know the AIDA-CoNLL benchmark and its two metrics: In-KB Accuracy (P@1) and NIL Detection Rate.',
    'Know the common pitfalls: NIL handling, mention boundary errors, popularity bias, cross-lingual linking, and knowledge base staleness.',
    'Run and verify real lexical and embedding-based disambiguation code.',
  ],
  objectivesKn: [
    'Lexical overlap ಬಳಸಿ context-based disambiguation ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'BLINK-ಶೈಲಿಯ embedding-ಆಧಾರಿತ entity linking ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'Structured prompts ಜೊತೆ generative entity linking ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'AIDA-CoNLL benchmark ಮತ್ತು ಇದರ ಎರಡು metrics ಗಳನ್ನೂ ತಿಳಿಯಿರಿ: In-KB Accuracy (P@1) ಮತ್ತು NIL Detection Rate.',
    'ಸಾಮಾನ್ಯ ಬಲೆಗಳನ್ನೂ ತಿಳಿಯಿರಿ: NIL handling, mention boundary errors, popularity bias, cross-lingual linking, ಮತ್ತು knowledge base staleness.',
    'ನಿಜ lexical ಮತ್ತು embedding-ಆಧಾರಿತ disambiguation code ಚಲಾಯಿಸಿ ಮತ್ತು ಪರಿಶೀಲಿಸಿ.',
  ],
  blocks: [
    { type: 'heading', data: { level: 'H1', textEn: 'Entity Linking & Disambiguation (Part 2)', textKn: 'Entity Linking & Disambiguation (Part 2)' } },
    { type: 'concept', data: {
      headingEn: 'Learning Objectives', headingKn: 'ಕಲಿಕಾ ಗುರಿಗಳು',
      bodyEn: '• Part 1 covered candidate generation and the three disambiguation approaches conceptually. Part 2 makes two of them concrete and genuinely executable: lexical (Jaccard) disambiguation and BLINK-style embedding disambiguation, both run on the lesson\'s own "Apple" (company vs. fruit) example.\n• Every genuinely runnable piece of code in this lesson was actually executed, including a real disambiguate() run and a real sentence-transformer-based embedding comparison -- both correctly resolving "Apple" differently depending on context.',
      bodyKn: '• Part 1 candidate generation ಮತ್ತು ಮೂರು disambiguation ವಿಧಾನಗಳನ್ನೂ ಪರಿಕಲ್ಪನಾತ್ಮಕವಾಗಿ ಒಳಗೊಂಡಿತ್ತು. Part 2 ಅವುಗಳಲ್ಲಿ ಎರಡನ್ನೂ ಕಾಂಕ್ರೀಟ್ ಮತ್ತು ನಿಜವಾಗಿ ಚಲಾಯಿಸಬಹುದಾಗಿಸುತ್ತದೆ: lexical (Jaccard) disambiguation ಮತ್ತು BLINK-ಶೈಲಿಯ embedding disambiguation, ಎರಡೂ ಲೆಸನ್‌ನ ಸ್ವಂತ "Apple" (ಕಂಪನಿ vs. ಹಣ್ಣು) ಉದಾಹರಣೆಯ ಮೇಲೆ ಚಲಾಯಿಸಲಾಗಿದೆ.\n• ಈ lesson ನಲ್ಲಿ ನಿಜವಾಗಿ ಚಲಾಯಿಸಬಹುದಾದ ಪ್ರತಿ code ನಿಜವಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ, ಒಂದು ನಿಜ disambiguate() run ಮತ್ತು ಒಂದು ನಿಜ sentence-transformer-ಆಧಾರಿತ embedding ಹೋಲಿಕೆ ಸೇರಿ -- ಎರಡೂ context ಮೇಲೆ ಅವಲಂಬಿಸಿ "Apple" ಅನ್ನೂ ಸರಿಯಾಗಿ ಬೇರೆಯಾಗಿ ಪರಿಹರಿಸುತ್ತಾ.' } },

    { type: 'heading', data: { level: 'H2', textEn: 'Step 2 — Context-Based Disambiguation', textKn: 'Step 2 — Context-Based Disambiguation' } },
    { type: 'code', data: {
      filename: 'context_disambiguation.py',
      headingEn: 'Original Code — Context-Based Disambiguation (Genuinely Executed)', headingKn: 'Original Code — Context-Based Disambiguation (ನಿಜವಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ)',
      descEn: 'The lesson\'s exact disambiguate() function, actually run on the lesson\'s own two "apple" examples -- one in a technology context, one in a fruit context.',
      descKn: 'ಲೆಸನ್‌ನ ನಿಖರ disambiguate() ಫಂಕ್ಷನ್, ಲೆಸನ್‌ನ ಸ್ವಂತ ಎರಡು "apple" ಉದಾಹರಣೆಗಳ ಮೇಲೆ ನಿಜವಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ -- ಒಂದು ತಂತ್ರಜ್ಞಾನ context ನಲ್ಲಿ, ಒಂದು ಹಣ್ಣಿನ context ನಲ್ಲಿ.',
      code: "def disambiguate(mention, context, alias_index, entity_desc):\n    candidates = alias_index.get(mention.lower(), [])\n    if not candidates:\n        return None, 0.0\n    context_words = set(tokenize(context))\n    best, best_score = None, -1\n    for entity_id in candidates:\n        desc_words = set(tokenize(entity_desc[entity_id]))\n        union = len(context_words | desc_words)\n        score = len(context_words & desc_words) / union if union else 0.0\n        if score > best_score:\n            best, best_score = entity_id, score\n    return best, best_score\n\nentity_desc = {\n    \"Q312 (Apple Inc.)\": \"Apple Inc. is an American technology company that designs and sells the iPhone and other consumer electronics.\",\n    \"Q89 (apple, fruit)\": \"An apple is a round fruit that grows on a tree and is often eaten raw or used in cooking.\",\n}\n\nctx1 = \"Apple released a new iPhone yesterday.\"\nprint(disambiguate(\"apple\", ctx1, alias_to_entities, entity_desc))\n\nctx2 = \"She picked an apple from the tree in the orchard.\"\nprint(disambiguate(\"apple\", ctx2, alias_to_entities, entity_desc))" } },
    { type: 'output', data: { output: "('Q312 (Apple Inc.)', 0.1)\n('Q89 (apple, fruit)', 0.17391304347826086)" } },

    { type: 'concept', data: {
      headingEn: 'Reading the Verified Output', headingKn: 'ಪರಿಶೀಲಿಸಿದ Output ಓದುವುದು',
      bodyEn: '• "Apple released a new iPhone yesterday." correctly resolved to Q312 (Apple Inc.) -- the tokens "iphone" and "released" overlap with the company description\'s "iphone" and "electronics" vocabulary. "She picked an apple from the tree in the orchard." correctly resolved to Q89 (apple, fruit) -- "tree" overlaps with the fruit description. The exact same mention, "apple," genuinely resolved to two different entities purely because of a simple word-overlap score against each candidate\'s description -- no embeddings, no neural network, just set intersection over union.\n• Notice how low both scores are (0.1 and 0.17) -- Jaccard similarity on short contexts rarely produces high absolute scores, but the relative comparison between candidates is what disambiguate() actually uses to decide, and that relative comparison was correct in both real runs.',
      bodyKn: '• "Apple released a new iPhone yesterday." Q312 (Apple Inc.) ಗೆ ಸರಿಯಾಗಿ ಪರಿಹರಿಸಲ್ಪಟ್ಟಿತು -- "iphone" ಮತ್ತು "released" tokens ಗಳು ಕಂಪನಿ ವಿವರಣೆಯ "iphone" ಮತ್ತು "electronics" ಶಬ್ದಕೋಶದೊಂದಿಗೆ overlap ಆಗುತ್ತವೆ. "She picked an apple from the tree in the orchard." Q89 (apple, fruit) ಗೆ ಸರಿಯಾಗಿ ಪರಿಹರಿಸಲ್ಪಟ್ಟಿತು -- "tree" ಹಣ್ಣಿನ ವಿವರಣೆಯೊಂದಿಗೆ overlap ಆಗುತ್ತದೆ. ನಿಖರ ಒಂದೇ mention, "apple," ಕೇವಲ ಪ್ರತಿ ಅಭ್ಯರ್ಥಿಯ ವಿವರಣೆಯ ವಿರುದ್ಧ ಒಂದು ಸರಳ ಪದ-overlap ಸ್ಕೋರ್ ಕಾರಣ ನಿಜವಾಗಿ ಎರಡು ಬೇರೆ entities ಗಳಿಗೆ ಪರಿಹರಿಸಲ್ಪಟ್ಟಿತು -- ಯಾವುದೇ embeddings ಇಲ್ಲ, ಯಾವುದೇ neural network ಇಲ್ಲ, ಕೇವಲ set intersection over union.\n• ಎರಡೂ ಸ್ಕೋರ್‌ಗಳು ಎಷ್ಟು ಕಡಿಮೆ ಇವೆ ಎಂದು ಗಮನಿಸಿ (0.1 ಮತ್ತು 0.17) -- ಚಿಕ್ಕ contexts ಗಳ ಮೇಲೆ Jaccard ಹೋಲಿಕೆ ವಿರಳವಾಗಿ ಹೆಚ್ಚಿನ ಸಂಪೂರ್ಣ ಸ್ಕೋರ್‌ಗಳನ್ನೂ ಉತ್ಪಾದಿಸುತ್ತದೆ, ಆದರೆ ಅಭ್ಯರ್ಥಿಗಳ ನಡುವಿನ ಸಾಪೇಕ್ಷ ಹೋಲಿಕೆಯೇ disambiguate() ನಿಜವಾಗಿ ನಿರ್ಧರಿಸಲು ಬಳಸುತ್ತದೆ, ಮತ್ತು ಆ ಸಾಪೇಕ್ಷ ಹೋಲಿಕೆ ಎರಡೂ ನಿಜ runs ಗಳಲ್ಲಿ ಸರಿಯಾಗಿತ್ತು.' } },

    { type: 'heading', data: { level: 'H2', textEn: 'Embedding-Based Entity Linking', textKn: 'Embedding-ಆಧಾರಿತ Entity Linking' } },
    { type: 'code', data: {
      filename: 'blink_style_embedding.py',
      headingEn: 'Original Code — BLINK-Style Embedding Disambiguation (Genuinely Executed)', headingKn: 'Original Code — BLINK-Style Embedding Disambiguation (ನಿಜವಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ)',
      descEn: 'The lesson\'s exact embed_mention() and embed_entity() functions, actually run using a real sentence-transformers/all-MiniLM-L6-v2 encoder on the same "Apple released a new iPhone yesterday." example.',
      descKn: 'ಲೆಸನ್‌ನ ನಿಖರ embed_mention() ಮತ್ತು embed_entity() ಫಂಕ್ಷನ್‌ಗಳು, ಅದೇ "Apple released a new iPhone yesterday." ಉದಾಹರಣೆಯ ಮೇಲೆ ಒಂದು ನಿಜ sentence-transformers/all-MiniLM-L6-v2 encoder ಬಳಸಿ ನಿಜವಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ.',
      code: "from sentence_transformers import SentenceTransformer\nencoder = SentenceTransformer(\"sentence-transformers/all-MiniLM-L6-v2\")\n\ndef embed_mention(text, mention_span):\n    start, end = mention_span\n    marked = f\"{text[:start]} [MENTION] {text[start:end]} [/MENTION] {text[end:]}\"\n    return encoder.encode([marked], normalize_embeddings=True)[0]\n\ndef embed_entity(entity_id, description):\n    return encoder.encode([f\"{entity_id}: {description}\"], normalize_embeddings=True)[0]\n\ntext = \"Apple released a new iPhone yesterday.\"\nm_emb = embed_mention(text, (0, 5))  # \"Apple\"\n\ncandidates = {\n    \"Q312 (Apple Inc.)\": \"An American technology company that designs and sells consumer electronics.\",\n    \"Q89 (apple, fruit)\": \"A round fruit that grows on a tree and is often eaten raw.\",\n}\nfor eid, desc in candidates.items():\n    e_emb = embed_entity(eid, desc)\n    print(f\"{eid}: cosine={float(m_emb @ e_emb):.4f}\")" } },
    { type: 'output', data: { output: "Q312 (Apple Inc.): cosine=0.3775\nQ89 (apple, fruit): cosine=0.2271" } },

    { type: 'concept', data: {
      headingEn: 'Reading the Verified Output', headingKn: 'ಪರಿಶೀಲಿಸಿದ Output ಓದುವುದು',
      bodyEn: '• The embedding-based approach agreed with the Jaccard approach on this example: Q312 (Apple Inc.) scored a clearly higher cosine similarity (0.378) than Q89 (apple, fruit) (0.227) against the marked mention "[MENTION] Apple [/MENTION]" in its iPhone-related sentence. Unlike the lexical approach, this used no explicit word overlap at all -- the [MENTION]/[/MENTION] markers let a real Transformer encoder capture the surrounding semantic context and produce a single dense vector, which was then compared against dense vectors of each candidate\'s description.\n• The genuine agreement between two structurally very different methods (bag-of-words Jaccard vs. neural embeddings) on the same example is itself a small but real piece of evidence that the underlying signal ("iPhone" context implies the company) is genuinely present in the text, not an artifact of either specific algorithm.',
      bodyKn: '• Embedding-ಆಧಾರಿತ ವಿಧಾನ ಈ ಉದಾಹರಣೆಯಲ್ಲಿ Jaccard ವಿಧಾನದ ಜೊತೆ ಒಪ್ಪಿತು: Q312 (Apple Inc.) ಇದರ iPhone-ಸಂಬಂಧಿತ ವಾಕ್ಯದಲ್ಲಿ ಗುರುತಿಸಿದ mention "[MENTION] Apple [/MENTION]" ವಿರುದ್ಧ Q89 (apple, fruit) (0.227) ಗಿಂತ ಸ್ಪಷ್ಟವಾಗಿ ಹೆಚ್ಚಿನ cosine ಹೋಲಿಕೆ (0.378) ಸ್ಕೋರ್ ಮಾಡಿತು. Lexical ವಿಧಾನಕ್ಕಿಂತ ಭಿನ್ನವಾಗಿ, ಇದೂ ಯಾವುದೇ ಸ್ಪಷ್ಟ ಪದ overlap ಬಳಸಲಿಲ್ಲ -- [MENTION]/[/MENTION] markers ಗಳು ಒಂದು ನಿಜ Transformer encoder ಗೆ ಸುತ್ತಮುತ್ತಲ semantic context ಸೆರೆಹಿಡಿಯಲು ಮತ್ತು ಒಂದು ಒಂಟಿ dense ವೆಕ್ಟರ್ ಉತ್ಪಾದಿಸಲು ಅನುಮತಿಸಿದವು, ಇದನ್ನೂ ನಂತರ ಪ್ರತಿ ಅಭ್ಯರ್ಥಿಯ ವಿವರಣೆಯ dense ವೆಕ್ಟರ್‌ಗಳ ವಿರುದ್ಧ ಹೋಲಿಸಲಾಗಿದೆ.\n• ಎರಡು structurally ಬಹಳ ಬೇರೆ ವಿಧಾನಗಳ (bag-of-words Jaccard vs. neural embeddings) ಅದೇ ಉದಾಹರಣೆಯ ಮೇಲಿನ ನಿಜ ಒಪ್ಪಂದ ಸ್ವತಃ underlying signal ("iPhone" context ಕಂಪನಿಯನ್ನೂ ಸೂಚಿಸುತ್ತದೆ) ಪಠ್ಯದಲ್ಲಿ ನಿಜವಾಗಿ ಇರುತ್ತದೆ, ಯಾವುದೇ ನಿರ್ದಿಷ್ಟ algorithm ನ ಒಂದು artifact ಅಲ್ಲ ಎಂಬುದಕ್ಕೆ ಒಂದು ಸಣ್ಣ ಆದರೆ ನಿಜ ಪುರಾವೆ.' } },

    { type: 'heading', data: { level: 'H2', textEn: 'Generative Entity Linking', textKn: 'Generative Entity Linking' } },
    { type: 'code', data: {
      filename: 'generative_el_prompt.py',
      headingEn: 'Original Code — Generative Entity Linking (Not Executed: Requires a Live LLM)', headingKn: 'Original Code — Generative Entity Linking (ಚಲಾಯಿಸಿಲ್ಲ: ಒಂದು Live LLM ಅಗತ್ಯ)',
      descEn: 'Presented exactly as written. Sending this prompt to a real model requires a live LLM API call not available in this environment.',
      descKn: 'ಬರೆದಂತೆ ನಿಖರವಾಗಿ ಪ್ರಸ್ತುತಪಡಿಸಲಾಗಿದೆ. ಈ prompt ಅನ್ನೂ ಒಂದು ನಿಜ model ಗೆ ಕಳುಹಿಸಲು ಈ environment ನಲ್ಲಿ ಲಭ್ಯವಿಲ್ಲದ ಒಂದು live LLM API ಕರೆ ಅಗತ್ಯ.',
      code: "prompt = f\"\"\"Text: {text}\nMention: {mention}\nList the best Wikipedia title for this mention.\nRespond with JSON: {{\"title\": \"...\"}}\"\"\"" } },
    { type: 'concept', data: {
      headingEn: 'Why Constraints Matter Here Too', headingKn: 'ಇಲ್ಲಿಯೂ ನಿರ್ಬಂಧಗಳು ಏಕೆ ಮುಖ್ಯ',
      bodyEn: '• When combined with constrained decoding or a whitelist of valid titles (the same logit-masking principle verified directly in the Structured Outputs lessons), this becomes a practical entity-linking solution -- the LLM proposes a title, but the system only accepts it if it matches a real knowledge-base entity, preventing the model from inventing a plausible-sounding but nonexistent entity.',
      bodyKn: '• Constrained decoding ಅಥವಾ ಮಾನ್ಯ titles ಗಳ ಒಂದು whitelist ಜೊತೆ ಸಂಯೋಜಿಸಿದಾಗ (Structured Outputs lessons ಗಳಲ್ಲಿ ನೇರವಾಗಿ ಪರಿಶೀಲಿಸಿದ ಅದೇ logit-masking ತತ್ವ), ಇದೂ ಒಂದು ಪ್ರಾಯೋಗಿಕ entity-linking ಪರಿಹಾರವಾಗುತ್ತದೆ -- LLM ಒಂದು title ಪ್ರಸ್ತಾಪಿಸುತ್ತದೆ, ಆದರೆ system ಇದೂ ಒಂದು ನಿಜ knowledge-base entity ಗೆ ಹೊಂದಿದರೆ ಮಾತ್ರ ಒಪ್ಪಿಕೊಳ್ಳುತ್ತದೆ, model ಒಂದು ಸಮಂಜಸ-ಧ್ವನಿಸುವ ಆದರೆ ಅಸ್ತಿತ್ವದಲ್ಲಿಲ್ಲದ entity ಕಟ್ಟುವುದನ್ನೂ ತಡೆಯುತ್ತಾ.' } },

    { type: 'heading', data: { level: 'H2', textEn: 'Evaluation: AIDA-CoNLL', textKn: 'Evaluation: AIDA-CoNLL' } },
    { type: 'table', data: { captionEn: 'AIDA-CoNLL Benchmark Metrics', captionKn: 'AIDA-CoNLL Benchmark Metrics',
      rows: 'Metric|What It Measures\nIn-KB Accuracy (P@1)|How often the top predicted entity is correct, for mentions that do exist in the knowledge base\nNIL Detection Rate|How accurately the system identifies mentions that do NOT exist in the knowledge base, rather than forcing a wrong match' } },

    { type: 'heading', data: { level: 'H2', textEn: 'Common Pitfalls', textKn: 'ಸಾಮಾನ್ಯ ಬಲೆಗಳು' } },
    { type: 'table', data: { captionEn: 'Five Real Production Entity Linking Pitfalls', captionKn: 'ಐದು ನಿಜ Production Entity Linking ಬಲೆಗಳು',
      rows: 'Pitfall|Problem\n1. NIL Handling|Not every mention exists in the KB (e.g. a newly founded startup) -- guessing an unrelated entity is worse than correctly predicting NIL\n2. Mention Boundary Errors|If NER incorrectly detects "Bank" instead of "Bank of America," entity linking now searches for the wrong, shorter mention -- poor NER directly reduces EL performance\n3. Popularity Bias|Frequently mentioned entities dominate predictions -- in an ML paper, "Michael Jordan" may be wrongly linked to the basketball player instead of the professor\n4. Cross-Lingual Entity Linking|Chinese "巴黎" must link to the same "Paris, France" entity -- requires multilingual embeddings or translation\n5. Knowledge Base Staleness|New companies, public figures, and events may not exist in last year\'s KB dump -- production systems must refresh regularly' } },

    { type: 'heading', data: { level: 'H2', textEn: 'Choosing the Right System', textKn: 'ಸರಿಯಾದ System ಆಯ್ಕೆ ಮಾಡುವುದು' } },
    { type: 'table', data: { captionEn: 'Situation -> Recommended Solution', captionKn: 'Situation -> ಶಿಫಾರಸು ಮಾಡಿದ Solution',
      rows: 'Situation|Recommended Solution\nGeneral English + Wikipedia|BLINK or REL\nCross-lingual Wikipedia|mGENRE\nFew mentions/day with LLMs|GPT/Claude + candidate list + constrained JSON\nDomain-specific knowledge base|Custom BERT + retrieval + fine-tuning\nUltra-low latency|Prior-based exact-match baseline\nResearch|GENRE, ExtEnD, or generative LLM-based EL' } },

    { type: 'heading', data: { level: 'H2', textEn: 'Production Pipeline (2026)', textKn: 'Production Pipeline (2026)' } },
    { type: 'diagram', data: {
      svgCode: "<svg viewBox=\"0 0 260 220\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"monospace\" font-size=\"6.8\">\n  <rect width=\"260\" height=\"220\" rx=\"8\" fill=\"#0f172a\"/>\n  <text x=\"130\" y=\"14\" fill=\"#94a3b8\" text-anchor=\"middle\" font-size=\"8.5\">2026 Document Understanding Pipeline</text>\n  <rect x=\"55\" y=\"24\" width=\"150\" height=\"16\" rx=\"3\" fill=\"#1e293b\" stroke=\"#94a3b8\"/><text x=\"130\" y=\"35\" fill=\"#cbd5e1\" text-anchor=\"middle\" font-size=\"5.5\">Raw Document</text>\n  <rect x=\"55\" y=\"48\" width=\"150\" height=\"16\" rx=\"3\" fill=\"#1e293b\" stroke=\"#60a5fa\"/><text x=\"130\" y=\"59\" fill=\"#93c5fd\" text-anchor=\"middle\" font-size=\"5.5\">NER</text>\n  <rect x=\"55\" y=\"72\" width=\"150\" height=\"16\" rx=\"3\" fill=\"#1e1b4b\" stroke=\"#a78bfa\"/><text x=\"130\" y=\"83\" fill=\"#c4b5fd\" text-anchor=\"middle\" font-size=\"5.5\">Coreference Resolution</text>\n  <rect x=\"55\" y=\"96\" width=\"150\" height=\"16\" rx=\"3\" fill=\"#022c22\" stroke=\"#34d399\"/><text x=\"130\" y=\"107\" fill=\"#6ee7b7\" text-anchor=\"middle\" font-size=\"5.5\">Entity Linking</text>\n  <rect x=\"55\" y=\"120\" width=\"150\" height=\"16\" rx=\"3\" fill=\"#292524\" stroke=\"#f59e0b\"/><text x=\"130\" y=\"131\" fill=\"#fde68a\" text-anchor=\"middle\" font-size=\"5.5\">Knowledge Base IDs</text>\n  <rect x=\"55\" y=\"144\" width=\"150\" height=\"16\" rx=\"3\" fill=\"#1e293b\" stroke=\"#94a3b8\"/><text x=\"130\" y=\"155\" fill=\"#cbd5e1\" text-anchor=\"middle\" font-size=\"5.5\">Merge Coref Clusters</text>\n  <rect x=\"55\" y=\"168\" width=\"150\" height=\"16\" rx=\"3\" fill=\"#1e293b\" stroke=\"#94a3b8\"/><text x=\"130\" y=\"179\" fill=\"#cbd5e1\" text-anchor=\"middle\" font-size=\"5.5\">KG / QA / Search</text>\n  <g stroke=\"#64748b\" stroke-width=\"1\"><line x1=\"130\" y1=\"40\" x2=\"130\" y2=\"48\"/><line x1=\"130\" y1=\"64\" x2=\"130\" y2=\"72\"/><line x1=\"130\" y1=\"88\" x2=\"130\" y2=\"96\"/><line x1=\"130\" y1=\"112\" x2=\"130\" y2=\"120\"/><line x1=\"130\" y1=\"136\" x2=\"130\" y2=\"144\"/><line x1=\"130\" y1=\"160\" x2=\"130\" y2=\"168\"/></g>\n</svg>",
      headingEn: 'NER -> Coreference -> Entity Linking -> Canonical IDs', headingKn: 'NER -> Coreference -> Entity Linking -> Canonical IDs',
      captionEn: 'The 2026 pattern chains this module\'s lesson with the previous one: detect entities (NER), resolve references (coreference), link each mention to a knowledge-base entity, then merge all mentions into one canonical representation.',
      captionKn: '2026 ಮಾದರಿ ಈ module ನ lesson ಅನ್ನೂ ಹಿಂದಿನದರ ಜೊತೆ ಸರಪಳಿ ಮಾಡುತ್ತದೆ: entities ಗಳನ್ನೂ ಪತ್ತೆಹಚ್ಚಿ (NER), ಉಲ್ಲೇಖಗಳನ್ನೂ ಪರಿಹರಿಸಿ (coreference), ಪ್ರತಿ mention ಅನ್ನೂ ಒಂದು knowledge-base entity ಗೆ ಸಂಪರ್ಕಿಸಿ, ನಂತರ ಎಲ್ಲಾ mentions ಗಳನ್ನೂ ಒಂದು canonical ಪ್ರತಿನಿಧಿತ್ವಕ್ಕೆ ವಿಲೀನಗೊಳಿಸಿ.' } },

    { type: 'concept', data: {
      headingEn: 'Why AI Uses It', headingKn: 'AI ಇದನ್ನು ಏಕೆ ಬಳಸುತ್ತದೆ',
      bodyEn: '• The verified agreement between the lexical disambiguate() (0.1 vs 0.174) and the embedding-based BLINK-style approach (0.378 vs 0.227) -- both correctly favoring Apple Inc. in an iPhone context -- is why production teams often deploy the cheap lexical method as a fast first pass and the more expensive embedding method as a stronger fallback or reranker: when they agree, that\'s a strong, corroborated signal; when they disagree, it is exactly the ambiguous case that deserves an LLM or human review.\n• The Popularity Bias pitfall (Michael Jordan the basketball player dominating over the ML professor) is a direct, real consequence of exactly the kind of alias index verified in Part 1: if a knowledge base\'s aliases and priors are built from general web text, they inherit the web\'s topic distribution, silently disadvantaging any domain (like ML research) that is less represented in that training data -- which is why domain-specific entity linking systems exist at all.\n• NIL Detection Rate matters because the alternative -- forcing every mention to link to some existing entity even when the true entity does not exist in the knowledge base yet -- creates exactly the same kind of confidently-wrong output problem this course has repeatedly verified in other contexts (hallucinated NLI claims, fabricated RAG answers): a system that can say "I don\'t know this entity" is more trustworthy than one that always guesses.',
      bodyKn: '• Lexical disambiguate() (0.1 vs 0.174) ಮತ್ತು embedding-ಆಧಾರಿತ BLINK-ಶೈಲಿಯ ವಿಧಾನದ (0.378 vs 0.227) ನಡುವಿನ ಪರಿಶೀಲಿಸಿದ ಒಪ್ಪಂದ -- ಎರಡೂ ಒಂದು iPhone context ನಲ್ಲಿ Apple Inc. ಅನ್ನೂ ಸರಿಯಾಗಿ ಆದ್ಯತೆ ನೀಡುತ್ತಾ -- production ತಂಡಗಳು ಆಗಾಗ್ಗೆ ಅಗ್ಗದ lexical ವಿಧಾನವನ್ನೂ ಒಂದು ವೇಗದ ಮೊದಲ ಪಾಸ್ ಆಗಿ ಮತ್ತು ಹೆಚ್ಚು ದುಬಾರಿ embedding ವಿಧಾನವನ್ನೂ ಒಂದು ಬಲಿಷ್ಠ fallback ಅಥವಾ reranker ಆಗಿ ಏಕೆ deploy ಮಾಡುತ್ತವೆ ಎಂಬುದಕ್ಕೆ ಕಾರಣ: ಅವು ಒಪ್ಪಿದಾಗ, ಅದೂ ಒಂದು ಬಲವಾದ, ದೃಢಪಡಿಸಿದ ಸಂಕೇತ; ಅವು ಒಪ್ಪದಿದ್ದಾಗ, ಅದೂ ನಿಖರವಾಗಿ ಒಂದು LLM ಅಥವಾ ಮಾನವ ಪರಿಶೀಲನೆ ಅರ್ಹಿಸುವ ಅಸ್ಪಷ್ಟ ಪ್ರಕರಣ.\n• Popularity Bias ಬಲೆ (ML ಪ್ರೊಫೆಸರ್ ಮೇಲೆ ಪ್ರಾಬಲ್ಯ ಸಾಧಿಸುವ ಬ್ಯಾಸ್ಕೆಟ್‌ಬಾಲ್ ಆಟಗಾರ Michael Jordan) Part 1 ರಲ್ಲಿ ಪರಿಶೀಲಿಸಿದ ನಿಖರ ಬಗೆಯ alias index ನ ಒಂದು ನೇರ, ನಿಜ ಪರಿಣಾಮ: ಒಂದು knowledge base ನ aliases ಮತ್ತು priors ಗಳನ್ನೂ ಸಾಮಾನ್ಯ web ಪಠ್ಯದಿಂದ ನಿರ್ಮಿಸಿದರೆ, ಅವು web ನ ವಿಷಯ ವಿತರಣೆಯನ್ನೂ ಆನುವಂಶಿಕವಾಗಿ ಪಡೆಯುತ್ತವೆ, ಆ ತರಬೇತಿ ಡೇಟಾದಲ್ಲಿ ಕಡಿಮೆ ಪ್ರತಿನಿಧಿಸಿದ ಯಾವುದೇ ಡೊಮೈನ್ ಅನ್ನೂ (ML ಸಂಶೋಧನೆಯಂತೆ) ಮೌನವಾಗಿ ಅನಾನುಕೂಲಗೊಳಿಸುತ್ತಾ -- ಇದೇ ಕಾರಣಕ್ಕಾಗಿ ಡೊಮೈನ್-ನಿರ್ದಿಷ್ಟ entity linking systems ಗಳು ಸಂಪೂರ್ಣವಾಗಿ ಅಸ್ತಿತ್ವದಲ್ಲಿವೆ.\n• NIL Detection Rate ಮುಖ್ಯ ಏಕೆಂದರೆ ಪರ್ಯಾಯ -- ನಿಜ entity ಇನ್ನೂ knowledge base ನಲ್ಲಿ ಅಸ್ತಿತ್ವದಲ್ಲಿಲ್ಲದಿದ್ದಾಗಲೂ ಪ್ರತಿ mention ಅನ್ನೂ ಕೆಲವು ಅಸ್ತಿತ್ವದಲ್ಲಿರುವ entity ಗೆ ಬಲವಂತಪಡಿಸುವುದು -- ಈ ಕೋರ್ಸ್ ಇತರ ಸಂದರ್ಭಗಳಲ್ಲಿ (ಕಟ್ಟಲ್ಪಟ್ಟ NLI ಹಕ್ಕುಗಳು, ಕಟ್ಟಲ್ಪಟ್ಟ RAG ಉತ್ತರಗಳು) ಪದೇ ಪದೇ ಪರಿಶೀಲಿಸಿದ ಅದೇ ಬಗೆಯ ಆತ್ಮವಿಶ್ವಾಸಪೂರ್ಣ-ತಪ್ಪಾದ output ಸಮಸ್ಯೆ ಸೃಷ್ಟಿಸುತ್ತದೆ: "ನನಗೆ ಈ entity ಗೊತ್ತಿಲ್ಲ" ಎಂದು ಹೇಳಬಲ್ಲ ಒಂದು system ಯಾವಾಗಲೂ ಊಹಿಸುವ ಒಂದಕ್ಕಿಂತ ಹೆಚ್ಚು ವಿಶ್ವಾಸಾರ್ಹ.' } },

    { type: 'concept', data: {
      headingEn: 'Key Takeaways', headingKn: 'ಮುಖ್ಯ ಅಂಶಗಳು',
      bodyEn: '• Context-based lexical disambiguation (Jaccard similarity) correctly distinguished Apple Inc. from the fruit based purely on word overlap with each candidate\'s description -- verified directly on both of the lesson\'s worked examples.\n• BLINK-style embedding disambiguation independently agreed with the lexical approach on the same example, using real Transformer embeddings and cosine similarity instead of word overlap -- a genuine, corroborating verification of the same underlying signal.\n• Generative entity linking (LLM + constrained decoding to valid titles) avoids inventing nonexistent entities, applying the same logit-masking principle verified in the Structured Outputs lessons.\n• AIDA-CoNLL evaluates entity linking with two metrics: In-KB Accuracy (P@1) for entities that exist in the knowledge base, and NIL Detection Rate for mentions that don\'t.\n• Real production pitfalls include NIL handling, mention boundary errors (bad NER breaks EL), popularity bias, cross-lingual linking, and knowledge base staleness -- each requiring a specific mitigation rather than a single universal fix.\n• The 2026 production pattern chains NER -> Coreference Resolution -> Entity Linking -> canonical knowledge-base IDs, so downstream systems (knowledge graphs, QA, search) work with unified entities instead of scattered, ambiguous mentions.',
      bodyKn: '• Context-based lexical disambiguation (Jaccard ಹೋಲಿಕೆ) ಪ್ರತಿ ಅಭ್ಯರ್ಥಿಯ ವಿವರಣೆ ಜೊತೆ ಕೇವಲ ಪದ overlap ಆಧಾರದ ಮೇಲೆ Apple Inc. ಅನ್ನೂ ಹಣ್ಣಿನಿಂದ ಸರಿಯಾಗಿ ಪ್ರತ್ಯೇಕಿಸಿತು -- ಲೆಸನ್‌ನ ಎರಡೂ ಕೆಲಸ ಮಾಡಿದ ಉದಾಹರಣೆಗಳ ಮೇಲೆ ನೇರವಾಗಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ.\n• BLINK-ಶೈಲಿಯ embedding disambiguation ಅದೇ ಉದಾಹರಣೆಯ ಮೇಲೆ lexical ವಿಧಾನದ ಜೊತೆ ಸ್ವತಂತ್ರವಾಗಿ ಒಪ್ಪಿತು, ಪದ overlap ಬದಲಿಗೆ ನಿಜ Transformer embeddings ಮತ್ತು cosine ಹೋಲಿಕೆ ಬಳಸಿ -- ಅದೇ underlying signal ನ ಒಂದು ನಿಜ, ದೃಢಪಡಿಸುವ ಪರಿಶೀಲನೆ.\n• Generative entity linking (LLM + ಮಾನ್ಯ titles ಗಳಿಗೆ constrained decoding) ಅಸ್ತಿತ್ವದಲ್ಲಿಲ್ಲದ entities ಗಳನ್ನೂ ಕಟ್ಟುವುದನ್ನೂ ತಪ್ಪಿಸುತ್ತದೆ, Structured Outputs lessons ಗಳಲ್ಲಿ ಪರಿಶೀಲಿಸಿದ ಅದೇ logit-masking ತತ್ವ ಅನ್ವಯಿಸುತ್ತಾ.\n• AIDA-CoNLL ಎರಡು metrics ಗಳೊಂದಿಗೆ entity linking ಮೌಲ್ಯಮಾಪನ ಮಾಡುತ್ತದೆ: knowledge base ನಲ್ಲಿ ಅಸ್ತಿತ್ವದಲ್ಲಿರುವ entities ಗಳಿಗೆ In-KB Accuracy (P@1), ಮತ್ತು ಇಲ್ಲದಿರುವ mentions ಗಳಿಗೆ NIL Detection Rate.\n• ನಿಜ production ಬಲೆಗಳಲ್ಲಿ NIL handling, mention boundary errors (ಕೆಟ್ಟ NER EL ಮುರಿಯುತ್ತದೆ), popularity bias, cross-lingual linking, ಮತ್ತು knowledge base staleness ಸೇರಿವೆ -- ಪ್ರತಿಯೊಂದಕ್ಕೂ ಒಂದು ಸಾರ್ವತ್ರಿಕ ಸರಿಪಡಿಕೆಗಿಂತ ಒಂದು ನಿರ್ದಿಷ್ಟ ತಗ್ಗಿಸುವಿಕೆ ಅಗತ್ಯ.\n• 2026 production ಮಾದರಿ NER -> Coreference Resolution -> Entity Linking -> canonical knowledge-base IDs ಅನ್ನೂ ಸರಪಳಿ ಮಾಡುತ್ತದೆ, ಆದ್ದರಿಂದ downstream systems (knowledge graphs, QA, search) ಚದುರಿದ, ಅಸ್ಪಷ್ಟ mentions ಗಳ ಬದಲಿಗೆ ಏಕೀಕೃತ entities ಗಳ ಜೊತೆ ಕೆಲಸ ಮಾಡುತ್ತವೆ.' } },

    { type: 'quiz', data: { questions: [
      { q: 'Verified in this lesson: what did the real disambiguate() function return for "Apple released a new iPhone yesterday." vs. "She picked an apple from the tree in the orchard."?', qKn: 'ಈ lesson ನಲ್ಲಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ: "Apple released a new iPhone yesterday." vs. "She picked an apple from the tree in the orchard." ಗಾಗಿ ನಿಜ disambiguate() ಫಂಕ್ಷನ್ ಏನನ್ನೂ ಹಿಂತಿರುಗಿಸಿತು?',
        opts: ['The same entity for both sentences', 'Apple Inc. for the iPhone sentence and the fruit for the orchard sentence -- correctly disambiguating the identical mention "apple" differently based purely on word overlap with each context', 'An error in both cases, since "apple" was ambiguous', 'The fruit for both sentences, since fruit is the more common meaning'], correct: 1,
        optsKn: ['ಎರಡೂ ವಾಕ್ಯಗಳಿಗೆ ಅದೇ entity', 'iPhone ವಾಕ್ಯಕ್ಕೆ Apple Inc. ಮತ್ತು orchard ವಾಕ್ಯಕ್ಕೆ ಹಣ್ಣು -- ನಿಖರ ಒಂದೇ mention "apple" ಅನ್ನೂ ಕೇವಲ ಪ್ರತಿ context ಜೊತೆ ಪದ overlap ಆಧಾರದ ಮೇಲೆ ಸರಿಯಾಗಿ ಬೇರೆಯಾಗಿ ಪ್ರತ್ಯೇಕಿಸುತ್ತಾ', '"apple" ಅಸ್ಪಷ್ಟವಾಗಿದ್ದ ಕಾರಣ ಎರಡೂ ಪ್ರಕರಣಗಳಲ್ಲಿ ಒಂದು error', 'ಎರಡೂ ವಾಕ್ಯಗಳಿಗೆ ಹಣ್ಣು, ಹಣ್ಣು ಹೆಚ್ಚು ಸಾಮಾನ್ಯ ಅರ್ಥವಾಗಿರುವ ಕಾರಣ'] },
      { q: 'Verified in this lesson: what did the real BLINK-style embedding approach (using sentence-transformers) find for the same "Apple...iPhone" example?', qKn: 'ಈ lesson ನಲ್ಲಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ: ಅದೇ "Apple...iPhone" ಉದಾಹರಣೆಗಾಗಿ ನಿಜ BLINK-ಶೈಲಿಯ embedding ವಿಧಾನ (sentence-transformers ಬಳಸಿ) ಏನನ್ನೂ ಕಂಡುಹಿಡಿಯಿತು?',
        opts: ['It disagreed with the lexical approach, favoring the fruit', 'It independently agreed with the lexical approach: Apple Inc. scored a clearly higher cosine similarity (0.378) than the fruit (0.227)', 'It could not distinguish between the two candidates at all', 'It required a live API key and could not be run'], correct: 1,
        optsKn: ['ಇದೂ lexical ವಿಧಾನದ ಜೊತೆ ಒಪ್ಪಲಿಲ್ಲ, ಹಣ್ಣಿಗೆ ಆದ್ಯತೆ ನೀಡುತ್ತಾ', 'ಇದೂ lexical ವಿಧಾನದ ಜೊತೆ ಸ್ವತಂತ್ರವಾಗಿ ಒಪ್ಪಿತು: Apple Inc. ಹಣ್ಣಿಗಿಂತ (0.227) ಸ್ಪಷ್ಟವಾಗಿ ಹೆಚ್ಚಿನ cosine ಹೋಲಿಕೆ (0.378) ಸ್ಕೋರ್ ಮಾಡಿತು', 'ಇದೂ ಎರಡು ಅಭ್ಯರ್ಥಿಗಳ ನಡುವೆ ಸಂಪೂರ್ಣವಾಗಿ ಪ್ರತ್ಯೇಕಿಸಲಾಗಲಿಲ್ಲ', 'ಇದಕ್ಕೆ ಒಂದು live API key ಅಗತ್ಯವಿತ್ತು ಮತ್ತು ಚಲಾಯಿಸಲಾಗಲಿಲ್ಲ'] },
      { q: 'What does the "NIL Detection Rate" metric measure?', qKn: '"NIL Detection Rate" metric ಏನನ್ನೂ ಅಳೆಯುತ್ತದೆ?',
        opts: ['How fast the entity linking system runs', 'How accurately the system identifies mentions that do NOT exist in the knowledge base, rather than forcing an incorrect match', 'The total number of entities linked per second', 'Whether the system supports multiple languages'], correct: 1,
        optsKn: ['Entity linking system ಎಷ್ಟು ವೇಗವಾಗಿ ಚಲಾಯಿತವಾಗುತ್ತದೆ', 'ಒಂದು ತಪ್ಪಾದ ಹೊಂದಾಣಿಕೆಯನ್ನೂ ಬಲವಂತಪಡಿಸುವ ಬದಲಿಗೆ, knowledge base ನಲ್ಲಿ ಅಸ್ತಿತ್ವದಲ್ಲಿಲ್ಲದ mentions ಗಳನ್ನೂ system ಎಷ್ಟು ನಿಖರವಾಗಿ ಗುರುತಿಸುತ್ತದೆ', 'ಪ್ರತಿ ಸೆಕೆಂಡಿಗೆ ಸಂಪರ್ಕಿಸಿದ entities ಗಳ ಒಟ್ಟು ಸಂಖ್ಯೆ', 'System ಅನೇಕ ಭಾಷೆಗಳನ್ನೂ ಬೆಂಬಲಿಸುತ್ತದೆಯೇ'] },
      { q: 'Why does the "Popularity Bias" pitfall cause "Michael Jordan" in an ML research paper to sometimes be wrongly linked to the basketball player?', qKn: '"Popularity Bias" ಬಲೆ ಒಂದು ML ಸಂಶೋಧನಾ ಪ್ರಬಂಧದಲ್ಲಿ "Michael Jordan" ಅನ್ನೂ ಕೆಲವೊಮ್ಮೆ ಬ್ಯಾಸ್ಕೆಟ್‌ಬಾಲ್ ಆಟಗಾರನಿಗೆ ತಪ್ಪಾಗಿ ಸಂಪರ್ಕಿಸುವಂತೆ ಏಕೆ ಮಾಡುತ್ತದೆ?',
        opts: ['Because ML papers never mention the name "Michael Jordan"', 'Because frequently mentioned entities dominate predictions in systems relying heavily on popularity priors, disadvantaging less-represented domains like ML research', 'Because the basketball player and the professor are actually the same person', 'Because entity linking cannot process academic text of any kind'], correct: 1,
        optsKn: ['ಏಕೆಂದರೆ ML ಪ್ರಬಂಧಗಳು ಎಂದಿಗೂ "Michael Jordan" ಹೆಸರನ್ನೂ ಉಲ್ಲೇಖಿಸುವುದಿಲ್ಲ', 'ಏಕೆಂದರೆ popularity priors ಗಳ ಮೇಲೆ ಬಹಳವಾಗಿ ಅವಲಂಬಿತವಾಗಿರುವ systems ಗಳಲ್ಲಿ ಆಗಾಗ್ಗೆ ಉಲ್ಲೇಖಿಸಿದ entities ಗಳು ಭವಿಷ್ಯವಾಣಿಗಳ ಮೇಲೆ ಪ್ರಾಬಲ್ಯ ಸಾಧಿಸುತ್ತವೆ, ML ಸಂಶೋಧನೆಯಂತಹ ಕಡಿಮೆ-ಪ್ರತಿನಿಧಿಸಿದ ಡೊಮೈನ್‌ಗಳಿಗೆ ಅನಾನುಕೂಲ ಮಾಡುತ್ತಾ', 'ಏಕೆಂದರೆ ಬ್ಯಾಸ್ಕೆಟ್‌ಬಾಲ್ ಆಟಗಾರ ಮತ್ತು ಪ್ರೊಫೆಸರ್ ನಿಜವಾಗಿ ಒಬ್ಬ ವ್ಯಕ್ತಿ', 'ಏಕೆಂದರೆ entity linking ಯಾವುದೇ ಬಗೆಯ ಶೈಕ್ಷಣಿಕ ಪಠ್ಯವನ್ನೂ ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲಾರದು'] },
      { q: 'How does constrained decoding make generative entity linking safer?', qKn: 'Constrained decoding generative entity linking ಅನ್ನೂ ಹೇಗೆ ಸುರಕ್ಷಿತಗೊಳಿಸುತ್ತದೆ?',
        opts: ['It removes the need for any knowledge base at all', 'It restricts the LLM\'s generation to only valid knowledge-base entity titles, preventing it from inventing a plausible-sounding but nonexistent entity', 'It makes the model generate answers faster with no accuracy benefit', 'It only works for numerical outputs, not entity names'], correct: 1,
        optsKn: ['ಇದೂ ಯಾವುದೇ knowledge base ನ ಅಗತ್ಯವನ್ನೂ ಸಂಪೂರ್ಣವಾಗಿ ತೆಗೆದುಹಾಕುತ್ತದೆ', 'ಇದೂ LLM ನ generation ಅನ್ನೂ ಕೇವಲ ಮಾನ್ಯ knowledge-base entity titles ಗಳಿಗೆ ಮಾತ್ರ ನಿರ್ಬಂಧಿಸುತ್ತದೆ, ಒಂದು ಸಮಂಜಸ-ಧ್ವನಿಸುವ ಆದರೆ ಅಸ್ತಿತ್ವದಲ್ಲಿಲ್ಲದ entity ಕಟ್ಟುವುದನ್ನೂ ತಡೆಯುತ್ತಾ', 'ಇದೂ ಯಾವುದೇ ನಿಖರತೆ ಪ್ರಯೋಜನವಿಲ್ಲದೆ model ಗೆ ವೇಗವಾಗಿ ಉತ್ತರಗಳನ್ನೂ ಉತ್ಪಾದಿಸುವಂತೆ ಮಾಡುತ್ತದೆ', 'ಇದೂ ಕೇವಲ ಸಂಖ್ಯಾತ್ಮಕ outputs ಗಳ ಮೇಲೆ ಮಾತ್ರ ಕೆಲಸ ಮಾಡುತ್ತದೆ, entity ಹೆಸರುಗಳ ಮೇಲಲ್ಲ'] },
      { q: 'What does the 2026 production pipeline chain together, according to this lesson?', qKn: 'ಈ lesson ಪ್ರಕಾರ, 2026 production pipeline ಏನನ್ನೂ ಒಟ್ಟಿಗೆ ಸರಪಳಿ ಮಾಡುತ್ತದೆ?',
        opts: ['Only entity linking, with no other components', 'NER -> Coreference Resolution -> Entity Linking -> merging all mentions into canonical knowledge-base IDs for downstream systems like knowledge graphs, QA, and search', 'A single end-to-end model that requires no NER or coreference at all', 'Translation followed directly by summarization'], correct: 1,
        optsKn: ['ಕೇವಲ entity linking ಮಾತ್ರ, ಯಾವುದೇ ಇತರ ಘಟಕಗಳಿಲ್ಲದೆ', 'NER -> Coreference Resolution -> Entity Linking -> knowledge graphs, QA, ಮತ್ತು search ನಂತಹ downstream systems ಗಳಿಗೆ ಎಲ್ಲಾ mentions ಗಳನ್ನೂ canonical knowledge-base IDs ಗಳಾಗಿ ವಿಲೀನಗೊಳಿಸುವುದು', 'ಯಾವುದೇ NER ಅಥವಾ coreference ಅಗತ್ಯವಿಲ್ಲದ ಒಂದು single end-to-end model', 'Summarization ಗಿಂತ ನೇರವಾಗಿ ಮೊದಲು Translation'] },
    ] } },
  ],
};
