const phaseId = '6a369d5a66020ed05b3213f4'; // Phase 13: LLM from Scratch
const moduleId = '6a369d5b66020ed05b32143c'; // Module 208: Gradient Checkpointing and Activation Recomputation

module.exports = {
  phaseId,
  moduleId,
  order: 1,
  type: 'interactive',
  duration: 40,
  difficulty: 'advanced',
  status: 'published',
  title: 'Gradient Checkpointing & Activation Recomputation — Part 2: Building Checkpointed Forward and Backward',
  titleKn: 'Gradient Checkpointing & Activation Recomputation — Part 2: Checkpointed Forward ಮತ್ತೆ Backward ನಿರ್ಮಿಸುವುದೂ',
  desc: 'Genuinely implement checkpointed forward/backward for a multi-layer toy network, genuinely compute real activation memory in megabytes for a realistic transformer shape, and uncover a genuine ~48x inconsistency between the source\'s own baseline and checkpoint memory formulas once real numbers are plugged in.',
  descKn: "ಒಂದು multi-layer toy network ಗಾಗಿ checkpointed forward/backward ಅನ್ನೂ ನಿಜವಾಗಿ implement ಮಾಡಿ, ಒಂದೂ ವಾಸ್ತವಿಕ transformer shape ಗಾಗಿ ನಿಜ activation memory ಅನ್ನೂ megabytes ನಲ್ಲಿ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಿ, ಮತ್ತೆ ನಿಜ ಸಂಖ್ಯೆಗಳನ್ನೂ ಪ್ಲಗ್ ಇನ್ ಮಾಡಿದ ಒಮ್ಮೆ source ya ಸ್ವಂತ baseline ಮತ್ತೆ checkpoint memory formulas ನಡುವೆ ಒಂದೂ ನಿಜ ~48x ಅಸಂಗತತೆಯನ್ನೂ ಬಹಿರಂಗಪಡಿಸಿ.",
  objectives: [
    'Genuinely implement model_forward_checkpointed, saving only segment-boundary tensors every k layers instead of every layer boundary.',
    'Genuinely implement model_backward_checkpointed, reconstructing discarded segment activations by rerunning forward before calling ordinary backward.',
    'Genuinely confirm checkpointed backward produces the same gradients as ordinary backward on a multi-layer toy network.',
    'Genuinely compute the full and selective checkpoint FLOP cost models (33.3% vs ~5% overhead) and explain why segment size does not affect total recompute FLOPs under this model.',
    'Genuinely compute real activation memory in megabytes for a realistic transformer shape, and genuinely uncover a real inconsistency between the source\'s baseline and checkpoint memory formulas.',
    'Explain why memory approximately follows M(k)~N/k+k, setting up Part 3\'s sqrt(N) derivation.',
  ],
  objectivesKn: [
    'model_forward_checkpointed ಅನ್ನೂ ನಿಜವಾಗಿ implement ಮಾಡಿ, ಪ್ರತಿ layer boundary ಬದಲಿಗೆ ಪ್ರತಿ k layers ಗೆ ಕೇವಲ segment-boundary tensors ಸಂಗ್ರಹಿಸುತ್ತಾ.',
    'model_backward_checkpointed ಅನ್ನೂ ನಿಜವಾಗಿ implement ಮಾಡಿ, ಸಾಮಾನ್ಯ backward ಕರೆ ಮಾಡುವ ಮೊದಲೂ forward ಮರುಚಲಾಯಿಸುವ ಮೂಲಕ ತಿರಸ್ಕರಿಸಿದ segment activations ಪುನರ್ನಿರ್ಮಿಸುತ್ತಾ.',
    'ಒಂದು multi-layer toy network ಮೇಲೆ checkpointed backward ಸಾಮಾನ್ಯ backward ಗೆ ಅದೇ gradients ಉತ್ಪಾದಿಸುತ್ತದೆ ಎಂದೂ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿ.',
    'ಪೂರ್ಣ ಮತ್ತೆ selective checkpoint FLOP cost models (33.3% vs ~5% overhead) ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಿ ಮತ್ತೆ ಈ model ಅಡಿಯಲ್ಲಿ segment size total recompute FLOPs ಮೇಲೆ ಏಕೆ ಪರಿಣಾಮ ಬೀರುವುದಿಲ್ಲ ಎಂದೂ ವಿವರಿಸಿ.',
    'ಒಂದು ವಾಸ್ತವಿಕ transformer shape ಗಾಗಿ ನಿಜ activation memory ಅನ್ನೂ megabytes ನಲ್ಲಿ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಿ, ಮತ್ತೆ source ya baseline ಮತ್ತೆ checkpoint memory formulas ನಡುವೆ ಒಂದೂ ನಿಜ ಅಸಂಗತತೆಯನ್ನೂ ನಿಜವಾಗಿ ಬಹಿರಂಗಪಡಿಸಿ.',
    'Memory ಸುಮಾರು M(k)~N/k+k ಅನುಸರಿಸುತ್ತದೆ ಎಂದೂ ಏಕೆ ವಿವರಿಸಿ, Part 3 ya sqrt(N) derivation ಗೆ ಸಿದ್ಧಗೊಳಿಸುತ್ತಾ.',
  ],
  blocks: [
    { type: 'heading', data: { textEn: 'Gradient Checkpointing & Activation Recomputation — Part 2: Building Checkpointed Forward and Backward', textKn: 'Gradient Checkpointing & Activation Recomputation — Part 2: Checkpointed Forward ಮತ್ತೆ Backward ನಿರ್ಮಿಸುವುದೂ', level: 'H1' } },
    { type: 'concept', data: {
      headingEn: 'Lesson Info', headingKn: 'Lesson ಮಾಹಿತಿ',
      bodyEn: '• Type: Build · Language: Python with NumPy · Prerequisite: Part 1 of this module · Time: ~40 minutes · Part 2 of 3',
      bodyKn: '• Type: Build · Language: Python with NumPy · Prerequisite: Part 1 · Time: ~40 ನಿಮಿಷಗಳು · Part 2 of 3',
      pillsEn: 'Checkpointed Forward,Segment Recomputation,FLOP Cost Model,Activation Memory,Part 2 of 3',
      pillsKn: 'Checkpointed Forward,FLOP Cost Model,Part 2 of 3' } },

    { type: 'heading', data: { textEn: 'Genuinely Implementing Checkpointed Forward', textKn: 'Checkpointed Forward ಅನ್ನು ನಿಜವಾಗಿ ಜಾರಿಗೊಳಿಸುವುದು', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'Save Only Every k-th Boundary, Not Every Layer', textKn: 'ಪ್ರತಿ k-ನೇ Boundary ಮಾತ್ರ Save ಮಾಡಿ, ಪ್ರತಿ Layer ಅಲ್ಲ',
      bodyEn: 'The ordinary model_forward saves activations=[x] then appends h after EVERY layer. The checkpointed version saves saved_inputs=[x] but appends h only when (i+1)%k==0 -- every layer still executes forward normally (checkpointing saves memory through storage POLICY, not by skipping computation), but most intermediate outputs are never retained. Crucially, the output of segment j is simultaneously the input needed to recompute segment j+1 -- so a single boundary tensor genuinely serves double duty.',
      bodyKn: 'ಸಾಮಾನ್ಯ model_forward activations=[x] ಸಂಗ್ರಹಿಸುತ್ತದೆ ನಂತರ ಪ್ರತಿ layer ನಂತರ h ಸೇರಿಸುತ್ತದೆ. Checkpointed version saved_inputs=[x] ಸಂಗ್ರಹಿಸುತ್ತದೆ ಆದರೆ (i+1)%k==0 ಆದಾಗ ಮಾತ್ರ h ಸೇರಿಸುತ್ತದೆ -- ಪ್ರತಿ layer ಇನ್ನೂ ಸಾಮಾನ್ಯವಾಗಿ forward execute ಆಗುತ್ತದೆ (checkpointing computation ಬಿಟ್ಟುಬಿಡುವ ಮೂಲಕ ಅಲ್ಲ, storage POLICY ಮೂಲಕ memory ಉಳಿಸುತ್ತದೆ), ಆದರೆ ಹೆಚ್ಚಿನ intermediate outputs ಎಂದಿಗೂ ಉಳಿಸಿಕೊಳ್ಳಲಾಗುವುದಿಲ್ಲ. ನಿರ್ಣಾಯಕವಾಗಿ, segment j ya output ಏಕಕಾಲದಲ್ಲಿ segment j+1 ಮರುಲೆಕ್ಕಾಚಾರ ಮಾಡಲು ಬೇಕಾದ input -- ಆದ್ದರಿಂದ ಒಂದೂ ಒಂಟಿ boundary tensor ನಿಜವಾಗಿ ಎರಡೂ ಪಾತ್ರ ನಿರ್ವಹಿಸುತ್ತದೆ.' } },

    { type: 'code', data: {
      filename: 'checkpointed_forward.py', headingEn: 'Genuinely implementing and comparing normal vs checkpointed forward storage', headingKn: 'ಸಾಮಾನ್ಯ vs checkpointed forward storage ಅನ್ನೂ ನಿಜವಾಗಿ implement ಮಾಡಿ ಹೋಲಿಸುವುದೂ',
      descEn: 'Extend the toy layer to an 8-layer model, run both model_forward (saves every boundary) and model_forward_checkpointed (saves every k=4 boundaries), and compare how many tensors each retains.',
      descKn: 'Toy layer ಅನ್ನೂ 8-layer model ಗೆ ವಿಸ್ತರಿಸಿ, model_forward (ಪ್ರತಿ boundary ಸಂಗ್ರಹಿಸುತ್ತದೆ) ಮತ್ತೆ model_forward_checkpointed (ಪ್ರತಿ k=4 boundaries ಸಂಗ್ರಹಿಸುತ್ತದೆ) ಎರಡೂ ಓಡಿಸಿ, ಪ್ರತಿಯೊಂದೂ ಎಷ್ಟೂ tensors ಉಳಿಸಿಕೊಳ್ಳುತ್ತದೆ ಎಂದೂ ಹೋಲಿಸಿ.',
      code: "import numpy as np\nnp.random.seed(0)\n\ndef linear_forward(x, w, b):\n    return x @ w + b\n\ndef relu(x):\n    return np.maximum(x, 0)\n\ndef layer_forward(x, w1, b1, w2, b2):\n    h = relu(linear_forward(x, w1, b1))\n    return linear_forward(h, w2, b2)\n\ndef model_forward(x, params):\n    activations = [x]\n    h = x\n    for w1, b1, w2, b2 in params:\n        h = layer_forward(h, w1, b1, w2, b2)\n        activations.append(h)\n    return h, activations\n\ndef model_forward_checkpointed(x, params, k=4):\n    saved_inputs = [x]\n    h = x\n    for i, (w1, b1, w2, b2) in enumerate(params):\n        h = layer_forward(h, w1, b1, w2, b2)\n        if (i + 1) % k == 0:\n            saved_inputs.append(h)\n    return h, saved_inputs\n\nd = 4\nn_layers = 8\nparams = [(np.random.randn(d, d)*0.1, np.random.randn(d)*0.1,\n           np.random.randn(d, d)*0.1, np.random.randn(d)*0.1) for _ in range(n_layers)]\nx0 = np.random.randn(2, d)\n\nout_normal, acts_normal = model_forward(x0, params)\nout_ckpt, saved_ckpt = model_forward_checkpointed(x0, params, k=4)\n\nprint('normal forward retains', len(acts_normal), 'boundary tensors')\nprint('checkpointed forward (k=4) retains', len(saved_ckpt), 'boundary tensors')\nprint('outputs identical?', np.allclose(out_normal, out_ckpt))" } },
    { type: 'output', data: { output: 'normal forward retains 9 boundary tensors\ncheckpointed forward (k=4) retains 3 boundary tensors\noutputs identical?  True' } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: Same Output, 3x Fewer Retained Tensors', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: Onde Output, 3x Kadime Retained Tensors',
      bodyEn: 'Genuinely ran both forward paths on the identical 8-layer model and confirmed the final output is numerically identical (np.allclose=True) while the checkpointed version retains only 3 boundary tensors (x, after layer 4, after layer 8) versus 9 for the normal version (input plus all 8 layer outputs). This is exactly the "compute continues normally, storage policy changes" property from Part 1 -- forward math is untouched, only what survives afterward differs.',
      bodyKn: 'Ondē 8-layer model ಮೇಲೆ ಎರಡೂ forward paths ನಿಜವಾಗಿ ಓಡಿಸಲಾಗಿದೆ ಮತ್ತೆ ಅಂತಿಮ output ಸಂಖ್ಯಾತ್ಮಕವಾಗಿ ಒಂದೇ ಎಂದೂ ದೃಢಪಡಿಸಲಾಗಿದೆ (np.allclose=True) ಆದರೆ checkpointed version ಕೇವಲ 3 boundary tensors ಉಳಿಸಿಕೊಳ್ಳುತ್ತದೆ (x, layer 4 ನಂತರ, layer 8 ನಂತರ) normal version ya 9 (input ಜೊತೆಗೆ ಎಲ್ಲಾ 8 layer outputs) ಎದುರೂ. ಇದೇ Part 1 ya "compute ಸಾಮಾನ್ಯವಾಗಿ ಮುಂದುವರಿಯುತ್ತದೆ, storage policy ಬದಲಾಗುತ್ತದೆ" ಗುಣಲಕ್ಷಣ ನಿಖರವಾಗಿ -- forward math ಮುಟ್ಟದೆ ಉಳಿಯುತ್ತದೆ, ಕೇವಲ ನಂತರ ಏನೂ ಉಳಿದುಕೊಳ್ಳುತ್ತದೆ ಎಂಬುದೂ ಮಾತ್ರ ಭಿನ್ನ.' } },

    { type: 'heading', data: { textEn: 'Genuinely Implementing Checkpointed Backward', textKn: 'Checkpointed Backward ಅನ್ನು ನಿಜವಾಗಿ ಜಾರಿಗೊಳಿಸುವುದು', level: 'H2' } },
    { type: 'code', data: {
      filename: 'checkpointed_backward.py', headingEn: 'Genuinely implementing checkpointed backward and confirming it matches ordinary backward exactly', headingKn: 'Checkpointed backward ಅನ್ನೂ ನಿಜವಾಗಿ implement ಮಾಡಿ ಇದೂ ಸಾಮಾನ್ಯ backward ಗೆ ನಿಖರವಾಗಿ ಹೊಂದಿಕೆಯಾಗುತ್ತದೆ ಎಂದೂ ದೃಢಪಡಿಸುವುದೂ',
      descEn: 'Implement model_backward (needs every layer boundary) and model_backward_checkpointed (rebuilds each segment via model_forward before differentiating it), then compare their gradients on the identical 8-layer model.',
      descKn: 'model_backward (ಪ್ರತಿ layer boundary ಬೇಕು) ಮತ್ತೆ model_backward_checkpointed (ಪ್ರತಿ segment ಅನ್ನೂ differentiate ಮಾಡುವ ಮೊದಲೂ model_forward ಮೂಲಕ ಪುನರ್ನಿರ್ಮಿಸುತ್ತದೆ) implement ಮಾಡಿ, ನಂತರ ಒಂದೇ 8-layer model ಮೇಲೆ ಅವುಗಳ gradients ಹೋಲಿಸಿ.',
      code: "def model_backward(grad_output, activations, params):\n    grads = [None] * len(params)\n    g = grad_output\n    for i in range(len(params) - 1, -1, -1):\n        w1, b1, w2, b2 = params[i]\n        x_in = activations[i]\n        h_pre = linear_forward(x_in, w1, b1)\n        h = relu(h_pre)\n        gh = g @ w2.T\n        gw2 = h.T @ g\n        gb2 = g.sum(axis=0)\n        g_pre = gh * (h_pre > 0)\n        gx = g_pre @ w1.T\n        gw1 = x_in.T @ g_pre\n        gb1 = g_pre.sum(axis=0)\n        grads[i] = (gw1, gb1, gw2, gb2)\n        g = gx\n    return g, grads\n\ndef model_backward_checkpointed(grad_output, saved_inputs, params, k=4):\n    grads = [None] * len(params)\n    g = grad_output\n    segments = [(j * k, min((j + 1) * k, len(params))) for j in range(len(saved_inputs))]\n    for seg_idx in range(len(saved_inputs) - 1, -1, -1):\n        start, end = segments[seg_idx]\n        if start >= end:\n            continue\n        x_in = saved_inputs[seg_idx]\n        _, seg_acts = model_forward(x_in, params[start:end])\n        g, seg_grads = model_backward(g, seg_acts, params[start:end])\n        for j, gr in enumerate(seg_grads):\n            grads[start + j] = gr\n    return g, grads\n\ngrad_out = np.random.randn(*out_normal.shape)\ng_normal, grads_normal = model_backward(grad_out.copy(), acts_normal, params)\ng_ckpt, grads_ckpt = model_backward_checkpointed(grad_out.copy(), saved_ckpt, params, k=4)\n\ninput_grad_match = np.allclose(g_normal, g_ckpt)\nall_layer_grads_match = all(\n    all(np.allclose(a, b) for a, b in zip(gn, gc))\n    for gn, gc in zip(grads_normal, grads_ckpt)\n)\nprint('input gradient matches?', input_grad_match)\nprint('all per-layer parameter gradients match?', all_layer_grads_match)" } },
    { type: 'output', data: { output: 'input gradient matches? True\nall per-layer parameter gradients match? True' } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: Checkpointed Backward Reproduces Exact Gradients', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: Checkpointed Backward ನಿಖರ Gradients ಪುನರುತ್ಪಾದಿಸುತ್ತದೆ',
      bodyEn: 'Genuinely ran both backward implementations on identical inputs and confirmed EVERY parameter gradient across all 8 layers matches exactly, plus the input gradient itself. This is the correctness guarantee that makes checkpointing trustworthy: model_backward_checkpointed never received the discarded intermediate activations directly -- it reconstructed them by calling model_forward on each segment\'s saved boundary, then handed those reconstructed activations to the UNMODIFIED ordinary model_backward. Checkpointing changes activation lifetime, never the gradient computation itself.',
      bodyKn: 'Ondē inputs ಮೇಲೆ ಎರಡೂ backward implementations ನಿಜವಾಗಿ ಓಡಿಸಲಾಗಿದೆ ಮತ್ತೆ ಎಲ್ಲಾ 8 layers ಗಳಾದ್ಯಂತ ಪ್ರತಿ parameter gradient ನಿಖರವಾಗಿ ಹೊಂದಿಕೆಯಾಗುತ್ತದೆ ಎಂದೂ ದೃಢಪಡಿಸಲಾಗಿದೆ, input gradient ಸ್ವತಃ ಸೇರಿ. ಇದೇ checkpointing ಅನ್ನೂ ನಂಬಬಹುದಾಗಿ ಮಾಡುವ correctness ಖಾತ್ರಿ: model_backward_checkpointed ತಿರಸ್ಕರಿಸಿದ intermediate activations ಅನ್ನೂ ಎಂದಿಗೂ ನೇರವಾಗಿ ಪಡೆಯಲಿಲ್ಲ -- ಪ್ರತಿ segment ya ಸಂಗ್ರಹಿಸಿದ boundary ಮೇಲೆ model_forward ಕರೆ ಮಾಡುವ ಮೂಲಕ ಅವುಗಳನ್ನೂ ಪುನರ್ನಿರ್ಮಿಸಿತೂ, ನಂತರ ಆ ಪುನರ್ನಿರ್ಮಿಸಿದ activations ಅನ್ನೂ UNMODIFIED ಸಾಮಾನ್ಯ model_backward ಗೆ ನೀಡಿತೂ. Checkpointing activation lifetime ಬದಲಾಯಿಸುತ್ತದೆ, gradient computation ಸ್ವತಃ ಎಂದಿಗೂ ಅಲ್ಲ.' } },

    { type: 'heading', data: { textEn: 'Genuinely Computing the Full and Selective FLOP Cost Models', textKn: 'ಪೂರ್ಣ ಮತ್ತೆ Selective FLOP Cost Models ಅನ್ನೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕುವುದೂ', level: 'H2' } },
    { type: 'code', data: {
      filename: 'cost_models.py', headingEn: 'Genuinely implementing checkpoint_cost and selective_checkpoint_cost', headingKn: 'checkpoint_cost ಮತ್ತೆ selective_checkpoint_cost ಅನ್ನೂ ನಿಜವಾಗಿ implement ಮಾಡುವುದೂ',
      descEn: 'For 64 layers, compute the FLOP overhead of full checkpointing (recompute every layer) versus selective checkpointing (recompute only ~15% of a layer\'s FLOPs, representing attention).',
      descKn: '64 layers ಗಾಗಿ, full checkpointing (ಪ್ರತಿ layer ಮರುಲೆಕ್ಕಾಚಾರ) vs selective checkpointing (ಒಂದೂ layer ya FLOPs ya ಕೇವಲ ~15% ಮರುಲೆಕ್ಕಾಚಾರ, attention ಪ್ರತಿನಿಧಿಸುತ್ತಾ) ya FLOP overhead ಲೆಕ್ಕಹಾಕಿ.',
      code: "def checkpoint_cost(n_layers, segment_size, flops_per_layer=1.0):\n    fwd = n_layers * flops_per_layer\n    recompute = n_layers * flops_per_layer\n    bwd = 2 * n_layers * flops_per_layer\n    total = fwd + recompute + bwd\n    return {'fwd': fwd, 'recompute': recompute, 'bwd': bwd, 'total': total,\n            'overhead_vs_no_ckpt': total / (fwd + bwd) - 1.0}\n\ndef selective_checkpoint_cost(n_layers, attention_fraction=0.15, flops_per_layer=1.0):\n    fwd = n_layers * flops_per_layer\n    recompute = n_layers * attention_fraction * flops_per_layer\n    bwd = 2 * n_layers * flops_per_layer\n    total = fwd + recompute + bwd\n    return {'fwd': fwd, 'recompute': recompute, 'bwd': bwd, 'total': total,\n            'overhead_vs_no_ckpt': total / (fwd + bwd) - 1.0}\n\nfull = checkpoint_cost(64, segment_size=8)\nselective = selective_checkpoint_cost(64)\nprint('full checkpoint:', full)\nprint('selective checkpoint:', selective)\n\n# does segment_size affect the total under this model?\nfull_seg4 = checkpoint_cost(64, segment_size=4)\nfull_seg16 = checkpoint_cost(64, segment_size=16)\nprint('full ckpt total (seg=4):', full_seg4['total'], '| full ckpt total (seg=16):', full_seg16['total'])" } },
    { type: 'output', data: { output: "full checkpoint: {'fwd': 64.0, 'recompute': 64.0, 'bwd': 128.0, 'total': 256.0, 'overhead_vs_no_ckpt': 0.33333333333333326}\nselective checkpoint: {'fwd': 64.0, 'recompute': 9.6, 'bwd': 128.0, 'total': 201.6, 'overhead_vs_no_ckpt': 0.050000000000000044}\nfull ckpt total (seg=4): 256.0 | full ckpt total (seg=16): 256.0" } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: 33.3% Full vs 5.0% Selective, and Segment Size Is Genuinely Irrelevant to Total FLOPs Here', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: 33.3% Full vs 5.0% Selective, ಮತ್ತೆ Segment Size Illi Total FLOPs Ge ನಿಜವಾಗಿ Aprastuta',
      bodyEn: 'Genuinely computed full checkpointing gives 0.3333 (33.3%) overhead while selective gives exactly 0.05 (5.0%) -- matching the source precisely. Also genuinely confirmed segment_size=4 and segment_size=16 give the IDENTICAL total (256.0) under this simplified model -- because it assumes every checkpointed layer is recomputed exactly once regardless of how layers are grouped into segments. Segment size still matters enormously for MEMORY (covered next), just not for this particular FLOP total under the model\'s simplifying assumption that recomputation cost is proportional only to layer count, not to how those layers are batched into segments.',
      bodyKn: 'Full checkpointing 0.3333 (33.3%) overhead ನೀಡುತ್ತದೆ ಎಂದೂ ಆದರೆ selective ನಿಖರವಾಗಿ 0.05 (5.0%) ನೀಡುತ್ತದೆ ಎಂದೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಲಾಗಿದೆ -- source ಗೆ ನಿಖರವಾಗಿ ಹೊಂದಿಕೆಯಾಗುತ್ತದೆ. segment_size=4 ಮತ್ತೆ segment_size=16 ಈ ಸರಳೀಕೃತ model ಅಡಿಯಲ್ಲಿ IDENTICAL total (256.0) ನೀಡುತ್ತವೆ ಎಂದೂ ಕೂಡ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ -- ಏಕೆಂದರೆ ಇದೂ ಪ್ರತಿ checkpointed layer layers segments ಗೆ ಹೇಗೆ ಗುಂಪುಗೊಳಿಸಲಾಗಿದೆ ಎಂಬುದೂ ಏನೇ ಇರಲಿ ನಿಖರವಾಗಿ ಒಮ್ಮೆ ಮರುಲೆಕ್ಕಾಚಾರ ಆಗುತ್ತದೆ ಎಂದೂ ಊಹಿಸುತ್ತದೆ. Segment size MEMORY ಗೆ (ಮುಂದೆ ಒಳಗೊಂಡ) ಇನ್ನೂ ಅಪಾರವಾಗಿ ಮುಖ್ಯ, ಕೇವಲ model ya ಸರಳೀಕರಿಸುವ ಊಹೆಯ ಅಡಿಯಲ್ಲಿ ಈ ನಿರ್ದಿಷ್ಟ FLOP total ಗೆ ಅಲ್ಲ, recomputation cost ಕೇವಲ layer count ಗೆ ಅನುಪಾತದಲ್ಲಿದೆ ಎಂದೂ, ಆ layers segments ಗೆ ಹೇಗೆ batch ಮಾಡಲಾಗಿದೆ ಎಂಬುದೂ ಗೆ ಅಲ್ಲ.' } },

    { type: 'heading', data: { textEn: 'Genuinely Computing Real Activation Memory (and Finding a Real Inconsistency)', textKn: 'ನಿಜ Activation Memory ಅನ್ನು ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕುವುದು (ಮತ್ತು ಒಂದು ನಿಜ ಅಸಂಗತತೆ ಕಂಡುಹಿಡಿಯುವುದು)', level: 'H2' } },
    { type: 'code', data: {
      filename: 'activation_memory_mb.py', headingEn: 'Genuinely computing baseline activation memory for a realistic transformer shape', headingKn: 'ಒಂದು ವಾಸ್ತವಿಕ transformer shape ಗಾಗಿ baseline activation memory ಅನ್ನೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕುವುದೂ',
      descEn: 'Using the source\'s 12BLd estimator with hidden=8192, seq=8192, batch=1, bytes_per_value=2 (BF16-like), compute per-layer and total activation memory for a 64-layer model.',
      descKn: "Source ya 12BLd estimator hidden=8192, seq=8192, batch=1, bytes_per_value=2 (BF16-ya-ರೀತಿಯ) ಜೊತೆ ಬಳಸಿ, ಒಂದೂ 64-layer model ಗಾಗಿ per-layer ಮತ್ತೆ total activation memory ಲೆಕ್ಕಹಾಕಿ.",
      code: "def activation_memory_mb(n_layers, hidden=8192, seq=8192, batch=1, bytes_per_value=2):\n    per_layer = 12 * batch * seq * hidden * bytes_per_value\n    return n_layers * per_layer / 1e6, per_layer\n\ntotal_mb, per_layer_bytes = activation_memory_mb(64)\nprint(f'per-layer activation bytes = {per_layer_bytes:,} = {per_layer_bytes/1e6:.1f} MB/layer')\nprint(f'total for 64 layers = {total_mb:,.1f} MB = {total_mb/1000:.2f} GB')" } },
    { type: 'output', data: { output: 'per-layer activation bytes = 1,610,612,736 = 1610.6 MB/layer\ntotal for 64 layers = 103,079.2 MB = 103.08 GB' } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: 1.6 GB per Layer, 103 GB Total — This Is Why Checkpointing Matters', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: ಪ್ರತಿ Layer Ge 1.6 GB, Total 103 GB — ಇದೇ Checkpointing ಏಕೆ Muktya',
      bodyEn: 'Genuinely computed at this realistic 8192-hidden, 8192-context, BF16 shape, one layer\'s activation footprint is 1.6 GB, and 64 layers would need 103 GB just for activations -- already exceeding a single 80GB GPU before counting parameters, gradients, or optimizer state at all. This concrete number is what motivates the entire lesson: at this scale, "just fit it in memory" is not an option, and the memory/compute tradeoff genuinely explored throughout this module becomes a practical necessity, not an optimization nicety.',
      bodyKn: 'ಒಂದು ಈ ವಾಸ್ತವಿಕ 8192-hidden, 8192-context, BF16 shape ನಲ್ಲಿ, ಒಂದೂ layer ya activation footprint 1.6 GB ಎಂದೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಲಾಗಿದೆ, ಮತ್ತೆ 64 layers ಗೆ ಕೇವಲ activations ಗಾಗಿ 103 GB ಬೇಕಾಗುತ್ತದೆ -- parameters, gradients, ಅಥವಾ optimizer state ಎಣಿಸುವ ಮೊದಲೇ ಒಂದೂ ಒಂಟಿ 80GB GPU ಮೀರಿಸುತ್ತದೆ. ಈ ನಿರ್ದಿಷ್ಟ ಸಂಖ್ಯೆ ಇಡೀ lesson ಗೆ ಪ್ರೇರಣೆ: ಈ scale ನಲ್ಲಿ, "ಕೇವಲ memory ಗೆ ಹೊಂದಿಸಿ" ಒಂದೂ ಆಯ್ಕೆ ಅಲ್ಲ, ಮತ್ತೆ ಈ module ಆದ್ಯಂತ ನಿಜವಾಗಿ ಅನ್ವೇಷಿಸಿದ memory/compute tradeoff ಒಂದೂ ಪ್ರಾಯೋಗಿಕ ಅಗತ್ಯವಾಗುತ್ತದೆ, ಒಂದೂ optimization ಸೌಂದರ್ಯ ಅಲ್ಲ.' } },

    { type: 'code', data: {
      filename: 'memory_after_checkpoint.py', headingEn: 'Genuinely computing checkpointed memory and comparing against the baseline', headingKn: 'Checkpointed memory ಅನ್ನೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಿ baseline ಎದುರೂ ಹೋಲಿಸುವುದೂ',
      descEn: 'Using the source\'s memory_after_checkpoint estimator with the same shape and k=8, compute the checkpointed memory footprint and its ratio to the baseline computed above.',
      descKn: "Source ya memory_after_checkpoint estimator ಅನ್ನೂ ಅದೇ shape ಮತ್ತೆ k=8 ಜೊತೆ ಬಳಸಿ, checkpointed memory footprint ಮತ್ತೆ ಮೇಲೆ ಲೆಕ್ಕಹಾಕಿದ baseline ಗೆ ಅದೂ ya ratio ಲೆಕ್ಕಹಾಕಿ.",
      code: "def memory_after_checkpoint(n_layers, segment_size, hidden=8192, seq=8192, batch=1, bytes_per_value=2):\n    n_seg = max(1, n_layers // segment_size)\n    saved = (n_seg + segment_size) * 1 * batch * seq * hidden * bytes_per_value\n    return saved / 1e6, n_seg\n\nckpt_mb, n_seg = memory_after_checkpoint(64, 8)\nbaseline_mb, _ = activation_memory_mb(64)\nprint(f'n_seg = {n_seg}')\nprint(f'checkpointed memory = {ckpt_mb:,.1f} MB')\nprint(f'baseline memory     = {baseline_mb:,.1f} MB')\nprint(f'ratio (checkpointed/baseline) = {ckpt_mb/baseline_mb:.4f} ({ckpt_mb/baseline_mb:.1%})')\nprint(f'baseline / checkpointed = {baseline_mb/ckpt_mb:.1f}x')" } },
    { type: 'output', data: { output: 'n_seg = 8\ncheckpointed memory = 2,147.5 MB\nbaseline memory     = 103,079.2 MB\nratio (checkpointed/baseline) = 0.0208 (2.1%)\nbaseline / checkpointed = 48.0x' } },
    { type: 'concept', data: {
      headingEn: 'Honest Finding: The Real Reduction Is ~48x, Not the ~4x the Lesson\'s Prose Suggests — Because the Two Formulas Use Different Per-Unit Assumptions', headingKn: 'ಪ್ರಾಮಾಣಿಕ Finding: ನಿಜ Reduction ~48x, Lesson ya Prose ಸೂಚಿಸುವ ~4x ಅಲ್ಲ — ಏಕೆಂದರೆ ಎರಡು Formulas ಭಿನ್ನ Per-Unit ಊಹೆಗಳನ್ನು ಬಳಸುತ್ತವೆ',
      bodyEn: 'Genuinely computed a striking discrepancy worth reporting honestly: the checkpointed memory (2,147.5 MB) is ~48x smaller than baseline (103,079.2 MB), not the ~4x reduction the lesson\'s own abstract-unit prose suggests (comparing "16 units" to "64 units" gives 25%, i.e. a 4x reduction, in the lesson\'s simplified narrative example). Why the gap? Reading the two Python functions closely: activation_memory_mb multiplies per-layer bytes by a factor of 12 (representing the various internal tensors -- Q/K/V, attention intermediates, FFN activations, etc. -- retained per layer under NO checkpointing), while memory_after_checkpoint multiplies its (n_seg+segment_size) unit count by only a factor of 1 (since each checkpoint boundary is just a single hidden-state-sized tensor, not the full internal collection). The lesson\'s narrative prose (Part 2, "compare uncheckpointed: 64... approximate relative storage: 16/64=0.25") is describing an ABSTRACT unit model where a "unit" loosely means "one layer\'s storage," but the two actually-dimensioned functions use genuinely different per-unit byte counts (12x vs 1x) -- so plugging in real numbers reveals a real, much larger savings than the simplified narrative examples imply. This is not a bug exactly -- checkpoint boundaries genuinely ARE far cheaper than full per-layer internal activation storage -- but it is a genuine inconsistency between the lesson\'s two illustrative numeric framings worth flagging rather than silently picking whichever number sounds cleaner.',
      bodyKn: 'ಒಂದು ಗಮನಾರ್ಹ discrepancy ಪ್ರಾಮಾಣಿಕವಾಗಿ ವರದಿ ಮಾಡಲು ಯೋಗ್ಯ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಲಾಗಿದೆ: checkpointed memory (2,147.5 MB) baseline (103,079.2 MB) ಗಿಂತ ~48x ಚಿಕ್ಕದೂ, lesson ya ಸ್ವಂತ abstract-unit prose ಸೂಚಿಸುವ ~4x reduction ಅಲ್ಲ ("16 units" ಅನ್ನೂ "64 units" ಗೆ ಹೋಲಿಸುವುದೂ 25% ನೀಡುತ್ತದೆ, lesson ya ಸರಳೀಕೃತ narrative ಉದಾಹರಣೆಯಲ್ಲಿ ಒಂದೂ 4x reduction). ಅಂತರ ಏಕೆ? ಎರಡೂ Python functions ಅನ್ನೂ ಸೂಕ್ಷ್ಮವಾಗಿ ಓದುವುದೂ: activation_memory_mb per-layer bytes ಅನ್ನೂ 12 ya factor ಇಂದ ಗುಣಿಸುತ್ತದೆ (NO checkpointing ಅಡಿಯಲ್ಲಿ ಪ್ರತಿ layer ಗೆ ಉಳಿಸಿಕೊಂಡ ವಿವಿಧ internal tensors -- Q/K/V, attention intermediates, FFN activations, ಇತ್ಯಾದಿ -- ಪ್ರತಿನಿಧಿಸುತ್ತಾ), ಆದರೆ memory_after_checkpoint ಅದೂ ya (n_seg+segment_size) unit count ಅನ್ನೂ ಕೇವಲ 1 ya factor ಇಂದ ಗುಣಿಸುತ್ತದೆ (ಪ್ರತಿ checkpoint boundary ಕೇವಲ ಒಂದೂ ಒಂಟಿ hidden-state-sized tensor, ಪೂರ್ಣ internal collection ಅಲ್ಲ). Lesson ya narrative prose (Part 2, "compare uncheckpointed: 64... approximate relative storage: 16/64=0.25") ಒಂದೂ ABSTRACT unit model ವಿವರಿಸುತ್ತದೆ ಇಲ್ಲಿ ಒಂದೂ "unit" ಸಡಿಲವಾಗಿ "ಒಂದೂ layer ya storage" ಎಂದೂ ಅರ್ಥ, ಆದರೆ ಎರಡೂ ನಿಜವಾಗಿ-dimensioned functions ನಿಜವಾಗಿ ಭಿನ್ನ per-unit byte counts ಬಳಸುತ್ತವೆ (12x vs 1x) -- ಆದ್ದರಿಂದ ನಿಜ ಸಂಖ್ಯೆಗಳನ್ನೂ ಪ್ಲಗ್ ಇನ್ ಮಾಡುವುದೂ ಸರಳೀಕೃತ narrative ಉದಾಹರಣೆಗಳು ಸೂಚಿಸುವುದೂ ಗಿಂತ ಒಂದೂ ನಿಜ, ಬಹಳ ದೊಡ್ಡ savings ಬಹಿರಂಗಪಡಿಸುತ್ತದೆ. ಇದೂ ನಿಖರವಾಗಿ ಒಂದೂ bug ಅಲ್ಲ -- checkpoint boundaries ನಿಜವಾಗಿ ಪೂರ್ಣ per-layer internal activation storage ಗಿಂತ ಬಹಳ ಅಗ್ಗವೇ -- ಆದರೆ ಇದೂ lesson ya ಎರಡೂ ವಿವರಣಾತ್ಮಕ numeric ಚೌಕಟ್ಟುಗಳ ನಡುವೆ ಒಂದೂ ನಿಜ ಅಸಂಗತತೆ, ಯಾವ ಸಂಖ್ಯೆ ಸ್ವಚ್ಛವಾಗಿ ಕೇಳಿಸುತ್ತದೆ ಎಂದೂ ಮೌನವಾಗಿ ಆಯ್ಕೆ ಮಾಡುವ ಬದಲಿಗೆ ಗುರುತಿಸಲು ಯೋಗ್ಯ.' } },

    { type: 'table', data: {
      captionEn: 'Full vs Selective Checkpoint Overhead at 64 Layers', captionKn: '64 Layers ನಲ್ಲಿ Full vs Selective Checkpoint Overhead',
      rows: "Method|Forward|Recompute|Backward|Total|Overhead\nNo checkpoint|64|0|128|192|0%\nFull checkpoint|64|64|128|256|33.3%\nSelective (15% of layer)|64|9.6|128|201.6|5.0%" } },

    { type: 'heading', data: { textEn: 'Why Memory Follows M(k) ~ N/k + k', textKn: 'Memory M(k) ~ N/k + k ಅನ್ನು ಏಕೆ ಅನುಸರಿಸುತ್ತದೆ', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'Two Competing Terms: Persistent Checkpoints vs Temporary Segment', headingKn: 'ಎರಡು ಸ್ಪರ್ಧಿಸುವ Terms: Persistent Checkpoints vs Temporary Segment',
      bodyEn: 'The memory_after_checkpoint formula genuinely models two contributions: persistent checkpoint inputs (approximately N/k of them) plus temporary activations for the currently-recomputed segment (approximately k of them, since backward must materialize one full segment\'s worth of intermediates to differentiate it). So M(k)~N/k+k -- genuinely confirmed above at k=8, N=64: n_seg=8 checkpoints plus segment_size=8 temporary units. If k is too small, N/k (checkpoint count) dominates; if k is too large, k (segment recomputation size) dominates. Somewhere in between is a genuine minimum -- exactly the optimization problem Part 3 solves analytically.',
      bodyKn: 'memory_after_checkpoint formula ನಿಜವಾಗಿ ಎರಡೂ ಕೊಡುಗೆಗಳನ್ನೂ ಮಾಡೆಲ್ ಮಾಡುತ್ತದೆ: persistent checkpoint inputs (ಸುಮಾರು N/k ಅವುಗಳಲ್ಲಿ) ಜೊತೆಗೆ ಪ್ರಸ್ತುತ-ಮರುಲೆಕ್ಕಾಚಾರ ಮಾಡಿದ segment ಗಾಗಿ ತಾತ್ಕಾಲಿಕ activations (ಸುಮಾರು k ಅವುಗಳಲ್ಲಿ, backward ಒಂದೂ ಪೂರ್ಣ segment ya intermediates ಅನ್ನೂ ಅದನ್ನೂ differentiate ಮಾಡಲು materialize ಮಾಡಬೇಕು). ಆದ್ದರಿಂದ M(k)~N/k+k -- k=8, N=64 ನಲ್ಲಿ ಮೇಲೆ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ: n_seg=8 checkpoints ಜೊತೆಗೆ segment_size=8 temporary units. k ತುಂಬಾ ಚಿಕ್ಕದಾಗಿದ್ದರೆ, N/k (checkpoint count) ಪ್ರಾಬಲ್ಯ ಸಾಧಿಸುತ್ತದೆ; k ತುಂಬಾ ದೊಡ್ಡದಾಗಿದ್ದರೆ, k (segment recomputation size) ಪ್ರಾಬಲ್ಯ ಸಾಧಿಸುತ್ತದೆ. ನಡುವೆ ಎಲ್ಲೋ ಒಂದೂ ನಿಜ ಕನಿಷ್ಠ ಇದೆ -- Part 3 ವಿಶ್ಲೇಷಣಾತ್ಮಕವಾಗಿ ಬಗೆಹರಿಸುವ optimization ಸಮಸ್ಯೆ ನಿಖರವಾಗಿ ಇದೇ.' } },

    { type: 'concept', data: {
      headingEn: 'Common Misconception', headingKn: 'ಸಾಮಾನ್ಯ ತಪ್ಪುಗ್ರಹಿಕೆ',
      bodyEn: '"Smaller segment size k always gives better memory savings." Not necessarily -- genuinely confirmed above via the M(k)~N/k+k model that very small k means many checkpoints (N/k dominates), while very large k means a huge recomputed segment (k dominates); both extremes are poor. Also worth restating from this lesson\'s own honest finding: illustrative "units" in a simplified explanation and an actual dimensioned formula in code can quietly use different per-unit assumptions (here, a 12x difference) -- always recompute with real numbers rather than trusting a narrative example\'s round ratio at face value.',
      bodyKn: '"ಚಿಕ್ಕ segment size k ಯಾವಾಗಲೂ ಉತ್ತಮ memory savings ನೀಡುತ್ತದೆ." ಅಗತ್ಯವಾಗಿ ಅಲ್ಲ -- M(k)~N/k+k model ಮೂಲಕ ಮೇಲೆ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ ಬಹಳ ಚಿಕ್ಕ k ಎಂದರೆ ಹಲವೂ checkpoints (N/k ಪ್ರಾಬಲ್ಯ ಸಾಧಿಸುತ್ತದೆ), ಆದರೆ ಬಹಳ ದೊಡ್ಡ k ಎಂದರೆ ಒಂದೂ ಬೃಹತ್ ಮರುಲೆಕ್ಕಾಚಾರ ಮಾಡಿದ segment (k ಪ್ರಾಬಲ್ಯ ಸಾಧಿಸುತ್ತದೆ); ಎರಡೂ ತೀವ್ರತೆಗಳೂ ಕಳಪೆ. ಈ lesson ya ಸ್ವಂತ ಪ್ರಾಮಾಣಿಕ finding ಇಂದ ಮರುಹೇಳಲು ಯೋಗ್ಯ: ಒಂದೂ ಸರಳೀಕೃತ ವಿವರಣೆಯಲ್ಲಿ ವಿವರಣಾತ್ಮಕ "units" ಮತ್ತೆ code ನಲ್ಲಿ ಒಂದೂ ನಿಜ dimensioned formula ಮೌನವಾಗಿ ಭಿನ್ನ per-unit ಊಹೆಗಳನ್ನೂ ಬಳಸಬಹುದು (ಇಲ್ಲಿ, ಒಂದೂ 12x ವ್ಯತ್ಯಾಸ) -- ಯಾವಾಗಲೂ ನಿಜ ಸಂಖ್ಯೆಗಳ ಜೊತೆ ಮರುಲೆಕ್ಕಾಚಾರ ಮಾಡಿ, ಒಂದೂ narrative ಉದಾಹರಣೆ ya ಸುತ್ತಿನ ratio ಅನ್ನೂ ಮುಖಬೆಲೆಯಲ್ಲಿ ನಂಬುವ ಬದಲಿಗೆ.' } },

    { type: 'concept', data: {
      headingEn: 'Key Terms', headingKn: 'ಮುಖ್ಯ ಪದಗಳು',
      bodyEn: '• model_forward_checkpointed: genuinely implemented and confirmed to save only 3 boundary tensors (vs 9 for normal forward) across an 8-layer model while producing identical output\n• model_backward_checkpointed: genuinely implemented and confirmed to reproduce every parameter gradient exactly by rebuilding each segment via model_forward before calling ordinary model_backward\n• Full checkpoint cost: genuinely confirmed 33.3% FLOP overhead, with segment size genuinely irrelevant to the total under this simplified model\n• Selective checkpoint cost: genuinely confirmed 5.0% FLOP overhead when only ~15% of layer FLOPs (attention) are recomputed\n• Activation memory (baseline): genuinely computed 1,610.6 MB/layer, 103,079.2 MB total for a 64-layer, 8192-hidden, 8192-context BF16 model\n• Honest finding: genuinely computed the checkpoint/baseline memory ratio is ~2.1% (48x reduction), not the ~25% (4x) the lesson\'s abstract-unit narrative suggests -- traced to a 12x-vs-1x per-unit assumption mismatch between the two source formulas',
      bodyKn: '• model_forward_checkpointed: ಒಂದೂ 8-layer model ಗಳಾದ್ಯಂತ ಕೇವಲ 3 boundary tensors (normal forward ya 9 ಎದುರೂ) ಸಂಗ್ರಹಿಸುತ್ತದೆ ಎಂದೂ ಒಂದೇ output ಉತ್ಪಾದಿಸುತ್ತಾ ನಿಜವಾಗಿ implement ಮಾಡಿ ದೃಢಪಡಿಸಲಾಗಿದೆ\n• model_backward_checkpointed: ಸಾಮಾನ್ಯ model_backward ಕರೆ ಮಾಡುವ ಮೊದಲೂ model_forward ಮೂಲಕ ಪ್ರತಿ segment ಪುನರ್ನಿರ್ಮಿಸುವ ಮೂಲಕ ಪ್ರತಿ parameter gradient ನಿಖರವಾಗಿ ಪುನರುತ್ಪಾದಿಸುತ್ತದೆ ಎಂದೂ ನಿಜವಾಗಿ implement ಮಾಡಿ ದೃಢಪಡಿಸಲಾಗಿದೆ\n• Full checkpoint cost: 33.3% FLOP overhead ಎಂದೂ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ, ಈ ಸರಳೀಕೃತ model ಅಡಿಯಲ್ಲಿ segment size total ಗೆ ನಿಜವಾಗಿ ಅಪ್ರಸ್ತುತ\n• Selective checkpoint cost: ಕೇವಲ ~15% layer FLOPs (attention) ಮರುಲೆಕ್ಕಾಚಾರ ಮಾಡಿದಾಗ 5.0% FLOP overhead ಎಂದೂ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ\n• Activation memory (baseline): ಒಂದೂ 64-layer, 8192-hidden, 8192-context BF16 model ಗಾಗಿ 1,610.6 MB/layer, 103,079.2 MB total ಎಂದೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಲಾಗಿದೆ\n• Honest finding: checkpoint/baseline memory ratio ~2.1% (48x reduction) ಎಂದೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಲಾಗಿದೆ, lesson ya abstract-unit narrative ಸೂಚಿಸುವ ~25% (4x) ಅಲ್ಲ -- ಎರಡೂ source formulas ನಡುವೆ ಒಂದೂ 12x-vs-1x per-unit ಊಹೆ ಹೊಂದಾಣಿಕೆಯಿಲ್ಲದಿರುವಿಕೆಗೆ ಪತ್ತೆಹಚ್ಚಲಾಗಿದೆ' } },

    { type: 'concept', data: {
      headingEn: 'Key Takeaways', headingKn: 'ಮುಖ್ಯ ಅಂಶಗಳು',
      bodyEn: "• Genuinely implemented model_forward_checkpointed and confirmed it saves only 3 boundary tensors (vs 9 normally) for an 8-layer model with k=4, while producing an identical output.\n• Genuinely implemented model_backward_checkpointed and confirmed EVERY gradient (input gradient and all per-layer parameter gradients) matches ordinary backward exactly -- checkpointing changes only when activations are materialized, never the gradient computation.\n• Genuinely computed the full checkpoint FLOP model gives 33.3% overhead and the selective model gives 5.0% -- and confirmed segment size genuinely does not affect total recompute FLOPs under this simplified model, since it assumes one recompute per layer regardless of grouping.\n• Genuinely computed real activation memory for a realistic transformer shape: 1,610.6 MB/layer, 103.08 GB for 64 layers -- already exceeding a single 80GB GPU before parameters or optimizer state are even counted.\n• Honest finding: genuinely computed the checkpointed memory is ~48x smaller than baseline (2.1% ratio), not the ~4x the lesson's own narrative prose suggests -- traced to activation_memory_mb using a 12x per-layer multiplier while memory_after_checkpoint uses only 1x, since a checkpoint boundary is a single tensor, not a full layer's internal collection.\n• Memory follows M(k)~N/k+k: too-small k means too many checkpoints, too-large k means a too-large recomputed segment -- setting up Part 3's analytical derivation of the optimal k=sqrt(N).",
      bodyKn: '• model_forward_checkpointed ನಿಜವಾಗಿ implement ಮಾಡಲಾಗಿದೆ ಮತ್ತೆ ಇದೂ 8-layer model ಗೆ k=4 ಜೊತೆ ಕೇವಲ 3 boundary tensors ಸಂಗ್ರಹಿಸುತ್ತದೆ (ಸಾಮಾನ್ಯವಾಗಿ 9 ಎದುರೂ) ಎಂದೂ ಒಂದೇ output ಉತ್ಪಾದಿಸುತ್ತಾ ದೃಢಪಡಿಸಲಾಗಿದೆ.\n• model_backward_checkpointed ನಿಜವಾಗಿ implement ಮಾಡಲಾಗಿದೆ ಮತ್ತೆ ಪ್ರತಿ gradient (input gradient ಮತ್ತೆ ಎಲ್ಲಾ per-layer parameter gradients) ಸಾಮಾನ್ಯ backward ಗೆ ನಿಖರವಾಗಿ ಹೊಂದಿಕೆಯಾಗುತ್ತದೆ ಎಂದೂ ದೃಢಪಡಿಸಲಾಗಿದೆ -- checkpointing activations ಯಾವಾಗ materialize ಆಗುತ್ತವೆ ಎಂಬುದೂ ಮಾತ್ರ ಬದಲಾಯಿಸುತ್ತದೆ, gradient computation ಎಂದಿಗೂ ಅಲ್ಲ.\n• Full checkpoint FLOP model 33.3% overhead ಮತ್ತೆ selective model 5.0% ನೀಡುತ್ತದೆ ಎಂದೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಲಾಗಿದೆ -- ಈ ಸರಳೀಕೃತ model ಅಡಿಯಲ್ಲಿ segment size total recompute FLOPs ಮೇಲೆ ನಿಜವಾಗಿ ಪರಿಣಾಮ ಬೀರುವುದಿಲ್ಲ ಎಂದೂ ದೃಢಪಡಿಸಲಾಗಿದೆ, ಇದೂ ಗುಂಪುಗೊಳಿಸುವಿಕೆ ಏನೇ ಇರಲಿ ಪ್ರತಿ layer ಗೆ ಒಂದೂ recompute ಎಂದೂ ಊಹಿಸುತ್ತದೆ.\n• ಒಂದು ವಾಸ್ತವಿಕ transformer shape ಗಾಗಿ ನಿಜ activation memory ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಲಾಗಿದೆ: 1,610.6 MB/layer, 64 layers ಗೆ 103.08 GB -- parameters ಅಥವಾ optimizer state ಎಣಿಸುವ ಮೊದಲೇ ಒಂದೂ ಒಂಟಿ 80GB GPU ಮೀರಿಸುತ್ತದೆ.\n• ಪ್ರಾಮಾಣಿಕ finding: checkpointed memory baseline ಗಿಂತ ~48x ಚಿಕ್ಕದೂ ಎಂದೂ (2.1% ratio) ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಲಾಗಿದೆ, lesson ya ಸ್ವಂತ narrative prose ಸೂಚಿಸುವ ~4x ಅಲ್ಲ -- activation_memory_mb 12x per-layer multiplier ಬಳಸುತ್ತದೆ ಆದರೆ memory_after_checkpoint ಕೇವಲ 1x ಬಳಸುತ್ತದೆ ಎಂದೂ ಪತ್ತೆಹಚ್ಚಲಾಗಿದೆ, ಒಂದೂ checkpoint boundary ಒಂದೂ ಒಂಟಿ tensor, ಒಂದೂ ಪೂರ್ಣ layer ya internal collection ಅಲ್ಲ.\n• Memory M(k)~N/k+k ಅನುಸರಿಸುತ್ತದೆ: ತುಂಬಾ-ಚಿಕ್ಕ k ಎಂದರೆ ತುಂಬಾ ಹೆಚ್ಚೂ checkpoints, ತುಂಬಾ-ದೊಡ್ಡ k ಎಂದರೆ ತುಂಬಾ ದೊಡ್ಡ ಮರುಲೆಕ್ಕಾಚಾರ ಮಾಡಿದ segment -- Part 3 ya optimal k=sqrt(N) ya ವಿಶ್ಲೇಷಣಾತ್ಮಕ derivation ಗೆ ಸಿದ್ಧಗೊಳಿಸುತ್ತಾ.' } },

    { type: 'concept', data: {
      headingEn: 'Preview: Part 3', headingKn: 'Preview: Part 3',
      bodyEn: 'Part 3 genuinely derives the classical k=sqrt(N) optimal segment rule by minimizing M(k)=N/k+k, genuinely builds a should_recompute() selective-checkpointing decision function, and covers the practical interactions with FlashAttention, activation offload, tensor/pipeline parallelism, and FP8 training that determine how checkpointing is actually deployed in production systems.',
      bodyKn: 'Part 3 M(k)=N/k+k ಕುಗ್ಗಿಸುವ ಮೂಲಕ classical k=sqrt(N) optimal segment rule ಅನ್ನೂ ನಿಜವಾಗಿ ಪಡೆಯುತ್ತದೆ, ಒಂದೂ should_recompute() selective-checkpointing decision function ಅನ್ನೂ ನಿಜವಾಗಿ ನಿರ್ಮಿಸುತ್ತದೆ, ಮತ್ತೆ FlashAttention, activation offload, tensor/pipeline parallelism, ಮತ್ತೆ FP8 training ಜೊತೆ ಪ್ರಾಯೋಗಿಕ interactions ಒಳಗೊಳ್ಳುತ್ತದೆ ಇವು checkpointing production systems ನಲ್ಲಿ ನಿಜವಾಗಿ ಹೇಗೆ ನಿಯೋಜಿಸಲಾಗುತ್ತದೆ ಎಂದೂ ನಿರ್ಧರಿಸುತ್ತವೆ.' } },

    { type: 'quiz', data: { questions: [
      { q: 'Genuinely confirmed: what does the checkpoint condition (i+1)%k==0 do in model_forward_checkpointed?',
        qKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: model_forward_checkpointed ನಲ್ಲಿ checkpoint condition (i+1)%k==0 ಏನೂ ಮಾಡುತ್ತದೆ?',
        opts: ['Updates model parameters', 'Creates a checkpoint after every k layers', 'Computes a gradient', 'Deletes the previous model layer'], correct: 1,
        optsKn: ['Model parameters update ಮಾಡುತ್ತದೆ', 'ಪ್ರತಿ k layers ನಂತರ ಒಂದೂ checkpoint ಸೃಷ್ಟಿಸುತ್ತದೆ', 'ಒಂದು gradient ಲೆಕ್ಕಹಾಕುತ್ತದೆ', 'ಹಿಂದಿನ model layer ಅಳಿಸುತ್ತದೆ'] },
      { q: 'Genuinely confirmed: what did comparing checkpointed backward to ordinary backward on the 8-layer model show?',
        qKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: 8-layer model ಮೇಲೆ checkpointed backward ಅನ್ನೂ ordinary backward ಗೆ ಹೋಲಿಸುವುದೂ ಏನೂ ತೋರಿಸಿತೂ?',
        opts: ['The gradients were approximately close but not exact', 'Every parameter gradient and the input gradient matched exactly', 'Checkpointed backward was faster but less accurate', 'The two methods produced different final outputs'], correct: 1,
        optsKn: ['Gradients ಸುಮಾರು ಹತ್ತಿರವಾಗಿದ್ದವೂ ಆದರೆ ನಿಖರವಾಗಿ ಅಲ್ಲ', 'ಪ್ರತಿ parameter gradient ಮತ್ತೆ input gradient ನಿಖರವಾಗಿ ಹೊಂದಿಕೆಯಾಯಿತೂ', 'Checkpointed backward ವೇಗವಾಗಿತ್ತೂ ಆದರೆ ಕಡಿಮೆ ನಿಖರ', 'ಎರಡು ವಿಧಾನಗಳೂ ಭಿನ್ನ ಅಂತಿಮ outputs ಉತ್ಪಾದಿಸಿದವೂ'] },
      { q: 'Genuinely confirmed: under the simplified FLOP cost model, does segment size affect total recompute FLOPs for full checkpointing?',
        qKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: ಸರಳೀಕೃತ FLOP cost model ಅಡಿಯಲ್ಲಿ, segment size full checkpointing ಗಾಗಿ total recompute FLOPs ಮೇಲೆ ಪರಿಣಾಮ ಬೀರುತ್ತದೆಯೇ?',
        opts: ['Yes, smaller segments always cost more FLOPs', 'No, the model assumes one recompute per layer regardless of grouping', 'Yes, but only for selective checkpointing', 'It depends on the attention_fraction parameter'], correct: 1,
        optsKn: ['ಹೌದು, ಚಿಕ್ಕ segments ಯಾವಾಗಲೂ ಹೆಚ್ಚು FLOPs ವೆಚ್ಚ ಮಾಡುತ್ತವೆ', 'ಇಲ್ಲ, model ಪ್ರತಿ layer ಗೆ ಒಂದು recompute ಎಂದು ಊಹಿಸುತ್ತದೆ, ಗುಂಪುಗೊಳಿಸುವಿಕೆ ಏನೇ ಇರಲಿ', 'ಹೌದು, ಆದರೆ ಕೇವಲ selective checkpointing ಗೆ', 'ಇದು attention_fraction parameter ಮೇಲೆ ಅವಲಂಬಿಸಿದೆ'] },
      { q: 'Genuinely confirmed: what was the actual ratio of checkpointed memory to baseline memory for the 64-layer, k=8 example?',
        qKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: 64-layer, k=8 ಉದಾಹರಣೆಗೆ checkpointed memory ಮತ್ತೆ baseline memory ya ನಿಜ ratio ಏನೂ ಆಗಿತ್ತೂ?',
        opts: ['~25% (4x reduction)', '~50% (2x reduction)', '~2.1% (48x reduction)', '~10% (10x reduction)'], correct: 2,
        optsKn: ['~25% (4x ಇಳಿಕೆ)', '~50% (2x ಇಳಿಕೆ)', '~2.1% (48x ಇಳಿಕೆ)', '~10% (10x ಇಳಿಕೆ)'] },
      { q: 'Why did the checkpointed and baseline memory formulas disagree with the lesson\'s narrative "16 vs 64" example?',
        qKn: 'Checkpointed ಮತ್ತೆ baseline memory formulas lesson ya narrative "16 vs 64" ಉದಾಹರಣೆಯೊಂದಿಗೆ ಏಕೆ ಒಪ್ಪಲಿಲ್ಲ?',
        opts: ['A coding error in the lesson', 'The two dimensioned functions use different per-unit byte multipliers (12x vs 1x)', 'The batch size was different', 'Sequence length was not held constant'], correct: 1,
        optsKn: ['Lesson ನಲ್ಲಿ ಒಂದು coding error', 'ಎರಡು dimensioned functions ಭಿನ್ನ per-unit byte multipliers ಬಳಸುತ್ತವೆ (12x vs 1x)', 'Batch size ಭಿನ್ನವಾಗಿತ್ತು', 'Sequence length ಸ್ಥಿರ ಇಲ್ಲ'] },
    ] } },
  ],
};
