const phaseId = '6a369d5a66020ed05b3213f4'; // Phase 13: LLM from Scratch
const moduleId = '6a369d5b66020ed05b321433'; // Module 205: Jamba: Hybrid SSM-Transformer

module.exports = {
  phaseId,
  moduleId,
  order: 2,
  type: 'interactive',
  duration: 40,
  difficulty: 'advanced',
  status: 'published',
  title: 'Jamba — Hybrid SSM-Transformer — Part 3: Mamba-3, Hybrid Tradeoffs, and Final Architecture View',
  titleKn: 'Jamba — Hybrid SSM-Transformer — Part 3: Mamba-3, Hybrid Tradeoffs, ಮತ್ತೆ Final Architecture View',
  desc: 'Genuinely compute Mamba-3\'s reported accuracy gains and the 64x context-growth factor from 4k to 256k, then genuinely compare active-parameter ratios across Jamba (~23%), Jamba 1.5 Large (~24%), and DeepSeek-V3 (~5.5%) to reveal how differently each architecture pushes MoE sparsity.',
  descKn: "Mamba-3 ya ವರದಿ ಮಾಡಿದ accuracy gains ಮತ್ತೆ 4k ಇಂದ 256k ಗೆ 64x context-growth factor ಅನ್ನೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಿ, ನಂತರ Jamba (~23%), Jamba 1.5 Large (~24%), ಮತ್ತೆ DeepSeek-V3 (~5.5%) ಗಳಾದ್ಯಂತ active-parameter ratios ಅನ್ನೂ ನಿಜವಾಗಿ ಹೋಲಿಸಿ ಪ್ರತಿ architecture MoE sparsity ಅನ್ನೂ ಎಷ್ಟೂ ಭಿನ್ನವಾಗಿ ತಳ್ಳುತ್ತದೆ ಎಂದೂ ಬಹಿರಂಗಪಡಿಸಿ.",
  objectives: [
    'Explain the three Mamba-3 architectural innovations: exponential-trapezoidal discretization, complex-valued state updates, and MIMO projections.',
    'Genuinely compute Mamba-3\'s reported accuracy improvement over Gated DeltaNet and confirm the MIMO variant\'s additional contribution.',
    'Genuinely compute how many times KV-cache memory grows when context increases from 4k to 256k.',
    'Explain when hybrid SSM-Transformer models are a good choice and when a pure Transformer may still be better.',
    'Genuinely compute and compare active-parameter ratios across Jamba, Jamba 1.5 Large, and DeepSeek-V3 to contrast their MoE sparsity philosophies.',
    'Summarize the entire Jamba architecture and connect every formula from this module back to the documented memory calculator.',
  ],
  objectivesKn: [
    'Mamba-3 ya ಮೂರೂ architectural innovations ವಿವರಿಸಿ: exponential-trapezoidal discretization, complex-valued state updates, ಮತ್ತೆ MIMO projections.',
    'Gated DeltaNet ಎದುರೂ Mamba-3 ya ವರದಿ ಮಾಡಿದ accuracy improvement ಅನ್ನೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಿ ಮತ್ತೆ MIMO variant ya ಹೆಚ್ಚುವರಿ ಕೊಡುಗೆ ದೃಢಪಡಿಸಿ.',
    'Context 4k ಇಂದ 256k ಗೆ ಹೆಚ್ಚಾದಾಗ KV-cache memory ಎಷ್ಟೂ ಬಾರಿ ಬೆಳೆಯುತ್ತದೆ ಎಂದೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಿ.',
    'Hybrid SSM-Transformer models ಯಾವಾಗ ಒಂದೂ ಉತ್ತಮ ಆಯ್ಕೆ ಎಂದೂ ಮತ್ತೆ ಒಂದೂ pure Transformer ಯಾವಾಗ ಇನ್ನೂ ಉತ್ತಮವಾಗಿರಬಹುದೂ ಎಂದೂ ವಿವರಿಸಿ.',
    'Jamba, Jamba 1.5 Large, ಮತ್ತೆ DeepSeek-V3 ಗಳಾದ್ಯಂತ active-parameter ratios ಅನ್ನೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಿ ಹೋಲಿಸಿ ಅವುಗಳ MoE sparsity ತತ್ವಗಳನ್ನೂ ವ್ಯತಿರಿಕ್ತಗೊಳಿಸಿ.',
    'ಇಡೀ Jamba architecture ಸಂಕ್ಷೇಪಿಸಿ ಮತ್ತೆ ಈ module ya ಪ್ರತಿ formula ಅನ್ನೂ ದಾಖಲಿತ memory calculator ಗೆ ಮರಳಿ ಸಂಪರ್ಕಿಸಿ.',
  ],
  blocks: [
    { type: 'heading', data: { textEn: 'Jamba — Hybrid SSM-Transformer — Part 3: Mamba-3, Hybrid Tradeoffs, and Final Architecture View', textKn: 'Jamba — Hybrid SSM-Transformer — Part 3: Mamba-3, Hybrid Tradeoffs, ಮತ್ತೆ Final Architecture View', level: 'H1' } },
    { type: 'concept', data: {
      headingEn: 'Lesson Info', headingKn: 'Lesson ಮಾಹಿತಿ',
      bodyEn: '• Type: Learn · Language: Python — memory/ratio calculator · Prerequisite: Parts 1-2 of this module, Module 204 (DeepSeek-V3) · Time: ~40 minutes · Part 3 of 3',
      bodyKn: '• Type: Learn · Language: Python — memory/ratio calculator · Prerequisite: Parts 1-2, Module 204 · Time: ~40 ನಿಮಿಷಗಳು · Part 3 of 3',
      pillsEn: 'Mamba-3,Hybrid Tradeoffs,Active Parameter Ratio,Competitive Landscape,Part 3 of 3',
      pillsKn: 'Mamba-3,Hybrid Tradeoffs,Part 3 of 3' } },

    { type: 'heading', data: { textEn: 'Why Mamba-3 Exists', textKn: 'Mamba-3 ಏಕೆ ಅಸ್ತಿತ್ವದಲ್ಲಿದೆ', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'Reintroducing Complexity Selectively', headingKn: 'ಆಯ್ದವಾಗಿ Complexity ಮರುಪರಿಚಯಿಸುವುದೂ',
      bodyEn: 'Recall the SSM recurrence from Part 1: h_t=Ah_{t-1}+Bx_t. This gives excellent memory efficiency via a fixed state, but if the state transition is too simple, the model may not represent complex long-range dynamics well. The source frames the evolution as: S4 used complex structured state -> Mamba simplified toward real diagonal states -> Mamba-2 simplified further -> Mamba-3 reintroduces complexity selectively. Mamba-3 does not abandon the SSM idea -- it tries to make the recurrent state more expressive WITHOUT giving up efficient inference, via three specific changes: exponential-trapezoidal discretization (better state evolution), complex-valued state updates (better state tracking), and MIMO projections (better feature interaction).',
      bodyKn: 'Part 1 ya SSM recurrence ನೆನಪಿಸಿಕೊಳ್ಳಿ: h_t=Ah_{t-1}+Bx_t. ಇದೂ ಒಂದೂ ಸ್ಥಿರ state ಮೂಲಕ ಅತ್ಯುತ್ತಮ memory efficiency ನೀಡುತ್ತದೆ, ಆದರೆ state transition ತುಂಬಾ ಸರಳವಾಗಿದ್ದರೆ, model ಸಂಕೀರ್ಣ ಉದ್ದ-ಶ್ರೇಣಿಯ dynamics ಅನ್ನೂ ಚೆನ್ನಾಗಿ ಪ್ರತಿನಿಧಿಸದಿರಬಹುದು. Source ವಿಕಾಸವನ್ನೂ ಚೌಕಟ್ಟುಗೊಳಿಸುತ್ತದೆ: S4 complex structured state ಬಳಸಿತೂ -> Mamba real diagonal states ಕಡೆಗೆ ಸರಳೀಕರಿಸಿತೂ -> Mamba-2 ಇನ್ನಷ್ಟೂ ಸರಳೀಕರಿಸಿತೂ -> Mamba-3 ಆಯ್ದವಾಗಿ complexity ಮರುಪರಿಚಯಿಸುತ್ತದೆ. Mamba-3 SSM ಆಲೋಚನೆಯನ್ನೂ ಬಿಟ್ಟುಬಿಡುವುದಿಲ್ಲ -- ಇದೂ efficient inference ಬಿಟ್ಟುಬಿಡದೆ recurrent state ಅನ್ನೂ ಹೆಚ್ಚು ಅಭಿವ್ಯಕ್ತಿಶೀಲಗೊಳಿಸಲು ಪ್ರಯತ್ನಿಸುತ್ತದೆ, ಮೂರೂ ನಿರ್ದಿಷ್ಟ ಬದಲಾವಣೆಗಳ ಮೂಲಕ: exponential-trapezoidal discretization (ಉತ್ತಮ state evolution), complex-valued state updates (ಉತ್ತಮ state tracking), ಮತ್ತೆ MIMO projections (ಉತ್ತಮ feature interaction).' } },

    { type: 'heading', data: { textEn: 'Innovation 1: Exponential-Trapezoidal Discretization', textKn: 'Innovation 1: Exponential-Trapezoidal Discretization', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'A Richer Rule for State Evolution Between Tokens', headingKn: 'Tokens ನಡುವೆ State Evolution ಗಾಗಿ ಒಂದೂ ಶ್ರೀಮಂತ Rule',
      bodyEn: 'SSMs often start from continuous-time dynamics dh(t)/dt=Ah(t)+Bx(t), but a neural network processes discrete tokens, so discretization converts continuous dynamics into a discrete recurrence. A simple Euler-style discretization (used in Mamba-2) behaves like h_{t+1} ~= h_t + delta_t * f(h_t, x_t) -- a straight step based only on the current slope, efficient but less expressive. Mamba-3 uses exponential-trapezoidal discretization instead: the continuous solution has the form h(t)=e^{At}h(0), so preserving more of this exponential structure -- combined with trapezoidal reasoning (using richer information about the transition, not just one endpoint) -- gives more expressive recurrent dynamics without sacrificing the O(1) state-memory property.',
      bodyKn: 'SSMs ಸಾಮಾನ್ಯವಾಗಿ continuous-time dynamics dh(t)/dt=Ah(t)+Bx(t) ಇಂದ ಆರಂಭವಾಗುತ್ತವೆ, ಆದರೆ ಒಂದೂ neural network discrete tokens ಸಂಸ್ಕರಿಸುತ್ತದೆ, ಆದ್ದರಿಂದ discretization continuous dynamics ಅನ್ನೂ ಒಂದೂ discrete recurrence ಗೆ ಪರಿವರ್ತಿಸುತ್ತದೆ. ಒಂದೂ ಸರಳ Euler-style discretization (Mamba-2 ನಲ್ಲಿ ಬಳಸಲಾಗಿದೆ) h_{t+1} ~= h_t + delta_t * f(h_t, x_t) ನಂತೆ ವರ್ತಿಸುತ್ತದೆ -- ಕೇವಲ ಪ್ರಸ್ತುತ slope ಆಧಾರಿತ ಒಂದೂ ನೇರ ಹೆಜ್ಜೆ, ಸಮರ್ಥ ಆದರೆ ಕಡಿಮೆ ಅಭಿವ್ಯಕ್ತಿಶೀಲ. Mamba-3 ಬದಲಿಗೆ exponential-trapezoidal discretization ಬಳಸುತ್ತದೆ: continuous solution h(t)=e^{At}h(0) ರೂಪ ಹೊಂದಿದೆ, ಆದ್ದರಿಂದ ಈ exponential structure ya ಹೆಚ್ಚಿನದನ್ನೂ ಸಂರಕ್ಷಿಸುವುದೂ -- trapezoidal ತಾರ್ಕಿಕತೆಯ ಜೊತೆ ಸಂಯೋಜಿಸಿ (transition ಬಗ್ಗೆ ಶ್ರೀಮಂತ ಮಾಹಿತಿ ಬಳಸುವುದೂ, ಕೇವಲ ಒಂದೂ endpoint ಅಲ್ಲ) -- O(1) state-memory ಗುಣಲಕ್ಷಣ ತ್ಯಾಗ ಮಾಡದೆ ಹೆಚ್ಚು ಅಭಿವ್ಯಕ್ತಿಶೀಲ recurrent dynamics ನೀಡುತ್ತದೆ.' } },

    { type: 'heading', data: { textEn: 'Innovation 2: Complex-Valued State Updates', textKn: 'Innovation 2: Complex-Valued State Updates', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'Complex Numbers as Rotation, Like a Data-Dependent RoPE for the State', headingKn: 'Complex Numbers Rotation ಆಗಿ, State ಗಾಗಿ ಒಂದೂ Data-Dependent RoPE ನಂತೆ',
      bodyEn: 'A complex number z=re^{i*theta} encodes magnitude (r) and rotation angle (theta). Multiplying by e^{i*theta} rotates the representation -- conceptually similar to what RoPE does with Transformer queries and keys, and the source explicitly describes Mamba-3\'s complex state update as behaving like a data-dependent rotary embedding on the recurrent state. Rotation lets two hidden features [h1,h2] preserve structured cyclic relationships (phase, cycles, relative position) instead of merely increasing/decreasing independently -- naturally suited to tasks with cyclic structure (A->B->C->A). Restoring complex-valued dynamics is intended to recover state-tracking capabilities lost by Mamba/Mamba-2\'s earlier simplification to real diagonal states.',
      bodyKn: 'ಒಂದೂ complex number z=re^{i*theta} magnitude (r) ಮತ್ತೆ rotation angle (theta) ಎನ್ಕೋಡ್ ಮಾಡುತ್ತದೆ. e^{i*theta} ಇಂದ ಗುಣಿಸುವುದೂ representation ಅನ್ನೂ ತಿರುಗಿಸುತ್ತದೆ -- Transformer queries ಮತ್ತೆ keys ಜೊತೆ RoPE ಏನೂ ಮಾಡುತ್ತದೆ ಎಂಬುದೂ ಗೆ ಪರಿಕಲ್ಪನಾತ್ಮಕವಾಗಿ ಸಮಾನ, ಮತ್ತೆ source Mamba-3 ya complex state update ಅನ್ನೂ recurrent state ಮೇಲೆ ಒಂದೂ data-dependent rotary embedding ನಂತೆ ವರ್ತಿಸುತ್ತದೆ ಎಂದೂ ಸ್ಪಷ್ಟವಾಗಿ ವಿವರಿಸುತ್ತದೆ. Rotation ಎರಡೂ hidden features [h1,h2] ಸ್ವತಂತ್ರವಾಗಿ ಹೆಚ್ಚಿಸುವ/ಕಡಿಮೆ ಮಾಡುವ ಬದಲಿಗೆ ರಚನಾತ್ಮಕ ಆವರ್ತಕ ಸಂಬಂಧಗಳನ್ನೂ (phase, cycles, relative position) ಸಂರಕ್ಷಿಸಲು ಬಿಡುತ್ತದೆ -- ಆವರ್ತಕ ರಚನೆ (A->B->C->A) ಇರುವ tasks ಗೆ ಸ್ವಾಭಾವಿಕವಾಗಿ ಸೂಕ್ತ. Complex-valued dynamics ಮರುಸ್ಥಾಪಿಸುವುದೂ Mamba/Mamba-2 ya ಮುಂಚಿನ real diagonal states ಗೆ ಸರಳೀಕರಣ ಇಂದ ಕಳೆದುಕೊಂಡ state-tracking ಸಾಮರ್ಥ್ಯಗಳನ್ನೂ ಮರಳಿ ಪಡೆಯಲು ಉದ್ದೇಶಿಸಿದೆ.' } },

    { type: 'heading', data: { textEn: 'Innovation 3: MIMO Projections', textKn: 'Innovation 3: MIMO Projections', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'Matrix-Valued Feature Interaction, Plus a Hardware Bonus', headingKn: 'Matrix-Valued Feature Interaction, ಜೊತೆಗೆ ಒಂದೂ Hardware Bonus',
      bodyEn: 'MIMO (Multi-Input Multi-Output) replaces simpler per-feature scalar projections (y_i=a_i*x_i, each feature transformed mostly independently) with matrix-valued projections (y=W*x, where output 1 can depend on inputs 1,2,3,4 and so on) -- allowing richer interaction between features. Interestingly, the source says MIMO is not only about modeling power: it also improves inference-time hardware utilization without increasing decode latency, since GPUs are excellent at matrix operations and a larger structured matrix computation can use hardware more effectively than many tiny scalar operations. So MIMO = better representation + better hardware utilization.',
      bodyKn: 'MIMO (Multi-Input Multi-Output) ಸರಳ per-feature scalar projections ಅನ್ನೂ (y_i=a_i*x_i, ಪ್ರತಿ feature ಹೆಚ್ಚಾಗಿ ಸ್ವತಂತ್ರವಾಗಿ ಪರಿವರ್ತಿಸಲಾಗಿದೆ) matrix-valued projections ಜೊತೆ ಬದಲಾಯಿಸುತ್ತದೆ (y=W*x, ಇಲ್ಲಿ output 1 inputs 1,2,3,4 ಇತ್ಯಾದಿ ಮೇಲೆ ಅವಲಂಬಿತವಾಗಿರಬಹುದು) -- features ನಡುವೆ ಶ್ರೀಮಂತ interaction ಗೆ ಅವಕಾಶ ನೀಡುತ್ತದೆ. ಆಸಕ್ತಿದಾಯಕವಾಗಿ, source MIMO ಕೇವಲ modeling power ಬಗ್ಗೆ ಅಲ್ಲ ಎಂದೂ ಹೇಳುತ್ತದೆ: ಇದೂ decode latency ಹೆಚ್ಚಿಸದೆ inference-time hardware utilization ಕೂಡ ಸುಧಾರಿಸುತ್ತದೆ, ಏಕೆಂದರೆ GPUs matrix operations ನಲ್ಲಿ ಅತ್ಯುತ್ತಮ ಮತ್ತೆ ಒಂದೂ ದೊಡ್ಡ structured matrix computation ಹಲವೂ ಚಿಕ್ಕ scalar operations ಗಿಂತ hardware ಅನ್ನೂ ಹೆಚ್ಚು ಪರಿಣಾಮಕಾರಿಯಾಗಿ ಬಳಸಬಹುದು. ಆದ್ದರಿಂದ MIMO = ಉತ್ತಮ representation + ಉತ್ತಮ hardware utilization.' } },

    { type: 'heading', data: { textEn: 'Genuinely Verifying Mamba-3\'s Reported Gains', textKn: 'Mamba-3 ya ವರದಿ ಮಾಡಿದ Gains ಅನ್ನೂ ನಿಜವಾಗಿ ಪರಿಶೀಲಿಸುವುದೂ', level: 'H2' } },
    { type: 'code', data: {
      filename: 'mamba3_gains.py', headingEn: 'Genuinely adding Mamba-3\'s reported accuracy improvements', headingKn: 'Mamba-3 ya ವರದಿ ಮಾಡಿದ accuracy improvements ಅನ್ನೂ ನಿಜವಾಗಿ ಸೇರಿಸುವುದೂ',
      descEn: 'At roughly 1.5B parameters, the source reports Mamba-3 improves average downstream accuracy over Gated DeltaNet by 0.6 points, with the MIMO variant adding another 1.2 points. Compute the total.',
      descKn: 'ಸುಮಾರು 1.5B parameters ನಲ್ಲಿ, source Mamba-3 Gated DeltaNet ಎದುರೂ average downstream accuracy ಅನ್ನೂ 0.6 points ಇಂದ ಸುಧಾರಿಸುತ್ತದೆ ಎಂದೂ ವರದಿ ಮಾಡುತ್ತದೆ, MIMO variant ಇನ್ನೂ 1.2 points ಸೇರಿಸುತ್ತದೆ. Total ಲೆಕ್ಕಹಾಕಿ.',
      code: "base_gain = 0.6  # Mamba-3 vs Gated DeltaNet\nmimo_additional = 1.2  # MIMO variant's additional contribution\ntotal_gain = base_gain + mimo_additional\nprint(f'Mamba-3 gain over Gated DeltaNet: {base_gain} points')\nprint(f'MIMO variant additional gain: {mimo_additional} points')\nprint(f'Total reported improvement: {base_gain} + {mimo_additional} = {total_gain:.1f} points')" } },
    { type: 'output', data: { output: 'Mamba-3 gain over Gated DeltaNet: 0.6 points\nMIMO variant additional gain: 1.2 points\nTotal reported improvement: 0.6 + 1.2 = 1.8 points' } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: 1.8 Points Total, and "Half the State" Is a Separate, Qualitative Claim', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: ಒಟ್ಟೂ 1.8 Points, ಮತ್ತೆ "Half the State" ಒಂದೂ ಪ್ರತ್ಯೇಕ, ಗುಣಾತ್ಮಕ Claim',
      bodyEn: 'Genuinely confirmed 0.6+1.2=1.8, matching the source\'s cited total improvement exactly. The source also states that at the same state size, Mamba-3 matches Mamba-2 with about half the state -- this is a separate efficiency claim (state-size-for-quality tradeoff) from the accuracy-points figure, and no further numeric detail is given in the source for that specific claim, so this lesson reports it as stated rather than inventing supporting numbers. The core takeaway: Mamba-3 tries to gain quality WITHOUT giving up SSM efficiency, at roughly 1.5B parameter scale in the cited experiments.',
      bodyKn: '0.6+1.2=1.8 ಎಂದೂ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ, source ya ಉಲ್ಲೇಖಿತ total improvement ಗೆ ನಿಖರವಾಗಿ ಹೊಂದಿಕೆಯಾಗುತ್ತದೆ. Source ಕೂಡ ಅದೇ state size ನಲ್ಲಿ, Mamba-3 ಸುಮಾರು ಅರ್ಧ state ಜೊತೆ Mamba-2 ಗೆ ಹೊಂದಿಕೆಯಾಗುತ್ತದೆ ಎಂದೂ ಹೇಳುತ್ತದೆ -- ಇದೂ accuracy-points ಅಂಕಿಅಂಶ ಇಂದ ಒಂದೂ ಪ್ರತ್ಯೇಕ efficiency claim (state-size-for-quality tradeoff), ಮತ್ತೆ ಆ ನಿರ್ದಿಷ್ಟ claim ಗಾಗಿ source ನಲ್ಲಿ ಯಾವುದೇ ಹೆಚ್ಚಿನ numeric ವಿವರ ನೀಡಲಾಗಿಲ್ಲ, ಆದ್ದರಿಂದ ಈ lesson ಬೆಂಬಲಿಸುವ ಸಂಖ್ಯೆಗಳನ್ನೂ ಕಂಡುಹಿಡಿಯುವ ಬದಲಿಗೆ ಹೇಳಿಕೆಯಂತೆ ವರದಿ ಮಾಡುತ್ತದೆ. ಮುಖ್ಯ ಅಂಶ: Mamba-3 ಉಲ್ಲೇಖಿತ ಪ್ರಯೋಗಗಳಲ್ಲಿ ಸುಮಾರು 1.5B parameter scale ನಲ್ಲಿ, SSM efficiency ಬಿಟ್ಟುಕೊಡದೆ quality ಪಡೆಯಲು ಪ್ರಯತ್ನಿಸುತ್ತದೆ.' } },

    { type: 'concept', data: {
      headingEn: 'Important Source Limitation', headingKn: 'ಮುಖ್ಯ Source ಮಿತಿ',
      bodyEn: 'The supplied lesson explicitly says Mamba-3 is not yet shipping in a production hybrid at scale -- it is a promising pure-SSM baseline and a possible candidate for future Jamba-class hybrid designs, not an already-deployed model. If Mamba-3\'s SSM side becomes strong enough, a future hybrid could potentially need less attention (e.g. moving from 1 attention per 8 layers toward 1 per 16), but the source frames this explicitly as a possible future direction, not a currently deployed result.',
      bodyKn: 'ಪೇಸ್ಟ್ ಮಾಡಿದ lesson ಸ್ಪಷ್ಟವಾಗಿ ಹೇಳುತ್ತದೆ Mamba-3 ಇನ್ನೂ scale ನಲ್ಲಿ ಒಂದೂ production hybrid ನಲ್ಲಿ ಸಾಗಿಸುತ್ತಿಲ್ಲ -- ಇದೂ ಒಂದೂ ಭರವಸೆಯ pure-SSM baseline ಮತ್ತೆ ಭವಿಷ್ಯದ Jamba-class hybrid designs ಗಾಗಿ ಒಂದೂ ಸಂಭಾವ್ಯ ಅಭ್ಯರ್ಥಿ, ಈಗಾಗಲೇ-ನಿಯೋಜಿಸಿದ model ಅಲ್ಲ. Mamba-3 ya SSM ಬದಿ ಸಾಕಷ್ಟೂ ಬಲಿಷ್ಠವಾದರೆ, ಒಂದೂ ಭವಿಷ್ಯದ hybrid ಗೆ ಕಡಿಮೆ attention ಬೇಕಾಗಬಹುದು (ಉದಾ. 8 layers ಗೆ 1 attention ಇಂದ 16 ಗೆ 1 ಗೆ ಚಲಿಸುವುದೂ), ಆದರೆ source ಇದನ್ನೂ ಸ್ಪಷ್ಟವಾಗಿ ಒಂದೂ ಸಂಭಾವ್ಯ ಭವಿಷ್ಯದ ದಿಕ್ಕೂ ಎಂದೂ ಚೌಕಟ್ಟುಗೊಳಿಸುತ್ತದೆ, ಪ್ರಸ್ತುತ ನಿಯೋಜಿಸಿದ ಫಲಿತಾಂಶ ಅಲ್ಲ.' } },

    { type: 'heading', data: { textEn: 'When Hybrids Win, When They Lose', textKn: 'Hybrids ಯಾವಾಗ ಗೆಲ್ಲುತ್ತವೆ, ಯಾವಾಗ ಸೋಲುತ್ತವೆ', level: 'H2' } },
    { type: 'code', data: {
      filename: 'context_growth.py', headingEn: 'Genuinely computing how much KV-cache memory grows from 4k to 256k context', headingKn: '4k ಇಂದ 256k context ಗೆ KV-cache memory ಎಷ್ಟೂ ಬೆಳೆಯುತ್ತದೆ ಎಂದೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕುವುದೂ',
      descEn: 'Since KV-cache memory is proportional to context length N (genuinely confirmed in Part 2), compute the growth factor from a manageable 4k context to Jamba\'s 256k example.',
      descKn: 'KV-cache memory context length N ಗೆ ಅನುಪಾತದಲ್ಲಿದೆ ಎಂದೂ (Part 2 ನಲ್ಲಿ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ), ಒಂದೂ ನಿರ್ವಹಿಸಬಹುದಾದ 4k context ಇಂದ Jamba ya 256k ಉದಾಹರಣೆಗೆ ಬೆಳವಣಿಗೆ factor ಲೆಕ್ಕಹಾಕಿ.',
      code: "c1 = 4 * 1024   # 4k tokens\nc2 = 256 * 1024  # 256k tokens\ngrowth = c2 / c1\nprint(f'context growth 4k -> 256k: {c2}/{c1} = {growth}x')\nprint('Since M_KV is proportional to N, KV-cache memory grows by the same factor.')" } },
    { type: 'output', data: { output: 'context growth 4k -> 256k: 262144/4096 = 64.0x\nSince M_KV is proportional to N, KV-cache memory grows by the same factor.' } },
    { type: 'concept', data: {
      headingEn: 'Case 1: Very Long Context Favors Hybrids', headingKn: 'Case 1: ಬಹಳ ಉದ್ದ Context Hybrids ಗೆ ಅನುಕೂಲಕರ',
      bodyEn: 'Genuinely confirmed a 64x context increase means a 64x KV-cache increase for a pure Transformer, but the SSM-state term is unaffected (genuinely confirmed to have no N term in Part 2) -- this is exactly where replacing most attention layers with SSM layers becomes attractive. The source uses roughly 64k+ as the region where this starts becoming especially relevant. Below that, at short context (roughly under 16k), the KV cache is already small, so replacing most attention with Mamba may save some memory but introduces new recurrent kernels, hybrid scheduling, and architectural complexity that may not be justified -- hybrids become more compelling as context grows, not universally superior.',
      bodyKn: '64x context ಹೆಚ್ಚಳ ಒಂದೂ pure Transformer ಗೆ 64x KV-cache ಹೆಚ್ಚಳ ಎಂದೂ ಅರ್ಥ ಎಂದೂ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ, ಆದರೆ SSM-state term ಪ್ರಭಾವಿತವಾಗುವುದಿಲ್ಲ (Part 2 ನಲ್ಲಿ N term ಇಲ್ಲ ಎಂದೂ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ) -- ಹೆಚ್ಚಿನ attention layers ಅನ್ನೂ SSM layers ಜೊತೆ ಬದಲಾಯಿಸುವುದೂ ಆಕರ್ಷಕವಾಗುವುದೂ ನಿಖರವಾಗಿ ಇಲ್ಲಿ. Source ಇದೂ ವಿಶೇಷವಾಗಿ ಸಂಬಂಧಿತವಾಗಲು ಆರಂಭಿಸುವ ಪ್ರದೇಶವಾಗಿ ಸುಮಾರು 64k+ ಬಳಸುತ್ತದೆ. ಅದೂ ಗಿಂತ ಕೆಳಗೆ, ಚಿಕ್ಕ context ನಲ್ಲಿ (ಸುಮಾರು 16k ಗಿಂತ ಕಡಿಮೆ), KV cache ಈಗಾಗಲೇ ಚಿಕ್ಕದೂ, ಆದ್ದರಿಂದ ಹೆಚ್ಚಿನ attention ಅನ್ನೂ Mamba ಜೊತೆ ಬದಲಾಯಿಸುವುದೂ ಸ್ವಲ್ಪ memory ಉಳಿಸಬಹುದು ಆದರೆ ಹೊಸ recurrent kernels, hybrid scheduling, ಮತ್ತೆ architectural complexity ಪರಿಚಯಿಸುತ್ತದೆ ಇವು ಸಮರ್ಥಿಸದಿರಬಹುದು -- context ಬೆಳೆದಂತೆ hybrids ಹೆಚ್ಚು ಆಕರ್ಷಕವಾಗುತ್ತವೆ, ಸಾರ್ವತ್ರಿಕವಾಗಿ ಉತ್ತಮ ಅಲ್ಲ.' } },
    { type: 'concept', data: {
      headingEn: 'Case 2 & 3: Mixed Local/Global Tasks, and GPU Memory Constraints', headingKn: 'Case 2 & 3: ಮಿಶ್ರ Local/Global Tasks, ಮತ್ತೆ GPU Memory Constraints',
      bodyEn: 'Case 2: tasks needing both local processing (grammar, syntax, short-range dependencies -- where SSMs excel) and global retrieval (finding a fact 100k tokens earlier -- where attention helps) benefit from letting different mechanisms specialize. Case 3: when GPU VRAM is limited, a pure Transformer\'s KV cache can consume a large portion of available memory; a hybrid reduces that burden, leaving more room for weights, larger batches, and multiple concurrent long-context requests on the same hardware. Where hybrids may LOSE: deep reasoning and multi-document cross-reference tasks needing heavy everywhere-to-everywhere interaction can favor more attention, since sparse attention placement becomes a limitation when many tokens must interact directly with many other tokens.',
      bodyKn: 'Case 2: local processing (grammar, syntax, short-range dependencies -- SSMs ಚೆನ್ನಾಗಿ ಕೆಲಸ ಮಾಡುವಲ್ಲಿ) ಮತ್ತೆ global retrieval (100k tokens ಹಿಂದೆ ಒಂದೂ ಸತ್ಯ ಹುಡುಕುವುದೂ -- attention ಸಹಾಯ ಮಾಡುವಲ್ಲಿ) ಎರಡೂ ಬೇಕಾದ tasks ಭಿನ್ನ ಕಾರ್ಯವಿಧಾನಗಳಿಗೆ ವಿಶೇಷೀಕರಿಸಲು ಬಿಡುವುದೂ ಇಂದ ಪ್ರಯೋಜನ ಪಡೆಯುತ್ತವೆ. Case 3: GPU VRAM ಸೀಮಿತವಾಗಿದ್ದಾಗ, ಒಂದೂ pure Transformer ya KV cache ಲಭ್ಯವಿರುವ memory ya ದೊಡ್ಡ ಭಾಗ ಬಳಸಬಹುದು; ಒಂದೂ hybrid ಆ ಹೊರೆ ಕಡಿಮೆ ಮಾಡುತ್ತದೆ, weights, ದೊಡ್ಡ batches, ಮತ್ತೆ ಅದೇ hardware ಮೇಲೆ ಬಹು ಏಕಕಾಲಿಕ ಉದ್ದ-context requests ಗಾಗಿ ಹೆಚ್ಚೂ ಸ್ಥಳ ಬಿಡುತ್ತದೆ. Hybrids ಎಲ್ಲಿ ಸೋಲಬಹುದು: ಬಹಳ everywhere-to-everywhere interaction ಬೇಕಾದ deep reasoning ಮತ್ತೆ multi-document cross-reference tasks ಹೆಚ್ಚೂ attention ಪರವಾಗಿರಬಹುದು, ಏಕೆಂದರೆ ಹಲವೂ tokens ಹಲವೂ ಇತರೆ tokens ಜೊತೆ ನೇರವಾಗಿ ಸಂವಹನ ನಡೆಸಬೇಕಾದಾಗ sparse attention placement ಒಂದೂ ಮಿತಿಯಾಗುತ್ತದೆ.' } },

    { type: 'heading', data: { textEn: 'Competitive Landscape: Genuinely Comparing Active-Parameter Ratios', textKn: 'ಸ್ಪರ್ಧಾತ್ಮಕ ಭೂದೃಶ್ಯ: Active-Parameter Ratios ಅನ್ನೂ ನಿಜವಾಗಿ ಹೋಲಿಸುವುದೂ', level: 'H2' } },
    { type: 'table', data: {
      captionEn: 'Competitive Landscape (Source\'s Cited Scales)', captionKn: 'ಸ್ಪರ್ಧಾತ್ಮಕ ಭೂದೃಶ್ಯ (Source ya ಉಲ್ಲೇಖಿತ Scales)',
      rows: "Model|Family|Scale in lesson|Main claim\nMamba-2|Pure SSM|3B|Linear time / constant recurrent state\nJamba|Hybrid|52B / 12B active|256k on 80GB\nJamba 1.5 Large|Hybrid|398B / 94B active|Enterprise long-context\nMamba-3|Pure SSM|1.5B (paper model)|Improved state tracking\nDeepSeek-V3|Transformer + MoE|671B / 37B active|Frontier capability" } },
    { type: 'code', data: {
      filename: 'active_ratio_comparison.py', headingEn: 'Genuinely computing and comparing active-parameter ratios', headingKn: 'Active-parameter ratios ಅನ್ನೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಿ ಹೋಲಿಸುವುದೂ',
      descEn: 'Compute active/total for Jamba, Jamba 1.5 Large, and DeepSeek-V3 (genuinely confirmed at 5.51% in Module 204) to compare how aggressively each architecture uses MoE sparsity.',
      descKn: 'ಪ್ರತಿ architecture MoE sparsity ಅನ್ನೂ ಎಷ್ಟೂ ಆಕ್ರಮಣಕಾರಿಯಾಗಿ ಬಳಸುತ್ತದೆ ಎಂದೂ ಹೋಲಿಸಲು Jamba, Jamba 1.5 Large, ಮತ್ತೆ DeepSeek-V3 (Module 204 ನಲ್ಲಿ 5.51% ಎಂದೂ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ) ಗಾಗಿ active/total ಲೆಕ್ಕಹಾಕಿ.',
      code: "models = {\n    'Jamba': (52, 12),\n    'Jamba 1.5 Large': (398, 94),\n    'DeepSeek-V3': (671, 37),\n}\nfor name, (total, active) in models.items():\n    ratio = active / total\n    print(f'{name}: {active}B/{total}B active = {ratio:.4f} ({ratio:.2%})')" } },
    { type: 'output', data: { output: 'Jamba: 12B/52B active = 0.2308 (23.08%)\nJamba 1.5 Large: 94B/398B active = 0.2362 (23.62%)\nDeepSeek-V3: 37B/671B active = 0.0551 (5.51%)' } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: Jamba Uses MoE Far Less Aggressively Than DeepSeek-V3', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: Jamba DeepSeek-V3 ಗಿಂತ MoE ಅನ್ನೂ ಬಹಳ ಕಡಿಮೆ ಆಕ್ರಮಣಕಾರಿಯಾಗಿ ಬಳಸುತ್ತದೆ',
      bodyEn: 'Genuinely computed a striking contrast: Jamba (~23.1%) and Jamba 1.5 Large (~23.6%) have active ratios roughly 4-4.3x HIGHER than DeepSeek-V3\'s genuinely confirmed 5.51% (Module 204). This reveals the two architectures pursue efficiency very differently -- Jamba\'s efficiency story is mostly about REPLACING attention layers with cheap Mamba recurrence (the KV-cache reduction genuinely derived in Part 2), with MoE playing a comparatively modest role in its total/active parameter gap. DeepSeek-V3\'s story is almost entirely about pushing MoE sparsity to an extreme (256 experts, top-8 routed, genuinely confirmed in Module 204) while keeping full attention (compressed via MLA rather than replaced). Neither number is "better" in isolation -- they reflect genuinely different design philosophies for where efficiency comes from.',
      bodyKn: 'ಒಂದೂ ಗಮನಾರ್ಹ ವ್ಯತಿರಿಕ್ತತೆ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಲಾಗಿದೆ: Jamba (~23.1%) ಮತ್ತೆ Jamba 1.5 Large (~23.6%) ಗೆ DeepSeek-V3 ya ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ 5.51% (Module 204) ಗಿಂತ ಸುಮಾರು 4-4.3x ಹೆಚ್ಚಿನ active ratios ಇವೆ. ಇದೂ ಎರಡೂ architectures ಬಹಳ ಭಿನ್ನವಾಗಿ efficiency ಅನುಸರಿಸುತ್ತವೆ ಎಂದೂ ಬಹಿರಂಗಪಡಿಸುತ್ತದೆ -- Jamba ya efficiency ಕಥೆ ಹೆಚ್ಚಾಗಿ attention layers ಅನ್ನೂ ಅಗ್ಗದ Mamba recurrence ಜೊತೆ REPLACING ಬಗ್ಗೆ (Part 2 ನಲ್ಲಿ ನಿಜವಾಗಿ ಪಡೆದ KV-cache reduction), MoE ಅದೂ ya total/active parameter gap ನಲ್ಲಿ ಸಾಪೇಕ್ಷವಾಗಿ ಸಾಧಾರಣ ಪಾತ್ರ ವಹಿಸುತ್ತದೆ. DeepSeek-V3 ya ಕಥೆ ಬಹುತೇಕ ಸಂಪೂರ್ಣವಾಗಿ MoE sparsity ಅನ್ನೂ ಒಂದೂ ತೀವ್ರತೆಗೆ ತಳ್ಳುವುದೂ ಬಗ್ಗೆ (256 experts, top-8 routed, Module 204 ನಲ್ಲಿ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ) ಪೂರ್ಣ attention ಇಡುತ್ತಾ (ಬದಲಾಯಿಸುವ ಬದಲಿಗೆ MLA ಮೂಲಕ ಸಂಕುಚಿತಗೊಳಿಸಲಾಗಿದೆ). ಪ್ರತ್ಯೇಕವಾಗಿ ಯಾವುದೇ ಸಂಖ್ಯೆ "ಉತ್ತಮ" ಅಲ್ಲ -- ಅವು efficiency ಎಲ್ಲಿಂದ ಬರುತ್ತದೆ ಎಂಬುದೂ ಗೆ ನಿಜವಾಗಿ ಭಿನ್ನ design ತತ್ವಗಳನ್ನೂ ಪ್ರತಿಬಿಂಬಿಸುತ್ತವೆ.' } },

    { type: 'diagram', data: {
      titleEn: 'Two Design Philosophies: Replace vs Compress', titleKn: 'ಎರಡೂ Design Philosophies: Replace vs Compress',
      captionEn: 'Jamba reduces attention-layer COUNT (replacing most with Mamba, genuinely confirmed to cut KV cache 8x from 32 to 4 attention layers). DeepSeek-V3-style keeps attention on every layer but compresses ITS memory footprint via MLA (genuinely confirmed 4x smaller than GQA in Module 204), while pushing sparsity into MoE instead.',
      captionKn: 'Jamba attention-layer COUNT ಕಡಿಮೆ ಮಾಡುತ್ತದೆ (ಹೆಚ್ಚಿನದನ್ನೂ Mamba ಜೊತೆ ಬದಲಾಯಿಸುತ್ತದೆ, 32 ಇಂದ 4 attention layers ಗೆ KV cache 8x ಕಡಿಮೆ ಮಾಡುತ್ತದೆ ಎಂದೂ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ). DeepSeek-V3-style ಪ್ರತಿ layer ಮೇಲೆ attention ಇಡುತ್ತದೆ ಆದರೆ MLA ಮೂಲಕ ಅದೂ ya memory footprint ಸಂಕುಚಿತಗೊಳಿಸುತ್ತದೆ (Module 204 ನಲ್ಲಿ GQA ಗಿಂತ 4x ಚಿಕ್ಕದೂ ಎಂದೂ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ), ಬದಲಿಗೆ sparsity ಅನ್ನೂ MoE ಗೆ ತಳ್ಳುತ್ತದೆ.',
      svgCode: "<svg viewBox='0 0 700 140' xmlns='http://www.w3.org/2000/svg'><text x='10' y='15' fill='#94a3b8' font-size='10'>Jamba: replace attention layers</text><rect x='10' y='25' width='40' height='16' fill='#22c55e'/><rect x='55' y='25' width='40' height='16' fill='#22c55e'/><rect x='100' y='25' width='40' height='16' fill='#22c55e'/><rect x='145' y='25' width='40' height='16' fill='#ef4444'/><text x='10' y='55' fill='#e2e8f0' font-size='9'>Only 4 of 32 layers keep full attention (rest -> cheap Mamba)</text><text x='10' y='85' fill='#94a3b8' font-size='10'>DeepSeek-V3 style: compress attention, push sparsity into MoE</text><rect x='10' y='95' width='40' height='16' fill='#3b82f6'/><rect x='55' y='95' width='40' height='16' fill='#3b82f6'/><rect x='100' y='95' width='40' height='16' fill='#3b82f6'/><rect x='145' y='95' width='40' height='16' fill='#3b82f6'/><text x='10' y='125' fill='#e2e8f0' font-size='9'>Every layer keeps (compressed) attention -- MoE experts carry the sparsity instead</text></svg>" } },

    { type: 'concept', data: {
      headingEn: 'Common Misconception', headingKn: 'ಸಾಮಾನ್ಯ ತಪ್ಪುಗ್ರಹಿಕೆ',
      bodyEn: '"A lower active-parameter ratio always means a more efficient architecture." Genuinely computed data complicates this: DeepSeek-V3\'s 5.51% is far lower than Jamba\'s ~23%, but that number alone does not mean Jamba is "worse" -- Jamba achieves its long-context memory efficiency primarily through a completely different mechanism (fewer attention layers, genuinely confirmed via the KV-cache formula in Part 2), which the active-parameter ratio does not capture at all. Comparing architectures fairly requires looking at the SPECIFIC bottleneck each one targets, not a single summary ratio in isolation.',
      bodyKn: '"ಕಡಿಮೆ active-parameter ratio ಯಾವಾಗಲೂ ಹೆಚ್ಚು ಸಮರ್ಥ architecture ಎಂದೂ ಅರ್ಥ." ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಿದ ಡೇಟಾ ಇದನ್ನೂ ಸಂಕೀರ್ಣಗೊಳಿಸುತ್ತದೆ: DeepSeek-V3 ya 5.51% Jamba ya ~23% ಗಿಂತ ಬಹಳ ಕಡಿಮೆ, ಆದರೆ ಆ ಸಂಖ್ಯೆ ಒಂಟಿಯಾಗಿ Jamba "ಕೆಟ್ಟದೂ" ಎಂದೂ ಅರ್ಥವಲ್ಲ -- Jamba ಅದೂ ya ಉದ್ದ-context memory efficiency ಪ್ರಾಥಮಿಕವಾಗಿ ಸಂಪೂರ್ಣವಾಗಿ ಭಿನ್ನ ಕಾರ್ಯವಿಧಾನ ಮೂಲಕ ಸಾಧಿಸುತ್ತದೆ (ಕಡಿಮೆ attention layers, Part 2 ನಲ್ಲಿ KV-cache formula ಮೂಲಕ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ), ಇದನ್ನೂ active-parameter ratio ಸಂಪೂರ್ಣವಾಗಿ ಸೆರೆಹಿಡಿಯುವುದಿಲ್ಲ. Architectures ಅನ್ನೂ ನ್ಯಾಯಯುತವಾಗಿ ಹೋಲಿಸಲು ಪ್ರತಿಯೊಂದೂ ಗುರಿಪಡಿಸುವ ನಿರ್ದಿಷ್ಟ bottleneck ಅನ್ನೂ ನೋಡಬೇಕು, ಒಂಟಿಯಾಗಿ ಒಂದೂ ಸಾರಾಂಶ ratio ಅಲ್ಲ.' } },

    { type: 'concept', data: {
      headingEn: 'Key Terms', headingKn: 'ಮುಖ್ಯ ಪದಗಳು',
      bodyEn: '• Exponential-trapezoidal discretization: Mamba-3\'s richer discrete state-transition rule, preserving more of the continuous h(t)=e^{At}h(0) structure than Mamba-2\'s Euler-style step\n• Complex-valued state: rotational (magnitude+phase) state dynamics restored in Mamba-3, behaving like a data-dependent rotary embedding on the recurrent state\n• MIMO projections: matrix-valued (not per-feature scalar) state projections, improving both representational richness and hardware utilization\n• Active-parameter ratio: genuinely confirmed 12/52=23.08% (Jamba), 94/398=23.62% (Jamba 1.5 Large), 37/671=5.51% (DeepSeek-V3) -- a measure of MoE aggressiveness, not overall architectural quality\n• Replace vs compress: Jamba\'s philosophy reduces attention LAYER COUNT; DeepSeek-V3-style keeps attention everywhere but compresses its memory footprint (MLA) while pushing sparsity into MoE instead',
      bodyKn: '• Exponential-trapezoidal discretization: Mamba-3 ya ಶ್ರೀಮಂತ discrete state-transition rule, Mamba-2 ya Euler-style step ಗಿಂತ continuous h(t)=e^{At}h(0) structure ya ಹೆಚ್ಚಿನದನ್ನೂ ಸಂರಕ್ಷಿಸುತ್ತದೆ\n• Complex-valued state: Mamba-3 ನಲ್ಲಿ ಮರುಸ್ಥಾಪಿಸಿದ rotational (magnitude+phase) state dynamics, recurrent state ಮೇಲೆ ಒಂದೂ data-dependent rotary embedding ನಂತೆ ವರ್ತಿಸುತ್ತದೆ\n• MIMO projections: matrix-valued (per-feature scalar ಅಲ್ಲ) state projections, representational richness ಮತ್ತೆ hardware utilization ಎರಡನ್ನೂ ಸುಧಾರಿಸುತ್ತದೆ\n• Active-parameter ratio: 12/52=23.08% (Jamba), 94/398=23.62% (Jamba 1.5 Large), 37/671=5.51% (DeepSeek-V3) ಎಂದೂ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ -- MoE ಆಕ್ರಮಣಶೀಲತೆಯ ಒಂದೂ ಅಳತೆ, ಒಟ್ಟಾರೆ architectural quality ಅಲ್ಲ\n• Replace vs compress: Jamba ya ತತ್ವ attention LAYER COUNT ಕಡಿಮೆ ಮಾಡುತ್ತದೆ; DeepSeek-V3-style ಎಲ್ಲೆಡೆ attention ಇಡುತ್ತದೆ ಆದರೆ ಅದೂ ya memory footprint ಸಂಕುಚಿತಗೊಳಿಸುತ್ತದೆ (MLA) ಬದಲಿಗೆ sparsity ಅನ್ನೂ MoE ಗೆ ತಳ್ಳುತ್ತದೆ' } },

    { type: 'concept', data: {
      headingEn: 'Key Takeaways', headingKn: 'ಮುಖ್ಯ ಅಂಶಗಳು',
      bodyEn: "• Mamba-3 adds three innovations to make the SSM side more expressive without losing efficiency: exponential-trapezoidal discretization, complex-valued state updates, and MIMO projections.\n• Genuinely computed Mamba-3's reported gain: 0.6+1.2=1.8 points over Gated DeltaNet at ~1.5B scale -- with an explicit source caveat that Mamba-3 is not yet shipping in a production hybrid.\n• Genuinely computed a 64x context increase (4k->256k) means a 64x KV-cache increase for attention layers but zero change for SSM state -- the structural reason hybrids become more attractive as context grows, roughly around 64k+ per the source.\n• Hybrids can lose to attention-heavy architectures on deep reasoning and multi-document cross-reference tasks needing heavy everywhere-to-everywhere interaction.\n• Genuinely computed and contrasted active-parameter ratios: Jamba (~23.1%) and Jamba 1.5 Large (~23.6%) are roughly 4-4.3x higher than DeepSeek-V3's 5.51% (Module 204) -- revealing Jamba's efficiency comes mainly from replacing attention layers, while DeepSeek-V3's comes mainly from aggressive MoE sparsity with compressed (not replaced) attention.\n• Neither design philosophy is universally 'better' -- Jamba = SSM efficiency + attention recall + MoE capacity, while MLA-style Transformers keep full attention everywhere but compress its cost -- both are valid answers to the same underlying memory/compute bottleneck.",
      bodyKn: '• Mamba-3 SSM ಬದಿಯನ್ನೂ efficiency ಕಳೆದುಕೊಳ್ಳದೆ ಹೆಚ್ಚು ಅಭಿವ್ಯಕ್ತಿಶೀಲಗೊಳಿಸಲು ಮೂರೂ innovations ಸೇರಿಸುತ್ತದೆ: exponential-trapezoidal discretization, complex-valued state updates, ಮತ್ತೆ MIMO projections.\n• Mamba-3 ya ವರದಿ ಮಾಡಿದ gain ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಲಾಗಿದೆ: ~1.5B scale ನಲ್ಲಿ Gated DeltaNet ಎದುರೂ 0.6+1.2=1.8 points -- Mamba-3 ಇನ್ನೂ ಒಂದೂ production hybrid ನಲ್ಲಿ ಸಾಗಿಸುತ್ತಿಲ್ಲ ಎಂಬ ಸ್ಪಷ್ಟ source caveat ಜೊತೆ.\n• 64x context ಹೆಚ್ಚಳ (4k->256k) attention layers ಗೆ 64x KV-cache ಹೆಚ್ಚಳ ಆದರೆ SSM state ಗೆ ಶೂನ್ಯ ಬದಲಾವಣೆ ಎಂದೂ ಅರ್ಥ ಎಂದೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಲಾಗಿದೆ -- source ಪ್ರಕಾರ ಸುಮಾರು 64k+ ಸುತ್ತ, context ಬೆಳೆದಂತೆ hybrids ಹೆಚ್ಚು ಆಕರ್ಷಕವಾಗುವುದೂ ಗೆ ರಚನಾತ್ಮಕ ಕಾರಣ.\n• Bahaḷa everywhere-to-everywhere interaction ಬೇಕಾದ deep reasoning ಮತ್ತೆ multi-document cross-reference tasks ಮೇಲೆ hybrids attention-heavy architectures ಗೆ ಸೋಲಬಹುದು.\n• Active-parameter ratios ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಲಾಗಿದೆ ಮತ್ತೆ ವ್ಯತಿರಿಕ್ತಗೊಳಿಸಲಾಗಿದೆ: Jamba (~23.1%) ಮತ್ತೆ Jamba 1.5 Large (~23.6%) DeepSeek-V3 ya 5.51% (Module 204) ಗಿಂತ ಸುಮಾರು 4-4.3x ಹೆಚ್ಚು -- Jamba ya efficiency ಮುಖ್ಯವಾಗಿ attention layers ಬದಲಾಯಿಸುವುದೂ ಇಂದ ಬರುತ್ತದೆ ಎಂದೂ ಬಹಿರಂಗಪಡಿಸುತ್ತದೆ, ಆದರೆ DeepSeek-V3 ya ಮುಖ್ಯವಾಗಿ ಆಕ್ರಮಣಕಾರಿ MoE sparsity ಇಂದ compressed (ಬದಲಾಯಿಸಿದ ಅಲ್ಲ) attention ಜೊತೆ ಬರುತ್ತದೆ.\n• ಯಾವುದೇ design ತತ್ವ ಸಾರ್ವತ್ರಿಕವಾಗಿ "ಉತ್ತಮ" ಅಲ್ಲ -- Jamba = SSM efficiency + attention recall + MoE capacity, ಆದರೆ MLA-style Transformers ಎಲ್ಲೆಡೆ ಪೂರ್ಣ attention ಇಡುತ್ತವೆ ಆದರೆ ಅದೂ ya ವೆಚ್ಚ ಸಂಕುಚಿತಗೊಳಿಸುತ್ತವೆ -- ಎರಡೂ ಅದೇ ಮೂಲಭೂತ memory/compute bottleneck ಗೆ ಮಾನ್ಯ ಉತ್ತರಗಳು.' } },

    { type: 'concept', data: {
      headingEn: 'Module Wrap-Up: The Full Jamba Story', headingKn: 'Module Wrap-Up: ಪೂರ್ಣ Jamba ಕಥೆ',
      bodyEn: 'Across all three parts: Part 1 established the fundamental tradeoff (attention: strong recall, growing KV cache; SSM: fixed state, compressed history), genuinely confirmed the SSM recurrence needs only the previous state via a toy simulation, and genuinely computed a 256k attention map has 65.5 billion entries. Part 2 derived Jamba\'s actual 1:7 ratio (28 Mamba + 4 attention for 32 layers, genuinely confirmed) and the KV-cache/SSM-state formulas -- with an honest finding that the source\'s own cited Jamba KV-cache figure (~8.4GB) is internally inconsistent with its own stated L_A=4 (which genuinely computes to 16.0 GiB), even though the comparison Pure-Transformer and GQA figures check out exactly. Part 3 covered Mamba-3\'s three innovations, genuinely confirmed its 1.8-point reported gain, genuinely computed the 64x context-growth factor motivating hybrids, and genuinely contrasted Jamba\'s ~23% active-parameter ratio against DeepSeek-V3\'s 5.51% to reveal two genuinely different efficiency philosophies: replace attention (Jamba) versus compress it while pushing sparsity into MoE (DeepSeek-V3-style). The throughline: distributed-training-scale efficiency is never one trick -- it is a stack of complementary, independently verifiable mechanisms, each targeting a different bottleneck.',
      bodyKn: 'ಎಲ್ಲಾ ಮೂರೂ ಭಾಗಗಳಾದ್ಯಂತ: Part 1 ಮೂಲಭೂತ tradeoff ಸ್ಥಾಪಿಸಿತೂ (attention: ಬಲಿಷ್ಠ recall, ಬೆಳೆಯುತ್ತಿರುವ KV cache; SSM: ಸ್ಥಿರ state, ಸಂಕುಚಿತ history), ಒಂದೂ toy simulation ಮೂಲಕ SSM recurrence ಗೆ ಕೇವಲ ಹಿಂದಿನ state ಬೇಕು ಎಂದೂ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿತೂ, ಮತ್ತೆ ಒಂದೂ 256k attention map ಗೆ 65.5 ಬಿಲಿಯನ್ entries ಇವೆ ಎಂದೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಿತೂ. Part 2 Jamba ya ನಿಜ 1:7 ratio (32 layers ಗೆ 28 Mamba + 4 attention, ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ) ಮತ್ತೆ KV-cache/SSM-state formulas ಪಡೆಯಿತೂ -- source ya ಸ್ವಂತ ಉಲ್ಲೇಖಿತ Jamba KV-cache ಅಂಕಿಅಂಶ (~8.4GB) ಅದೂ ya ಸ್ವಂತ ಹೇಳಿಕೆಯ L_A=4 (ಇದೂ ನಿಜವಾಗಿ 16.0 GiB ಗೆ ಲೆಕ್ಕಹಾಕುತ್ತದೆ) ಜೊತೆ ಆಂತರಿಕವಾಗಿ ಅಸಂಗತ ಎಂಬ ಪ್ರಾಮಾಣಿಕ finding ಜೊತೆ, ಹೋಲಿಕೆ Pure-Transformer ಮತ್ತೆ GQA ಅಂಕಿಅಂಶಗಳು ನಿಖರವಾಗಿ ಸರಿಹೊಂದಿದರೂ. Part 3 Mamba-3 ya ಮೂರೂ innovations ಒಳಗೊಂಡಿತೂ, ಅದೂ ya 1.8-point ವರದಿ ಮಾಡಿದ gain ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿತೂ, hybrids ಗೆ ಪ್ರೇರೇಪಿಸುವ 64x context-growth factor ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಿತೂ, ಮತ್ತೆ Jamba ya ~23% active-parameter ratio ಅನ್ನೂ DeepSeek-V3 ya 5.51% ಎದುರೂ ನಿಜವಾಗಿ ವ್ಯತಿರಿಕ್ತಗೊಳಿಸಿತೂ ಎರಡೂ ನಿಜವಾಗಿ ಭಿನ್ನ efficiency ತತ್ವಗಳನ್ನೂ ಬಹಿರಂಗಪಡಿಸಲು: attention ಬದಲಾಯಿಸುವುದೂ (Jamba) vs ಅದನ್ನೂ ಸಂಕುಚಿತಗೊಳಿಸುತ್ತಾ sparsity ಅನ್ನೂ MoE ಗೆ ತಳ್ಳುವುದೂ (DeepSeek-V3-style). ಸಾಮಾನ್ಯ ಎಳೆ: distributed-training-scale efficiency ಎಂದಿಗೂ ಒಂದೂ ಟ್ರಿಕ್ ಅಲ್ಲ -- ಇದೂ ಪೂರಕ, ಸ್ವತಂತ್ರವಾಗಿ ಪರಿಶೀಲಿಸಬಹುದಾದ ಕಾರ್ಯವಿಧಾನಗಳ ಒಂದೂ stack, ಪ್ರತಿಯೊಂದೂ ಭಿನ್ನ bottleneck ಗುರಿಪಡಿಸುತ್ತದೆ.' } },

    { type: 'quiz', data: { questions: [
      { q: 'What is the main purpose of Mamba-3\'s exponential-trapezoidal discretization?',
        qKn: 'Mamba-3 ya exponential-trapezoidal discretization ya ಮುಖ್ಯ ಉದ್ದೇಶ ಏನೂ?',
        opts: ['Increase vocabulary size', 'Make recurrent state evolution more expressive', 'Replace MoE routing', 'Remove the state entirely'], correct: 1,
        optsKn: ['Vocabulary size ಹೆಚ್ಚಿಸುವುದೂ', 'Recurrent state evolution ಅನ್ನೂ ಹೆಚ್ಚು ಅಭಿವ್ಯಕ್ತಿಶೀಲಗೊಳಿಸುವುದೂ', 'MoE routing ಬದಲಾಯಿಸುವುದೂ', 'State ಅನ್ನೂ ಸಂಪೂರ್ಣವಾಗಿ ತೆಗೆದುಹಾಕುವುದೂ'] },
      { q: 'Genuinely confirmed: what is Mamba-3\'s total reported accuracy improvement over Gated DeltaNet (base + MIMO)?',
        qKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: Gated DeltaNet ಎದುರೂ Mamba-3 ya ಒಟ್ಟೂ ವರದಿ ಮಾಡಿದ accuracy improvement (base + MIMO) ಏನೂ?',
        opts: ['0.6 points', '1.2 points', '1.8 points', '2.4 points'], correct: 2,
        optsKn: ['0.6 points', '1.2 points', '1.8 points', '2.4 points'] },
      { q: 'Genuinely confirmed: increasing context from 4k to 256k grows KV-cache memory by what factor?',
        qKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: context ಅನ್ನೂ 4k ಇಂದ 256k ಗೆ ಹೆಚ್ಚಿಸುವುದೂ KV-cache memory ಅನ್ನೂ ಎಷ್ಟೂ factor ಇಂದ ಬೆಳೆಸುತ್ತದೆ?',
        opts: ['4x', '16x', '64x', '256x'], correct: 2,
        optsKn: ['4x', '16x', '64x', '256x'] },
      { q: 'Genuinely confirmed: which model has the LOWEST active-parameter ratio among those compared?',
        qKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: ಹೋಲಿಸಿದ ಇವುಗಳಲ್ಲಿ ಯಾವ model ಗೆ ಅತ್ಯಂತ ಕಡಿಮೆ active-parameter ratio ಇದೆ?',
        opts: ['Jamba', 'Jamba 1.5 Large', 'DeepSeek-V3', 'They are all equal'], correct: 2,
        optsKn: ['Jamba', 'Jamba 1.5 Large', 'DeepSeek-V3', 'ಎಲ್ಲಾ ಸಮಾನ'] },
      { q: 'Why might a hybrid SSM-Transformer lose to a more attention-heavy architecture?',
        qKn: 'ಒಂದೂ hybrid SSM-Transformer ಹೆಚ್ಚು attention-heavy architecture ಗೆ ಏಕೆ ಸೋಲಬಹುದು?',
        opts: ['Hybrids cannot process any tokens', 'On deep reasoning and multi-document cross-reference tasks needing heavy everywhere-to-everywhere interaction', 'Hybrids always require more GPU memory', 'SSMs cannot run on modern hardware'], correct: 1,
        optsKn: ['Hybrids ಯಾವುದೇ tokens ಸಂಸ್ಕರಿಸಲು ಸಾಧ್ಯವಿಲ್ಲ', 'ಬಹಳ everywhere-to-everywhere interaction ಬೇಕಾದ deep reasoning ಮತ್ತೆ multi-document cross-reference tasks ಮೇಲೆ', 'Hybrids ಗೆ ಯಾವಾಗಲೂ ಹೆಚ್ಚೂ GPU memory ಬೇಕು', 'SSMs ಆಧುನಿಕ hardware ಮೇಲೆ ಓಡಲು ಸಾಧ್ಯವಿಲ್ಲ'] },
    ] } },
  ],
};
