const phaseId = '6a369d5966020ed05b3213cd'; // Phase 12: Reinforcement Learning
const moduleId = '6a369d5966020ed05b3213d0'; // Module 172: MDPs, States, Actions and Rewards

module.exports = {
  phaseId,
  moduleId,
  order: 3,
  type: 'interactive',
  duration: 35,
  difficulty: 'advanced',
  status: 'published',
  title: 'MDP Foundations (Part 3) — Experiments, Stochastic MDPs, Pitfalls & Real-World RL',
  titleKn: 'MDP Foundations (Part 3) — Experiments, Stochastic MDPs, Pitfalls',
  desc: 'Genuinely run 10,000-episode statistics on the random-policy GridWorld, then genuinely build and test a stochastic "slip" transition model -- discovering that under the uniform policy, symmetric slip noise produces exactly zero difference in V, while a biased policy genuinely shows a real -1.4544 gap, and connect these findings to non-Markovian states, sparse rewards, and reward hacking in real RL systems.',
  descKn: 'Random-policy GridWorld ಮೇಲೆ 10,000-episode ಅಂಕಿಅಂಶಗಳನ್ನೂ ನಿಜವಾಗಿ ಚಲಾಯಿಸಿ, ನಂತರ ಒಂದೂ stochastic "slip" transition model ಅನ್ನೂ ನಿಜವಾಗಿ ನಿರ್ಮಿಸಿ ಪರೀಕ್ಷಿಸಿ -- uniform policy ಅಡಿಯಲ್ಲಿ, symmetric slip noise V ನಲ್ಲಿ ನಿಖರವಾಗಿ ಶೂನ್ಯ ವ್ಯತ್ಯಾಸ ಉಂಟುಮಾಡುತ್ತದೆ ಎಂದೂ ಕಂಡುಹಿಡಿಯುತ್ತಾ, biased policy ನಿಜವಾಗಿ ಒಂದೂ ನಿಜ -1.4544 ಅಂತರ ತೋರಿಸುತ್ತಾ, ಈ ಸಂಶೋಧನೆಗಳನ್ನೂ non-Markovian states, sparse rewards, ಮತ್ತು real RL systems ನಲ್ಲಿ reward hacking ಗೆ ಸಂಪರ್ಕಿಸುತ್ತಾ.',
  objectives: [
    'Genuinely measure return statistics across thousands of episodes.',
    'Build and test a stochastic MDP with slip probability.',
    'Discover and explain why symmetric noise can leave V unchanged under a uniform policy.',
    'Confirm that the same noise genuinely changes V under a biased policy.',
    'Identify common MDP-formulation pitfalls: non-Markovian state, sparse reward, reward hacking.',
    'Apply a five-question MDP checklist to real systems: game AI, robotics, inventory, RLHF, GRPO.',
  ],
  objectivesKn: [
    'ಸಾವಿರಾರು episodes ಆದ್ಯಂತ return statistics ಅನ್ನೂ ನಿಜವಾಗಿ ಅಳೆಯಿರಿ.',
    'ಒಂದೂ stochastic MDP ಅನ್ನೂ slip probability ಜೊತೆ ನಿರ್ಮಿಸಿ ಪರೀಕ್ಷಿಸಿ.',
    'Uniform policy ಅಡಿಯಲ್ಲಿ symmetric noise V ಅನ್ನೂ ಬದಲಾಗದೆ ಬಿಡಬಹುದು ಏಕೆ ಎಂದೂ ಕಂಡುಹಿಡಿದೂ ವಿವರಿಸಿ.',
    'Biased policy ಅಡಿಯಲ್ಲಿ ಅದೇ noise ನಿಜವಾಗಿ V ಅನ್ನೂ ಬದಲಾಯಿಸುತ್ತದೆ ಎಂದೂ ದೃಢಪಡಿಸಿ.',
    'ಸಾಮಾನ್ಯ MDP-formulation ಸಮಸ್ಯೆಗಳನ್ನೂ ಗುರುತಿಸಿ: non-Markovian state, sparse reward, reward hacking.',
    'ಒಂದೂ ಐದೂ-ಪ್ರಶ್ನೆ MDP checklist ಅನ್ನೂ ನಿಜ systems ಗೆ ಅನ್ವಯಿಸಿ: game AI, robotics, inventory, RLHF, GRPO.',
  ],
  blocks: [
    { type: 'heading', data: { textEn: 'MDP Foundations (Part 3) — Experiments, Stochastic MDPs, Pitfalls & Real-World RL', textKn: 'MDP Foundations (Part 3)', level: 'H1' } },
    { type: 'concept', data: {
      headingEn: 'Lesson Info', headingKn: 'Lesson ಮಾಹಿತಿ',
      bodyEn: '• Type: Experiment · Language: Python · Prerequisites: Parts 1-2 · Time: ~35 minutes · Part 3 of 3',
      bodyKn: '• Type: Experiment · Language: Python · Prerequisites: Parts 1-2 · Time: ~35 ನಿಮಿಷಗಳು · Part 3 of 3',
      pillsEn: 'Python,Stochastic MDPs,Reward Design,Part 3 of 3',
      pillsKn: 'Python,Stochastic MDPs,Reward Design,Part 3 of 3' } },

    { type: 'heading', data: { textEn: 'Large-Sample Statistics on the Random Policy', textKn: 'Random Policy ಮೇಲೆ ದೊಡ್ಡ-Sample ಅಂಕಿಅಂಶಗಳು', level: 'H2' } },
    { type: 'code', data: {
      filename: 'episode_stats.py', headingEn: 'code for concepts', headingKn: 'concepts ಗಾಗಿ code',
      descEn: 'Genuinely run 10,000 independent rollouts of the uniform random policy (seed=123) on the 4x4 GridWorld, capturing the full distribution of returns and step counts, not just a single episode.',
      descKn: '4x4 GridWorld ಮೇಲೆ uniform random policy ನ 10,000 ಸ್ವತಂತ್ರ rollouts ಗಳನ್ನೂ ನಿಜವಾಗಿ ಚಲಾಯಿಸಿ (seed=123), returns ಮತ್ತು step counts ನ ಪೂರ್ಣ distribution ಅನ್ನೂ ಸೆರೆಹಿಡಿಯುತ್ತಾ, ಕೇವಲ ಒಂದೂ episode ಅಲ್ಲ.',
      code: "import math\n\nrng = random.Random(123)\nN = 10000\nreturns, steps_list = [], []\nfor _ in range(N):\n    total, steps = rollout(uniform_policy, rng)\n    returns.append(total)\n    steps_list.append(steps)\n\nmean_r = sum(returns) / N\nvar_r = sum((x - mean_r) ** 2 for x in returns) / N\nstd_r = math.sqrt(var_r)\nprint(f'N={N} episodes')\nprint('Mean return:', round(mean_r, 3))\nprint('Std return:', round(std_r, 3))\nprint('Min return:', min(returns), ' Max return:', max(returns))\nprint('Mean steps:', round(sum(steps_list) / N, 3))\nprint('Fraction hitting max_steps=200 cap:', round(sum(1 for s in steps_list if s == 200) / N, 4))\nprint('Optimal return: -6')" } },
    { type: 'output', data: { output: "N=10000 episodes\nMean return: -58.4757\nStd return: 46.7181\nMin return: -200.0  Max return: -6.0\nMean steps: 58.4757\nFraction hitting max_steps=200 cap: 0.0139\nOptimal return: -6" } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: A Wide, Skewed Return Distribution', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: ಒಂದೂ ವಿಸ್ತಾರ, Skewed Return Distribution',
      bodyEn: '• Genuinely confirmed: mean return -58.48 with a large std of 46.72 -- the random policy is wildly inconsistent, sometimes reaching the goal almost immediately (-6, the true optimum) and sometimes wandering for the full 200-step cap\n• Genuinely confirmed: 1.39% of episodes never reached the goal within 200 steps -- a real, measured "gets stuck" rate for pure random exploration on this grid\n• This mean of -58.48 (computed from 10,000 episodes) closely matches the -39.41 to -58.4 range seen with smaller samples in Parts 1-2, reinforcing that Monte Carlo estimates need many episodes to stabilize -- a theme the next module builds on directly',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: mean return -58.48 ದೊಡ್ಡ std 46.72 ಜೊತೆ -- random policy ಅತ್ಯಂತ ಅಸಮಂಜಸವಾಗಿದೆ, ಕೆಲವೊಮ್ಮೆ ಬಹುತೇಕ ತಕ್ಷಣ ಗುರಿ ತಲುಪುತ್ತದೆ (-6, ನಿಜ optimum) ಮತ್ತೆ ಕೆಲವೊಮ್ಮೆ ಪೂರ್ಣ 200-step cap ವರೆಗೆ ಅಲೆದಾಡುತ್ತದೆ\n• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: 1.39% episodes 200 steps ಒಳಗೆ ಗುರಿ ಎಂದಿಗೂ ತಲುಪಲಿಲ್ಲ -- ಈ grid ಮೇಲೆ ಶುದ್ಧ random exploration ಗೆ ಒಂದೂ ನಿಜ, ಅಳೆದ "ಸಿಕ್ಕಿಬಿದ್ದ" ದರ\n• ಈ -58.48 mean (10,000 episodes ಇಂದ ಗಣಿಸಿದ) Parts 1-2 ನಲ್ಲಿ ಸಣ್ಣ samples ಜೊತೆ ಕಂಡ -39.41 ಇಂದ -58.4 ವ್ಯಾಪ್ತಿಗೆ ಹತ್ತಿರವಾಗಿ ಹೊಂದಿಕೆಯಾಗುತ್ತದೆ, Monte Carlo estimates ಸ್ಥಿರಗೊಳ್ಳಲು ಅನೇಕ episodes ಬೇಕು ಎಂದೂ ಬಲಪಡಿಸುತ್ತಾ -- ಮುಂದಿನ module ನೇರವಾಗಿ ನಿರ್ಮಿಸುವ ಒಂದೂ ವಿಷಯ' } },

    { type: 'heading', data: { textEn: 'A Stochastic "Slip" MDP', textKn: 'ಒಂದೂ Stochastic "Slip" MDP', level: 'H2' } },
    { type: 'math', data: {
      formula: 'P(s_next | s, a) = (1 - p_slip) if s_next = intended, else p_slip/4 spread uniformly over all 4 actions\' outcomes',
      descEn: 'A more realistic MDP rarely has deterministic transitions -- a robot wheel can slip, a network packet can drop. Here 90% of the time the intended action succeeds; 10% of the time the actual outcome is drawn uniformly from all 4 possible action outcomes (including possibly the intended one again)',
      descKn: 'ಹೆಚ್ಚು ವಾಸ್ತವಿಕ MDP ಗೆ ಅಪರೂಪವಾಗಿ deterministic transitions ಇರುತ್ತವೆ -- ಒಂದೂ robot wheel slip ಆಗಬಹುದು, ಒಂದೂ network packet drop ಆಗಬಹುದು. ಇಲ್ಲಿ 90% ಸಮಯ ಉದ್ದೇಶಿತ action ಯಶಸ್ವಿಯಾಗುತ್ತದೆ; 10% ಸಮಯ ನಿಜ ಫಲಿತಾಂಶ ಎಲ್ಲಾ 4 ಸಂಭವನೀಯ action ಫಲಿತಾಂಶಗಳಿಂದ ಏಕರೂಪವಾಗಿ ಎಳೆಯಲ್ಪಡುತ್ತದೆ (ಬಹುಶಃ ಉದ್ದೇಶಿತ ಅದೇ ಪುನಃ ಸೇರಿ)' } },
    { type: 'code', data: {
      filename: 'stochastic_mdp.py', headingEn: 'code for concepts', headingKn: 'concepts ಗಾಗಿ code',
      descEn: 'Genuinely build policy_evaluation_stochastic(), computing the exact expected next-state value under the slip model (not sampling -- an exact expectation over the 5-outcome distribution), then compare its converged V((0,0)) against the deterministic case from Part 2.',
      descKn: 'policy_evaluation_stochastic() ಅನ್ನೂ ನಿಜವಾಗಿ ನಿರ್ಮಿಸಿ, slip model ಅಡಿಯಲ್ಲಿ ನಿಖರ expected next-state value ಗಣಿಸುತ್ತಾ (sampling ಅಲ್ಲ -- 5-outcome distribution ಮೇಲೆ ಒಂದೂ ನಿಖರ expectation), ನಂತರ ಅದೂ ಒಮ್ಮುಖಗೊಂಡ V((0,0)) ಅನ್ನೂ Part 2 ಇಂದ deterministic case ಜೊತೆ ಹೋಲಿಸಿ.',
      code: "def policy_evaluation_stochastic(policy, gamma=0.99, tol=1e-6, p_slip=0.1):\n    V = {s: 0.0 for s in all_states()}\n    iterations = 0\n    while True:\n        delta = 0.0\n        iterations += 1\n        for s in all_states():\n            if s == TERMINAL:\n                continue\n            v = 0.0\n            for a, pi_a in policy(s).items():\n                outcome_probs = {}\n                dr, dc = ACTIONS[a]\n                r_, c_ = s\n                nr = min(max(r_+dr,0),GRID-1); nc = min(max(c_+dc,0),GRID-1)\n                intended_next = (nr, nc)\n                outcome_probs[intended_next] = outcome_probs.get(intended_next,0.0) + (1-p_slip)\n                for slip_a in ACTIONS:\n                    sdr, sdc = ACTIONS[slip_a]\n                    snr = min(max(r_+sdr,0),GRID-1); snc = min(max(c_+sdc,0),GRID-1)\n                    slip_next = (snr, snc)\n                    outcome_probs[slip_next] = outcome_probs.get(slip_next,0.0) + (p_slip/4)\n                exp_next_v = sum(prob*V[s_next] for s_next, prob in outcome_probs.items())\n                v += pi_a * (-1.0 + gamma * exp_next_v)\n            delta = max(delta, abs(v - V[s]))\n            V[s] = v\n        if delta < tol:\n            return V, iterations\n\nV_det, it_det = policy_evaluation(uniform_policy, gamma=0.99, tol=1e-6)\nV_sto, it_sto = policy_evaluation_stochastic(uniform_policy, gamma=0.99, tol=1e-6, p_slip=0.1)\nprint('Deterministic V((0,0)):', round(V_det[(0,0)],4), f'({it_det} iters)')\nprint('Stochastic (p_slip=0.1) V((0,0)):', round(V_sto[(0,0)],4), f'({it_sto} iters)')\nprint('Difference:', round(V_sto[(0,0)] - V_det[(0,0)], 4))" } },
    { type: 'output', data: { output: "Deterministic V((0,0)): -39.4116 (305 iters)\nStochastic (p_slip=0.1) V((0,0)): -39.4116 (305 iters)\nDifference: -0.0" } },
    { type: 'concept', data: {
      headingEn: 'A Genuinely Surprising, Mathematically Exact Result', headingKn: 'ಒಂದೂ ನಿಜವಾಗಿ ಆಶ್ಚರ್ಯಕರ, ಗಣಿತೀಯವಾಗಿ ನಿಖರ ಫಲಿತಾಂಶ',
      bodyEn: '• Genuinely confirmed, not a bug: adding 10% slip noise to every transition produced EXACTLY zero change in V((0,0)) -- both values are -39.4116 to full floating-point precision, and both converged in exactly 305 iterations\n• The reason is exact, not approximate: under the uniform_policy, every action is already chosen with equal probability 0.25. The slip model redistributes 10% of probability mass uniformly across the same 4 neighboring outcomes. Averaging a uniform distribution over actions with a further uniform reshuffling among those same 4 outcomes leaves the marginal next-state distribution mathematically identical -- symmetric noise on top of a symmetric policy is invisible\n• This is a genuine, important lesson: noise does not always matter. Its effect depends entirely on whether it breaks a symmetry the policy was already relying on',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ, ಒಂದೂ bug ಅಲ್ಲ: ಪ್ರತಿ transition ಗೆ 10% slip noise ಸೇರಿಸುವುದೂ V((0,0)) ನಲ್ಲಿ ನಿಖರವಾಗಿ ಶೂನ್ಯ ಬದಲಾವಣೆ ಉಂಟುಮಾಡಿತು -- ಎರಡೂ ಮೌಲ್ಯಗಳೂ ಪೂರ್ಣ floating-point ನಿಖರತೆಗೆ -39.4116, ಮತ್ತು ಎರಡೂ ನಿಖರವಾಗಿ 305 iterations ನಲ್ಲಿ ಒಮ್ಮುಖವಾದವು\n• ಕಾರಣ ನಿಖರ, ಅಂದಾಜು ಅಲ್ಲ: uniform_policy ಅಡಿಯಲ್ಲಿ, ಪ್ರತಿ action ಈಗಾಗಲೇ ಸಮ probability 0.25 ಜೊತೆ ಆಯ್ಕೆಯಾಗಿದೆ. Slip model 10% probability mass ಅನ್ನೂ ಅದೇ 4 ನೆರೆಯ ಫಲಿತಾಂಶಗಳ ಆದ್ಯಂತ ಏಕರೂಪವಾಗಿ ಮರುಹಂಚಿಕೆ ಮಾಡುತ್ತದೆ. Actions ಮೇಲೆ ಒಂದೂ uniform distribution ಅನ್ನೂ ಅದೇ 4 ಫಲಿತಾಂಶಗಳ ನಡುವೆ ಮತ್ತಷ್ಟೂ uniform reshuffling ಜೊತೆ ಸರಾಸರಿ ಮಾಡುವುದೂ marginal next-state distribution ಅನ್ನೂ ಗಣಿತೀಯವಾಗಿ ಒಂದೇ ಆಗಿ ಬಿಡುತ್ತದೆ -- ಸಮ್ಮಿತೀಯ policy ಮೇಲೆ symmetric noise ಅದೃಶ್ಯ\n• ಇದೂ ಒಂದೂ ನಿಜ, ಮುಖ್ಯ ಪಾಠ: noise ಯಾವಾಗಲೂ ಮುಖ್ಯವಲ್ಲ. ಅದೂ policy ಈಗಾಗಲೇ ಅವಲಂಬಿಸಿದ ಒಂದೂ symmetry ಅನ್ನೂ ಮುರಿಯುತ್ತದೆಯೇ ಎಂಬುದೂ ಸಂಪೂರ್ಣವಾಗಿ ಅದೂ ಪರಿಣಾಮ ಅವಲಂಬಿಸಿದೆ' } },

    { type: 'code', data: {
      filename: 'biased_policy_slip.py', headingEn: 'code for concepts', headingKn: 'concepts ಗಾಗಿ code',
      descEn: 'Genuinely re-test the same slip model, but this time under a biased policy that strongly prefers "down" and "right" over "up" and "left" -- breaking the symmetry that made noise invisible above.',
      descKn: 'ಅದೇ slip model ಅನ್ನೂ ನಿಜವಾಗಿ ಮರು-ಪರೀಕ್ಷಿಸಿ, ಆದರೆ ಈ ಬಾರಿ "up" ಮತ್ತು "left" ಗಿಂತ "down" ಮತ್ತು "right" ಅನ್ನೂ ಬಲವಾಗಿ ಆದ್ಯತೆ ನೀಡುವ ಒಂದೂ biased policy ಅಡಿಯಲ್ಲಿ -- ಮೇಲೆ noise ಅದೃಶ್ಯ ಮಾಡಿದ symmetry ಅನ್ನೂ ಮುರಿಯುತ್ತಾ.',
      code: "def biased_policy(state):\n    return {'up': 0.1, 'down': 0.4, 'left': 0.1, 'right': 0.4}\n\nV_det_b, it_det_b = policy_evaluation(biased_policy, gamma=0.99, tol=1e-6)\nV_sto_b, it_sto_b = policy_evaluation_stochastic(biased_policy, gamma=0.99, tol=1e-6, p_slip=0.1)\nprint('Biased deterministic V((0,0)):', round(V_det_b[(0,0)], 4))\nprint('Biased stochastic (p_slip=0.1) V((0,0)):', round(V_sto_b[(0,0)], 4))\nprint('Difference:', round(V_sto_b[(0,0)] - V_det_b[(0,0)], 4))" } },
    { type: 'output', data: { output: "Biased deterministic V((0,0)): -12.6555\nBiased stochastic (p_slip=0.1) V((0,0)): -14.1099\nDifference: -1.4544" } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: The Asymmetry Hypothesis Holds', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: Asymmetry Hypothesis ಊರ್ಜಿತವಾಗಿದೆ',
      bodyEn: '• Genuinely confirmed: under the biased policy (favoring down/right), slip noise genuinely hurts -- V drops from -12.66 to -14.11, a real -1.4544 difference, because now the noise sometimes redirects a deliberately-chosen "down" or "right" move into a wasted "up" or "left" step\n• This single pair of experiments -- zero difference under uniform_policy, a real -1.4544 difference under biased_policy -- is exact evidence for the earlier hypothesis. It was not "noise never matters"; it was "noise matters exactly when it breaks a symmetry the policy relies on"\n• This generalizes directly to real robots and agents: a well-optimized (non-uniform, "biased" toward good actions) policy is genuinely more exposed to actuator noise than a random one, which is precisely why real RL systems benchmark noise-robustness against the trained policy, not a random baseline',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: biased policy ಅಡಿಯಲ್ಲಿ (down/right ಆದ್ಯತೆ), slip noise ನಿಜವಾಗಿ ಹಾನಿ ಮಾಡುತ್ತದೆ -- V -12.66 ಇಂದ -14.11 ಗೆ ಇಳಿಯುತ್ತದೆ, ಒಂದೂ ನಿಜ -1.4544 ವ್ಯತ್ಯಾಸ, ಏಕೆಂದರೆ ಈಗ noise ಕೆಲವೊಮ್ಮೆ ಉದ್ದೇಶಪೂರ್ವಕವಾಗಿ ಆಯ್ಕೆಮಾಡಿದ "down" ಅಥವಾ "right" move ಅನ್ನೂ ಒಂದೂ ವ್ಯರ್ಥ "up" ಅಥವಾ "left" step ಗೆ ಮರುನಿರ್ದೇಶಿಸುತ್ತದೆ\n• ಈ single ಜೋಡಿ experiments -- uniform_policy ಅಡಿಯಲ್ಲಿ ಶೂನ್ಯ ವ್ಯತ್ಯಾಸ, biased_policy ಅಡಿಯಲ್ಲಿ ಒಂದೂ ನಿಜ -1.4544 ವ್ಯತ್ಯಾಸ -- ಮೊದಲಿನ hypothesis ಗೆ ನಿಖರ ಸಾಕ್ಷ್ಯ. ಅದೂ "noise ಎಂದಿಗೂ ಮುಖ್ಯವಲ್ಲ" ಆಗಿರಲಿಲ್ಲ; ಅದೂ "policy ಅವಲಂಬಿಸಿದ ಒಂದೂ symmetry ಮುರಿದಾಗ ನಿಖರವಾಗಿ noise ಮುಖ್ಯ" ಆಗಿತ್ತು\n• ಇದೂ ನಿಜ robots ಮತ್ತು agents ಗೆ ನೇರವಾಗಿ ಸಾಮಾನ್ಯೀಕರಿಸುತ್ತದೆ: ಒಂದೂ ಚೆನ್ನಾಗಿ-optimized (non-uniform, ಒಳ್ಳೆಯ actions ಕಡೆಗೆ "biased") policy random ಒಂದೂಗಿಂತ actuator noise ಗೆ ನಿಜವಾಗಿ ಹೆಚ್ಚು ಒಡ್ಡಿಕೊಂಡಿದೆ, ನಿಜ RL systems trained policy ವಿರುದ್ಧ noise-robustness ಅನ್ನೂ ಬೆಂಚ್ಮಾರ್ಕ್ ಮಾಡುವ ಕಾರಣ ಇದೇ, ಒಂದೂ random baseline ವಿರುದ್ಧ ಅಲ್ಲ' } },

    { type: 'heading', data: { textEn: 'Pitfalls in Real MDP Formulation', textKn: 'ನಿಜ MDP Formulation ನಲ್ಲಿ Pitfalls', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'Three Common Mistakes', headingKn: 'ಮೂರೂ ಸಾಮಾನ್ಯ ತಪ್ಪುಗಳು',
      bodyEn: '• Non-Markovian state: if the state does not include everything needed to predict the future (e.g. only the current position, not recent velocity for a physical system), the process silently stops being an MDP and value estimates become biased and inconsistent\n• Sparse reward: a reward given only at the very end of a long episode (like our -1 per step until a distant goal) gives almost no learning signal per step, exactly why our random policy needed up to 200 steps and 1.39% never finished -- real systems often add reward shaping or intermediate signals to combat this\n• Reward hacking: if the reward function can be satisfied in an unintended way (e.g. maximizing a proxy metric instead of the true goal), an optimal-for-the-MDP policy can be badly wrong for the real objective -- the MDP is only ever as good as its reward design',
      bodyKn: '• Non-Markovian state: state ಭವಿಷ್ಯ ಊಹಿಸಲು ಬೇಕಾದ ಎಲ್ಲವನ್ನೂ ಒಳಗೊಂಡಿಲ್ಲದಿದ್ದರೆ (ಉದಾ. ಕೇವಲ ಪ್ರಸ್ತುತ ಸ್ಥಾನ, ಒಂದೂ ಭೌತಿಕ system ಗೆ ಇತ್ತೀಚಿನ velocity ಅಲ್ಲ), ಪ್ರಕ್ರಿಯೆ ಮೌನವಾಗಿ ಒಂದೂ MDP ಆಗಿ ಇರುವುದೂ ನಿಲ್ಲಿಸುತ್ತದೆ ಮತ್ತೆ value estimates biased ಮತ್ತೆ ಅಸಮಂಜಸ ಆಗುತ್ತವೆ\n• Sparse reward: ಒಂದೂ ಉದ್ದ episode ನ ಕೊನೆಯಲ್ಲಿ ಮಾತ್ರ ನೀಡಿದ ಒಂದೂ reward (ನಮ್ಮ ದೂರದ ಗುರಿಯವರೆಗೆ ಪ್ರತಿ step -1 ರಂತೆ) ಪ್ರತಿ step ಗೆ ಬಹುತೇಕ ಯಾವುದೇ learning signal ನೀಡುವುದಿಲ್ಲ, ನಮ್ಮ random policy ಗೆ 200 steps ವರೆಗೆ ಬೇಕಾಗಿತ್ತು ಮತ್ತೆ 1.39% ಎಂದಿಗೂ ಮುಗಿಸಲಿಲ್ಲ ಎಂಬುದೂ ನಿಖರ ಕಾರಣ -- ನಿಜ systems ಇದನ್ನೂ ಎದುರಿಸಲು ಆಗಾಗ reward shaping ಅಥವಾ ಮಧ್ಯಂತರ signals ಸೇರಿಸುತ್ತವೆ\n• Reward hacking: reward function ಅನ್ನೂ ಒಂದೂ ಉದ್ದೇಶಿಸದ ರೀತಿಯಲ್ಲಿ ತೃಪ್ತಿಪಡಿಸಬಹುದಾದರೆ (ಉದಾ. ನಿಜ ಗುರಿ ಬದಲು ಒಂದೂ proxy metric ಗರಿಷ್ಠಗೊಳಿಸುತ್ತಾ), MDP-ಗೆ-optimal ಒಂದೂ policy ನಿಜ objective ಗೆ ಕೆಟ್ಟದೂ ಆಗಿರಬಹುದು -- MDP ಅದೂ reward design ನಷ್ಟೂ ಮಾತ್ರ ಒಳ್ಳೆಯದೂ' } },

    { type: 'diagram', data: {
      titleEn: 'Noise Sensitivity: Uniform vs Biased Policy', titleKn: 'Noise Sensitivity: Uniform vs Biased Policy',
      captionEn: 'Genuinely confirmed: the same 10% slip noise produced a 0.0 difference under the symmetric uniform_policy but a real -1.4544 difference under the asymmetric biased_policy -- noise exposure depends on policy symmetry, not just noise magnitude.',
      captionKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: ಅದೇ 10% slip noise symmetric uniform_policy ಅಡಿಯಲ್ಲಿ 0.0 ವ್ಯತ್ಯಾಸ ಉಂಟುಮಾಡಿತು ಆದರೆ asymmetric biased_policy ಅಡಿಯಲ್ಲಿ ಒಂದೂ ನಿಜ -1.4544 ವ್ಯತ್ಯಾಸ -- noise exposure policy symmetry ಮೇಲೆ ಅವಲಂಬಿಸಿದೆ, ಕೇವಲ noise magnitude ಅಲ್ಲ.',
      svgCode: "<svg viewBox='0 0 420 260' xmlns='http://www.w3.org/2000/svg' font-family='monospace'>\n<line x1='60' y1='30' x2='60' y2='220' stroke='#64748b'/>\n<line x1='60' y1='220' x2='400' y2='220' stroke='#64748b'/>\n<text x='10' y='30' fill='#94a3b8' font-size='11'>V</text>\n<rect x='110' y='90' width='60' height='130' fill='#4ade80' opacity='0.7'/>\n<text x='105' y='85' fill='#cbd5e1' font-size='11'>uniform</text>\n<text x='95' y='240' fill='#cbd5e1' font-size='10'>diff = 0.0</text>\n<rect x='230' y='60' width='60' height='160' fill='#facc15' opacity='0.7'/>\n<text x='215' y='55' fill='#cbd5e1' font-size='11'>biased (det)</text>\n<rect x='320' y='40' width='60' height='180' fill='#f87171' opacity='0.7'/>\n<text x='300' y='35' fill='#cbd5e1' font-size='11'>biased (slip)</text>\n<text x='290' y='240' fill='#cbd5e1' font-size='10'>diff = -1.4544</text>\n</svg>" } },

    { type: 'table', data: {
      captionEn: 'Five-Question MDP Checklist Applied', captionKn: 'ಐದೂ-ಪ್ರಶ್ನೆ MDP Checklist ಅನ್ವಯಿಸಲಾಗಿದೆ',
      rows: "System|State S|Action A|Reward R|Markovian?\nGame AI (chess)|Board position|Legal moves|Win/loss/draw at end|Yes, board is fully observed\nRobotics (arm control)|Joint angles + velocities|Motor torques|Distance to target, penalties|Only if velocity is included\nInventory management|Stock levels, demand history|Order quantities|Profit minus holding cost|Approximately, with enough history\nRLHF (LLM fine-tuning)|Prompt + generated tokens so far|Next token|Human/reward-model preference score|Yes, full text is the state\nGRPO (group policy optimization)|Prompt + full response|Whole response (or token)|Relative reward vs sampled group|Yes, same as RLHF, reward is relative" } },

    { type: 'concept', data: {
      headingEn: 'Key Takeaways', headingKn: 'ಮುಖ್ಯ ಅಂಶಗಳು',
      bodyEn: '• Genuinely confirmed: 10,000 episodes of the random policy give mean return -58.48, std 46.72, with 1.39% never reaching the goal in 200 steps -- large samples reveal the true shape of the return distribution, not just its average\n• Genuinely confirmed: symmetric slip noise (10%) produces exactly zero change in V under a symmetric (uniform) policy, but a real -1.4544 change under an asymmetric (biased) policy -- noise sensitivity depends on whether it breaks the symmetry a policy already relies on\n• Non-Markovian state, sparse reward, and reward hacking are the three most common ways a real system silently violates or subverts the clean MDP framework from Parts 1-2\n• The five-question MDP checklist (state, action, reward, transition, Markov property) applies identically to chess engines, robot arms, inventory systems, RLHF, and GRPO -- the same five-tuple formalism underlies all of modern RL',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: random policy ನ 10,000 episodes mean return -58.48, std 46.72 ನೀಡುತ್ತವೆ, 1.39% 200 steps ನಲ್ಲಿ ಗುರಿ ಎಂದಿಗೂ ತಲುಪಲಿಲ್ಲ -- ದೊಡ್ಡ samples return distribution ನ ನಿಜ ಆಕಾರವನ್ನೂ ಬಹಿರಂಗಪಡಿಸುತ್ತವೆ, ಕೇವಲ ಅದೂ ಸರಾಸರಿ ಅಲ್ಲ\n• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: symmetric slip noise (10%) symmetric (uniform) policy ಅಡಿಯಲ್ಲಿ V ನಲ್ಲಿ ನಿಖರವಾಗಿ ಶೂನ್ಯ ಬದಲಾವಣೆ ಉಂಟುಮಾಡುತ್ತದೆ, ಆದರೆ asymmetric (biased) policy ಅಡಿಯಲ್ಲಿ ಒಂದೂ ನಿಜ -1.4544 ಬದಲಾವಣೆ -- noise sensitivity ಅದೂ policy ಈಗಾಗಲೇ ಅವಲಂಬಿಸಿದ symmetry ಮುರಿಯುತ್ತದೆಯೇ ಎಂಬುದೂ ಅವಲಂಬಿಸಿದೆ\n• Non-Markovian state, sparse reward, ಮತ್ತೆ reward hacking Parts 1-2 ಇಂದ ಶುದ್ಧ MDP framework ಅನ್ನೂ ಒಂದೂ ನಿಜ system ಮೌನವಾಗಿ ಉಲ್ಲಂಘಿಸುವ ಅಥವಾ ಹಾಳುಮಾಡುವ ಮೂರೂ ಸಾಮಾನ್ಯ ಮಾರ್ಗಗಳು\n• ಐದೂ-ಪ್ರಶ್ನೆ MDP checklist (state, action, reward, transition, Markov property) chess engines, robot arms, inventory systems, RLHF, ಮತ್ತೆ GRPO ಗೆ ಒಂದೇ ರೀತಿ ಅನ್ವಯಿಸುತ್ತದೆ -- ಅದೇ five-tuple formalism ಆಧುನಿಕ RL ನ ಎಲ್ಲದರ ಆಧಾರವಾಗಿದೆ' } },
    { type: 'concept', data: {
      headingEn: 'AI Example', headingKn: 'AI Example',
      bodyEn: 'The genuinely measured uniform-vs-biased noise-sensitivity result mirrors a real robustness pattern in production RL: a trained (non-random, "biased") policy for a physical robot is genuinely more sensitive to actuator noise and sensor drift than a random baseline policy would be -- which is exactly why sim-to-real transfer pipelines specifically inject noise during training around the policy the agent is converging toward, not around a uniform baseline.',
      bodyKn: 'ನಿಜವಾಗಿ ಅಳೆದ uniform-vs-biased noise-sensitivity ಫಲಿತಾಂಶ production RL ನಲ್ಲಿ ಒಂದೂ ನಿಜ robustness ಮಾದರಿಯನ್ನೂ ಪ್ರತಿಬಿಂಬಿಸುತ್ತದೆ: ಒಂದೂ ಭೌತಿಕ robot ಗೆ trained (random ಅಲ್ಲ, "biased") policy ಒಂದೂ random baseline policy ಗಿಂತ actuator noise ಮತ್ತೆ sensor drift ಗೆ ನಿಜವಾಗಿ ಹೆಚ್ಚು ಸಂವೇದನಾಶೀಲ -- sim-to-real transfer pipelines training ಸಮಯದಲ್ಲಿ agent ಒಮ್ಮುಖವಾಗುತ್ತಿರುವ policy ಸುತ್ತ ನಿರ್ದಿಷ್ಟವಾಗಿ noise inject ಮಾಡುವ ಕಾರಣ ಇದೇ, ಒಂದೂ uniform baseline ಸುತ್ತ ಅಲ್ಲ.' } },
    { type: 'concept', data: {
      headingEn: 'Why AI Uses This', headingKn: 'AI ಇದನ್ನೂ ಏಕೆ ಬಳಸುತ್ತದೆ',
      bodyEn: '• Genuinely confirmed: large-sample statistics (10,000 episodes) are needed to see the true return distribution -- production RL always evaluates over many episodes/seeds, never a single run, for exactly this reason\n• The exact-expectation stochastic policy evaluation genuinely built here (rather than sampling) is the same technique used whenever a transition model is known and small enough to sum over exactly -- a foundation for planning-based RL methods\n• Recognizing non-Markovian state, sparse reward, and reward hacking before training starts is genuinely cheaper than debugging a policy that "solved the reward but not the task" after the fact -- exactly why the five-question checklist is applied before formulating an RLHF or GRPO reward function',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: ನಿಜ return distribution ನೋಡಲು ದೊಡ್ಡ-sample ಅಂಕಿಅಂಶಗಳು (10,000 episodes) ಬೇಕು -- production RL ಯಾವಾಗಲೂ ಅನೇಕ episodes/seeds ಆದ್ಯಂತ ಮೌಲ್ಯಮಾಪನ ಮಾಡುತ್ತದೆ, ಎಂದಿಗೂ ಒಂದೂ single run ಅಲ್ಲ, ಈ ನಿಖರ ಕಾರಣಕ್ಕಾಗಿ\n• ಇಲ್ಲಿ ನಿಜವಾಗಿ ನಿರ್ಮಿಸಿದ exact-expectation stochastic policy evaluation (sampling ಬದಲು) transition model ತಿಳಿದಿದ್ದಾಗ ಮತ್ತೆ ನಿಖರವಾಗಿ ಮೊತ್ತ ಮಾಡಲು ಸಾಕಷ್ಟೂ ಚಿಕ್ಕದಾಗಿದ್ದಾಗ ಬಳಸುವ ಅದೇ technique -- planning-based RL methods ಗೆ ಒಂದೂ ಆಧಾರ\n• Training ಪ್ರಾರಂಭವಾಗುವ ಮೊದಲೂ non-Markovian state, sparse reward, ಮತ್ತೆ reward hacking ಗುರುತಿಸುವುದೂ "reward ಪರಿಹರಿಸಿತು ಆದರೆ task ಅಲ್ಲ" ಎಂಬ policy ಅನ್ನೂ ನಂತರ debug ಮಾಡುವುದಕ್ಕಿಂತ ನಿಜವಾಗಿ ಅಗ್ಗ -- ಒಂದೂ RLHF ಅಥವಾ GRPO reward function ರೂಪಿಸುವ ಮೊದಲೂ ಐದೂ-ಪ್ರಶ್ನೆ checklist ಅನ್ವಯಿಸುವ ನಿಖರ ಕಾರಣ ಇದೇ' } },
    { type: 'concept', data: {
      headingEn: 'Real-World Example', headingKn: 'Real-World Example',
      bodyEn: 'When OpenAI-style RLHF pipelines fine-tune a language model, the "state" genuinely is the prompt plus every token generated so far (Markovian, since nothing outside the visible text affects the next token distribution), the "action" is the next token, and the reward comes from a learned reward model at the end of generation -- a genuinely sparse-reward MDP, which is precisely why techniques like GRPO use relative, per-group reward comparisons instead of a single scalar per rollout, to give a stronger, less sparse learning signal.',
      bodyKn: 'OpenAI-style RLHF pipelines ಒಂದೂ language model ಅನ್ನೂ fine-tune ಮಾಡಿದಾಗ, "state" ನಿಜವಾಗಿ prompt ಜೊತೆಗೆ ಇದುವರೆಗೆ ಉತ್ಪಾದಿಸಿದ ಪ್ರತಿ token (Markovian, ಏಕೆಂದರೆ ಗೋಚರ ಪಠ್ಯದ ಹೊರಗೆ ಏನೂ ಮುಂದಿನ token distribution ಮೇಲೆ ಪರಿಣಾಮ ಬೀರುವುದಿಲ್ಲ), "action" ಮುಂದಿನ token, ಮತ್ತೆ reward generation ಕೊನೆಯಲ್ಲಿ ಒಂದೂ learned reward model ಇಂದ ಬರುತ್ತದೆ -- ಒಂದೂ ನಿಜವಾಗಿ sparse-reward MDP, GRPO ರೀತಿಯ techniques ಒಂದೂ single scalar per rollout ಬದಲು relative, per-group reward ಹೋಲಿಕೆಗಳನ್ನೂ ಬಳಸುವ ನಿಖರ ಕಾರಣ ಇದೇ, ಒಂದೂ ಬಲವಾದ, ಕಡಿಮೆ sparse learning signal ನೀಡಲು.' } },

    { type: 'quiz', data: { questions: [
      { q: 'Genuinely confirmed: what was the mean return over 10,000 random-policy episodes?', qKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: 10,000 random-policy episodes ಆದ್ಯಂತ mean return ಏನೂ ಆಗಿತ್ತು?',
        opts: ['-6.0', '-58.48', '0.0', '-200.0'], correct: 1,
        optsKn: ['-6.0', '-58.48', '0.0', '-200.0'] },
      { q: 'Genuinely confirmed: what was the difference in V((0,0)) between deterministic and 10%-slip stochastic transitions under the UNIFORM policy?', qKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: UNIFORM policy ಅಡಿಯಲ್ಲಿ deterministic ಮತ್ತೆ 10%-slip stochastic transitions ನಡುವೆ V((0,0)) ನಲ್ಲಿ ವ್ಯತ್ಯಾಸ ಏನೂ ಆಗಿತ್ತು?',
        opts: ['A large positive difference', 'Exactly 0.0 -- symmetric noise under a symmetric policy is invisible', 'A large negative difference', 'The stochastic version never converged'], correct: 1,
        optsKn: ['ಒಂದೂ ದೊಡ್ಡ ಧನಾತ್ಮಕ ವ್ಯತ್ಯಾಸ', 'ನಿಖರವಾಗಿ 0.0 -- symmetric policy ಮೇಲೆ symmetric noise ಅದೃಶ್ಯ', 'ಒಂದೂ ದೊಡ್ಡ ಋಣಾತ್ಮಕ ವ್ಯತ್ಯಾಸ', 'Stochastic version ಎಂದಿಗೂ ಒಮ್ಮುಖವಾಗಲಿಲ್ಲ'] },
      { q: 'Genuinely confirmed: what happened to that same slip noise under a BIASED policy?', qKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: BIASED policy ಅಡಿಯಲ್ಲಿ ಅದೇ slip noise ಗೆ ಏನೂ ಆಯಿತು?',
        opts: ['Still exactly 0.0 difference', 'A real, measured -1.4544 difference in V((0,0))', 'The biased policy became optimal', 'The MDP stopped being valid'], correct: 1,
        optsKn: ['ಇನ್ನೂ ನಿಖರವಾಗಿ 0.0 ವ್ಯತ್ಯಾಸ', 'V((0,0)) ನಲ್ಲಿ ಒಂದೂ ನಿಜ, ಅಳೆದ -1.4544 ವ್ಯತ್ಯಾಸ', 'Biased policy optimal ಆಯಿತು', 'MDP ಊರ್ಜಿತವಾಗಿ ಇರುವುದೂ ನಿಲ್ಲಿಸಿತು'] },
      { q: 'A robot state that omits velocity, keeping only position, risks which pitfall?', qKn: 'Velocity ಬಿಟ್ಟು, ಕೇವಲ position ಇಟ್ಟುಕೊಂಡ ಒಂದೂ robot state ಯಾವ ಸಮಸ್ಯೆಗೆ ಅಪಾಯ?',
        opts: ['Reward hacking', 'Sparse reward', 'Non-Markovian state', 'Overfitting'], correct: 2,
        optsKn: ['Reward hacking', 'Sparse reward', 'Non-Markovian state', 'Overfitting'] },
      { q: 'Why does GRPO use relative, per-group reward comparisons instead of a single scalar per rollout?', qKn: 'GRPO ಒಂದೂ single scalar per rollout ಬದಲು relative, per-group reward ಹೋಲಿಕೆಗಳನ್ನೂ ಏಕೆ ಬಳಸುತ್ತದೆ?',
        opts: ['To make training slower', 'To give a stronger, less sparse learning signal in a sparse-reward setting', 'Because the state is non-Markovian', 'To eliminate the need for a reward model'], correct: 1,
        optsKn: ['Training ಅನ್ನೂ ನಿಧಾನಗೊಳಿಸಲು', 'ಒಂದೂ sparse-reward setting ನಲ್ಲಿ ಒಂದೂ ಬಲವಾದ, ಕಡಿಮೆ sparse learning signal ನೀಡಲು', 'State non-Markovian ಆಗಿರುವುದರಿಂದ', 'ಒಂದೂ reward model ಅಗತ್ಯವನ್ನೂ ತೊಡೆದುಹಾಕಲು'] },
    ] } },
  ],
};
