const phaseId = '6a369d5a66020ed05b3213f4'; // Phase 13: LLM from Scratch
const moduleId = '6a369d5b66020ed05b321436'; // Module 206: Async and Hogwild! Inference

module.exports = {
  phaseId,
  moduleId,
  order: 0,
  type: 'interactive',
  duration: 40,
  difficulty: 'advanced',
  status: 'published',
  title: 'Async and Hogwild! Inference — Part 1: Foundations',
  titleKn: 'Async and Hogwild! Inference — Part 1: Foundations',
  desc: 'Genuinely compute how long a 50,000-token reasoning trace takes at 35 tokens/sec, then understand why Hogwild! Inference runs multiple LLM workers sharing one KV cache to achieve emergent, unscripted task-level coordination -- distinct from voting ensembles, tree-of-thought, and multi-agent systems.',
  descKn: "35 tokens/sec ನಲ್ಲಿ ಒಂದೂ 50,000-token reasoning trace ಎಷ್ಟೂ ಸಮಯ ತೆಗೆದುಕೊಳ್ಳುತ್ತದೆ ಎಂದೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಿ, ನಂತರ Hogwild! Inference ಒಂದೂ KV cache ಹಂಚಿಕೊಳ್ಳುವ ಬಹು LLM workers ಅನ್ನೂ ಓಡಿಸಿ emergent, unscripted task-level coordination ಸಾಧಿಸುತ್ತದೆ ಎಂದೂ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ -- voting ensembles, tree-of-thought, ಮತ್ತೆ multi-agent systems ಗಳಿಂದ ಭಿನ್ನ.",
  objectives: [
    'Explain why ordinary autoregressive LLM inference is inherently sequential, and genuinely compute how long a long reasoning trace takes at a given token rate.',
    'Distinguish token-level parallelism (e.g. speculative decoding) from task-level parallelism (e.g. Hogwild!).',
    'Distinguish voting ensembles, tree-of-thought, multi-agent frameworks, and Hogwild! inference by their coordination mechanism.',
    'Explain what a shared KV cache is and how it lets Hogwild! workers observe each other\'s progress without explicit messaging.',
    'Explain the meaning of "emergent coordination" and why it does not require a separately trained coordinator.',
    'Explain why Hogwild! is named after Hogwild! SGD, and why coordination overhead makes it primarily suited to long reasoning tasks.',
  ],
  objectivesKn: [
    'ಸಾಮಾನ್ಯ autoregressive LLM inference ಅಂತರ್ಗತವಾಗಿ ಅನುಕ್ರಮ ಏಕೆ ಎಂದೂ ವಿವರಿಸಿ, ಮತ್ತೆ ಒಂದೂ ಕೊಟ್ಟಿರುವ token rate ನಲ್ಲಿ ಒಂದೂ ಉದ್ದ reasoning trace ಎಷ್ಟೂ ಸಮಯ ತೆಗೆದುಕೊಳ್ಳುತ್ತದೆ ಎಂದೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಿ.',
    'Token-level parallelism (ಉದಾ. speculative decoding) ಅನ್ನೂ task-level parallelism (ಉದಾ. Hogwild!) ಇಂದ ಪ್ರತ್ಯೇಕಿಸಿ.',
    'Voting ensembles, tree-of-thought, multi-agent frameworks, ಮತ್ತೆ Hogwild! inference ಅನ್ನೂ ಅವುಗಳ coordination ಕಾರ್ಯವಿಧಾನದ ಮೂಲಕ ಪ್ರತ್ಯೇಕಿಸಿ.',
    'ಒಂದೂ shared KV cache ಏನೂ ಎಂದೂ ಮತ್ತೆ ಅದೂ Hogwild! workers ಗೆ ಸ್ಪಷ್ಟ messaging ಇಲ್ಲದೆ ಪರಸ್ಪರ progress ಗಮನಿಸಲು ಹೇಗೆ ಬಿಡುತ್ತದೆ ಎಂದೂ ವಿವರಿಸಿ.',
    '"Emergent coordination" ya ಅರ್ಥ ಮತ್ತೆ ಅದೂ ಗೆ ಪ್ರತ್ಯೇಕವಾಗಿ ತರಬೇತಿ ಪಡೆದ coordinator ಏಕೆ ಬೇಡ ಎಂದೂ ವಿವರಿಸಿ.',
    'Hogwild! ಅನ್ನೂ Hogwild! SGD ya ಹೆಸರಿನಲ್ಲಿ ಏಕೆ ಇಡಲಾಗಿದೆ ಎಂದೂ, ಮತ್ತೆ coordination overhead ಅದನ್ನೂ ಪ್ರಾಥಮಿಕವಾಗಿ ಉದ್ದ reasoning tasks ಗೆ ಏಕೆ ಸೂಕ್ತಗೊಳಿಸುತ್ತದೆ ಎಂದೂ ವಿವರಿಸಿ.',
  ],
  blocks: [
    { type: 'heading', data: { textEn: 'Async and Hogwild! Inference — Part 1: Foundations', textKn: 'Async and Hogwild! Inference — Part 1: Foundations', level: 'H1' } },
    { type: 'concept', data: {
      headingEn: 'Lesson Info', headingKn: 'Lesson ಮಾಹಿತಿ',
      bodyEn: '• Type: Learn · Language: Python — coordination simulator · Prerequisite: Module 196 (Inference Optimization), Module 199 (Speculative Decoding) · Time: ~40 minutes · Part 1 of 3',
      bodyKn: '• Type: Learn · Language: Python — coordination simulator · Prerequisite: Module 196, Module 199 · Time: ~40 ನಿಮಿಷಗಳು · Part 1 of 3',
      pillsEn: 'Hogwild! Inference,Task-Level Parallelism,Shared KV Cache,Emergent Coordination,Part 1 of 3',
      pillsKn: 'Hogwild! Inference,Emergent Coordination,Part 1 of 3' } },

    { type: 'heading', data: { textEn: 'The Problem: Reasoning Traces Are Long and Sequential', textKn: 'ಸಮಸ್ಯೆ: Reasoning Traces ಉದ್ದ ಮತ್ತೆ ಅನುಕ್ರಮ', level: 'H2' } },
    { type: 'code', data: {
      filename: 'reasoning_time.py', headingEn: 'Genuinely computing how long a 50,000-token reasoning trace takes', headingKn: 'ಒಂದೂ 50,000-token reasoning trace ಎಷ್ಟೂ ಸಮಯ ತೆಗೆದುಕೊಳ್ಳುತ್ತದೆ ಎಂದೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕುವುದೂ',
      descEn: 'A modern reasoning model may need tens of thousands of tokens for a difficult problem. At 35 tokens/sec, compute the wall-clock time for 50,000 tokens.',
      descKn: 'ಒಂದೂ ಆಧುನಿಕ reasoning model ಒಂದೂ ಕಷ್ಟಕರ ಸಮಸ್ಯೆಗೆ ಹತ್ತಾರೂ ಸಾವಿರ tokens ಬೇಕಾಗಬಹುದು. 35 tokens/sec ನಲ್ಲಿ, 50,000 tokens ಗಾಗಿ wall-clock time ಲೆಕ್ಕಹಾಕಿ.',
      code: "tokens = 50_000\nrate = 35  # tokens/sec\nseconds = tokens / rate\nminutes = seconds / 60\nprint(f'{tokens:,} tokens / {rate} tokens/sec = {seconds:.1f} sec = {minutes:.2f} minutes')" } },
    { type: 'output', data: { output: '50,000 tokens / 35 tokens/sec = 1428.6 sec = 23.81 minutes' } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: ~23.8 Minutes for One Reasoning Trajectory', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: ಒಂದೂ Reasoning Trajectory ಗೆ ~23.8 ನಿಮಿಷಗಳು',
      bodyEn: 'Genuinely computed 1428.6 seconds = 23.81 minutes, matching the source exactly. This motivates the central question: instead of forcing a single LLM instance to perform all reasoning sequentially, can several instances work on the same problem simultaneously? The lesson explicitly contrasts this with speculative decoding (Module 199), which accelerates generation WITHIN one sequence, whereas Hogwild! tries to exploit parallelism ACROSS reasoning work performed by several independent workers.',
      bodyKn: '1428.6 seconds = 23.81 minutes ಎಂದೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಲಾಗಿದೆ, source ಗೆ ನಿಖರವಾಗಿ ಹೊಂದಿಕೆಯಾಗುತ್ತದೆ. ಇದೂ ಕೇಂದ್ರ ಪ್ರಶ್ನೆಗೆ ಪ್ರೇರೇಪಿಸುತ್ತದೆ: ಒಂದೂ ಒಂಟಿ LLM instance ಅನ್ನೂ ಎಲ್ಲಾ reasoning ಅನುಕ್ರಮವಾಗಿ ನಿರ್ವಹಿಸುವಂತೆ ಒತ್ತಾಯಿಸುವ ಬದಲಿಗೆ, ಹಲವೂ instances ಅದೇ ಸಮಸ್ಯೆ ಮೇಲೆ ಏಕಕಾಲದಲ್ಲಿ ಕೆಲಸ ಮಾಡಬಹುದೂ? Lesson ಇದನ್ನೂ speculative decoding (Module 199) ಜೊತೆ ಸ್ಪಷ್ಟವಾಗಿ ವ್ಯತಿರಿಕ್ತಗೊಳಿಸುತ್ತದೆ, ಇದೂ ಒಂದೂ sequence ಒಳಗೆ generation ವೇಗಗೊಳಿಸುತ್ತದೆ, ಆದರೆ Hogwild! ಹಲವೂ ಸ್ವತಂತ್ರ workers ನಿರ್ವಹಿಸಿದ reasoning ಕೆಲಸ ಆದ್ಯಂತ parallelism ಬಳಸಿಕೊಳ್ಳಲು ಪ್ರಯತ್ನಿಸುತ್ತದೆ.' } },

    { type: 'heading', data: { textEn: 'Two Different Levels of Parallelism', textKn: 'ಎರಡೂ ಭಿನ್ನ Levels ya Parallelism', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'Token-Level vs Task-Level', headingKn: 'Token-Level vs Task-Level',
      bodyEn: 'Token-level parallelism asks: can we make generation of a SINGLE sequence faster? (Prompt -> t1 -> t2 -> t3 -> t4; speculative decoding operates here.) Task-level parallelism asks: can DIFFERENT pieces of the reasoning problem be solved at the same time? (Problem splits into Case A / Case B / Case C, investigated by different workers concurrently.) The normal autoregressive factorization P(x_1,...,x_T)=product of P(x_t|x_<t}) means token x_t normally cannot be finalized before every token preceding it exists -- adding four GPUs does not automatically let four consecutive tokens of the SAME sequence generate independently. That sequential dependency is what Hogwild! works around, not by eliminating it, but by exploiting a different axis of parallelism entirely.',
      bodyKn: 'Token-level parallelism ಕೇಳುತ್ತದೆ: ನಾವು ಒಂದೂ SINGLE sequence ya generation ಅನ್ನೂ ವೇಗವಾಗಿ ಮಾಡಬಹುದೇ? (Prompt -> t1 -> t2 -> t3 -> t4; speculative decoding ಇಲ್ಲಿ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತದೆ.) Task-level parallelism ಕೇಳುತ್ತದೆ: reasoning ಸಮಸ್ಯೆಯ ಭಿನ್ನ ಭಾಗಗಳನ್ನೂ ಅದೇ ಸಮಯದಲ್ಲಿ ಬಗೆಹರಿಸಬಹುದೇ? (Problem Case A / Case B / Case C ಗೆ ವಿಭಜನೆಯಾಗುತ್ತದೆ, ಭಿನ್ನ workers ಇಂದ ಏಕಕಾಲದಲ್ಲಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ.) ಸಾಮಾನ್ಯ autoregressive factorization P(x_1,...,x_T)=P(x_t|x_<t}) ya ಗುಣಲಬ್ಧ ಎಂದರೆ token x_t ಸಾಮಾನ್ಯವಾಗಿ ಅದೂ ಮುಂಚಿನ ಪ್ರತಿ token ಅಸ್ತಿತ್ವದಲ್ಲಿಲ್ಲದ ಹೊರತೂ ಅಂತಿಮಗೊಳ್ಳಲಾಗುವುದಿಲ್ಲ -- ನಾಲ್ಕೂ GPUs ಸೇರಿಸುವುದೂ ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಅದೇ sequence ya ನಾಲ್ಕೂ ಸತತ tokens ಸ್ವತಂತ್ರವಾಗಿ ಉತ್ಪಾದಿಸಲು ಬಿಡುವುದಿಲ್ಲ. ಆ ಅನುಕ್ರಮ ಅವಲಂಬನೆ Hogwild! ಸುತ್ತ ಕೆಲಸ ಮಾಡುತ್ತದೆ, ಅದನ್ನೂ ತೆಗೆದುಹಾಕುವ ಮೂಲಕ ಅಲ್ಲ, ಆದರೆ ಸಂಪೂರ್ಣವಾಗಿ ಭಿನ್ನ parallelism axis ಬಳಸಿಕೊಳ್ಳುವ ಮೂಲಕ.' } },

    { type: 'heading', data: { textEn: 'Three Explicit Coordination Strategies', textKn: 'ಮೂರೂ ಸ್ಪಷ್ಟ Coordination Strategies', level: 'H2' } },
    { type: 'table', data: {
      captionEn: 'Voting, Tree-of-Thought, and Multi-Agent All Use Explicit Coordination', captionKn: 'Voting, Tree-of-Thought, ಮತ್ತೆ Multi-Agent ಎಲ್ಲಾ ಸ್ಪಷ್ಟ Coordination ಬಳಸುತ್ತವೆ',
      rows: "Strategy|Coordination mechanism|Weakness\nVoting ensemble|Majority vote after independent solving|Workers duplicate most computation (4 workers on 10k tokens each ~ 40k reasoning tokens)\nTree of thought|Explicit branch/score/prune logic|Requires an explicit orchestrator deciding which branches to keep\nMulti-agent framework|Coordinator assigns roles and merges results|Coordination is deliberately designed and hand-specified per task\nHogwild! inference|Workers read/write one shared cache, no assignment|Coordination must emerge from the model's own reasoning, which can fail" } },
    { type: 'concept', data: {
      headingEn: 'Why Voting Wastes Computation on Long Reasoning', headingKn: 'Voting ಉದ್ದ Reasoning ಮೇಲೆ Computation ಅನ್ನೂ ಏಕೆ ವ್ಯರ್ಥ ಮಾಡುತ್ತದೆ',
      bodyEn: 'In a voting ensemble, each model solves the COMPLETE problem independently, then a majority vote picks the answer -- very simple, almost no communication, but if a complex proof takes 10,000 tokens, four workers might independently spend close to 4x10,000=40,000 reasoning tokens without truly collaborating; they produce several independent attempts, not a divided effort. Voting works well for short-answer tasks (classification, multiple-choice, self-consistency sampling) where each worker\'s cost is small, but becomes unattractive once every worker independently generates a huge chain of reasoning. Tree-of-thought and multi-agent frameworks improve on pure duplication by adding explicit orchestration (branch-and-prune logic, or a coordinator assigning roles like "Agent 1: derive solution, Agent 2: verify calculations") -- but that coordination protocol must be deliberately designed for each task.',
      bodyKn: 'ಒಂದು voting ensemble ನಲ್ಲಿ, ಪ್ರತಿ model ಪೂರ್ಣ ಸಮಸ್ಯೆಯನ್ನೂ ಸ್ವತಂತ್ರವಾಗಿ ಬಗೆಹರಿಸುತ್ತದೆ, ನಂತರ ಒಂದೂ majority vote ಉತ್ತರ ಆಯ್ಕೆ ಮಾಡುತ್ತದೆ -- ಬಹಳ ಸರಳ, ಬಹುತೇಕ ಸಂವಹನ ಇಲ್ಲ, ಆದರೆ ಒಂದೂ ಸಂಕೀರ್ಣ ಪ್ರಮಾಣ 10,000 tokens ತೆಗೆದುಕೊಂಡರೆ, ನಾಲ್ಕೂ workers ನಿಜವಾಗಿ ಸಹಕರಿಸದೆ ಸ್ವತಂತ್ರವಾಗಿ ಸುಮಾರು 4x10,000=40,000 reasoning tokens ಖರ್ಚು ಮಾಡಬಹುದು; ಅವು ಹಲವೂ ಸ್ವತಂತ್ರ ಪ್ರಯತ್ನಗಳನ್ನೂ ಉತ್ಪಾದಿಸುತ್ತವೆ, ವಿಭಜಿಸಿದ ಪ್ರಯತ್ನವನ್ನೂ ಅಲ್ಲ. Voting ಚಿಕ್ಕ-ಉತ್ತರ tasks (classification, multiple-choice, self-consistency sampling) ಗೆ ಚೆನ್ನಾಗಿ ಕೆಲಸ ಮಾಡುತ್ತದೆ ಇಲ್ಲಿ ಪ್ರತಿ worker ya ವೆಚ್ಚ ಚಿಕ್ಕದೂ, ಆದರೆ ಪ್ರತಿ worker ಸ್ವತಂತ್ರವಾಗಿ ಒಂದೂ ಬೃಹತ್ reasoning ಸರಪಳಿ ಉತ್ಪಾದಿಸಿದಾಗ ಆಕರ್ಷಕವಲ್ಲದೂ ಆಗುತ್ತದೆ. Tree-of-thought ಮತ್ತೆ multi-agent frameworks ಸ್ಪಷ್ಟ orchestration ಸೇರಿಸಿ ಶುದ್ಧ ಪುನರಾವರ್ತನೆ ಮೇಲೆ ಸುಧಾರಿಸುತ್ತವೆ (branch-and-prune logic, ಅಥವಾ "Agent 1: solution derive ಮಾಡಿ, Agent 2: calculations ಪರಿಶೀಲಿಸಿ" ನಂತೆ ಪಾತ್ರಗಳನ್ನೂ ನಿಯೋಜಿಸುವ ಒಂದೂ coordinator) -- ಆದರೆ ಆ coordination protocol ಪ್ರತಿ task ಗೆ ಉದ್ದೇಶಪೂರ್ವಕವಾಗಿ ವಿನ್ಯಾಸಗೊಳಿಸಬೇಕು.' } },

    { type: 'heading', data: { textEn: 'Hogwild!: Removing the Explicit Protocol', textKn: 'Hogwild!: ಸ್ಪಷ್ಟ Protocol ತೆಗೆದುಹಾಕುವುದೂ', level: 'H2' } },
    { type: 'diagram', data: {
      titleEn: 'Hogwild! Architecture: N Workers, One Shared Cache', titleKn: 'Hogwild! Architecture: N Workers, ಒಂದೂ Shared Cache',
      captionEn: 'Every worker reads the same growing shared cache, sees what the others have already produced, decides what useful work remains, and writes its output back -- no separate coordinator dictates "Worker 1: do A, Worker 2: do B."',
      captionKn: 'ಪ್ರತಿ worker ಅದೇ ಬೆಳೆಯುತ್ತಿರುವ shared cache ಓದುತ್ತದೆ, ಇತರರೂ ಈಗಾಗಲೇ ಏನೂ ಉತ್ಪಾದಿಸಿದ್ದಾರೂ ಎಂದೂ ನೋಡುತ್ತದೆ, ಯಾವ ಉಪಯುಕ್ತ ಕೆಲಸ ಉಳಿದಿದೆ ಎಂದೂ ನಿರ್ಧರಿಸುತ್ತದೆ, ಮತ್ತೆ ಅದೂ ya output ಮರಳಿ ಬರೆಯುತ್ತದೆ -- ಯಾವುದೇ ಪ್ರತ್ಯೇಕ coordinator "Worker 1: A ಮಾಡಿ, Worker 2: B ಮಾಡಿ" ಎಂದೂ ಆದೇಶಿಸುವುದಿಲ್ಲ.',
      svgCode: "<svg viewBox='0 0 700 160' xmlns='http://www.w3.org/2000/svg'><rect x='50' y='10' width='90' height='30' fill='#22c55e'/><text x='65' y='29' fill='#0f172a' font-size='9'>Worker 0</text><rect x='200' y='10' width='90' height='30' fill='#22c55e'/><text x='215' y='29' fill='#0f172a' font-size='9'>Worker 1</text><rect x='350' y='10' width='90' height='30' fill='#22c55e'/><text x='365' y='29' fill='#0f172a' font-size='9'>Worker 2</text><line x1='95' y1='40' x2='300' y2='90' stroke='#94a3b8'/><line x1='245' y1='40' x2='300' y2='90' stroke='#94a3b8'/><line x1='395' y1='40' x2='300' y2='90' stroke='#94a3b8'/><rect x='220' y='90' width='160' height='30' fill='#f59e0b'/><text x='230' y='109' fill='#0f172a' font-size='9'>SHARED KV CACHE</text><line x1='300' y1='120' x2='95' y2='150' stroke='#94a3b8'/><line x1='300' y1='120' x2='245' y2='150' stroke='#94a3b8'/><line x1='300' y1='120' x2='395' y2='150' stroke='#94a3b8'/><text x='10' y='150' fill='#e2e8f0' font-size='9'>read/write both directions -- no explicit task assignment</text></svg>" } },
    { type: 'concept', data: {
      headingEn: 'The Core Setup: N Workers, Same LLM, One Shared Cache', headingKn: 'ಮುಖ್ಯ Setup: N Workers, ಅದೇ LLM, ಒಂದೂ Shared Cache',
      bodyEn: 'The architecture is essentially N workers + same LLM + one shared cache, where each worker both reads from and writes to a common growing context rather than maintaining its own isolated KV cache. Normally each model request owns its own context (Worker A -> KV Cache A, Worker B -> KV Cache B, isolated) so Worker A cannot see Worker B\'s reasoning. Hogwild! changes this: if Worker A writes "Case A fails because x must be positive," when Worker B performs its next inference step, that information is already part of the shared context it attends to -- Worker B can reason "Case A was already checked, I\'ll investigate Case B" without anyone telling it to.',
      bodyKn: 'Architecture ಮೂಲಭೂತವಾಗಿ N workers + ಅದೇ LLM + ಒಂದೂ shared cache, ಇಲ್ಲಿ ಪ್ರತಿ worker ಅದೂ ya ಸ್ವಂತ ಪ್ರತ್ಯೇಕ KV cache ಇಡುವ ಬದಲಿಗೆ ಒಂದೂ ಸಾಮಾನ್ಯ ಬೆಳೆಯುತ್ತಿರುವ context ಅನ್ನೂ ಓದುತ್ತದೆ ಮತ್ತೆ ಬರೆಯುತ್ತದೆ. ಸಾಮಾನ್ಯವಾಗಿ ಪ್ರತಿ model request ಅದೂ ya ಸ್ವಂತ context ಹೊಂದಿದೆ (Worker A -> KV Cache A, Worker B -> KV Cache B, ಪ್ರತ್ಯೇಕ) ಆದ್ದರಿಂದ Worker A ಗೆ Worker B ya reasoning ಕಾಣಲು ಸಾಧ್ಯವಿಲ್ಲ. Hogwild! ಇದನ್ನೂ ಬದಲಾಯಿಸುತ್ತದೆ: Worker A "Case A fails because x must be positive" ಎಂದೂ ಬರೆದರೆ, Worker B ಅದೂ ya ಮುಂದಿನ inference step ನಿರ್ವಹಿಸುವಾಗ, ಆ ಮಾಹಿತಿ ಈಗಾಗಲೇ ಅದೂ ಗಮನಿಸುವ shared context ya ಭಾಗ -- Worker B ಯಾರೂ ಹೇಳದೆ "Case A ಈಗಾಗಲೇ ಪರಿಶೀಲಿಸಲಾಗಿದೆ, ನಾನೂ Case B ಪರಿಶೀಲಿಸುತ್ತೇನೂ" ಎಂದೂ ತಾರ್ಕಿಕವಾಗಿ ಯೋಚಿಸಬಹುದು.' } },

    { type: 'heading', data: { textEn: 'What "Emergent Coordination" Means', textKn: '"Emergent Coordination" ya ಅರ್ಥ', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'No Dedicated Router, No Assigned Tasks', headingKn: 'ಯಾವುದೇ Dedicated Router ಇಲ್ಲ, ಯಾವುದೇ Assigned Tasks ಇಲ್ಲ',
      bodyEn: 'Explicit coordination looks like tasks={"worker_1":"solve A","worker_2":"solve B","worker_3":"solve C"} -- workers are explicitly told what to do. Emergent coordination has tasks=None: every worker sees the same problem and shared context, and a capable model notices "Worker 1 already solved A" and independently infers "I should solve B" -- the coordination emerges from the model\'s EXISTING reasoning behavior, not a separately trained or hand-coded protocol. The source specifically describes workers planning through the cache, noticing one another\'s errors, changing plans when something fails, and detecting redundant work WITHOUT additional fine-tuning -- this last point matters: it is a property of using a sufficiently capable reasoning model on a shared context, not a new capability that had to be trained in.',
      bodyKn: 'Explicit coordination tasks={"worker_1":"solve A","worker_2":"solve B","worker_3":"solve C"} ನಂತೆ ಕಾಣುತ್ತದೆ -- workers ಗೆ ಏನೂ ಮಾಡಬೇಕು ಎಂದೂ ಸ್ಪಷ್ಟವಾಗಿ ಹೇಳಲಾಗಿದೆ. Emergent coordination ಗೆ tasks=None: ಪ್ರತಿ worker ಅದೇ ಸಮಸ್ಯೆ ಮತ್ತೆ shared context ನೋಡುತ್ತದೆ, ಮತ್ತೆ ಒಂದೂ ಸಮರ್ಥ model "Worker 1 ಈಗಾಗಲೇ A ಬಗೆಹರಿಸಿತೂ" ಎಂದೂ ಗಮನಿಸುತ್ತದೆ ಮತ್ತೆ ಸ್ವತಂತ್ರವಾಗಿ "ನಾನೂ B ಬಗೆಹರಿಸಬೇಕು" ಎಂದೂ ತೀರ್ಮಾನಿಸುತ್ತದೆ -- coordination model ya ಈಗಾಗಲೇ ಇರುವ reasoning behavior ಇಂದ ಹೊರಹೊಮ್ಮುತ್ತದೆ, ಪ್ರತ್ಯೇಕವಾಗಿ ತರಬೇತಿ ಪಡೆದ ಅಥವಾ hand-coded protocol ಅಲ್ಲ. Source ನಿರ್ದಿಷ್ಟವಾಗಿ workers cache ಮೂಲಕ ಯೋಜಿಸುತ್ತಾ, ಪರಸ್ಪರ ದೋಷಗಳನ್ನೂ ಗಮನಿಸುತ್ತಾ, ಏನೋ ವಿಫಲವಾದಾಗ ಯೋಜನೆಗಳನ್ನೂ ಬದಲಾಯಿಸುತ್ತಾ, ಹೆಚ್ಚುವರಿ fine-tuning ಇಲ್ಲದೆ ಪುನರಾವರ್ತಿತ ಕೆಲಸ ಪತ್ತೆ ಮಾಡುತ್ತಾ ಎಂದೂ ವಿವರಿಸುತ್ತದೆ -- ಈ ಕೊನೆಯ ಅಂಶ ಮುಖ್ಯ: ಇದೂ shared context ಮೇಲೆ ಸಾಕಷ್ಟೂ ಸಮರ್ಥ reasoning model ಬಳಸುವುದೂ ya ಒಂದೂ ಗುಣಲಕ್ಷಣ, ತರಬೇತಿ ಪಡೆಯಬೇಕಾದ ಒಂದೂ ಹೊಸ ಸಾಮರ್ಥ್ಯ ಅಲ್ಲ.' } },

    { type: 'concept', data: {
      headingEn: 'Self-Prompting Enables the Behavior', headingKn: 'Self-Prompting ಈ Behavior ಅನ್ನೂ ಸಾಧ್ಯಗೊಳಿಸುತ್ತದೆ',
      bodyEn: 'Workers are not launched with an ordinary user prompt. The source describes a collaborative framing conceptually like: "You are one of N instances working together on this problem. Each instance reads shared memory containing what all workers have written. Avoid redundant work." That small instruction changes how the model interprets the strange shared context -- without it, Worker 2 might simply continue Worker 1\'s text as if it were its own; with the collaborative framing, Worker 2 can infer "someone else handled that portion, I should contribute something different."',
      bodyKn: 'Workers ಒಂದೂ ಸಾಮಾನ್ಯ user prompt ಜೊತೆ ಪ್ರಾರಂಭಿಸಲಾಗುವುದಿಲ್ಲ. Source ಒಂದೂ ಸಹಕಾರಿ ಚೌಕಟ್ಟನ್ನೂ ಪರಿಕಲ್ಪನಾತ್ಮಕವಾಗಿ ವಿವರಿಸುತ್ತದೆ: "ನೀವೂ ಈ ಸಮಸ್ಯೆ ಮೇಲೆ ಒಟ್ಟಿಗೆ ಕೆಲಸ ಮಾಡುತ್ತಿರುವ N instances ಗಳಲ್ಲಿ ಒಂದೂ. ಪ್ರತಿ instance ಎಲ್ಲಾ workers ಬರೆದಿರುವುದೂ ಒಳಗೊಂಡ shared memory ಓದುತ್ತದೆ. ಪುನರಾವರ್ತಿತ ಕೆಲಸ ತಪ್ಪಿಸಿ." ಆ ಚಿಕ್ಕ ಸೂಚನೆ model ಆ ವಿಚಿತ್ರ shared context ಅನ್ನೂ ಹೇಗೆ ಅರ್ಥೈಸುತ್ತದೆ ಎಂಬುದನ್ನೂ ಬದಲಾಯಿಸುತ್ತದೆ -- ಅದೂ ಇಲ್ಲದೆ, Worker 2 ಕೇವಲ Worker 1 ya ಪಠ್ಯವನ್ನೂ ಅದೂ ya ಸ್ವಂತವೂ ಎಂಬಂತೆ ಮುಂದುವರಿಸಬಹುದು; ಸಹಕಾರಿ ಚೌಕಟ್ಟಿನ ಜೊತೆ, Worker 2 "ಬೇರೊಬ್ಬರೂ ಆ ಭಾಗ ನಿರ್ವಹಿಸಿದ್ದಾರೂ, ನಾನೂ ಭಿನ್ನವಾದದ್ದೂ ಕೊಡುಗೆ ನೀಡಬೇಕು" ಎಂದೂ ತೀರ್ಮಾನಿಸಬಹುದು.' } },

    { type: 'heading', data: { textEn: 'Why "Hogwild!"', textKn: '"Hogwild!" ಏಕೆ', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'The Name Comes From Hogwild! SGD', headingKn: 'ಹೆಸರೂ Hogwild! SGD ಇಂದ ಬರುತ್ತದೆ',
      bodyEn: 'In asynchronous optimization (Hogwild! SGD), several workers update shared parameters WITHOUT perfectly synchronized updates -- Worker 1, Worker 2, Worker 3 all write to shared parameters concurrently, accepting some raciness in exchange for throughput. Hogwild! inference changes the shared object from parameters to a shared KV cache: workers race to write, and the shared sequence\'s order is determined by write-arrival time, not by a fixed schedule. Async is essential to the idea -- if Worker 1 takes 30ms/token and Worker 2 takes 28ms/token, you do not want "Worker 1 generates, everyone waits, Worker 2 generates, everyone waits" -- they operate asynchronously, writing whenever their step completes.',
      bodyKn: 'Asynchronous optimization (Hogwild! SGD) ನಲ್ಲಿ, ಹಲವೂ workers ಪರಿಪೂರ್ಣವಾಗಿ ಸಿಂಕ್ರೊನೈಸ್ ಮಾಡದ updates ಜೊತೆ shared parameters ಅಪ್ಡೇಟ್ ಮಾಡುತ್ತವೆ -- Worker 1, Worker 2, Worker 3 ಎಲ್ಲಾ ಏಕಕಾಲದಲ್ಲಿ shared parameters ಗೆ ಬರೆಯುತ್ತವೆ, throughput ಗಾಗಿ ಸ್ವಲ್ಪ raciness ಸ್ವೀಕರಿಸುತ್ತಾ. Hogwild! inference shared object ಅನ್ನೂ parameters ಇಂದ ಒಂದೂ shared KV cache ಗೆ ಬದಲಾಯಿಸುತ್ತದೆ: workers ಬರೆಯಲು ಸ್ಪರ್ಧಿಸುತ್ತವೆ, ಮತ್ತೆ shared sequence ya order write-arrival time ಇಂದ ನಿರ್ಧರಿಸಲಾಗುತ್ತದೆ, ಒಂದೂ ಸ್ಥಿರ schedule ಇಂದ ಅಲ್ಲ. Async ಆಲೋಚನೆಗೆ ಅಗತ್ಯ -- Worker 1 30ms/token ತೆಗೆದುಕೊಂಡರೆ ಮತ್ತೆ Worker 2 28ms/token ತೆಗೆದುಕೊಂಡರೆ, ನಿಮಗೆ "Worker 1 ಉತ್ಪಾದಿಸುತ್ತದೆ, ಎಲ್ಲರೂ ಕಾಯುತ್ತಾರೂ, Worker 2 ಉತ್ಪಾದಿಸುತ್ತದೆ, ಎಲ್ಲರೂ ಕಾಯುತ್ತಾರೂ" ಎಂಬುದೂ ಬೇಡ -- ಅವು ಅಸಮಕಾಲಿಕವಾಗಿ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತವೆ, ಅವುಗಳ step ಪೂರ್ಣಗೊಂಡಾಗಲೆಲ್ಲಾ ಬರೆಯುತ್ತವೆ.' } },

    { type: 'heading', data: { textEn: 'The Toy Simulator: Symbolic Tokens Instead of a Real LLM', textKn: 'Toy Simulator: ನಿಜ LLM ಬದಲಿಗೆ Symbolic Tokens', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'Why the Lesson Uses a List of Symbolic Tokens', headingKn: 'Lesson Symbolic Tokens ya List ಅನ್ನೂ ಏಕೆ ಬಳಸುತ್ತದೆ',
      bodyEn: 'A real implementation would contain tensors representing keys and values per layer (real_kv_cache={layer_0:(K0,V0), layer_1:(K1,V1), ...}). The lesson deliberately simplifies this to shared_cache=[] storing symbolic strings like "worker-0:work:A", "worker-1:observe:A", "worker-1:work:B" -- letting the coordination MECHANISM be studied without loading an actual LLM. Three conceptual token categories appear: WORK tokens (useful progress, e.g. W1:WORK:A), OBSERVE tokens (a worker inspecting what others did, e.g. W2:OBSERVE:A), and COORDINATE tokens (a worker changing direction, e.g. W2:COORDINATE:B meaning "I\'ll move to category B instead"). The uploaded material references code/main.py but contains only its description, not the literal source -- so this lesson maps the documented architecture to concepts rather than inventing unseen code.',
      bodyKn: 'ಒಂದೂ ನಿಜ implementation ಪ್ರತಿ layer ಗೆ keys ಮತ್ತೆ values ಪ್ರತಿನಿಧಿಸುವ tensors ಹೊಂದಿರುತ್ತದೆ (real_kv_cache={layer_0:(K0,V0), layer_1:(K1,V1), ...}). Lesson ಉದ್ದೇಶಪೂರ್ವಕವಾಗಿ ಇದನ್ನೂ shared_cache=[] ಗೆ ಸರಳೀಕರಿಸುತ್ತದೆ "worker-0:work:A", "worker-1:observe:A", "worker-1:work:B" ನಂತೆ symbolic strings ಸಂಗ್ರಹಿಸುತ್ತದೆ -- ಒಂದೂ ನಿಜ LLM ಲೋಡ್ ಮಾಡದೆ coordination ಕಾರ್ಯವಿಧಾನ ಅಧ್ಯಯನ ಮಾಡಲು ಬಿಡುತ್ತದೆ. ಮೂರೂ ಪರಿಕಲ್ಪನಾತ್ಮಕ token categories ಕಾಣಿಸುತ್ತವೆ: WORK tokens (ಉಪಯುಕ್ತ progress, ಉದಾ. W1:WORK:A), OBSERVE tokens (ಇತರರೂ ಏನೂ ಮಾಡಿದ್ದಾರೂ ಎಂದೂ ಪರಿಶೀಲಿಸುವ ಒಂದೂ worker, ಉದಾ. W2:OBSERVE:A), ಮತ್ತೆ COORDINATE tokens (ದಿಕ್ಕೂ ಬದಲಾಯಿಸುವ ಒಂದೂ worker, ಉದಾ. W2:COORDINATE:B ಎಂದರೆ "ನಾನೂ ಬದಲಿಗೆ category B ಗೆ ಚಲಿಸುತ್ತೇನೂ"). ಪೇಸ್ಟ್ ಮಾಡಿದ ವಸ್ತು code/main.py ಉಲ್ಲೇಖಿಸುತ್ತದೆ ಆದರೆ ಕೇವಲ ಅದೂ ya ವಿವರಣೆ ಒಳಗೊಂಡಿದೆ, ಅಕ್ಷರಶಃ source ಅಲ್ಲ -- ಆದ್ದರಿಂದ ಈ lesson ಕಾಣದ code ಕಂಡುಹಿಡಿಯುವ ಬದಲಿಗೆ ದಾಖಲಿತ architecture ಅನ್ನೂ concepts ಗೆ ನಕ್ಷೆ ಮಾಡುತ್ತದೆ.' } },

    { type: 'code', data: {
      filename: 'toy_trace.py', headingEn: 'Genuinely simulating a simple two-worker shared-cache trace', headingKn: 'ಒಂದೂ ಸರಳ two-worker shared-cache trace ಅನ್ನೂ ನಿಜವಾಗಿ simulate ಮಾಡುವುದೂ',
      descEn: 'A minimal deterministic simulation of two workers appending work/observe tokens to a shared list, illustrating how each worker\'s later decision can depend on what the other already wrote.',
      descKn: 'ಒಂದು shared list ಗೆ work/observe tokens ಸೇರಿಸುವ ಎರಡೂ workers ya ಒಂದೂ ಕನಿಷ್ಠ deterministic simulation, ಪ್ರತಿ worker ya ನಂತರದ ನಿರ್ಧಾರ ಇತರೂ ಈಗಾಗಲೇ ಬರೆದದ್ದೂ ಮೇಲೆ ಹೇಗೆ ಅವಲಂಬಿತವಾಗಿರಬಹುದೂ ಎಂದೂ ವಿವರಿಸುತ್ತದೆ.',
      code: "shared_cache = []\n\ndef categories_covered(cache):\n    return set(entry.split(':')[-1] for entry in cache if 'WORK' in entry)\n\n# Worker 0 starts on category A\nshared_cache.append('W0:WORK:A')\nprint('after W0:', shared_cache, '| categories covered:', categories_covered(shared_cache))\n\n# Worker 1 reads the cache, sees A is taken, picks B\ncovered = categories_covered(shared_cache)\nchoice = 'B' if 'A' in covered else 'A'\nshared_cache.append(f'W1:WORK:{choice}')\nprint('after W1:', shared_cache, '| categories covered:', categories_covered(shared_cache))" } },
    { type: 'output', data: { output: "after W0: ['W0:WORK:A'] | categories covered: {'A'}\nafter W1: ['W0:WORK:A', 'W1:WORK:B'] | categories covered: {'A', 'B'}" } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: Worker 1\'s Choice Depended on Reading the Shared Cache', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: Worker 1 ಯ Choice Shared Cache ಓದುವುದರ ಮೇಲೆ ಅವಲಂಬಿತವಾಗಿತ್ತು',
      bodyEn: 'Genuinely ran this minimal simulation: Worker 1\'s decision to write category B rather than A was computed directly from reading shared_cache\'s current contents -- no external scheduler assigned "B" to Worker 1. This is a deliberately tiny, deterministic stand-in for the real mechanism the source describes: a capable model reading shared context and inferring which portion of the task remains uncovered. Part 2 will build the full worker loop with a threshold-based coordination heuristic and genuinely trace multi-step runs.',
      bodyKn: 'ಈ ಕನಿಷ್ಠ simulation ಅನ್ನೂ ನಿಜವಾಗಿ ಓಡಿಸಲಾಗಿದೆ: Worker 1 ya category A ಬದಲಿಗೆ B ಬರೆಯುವ ನಿರ್ಧಾರ shared_cache ya ಪ್ರಸ್ತುತ ವಿಷಯಗಳನ್ನೂ ಓದುವುದೂ ಇಂದ ನೇರವಾಗಿ ಲೆಕ್ಕಹಾಕಲಾಗಿದೆ -- ಯಾವುದೇ ಬಾಹ್ಯ scheduler Worker 1 ಗೆ "B" ನಿಯೋಜಿಸಲಿಲ್ಲ. ಇದೂ source ವಿವರಿಸುವ ನಿಜ ಕಾರ್ಯವಿಧಾನಕ್ಕೆ ಉದ್ದೇಶಪೂರ್ವಕವಾಗಿ ಚಿಕ್ಕ, deterministic stand-in: ಒಂದೂ ಸಮರ್ಥ model shared context ಓದುತ್ತಾ ಮತ್ತೆ task ya ಯಾವ ಭಾಗ ಆವರಿಸಲ್ಪಡದೆ ಉಳಿದಿದೆ ಎಂದೂ ತೀರ್ಮಾನಿಸುತ್ತಾ. Part 2 ಒಂದೂ threshold-based coordination heuristic ಜೊತೆ ಪೂರ್ಣ worker loop ನಿರ್ಮಿಸುತ್ತದೆ ಮತ್ತೆ multi-step runs ಅನ್ನೂ ನಿಜವಾಗಿ trace ಮಾಡುತ್ತದೆ.' } },

    { type: 'concept', data: {
      headingEn: 'Why Parallel Workers Can Also Fail', headingKn: 'Parallel Workers ಕೂಡ ಏಕೆ ವಿಫಲಗೊಳ್ಳಬಹುದು',
      bodyEn: 'Running more workers alone does not guarantee speedup. If all workers see "Solve cases A, B, C" and all independently decide "I\'ll solve A," you get Worker 1->A, Worker 2->A, Worker 3->A, Worker 4->A -- four times the compute without four times the useful work. That is redundant reasoning, and Hogwild! only becomes interesting if workers can DETECT such redundancy and pivot. This ties directly to coordination overhead c: workers must periodically inspect shared state and decide what has already been done, what is incomplete, and what to work on -- those operations are not free. For useful reasoning=20,000 tokens and coordination=200 tokens, overhead is small; for useful answer=100 tokens and coordination=200 tokens, coordination costs more than the task itself. This is why Hogwild! is primarily interesting for LONG reasoning workloads, not short responses.',
      bodyKn: 'ಕೇವಲ ಹೆಚ್ಚೂ workers ಓಡಿಸುವುದೂ speedup ಖಾತ್ರಿಪಡಿಸುವುದಿಲ್ಲ. ಎಲ್ಲಾ workers "Cases A, B, C ಬಗೆಹರಿಸಿ" ಎಂದೂ ನೋಡಿದರೆ ಮತ್ತೆ ಎಲ್ಲಾ ಸ್ವತಂತ್ರವಾಗಿ "ನಾನೂ A ಬಗೆಹರಿಸುತ್ತೇನೂ" ಎಂದೂ ತೀರ್ಮಾನಿಸಿದರೆ, ನಿಮಗೆ Worker 1->A, Worker 2->A, Worker 3->A, Worker 4->A ಸಿಗುತ್ತದೆ -- ನಾಲ್ಕೂ ಪಟ್ಟೂ compute ಆದರೆ ನಾಲ್ಕೂ ಪಟ್ಟೂ ಉಪಯುಕ್ತ ಕೆಲಸ ಇಲ್ಲ. ಇದೂ ಪುನರಾವರ್ತಿತ reasoning, ಮತ್ತೆ workers ಅಂತಹ ಪುನರಾವರ್ತನೆಯನ್ನೂ ಪತ್ತೆ ಮಾಡಿ ಬದಲಾಯಿಸಬಹುದಾದಾಗ ಮಾತ್ರ Hogwild! ಆಸಕ್ತಿದಾಯಕವಾಗುತ್ತದೆ. ಇದೂ coordination overhead c ಗೆ ನೇರವಾಗಿ ಸಂಪರ್ಕಿಸುತ್ತದೆ: workers ಆವರ್ತಕವಾಗಿ shared state ಪರಿಶೀಲಿಸಬೇಕು ಮತ್ತೆ ಈಗಾಗಲೇ ಏನೂ ಮಾಡಲಾಗಿದೆ, ಏನೂ ಅಪೂರ್ಣ, ಮತ್ತೆ ಏನೂ ಮೇಲೆ ಕೆಲಸ ಮಾಡಬೇಕು ಎಂದೂ ನಿರ್ಧರಿಸಬೇಕು -- ಆ operations ಉಚಿತ ಅಲ್ಲ. Useful reasoning=20,000 tokens ಮತ್ತೆ coordination=200 tokens ಗೆ, overhead ಚಿಕ್ಕದೂ; useful answer=100 tokens ಮತ್ತೆ coordination=200 tokens ಗೆ, coordination task ಗಿಂತ ಹೆಚ್ಚೂ ವೆಚ್ಚ ಮಾಡುತ್ತದೆ. Hogwild! ಪ್ರಾಥಮಿಕವಾಗಿ ಉದ್ದ reasoning workloads ಗೆ ಆಸಕ್ತಿದಾಯಕ ಏಕೆ ಎಂಬುದೂ ಗೆ ಇದೇ ಕಾರಣ, ಚಿಕ್ಕ responses ಗೆ ಅಲ್ಲ.' } },

    { type: 'concept', data: {
      headingEn: 'Common Misconception', headingKn: 'ಸಾಮಾನ್ಯ ತಪ್ಪುಗ್ರಹಿಕೆ',
      bodyEn: '"Hogwild! is just running several LLMs at once, like voting." No -- that already exists in voting ensembles. The important idea is running several reasoning workers concurrently AND giving them one shared evolving context, so each can repeatedly READ shared work -> REASON about what remains -> CHOOSE useful work -> WRITE it back, with other workers immediately seeing the update. Also worth flagging: "emergent coordination" does not mean coordination is guaranteed -- it means coordination is not explicitly programmed. A weak reasoning model can still fail to redirect and simply duplicate another worker\'s effort (Part 2 and 3 will genuinely demonstrate this failure mode).',
      bodyKn: '"Hogwild! ಕೇವಲ ಹಲವೂ LLMs ಗಳನ್ನೂ ಏಕಕಾಲದಲ್ಲಿ ಓಡಿಸುವುದೂ, voting ನಂತೆ." ಇಲ್ಲ -- ಅದೂ ಈಗಾಗಲೇ voting ensembles ನಲ್ಲಿ ಅಸ್ತಿತ್ವದಲ್ಲಿದೆ. ಮುಖ್ಯ ಆಲೋಚನೆ ಹಲವೂ reasoning workers ಏಕಕಾಲದಲ್ಲಿ ಓಡಿಸುವುದೂ ಮತ್ತೆ ಅವುಗಳಿಗೆ ಒಂದೂ shared evolving context ನೀಡುವುದೂ, ಆದ್ದರಿಂದ ಪ್ರತಿಯೊಂದೂ ಪುನರಾವರ್ತಿತವಾಗಿ shared work READ ಮಾಡಬಹುದು -> ಉಳಿದಿರುವುದೂ ಬಗ್ಗೆ REASON ಮಾಡಬಹುದು -> ಉಪಯುಕ್ತ ಕೆಲಸ CHOOSE ಮಾಡಬಹುದು -> ಅದನ್ನೂ WRITE ಮಾಡಬಹುದು, ಇತರೂ workers ತಕ್ಷಣ update ನೋಡುತ್ತಾ. ಗುರುತಿಸಲು ಯೋಗ್ಯ: "emergent coordination" ಎಂದರೆ coordination ಖಾತ್ರಿಪಡಿಸಲಾಗಿದೆ ಎಂದೂ ಅರ್ಥವಲ್ಲ -- ಇದೂ coordination ಸ್ಪಷ್ಟವಾಗಿ ಪ್ರೋಗ್ರಾಮ್ ಮಾಡಲಾಗಿಲ್ಲ ಎಂದೂ ಅರ್ಥ. ಒಂದೂ ದುರ್ಬಲ reasoning model ಇನ್ನೂ ಮರುನಿರ್ದೇಶಿಸಲು ವಿಫಲಗೊಳ್ಳಬಹುದು ಮತ್ತೆ ಕೇವಲ ಇನ್ನೊಂದೂ worker ya ಪ್ರಯತ್ನವನ್ನೂ ಪುನರಾವರ್ತಿಸಬಹುದು (Part 2 ಮತ್ತೆ 3 ಈ ವೈಫಲ್ಯ mode ಅನ್ನೂ ನಿಜವಾಗಿ ಪ್ರದರ್ಶಿಸುತ್ತವೆ).' } },

    { type: 'concept', data: {
      headingEn: 'Key Terms', headingKn: 'ಮುಖ್ಯ ಪದಗಳು',
      bodyEn: '• Hogwild! inference: multiple instances of the same LLM operate concurrently through shared cache state, named after Hogwild! SGD\'s asynchronous shared-parameter updates\n• Shared KV cache: common attention-state memory visible across all workers, replacing each worker\'s isolated cache\n• Emergent coordination: workers divide or correct work using their existing reasoning ability rather than a separately trained coordination protocol -- genuinely demonstrated above via a minimal simulation\n• Task-level parallelism: parallelizing DIFFERENT pieces of a reasoning problem across workers, distinct from token-level parallelism (speculative decoding) which speeds up ONE sequence\n• Coordination overhead (c): time/tokens spent understanding shared work and deciding what to do -- must stay small relative to useful reasoning for Hogwild! to pay off\n• Redundant work: several workers spending compute on the same already-covered subproblem, the primary failure mode Hogwild! must avoid',
      bodyKn: '• Hogwild! inference: ಅದೇ LLM ya ಬಹು instances shared cache state ಮೂಲಕ ಏಕಕಾಲದಲ್ಲಿ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತವೆ, Hogwild! SGD ya asynchronous shared-parameter updates ya ಹೆಸರಿನಲ್ಲಿ\n• Shared KV cache: ಎಲ್ಲಾ workers ಗಳಾದ್ಯಂತ ಗೋಚರಿಸುವ ಸಾಮಾನ್ಯ attention-state memory, ಪ್ರತಿ worker ya ಪ್ರತ್ಯೇಕ cache ಬದಲಾಯಿಸುತ್ತದೆ\n• Emergent coordination: workers ಪ್ರತ್ಯೇಕವಾಗಿ ತರಬೇತಿ ಪಡೆದ coordination protocol ಬದಲಿಗೆ ಅವುಗಳ ಈಗಾಗಲೇ ಇರುವ reasoning ಸಾಮರ್ಥ್ಯ ಬಳಸಿ ಕೆಲಸ ವಿಭಜಿಸುತ್ತವೆ ಅಥವಾ ಸರಿಪಡಿಸುತ್ತವೆ -- ಮೇಲೆ ಒಂದೂ ಕನಿಷ್ಠ simulation ಮೂಲಕ ನಿಜವಾಗಿ ಪ್ರದರ್ಶಿಸಲಾಗಿದೆ\n• Task-level parallelism: reasoning ಸಮಸ್ಯೆಯ ಭಿನ್ನ ಭಾಗಗಳನ್ನೂ workers ಗಳಾದ್ಯಂತ parallelize ಮಾಡುವುದೂ, ONE sequence ವೇಗಗೊಳಿಸುವ token-level parallelism (speculative decoding) ಇಂದ ಭಿನ್ನ\n• Coordination overhead (c): shared work ಅರ್ಥಮಾಡಿಕೊಳ್ಳಲು ಮತ್ತೆ ಏನೂ ಮಾಡಬೇಕು ಎಂದೂ ನಿರ್ಧರಿಸಲು ಖರ್ಚಾದ ಸಮಯ/tokens -- Hogwild! ಫಲ ನೀಡಲು ಉಪಯುಕ್ತ reasoning ಗೆ ಸಾಪೇಕ್ಷವಾಗಿ ಚಿಕ್ಕದೂ ಆಗಿ ಉಳಿಯಬೇಕು\n• Redundant work: ಹಲವೂ workers ಅದೇ ಈಗಾಗಲೇ-ಆವರಿಸಿದ subproblem ಮೇಲೆ compute ಖರ್ಚು ಮಾಡುತ್ತವೆ, Hogwild! ತಪ್ಪಿಸಬೇಕಾದ ಪ್ರಾಥಮಿಕ ವೈಫಲ್ಯ mode' } },

    { type: 'concept', data: {
      headingEn: 'Key Takeaways', headingKn: 'ಮುಖ್ಯ ಅಂಶಗಳು',
      bodyEn: "• Genuinely computed a 50,000-token reasoning trace takes ~23.8 minutes at 35 tokens/sec -- motivating the search for parallelism beyond a single autoregressive stream.\n• Token-level parallelism (speculative decoding) speeds up ONE sequence; task-level parallelism (Hogwild!) splits DIFFERENT pieces of reasoning across workers -- orthogonal axes.\n• Voting ensembles, tree-of-thought, and multi-agent frameworks all use EXPLICIT coordination (majority vote, branch-and-prune, or a designed coordinator); Hogwild! removes that explicit protocol in favor of a shared KV cache workers read and write.\n• Genuinely simulated a minimal two-worker trace confirming a worker's category choice can be computed directly from reading the shared cache -- no external scheduler required.\n• Hogwild! is named after Hogwild! SGD's asynchronous shared-parameter updates; workers race to write, and shared-sequence order is determined by write-arrival time, not a fixed schedule.\n• Parallel workers can fail if they duplicate work instead of detecting redundancy -- coordination overhead must stay small relative to useful reasoning, which is why Hogwild! suits long reasoning tasks far better than short responses.",
      bodyKn: '• 50,000-token reasoning trace 35 tokens/sec ನಲ್ಲಿ ~23.8 ನಿಮಿಷಗಳು ತೆಗೆದುಕೊಳ್ಳುತ್ತದೆ ಎಂದೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಲಾಗಿದೆ -- ಒಂಟಿ autoregressive stream ಆಚೆ parallelism ಹುಡುಕಾಟಕ್ಕೆ ಪ್ರೇರೇಪಿಸುತ್ತದೆ.\n• Token-level parallelism (speculative decoding) ONE sequence ವೇಗಗೊಳಿಸುತ್ತದೆ; task-level parallelism (Hogwild!) reasoning ya ಭಿನ್ನ ಭಾಗಗಳನ್ನೂ workers ಗಳಾದ್ಯಂತ ವಿಭಜಿಸುತ್ತದೆ -- ಆರ್ಥೊಗೊನಲ್ axes.\n• Voting ensembles, tree-of-thought, ಮತ್ತೆ multi-agent frameworks ಎಲ್ಲಾ EXPLICIT coordination ಬಳಸುತ್ತವೆ (majority vote, branch-and-prune, ಅಥವಾ ಒಂದೂ ವಿನ್ಯಾಸಗೊಳಿಸಿದ coordinator); Hogwild! ಆ ಸ್ಪಷ್ಟ protocol ಅನ್ನೂ ತೆಗೆದುಹಾಕುತ್ತದೆ, workers ಓದುವ ಮತ್ತೆ ಬರೆಯುವ ಒಂದೂ shared KV cache ಗೆ ಪರವಾಗಿ.\n• ಒಂದೂ ಕನಿಷ್ಠ two-worker trace ನಿಜವಾಗಿ simulate ಮಾಡಲಾಗಿದೆ, ಒಂದೂ worker ya category choice shared cache ಓದುವುದೂ ಇಂದ ನೇರವಾಗಿ ಲೆಕ್ಕಹಾಕಬಹುದು ಎಂದೂ ದೃಢಪಡಿಸುತ್ತಾ -- ಯಾವುದೇ ಬಾಹ್ಯ scheduler ಬೇಡ.\n• Hogwild! Hogwild! SGD ya asynchronous shared-parameter updates ya ಹೆಸರಿನಲ್ಲಿ ಇಡಲಾಗಿದೆ; workers ಬರೆಯಲು ಸ್ಪರ್ಧಿಸುತ್ತವೆ, ಮತ್ತೆ shared-sequence order write-arrival time ಇಂದ ನಿರ್ಧರಿಸಲಾಗುತ್ತದೆ, ಒಂದೂ ಸ್ಥಿರ schedule ಇಂದ ಅಲ್ಲ.\n• Parallel workers ಪುನರಾವರ್ತನೆ ಪತ್ತೆ ಮಾಡುವ ಬದಲಿಗೆ ಕೆಲಸ ಪುನರಾವರ್ತಿಸಿದರೆ ವಿಫಲಗೊಳ್ಳಬಹುದು -- coordination overhead ಉಪಯುಕ್ತ reasoning ಗೆ ಸಾಪೇಕ್ಷವಾಗಿ ಚಿಕ್ಕದೂ ಆಗಿ ಉಳಿಯಬೇಕು, Hogwild! ಚಿಕ್ಕ responses ಗಿಂತ ಉದ್ದ reasoning tasks ಗೆ ಬಹಳ ಚೆನ್ನಾಗಿ ಸೂಕ್ತವಾಗುವುದೂ ಗೆ ಇದೇ ಕಾರಣ.' } },

    { type: 'concept', data: {
      headingEn: 'Preview: Part 2', headingKn: 'Preview: Part 2',
      bodyEn: 'Part 2 covers the mechanics that determine whether Hogwild! parallelism is actually useful: why RoPE\'s relative-position property makes a shared, concurrently-written cache tractable, the Amdahl-style wall-time equation T_N=T_serial*((1-p)+p/N)+coordination_overhead, and genuinely working through the lesson\'s concrete 10,000-step example to derive its cited 1.8x speedup.',
      bodyKn: 'Part 2 Hogwild! parallelism ನಿಜವಾಗಿ ಉಪಯುಕ್ತವಾಗಿದೆಯೇ ಎಂದೂ ನಿರ್ಧರಿಸುವ ಕಾರ್ಯವಿಧಾನಗಳನ್ನೂ ಒಳಗೊಳ್ಳುತ್ತದೆ: RoPE ya relative-position ಗುಣಲಕ್ಷಣ ಒಂದೂ shared, ಏಕಕಾಲದಲ್ಲಿ-ಬರೆದ cache ಅನ್ನೂ ಏಕೆ ನಿರ್ವಹಿಸಬಹುದಾಗಿ ಮಾಡುತ್ತದೆ, Amdahl-style wall-time equation T_N=T_serial*((1-p)+p/N)+coordination_overhead, ಮತ್ತೆ lesson ya ನಿರ್ದಿಷ್ಟ 10,000-step ಉದಾಹರಣೆ ಮೂಲಕ ನಿಜವಾಗಿ ಕೆಲಸ ಮಾಡಿ ಅದೂ ya ಉಲ್ಲೇಖಿತ 1.8x speedup ಪಡೆಯುವುದೂ.' } },

    { type: 'quiz', data: { questions: [
      { q: 'What is the defining architectural idea behind Hogwild! inference?',
        qKn: 'Hogwild! inference ya ಹಿಂದಿನ ವ್ಯಾಖ್ಯಾನಿಸುವ architectural ಆಲೋಚನೆ ಏನೂ?',
        opts: ['Every worker receives a separate model', 'Every worker has a completely independent KV cache', 'Multiple workers operate against shared cache state', 'Workers generate multiple consecutive tokens simultaneously'], correct: 2,
        optsKn: ['ಪ್ರತಿ worker ಒಂದೂ ಪ್ರತ್ಯೇಕ model ಪಡೆಯುತ್ತದೆ', 'ಪ್ರತಿ worker ಗೆ ಸಂಪೂರ್ಣವಾಗಿ ಸ್ವತಂತ್ರ KV cache ಇದೆ', 'ಬಹು workers shared cache state ಎದುರೂ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತವೆ', 'Workers ಬಹು ಸತತ tokens ಏಕಕಾಲದಲ್ಲಿ ಉತ್ಪಾದಿಸುತ್ತವೆ'] },
      { q: 'What is the primary difference between a voting ensemble and Hogwild!?',
        qKn: 'ಒಂದು voting ensemble ಮತ್ತೆ Hogwild! ನಡುವಿನ ಪ್ರಾಥಮಿಕ ವ್ಯತ್ಯಾಸ ಏನೂ?',
        opts: ['Voting requires transformers but Hogwild! does not', 'Voting workers usually solve independently, whereas Hogwild! workers can observe one another\'s progress', 'Hogwild! uses only one worker', 'Voting requires a shared KV cache'], correct: 1,
        optsKn: ['Voting ಗೆ transformers ಬೇಕು ಆದರೆ Hogwild! ಗೆ ಬೇಡ', 'Voting workers ಸಾಮಾನ್ಯವಾಗಿ ಸ್ವತಂತ್ರವಾಗಿ ಬಗೆಹರಿಸುತ್ತವೆ, ಆದರೆ Hogwild! workers ಪರಸ್ಪರ progress ಗಮನಿಸಬಹುದು', 'Hogwild! ಕೇವಲ ಒಂದೂ worker ಬಳಸುತ್ತದೆ', 'Voting ಗೆ ಒಂದೂ shared KV cache ಬೇಕು'] },
      { q: 'What does emergent coordination mean?',
        qKn: 'Emergent coordination ya ಅರ್ಥ ಏನೂ?',
        opts: ['A human manually assigns tasks to workers', 'A learned router assigns every subproblem', 'Workers infer useful task division from shared context without a dedicated explicit coordination protocol', 'Workers execute in strict round-robin order'], correct: 2,
        optsKn: ['ಒಂದೂ ಮಾನವ workers ಗೆ ಕೈಯಾರೆ tasks ನಿಯೋಜಿಸುತ್ತಾರೂ', 'ಒಂದೂ learned router ಪ್ರತಿ subproblem ನಿಯೋಜಿಸುತ್ತದೆ', 'Workers ಪ್ರತ್ಯೇಕ ಸ್ಪಷ್ಟ coordination protocol ಇಲ್ಲದೆ shared context ಇಂದ ಉಪಯುಕ್ತ task division ತೀರ್ಮಾನಿಸುತ್ತವೆ', 'Workers ಕಟ್ಟುನಿಟ್ಟಾದ round-robin order ನಲ್ಲಿ execute ಆಗುತ್ತವೆ'] },
      { q: 'Genuinely confirmed: how long does a 50,000-token reasoning trace take at 35 tokens/sec?',
        qKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: 35 tokens/sec ನಲ್ಲಿ ಒಂದೂ 50,000-token reasoning trace ಎಷ್ಟೂ ಸಮಯ ತೆಗೆದುಕೊಳ್ಳುತ್ತದೆ?',
        opts: ['~2.4 minutes', '~14.3 minutes', '~23.8 minutes', '~50 minutes'], correct: 2,
        optsKn: ['~2.4 ನಿಮಿಷಗಳು', '~14.3 ನಿಮಿಷಗಳು', '~23.8 ನಿಮಿಷಗಳು', '~50 ನಿಮಿಷಗಳು'] },
      { q: 'Why might four Hogwild! workers fail to provide a 4x speedup?',
        qKn: 'ನಾಲ್ಕೂ Hogwild! workers 4x speedup ನೀಡಲು ಏಕೆ ವಿಫಲಗೊಳ್ಳಬಹುದು?',
        opts: ['Transformers cannot use GPUs', 'Workers may duplicate reasoning and spend resources coordinating', 'KV caches cannot contain more than one token', 'Parallel inference always halves accuracy'], correct: 1,
        optsKn: ['Transformers GPUs ಬಳಸಲು ಸಾಧ್ಯವಿಲ್ಲ', 'Workers reasoning ಪುನರಾವರ್ತಿಸಬಹುದು ಮತ್ತೆ coordinate ಮಾಡುವುದೂ ಗೆ resources ಖರ್ಚು ಮಾಡಬಹುದು', 'KV caches ಒಂದೂ token ಗಿಂತ ಹೆಚ್ಚೂ ಹೊಂದಿರಲು ಸಾಧ್ಯವಿಲ್ಲ', 'Parallel inference ಯಾವಾಗಲೂ accuracy ಅರ್ಧಗೊಳಿಸುತ್ತದೆ'] },
    ] } },
  ],
};
