const phaseId = '6a369d5666020ed05b321334'; // Phase 9
const moduleId = '6a369d5766020ed05b321361'; // Module 138: Streaming Speech-to-Speech (Moshi, Hibiki)

module.exports = {
  phaseId,
  moduleId,
  order: 2,
  type: 'reading',
  duration: 50,
  difficulty: 'advanced',
  status: 'published',
  title: 'Streaming Speech-to-Speech (Part 2) — Hibiki, Sesame CSM & Choosing an Architecture',
  titleKn: 'Streaming Speech-to-Speech (Part 2) — Hibiki, Sesame CSM & Architecture ಆಯ್ಕೆ',
  desc: 'Hibiki extends Moshi\'s full-duplex architecture to real-time speech-to-speech translation, Sesame CSM takes a context-conditioned middle path between full-duplex and pipeline architectures, and a decision tree ties Modules 134-138 together into a single practical framework for choosing a voice-AI architecture.',
  objectives: [
    'Explain how Hibiki adapts Moshi\'s architecture for real-time speech-to-speech translation.',
    'Understand Sesame CSM\'s context-conditioned, non-full-duplex design and where it sits between pipelines and Moshi.',
    'Read the lesson\'s illustrative WebSocket client code and identify what is illustrative versus runnable.',
    'Compare full-duplex and pipeline architectures on a concrete tradeoff table.',
    'Apply a decision tree to choose an architecture for a given voice-AI product requirement.',
  ],
  objectivesKn: [
    'Hibiki real-time speech-to-speech translation ಗಾಗಿ Moshi ನ architecture ಹೇಗೆ ಅಳವಡಿಸುತ್ತದೆ ಎಂದು ವಿವರಿಸಿ.',
    'Sesame CSM ನ context-conditioned, non-full-duplex ವಿನ್ಯಾಸ ಮತ್ತು ಇದೂ pipelines ಮತ್ತು Moshi ನಡುವೆ ಎಲ್ಲಿ ಕುಳಿತಿದೆ ಎಂದು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'ಲೆಸನ್‌ನ ವಿವರಣಾತ್ಮಕ WebSocket client code ಓದಿ ಮತ್ತು ಏನೂ ವಿವರಣಾತ್ಮಕ vs ಚಲಾಯಿಸಬಹುದಾದ ಎಂದು ಗುರುತಿಸಿ.',
    'ಒಂದು ನಿರ್ದಿಷ್ಟ tradeoff table ಮೇಲೆ full-duplex ಮತ್ತು pipeline architectures ಹೋಲಿಸಿ.',
    'ಒಂದು ನಿರ್ದಿಷ್ಟ voice-AI product ಅಗತ್ಯಕ್ಕೆ ಒಂದು architecture ಆಯ್ಕೆ ಮಾಡಲು ಒಂದು decision tree ಅನ್ವಯಿಸಿ.',
  ],
  blocks: [
    { type: 'heading', data: { level: 'H1', textEn: 'Streaming Speech-to-Speech (Part 2) — Hibiki, Sesame CSM & Choosing an Architecture', textKn: 'Streaming Speech-to-Speech (Part 2) — Hibiki, Sesame CSM & Architecture ಆಯ್ಕೆ' } },
    { type: 'concept', data: {
      headingEn: 'Learning Objectives', headingKn: 'ಕಲಿಕಾ ಗುರಿಗಳು',
      bodyEn: '• Part 1 established why Moshi collapses VAD/STT/LLM/TTS into one full-duplex model. Part 2 looks at two more points on the same design spectrum: Hibiki, which repurposes the same architecture for real-time translation, and Sesame CSM, which deliberately does not go full-duplex and instead takes a context-conditioned approach.\n• This lesson closes Module 138 by tying Modules 134-138 together: VAD, real-time audio, pipeline voice assistants, codecs, turn-taking, and now full-duplex/context-conditioned architectures all become inputs to one practical decision: which architecture should an actual product use?',
      bodyKn: '• Part 1 Moshi ಏಕೆ VAD/STT/LLM/TTS ಅನ್ನೂ ಒಂದೇ full-duplex model ಆಗಿ ಕುಸಿಯುತ್ತದೆ ಎಂದು ಸ್ಥಾಪಿಸಿತು. Part 2 ಅದೇ ವಿನ್ಯಾಸ spectrum ನಲ್ಲಿ ಇನ್ನೂ ಎರಡು ಬಿಂದುಗಳನ್ನೂ ನೋಡುತ್ತದೆ: Hibiki, ಇದೂ real-time translation ಗಾಗಿ ಅದೇ architecture ಮರುಬಳಕೆ ಮಾಡುತ್ತದೆ, ಮತ್ತು Sesame CSM, ಇದೂ ಉದ್ದೇಶಪೂರ್ವಕವಾಗಿ full-duplex ಗೆ ಹೋಗುವುದಿಲ್ಲ ಮತ್ತು ಬದಲಿಗೆ ಒಂದು context-conditioned ವಿಧಾನ ತೆಗೆದುಕೊಳ್ಳುತ್ತದೆ.\n• ಈ lesson Modules 134-138 ಅನ್ನೂ ಒಟ್ಟಿಗೆ ಜೋಡಿಸುವ ಮೂಲಕ Module 138 ಮುಚ್ಚುತ್ತದೆ: VAD, real-time audio, pipeline voice assistants, codecs, turn-taking, ಮತ್ತು ಈಗ full-duplex/context-conditioned architectures ಎಲ್ಲಾ ಒಂದು ಪ್ರಾಯೋಗಿಕ ನಿರ್ಧಾರಕ್ಕೆ inputs ಆಗುತ್ತವೆ: ಒಂದು ನಿಜ product ಯಾವ architecture ಬಳಸಬೇಕು?' } },

    { type: 'heading', data: { level: 'H2', textEn: 'Hibiki — Full-Duplex Speech Translation', textKn: 'Hibiki — Full-Duplex Speech Translation' } },
    { type: 'concept', data: {
      headingEn: 'The Same Architecture, a Different Task', headingKn: 'ಅದೇ Architecture, ಒಂದು ಬೇರೆ Task',
      bodyEn: '• Hibiki, also from Kyutai, reuses Moshi\'s two-stream, temporal/depth-transformer, Mimi-token architecture but repurposes it for simultaneous speech-to-speech translation rather than open dialogue: one stream carries the source-language input, the other generates target-language speech, incrementally, while the source is still being spoken -- the same way a professional simultaneous interpreter speaks a sentence behind the speaker rather than waiting for them to finish.\n• Hibiki-Zero is a distilled/lighter variant of this idea, trading some quality for speed and deployability -- the same accuracy-vs-latency tradeoff this course has now seen repeatedly (VAD choice in Module 137, STT-1B vs STT-2.6B look-ahead in Module 137 Lesson 2, EnCodec bandwidth in Module 136).\n• The key architectural insight worth naming explicitly: full-duplex was not designed as a "dialogue-only" trick. It is a general solution to "process one continuous audio stream while producing another continuous audio stream with low latency," and translation is simply a second application of that same underlying capability.',
      bodyKn: '• Hibiki, Kyutai ಇಂದ ಕೂಡ, Moshi ನ two-stream, temporal/depth-transformer, Mimi-token architecture ಮರುಬಳಕೆ ಮಾಡುತ್ತದೆ ಆದರೆ ಇದನ್ನೂ ಮುಕ್ತ ಸಂಭಾಷಣೆಗಿಂತ ಏಕಕಾಲಿಕ speech-to-speech translation ಗಾಗಿ ಮರುಉದ್ದೇಶಿಸುತ್ತದೆ: ಒಂದು stream ಮೂಲ-ಭಾಷೆಯ input ಒಯ್ಯುತ್ತದೆ, ಇನ್ನೊಂದೂ ಗುರಿ-ಭಾಷೆಯ ಭಾಷಣ ಉತ್ಪಾದಿಸುತ್ತದೆ, ಕ್ರಮೇಣ, ಮೂಲ ಇನ್ನೂ ಮಾತನಾಡುತ್ತಿರುವಾಗ -- ಒಬ್ಬ ವೃತ್ತಿಪರ ಏಕಕಾಲಿಕ ಅನುವಾದಕ ಮಾತನಾಡುವವರು ಮುಗಿಸುವವರೆಗೆ ಕಾಯುವ ಬದಲಿಗೆ ಮಾತನಾಡುವವರ ಹಿಂದೆ ಒಂದು ವಾಕ್ಯ ಮಾತನಾಡುವ ಅದೇ ರೀತಿ.\n• Hibiki-Zero ಈ ಕಲ್ಪನೆಯ ಒಂದು distilled/ಹಗುರ variant, ವೇಗ ಮತ್ತು deployability ಗಾಗಿ ಕೆಲವು ಗುಣಮಟ್ಟ ವಿನಿಮಯ ಮಾಡುತ್ತಾ -- ಈ ಕೋರ್ಸ್ ಈಗ ಪದೇ ಪದೇ ಕಂಡ ಅದೇ accuracy-vs-latency tradeoff (Module 137 ನಲ್ಲಿ VAD ಆಯ್ಕೆ, Module 137 Lesson 2 ನಲ್ಲಿ STT-1B vs STT-2.6B look-ahead, Module 136 ನಲ್ಲಿ EnCodec bandwidth).\n• ಸ್ಪಷ್ಟವಾಗಿ ಹೆಸರಿಸಲು ಯೋಗ್ಯವಾದ ಮುಖ್ಯ architectural ಒಳನೋಟ: full-duplex ಅನ್ನೂ ಒಂದು "ಸಂಭಾಷಣೆ-ಮಾತ್ರ" ಟ್ರಿಕ್ ಆಗಿ ವಿನ್ಯಾಸಗೊಳಿಸಲಾಗಿಲ್ಲ. ಇದೂ "ಒಂದು ನಿರಂತರ audio stream ಪ್ರಕ್ರಿಯೆಗೊಳಿಸುತ್ತಿರುವಾಗ ಕಡಿಮೆ latency ಜೊತೆ ಇನ್ನೊಂದೂ ನಿರಂತರ audio stream ಉತ್ಪಾದಿಸುವುದೂ" ಗೆ ಒಂದು ಸಾಮಾನ್ಯ ಪರಿಹಾರ, ಮತ್ತು translation ಕೇವಲ ಅದೇ ಆಧಾರವಾಗಿರುವ ಸಾಮರ್ಥ್ಯದ ಒಂದು ಎರಡನೇ ಅಪ್ಲಿಕೇಶನ್.' } },

    { type: 'heading', data: { level: 'H2', textEn: 'Sesame CSM — Context-Conditioned, Not Full-Duplex', textKn: 'Sesame CSM — Context-Conditioned, Full-Duplex ಅಲ್ಲ' } },
    { type: 'concept', data: {
      headingEn: 'A Deliberate Middle Path', headingKn: 'ಒಂದು ಉದ್ದೇಶಪೂರ್ವಕ ಮಧ್ಯದ ಮಾರ್ಗ',
      bodyEn: '• Sesame\'s Conversational Speech Model (CSM) uses a Llama-3 backbone paired with a Mimi codec head, but is explicitly context-conditioned rather than full-duplex: it generates speech conditioned on the full conversation history (previous turns, both audio and text), producing highly natural, context-aware prosody, but it still operates in a turn-based mode rather than processing two simultaneous live audio streams the way Moshi does.\n• This is a deliberate, not accidental, design choice. Full-duplex buys the lowest possible latency and native interruption handling but is architecturally more complex and, as documented in Part 1, has heavier real-world deployment requirements. A context-conditioned turn-based model like CSM is simpler to integrate into an existing pipeline-style product (it can slot in as a TTS-like component with unusually good context awareness) while still capturing much of the naturalness benefit of modeling conversation history explicitly -- a genuinely different point on the same tradeoff curve, not a strictly worse one.',
      bodyKn: '• Sesame ನ Conversational Speech Model (CSM) ಒಂದು Llama-3 backbone ಅನ್ನೂ ಒಂದು Mimi codec head ಜೊತೆ ಜೋಡಿಸಿ ಬಳಸುತ್ತದೆ, ಆದರೆ ಸ್ಪಷ್ಟವಾಗಿ full-duplex ಗಿಂತ context-conditioned: ಇದೂ ಪೂರ್ಣ ಸಂಭಾಷಣೆ ಇತಿಹಾಸ (ಹಿಂದಿನ turns, audio ಮತ್ತು ಪಠ್ಯ ಎರಡೂ) ಮೇಲೆ ಷರತ್ತಿಗೊಳಪಟ್ಟು ಭಾಷಣ ಉತ್ಪಾದಿಸುತ್ತದೆ, ಹೆಚ್ಚು ಸ್ವಾಭಾವಿಕ, context-ಅರಿವುಳ್ಳ prosody ಉತ್ಪಾದಿಸುತ್ತಾ, ಆದರೆ ಇದೂ Moshi ಮಾಡುವ ರೀತಿ ಎರಡು ಏಕಕಾಲಿಕ ಲೈವ್ audio streams ಪ್ರಕ್ರಿಯೆಗೊಳಿಸುವ ಬದಲಿಗೆ ಇನ್ನೂ ಒಂದು turn-based ಮೋಡ್‌ನಲ್ಲಿ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತದೆ.\n• ಇದೂ ಒಂದು ಉದ್ದೇಶಪೂರ್ವಕ, ಆಕಸ್ಮಿಕವಲ್ಲದ, ವಿನ್ಯಾಸ ಆಯ್ಕೆ. Full-duplex ಅತ್ಯಂತ ಕಡಿಮೆ ಸಾಧ್ಯ latency ಮತ್ತು ಸ್ಥಳೀಯ interruption handling ಖರೀದಿಸುತ್ತದೆ ಆದರೆ architecturally ಹೆಚ್ಚು ಸಂಕೀರ್ಣ ಮತ್ತು, Part 1 ನಲ್ಲಿ ದಾಖಲಿಸಿದಂತೆ, ಭಾರೀ ನಿಜ-ಪ್ರಪಂಚ deployment ಅಗತ್ಯಗಳನ್ನೂ ಹೊಂದಿದೆ. CSM ನಂತಹ ಒಂದು context-conditioned turn-based model ಅನ್ನೂ ಒಂದು ಅಸ್ತಿತ್ವದಲ್ಲಿರುವ pipeline-style product ಗೆ ಸಂಯೋಜಿಸಲು ಸರಳ (ಇದೂ ಅಸಾಧಾರಣವಾಗಿ ಒಳ್ಳೆಯ context ಅರಿವು ಹೊಂದಿರುವ ಒಂದು TTS-ರೀತಿಯ ಘಟಕವಾಗಿ ಸ್ಲಾಟ್ ಮಾಡಬಹುದು) ಸಂಭಾಷಣೆ ಇತಿಹಾಸ ಸ್ಪಷ್ಟವಾಗಿ ಮಾಡೆಲಿಂಗ್ ಮಾಡುವ ಸ್ವಾಭಾವಿಕತೆಯ ಪ್ರಯೋಜನದ ಬಹಳಷ್ಟನ್ನೂ ಇನ್ನೂ ಸೆರೆಹಿಡಿಯುತ್ತಿರುವಾಗಲೇ -- ಅದೇ tradeoff curve ನಲ್ಲಿ ನಿಜವಾಗಿ ಒಂದು ಬೇರೆ ಬಿಂದು, ಕಟ್ಟುನಿಟ್ಟಾಗಿ ಕೆಟ್ಟದ್ದೂ ಅಲ್ಲ.' } },

    { type: 'code', data: {
      filename: 'moshi_websocket_client.py',
      headingEn: 'Original Code — Illustrative WebSocket Client', headingKn: 'Original Code — ವಿವರಣಾತ್ಮಕ WebSocket Client',
      descEn: 'The lesson presents a client sketch using `moshi.client_utils`. That module and its `connect()`/`stream_audio()` interface are illustrative of how a real client would talk to a Moshi/Hibiki WebSocket server -- consistent with this course\'s established convention for pipeline-glue code -- not a runnable dependency, and it was not executed for that reason.',
      descKn: 'ಲೆಸನ್ `moshi.client_utils` ಬಳಸಿ ಒಂದು client sketch ಪ್ರಸ್ತುತಪಡಿಸುತ್ತದೆ. ಆ module ಮತ್ತು ಇದರ `connect()`/`stream_audio()` interface ಒಂದು ನಿಜ client ಒಂದು Moshi/Hibiki WebSocket server ಜೊತೆ ಹೇಗೆ ಮಾತನಾಡುತ್ತದೆ ಎಂಬುದರ ವಿವರಣಾತ್ಮಕ -- pipeline-glue code ಗಾಗಿ ಈ ಕೋರ್ಸ್‌ನ ಸ್ಥಾಪಿತ ಸಂಪ್ರದಾಯಕ್ಕೆ ಸ್ಥಿರವಾಗಿ -- ಒಂದು ಚಲಾಯಿಸಬಹುದಾದ dependency ಅಲ್ಲ, ಮತ್ತು ಆ ಕಾರಣಕ್ಕಾಗಿ ಇದನ್ನೂ ಚಲಾಯಿಸಲಾಗಿಲ್ಲ.',
      code: "import asyncio\nfrom moshi.client_utils import connect, stream_audio\n\nasync def talk_to_moshi(mic_stream):\n    ws = await connect(\"ws://localhost:8998\")\n    async for user_chunk in mic_stream:\n        await ws.send_audio(user_chunk)\n        model_chunk = await ws.recv_audio()\n        yield model_chunk  # play immediately -- full duplex, no waiting for a full turn" } },

    { type: 'heading', data: { level: 'H2', textEn: 'Full-Duplex vs Pipeline: The Tradeoff', textKn: 'Full-Duplex vs Pipeline: Tradeoff' } },
    { type: 'table', data: { captionEn: 'Architecture Comparison', captionKn: 'Architecture ಹೋಲಿಕೆ',
      rows: 'Dimension|Pipeline (Module 135)|Context-Conditioned (Sesame CSM)|Full-Duplex (Moshi/Hibiki)\nLatency floor|Sum of stage latencies|One TTS-like forward pass per turn|One joint forward pass, continuous\nInterruption handling|Requires explicit barge-in logic|Turn-based, limited|Native to the architecture\nIntegration complexity|Low -- swap any component|Medium -- slots in as an advanced TTS stage|High -- replaces the whole stack\nComponent flexibility|High -- mix best-of-breed ASR/LLM/TTS|Medium|Low -- tightly coupled, hard to swap parts\nBest fit|Teams wanting modularity, fast iteration|Products wanting natural, context-aware turns without full-duplex complexity|Products where raw latency and natural overlap are the top priority' } },

    { type: 'heading', data: { level: 'H2', textEn: 'Choosing an Architecture: A Decision Tree', textKn: 'Architecture ಆಯ್ಕೆ ಮಾಡುವುದೂ: ಒಂದು Decision Tree' } },
    { type: 'diagram', data: {
      svgCode: "<svg viewBox=\"0 0 260 200\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"monospace\" font-size=\"6\">\n  <rect width=\"260\" height=\"200\" rx=\"8\" fill=\"#0f172a\"/>\n  <text x=\"130\" y=\"13\" fill=\"#94a3b8\" text-anchor=\"middle\" font-size=\"7\">Voice-AI Architecture Decision Tree</text>\n  <rect x=\"70\" y=\"20\" width=\"120\" height=\"18\" rx=\"3\" fill=\"#1e293b\" stroke=\"#60a5fa\"/><text x=\"130\" y=\"32\" fill=\"#93c5fd\" text-anchor=\"middle\" font-size=\"5\">Need lowest latency + native overlap?</text>\n  <g stroke=\"#475569\"><path d=\"M100,38 L50,50\"/><path d=\"M160,38 L210,50\"/></g>\n  <text x=\"45\" y=\"47\" fill=\"#6ee7b7\" font-size=\"5\">yes</text><text x=\"195\" y=\"47\" font-size=\"5\" fill=\"#fca5a5\">no</text>\n  <rect x=\"5\" y=\"52\" width=\"90\" height=\"24\" rx=\"3\" fill=\"#022c22\" stroke=\"#34d399\"/><text x=\"50\" y=\"63\" fill=\"#6ee7b7\" text-anchor=\"middle\" font-size=\"5\">Moshi / Hibiki</text><text x=\"50\" y=\"72\" fill=\"#6ee7b7\" text-anchor=\"middle\" font-size=\"4.6\">(full duplex)</text>\n  <rect x=\"165\" y=\"52\" width=\"90\" height=\"18\" rx=\"3\" fill=\"#1e293b\" stroke=\"#60a5fa\"/><text x=\"210\" y=\"63\" fill=\"#93c5fd\" text-anchor=\"middle\" font-size=\"4.8\">Need context-aware prosody?</text>\n  <g stroke=\"#475569\"><path d=\"M195,70 L165,84\"/><path d=\"M225,70 L245,84\"/></g>\n  <text x=\"160\" y=\"81\" fill=\"#6ee7b7\" font-size=\"5\">yes</text><text x=\"233\" y=\"81\" fill=\"#fca5a5\" font-size=\"5\">no</text>\n  <rect x=\"115\" y=\"86\" width=\"90\" height=\"24\" rx=\"3\" fill=\"#1e1b4b\" stroke=\"#a78bfa\"/><text x=\"160\" y=\"97\" fill=\"#c4b5fd\" text-anchor=\"middle\" font-size=\"5\">Sesame CSM</text><text x=\"160\" y=\"106\" fill=\"#c4b5fd\" text-anchor=\"middle\" font-size=\"4.6\">(context-conditioned)</text>\n  <rect x=\"210\" y=\"86\" width=\"45\" height=\"24\" rx=\"3\" fill=\"#292524\" stroke=\"#f59e0b\"/><text x=\"232\" y=\"97\" fill=\"#fde68a\" text-anchor=\"middle\" font-size=\"4.6\">Pipeline</text><text x=\"232\" y=\"106\" fill=\"#fde68a\" text-anchor=\"middle\" font-size=\"4.4\">(Module 135)</text>\n  <text x=\"130\" y=\"130\" fill=\"#94a3b8\" text-anchor=\"middle\" font-size=\"5.3\">Pipeline still wins when you need to swap</text>\n  <text x=\"130\" y=\"140\" fill=\"#94a3b8\" text-anchor=\"middle\" font-size=\"5.3\">best-of-breed ASR/LLM/TTS components independently,</text>\n  <text x=\"130\" y=\"150\" fill=\"#94a3b8\" text-anchor=\"middle\" font-size=\"5.3\">or when integration simplicity beats raw latency.</text>\n</svg>",
      headingEn: 'From Requirements to Architecture', headingKn: 'Requirements ಇಂದ Architecture ಗೆ',
      captionEn: 'Full-duplex is not universally "better" -- it is the right answer only when interruption-handling and raw latency dominate the product requirement.',
      captionKn: 'Full-duplex ಸಾರ್ವತ್ರಿಕವಾಗಿ "ಉತ್ತಮ" ಅಲ್ಲ -- interruption-handling ಮತ್ತು ಕಚ್ಚಾ latency product ಅಗತ್ಯದಲ್ಲಿ ಪ್ರಾಬಲ್ಯ ಸಾಧಿಸಿದಾಗ ಮಾತ್ರ ಇದೂ ಸರಿಯಾದ ಉತ್ತರ.' } },

    { type: 'concept', data: {
      headingEn: 'Why AI Uses It', headingKn: 'AI ಇದನ್ನು ಏಕೆ ಬಳಸುತ್ತದೆ',
      bodyEn: '• Hibiki reuses Moshi\'s architecture for translation because the underlying capability the architecture provides -- low-latency joint processing of two continuous audio streams -- is not inherently about dialogue at all; simultaneous translation is just another instance of "map one continuous stream to another with minimal delay," which is exactly the guarantee the temporal/depth transformer split and dual audio streams from Part 1 were built to provide.\n• Sesame CSM exists because full-duplex is not a free upgrade -- it trades integration flexibility and component modularity for latency and native interruption handling, and many real products (support bots, IVR replacements, narration with occasional turn-taking) get most of the naturalness benefit from context-conditioning without needing to pay full-duplex\'s architectural cost.\n• The decision tree exists because this module\'s honest answer to "which architecture should I use" is "it depends on which specific requirement dominates" -- exactly the same reasoning this course applied when choosing a VAD (Module 137) or a codec bandwidth setting (Module 136): there is no universally best choice, only a best choice for a stated set of constraints.',
      bodyKn: '• Hibiki translation ಗಾಗಿ Moshi ನ architecture ಮರುಬಳಕೆ ಮಾಡುತ್ತದೆ ಏಕೆಂದರೆ architecture ಒದಗಿಸುವ ಆಧಾರವಾಗಿರುವ ಸಾಮರ್ಥ್ಯ -- ಎರಡು ನಿರಂತರ audio streams ನ ಕಡಿಮೆ-latency ಜಂಟಿ ಪ್ರಕ್ರಿಯೆಗೊಳಿಸುವಿಕೆ -- ಮೂಲಭೂತವಾಗಿ ಸಂಭಾಷಣೆಯ ಬಗ್ಗೆ ಎಂದೇ ಅಲ್ಲ; ಏಕಕಾಲಿಕ ಅನುವಾದ ಕೇವಲ "ಒಂದು ನಿರಂತರ stream ಅನ್ನೂ ಕನಿಷ್ಠ ವಿಳಂಬ ಜೊತೆ ಇನ್ನೊಂದಕ್ಕೆ ಮ್ಯಾಪ್ ಮಾಡುವುದೂ" ಎಂಬುದರ ಇನ್ನೊಂದೂ ನಿದರ್ಶನ, ಇದೂ Part 1 ಇಂದ temporal/depth transformer ವಿಭಜನೆ ಮತ್ತು dual audio streams ಒದಗಿಸಲು ನಿರ್ಮಿಸಲಾಗಿದ ನಿಖರವಾದ ಗ್ಯಾರಂಟಿ.\n• Sesame CSM ಅಸ್ತಿತ್ವದಲ್ಲಿದೆ ಏಕೆಂದರೆ full-duplex ಒಂದು ಉಚಿತ ಅಪ್‌ಗ್ರೇಡ್ ಅಲ್ಲ -- ಇದೂ latency ಮತ್ತು ಸ್ಥಳೀಯ interruption handling ಗಾಗಿ integration flexibility ಮತ್ತು component modularity ವಿನಿಮಯ ಮಾಡುತ್ತದೆ, ಮತ್ತು ಅನೇಕ ನಿಜ products (support bots, IVR replacements, ಸಾಂದರ್ಭಿಕ turn-taking ಜೊತೆ narration) full-duplex ನ architectural ವೆಚ್ಚ ಪಾವತಿಸುವ ಅಗತ್ಯವಿಲ್ಲದೆ context-conditioning ಇಂದ ಸ್ವಾಭಾವಿಕತೆಯ ಪ್ರಯೋಜನದ ಹೆಚ್ಚಿನದನ್ನೂ ಪಡೆಯುತ್ತವೆ.\n• Decision tree ಅಸ್ತಿತ್ವದಲ್ಲಿದೆ ಏಕೆಂದರೆ "ನಾನು ಯಾವ architecture ಬಳಸಬೇಕು" ಗೆ ಈ module ನ ಪ್ರಾಮಾಣಿಕ ಉತ್ತರ "ಇದೂ ಯಾವ ನಿರ್ದಿಷ್ಟ ಅಗತ್ಯ ಪ್ರಾಬಲ್ಯ ಸಾಧಿಸುತ್ತದೆ ಎಂಬುದರ ಮೇಲೆ ಅವಲಂಬಿತ" -- ಒಂದು VAD (Module 137) ಅಥವಾ ಒಂದು codec bandwidth setting (Module 136) ಆಯ್ಕೆ ಮಾಡುವಾಗ ಈ ಕೋರ್ಸ್ ಅನ್ವಯಿಸಿದ ನಿಖರವಾದ ಅದೇ ತರ್ಕ: ಸಾರ್ವತ್ರಿಕವಾಗಿ ಅತ್ಯುತ್ತಮ ಆಯ್ಕೆ ಇಲ್ಲ, ಕೇವಲ ಒಂದು ಹೇಳಿದ ಮಿತಿಗಳ ಸೆಟ್‌ಗೆ ಅತ್ಯುತ್ತಮ ಆಯ್ಕೆ.' } },

    { type: 'concept', data: {
      headingEn: 'Key Takeaways', headingKn: 'ಮುಖ್ಯ ಅಂಶಗಳು',
      bodyEn: '• Hibiki reuses Moshi\'s full-duplex architecture for real-time speech-to-speech translation, generating target-language speech incrementally while the source is still being spoken; Hibiki-Zero is a lighter, distilled variant.\n• Sesame CSM (Llama-3 backbone + Mimi codec head) is context-conditioned on full conversation history but is deliberately turn-based rather than full-duplex -- a middle path between pipeline modularity and Moshi\'s architectural complexity.\n• The lesson\'s WebSocket client code (`moshi.client_utils`) is illustrative, showing the shape of a real-time client integration, not a runnable dependency.\n• Full-duplex wins on latency and native interruption handling but loses on integration simplicity and component swappability compared to pipelines; context-conditioned models like CSM sit in between.\n• There is no universally correct voice-AI architecture -- the right choice depends on which constraint (latency, naturalness, modularity, integration complexity) dominates for a given product, the same situational-tradeoff reasoning applied to VAD and codec choices earlier in this module sequence.',
      bodyKn: '• Hibiki real-time speech-to-speech translation ಗಾಗಿ Moshi ನ full-duplex architecture ಮರುಬಳಕೆ ಮಾಡುತ್ತದೆ, ಮೂಲ ಇನ್ನೂ ಮಾತನಾಡುತ್ತಿರುವಾಗ ಗುರಿ-ಭಾಷೆಯ ಭಾಷಣ ಅನ್ನೂ ಕ್ರಮೇಣ ಉತ್ಪಾದಿಸುತ್ತಾ; Hibiki-Zero ಒಂದು ಹಗುರ, distilled variant.\n• Sesame CSM (Llama-3 backbone + Mimi codec head) ಪೂರ್ಣ ಸಂಭಾಷಣೆ ಇತಿಹಾಸ ಮೇಲೆ context-conditioned ಆದರೆ ಉದ್ದೇಶಪೂರ್ವಕವಾಗಿ full-duplex ಗಿಂತ turn-based -- pipeline modularity ಮತ್ತು Moshi ನ architectural ಸಂಕೀರ್ಣತೆ ನಡುವಿನ ಒಂದು ಮಧ್ಯದ ಮಾರ್ಗ.\n• ಲೆಸನ್‌ನ WebSocket client code (`moshi.client_utils`) ವಿವರಣಾತ್ಮಕ, ಒಂದು real-time client integration ನ ಆಕಾರ ತೋರಿಸುತ್ತಾ, ಒಂದು ಚಲಾಯಿಸಬಹುದಾದ dependency ಅಲ್ಲ.\n• Full-duplex latency ಮತ್ತು ಸ್ಥಳೀಯ interruption handling ಮೇಲೆ ಗೆಲ್ಲುತ್ತದೆ ಆದರೆ pipelines ಗೆ ಹೋಲಿಸಿದಾಗ integration ಸರಳತೆ ಮತ್ತು component swappability ಮೇಲೆ ಸೋಲುತ್ತದೆ; CSM ನಂತಹ context-conditioned models ಮಧ್ಯದಲ್ಲಿ ಕುಳಿತಿವೆ.\n• ಸಾರ್ವತ್ರಿಕವಾಗಿ ಸರಿಯಾದ voice-AI architecture ಇಲ್ಲ -- ಸರಿಯಾದ ಆಯ್ಕೆ ಒಂದು ನಿರ್ದಿಷ್ಟ product ಗೆ ಯಾವ ಮಿತಿ (latency, ಸ್ವಾಭಾವಿಕತೆ, modularity, integration ಸಂಕೀರ್ಣತೆ) ಪ್ರಾಬಲ್ಯ ಸಾಧಿಸುತ್ತದೆ ಎಂಬುದರ ಮೇಲೆ ಅವಲಂಬಿತ, ಈ module ಅನುಕ್ರಮದಲ್ಲಿ ಮೊದಲು VAD ಮತ್ತು codec ಆಯ್ಕೆಗಳಿಗೆ ಅನ್ವಯಿಸಿದ ಅದೇ ಸಾಂದರ್ಭಿಕ-tradeoff ತರ್ಕ.' } },

    { type: 'quiz', data: { questions: [
      { q: 'What task does Hibiki repurpose Moshi\'s architecture for?', qKn: 'Hibiki ಯಾವ task ಗಾಗಿ Moshi ನ architecture ಮರುಉದ್ದೇಶಿಸುತ್ತದೆ?',
        opts: ['Image generation', 'Real-time, incremental speech-to-speech translation while the source is still being spoken', 'Text summarization', 'Music generation'], correct: 1,
        optsKn: ['Image generation', 'ಮೂಲ ಇನ್ನೂ ಮಾತನಾಡುತ್ತಿರುವಾಗ real-time, ಕ್ರಮೇಣ speech-to-speech translation', 'ಪಠ್ಯ summarization', 'Music generation'] },
      { q: 'How does Sesame CSM differ from Moshi\'s full-duplex design?', qKn: 'Sesame CSM Moshi ನ full-duplex ವಿನ್ಯಾಸ ಇಂದ ಹೇಗೆ ಭಿನ್ನವಾಗಿದೆ?',
        opts: ['CSM does not use any neural codec', 'CSM is context-conditioned on conversation history but operates in a turn-based mode, not processing two simultaneous live audio streams', 'CSM is identical to Moshi in every respect', 'CSM only works for text, not speech'], correct: 1,
        optsKn: ['CSM ಯಾವುದೇ neural codec ಬಳಸುವುದಿಲ್ಲ', 'CSM ಸಂಭಾಷಣೆ ಇತಿಹಾಸ ಮೇಲೆ context-conditioned ಆದರೆ ಒಂದು turn-based ಮೋಡ್‌ನಲ್ಲಿ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತದೆ, ಎರಡು ಏಕಕಾಲಿಕ ಲೈವ್ audio streams ಪ್ರಕ್ರಿಯೆಗೊಳಿಸುವುದಿಲ್ಲ', 'CSM ಪ್ರತಿಯೊಂದೂ ವಿಷಯದಲ್ಲಿ Moshi ಗೆ ಒಂದೇ', 'CSM ಕೇವಲ ಪಠ್ಯಕ್ಕೆ ಮಾತ್ರ ಕೆಲಸ ಮಾಡುತ್ತದೆ, ಭಾಷಣಕ್ಕಲ್ಲ'] },
      { q: 'Why was the lesson\'s `moshi.client_utils` WebSocket example not executed?', qKn: 'ಲೆಸನ್‌ನ `moshi.client_utils` WebSocket example ಅನ್ನೂ ಏಕೆ ಚಲಾಯಿಸಲಾಗಿಲ್ಲ?',
        opts: ['It contains a syntax error', 'It is illustrative pipeline-glue code showing the shape of a real-time client integration, not a runnable dependency, matching a convention used elsewhere in this course', 'WebSockets cannot be used with audio', 'It was executed and worked correctly'], correct: 1,
        optsKn: ['ಇದೂ ಒಂದು syntax error ಒಳಗೊಂಡಿದೆ', 'ಇದೂ ಒಂದು real-time client integration ನ ಆಕಾರ ತೋರಿಸುವ ವಿವರಣಾತ್ಮಕ pipeline-glue code, ಒಂದು ಚಲಾಯಿಸಬಹುದಾದ dependency ಅಲ್ಲ, ಈ ಕೋರ್ಸ್‌ನಲ್ಲಿ ಬೇರೆಡೆ ಬಳಸಿದ ಒಂದು ಸಂಪ್ರದಾಯಕ್ಕೆ ಹೊಂದಿಕೆಯಾಗುತ್ತಾ', 'WebSockets ಗಳನ್ನೂ audio ಜೊತೆ ಬಳಸಲಾಗುವುದಿಲ್ಲ', 'ಇದೂ ಚಲಾಯಿಸಲಾಯಿತು ಮತ್ತು ಸರಿಯಾಗಿ ಕೆಲಸ ಮಾಡಿತು'] },
      { q: 'According to the decision tree, when should a pipeline architecture (Module 135 style) be preferred over full-duplex?', qKn: 'Decision tree ಪ್ರಕಾರ, ಒಂದು pipeline architecture (Module 135 style) ಅನ್ನೂ ಯಾವಾಗ full-duplex ಗಿಂತ ಆದ್ಯತೆ ನೀಡಬೇಕು?',
        opts: ['Always, pipelines are strictly better', 'When integration simplicity and the ability to independently swap best-of-breed ASR/LLM/TTS components matter more than achieving the absolute lowest latency', 'Never, full-duplex is always superior', 'Only when there is no internet connection'], correct: 1,
        optsKn: ['ಯಾವಾಗಲೂ, pipelines ಗಳು ಕಟ್ಟುನಿಟ್ಟಾಗಿ ಉತ್ತಮ', 'Integration ಸರಳತೆ ಮತ್ತು ಸ್ವತಂತ್ರವಾಗಿ best-of-breed ASR/LLM/TTS components ಬದಲಾಯಿಸುವ ಸಾಮರ್ಥ್ಯ ಸಂಪೂರ್ಣ ಕಡಿಮೆ latency ಸಾಧಿಸುವುದಕ್ಕಿಂತ ಹೆಚ್ಚು ಮುಖ್ಯವಾದಾಗ', 'ಎಂದಿಗೂ ಇಲ್ಲ, full-duplex ಯಾವಾಗಲೂ ಉತ್ತಮ', 'ಇಂಟರ್ನೆಟ್ ಸಂಪರ್ಕ ಇಲ್ಲದಾಗ ಮಾತ್ರ'] },
      { q: 'What is the broader architectural insight behind Hibiki reusing Moshi\'s design for translation?', qKn: 'Hibiki translation ಗಾಗಿ Moshi ನ ವಿನ್ಯಾಸ ಮರುಬಳಕೆ ಮಾಡುವ ಹಿಂದಿನ ವಿಶಾಲ architectural ಒಳನೋಟ ಏನೂ?',
        opts: ['Translation and dialogue require completely unrelated model architectures', 'Full-duplex is fundamentally a general low-latency dual-stream processing capability, not an inherently dialogue-specific trick, so it transfers to any task shaped like "map one continuous audio stream to another"', 'Moshi cannot actually be reused for anything else', 'Translation is easier than dialogue so it needs a smaller model'], correct: 1,
        optsKn: ['Translation ಮತ್ತು ಸಂಭಾಷಣೆಗೆ ಸಂಪೂರ್ಣವಾಗಿ ಸಂಬಂಧವಿಲ್ಲದ model architectures ಬೇಕು', 'Full-duplex ಮೂಲಭೂತವಾಗಿ ಒಂದು ಸಾಮಾನ್ಯ ಕಡಿಮೆ-latency dual-stream ಪ್ರಕ್ರಿಯೆಗೊಳಿಸುವ ಸಾಮರ್ಥ್ಯ, ಅಂತರ್ಗತವಾಗಿ ಸಂಭಾಷಣೆ-ನಿರ್ದಿಷ್ಟ ಟ್ರಿಕ್ ಅಲ್ಲ, ಆದ್ದರಿಂದ ಇದೂ "ಒಂದು ನಿರಂತರ audio stream ಅನ್ನೂ ಇನ್ನೊಂದಕ್ಕೆ ಮ್ಯಾಪ್ ಮಾಡುವುದೂ" ಆಕಾರದ ಯಾವುದೇ task ಗೆ ವರ್ಗಾಯಿಸುತ್ತದೆ', 'Moshi ಅನ್ನೂ ವಾಸ್ತವವಾಗಿ ಬೇರೆ ಯಾವುದಕ್ಕೂ ಮರುಬಳಕೆ ಮಾಡಲು ಸಾಧ್ಯವಿಲ್ಲ', 'Translation ಸಂಭಾಷಣೆಗಿಂತ ಸುಲಭ ಆದ್ದರಿಂದ ಇದಕ್ಕೆ ಒಂದು ಚಿಕ್ಕ model ಬೇಕು'] },
    ] } },
  ],
};
