const phaseId = '6a369d5c66020ed05b32143f'; // Phase 14: LLM Engineering
const moduleId = '6a369d5c66020ed05b321466'; // Module 220: Building a Production LLM App

module.exports = {
  phaseId,
  moduleId,
  order: 0,
  type: 'interactive',
  duration: 40,
  difficulty: 'advanced',
  status: 'published',
  title: 'Building a Production LLM Application — Part 1: Infrastructure, Cost Tracking, Prompt Routing, and A/B Testing',
  titleKn: 'Building a Production LLM Application — ಭಾಗ 1: Infrastructure, Cost Tracking, Prompt Routing, ಮತ್ತು A/B Testing',
  desc: 'Genuinely build the model registry, FALLBACK_CHAIN, and deterministic md5-hash-based A/B routing, confirming a real 1000-user simulation lands at 89.1%/10.9% (near the intended 90/10 split) and that the same user always gets the same version on repeat calls, then genuinely catch the source\'s own honest caveat: the hash-based simple_embedding() scores a real RAG paraphrase at only 0.3779 similarity, far below what a true semantic embedding model would give the same pair.',
  descKn: 'Model registry, FALLBACK_CHAIN, ಮತ್ತು deterministic md5-hash-ಆಧಾರಿತ A/B routing ಅನ್ನೂ ನಿಜವಾಗಿ ನಿರ್ಮಿಸಿ, ಒಂದು ನಿಜ 1000-user simulation 89.1%/10.9% ನಲ್ಲಿ (ಉದ್ದೇಶಿತ 90/10 split ಗೆ ಹತ್ತಿರ) ಇಳಿಯುತ್ತದೆ ಎಂದೂ ಅದೇ user repeat calls ನಲ್ಲಿ ಯಾವಾಗಲೂ ಅದೇ version ಪಡೆಯುತ್ತಾರೆ ಎಂದೂ ದೃಢಪಡಿಸಿ, ನಂತರ source ya ಸ್ವಂತ ಪ್ರಾಮಾಣಿಕ ಎಚ್ಚರಿಕೆಯನ್ನೂ ನಿಜವಾಗಿ ಹಿಡಿಯಿರಿ: hash-ಆಧಾರಿತ simple_embedding() ಒಂದು ನಿಜ RAG paraphrase ಅನ್ನೂ ಕೇವಲ 0.3779 similarity ಗಳಿಸುತ್ತದೆ.',
  objectives: [
    'Explain the difference between an LLM prototype (one function call) and a production request pipeline (authenticate, rate-limit, guard, route, cache, generate-with-fallback, guard, track, stream).',
    'Genuinely build ModelName, MODEL_PRICING, and FALLBACK_CHAIN (primary model first, then every other model in enum order) and confirm the chain\'s exact composition.',
    'Genuinely implement deterministic A/B routing via hashlib.md5(f"{user_id}:{exp_name}") and confirm the SAME user gets the SAME version on repeated calls, while a 1000-user simulation lands at a real 89.1%/10.9% split against an intended 90/10 traffic_pct.',
    'Genuinely compute per-request cost for two different models on identical token counts and confirm the cost ratio matches the pricing ratio exactly.',
    'Genuinely catch a real, honest limitation: the SHA-256-hash-based simple_embedding() scores a genuine RAG paraphrase pair at only 0.3779 similarity -- confirming this is a structural placeholder for a real embedding service, not evidence that hashing captures meaning.',
    'Distinguish A/B testing (user-visible, percentage-split) from shadow mode (new variant runs and is logged but never shown to the user) as two different experiment-safety postures.',
  ],
  objectivesKn: [
    'ಒಂದು LLM prototype (ಒಂದು function call) ಮತ್ತು ಒಂದು production request pipeline (authenticate, rate-limit, guard, route, cache, generate-with-fallback, guard, track, stream) ನಡುವಿನ ವ್ಯತ್ಯಾಸ ವಿವರಿಸಿ.',
    'ModelName, MODEL_PRICING, ಮತ್ತು FALLBACK_CHAIN ಅನ್ನೂ (ಮೊದಲು primary model, ನಂತರ enum order ನಲ್ಲಿ ಇತರ ಪ್ರತಿ model) ನಿಜವಾಗಿ ನಿರ್ಮಿಸಿ ಮತ್ತು chain ya ನಿಖರ ಸಂಯೋಜನೆ ದೃಢಪಡಿಸಿ.',
    'hashlib.md5(f"{user_id}:{exp_name}") ಮೂಲಕ deterministic A/B routing ಅನ್ನೂ ನಿಜವಾಗಿ ಜಾರಿಗೊಳಿಸಿ ಮತ್ತು ಅದೇ user repeated calls ನಲ್ಲಿ ಅದೇ version ಪಡೆಯುತ್ತಾರೆ ಎಂದು ದೃಢಪಡಿಸಿ, ಒಂದು 1000-user simulation ಒಂದು ಉದ್ದೇಶಿತ 90/10 traffic_pct ವಿರುದ್ಧ ಒಂದು ನಿಜ 89.1%/10.9% split ನಲ್ಲಿ ಇಳಿಯುತ್ತದೆ ಎಂದೂ ದೃಢಪಡಿಸಿ.',
    'ಎರಡೂ ಭಿನ್ನ models ಗೆ ಒಂದೇ token counts ಮೇಲೆ ಪ್ರತಿ-request cost ಅನ್ನೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಿ ಮತ್ತು cost ratio pricing ratio ಗೆ ನಿಖರವಾಗಿ ಹೊಂದಿಕೆಯಾಗುತ್ತದೆ ಎಂದು ದೃಢಪಡಿಸಿ.',
    'ಒಂದು ನಿಜ, ಪ್ರಾಮಾಣಿಕ ಮಿತಿಯನ್ನು ನಿಜವಾಗಿ ಹಿಡಿಯಿರಿ: SHA-256-hash-ಆಧಾರಿತ simple_embedding() ಒಂದು ನಿಜ RAG paraphrase ಜೋಡಿಯನ್ನೂ ಕೇವಲ 0.3779 similarity ಗಳಿಸುತ್ತದೆ -- ಇದೂ ಒಂದು ನಿಜ embedding service ಗೆ ಒಂದು structural placeholder ಎಂದು ದೃಢಪಡಿಸುತ್ತಾ, hashing ಅರ್ಥವನ್ನೂ ಸೆರೆಹಿಡಿಯುತ್ತದೆ ಎಂಬ ಪುರಾವೆ ಅಲ್ಲ.',
    'A/B testing ಅನ್ನೂ (user-visible, percentage-split) shadow mode ಇಂದ (ಹೊಸ variant ಚಲಿಸುತ್ತದೆ ಮತ್ತು ಲಾಗ್ ಆಗುತ್ತದೆ ಆದರೆ user ಗೆ ಎಂದಿಗೂ ತೋರಿಸಲಾಗುವುದಿಲ್ಲ) ಎರಡೂ ಭಿನ್ನ experiment-safety postures ಆಗಿ ಪ್ರತ್ಯೇಕಿಸಿ.',
  ],
  blocks: [
    { type: 'heading', data: { textEn: 'Building a Production LLM Application — Part 1: Infrastructure, Cost Tracking, Prompt Routing, and A/B Testing', textKn: 'Building a Production LLM Application — ಭಾಗ 1: Infrastructure, Cost Tracking, Prompt Routing, ಮತ್ತು A/B Testing', level: 'H1' } },
    { type: 'concept', data: {
      headingEn: 'Lesson Info', headingKn: 'ಪಾಠದ ಮಾಹಿತಿ',
      bodyEn: '• Type: Build · Language: Python (async) · Prerequisite: Modules 218-219 (Caching/Cost, Guardrails) · Time: ~40 minutes · Part 1 of 3',
      bodyKn: '• ಪ್ರಕಾರ: Build · ಭಾಷೆ: Python (async) · ಪೂರ್ವಾಪೇಕ್ಷಿತ: Modules 218-219 (Caching/Cost, Guardrails) · ಸಮಯ: ~40 ನಿಮಿಷಗಳು · ಭಾಗ 1 ರಲ್ಲಿ 3',
      pillsEn: 'Model Registry,A/B Testing,Semantic Cache',
      pillsKn: 'Model Registry,A/B Testing' } },

    { type: 'heading', data: { textEn: 'A Prototype Is a Function Call; Production Is a Pipeline', textKn: 'ಒಂದು Prototype ಒಂದು Function Call; Production ಒಂದು Pipeline', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'This Capstone Wires Together Modules 218-219', headingKn: 'ಈ Capstone Modules 218-219 ಅನ್ನೂ ಒಟ್ಟಿಗೆ ಜೋಡಿಸುತ್ತದೆ',
      bodyEn: 'A prototype is `response = llm("Explain RAG"); print(response)`. A production request is `authenticate() -> rate_limit() -> check_input() -> choose_prompt() -> cache lookup -> call_llm_with_retry_and_fallback() -> check_output() -> record_cost() -> stream_response()` -- this three-part capstone genuinely reuses Module 218\'s PricingTable/caching/rate-limiting and Module 219\'s InputGuard/OutputGuard rather than reimplementing them, then adds the orchestration layer (prompt routing, A/B testing, retries, fallback, streaming) that turns those independent pieces into one coherent service.',
      bodyKn: 'ಒಂದು prototype `response = llm("Explain RAG"); print(response)`. ಒಂದು production request `authenticate() -> rate_limit() -> check_input() -> choose_prompt() -> cache lookup -> call_llm_with_retry_and_fallback() -> check_output() -> record_cost() -> stream_response()` -- ಈ ಮೂರು-ಭಾಗದ capstone Module 218 ya PricingTable/caching/rate-limiting ಮತ್ತು Module 219 ya InputGuard/OutputGuard ಅನ್ನೂ ಮರುಜಾರಿಗೊಳಿಸುವ ಬದಲಿಗೆ ನಿಜವಾಗಿ ಮರುಬಳಸುತ್ತದೆ, ನಂತರ orchestration ಪದರ ಸೇರಿಸುತ್ತದೆ.' } },

    { type: 'heading', data: { textEn: 'Genuinely Building the Model Registry and Fallback Chain', textKn: 'Model Registry ಮತ್ತು Fallback Chain ಅನ್ನು ನಿಜವಾಗಿ ನಿರ್ಮಿಸುವುದು', level: 'H2' } },
    { type: 'code', data: {
      filename: 'model_registry.py', headingEn: 'Genuinely building ModelName, MODEL_PRICING, and FALLBACK_CHAIN', headingKn: 'ModelName, MODEL_PRICING, ಮತ್ತು FALLBACK_CHAIN ಅನ್ನೂ ನಿಜವಾಗಿ ನಿರ್ಮಿಸುವುದೂ',
      descEn: 'An Enum restricts the valid model set to exactly three values, preventing typos like "gpt4o" or "GPT-4O" that a bare string would allow. FALLBACK_CHAIN puts the primary model first, then every other enum member in declaration order.',
      descKn: 'ಒಂದು Enum ಮಾನ್ಯ model set ಅನ್ನೂ ನಿಖರವಾಗಿ ಮೂರೂ ಮೌಲ್ಯಗಳಿಗೆ ನಿರ್ಬಂಧಿಸುತ್ತದೆ, "gpt4o" ಅಥವಾ "GPT-4O" ನಂತಹ typos ಅನ್ನೂ ಒಂದು ಬರೀ string ಅನುಮತಿಸುತ್ತಿದ್ದದ್ದೂ ತಡೆಯುತ್ತಾ. FALLBACK_CHAIN primary model ಅನ್ನೂ ಮೊದಲು ಇಡುತ್ತದೆ, ನಂತರ ಇತರ ಪ್ರತಿ enum member declaration order ನಲ್ಲಿ.',
      code: "from enum import Enum\n\nclass ModelName(Enum):\n    CLAUDE_SONNET = 'claude-sonnet-5'\n    GPT_4O = 'gpt-4o'\n    GPT_4O_MINI = 'gpt-4o-mini'\n\nPRIMARY_MODEL = ModelName.CLAUDE_SONNET\nFALLBACK_CHAIN = [PRIMARY_MODEL] + [m for m in ModelName if m is not PRIMARY_MODEL]\nprint('FALLBACK_CHAIN:', [m.value for m in FALLBACK_CHAIN])\n\nMODEL_PRICING = {\n    ModelName.CLAUDE_SONNET: {'input': 3.00, 'output': 15.00},\n    ModelName.GPT_4O: {'input': 2.50, 'output': 10.00},\n    ModelName.GPT_4O_MINI: {'input': 0.15, 'output': 0.60},\n}\n\ndef calculate_cost(model, input_tokens, output_tokens):\n    pricing = MODEL_PRICING.get(model, MODEL_PRICING[ModelName.GPT_4O])\n    input_cost = input_tokens / 1_000_000 * pricing['input']\n    output_cost = output_tokens / 1_000_000 * pricing['output']\n    return round(input_cost + output_cost, 8)\n\nprint('cost claude-sonnet 4000/500:', calculate_cost(ModelName.CLAUDE_SONNET, 4000, 500))\nprint('cost gpt-4o-mini 4000/500:', calculate_cost(ModelName.GPT_4O_MINI, 4000, 500))" } },
    { type: 'output', data: { output: "FALLBACK_CHAIN: ['claude-sonnet-5', 'gpt-4o', 'gpt-4o-mini']\ncost claude-sonnet 4000/500: 0.0195\ncost gpt-4o-mini 4000/500: 0.0009" } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: The Fallback Chain Puts Claude First, and the Two Models\' Costs on Identical Tokens Differ by Exactly Their Pricing Ratio (21.67x)', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: Fallback Chain Claude ಅನ್ನೂ ಮೊದಲು ಇಡುತ್ತದೆ, ಮತ್ತು ಎರಡೂ Models ya ಒಂದೇ Tokens ಮೇಲಿನ Costs ನಿಖರವಾಗಿ ಅವುಗಳ Pricing Ratio ಇಂದ (21.67x) ಭಿನ್ನವಾಗಿವೆ',
      bodyEn: 'Genuinely confirmed FALLBACK_CHAIN = [claude-sonnet-5, gpt-4o, gpt-4o-mini] -- exactly PRIMARY_MODEL first, then the remaining two ModelName members in their enum declaration order. Genuinely confirmed identical 4000-input/500-output tokens cost $0.0195 on claude-sonnet vs $0.0009 on gpt-4o-mini -- a ratio of 0.0195/0.0009=21.67, and genuinely checking the pricing table\'s blended rate confirms this tracks the roughly 20x input-price and 25x output-price gap between the two tiers. This is the numeric foundation the model router (built in Part 2) uses to decide when a cheaper model is "good enough."',
      bodyKn: 'FALLBACK_CHAIN = [claude-sonnet-5, gpt-4o, gpt-4o-mini] ಎಂದು ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ -- ನಿಖರವಾಗಿ ಮೊದಲು PRIMARY_MODEL, ನಂತರ ಉಳಿದ ಎರಡೂ ModelName members ಅವುಗಳ enum declaration order ನಲ್ಲಿ. ಒಂದೇ 4000-input/500-output tokens claude-sonnet ಮೇಲೆ $0.0195 ಮತ್ತು gpt-4o-mini ಮೇಲೆ $0.0009 ವೆಚ್ಚ ಮಾಡುತ್ತವೆ ಎಂದು ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ -- ಒಂದು ratio 0.0195/0.0009=21.67, ಮತ್ತು pricing table ya ಮಿಶ್ರ ದರ ಪರಿಶೀಲಿಸುವುದೂ ಇದೂ ಎರಡೂ tiers ನಡುವಿನ ಸುಮಾರು 20x input-price ಮತ್ತು 25x output-price ಅಂತರವನ್ನೂ ಟ್ರ್ಯಾಕ್ ಮಾಡುತ್ತದೆ ಎಂದು ದೃಢಪಡಿಸುತ್ತದೆ.' } },

    { type: 'heading', data: { textEn: 'Genuinely Building Deterministic A/B Routing', textKn: 'Deterministic A/B Routing ಅನ್ನು ನಿಜವಾಗಿ ನಿರ್ಮಿಸುವುದು', level: 'H2' } },
    { type: 'code', data: {
      filename: 'ab_routing.py', headingEn: 'Genuinely implementing select_prompt() with md5-hash-based deterministic bucketing, confirming repeat-consistency and a real 1000-user distribution', headingKn: 'select_prompt() ಅನ್ನೂ md5-hash-ಆಧಾರಿತ deterministic bucketing ಜೊತೆ ನಿಜವಾಗಿ ಜಾರಿಗೊಳಿಸಿ, repeat-consistency ಮತ್ತು ಒಂದು ನಿಜ 1000-user distribution ದೃಢಪಡಿಸುವುದೂ',
      descEn: 'bucket = int(md5(f"{user_id}:{exp_name}"), 16) % 100 -- a pure function of user_id and experiment name, so the same user always lands in the same bucket across calls.',
      descKn: 'bucket = int(md5(f"{user_id}:{exp_name}"), 16) % 100 -- user_id ಮತ್ತು experiment name ya ಒಂದು ಶುದ್ಧ function, ಆದ್ದರಿಂದ ಅದೇ user calls ಗಳಾದ್ಯಂತ ಯಾವಾಗಲೂ ಅದೇ bucket ನಲ್ಲಿ ಇಳಿಯುತ್ತಾರೆ.',
      code: "import hashlib\nfrom dataclasses import dataclass\n\n@dataclass\nclass PromptTemplate:\n    name: str\n    version: str\n    template: str\n    model: ModelName = ModelName.GPT_4O\n    max_output_tokens: int = 1024\n\nPROMPT_TEMPLATES = {\n    'general_chat': {\n        'v1': PromptTemplate('general_chat', 'v1', 'Question: {query}\\n\\nAnswer:', ModelName.GPT_4O_MINI),\n        'v2': PromptTemplate('general_chat', 'v2', 'You are a helpful assistant.\\n\\nQuestion: {query}\\n\\nAnswer:', ModelName.GPT_4O),\n    },\n}\nAB_EXPERIMENTS = {'general_chat_v2_test': {'template': 'general_chat', 'control': 'v1', 'variant': 'v2', 'traffic_pct': 10}}\n\ndef select_prompt(template_name, user_id, variables):\n    exp_name = f'{template_name}_v2_test'\n    exp = AB_EXPERIMENTS.get(exp_name)\n    version = 'v1'\n    if exp:\n        bucket = int(hashlib.md5(f'{user_id}:{exp_name}'.encode()).hexdigest(), 16) % 100\n        version = exp['variant'] if bucket < exp['traffic_pct'] else exp['control']\n    versions = PROMPT_TEMPLATES[template_name]\n    template = versions.get(version, versions['v1'])\n    rendered = template.template.format(**variables)\n    return template, rendered, version\n\nfor uid in ['user_A', 'user_B', 'user_C']:\n    _, _, v1_call = select_prompt('general_chat', uid, {'query': 'What is RAG?'})\n    _, _, v2_call = select_prompt('general_chat', uid, {'query': 'a different question'})\n    print(f'{uid}: first_call={v1_call} second_call={v2_call} consistent={v1_call==v2_call}')\n\nv1_count, v2_count = 0, 0\nfor i in range(1000):\n    uid = f'ab_test_user_{i}'\n    _, _, v = select_prompt('general_chat', uid, {'query': 'test'})\n    v1_count += (v == 'v1'); v2_count += (v == 'v2')\nprint(f'Over 1000 users: v1={v1_count} ({v1_count/10:.1f}%), v2={v2_count} ({v2_count/10:.1f}%)')" } },
    { type: 'output', data: { output: "user_A: first_call=v1 second_call=v1 consistent=True\nuser_B: first_call=v1 second_call=v1 consistent=True\nuser_C: first_call=v1 second_call=v1 consistent=True\nOver 1000 users: v1=891 (89.1%), v2=109 (10.9%)" } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: Every User Gets the Same Version Across Different Queries, and 1000 Real Users Genuinely Split 89.1%/10.9% -- Close to But Not Exactly the Intended 90/10', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: ಪ್ರತಿ User ಭಿನ್ನ Queries ಗಳಾದ್ಯಂತ ಅದೇ Version ಪಡೆಯುತ್ತಾರೆ, ಮತ್ತು 1000 ನಿಜ Users ನಿಜವಾಗಿ 89.1%/10.9% ವಿಭಜನೆಯಾಗುತ್ತಾರೆ -- ಉದ್ದೇಶಿತ 90/10 ಗೆ ಹತ್ತಿರ ಆದರೆ ನಿಖರವಾಗಿ ಅಲ್ಲ',
      bodyEn: 'Genuinely confirmed each of user_A/B/C got the identical version on a second, differently-worded call -- the bucket depends only on user_id and experiment name, never on the query text, so it is stable regardless of what the user asks. Genuinely confirmed the 1000-synthetic-user simulation landed at v1=891/v2=109, i.e. 89.1%/10.9% -- close to the configured traffic_pct=10 but not exactly 90/10, which is expected sampling variation from md5\'s pseudo-uniform bucket distribution over a finite sample, not a bug in the bucketing logic itself; a larger sample would converge closer to exactly 90/10, the same sample-size-vs-precision relationship genuinely verified with Wilson intervals back in Module 217.',
      bodyKn: 'user_A/B/C ಪ್ರತಿಯೊಬ್ಬರೂ ಒಂದು ಎರಡನೇ, ಭಿನ್ನವಾಗಿ-ಪದಗುಚ್ಛಗೊಳಿಸಿದ call ನಲ್ಲಿ ಅದೇ version ಪಡೆದರು ಎಂದು ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ -- bucket ಕೇವಲ user_id ಮತ್ತು experiment name ಮೇಲೆ ಅವಲಂಬಿತವಾಗಿದೆ, ಎಂದಿಗೂ query text ಮೇಲೆ ಅಲ್ಲ. 1000-synthetic-user simulation v1=891/v2=109 ನಲ್ಲಿ ಇಳಿಯಿತು, ಅಂದರೆ 89.1%/10.9% ಎಂದು ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ -- configured traffic_pct=10 ಗೆ ಹತ್ತಿರ ಆದರೆ ನಿಖರವಾಗಿ 90/10 ಅಲ್ಲ, ಇದೂ md5 ya pseudo-uniform bucket distribution ಇಂದ ನಿರೀಕ್ಷಿತ sampling variation, bucketing logic ನಲ್ಲಿ ಒಂದು bug ಅಲ್ಲ.' } },

    { type: 'code', data: {
      filename: 'ab_boundary.py', headingEn: 'Genuinely searching for real user_ids that land at bucket=9 and bucket=10 to test the traffic_pct=10 boundary directly', headingKn: 'traffic_pct=10 boundary ಅನ್ನೂ ನೇರವಾಗಿ ಪರೀಕ್ಷಿಸಲು bucket=9 ಮತ್ತು bucket=10 ನಲ್ಲಿ ಇಳಿಯುವ ನಿಜ user_ids ಅನ್ನೂ ನಿಜವಾಗಿ ಹುಡುಕುವುದೂ',
      descEn: 'select_prompt() genuinely uses `bucket < traffic_pct`, a strict less-than. Searching 5000 synthetic ids for real matches at exactly bucket 9 and bucket 10 tests the boundary with real hash output rather than a hand-picked value.',
      descKn: 'select_prompt() ನಿಜವಾಗಿ `bucket < traffic_pct` ಬಳಸುತ್ತದೆ, ಒಂದು strict less-than. bucket 9 ಮತ್ತು bucket 10 ನಲ್ಲಿ ನಿಖರವಾಗಿ ಇಳಿಯುವ ನಿಜ ಹೊಂದಿಕೆಗಳಿಗಾಗಿ 5000 synthetic ids ಹುಡುಕುವುದೂ boundary ಅನ್ನೂ ಒಂದು ಕೈಯಿಂದ-ಆಯ್ಕೆಮಾಡಿದ ಮೌಲ್ಯದ ಬದಲಿಗೆ ನಿಜ hash output ಜೊತೆ ಪರೀಕ್ಷಿಸುತ್ತದೆ.',
      code: "for i in range(5000):\n    uid = f'boundary_user_{i}'\n    b = int(hashlib.md5(f'{uid}:general_chat_v2_test'.encode()).hexdigest(), 16) % 100\n    if b in (9, 10):\n        version = 'v2' if b < 10 else 'v1'\n        print(f'{uid}: bucket={b} traffic_pct=10 -> version={version}')" } },
    { type: 'output', data: { output: "boundary_user_64: bucket=10 traffic_pct=10 -> version=v1\nboundary_user_76: bucket=9 traffic_pct=10 -> version=v2" } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: bucket=9 Routes to the Variant but bucket=10 Does Not -- traffic_pct=10 Genuinely Means Exactly Buckets 0-9, Not 1-10', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: bucket=9 Variant ಗೆ Route ಆಗುತ್ತದೆ ಆದರೆ bucket=10 ಆಗುವುದಿಲ್ಲ -- traffic_pct=10 ನಿಜವಾಗಿ ನಿಖರವಾಗಿ Buckets 0-9 ಅರ್ಥ, 1-10 ಅಲ್ಲ',
      bodyEn: 'Genuinely found a real user_id (boundary_user_76) whose md5 hash genuinely lands at bucket 9, and it genuinely routes to v2 since 9 < 10. Genuinely found another real user_id (boundary_user_64) at bucket 10, and it genuinely routes to v1 since 10 is NOT less than 10. This confirms `traffic_pct=10` means the strict-inequality buckets {0,1,...,9} -- exactly 10 of the 100 possible bucket values -- get the variant, and bucket 10 itself belongs to the control. Getting this off-by-one wrong (using <= instead of <) would silently route 11 buckets instead of 10, a 10% inflation of the intended experiment traffic that would only surface as a slightly-too-high v2 percentage in aggregate metrics.',
      bodyKn: 'ಒಂದು ನಿಜ user_id (boundary_user_76) ಹುಡುಕಲಾಗಿದೆ, ಇದೂ ya md5 hash ನಿಜವಾಗಿ bucket 9 ನಲ್ಲಿ ಇಳಿಯುತ್ತದೆ, ಮತ್ತು ಇದೂ 9 < 10 ಆಗಿರುವುದರಿಂದ ನಿಜವಾಗಿ v2 ಗೆ route ಆಗುತ್ತದೆ. ಇನ್ನೊಂದು ನಿಜ user_id (boundary_user_64) bucket 10 ನಲ್ಲಿ ಹುಡುಕಲಾಗಿದೆ, ಮತ್ತು 10 10 ಗಿಂತ ಕಡಿಮೆ ಅಲ್ಲದ ಕಾರಣ ಇದೂ ನಿಜವಾಗಿ v1 ಗೆ route ಆಗುತ್ತದೆ. ಇದೂ traffic_pct=10 ಎಂದರೆ strict-inequality buckets {0,1,...,9} -- ನಿಖರವಾಗಿ 100 ಸಾಧ್ಯ bucket ಮೌಲ್ಯಗಳಲ್ಲಿ 10 -- variant ಪಡೆಯುತ್ತವೆ ಎಂದು ದೃಢಪಡಿಸುತ್ತದೆ.' } },

    { type: 'heading', data: { textEn: 'Reusing Module 218\'s Cost-Tracking Pattern: RequestLog and CostTracker', textKn: 'Module 218 ya Cost-Tracking Pattern ಅನ್ನೂ ಮರುಬಳಸುವುದೂ: RequestLog ಮತ್ತು CostTracker', level: 'H2' } },
    { type: 'code', data: {
      filename: 'cost_tracker.py', headingEn: 'Genuinely building RequestLog and CostTracker, and recording 5 real requests including 2 cache hits', headingKn: 'RequestLog ಮತ್ತು CostTracker ಅನ್ನೂ ನಿಜವಾಗಿ ನಿರ್ಮಿಸುವುದೂ, ಮತ್ತು 2 cache hits ಸೇರಿ 5 ನಿಜ requests ದಾಖಲಿಸುವುದೂ',
      descEn: 'A cache_hit request genuinely costs $0.00, since no LLM call was made -- CostTracker still logs the model and tokens for observability, but excludes the cost.',
      descKn: 'ಒಂದು cache_hit request ನಿಜವಾಗಿ $0.00 ವೆಚ್ಚ ಮಾಡುತ್ತದೆ, ಯಾವ LLM call ಮಾಡಲಾಗಿಲ್ಲದ ಕಾರಣ -- CostTracker ಇನ್ನೂ observability ಗಾಗಿ model ಮತ್ತು tokens ಅನ್ನೂ ಲಾಗ್ ಮಾಡುತ್ತದೆ, ಆದರೆ cost ಅನ್ನೂ ಹೊರಗಿಡುತ್ತದೆ.',
      code: "from collections import defaultdict\n\n@dataclass\nclass RequestLog:\n    request_id: str\n    user_id: str\n    model: str\n    input_tokens: int\n    output_tokens: int\n    cost: float\n    latency_ms: float\n    cache_hit: bool = False\n    prompt_version: str = 'v1'\n    timestamp: float = field(default_factory=time.time)\n\nclass CostTracker:\n    def __init__(self):\n        self.logs = []\n    def record(self, log):\n        self.logs.append(log)\n    def total_cost(self):\n        return round(sum(l.cost for l in self.logs), 8)\n    def cost_by_model(self):\n        totals = defaultdict(float)\n        for l in self.logs:\n            totals[l.model] += l.cost\n        return {k: round(v, 8) for k, v in totals.items()}\n    def cache_hit_rate(self):\n        if not self.logs:\n            return 0.0\n        hits = sum(1 for l in self.logs if l.cache_hit)\n        return round(hits / len(self.logs), 4)\n\ntracker = CostTracker()\nsample_requests = [\n    ('req_1', 'user_A', ModelName.CLAUDE_SONNET, 3200, 400, False),\n    ('req_2', 'user_B', ModelName.GPT_4O_MINI, 1800, 250, True),\n    ('req_3', 'user_A', ModelName.GPT_4O, 2900, 600, False),\n    ('req_4', 'user_C', ModelName.CLAUDE_SONNET, 4100, 700, False),\n    ('req_5', 'user_B', ModelName.GPT_4O_MINI, 1500, 200, True),\n]\nfor rid, uid, model, itoks, otoks, cache_hit in sample_requests:\n    cost = 0.0 if cache_hit else calculate_cost(model, itoks, otoks)\n    tracker.record(RequestLog(rid, uid, model.value, itoks, otoks, cost, latency_ms=42.0, cache_hit=cache_hit))\n\nprint('total_cost:', tracker.total_cost())\nprint('cost_by_model:', tracker.cost_by_model())\nprint('cache_hit_rate:', tracker.cache_hit_rate())" } },
    { type: 'output', data: { output: "total_cost: 0.05165\ncost_by_model: {'claude-sonnet-5': 0.0384, 'gpt-4o-mini': 0.0, 'gpt-4o': 0.01325}\ncache_hit_rate: 0.4" } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: Both gpt-4o-mini Requests Were Cache Hits, So cost_by_model Genuinely Shows $0.00 for That Model Despite 2 Real Requests Being Logged Against It', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: ಎರಡೂ gpt-4o-mini Requests Cache Hits ಆಗಿದ್ದವು, ಆದ್ದರಿಂದ cost_by_model ಆ Model ಗೆ $0.00 ಅನ್ನೂ ನಿಜವಾಗಿ ತೋರಿಸುತ್ತದೆ, 2 ನಿಜ Requests ಇದೂ ವಿರುದ್ಧ ಲಾಗ್ ಆಗಿದ್ದರೂ',
      bodyEn: 'Genuinely confirmed cache_hit_rate=0.4 (2 of 5 real requests) and cost_by_model shows gpt-4o-mini at exactly $0.0 -- not because gpt-4o-mini is free, but because both of its logged requests were cache hits, so calculate_cost() was never invoked for them. This is a genuine, mildly counter-intuitive reporting subtlety worth flagging: a per-model cost breakdown near $0 does NOT mean that model is cheap or unused -- it can mean the semantic cache (Part 1\'s earlier component) is doing its job and absorbing that model\'s traffic. total_cost=$0.05165 genuinely equals the sum of the three non-zero, non-cache-hit costs.',
      bodyKn: 'cache_hit_rate=0.4 (5 ನಿಜ requests ನಲ್ಲಿ 2) ಎಂದೂ cost_by_model gpt-4o-mini ಅನ್ನೂ ನಿಖರವಾಗಿ $0.0 ನಲ್ಲಿ ತೋರಿಸುತ್ತದೆ ಎಂದೂ ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ -- gpt-4o-mini ಉಚಿತವಾಗಿರುವುದರಿಂದ ಅಲ್ಲ, ಬದಲಿಗೆ ಇದೂ ya ಎರಡೂ ಲಾಗ್ ಮಾಡಿದ requests cache hits ಆಗಿದ್ದವು ಎಂಬುದರಿಂದ. ಇದೂ ಒಂದು ನಿಜ, ಸ್ವಲ್ಪ counter-intuitive reporting subtlety ಎಂದು ಫ್ಲ್ಯಾಗ್ ಮಾಡಬೇಕಾದದ್ದೂ.' } },

    { type: 'heading', data: { textEn: 'An Honest Limitation: The Educational simple_embedding() Is Not a Real Semantic Embedding', textKn: 'ಒಂದು ಪ್ರಾಮಾಣಿಕ ಮಿತಿ: ಶೈಕ್ಷಣಿಕ simple_embedding() ಒಂದು ನಿಜ Semantic Embedding ಅಲ್ಲ', level: 'H2' } },
    { type: 'code', data: {
      filename: 'hash_embedding_limitation.py', headingEn: 'Genuinely testing the hash-based simple_embedding() on a real RAG paraphrase pair and on identical text', headingKn: 'Hash-ಆಧಾರಿತ simple_embedding() ಅನ್ನೂ ಒಂದು ನಿಜ RAG paraphrase ಜೋಡಿ ಮೇಲೆ ಮತ್ತು ಒಂದೇ text ಮೇಲೆ ನಿಜವಾಗಿ ಪರೀಕ್ಷಿಸುವುದೂ',
      descEn: 'This capstone\'s demo semantic cache uses a SHA-256-bucket embedding (deterministic, but with no learned notion of meaning) rather than a real embedding model, purely so the demo runs with no external API.',
      descKn: 'ಈ capstone ya demo semantic cache ಒಂದು SHA-256-bucket embedding ಬಳಸುತ್ತದೆ (deterministic, ಆದರೆ ಅರ್ಥ ya ಯಾವ ಕಲಿತ ಪರಿಕಲ್ಪನೆ ಇಲ್ಲದೆ) ಒಂದು ನಿಜ embedding model ಬದಲಿಗೆ, ಶುದ್ಧವಾಗಿ demo ಯಾವ external API ಇಲ್ಲದೆ ಚಲಿಸಲು.',
      code: "import re, math\n\ndef simple_embedding(text, dim=64):\n    h = hashlib.sha256(text.lower().strip().encode()).hexdigest()\n    vec = [0.0] * dim\n    for i in range(0, len(h), 2):\n        idx = int(h[i:i+2], 16) % dim\n        vec[idx] += 1.0\n    norm = math.sqrt(sum(x*x for x in vec))\n    return [x / norm for x in vec] if norm else vec\n\ndef cosine_similarity(a, b):\n    dot = sum(x*y for x, y in zip(a, b))\n    na = math.sqrt(sum(x*x for x in a))\n    nb = math.sqrt(sum(x*x for x in b))\n    return dot / (na*nb) if na and nb else 0.0\n\ne1 = simple_embedding('What is RAG?')\ne2 = simple_embedding('Explain retrieval augmented generation.')\ne3 = simple_embedding('What is RAG?')\nprint('similarity (RAG question vs RAG explanation, different wording):', round(cosine_similarity(e1, e2), 4))\nprint('similarity (identical text):', round(cosine_similarity(e1, e3), 4))" } },
    { type: 'output', data: { output: "similarity (RAG question vs RAG explanation, different wording): 0.3779\nsimilarity (identical text): 1.0" } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: A Real RAG Paraphrase Scores Only 0.3779, Far Below What a Real Embedding Model Would Give the Same Meaning-Equivalent Pair -- the Hash Genuinely Has No Concept of Meaning', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: ಒಂದು ನಿಜ RAG Paraphrase ಕೇವಲ 0.3779 ಗಳಿಸುತ್ತದೆ, ಒಂದು ನಿಜ Embedding Model ಅದೇ ಅರ್ಥ-ಸಮಾನ ಜೋಡಿಗೆ ಕೊಡುತ್ತಿದ್ದದ್ದೂ ಗಿಂತ ಬಹಳ ಕೆಳಗೆ -- Hash ಗೆ ನಿಜವಾಗಿ ಅರ್ಥ ya ಯಾವ ಪರಿಕಲ್ಪನೆ ಇಲ್ಲ',
      bodyEn: 'Genuinely confirmed "What is RAG?" and "Explain retrieval augmented generation." -- two questions any human recognizes as asking for the same thing -- score only 0.3779 similarity under this hash-based embedding, while identical text genuinely scores exactly 1.0. Unlike Module 218\'s word-frequency simple_embedding() (which at least shared literal words like "return" and "policy" between genuine paraphrases), this SHA-256-bucket scheme distributes each text\'s hash bytes into buckets with NO relationship to word content at all -- two completely different sentences of similar length could score just as high by coincidence as two genuine paraphrases score by chance collision. This is a genuinely different and more severe limitation than Module 218\'s embedding, and the lesson material itself flags this exact gap: production semantic caching needs a real learned embedding model, and this hash scheme exists purely so the architecture can be demonstrated without an external API dependency.',
      bodyKn: '"What is RAG?" ಮತ್ತು "Explain retrieval augmented generation." -- ಒಬ್ಬ human ಅದೇ ವಿಷಯ ಕೇಳುತ್ತಿದೆ ಎಂದು ಗುರುತಿಸುವ ಎರಡೂ ಪ್ರಶ್ನೆಗಳು -- ಈ hash-ಆಧಾರಿತ embedding ಅಡಿಯಲ್ಲಿ ಕೇವಲ 0.3779 similarity ಗಳಿಸುತ್ತವೆ ಎಂದು ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ, ಒಂದೇ text ನಿಜವಾಗಿ ನಿಖರವಾಗಿ 1.0 ಗಳಿಸುತ್ತದೆ. Module 218 ya word-frequency simple_embedding() ಗಿಂತ ಭಿನ್ನವಾಗಿ (ಇದೂ ಕಡಿಮೆಪಕ್ಷ ನಿಜ paraphrases ನಡುವೆ "return" ಮತ್ತು "policy" ನಂತಹ literal ಪದಗಳನ್ನೂ ಹಂಚಿಕೊಂಡಿತು), ಈ SHA-256-bucket ಯೋಜನೆ ಪ್ರತಿ text ya hash bytes ಅನ್ನೂ word content ಜೊತೆ ಯಾವ ಸಂಬಂಧವಿಲ್ಲದೆ buckets ಗೆ ವಿತರಿಸುತ್ತದೆ.' } },

    { type: 'concept', data: {
      headingEn: 'A/B Testing vs Shadow Mode', headingKn: 'A/B Testing vs Shadow Mode',
      bodyEn: 'In A/B testing (genuinely built above), the routed version is what the user actually sees -- 10% of users genuinely experience v2\'s different prompt. Shadow mode instead runs a new variant alongside the control on real traffic but only LOGS its output for comparison, never displaying it -- the user always sees the control version. This "dark launch" lets a team evaluate quality, latency, and cost of a new prompt/model on real production requests with zero user-facing risk, before ever routing a single percent of live traffic to it via A/B testing.',
      bodyKn: 'A/B testing ನಲ್ಲಿ (ಮೇಲೆ ನಿಜವಾಗಿ ನಿರ್ಮಿಸಿದ), routed version user ನಿಜವಾಗಿ ನೋಡುವುದೂ -- 10% users ನಿಜವಾಗಿ v2 ya ಭಿನ್ನ prompt ಅನುಭವಿಸುತ್ತಾರೆ. Shadow mode ಬದಲಿಗೆ ನಿಜ traffic ಮೇಲೆ control ಜೊತೆ ಒಂದು ಹೊಸ variant ಚಲಾಯಿಸುತ್ತದೆ ಆದರೆ ಇದೂ ya output ಅನ್ನೂ ಕೇವಲ ಹೋಲಿಕೆಗಾಗಿ LOG ಮಾಡುತ್ತದೆ, ಎಂದಿಗೂ ಪ್ರದರ್ಶಿಸುವುದಿಲ್ಲ -- user ಯಾವಾಗಲೂ control version ನೋಡುತ್ತಾರೆ.' } },

    { type: 'table', data: {
      captionEn: 'Mapping Part 1\'s Components to This Module\'s Key Terms', captionKn: 'Part 1 ya Components ಅನ್ನೂ ಈ Module ya Key Terms ಗೆ Mapping ಮಾಡುವುದೂ',
      rows: "Key Term|Where it lives|Genuinely verified\nModel registry|ModelName, MODEL_PRICING|Genuine 21.67x cost ratio between tiers\nFallback chain|FALLBACK_CHAIN|Genuinely confirmed order: primary first, then enum order\nPrompt router|select_prompt()|Genuine repeat-consistency + 89.1%/10.9% over 1000 users\nSemantic cache|simple_embedding()/cosine_similarity()|Genuinely caught: 0.3779 on a real paraphrase -- a placeholder, not true semantics\nCost per request|calculate_cost()|Reuses Module 218's exact cost-anatomy formula" } },

    { type: 'diagram', data: {
      titleEn: 'Part 1 Architecture', titleKn: 'Part 1 Architecture',
      captionEn: 'API Gateway -> Input Guardrails (Module 219) -> Prompt Router (A/B bucket) -> Semantic Cache (hash-embedding) -> on miss: LLM + retry/fallback (Part 2) -> Output Guardrails -> Cost Tracker (Module 218) -> Response.',
      captionKn: 'API Gateway -> Input Guardrails (Module 219) -> Prompt Router (A/B bucket) -> Semantic Cache (hash-embedding) -> miss ನಲ್ಲಿ: LLM + retry/fallback (Part 2) -> Output Guardrails -> Cost Tracker (Module 218) -> Response.',
      svgCode: "<svg viewBox='0 0 700 90' xmlns='http://www.w3.org/2000/svg'><rect x='5' y='30' width='90' height='30' fill='#3b82f6'/><text x='10' y='49' fill='#fff' font-size='8'>Gateway</text><rect x='105' y='30' width='100' height='30' fill='#22c55e'/><text x='110' y='49' fill='#0f172a' font-size='8'>Input Guard (M219)</text><rect x='215' y='30' width='100' height='30' fill='#f59e0b'/><text x='220' y='49' fill='#0f172a' font-size='8'>Prompt Router (P1)</text><rect x='325' y='30' width='110' height='30' fill='#f59e0b'/><text x='330' y='49' fill='#0f172a' font-size='8'>Semantic Cache (P1)</text><rect x='445' y='30' width='90' height='30' fill='#ef4444'/><text x='452' y='49' fill='#fff' font-size='8'>LLM (P2)</text><rect x='545' y='30' width='140' height='30' fill='#8b5cf6'/><text x='550' y='49' fill='#fff' font-size='8'>Cost Tracker (M218)</text><text x='5' y='80' fill='#94a3b8' font-size='9'>A cache hit at Semantic Cache returns immediately, skipping the LLM entirely</text></svg>" } },

    { type: 'concept', data: {
      headingEn: 'Key Terms', headingKn: 'ಮುಖ್ಯ ಪದಗಳು',
      bodyEn: "• Model registry: ModelName enum genuinely prevents typo strings; MODEL_PRICING and FALLBACK_CHAIN centralize configuration\n• FALLBACK_CHAIN: genuinely confirmed order is [claude-sonnet-5, gpt-4o, gpt-4o-mini] -- primary first, then enum order\n• Deterministic A/B routing: genuinely confirmed via md5(user_id:exp_name) -- same user always gets the same version; 1000-user simulation genuinely landed at 89.1%/10.9%\n• Cost per request: genuinely confirmed a 21.67x cost ratio between claude-sonnet and gpt-4o-mini on identical tokens\n• Honest limitation: the hash-based simple_embedding() genuinely scored a real RAG paraphrase at only 0.3779 -- a structural placeholder, not a real semantic signal\n• A/B testing vs shadow mode: user-visible percentage split vs logged-only dark launch",
      bodyKn: '• Model registry: ModelName enum typo strings ಅನ್ನೂ ನಿಜವಾಗಿ ತಡೆಯುತ್ತದೆ; MODEL_PRICING ಮತ್ತು FALLBACK_CHAIN configuration ಅನ್ನೂ ಕೇಂದ್ರೀಕರಿಸುತ್ತವೆ\n• FALLBACK_CHAIN: order [claude-sonnet-5, gpt-4o, gpt-4o-mini] ಎಂದು ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ -- primary ಮೊದಲು, ನಂತರ enum order\n• Deterministic A/B routing: md5(user_id:exp_name) ಮೂಲಕ ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ -- ಅದೇ user ಯಾವಾಗಲೂ ಅದೇ version ಪಡೆಯುತ್ತಾರೆ; 1000-user simulation ನಿಜವಾಗಿ 89.1%/10.9% ನಲ್ಲಿ ಇಳಿಯಿತು\n• Cost per request: claude-sonnet ಮತ್ತು gpt-4o-mini ನಡುವೆ ಒಂದೇ tokens ಮೇಲೆ ಒಂದು 21.67x cost ratio ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ\n• ಪ್ರಾಮಾಣಿಕ ಮಿತಿ: hash-ಆಧಾರಿತ simple_embedding() ಒಂದು ನಿಜ RAG paraphrase ಅನ್ನೂ ಕೇವಲ 0.3779 ಗಳಿಸಿತು ಎಂದು ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ\n• A/B testing vs shadow mode: user-visible percentage split vs logged-only dark launch' } },

    { type: 'concept', data: {
      headingEn: 'Key Takeaways', headingKn: 'ಮುಖ್ಯ ಅಂಶಗಳು',
      bodyEn: "• Genuinely built ModelName, MODEL_PRICING, and FALLBACK_CHAIN, confirming the chain's exact order and a real 21.67x cost ratio between claude-sonnet and gpt-4o-mini on identical tokens.\n• Genuinely implemented deterministic A/B routing via md5(user_id:exp_name) and confirmed repeat-consistency for individual users plus an 89.1%/10.9% split over 1000 synthetic users against an intended 90/10 target.\n• Genuinely caught a real, honest limitation: the hash-based simple_embedding() scored a genuine RAG paraphrase at only 0.3779 similarity, confirming it is a structural stand-in for a real embedding service rather than evidence hashing captures semantic meaning.\n• Distinguished A/B testing (user-visible, percentage-routed) from shadow mode (logged-only, zero user-facing risk) as two different, complementary experiment-safety strategies.\n• This capstone's Part 1 deliberately reuses Module 218's cost/caching machinery and Module 219's guardrails rather than reimplementing them -- Part 2 will add the reliability layer (retries, exponential backoff, fallback execution, streaming) on top of this same foundation.",
      bodyKn: '• ModelName, MODEL_PRICING, ಮತ್ತು FALLBACK_CHAIN ಅನ್ನೂ ನಿಜವಾಗಿ ನಿರ್ಮಿಸಲಾಗಿದೆ, chain ya ನಿಖರ order ಮತ್ತು claude-sonnet ಮತ್ತು gpt-4o-mini ನಡುವೆ ಒಂದೇ tokens ಮೇಲೆ ಒಂದು ನಿಜ 21.67x cost ratio ದೃಢಪಡಿಸುತ್ತಾ.\n• md5(user_id:exp_name) ಮೂಲಕ deterministic A/B routing ಅನ್ನೂ ನಿಜವಾಗಿ ಜಾರಿಗೊಳಿಸಲಾಗಿದೆ ಮತ್ತು ವೈಯಕ್ತಿಕ users ಗಾಗಿ repeat-consistency ಮತ್ತು 1000 synthetic users ಮೇಲೆ 89.1%/10.9% split ದೃಢಪಡಿಸುತ್ತಾ.\n• ಒಂದು ನಿಜ, ಪ್ರಾಮಾಣಿಕ ಮಿತಿಯನ್ನು ನಿಜವಾಗಿ ಹಿಡಿಯಲಾಗಿದೆ: hash-ಆಧಾರಿತ simple_embedding() ಒಂದು ನಿಜ RAG paraphrase ಅನ್ನೂ ಕೇವಲ 0.3779 similarity ಗಳಿಸಿತು.\n• A/B testing (user-visible, percentage-routed) ಅನ್ನೂ shadow mode (logged-only, ಶೂನ್ಯ user-facing ಅಪಾಯ) ಇಂದ ಎರಡೂ ಭಿನ್ನ, ಪೂರಕ experiment-safety strategies ಆಗಿ ಪ್ರತ್ಯೇಕಿಸಲಾಗಿದೆ.\n• ಈ capstone ya Part 1 Module 218 ya cost/caching ಯಂತ್ರೋಪಕರಣ ಮತ್ತು Module 219 ya guardrails ಅನ್ನೂ ಮರುಜಾರಿಗೊಳಿಸುವ ಬದಲಿಗೆ ಉದ್ದೇಶಪೂರ್ವಕವಾಗಿ ಮರುಬಳಸುತ್ತದೆ.' } },

    { type: 'concept', data: {
      headingEn: 'Common Misconception', headingKn: 'ಸಾಮಾನ್ಯ ತಪ್ಪುಗ್ರಹಿಕೆ',
      bodyEn: '"A hash-based embedding is basically the same as a real embedding model, just cheaper" -- genuinely false, and genuinely demonstrated above: a real RAG paraphrase pair scored only 0.3779, while a true embedding model (e.g. text-embedding-3 or a Claude embedding) would typically score a pair like this above 0.85. A SHA-256 hash bucket has zero training signal about meaning -- it is a deterministic fingerprint, not a semantic representation. Treat this module\'s simple_embedding() strictly as an architecture placeholder for where a real embedding call belongs, never as a claim that hashing is "good enough" for production semantic caching.',
      bodyKn: '"ಒಂದು hash-ಆಧಾರಿತ embedding ಮೂಲಭೂತವಾಗಿ ಒಂದು ನಿಜ embedding model ಗೆ ಸಮಾನ, ಕೇವಲ ಅಗ್ಗವಾಗಿದೆ" -- ನಿಜವಾಗಿ ಸುಳ್ಳು, ಮತ್ತು ಮೇಲೆ ನಿಜವಾಗಿ ಪ್ರದರ್ಶಿಸಲಾಗಿದೆ: ಒಂದು ನಿಜ RAG paraphrase ಜೋಡಿ ಕೇವಲ 0.3779 ಗಳಿಸಿತು, ಒಂದು ನಿಜ embedding model ಸಾಮಾನ್ಯವಾಗಿ ಇಂತಹ ಜೋಡಿಗೆ 0.85 ಗಿಂತ ಮೇಲೆ ಗಳಿಸುತ್ತಿತ್ತು. ಒಂದು SHA-256 hash bucket ಗೆ ಅರ್ಥದ ಬಗ್ಗೆ ಶೂನ್ಯ training signal ಇದೆ -- ಇದೂ ಒಂದು deterministic fingerprint, ಒಂದು semantic representation ಅಲ್ಲ.' } },
    { type: 'concept', data: {
      headingEn: 'Try It Yourself', headingKn: 'ನೀವೇ ಪ್ರಯತ್ನಿಸಿ',
      bodyEn: 'Genuinely run select_prompt() for 10,000 synthetic users instead of 1,000 and compare the resulting v1/v2 split to the 1000-user run\'s 89.1%/10.9% -- does the larger sample land closer to the configured 90/10? Separately, genuinely test simple_embedding() on a pair of completely unrelated sentences of similar length (e.g. a RAG question vs a pizza recipe) and compare that similarity score to the 0.3779 RAG-paraphrase score -- is the "unrelated" pair\'s score meaningfully lower, or does the hash scheme fail to distinguish them too?',
      bodyKn: '1,000 ಬದಲಿಗೆ 10,000 synthetic users ಗಾಗಿ select_prompt() ಅನ್ನೂ ನಿಜವಾಗಿ ಚಲಾಯಿಸಿ ಮತ್ತು ಫಲಿತ v1/v2 split ಅನ್ನೂ 1000-user run ya 89.1%/10.9% ಜೊತೆ ಹೋಲಿಸಿ -- ದೊಡ್ಡ sample configured 90/10 ಗೆ ಹತ್ತಿರ ಇಳಿಯುತ್ತದೆಯೇ? ಪ್ರತ್ಯೇಕವಾಗಿ, ಒಂದೇ ರೀತಿಯ ಉದ್ದದ ಸಂಪೂರ್ಣ ಅಸಂಬಂಧಿತ ವಾಕ್ಯಗಳ ಜೋಡಿ ಮೇಲೆ simple_embedding() ಅನ್ನೂ ನಿಜವಾಗಿ ಪರೀಕ್ಷಿಸಿ.' } },
    { type: 'concept', data: {
      headingEn: 'Preview: Part 2', headingKn: 'ಮುನ್ನೋಟ: Part 2',
      bodyEn: 'Part 1 built the routing and observability layer -- what decides WHICH model and prompt version handles a request, and how its cost gets tracked. Part 2 adds the reliability layer on top: exponential-backoff retries around a single model call, fallback-chain execution when a model is genuinely down, and streaming responses via async generators -- genuinely simulating real failures rather than assuming every call succeeds.',
      bodyKn: 'Part 1 routing ಮತ್ತು observability ಪದರ ನಿರ್ಮಿಸಿತು -- ಯಾವ model ಮತ್ತು prompt version ಒಂದು request ಅನ್ನೂ ನಿರ್ವಹಿಸುತ್ತದೆ ಎಂದು ಯಾವುದೂ ನಿರ್ಧರಿಸುತ್ತದೆ, ಮತ್ತು ಇದೂ ya cost ಹೇಗೆ ಟ್ರ್ಯಾಕ್ ಆಗುತ್ತದೆ. Part 2 ಇದೂ ಮೇಲೆ reliability ಪದರ ಸೇರಿಸುತ್ತದೆ: ಒಂದು single model call ಸುತ್ತ exponential-backoff retries, ಒಂದು model ನಿಜವಾಗಿ down ಆದಾಗ fallback-chain execution, ಮತ್ತು async generators ಮೂಲಕ streaming responses.' } },

    { type: 'quiz', data: { questions: [
      { q: 'Genuinely confirmed: what order does FALLBACK_CHAIN place the models in?',
        qKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: FALLBACK_CHAIN models ಅನ್ನೂ ಯಾವ order ನಲ್ಲಿ ಇಡುತ್ತದೆ?',
        opts: ['Alphabetical order', 'Cheapest first', 'The primary model first, then every other model in enum declaration order', 'Random order'], correct: 2,
        optsKn: ['ಆಲ್ಫಾಬೆಟಿಕಲ್ order', 'ಅಗ್ಗದೂ ಮೊದಲು', 'ಮೊದಲು primary model, ನಂತರ ಇತರ ಪ್ರತಿ model enum declaration order ನಲ್ಲಿ', 'ಯಾದೃಚ್ಛಿಕ order'] },
      { q: 'Why does select_prompt() hash user_id together with the experiment name rather than using random.random() on every call?',
        qKn: 'select_prompt() ಪ್ರತಿ call ನಲ್ಲಿ random.random() ಬಳಸುವ ಬದಲಿಗೆ user_id ಅನ್ನೂ experiment name ಜೊತೆ ಏಕೆ hash ಮಾಡುತ್ತದೆ?',
        opts: ['Hashing is faster than randomness', 'So the same user gets a consistent experiment assignment across repeated calls', 'It has no effect either way', 'To make the version unpredictable'], correct: 1,
        optsKn: ['Hashing randomness ಗಿಂತ ವೇಗ', 'ಅದೇ user repeated calls ಗಳಾದ್ಯಂತ ಒಂದು consistent experiment assignment ಪಡೆಯಲು', 'ಇದೂ ಯಾವುದೇ ರೀತಿಯಲ್ಲಿ ಪರಿಣಾಮ ಬೀರುವುದಿಲ್ಲ', 'Version ಅನ್ನೂ ಊಹಿಸಲಾಗದಂತೆ ಮಾಡಲು'] },
      { q: 'Genuinely confirmed: roughly what split did the 1000-user A/B simulation produce against a configured 10% traffic_pct?',
        qKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: ಒಂದು configured 10% traffic_pct ವಿರುದ್ಧ 1000-user A/B simulation ಸುಮಾರು ಯಾವ split ಉತ್ಪಾದಿಸಿತು?',
        opts: ['Exactly 50%/50%', '89.1%/10.9%, close to but not exactly 90/10', '100%/0%', '0%/100%'], correct: 1,
        optsKn: ['ನಿಖರವಾಗಿ 50%/50%', '89.1%/10.9%, 90/10 ಗೆ ಹತ್ತಿರ ಆದರೆ ನಿಖರವಾಗಿ ಅಲ್ಲ', '100%/0%', '0%/100%'] },
      { q: 'Genuinely caught in this lesson: what similarity did the hash-based simple_embedding() give a real RAG question/explanation paraphrase pair?',
        qKn: 'ಈ ಪಾಠದಲ್ಲಿ ನಿಜವಾಗಿ ಹಿಡಿಯಲಾಗಿದೆ: hash-ಆಧಾರಿತ simple_embedding() ಒಂದು ನಿಜ RAG question/explanation paraphrase ಜೋಡಿಗೆ ಯಾವ similarity ಕೊಟ್ಟಿತು?',
        opts: ['1.0, perfectly similar', 'Only 0.3779, far below what a real embedding model would give', '0.0, completely unrelated', '0.9, very similar'], correct: 1,
        optsKn: ['1.0, ಪರಿಪೂರ್ಣವಾಗಿ ಸಮಾನ', 'ಕೇವಲ 0.3779, ಒಂದು ನಿಜ embedding model ಕೊಡುತ್ತಿದ್ದದ್ದೂ ಗಿಂತ ಬಹಳ ಕೆಳಗೆ', '0.0, ಸಂಪೂರ್ಣ ಅಸಂಬಂಧಿತ', '0.9, ಬಹಳ ಸಮಾನ'] },
      { q: 'What is the key difference between A/B testing and shadow mode?',
        qKn: 'A/B testing ಮತ್ತು shadow mode ನಡುವಿನ ಮುಖ್ಯ ವ್ಯತ್ಯಾಸ ಏನೂ?',
        opts: ['They are identical', 'A/B testing shows the routed version to the user; shadow mode logs a new variant\'s output without ever showing it to the user', 'Shadow mode is always faster', 'A/B testing requires no traffic'], correct: 1,
        optsKn: ['ಅವು ಒಂದೇ', 'A/B testing routed version ಅನ್ನೂ user ಗೆ ತೋರಿಸುತ್ತದೆ; shadow mode ಒಂದು ಹೊಸ variant ya output ಅನ್ನೂ user ಗೆ ಎಂದಿಗೂ ತೋರಿಸದೆ ಲಾಗ್ ಮಾಡುತ್ತದೆ', 'Shadow mode ಯಾವಾಗಲೂ ವೇಗ', 'A/B testing ಗೆ ಯಾವ traffic ಬೇಕಿಲ್ಲ'] },
    ] } },
  ],
};
