const phaseId = '6a369d5766020ed05b32136a'; // Phase 10
const moduleId = '6a369d5866020ed05b321388'; // Module 146: Audio Transformers: Whisper Architecture

module.exports = {
  phaseId,
  moduleId,
  order: 3,
  type: 'interactive',
  duration: 45,
  difficulty: 'intermediate',
  status: 'published',
  title: 'Whisper (Part 3) — Build, Use & Ship Whisper',
  titleKn: 'Whisper (Part 3) — Build, Use & Ship Whisper',
  desc: 'Genuinely re-run frame_signal() on a synthesized 440Hz sine wave, confirming the exact frame count the lesson claims (98, not the intuitive ~100), then trace the real inference path (model.transcribe, faster-whisper, VAD, chunking) and genuinely compute WER on a worked example.',
  descKn: 'ಒಂದೂ synthesized 440Hz sine wave ಮೇಲೆ frame_signal() ಅನ್ನೂ ನಿಜವಾಗಿ ಮತ್ತೆ ಚಲಾಯಿಸಿ, lesson ಪ್ರತಿಪಾದಿಸುವ ನಿಖರ frame count (98, ಅರ್ಥಗರ್ಭಿತ ~100 ಅಲ್ಲ) ದೃಢಪಡಿಸಿ, ನಂತರ ನಿಜ inference path (model.transcribe, faster-whisper, VAD, chunking) ಪತ್ತೆಹಚ್ಚಿ ಮತ್ತು ಒಂದೂ worked example ಮೇಲೆ WER ಅನ್ನೂ ನಿಜವಾಗಿ ಗಣಿಸಿ.',
  objectives: [
    'Explain what frame_signal() and whisper_prompt() are each implementing.',
    'Generate a synthetic audio signal and compute its exact frame count.',
    'Understand why the code produces 98 frames, not the intuitive ~100.',
    'Trace model.transcribe() and faster-whisper as real inference paths.',
    'Understand VAD, quantization, and chunking at a practical level.',
    'Compute Word Error Rate on a worked example.',
    'Know when Whisper is a good choice and when another ASR system is better.',
  ],
  objectivesKn: [
    'frame_signal() ಮತ್ತು whisper_prompt() ಪ್ರತಿಯೊಂದೂ ಏನೂ implement ಮಾಡುತ್ತದೆ ಎಂದು ವಿವರಿಸಿ.',
    'ಒಂದೂ synthetic audio signal ಉತ್ಪಾದಿಸಿ ಮತ್ತು ಅದರ ನಿಖರ frame count ಗಣಿಸಿ.',
    'Code ಏಕೆ 98 frames ಉತ್ಪಾದಿಸುತ್ತದೆ, ಅರ್ಥಗರ್ಭಿತ ~100 ಅಲ್ಲ ಎಂದು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'model.transcribe() ಮತ್ತು faster-whisper ಅನ್ನೂ ನಿಜ inference paths ಆಗಿ ಪತ್ತೆಹಚ್ಚಿ.',
    'VAD, quantization, ಮತ್ತು chunking ಅನ್ನೂ ಪ್ರಾಯೋಗಿಕ ಮಟ್ಟದಲ್ಲಿ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'ಒಂದೂ worked example ಮೇಲೆ Word Error Rate ಗಣಿಸಿ.',
    'Whisper ಯಾವಾಗ ಒಳ್ಳೆಯ ಆಯ್ಕೆ ಮತ್ತು ಯಾವಾಗ ಬೇರೆ ASR system ಒಳ್ಳೆಯದೂ ಎಂದು ತಿಳಿಯಿರಿ.',
  ],
  blocks: [
    { type: 'heading', data: { textEn: 'Build, Use & Ship Whisper', textKn: 'Build, Use & Ship Whisper', level: 'H1' } },
    { type: 'concept', data: {
      headingEn: 'Lesson Info', headingKn: 'Lesson ಮಾಹಿತಿ',
      bodyEn: '• Type: Build · Language: Python (NumPy) · Prerequisites: Part 1 -- framing, Part 2 -- encoder/decoder/task tokens · Time: ~45 minutes · Part 3 of 3',
      bodyKn: '• Type: Build · Language: Python (NumPy) · Prerequisites: Part 1 -- framing, Part 2 -- encoder/decoder/task tokens · Time: ~45 ನಿಮಿಷಗಳು · Part 3 of 3',
      pillsEn: 'Python,NumPy,Prereq: Parts 1-2,~45 min,Part 3 of 3',
      pillsKn: 'Python,NumPy,Prereq: Parts 1-2,~45 ನಿಮಿಷ,Part 3 of 3' } },

    { type: 'heading', data: { textEn: 'Re-Running frame_signal() — Intuition vs Exact Output', textKn: 'Re-Running frame_signal() — Intuition vs Exact Output', level: 'H2' } },
    { type: 'code', data: {
      filename: 'frame_signal.py', headingEn: 'code for concepts', headingKn: 'concepts ಗಾಗಿ code',
      descEn: 'Genuinely executed below: a synthesized 1-second, 440Hz, 16kHz sine wave passed through the original frame_signal() function, exactly as given.',
      descKn: 'ಕೆಳಗೆ ನಿಜವಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ: ಒಂದೂ synthesized 1-second, 440Hz, 16kHz sine wave ಅನ್ನೂ ಮೂಲ frame_signal() function ಮೂಲಕ ರವಾನಿಸಲಾಗಿದೆ, ನೀಡಿದಂತೆ ನಿಖರವಾಗಿ.',
      code: "import numpy as np\n\nsample_rate = 16000\nt = np.linspace(0, 1.0, sample_rate, endpoint=False)\nx = np.sin(2 * np.pi * 440 * t)\nprint('len(x):', len(x))\n\ndef frame_signal(x, frame_size=400, hop=160):\n    frames = []\n    for start in range(0, len(x) - frame_size + 1, hop):\n        frames.append(x[start:start + frame_size])\n    return frames\n\nframes = frame_signal(x)\nprint('len(frames):', len(frames))\nprint('len(frames[0]):', len(frames[0]))\n\n# intuitive estimate vs exact formula\nintuitive = 1000 // 10\nexact = (len(x) - 400) // 160 + 1\nprint('intuitive (1000ms / 10ms hop):', intuitive)\nprint('exact floor((N-frame_size)/hop)+1:', exact)\n\n# 30-second case\nN30 = 16000 * 30\nprint('30s exact frame count:', (N30 - 400) // 160 + 1)" } },
    { type: 'output', data: { output: "len(x): 16000\nlen(frames): 98\nlen(frames[0]): 400\nintuitive (1000ms / 10ms hop): 100\nexact floor((N-frame_size)/hop)+1: 98\n30s exact frame count: 2998" } },
    { type: 'concept', data: {
      headingEn: 'Reading the Verified Output', headingKn: 'ಪರಿಶೀಲಿಸಿದ Output ಓದುವುದೂ',
      bodyEn: '• Genuinely confirmed exactly as the lesson states: the intuitive time-based estimate (1000ms / 10ms hop = 100) and the exact code output (98) genuinely differ -- the loop requires each complete 25ms frame to fit inside the 16,000-sample signal, so the last two intuitively-expected starting positions (990 and 1000 in "10ms steps" terms) never happen because a full 400-sample frame would run past the end of the array\n• Genuinely confirmed for 30 seconds: 2,998 frames, matching Part 1\'s already-verified result exactly and the lesson\'s "~3,000" approximation\n• This genuinely reproduces the lesson\'s core engineering lesson: conceptual/architectural dimensions (100, ~3,000) and exact implementation shapes (98, 2,998) are not always identical -- always print and inspect the real array shape rather than trusting the mental model',
      bodyKn: '• Lesson ಹೇಳುವಂತೆ ನಿಖರವಾಗಿ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ: ಅರ್ಥಗರ್ಭಿತ ಸಮಯ-ಆಧಾರಿತ ಅಂದಾಜು (1000ms / 10ms hop = 100) ಮತ್ತು ನಿಖರ code output (98) ನಿಜವಾಗಿ ಭಿನ್ನವಾಗಿವೆ -- loop ಗೆ ಪ್ರತಿ ಪೂರ್ಣ 25ms frame 16,000-sample signal ಒಳಗೆ ಹೊಂದಬೇಕು, ಆದ್ದರಿಂದ ಕೊನೆಯ ಎರಡೂ ಅರ್ಥಗರ್ಭಿತವಾಗಿ-ನಿರೀಕ್ಷಿತ starting positions ಎಂದಿಗೂ ಸಂಭವಿಸುವುದಿಲ್ಲ ಏಕೆಂದರೆ ಒಂದೂ ಪೂರ್ಣ 400-sample frame array ಅಂತ್ಯ ಮೀರಿ ಓಡುತ್ತದೆ\n• 30 ಸೆಕೆಂಡುಗಳಿಗೆ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ: 2,998 frames, Part 1 ನ ಈಗಾಗಲೇ-ಪರಿಶೀಲಿಸಿದ ಫಲಿತಾಂಶಕ್ಕೆ ಮತ್ತು lesson ನ "~3,000" ಅಂದಾಜಿಗೆ ನಿಖರವಾಗಿ ಹೊಂದಿಕೆಯಾಗುತ್ತದೆ\n• ಇದೂ lesson ನ ಮುಖ್ಯ engineering ಪಾಠವನ್ನೂ ನಿಜವಾಗಿ ಪುನರುತ್ಪಾದಿಸುತ್ತದೆ: ಪರಿಕಲ್ಪನಾತ್ಮಕ/architectural dimensions (100, ~3,000) ಮತ್ತು ನಿಖರ implementation shapes (98, 2,998) ಯಾವಾಗಲೂ ಒಂದೇ ಅಲ್ಲ -- mental model ನಂಬುವ ಬದಲು ಯಾವಾಗಲೂ ನಿಜ array shape ಮುದ್ರಿಸಿ ಮತ್ತು ಪರಿಶೀಲಿಸಿ' } },

    { type: 'heading', data: { textEn: 'whisper_prompt() — Decoder Control, Not Audio Processing', textKn: 'whisper_prompt() — Decoder Control, Not Audio Processing', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'Two Functions, Two Jobs', headingKn: 'ಎರಡೂ Functions, ಎರಡೂ ಕೆಲಸಗಳು',
      bodyEn: '• frame_signal() (above) turns a raw waveform into overlapping windows -- pure signal processing, no notion of language or task\n• whisper_prompt() (genuinely verified in Part 2 across English transcription, French transcription, French-to-English translation, and the no-timestamps variant) builds the decoder\'s starting control tokens -- pure decoder configuration, no audio involved\n• These two functions genuinely never touch each other\'s inputs -- one produces `frames`, the other produces `tokens` -- and Whisper\'s real architecture keeps this same separation: encoder consumes audio-derived features, decoder consumes token-derived prompts, and cross-attention (Part 2) is the only bridge between them',
      bodyKn: '• frame_signal() (ಮೇಲೆ) ಒಂದೂ raw waveform ಅನ್ನೂ overlapping windows ಆಗಿ ಪರಿವರ್ತಿಸುತ್ತದೆ -- ಶುದ್ಧ signal processing, language ಅಥವಾ task ನ ಯಾವುದೇ ಕಲ್ಪನೆ ಇಲ್ಲದೆ\n• whisper_prompt() (Part 2 ನಲ್ಲಿ English transcription, French transcription, French-to-English translation, ಮತ್ತು no-timestamps variant ಆದ್ಯಂತ ನಿಜವಾಗಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ) decoder ನ ಆರಂಭಿಕ control tokens ಅನ್ನೂ ನಿರ್ಮಿಸುತ್ತದೆ -- ಶುದ್ಧ decoder configuration, ಯಾವುದೇ audio ಒಳಗೊಂಡಿಲ್ಲ\n• ಈ ಎರಡೂ functions ನಿಜವಾಗಿ ಎಂದಿಗೂ ಒಂದಕ್ಕೊಂದು inputs ಮುಟ್ಟುವುದಿಲ್ಲ -- ಒಂದೂ `frames` ಉತ್ಪಾದಿಸುತ್ತದೆ, ಇನ್ನೊಂದೂ `tokens` ಉತ್ಪಾದಿಸುತ್ತದೆ -- ಮತ್ತು Whisper ನ ನಿಜ architecture ಇದೇ ಪ್ರತ್ಯೇಕತೆ ಇಡುತ್ತದೆ: encoder audio-derived features ಸೇವಿಸುತ್ತದೆ, decoder token-derived prompts ಸೇವಿಸುತ್ತದೆ, ಮತ್ತು cross-attention (Part 2) ಇವೆರಡರ ನಡುವಿನ ಏಕೈಕ ಸೇತುವೆ' } },

    { type: 'heading', data: { textEn: 'From Educational Code to Real Inference', textKn: 'From Educational Code to Real Inference', level: 'H2' } },
    { type: 'code', data: {
      filename: 'real_inference.py', headingEn: 'code for concepts', headingKn: 'concepts ಗಾಗಿ code',
      descEn: 'This is real, runnable Whisper inference code (not re-executed here, since it requires downloading a multi-hundred-million-parameter model and a real audio file) -- shown for the code-to-architecture mapping that follows.',
      descKn: 'ಇದೂ ನಿಜ, ಚಲಾಯಿಸಬಹುದಾದ Whisper inference code (ಇಲ್ಲಿ ಮತ್ತೆ ಚಲಾಯಿಸಲಾಗಿಲ್ಲ, ಇದಕ್ಕೆ ನೂರಾರು-ಮಿಲಿಯನ್-parameter model ಮತ್ತು ನಿಜ audio file ಡೌನ್‌ಲೋಡ್ ಅಗತ್ಯವಿರುವುದರಿಂದ) -- ಕೆಳಗಿನ code-to-architecture mapping ಗಾಗಿ ತೋರಿಸಲಾಗಿದೆ.',
      code: "import whisper\n\nmodel = whisper.load_model('large-v3-turbo')\nresult = model.transcribe('meeting.wav', language='en', task='transcribe')\n\nprint(result['text'])\nprint(result['segments'][0]['start'], result['segments'][0]['end'])\n\n# production-oriented alternative\nfrom faster_whisper import WhisperModel\nfw_model = WhisperModel('large-v3-turbo', compute_type='int8_float16')\nsegments, info = fw_model.transcribe('meeting.wav', vad_filter=True)\nfor s in segments:\n    print(f'{s.start:.2f} - {s.end:.2f}: {s.text}')" } },
    { type: 'concept', data: {
      headingEn: 'Reading This Code Honestly', headingKn: 'ಈ Code ಅನ್ನೂ ಪ್ರಾಮಾಣಿಕವಾಗಿ ಓದುವುದೂ',
      bodyEn: '• Disclosed honestly: unlike frame_signal() and whisper_prompt() above, this block was not genuinely executed in this lesson -- it requires network access to download a real pretrained checkpoint and a real audio file, neither of which is available in this verification environment\n• What genuinely was verified is everything upstream of it: the exact frame counts frame_signal() produces, the exact tokens whisper_prompt() produces, and the exact 4x attention-workload reduction from downsampling (Part 2) -- model.transcribe() genuinely runs this same pipeline internally, just compiled into a trained neural network instead of NumPy arrays\n• The parameter counts commonly cited for these checkpoints (large-v3 near 1550M parameters, large-v3-turbo near 809M, with a substantially smaller decoder) are published figures from the model release, not something independently computed here',
      bodyKn: '• ಪ್ರಾಮಾಣಿಕವಾಗಿ ಬಹಿರಂಗಪಡಿಸಲಾಗಿದೆ: ಮೇಲಿನ frame_signal() ಮತ್ತು whisper_prompt() ಗಿಂತ ಭಿನ್ನವಾಗಿ, ಈ block ಈ lesson ನಲ್ಲಿ ನಿಜವಾಗಿ ಚಲಾಯಿಸಲಾಗಿಲ್ಲ -- ಇದಕ್ಕೆ ಒಂದೂ ನಿಜ pretrained checkpoint ಮತ್ತು ಒಂದೂ ನಿಜ audio file ಡೌನ್‌ಲೋಡ್ ಮಾಡಲು network access ಅಗತ್ಯ, ಇವೆರಡೂ ಈ ಪರಿಶೀಲನಾ ಪರಿಸರದಲ್ಲಿ ಲಭ್ಯವಿಲ್ಲ\n• ಇದರ ಮೊದಲು ಎಲ್ಲವೂ ನಿಜವಾಗಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ: frame_signal() ಉತ್ಪಾದಿಸುವ ನಿಖರ frame counts, whisper_prompt() ಉತ್ಪಾದಿಸುವ ನಿಖರ tokens, ಮತ್ತು downsampling ಇಂದ ನಿಖರ 4x attention-workload ಕಡಿತ (Part 2) -- model.transcribe() ನಿಜವಾಗಿ ಇದೇ pipeline ಅನ್ನೂ ಆಂತರಿಕವಾಗಿ ಚಲಾಯಿಸುತ್ತದೆ, ಕೇವಲ NumPy arrays ಬದಲು ಒಂದೂ trained neural network ಆಗಿ ಸಂಕಲಿಸಲಾಗಿದೆ\n• ಈ checkpoints ಗಾಗಿ ಸಾಮಾನ್ಯವಾಗಿ ಉಲ್ಲೇಖಿಸಲಾದ parameter counts (large-v3 ಸುಮಾರು 1550M parameters, large-v3-turbo ಸುಮಾರು 809M, ಗಣನೀಯವಾಗಿ ಚಿಕ್ಕ decoder ಜೊತೆ) model release ಇಂದ ಪ್ರಕಟಿತ ಅಂಕಿಗಳು, ಇಲ್ಲಿ ಸ್ವತಂತ್ರವಾಗಿ ಗಣಿಸಿದ್ದಲ್ಲ' } },

    { type: 'heading', data: { textEn: 'Measuring Accuracy: Word Error Rate', textKn: 'Measuring Accuracy: Word Error Rate', level: 'H2' } },
    { type: 'code', data: {
      filename: 'wer.py', headingEn: 'code for concepts', headingKn: 'concepts ಗಾಗಿ code',
      descEn: 'Genuinely computed below with a real edit-distance implementation on the lesson\'s own worked example.',
      descKn: 'Lesson ನ ಸ್ವಂತ worked example ಮೇಲೆ ಒಂದೂ ನಿಜ edit-distance implementation ಜೊತೆ ಕೆಳಗೆ ನಿಜವಾಗಿ ಗಣಿಸಲಾಗಿದೆ.',
      code: "def wer(ref, hyp):\n    r, h = ref.split(), hyp.split()\n    m, n = len(r), len(h)\n    dp = [[0]*(n+1) for _ in range(m+1)]\n    for i in range(m+1): dp[i][0] = i\n    for j in range(n+1): dp[0][j] = j\n    for i in range(1, m+1):\n        for j in range(1, n+1):\n            if r[i-1] == h[j-1]:\n                dp[i][j] = dp[i-1][j-1]\n            else:\n                dp[i][j] = 1 + min(dp[i-1][j], dp[i][j-1], dp[i-1][j-1])\n    return dp[m][n] / len(r)\n\nref = 'The cat is sleeping'\nhyp = 'The dog is sleeping'\nprint('WER:', wer(ref, hyp))" } },
    { type: 'output', data: { output: "WER: 0.25" } },
    { type: 'concept', data: {
      headingEn: 'Reading the Verified Output', headingKn: 'ಪರಿಶೀಲಿಸಿದ Output ಓದುವುದೂ',
      bodyEn: '• Genuinely confirmed: one substitution (cat -> dog) out of 4 reference words gives exactly 1/4 = 0.25 -- matching the lesson\'s described "cat -> dog is a substitution" example with a real computed number\n• A genuine edit-distance (Levenshtein) computation is required in general, since real transcription errors include insertions and deletions as well as substitutions -- simple word-by-word comparison would fail whenever the hypothesis has a different length than the reference',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ: 4 reference words ನಲ್ಲಿ ಒಂದೂ substitution (cat -> dog) ನಿಖರವಾಗಿ 1/4 = 0.25 ನೀಡುತ್ತದೆ -- lesson ವಿವರಿಸಿದ "cat -> dog is a substitution" ಉದಾಹರಣೆಗೆ ಒಂದೂ ನಿಜ ಗಣಿಸಿದ ಸಂಖ್ಯೆ ಜೊತೆ ಹೊಂದಿಕೆಯಾಗುತ್ತದೆ\n• ಸಾಮಾನ್ಯವಾಗಿ ಒಂದೂ ನಿಜ edit-distance (Levenshtein) ಗಣನೆ ಅಗತ್ಯ, ನಿಜ transcription errors substitutions ಜೊತೆಗೆ insertions ಮತ್ತು deletions ಸಹ ಒಳಗೊಂಡಿರುವುದರಿಂದ -- hypothesis reference ಗಿಂತ ಭಿನ್ನ ಉದ್ದ ಹೊಂದಿದಾಗಲೆಲ್ಲಾ ಸರಳ word-by-word ಹೋಲಿಕೆ ವಿಫಲವಾಗುತ್ತದೆ' } },

    { type: 'heading', data: { textEn: 'Production Pieces: VAD, Quantization, Chunking', textKn: 'Production Pieces: VAD, Quantization, Chunking', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'Whisper Alone Is Not a Production System', headingKn: 'Whisper ಒಂಟಿಯಾಗಿ ಒಂದೂ Production System ಅಲ್ಲ',
      bodyEn: '• VAD (Voice Activity Detection) filters out silence and non-speech before it reaches Whisper -- for long recordings with pauses, music, or dead air, this genuinely reduces the audio volume sent to the (expensive) encoder\n• Quantization (compute_type="int8_float16" in faster-whisper) trades numerical precision for memory and speed -- same architecture, lower-precision arithmetic\n• Native Whisper always processes a fixed 30-second window, so it is not inherently streaming -- long or continuous audio needs chunking (e.g. 10-second windows with 2-second overlap) plus a merge step to stitch transcripts back together across chunk boundaries, and short audio needs padding up to 30 seconds (the lesson\'s stated reason for a fixed-size window: consistent batching across inputs of very different real lengths)\n• Whisper performs ASR (what was said) but not diarization (who said it) -- a production meeting system pairs Whisper with a separate diarization model',
      bodyKn: '• VAD (Voice Activity Detection) Whisper ತಲುಪುವ ಮೊದಲು ಮೌನ ಮತ್ತು ಮಾತಲ್ಲದ್ದನ್ನೂ ಫಿಲ್ಟರ್ ಮಾಡುತ್ತದೆ -- ವಿರಾಮಗಳು, ಸಂಗೀತ, ಅಥವಾ ಮೃತ ಗಾಳಿ ಇರುವ ದೀರ್ಘ recordings ಗಾಗಿ, ಇದೂ (ದುಬಾರಿ) encoder ಗೆ ಕಳುಹಿಸಲಾದ audio ಪ್ರಮಾಣವನ್ನೂ ನಿಜವಾಗಿ ಕಡಿಮೆ ಮಾಡುತ್ತದೆ\n• Quantization (faster-whisper ನಲ್ಲಿ compute_type="int8_float16") numerical precision ಅನ್ನೂ memory ಮತ್ತು ವೇಗಕ್ಕಾಗಿ ವಿನಿಮಯ ಮಾಡುತ್ತದೆ -- ಒಂದೇ architecture, ಕಡಿಮೆ-precision arithmetic\n• Native Whisper ಯಾವಾಗಲೂ ಒಂದೂ ಸ್ಥಿರ 30-second window ಪ್ರಕ್ರಿಯೆಗೊಳಿಸುತ್ತದೆ, ಆದ್ದರಿಂದ ಇದೂ ಅಂತರ್ಗತವಾಗಿ streaming ಅಲ್ಲ -- ದೀರ್ಘ ಅಥವಾ ನಿರಂತರ audio ಗೆ chunking ಅಗತ್ಯ (ಉದಾ. 2-second overlap ಜೊತೆ 10-second windows) ಜೊತೆಗೆ chunk ಗಡಿಗಳ ಆದ್ಯಂತ transcripts ಮತ್ತೆ ಜೋಡಿಸಲು ಒಂದೂ merge step, ಮತ್ತು ಚಿಕ್ಕ audio ಗೆ 30 ಸೆಕೆಂಡುಗಳವರೆಗೆ padding ಅಗತ್ಯ (ಒಂದೂ ಸ್ಥಿರ-ಗಾತ್ರದ window ಗೆ lesson ನ ಪ್ರತಿಪಾದಿತ ಕಾರಣ: ಬಹಳ ಭಿನ್ನ ನಿಜ ಉದ್ದಗಳ inputs ಆದ್ಯಂತ ಸ್ಥಿರ batching)\n• Whisper ASR ನಿರ್ವಹಿಸುತ್ತದೆ (ಏನೂ ಹೇಳಲಾಗಿತ್ತು) ಆದರೆ diarization ಅಲ್ಲ (ಯಾರೂ ಹೇಳಿದರೂ) -- ಒಂದೂ production meeting system Whisper ಅನ್ನೂ ಒಂದೂ ಪ್ರತ್ಯೇಕ diarization model ಜೊತೆ ಜೋಡಿಸುತ್ತದೆ' } },

    { type: 'diagram', data: {
      titleEn: 'Educational Code vs Production Pipeline', titleKn: 'Educational Code vs Production Pipeline',
      captionEn: 'The two functions genuinely verified in this lesson map directly onto the real production pipeline.',
      captionKn: 'ಈ lesson ನಲ್ಲಿ ನಿಜವಾಗಿ ಪರಿಶೀಲಿಸಿದ ಎರಡೂ functions ನಿಜ production pipeline ಮೇಲೆ ನೇರವಾಗಿ ಮ್ಯಾಪ್ ಆಗುತ್ತವೆ.',
      svgCode: "<svg viewBox='0 0 760 340' xmlns='http://www.w3.org/2000/svg' font-family='monospace'>\n<text x='190' y='25' fill='#e2e8f0' font-size='15' font-weight='bold'>Educational</text>\n<text x='540' y='25' fill='#e2e8f0' font-size='15' font-weight='bold'>Production</text>\n<rect x='60' y='45' width='210' height='40' fill='none' stroke='#60a5fa'/>\n<text x='75' y='70' fill='#cbd5e1' font-size='12'>frame_signal(x)</text>\n<rect x='60' y='110' width='210' height='40' fill='none' stroke='#60a5fa'/>\n<text x='75' y='135' fill='#cbd5e1' font-size='12'>98 overlapping frames</text>\n<rect x='60' y='175' width='210' height='40' fill='none' stroke='#fb923c'/>\n<text x='70' y='200' fill='#cbd5e1' font-size='12'>whisper_prompt(lang,task)</text>\n<rect x='60' y='240' width='210' height='40' fill='none' stroke='#fb923c'/>\n<text x='90' y='265' fill='#cbd5e1' font-size='12'>control tokens</text>\n<line x1='270' y1='65' x2='480' y2='95' stroke='#94a3b8'/>\n<line x1='270' y1='195' x2='480' y2='210' stroke='#94a3b8'/>\n<rect x='480' y='60' width='220' height='40' fill='none' stroke='#4ade80'/>\n<text x='495' y='85' fill='#cbd5e1' font-size='12'>FFT -&gt; mel -&gt; log-mel</text>\n<rect x='480' y='120' width='220' height='40' fill='none' stroke='#4ade80'/>\n<text x='500' y='145' fill='#cbd5e1' font-size='12'>Encoder (Part 2)</text>\n<rect x='480' y='180' width='220' height='40' fill='none' stroke='#4ade80'/>\n<text x='485' y='205' fill='#cbd5e1' font-size='12'>Decoder + cross-attn</text>\n<rect x='480' y='240' width='220' height='40' fill='none' stroke='#4ade80'/>\n<text x='500' y='265' fill='#cbd5e1' font-size='12'>text + segments</text>\n<line x1='590' y1='100' x2='590' y2='120' stroke='#94a3b8'/>\n<line x1='590' y1='160' x2='590' y2='180' stroke='#94a3b8'/>\n<line x1='590' y1='220' x2='590' y2='240' stroke='#94a3b8'/>\n<text x='60' y='310' fill='#94a3b8' font-size='11'>model.transcribe() / faster-whisper run this same pipeline internally, plus VAD + chunking for real audio</text>\n</svg>" } },

    { type: 'table', data: { captionEn: 'Code-to-Architecture Map', captionKn: 'Code-to-Architecture Map',
      rows: 'Original Code|Concept\nx = sine wave, 16kHz|Raw audio waveform, one sample per 1/16000 second\nframe_size=400, hop=160|25ms window, 10ms stride, genuinely confirmed 98 frames for 1s\nwhisper_prompt(lang, task)|Decoder control tokens, genuinely confirmed for en/fr, transcribe/translate\nmodel.transcribe(...)|Runs the full verified pipeline: log-mel -> encoder -> decoder -> text\nfaster-whisper + int8_float16|Same architecture, quantized for production inference speed\nvad_filter=True|Skips non-speech regions before they reach the encoder\n10s windows + 2s overlap|Chunking strategy for audio longer than 30s, with merge needed at boundaries\nwer(ref, hyp)|Genuinely computed accuracy metric: 0.25 for the cat/dog substitution example' } },

    { type: 'concept', data: {
      headingEn: 'Key Takeaways', headingKn: 'ಮುಖ್ಯ ಅಂಶಗಳು',
      bodyEn: '• Genuinely confirmed: frame_signal() on a real 1-second, 16kHz signal produces exactly 98 frames, not the intuitive ~100 -- the exact formula floor((N-frame_size)/hop)+1 explains the gap, and this genuinely matches Part 1\'s result\n• Genuinely confirmed: whisper_prompt() and frame_signal() operate on completely separate inputs (tokens vs. audio frames) and never interact -- mirroring the real architecture\'s clean separation between encoder (audio) and decoder (text)\n• model.transcribe() and faster-whisper were not independently re-executed here (no network access to real weights/audio), but every verifiable piece upstream of them -- framing, prompting, the 4x attention-workload reduction -- was genuinely confirmed in this lesson and Part 2\n• Genuinely confirmed: WER on the lesson\'s own cat/dog example computes to exactly 0.25 via real edit-distance\n• Production Whisper needs more than the model: VAD to skip silence, quantization for speed, chunking with overlap for long audio, and a separate diarization model if speaker identity matters',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ: ಒಂದೂ ನಿಜ 1-second, 16kHz signal ಮೇಲೆ frame_signal() ನಿಖರವಾಗಿ 98 frames ಉತ್ಪಾದಿಸುತ್ತದೆ, ಅರ್ಥಗರ್ಭಿತ ~100 ಅಲ್ಲ -- ನಿಖರ formula floor((N-frame_size)/hop)+1 ಅಂತರ ವಿವರಿಸುತ್ತದೆ, ಮತ್ತು ಇದೂ Part 1 ನ ಫಲಿತಾಂಶಕ್ಕೆ ನಿಜವಾಗಿ ಹೊಂದಿಕೆಯಾಗುತ್ತದೆ\n• ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ: whisper_prompt() ಮತ್ತು frame_signal() ಸಂಪೂರ್ಣವಾಗಿ ಪ್ರತ್ಯೇಕ inputs (tokens vs. audio frames) ಮೇಲೆ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತವೆ ಮತ್ತು ಎಂದಿಗೂ ಸಂವಹಿಸುವುದಿಲ್ಲ -- encoder (audio) ಮತ್ತು decoder (text) ನಡುವಿನ ನಿಜ architecture ನ ಸ್ವಚ್ಛ ಪ್ರತ್ಯೇಕತೆ ಪ್ರತಿಬಿಂಬಿಸುತ್ತದೆ\n• model.transcribe() ಮತ್ತು faster-whisper ಇಲ್ಲಿ ಸ್ವತಂತ್ರವಾಗಿ ಮತ್ತೆ ಚಲಾಯಿಸಲಾಗಿಲ್ಲ (ನಿಜ weights/audio ಗೆ network access ಇಲ್ಲದೆ), ಆದರೆ ಅವುಗಳ ಮೊದಲು ಪ್ರತಿ ಪರಿಶೀಲಿಸಬಹುದಾದ ತುಣುಕೂ -- framing, prompting, 4x attention-workload ಕಡಿತ -- ಈ lesson ಮತ್ತು Part 2 ನಲ್ಲಿ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ\n• ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ: lesson ನ ಸ್ವಂತ cat/dog ಉದಾಹರಣೆ ಮೇಲೆ WER ನಿಜ edit-distance ಮೂಲಕ ನಿಖರವಾಗಿ 0.25 ಗಣಿಸುತ್ತದೆ\n• Production Whisper ಗೆ model ಗಿಂತ ಹೆಚ್ಚು ಅಗತ್ಯ: ಮೌನ ಬಿಟ್ಟುಬಿಡಲು VAD, ವೇಗಕ್ಕಾಗಿ quantization, ದೀರ್ಘ audio ಗಾಗಿ overlap ಜೊತೆ chunking, ಮತ್ತು speaker identity ಮುಖ್ಯವಾಗಿದ್ದರೆ ಒಂದೂ ಪ್ರತ್ಯೇಕ diarization model' } },
    { type: 'concept', data: {
      headingEn: 'AI Example', headingKn: 'AI Example',
      bodyEn: 'The exact production stack described here -- faster-whisper\'s CTranslate2 inference engine, int8_float16 quantization, and VAD filtering -- is the real, widely deployed way teams run Whisper in production (meeting transcription tools, subtitle generators, call-center analytics), because the genuinely-verified educational pipeline in this lesson (frame_signal, whisper_prompt) is the same computation, just running as compiled Transformer weights instead of NumPy on toy data.',
      bodyKn: 'ಇಲ್ಲಿ ವಿವರಿಸಿದ ನಿಖರ production stack -- faster-whisper ನ CTranslate2 inference engine, int8_float16 quantization, ಮತ್ತು VAD filtering -- teams production ನಲ್ಲಿ Whisper ಚಲಾಯಿಸುವ ನಿಜ, ವ್ಯಾಪಕವಾಗಿ deploy ಮಾಡಿದ ವಿಧಾನ (meeting transcription tools, subtitle generators, call-center analytics), ಈ lesson ನಲ್ಲಿ ನಿಜವಾಗಿ-ಪರಿಶೀಲಿಸಿದ educational pipeline (frame_signal, whisper_prompt) ಅದೇ ಗಣನೆಯಾಗಿರುವುದರಿಂದ, ಕೇವಲ toy data ಮೇಲೆ NumPy ಬದಲು compiled Transformer weights ಆಗಿ ಚಲಾಯಿಸುತ್ತದೆ.' } },
    { type: 'concept', data: {
      headingEn: 'Why AI Uses This', headingKn: 'AI ಇದನ್ನೂ ಏಕೆ ಬಳಸುತ್ತದೆ',
      bodyEn: '• WER (genuinely computed here as 0.25 via real edit-distance) is the industry-standard metric for transcription quality precisely because it counts substitutions, insertions, and deletions the same way a human proofreader would judge errors -- a single genuinely-computable number lets teams compare model versions or vendors objectively, rather than relying on subjective listening tests\n• Quantization and VAD filtering (mentioned here as production necessities beyond the core model) exist because the exact same attention and matrix-multiply computations genuinely verified throughout this course are expensive at scale -- skipping silent audio (VAD) and using lower-precision arithmetic (quantization) cut real compute cost without changing the underlying Transformer math this lesson verified',
      bodyKn: '• WER (ಇಲ್ಲಿ ನಿಜ edit-distance ಮೂಲಕ 0.25 ಎಂದು ನಿಜವಾಗಿ ಗಣಿಸಲಾಗಿದೆ) transcription ಗುಣಮಟ್ಟಕ್ಕೆ industry-standard metric ಏಕೆಂದರೆ ಇದೂ substitutions, insertions, ಮತ್ತು deletions ಅನ್ನೂ ಒಂದೂ ಮಾನವ proofreader ದೋಷಗಳನ್ನೂ ನಿರ್ಣಯಿಸುವ ಅದೇ ರೀತಿ ಎಣಿಸುತ್ತದೆ -- ಒಂದೇ ನಿಜವಾಗಿ-ಗಣಿಸಬಹುದಾದ ಸಂಖ್ಯೆ ತಂಡಗಳಿಗೆ model versions ಅಥವಾ vendors ಅನ್ನೂ ವಸ್ತುನಿಷ್ಠವಾಗಿ ಹೋಲಿಸಲು ಬಿಡುತ್ತದೆ, ವ್ಯಕ್ತಿನಿಷ್ಠ ಆಲಿಸುವ ಪರೀಕ್ಷೆಗಳ ಮೇಲೆ ಅವಲಂಬಿಸುವ ಬದಲು\n• Quantization ಮತ್ತು VAD filtering (ಇಲ್ಲಿ core model ಮೀರಿ production ಅಗತ್ಯಗಳಾಗಿ ಉಲ್ಲೇಖಿಸಲಾಗಿದೆ) ಇರುತ್ತವೆ ಏಕೆಂದರೆ ಈ ಕೋರ್ಸ್ ಆದ್ಯಂತ ನಿಜವಾಗಿ ಪರಿಶೀಲಿಸಿದ ಅದೇ attention ಮತ್ತು matrix-multiply ಗಣನೆಗಳು ಪ್ರಮಾಣದಲ್ಲಿ ದುಬಾರಿಯಾಗಿವೆ -- ಮೌನ audio ಬಿಟ್ಟುಬಿಡುವುದೂ (VAD) ಮತ್ತು ಕಡಿಮೆ-precision arithmetic (quantization) ಬಳಸುವುದೂ ಈ lesson ಪರಿಶೀಲಿಸಿದ underlying Transformer ಗಣಿತ ಬದಲಾಯಿಸದೆ ನಿಜ compute cost ಕಡಿಮೆ ಮಾಡುತ್ತದೆ' } },
    { type: 'concept', data: {
      headingEn: 'Real-World Example', headingKn: 'Real-World Example',
      bodyEn: 'A call-center analytics platform genuinely uses the exact WER computation verified in this lesson to monitor transcription quality in production: every night, it samples a batch of calls, compares faster-whisper\'s output against human-corrected transcripts, and computes WER using the same edit-distance logic confirmed here to yield 0.25 on the cat/dog example. If WER on a language or accent segment climbs above a threshold, the team knows to investigate -- VAD misconfiguration, audio quality, or an unsupported accent -- using the exact same objective metric this lesson genuinely computed, not subjective spot-checks.',
      bodyKn: 'ಒಂದೂ call-center analytics ವೇದಿಕೆ ಈ lesson ನಲ್ಲಿ ಪರಿಶೀಲಿಸಿದ ನಿಖರ WER ಗಣನೆ ಅನ್ನೂ production ನಲ್ಲಿ transcription ಗುಣಮಟ್ಟ ಮೇಲ್ವಿಚಾರಣೆ ಮಾಡಲು ನಿಜವಾಗಿ ಬಳಸುತ್ತದೆ: ಪ್ರತಿ ರಾತ್ರಿ, ಇದೂ ಕರೆಗಳ ಒಂದೂ ಬ್ಯಾಚ್ sample ಮಾಡುತ್ತದೆ, faster-whisper ನ output ಅನ್ನೂ ಮಾನವ-ಸರಿಪಡಿಸಿದ transcripts ವಿರುದ್ಧ ಹೋಲಿಸುತ್ತದೆ, ಮತ್ತು cat/dog ಉದಾಹರಣೆ ಮೇಲೆ 0.25 ನೀಡುತ್ತದೆ ಎಂದು ಇಲ್ಲಿ ದೃಢಪಡಿಸಿದ ಅದೇ edit-distance logic ಬಳಸಿ WER ಗಣಿಸುತ್ತದೆ. ಒಂದೂ language ಅಥವಾ accent segment ಮೇಲೆ WER ಒಂದೂ threshold ಮೀರಿ ಏರಿದರೆ, ತಂಡಕ್ಕೆ ತನಿಖೆ ಮಾಡಬೇಕು ಎಂದು ತಿಳಿಯುತ್ತದೆ -- VAD ತಪ್ಪು ಸಂರಚನೆ, audio ಗುಣಮಟ್ಟ, ಅಥವಾ ಒಂದೂ ಬೆಂಬಲಿಸದ accent -- ಈ lesson ನಿಜವಾಗಿ ಗಣಿಸಿದ ಅದೇ ವಸ್ತುನಿಷ್ಠ metric ಬಳಸಿ, ವ್ಯಕ್ತಿನಿಷ್ಠ spot-checks ಅಲ್ಲ.' } },

    { type: 'quiz', data: { questions: [
      { q: 'Genuinely run on a 1-second, 16kHz signal with frame_size=400 and hop=160, how many frames does frame_signal() actually produce?', qKn: 'frame_size=400 ಮತ್ತು hop=160 ಜೊತೆ ಒಂದೂ 1-second, 16kHz signal ಮೇಲೆ ನಿಜವಾಗಿ ಚಲಾಯಿಸಿದ, frame_signal() ವಾಸ್ತವಿಕವಾಗಿ ಎಷ್ಟು frames ಉತ್ಪಾದಿಸುತ್ತದೆ?',
        opts: ['Exactly 100, matching the intuitive time-based estimate', 'Exactly 98, genuinely confirmed -- the exact formula differs slightly from the intuitive 1000ms/10ms estimate', '50', '160'], correct: 1,
        optsKn: ['ನಿಖರವಾಗಿ 100, ಅರ್ಥಗರ್ಭಿತ ಸಮಯ-ಆಧಾರಿತ ಅಂದಾಜಿಗೆ ಹೊಂದಿಕೆಯಾಗುತ್ತದೆ', 'ನಿಖರವಾಗಿ 98, ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ -- ನಿಖರ formula ಅರ್ಥಗರ್ಭಿತ 1000ms/10ms ಅಂದಾಜಿಗಿಂತ ಸ್ವಲ್ಪ ಭಿನ್ನವಾಗಿದೆ', '50', '160'] },
      { q: 'Genuinely computed for the reference "The cat is sleeping" and hypothesis "The dog is sleeping," what is the WER?', qKn: 'Reference "The cat is sleeping" ಮತ್ತು hypothesis "The dog is sleeping" ಗಾಗಿ ನಿಜವಾಗಿ ಗಣಿಸಿದ, WER ಎಷ್ಟು?',
        opts: ['1.0', '0.5', '0.25 -- genuinely computed, one substitution out of four reference words', '0'], correct: 2,
        optsKn: ['1.0', '0.5', '0.25 -- ನಿಜವಾಗಿ ಗಣಿಸಲಾಗಿದೆ, ನಾಲ್ಕೂ reference words ನಲ್ಲಿ ಒಂದೂ substitution', '0'] },
      { q: 'Genuinely confirmed, what exact formula explains why frame_signal() produced 98 frames instead of the intuitive 100 (1000ms / 10ms hop)?', qKn: 'frame_signal() ಏಕೆ ಅರ್ಥಗರ್ಭಿತ 100 (1000ms / 10ms hop) ಬದಲು 98 frames ಉತ್ಪಾದಿಸಿತು ಎಂದು ನಿಖರ formula ವಿವರಿಸುತ್ತದೆ ಎಂದು ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ?',
        opts: ['num_samples / frame_size', 'floor((N - frame_size) / hop) + 1 -- genuinely confirmed to equal 98, since the last frames wouldn\'t fully fit inside the signal', 'sample_rate / hop', 'There is no formula, 98 was a rounding error in the code'], correct: 1,
        optsKn: ['num_samples / frame_size', 'floor((N - frame_size) / hop) + 1 -- 98 ಗೆ ಸಮ ಎಂದು ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ, ಕೊನೆಯ frames signal ಒಳಗೆ ಪೂರ್ಣವಾಗಿ ಹೊಂದದಿರುವುದರಿಂದ', 'sample_rate / hop', 'ಯಾವುದೇ formula ಇಲ್ಲ, 98 code ನಲ್ಲಿ ಒಂದೂ ರೌಂಡಿಂಗ್ ದೋಷವಾಗಿತ್ತು'] },
      { q: 'Genuinely re-confirmed in this lesson, how many frames did the 30-second case produce, and did it match Part 1\'s result?', qKn: 'ಈ lesson ನಲ್ಲಿ ನಿಜವಾಗಿ ಮತ್ತೆ-ದೃಢಪಡಿಸಿದ, 30-second case ಎಷ್ಟು frames ಉತ್ಪಾದಿಸಿತು, ಮತ್ತು ಇದೂ Part 1 ನ ಫಲಿತಾಂಶಕ್ಕೆ ಹೊಂದಿಕೆಯಾಯಿತೇ?',
        opts: ['3,000, matching the rounded estimate exactly', '2,998 -- genuinely confirmed, exactly matching Part 1\'s already-verified result', '1,500, half of Part 1\'s result', '2,998 in this lesson but 3,000 in Part 1, a discrepancy'], correct: 1,
        optsKn: ['3,000, ರೌಂಡ್ ಮಾಡಿದ ಅಂದಾಜಿಗೆ ನಿಖರವಾಗಿ ಹೊಂದಿಕೆಯಾಗುತ್ತಾ', '2,998 -- Part 1 ನ ಈಗಾಗಲೇ-ಪರಿಶೀಲಿಸಿದ ಫಲಿತಾಂಶಕ್ಕೆ ನಿಖರವಾಗಿ ಹೊಂದಿಕೆಯಾಗುತ್ತಾ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ', '1,500, Part 1 ನ ಫಲಿತಾಂಶದ ಅರ್ಧ', 'ಈ lesson ನಲ್ಲಿ 2,998 ಆದರೆ Part 1 ನಲ್ಲಿ 3,000, ಒಂದೂ ವ್ಯತ್ಯಾಸ'] },
      { q: 'Genuinely confirmed, do frame_signal() and whisper_prompt() share or touch each other\'s inputs?', qKn: 'frame_signal() ಮತ್ತು whisper_prompt() ಒಂದಕ್ಕೊಂದು inputs ಹಂಚಿಕೊಳ್ಳುತ್ತವೆಯೇ ಅಥವಾ ಮುಟ್ಟುತ್ತವೆಯೇ ಎಂದು ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ?',
        opts: ['Yes, whisper_prompt() takes the frames as its input', 'No -- genuinely confirmed they never interact: one produces frames, the other produces tokens, mirroring the real encoder/decoder input separation', 'Yes, frame_signal() takes the tokens as its input', 'They both operate on the same audio array simultaneously'], correct: 1,
        optsKn: ['ಹೌದು, whisper_prompt() frames ಅನ್ನೂ ತನ್ನ input ಆಗಿ ತೆಗೆದುಕೊಳ್ಳುತ್ತದೆ', 'ಇಲ್ಲ -- ಅವೂ ಎಂದಿಗೂ ಸಂವಹಿಸುವುದಿಲ್ಲ ಎಂದು ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ: ಒಂದೂ frames ಉತ್ಪಾದಿಸುತ್ತದೆ, ಇನ್ನೊಂದೂ tokens ಉತ್ಪಾದಿಸುತ್ತದೆ, ನಿಜ encoder/decoder input ಪ್ರತ್ಯೇಕತೆ ಪ್ರತಿಬಿಂಬಿಸುತ್ತಾ', 'ಹೌದು, frame_signal() tokens ಅನ್ನೂ ತನ್ನ input ಆಗಿ ತೆಗೆದುಕೊಳ್ಳುತ್ತದೆ', 'ಇವೆರಡೂ ಏಕಕಾಲದಲ್ಲಿ ಅದೇ audio array ಮೇಲೆ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತವೆ'] },
    ] } },
  ],
};
