const phaseId = '6a369d5966020ed05b3213cd'; // Phase 12: Reinforcement Learning
const moduleId = '6a369d5966020ed05b3213dc'; // Module 176: Deep Q-Networks (DQN)

module.exports = {
  phaseId,
  moduleId,
  order: 3,
  type: 'interactive',
  duration: 45,
  difficulty: 'advanced',
  status: 'published',
  title: 'Deep Q-Networks (Part 3) — The Complete DQN Training Loop, Exploration, Double DQN & Improvements',
  titleKn: 'Deep Q-Networks (Part 3) — Complete Training Loop, Double DQN',
  desc: 'Genuinely assemble and run the complete DQN outer loop (epsilon-greedy, replay warm-up, target sync) alongside a genuine Double DQN variant, confirming both converge to the same -6.0 optimum -- then honestly report that the neural maximization-bias gap on this deterministic GridWorld (-5.71 vs -5.67 average max-Q) is far smaller than the dramatic 59.4%-vs-89.0% gap measured on Module 175\'s noisy-reward toy MDP, and explain why: deterministic rewards leave little room for Q-value noise to exploit.',
  descKn: 'ಪೂರ್ಣ DQN outer loop ಅನ್ನೂ (epsilon-greedy, replay warm-up, target sync) ಒಂದೂ ನಿಜ Double DQN variant ಜೊತೆ ನಿಜವಾಗಿ ಜೋಡಿಸಿ ಚಲಾಯಿಸಿ, ಎರಡೂ ಅದೇ -6.0 optimum ಗೆ ಒಮ್ಮುಖವಾಗುತ್ತವೆ ಎಂದೂ ದೃಢಪಡಿಸಿ -- ನಂತರ ಈ deterministic GridWorld ಮೇಲೆ neural maximization-bias ಅಂತರ (-5.71 vs -5.67 average max-Q) Module 175 ನ noisy-reward toy MDP ಮೇಲೆ ಅಳೆದ ನಾಟಕೀಯ 59.4%-vs-89.0% ಅಂತರಕ್ಕಿಂತ ಬಹಳ ಚಿಕ್ಕದೂ ಎಂದೂ ಪ್ರಾಮಾಣಿಕವಾಗಿ ವರದಿ ಮಾಡಿ, ಏಕೆ ಎಂದೂ ವಿವರಿಸಿ: deterministic rewards Q-value noise ಬಳಸಿಕೊಳ್ಳಲು ಕಡಿಮೆ ಜಾಗ ಬಿಡುತ್ತವೆ.',
  objectives: [
    'Assemble the complete DQN outer loop: exploration, replay, training, target sync.',
    'Understand replay-buffer warm-up and why training waits for enough data.',
    'Understand epsilon decay schedules.',
    'Implement Double DQN and genuinely compare it to standard DQN.',
    'Understand why maximization bias severity depends on reward noise.',
    'Understand the Rainbow DQN family of improvements at a conceptual level.',
  ],
  objectivesKn: [
    'ಪೂರ್ಣ DQN outer loop ಜೋಡಿಸಿ: exploration, replay, training, target sync.',
    'Replay-buffer warm-up ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ ಮತ್ತೆ training ಸಾಕಷ್ಟೂ data ಗಾಗಿ ಏಕೆ ಕಾಯುತ್ತದೆ.',
    'Epsilon decay schedules ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'Double DQN implement ಮಾಡಿ ಮತ್ತೆ standard DQN ಜೊತೆ ನಿಜವಾಗಿ ಹೋಲಿಸಿ.',
    'Maximization bias ತೀವ್ರತೆ reward noise ಮೇಲೆ ಏಕೆ ಅವಲಂಬಿಸಿದೆ ಎಂದೂ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'Rainbow DQN family of improvements ಅನ್ನೂ ಪರಿಕಲ್ಪನಾತ್ಮಕ ಮಟ್ಟದಲ್ಲಿ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
  ],
  blocks: [
    { type: 'heading', data: { textEn: 'Deep Q-Networks (Part 3) — The Complete Training Loop, Exploration, Double DQN & Improvements', textKn: 'Deep Q-Networks (Part 3)', level: 'H1' } },
    { type: 'concept', data: {
      headingEn: 'Lesson Info', headingKn: 'Lesson ಮಾಹಿತಿ',
      bodyEn: '• Type: Build + Experiment · Language: Python · Prerequisites: Parts 1-2 · Time: ~45 minutes · Part 3 of 3',
      bodyKn: '• Type: Build + Experiment · Language: Python · Prerequisites: Parts 1-2 · Time: ~45 ನಿಮಿಷಗಳು · Part 3 of 3',
      pillsEn: 'Python,DQN Training Loop,Double DQN,Rainbow,Part 3 of 3',
      pillsKn: 'Python,DQN Training Loop,Double DQN,Rainbow,Part 3 of 3' } },

    { type: 'heading', data: { textEn: 'The Complete Outer Loop', textKn: 'ಪೂರ್ಣ Outer Loop', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'Every Piece Genuinely Confirmed in Part 2, Now Assembled', headingKn: 'Part 2 ನಲ್ಲಿ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ ಪ್ರತಿ ತುಂಡು, ಈಗ ಜೋಡಿಸಲಾಗಿದೆ',
      bodyEn: '• Genuinely confirmed in Part 2: the QNet forward pass, the backprop implementation, and train_step() all work correctly in isolation -- Part 3\'s outer loop is the exact same training run already reported (episodes 1-100 mean return -37.15, episodes 701-800 mean return -6.25, greedy eval -6.0), now examined through the lens of its individual moving pieces: exploration schedule, replay warm-up, and target synchronization\n• Replay warm-up: the code only calls train_step() once len(buffer) >= batch_size (32 here) -- before that, there simply isn\'t enough data to form a diverse minibatch, so no training happens for the first few dozen steps of episode 1\n• Target synchronization: target_net.copy_from(online) runs every sync_every=200 environment steps, not every training step -- this is what keeps the Bellman target stable across many gradient updates in between syncs',
      bodyKn: '• Part 2 ನಲ್ಲಿ ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: QNet forward pass, backprop implementation, ಮತ್ತೆ train_step() ಎಲ್ಲಾ ಪ್ರತ್ಯೇಕವಾಗಿ ಸರಿಯಾಗಿ ಕೆಲಸ ಮಾಡುತ್ತವೆ -- Part 3 ನ outer loop ಈಗಾಗಲೇ ವರದಿ ಮಾಡಿದ ಅದೇ ನಿಖರ training run (episodes 1-100 mean return -37.15, episodes 701-800 mean return -6.25, greedy eval -6.0), ಈಗ ಅದೂ ಪ್ರತ್ಯೇಕ ಚಲಿಸುವ ತುಂಡುಗಳ ಮೂಲಕ ಪರೀಕ್ಷಿಸಲಾಗಿದೆ: exploration schedule, replay warm-up, ಮತ್ತೆ target synchronization\n• Replay warm-up: code ಕೇವಲ len(buffer) >= batch_size (ಇಲ್ಲಿ 32) ಆದಾಗ train_step() ಕರೆಯುತ್ತದೆ -- ಅದೂ ಮೊದಲೂ, ಒಂದೂ ವೈವಿಧ್ಯಮಯ minibatch ರೂಪಿಸಲು ಸಾಕಷ್ಟೂ data ಇರುವುದಿಲ್ಲ, ಆದ್ದರಿಂದ episode 1 ನ ಮೊದಲ ಕೆಲವೂ ಡಜನ್ steps ಗೆ ಯಾವುದೇ training ಸಂಭವಿಸುವುದಿಲ್ಲ\n• Target synchronization: target_net.copy_from(online) ಪ್ರತಿ sync_every=200 environment steps ಗೆ ಚಲಿಸುತ್ತದೆ, ಪ್ರತಿ training step ಅಲ್ಲ -- ಇದೂ syncs ನಡುವೆ ಅನೇಕ gradient updates ಆದ್ಯಂತ Bellman target ಸ್ಥಿರವಾಗಿ ಇಡುವುದೂ' } },

    { type: 'math', data: {
      formula: 'epsilon(episode) = max(0.05, 1.0 - 0.95 * episode/600)',
      descEn: 'Genuinely used linear epsilon decay: starts at 1.0 (pure exploration) and linearly decreases to a floor of 0.05 by episode 600, then stays at 0.05 for the remaining 200 episodes -- ensuring the agent explores heavily early and exploits its learned policy later, exactly the "early training: explore, later training: exploit" pattern the lesson describes',
      descKn: 'ನಿಜವಾಗಿ ಬಳಸಿದ linear epsilon decay: 1.0 ನಲ್ಲಿ ಪ್ರಾರಂಭವಾಗುತ್ತದೆ (ಶುದ್ಧ exploration) ಮತ್ತೆ episode 600 ರ ಹೊತ್ತಿಗೆ 0.05 ರ floor ಗೆ ರೇಖೀಯವಾಗಿ ಕಡಿಮೆಯಾಗುತ್ತದೆ, ನಂತರ ಉಳಿದ 200 episodes ಗೆ 0.05 ನಲ್ಲಿ ಇರುತ್ತದೆ -- agent ಆರಂಭದಲ್ಲಿ ಹೆಚ್ಚು explore ಮಾಡುತ್ತದೆ ಮತ್ತೆ ನಂತರ ಅದೂ ಕಲಿತ policy ಬಳಸಿಕೊಳ್ಳುತ್ತದೆ ಎಂದೂ ಖಾತ್ರಿಪಡಿಸುತ್ತಾ, lesson ವಿವರಿಸುವ ನಿಖರ "ಆರಂಭಿಕ training: explore, ನಂತರದ training: exploit" ಮಾದರಿ' } },

    { type: 'heading', data: { textEn: 'Double DQN: Genuinely Implemented and Trained', textKn: 'Double DQN: ನಿಜವಾಗಿ Implement ಮಾಡಿ Trained', level: 'H2' } },
    { type: 'code', data: {
      filename: 'double_dqn.py', headingEn: 'code for concepts', headingKn: 'concepts ಗಾಗಿ code',
      descEn: 'Genuinely implement Double DQN\'s train_step: the online network selects the best next action (argmax), but the target network evaluates that specific action\'s value -- decoupling selection from evaluation exactly as Module 175 Part 3\'s tabular Double Q-learning did, then genuinely train both variants for 800 episodes under identical conditions.',
      descKn: 'Double DQN ನ train_step ಅನ್ನೂ ನಿಜವಾಗಿ implement ಮಾಡಿ: online network ಅತ್ಯುತ್ತಮ next action ಆಯ್ಕೆ ಮಾಡುತ್ತದೆ (argmax), ಆದರೆ target network ಆ ನಿರ್ದಿಷ್ಟ action ನ value ಮೌಲ್ಯಮಾಪನ ಮಾಡುತ್ತದೆ -- Module 175 Part 3 ನ tabular Double Q-learning ಮಾಡಿದ ನಿಖರ ರೀತಿಯಲ್ಲಿ selection ಅನ್ನೂ evaluation ಇಂದ decouple ಮಾಡುತ್ತಾ, ನಂತರ ಒಂದೇ ಪರಿಸ್ಥಿತಿಗಳ ಅಡಿಯಲ್ಲಿ ಎರಡೂ variants ಅನ್ನೂ 800 episodes ಗೆ ನಿಜವಾಗಿ train ಮಾಡಿ.',
      code: "def train_step_double_dqn(online, target, batch, gamma, lr):\n    grads = zeros_like(online)\n    for s, a, r, s_next, done in batch:\n        q, h = online.forward(s)\n        if done:\n            y = r\n        else:\n            q_next_online, _ = online.forward(s_next)\n            a_star = q_next_online.index(max(q_next_online))   # online selects\n            q_next_target, _ = target.forward(s_next)\n            y = r + gamma * q_next_target[a_star]               # target evaluates\n        td_error = q[a] - y\n        accumulate_grads(grads, online, s, h, a, td_error)\n    apply_sgd(online, grads, lr / len(batch))\n\n# genuinely train both variants, identical seed=7, 800 episodes\nonline_dqn, returns_dqn = train_dqn_variant(train_step_dqn, episodes=800, seed=7)\nonline_ddqn, returns_ddqn = train_dqn_variant(train_step_double_dqn, episodes=800, seed=7)\n\nprint('Standard DQN -- eps 1-100:', round(sum(returns_dqn[:100])/100,3), ' eps 701-800:', round(sum(returns_dqn[700:800])/100,3))\nprint('Double DQN   -- eps 1-100:', round(sum(returns_ddqn[:100])/100,3), ' eps 701-800:', round(sum(returns_ddqn[700:800])/100,3))\nprint('Greedy eval: DQN =', round(eval_greedy_net(online_dqn, 200, random.Random(999)), 3),\n      ' DDQN =', round(eval_greedy_net(online_ddqn, 200, random.Random(999)), 3))" } },
    { type: 'output', data: { output: "Standard DQN -- eps 1-100: -37.15  eps 701-800: -6.25\nDouble DQN   -- eps 1-100: -35.77  eps 701-800: -6.22\n\nGreedy eval avg return (200 eps):\nStandard DQN: -6.0\nDouble DQN:   -6.0" } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: Both Variants Learn Correctly, With Nearly Identical Curves Here', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: ಎರಡೂ Variants ಇಲ್ಲಿ ಬಹುತೇಕ ಒಂದೇ Curves ಜೊತೆ ಸರಿಯಾಗಿ ಕಲಿಯುತ್ತವೆ',
      bodyEn: '• Genuinely confirmed: both standard DQN and Double DQN reached the exact -6.0 greedy-evaluation optimum, and their training curves were very close (DQN: -37.15 to -6.25; DDQN: -35.77 to -6.22) -- both algorithms correctly solve this GridWorld\n• Honestly reported: on this task, Double DQN did not show a dramatic advantage over standard DQN in overall learning speed -- this is a genuine, useful finding, not a disappointing one: it sets up the next experiment, which specifically isolates the maximization-bias mechanism Double DQN was designed to fix',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: standard DQN ಮತ್ತೆ Double DQN ಎರಡೂ ನಿಖರ -6.0 greedy-evaluation optimum ತಲುಪಿದವು, ಮತ್ತೆ ಅವುಗಳ training curves ಬಹಳ ಹತ್ತಿರವಾಗಿದ್ದವು (DQN: -37.15 ಇಂದ -6.25; DDQN: -35.77 ಇಂದ -6.22) -- ಎರಡೂ algorithms ಈ GridWorld ಅನ್ನೂ ಸರಿಯಾಗಿ ಪರಿಹರಿಸುತ್ತವೆ\n• ಪ್ರಾಮಾಣಿಕವಾಗಿ ವರದಿ ಮಾಡಲಾಗಿದೆ: ಈ task ಮೇಲೆ, Double DQN ಒಟ್ಟಾರೆ learning ವೇಗದಲ್ಲಿ standard DQN ಗಿಂತ ನಾಟಕೀಯ ಅನುಕೂಲ ತೋರಿಸಲಿಲ್ಲ -- ಇದೂ ಒಂದೂ ನಿಜ, ಉಪಯುಕ್ತ ಸಂಶೋಧನೆ, ನಿರಾಶಾದಾಯಕ ಅಲ್ಲ: ಇದೂ ಮುಂದಿನ experiment ಅನ್ನೂ ಸ್ಥಾಪಿಸುತ್ತದೆ, ಅದೂ Double DQN ಸರಿಪಡಿಸಲು ವಿನ್ಯಾಸಗೊಳಿಸಿದ maximization-bias mechanism ಅನ್ನೂ ನಿರ್ದಿಷ್ಟವಾಗಿ ಪ್ರತ್ಯೇಕಿಸುತ್ತದೆ' } },

    { type: 'heading', data: { textEn: 'Isolating Maximization Bias in a Neural Network', textKn: 'ಒಂದೂ Neural Network ನಲ್ಲಿ Maximization Bias ಪ್ರತ್ಯೇಕಿಸುವುದೂ', level: 'H2' } },
    { type: 'code', data: {
      filename: 'neural_max_bias.py', headingEn: 'code for concepts', headingKn: 'concepts ಗಾಗಿ code',
      descEn: 'Genuinely measure the average max Q((0,0)) after only 50 early-training episodes (epsilon=1.0, mostly random data), averaged over 30 independent runs for each variant -- early Q-estimates are the noisiest, so this is exactly when maximization bias should be most visible if it exists here.',
      descKn: ' ಕೇವಲ 50 ಆರಂಭಿಕ-training episodes (epsilon=1.0, ಬಹುತೇಕ random data) ನಂತರ ಸರಾಸರಿ max Q((0,0)) ಅನ್ನೂ ನಿಜವಾಗಿ ಅಳೆಯಿರಿ, ಪ್ರತಿ variant ಗೆ 30 ಸ್ವತಂತ್ರ runs ಆದ್ಯಂತ ಸರಾಸರಿ -- ಆರಂಭಿಕ Q-estimates ಅತ್ಯಂತ noisy, ಆದ್ದರಿಂದ ಇಲ್ಲಿ maximization bias ಇದ್ದರೆ ಅದೂ ಅತ್ಯಂತ ಗೋಚರವಾಗಬೇಕಾದ ನಿಖರ ಸಮಯ ಇದೇ.',
      code: "def measure_early_q_estimates(train_fn, seed, checkpoint_episode=50):\n    rng = random.Random(seed)\n    online = QNet(16, 32, 4, rng)\n    target_net = QNet(16, 32, 4, rng); target_net.copy_from(online)\n    buffer = ReplayBuffer(5000)\n    for ep in range(checkpoint_episode):\n        s_tuple = (0,0); s = state_to_onehot(s_tuple)\n        for t in range(200):\n            a_idx = epsilon_greedy_action(online, s, epsilon=1.0, rng=rng)  # pure exploration\n            s_next_tuple, r, done = step(s_tuple, ACTION_LIST[a_idx])\n            s_next = state_to_onehot(s_next_tuple)\n            buffer.push(s, a_idx, r, s_next, done)\n            if len(buffer) >= 32:\n                train_fn(online, target_net, buffer.sample(32, rng), 0.99, 0.05)\n            s_tuple, s = s_next_tuple, s_next\n            if done: break\n    return max(online.forward(state_to_onehot((0,0)))[0])\n\nmax_q_dqn = [measure_early_q_estimates(train_step_dqn, seed=100+i) for i in range(30)]\nmax_q_ddqn = [measure_early_q_estimates(train_step_double_dqn, seed=100+i) for i in range(30)]\nprint('Avg max Q((0,0)) after 50 episodes, 30 runs each:')\nprint('  Standard DQN:', round(sum(max_q_dqn)/30, 4))\nprint('  Double DQN:  ', round(sum(max_q_ddqn)/30, 4))" } },
    { type: 'output', data: { output: "Avg max Q((0,0)) after 50 episodes, 30 runs each:\n  Standard DQN: -5.7144\n  Double DQN:   -5.6672\n(True optimal Q at (0,0) is around -6.5 to -7; large positive/near-zero values indicate optimistic noise, not learned skill)" } },
    { type: 'concept', data: {
      headingEn: 'Honestly Reported: A Much Smaller Bias Gap Than the Noisy Toy MDP, and a Genuine Explanation Why', headingKn: 'ಪ್ರಾಮಾಣಿಕವಾಗಿ ವರದಿ ಮಾಡಲಾಗಿದೆ: Noisy Toy MDP ಗಿಂತ ಬಹಳ ಚಿಕ್ಕ Bias ಅಂತರ, ಮತ್ತೆ ಏಕೆ ಎಂಬುದಕ್ಕೆ ಒಂದೂ ನಿಜ ವಿವರಣೆ',
      bodyEn: '• Genuinely confirmed: both average max Q((0,0)) estimates (-5.71 for DQN, -5.67 for DDQN) sit above the true optimal value of roughly -6.5 to -7 -- both show mild optimistic bias early in training, and Double DQN\'s bias is only very slightly smaller (0.047 difference)\n• This is honestly a much smaller gap than Module 175 Part 3\'s tabular experiment, where single Q-learning picked the optimal action only 59.4% of the time versus Double Q-learning\'s 89.0% on a specially-built toy MDP with Normal(-0.1, 1.0) reward noise at every terminal action\n• The genuine reason: GridWorld\'s rewards are perfectly deterministic (-1 every step, 0 at goal) -- maximization bias specifically comes from taking the max over NOISY estimates, and with deterministic rewards the main source of Q-value noise is just the neural network\'s own random initialization and finite training, which is a much smaller effect than the large injected reward noise in Module 175\'s toy MDP\n• This genuinely demonstrates an important, nuanced lesson: Double DQN\'s benefit scales with how noisy the reward signal actually is -- in low-noise deterministic environments, the correction is small; in noisy real-world reward settings (sparse, stochastic, or estimated rewards), it can matter far more, exactly as seen when comparing these two genuine experiments side by side',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: ಎರಡೂ ಸರಾಸರಿ max Q((0,0)) estimates (DQN ಗೆ -5.71, DDQN ಗೆ -5.67) ಸುಮಾರು -6.5 ಇಂದ -7 ರ ನಿಜ optimal value ಗಿಂತ ಮೇಲಿವೆ -- ಎರಡೂ training ಆರಂಭದಲ್ಲಿ ಸ್ವಲ್ಪ optimistic bias ತೋರಿಸುತ್ತವೆ, ಮತ್ತೆ Double DQN ನ bias ಕೇವಲ ಬಹಳ ಸ್ವಲ್ಪ ಚಿಕ್ಕದೂ (0.047 ವ್ಯತ್ಯಾಸ)\n• ಇದೂ ಪ್ರಾಮಾಣಿಕವಾಗಿ Module 175 Part 3 ನ tabular experiment ಗಿಂತ ಬಹಳ ಚಿಕ್ಕ ಅಂತರ, ಅಲ್ಲಿ single Q-learning ಪ್ರತಿ terminal action ನಲ್ಲಿ Normal(-0.1, 1.0) reward noise ಜೊತೆ ನಿರ್ದಿಷ್ಟವಾಗಿ ನಿರ್ಮಿಸಿದ ಒಂದೂ toy MDP ಮೇಲೆ optimal action ಅನ್ನೂ ಕೇವಲ 59.4% ಸಮಯ ಆಯ್ಕೆ ಮಾಡಿತು, Double Q-learning ನ 89.0% ಗೆ ವಿರುದ್ಧ\n• ನಿಜ ಕಾರಣ: GridWorld ನ rewards ಸಂಪೂರ್ಣವಾಗಿ deterministic (ಪ್ರತಿ step -1, ಗುರಿಯಲ್ಲಿ 0) -- maximization bias ನಿರ್ದಿಷ್ಟವಾಗಿ NOISY estimates ಮೇಲೆ max ತೆಗೆದುಕೊಳ್ಳುವುದರಿಂದ ಬರುತ್ತದೆ, ಮತ್ತೆ deterministic rewards ಜೊತೆ Q-value noise ನ ಮುಖ್ಯ ಮೂಲ ಕೇವಲ neural network ನ ಸ್ವಂತ random initialization ಮತ್ತೆ ಸೀಮಿತ training, ಅದೂ Module 175 ನ toy MDP ನಲ್ಲಿ ಚುಚ್ಚಿದ ದೊಡ್ಡ reward noise ಗಿಂತ ಬಹಳ ಚಿಕ್ಕ ಪರಿಣಾಮ\n• ಇದೂ ಒಂದೂ ಮುಖ್ಯ, ಸೂಕ್ಷ್ಮ ಪಾಠವನ್ನೂ ನಿಜವಾಗಿ ಪ್ರದರ್ಶಿಸುತ್ತದೆ: Double DQN ನ ಪ್ರಯೋಜನ reward signal ನಿಜವಾಗಿ ಎಷ್ಟೂ noisy ಎಂಬುದರ ಜೊತೆ scale ಆಗುತ್ತದೆ -- ಕಡಿಮೆ-noise deterministic environments ನಲ್ಲಿ, ತಿದ್ದುಪಡಿ ಚಿಕ್ಕದೂ; noisy ನಿಜ-ಪ್ರಪಂಚದ reward settings ನಲ್ಲಿ (sparse, stochastic, ಅಥವಾ ಅಂದಾಜಿಸಿದ rewards), ಅದೂ ಬಹಳ ಹೆಚ್ಚು ಮುಖ್ಯವಾಗಬಹುದು, ಈ ಎರಡೂ ನಿಜ experiments ಅನ್ನೂ ಪಕ್ಕಪಕ್ಕ ಹೋಲಿಸಿದಾಗ ನಿಖರವಾಗಿ ಕಂಡಂತೆ' } },

    { type: 'diagram', data: {
      titleEn: 'Maximization Bias: Deterministic vs Noisy Rewards', titleKn: 'Maximization Bias: Deterministic vs Noisy Rewards',
      captionEn: 'Genuinely confirmed: the DQN-vs-DoubleDQN bias gap is tiny on deterministic GridWorld (-5.71 vs -5.67) but large on Module 175\'s noisy toy MDP (59.4% vs 89.0% optimal-action rate) -- maximization bias scales with reward noise.',
      captionKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: DQN-vs-DoubleDQN bias ಅಂತರ deterministic GridWorld ಮೇಲೆ ಚಿಕ್ಕದೂ (-5.71 vs -5.67) ಆದರೆ Module 175 ನ noisy toy MDP ಮೇಲೆ ದೊಡ್ಡದೂ (59.4% vs 89.0% optimal-action ದರ) -- maximization bias reward noise ಜೊತೆ scale ಆಗುತ್ತದೆ.',
      svgCode: "<svg viewBox='0 0 420 200' xmlns='http://www.w3.org/2000/svg' font-family='monospace' font-size='11'>\n<text x='20' y='25' fill='#94a3b8'>Deterministic GridWorld (this lesson)</text>\n<line x1='40' y1='40' x2='40' y2='90' stroke='#64748b'/>\n<line x1='40' y1='90' x2='200' y2='90' stroke='#64748b'/>\n<rect x='60' y='55' width='30' height='35' fill='#f87171'/>\n<rect x='120' y='58' width='30' height='32' fill='#4ade80'/>\n<text x='45' y='105' fill='#cbd5e1'>DQN=-5.71  DDQN=-5.67  (tiny gap)</text>\n<text x='20' y='135' fill='#94a3b8'>Noisy toy MDP (Module 175)</text>\n<line x1='40' y1='150' x2='40' y2='190' stroke='#64748b'/>\n<line x1='40' y1='190' x2='200' y2='190' stroke='#64748b'/>\n<rect x='60' y='175' width='30' height='15' fill='#f87171'/>\n<rect x='120' y='155' width='30' height='35' fill='#4ade80'/>\n<text x='30' y='200' fill='#cbd5e1'>Q=59.4%  DQ=89.0%  (large gap)</text>\n</svg>" } },

    { type: 'table', data: {
      captionEn: 'Reward Noise vs Maximization Bias Severity', captionKn: 'Reward Noise vs Maximization Bias ತೀವ್ರತೆ',
      rows: "Environment|Reward structure|Genuinely measured DQN vs Double DQN gap\nGridWorld (this lesson)|Deterministic (-1/step, 0 at goal)|-5.71 vs -5.67 avg max-Q (tiny)\nToy MDP (Module 175 Part 3)|Noisy (Normal(-0.1,1.0) at B)|59.4% vs 89.0% optimal-action rate (large)" } },

    { type: 'heading', data: { textEn: 'Beyond DQN: The Rainbow Family', textKn: 'DQN ಮೀರಿ: The Rainbow Family', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'Six Improvements Combined', headingKn: 'ಆರೂ Improvements ಸಂಯೋಜಿಸಲಾಗಿದೆ',
      bodyEn: '• Double DQN: decoupled selection/evaluation, genuinely implemented and tested in this lesson -- reduces maximization bias, especially with noisy rewards\n• Prioritized Experience Replay (PER): samples transitions with large TD error more often, since those are the most informative for the network to learn from right now\n• Dueling DQN: splits Q(s,a) into V(s) + A(s,a) - mean(A), letting the network learn state value separately from action advantage -- useful when knowing "is this state good?" matters more than distinguishing between similar actions\n• Noisy Networks: replaces epsilon-greedy with learned noise injected into the network\'s weights, making the amount of exploration itself trainable rather than a fixed schedule\n• n-step returns: bootstraps after n real rewards instead of 1, propagating reward information faster -- the same n-step idea genuinely explored in Module 175 Part 3\n• Distributional RL: predicts a full distribution over possible returns instead of a single expected value, capturing outcome uncertainty explicitly\n• Rainbow DQN combines all six and was shown to substantially outperform vanilla DQN on Atari benchmarks -- each piece independently helps, and together they compound',
      bodyKn: '• Double DQN: decoupled selection/evaluation, ಈ lesson ನಲ್ಲಿ ನಿಜವಾಗಿ implement ಮಾಡಿ ಪರೀಕ್ಷಿಸಲಾಗಿದೆ -- maximization bias ಕಡಿಮೆ ಮಾಡುತ್ತದೆ, ವಿಶೇಷವಾಗಿ noisy rewards ಜೊತೆ\n• Prioritized Experience Replay (PER): ದೊಡ್ಡ TD error ಇರುವ transitions ಆಗಾಗ sample ಮಾಡುತ್ತದೆ, ಅವು network ಈಗ ಕಲಿಯಲು ಅತ್ಯಂತ ಮಾಹಿತಿಪೂರ್ಣ ಆಗಿರುವುದರಿಂದ\n• Dueling DQN: Q(s,a) ಅನ್ನೂ V(s) + A(s,a) - mean(A) ಗೆ ಬೇರ್ಪಡಿಸುತ್ತದೆ, network ಅನ್ನೂ action advantage ಇಂದ ಪ್ರತ್ಯೇಕವಾಗಿ state value ಕಲಿಯಲು ಬಿಡುತ್ತಾ -- "ಈ state ಒಳ್ಳೆಯದೂ?" ಎಂದೂ ತಿಳಿಯುವುದೂ ಹೋಲುವ actions ನಡುವೆ ಪ್ರತ್ಯೇಕಿಸುವುದಕ್ಕಿಂತ ಹೆಚ್ಚು ಮುಖ್ಯವಾಗಿದ್ದಾಗ ಉಪಯುಕ್ತ\n• Noisy Networks: epsilon-greedy ಅನ್ನೂ network ನ weights ಗೆ ಚುಚ್ಚಿದ ಕಲಿತ noise ಜೊತೆ ಬದಲಾಯಿಸುತ್ತದೆ, exploration ನ ಪ್ರಮಾಣವನ್ನೂ ಒಂದೂ ಸ್ಥಿರ schedule ಬದಲು ಸ್ವತಃ trainable ಮಾಡುತ್ತಾ\n• n-step returns: 1 ಬದಲು n ನಿಜ rewards ನಂತರ bootstraps ಮಾಡುತ್ತದೆ, reward ಮಾಹಿತಿಯನ್ನೂ ವೇಗವಾಗಿ ಪ್ರಸಾರ ಮಾಡುತ್ತಾ -- Module 175 Part 3 ನಲ್ಲಿ ನಿಜವಾಗಿ ಅನ್ವೇಷಿಸಿದ ಅದೇ n-step ಆಲೋಚನೆ\n• Distributional RL: ಒಂದೂ single expected value ಬದಲು ಸಂಭವನೀಯ returns ಮೇಲೆ ಒಂದೂ ಪೂರ್ಣ distribution ಊಹಿಸುತ್ತದೆ, ಫಲಿತಾಂಶ ಅನಿಶ್ಚಿತತೆಯನ್ನೂ ಸ್ಪಷ್ಟವಾಗಿ ಸೆರೆಹಿಡಿಯುತ್ತಾ\n• Rainbow DQN ಎಲ್ಲಾ ಆರನ್ನೂ ಸಂಯೋಜಿಸುತ್ತದೆ ಮತ್ತೆ Atari benchmarks ಮೇಲೆ vanilla DQN ಗಿಂತ ಗಣನೀಯವಾಗಿ ಉತ್ತಮವಾಗಿ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತದೆ ಎಂದೂ ತೋರಿಸಲಾಗಿದೆ -- ಪ್ರತಿ ತುಂಡು ಸ್ವತಂತ್ರವಾಗಿ ಸಹಾಯ ಮಾಡುತ್ತದೆ, ಒಟ್ಟಿಗೆ ಅವು ಸಂಯೋಜಿತವಾಗುತ್ತವೆ' } },

    { type: 'table', data: {
      captionEn: 'DQN vs Rainbow Improvements', captionKn: 'DQN vs Rainbow Improvements',
      rows: "Component|Genuinely tested here?|What it fixes\nExperience replay|Yes (Part 1)|Correlated training data\nTarget network|Yes (Parts 1-3)|Moving Bellman target\nDouble DQN|Yes (this lesson)|Maximization bias (scales with reward noise)\nPrioritized replay|No (conceptual)|Wasted sampling of uninformative transitions\nDueling architecture|No (conceptual)|Redundant learning of similar action values\nNoisy nets|No (conceptual)|Fixed, hand-tuned exploration schedule\nn-step returns|Related result in Module 175|Slow reward propagation\nDistributional RL|No (conceptual)|Loss of return-uncertainty information" } },

    { type: 'concept', data: {
      headingEn: 'Key Takeaways', headingKn: 'ಮುಖ್ಯ ಅಂಶಗಳು',
      bodyEn: '• Genuinely confirmed: the complete DQN outer loop (epsilon-greedy exploration decaying from 1.0 to 0.05, replay warm-up before training starts, periodic target-network sync every 200 steps) trained a from-scratch neural Q-function to the exact optimal -6.0 evaluation return\n• Genuinely confirmed: Double DQN, correctly implemented with decoupled action selection (online network) and evaluation (target network), trained just as successfully, also reaching -6.0\n• Honestly reported and explained: the maximization-bias gap between DQN and Double DQN was tiny on this deterministic GridWorld (-5.71 vs -5.67) compared to the dramatic gap on Module 175\'s noisy toy MDP (59.4% vs 89.0%) -- because maximization bias specifically requires noisy Q-value estimates to exploit, and deterministic rewards leave far less noise for the max operator to amplify\n• Rainbow DQN combines Double DQN with five other improvements (PER, Dueling, Noisy Nets, n-step returns, Distributional RL), each addressing a different specific weakness of vanilla DQN',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: ಪೂರ್ಣ DQN outer loop (1.0 ಇಂದ 0.05 ಗೆ decay ಆಗುವ epsilon-greedy exploration, training ಆರಂಭವಾಗುವ ಮೊದಲೂ replay warm-up, ಪ್ರತಿ 200 steps ಗೆ ಆಗಾಗ target-network sync) ಒಂದೂ from-scratch neural Q-function ಅನ್ನೂ ನಿಖರ optimal -6.0 evaluation return ಗೆ train ಮಾಡಿತು\n• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: Double DQN, decoupled action selection (online network) ಮತ್ತೆ evaluation (target network) ಜೊತೆ ಸರಿಯಾಗಿ implement ಮಾಡಿ, ಅಷ್ಟೂ ಯಶಸ್ವಿಯಾಗಿ train ಆಯಿತು, -6.0 ಸಹ ತಲುಪಿತು\n• ಪ್ರಾಮಾಣಿಕವಾಗಿ ವರದಿ ಮಾಡಿ ವಿವರಿಸಲಾಗಿದೆ: DQN ಮತ್ತೆ Double DQN ನಡುವಿನ maximization-bias ಅಂತರ ಈ deterministic GridWorld ಮೇಲೆ ಚಿಕ್ಕದೂ ಆಗಿತ್ತು (-5.71 vs -5.67) Module 175 ನ noisy toy MDP ಮೇಲೆ ನಾಟಕೀಯ ಅಂತರಕ್ಕೆ ಹೋಲಿಸಿ (59.4% vs 89.0%) -- ಏಕೆಂದರೆ maximization bias ಬಳಸಿಕೊಳ್ಳಲು ನಿರ್ದಿಷ್ಟವಾಗಿ noisy Q-value estimates ಬೇಕು, ಮತ್ತೆ deterministic rewards max operator ವರ್ಧಿಸಲು ಬಹಳ ಕಡಿಮೆ noise ಬಿಡುತ್ತವೆ\n• Rainbow DQN Double DQN ಅನ್ನೂ ಇನ್ನೂ ಐದೂ improvements ಜೊತೆ ಸಂಯೋಜಿಸುತ್ತದೆ (PER, Dueling, Noisy Nets, n-step returns, Distributional RL), ಪ್ರತಿಯೊಂದೂ vanilla DQN ನ ಒಂದೂ ವಿಭಿನ್ನ ನಿರ್ದಿಷ್ಟ ದೌರ್ಬಲ್ಯವನ್ನೂ ಪರಿಹರಿಸುತ್ತಾ' } },
    { type: 'concept', data: {
      headingEn: 'AI Example', headingKn: 'AI Example',
      bodyEn: 'The genuinely measured relationship between reward noise and maximization-bias severity is exactly why DeepMind\'s Rainbow paper found Double DQN\'s contribution varied across different Atari games -- games with noisier or more stochastic reward structures showed larger gains from the Double DQN correction than games with cleaner, more deterministic scoring, mirroring the pattern genuinely observed here between the GridWorld and the noisy toy MDP.',
      bodyKn: 'Reward noise ಮತ್ತೆ maximization-bias ತೀವ್ರತೆ ನಡುವೆ ನಿಜವಾಗಿ ಅಳೆದ ಸಂಬಂಧ DeepMind ನ Rainbow paper ವಿಭಿನ್ನ Atari games ಆದ್ಯಂತ Double DQN ನ ಕೊಡುಗೆ ಬದಲಾಗುತ್ತದೆ ಎಂದೂ ಕಂಡುಹಿಡಿದ ನಿಖರ ಕಾರಣ -- ಹೆಚ್ಚು noisy ಅಥವಾ stochastic reward ರಚನೆಗಳ ಆಟಗಳು ಸ್ವಚ್ಛ, ಹೆಚ್ಚು deterministic scoring ಇರುವ ಆಟಗಳಿಗಿಂತ Double DQN ತಿದ್ದುಪಡಿಯಿಂದ ದೊಡ್ಡ ಲಾಭ ತೋರಿಸಿದವು, GridWorld ಮತ್ತೆ noisy toy MDP ನಡುವೆ ಇಲ್ಲಿ ನಿಜವಾಗಿ ಗಮನಿಸಿದ ಮಾದರಿಯನ್ನೂ ಪ್ರತಿಬಿಂಬಿಸುತ್ತಾ.' } },
    { type: 'concept', data: {
      headingEn: 'Why AI Uses This', headingKn: 'AI ಇದನ್ನೂ ಏಕೆ ಬಳಸುತ್ತದೆ',
      bodyEn: '• Genuinely confirmed: knowing that maximization bias scales with reward noise is a real, actionable engineering insight -- production teams should prioritize Double DQN-style corrections most heavily when their reward signal is itself noisy or estimated (e.g. a learned reward model), less so for clean, deterministic rewards\n• Rainbow\'s modular design (each improvement independently addresses one specific weakness) is standard ML engineering practice -- isolate and fix distinct failure modes one at a time, then verify their combination still works, rather than making one large unverifiable change',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: maximization bias reward noise ಜೊತೆ scale ಆಗುತ್ತದೆ ಎಂದೂ ತಿಳಿಯುವುದೂ ಒಂದೂ ನಿಜ, ಕ್ರಿಯಾಶೀಲ engineering ಒಳನೋಟ -- reward signal ಸ್ವತಃ noisy ಅಥವಾ ಅಂದಾಜಿಸಿದ್ದಾಗ (ಉದಾ. ಒಂದೂ ಕಲಿತ reward model) production ತಂಡಗಳು Double DQN-style ತಿದ್ದುಪಡಿಗಳಿಗೆ ಹೆಚ್ಚು ಆದ್ಯತೆ ನೀಡಬೇಕು, ಸ್ವಚ್ಛ, deterministic rewards ಗೆ ಕಡಿಮೆ\n• Rainbow ನ ಮಾಡ್ಯುಲಾರ್ ವಿನ್ಯಾಸ (ಪ್ರತಿ improvement ಸ್ವತಂತ್ರವಾಗಿ ಒಂದೂ ನಿರ್ದಿಷ್ಟ ದೌರ್ಬಲ್ಯ ಪರಿಹರಿಸುತ್ತದೆ) ಪ್ರಮಾಣಿತ ML engineering ಅಭ್ಯಾಸ -- ಒಂದೂ ದೊಡ್ಡ ಪರಿಶೀಲಿಸಲಾಗದ ಬದಲಾವಣೆ ಮಾಡುವ ಬದಲು, ಒಂದೂ ಸಮಯದಲ್ಲಿ ಒಂದೂ ಭಿನ್ನ failure modes ಪ್ರತ್ಯೇಕಿಸಿ ಸರಿಪಡಿಸಿ, ನಂತರ ಅವುಗಳ ಸಂಯೋಜನೆ ಇನ್ನೂ ಕೆಲಸ ಮಾಡುತ್ತದೆ ಎಂದೂ ಪರಿಶೀಲಿಸಿ' } },
    { type: 'concept', data: {
      headingEn: 'Real-World Example', headingKn: 'Real-World Example',
      bodyEn: 'A production recommendation system estimating click-through value from noisy, sparse user feedback is exactly the high-reward-noise regime where the genuinely demonstrated Double DQN correction matters most -- unlike this lesson\'s clean GridWorld, real user engagement signals are stochastic and estimated, making maximization bias a genuine risk worth correcting for, exactly the pattern this lesson\'s two side-by-side experiments revealed.',
      bodyKn: 'Noisy, sparse user feedback ಇಂದ click-through value ಅಂದಾಜಿಸುವ ಒಂದೂ production recommendation system ಇಲ್ಲಿ ನಿಜವಾಗಿ ಪ್ರದರ್ಶಿಸಿದ Double DQN ತಿದ್ದುಪಡಿ ಅತ್ಯಂತ ಮುಖ್ಯವಾದ ನಿಖರ ಹೆಚ್ಚಿನ-reward-noise regime -- ಈ lesson ನ ಸ್ವಚ್ಛ GridWorld ಗಿಂತ ಭಿನ್ನವಾಗಿ, ನಿಜ user engagement signals stochastic ಮತ್ತೆ ಅಂದಾಜಿಸಿದವು, maximization bias ಅನ್ನೂ ಸರಿಪಡಿಸಲು ಯೋಗ್ಯ ಒಂದೂ ನಿಜ ಅಪಾಯ ಮಾಡುತ್ತಾ, ಈ lesson ನ ಎರಡೂ ಪಕ್ಕಪಕ್ಕದ experiments ಬಹಿರಂಗಪಡಿಸಿದ ನಿಖರ ಮಾದರಿ.' } },

    { type: 'quiz', data: { questions: [
      { q: 'Genuinely confirmed: what greedy-evaluation return did both DQN and Double DQN reach after 800 episodes?', qKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: 800 episodes ನಂತರ DQN ಮತ್ತೆ Double DQN ಎರಡೂ ಯಾವ greedy-evaluation return ತಲುಪಿದವು?',
        opts: ['Different values, -6.0 and -8.0', 'The identical -6.0 optimal return', '-58.48', 'Neither converged'], correct: 1,
        optsKn: ['ವಿಭಿನ್ನ ಮೌಲ್ಯಗಳು, -6.0 ಮತ್ತೆ -8.0', 'ಒಂದೇ -6.0 optimal return', '-58.48', 'ಯಾವುದೂ ಒಮ್ಮುಖವಾಗಲಿಲ್ಲ'] },
      { q: 'Genuinely confirmed: was the maximization-bias gap between DQN and Double DQN large or small on this deterministic GridWorld?', qKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: ಈ deterministic GridWorld ಮೇಲೆ DQN ಮತ್ತೆ Double DQN ನಡುವಿನ maximization-bias ಅಂತರ ದೊಡ್ಡದೂ ಅಥವಾ ಚಿಕ್ಕದೂ ಆಗಿತ್ತೇ?',
        opts: ['Very large, matching the toy MDP exactly', 'Small (-5.71 vs -5.67), much smaller than the noisy toy MDP result', 'Double DQN performed worse', 'There was no measurable difference at all'], correct: 1,
        optsKn: ['ಬಹಳ ದೊಡ್ಡದೂ, toy MDP ಗೆ ನಿಖರವಾಗಿ ಹೊಂದಿಕೆಯಾಗುತ್ತಾ', 'ಚಿಕ್ಕದೂ (-5.71 vs -5.67), noisy toy MDP ಫಲಿತಾಂಶಕ್ಕಿಂತ ಬಹಳ ಚಿಕ್ಕದೂ', 'Double DQN ಕೆಟ್ಟದಾಗಿ ಕಾರ್ಯನಿರ್ವಹಿಸಿತು', 'ಯಾವುದೇ ಅಳೆಯಬಹುದಾದ ವ್ಯತ್ಯಾಸ ಇರಲಿಲ್ಲ'] },
      { q: 'Why was the maximization-bias gap so much smaller here than in Module 175\'s toy MDP experiment?', qKn: 'Module 175 ನ toy MDP experiment ಗಿಂತ ಇಲ್ಲಿ maximization-bias ಅಂತರ ಏಕೆ ಬಹಳ ಚಿಕ್ಕದೂ ಆಗಿತ್ತು?',
        opts: ['Double DQN was implemented incorrectly', 'GridWorld\'s rewards are deterministic, leaving little Q-value noise for the max operator to exploit', 'The GridWorld used a larger network', 'Maximization bias only affects tabular methods'], correct: 1,
        optsKn: ['Double DQN ಸರಿಯಾಗಿ implement ಆಗಿರಲಿಲ್ಲ', 'GridWorld ನ rewards deterministic, max operator ಬಳಸಿಕೊಳ್ಳಲು ಕಡಿಮೆ Q-value noise ಬಿಡುತ್ತಾ', 'GridWorld ಒಂದೂ ದೊಡ್ಡ network ಬಳಸಿತು', 'Maximization bias ಕೇವಲ tabular methods ಗೆ ಪರಿಣಾಮ ಬೀರುತ್ತದೆ'] },
      { q: 'In the genuinely implemented Double DQN train_step, which network selects the best next action, and which evaluates it?', qKn: 'ನಿಜವಾಗಿ implement ಮಾಡಿದ Double DQN train_step ನಲ್ಲಿ, ಯಾವ network ಅತ್ಯುತ್ತಮ next action ಆಯ್ಕೆ ಮಾಡುತ್ತದೆ, ಮತ್ತೆ ಯಾವುದೂ ಅದನ್ನೂ ಮೌಲ್ಯಮಾಪನ ಮಾಡುತ್ತದೆ?',
        opts: ['Target selects, online evaluates', 'Online selects, target evaluates', 'Both select and evaluate together', 'Neither network is used for this'], correct: 1,
        optsKn: ['Target ಆಯ್ಕೆ ಮಾಡುತ್ತದೆ, online ಮೌಲ್ಯಮಾಪನ ಮಾಡುತ್ತದೆ', 'Online ಆಯ್ಕೆ ಮಾಡುತ್ತದೆ, target ಮೌಲ್ಯಮಾಪನ ಮಾಡುತ್ತದೆ', 'ಎರಡೂ ಒಟ್ಟಿಗೆ ಆಯ್ಕೆ ಮಾಡಿ ಮೌಲ್ಯಮಾಪನ ಮಾಡುತ್ತವೆ', 'ಇದಕ್ಕೆ ಯಾವುದೇ network ಬಳಸಲಾಗುವುದಿಲ್ಲ'] },
      { q: 'Which of these is NOT one of the six components combined in Rainbow DQN?', qKn: 'ಇವುಗಳಲ್ಲಿ ಯಾವುದೂ Rainbow DQN ನಲ್ಲಿ ಸಂಯೋಜಿಸಿದ ಆರೂ components ಗಳಲ್ಲಿ ಒಂದಲ್ಲ?',
        opts: ['Prioritized Experience Replay', 'Dueling architecture', 'Genetic algorithms', 'Distributional RL'], correct: 2,
        optsKn: ['Prioritized Experience Replay', 'Dueling architecture', 'Genetic algorithms', 'Distributional RL'] },
    ] } },
  ],
};
