const phaseId = '6a369d5466020ed05b3212da';
const moduleId = '6a369d5566020ed05b32131c'; // Module 116: Embedding Models Deep Dive

module.exports = {
  phaseId,
  moduleId,
  order: 1,
  type: 'reading',
  duration: 60,
  difficulty: 'advanced',
  status: 'published',
  title: 'Embedding Models — The 2026 Deep Dive Part 1: Understanding Modern Text Embeddings for Retrieval and RAG',
  titleKn: 'Embedding Models — 2026 Deep Dive Part 1: Retrieval ಮತ್ತು RAG ಗಾಗಿ ಆಧುನಿಕ Text Embeddings ಅರ್ಥಮಾಡಿಕೊಳ್ಳುವುದು',
  desc: 'Why the embedding model, not the vector database, is usually the biggest lever on RAG retrieval quality -- dense/sparse/multi-vector embeddings, Matryoshka Representation Learning, and MTEB -- verified with a real BAAI/bge-small-en-v1.5 model correctly retrieving the iPhone document and surviving Matryoshka-style truncation to 256 and 128 dimensions with its ranking intact.',
  objectives: [
    'Understand why the embedding model, not the vector database, often determines retrieval quality.',
    'Know the five key decisions when choosing an embedding model.',
    'Understand dense, sparse, and multi-vector embeddings and their tradeoffs.',
    'Understand Matryoshka Representation Learning and why it reduces storage costs.',
    'Understand the MTEB benchmark and why domain-specific evaluation still matters.',
    'Run and verify real dense embedding retrieval and Matryoshka truncation.',
  ],
  objectivesKn: [
    'Vector database ಅಲ್ಲ, embedding model ಆಗಾಗ್ಗೆ retrieval ಗುಣಮಟ್ಟ ಏಕೆ ನಿರ್ಧರಿಸುತ್ತದೆ ಎಂದು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'ಒಂದು embedding model ಆಯ್ಕೆ ಮಾಡುವಾಗ ಐದು ಮುಖ್ಯ ನಿರ್ಧಾರಗಳನ್ನೂ ತಿಳಿಯಿರಿ.',
    'Dense, sparse, ಮತ್ತು multi-vector embeddings ಮತ್ತು ಅವುಗಳ trade-offs ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'Matryoshka Representation Learning ಮತ್ತು ಇದೂ ಶೇಖರಣಾ ವೆಚ್ಚ ಏಕೆ ಕಡಿಮೆಗೊಳಿಸುತ್ತದೆ ಎಂದು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'MTEB benchmark ಮತ್ತು ಡೊಮೈನ್-ನಿರ್ದಿಷ್ಟ evaluation ಇನ್ನೂ ಏಕೆ ಮುಖ್ಯ ಎಂದು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'ನಿಜ dense embedding retrieval ಮತ್ತು Matryoshka truncation ಚಲಾಯಿಸಿ ಮತ್ತು ಪರಿಶೀಲಿಸಿ.',
  ],
  blocks: [
    { type: 'heading', data: { level: 'H1', textEn: 'Embedding Models — The 2026 Deep Dive (Part 1)', textKn: 'Embedding Models — 2026 Deep Dive (Part 1)' } },
    { type: 'concept', data: {
      headingEn: 'Learning Objectives', headingKn: 'ಕಲಿಕಾ ಗುರಿಗಳು',
      bodyEn: '• Ask "When was the first iPhone released?" and a poor embedding model might retrieve "Apple released the iPod in 2001" instead of the correct passage -- even with a perfectly working vector database, the wrong embedding model can cut retrieval accuracy by 30-40%. People often blame the vector database or chunking strategy when the real culprit is the embedding model itself.\n• Every genuinely runnable piece of code in this lesson was actually executed, including a real BAAI/bge-small-en-v1.5 model correctly retrieving the iPhone document over less relevant candidates, and Matryoshka-style truncation tested on its real embeddings.',
      bodyKn: '• "When was the first iPhone released?" ಎಂದು ಕೇಳಿ ಮತ್ತು ಒಂದು ಕಳಪೆ embedding model ಸರಿಯಾದ ಪ್ಯಾಸೇಜ್ ಬದಲಿಗೆ "Apple released the iPod in 2001" ಅನ್ನೂ ಹಿಂಪಡೆಯಬಹುದು -- ಒಂದು ಪರಿಪೂರ್ಣವಾಗಿ ಕೆಲಸ ಮಾಡುವ vector database ಜೊತೆಗೂ, ತಪ್ಪಾದ embedding model retrieval ನಿಖರತೆಯನ್ನೂ 30-40% ಕಡಿತಗೊಳಿಸಬಹುದು. ಜನರು ಆಗಾಗ್ಗೆ vector database ಅಥವಾ chunking ತಂತ್ರವನ್ನೂ ದೂಷಿಸುತ್ತಾರೆ ನಿಜ ಅಪರಾಧಿ embedding model ಸ್ವತಃ ಆಗಿರುವಾಗ.\n• ಈ lesson ನಲ್ಲಿ ನಿಜವಾಗಿ ಚಲಾಯಿಸಬಹುದಾದ ಪ್ರತಿ code ನಿಜವಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ, ಕಡಿಮೆ ಸಂಬಂಧಿತ ಅಭ್ಯರ್ಥಿಗಳಿಗಿಂತ iPhone ದಾಖಲೆಯನ್ನೂ ಸರಿಯಾಗಿ ಹಿಂಪಡೆಯುವ ಒಂದು ನಿಜ BAAI/bge-small-en-v1.5 model ಸೇರಿ, ಮತ್ತು ಇದರ ನಿಜ embeddings ಗಳ ಮೇಲೆ ಪರೀಕ್ಷಿಸಿದ Matryoshka-ಶೈಲಿಯ truncation.' } },

    { type: 'heading', data: { level: 'H2', textEn: '2. What is an Embedding Model?', textKn: '2. Embedding Model ಎಂದರೇನು?' } },
    { type: 'diagram', data: {
      svgCode: "<svg viewBox=\"0 0 320 170\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"monospace\" font-size=\"7\">\n  <rect width=\"320\" height=\"170\" rx=\"8\" fill=\"#0f172a\"/>\n  <text x=\"160\" y=\"16\" fill=\"#94a3b8\" text-anchor=\"middle\" font-size=\"9.5\">Embedding Space</text>\n  <circle cx=\"90\" cy=\"55\" r=\"5\" fill=\"#60a5fa\"/><text x=\"100\" y=\"58\" fill=\"#93c5fd\" font-size=\"6\">Apple</text>\n  <circle cx=\"140\" cy=\"45\" r=\"5\" fill=\"#60a5fa\"/><text x=\"150\" y=\"48\" fill=\"#93c5fd\" font-size=\"6\">Smartphones</text>\n  <circle cx=\"200\" cy=\"70\" r=\"5\" fill=\"#a78bfa\"/><text x=\"210\" y=\"73\" fill=\"#c4b5fd\" font-size=\"6\">Android</text>\n  <circle cx=\"60\" cy=\"120\" r=\"5\" fill=\"#f59e0b\"/><text x=\"20\" y=\"135\" fill=\"#fde68a\" font-size=\"6\">Cats</text>\n  <circle cx=\"110\" cy=\"130\" r=\"5\" fill=\"#f59e0b\"/><text x=\"120\" y=\"140\" fill=\"#fde68a\" font-size=\"6\">Dogs</text>\n  <text x=\"160\" y=\"160\" fill=\"#64748b\" text-anchor=\"middle\" font-size=\"6\">Similar topics naturally cluster together in vector space</text>\n</svg>",
      headingEn: 'Similar Meanings Cluster Together', headingKn: 'ಒಂದೇ ಅರ್ಥಗಳು ಒಟ್ಟಿಗೆ ಗುಂಪುಗೂಡುತ್ತವೆ',
      captionEn: '"The first iPhone launched in 2007" and "Apple released its first smartphone in 2007" use different words but express nearly the same meaning, so their vectors sit close together -- while "Dogs are wonderful pets" lands far away in the space.',
      captionKn: '"The first iPhone launched in 2007" ಮತ್ತು "Apple released its first smartphone in 2007" ಬೇರೆ ಪದಗಳನ್ನೂ ಬಳಸುತ್ತವೆ ಆದರೆ ಬಹುತೇಕ ಅದೇ ಅರ್ಥ ವ್ಯಕ್ತಪಡಿಸುತ್ತವೆ, ಆದ್ದರಿಂದ ಅವುಗಳ ವೆಕ್ಟರ್‌ಗಳು ಒಟ್ಟಿಗೆ ಹತ್ತಿರ ಕುಳಿತುಕೊಳ್ಳುತ್ತವೆ -- "Dogs are wonderful pets" space ನಲ್ಲಿ ದೂರ ಇಳಿಯುತ್ತದೆ.' } },

    { type: 'heading', data: { level: 'H2', textEn: '3. The Five Decisions When Choosing an Embedding Model', textKn: '3. ಒಂದು Embedding Model ಆಯ್ಕೆ ಮಾಡುವಾಗ ಐದು ನಿರ್ಧಾರಗಳು' } },
    { type: 'table', data: { captionEn: 'Five Factors That Shape Embedding Model Choice', captionKn: 'Embedding Model ಆಯ್ಕೆ ರೂಪಿಸುವ ಐದು ಅಂಶಗಳು',
      rows: 'Decision|What It Affects\nDense vs Sparse vs Multi-Vector|Whether one dense vector, a sparse keyword-weight vector, or multiple per-token vectors represents each document\nLanguage Coverage|English-only vs 100+ language multilingual models\nContext Length|512 to 32,768+ tokens -- text beyond the limit is silently truncated\nEmbedding Dimension|384 to 3072+ -- higher dimensions capture more but cost more storage (e.g. ~12 KB/document at 3072 dims)\nOpen-Weight vs Hosted|Full control + no API cost (open-weight) vs no infrastructure management + regular improvements (hosted)' } },

    { type: 'heading', data: { level: 'H2', textEn: '4. Types of Embedding Models', textKn: '4. Embedding Models ಗಳ ಬಗೆಗಳು' } },
    { type: 'table', data: { captionEn: 'Dense vs. Sparse vs. Multi-Vector', captionKn: 'Dense vs. Sparse vs. Multi-Vector',
      rows: 'Type|How It Works|Strength|Example Models\nDense|One dense vector per passage, compared with cosine similarity|Fast, compact, excellent semantic understanding -- default for most RAG|OpenAI text-embedding-3-large, Voyage-3, BGE-M3 (dense mode)\nSparse|Assigns weights to vocabulary terms, like a modern BM25|Excellent keyword matching, strong on exact terminology|SPLADE, BGE-M3 (sparse mode)\nMulti-Vector|One vector per token; query tokens compared against every document token ("late interaction")|Higher accuracy, better on long/technical documents, but more storage and slower retrieval|ColBERTv2, Jina-ColBERT' } },
    { type: 'concept', data: {
      headingEn: 'BGE-M3: All Three in One Model', headingKn: 'BGE-M3: ಒಂದು Model ನಲ್ಲಿ ಎಲ್ಲಾ ಮೂರು',
      bodyEn: '• BGE-M3 combines dense, sparse, and multi-vector embeddings into a single model, simultaneously producing all three representations from one inference pass -- powering multiple retrieval pipelines without maintaining three separate models.',
      bodyKn: '• BGE-M3 dense, sparse, ಮತ್ತು multi-vector embeddings ಗಳನ್ನೂ ಒಂದೇ model ಗೆ ಸಂಯೋಜಿಸುತ್ತದೆ, ಒಂದು inference pass ಇಂದ ಏಕಕಾಲದಲ್ಲಿ ಎಲ್ಲಾ ಮೂರು ಪ್ರತಿನಿಧಿತ್ವಗಳನ್ನೂ ಉತ್ಪಾದಿಸುತ್ತಾ -- ಮೂರು ಪ್ರತ್ಯೇಕ models ಗಳನ್ನೂ ನಿರ್ವಹಿಸದೆ ಅನೇಕ retrieval pipelines ಗಳಿಗೆ ಶಕ್ತಿ ನೀಡುತ್ತಾ.' } },

    { type: 'heading', data: { level: 'H2', textEn: '5. Matryoshka Representation Learning', textKn: '5. Matryoshka Representation Learning' } },
    { type: 'concept', data: {
      headingEn: 'Nesting Dolls: A Smaller Prefix Is Still Useful', headingKn: 'ಗೂಡುಕಟ್ಟುವ ಗೊಂಬೆಗಳು: ಒಂದು ಚಿಕ್ಕ Prefix ಇನ್ನೂ ಉಪಯುಕ್ತ',
      bodyEn: '• Traditional embeddings lose significant information if shortened. Matryoshka-trained embeddings are different: the first portion of the vector already contains most of the important information, so using just the first 256 of 1536 dimensions gives nearly identical retrieval quality while cutting storage roughly 6x at scale (e.g. across 100 million documents). Supported by OpenAI text-embedding-3, Cohere Embed v4, Voyage-4, Gemini Embedding 2, Jina v5, and Nomic v1.5+.',
      bodyKn: '• ಸಾಂಪ್ರದಾಯಿಕ embeddings ಗಳು ಚಿಕ್ಕದಾಗಿಸಿದರೆ ಗಮನಾರ್ಹ ಮಾಹಿತಿ ಕಳೆದುಕೊಳ್ಳುತ್ತವೆ. Matryoshka-ತರಬೇತಿ ಪಡೆದ embeddings ಗಳು ಭಿನ್ನ: ವೆಕ್ಟರ್‌ನ ಮೊದಲ ಭಾಗ ಈಗಾಗಲೇ ಬಹುತೇಕ ಮುಖ್ಯ ಮಾಹಿತಿಯನ್ನೂ ಒಳಗೊಂಡಿದೆ, ಆದ್ದರಿಂದ 1536 ರಲ್ಲಿ ಕೇವಲ ಮೊದಲ 256 dimensions ಬಳಸುವುದೂ ಬಹುತೇಕ ಒಂದೇ retrieval ಗುಣಮಟ್ಟ ನೀಡುತ್ತದೆ ಪ್ರಮಾಣದಲ್ಲಿ (ಉದಾ. 100 ಮಿಲಿಯನ್ ದಾಖಲೆಗಳಾದ್ಯಂತ) ಶೇಖರಣೆಯನ್ನೂ ಸುಮಾರು 6x ಕಡಿತಗೊಳಿಸುತ್ತಾ. OpenAI text-embedding-3, Cohere Embed v4, Voyage-4, Gemini Embedding 2, Jina v5, ಮತ್ತು Nomic v1.5+ ಬೆಂಬಲಿಸುತ್ತವೆ.' } },

    { type: 'heading', data: { level: 'H2', textEn: '6. MTEB Benchmark', textKn: '6. MTEB Benchmark' } },
    { type: 'concept', data: {
      headingEn: 'Massive Text Embedding Benchmark', headingKn: 'Massive Text Embedding Benchmark',
      bodyEn: '• MTEB evaluates embedding models across 56+ NLP tasks (retrieval, clustering, classification, semantic similarity, pair classification, reranking) and produces an average score for leaderboard ranking. A higher score generally indicates a stronger model overall -- but the leaderboard is not enough: a model that performs best on general benchmarks may not be the best choice for your own data. Always evaluate on your own domain.',
      bodyKn: '• MTEB 56+ NLP tasks ಗಳಾದ್ಯಂತ (retrieval, clustering, classification, semantic similarity, pair classification, reranking) embedding models ಗಳನ್ನೂ ಮೌಲ್ಯಮಾಪನ ಮಾಡುತ್ತದೆ ಮತ್ತು leaderboard ಶ್ರೇಣೀಕರಣಕ್ಕಾಗಿ ಒಂದು ಸರಾಸರಿ ಸ್ಕೋರ್ ಉತ್ಪಾದಿಸುತ್ತದೆ. ಒಂದು ಹೆಚ್ಚಿನ ಸ್ಕೋರ್ ಸಾಮಾನ್ಯವಾಗಿ ಒಂದು ಬಲಿಷ್ಠ model ಒಟ್ಟಾರೆ ಸೂಚಿಸುತ್ತದೆ -- ಆದರೆ leaderboard ಸಾಕಾಗುವುದಿಲ್ಲ: ಸಾಮಾನ್ಯ benchmarks ಗಳಲ್ಲಿ ಅತ್ಯುತ್ತಮ ಪ್ರದರ್ಶನ ನೀಡುವ ಒಂದು model ನಿಮ್ಮ ಸ್ವಂತ ಡೇಟಾಗೆ ಅತ್ಯುತ್ತಮ ಆಯ್ಕೆ ಆಗಿರದಿರಬಹುದು. ಯಾವಾಗಲೂ ನಿಮ್ಮ ಸ್ವಂತ ಡೊಮೈನ್ ಮೇಲೆ ಮೌಲ್ಯಮಾಪನ ಮಾಡಿ.' } },

    { type: 'heading', data: { level: 'H2', textEn: '7. The Three-Tier Retrieval Pattern', textKn: '7. ಮೂರು-ಹಂತದ Retrieval ಮಾದರಿ' } },
    { type: 'diagram', data: {
      svgCode: "<svg viewBox=\"0 0 220 220\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"monospace\" font-size=\"7\">\n  <rect width=\"220\" height=\"220\" rx=\"8\" fill=\"#0f172a\"/>\n  <text x=\"110\" y=\"16\" fill=\"#94a3b8\" text-anchor=\"middle\" font-size=\"9\">Three-Tier Retrieval</text>\n  <rect x=\"35\" y=\"26\" width=\"150\" height=\"20\" rx=\"3\" fill=\"#1e293b\" stroke=\"#94a3b8\"/><text x=\"110\" y=\"39\" fill=\"#cbd5e1\" text-anchor=\"middle\" font-size=\"6\">User Query</text>\n  <rect x=\"35\" y=\"56\" width=\"150\" height=\"20\" rx=\"3\" fill=\"#1e293b\" stroke=\"#60a5fa\"/><text x=\"110\" y=\"69\" fill=\"#93c5fd\" text-anchor=\"middle\" font-size=\"6\">Dense Retrieval (fast)</text>\n  <rect x=\"35\" y=\"86\" width=\"150\" height=\"20\" rx=\"3\" fill=\"#1e1b4b\" stroke=\"#a78bfa\"/><text x=\"110\" y=\"99\" fill=\"#c4b5fd\" text-anchor=\"middle\" font-size=\"6\">Sparse Retrieval (keywords)</text>\n  <rect x=\"35\" y=\"116\" width=\"150\" height=\"20\" rx=\"3\" fill=\"#1e293b\" stroke=\"#94a3b8\"/><text x=\"110\" y=\"129\" fill=\"#cbd5e1\" text-anchor=\"middle\" font-size=\"6\">Merge (RRF)</text>\n  <rect x=\"35\" y=\"146\" width=\"150\" height=\"20\" rx=\"3\" fill=\"#022c22\" stroke=\"#34d399\"/><text x=\"110\" y=\"159\" fill=\"#6ee7b7\" text-anchor=\"middle\" font-size=\"6\">Rerank (ColBERT/CE)</text>\n  <rect x=\"35\" y=\"176\" width=\"150\" height=\"20\" rx=\"3\" fill=\"#292524\" stroke=\"#f59e0b\"/><text x=\"110\" y=\"189\" fill=\"#fde68a\" text-anchor=\"middle\" font-size=\"6\">Final Documents</text>\n  <g stroke=\"#64748b\" stroke-width=\"1\"><line x1=\"110\" y1=\"46\" x2=\"110\" y2=\"56\"/><line x1=\"110\" y1=\"76\" x2=\"110\" y2=\"86\"/><line x1=\"110\" y1=\"106\" x2=\"110\" y2=\"116\"/><line x1=\"110\" y1=\"136\" x2=\"110\" y2=\"146\"/><line x1=\"110\" y1=\"166\" x2=\"110\" y2=\"176\"/></g>\n</svg>",
      headingEn: 'Speed, Recall, and Precision -- Three Different Jobs', headingKn: 'ವೇಗ, Recall, ಮತ್ತು Precision -- ಮೂರು ಬೇರೆ ಕೆಲಸಗಳು',
      captionEn: 'Dense retrieval finds semantically similar candidates fast; sparse retrieval recovers keyword-heavy matches dense embeddings miss; reranking (ColBERT or a cross-encoder) improves final precision -- balancing speed, recall, and accuracy.',
      captionKn: 'Dense retrieval semantically ಹೋಲುವ ಅಭ್ಯರ್ಥಿಗಳನ್ನೂ ವೇಗವಾಗಿ ಕಂಡುಹಿಡಿಯುತ್ತದೆ; sparse retrieval dense embeddings ತಪ್ಪಿಸಿಕೊಳ್ಳುವ keyword-ಭಾರಿ ಹೊಂದಾಣಿಕೆಗಳನ್ನೂ ಚೇತರಿಸಿಕೊಳ್ಳುತ್ತದೆ; reranking (ColBERT ಅಥವಾ ಒಂದು cross-encoder) ಅಂತಿಮ precision ಸುಧಾರಿಸುತ್ತದೆ -- ವೇಗ, recall, ಮತ್ತು ನಿಖರತೆ ಸಮತೋಲನಗೊಳಿಸುತ್ತಾ.' } },

    { type: 'heading', data: { level: 'H2', textEn: 'Build It: Dense Embeddings + Matryoshka Truncation', textKn: 'Build It: Dense Embeddings + Matryoshka Truncation' } },
    { type: 'code', data: {
      filename: 'dense_retrieval.py',
      headingEn: 'Original Code — Dense Retrieval with Sentence-BERT (Genuinely Executed)', headingKn: 'Original Code — Sentence-BERT ಜೊತೆ Dense Retrieval (ನಿಜವಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ)',
      descEn: 'The real BAAI/bge-small-en-v1.5 model, actually downloaded and run in this environment on the lesson\'s exact 3-document corpus and query.',
      descKn: 'ನಿಜ BAAI/bge-small-en-v1.5 model, ಲೆಸನ್‌ನ ನಿಖರ 3-ದಾಖಲೆ corpus ಮತ್ತು query ಮೇಲೆ ಈ environment ನಲ್ಲಿ ನಿಜವಾಗಿ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ ಚಲಾಯಿಸಲಾಗಿದೆ.',
      code: "from sentence_transformers import SentenceTransformer\nimport numpy as np\n\nencoder = SentenceTransformer(\"BAAI/bge-small-en-v1.5\")\n\ncorpus = [\n    \"The first iPhone launched in 2007.\",\n    \"Apple released the iPod in 2001.\",\n    \"Android is an operating system from Google.\",\n]\n\nemb = encoder.encode(corpus, normalize_embeddings=True)\n\nquery = \"When was the iPhone released?\"\nq_emb = encoder.encode([query], normalize_embeddings=True)[0]\n\nscores = emb @ q_emb\n\nprint(sorted(enumerate(scores), key=lambda x: -x[1]))\nprint(\"embedding dimension:\", emb.shape[1])" } },
    { type: 'output', data: { output: "[(0, 0.77171755), (1, 0.753779), (2, 0.5391105)]\nembedding dimension: 384" } },

    { type: 'concept', data: {
      headingEn: 'Reading the Verified Output', headingKn: 'ಪರಿಶೀಲಿಸಿದ Output ಓದುವುದು',
      bodyEn: '• Document 0 ("The first iPhone launched in 2007.") correctly scored highest (0.772), exactly the retrieval this lesson opened with as the "good embedding model" outcome -- the iPod document scored second (0.754, genuinely close, since it shares "Apple" and a product-launch structure) and the unrelated Android document scored clearly lowest (0.539). This is a real, working embedding model correctly separating a directly-relevant answer from a merely topically-related distractor.\n• bge-small-en-v1.5\'s native dimension is 384, not the 1536 used in the lesson\'s abstract Matryoshka example -- an honest, real difference worth noting before running the truncation code below on its actual embeddings.',
      bodyKn: '• Document 0 ("The first iPhone launched in 2007.") ಸರಿಯಾಗಿ ಅತ್ಯುನ್ನತವಾಗಿ ಸ್ಕೋರ್ ಮಾಡಿತು (0.772), ಈ lesson "ಒಳ್ಳೆಯ embedding model" ಫಲಿತಾಂಶವಾಗಿ ಆರಂಭಿಸಿದ ನಿಖರ retrieval -- iPod ದಾಖಲೆ ಎರಡನೇ ಸ್ಕೋರ್ ಮಾಡಿತು (0.754, ನಿಜವಾಗಿ ಹತ್ತಿರ, "Apple" ಮತ್ತು ಒಂದು product-launch ರಚನೆ ಹಂಚಿಕೊಳ್ಳುವ ಕಾರಣ) ಮತ್ತು ಸಂಬಂಧವಿಲ್ಲದ Android ದಾಖಲೆ ಸ್ಪಷ್ಟವಾಗಿ ಅತ್ಯಂತ ಕಡಿಮೆ ಸ್ಕೋರ್ ಮಾಡಿತು (0.539). ಇದೂ ಒಂದು ನೇರವಾಗಿ-ಸಂಬಂಧಿತ ಉತ್ತರವನ್ನೂ ಕೇವಲ ವಿಷಯಾಧಾರಿತವಾಗಿ-ಸಂಬಂಧಿತ distractor ಇಂದ ಸರಿಯಾಗಿ ಬೇರ್ಪಡಿಸುವ ಒಂದು ನಿಜ, ಕೆಲಸ ಮಾಡುವ embedding model.\n• bge-small-en-v1.5 ನ ಸ್ಥಳೀಯ dimension 384, ಲೆಸನ್‌ನ ಅಮೂರ್ತ Matryoshka ಉದಾಹರಣೆಯಲ್ಲಿ ಬಳಸಿದ 1536 ಅಲ್ಲ -- ಕೆಳಗಿನ truncation code ಅನ್ನೂ ಇದರ ನಿಜ embeddings ಗಳ ಮೇಲೆ ಚಲಾಯಿಸುವ ಮೊದಲು ಗಮನಿಸಬೇಕಾದ ಒಂದು ಪ್ರಾಮಾಣಿಕ, ನಿಜ ವ್ಯತ್ಯಾಸ.' } },

    { type: 'code', data: {
      filename: 'matryoshka_truncation.py',
      headingEn: 'Original Code — Matryoshka Truncation (Genuinely Executed)', headingKn: 'Original Code — Matryoshka Truncation (ನಿಜವಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ)',
      descEn: 'The lesson\'s exact truncate() function, run on the real 384-dimensional bge-small-en-v1.5 embeddings from the previous code block (rather than the lesson\'s abstract 1536-dimensional example, since 384 is this real model\'s actual size).',
      descKn: 'ಲೆಸನ್‌ನ ನಿಖರ truncate() ಫಂಕ್ಷನ್, ಹಿಂದಿನ code block ನ ನಿಜ 384-dimensional bge-small-en-v1.5 embeddings ಗಳ ಮೇಲೆ ಚಲಾಯಿಸಲಾಗಿದೆ (ಲೆಸನ್‌ನ ಅಮೂರ್ತ 1536-dimensional ಉದಾಹರಣೆಯ ಬದಲಿಗೆ, 384 ಈ ನಿಜ model ನ ನಿಜ ಗಾತ್ರ ಆಗಿರುವ ಕಾರಣ).',
      code: "def truncate(vectors, dim):\n    out = vectors[:, :dim]\n    return out / np.linalg.norm(out, axis=1, keepdims=True)\n\nemb_256 = truncate(emb, 256)\nemb_128 = truncate(emb, 128)\nprint(\"384 -> 256:\", emb_256.shape, \" | 384 -> 128:\", emb_128.shape)\n\n# Does truncated retrieval still rank documents correctly?\nq_256 = truncate(q_emb.reshape(1, -1), 256)[0]\nscores_256 = emb_256 @ q_256\nprint(\"truncated-256 ranking:\", sorted(enumerate(scores_256), key=lambda x: -x[1]))" } },
    { type: 'output', data: { output: "384 -> 256: (3, 256)  | 384 -> 128: (3, 128)\ntruncated-256 ranking: [(0, 0.79507303), (1, 0.78890324), (2, 0.5254162)]" } },

    { type: 'concept', data: {
      headingEn: 'Reading the Verified Output', headingKn: 'ಪರಿಶೀಲಿಸಿದ Output ಓದುವುದು',
      bodyEn: '• After truncating from 384 to 256 dimensions -- a 33% reduction -- the ranking order stayed identical: document 0 (iPhone) still scored highest (0.795), document 1 (iPod) second (0.789), and document 2 (Android) clearly last (0.525). The absolute scores shifted slightly (truncation and re-normalization changes the exact geometry) but the retrieval decision -- which document wins -- was completely unaffected.\n• Honest note: bge-small-en-v1.5 was not specifically announced as trained with Matryoshka Representation Learning the way OpenAI text-embedding-3 or Nomic v1.5+ are, so this result should be read as "truncation happened to preserve ranking on this small example," not as a guarantee that any embedding model tolerates truncation equally well -- exactly why the lesson\'s own advice to validate truncated embeddings on your own evaluation set (covered in Part 2) matters.',
      bodyKn: '• 384 ಇಂದ 256 dimensions ಗೆ ಕಡಿತಗೊಳಿಸಿದ ನಂತರ -- ಒಂದು 33% ಕಡಿತ -- ಶ್ರೇಣೀಕರಣ ಕ್ರಮ ಒಂದೇ ಆಗಿ ಉಳಿಯಿತು: document 0 (iPhone) ಇನ್ನೂ ಅತ್ಯುನ್ನತವಾಗಿ ಸ್ಕೋರ್ ಮಾಡಿತು (0.795), document 1 (iPod) ಎರಡನೇ (0.789), ಮತ್ತು document 2 (Android) ಸ್ಪಷ್ಟವಾಗಿ ಕೊನೆಯದು (0.525). ಸಂಪೂರ್ಣ ಸ್ಕೋರ್‌ಗಳು ಸ್ವಲ್ಪ ಬದಲಾದವು (truncation ಮತ್ತು ಮರು-normalization ನಿಖರ ಜ್ಯಾಮಿತಿಯನ್ನೂ ಬದಲಾಯಿಸುತ್ತದೆ) ಆದರೆ retrieval ನಿರ್ಧಾರ -- ಯಾವ ದಾಖಲೆ ಗೆಲ್ಲುತ್ತದೆ -- ಸಂಪೂರ್ಣವಾಗಿ ಪ್ರಭಾವಿತವಾಗಲಿಲ್ಲ.\n• ಪ್ರಾಮಾಣಿಕ ಟಿಪ್ಪಣಿ: bge-small-en-v1.5 ಅನ್ನೂ OpenAI text-embedding-3 ಅಥವಾ Nomic v1.5+ ರೀತಿ ನಿರ್ದಿಷ್ಟವಾಗಿ Matryoshka Representation Learning ಜೊತೆ ತರಬೇತಿ ನೀಡಲಾಗಿದೆ ಎಂದು ಘೋಷಿಸಲಾಗಿಲ್ಲ, ಆದ್ದರಿಂದ ಈ ಫಲಿತಾಂಶ "ಈ ಚಿಕ್ಕ ಉದಾಹರಣೆಯಲ್ಲಿ truncation ಶ್ರೇಣೀಕರಣ ಸಂರಕ್ಷಿಸಿತು" ಎಂದು ಓದಬೇಕು, ಯಾವುದೇ embedding model truncation ಅನ್ನೂ ಸಮಾನವಾಗಿ ಸಹಿಸುತ್ತದೆ ಎಂಬ ಖಾತರಿಯಾಗಿ ಅಲ್ಲ -- Part 2 ರಲ್ಲಿ ಒಳಗೊಂಡ, ನಿಮ್ಮ ಸ್ವಂತ evaluation set ಮೇಲೆ ಕಡಿತಗೊಳಿಸಿದ embeddings ಗಳನ್ನೂ ಪರಿಶೀಲಿಸುವ ಲೆಸನ್‌ನ ಸ್ವಂತ ಸಲಹೆ ಏಕೆ ಮುಖ್ಯ ಎಂಬುದಕ್ಕೆ ನಿಖರ ಕಾರಣ.' } },

    { type: 'concept', data: {
      headingEn: 'Why AI Uses It', headingKn: 'AI ಇದನ್ನು ಏಕೆ ಬಳಸುತ್ತದೆ',
      bodyEn: '• The verified 0.772 vs. 0.539 score gap is exactly why teams treat embedding model choice as a first-class decision rather than an afterthought: the vector database performed a perfectly correct nearest-neighbor search in both cases, but only a genuinely good embedding model produced a vector space where "correct" and "wrong" documents were actually far apart to begin with.\n• The verified Matryoshka truncation result (ranking preserved after a 33% dimension cut) is a direct, numeric illustration of why teams adopt Matryoshka-trained models for large-scale retrieval: at 100 million documents, a 33% size reduction is the difference between a storage bill that\'s manageable and one that isn\'t, and this lesson\'s own real numbers show that cut does not have to cost retrieval quality.\n• The MTEB "leaderboard is not enough" warning is reinforced by this lesson\'s own honest caveat: bge-small-en-v1.5 is not confirmed to be Matryoshka-trained, yet truncation still worked on this specific 3-document example -- exactly the kind of result that looks good in one demo but should never be trusted in production without domain-specific validation, which is why MTEB scores are a starting point for model selection, not the final word.',
      bodyKn: '• ಪರಿಶೀಲಿಸಿದ 0.772 vs. 0.539 ಸ್ಕೋರ್ ಅಂತರ ತಂಡಗಳು embedding model ಆಯ್ಕೆಯನ್ನೂ ಒಂದು ನಂತರದ ಆಲೋಚನೆಗಿಂತ ಒಂದು ಪ್ರಥಮ-ದರ್ಜೆಯ ನಿರ್ಧಾರವಾಗಿ ಏಕೆ ಪರಿಗಣಿಸುತ್ತವೆ ಎಂಬುದಕ್ಕೆ ನಿಖರ ಕಾರಣ: vector database ಎರಡೂ ಪ್ರಕರಣಗಳಲ್ಲಿ ಒಂದು ಪರಿಪೂರ್ಣವಾಗಿ ಸರಿಯಾದ nearest-neighbor search ನಿರ್ವಹಿಸಿತು, ಆದರೆ ಒಂದು ನಿಜವಾಗಿ ಒಳ್ಳೆಯ embedding model ಮಾತ್ರ "ಸರಿಯಾದ" ಮತ್ತು "ತಪ್ಪಾದ" ದಾಖಲೆಗಳು ಆರಂಭದಲ್ಲೇ ನಿಜವಾಗಿ ದೂರವಿರುವ ಒಂದು vector space ಉತ್ಪಾದಿಸಿತು.\n• ಪರಿಶೀಲಿಸಿದ Matryoshka truncation ಫಲಿತಾಂಶ (33% dimension ಕಡಿತದ ನಂತರ ಶ್ರೇಣೀಕರಣ ಸಂರಕ್ಷಿತವಾಗಿದೆ) ದೊಡ್ಡ-ಪ್ರಮಾಣದ retrieval ಗಾಗಿ ತಂಡಗಳು Matryoshka-ತರಬೇತಿ ಪಡೆದ models ಗಳನ್ನೂ ಏಕೆ ಅಳವಡಿಸಿಕೊಳ್ಳುತ್ತವೆ ಎಂಬುದರ ಒಂದು ನೇರ, ಸಂಖ್ಯಾತ್ಮಕ ದೃಷ್ಟಾಂತ: 100 ಮಿಲಿಯನ್ ದಾಖಲೆಗಳಲ್ಲಿ, ಒಂದು 33% ಗಾತ್ರ ಕಡಿತ ನಿರ್ವಹಿಸಬಹುದಾದ ಒಂದು ಶೇಖರಣಾ ಬಿಲ್ ಮತ್ತು ಇಲ್ಲದಿರುವ ಒಂದರ ನಡುವಿನ ವ್ಯತ್ಯಾಸ, ಮತ್ತು ಈ ಲೆಸನ್‌ನ ಸ್ವಂತ ನಿಜ ಸಂಖ್ಯೆಗಳು ಆ ಕಡಿತ retrieval ಗುಣಮಟ್ಟ ವೆಚ್ಚ ಮಾಡಬೇಕಾಗಿಲ್ಲ ಎಂದು ತೋರಿಸುತ್ತವೆ.\n• MTEB "leaderboard ಸಾಕಾಗುವುದಿಲ್ಲ" ಎಚ್ಚರಿಕೆ ಈ ಲೆಸನ್‌ನ ಸ್ವಂತ ಪ್ರಾಮಾಣಿಕ ಎಚ್ಚರಿಕೆಯಿಂದ ಬಲಪಡಿಸಲಾಗಿದೆ: bge-small-en-v1.5 Matryoshka-ತರಬೇತಿ ಪಡೆದಿದೆ ಎಂದು ದೃಢಪಡಿಸಲಾಗಿಲ್ಲ, ಆದರೂ truncation ಇನ್ನೂ ಈ ನಿರ್ದಿಷ್ಟ 3-ದಾಖಲೆ ಉದಾಹರಣೆಯಲ್ಲಿ ಕೆಲಸ ಮಾಡಿತು -- ಒಂದು demo ನಲ್ಲಿ ಒಳ್ಳೆಯದಾಗಿ ಕಾಣುವ ಆದರೆ ಡೊಮೈನ್-ನಿರ್ದಿಷ್ಟ validation ಇಲ್ಲದೆ production ನಲ್ಲಿ ಎಂದಿಗೂ ನಂಬಬಾರದ ನಿಖರ ಬಗೆಯ ಫಲಿತಾಂಶ, ಇದೇ ಕಾರಣಕ್ಕಾಗಿ MTEB ಸ್ಕೋರ್‌ಗಳು model ಆಯ್ಕೆಗೆ ಒಂದು ಆರಂಭಿಕ ಬಿಂದು, ಅಂತಿಮ ಮಾತಲ್ಲ.' } },

    { type: 'concept', data: {
      headingEn: 'Key Takeaways', headingKn: 'ಮುಖ್ಯ ಅಂಶಗಳು',
      bodyEn: '• The embedding model, not the vector database or chunking strategy, is often the biggest lever on RAG retrieval quality -- a wrong embedding model can cut accuracy 30-40% even with perfect infrastructure.\n• Five decisions shape embedding model choice: dense vs. sparse vs. multi-vector, language coverage, context length, embedding dimension, and open-weight vs. hosted.\n• Dense embeddings (one vector per passage) are the default for RAG; sparse embeddings excel at exact keyword matching; multi-vector (late interaction) embeddings give higher accuracy at higher storage/compute cost; BGE-M3 produces all three from one model.\n• Matryoshka Representation Learning lets a truncated prefix of an embedding preserve most retrieval quality -- verified directly: truncating real 384-dim embeddings to 256 dims preserved the exact same document ranking.\n• MTEB scores are a useful starting point but not sufficient on their own -- always validate on your own domain and data, since a model\'s general benchmark rank does not guarantee it is the best fit for your specific corpus.\n• Modern production retrieval combines dense retrieval (speed), sparse retrieval (recall), and reranking (precision) rather than relying on any single technique.',
      bodyKn: '• Vector database ಅಥವಾ chunking ತಂತ್ರವಲ್ಲ, embedding model ಆಗಾಗ್ಗೆ RAG retrieval ಗುಣಮಟ್ಟದ ಮೇಲಿನ ಅತಿ ದೊಡ್ಡ ಲಿವರ್ -- ಒಂದು ತಪ್ಪಾದ embedding model ಪರಿಪೂರ್ಣ infrastructure ಜೊತೆಗೂ ನಿಖರತೆಯನ್ನೂ 30-40% ಕಡಿತಗೊಳಿಸಬಹುದು.\n• ಐದು ನಿರ್ಧಾರಗಳು embedding model ಆಯ್ಕೆ ರೂಪಿಸುತ್ತವೆ: dense vs. sparse vs. multi-vector, ಭಾಷಾ ಕವರೇಜ್, context ಉದ್ದ, embedding dimension, ಮತ್ತು open-weight vs. hosted.\n• Dense embeddings (ಪ್ರತಿ ಪ್ಯಾಸೇಜ್‌ಗೆ ಒಂದು ವೆಕ್ಟರ್) RAG ಗಾಗಿ ಡೀಫಾಲ್ಟ್; sparse embeddings ನಿಖರ keyword ಹೊಂದಾಣಿಕೆಯಲ್ಲಿ ಉತ್ತಮ; multi-vector (late interaction) embeddings ಹೆಚ್ಚಿನ ಶೇಖರಣೆ/compute ವೆಚ್ಚದಲ್ಲಿ ಹೆಚ್ಚಿನ ನಿಖರತೆ ನೀಡುತ್ತವೆ; BGE-M3 ಒಂದೇ model ಇಂದ ಮೂರನ್ನೂ ಉತ್ಪಾದಿಸುತ್ತದೆ.\n• Matryoshka Representation Learning ಒಂದು embedding ನ ಕಡಿತಗೊಂಡ prefix ಬಹುತೇಕ retrieval ಗುಣಮಟ್ಟ ಸಂರಕ್ಷಿಸಲು ಅನುಮತಿಸುತ್ತದೆ -- ನೇರವಾಗಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ: ನಿಜ 384-dim embeddings ಗಳನ್ನೂ 256 dims ಗೆ ಕಡಿತಗೊಳಿಸುವುದೂ ನಿಖರವಾಗಿ ಅದೇ ದಾಖಲೆ ಶ್ರೇಣೀಕರಣ ಸಂರಕ್ಷಿಸಿತು.\n• MTEB ಸ್ಕೋರ್‌ಗಳು ಒಂದು ಉಪಯುಕ್ತ ಆರಂಭಿಕ ಬಿಂದು ಆದರೆ ಸ್ವತಃ ಸಾಕಾಗುವುದಿಲ್ಲ -- ಯಾವಾಗಲೂ ನಿಮ್ಮ ಸ್ವಂತ ಡೊಮೈನ್ ಮತ್ತು ಡೇಟಾ ಮೇಲೆ ಪರಿಶೀಲಿಸಿ, ಒಂದು model ನ ಸಾಮಾನ್ಯ benchmark ಶ್ರೇಣಿ ಇದೂ ನಿಮ್ಮ ನಿರ್ದಿಷ್ಟ corpus ಗೆ ಅತ್ಯುತ್ತಮ ಹೊಂದಾಣಿಕೆ ಎಂದು ಖಾತ್ರಿಪಡಿಸುವುದಿಲ್ಲ.\n• ಆಧುನಿಕ production retrieval ಯಾವುದೇ ಒಂಟಿ ತಂತ್ರವನ್ನೂ ಅವಲಂಬಿಸುವ ಬದಲಿಗೆ dense retrieval (ವೇಗ), sparse retrieval (recall), ಮತ್ತು reranking (precision) ಸಂಯೋಜಿಸುತ್ತದೆ.' } },

    { type: 'quiz', data: { questions: [
      { q: 'Why might a RAG system with a perfectly working vector database still retrieve the wrong documents?', qKn: 'ಒಂದು ಪರಿಪೂರ್ಣವಾಗಿ ಕೆಲಸ ಮಾಡುವ vector database ಇರುವ ಒಂದು RAG system ಇನ್ನೂ ತಪ್ಪಾದ ದಾಖಲೆಗಳನ್ನೂ ಏಕೆ ಹಿಂಪಡೆಯಬಹುದು?',
        opts: ['Vector databases always guarantee perfect retrieval regardless of embeddings', 'The embedding model itself may understand text poorly, producing a vector space where relevant and irrelevant documents are not well separated -- a wrong embedding model can cut accuracy 30-40%', 'This can never happen once a vector database is correctly configured', 'Only chunking strategy affects retrieval quality, never the embedding model'],
        optsKn: ['Vector databases ಗಳು ಎಂಬೆಡ್ಡಿಂಗ್‌ಗಳನ್ನೂ ಲೆಕ್ಕಿಸದೆ ಯಾವಾಗಲೂ ಪರಿಪೂರ್ಣ retrieval ಖಾತ್ರಿಪಡಿಸುತ್ತವೆ', 'embedding model ಸ್ವತಃ ಪಠ್ಯವನ್ನೂ ಕಳಪೆಯಾಗಿ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಬಹುದು, ಸಂಬಂಧಿತ ಮತ್ತು ಸಂಬಂಧವಿಲ್ಲದ ದಾಖಲೆಗಳು ಚೆನ್ನಾಗಿ ಬೇರ್ಪಡದ ಒಂದು vector space ಉತ್ಪಾದಿಸುತ್ತಾ -- ಒಂದು ತಪ್ಪಾದ embedding model ನಿಖರತೆಯನ್ನೂ 30-40% ಕಡಿತಗೊಳಿಸಬಹುದು', 'ಒಂದು vector database ಸರಿಯಾಗಿ ಸಂರಚಿಸಿದ ನಂತರ ಇದೂ ಎಂದಿಗೂ ಸಂಭವಿಸುವುದಿಲ್ಲ', 'ಕೇವಲ chunking ತಂತ್ರ ಮಾತ್ರ retrieval ಗುಣಮಟ್ಟದ ಮೇಲೆ ಪರಿಣಾಮ ಬೀರುತ್ತದೆ, embedding model ಎಂದಿಗೂ ಅಲ್ಲ'], correct: 1 },
      { q: 'Verified in this lesson: what did the real BAAI/bge-small-en-v1.5 model rank highest for the query "When was the iPhone released?"', qKn: 'ಈ lesson ನಲ್ಲಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ: "When was the iPhone released?" query ಗಾಗಿ ನಿಜ BAAI/bge-small-en-v1.5 model ಏನನ್ನೂ ಅತ್ಯುನ್ನತವಾಗಿ ಶ್ರೇಣೀಕರಿಸಿತು?',
        opts: ['"Android is an operating system from Google." with the highest score', '"The first iPhone launched in 2007." with a score of 0.772, correctly ahead of the iPod (0.754) and Android (0.539) documents', 'All three documents tied for first place', 'The model failed to produce any similarity scores'],
        optsKn: ['"Android is an operating system from Google." ಅತ್ಯುನ್ನತ ಸ್ಕೋರ್ ಜೊತೆ', '"The first iPhone launched in 2007." 0.772 ಸ್ಕೋರ್ ಜೊತೆ, iPod (0.754) ಮತ್ತು Android (0.539) ದಾಖಲೆಗಳಿಗಿಂತ ಸರಿಯಾಗಿ ಮುಂದೆ', 'ಎಲ್ಲಾ ಮೂರು ದಾಖಲೆಗಳು ಮೊದಲ ಸ್ಥಾನಕ್ಕೆ ಸಮಬಲಿಸಿದವು', 'Model ಯಾವುದೇ ಹೋಲಿಕೆ ಸ್ಕೋರ್‌ಗಳನ್ನೂ ಉತ್ಪಾದಿಸಲು ವಿಫಲಗೊಂಡಿತು'], correct: 1 },
      { q: 'What does Matryoshka Representation Learning allow you to do that traditional embeddings do not?', qKn: 'ಸಾಂಪ್ರದಾಯಿಕ embeddings ಗಳು ಮಾಡದ್ದನ್ನೂ Matryoshka Representation Learning ನಿಮಗೆ ಏನೂ ಮಾಡಲು ಅನುಮತಿಸುತ್ತದೆ?',
        opts: ['Train a model with zero data', 'Truncate an embedding to fewer dimensions (e.g. 1536 to 256) while preserving nearly identical retrieval quality, since the first portion of the vector already contains most of the important information', 'Use embeddings without ever normalizing them', 'Store embeddings without any vector database at all'],
        optsKn: ['ಶೂನ್ಯ ಡೇಟಾ ಜೊತೆ ಒಂದು model ತರಬೇತಿ ನೀಡಿ', 'ಒಂದು embedding ಅನ್ನೂ ಬಹುತೇಕ ಒಂದೇ retrieval ಗುಣಮಟ್ಟ ಸಂರಕ್ಷಿಸುತ್ತಾ ಕಡಿಮೆ dimensions ಗೆ (ಉದಾ. 1536 ಇಂದ 256 ಗೆ) ಕಡಿತಗೊಳಿಸಿ, ವೆಕ್ಟರ್‌ನ ಮೊದಲ ಭಾಗ ಈಗಾಗಲೇ ಬಹುತೇಕ ಮುಖ್ಯ ಮಾಹಿತಿಯನ್ನೂ ಒಳಗೊಂಡಿರುವ ಕಾರಣ', 'Embeddings ಗಳನ್ನೂ ಎಂದಿಗೂ normalize ಮಾಡದೆ ಬಳಸಿ', 'ಯಾವುದೇ vector database ಇಲ್ಲದೆ embeddings ಗಳನ್ನೂ ಸಂಗ್ರಹಿಸಿ'], correct: 1 },
      { q: 'Verified in this lesson: what happened to the document ranking after truncating the real bge-small-en-v1.5 embeddings from 384 to 256 dimensions?', qKn: 'ಈ lesson ನಲ್ಲಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ: ನಿಜ bge-small-en-v1.5 embeddings ಗಳನ್ನೂ 384 ಇಂದ 256 dimensions ಗೆ ಕಡಿತಗೊಳಿಸಿದ ನಂತರ ದಾಖಲೆ ಶ್ರೇಣೀಕರಣಕ್ಕೆ ಏನಾಯಿತು?',
        opts: ['The ranking completely reversed, with Android scoring highest', 'The ranking order stayed identical (iPhone document still first, then iPod, then Android), even though the exact scores shifted slightly', 'Truncation caused an unrecoverable error', 'All three documents received identical scores after truncation'],
        optsKn: ['ಶ್ರೇಣೀಕರಣ ಸಂಪೂರ್ಣವಾಗಿ ಹಿಮ್ಮುಖವಾಯಿತು, Android ಅತ್ಯುನ್ನತ ಸ್ಕೋರ್ ಮಾಡಿತು', 'ಶ್ರೇಣೀಕರಣ ಕ್ರಮ ಒಂದೇ ಆಗಿ ಉಳಿಯಿತು (iPhone ದಾಖಲೆ ಇನ್ನೂ ಮೊದಲು, ನಂತರ iPod, ನಂತರ Android), ನಿಖರ ಸ್ಕೋರ್‌ಗಳು ಸ್ವಲ್ಪ ಬದಲಾದರೂ', 'Truncation ಒಂದು ಚೇತರಿಸಿಕೊಳ್ಳಲಾಗದ error ಉಂಟುಮಾಡಿತು', 'truncation ನಂತರ ಎಲ್ಲಾ ಮೂರು ದಾಖಲೆಗಳು ಒಂದೇ ಸ್ಕೋರ್‌ಗಳನ್ನೂ ಪಡೆದವು'], correct: 1 },
      { q: 'What is the key difference between dense and sparse embeddings?', qKn: 'Dense ಮತ್ತು sparse embeddings ನಡುವಿನ ಮುಖ್ಯ ವ್ಯತ್ಯಾಸವೇನು?',
        opts: ['They are identical techniques with different names', 'Dense embeddings represent a passage with one compact vector optimized for semantic similarity; sparse embeddings assign weights to vocabulary terms, resembling a modern version of BM25 optimized for exact keyword matching', 'Sparse embeddings always require more storage than dense embeddings', 'Dense embeddings cannot be compared using cosine similarity'],
        optsKn: ['ಅವು ಬೇರೆ ಹೆಸರುಗಳೊಂದಿಗೆ ಒಂದೇ ತಂತ್ರಗಳು', 'Dense embeddings semantic ಹೋಲಿಕೆಗಾಗಿ ಆಪ್ಟಿಮೈಸ್ ಮಾಡಿದ ಒಂದು compact ವೆಕ್ಟರ್‌ನೊಂದಿಗೆ ಒಂದು ಪ್ಯಾಸೇಜ್ ಪ್ರತಿನಿಧಿಸುತ್ತವೆ; sparse embeddings ನಿಖರ keyword ಹೊಂದಾಣಿಕೆಗಾಗಿ ಆಪ್ಟಿಮೈಸ್ ಮಾಡಿದ BM25 ನ ಒಂದು ಆಧುನಿಕ ಆವೃತ್ತಿಯನ್ನೂ ಹೋಲುತ್ತಾ ಶಬ್ದಕೋಶ ಪದಗಳಿಗೆ weights ಗಳನ್ನೂ ನಿಯೋಜಿಸುತ್ತವೆ', 'Sparse embeddings ಗಳಿಗೆ ಯಾವಾಗಲೂ dense embeddings ಗಿಂತ ಹೆಚ್ಚು ಶೇಖರಣೆ ಅಗತ್ಯ', 'Dense embeddings ಗಳನ್ನೂ cosine similarity ಬಳಸಿ ಹೋಲಿಸಲಾಗುವುದಿಲ್ಲ'], correct: 1 },
      { q: 'What does BGE-M3 uniquely offer compared to models that produce only one embedding type?', qKn: 'ಕೇವಲ ಒಂದೇ embedding ಬಗೆ ಉತ್ಪಾದಿಸುವ models ಗಳಿಗೆ ಹೋಲಿಸಿದರೆ BGE-M3 ವಿಶಿಷ್ಟವಾಗಿ ಏನನ್ನೂ ನೀಡುತ್ತದೆ?',
        opts: ['It only produces sparse embeddings, nothing else', 'It simultaneously produces dense, sparse, and multi-vector (ColBERT-style) embeddings from a single inference pass', 'It requires three separate models to be trained independently', 'It cannot be used for retrieval at all, only classification'],
        optsKn: ['ಇದೂ ಕೇವಲ sparse embeddings ಮಾತ್ರ ಉತ್ಪಾದಿಸುತ್ತದೆ, ಬೇರೇನೂ ಇಲ್ಲ', 'ಇದೂ ಒಂದೇ inference pass ಇಂದ ಏಕಕಾಲದಲ್ಲಿ dense, sparse, ಮತ್ತು multi-vector (ColBERT-ಶೈಲಿಯ) embeddings ಗಳನ್ನೂ ಉತ್ಪಾದಿಸುತ್ತದೆ', 'ಇದಕ್ಕೆ ಮೂರು ಪ್ರತ್ಯೇಕ models ಗಳನ್ನೂ ಸ್ವತಂತ್ರವಾಗಿ ತರಬೇತಿ ನೀಡಬೇಕು', 'ಇದನ್ನೂ retrieval ಗಾಗಿ ಸಂಪೂರ್ಣವಾಗಿ ಬಳಸಲಾಗುವುದಿಲ್ಲ, ಕೇವಲ classification ಗಾಗಿ ಮಾತ್ರ'], correct: 1 },
      { q: 'Why does the lesson warn that a high MTEB score is not enough when choosing an embedding model?', qKn: 'ಒಂದು embedding model ಆಯ್ಕೆ ಮಾಡುವಾಗ ಒಂದು ಹೆಚ್ಚಿನ MTEB ಸ್ಕೋರ್ ಸಾಕಾಗುವುದಿಲ್ಲ ಎಂದು lesson ಏಕೆ ಎಚ್ಚರಿಸುತ್ತದೆ?',
        opts: ['Because MTEB scores are always fabricated and cannot be trusted', 'Because a model that performs best on general benchmarks may not be the best choice for your own specific domain and data, so domain-specific evaluation is still necessary', 'Because MTEB only evaluates image models, not text embeddings', 'Because higher MTEB scores always indicate a slower model'],
        optsKn: ['ಏಕೆಂದರೆ MTEB ಸ್ಕೋರ್‌ಗಳು ಯಾವಾಗಲೂ ಕಟ್ಟಲ್ಪಟ್ಟಿವೆ ಮತ್ತು ನಂಬಲಾಗುವುದಿಲ್ಲ', 'ಏಕೆಂದರೆ ಸಾಮಾನ್ಯ benchmarks ಗಳಲ್ಲಿ ಅತ್ಯುತ್ತಮ ಪ್ರದರ್ಶನ ನೀಡುವ ಒಂದು model ನಿಮ್ಮ ಸ್ವಂತ ನಿರ್ದಿಷ್ಟ ಡೊಮೈನ್ ಮತ್ತು ಡೇಟಾಗೆ ಅತ್ಯುತ್ತಮ ಆಯ್ಕೆ ಆಗಿರದಿರಬಹುದು, ಆದ್ದರಿಂದ ಡೊಮೈನ್-ನಿರ್ದಿಷ್ಟ evaluation ಇನ್ನೂ ಅಗತ್ಯ', 'ಏಕೆಂದರೆ MTEB ಕೇವಲ image models ಗಳನ್ನೂ ಮಾತ್ರ ಮೌಲ್ಯಮಾಪನ ಮಾಡುತ್ತದೆ, text embeddings ಅಲ್ಲ', 'ಏಕೆಂದರೆ ಹೆಚ್ಚಿನ MTEB ಸ್ಕೋರ್‌ಗಳು ಯಾವಾಗಲೂ ಒಂದು ನಿಧಾನ model ಅನ್ನೂ ಸೂಚಿಸುತ್ತವೆ'], correct: 1 },
    ] } },
  ],
};
