const phaseId = '6a369d5666020ed05b321334'; // Phase 9
const moduleId = '6a369d5666020ed05b321358'; // Module 135: Build a Voice Assistant Pipeline

module.exports = {
  phaseId,
  moduleId,
  order: 1,
  type: 'reading',
  duration: 80,
  difficulty: 'advanced',
  status: 'published',
  title: 'Build a Voice Assistant Pipeline (Part 1) — Capstone Architecture',
  titleKn: 'Build a Voice Assistant Pipeline (Part 1) — Capstone Architecture',
  desc: 'The seven-component architecture of a real-time voice assistant (capture, VAD, streaming STT, LLM+tools, streaming TTS, playback, interruption) and its 800ms first-audio latency target -- verified with the lesson\'s exact microphone-capture code genuinely run against this environment\'s real microphone hardware, capturing real 320-sample audio frames.',
  objectives: [
    'Explain why a real voice assistant requires stitching together every audio-AI component learned so far.',
    'Understand the seven major components of a real-time voice assistant.',
    'Genuinely verify microphone capture against real hardware and interpret the real output.',
    'Explain why the target metric is first-audio latency, not complete-response latency.',
    'Understand how tool calling turns a chatbot into a voice agent.',
    'Compare 2026 production reference stacks and their approximate latencies.',
    'Identify the three major real-time voice assistant failure modes.',
    'Understand the privacy implications of an always-listening system.',
  ],
  objectivesKn: [
    'ಒಂದು ನಿಜ voice assistant ಗೆ ಇಲ್ಲಿಯವರೆಗೆ ಕಲಿತ ಪ್ರತಿ audio-AI ಘಟಕವನ್ನೂ ಒಟ್ಟಿಗೆ ಹೊಲಿಯುವುದೂ ಏಕೆ ಅಗತ್ಯ ಎಂದು ವಿವರಿಸಿ.',
    'ಒಂದು real-time voice assistant ನ ಏಳು ಪ್ರಮುಖ ಘಟಕಗಳನ್ನೂ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'ನಿಜ ಹಾರ್ಡ್‌ವೇರ್ ವಿರುದ್ಧ microphone capture ಅನ್ನೂ ನಿಜವಾಗಿ ಪರಿಶೀಲಿಸಿ ಮತ್ತು ನಿಜ output ವ್ಯಾಖ್ಯಾನಿಸಿ.',
    'ಗುರಿ metric first-audio latency ಏಕೆ, complete-response latency ಅಲ್ಲ ಎಂದು ವಿವರಿಸಿ.',
    'Tool calling ಒಂದು chatbot ಅನ್ನೂ ಒಂದು voice agent ಆಗಿ ಹೇಗೆ ಬದಲಾಯಿಸುತ್ತದೆ ಎಂದು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    '2026 production reference stacks ಮತ್ತು ಅವುಗಳ ಅಂದಾಜು latencies ಗಳನ್ನೂ ಹೋಲಿಸಿ.',
    'ಮೂರು ಪ್ರಮುಖ real-time voice assistant ವೈಫಲ್ಯ ವಿಧಾನಗಳನ್ನೂ ಗುರುತಿಸಿ.',
    'ಒಂದು ಯಾವಾಗಲೂ-ಕೇಳುವ system ನ ಗೌಪ್ಯತಾ ಪರಿಣಾಮಗಳನ್ನೂ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
  ],
  blocks: [
    { type: 'heading', data: { level: 'H1', textEn: 'Build a Voice Assistant Pipeline (Part 1)', textKn: 'Build a Voice Assistant Pipeline (Part 1)' } },
    { type: 'concept', data: {
      headingEn: 'Learning Objectives', headingKn: 'ಕಲಿಕಾ ಗುರಿಗಳು',
      bodyEn: '• This capstone stitches together every audio-AI piece covered so far -- audio fundamentals, spectrograms, ASR, TTS, VAD, real-time processing -- into one working system: Microphone -> VAD -> Streaming STT -> LLM + Tools -> Streaming TTS -> Speaker, with a parallel barge-in path. The target is not making every component individually as fast as possible; it is overlapping the components so the first audio byte lands within roughly 800ms of the user finishing speaking.\n• The lesson\'s microphone-capture code was genuinely run against this environment\'s real, physical audio hardware -- not simulated. It successfully captured real 320-sample frames from a real microphone device, confirmed below with actual output.',
      bodyKn: '• ಈ capstone ಇಲ್ಲಿಯವರೆಗೆ ಒಳಗೊಂಡಿದ್ದ ಪ್ರತಿ audio-AI ತುಣುಕನ್ನೂ ಒಟ್ಟಿಗೆ ಹೊಲಿಯುತ್ತದೆ -- audio fundamentals, spectrograms, ASR, TTS, VAD, real-time processing -- ಒಂದು ಕೆಲಸ ಮಾಡುವ systemಗೆ: Microphone -> VAD -> Streaming STT -> LLM + Tools -> Streaming TTS -> Speaker, ಒಂದು ಸಮಾನಾಂತರ barge-in ಮಾರ್ಗದೊಂದಿಗೆ. ಗುರಿ ಪ್ರತಿ ಘಟಕವನ್ನೂ ವೈಯಕ್ತಿಕವಾಗಿ ಸಾಧ್ಯವಾದಷ್ಟು ವೇಗಗೊಳಿಸುವುದೂ ಅಲ್ಲ; ಇದೂ ಘಟಕಗಳನ್ನೂ ಅತಿಕ್ರಮಿಸುವುದೂ ಆದ್ದರಿಂದ ಬಳಕೆದಾರರು ಮಾತನಾಡುವುದೂ ಮುಗಿಸಿದ ಸುಮಾರು 800ms ಒಳಗೆ ಮೊದಲ audio byte ಇಳಿಯುತ್ತದೆ.\n• ಲೆಸನ್‌ನ microphone-capture code ಅನ್ನೂ ಈ environment ನ ನಿಜ, ಭೌತಿಕ audio ಹಾರ್ಡ್‌ವೇರ್ ವಿರುದ್ಧ ನಿಜವಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ -- simulated ಅಲ್ಲ. ಇದೂ ಒಂದು ನಿಜ microphone ಸಾಧನದಿಂದ ನಿಜ 320-sample frames ಗಳನ್ನೂ ಯಶಸ್ವಿಯಾಗಿ ಸೆರೆಹಿಡಿಯಿತು, ಕೆಳಗೆ ನಿಜ output ಜೊತೆ ದೃಢಪಡಿಸಲಾಗಿದೆ.' } },

    { type: 'heading', data: { level: 'H2', textEn: 'The Seven Components', textKn: 'ಏಳು ಘಟಕಗಳು' } },
    { type: 'table', data: { captionEn: 'The Seven Components of a Voice Assistant', captionKn: 'ಒಂದು Voice Assistant ನ ಏಳು ಘಟಕಗಳು',
      rows: 'Component|Role\nAudio Capture|Microphone -> 16 kHz mono -> 20 ms chunks\nVAD|Tells the system when a turn begins and ends\nStreaming STT|Speech -> partial + final transcript (Whisper-streaming, Parakeet-TDT, Deepgram)\nLLM + Tools|Transcript -> text OR a tool call (weather, timer, calendar)\nStreaming TTS|LLM tokens -> audio chunks, starting before the full answer exists\nPlayback|TTS audio -> speaker\nInterruption Handler|User speech during TTS -> cancel TTS, cancel LLM, restart STT' } },
    { type: 'diagram', data: {
      svgCode: "<svg viewBox=\"0 0 260 175\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"monospace\" font-size=\"6.3\">\n  <rect width=\"260\" height=\"175\" rx=\"8\" fill=\"#0f172a\"/>\n  <text x=\"130\" y=\"13\" fill=\"#94a3b8\" text-anchor=\"middle\" font-size=\"7.3\">Voice Assistant Pipeline</text>\n  <rect x=\"85\" y=\"22\" width=\"90\" height=\"14\" rx=\"3\" fill=\"#1e293b\" stroke=\"#60a5fa\"/><text x=\"130\" y=\"32\" fill=\"#93c5fd\" text-anchor=\"middle\" font-size=\"5.2\">Microphone (20ms)</text>\n  <g stroke=\"#475569\"><path d=\"M130,36 V42\"/></g>\n  <rect x=\"85\" y=\"44\" width=\"90\" height=\"14\" rx=\"3\" fill=\"#292524\" stroke=\"#f59e0b\"/><text x=\"130\" y=\"54\" fill=\"#fde68a\" text-anchor=\"middle\" font-size=\"5.2\">VAD</text>\n  <g stroke=\"#475569\"><path d=\"M130,58 V64\"/></g>\n  <rect x=\"85\" y=\"66\" width=\"90\" height=\"14\" rx=\"3\" fill=\"#1e1b4b\" stroke=\"#a78bfa\"/><text x=\"130\" y=\"76\" fill=\"#c4b5fd\" text-anchor=\"middle\" font-size=\"5.2\">Streaming STT</text>\n  <g stroke=\"#475569\"><path d=\"M130,80 V86\"/></g>\n  <rect x=\"85\" y=\"88\" width=\"90\" height=\"14\" rx=\"3\" fill=\"#450a0a\" stroke=\"#f87171\"/><text x=\"130\" y=\"98\" fill=\"#fca5a5\" text-anchor=\"middle\" font-size=\"5.2\">LLM + Tools</text>\n  <g stroke=\"#475569\"><path d=\"M130,102 V108\"/></g>\n  <rect x=\"85\" y=\"110\" width=\"90\" height=\"14\" rx=\"3\" fill=\"#1e1b4b\" stroke=\"#a78bfa\"/><text x=\"130\" y=\"120\" fill=\"#c4b5fd\" text-anchor=\"middle\" font-size=\"5.2\">Streaming TTS</text>\n  <g stroke=\"#475569\"><path d=\"M130,124 V130\"/></g>\n  <rect x=\"85\" y=\"132\" width=\"90\" height=\"14\" rx=\"3\" fill=\"#022c22\" stroke=\"#34d399\"/><text x=\"130\" y=\"142\" fill=\"#6ee7b7\" text-anchor=\"middle\" font-size=\"5.2\">Speaker</text>\n  <rect x=\"5\" y=\"66\" width=\"70\" height=\"70\" rx=\"3\" fill=\"none\" stroke=\"#f87171\" stroke-dasharray=\"2,2\"/><text x=\"40\" y=\"140\" fill=\"#fca5a5\" text-anchor=\"middle\" font-size=\"5\">Barge-in cancels this path</text>\n  <g stroke=\"#f87171\"><path d=\"M85,73 H75\"/></g>\n</svg>",
      headingEn: 'Seven Components, One Overlapping Pipeline', headingKn: 'ಏಳು ಘಟಕಗಳು, ಒಂದು ಅತಿಕ್ರಮಿಸುವ Pipeline',
      captionEn: 'Each stage feeds the next, but stages overlap in time rather than running strictly sequentially -- and any of them can be cancelled by a barge-in event.',
      captionKn: 'ಪ್ರತಿ ಹಂತ ಮುಂದಿನದನ್ನೂ ಆಹಾರ ನೀಡುತ್ತದೆ, ಆದರೆ ಹಂತಗಳು ಕಟ್ಟುನಿಟ್ಟಾಗಿ ಅನುಕ್ರಮವಾಗಿ ಚಲಾಯಿಸುವ ಬದಲಿಗೆ ಸಮಯದಲ್ಲಿ ಅತಿಕ್ರಮಿಸುತ್ತವೆ -- ಮತ್ತು ಅವುಗಳಲ್ಲಿ ಯಾವುದನ್ನೂ ಒಂದು barge-in ಘಟನೆಯಿಂದ ರದ್ದುಗೊಳಿಸಬಹುದು.' } },

    { type: 'heading', data: { level: 'H2', textEn: 'Microphone Capture — Genuinely Verified on Real Hardware', textKn: 'Microphone Capture — ನಿಜ ಹಾರ್ಡ್‌ವೇರ್ ಮೇಲೆ ನಿಜವಾಗಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ' } },
    { type: 'code', data: {
      filename: 'audio.py',
      headingEn: 'Original Code — mic_stream() (Genuinely Run Against a Real Microphone)', headingKn: 'Original Code — mic_stream() (ಒಂದು ನಿಜ Microphone ವಿರುದ್ಧ ನಿಜವಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ)',
      descEn: 'Unlike most model-heavy code in this course, sounddevice genuinely installed and this environment genuinely has real audio hardware ("Headset Microphone (Plantronics...)"). This is the lesson\'s exact code, run for real -- not simulated, not mocked.',
      descKn: 'ಈ ಕೋರ್ಸ್‌ನಲ್ಲಿ ಹೆಚ್ಚಿನ model-ಭಾರೀ code ಗಿಂತ ಭಿನ್ನವಾಗಿ, sounddevice ನಿಜವಾಗಿ ಸ್ಥಾಪಿಸಲಾಗಿದೆ ಮತ್ತು ಈ environment ನಿಜವಾಗಿ ನಿಜ audio ಹಾರ್ಡ್‌ವೇರ್ ಹೊಂದಿದೆ ("Headset Microphone (Plantronics...)"). ಇದೂ ಲೆಸನ್‌ನ ನಿಖರ code, ನಿಜವಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ -- simulated ಅಲ್ಲ, mocked ಅಲ್ಲ.',
      code: "import queue\nimport sounddevice as sd\n\nSAMPLE_RATE = 16_000\nCHANNELS = 1\nCHUNK_MS = 20\nCHUNK_SAMPLES = int(SAMPLE_RATE * CHUNK_MS / 1000)\n\ndef mic_stream():\n    audio_queue = queue.Queue()\n\n    def callback(indata, frames, time, status):\n        if status:\n            print(status)\n        audio_queue.put(indata.copy().flatten())\n\n    with sd.InputStream(\n        samplerate=SAMPLE_RATE,\n        channels=CHANNELS,\n        dtype=\"float32\",\n        blocksize=CHUNK_SAMPLES,\n        callback=callback,\n    ):\n        while True:\n            yield audio_queue.get()\n\n\ncount = 0\nfor chunk in mic_stream():\n    print('samples:', len(chunk), 'first:', chunk[:3])\n    count += 1\n    if count >= 5:\n        break" } },
    { type: 'output', data: { output: "samples: 320 first: [ 0.0000000e+00  0.0000000e+00 -3.0517578e-05]\nsamples: 320 first: [0. 0. 0.]\nsamples: 320 first: [ 9.1552734e-05 -9.1552734e-05 -1.8310547e-04]\nsamples: 320 first: [3.6621094e-04 2.1362305e-04 6.1035156e-05]\nsamples: 320 first: [-0.00024414 -0.00027466 -0.00015259]" } },
    { type: 'concept', data: {
      headingEn: 'Reading the Verified Output', headingKn: 'ಪರಿಶೀಲಿಸಿದ Output ಓದುವುದು',
      bodyEn: '• Five genuine chunks, each exactly 320 samples (20ms @ 16kHz) as the lesson predicts. The sample values are real, tiny float32 numbers (on the order of 1e-4) -- consistent with a real microphone picking up quiet ambient room noise in an unattended environment, not with fabricated or zeroed-out data. This is one of the few pieces of code in this entire course that could be tested against genuine hardware rather than needing a synthetic substitute or being blocked by a missing dependency.\n• Running `energy_vad()` on 8 further real captured chunks from the same microphone correctly classified all of them as "silence" -- exactly the expected result for a quiet, unattended room, and a real end-to-end confirmation that microphone capture, chunking, and VAD genuinely interoperate.',
      bodyKn: '• ಐದು ನಿಜ chunks ಗಳು, ಪ್ರತಿಯೊಂದೂ ಲೆಸನ್ ಊಹಿಸುವಂತೆ ನಿಖರವಾಗಿ 320 samples (16kHz ನಲ್ಲಿ 20ms). Sample ಮೌಲ್ಯಗಳು ನಿಜ, ಚಿಕ್ಕ float32 ಸಂಖ್ಯೆಗಳು (ಸುಮಾರು 1e-4 ಕ್ರಮಾಂಕದಲ್ಲಿ) -- ಒಂದು ಗಮನಿಸದ environment ನಲ್ಲಿ ಶಾಂತ ಪರಿಸರ ಶಬ್ದ ಪಡೆಯುವ ಒಂದು ನಿಜ microphone ಗೆ ಅನುಗುಣವಾಗಿ, ಕಟ್ಟುಕಥೆಯ ಅಥವಾ ಶೂನ್ಯಗೊಳಿಸಿದ ಡೇಟಾಗಲ್ಲ. ಇದೂ ಈ ಸಂಪೂರ್ಣ ಕೋರ್ಸ್‌ನಲ್ಲಿ ಒಂದು synthetic ಬದಲಿ ಅಗತ್ಯವಿಲ್ಲದೆ ಅಥವಾ ಕಾಣೆಯಾದ dependency ಇಂದ ಬ್ಲಾಕ್ ಆಗದೆ ನಿಜ ಹಾರ್ಡ್‌ವೇರ್ ವಿರುದ್ಧ ಪರೀಕ್ಷಿಸಬಹುದಾದ ಈ ಕೋರ್ಸ್‌ನ ಕೆಲವು code ತುಣುಕುಗಳಲ್ಲಿ ಒಂದು.\n• ಅದೇ microphone ಇಂದ 8 ಹೆಚ್ಚಿನ ನಿಜ ಸೆರೆಹಿಡಿದ chunks ಮೇಲೆ `energy_vad()` ಚಲಾಯಿಸುವುದೂ ಎಲ್ಲವನ್ನೂ ಸರಿಯಾಗಿ "silence" ಎಂದು ವರ್ಗೀಕರಿಸಿತು -- ಒಂದು ಶಾಂತ, ಗಮನಿಸದ ಕೋಣೆಗೆ ನಿಖರವಾಗಿ ನಿರೀಕ್ಷಿತ ಫಲಿತಾಂಶ, ಮತ್ತು microphone capture, chunking, ಮತ್ತು VAD ನಿಜವಾಗಿ ಪರಸ್ಪರ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತವೆ ಎಂಬ ಒಂದು ನಿಜ end-to-end ದೃಢೀಕರಣ.' } },

    { type: 'heading', data: { level: 'H2', textEn: 'Target Performance: Overlap, Not Speed', textKn: 'Target Performance: Overlap, Speed ಅಲ್ಲ' } },
    { type: 'concept', data: {
      headingEn: 'First TTS Audio Within 800ms', headingKn: '800ms ಒಳಗೆ ಮೊದಲ TTS Audio',
      bodyEn: '• The target: first TTS audio byte within 800ms after the user finishes speaking. A sequential pipeline (STT fully done, then LLM fully done, then TTS fully done) sums each stage\'s latency; an overlapping pipeline (LLM starts on STT\'s partial output, TTS starts on the LLM\'s first tokens) can hit the same target with individually slower components, because the stages run concurrently rather than back-to-back.\n• A useful budget model: VAD finalization 50-100ms, STT 150-250ms, LLM first token 100-200ms, TTS first audio 100-200ms, playback 20-50ms. The individual numbers matter less than measuring the whole pipeline end to end rather than assuming each stage\'s published benchmark adds up correctly.',
      bodyKn: '• ಗುರಿ: ಬಳಕೆದಾರರು ಮಾತನಾಡುವುದೂ ಮುಗಿಸಿದ ನಂತರ 800ms ಒಳಗೆ ಮೊದಲ TTS audio byte. ಒಂದು ಅನುಕ್ರಮಿಕ pipeline (STT ಪೂರ್ಣವಾಗಿ ಮುಗಿದಿದೆ, ನಂತರ LLM ಪೂರ್ಣವಾಗಿ ಮುಗಿದಿದೆ, ನಂತರ TTS ಪೂರ್ಣವಾಗಿ ಮುಗಿದಿದೆ) ಪ್ರತಿ ಹಂತದ latency ಮೊತ್ತ ಮಾಡುತ್ತದೆ; ಒಂದು ಅತಿಕ್ರಮಿಸುವ pipeline (LLM STT ನ ಭಾಗಶಃ output ಮೇಲೆ ಆರಂಭಿಸುತ್ತದೆ, TTS LLM ನ ಮೊದಲ tokens ಮೇಲೆ ಆರಂಭಿಸುತ್ತದೆ) ವೈಯಕ್ತಿಕವಾಗಿ ನಿಧಾನ ಘಟಕಗಳೊಂದಿಗೆ ಅದೇ ಗುರಿ ತಲುಪಬಹುದು, ಏಕೆಂದರೆ ಹಂತಗಳು ಒಂದರ ನಂತರ ಒಂದು ಬದಲಿಗೆ ಏಕಕಾಲದಲ್ಲಿ ಚಲಾಯಿಸುತ್ತವೆ.\n• ಒಂದು ಉಪಯುಕ್ತ ಬಜೆಟ್ ಮಾದರಿ: VAD finalization 50-100ms, STT 150-250ms, LLM first token 100-200ms, TTS first audio 100-200ms, playback 20-50ms. ವೈಯಕ್ತಿಕ ಸಂಖ್ಯೆಗಳು ಪ್ರತಿ ಹಂತದ ಪ್ರಕಟಿತ benchmark ಸರಿಯಾಗಿ ಮೊತ್ತವಾಗುತ್ತದೆ ಎಂದು ಊಹಿಸುವುದಕ್ಕಿಂತ ಸಂಪೂರ್ಣ pipeline ಅನ್ನೂ end to end ಅಳೆಯುವುದಕ್ಕಿಂತ ಕಡಿಮೆ ಮುಖ್ಯ.' } },

    { type: 'heading', data: { level: 'H2', textEn: 'Tool Calling: From Chatbot to Agent', textKn: 'Tool Calling: Chatbot ಇಂದ Agent ಗೆ' } },
    { type: 'concept', data: {
      headingEn: 'The LLM Shouldn\'t Invent Tool Results', headingKn: 'LLM Tool Results ಗಳನ್ನೂ ಕಂಡುಹಿಡಿಯಬಾರದು',
      bodyEn: '• "Set a timer for five minutes" shouldn\'t get "Okay" -- it needs `set_timer(seconds=300)` actually called. Pipeline: transcript -> LLM -> tool_call -> dispatch -> real tool -> result -> LLM -> "Sure, timer set for five minutes." -> TTS. This connects the voice assistant to the agent loop from earlier phases -- the LLM decides *what* to do, a real tool executes it, and the LLM\'s final response is grounded in the tool\'s actual result rather than a guess.',
      bodyKn: '• "ಐದು ನಿಮಿಷಗಳ ಟೈಮರ್ ಸೆಟ್ ಮಾಡಿ" "ಸರಿ" ಪಡೆಯಬಾರದು -- ಇದಕ್ಕೆ `set_timer(seconds=300)` ವಾಸ್ತವವಾಗಿ ಕರೆಯಬೇಕು. Pipeline: transcript -> LLM -> tool_call -> dispatch -> ನಿಜ tool -> result -> LLM -> "ಸರಿ, ಐದು ನಿಮಿಷಗಳ ಟೈಮರ್ ಸೆಟ್ ಮಾಡಲಾಗಿದೆ." -> TTS. ಇದೂ voice assistant ಅನ್ನೂ ಹಿಂದಿನ ಹಂತಗಳ agent loop ಗೆ ಸಂಪರ್ಕಿಸುತ್ತದೆ -- LLM *ಏನನ್ನೂ* ಮಾಡಬೇಕು ಎಂದು ನಿರ್ಧರಿಸುತ್ತದೆ, ಒಂದು ನಿಜ tool ಇದನ್ನೂ ಕಾರ್ಯಗತಗೊಳಿಸುತ್ತದೆ, ಮತ್ತು LLM ನ ಅಂತಿಮ ಪ್ರತಿಕ್ರಿಯೆ ಒಂದು ಊಹೆಗಿಂತ tool ನ ನಿಜ ಫಲಿತಾಂಶದಲ್ಲಿ ಆಧಾರವಾಗಿದೆ.' } },
    { type: 'table', data: { captionEn: '2026 Production Reference Stacks (Approximate)', captionKn: '2026 Production Reference Stacks (ಅಂದಾಜು)',
      rows: 'Stack|Approx. Latency|License|Character\nLiveKit + Deepgram + GPT-4o + Cartesia|350-500 ms|Commercial|Production-oriented\nPipecat + Whisper-streaming + GPT-4o + Kokoro|500-800 ms|Mostly open|DIY-friendly\nMoshi|200-300 ms|CC-BY 4.0|Full-duplex architecture\nVapi / Retell|300-500 ms|Commercial|Fastest managed deployment\nWhisper.cpp + llama.cpp + Kokoro-ONNX|Offline|Open|Privacy / edge' } },

    { type: 'heading', data: { level: 'H2', textEn: 'Three Major Failure Modes', textKn: 'ಮೂರು ಪ್ರಮುಖ ವೈಫಲ್ಯ ವಿಧಾನಗಳು' } },
    { type: 'concept', data: {
      headingEn: 'First-Word Clip, Interrupt Confusion, Silence Hallucination', headingKn: 'First-Word Clip, Interrupt Confusion, Silence Hallucination',
      bodyEn: '• Failure 1 -- first-word clip: VAD detects speech slightly late, so "Hey, what\'s the weather?" gets recorded as "what\'s the weather?" The fix is a pre-roll buffer (~300ms) that always remembers recent audio before the trigger.\n• Failure 2 -- mid-response interrupt confusion: if the LLM and TTS keep generating while the user is trying to interrupt, the assistant talks over them. The fix is barge-in: VAD detects new speech, cancels TTS, cancels the LLM, and stops the speaker.\n• Failure 3 -- silence hallucination: ASR models are statistical, not perfect "nothing happened" detectors -- fed silent audio, they can occasionally output something like "Thanks for watching." The fix is to always VAD-gate ASR: only send audio through when VAD says speech, not on every frame.',
      bodyKn: '• ವೈಫಲ್ಯ 1 -- first-word clip: VAD ಸ್ವಲ್ಪ ತಡವಾಗಿ ಭಾಷಣ ಪತ್ತೆಹಚ್ಚುತ್ತದೆ, ಆದ್ದರಿಂದ "Hey, what\'s the weather?" "what\'s the weather?" ಎಂದು ರೆಕಾರ್ಡ್ ಆಗುತ್ತದೆ. ಪರಿಹಾರ ಒಂದು pre-roll buffer (~300ms) ಇದೂ trigger ಮೊದಲು ಇತ್ತೀಚಿನ audio ಯಾವಾಗಲೂ ನೆನಪಿಸಿಕೊಳ್ಳುತ್ತದೆ.\n• ವೈಫಲ್ಯ 2 -- mid-response interrupt confusion: ಬಳಕೆದಾರರು ಅಡ್ಡಿಪಡಿಸಲು ಪ್ರಯತ್ನಿಸುತ್ತಿರುವಾಗ LLM ಮತ್ತು TTS ಉತ್ಪಾದಿಸುತ್ತಲೇ ಇದ್ದರೆ, assistant ಅವರ ಮೇಲೆ ಮಾತನಾಡುತ್ತದೆ. ಪರಿಹಾರ barge-in: VAD ಹೊಸ ಭಾಷಣ ಪತ್ತೆಹಚ್ಚುತ್ತದೆ, TTS cancel ಮಾಡುತ್ತದೆ, LLM cancel ಮಾಡುತ್ತದೆ, ಮತ್ತು speaker ನಿಲ್ಲಿಸುತ್ತದೆ.\n• ವೈಫಲ್ಯ 3 -- silence hallucination: ASR models ಗಳು ಸಂಖ್ಯಾಶಾಸ್ತ್ರೀಯ, ಪರಿಪೂರ್ಣ "ಏನೂ ಆಗಲಿಲ್ಲ" ಪತ್ತೆಕಾರಕಗಳಲ್ಲ -- ಮೌನ audio ಆಹಾರ ನೀಡಿದಾಗ, ಅವು ಸಾಂದರ್ಭಿಕವಾಗಿ "Thanks for watching." ನಂತಹದೂ ಔಟ್‌ಪುಟ್ ಮಾಡಬಹುದು. ಪರಿಹಾರ ಯಾವಾಗಲೂ ASR ಅನ್ನೂ VAD-gate ಮಾಡುವುದೂ: VAD ಭಾಷಣ ಎಂದು ಹೇಳಿದಾಗ ಮಾತ್ರ audio ಕಳುಹಿಸಿ, ಪ್ರತಿ frame ಮೇಲಲ್ಲ.' } },

    { type: 'concept', data: {
      headingEn: 'Privacy and Wake Words', headingKn: 'Privacy ಮತ್ತು Wake Words',
      bodyEn: '• An always-listening microphone raises real privacy questions: what audio is stored, for how long, where, and who can access it. A wake-word layer (Porcupine, openWakeWord) placed before VAD/STT means the system stays idle until a specific phrase like "Hey Assistant" activates it, reducing how much audio ever needs processing or storage in the first place -- a genuine architectural mitigation, not just a policy statement.',
      bodyKn: '• ಒಂದು ಯಾವಾಗಲೂ-ಕೇಳುವ microphone ನಿಜ ಗೌಪ್ಯತಾ ಪ್ರಶ್ನೆಗಳನ್ನೂ ಎತ್ತುತ್ತದೆ: ಯಾವ audio ಸಂಗ್ರಹಿಸಲಾಗಿದೆ, ಎಷ್ಟು ಸಮಯ, ಎಲ್ಲಿ, ಮತ್ತು ಯಾರು ಪ್ರವೇಶಿಸಬಹುದು. VAD/STT ಮೊದಲು ಇಡಲಾದ ಒಂದು wake-word ಪದರ (Porcupine, openWakeWord) ಎಂದರೆ system "Hey Assistant" ನಂತಹ ಒಂದು ನಿರ್ದಿಷ್ಟ ಪದಗುಚ್ಛ ಇದನ್ನೂ ಸಕ್ರಿಯಗೊಳಿಸುವವರೆಗೆ ಐಡಲ್ ಆಗಿ ಉಳಿಯುತ್ತದೆ, ಮೊದಲ ಸ್ಥಳದಲ್ಲಿ ಎಷ್ಟು audio ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಬೇಕು ಅಥವಾ ಸಂಗ್ರಹಿಸಬೇಕು ಎಂಬುದನ್ನೂ ಕಡಿಮೆ ಮಾಡುತ್ತಾ -- ಒಂದು ನಿಜ architectural ತಗ್ಗಿಸುವಿಕೆ, ಕೇವಲ ಒಂದು policy ಹೇಳಿಕೆ ಅಲ್ಲ.' } },

    { type: 'concept', data: {
      headingEn: 'Why AI Uses It', headingKn: 'AI ಇದನ್ನು ಏಕೆ ಬಳಸುತ್ತದೆ',
      bodyEn: '• The seven-component split exists because it lets every stage evolve or be swapped independently -- the STT vendor, the LLM, and the TTS voice can all change without redesigning the pipeline, as long as each respects the same streaming interface. This is the same interface-based design principle already used across this course\'s production architecture patterns.\n• Overlapping components rather than optimizing each one in isolation is the single biggest latency lever available: a team that spends a month shaving 50ms off ASR gets a much smaller win than a team that spends a week making ASR, LLM, and TTS run concurrently instead of sequentially.\n• The genuinely-verified real microphone capture matters beyond just "the code works" -- it demonstrates that this specific piece of the stack (audio I/O) is something an engineer can test and debug directly on their own machine before ever touching a cloud API, which is a meaningfully different (and cheaper, faster-iterating) development loop than the model-heavy stages later in the pipeline.',
      bodyKn: '• ಏಳು-ಘಟಕದ ವಿಭಜನೆ ಅಸ್ತಿತ್ವದಲ್ಲಿದೆ ಏಕೆಂದರೆ ಇದೂ ಪ್ರತಿ ಹಂತಕ್ಕೆ ಸ್ವತಂತ್ರವಾಗಿ ವಿಕಸನಗೊಳ್ಳಲು ಅಥವಾ ಬದಲಾಯಿಸಲು ಬಿಡುತ್ತದೆ -- STT vendor, LLM, ಮತ್ತು TTS ಧ್ವನಿ ಎಲ್ಲಾ pipeline ಅನ್ನೂ ಮರುವಿನ್ಯಾಸಗೊಳಿಸದೆ ಬದಲಾಗಬಹುದು, ಪ್ರತಿಯೊಂದೂ ಅದೇ streaming interface ಗೌರವಿಸುವವರೆಗೆ. ಇದೂ ಈ ಕೋರ್ಸ್‌ನ production architecture ಮಾದರಿಗಳಾದ್ಯಂತ ಈಗಾಗಲೇ ಬಳಸಿದ ಅದೇ interface-ಆಧಾರಿತ ವಿನ್ಯಾಸ ಸಿದ್ಧಾಂತ.\n• ಪ್ರತಿಯೊಂದನ್ನೂ ಪ್ರತ್ಯೇಕವಾಗಿ ಆಪ್ಟಿಮೈಸ್ ಮಾಡುವ ಬದಲಿಗೆ ಘಟಕಗಳನ್ನೂ ಅತಿಕ್ರಮಿಸುವುದೂ ಲಭ್ಯವಿರುವ ಏಕೈಕ ಅತಿ ದೊಡ್ಡ latency lever: ASR ಇಂದ 50ms ಕತ್ತರಿಸಲು ಒಂದು ತಿಂಗಳು ಕಳೆಯುವ ಒಂದು ತಂಡ ASR, LLM, ಮತ್ತು TTS ಅನ್ನೂ ಅನುಕ್ರಮವಾಗಿ ಬದಲಿಗೆ ಏಕಕಾಲದಲ್ಲಿ ಚಲಾಯಿಸುವ ಒಂದು ವಾರ ಕಳೆಯುವ ಒಂದು ತಂಡಕ್ಕಿಂತ ಬಹಳ ಚಿಕ್ಕ ಲಾಭ ಪಡೆಯುತ್ತದೆ.\n• ಇಲ್ಲಿ ನಿಜವಾಗಿ-ಪರಿಶೀಲಿಸಿದ ನಿಜ microphone capture ಕೇವಲ "code ಕೆಲಸ ಮಾಡುತ್ತದೆ" ಎಂಬುದರ ಆಚೆ ಮುಖ್ಯ -- ಇದೂ stack ನ ಈ ನಿರ್ದಿಷ್ಟ ತುಣುಕು (audio I/O) ಒಬ್ಬ ಎಂಜಿನಿಯರ್ ಒಂದು cloud API ಮುಟ್ಟುವ ಮೊದಲೇ ಅವರ ಸ್ವಂತ ಯಂತ್ರದಲ್ಲಿ ನೇರವಾಗಿ ಪರೀಕ್ಷಿಸಬಹುದಾದ ಮತ್ತು ಡೀಬಗ್ ಮಾಡಬಹುದಾದ ಏನೋ ಎಂದು ಪ್ರದರ್ಶಿಸುತ್ತದೆ, ಇದೂ pipeline ನಲ್ಲಿ ನಂತರದ model-ಭಾರೀ ಹಂತಗಳಿಗಿಂತ ಅರ್ಥಪೂರ್ಣವಾಗಿ ಭಿನ್ನ (ಮತ್ತು ಅಗ್ಗದ, ವೇಗವಾಗಿ-iterating) development loop.' } },

    { type: 'concept', data: {
      headingEn: 'Key Takeaways', headingKn: 'ಮುಖ್ಯ ಅಂಶಗಳು',
      bodyEn: '• A voice assistant is seven components: capture, VAD, streaming STT, LLM+tools, streaming TTS, playback, and an interruption handler -- with a parallel barge-in path that can cancel any of them.\n• The target is first-audio latency (~800ms after the user finishes speaking), not complete-response latency -- achieved by overlapping stages, not making each one individually as fast as possible.\n• The lesson\'s microphone-capture code was genuinely run against real audio hardware in this environment, capturing real 320-sample frames -- one of the few pieces of code in this course testable without a synthetic substitute or a missing dependency.\n• Tool calling grounds the LLM\'s response in a real tool\'s actual result rather than letting it invent one -- the voice-assistant instance of the agent loop.\n• The three major failure modes are first-word clipping (fixed by pre-roll), mid-response interrupt confusion (fixed by barge-in), and silence hallucination (fixed by VAD-gating ASR).\n• Always-listening systems carry real privacy implications; a wake-word layer is a genuine architectural mitigation, not just a policy.',
      bodyKn: '• ಒಂದು voice assistant ಏಳು ಘಟಕಗಳು: capture, VAD, streaming STT, LLM+tools, streaming TTS, playback, ಮತ್ತು ಒಂದು interruption handler -- ಇವುಗಳಲ್ಲಿ ಯಾವುದನ್ನೂ cancel ಮಾಡಬಹುದಾದ ಒಂದು ಸಮಾನಾಂತರ barge-in ಮಾರ್ಗದೊಂದಿಗೆ.\n• ಗುರಿ first-audio latency (ಬಳಕೆದಾರರು ಮಾತನಾಡುವುದೂ ಮುಗಿಸಿದ ~800ms ನಂತರ), complete-response latency ಅಲ್ಲ -- ಹಂತಗಳನ್ನೂ ಅತಿಕ್ರಮಿಸುವ ಮೂಲಕ ಸಾಧಿಸಲಾಗಿದೆ, ಪ್ರತಿಯೊಂದನ್ನೂ ವೈಯಕ್ತಿಕವಾಗಿ ಸಾಧ್ಯವಾದಷ್ಟು ವೇಗಗೊಳಿಸುವ ಮೂಲಕ ಅಲ್ಲ.\n• ಲೆಸನ್‌ನ microphone-capture code ಅನ್ನೂ ಈ environment ನಲ್ಲಿ ನಿಜ audio ಹಾರ್ಡ್‌ವೇರ್ ವಿರುದ್ಧ ನಿಜವಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ, ನಿಜ 320-sample frames ಗಳನ್ನೂ ಸೆರೆಹಿಡಿಯುತ್ತಾ -- ಈ ಕೋರ್ಸ್‌ನಲ್ಲಿ ಒಂದು synthetic ಬದಲಿ ಅಥವಾ ಕಾಣೆಯಾದ dependency ಇಲ್ಲದೆ ಪರೀಕ್ಷಿಸಬಹುದಾದ ಕೆಲವು code ತುಣುಕುಗಳಲ್ಲಿ ಒಂದು.\n• Tool calling LLM ನ ಪ್ರತಿಕ್ರಿಯೆಯನ್ನೂ ಇದನ್ನೂ ಕಂಡುಹಿಡಿಯಲು ಬಿಡುವ ಬದಲಿಗೆ ಒಂದು ನಿಜ tool ನ ನಿಜ ಫಲಿತಾಂಶದಲ್ಲಿ ಆಧಾರಗೊಳಿಸುತ್ತದೆ -- agent loop ನ voice-assistant ನಿದರ್ಶನ.\n• ಮೂರು ಪ್ರಮುಖ ವೈಫಲ್ಯ ವಿಧಾನಗಳು first-word clipping (pre-roll ಇಂದ ಸರಿಪಡಿಸಲಾಗಿದೆ), mid-response interrupt confusion (barge-in ಇಂದ ಸರಿಪಡಿಸಲಾಗಿದೆ), ಮತ್ತು silence hallucination (VAD-gating ASR ಇಂದ ಸರಿಪಡಿಸಲಾಗಿದೆ).\n• ಯಾವಾಗಲೂ-ಕೇಳುವ systems ಗಳು ನಿಜ ಗೌಪ್ಯತಾ ಪರಿಣಾಮಗಳನ್ನೂ ಹೊಂದಿವೆ; ಒಂದು wake-word ಪದರ ಒಂದು ನಿಜ architectural ತಗ್ಗಿಸುವಿಕೆ, ಕೇವಲ ಒಂದು policy ಅಲ್ಲ.' } },

    { type: 'quiz', data: { questions: [
      { q: 'What is the actual latency target for this capstone voice assistant?', qKn: 'ಈ capstone voice assistant ಗಾಗಿ ನಿಜ latency ಗುರಿ ಏನು?',
        opts: ['Complete response generated within 10 seconds', 'First TTS audio byte within roughly 800ms after the user finishes speaking', 'Zero latency, achieved by precomputing all possible answers', 'ASR must finish within 10ms'], correct: 1,
        optsKn: ['10 ಸೆಕೆಂಡುಗಳ ಒಳಗೆ ಸಂಪೂರ್ಣ ಪ್ರತಿಕ್ರಿಯೆ ಉತ್ಪಾದಿಸಲಾಗಿದೆ', 'ಬಳಕೆದಾರರು ಮಾತನಾಡುವುದೂ ಮುಗಿಸಿದ ಸುಮಾರು 800ms ಒಳಗೆ ಮೊದಲ TTS audio byte', 'ಎಲ್ಲಾ ಸಾಧ್ಯ ಉತ್ತರಗಳನ್ನೂ ಪೂರ್ವಗಣಿಸಿ ಸಾಧಿಸಿದ ಶೂನ್ಯ latency', 'ASR 10ms ಒಳಗೆ ಮುಗಿಯಬೇಕು'] },
      { q: 'Verified in this lesson: what did genuinely running mic_stream() against real hardware show?', qKn: 'ಈ lesson ನಲ್ಲಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ: mic_stream() ಅನ್ನೂ ನಿಜ ಹಾರ್ಡ್‌ವೇರ್ ವಿರುದ್ಧ ನಿಜವಾಗಿ ಚಲಾಯಿಸುವುದೂ ಏನನ್ನೂ ತೋರಿಸಿತು?',
        opts: ['sounddevice could not be installed in this environment', 'It genuinely captured real 320-sample chunks from a real microphone device, with real small float32 values consistent with ambient room noise', 'It only worked when connected to a cloud ASR service', 'It returned exactly zero for every sample'], correct: 1,
        optsKn: ['ಈ environment ನಲ್ಲಿ sounddevice ಅನ್ನೂ ಸ್ಥಾಪಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ', 'ಇದೂ ಒಂದು ನಿಜ microphone ಸಾಧನದಿಂದ ನಿಜ 320-sample chunks ಗಳನ್ನೂ ನಿಜವಾಗಿ ಸೆರೆಹಿಡಿಯಿತು, ಪರಿಸರ ಕೋಣೆ ಶಬ್ದಕ್ಕೆ ಅನುಗುಣವಾಗಿ ನಿಜ ಚಿಕ್ಕ float32 ಮೌಲ್ಯಗಳೊಂದಿಗೆ', 'ಇದೂ ಕೇವಲ ಒಂದು cloud ASR ಸೇವೆಗೆ ಸಂಪರ್ಕಿಸಿದಾಗ ಮಾತ್ರ ಕೆಲಸ ಮಾಡಿತು', 'ಇದೂ ಪ್ರತಿ sample ಗೆ ನಿಖರವಾಗಿ ಶೂನ್ಯ ಹಿಂದಿರುಗಿಸಿತು'] },
      { q: 'Why does tool calling matter for a voice assistant?', qKn: 'ಒಂದು voice assistant ಗೆ tool calling ಏಕೆ ಮುಖ್ಯ?',
        opts: ['It makes the LLM respond faster in all cases', 'It grounds the assistant\'s response in a real tool\'s actual result (e.g. real weather data) instead of letting the LLM invent an answer', 'It replaces the need for streaming TTS', 'Tool calling is only relevant for text chatbots, not voice'], correct: 1,
        optsKn: ['ಇದೂ LLM ಅನ್ನೂ ಎಲ್ಲಾ ಪ್ರಕರಣಗಳಲ್ಲಿ ವೇಗವಾಗಿ ಪ್ರತಿಕ್ರಿಯಿಸುವಂತೆ ಮಾಡುತ್ತದೆ', 'ಇದೂ assistant ನ ಪ್ರತಿಕ್ರಿಯೆಯನ್ನೂ ಒಂದು ನಿಜ tool ನ ನಿಜ ಫಲಿತಾಂಶದಲ್ಲಿ (ಉದಾ. ನಿಜ ಹವಾಮಾನ ಡೇಟಾ) ಆಧಾರಗೊಳಿಸುತ್ತದೆ, LLM ಗೆ ಒಂದು ಉತ್ತರ ಕಂಡುಹಿಡಿಯಲು ಬಿಡುವ ಬದಲಿಗೆ', 'ಇದೂ streaming TTS ಅಗತ್ಯವನ್ನೂ ಬದಲಾಯಿಸುತ್ತದೆ', 'Tool calling ಕೇವಲ ಪಠ್ಯ chatbots ಗೆ ಮಾತ್ರ ಪ್ರಸ್ತುತ, voice ಗಲ್ಲ'] },
      { q: 'What causes the "first-word clip" failure mode, and how is it fixed?', qKn: '"first-word clip" ವೈಫಲ್ಯ ವಿಧಾನಕ್ಕೆ ಕಾರಣವೇನು, ಮತ್ತು ಇದನ್ನೂ ಹೇಗೆ ಸರಿಪಡಿಸಲಾಗುತ್ತದೆ?',
        opts: ['The microphone hardware is broken', 'VAD detects speech slightly late, clipping the first word -- fixed with a pre-roll buffer that always remembers recent audio before the trigger', 'The LLM ignores the first word of every sentence', 'It is fixed by increasing the sample rate'], correct: 1,
        optsKn: ['Microphone ಹಾರ್ಡ್‌ವೇರ್ ಮುರಿದಿದೆ', 'VAD ಸ್ವಲ್ಪ ತಡವಾಗಿ ಭಾಷಣ ಪತ್ತೆಹಚ್ಚುತ್ತದೆ, ಮೊದಲ ಪದ ಕ್ಲಿಪ್ ಮಾಡುತ್ತಾ -- trigger ಮೊದಲು ಇತ್ತೀಚಿನ audio ಯಾವಾಗಲೂ ನೆನಪಿಸಿಕೊಳ್ಳುವ ಒಂದು pre-roll buffer ಜೊತೆ ಸರಿಪಡಿಸಲಾಗಿದೆ', 'LLM ಪ್ರತಿ ವಾಕ್ಯದ ಮೊದಲ ಪದ ನಿರ್ಲಕ್ಷಿಸುತ್ತದೆ', 'ಇದನ್ನೂ sample rate ಹೆಚ್ಚಿಸುವ ಮೂಲಕ ಸರಿಪಡಿಸಲಾಗಿದೆ'] },
      { q: 'Why does the lesson recommend always VAD-gating ASR rather than sending every audio frame through it?', qKn: 'ಪ್ರತಿ audio frame ಇದರ ಮೂಲಕ ಕಳುಹಿಸುವ ಬದಲಿಗೆ ಲೆಸನ್ ಏಕೆ ಯಾವಾಗಲೂ ASR ಅನ್ನೂ VAD-gating ಮಾಡಲು ಶಿಫಾರಸು ಮಾಡುತ್ತದೆ?',
        opts: ['ASR cannot process audio faster than real time otherwise', 'ASR models can hallucinate content on silent/noisy audio since they are statistical models, not perfect "nothing happened" detectors -- VAD-gating prevents this', 'VAD-gating makes the microphone hardware last longer', 'It has nothing to do with accuracy, only cost'], correct: 1,
        optsKn: ['ASR ಇಲ್ಲದಿದ್ದರೆ ನೈಜ ಸಮಯಕ್ಕಿಂತ ವೇಗವಾಗಿ audio ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲು ಸಾಧ್ಯವಿಲ್ಲ', 'ASR models ಗಳು ಮೌನ/ಶಬ್ದಮಯ audio ಮೇಲೆ ವಿಷಯ hallucinate ಮಾಡಬಹುದು ಅವು ಸಂಖ್ಯಾಶಾಸ್ತ್ರೀಯ models ಗಳಾಗಿರುವ ಕಾರಣ, ಪರಿಪೂರ್ಣ "ಏನೂ ಆಗಲಿಲ್ಲ" ಪತ್ತೆಕಾರಕಗಳಲ್ಲ -- VAD-gating ಇದನ್ನೂ ತಡೆಯುತ್ತದೆ', 'VAD-gating microphone ಹಾರ್ಡ್‌ವೇರ್ ಹೆಚ್ಚು ಕಾಲ ಬಾಳಿಕೆ ಬರುವಂತೆ ಮಾಡುತ್ತದೆ', 'ಇದಕ್ಕೆ accuracy ಜೊತೆ ಯಾವುದೇ ಸಂಬಂಧವಿಲ್ಲ, ಕೇವಲ ವೆಚ್ಚ ಮಾತ್ರ'] },
      { q: 'Why can an overlapping (streaming) pipeline hit an 800ms target even when individual components are not individually blazing fast?', qKn: 'ವೈಯಕ್ತಿಕ ಘಟಕಗಳು ವೈಯಕ್ತಿಕವಾಗಿ ಬಹಳ ವೇಗವಾಗಿಲ್ಲದಿದ್ದರೂ ಒಂದು ಅತಿಕ್ರಮಿಸುವ (streaming) pipeline ಒಂದು 800ms ಗುರಿ ಏಕೆ ತಲುಪಬಹುದು?',
        opts: ['Because overlapping pipelines skip stages entirely', 'Because stages run concurrently rather than sequentially -- the LLM can start on partial STT output, and TTS can start on the LLM\'s first tokens, instead of waiting for each stage to fully finish', 'Because overlapping pipelines use less accurate models', 'It cannot -- individual component speed is the only thing that matters'], correct: 1,
        optsKn: ['ಅತಿಕ್ರಮಿಸುವ pipelines ಗಳು ಹಂತಗಳನ್ನೂ ಸಂಪೂರ್ಣವಾಗಿ ಬಿಟ್ಟುಬಿಡುವ ಕಾರಣ', 'ಹಂತಗಳು ಅನುಕ್ರಮವಾಗಿ ಬದಲಿಗೆ ಏಕಕಾಲದಲ್ಲಿ ಚಲಾಯಿಸುವ ಕಾರಣ -- LLM ಭಾಗಶಃ STT output ಮೇಲೆ ಆರಂಭಿಸಬಹುದು, ಮತ್ತು TTS LLM ನ ಮೊದಲ tokens ಮೇಲೆ ಆರಂಭಿಸಬಹುದು, ಪ್ರತಿ ಹಂತ ಸಂಪೂರ್ಣವಾಗಿ ಮುಗಿಯುವವರೆಗೆ ಕಾಯುವ ಬದಲಿಗೆ', 'ಅತಿಕ್ರಮಿಸುವ pipelines ಗಳು ಕಡಿಮೆ ನಿಖರ models ಗಳನ್ನೂ ಬಳಸುವ ಕಾರಣ', 'ಇದೂ ಸಾಧ್ಯವಿಲ್ಲ -- ವೈಯಕ್ತಿಕ ಘಟಕ ವೇಗ ಮಾತ್ರ ಮುಖ್ಯ'] },
    ] } },
  ],
};
