const phaseId = '6a369d5866020ed05b32139d'; // Phase 11: Generative AI
const moduleId = '6a369d5866020ed05b3213a0'; // Module 157: Generative Models: Taxonomy and History

module.exports = {
  phaseId,
  moduleId,
  order: 3,
  type: 'interactive',
  duration: 45,
  difficulty: 'advanced',
  status: 'published',
  title: 'Generative Models — Taxonomy & History (Lesson 3) — Choosing the Right Generative Family',
  titleKn: 'Generative Models — Taxonomy & History (Lesson 3) — Choosing the Right Generative Family',
  desc: 'Build a reusable decision framework for choosing a generative-model family for a real problem, compare families by training objective/inference shape/latency, and learn to translate marketing claims like "10x faster than diffusion" into genuine compute trade-offs.',
  descKn: 'ಒಂದೂ ನಿಜ ಸಮಸ್ಯೆಗೆ ಒಂದೂ generative-model family ಆಯ್ಕೆ ಮಾಡಲು ಒಂದೂ ಮರುಬಳಕೆ ಮಾಡಬಹುದಾದ decision framework ನಿರ್ಮಿಸಿ, families ಅನ್ನೂ training objective/inference shape/latency ಮೂಲಕ ಹೋಲಿಸಿ, ಮತ್ತು "10x faster than diffusion" ನಂತಹ marketing claims ಅನ್ನೂ ನಿಜ compute trade-offs ಗೆ ಭಾಷಾಂತರಿಸಲು ಕಲಿಯಿರಿ.',
  objectives: [
    'Choose a generative-model family for a real problem using a decision framework.',
    'Compare models by training objective, inference shape, likelihood, quality, latency, and controllability.',
    'Understand when to choose VAE, GAN, autoregressive Transformer, normalizing flow, diffusion, latent diffusion, flow matching, or VAR.',
    'Understand why production systems often combine multiple families.',
    'Translate claims such as "10x faster than diffusion" into actual compute trade-offs.',
    'Build a simple decision framework reusable when reading new papers.',
  ],
  objectivesKn: [
    'ಒಂದೂ decision framework ಬಳಸಿ ಒಂದೂ ನಿಜ ಸಮಸ್ಯೆಗೆ ಒಂದೂ generative-model family ಆಯ್ಕೆ ಮಾಡಿ.',
    'Training objective, inference shape, likelihood, quality, latency, ಮತ್ತು controllability ಮೂಲಕ models ಹೋಲಿಸಿ.',
    'VAE, GAN, autoregressive Transformer, normalizing flow, diffusion, latent diffusion, flow matching, ಅಥವಾ VAR ಯಾವಾಗ ಆಯ್ಕೆ ಮಾಡಬೇಕು ಎಂದೂ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'Production systems ಸಾಮಾನ್ಯವಾಗಿ ಅನೇಕ families ಅನ್ನೂ ಏಕೆ ಸಂಯೋಜಿಸುತ್ತವೆ ಎಂದೂ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    '"10x faster than diffusion" ನಂತಹ claims ಅನ್ನೂ ನಿಜ compute trade-offs ಗೆ ಭಾಷಾಂತರಿಸಿ.',
    'ಹೊಸ papers ಓದುವಾಗ ಮರುಬಳಕೆ ಮಾಡಬಹುದಾದ ಒಂದೂ ಸರಳ decision framework ನಿರ್ಮಿಸಿ.',
  ],
  blocks: [
    { type: 'heading', data: { textEn: 'Generative Models — Taxonomy & History (Lesson 3)', textKn: 'Generative Models — Taxonomy & History (Lesson 3)', level: 'H1' } },
    { type: 'concept', data: {
      headingEn: 'Lesson Info', headingKn: 'Lesson ಮಾಹಿತಿ',
      bodyEn: '• Type: Learn · Language: Python concepts + architecture reasoning · Time: ~15 minutes · Part 3 of 3',
      bodyKn: '• Type: Learn · Language: Python concepts + architecture reasoning · Time: ~15 ನಿಮಿಷಗಳು · Part 3 of 3',
      pillsEn: 'Decision Framework,Trade-offs,Production,Part 3 of 3',
      pillsKn: 'Decision Framework,Trade-offs,Production,Part 3 of 3' } },

    { type: 'heading', data: { textEn: 'The Most Important Question', textKn: 'The Most Important Question', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'Ask "What Problem?" Before "What Architecture?"', headingKn: '"ಏನೂ Architecture?" ಗಿಂತ ಮೊದಲೂ "ಏನೂ Problem?" ಕೇಳಿ',
      bodyEn: '• When you encounter a new generative model, don\'t begin with "what architecture is this?" -- begin with "what problem is the model trying to solve?" Then ask: what does it generate -> what representation does it use -> what does it learn -> how is generation performed -> what does inference cost?\n• This sequence is much more useful than memorizing model names, and it is the same three-question framework from Lesson 1 (representation, training objective, inference loop) applied concretely to a production decision',
      bodyKn: '• ಒಂದೂ ಹೊಸ generative model ಎದುರಿಸಿದಾಗ, "ಇದೂ ಯಾವ architecture?" ಇಂದ ಪ್ರಾರಂಭಿಸಬೇಡಿ -- "model ಏನೂ ಸಮಸ್ಯೆ ಪರಿಹರಿಸಲು ಪ್ರಯತ್ನಿಸುತ್ತಿದೆ?" ಇಂದ ಪ್ರಾರಂಭಿಸಿ. ನಂತರ ಕೇಳಿ: ಅದೂ ಏನೂ ಉತ್ಪಾದಿಸುತ್ತದೆ -> ಯಾವ representation ಬಳಸುತ್ತದೆ -> ಏನೂ ಕಲಿಯುತ್ತದೆ -> generation ಹೇಗೆ ನಡೆಸಲಾಗುತ್ತದೆ -> inference ವೆಚ್ಚ ಏನೂ?\n• ಈ ಅನುಕ್ರಮ model ಹೆಸರುಗಳನ್ನೂ ನೆನಪಿಡುವುದಕ್ಕಿಂತ ಹೆಚ್ಚು ಉಪಯುಕ್ತ, ಮತ್ತು ಅದೂ Lesson 1 ಇಂದ ಅದೇ ಮೂರೂ-ಪ್ರಶ್ನೆ framework (representation, training objective, inference loop) ಒಂದೂ production ನಿರ್ಧಾರಕ್ಕೆ ನಿರ್ದಿಷ್ಟವಾಗಿ ಅನ್ವಯಿಸಲಾಗಿದೆ' } },

    { type: 'heading', data: { textEn: 'When to Choose Each Family', textKn: 'When to Choose Each Family', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'VAE, GAN, and Autoregressive Transformer', headingKn: 'VAE, GAN, ಮತ್ತು Autoregressive Transformer',
      bodyEn: '• Choose a VAE when the main problem is learning a useful continuous latent representation -- representation learning, compression, or as the first stage of a larger latent-diffusion-style system, not usually as the final production image generator\n• Choose a GAN when you have a narrow domain plus a very low latency requirement plus need for high-quality samples (faces, product variants, game assets, fixed visual style) -- inference is essentially one generator forward pass, versus diffusion\'s N-step loop\n• Choose an ordinary autoregressive Transformer when the data naturally has sequential structure, like text -- the transformer processes the whole prompt in parallel during training, while inference proceeds token by token, a trade-off acceptable because sequence length is usually much smaller than raw pixel counts',
      bodyKn: '• ಒಂದೂ VAE ಆಯ್ಕೆ ಮಾಡಿ ಮುಖ್ಯ ಸಮಸ್ಯೆ ಒಂದೂ ಉಪಯುಕ್ತ continuous latent representation ಕಲಿಯುವುದಾದಾಗ -- representation learning, compression, ಅಥವಾ ಒಂದೂ ದೊಡ್ಡ latent-diffusion-style system ನ ಮೊದಲ stage ಆಗಿ, ಸಾಮಾನ್ಯವಾಗಿ ಅಂತಿಮ production image generator ಆಗಿ ಅಲ್ಲ\n• ಒಂದೂ GAN ಆಯ್ಕೆ ಮಾಡಿ ನಿಮಗೆ ಒಂದೂ ಚಿಕ್ಕ domain ಜೊತೆಗೆ ಒಂದೂ ಅತ್ಯಂತ ಕಡಿಮೆ latency ಅಗತ್ಯ ಮತ್ತು ಉನ್ನತ-ಗುಣಮಟ್ಟ samples ಬೇಕಿದ್ದಾಗ (faces, product variants, game assets, ಸ್ಥಿರ visual style) -- inference essentially ಒಂದೂ generator forward pass, diffusion ನ N-step loop ಗೆ ಹೋಲಿಸಿದಾಗ\n• ಒಂದೂ ಸಾಮಾನ್ಯ autoregressive Transformer ಆಯ್ಕೆ ಮಾಡಿ data ಸ್ವಾಭಾವಿಕವಾಗಿ sequential ರಚನೆ ಹೊಂದಿದ್ದಾಗ, text ನಂತೆ -- transformer training ಸಮಯದಲ್ಲಿ ಸಂಪೂರ್ಣ prompt ಅನ್ನೂ parallel ಆಗಿ ಪ್ರಕ್ರಿಯೆಗೊಳಿಸುತ್ತದೆ, inference token by token ಮುಂದುವರಿಯುತ್ತದೆ, sequence length ಸಾಮಾನ್ಯವಾಗಿ raw pixel counts ಗಿಂತ ಹೆಚ್ಚು ಚಿಕ್ಕದಾಗಿರುವುದರಿಂದ ಸ್ವೀಕಾರಾರ್ಹ trade-off' } },
    { type: 'concept', data: {
      headingEn: 'Normalizing Flow, Diffusion, Latent Diffusion, Flow Matching, VAR', headingKn: 'Normalizing Flow, Diffusion, Latent Diffusion, Flow Matching, VAR',
      bodyEn: '• Choose a normalizing flow when you actually care about evaluating probability density (density estimation, scientific modeling, some probabilistic inference tasks) -- the requirement is log p(x), not simply good samples; the trade-off is exact likelihood versus architectural freedom\n• Choose diffusion for high sample quality plus conditioning plus flexible editing plus broad domains -- slower than a GAN but historically much more robust. Move to latent diffusion specifically when raw pixel-space diffusion is too expensive (the general rule: if raw data is too large, move generation into a learned latent representation, a pattern that also appears in audio codecs, video VAEs, VQ tokenizers, and 3D latent representations)\n• Choose flow matching when diffusion works but its step count is too slow -- learn v_theta(x,t) and integrate an ODE; add rectification and distillation for few-step generation. Choose VAR specifically when you want a Transformer over discrete visual tokens with coarse-to-fine generation and the token-by-token raster ordering of ordinary image AR is inefficient',
      bodyKn: '• ಒಂದೂ normalizing flow ಆಯ್ಕೆ ಮಾಡಿ ನೀವೂ ವಾಸ್ತವವಾಗಿ probability density ಮೌಲ್ಯಮಾಪನ ಮಾಡುವ ಬಗ್ಗೆ ಕಾಳಜಿ ವಹಿಸಿದಾಗ (density estimation, scientific modeling, ಕೆಲವೂ probabilistic inference tasks) -- ಅಗತ್ಯ log p(x), ಕೇವಲ ಒಳ್ಳೆಯ samples ಅಲ್ಲ; trade-off ನಿಖರ likelihood ವಿರುದ್ಧ architectural ಸ್ವಾತಂತ್ರ್ಯ\n• Diffusion ಆಯ್ಕೆ ಮಾಡಿ ಉನ್ನತ sample quality ಜೊತೆಗೆ conditioning ಜೊತೆಗೆ ಹೊಂದಿಕೊಳ್ಳುವ editing ಜೊತೆಗೆ ವಿಶಾಲ domains ಗೆ -- GAN ಗಿಂತ ನಿಧಾನ ಆದರೆ ಐತಿಹಾಸಿಕವಾಗಿ ಹೆಚ್ಚು ಬಲಿಷ್ಠ. Raw pixel-space diffusion ತುಂಬಾ ದುಬಾರಿ ಇದ್ದಾಗ ನಿರ್ದಿಷ್ಟವಾಗಿ latent diffusion ಗೆ ಸರಿಸಿ (ಸಾಮಾನ್ಯ ನಿಯಮ: ನಿಮ್ಮ raw data ತುಂಬಾ ದೊಡ್ಡದಾಗಿದ್ದರೆ, generation ಅನ್ನೂ ಒಂದೂ ಕಲಿತ latent representation ಗೆ ಸರಿಸಿ, ಈ ಮಾದರಿ audio codecs, video VAEs, VQ tokenizers, ಮತ್ತು 3D latent representations ನಲ್ಲೂ ಕಾಣಿಸಿಕೊಳ್ಳುತ್ತದೆ)\n• Diffusion ಕೆಲಸ ಮಾಡಿದರೂ ಅದೂ step count ತುಂಬಾ ನಿಧಾನ ಇದ್ದಾಗ flow matching ಆಯ್ಕೆ ಮಾಡಿ -- v_theta(x,t) ಕಲಿಯಿರಿ ಮತ್ತು ಒಂದೂ ODE ಸಂಯೋಜಿಸಿ; few-step generation ಗಾಗಿ rectification ಮತ್ತು distillation ಸೇರಿಸಿ. ನಿಮಗೆ discrete visual tokens ಮೇಲೆ ಒಂದೂ Transformer coarse-to-fine generation ಜೊತೆ ಬೇಕಿದ್ದಾಗ ಮತ್ತು ಸಾಮಾನ್ಯ image AR ನ token-by-token raster ordering ಅಸಮರ್ಥವಾಗಿದ್ದಾಗ ನಿರ್ದಿಷ್ಟವಾಗಿ VAR ಆಯ್ಕೆ ಮಾಡಿ' } },

    { type: 'math', data: {
      formula: 'Latency ~= N_sequential x Cost_parallel_stage          GAN: N=1     Diffusion: N=20-50     Flow-matched distilled: N=1-8     AR: N=token count     VAR: N=scale count',
      descEn: '• This single approximation explains a huge amount of production behavior: total inference latency is roughly the number of unavoidably sequential steps multiplied by the cost of one parallel stage. Different families sit at very different points on N',
      descKn: 'ಈ ಒಂದೂ approximation production ವರ್ತನೆಯ ಬಹಳ ದೊಡ್ಡ ಭಾಗ ವಿವರಿಸುತ್ತದೆ: ಒಟ್ಟೂ inference latency ಸುಮಾರು ಅನಿವಾರ್ಯವಾಗಿ sequential steps ಸಂಖ್ಯೆಯನ್ನೂ ಒಂದೂ parallel stage ನ ವೆಚ್ಚದಿಂದ ಗುಣಿಸಿದಂತೆ. ಭಿನ್ನ families N ಮೇಲೆ ಬಹಳ ಭಿನ್ನ points ನಲ್ಲಿ ಕುಳಿತಿವೆ' } },
    { type: 'code', data: {
      filename: 'faster_than_diffusion.py', headingEn: 'code for concepts', headingKn: 'concepts ಗಾಗಿ code',
      descEn: 'Genuinely executed below: translating the marketing claim "10x faster than diffusion" into its actual step-count x cost-per-step arithmetic, confirming the true speedup is about 6x, not 10x.',
      descKn: 'ಕೆಳಗೆ ನಿಜವಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ: "10x faster than diffusion" marketing claim ಅನ್ನೂ ಅದೂ ನ ನಿಜ step-count x cost-per-step arithmetic ಗೆ ಭಾಷಾಂತರಿಸುತ್ತಾ, ನಿಜ speedup ಸುಮಾರು 6x, 10x ಅಲ್ಲ ಎಂದೂ ದೃಢಪಡಿಸುತ್ತಾ.',
      code: "diffusion_steps, diffusion_cost_per_step = 30, 1.0\nnew_model_steps, new_model_cost_per_step = 6, 0.8  # cheaper AND fewer steps\n\ndiffusion_total = diffusion_steps * diffusion_cost_per_step\nnew_total = new_model_steps * new_model_cost_per_step\n\nprint('Diffusion total cost:', diffusion_total)\nprint('New model total cost:', new_total)\nprint('Genuine speedup ratio:', round(diffusion_total / new_total, 2), 'x  (not the claimed 10x)')" } },
    { type: 'output', data: { output: "Diffusion total cost: 30.0\nNew model total cost: 4.800000000000001\nGenuine speedup ratio: 6.25 x  (not the claimed 10x)" } },
    { type: 'concept', data: {
      headingEn: 'Reading the Genuinely Confirmed Speedup Arithmetic', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ Speedup Arithmetic ಓದುವುದೂ',
      bodyEn: '• Genuinely confirmed: 30 diffusion steps at cost 1.0 each versus 6 new-model steps at cost 0.8 each gives 30/4.8 = 6.25x, not the claimed 10x -- the claim likely rounded up or measured under different conditions\n• Whenever you read "N times faster than diffusion," decompose it into: did they reduce the number of steps? or the cost per step (smaller model, lower precision, smaller latent resolution)? or both? This decomposition is what separates a genuine engineering claim from a marketing headline',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: 30 diffusion steps ಪ್ರತಿಯೊಂದೂ 1.0 ವೆಚ್ಚದಲ್ಲಿ 6 new-model steps ಪ್ರತಿಯೊಂದೂ 0.8 ವೆಚ್ಚದಲ್ಲಿ ವಿರುದ್ಧ 30/4.8 = 6.25x ಕೊಡುತ್ತದೆ, claim ಮಾಡಿದ 10x ಅಲ್ಲ -- claim ಬಹುಶಃ ಮೇಲ್ಮುಖವಾಗಿ ಸುತ್ತಿಕೊಂಡಿತು ಅಥವಾ ವಿಭಿನ್ನ ಪರಿಸ್ಥಿತಿಗಳಲ್ಲಿ ಅಳೆಯಲಾಗಿದೆ\n• "diffusion ಗಿಂತ N ಪಟ್ಟೂ ವೇಗ" ಓದಿದಾಗಲೆಲ್ಲ, ಅದನ್ನೂ ಬೇರ್ಪಡಿಸಿ: ಅವರೂ steps ಸಂಖ್ಯೆ ಕಡಿಮೆಗೊಳಿಸಿದರೇ? ಅಥವಾ ಪ್ರತಿ step ವೆಚ್ಚ (ಚಿಕ್ಕ model, ಕಡಿಮೆ precision, ಚಿಕ್ಕ latent resolution)? ಅಥವಾ ಎರಡೂ? ಈ ಬೇರ್ಪಡಿಕೆ ಒಂದೂ ನಿಜ engineering claim ಅನ್ನೂ ಒಂದೂ marketing headline ಇಂದ ಬೇರ್ಪಡಿಸುತ್ತದೆ' } },

    { type: 'heading', data: { textEn: 'Production Systems Combine Multiple Families', textKn: 'Production Systems Combine Multiple Families', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'Representation, Architecture, and Objective Are Separate Choices', headingKn: 'Representation, Architecture, ಮತ್ತು Objective ಪ್ರತ್ಯೇಕ Choices',
      bodyEn: '• A production model does not necessarily belong to one bucket -- a real image generator can combine a VAE (latent representation) + Transformer (architecture) + flow matching (generative objective) + LoRA (adaptation) + ControlNet (conditioning) all at once. "Is this model a Transformer or diffusion?" may be the wrong question\n• Keep three concepts separate: Representation (pixels, latent, tokens, audio codec, video latent), Architecture (CNN, U-Net, Transformer, MLP), and Generative objective (GAN, diffusion, flow matching, autoregressive likelihood). A model combines all three, and the task requirements matter more than the modality name -- both image and audio can be generated by AR, diffusion, GAN, or flow-based systems',
      bodyKn: '• ಒಂದೂ production model ಒಂದೂ bucket ಗೆ ಸೇರಬೇಕಿಲ್ಲ -- ಒಂದೂ ನಿಜ image generator ಒಂದೂ VAE (latent representation) + Transformer (architecture) + flow matching (generative objective) + LoRA (adaptation) + ControlNet (conditioning) ಎಲ್ಲಾ ಒಟ್ಟಿಗೆ ಸಂಯೋಜಿಸಬಹುದು. "ಈ model ಒಂದೂ Transformer ಅಥವಾ diffusion?" ತಪ್ಪೂ ಪ್ರಶ್ನೆಯಾಗಿರಬಹುದು\n• ಮೂರೂ ಆಲೋಚನೆಗಳನ್ನೂ ಪ್ರತ್ಯೇಕವಾಗಿ ಇರಿಸಿ: Representation (pixels, latent, tokens, audio codec, video latent), Architecture (CNN, U-Net, Transformer, MLP), ಮತ್ತು Generative objective (GAN, diffusion, flow matching, autoregressive likelihood). ಒಂದೂ model ಎಲ್ಲಾ ಮೂರನ್ನೂ ಸಂಯೋಜಿಸುತ್ತದೆ, ಮತ್ತು ಟಾಸ್ಕ್ ಅಗತ್ಯಗಳು modality ಹೆಸರಿಗಿಂತ ಹೆಚ್ಚು ಮುಖ್ಯ -- image ಮತ್ತು audio ಎರಡನ್ನೂ AR, diffusion, GAN, ಅಥವಾ flow-based systems ಉತ್ಪಾದಿಸಬಹುದು' } },

    { type: 'diagram', data: {
      titleEn: 'The Final Decision Tree', titleKn: 'ಅಂತಿಮ Decision Tree',
      captionEn: 'Genuinely structured decision path: ask about density needs, sampling quality, and speed requirements first, then separately ask whether the data can be compressed (continuous -> VAE, discrete -> VQ/codec) and whether visual AR needs scale-ordering (VAR).',
      captionKn: 'ನಿಜವಾಗಿ ರಚಿಸಿದ decision path: ಮೊದಲೂ density ಅಗತ್ಯಗಳು, sampling quality, ಮತ್ತು speed ಅಗತ್ಯಗಳ ಬಗ್ಗೆ ಕೇಳಿ, ನಂತರ ಪ್ರತ್ಯೇಕವಾಗಿ data compress ಮಾಡಬಹುದೇ ಎಂದೂ ಕೇಳಿ (continuous -> VAE, discrete -> VQ/codec) ಮತ್ತು visual AR ಗೆ scale-ordering ಬೇಕೇ ಎಂದೂ (VAR).',
      svgCode: "<svg viewBox='0 0 760 200' xmlns='http://www.w3.org/2000/svg' font-family='monospace'>\n<text x='300' y='18' fill='#e2e8f0' font-size='12' font-weight='bold'>What do I need?</text>\n<rect x='20' y='35' width='160' height='50' fill='none' stroke='#4ade80'/><text x='28' y='55' fill='#cbd5e1' font-size='10'>Exact log p(x)?</text><text x='28' y='72' fill='#94a3b8' font-size='9'>-&gt; Flow / AR</text>\n<rect x='200' y='35' width='160' height='50' fill='none' stroke='#60a5fa'/><text x='208' y='55' fill='#cbd5e1' font-size='10'>Narrow domain,</text><text x='208' y='72' fill='#94a3b8' font-size='9'>low latency -&gt; GAN</text>\n<rect x='380' y='35' width='160' height='50' fill='none' stroke='#fb923c'/><text x='388' y='55' fill='#cbd5e1' font-size='10'>General quality</text><text x='388' y='72' fill='#94a3b8' font-size='9'>-&gt; Diffusion/Flow</text>\n<rect x='560' y='35' width='180' height='50' fill='none' stroke='#f87171'/><text x='568' y='55' fill='#cbd5e1' font-size='10'>Too many steps?</text><text x='568' y='72' fill='#94a3b8' font-size='9'>-&gt; Flow Matching+Distill</text>\n<text x='20' y='115' fill='#e2e8f0' font-size='11' font-weight='bold'>Can I compress the data?  continuous -&gt; VAE   |   discrete -&gt; VQ / codec</text>\n<text x='20' y='140' fill='#e2e8f0' font-size='11' font-weight='bold'>If discrete visual tokens: normal AR ordering a problem?  Yes -&gt; VAR</text>\n<text x='20' y='170' fill='#94a3b8' font-size='10'>Latency ~= N_sequential x Cost_per_stage: GAN N=1, Diffusion N=20-50, Flow-matched N=1-8, AR N=tokens, VAR N=scales</text>\n</svg>" } },

    { type: 'table', data: {
      captionEn: 'Practical Decision Table (genuinely reasoned)', captionKn: 'ಪ್ರಾಯೋಗಿಕ Decision Table (ನಿಜವಾಗಿ ತರ್ಕಿಸಿದ)',
      rows: "Requirement|Good starting family|Main reason\nExact log p(x)|Normalizing Flow / AR|Tractable likelihood\nLanguage|Autoregressive Transformer|Natural sequential structure\nFast fixed-domain image generation|GAN|One-pass inference (N=1)\nHigh-quality general image generation|Latent Diffusion / Flow|Flexible conditioning\nFast image generation|Flow Matching + Distillation|Few steps (N=1-8)\nImage editing|Diffusion / Flow + conditioning|Flexible controls\nVisual AR|VAR|Next-scale prediction (N=scales)\nLatent representation|VAE / VQ-VAE|Compression\nDensity estimation|Flow|Exact likelihood" } },

    { type: 'concept', data: {
      headingEn: 'Key Takeaways', headingKn: 'ಮುಖ್ಯ ಅಂಶಗಳು',
      bodyEn: '• Genuinely confirmed: the "N times faster" arithmetic worked out to 6.25x from a claimed 10x -- always decompose latency claims into step count x cost per step before trusting them\n• The Latency ~= N_sequential x Cost_parallel_stage approximation explains why GAN (N=1) is fastest, AR is slowest for long sequences (N=token count), and flow matching/VAR sit in between by reducing N through smarter parallelism (integration steps or scale count) rather than eliminating sequential structure entirely\n• Production systems routinely combine representation (VAE/VQ), architecture (Transformer/U-Net), and objective (diffusion/flow/GAN/AR) independently -- the task requirements (latency, quality, controllability, exactness of likelihood) should drive family selection more than the data modality itself',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: "N ಪಟ್ಟೂ ವೇಗ" arithmetic claim ಮಾಡಿದ 10x ಇಂದ 6.25x ಗೆ ಇಳಿಯಿತು -- ಯಾವಾಗಲೂ latency claims ಅನ್ನೂ ನಂಬುವ ಮೊದಲೂ step count x cost per step ಗೆ ಬೇರ್ಪಡಿಸಿ\n• Latency ~= N_sequential x Cost_parallel_stage approximation ಇದೂ ಏಕೆ GAN (N=1) ಅತ್ಯಂತ ವೇಗ, AR ಉದ್ದ sequences ಗೆ ಅತ್ಯಂತ ನಿಧಾನ (N=token count), ಮತ್ತು flow matching/VAR N ಅನ್ನೂ ಚುರುಕಾದ parallelism ಮೂಲಕ ಕಡಿಮೆಗೊಳಿಸುವ ಮೂಲಕ (integration steps ಅಥವಾ scale count) ನಡುವೆ ಇವೆ ಎಂದೂ ವಿವರಿಸುತ್ತದೆ, sequential ರಚನೆ ಸಂಪೂರ್ಣವಾಗಿ ತೆಗೆದುಹಾಕದೆ\n• Production systems ಸಾಮಾನ್ಯವಾಗಿ representation (VAE/VQ), architecture (Transformer/U-Net), ಮತ್ತು objective (diffusion/flow/GAN/AR) ಅನ್ನೂ ಸ್ವತಂತ್ರವಾಗಿ ಸಂಯೋಜಿಸುತ್ತವೆ -- ಟಾಸ್ಕ್ ಅಗತ್ಯಗಳು (latency, quality, controllability, likelihood ನ ನಿಖರತೆ) data modality ಗಿಂತ family ಆಯ್ಕೆಯನ್ನೂ ಹೆಚ್ಚು ಚಾಲಿಸಬೇಕು' } },
    { type: 'concept', data: {
      headingEn: 'AI Example', headingKn: 'AI Example',
      bodyEn: 'The genuinely computed 6.25x-vs-10x example in this lesson mirrors exactly how research teams report inference speedups for real distilled flow-matching or rectified-flow models (e.g. reducing a 30-step Stable-Diffusion-style sampler to a handful of steps): the honest number always comes from multiplying the real step-count reduction by the real per-step cost reduction, not from rounding up a partial improvement.',
      bodyKn: 'ಈ lesson ನಲ್ಲಿ ನಿಜವಾಗಿ ಗಣಿಸಿದ 6.25x-vs-10x example research teams ನಿಜ distilled flow-matching ಅಥವಾ rectified-flow models ಗಾಗಿ inference speedups ಹೇಗೆ ವರದಿ ಮಾಡುತ್ತಾರೆ ಎಂಬುದನ್ನೂ ನಿಖರವಾಗಿ ಪ್ರತಿಬಿಂಬಿಸುತ್ತದೆ (ಉದಾ. ಒಂದೂ 30-step Stable-Diffusion-style sampler ಅನ್ನೂ ಕೆಲವೂ steps ಗೆ ಕಡಿಮೆಗೊಳಿಸುವುದೂ): ಪ್ರಾಮಾಣಿಕ ಸಂಖ್ಯೆ ಯಾವಾಗಲೂ ನಿಜ step-count ಕಡಿತವನ್ನೂ ನಿಜ per-step cost ಕಡಿತದಿಂದ ಗುಣಿಸುವುದರಿಂದ ಬರುತ್ತದೆ, ಒಂದೂ ಭಾಗಶಃ ಸುಧಾರಣೆಯನ್ನೂ ಮೇಲ್ಮುಖವಾಗಿ ಸುತ್ತುವುದರಿಂದ ಅಲ್ಲ.' } },
    { type: 'concept', data: {
      headingEn: 'Why AI Uses This', headingKn: 'AI ಇದನ್ನೂ ಏಕೆ ಬಳಸುತ್ತದೆ',
      bodyEn: '• Genuinely confirmed: the Latency ~= N x Cost_per_stage model gives engineers a concrete lever list per family (AR: KV cache, batching, speculative decoding, token count; Diffusion: step count, latent resolution, precision, distillation; GAN: model size, batching, precision; VAR: number of scales, tokens per scale) -- turning an abstract "make it faster" request into specific, actionable engineering knobs\n• Separating representation from architecture from objective lets a team swap one axis (e.g. replace a U-Net with a DiT) without needing to redesign the entire system, which is exactly how the 2013-2026 history in Lesson 2 actually proceeded',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: Latency ~= N x Cost_per_stage model ಎಂಜಿನಿಯರ್‌ಗಳಿಗೆ ಪ್ರತಿ family ಗೆ ಒಂದೂ ನಿರ್ದಿಷ್ಟ lever list ಕೊಡುತ್ತದೆ (AR: KV cache, batching, speculative decoding, token count; Diffusion: step count, latent resolution, precision, distillation; GAN: model size, batching, precision; VAR: number of scales, tokens per scale) -- ಒಂದೂ ಅಮೂರ್ತ "ಇದೂ ವೇಗ ಮಾಡಿ" request ಅನ್ನೂ ನಿರ್ದಿಷ್ಟ, ಕಾರ್ಯಸಾಧ್ಯ engineering knobs ಗೆ ಪರಿವರ್ತಿಸುತ್ತಾ\n• Representation ಅನ್ನೂ architecture ಇಂದ objective ಇಂದ ಬೇರ್ಪಡಿಸುವುದೂ ಒಂದೂ team ಗೆ ಒಂದೂ axis ಬದಲಾಯಿಸಲು ಬಿಡುತ್ತದೆ (ಉದಾ. ಒಂದೂ U-Net ಅನ್ನೂ ಒಂದೂ DiT ಜೊತೆ ಬದಲಾಯಿಸುವುದೂ) ಸಂಪೂರ್ಣ system ಮರುವಿನ್ಯಾಸ ಮಾಡದೆ, Lesson 2 ನ 2013-2026 history ವಾಸ್ತವವಾಗಿ ಮುಂದುವರಿದ ಅದೇ ರೀತಿ' } },
    { type: 'concept', data: {
      headingEn: 'Real-World Example', headingKn: 'Real-World Example',
      bodyEn: 'A product team choosing between a GAN and a distilled flow-matching model for a real-time avatar generator genuinely applies this lesson\'s framework: they check N (GAN\'s N=1 vs. flow-matching\'s N=1-8), check whether they need exact likelihood (no), check whether the domain is narrow (yes, avatars), and check whether paired/labeled training data exists -- exactly the decision sequence this lesson\'s decision tree and table are built to support, with the genuinely computed speedup arithmetic used to sanity-check any vendor performance claims.',
      bodyKn: 'ಒಂದೂ real-time avatar generator ಗಾಗಿ ಒಂದೂ GAN ಮತ್ತು ಒಂದೂ distilled flow-matching model ನಡುವೆ ಆಯ್ಕೆ ಮಾಡುವ ಒಂದೂ product team ಈ lesson ನ framework ಅನ್ನೂ ನಿಜವಾಗಿ ಅನ್ವಯಿಸುತ್ತದೆ: ಅವರೂ N ಪರಿಶೀಲಿಸುತ್ತಾರೆ (GAN ನ N=1 vs. flow-matching ನ N=1-8), exact likelihood ಬೇಕೇ ಎಂದೂ ಪರಿಶೀಲಿಸುತ್ತಾರೆ (ಇಲ್ಲ), domain ಚಿಕ್ಕದೇ ಎಂದೂ ಪರಿಶೀಲಿಸುತ್ತಾರೆ (ಹೌದೂ, avatars), ಮತ್ತು paired/labeled training data ಅಸ್ತಿತ್ವದಲ್ಲಿದೆಯೇ ಎಂದೂ ಪರಿಶೀಲಿಸುತ್ತಾರೆ -- ಈ lesson ನ decision tree ಮತ್ತು table ಬೆಂಬಲಿಸಲು ನಿರ್ಮಿಸಿದ ನಿಖರ ನಿರ್ಧಾರ ಅನುಕ್ರಮ, ಯಾವುದೇ vendor performance claims sanity-check ಮಾಡಲು ನಿಜವಾಗಿ ಗಣಿಸಿದ speedup arithmetic ಬಳಸುತ್ತಾ.' } },

    { type: 'quiz', data: { questions: [
      { q: 'Genuinely confirmed: a vendor claims "10x faster than diffusion." Given 30 diffusion steps at cost 1.0 and 6 new-model steps at cost 0.8, what is the genuine speedup?', qKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: ಒಂದೂ vendor "10x faster than diffusion" ಎಂದೂ ಹೇಳುತ್ತದೆ. 30 diffusion steps ವೆಚ್ಚ 1.0 ಮತ್ತು 6 new-model steps ವೆಚ್ಚ 0.8 ಕೊಟ್ಟಾಗ, ನಿಜ speedup ಏನೂ?',
        opts: ['Exactly 10x as claimed', '6.25x -- genuinely computed as 30/4.8', '1x, no real speedup', '30x'], correct: 1,
        optsKn: ['ಹೇಳಿದಂತೆ ನಿಖರವಾಗಿ 10x', '6.25x -- 30/4.8 ಎಂದೂ ನಿಜವಾಗಿ ಗಣಿಸಿದ', '1x, ಯಾವುದೇ ನಿಜ speedup ಇಲ್ಲ', '30x'] },
      { q: 'Which family should you choose when the primary requirement is exact log p(x), such as for density estimation?', qKn: 'ಮುಖ್ಯ ಅಗತ್ಯ ನಿಖರ log p(x) ಆಗಿದ್ದಾಗ, density estimation ನಂತೆ, ಯಾವ family ಆಯ್ಕೆ ಮಾಡಬೇಕು?',
        opts: ['GAN', 'Normalizing Flow (or AR)', 'StyleGAN', 'Any diffusion model'], correct: 1,
        optsKn: ['GAN', 'Normalizing Flow (ಅಥವಾ AR)', 'StyleGAN', 'ಯಾವುದೇ diffusion model'] },
      { q: 'In the Latency ~= N_sequential x Cost_parallel_stage model, what is N for a GAN?', qKn: 'Latency ~= N_sequential x Cost_parallel_stage model ನಲ್ಲಿ, ಒಂದೂ GAN ಗೆ N ಏನೂ?',
        opts: ['N = token count', 'N = 1 (one generator forward pass)', 'N = number of scales', 'N = 20-50'], correct: 1,
        optsKn: ['N = token count', 'N = 1 (ಒಂದೂ generator forward pass)', 'N = scales ಸಂಖ್ಯೆ', 'N = 20-50'] },
      { q: 'Why is "is this model a Transformer or diffusion?" often the wrong question for a production system?', qKn: '"ಈ model ಒಂದೂ Transformer ಅಥವಾ diffusion?" ಒಂದೂ production system ಗೆ ಏಕೆ ಸಾಮಾನ್ಯವಾಗಿ ತಪ್ಪೂ ಪ್ರಶ್ನೆ?',
        opts: ['Because production systems never use Transformers', 'Because representation, architecture, and generative objective are independent choices that a production model can combine simultaneously', 'Because diffusion models cannot use Transformers', 'Because all production models are identical'], correct: 1,
        optsKn: ['ಏಕೆಂದರೆ production systems ಎಂದಿಗೂ Transformers ಬಳಸುವುದಿಲ್ಲ', 'ಏಕೆಂದರೆ representation, architecture, ಮತ್ತು generative objective ಸ್ವತಂತ್ರ choices, ಒಂದೂ production model ಏಕಕಾಲದಲ್ಲಿ ಸಂಯೋಜಿಸಬಹುದು', 'ಏಕೆಂದರೆ diffusion models Transformers ಬಳಸಲಾಗುವುದಿಲ್ಲ', 'ಏಕೆಂದರೆ ಎಲ್ಲಾ production models ಒಂದೇ ಆಗಿವೆ'] },
      { q: 'When should you specifically choose VAR over ordinary token-based autoregression for images?', qKn: 'Images ಗಾಗಿ ಸಾಮಾನ್ಯ token-based autoregression ಗಿಂತ ನಿರ್ದಿಷ್ಟವಾಗಿ VAR ಯಾವಾಗ ಆಯ್ಕೆ ಮಾಡಬೇಕು?',
        opts: ['When you need exact log p(x)', 'When you want a Transformer over discrete visual tokens but token-by-token raster ordering is inefficient', 'When no GPU is available', 'When the dataset has no images'], correct: 1,
        optsKn: ['ನಿಮಗೆ ನಿಖರ log p(x) ಬೇಕಾದಾಗ', 'ನಿಮಗೆ discrete visual tokens ಮೇಲೆ ಒಂದೂ Transformer ಬೇಕಾದಾಗ ಆದರೆ token-by-token raster ordering ಅಸಮರ್ಥವಾಗಿದ್ದಾಗ', 'ಯಾವುದೇ GPU ಲಭ್ಯವಿಲ್ಲದಿದ್ದಾಗ', 'Dataset ಯಾವುದೇ images ಹೊಂದಿಲ್ಲದಿದ್ದಾಗ'] },
    ] } },
  ],
};
