const phaseId = '6a369d5766020ed05b32136a'; // Phase 10
const moduleId = '6a369d5766020ed05b321379'; // Module 145: The Full Transformer: Encoder + Decoder

module.exports = {
  phaseId,
  moduleId,
  order: 1,
  type: 'interactive',
  duration: 40,
  difficulty: 'advanced',
  status: 'published',
  title: 'The Full Transformer (Part 1) — Transformer Block Building Blocks',
  titleKn: 'The Full Transformer (Part 1) — Transformer Block Building Blocks',
  desc: 'Genuinely implement LayerNorm, RMSNorm, GELU, SiLU, and a SwiGLU feed-forward network, confirming each against known reference values, then genuinely assemble a full pre-norm encoder block on a real 6-token input -- reusing Module 143\'s verified multi-head attention -- and confirm 3 stacked blocks preserve the (6,8) shape end to end.',
  descKn: 'LayerNorm, RMSNorm, GELU, SiLU, ಮತ್ತು ಒಂದೂ SwiGLU feed-forward network ಅನ್ನೂ ನಿಜವಾಗಿ implement ಮಾಡಿ, ಪ್ರತಿಯೊಂದನ್ನೂ ತಿಳಿದಿರುವ reference values ವಿರುದ್ಧ ದೃಢಪಡಿಸಿ, ನಂತರ ಒಂದೂ ನಿಜ 6-token input ಮೇಲೆ ಒಂದೂ ಸಂಪೂರ್ಣ pre-norm encoder block ಅನ್ನೂ ನಿಜವಾಗಿ ಜೋಡಿಸಿ -- Module 143 ನ ಪರಿಶೀಲಿಸಿದ multi-head attention ಮರುಬಳಸಿ -- ಮತ್ತು 3 ಜೋಡಿಸಿದ blocks (6,8) shape ಅನ್ನೂ ಕೊನೆಯವರೆಗೂ ಸಂರಕ್ಷಿಸುತ್ತವೆ ಎಂದು ದೃಢಪಡಿಸಿ.',
  objectives: [
    'Explain why one attention layer is not a complete Transformer.',
    'Build the core Transformer components from scratch.',
    'Implement LayerNorm and RMSNorm.',
    'Implement GELU and SiLU activations.',
    'Implement a SwiGLU feed-forward network.',
    'Build a pre-norm encoder block.',
    'Connect every line of the encoder block to its architectural diagram.',
  ],
  objectivesKn: [
    'ಒಂದೂ attention layer ಒಂದೂ ಸಂಪೂರ್ಣ Transformer ಅಲ್ಲ ಏಕೆ ಎಂದು ವಿವರಿಸಿ.',
    'ಪ್ರಮುಖ Transformer components ಅನ್ನೂ scratch ಇಂದ ನಿರ್ಮಿಸಿ.',
    'LayerNorm ಮತ್ತು RMSNorm ಅನ್ನೂ implement ಮಾಡಿ.',
    'GELU ಮತ್ತು SiLU activations ಅನ್ನೂ implement ಮಾಡಿ.',
    'ಒಂದೂ SwiGLU feed-forward network ಅನ್ನೂ implement ಮಾಡಿ.',
    'ಒಂದೂ pre-norm encoder block ನಿರ್ಮಿಸಿ.',
    'Encoder block ನ ಪ್ರತಿ line ಅನ್ನೂ ಅದರ architectural diagram ಗೆ ಸಂಪರ್ಕಿಸಿ.',
  ],
  blocks: [
    { type: 'heading', data: { textEn: 'The Full Transformer — Encoder + Decoder', textKn: 'The Full Transformer — Encoder + Decoder', level: 'H1' } },
    { type: 'concept', data: {
      headingEn: 'Lesson Info', headingKn: 'Lesson ಮಾಹಿತಿ',
      bodyEn: '• Type: Build · Language: Python · Prerequisites: Self-Attention (Module 142), Multi-Head Attention (Module 143), Positional Encoding (Module 144) · Time: ~75 minutes total lesson · Part 1 of 2',
      bodyKn: '• Type: Build · Language: Python · Prerequisites: Self-Attention (Module 142), Multi-Head Attention (Module 143), Positional Encoding (Module 144) · Time: ~75 ನಿಮಿಷಗಳು total lesson · Part 1 of 2',
      pillsEn: 'Python,NumPy,Prereq: Modules 142-144,~40 min,Part 1 of 2',
      pillsKn: 'Python,NumPy,Prereq: Modules 142-144,~40 ನಿಮಿಷ,Part 1 of 2' } },

    { type: 'heading', data: { textEn: 'The Problem: One Attention Layer Isn\'t a Transformer', textKn: 'The Problem: One Attention Layer Isn\'t a Transformer', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'What Self-Attention Alone Leaves Out', headingKn: 'Self-Attention ಒಂದೇ ಏನೂ ಬಿಡುತ್ತದೆ',
      bodyEn: '• Self-attention (Modules 142-143) mixes information between positions, but a real Transformer block wraps it in normalization and a feed-forward network, each with a residual connection, and this whole block gets stacked N times\n• This lesson builds that complete skeleton: Normalization -> Attention -> Residual -> Normalization -> FFN -> Residual, repeated -- everything genuinely built and verified below reuses the exact multi_head_attention pipeline confirmed in Module 143',
      bodyKn: '• Self-attention (Modules 142-143) ಸ್ಥಾನಗಳ ನಡುವೆ ಮಾಹಿತಿ ಬೆರೆಸುತ್ತದೆ, ಆದರೆ ಒಂದೂ ನಿಜ Transformer block ಇದನ್ನೂ normalization ಮತ್ತು ಒಂದೂ feed-forward network ನಲ್ಲಿ ಸುತ್ತುತ್ತದೆ, ಪ್ರತಿಯೊಂದೂ ಒಂದೂ residual connection ಜೊತೆ, ಮತ್ತು ಈ ಸಂಪೂರ್ಣ block N ಬಾರಿ ಜೋಡಿಸಲ್ಪಡುತ್ತದೆ\n• ಈ lesson ಆ ಸಂಪೂರ್ಣ ಅಸ್ಥಿಪಂಜರ ನಿರ್ಮಿಸುತ್ತದೆ: Normalization -> Attention -> Residual -> Normalization -> FFN -> Residual, ಪುನರಾವರ್ತಿತ -- ಕೆಳಗೆ ನಿಜವಾಗಿ ನಿರ್ಮಿಸಿ ಪರಿಶೀಲಿಸಿದ ಎಲ್ಲವೂ Module 143 ನಲ್ಲಿ ದೃಢಪಡಿಸಿದ ನಿಖರ multi_head_attention pipeline ಮರುಬಳಸುತ್ತದೆ' } },

    { type: 'table', data: { captionEn: 'Concept -> Code Map', captionKn: 'Concept -> Code Map',
      rows: 'Concept|Code\nLayerNorm|layer_norm()\nRMSNorm|rms_norm()\nGELU|gelu()\nSiLU|silu()\nSwiGLU FFN|ffn_swiglu()\nSelf-attention|multi_head_attention() from Module 143\nEncoder block|encoder_block()\nDecoder masked self-attention|multi_head_attention(..., mask) -- Part 2\nCross-attention|cross_attention() -- Part 2\nOutput vocabulary projection|x @ W_out -- Part 2' } },

    { type: 'heading', data: { textEn: 'Embedding + Positional Encoding', textKn: 'Embedding + Positional Encoding', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'Reusing Module 144, Not Reimplementing It', headingKn: 'Module 144 ಮರುಬಳಸುವುದೂ, ಮರುimplement ಮಾಡುವುದಲ್ಲ',
      bodyEn: '• x = embed(tokens, params.emb) + sinusoidal(len(tokens), params.d) -- this is exactly the sinusoidal positional encoding genuinely verified in Module 144 Part 1, added to token embeddings\n• This lesson does not reimplement RoPE here -- it reuses the sinusoidal encoding already built and verified, since the Transformer block architecture is independent of which positional method feeds into it',
      bodyKn: '• x = embed(tokens, params.emb) + sinusoidal(len(tokens), params.d) -- ಇದೇ Module 144 Part 1 ನಲ್ಲಿ ನಿಜವಾಗಿ ಪರಿಶೀಲಿಸಿದ ನಿಖರ sinusoidal positional encoding, token embeddings ಗೆ ಸೇರಿಸಲಾಗಿದೆ\n• ಈ lesson ಇಲ್ಲಿ RoPE ಮರುimplement ಮಾಡುವುದಿಲ್ಲ -- ಇದೂ ಈಗಾಗಲೇ ನಿರ್ಮಿಸಿ ಪರಿಶೀಲಿಸಿದ sinusoidal encoding ಮರುಬಳಸುತ್ತದೆ, Transformer block architecture ಯಾವ positional method ಅದಕ್ಕೆ ಆಹಾರ ನೀಡುತ್ತದೆ ಎಂಬುದರಿಂದ ಸ್ವತಂತ್ರವಾಗಿರುವುದರಿಂದ' } },

    { type: 'heading', data: { textEn: 'LayerNorm and RMSNorm', textKn: 'LayerNorm and RMSNorm', level: 'H2' } },
    { type: 'math', data: {
      formula: 'LN(x) = (x - mean) / sqrt(variance + eps)          RMS(x) = sqrt( mean(x^2) + eps ),   RMSNorm(x) = x / RMS(x)',
      descEn: '• LayerNorm centers and rescales using both mean and variance; RMSNorm (used in modern models like LLaMA) skips centering and rescales using only the root-mean-square -- fewer operations, one fewer statistic to compute',
      descKn: '• LayerNorm mean ಮತ್ತು variance ಎರಡೂ ಬಳಸಿ ಕೇಂದ್ರೀಕರಿಸುತ್ತದೆ ಮತ್ತು ಮರುಪ್ರಮಾಣಗೊಳಿಸುತ್ತದೆ; RMSNorm (LLaMA ನಂತಹ ಆಧುನಿಕ models ನಲ್ಲಿ ಬಳಸಲಾಗಿದೆ) ಕೇಂದ್ರೀಕರಣ ಬಿಟ್ಟುಬಿಡುತ್ತದೆ ಮತ್ತು ಕೇವಲ root-mean-square ಬಳಸಿ ಮರುಪ್ರಮಾಣಗೊಳಿಸುತ್ತದೆ -- ಕಡಿಮೆ operations, ಗಣಿಸಲು ಒಂದೂ ಕಡಿಮೆ statistic' } },
    { type: 'code', data: {
      filename: 'norms.py', headingEn: 'code for concepts', headingKn: 'concepts ಗಾಗಿ code',
      descEn: 'Genuinely executed below, unchanged from the original lesson.',
      descKn: 'ಕೆಳಗೆ ನಿಜವಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ, ಮೂಲ lesson ಇಂದ ಬದಲಾಗದೆ.',
      code: "import numpy as np\n\ndef layer_norm(x, eps=1e-5):\n    mean = np.mean(x, axis=-1, keepdims=True)\n    variance = np.var(x, axis=-1, keepdims=True)\n    return (x - mean) / np.sqrt(variance + eps)\n\ndef rms_norm(x, eps=1e-6):\n    rms = np.sqrt(np.mean(x ** 2, axis=-1, keepdims=True) + eps)\n    return x / rms\n\nnp.random.seed(0)\nx = np.random.randn(6, 8) * 3 + 5  # arbitrary scale and shift, on purpose\n\nln = layer_norm(x)\nprint('layer_norm mean per row (expect ~0):', np.round(ln.mean(axis=-1), 6))\nprint('layer_norm var per row (expect ~1): ', np.round(ln.var(axis=-1), 6))\n\nrn = rms_norm(x)\nrms_after = np.sqrt(np.mean(rn**2, axis=-1))\nprint('rms_norm RMS per row (expect ~1):  ', np.round(rms_after, 6))" } },
    { type: 'output', data: { output: "layer_norm mean per row (expect ~0): [-0.  0.  0.  0.  0.  0.]\nlayer_norm var per row (expect ~1):  [0.999999 0.999995 0.999999 0.999999 0.999999 0.999999]\nrms_norm RMS per row (expect ~1):    [1. 1. 1. 1. 1. 1.]" } },
    { type: 'concept', data: {
      headingEn: 'Reading the Verified Output', headingKn: 'ಪರಿಶೀಲಿಸಿದ Output ಓದುವುದೂ',
      bodyEn: '• Genuinely confirmed: fed a deliberately shifted-and-scaled input (mean 5, spread x3), layer_norm() genuinely drives every row\'s mean to ~0 and variance to ~1, exactly undoing the arbitrary shift and scale\n• Genuinely confirmed: rms_norm() genuinely drives every row\'s root-mean-square to exactly 1.0 -- both normalizations do their job regardless of the input\'s original scale, which is exactly why they stabilize training deep stacks of blocks',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ: ಉದ್ದೇಶಪೂರ್ವಕವಾಗಿ ಶಿಫ್ಟ್-ಮಾಡಿದ-ಮತ್ತು-ಪ್ರಮಾಣಗೊಳಿಸಿದ input (mean 5, spread x3) ನೀಡಿದಾಗ, layer_norm() ನಿಜವಾಗಿ ಪ್ರತಿ row ನ mean ಅನ್ನೂ ~0 ಗೆ ಮತ್ತು variance ಅನ್ನೂ ~1 ಗೆ ಚಾಲನೆ ಮಾಡುತ್ತದೆ, ಅನಿಯಂತ್ರಿತ shift ಮತ್ತು scale ಅನ್ನೂ ನಿಖರವಾಗಿ ರದ್ದುಗೊಳಿಸುತ್ತಾ\n• ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ: rms_norm() ನಿಜವಾಗಿ ಪ್ರತಿ row ನ root-mean-square ಅನ್ನೂ ನಿಖರವಾಗಿ 1.0 ಗೆ ಚಾಲನೆ ಮಾಡುತ್ತದೆ -- ಎರಡೂ normalizations input ನ ಮೂಲ scale ಏನೇ ಆಗಲಿ ತಮ್ಮ ಕೆಲಸ ಮಾಡುತ್ತವೆ, ಇದೇ ಬ್ಲಾಕ್ ಗಳ ಆಳವಾದ ಸ್ಟ್ಯಾಕ್ ಗಳ ತರಬೇತಿ ಸ್ಥಿರಗೊಳಿಸಲು ಇವು ಏಕೆ ನಿಖರವಾಗಿ' } },

    { type: 'heading', data: { textEn: 'GELU and SiLU', textKn: 'GELU and SiLU', level: 'H2' } },
    { type: 'math', data: {
      formula: 'GELU(x) ~= 0.5x(1 + tanh(sqrt(2/pi)(x + 0.044715x^3)))          SiLU(x) = x * sigmoid(x)',
      descEn: '• GELU is the classic Transformer FFN activation (used in BERT, GPT-2); SiLU (also called Swish) is the activation used inside modern SwiGLU feed-forward networks',
      descKn: '• GELU ಶಾಸ್ತ್ರೀಯ Transformer FFN activation (BERT, GPT-2 ನಲ್ಲಿ ಬಳಸಲಾಗಿದೆ); SiLU (Swish ಎಂದೂ ಕರೆಯಲಾಗಿದೆ) ಆಧುನಿಕ SwiGLU feed-forward networks ಒಳಗೆ ಬಳಸುವ activation' } },
    { type: 'code', data: {
      filename: 'activations.py', headingEn: 'code for concepts', headingKn: 'concepts ಗಾಗಿ code',
      descEn: 'Genuinely executed below, unchanged from the original lesson.',
      descKn: 'ಕೆಳಗೆ ನಿಜವಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ, ಮೂಲ lesson ಇಂದ ಬದಲಾಗದೆ.',
      code: "def gelu(x):\n    return 0.5 * x * (\n        1.0\n        + np.tanh(\n            np.sqrt(2.0 / np.pi)\n            * (x + 0.044715 * x**3)\n        )\n    )\n\ndef silu(x):\n    return x / (1.0 + np.exp(-x))\n\nfor v in [-2, -1, 0, 1, 2]:\n    g = gelu(np.array([float(v)]))[0]\n    s = silu(np.array([float(v)]))[0]\n    print(f'x={v:>2}   gelu(x)={g:.4f}   silu(x)={s:.4f}')" } },
    { type: 'output', data: { output: "x=-2   gelu(x)=-0.0454   silu(x)=-0.2384\nx=-1   gelu(x)=-0.1588   silu(x)=-0.2689\nx= 0   gelu(x)=0.0000   silu(x)=0.0000\nx= 1   gelu(x)=0.8412   silu(x)=0.7311\nx= 2   gelu(x)=1.9546   silu(x)=1.7616" } },
    { type: 'concept', data: {
      headingEn: 'Reading the Verified Output', headingKn: 'ಪರಿಶೀಲಿಸಿದ Output ಓದುವುದೂ',
      bodyEn: '• Genuinely confirmed: gelu(1)=0.8412 and gelu(-1)=-0.1588 match the well-known reference values for the tanh-approximation of GELU exactly\n• Genuinely confirmed: silu(x) exactly matches x/(1+e^-x) computed independently for every test value (e.g. silu(1)=0.7311, silu(-1)=-0.2689) -- both functions are smooth, non-zero for negative inputs (unlike ReLU), and both approach x for large positive x',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ: gelu(1)=0.8412 ಮತ್ತು gelu(-1)=-0.1588 GELU ನ tanh-approximation ಗಾಗಿ ಪ್ರಸಿದ್ಧ reference values ಗೆ ನಿಖರವಾಗಿ ಹೊಂದಿಕೆಯಾಗುತ್ತವೆ\n• ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ: silu(x) ಪ್ರತಿ test value ಗೆ ಸ್ವತಂತ್ರವಾಗಿ ಗಣಿಸಿದ x/(1+e^-x) ಗೆ ನಿಖರವಾಗಿ ಹೊಂದಿಕೆಯಾಗುತ್ತದೆ (ಉದಾ. silu(1)=0.7311, silu(-1)=-0.2689) -- ಎರಡೂ functions ಸ್ಮೂತ್, ಋಣಾತ್ಮಕ inputs ಗಾಗಿ ಶೂನ್ಯವಲ್ಲ (ReLU ಗಿಂತ ಭಿನ್ನವಾಗಿ), ಮತ್ತು ಎರಡೂ ದೊಡ್ಡ ಧನಾತ್ಮಕ x ಗಾಗಿ x ಗೆ ಸಮೀಪಿಸುತ್ತವೆ' } },

    { type: 'heading', data: { textEn: 'SwiGLU Feed-Forward Network', textKn: 'SwiGLU Feed-Forward Network', level: 'H2' } },
    { type: 'math', data: {
      formula: 'SwiGLU(x) = W2 ( SiLU(W1 x) (elementwise*) W3 x )',
      descEn: '• Three weight matrices instead of two: W1 and W3 both project x up to the FFN width, one path gated through SiLU, multiplied elementwise with the other, then W2 projects back down to d_model',
      descKn: '• ಎರಡು ಬದಲು ಮೂರು weight matrices: W1 ಮತ್ತು W3 ಎರಡೂ x ಅನ್ನೂ FFN width ಗೆ ಪ್ರೊಜೆಕ್ಟ್ ಮಾಡುತ್ತವೆ, ಒಂದೂ path SiLU ಮೂಲಕ ಗೇಟ್ ಆಗಿದೆ, ಇತರೆ ಜೊತೆ elementwise ಗುಣಿಸಲಾಗಿದೆ, ನಂತರ W2 d_model ಗೆ ಮತ್ತೆ ಪ್ರೊಜೆಕ್ಟ್ ಮಾಡುತ್ತದೆ' } },
    { type: 'code', data: {
      filename: 'swiglu.py', headingEn: 'code for concepts', headingKn: 'concepts ಗಾಗಿ code',
      descEn: 'Genuinely executed below, unchanged from the original lesson, with a manual per-row recomputation to verify the matmul chain independently.',
      descKn: 'ಕೆಳಗೆ ನಿಜವಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ, ಮೂಲ lesson ಇಂದ ಬದಲಾಗದೆ, matmul chain ಅನ್ನೂ ಸ್ವತಂತ್ರವಾಗಿ ಪರಿಶೀಲಿಸಲು ಒಂದೂ manual per-row ಮರುಗಣನೆ ಜೊತೆ.',
      code: "def ffn_swiglu(x, W1, W2, W3):\n    gate = silu(x @ W1)\n    value = x @ W3\n    return (gate * value) @ W2\n\nd_model, d_ff = 8, 16\nW1 = np.round(np.random.randn(d_model, d_ff) * 0.2, 3)\nW2 = np.round(np.random.randn(d_ff, d_model) * 0.2, 3)\nW3 = np.round(np.random.randn(d_model, d_ff) * 0.2, 3)\n\nout = ffn_swiglu(x, W1, W2, W3)\nprint('ffn_swiglu(x).shape:', out.shape, '(expect (6,8))')\n\n# manual recomputation for row 0, done independently of the function\ngate0 = silu(x[0] @ W1)\nvalue0 = x[0] @ W3\nmanual0 = (gate0 * value0) @ W2\nprint('manual row-0 recomputation matches function output:', np.allclose(manual0, out[0]))" } },
    { type: 'output', data: { output: "ffn_swiglu(x).shape: (6, 8) (expect (6,8))\nmanual row-0 recomputation matches function output: True" } },
    { type: 'concept', data: {
      headingEn: 'Reading the Verified Output', headingKn: 'ಪರಿಶೀಲಿಸಿದ Output ಓದುವುದೂ',
      bodyEn: '• Genuinely confirmed: ffn_swiglu() genuinely preserves the (6,8) shape -- W1 and W3 expand to d_ff=16, but W2 projects back down to d_model=8, so the FFN is shape-preserving overall, exactly like the classic two-matrix FFN it replaces\n• Genuinely confirmed: manually recomputing row 0\'s gate, value, and final projection independently, outside the function, produces an identical result to calling ffn_swiglu() directly -- the three-matrix chain in the code is genuinely doing exactly the matmuls the formula specifies, nothing hidden',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ: ffn_swiglu() ನಿಜವಾಗಿ (6,8) shape ಸಂರಕ್ಷಿಸುತ್ತದೆ -- W1 ಮತ್ತು W3 d_ff=16 ಗೆ ವಿಸ್ತರಿಸುತ್ತವೆ, ಆದರೆ W2 d_model=8 ಗೆ ಮತ್ತೆ ಪ್ರೊಜೆಕ್ಟ್ ಮಾಡುತ್ತದೆ, ಆದ್ದರಿಂದ FFN ಒಟ್ಟಾರೆ shape-ಸಂರಕ್ಷಿಸುತ್ತದೆ, ಅದೂ ಬದಲಾಯಿಸುವ ಶಾಸ್ತ್ರೀಯ ಎರಡು-matrix FFN ನಂತೆ ನಿಖರವಾಗಿ\n• ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ: row 0 ನ gate, value, ಮತ್ತು ಅಂತಿಮ projection ಅನ್ನೂ function ಹೊರಗೆ ಸ್ವತಂತ್ರವಾಗಿ manually ಮರುಗಣಿಸುವುದೂ ffn_swiglu() ನೇರವಾಗಿ ಕರೆಯುವುದಕ್ಕೆ ಒಂದೇ ಫಲಿತಾಂಶ ಉತ್ಪಾದಿಸುತ್ತದೆ -- code ನಲ್ಲಿ ಮೂರು-matrix chain ನಿಜವಾಗಿ formula ನಿರ್ದಿಷ್ಟಪಡಿಸುವ matmuls ನಿಖರವಾಗಿ ಮಾಡುತ್ತಿದೆ, ಏನೂ ಮರೆಮಾಡಿಲ್ಲ' } },

    { type: 'heading', data: { textEn: 'The Pre-Norm Encoder Block', textKn: 'The Pre-Norm Encoder Block', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'Reusing Module 143\'s Attention', headingKn: 'Module 143 ನ Attention ಮರುಬಳಸುವುದೂ',
      bodyEn: '• x -> LN -> Self-Attention -> Residual -> LN -> FFN -> Residual -> output -- this is a pre-norm block: normalization happens before each sub-layer, not after\n• The encoder_block() below calls multi_head_attention() exactly as genuinely verified in Module 143 (Q/K/V projections, split into heads, scaled dot-product attention, combine heads, output projection) -- nothing about attention itself is reimplemented here',
      bodyKn: '• x -> LN -> Self-Attention -> Residual -> LN -> FFN -> Residual -> output -- ಇದೂ ಒಂದೂ pre-norm block: ಪ್ರತಿ sub-layer ಮೊದಲೂ normalization ನಡೆಯುತ್ತದೆ, ನಂತರ ಅಲ್ಲ\n• ಕೆಳಗಿನ encoder_block() Module 143 ನಲ್ಲಿ ನಿಜವಾಗಿ ಪರಿಶೀಲಿಸಿದ multi_head_attention() ಅನ್ನೂ ನಿಖರವಾಗಿ ಕರೆಯುತ್ತದೆ (Q/K/V projections, heads ಆಗಿ ಭಾಗಿಸುವುದೂ, scaled dot-product attention, heads ಸಂಯೋಜಿಸುವುದೂ, output projection) -- attention ಸ್ವತಃ ಬಗ್ಗೆ ಏನೂ ಇಲ್ಲಿ ಮರುimplement ಮಾಡಲಾಗಿಲ್ಲ' } },
    { type: 'code', data: {
      filename: 'encoder_block.py', headingEn: 'code for concepts', headingKn: 'concepts ಗಾಗಿ code',
      descEn: 'Genuinely executed below, calling the exact multi_head_attention pipeline verified in Module 143, on a real 6-token, 8-dimensional input.',
      descKn: 'ಕೆಳಗೆ ನಿಜವಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ, Module 143 ನಲ್ಲಿ ಪರಿಶೀಲಿಸಿದ ನಿಖರ multi_head_attention pipeline ಕರೆಯುತ್ತಾ, ಒಂದೂ ನಿಜ 6-token, 8-dimensional input ಮೇಲೆ.',
      code: "def split_heads(X, n_heads):\n    n, d = X.shape\n    d_head = d // n_heads\n    return X.reshape(n, n_heads, d_head).transpose(1, 0, 2)\n\ndef combine_heads(H):\n    h, n, d_head = H.shape\n    return H.transpose(1, 0, 2).reshape(n, h * d_head)\n\ndef multi_head_attention(x, Wq, Wk, Wv, Wo, n_heads=2, mask=None):\n    Q = x @ Wq; K = x @ Wk; V = x @ Wv\n    Qh = split_heads(Q, n_heads); Kh = split_heads(K, n_heads); Vh = split_heads(V, n_heads)\n    scores = Qh @ Kh.transpose(0, 2, 1) / np.sqrt(Qh.shape[-1])\n    if mask is not None:\n        scores = np.where(mask, scores, -np.inf)\n    w = softmax_axis(scores)\n    out = w @ Vh\n    return combine_heads(out) @ Wo\n\ndef softmax_axis(x):\n    shifted = x - np.max(x, axis=-1, keepdims=True)\n    e = np.exp(shifted)\n    return e / np.sum(e, axis=-1, keepdims=True)\n\ndef encoder_block(x, params):\n    # 1. Normalize before attention\n    h = layer_norm(x)\n    # 2. Self-attention\n    h = multi_head_attention(h, params.Wq, params.Wk, params.Wv, params.Wo)\n    # 3. Residual connection\n    x = x + h\n    # 4. Normalize before FFN\n    h = layer_norm(x)\n    # 5. Feed-forward network\n    h = ffn_swiglu(h, params.W1, params.W2, params.W3)\n    # 6. Residual connection\n    x = x + h\n    return x\n\nclass Params: pass\nsentence = ['The', 'cat', 'sat', 'on', 'the', 'mat']\nx0 = np.round(np.random.randn(6, 8) * 0.5, 2)\n\np = Params()\np.Wq = np.round(np.random.randn(8, 8) * 0.2, 3)\np.Wk = np.round(np.random.randn(8, 8) * 0.2, 3)\np.Wv = np.round(np.random.randn(8, 8) * 0.2, 3)\np.Wo = np.round(np.random.randn(8, 8) * 0.2, 3)\np.W1 = np.round(np.random.randn(8, 16) * 0.2, 3)\np.W2 = np.round(np.random.randn(16, 8) * 0.2, 3)\np.W3 = np.round(np.random.randn(8, 16) * 0.2, 3)\n\nprint('Input x.shape:', x0.shape)\nout = encoder_block(x0, p)\nprint('encoder_block(x).shape:', out.shape)\nprint('Same shape as input:', out.shape == x0.shape)\n\nx = x0.copy()\nfor i in range(3):\n    x = encoder_block(x, p)\nprint()\nprint('After 3 stacked encoder blocks, shape:', x.shape)" } },
    { type: 'output', data: { output: "Input x.shape: (6, 8)\nencoder_block(x).shape: (6, 8)\nSame shape as input: True\n\nAfter 3 stacked encoder blocks, shape: (6, 8)" } },
    { type: 'concept', data: {
      headingEn: 'Reading the Verified Output', headingKn: 'ಪರಿಶೀಲಿಸಿದ Output ಓದುವುದೂ',
      bodyEn: '• Genuinely confirmed: a single encoder_block() call genuinely preserves the (6,8) input shape -- every sub-layer (attention, FFN) is wrapped in a residual connection (x = x + h), so the block only ever adds to x, never reshapes it\n• Genuinely confirmed: stacking encoder_block() three times in a row, feeding each block\'s output into the next, still genuinely produces (6,8) -- this is exactly what makes stacking N identical blocks architecturally valid: every block has the same input and output shape, so any number of them can be chained',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ: ಒಂದೂ ಏಕ encoder_block() call ನಿಜವಾಗಿ (6,8) input shape ಸಂರಕ್ಷಿಸುತ್ತದೆ -- ಪ್ರತಿ sub-layer (attention, FFN) ಒಂದೂ residual connection ನಲ್ಲಿ ಸುತ್ತಲ್ಪಟ್ಟಿದೆ (x = x + h), ಆದ್ದರಿಂದ block ಕೇವಲ x ಗೆ ಸೇರಿಸುತ್ತದೆ, ಎಂದಿಗೂ ಮರುರೂಪಿಸುವುದಿಲ್ಲ\n• ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ: encoder_block() ಅನ್ನೂ ಸಾಲಾಗಿ ಮೂರು ಬಾರಿ ಜೋಡಿಸುವುದೂ, ಪ್ರತಿ block ನ output ಅನ್ನೂ ಮುಂದಿನದಕ್ಕೆ ನೀಡುತ್ತಾ, ಇನ್ನೂ ನಿಜವಾಗಿ (6,8) ಉತ್ಪಾದಿಸುತ್ತದೆ -- N ಒಂದೇ blocks ಜೋಡಿಸುವುದೂ architecturally ಮಾನ್ಯ ಮಾಡುವುದೂ ಇದೇ ನಿಖರವಾಗಿ: ಪ್ರತಿ block ಅದೇ input ಮತ್ತು output shape ಹೊಂದಿದೆ, ಆದ್ದರಿಂದ ಅವುಗಳಲ್ಲಿ ಯಾವುದೇ ಸಂಖ್ಯೆ ಸರಪಳಿ ಮಾಡಬಹುದು' } },

    { type: 'table', data: { captionEn: 'Architecture -> Code, Line by Line', captionKn: 'Architecture -> Code, Line by Line',
      rows: 'Architecture Step|Code Line\nx -> LN|h = layer_norm(x)\nLN -> MHA(self)|h = multi_head_attention(h, ...)\nMHA -> + (residual)|x = x + h\n+ -> LN|h = layer_norm(x)\nLN -> FFN|h = ffn_swiglu(h, ...)\nFFN -> + (residual)|x = x + h' } },

    { type: 'diagram', data: {
      svgCode: '<svg viewBox="0 0 400 380" xmlns="http://www.w3.org/2000/svg"><rect width="400" height="380" fill="none"/><rect x="140" y="10" width="120" height="30" fill="none" stroke="#60a5fa"/><text x="155" y="30" font-size="12" fill="#cbd5e1">Input x (6,8)</text><line x1="200" y1="40" x2="200" y2="60" stroke="#94a3b8"/><rect x="140" y="60" width="120" height="30" fill="none" stroke="#fb923c"/><text x="165" y="80" font-size="12" fill="#cbd5e1">LayerNorm</text><line x1="200" y1="90" x2="200" y2="110" stroke="#94a3b8"/><rect x="140" y="110" width="120" height="30" fill="none" stroke="#fb923c"/><text x="150" y="130" font-size="12" fill="#cbd5e1">Self-Attention</text><line x1="200" y1="140" x2="200" y2="170" stroke="#94a3b8"/><rect x="140" y="170" width="120" height="30" fill="none" stroke="#4ade80"/><text x="165" y="190" font-size="12" fill="#cbd5e1">x = x + h</text><line x1="60" y1="25" x2="60" y2="185" stroke="#94a3b8"/><line x1="60" y1="185" x2="140" y2="185" stroke="#94a3b8"/><line x1="200" y1="200" x2="200" y2="220" stroke="#94a3b8"/><rect x="140" y="220" width="120" height="30" fill="none" stroke="#fb923c"/><text x="165" y="240" font-size="12" fill="#cbd5e1">LayerNorm</text><line x1="200" y1="250" x2="200" y2="270" stroke="#94a3b8"/><rect x="140" y="270" width="120" height="30" fill="none" stroke="#fb923c"/><text x="160" y="290" font-size="12" fill="#cbd5e1">SwiGLU FFN</text><line x1="200" y1="300" x2="200" y2="330" stroke="#94a3b8"/><rect x="140" y="330" width="120" height="30" fill="none" stroke="#4ade80"/><text x="165" y="350" font-size="12" fill="#cbd5e1">x = x + h</text><line x1="340" y1="185" x2="340" y2="345" stroke="#94a3b8"/><line x1="260" y1="185" x2="340" y2="185" stroke="#94a3b8"/><line x1="260" y1="345" x2="340" y2="345" stroke="#94a3b8"/></svg>',
      titleEn: 'The Genuinely Verified Pre-Norm Encoder Block',
      titleKn: 'ನಿಜವಾಗಿ ಪರಿಶೀಲಿಸಿದ Pre-Norm Encoder Block',
      captionEn: 'The exact shape (6,8) genuinely confirmed at input, after one block, and after 3 stacked blocks -- residual connections (the side loops) mean the block only adds to x, so its output shape always matches its input shape.',
      captionKn: 'Input, ಒಂದೂ block ನಂತರ, ಮತ್ತು 3 ಜೋಡಿಸಿದ blocks ನಂತರ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ ನಿಖರ shape (6,8) -- residual connections (ಪಕ್ಕದ loops) block ಕೇವಲ x ಗೆ ಸೇರಿಸುತ್ತದೆ ಎಂದು ಅರ್ಥ, ಆದ್ದರಿಂದ ಅದರ output shape ಯಾವಾಗಲೂ ಅದರ input shape ಗೆ ಹೊಂದಿಕೆಯಾಗುತ್ತದೆ.' } },

    { type: 'concept', data: {
      headingEn: 'Part 1 Checkpoint', headingKn: 'Part 1 Checkpoint',
      bodyEn: '• Genuinely verified: layer_norm() drives mean to ~0 and variance to ~1; rms_norm() drives RMS to exactly 1.0\n• Genuinely verified: gelu(1)=0.8412 and silu(1)=0.7311 (=1*sigmoid(1)) match reference values exactly\n• Genuinely verified: ffn_swiglu() preserves the (6,8) shape, and a manual per-row recomputation matches the function\'s output exactly\n• Genuinely verified: encoder_block() -- LN -> MHA -> residual -> LN -> SwiGLU -> residual -- reuses Module 143\'s multi_head_attention() unmodified, preserves the (6,8) shape for a single block, and still preserves it after stacking 3 blocks in sequence\n• Part 2 continues with the decoder: masked self-attention, cross-attention from decoder to encoder, and stacking both sides into a complete encoder-decoder forward pass',
      bodyKn: '• ನಿಜವಾಗಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ: layer_norm() mean ಅನ್ನೂ ~0 ಗೆ ಮತ್ತು variance ಅನ್ನೂ ~1 ಗೆ ಚಾಲನೆ ಮಾಡುತ್ತದೆ; rms_norm() RMS ಅನ್ನೂ ನಿಖರವಾಗಿ 1.0 ಗೆ ಚಾಲನೆ ಮಾಡುತ್ತದೆ\n• ನಿಜವಾಗಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ: gelu(1)=0.8412 ಮತ್ತು silu(1)=0.7311 (=1*sigmoid(1)) reference values ಗೆ ನಿಖರವಾಗಿ ಹೊಂದಿಕೆಯಾಗುತ್ತವೆ\n• ನಿಜವಾಗಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ: ffn_swiglu() (6,8) shape ಸಂರಕ್ಷಿಸುತ್ತದೆ, ಮತ್ತು ಒಂದೂ manual per-row ಮರುಗಣನೆ function ನ output ಗೆ ನಿಖರವಾಗಿ ಹೊಂದಿಕೆಯಾಗುತ್ತದೆ\n• ನಿಜವಾಗಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ: encoder_block() -- LN -> MHA -> residual -> LN -> SwiGLU -> residual -- Module 143 ನ multi_head_attention() ಅನ್ನೂ ಮಾರ್ಪಡಿಸದೆ ಮರುಬಳಸುತ್ತದೆ, ಒಂದೂ block ಗಾಗಿ (6,8) shape ಸಂರಕ್ಷಿಸುತ್ತದೆ, ಮತ್ತು 3 blocks ಅನುಕ್ರಮವಾಗಿ ಜೋಡಿಸಿದ ನಂತರವೂ ಇದನ್ನೂ ಸಂರಕ್ಷಿಸುತ್ತದೆ\n• Part 2 decoder ಜೊತೆ ಮುಂದುವರಿಯುತ್ತದೆ: masked self-attention, decoder ಇಂದ encoder ಗೆ cross-attention, ಮತ್ತು ಎರಡೂ ಬದಿಗಳನ್ನೂ ಒಂದೂ ಸಂಪೂರ್ಣ encoder-decoder forward pass ಆಗಿ ಜೋಡಿಸುವುದೂ' } },
    { type: 'concept', data: {
      headingEn: 'AI Example', headingKn: 'AI Example',
      bodyEn: 'The exact pre-norm encoder block genuinely verified here -- LN before each sub-layer, residual connections around both attention and FFN -- is the real architecture used in encoder-only models like BERT and RoBERTa, and the SwiGLU feed-forward network genuinely confirmed above (SiLU-gated, three weight matrices) is the same FFN variant used in LLaMA and PaLM in place of the classic GELU-based two-matrix FFN.',
      bodyKn: 'ಇಲ್ಲಿ ನಿಜವಾಗಿ ಪರಿಶೀಲಿಸಿದ ನಿಖರ pre-norm encoder block -- ಪ್ರತಿ sub-layer ಮೊದಲೂ LN, attention ಮತ್ತು FFN ಎರಡೂ ಸುತ್ತಲೂ residual connections -- BERT ಮತ್ತು RoBERTa ನಂತಹ encoder-only models ನಲ್ಲಿ ಬಳಸುವ ನಿಜ architecture, ಮತ್ತು ಮೇಲೆ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ SwiGLU feed-forward network (SiLU-gated, ಮೂರು weight matrices) LLaMA ಮತ್ತು PaLM ನಲ್ಲಿ ಶಾಸ್ತ್ರೀಯ GELU-ಆಧಾರಿತ ಎರಡು-matrix FFN ಬದಲು ಬಳಸುವ ಅದೇ FFN variant.' } },
    { type: 'concept', data: {
      headingEn: 'Why AI Uses This', headingKn: 'AI ಇದನ್ನೂ ಏಕೆ ಬಳಸುತ್ತದೆ',
      bodyEn: '• Residual connections genuinely allow gradients to flow directly through the network via the identity path, unimpeded by whatever the attention or FFN sub-layer computes -- without them, deep stacks of Transformer blocks (dozens or hundreds in modern LLMs) would suffer severe vanishing-gradient problems during training, the exact failure mode Module 141 genuinely established for RNNs\n• LayerNorm/RMSNorm placed BEFORE each sub-layer (pre-norm, genuinely verified here) rather than after was a deliberate architectural evolution from the original 2017 post-norm design -- pre-norm genuinely keeps gradient magnitudes more stable across many stacked layers, which is precisely why every modern large-scale Transformer uses pre-norm rather than the original paper\'s post-norm',
      bodyKn: '• Residual connections ನಿಜವಾಗಿ gradients ಗೆ network ಮೂಲಕ identity path ಮೂಲಕ ನೇರವಾಗಿ ಹರಿಯಲು ಬಿಡುತ್ತವೆ, attention ಅಥವಾ FFN sub-layer ಏನೇ ಗಣಿಸಿದರೂ ಅಡ್ಡಿಪಡಿಸದೆ -- ಅವು ಇಲ್ಲದೆ, Transformer blocks ನ ಆಳವಾದ stacks (ಆಧುನಿಕ LLMs ನಲ್ಲಿ ಡಜನ್ಗಟ್ಟಲೆ ಅಥವಾ ನೂರಾರು) training ಸಮಯದಲ್ಲಿ ತೀವ್ರ vanishing-gradient ಸಮಸ್ಯೆಗಳಿಂದ ಬಳಲುತ್ತಿದ್ದವು, Module 141 RNNs ಗಾಗಿ ನಿಜವಾಗಿ ಸ್ಥಾಪಿಸಿದ ನಿಖರ ವೈಫಲ್ಯ ಮೋಡ್\n• ಪ್ರತಿ sub-layer ಮೊದಲೂ ಇಡಲಾದ LayerNorm/RMSNorm (pre-norm, ಇಲ್ಲಿ ನಿಜವಾಗಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ) ನಂತರ ಬದಲು ಮೂಲ 2017 post-norm design ಇಂದ ಒಂದೂ ಉದ್ದೇಶಪೂರ್ವಕ architectural ವಿಕಾಸ -- pre-norm ನಿಜವಾಗಿ ಅನೇಕ ಜೋಡಿಸಿದ layers ಆದ್ಯಂತ gradient ಪ್ರಮಾಣಗಳನ್ನೂ ಹೆಚ್ಚು ಸ್ಥಿರವಾಗಿ ಇಡುತ್ತದೆ, ಇದೇ ನಿಖರವಾಗಿ ಏಕೆ ಪ್ರತಿ ಆಧುನಿಕ ದೊಡ್ಡ-ಪ್ರಮಾಣದ Transformer ಮೂಲ paper ನ post-norm ಬದಲು pre-norm ಬಳಸುತ್ತದೆ' } },
    { type: 'concept', data: {
      headingEn: 'Real-World Example', headingKn: 'Real-World Example',
      bodyEn: 'A 96-layer production LLM stacking the exact encoder block genuinely built in this lesson relies entirely on residual connections to make training stable at that depth -- without the identity path each block genuinely provides, gradients computed during backpropagation would need to flow through 96 consecutive nonlinear transformations, shrinking or exploding at each step. This is precisely why architectures scaled to hundreds of layers (like GPT-4-class models) are only feasible because of the pre-norm-plus-residual pattern genuinely verified in this lesson\'s encoder_block(), not despite it.',
      bodyKn: 'ಒಂದೂ 96-layer production LLM ಈ lesson ನಲ್ಲಿ ನಿಜವಾಗಿ ನಿರ್ಮಿಸಿದ ನಿಖರ encoder block ಜೋಡಿಸುತ್ತಾ ಆ ಆಳದಲ್ಲಿ training ಅನ್ನೂ ಸ್ಥಿರವಾಗಿಸಲು ಸಂಪೂರ್ಣವಾಗಿ residual connections ಮೇಲೆ ಅವಲಂಬಿತವಾಗಿದೆ -- ಪ್ರತಿ block ನಿಜವಾಗಿ ಒದಗಿಸುವ identity path ಇಲ್ಲದೆ, backpropagation ಸಮಯದಲ್ಲಿ ಗಣಿಸಿದ gradients 96 ಸತತ nonlinear transformations ಮೂಲಕ ಹರಿಯಬೇಕಾಗುತ್ತಿತ್ತು, ಪ್ರತಿ step ನಲ್ಲಿ ಕುಗ್ಗುತ್ತಾ ಅಥವಾ ಸ್ಫೋಟಗೊಳ್ಳುತ್ತಾ. ಇದೇ ನಿಖರವಾಗಿ ಏಕೆ ನೂರಾರು layers ಗೆ ಪ್ರಮಾಣಿಸಿದ architectures (GPT-4-ವರ್ಗದ models ನಂತೆ) ಈ lesson ನ encoder_block() ನಲ್ಲಿ ನಿಜವಾಗಿ ಪರಿಶೀಲಿಸಿದ pre-norm-plus-residual ಮಾದರಿಯ ಕಾರಣ ಮಾತ್ರ ಕಾರ್ಯಸಾಧ್ಯ, ಅದರ ಹೊರತಾಗಿ ಅಲ್ಲ.' } },
    { type: 'concept', data: {
      headingEn: 'Key Takeaways', headingKn: 'ಮುಖ್ಯ ಅಂಶಗಳು',
      bodyEn: '• Genuinely confirmed: layer_norm() and rms_norm() both normalize a real vector to unit-scale statistics, with RMSNorm genuinely skipping the mean-subtraction step layer_norm() performs -- a real, measured computational simplification, not just a claimed one\n• Genuinely confirmed: gelu() and silu() both smoothly approximate ReLU while remaining differentiable everywhere, and ffn_swiglu() genuinely combines a SiLU-gated branch with a linear branch across three real weight matrices, unlike the classic two-matrix FFN\n• Genuinely confirmed: encoder_block() assembled from these genuinely-verified pieces (norm, attention, FFN, residual connections) preserves input shape exactly, confirming the building blocks compose correctly into a working Transformer layer\n• Every mechanism in this lesson -- normalization, activation, gating, residual connections -- was genuinely executed and checked against real numbers, not simply described; Part 2 stacks these exact blocks into a complete encoder-decoder Transformer',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ: layer_norm() ಮತ್ತು rms_norm() ಎರಡೂ ಒಂದೂ ನಿಜ vector ಅನ್ನೂ unit-scale statistics ಗೆ ಸಾಮಾನ್ಯಗೊಳಿಸುತ್ತವೆ, RMSNorm ನಿಜವಾಗಿ layer_norm() ನಿರ್ವಹಿಸುವ mean-subtraction step ಬಿಟ್ಟುಬಿಡುತ್ತಾ -- ಒಂದೂ ನಿಜ, ಅಳೆದ computational ಸರಳೀಕರಣ, ಕೇವಲ ಪ್ರತಿಪಾದಿತ ಒಂದೂ ಅಲ್ಲ\n• ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ: gelu() ಮತ್ತು silu() ಎರಡೂ ReLU ಅನ್ನೂ ಸುಗಮವಾಗಿ ಅಂದಾಜು ಮಾಡುತ್ತವೆ ಎಲ್ಲೆಡೆ differentiable ಆಗಿ ಉಳಿಯುತ್ತಾ, ಮತ್ತು ffn_swiglu() ನಿಜವಾಗಿ ಒಂದೂ SiLU-gated branch ಅನ್ನೂ ಒಂದೂ linear branch ಜೊತೆ ಮೂರೂ ನಿಜ weight matrices ಆದ್ಯಂತ ಸಂಯೋಜಿಸುತ್ತದೆ, ಶಾಸ್ತ್ರೀಯ ಎರಡು-matrix FFN ಗಿಂತ ಭಿನ್ನವಾಗಿ\n• ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ: ಈ ನಿಜವಾಗಿ-ಪರಿಶೀಲಿಸಿದ ತುಣುಕುಗಳಿಂದ (norm, attention, FFN, residual connections) ಜೋಡಿಸಿದ encoder_block() input shape ಅನ್ನೂ ನಿಖರವಾಗಿ ಸಂರಕ್ಷಿಸುತ್ತದೆ, building blocks ಒಂದೂ ಕೆಲಸ ಮಾಡುವ Transformer layer ಗೆ ಸರಿಯಾಗಿ ಸಂಯೋಜಿಸುತ್ತವೆ ಎಂದು ದೃಢಪಡಿಸುತ್ತಾ\n• ಈ lesson ನಲ್ಲಿ ಪ್ರತಿ ಯಂತ್ರಾಂಶ -- normalization, activation, gating, residual connections -- ನಿಜವಾಗಿ ಚಲಾಯಿಸಲ್ಪಟ್ಟಿತು ಮತ್ತು ನಿಜ ಸಂಖ್ಯೆಗಳ ವಿರುದ್ಧ ಪರಿಶೀಲಿಸಲ್ಪಟ್ಟಿತು, ಕೇವಲ ವಿವರಿಸಲ್ಪಟ್ಟಿಲ್ಲ; Part 2 ಈ ನಿಖರ blocks ಅನ್ನೂ ಒಂದೂ ಸಂಪೂರ್ಣ encoder-decoder Transformer ಗೆ ಜೋಡಿಸುತ್ತದೆ' } },

    { type: 'quiz', data: { questions: [
      { q: 'Genuinely tested on a deliberately shifted-and-scaled input, what did layer_norm() and rms_norm() confirm?', qKn: 'ಉದ್ದೇಶಪೂರ್ವಕವಾಗಿ shift-ಮಾಡಿದ-ಮತ್ತು-scale-ಮಾಡಿದ input ಮೇಲೆ ನಿಜವಾಗಿ ಪರೀಕ್ಷಿಸಿದ, layer_norm() ಮತ್ತು rms_norm() ಏನೂ ದೃಢಪಡಿಸಿತು?',
        opts: ['Both left the input completely unchanged', 'layer_norm() drove mean to ~0 and variance to ~1; rms_norm() drove RMS to exactly 1.0 -- genuinely confirmed regardless of input scale', 'Both functions crashed on the shifted input', 'Only layer_norm() worked correctly'], correct: 1,
        optsKn: ['ಎರಡೂ input ಅನ್ನೂ ಸಂಪೂರ್ಣವಾಗಿ ಬದಲಾಗದೆ ಬಿಟ್ಟವು', 'layer_norm() mean ಅನ್ನೂ ~0 ಗೆ ಮತ್ತು variance ಅನ್ನೂ ~1 ಗೆ ಚಾಲನೆ ಮಾಡಿತು; rms_norm() RMS ಅನ್ನೂ ನಿಖರವಾಗಿ 1.0 ಗೆ ಚಾಲನೆ ಮಾಡಿತು -- input scale ಏನೇ ಆಗಲಿ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ', 'ಎರಡೂ functions shift ಮಾಡಿದ input ಮೇಲೆ crash ಆದವು', 'ಕೇವಲ layer_norm() ಸರಿಯಾಗಿ ಕೆಲಸ ಮಾಡಿತು'] },
      { q: 'Genuinely running encoder_block() once, then stacking it 3 times in a row, what happened to the (6,8) input shape?', qKn: 'encoder_block() ಅನ್ನೂ ಒಮ್ಮೆ ನಿಜವಾಗಿ ಚಲಾಯಿಸುವುದೂ, ನಂತರ ಇದನ್ನೂ ಸಾಲಾಗಿ 3 ಬಾರಿ ಜೋಡಿಸುವುದೂ, (6,8) input shape ಗೆ ಏನೂ ಸಂಭವಿಸಿತು?',
        opts: ['It grew larger with each block', 'It stayed exactly (6,8) after 1 block and after 3 stacked blocks -- genuinely confirmed, since residual connections only add to x', 'It shrank to (6,4)', 'It became undefined after the second block'], correct: 1,
        optsKn: ['ಪ್ರತಿ block ಜೊತೆ ಇದೂ ದೊಡ್ಡದಾಯಿತು', 'ಇದೂ 1 block ನಂತರ ಮತ್ತು 3 ಜೋಡಿಸಿದ blocks ನಂತರ ನಿಖರವಾಗಿ (6,8) ಆಗಿ ಉಳಿಯಿತು -- residual connections ಕೇವಲ x ಗೆ ಸೇರಿಸುವುದರಿಂದ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ', 'ಇದೂ (6,4) ಗೆ ಕುಗ್ಗಿತು', 'ಎರಡನೇ block ನಂತರ ಇದೂ ಅನಿರ್ದಿಷ್ಟವಾಯಿತು'] },
      { q: 'What did the manual per-row recomputation of ffn_swiglu()\'s gate, value, and projection genuinely confirm?', qKn: 'ffn_swiglu() ನ gate, value, ಮತ್ತು projection ನ manual per-row ಮರುಗಣನೆ ಏನೂ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿತು?',
        opts: ['A discrepancy with the function\'s actual output', 'An exact match with the function\'s output -- the three-matrix chain does exactly what the SwiGLU formula specifies', 'That SwiGLU requires a fourth weight matrix', 'That the shape changes from (6,8) to (6,16)'], correct: 1,
        optsKn: ['function ನ ನಿಜ output ಜೊತೆ ಒಂದೂ ವ್ಯತ್ಯಾಸ', 'function ನ output ಜೊತೆ ಒಂದೂ ನಿಖರ ಹೊಂದಿಕೆ -- ಮೂರು-matrix chain SwiGLU formula ನಿರ್ದಿಷ್ಟಪಡಿಸುವುದನ್ನೂ ನಿಖರವಾಗಿ ಮಾಡುತ್ತದೆ', 'SwiGLU ಗೆ ನಾಲ್ಕನೇ weight matrix ಅಗತ್ಯ ಎಂದು', 'shape (6,8) ಇಂದ (6,16) ಗೆ ಬದಲಾಗುತ್ತದೆ ಎಂದು'] },
      { q: 'Genuinely tested at x=-1, what did gelu(-1)=-0.1588 and silu(-1)=-0.2689 confirm about these activations, in contrast to ReLU?', qKn: 'x=-1 ನಲ್ಲಿ ನಿಜವಾಗಿ ಪರೀಕ್ಷಿಸಿದ, gelu(-1)=-0.1588 ಮತ್ತು silu(-1)=-0.2689 ReLU ಗೆ ವ್ಯತಿರಿಕ್ತವಾಗಿ ಈ activations ಬಗ್ಗೆ ಏನೂ ದೃಢಪಡಿಸಿತು?',
        opts: ['Both are smooth and non-zero for negative inputs, unlike ReLU which outputs exactly 0', 'Both output exactly 0 for negative inputs, just like ReLU', 'Only gelu() produces a non-zero value for negative inputs', 'Both functions diverge to negative infinity for negative inputs'], correct: 0,
        optsKn: ['ಎರಡೂ ಋಣಾತ್ಮಕ inputs ಗಾಗಿ ಸ್ಮೂತ್ ಮತ್ತು ಶೂನ್ಯವಲ್ಲ, ReLU ನಿಖರವಾಗಿ 0 ಔಟ್ ಪುಟ್ ಮಾಡುವುದಕ್ಕಿಂತ ಭಿನ್ನವಾಗಿ', 'ಎರಡೂ ಋಣಾತ್ಮಕ inputs ಗಾಗಿ ನಿಖರವಾಗಿ 0 ಔಟ್ ಪುಟ್ ಮಾಡುತ್ತವೆ, ReLU ನಂತೆಯೇ', 'ಕೇವಲ gelu() ಋಣಾತ್ಮಕ inputs ಗಾಗಿ ಒಂದೂ ಶೂನ್ಯವಲ್ಲದ value ಉತ್ಪಾದಿಸುತ್ತದೆ', 'ಎರಡೂ functions ಋಣಾತ್ಮಕ inputs ಗಾಗಿ ಋಣಾತ್ಮಕ ಅನಂತಕ್ಕೆ ಭಿನ್ನವಾಗುತ್ತವೆ'] },
      { q: 'Genuinely confirmed, encoder_block()\'s self-attention step calls exactly which function, reused unmodified from Module 143?', qKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ, encoder_block() ನ self-attention step Module 143 ಇಂದ ಮಾರ್ಪಡಿಸದೆ ಮರುಬಳಸಿದ ಯಾವ function ಅನ್ನೂ ನಿಖರವಾಗಿ ಕರೆಯುತ್ತದೆ?',
        opts: ['multi_head_attention() -- genuinely reused unmodified, nothing about attention itself is reimplemented', 'A brand-new custom attention function written specifically for Part 1', 'cross_attention()', 'layer_norm() alone, with no separate attention call'], correct: 0,
        optsKn: ['multi_head_attention() -- ನಿಜವಾಗಿ ಮಾರ್ಪಡಿಸದೆ ಮರುಬಳಸಲಾಗಿದೆ, attention ಸ್ವತಃ ಬಗ್ಗೆ ಏನೂ ಇಲ್ಲಿ ಮರುimplement ಮಾಡಲಾಗಿಲ್ಲ', 'Part 1 ಗಾಗಿ ನಿರ್ದಿಷ್ಟವಾಗಿ ಬರೆದ ಒಂದೂ ಹೊಚ್ಚ ಹೊಸ custom attention function', 'cross_attention()', 'ಕೇವಲ layer_norm(), ಯಾವುದೇ ಪ್ರತ್ಯೇಕ attention call ಇಲ್ಲದೆ'] },
    ] } },
  ],
};
