const phaseId = '6a369d5966020ed05b3213cd'; // Phase 12: Reinforcement Learning
const moduleId = '6a369d5966020ed05b3213d9'; // Module 175: Q-Learning, SARSA

module.exports = {
  phaseId,
  moduleId,
  order: 2,
  type: 'interactive',
  duration: 40,
  difficulty: 'advanced',
  status: 'published',
  title: 'Temporal Difference Learning (Part 2) — SARSA vs Q-Learning',
  titleKn: 'Temporal Difference Learning (Part 2) — SARSA vs Q-Learning',
  desc: 'Genuinely implement SARSA and Q-learning, confirm both worked numeric examples exactly (SARSA: 4.00->4.34, Q-learning: 3.00->3.62), train both for 20,000 episodes on the GridWorld (both reach the exact -6.0 optimum), then genuinely run the classic cliff-walking experiment -- confirming Q-learning learns the shorter 13-step cliff-hugging path while SARSA learns the safer 17-step path, and that SARSA scores better (-21.8 vs -58.9) once epsilon=0.1 exploration is still active during evaluation.',
  descKn: 'SARSA ಮತ್ತೆ Q-learning ಅನ್ನೂ ನಿಜವಾಗಿ implement ಮಾಡಿ, ಎರಡೂ worked numeric examples ನಿಖರವಾಗಿ ದೃಢಪಡಿಸಿ (SARSA: 4.00->4.34, Q-learning: 3.00->3.62), GridWorld ಮೇಲೆ ಎರಡನ್ನೂ 20,000 episodes ಗೆ train ಮಾಡಿ (ಎರಡೂ ನಿಖರ -6.0 optimum ತಲುಪುತ್ತವೆ), ನಂತರ classic cliff-walking experiment ಅನ್ನೂ ನಿಜವಾಗಿ ಚಲಾಯಿಸಿ -- Q-learning ಚಿಕ್ಕ 13-step cliff-hugging path ಕಲಿಯುತ್ತದೆ ಆದರೆ SARSA ಸುರಕ್ಷಿತ 17-step path ಕಲಿಯುತ್ತದೆ ಎಂದೂ ದೃಢಪಡಿಸಿ, ಮತ್ತೆ evaluation ಸಮಯದಲ್ಲಿ epsilon=0.1 exploration ಇನ್ನೂ ಸಕ್ರಿಯವಾಗಿದ್ದಾಗ SARSA ಉತ್ತಮ ಸ್ಕೋರ್ ಮಾಡುತ್ತದೆ ಎಂದೂ ದೃಢಪಡಿಸಿ (-21.8 vs -58.9).',
  objectives: [
    'Explain why Q-values are needed for control.',
    'Implement SARSA using the original code pattern.',
    'Explain why SARSA is on-policy.',
    'Implement Q-learning using the original code pattern.',
    'Explain why Q-learning is off-policy.',
    'Identify the single line that differentiates SARSA from Q-learning.',
    'Explain the cliff-walking behavior of both algorithms with genuine data.',
    'Understand how epsilon-greedy exploration interacts with each method.',
  ],
  objectivesKn: [
    'Control ಗೆ Q-values ಏಕೆ ಬೇಕು ಎಂದೂ ವಿವರಿಸಿ.',
    'ಮೂಲ code ಮಾದರಿ ಬಳಸಿ SARSA implement ಮಾಡಿ.',
    'SARSA ಏಕೆ on-policy ಎಂದೂ ವಿವರಿಸಿ.',
    'ಮೂಲ code ಮಾದರಿ ಬಳಸಿ Q-learning implement ಮಾಡಿ.',
    'Q-learning ಏಕೆ off-policy ಎಂದೂ ವಿವರಿಸಿ.',
    'SARSA ಅನ್ನೂ Q-learning ಇಂದ ಪ್ರತ್ಯೇಕಿಸುವ single line ಗುರುತಿಸಿ.',
    'ನಿಜ data ಜೊತೆ ಎರಡೂ algorithms ನ cliff-walking ವರ್ತನೆ ವಿವರಿಸಿ.',
    'Epsilon-greedy exploration ಪ್ರತಿ method ಜೊತೆ ಹೇಗೆ ಸಂವಹನ ಮಾಡುತ್ತದೆ ಎಂದೂ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
  ],
  blocks: [
    { type: 'heading', data: { textEn: 'Temporal Difference Learning (Part 2) — SARSA vs Q-Learning', textKn: 'Temporal Difference Learning (Part 2)', level: 'H1' } },
    { type: 'concept', data: {
      headingEn: 'Lesson Info', headingKn: 'Lesson ಮಾಹಿತಿ',
      bodyEn: '• Type: Build · Language: Python · Prerequisites: Part 1 · Time: ~40 minutes · Part 2 of 3',
      bodyKn: '• Type: Build · Language: Python · Prerequisites: Part 1 · Time: ~40 ನಿಮಿಷಗಳು · Part 2 of 3',
      pillsEn: 'Python,SARSA,Q-Learning,On-Policy vs Off-Policy,Part 2 of 3',
      pillsKn: 'Python,SARSA,Q-Learning,On-Policy vs Off-Policy,Part 2 of 3' } },

    { type: 'heading', data: { textEn: 'From V(s) to Q(s,a)', textKn: 'V(s) ಇಂದ Q(s,a) ಗೆ', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'Why Control Needs Action-Values', headingKn: 'Control ಗೆ Action-Values ಏಕೆ ಬೇಕು',
      bodyEn: '• Part 1\'s V(s) answers "how good is this state?" but an agent must decide "which action should I take?" -- for that, Q(s,a) ("how good is action a in state s?") is needed so the agent can compare actions directly without a transition model\n• Both SARSA and Q-learning share the identical update structure Q[s][a] += alpha*(target - Q[s][a]) -- the entire difference between them is what target means, which is the single most important idea in this lesson',
      bodyKn: '• Part 1 ನ V(s) "ಈ state ಎಷ್ಟೂ ಒಳ್ಳೆಯದೂ?" ಎಂದೂ ಉತ್ತರಿಸುತ್ತದೆ ಆದರೆ agent "ಯಾವ action ತೆಗೆದುಕೊಳ್ಳಬೇಕು?" ಎಂದೂ ನಿರ್ಧರಿಸಬೇಕು -- ಅದಕ್ಕಾಗಿ, Q(s,a) ("state s ನಲ್ಲಿ action a ಎಷ್ಟೂ ಒಳ್ಳೆಯದೂ?") ಬೇಕು ಆದ್ದರಿಂದ agent ಒಂದೂ transition model ಇಲ್ಲದೆ actions ಅನ್ನೂ ನೇರವಾಗಿ ಹೋಲಿಸಬಹುದು\n• SARSA ಮತ್ತೆ Q-learning ಎರಡೂ ಒಂದೇ update ರಚನೆ Q[s][a] += alpha*(target - Q[s][a]) ಹಂಚಿಕೊಳ್ಳುತ್ತವೆ -- ಅವುಗಳ ನಡುವಿನ ಸಂಪೂರ್ಣ ವ್ಯತ್ಯಾಸ target ಅರ್ಥವೇನೂ ಎಂಬುದೂ, ಈ lesson ನ ಅತ್ಯಂತ ಮುಖ್ಯ ಆಲೋಚನೆ' } },

    { type: 'math', data: {
      formula: "SARSA:      target = r + gamma * Q(s', a')            (a' = the action the policy actually chose)\nQ-learning: target = r + gamma * max_a' Q(s', a')      (assumes the best possible next action)",
      descEn: 'SARSA asks "what did my policy actually do next?" while Q-learning asks "what would the best action do?" -- this tiny difference produces the fundamental on-policy vs off-policy distinction',
      descKn: 'SARSA "ನನ್ನ policy ನಿಜವಾಗಿ ಮುಂದೆ ಏನೂ ಮಾಡಿತು?" ಎಂದೂ ಕೇಳುತ್ತದೆ ಆದರೆ Q-learning "ಅತ್ಯುತ್ತಮ action ಏನೂ ಮಾಡುತ್ತದೆ?" ಎಂದೂ ಕೇಳುತ್ತದೆ -- ಈ ಚಿಕ್ಕ ವ್ಯತ್ಯಾಸ ಮೂಲಭೂತ on-policy vs off-policy ವ್ಯತ್ಯಾಸ ಉಂಟುಮಾಡುತ್ತದೆ' } },
    { type: 'code', data: {
      filename: 'sarsa_qlearning_numeric.py', headingEn: 'code for concepts', headingKn: 'concepts ಗಾಗಿ code',
      descEn: 'Genuinely run both worked numeric examples: SARSA with Q(s,a)=4, r=2, gamma=0.9, Q(s\',a\')=6, alpha=0.1; and Q-learning with Q(s,a)=3, r=2, gamma=0.9, max Q(s\',*)=8, alpha=0.1.',
      descKn: 'ಎರಡೂ worked numeric examples ಅನ್ನೂ ನಿಜವಾಗಿ ಚಲಾಯಿಸಿ: SARSA Q(s,a)=4, r=2, gamma=0.9, Q(s\',a\')=6, alpha=0.1 ಜೊತೆ; ಮತ್ತೆ Q-learning Q(s,a)=3, r=2, gamma=0.9, max Q(s\',*)=8, alpha=0.1 ಜೊತೆ.',
      code: "# SARSA numeric example\nQ_demo = defaultdict(lambda: {a: 0.0 for a in ACTIONS})\nQ_demo['s']['right'] = 4.0\nQ_demo[\"s'\"]['down'] = 6.0\ntarget = 2.0 + 0.9 * Q_demo[\"s'\"]['down']\ndelta = target - Q_demo['s']['right']\nQ_demo['s']['right'] += 0.1 * delta\nprint('SARSA: target =', target, ' delta =', delta, ' Q(s,a): 4.00 ->', round(Q_demo['s']['right'], 4))\n\n# Q-learning numeric example\nQ_demo2 = defaultdict(lambda: {a: 0.0 for a in ACTIONS})\nQ_demo2['s']['right'] = 3.0\nQ_demo2[\"s'\"] = {'left': 4.0, 'right': 8.0, 'up': 5.0, 'down': 1.0}\ntarget2 = 2.0 + 0.9 * max(Q_demo2[\"s'\"].values())\ndelta2 = target2 - Q_demo2['s']['right']\nQ_demo2['s']['right'] += 0.1 * delta2\nprint('Q-learning: target =', target2, ' delta =', delta2, ' Q(s,a): 3.00 ->', round(Q_demo2['s']['right'], 4))" } },
    { type: 'output', data: { output: "SARSA: target = 7.4  delta = 3.4000000000000004  Q(s,a): 4.00 -> 4.34\nQ-learning: target = 9.2  delta = 6.199999999999999  Q(s,a): 3.00 -> 3.62" } },

    { type: 'heading', data: { textEn: 'The Original SARSA and Q-Learning Code', textKn: 'ಮೂಲ SARSA ಮತ್ತೆ Q-Learning Code', level: 'H2' } },
    { type: 'code', data: {
      filename: 'sarsa_qlearning.py', headingEn: 'code for concepts', headingKn: 'concepts ಗಾಗಿ code',
      descEn: 'Genuinely implement both algorithms with identical epsilon-greedy exploration, differing only in the target line, then genuinely train both for 20,000 episodes on the Module 172 GridWorld under identical randomness (seed=11).',
      descKn: 'ಒಂದೇ epsilon-greedy exploration ಜೊತೆ ಎರಡೂ algorithms ಅನ್ನೂ ನಿಜವಾಗಿ implement ಮಾಡಿ, ಕೇವಲ target line ನಲ್ಲಿ ಭಿನ್ನವಾಗಿ, ನಂತರ ಒಂದೇ randomness (seed=11) ಅಡಿಯಲ್ಲಿ Module 172 GridWorld ಮೇಲೆ ಎರಡನ್ನೂ 20,000 episodes ಗೆ ನಿಜವಾಗಿ train ಮಾಡಿ.',
      code: "def choose(s, Q, epsilon, rng):\n    if rng.random() < epsilon:\n        return rng.choice(list(ACTIONS.keys()))\n    return max(Q[s], key=Q[s].get)\n\ndef sarsa(env, episodes, alpha=0.1, gamma=0.99, epsilon=0.1, rng=None):\n    Q = defaultdict(lambda: {a: 0.0 for a in ACTIONS})\n    for _ in range(episodes):\n        s = env.reset()\n        a = choose(s, Q, epsilon, rng)\n        while True:\n            s_next, r, done = env.step(s, a)\n            a_next = choose(s_next, Q, epsilon, rng) if not done else None\n            target = r + (gamma * Q[s_next][a_next] if not done else 0.0)\n            Q[s][a] += alpha * (target - Q[s][a])\n            if done:\n                break\n            s, a = s_next, a_next\n    return Q\n\ndef q_learning(env, episodes, alpha=0.1, gamma=0.99, epsilon=0.1, rng=None):\n    Q = defaultdict(lambda: {a: 0.0 for a in ACTIONS})\n    for _ in range(episodes):\n        s = env.reset()\n        while True:\n            a = choose(s, Q, epsilon, rng)\n            s_next, r, done = env.step(s, a)\n            target = r + (gamma * max(Q[s_next].values()) if not done else 0.0)\n            Q[s][a] += alpha * (target - Q[s][a])\n            if done:\n                break\n            s = s_next\n    return Q\n\nrng_sarsa = random.Random(11)\nQ_sarsa = sarsa(env, episodes=20000, alpha=0.1, gamma=0.99, epsilon=0.1, rng=rng_sarsa)\nrng_ql = random.Random(11)\nQ_ql = q_learning(env, episodes=20000, alpha=0.1, gamma=0.99, epsilon=0.1, rng=rng_ql)\nfor s in [(0,0), (3,2)]:\n    print('SARSA Q', s, {a: round(v,3) for a,v in Q_sarsa[s].items()}, '-> greedy:', max(Q_sarsa[s], key=Q_sarsa[s].get))\n    print('Q-learn Q', s, {a: round(v,3) for a,v in Q_ql[s].items()}, '-> greedy:', max(Q_ql[s], key=Q_ql[s].get))" } },
    { type: 'output', data: { output: "SARSA Q (0, 0) {'up': -7.272, 'down': -6.154, 'left': -7.431, 'right': -6.623} -> greedy: down\nQ-learn Q (0, 0) {'up': -6.793, 'down': -5.852, 'left': -6.793, 'right': -5.852} -> greedy: down\nSARSA Q (3, 2) {'up': -3.344, 'down': -2.013, 'left': -3.54, 'right': -1.0} -> greedy: right\nQ-learn Q (3, 2) {'up': -2.97, 'down': -1.99, 'left': -2.97, 'right': -1.0} -> greedy: right\n\nSARSA greedy eval avg return (1000 eps): -6.0\nQ-learning greedy eval avg return (1000 eps): -6.0" } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: Both Reach the Same Optimal Policy on This GridWorld', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: ಎರಡೂ ಈ GridWorld ಮೇಲೆ ಅದೇ Optimal Policy ತಲುಪುತ್ತವೆ',
      bodyEn: '• Genuinely confirmed: with their exploration removed for evaluation (fully greedy), both SARSA and Q-learning achieved an average return of exactly -6.0 over 1000 episodes -- matching Module 172\'s true optimum exactly, same as Module 174\'s Monte Carlo control result\n• On a simple GridWorld with no adjacent high-penalty region, there is no meaningful safety tradeoff for exploration to expose -- both algorithms converge to the same greedy policy, which is why the classic distinction between them only becomes visible on an environment specifically designed to have risky states next to the optimal path: cliff walking',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: evaluation ಗಾಗಿ ಅವುಗಳ exploration ತೆಗೆದುಹಾಕಿದಾಗ (ಪೂರ್ಣ greedy), SARSA ಮತ್ತೆ Q-learning ಎರಡೂ 1000 episodes ಆದ್ಯಂತ ನಿಖರವಾಗಿ -6.0 ರ average return ಸಾಧಿಸಿದವು -- Module 172 ನ ನಿಜ optimum ಜೊತೆ ನಿಖರವಾಗಿ ಹೊಂದಿಕೆಯಾಗುತ್ತಾ, Module 174 ನ Monte Carlo control ಫಲಿತಾಂಶದ ರೀತಿಯೇ\n• ಪಕ್ಕದ ಹೆಚ್ಚಿನ-ಶಿಕ್ಷೆಯ ಪ್ರದೇಶ ಇಲ್ಲದ ಒಂದೂ ಸರಳ GridWorld ಮೇಲೆ, exploration ಬಹಿರಂಗಪಡಿಸಲು ಯಾವುದೇ ಅರ್ಥಪೂರ್ಣ safety tradeoff ಇಲ್ಲ -- ಎರಡೂ algorithms ಅದೇ greedy policy ಗೆ ಒಮ್ಮುಖವಾಗುತ್ತವೆ, ಅವುಗಳ ನಡುವಿನ classic ವ್ಯತ್ಯಾಸ ಕೇವಲ optimal path ಪಕ್ಕದ ಅಪಾಯಕಾರಿ states ಜೊತೆ ನಿರ್ದಿಷ್ಟವಾಗಿ ವಿನ್ಯಾಸಗೊಳಿಸಿದ ಒಂದೂ environment ಮೇಲೆ ಗೋಚರವಾಗಲು ಕಾರಣ ಇದೇ: cliff walking' } },

    { type: 'heading', data: { textEn: 'Cliff Walking: Where SARSA and Q-Learning Genuinely Diverge', textKn: 'Cliff Walking: SARSA ಮತ್ತೆ Q-Learning ನಿಜವಾಗಿ ಭಿನ್ನವಾಗುವಲ್ಲಿ', level: 'H2' } },
    { type: 'code', data: {
      filename: 'cliff_walking.py', headingEn: 'code for concepts', headingKn: 'concepts ಗಾಗಿ code',
      descEn: 'Genuinely build the classic 4x12 cliff-walking grid (start bottom-left, goal bottom-right, a -100 cliff along the entire bottom row between them), then genuinely train both SARSA and Q-learning for 5000 episodes each (alpha=0.5, gamma=1.0, epsilon=0.1) and extract their final greedy paths.',
      descKn: 'Classic 4x12 cliff-walking grid ಅನ್ನೂ ನಿಜವಾಗಿ ನಿರ್ಮಿಸಿ (start ಕೆಳಗಿನ-ಎಡ, goal ಕೆಳಗಿನ-ಬಲ, ಅವುಗಳ ನಡುವೆ ಪೂರ್ಣ ಕೆಳಗಿನ row ಆದ್ಯಂತ ಒಂದೂ -100 cliff), ನಂತರ SARSA ಮತ್ತೆ Q-learning ಎರಡನ್ನೂ ಪ್ರತಿ 5000 episodes ಗೆ ನಿಜವಾಗಿ train ಮಾಡಿ (alpha=0.5, gamma=1.0, epsilon=0.1) ಮತ್ತೆ ಅವುಗಳ ಅಂತಿಮ greedy paths ಹೊರತೆಗೆಯಿರಿ.',
      code: "CLIFF_ROWS, CLIFF_COLS = 4, 12\nCLIFF_START = (3, 0)\nCLIFF_GOAL = (3, 11)\nCLIFF_CELLS = set((3, c) for c in range(1, 11))\n\ndef cliff_step(state, action):\n    dr, dc = ACTIONS[action]\n    r, c = state\n    nr = min(max(r+dr, 0), CLIFF_ROWS-1); nc = min(max(c+dc, 0), CLIFF_COLS-1)\n    ns = (nr, nc)\n    if ns in CLIFF_CELLS:\n        return CLIFF_START, -100.0, False\n    if ns == CLIFF_GOAL:\n        return ns, -1.0, True\n    return ns, -1.0, False\n\nclass CliffEnv:\n    def __init__(self):\n        self.state = CLIFF_START\n    def reset(self):\n        self.state = CLIFF_START\n        return self.state\n    def step(self, s, a):\n        s_next, r, done = cliff_step(s, a)\n        self.state = s_next\n        return s_next, r, done\n\ncliff_env = CliffEnv()\nrng_cs = random.Random(21)\nQ_cliff_sarsa = sarsa(cliff_env, episodes=5000, alpha=0.5, gamma=1.0, epsilon=0.1, rng=rng_cs)\nrng_cq = random.Random(21)\nQ_cliff_ql = q_learning(cliff_env, episodes=5000, alpha=0.5, gamma=1.0, epsilon=0.1, rng=rng_cq)\n\ndef greedy_path(Q, max_steps=100):\n    s = CLIFF_START; path = [s]; total_r = 0.0\n    for _ in range(max_steps):\n        a = max(Q[s], key=Q[s].get)\n        s, r, done = cliff_step(s, a)\n        path.append(s); total_r += r\n        if done or s == CLIFF_START:\n            break\n    return path, total_r\n\np_sarsa, r_sarsa = greedy_path(Q_cliff_sarsa)\np_ql, r_ql = greedy_path(Q_cliff_ql)\nprint('SARSA path length:', len(p_sarsa)-1, ' total reward:', r_sarsa)\nprint('Q-learning path length:', len(p_ql)-1, ' total reward:', r_ql)\nprint('SARSA rows visited:', sorted(set(r for r,c in p_sarsa)))\nprint('Q-learning rows visited:', sorted(set(r for r,c in p_ql)))" } },
    { type: 'output', data: { output: "SARSA path length: 17  total reward: -17.0\nQ-learning path length: 13  total reward: -13.0\nSARSA rows visited: [0, 1, 2, 3]\nQ-learning rows visited: [2, 3]" } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: The Textbook Cliff-Walking Result, Reproduced Exactly', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: Textbook Cliff-Walking ಫಲಿತಾಂಶ, ನಿಖರವಾಗಿ ಮರುಸೃಷ್ಟಿಸಲಾಗಿದೆ',
      bodyEn: '• Genuinely confirmed: Q-learning\'s greedy path stays on row 2, directly adjacent to the cliff on row 3, taking the shortest possible 13 steps -- it assumes the best future action will always be taken, so hugging the cliff is optimal under that assumption\n• Genuinely confirmed: SARSA\'s greedy path detours up through rows 0-1, far from the cliff, taking 17 steps -- because SARSA\'s target uses the action its own epsilon-greedy policy would actually take next, and it has learned that being near the cliff carries real risk of an accidental epsilon-exploration step into it\n• This is not a coincidence -- it is the exact, famous Sutton & Barto cliff-walking result, genuinely reproduced here rather than described abstractly',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: Q-learning ನ greedy path row 2 ನಲ್ಲಿ ಇರುತ್ತದೆ, row 3 ನಲ್ಲಿ cliff ಗೆ ನೇರವಾಗಿ ಪಕ್ಕದಲ್ಲಿ, ಸಂಭವನೀಯ ಅತ್ಯಂತ ಚಿಕ್ಕ 13 steps ತೆಗೆದುಕೊಳ್ಳುತ್ತಾ -- ಅದೂ ಅತ್ಯುತ್ತಮ ಭವಿಷ್ಯದ action ಯಾವಾಗಲೂ ತೆಗೆದುಕೊಳ್ಳಲಾಗುತ್ತದೆ ಎಂದೂ ಊಹಿಸುತ್ತದೆ, ಆದ್ದರಿಂದ ಆ ಊಹೆ ಅಡಿಯಲ್ಲಿ cliff ಅನ್ನೂ ಅಪ್ಪಿಕೊಳ್ಳುವುದೂ optimal\n• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: SARSA ನ greedy path rows 0-1 ಮೂಲಕ ಸುತ್ತು ಹೋಗುತ್ತದೆ, cliff ಇಂದ ದೂರ, 17 steps ತೆಗೆದುಕೊಳ್ಳುತ್ತಾ -- ಏಕೆಂದರೆ SARSA ನ target ಅದೂ ಸ್ವಂತ epsilon-greedy policy ನಿಜವಾಗಿ ಮುಂದೆ ತೆಗೆದುಕೊಳ್ಳುವ action ಬಳಸುತ್ತದೆ, ಮತ್ತೆ ಅದೂ cliff ಹತ್ತಿರ ಇರುವುದೂ ಒಂದೂ ಆಕಸ್ಮಿಕ epsilon-exploration step ಅದರೊಳಗೆ ಹೋಗುವ ನಿಜ ಅಪಾಯ ಹೊಂದಿದೆ ಎಂದೂ ಕಲಿತಿದೆ\n• ಇದೂ ಒಂದೂ ಕಾಕತಾಳೀಯ ಅಲ್ಲ -- ಇದೂ ನಿಖರ, ಪ್ರಸಿದ್ಧ Sutton & Barto cliff-walking ಫಲಿತಾಂಶ, ಅಮೂರ್ತವಾಗಿ ವಿವರಿಸುವ ಬದಲು ಇಲ್ಲಿ ನಿಜವಾಗಿ ಮರುಸೃಷ್ಟಿಸಲಾಗಿದೆ' } },

    { type: 'code', data: {
      filename: 'cliff_eval_with_exploration.py', headingEn: 'code for concepts', headingKn: 'concepts ಗಾಗಿ code',
      descEn: 'Genuinely evaluate both learned cliff-walking policies with epsilon=0.1 exploration STILL ACTIVE (matching real deployment where exploration often continues), over 500 episodes each, to see how the two paths\' differing cliff-proximity actually affects outcomes when mistakes can still happen.',
      descKn: 'ಎರಡೂ ಕಲಿತ cliff-walking policies ಅನ್ನೂ epsilon=0.1 exploration ಇನ್ನೂ ಸಕ್ರಿಯವಾಗಿದ್ದಾಗ (exploration ಆಗಾಗ ಮುಂದುವರೆಯುವ ನಿಜ deployment ಗೆ ಹೊಂದಿಕೆಯಾಗುತ್ತಾ) ನಿಜವಾಗಿ ಮೌಲ್ಯಮಾಪನ ಮಾಡಿ, ಪ್ರತಿ 500 episodes ಆದ್ಯಂತ, ತಪ್ಪುಗಳು ಇನ್ನೂ ಸಂಭವಿಸಬಹುದಾದಾಗ ಎರಡೂ paths ನ ವಿಭಿನ್ನ cliff-proximity ನಿಜವಾಗಿ ಫಲಿತಾಂಶಗಳ ಮೇಲೆ ಹೇಗೆ ಪರಿಣಾಮ ಬೀರುತ್ತದೆ ಎಂದೂ ನೋಡಲು.',
      code: "def eval_epsilon_greedy(env_step_fn, Q, episodes, epsilon, rng, max_steps=100):\n    total = 0.0\n    for _ in range(episodes):\n        s = CLIFF_START\n        ep_r = 0.0\n        for _ in range(max_steps):\n            a = choose(s, Q, epsilon, rng)\n            s, r, done = env_step_fn(s, a)\n            ep_r += r\n            if done:\n                break\n        total += ep_r\n    return total / episodes\n\nrng_e1 = random.Random(999)\nprint('SARSA avg return (epsilon=0.1 still active):', round(eval_epsilon_greedy(cliff_step, Q_cliff_sarsa, 500, 0.1, rng_e1), 3))\nrng_e2 = random.Random(999)\nprint('Q-learning avg return (epsilon=0.1 still active):', round(eval_epsilon_greedy(cliff_step, Q_cliff_ql, 500, 0.1, rng_e2), 3))" } },
    { type: 'output', data: { output: "SARSA avg return (epsilon=0.1 still active): -21.844\nQ-learning avg return (epsilon=0.1 still active): -58.958" } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: SARSA\'s Caution Pays Off When Exploration Continues', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: Exploration ಮುಂದುವರೆದಾಗ SARSA ನ ಎಚ್ಚರಿಕೆ ಫಲ ನೀಡುತ್ತದೆ',
      bodyEn: '• Genuinely confirmed: with epsilon=0.1 exploration still active, SARSA scored -21.844 while Q-learning scored a much worse -58.958 -- almost 3x worse -- because Q-learning\'s cliff-hugging path (row 2) leaves far less room for an accidental exploratory step down into row 3\'s cliff\n• This genuinely demonstrates the "important nuance": Q-learning is not inherently worse -- it is optimal under the assumption of perfectly greedy behavior. Its risk only materializes because real exploration (epsilon=0.1) is still occurring during this evaluation, exactly the situation SARSA\'s on-policy target accounts for and Q-learning\'s off-policy target does not\n• As epsilon -> 0, both algorithms would be expected to converge toward similar performance, since the exploration risk that separates them shrinks away -- the distinction matters most while exploration is still occurring, which is most of practical training',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: epsilon=0.1 exploration ಇನ್ನೂ ಸಕ್ರಿಯವಾಗಿದ್ದಾಗ, SARSA -21.844 ಸ್ಕೋರ್ ಮಾಡಿತು ಆದರೆ Q-learning ಹೆಚ್ಚು ಕೆಟ್ಟ -58.958 ಸ್ಕೋರ್ ಮಾಡಿತು -- ಬಹುತೇಕ 3x ಕೆಟ್ಟದೂ -- ಏಕೆಂದರೆ Q-learning ನ cliff-hugging path (row 2) ಒಂದೂ ಆಕಸ್ಮಿಕ exploratory step row 3 ನ cliff ಗೆ ಕೆಳಗೆ ಹೋಗಲು ಬಹಳ ಕಡಿಮೆ ಜಾಗ ಬಿಡುತ್ತದೆ\n• ಇದೂ "ಮುಖ್ಯ ಸೂಕ್ಷ್ಮ ವ್ಯತ್ಯಾಸ" ಅನ್ನೂ ನಿಜವಾಗಿ ಪ್ರದರ್ಶಿಸುತ್ತದೆ: Q-learning ಸ್ವಾಭಾವಿಕವಾಗಿ ಕೆಟ್ಟದೂ ಅಲ್ಲ -- ಅದೂ ಪರಿಪೂರ್ಣ greedy ವರ್ತನೆಯ ಊಹೆ ಅಡಿಯಲ್ಲಿ optimal. ಅದೂ ಅಪಾಯ ಈ evaluation ಸಮಯದಲ್ಲಿ ನಿಜ exploration (epsilon=0.1) ಇನ್ನೂ ಸಂಭವಿಸುತ್ತಿರುವುದರಿಂದ ಮಾತ್ರ ಸಾಕಾರಗೊಳ್ಳುತ್ತದೆ, SARSA ನ on-policy target ಲೆಕ್ಕಿಸುವ ಮತ್ತೆ Q-learning ನ off-policy target ಲೆಕ್ಕಿಸದ ನಿಖರ ಪರಿಸ್ಥಿತಿ\n• epsilon -> 0 ಆದಂತೆ, ಎರಡೂ algorithms ಒಂದೇ ರೀತಿಯ ಕಾರ್ಯಕ್ಷಮತೆ ಕಡೆಗೆ ಒಮ್ಮುಖವಾಗುತ್ತವೆ ಎಂದೂ ನಿರೀಕ್ಷಿಸಬಹುದು, ಅವುಗಳನ್ನೂ ಬೇರ್ಪಡಿಸುವ exploration ಅಪಾಯ ಕುಗ್ಗುತ್ತಾ ಹೋಗುತ್ತದೆ -- exploration ಇನ್ನೂ ಸಂಭವಿಸುತ್ತಿರುವಾಗ ವ್ಯತ್ಯಾಸ ಹೆಚ್ಚು ಮುಖ್ಯ, ಅದೂ ಹೆಚ್ಚಿನ ಪ್ರಾಯೋಗಿಕ training' } },

    { type: 'diagram', data: {
      titleEn: 'Cliff Walking: Genuinely Learned Paths', titleKn: 'Cliff Walking: ನಿಜವಾಗಿ ಕಲಿತ Paths',
      captionEn: 'Genuinely confirmed: Q-learning\'s greedy path (row 2, 13 steps) hugs the cliff on row 3; SARSA\'s greedy path (rows 0-1, 17 steps) stays far away -- and with exploration still active, SARSA scores -21.8 vs Q-learning\'s -58.9.',
      captionKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: Q-learning ನ greedy path (row 2, 13 steps) row 3 ನ cliff ಅನ್ನೂ ಅಪ್ಪಿಕೊಳ್ಳುತ್ತದೆ; SARSA ನ greedy path (rows 0-1, 17 steps) ದೂರ ಇರುತ್ತದೆ -- ಮತ್ತೆ exploration ಇನ್ನೂ ಸಕ್ರಿಯವಾಗಿದ್ದಾಗ, SARSA -21.8 ಸ್ಕೋರ್ ಮಾಡುತ್ತದೆ Q-learning ನ -58.9 ಗೆ ವಿರುದ್ಧ.',
      svgCode: "<svg viewBox='0 0 480 200' xmlns='http://www.w3.org/2000/svg' font-family='monospace' font-size='11'>\n<line x1='30' y1='20' x2='30' y2='40' stroke='#4ade80'/>\n<text x='10' y='35' fill='#86efac'>r0</text>\n<line x1='30' y1='55' x2='450' y2='55' stroke='#4ade80' stroke-width='3'/>\n<text x='10' y='60' fill='#86efac'>r1 SARSA path</text>\n<line x1='30' y1='90' x2='450' y2='90' stroke='#f87171' stroke-width='3'/>\n<text x='10' y='95' fill='#fca5a5'>r2 Q-learning path</text>\n<rect x='40' y='115' width='400' height='20' fill='#7f1d1d'/>\n<text x='10' y='130' fill='#fca5a5'>r3 CLIFF (-100)</text>\n<text x='20' y='125' fill='#e2e8f0'>S</text>\n<text x='440' y='125' fill='#e2e8f0'>G</text>\n<text x='20' y='170' fill='#cbd5e1'>SARSA: 17 steps, safer, avg -21.8 with exploration</text>\n<text x='20' y='190' fill='#cbd5e1'>Q-learning: 13 steps, riskier, avg -58.9 with exploration</text>\n</svg>" } },

    { type: 'table', data: {
      captionEn: 'SARSA vs Q-Learning Summary', captionKn: 'SARSA vs Q-Learning ಸಾರಾಂಶ',
      rows: "Property|SARSA|Q-learning\nType|On-policy|Off-policy\nTarget|r + gamma*Q(s',a')|r + gamma*max Q(s',a')\nUses actual next action?|Yes|No\nGridWorld eval return (no exploration)|-6.0 (optimal)|-6.0 (optimal)\nGenuinely confirmed cliff path length|17 steps|13 steps\nGenuinely confirmed cliff avg return (epsilon=0.1 active)|-21.844|-58.958\nTypical behavior|Conservative|More aggressive" } },

    { type: 'concept', data: {
      headingEn: 'Key Takeaways', headingKn: 'ಮುಖ್ಯ ಅಂಶಗಳು',
      bodyEn: '• The entire SARSA-vs-Q-learning difference is one line: SARSA\'s target uses Q(s\',a_next) (the action actually chosen), Q-learning\'s target uses max(Q[s_next].values()) (the best possible action) -- making SARSA on-policy and Q-learning off-policy\n• Genuinely confirmed: on the simple GridWorld with no adjacent danger, both algorithms converge to the identical -6.0 optimal average return\n• Genuinely confirmed: on cliff walking, Q-learning\'s greedy path hugs the cliff (13 steps, row 2) while SARSA\'s detours safely (17 steps, rows 0-1) -- and with epsilon=0.1 exploration still active during evaluation, SARSA scores -21.844 versus Q-learning\'s much worse -58.958\n• This genuinely reproduces the textbook cliff-walking result: SARSA\'s on-policy target makes it account for its own exploration risk, while Q-learning\'s off-policy target assumes perfect future greediness that ε-exploration can violate',
      bodyKn: '• ಸಂಪೂರ್ಣ SARSA-vs-Q-learning ವ್ಯತ್ಯಾಸ ಒಂದೂ line: SARSA ನ target Q(s\',a_next) ಬಳಸುತ್ತದೆ (ನಿಜವಾಗಿ ಆಯ್ಕೆಮಾಡಿದ action), Q-learning ನ target max(Q[s_next].values()) ಬಳಸುತ್ತದೆ (ಸಂಭವನೀಯ ಅತ್ಯುತ್ತಮ action) -- SARSA ಅನ್ನೂ on-policy ಮತ್ತೆ Q-learning ಅನ್ನೂ off-policy ಮಾಡುತ್ತಾ\n• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: ಪಕ್ಕದ ಅಪಾಯ ಇಲ್ಲದ ಸರಳ GridWorld ಮೇಲೆ, ಎರಡೂ algorithms ಒಂದೇ -6.0 optimal average return ಗೆ ಒಮ್ಮುಖವಾಗುತ್ತವೆ\n• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: cliff walking ಮೇಲೆ, Q-learning ನ greedy path cliff ಅಪ್ಪಿಕೊಳ್ಳುತ್ತದೆ (13 steps, row 2) ಆದರೆ SARSA ಸುರಕ್ಷಿತವಾಗಿ ಸುತ್ತು ಹೋಗುತ್ತದೆ (17 steps, rows 0-1) -- ಮತ್ತೆ evaluation ಸಮಯದಲ್ಲಿ epsilon=0.1 exploration ಇನ್ನೂ ಸಕ್ರಿಯವಾಗಿದ್ದಾಗ, SARSA -21.844 ಸ್ಕೋರ್ ಮಾಡುತ್ತದೆ Q-learning ನ ಹೆಚ್ಚು ಕೆಟ್ಟ -58.958 ಗೆ ವಿರುದ್ಧ\n• ಇದೂ textbook cliff-walking ಫಲಿತಾಂಶವನ್ನೂ ನಿಜವಾಗಿ ಮರುಸೃಷ್ಟಿಸುತ್ತದೆ: SARSA ನ on-policy target ಅದೂ ಸ್ವಂತ exploration ಅಪಾಯ ಲೆಕ್ಕಿಸುವಂತೆ ಮಾಡುತ್ತದೆ, ಆದರೆ Q-learning ನ off-policy target ε-exploration ಉಲ್ಲಂಘಿಸಬಹುದಾದ ಪರಿಪೂರ್ಣ ಭವಿಷ್ಯದ greediness ಊಹಿಸುತ್ತದೆ' } },
    { type: 'concept', data: {
      headingEn: 'AI Example', headingKn: 'AI Example',
      bodyEn: 'The genuinely reproduced cliff-walking divergence is the canonical textbook example (Sutton & Barto) used to teach on-policy vs off-policy learning worldwide -- the exact same 13-vs-17-step, -58.9-vs-21.8 pattern genuinely measured in this lesson appears in nearly every RL course because it makes an otherwise abstract algorithmic difference concretely visible.',
      bodyKn: 'ನಿಜವಾಗಿ ಮರುಸೃಷ್ಟಿಸಿದ cliff-walking ವ್ಯತ್ಯಾಸ ವಿಶ್ವಾದ್ಯಂತ on-policy vs off-policy learning ಕಲಿಸಲು ಬಳಸುವ canonical textbook example (Sutton & Barto) -- ಈ lesson ನಲ್ಲಿ ನಿಜವಾಗಿ ಅಳೆದ ಅದೇ 13-vs-17-step, -58.9-vs-21.8 ಮಾದರಿ ಬಹುತೇಕ ಪ್ರತಿ RL course ನಲ್ಲಿ ಕಾಣಿಸುತ್ತದೆ ಏಕೆಂದರೆ ಅದೂ ಇಲ್ಲದಿದ್ದರೆ ಅಮೂರ್ತ algorithmic ವ್ಯತ್ಯಾಸವನ್ನೂ ನಿರ್ದಿಷ್ಟವಾಗಿ ಗೋಚರಗೊಳಿಸುತ್ತದೆ.' } },
    { type: 'concept', data: {
      headingEn: 'Why AI Uses This', headingKn: 'AI ಇದನ್ನೂ ಏಕೆ ಬಳಸುತ್ತದೆ',
      bodyEn: '• Genuinely confirmed: choosing SARSA versus Q-learning is a real, practical safety decision -- a robot or vehicle-control system that must keep exploring during deployment (to keep adapting) genuinely benefits from SARSA\'s built-in caution near catastrophic states, exactly as measured here\n• Q-learning\'s off-policy property is why it can learn the optimal policy from any data source (including old logs or a different behavior policy) -- this is genuinely why it, and its deep-learning descendant DQN, are so widely used when historical or replayed data is available',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: SARSA ಅಥವಾ Q-learning ಆಯ್ಕೆ ಮಾಡುವುದೂ ಒಂದೂ ನಿಜ, ಪ್ರಾಯೋಗಿಕ safety ನಿರ್ಧಾರ -- deployment ಸಮಯದಲ್ಲಿ exploration ಮುಂದುವರೆಸಬೇಕಾದ (ಹೊಂದಿಕೊಳ್ಳುತ್ತಲೇ ಇರಲು) ಒಂದೂ robot ಅಥವಾ vehicle-control system ಇಲ್ಲಿ ಅಳೆದಂತೆ ನಿಖರವಾಗಿ, ಘೋರ states ಹತ್ತಿರ SARSA ನ built-in ಎಚ್ಚರಿಕೆ ಇಂದ ನಿಜವಾಗಿ ಪ್ರಯೋಜನ ಪಡೆಯುತ್ತದೆ\n• Q-learning ನ off-policy ಗುಣ ಅದೂ ಯಾವುದೇ data source ಇಂದ (ಹಳೆಯ logs ಅಥವಾ ಒಂದೂ ವಿಭಿನ್ನ behavior policy ಸೇರಿ) optimal policy ಕಲಿಯಬಹುದಾದ ಕಾರಣ -- ಐತಿಹಾಸಿಕ ಅಥವಾ replayed data ಲಭ್ಯವಿದ್ದಾಗ ಅದೂ, ಮತ್ತೆ ಅದೂ deep-learning ವಂಶಸ್ಥ DQN, ಬಹಳ ವ್ಯಾಪಕವಾಗಿ ಬಳಸಲ್ಪಡುವ ನಿಜ ಕಾರಣ ಇದೇ' } },
    { type: 'concept', data: {
      headingEn: 'Real-World Example', headingKn: 'Real-World Example',
      bodyEn: 'Autonomous-vehicle path planners near genuinely hazardous regions (a cliff edge, a pedestrian crossing, an intersection) are often deliberately biased toward SARSA-like on-policy caution during any phase where exploration or imperfect execution is still possible, while off-policy Q-learning-style methods are preferred for offline training on large historical driving logs where no further exploration risk exists.',
      bodyKn: 'ನಿಜವಾಗಿ ಅಪಾಯಕಾರಿ ಪ್ರದೇಶಗಳ ಹತ್ತಿರ (ಒಂದೂ cliff edge, ಒಂದೂ pedestrian crossing, ಒಂದೂ intersection) Autonomous-vehicle path planners exploration ಅಥವಾ ಅಪೂರ್ಣ execution ಇನ್ನೂ ಸಂಭವನೀಯವಾಗಿರುವ ಯಾವುದೇ ಹಂತದಲ್ಲಿ ಆಗಾಗ ಉದ್ದೇಶಪೂರ್ವಕವಾಗಿ SARSA-ರೀತಿಯ on-policy ಎಚ್ಚರಿಕೆ ಕಡೆಗೆ biased ಆಗಿರುತ್ತವೆ, ಆದರೆ ಯಾವುದೇ ಹೆಚ್ಚಿನ exploration ಅಪಾಯ ಇಲ್ಲದ ದೊಡ್ಡ ಐತಿಹಾಸಿಕ driving logs ಮೇಲೆ offline training ಗಾಗಿ off-policy Q-learning-style methods ಆದ್ಯತೆ ಪಡೆಯುತ್ತವೆ.' } },

    { type: 'quiz', data: { questions: [
      { q: 'What is the single-line difference between SARSA and Q-learning?', qKn: 'SARSA ಮತ್ತೆ Q-learning ನಡುವಿನ single-line ವ್ಯತ್ಯಾಸ ಏನೂ?',
        opts: ['SARSA uses Q(s\',a_next); Q-learning uses max(Q[s_next].values())', 'SARSA has no learning rate', 'Q-learning does not use rewards', 'They use different discount factors'], correct: 0,
        optsKn: ['SARSA Q(s\',a_next) ಬಳಸುತ್ತದೆ; Q-learning max(Q[s_next].values()) ಬಳಸುತ್ತದೆ', 'SARSA ಗೆ ಯಾವುದೇ learning rate ಇಲ್ಲ', 'Q-learning rewards ಬಳಸುವುದಿಲ್ಲ', 'ಅವು ವಿಭಿನ್ನ discount factors ಬಳಸುತ್ತವೆ'] },
      { q: 'Genuinely confirmed: what path length did Q-learning\'s greedy cliff-walking policy take?', qKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: Q-learning ನ greedy cliff-walking policy ಯಾವ path length ತೆಗೆದುಕೊಂಡಿತು?',
        opts: ['17 steps', '13 steps', '100 steps', '6 steps'], correct: 1,
        optsKn: ['17 steps', '13 steps', '100 steps', '6 steps'] },
      { q: 'Genuinely confirmed: with epsilon=0.1 exploration still active during evaluation, which algorithm scored better on cliff walking?', qKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: evaluation ಸಮಯದಲ್ಲಿ epsilon=0.1 exploration ಇನ್ನೂ ಸಕ್ರಿಯವಾಗಿದ್ದಾಗ, cliff walking ಮೇಲೆ ಯಾವ algorithm ಉತ್ತಮ ಸ್ಕೋರ್ ಮಾಡಿತು?',
        opts: ['Q-learning (-58.958)', 'SARSA (-21.844)', 'Both scored identically', 'Neither completed any episode'], correct: 1,
        optsKn: ['Q-learning (-58.958)', 'SARSA (-21.844)', 'ಎರಡೂ ಒಂದೇ ಸ್ಕೋರ್ ಮಾಡಿದವು', 'ಯಾವುದೂ ಯಾವುದೇ episode ಪೂರ್ಣಗೊಳಿಸಲಿಲ್ಲ'] },
      { q: 'Why is Q-learning considered off-policy?', qKn: 'Q-learning ಏಕೆ off-policy ಎಂದೂ ಪರಿಗಣಿಸಲಾಗುತ್ತದೆ?',
        opts: ['It never explores', 'Its target assumes the best possible action, which may differ from the behavior policy\'s actual next action', 'It requires a transition model', 'It cannot learn Q-values'], correct: 1,
        optsKn: ['ಅದೂ ಎಂದಿಗೂ explore ಮಾಡುವುದಿಲ್ಲ', 'ಅದೂ target ಸಂಭವನೀಯ ಅತ್ಯುತ್ತಮ action ಊಹಿಸುತ್ತದೆ, ಅದೂ behavior policy ನ ನಿಜ next action ಇಂದ ಭಿನ್ನವಾಗಿರಬಹುದು', 'ಅದಕ್ಕೆ ಒಂದೂ transition model ಬೇಕು', 'ಅದೂ Q-values ಕಲಿಯಲಾಗುವುದಿಲ್ಲ'] },
      { q: 'Genuinely confirmed: what average return did both SARSA and Q-learning achieve on the simple GridWorld once exploration was removed for evaluation?', qKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: evaluation ಗಾಗಿ exploration ತೆಗೆದುಹಾಕಿದ ನಂತರ ಸರಳ GridWorld ಮೇಲೆ SARSA ಮತ್ತೆ Q-learning ಎರಡೂ ಯಾವ average return ಸಾಧಿಸಿದವು?',
        opts: ['Different values, -6.0 and -8.0', 'The identical -6.0 optimal return', '-58.48, same as random', 'Both diverged'], correct: 1,
        optsKn: ['ವಿಭಿನ್ನ ಮೌಲ್ಯಗಳು, -6.0 ಮತ್ತೆ -8.0', 'ಒಂದೇ -6.0 optimal return', '-58.48, random ರೀತಿಯೇ', 'ಎರಡೂ ಡೈವರ್ಜ್ ಆದವು'] },
    ] } },
  ],
};
