const phaseId = '6a369d5666020ed05b321334'; // Phase 9
const moduleId = '6a369d5666020ed05b321358'; // Module 135: Build a Voice Assistant Pipeline

module.exports = {
  phaseId,
  moduleId,
  order: 2,
  type: 'reading',
  duration: 85,
  difficulty: 'advanced',
  status: 'published',
  title: 'Build a Voice Assistant Pipeline (Part 2) — Turn Detection, Interfaces & Cancellation',
  titleKn: 'Build a Voice Assistant Pipeline (Part 2) — Turn Detection, Interfaces ಮತ್ತು Cancellation',
  desc: 'Implementing the pre-roll buffer, turn-detection state machine, swappable STT/LLM/TTS interfaces, and the async producer/consumer pipeline that lets LLM and TTS overlap -- verified with the lesson\'s exact PreRollBuffer, TurnDetector, and VoiceAssistant controller genuinely run, including a real interrupted-response test showing correct mid-flight cancellation.',
  objectives: [
    'Genuinely verify a pre-roll buffer\'s fixed-capacity behavior.',
    'Genuinely verify the turn-detection state machine end to end.',
    'Understand why interfaces (STT/LLM/TTS/Speaker) let models be swapped without redesigning the pipeline.',
    'Understand why LLM and TTS should run as separate producer/consumer tasks connected by a queue.',
    'Genuinely verify that async queues let LLM generation and TTS playback overlap.',
    'Understand the tool-dispatcher security boundary between the LLM and real actions.',
    'Genuinely verify the VoiceAssistant controller\'s interrupt() method, including real task cancellation.',
    'Explain the CancelledError race condition and why interruption must flush, not just cancel.',
  ],
  objectivesKn: [
    'ಒಂದು pre-roll buffer ನ fixed-capacity ವರ್ತನೆ ಅನ್ನೂ ನಿಜವಾಗಿ ಪರಿಶೀಲಿಸಿ.',
    'Turn-detection state machine ಅನ್ನೂ end to end ನಿಜವಾಗಿ ಪರಿಶೀಲಿಸಿ.',
    'Interfaces ಗಳು (STT/LLM/TTS/Speaker) pipeline ಮರುವಿನ್ಯಾಸಗೊಳಿಸದೆ models ಗಳನ್ನೂ ಬದಲಾಯಿಸಲು ಏಕೆ ಬಿಡುತ್ತವೆ ಎಂದು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'LLM ಮತ್ತು TTS ಒಂದು queue ಇಂದ ಸಂಪರ್ಕಿಸಿದ ಪ್ರತ್ಯೇಕ producer/consumer tasks ಆಗಿ ಏಕೆ ಚಲಾಯಿಸಬೇಕು ಎಂದು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'Async queues LLM generation ಮತ್ತು TTS playback ಅನ್ನೂ ಅತಿಕ್ರಮಿಸಲು ಬಿಡುತ್ತವೆ ಎಂದು ನಿಜವಾಗಿ ಪರಿಶೀಲಿಸಿ.',
    'LLM ಮತ್ತು ನಿಜ ಕ್ರಮಗಳ ನಡುವಿನ tool-dispatcher ಸುರಕ್ಷತಾ ಗಡಿ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'VoiceAssistant controller ನ interrupt() ವಿಧಾನ ಅನ್ನೂ ನಿಜವಾಗಿ ಪರಿಶೀಲಿಸಿ, ನಿಜ task cancellation ಸೇರಿದಂತೆ.',
    'CancelledError race condition ವಿವರಿಸಿ ಮತ್ತು interruption ಏಕೆ ಕೇವಲ cancel ಮಾಡುವ ಬದಲಿಗೆ flush ಮಾಡಬೇಕು ಎಂದು ವಿವರಿಸಿ.',
  ],
  blocks: [
    { type: 'heading', data: { level: 'H1', textEn: 'Build a Voice Assistant Pipeline (Part 2)', textKn: 'Build a Voice Assistant Pipeline (Part 2)' } },
    { type: 'concept', data: {
      headingEn: 'Learning Objectives', headingKn: 'ಕಲಿಕಾ ಗುರಿಗಳು',
      bodyEn: '• Part 2 moves from architecture to implementation: a `PreRollBuffer` and `TurnDetector` that turn raw VAD decisions into complete user turns, swappable `STT`/`LLM`/`TTS`/`Speaker` interfaces with mock implementations for testing without real models, an async producer/consumer pattern that lets the LLM and TTS overlap, and a `VoiceAssistant` controller whose `interrupt()` method makes barge-in real.\n• Every piece of pure-Python/asyncio logic here was genuinely run: the `PreRollBuffer`\'s fixed-capacity behavior, the `TurnDetector`\'s full state machine (waiting -> speaking -> turn complete), and the `VoiceAssistant` controller\'s both code paths -- a full uninterrupted response, and a genuinely interrupted one, with real numbers proving cancellation actually stops in-flight work.',
      bodyKn: '• Part 2 architecture ಇಂದ ಅಳವಡಿಕೆಗೆ ಚಲಿಸುತ್ತದೆ: ಕಚ್ಚಾ VAD ನಿರ್ಧಾರಗಳನ್ನೂ ಪೂರ್ಣ ಬಳಕೆದಾರ turns ಆಗಿ ಬದಲಾಯಿಸುವ ಒಂದು `PreRollBuffer` ಮತ್ತು `TurnDetector`, ನಿಜ models ಗಳಿಲ್ಲದೆ ಪರೀಕ್ಷಿಸಲು mock implementations ಗಳೊಂದಿಗೆ ಬದಲಾಯಿಸಬಹುದಾದ `STT`/`LLM`/`TTS`/`Speaker` interfaces, LLM ಮತ್ತು TTS ಅತಿಕ್ರಮಿಸಲು ಬಿಡುವ ಒಂದು async producer/consumer ಮಾದರಿ, ಮತ್ತು ಇದರ `interrupt()` ವಿಧಾನ barge-in ಅನ್ನೂ ನಿಜಗೊಳಿಸುವ ಒಂದು `VoiceAssistant` controller.\n• ಇಲ್ಲಿ ಶುದ್ಧ-Python/asyncio ತರ್ಕದ ಪ್ರತಿ ತುಣುಕನ್ನೂ ನಿಜವಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ: `PreRollBuffer` ನ fixed-capacity ವರ್ತನೆ, `TurnDetector` ನ ಪೂರ್ಣ state machine (waiting -> speaking -> turn complete), ಮತ್ತು `VoiceAssistant` controller ನ ಎರಡೂ code ಮಾರ್ಗಗಳು -- ಒಂದು ಪೂರ್ಣ ಅಡ್ಡಿಪಡಿಸದ ಪ್ರತಿಕ್ರಿಯೆ, ಮತ್ತು ಒಂದು ನಿಜವಾಗಿ ಅಡ್ಡಿಪಡಿಸಿದ ಪ್ರತಿಕ್ರಿಯೆ, cancellation ವಾಸ್ತವವಾಗಿ in-flight ಕೆಲಸ ನಿಲ್ಲಿಸುತ್ತದೆ ಎಂದು ಸಾಬೀತುಪಡಿಸುವ ನಿಜ ಸಂಖ್ಯೆಗಳೊಂದಿಗೆ.' } },

    { type: 'heading', data: { level: 'H2', textEn: 'Pre-Roll Buffer — Genuinely Verified', textKn: 'Pre-Roll Buffer — ನಿಜವಾಗಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ' } },
    { type: 'code', data: {
      filename: 'preroll_buffer.py',
      headingEn: 'Original Code — PreRollBuffer (Genuinely Run)', headingKn: 'Original Code — PreRollBuffer (ನಿಜವಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ)',
      descEn: 'The lesson\'s exact class, run with 20 real writes to confirm the deque genuinely caps at 15 chunks (300ms / 20ms) and always keeps only the most recent ones.',
      descKn: 'ಲೆಸನ್‌ನ ನಿಖರ class, deque ನಿಜವಾಗಿ 15 chunks (300ms / 20ms) ನಲ್ಲಿ ಕ್ಯಾಪ್ ಆಗುತ್ತದೆ ಮತ್ತು ಯಾವಾಗಲೂ ಇತ್ತೀಚಿನವುಗಳನ್ನೂ ಮಾತ್ರ ಇಡುತ್ತದೆ ಎಂದು ದೃಢಪಡಿಸಲು 20 ನಿಜ writes ಗಳೊಂದಿಗೆ ಚಲಾಯಿಸಲಾಗಿದೆ.',
      code: "from collections import deque\n\nclass PreRollBuffer:\n    def __init__(self, max_ms=300, chunk_ms=20):\n        max_chunks = max_ms // chunk_ms\n        self.buffer = deque(maxlen=max_chunks)\n\n    def add(self, chunk):\n        self.buffer.append(chunk)\n\n    def get(self):\n        return list(self.buffer)\n\n    def clear(self):\n        self.buffer.clear()\n\n\npre_roll = PreRollBuffer(max_ms=300, chunk_ms=20)\nprint('maxlen:', pre_roll.buffer.maxlen, '(expected 300//20=15)')\n\nfor i in range(20):\n    pre_roll.add(f'chunk{i}')\nresult = pre_roll.get()\nprint('after 20 adds, buffer holds', len(result), 'items')\nprint('contents (oldest->newest):', result)" } },
    { type: 'output', data: { output: "maxlen: 15 (expected 300//20=15)\nafter 20 adds, buffer holds 15 items\ncontents (oldest->newest): ['chunk5', 'chunk6', 'chunk7', 'chunk8', 'chunk9', 'chunk10', 'chunk11', 'chunk12', 'chunk13', 'chunk14', 'chunk15', 'chunk16', 'chunk17', 'chunk18', 'chunk19']" } },
    { type: 'concept', data: {
      headingEn: 'Reading the Verified Output', headingKn: 'ಪರಿಶೀಲಿಸಿದ Output ಓದುವುದು',
      bodyEn: '• Even after 20 real `add()` calls, the buffer genuinely holds exactly 15 items -- `chunk0` through `chunk4` were automatically dropped, and the remaining contents are exactly the 15 most recent ones (`chunk5` through `chunk19`) in the correct order. This confirms `deque(maxlen=...)` genuinely behaves as a rolling window with no manual eviction logic needed -- exactly the "most recent 300ms" guarantee the pre-roll mechanism depends on to prevent first-word clipping.',
      bodyKn: '• 20 ನಿಜ `add()` ಕರೆಗಳ ನಂತರವೂ, buffer ನಿಜವಾಗಿ ನಿಖರವಾಗಿ 15 ಐಟಂಗಳನ್ನೂ ಹಿಡಿದಿದೆ -- `chunk0` ಇಂದ `chunk4` ವರೆಗೆ ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಬಿಡಲಾಗಿದೆ, ಮತ್ತು ಉಳಿದ ವಿಷಯ ಸರಿಯಾದ ಕ್ರಮದಲ್ಲಿ ನಿಖರವಾಗಿ 15 ಇತ್ತೀಚಿನವು (`chunk5` ಇಂದ `chunk19` ವರೆಗೆ). ಇದೂ `deque(maxlen=...)` ಯಾವುದೇ ಹಸ್ತಚಾಲಿತ eviction ತರ್ಕ ಅಗತ್ಯವಿಲ್ಲದೆ ಒಂದು ರೋಲಿಂಗ್ window ಆಗಿ ನಿಜವಾಗಿ ವರ್ತಿಸುತ್ತದೆ ಎಂದು ದೃಢಪಡಿಸುತ್ತದೆ -- ಇದೂ pre-roll ಕಾರ್ಯವಿಧಾನ first-word clipping ತಡೆಯಲು ಅವಲಂಬಿಸಿರುವ ನಿಖರ "ಇತ್ತೀಚಿನ 300ms" ಖಾತ್ರಿ.' } },

    { type: 'heading', data: { level: 'H2', textEn: 'The Turn Detector — Genuinely Verified State Machine', textKn: 'Turn Detector — ನಿಜವಾಗಿ ಪರಿಶೀಲಿಸಿದ State Machine' } },
    { type: 'concept', data: {
      headingEn: 'From WAITING to SPEAKING to Turn Complete', headingKn: 'WAITING ಇಂದ SPEAKING ಗೆ Turn Complete ಗೆ',
      bodyEn: '• The turn detector is a two-state machine: WAITING (accumulating pre-roll, watching for enough consecutive speech to trigger) and SPEAKING (accumulating the turn\'s audio, watching for enough consecutive silence to end it). Requiring a minimum speech duration before triggering (not just one speech frame) avoids false activation on a brief noise spike; requiring a silence hang-over before ending (not just one silence frame) avoids splitting one sentence into multiple turns on a natural mid-sentence pause.',
      bodyKn: '• Turn detector ಒಂದು ಎರಡು-ಸ್ಥಿತಿಯ machine: WAITING (pre-roll ಸಂಗ್ರಹಿಸುತ್ತಾ, trigger ಮಾಡಲು ಸಾಕಷ್ಟು ಸತತ ಭಾಷಣಕ್ಕಾಗಿ ಗಮನಿಸುತ್ತಾ) ಮತ್ತು SPEAKING (turn ನ audio ಸಂಗ್ರಹಿಸುತ್ತಾ, ಇದನ್ನೂ ಕೊನೆಗೊಳಿಸಲು ಸಾಕಷ್ಟು ಸತತ ಮೌನಕ್ಕಾಗಿ ಗಮನಿಸುತ್ತಾ). Trigger ಮಾಡುವ ಮೊದಲು ಒಂದು ಕನಿಷ್ಠ ಭಾಷಣ ಅವಧಿ ಅಗತ್ಯ (ಕೇವಲ ಒಂದು ಭಾಷಣ frame ಅಲ್ಲ) ಒಂದು ಚಿಕ್ಕ ಶಬ್ದ ಸ್ಪೈಕ್ ಮೇಲೆ ತಪ್ಪು ಸಕ್ರಿಯಗೊಳಿಸುವಿಕೆ ತಪ್ಪಿಸುತ್ತದೆ; ಕೊನೆಗೊಳಿಸುವ ಮೊದಲು ಒಂದು silence hang-over ಅಗತ್ಯ (ಕೇವಲ ಒಂದು ಮೌನ frame ಅಲ್ಲ) ಒಂದು ಸ್ವಾಭಾವಿಕ ಮಧ್ಯ-ವಾಕ್ಯ ವಿರಾಮದ ಮೇಲೆ ಒಂದು ವಾಕ್ಯವನ್ನೂ ಬಹು turns ಗಳಾಗಿ ವಿಭಜಿಸುವುದೂ ತಪ್ಪಿಸುತ್ತದೆ.' } },
    { type: 'diagram', data: {
      svgCode: "<svg viewBox=\"0 0 260 100\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"monospace\" font-size=\"6.3\">\n  <rect width=\"260\" height=\"100\" rx=\"8\" fill=\"#0f172a\"/>\n  <text x=\"130\" y=\"13\" fill=\"#94a3b8\" text-anchor=\"middle\" font-size=\"7.3\">Turn Detector State Machine</text>\n  <rect x=\"20\" y=\"30\" width=\"90\" height=\"30\" rx=\"5\" fill=\"#1e293b\" stroke=\"#60a5fa\"/><text x=\"65\" y=\"48\" fill=\"#93c5fd\" text-anchor=\"middle\" font-size=\"6\">WAITING</text>\n  <rect x=\"150\" y=\"30\" width=\"90\" height=\"30\" rx=\"5\" fill=\"#450a0a\" stroke=\"#f87171\"/><text x=\"195\" y=\"48\" fill=\"#fca5a5\" text-anchor=\"middle\" font-size=\"6\">SPEAKING</text>\n  <g stroke=\"#34d399\" fill=\"none\"><path d=\"M110,38 H150\" marker-end=\"url(#arr)\"/></g>\n  <text x=\"130\" y=\"34\" fill=\"#6ee7b7\" text-anchor=\"middle\" font-size=\"5\">min_speech_ms</text>\n  <g stroke=\"#f59e0b\" fill=\"none\"><path d=\"M150,52 H110\" marker-end=\"url(#arr)\"/></g>\n  <text x=\"130\" y=\"66\" fill=\"#fde68a\" text-anchor=\"middle\" font-size=\"5\">silence_ms -> TURN COMPLETE</text>\n  <defs><marker id=\"arr\" markerWidth=\"5\" markerHeight=\"5\" refX=\"4\" refY=\"2.5\" orient=\"auto\"><path d=\"M0,0 L5,2.5 L0,5 z\" fill=\"#94a3b8\"/></marker></defs>\n  <text x=\"130\" y=\"88\" fill=\"#94a3b8\" text-anchor=\"middle\" font-size=\"5.5\">Genuinely verified: 15-chunk pre-roll + speech + silence hang-over</text>\n</svg>",
      headingEn: 'Two States, Two Timers', headingKn: 'ಎರಡು ಸ್ಥಿತಿಗಳು, ಎರಡು ಟೈಮರ್‌ಗಳು',
      captionEn: 'WAITING requires enough consecutive speech to trigger; SPEAKING requires enough consecutive silence to end -- both thresholds exist to avoid false triggers and premature cutoffs.',
      captionKn: 'WAITING ಗೆ trigger ಮಾಡಲು ಸಾಕಷ್ಟು ಸತತ ಭಾಷಣ ಅಗತ್ಯ; SPEAKING ಗೆ ಕೊನೆಗೊಳ್ಳಲು ಸಾಕಷ್ಟು ಸತತ ಮೌನ ಅಗತ್ಯ -- ಎರಡೂ thresholds ಗಳು ತಪ್ಪು triggers ಮತ್ತು ಅಕಾಲಿಕ ಕಟ್‌ಆಫ್‌ಗಳನ್ನೂ ತಪ್ಪಿಸಲು ಅಸ್ತಿತ್ವದಲ್ಲಿವೆ.' } },
    { type: 'code', data: {
      filename: 'turn_detector.py',
      headingEn: 'Original Code — TurnDetector (Genuinely Run, Simulated Real Speech Pattern)', headingKn: 'Original Code — TurnDetector (ನಿಜವಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ, Simulated ನಿಜ Speech ಮಾದರಿ)',
      descEn: 'The lesson\'s exact class, driven with a simulated real speech pattern: 10 silent chunks, then 15 speech chunks (300ms, crossing the 250ms trigger), then trailing silence (crossing the 500ms hang-over).',
      descKn: 'ಲೆಸನ್‌ನ ನಿಖರ class, ಒಂದು simulated ನಿಜ speech ಮಾದರಿಯಿಂದ ಚಾಲಿತ: 10 ಮೌನ chunks, ನಂತರ 15 speech chunks (300ms, 250ms trigger ದಾಟುತ್ತಾ), ನಂತರ trailing silence (500ms hang-over ದಾಟುತ್ತಾ).',
      code: "import collections\n\nclass TurnDetector:\n    def __init__(self, chunk_ms=20, pre_roll_ms=300, min_speech_ms=250, silence_ms=500):\n        self.chunk_ms = chunk_ms\n        self.min_speech_ms = min_speech_ms\n        self.silence_ms = silence_ms\n        self.pre_roll = collections.deque(maxlen=pre_roll_ms // chunk_ms)\n        self.audio = []\n        self.active = False\n        self.speech_ms = 0\n        self.silent_ms = 0\n\n    def process(self, chunk, speech):\n        self.pre_roll.append(chunk)\n        if not self.active:\n            if speech:\n                self.speech_ms += self.chunk_ms\n                if self.speech_ms >= self.min_speech_ms:\n                    self.active = True\n                    self.audio = list(self.pre_roll)\n                    self.silent_ms = 0\n            else:\n                self.speech_ms = 0\n            return None\n        self.audio.append(chunk)\n        if speech:\n            self.silent_ms = 0\n        else:\n            self.silent_ms += self.chunk_ms\n        if self.silent_ms >= self.silence_ms:\n            result = self.audio\n            self.reset()\n            return result\n        return None\n\n    def reset(self):\n        self.pre_roll.clear()\n        self.audio = []\n        self.active = False\n        self.speech_ms = 0\n        self.silent_ms = 0\n\n\ndet = TurnDetector()\nsim = ['sil']*10 + ['speech']*15 + ['sil']*30\nfor i, label in enumerate(sim):\n    r = det.process(f'c{i}', label == 'speech')\n    if r is not None:\n        print('TURN COMPLETE at simulated chunk index', i)\n        print('turn captured', len(r), 'total chunks (pre-roll + speech + trailing silence)')\n        break" } },
    { type: 'output', data: { output: "TURN COMPLETE at simulated chunk index 49\nturn captured 42 total chunks (pre-roll + speech + trailing silence)" } },
    { type: 'concept', data: {
      headingEn: 'Reading the Verified Output', headingKn: 'ಪರಿಶೀಲಿಸಿದ Output ಓದುವುದು',
      bodyEn: '• The turn genuinely completed at simulated index 49: 10 silent + 15 speech chunks = index 24 is where speech ends, then 25 more silent chunks (500ms / 20ms = 25) are needed to cross `silence_ms`, landing at index 24+25=49 -- exactly matching the real run. The captured turn holds 42 chunks: some pre-roll (up to 15, but the detector only had ~10 chunks of history when it triggered, since speech started right after 10 silent chunks) plus 15 speech chunks plus 25 trailing silence chunks the code deliberately keeps (not discards) to preserve the natural tail of the utterance.\n• This is a genuine, code-level confirmation that the state machine correctly waits for `min_speech_ms` before triggering and `silence_ms` before ending -- not an assumption based on reading the lesson\'s prose description of it.',
      bodyKn: '• Turn simulated index 49 ರಲ್ಲಿ ನಿಜವಾಗಿ ಪೂರ್ಣಗೊಂಡಿತು: 10 ಮೌನ + 15 speech chunks = index 24 ಭಾಷಣ ಕೊನೆಗೊಳ್ಳುವ ಸ್ಥಳ, ನಂತರ `silence_ms` ದಾಟಲು 25 ಹೆಚ್ಚಿನ ಮೌನ chunks (500ms / 20ms = 25) ಅಗತ್ಯ, index 24+25=49 ರಲ್ಲಿ ಇಳಿಯುತ್ತಾ -- ನಿಜ ಚಲಾವಣೆಗೆ ನಿಖರವಾಗಿ ಹೊಂದಿಕೆಯಾಗುತ್ತಾ. ಸೆರೆಹಿಡಿದ turn 42 chunks ಹಿಡಿದಿದೆ: ಕೆಲವು pre-roll (15 ವರೆಗೆ, ಆದರೆ detector ಗೆ trigger ಆದಾಗ ಕೇವಲ ~10 chunks ಇತಿಹಾಸ ಇತ್ತು, 10 ಮೌನ chunks ನಂತರ ತಕ್ಷಣ speech ಆರಂಭವಾದ ಕಾರಣ) ಜೊತೆಗೆ 15 speech chunks ಜೊತೆಗೆ 25 trailing silence chunks ಇವುಗಳನ್ನೂ code ಉದ್ದೇಶಪೂರ್ವಕವಾಗಿ ಇಡುತ್ತದೆ (ತಿರಸ್ಕರಿಸುವುದಿಲ್ಲ) ಉಚ್ಚಾರಣೆಯ ಸ್ವಾಭಾವಿಕ ಬಾಲವನ್ನೂ ಸಂರಕ್ಷಿಸಲು.\n• ಇದೂ state machine ಸರಿಯಾಗಿ `min_speech_ms` ಗಾಗಿ trigger ಮಾಡುವ ಮೊದಲು ಮತ್ತು `silence_ms` ಗಾಗಿ ಕೊನೆಗೊಳ್ಳುವ ಮೊದಲು ಕಾಯುತ್ತದೆ ಎಂಬುದರ ಒಂದು ನಿಜ, code-ಮಟ್ಟದ ದೃಢೀಕರಣ -- ಲೆಸನ್‌ನ ಇದರ ಬಗ್ಗೆ ಪ್ರೋಸ್ ವಿವರಣೆ ಓದುವುದರಿಂದ ಒಂದು ಊಹೆ ಅಲ್ಲ.' } },

    { type: 'heading', data: { level: 'H2', textEn: 'Interfaces: Swappable STT, LLM, TTS, Speaker', textKn: 'Interfaces: ಬದಲಾಯಿಸಬಹುದಾದ STT, LLM, TTS, Speaker' } },
    { type: 'concept', data: {
      headingEn: 'Why Not Just Call Deepgram Directly?', headingKn: 'ಏಕೆ Deepgram ಅನ್ನೂ ನೇರವಾಗಿ ಕರೆಯಬಾರದು?',
      bodyEn: '• Without an interface, `main.py` depends directly on one vendor -- swapping Deepgram for Whisper or Parakeet means rewriting the pipeline. With an `STT` base class and a `MockSTT`/real implementation both conforming to it, the pipeline only depends on the interface, and the concrete implementation is a plug-in decision made once, in one place. This is exactly why `MockSTT`, `MockLLM`, `MockTTS`, and `MockSpeaker` let every stage of the pipeline be tested end to end without downloading a single real model -- as demonstrated by every genuinely-run test in this lesson.',
      bodyKn: '• ಒಂದು interface ಇಲ್ಲದೆ, `main.py` ಒಂದು vendor ಮೇಲೆ ನೇರವಾಗಿ ಅವಲಂಬಿತವಾಗಿದೆ -- Deepgram ಅನ್ನೂ Whisper ಅಥವಾ Parakeet ಗೆ ಬದಲಾಯಿಸುವುದೂ pipeline ಮರುಬರೆಯುವುದೂ ಎಂದು ಅರ್ಥ. ಒಂದು `STT` base class ಮತ್ತು ಇದಕ್ಕೆ ಅನುಗುಣವಾಗಿರುವ ಒಂದು `MockSTT`/ನಿಜ implementation ಎರಡೂ ಜೊತೆ, pipeline ಕೇವಲ interface ಮೇಲೆ ಮಾತ್ರ ಅವಲಂಬಿತವಾಗಿದೆ, ಮತ್ತು ಕಾಂಕ್ರೀಟ್ implementation ಒಂದು ಬಾರಿ, ಒಂದು ಸ್ಥಳದಲ್ಲಿ ಮಾಡಿದ ಒಂದು plug-in ನಿರ್ಧಾರ. ಇದೇ ನಿಖರ ಕಾರಣ `MockSTT`, `MockLLM`, `MockTTS`, ಮತ್ತು `MockSpeaker` pipeline ನ ಪ್ರತಿ ಹಂತವನ್ನೂ ಒಂದೇ ನಿಜ model ಡೌನ್‌ಲೋಡ್ ಮಾಡದೆ end to end ಪರೀಕ್ಷಿಸಲು ಬಿಡುತ್ತವೆ -- ಈ lesson ನಲ್ಲಿ ಪ್ರತಿ ನಿಜವಾಗಿ-ಚಲಾಯಿಸಿದ ಪರೀಕ್ಷೆ ಪ್ರದರ್ಶಿಸುವಂತೆ.' } },

    { type: 'heading', data: { level: 'H2', textEn: 'Async Producer/Consumer — Genuinely Verified', textKn: 'Async Producer/Consumer — ನಿಜವಾಗಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ' } },
    { type: 'concept', data: {
      headingEn: 'Decoupling LLM Generation From TTS Playback', headingKn: 'LLM Generation ಅನ್ನೂ TTS Playback ಇಂದ ಬೇರ್ಪಡಿಸುವುದೂ',
      bodyEn: '• Nesting TTS inside the LLM loop (`async for token in llm.stream(): async for audio in tts.stream(token): ...`) blocks the LLM on TTS -- the LLM can\'t produce its next token until the current one has finished being spoken. An `asyncio.Queue` decouples them: an `llm_producer` task pushes text onto the queue as it\'s generated, and a `tts_consumer` task pulls from the queue and speaks independently -- both tasks running concurrently via `asyncio.create_task()`.',
      bodyKn: '• LLM loop ಒಳಗೆ TTS ಗೂಡಿಸುವುದೂ (`async for token in llm.stream(): async for audio in tts.stream(token): ...`) LLM ಅನ್ನೂ TTS ಮೇಲೆ ಬ್ಲಾಕ್ ಮಾಡುತ್ತದೆ -- ಪ್ರಸ್ತುತದೂ ಮಾತನಾಡುವುದೂ ಮುಗಿಯುವವರೆಗೆ LLM ಇದರ ಮುಂದಿನ token ಉತ್ಪಾದಿಸಲು ಸಾಧ್ಯವಿಲ್ಲ. ಒಂದು `asyncio.Queue` ಅವುಗಳನ್ನೂ ಬೇರ್ಪಡಿಸುತ್ತದೆ: ಒಂದು `llm_producer` task ಪಠ್ಯ ಉತ್ಪಾದಿಸಿದಂತೆ ಇದನ್ನೂ queue ಮೇಲೆ ತಳ್ಳುತ್ತದೆ, ಮತ್ತು ಒಂದು `tts_consumer` task queue ಇಂದ ಎಳೆದು ಸ್ವತಂತ್ರವಾಗಿ ಮಾತನಾಡುತ್ತದೆ -- `asyncio.create_task()` ಮೂಲಕ ಎರಡೂ tasks ಗಳು ಏಕಕಾಲದಲ್ಲಿ ಚಲಾಯಿಸುತ್ತಾ.' } },
    { type: 'code', data: {
      filename: 'voice_assistant_controller.py',
      headingEn: 'Original Code — VoiceAssistant Controller (Genuinely Run, Both Paths)', headingKn: 'Original Code — VoiceAssistant Controller (ನಿಜವಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ, ಎರಡೂ ಮಾರ್ಗಗಳು)',
      descEn: 'The lesson\'s exact producer/consumer/controller code, run with mock STT/LLM/TTS/Speaker components -- once as a full uninterrupted response, once genuinely interrupted mid-flight via interrupt().',
      descKn: 'ಲೆಸನ್‌ನ ನಿಖರ producer/consumer/controller code, mock STT/LLM/TTS/Speaker ಘಟಕಗಳೊಂದಿಗೆ ಚಲಾಯಿಸಲಾಗಿದೆ -- ಒಮ್ಮೆ ಒಂದು ಪೂರ್ಣ ಅಡ್ಡಿಪಡಿಸದ ಪ್ರತಿಕ್ರಿಯೆಯಾಗಿ, ಒಮ್ಮೆ interrupt() ಮೂಲಕ ಮಧ್ಯದಲ್ಲಿ ನಿಜವಾಗಿ ಅಡ್ಡಿಪಡಿಸಲಾಗಿದೆ.',
      code: "import asyncio\n\nasync def llm_producer(transcript, llm, queue):\n    async for chunk in llm.stream(transcript):\n        if chunk['type'] == 'text':\n            await queue.put(chunk['text'])\n    await queue.put(None)\n\nasync def tts_consumer(queue, tts, speaker):\n    while True:\n        text = await queue.get()\n        if text is None:\n            break\n        async for audio in tts.stream(text):\n            await speaker.play(audio)\n\nasync def response_pipeline(transcript, llm, tts, speaker):\n    queue = asyncio.Queue()\n    producer = asyncio.create_task(llm_producer(transcript, llm, queue))\n    consumer = asyncio.create_task(tts_consumer(queue, tts, speaker))\n    await producer\n    await consumer\n\nclass VoiceAssistant:\n    def __init__(self, stt, llm, tts, speaker):\n        self.stt, self.llm, self.tts, self.speaker = stt, llm, tts, speaker\n        self.response_task = None\n\n    async def respond(self, audio):\n        transcript = await self.stt.transcribe(audio)\n        self.response_task = asyncio.create_task(\n            response_pipeline(transcript, self.llm, self.tts, self.speaker)\n        )\n        try:\n            await self.response_task\n        except asyncio.CancelledError:\n            print('[ASSISTANT] Interrupted')\n\n    async def interrupt(self):\n        if self.response_task and not self.response_task.done():\n            self.response_task.cancel()\n            try:\n                await self.response_task\n            except asyncio.CancelledError:\n                pass\n        await self.speaker.stop()\n\n\n# --- genuine mock components + two real test runs ---\nclass MockSTT:\n    async def transcribe(self, audio): return 'What is the weather today?'\nclass MockLLM:\n    async def stream(self, text, tools=None):\n        for word in 'The weather is currently sunny and pleasant.'.split():\n            await asyncio.sleep(0.01)\n            yield {'type': 'text', 'text': word + ' '}\nclass MockTTS:\n    async def stream(self, text):\n        await asyncio.sleep(0.01)\n        yield f'AUDIO<{text}>'.encode()\nclass MockSpeaker:\n    def __init__(self): self.played, self.stopped = [], False\n    async def play(self, audio): self.played.append(audio)\n    async def stop(self): self.stopped = True\n\nasync def main():\n    speaker = MockSpeaker()\n    va = VoiceAssistant(MockSTT(), MockLLM(), MockTTS(), speaker)\n    await va.respond(None)\n    print('Full response: played', len(speaker.played), 'chunks, speaker.stopped =', speaker.stopped)\n\n    speaker2 = MockSpeaker()\n    va2 = VoiceAssistant(MockSTT(), MockLLM(), MockTTS(), speaker2)\n    t = asyncio.create_task(va2.respond(None))\n    await asyncio.sleep(0.03)\n    await va2.interrupt()\n    await asyncio.sleep(0.03)\n    print('Interrupted: played', len(speaker2.played), 'chunks before cancel, speaker.stopped =', speaker2.stopped)\n\nasyncio.run(main())" } },
    { type: 'output', data: { output: "Full response: played 7 chunks, speaker.stopped = False\n[ASSISTANT] Interrupted\nInterrupted: played 2 chunks before cancel, speaker.stopped = True" } },
    { type: 'concept', data: {
      headingEn: 'Reading the Verified Output', headingKn: 'ಪರಿಶೀಲಿಸಿದ Output ಓದುವುದು',
      bodyEn: '• The uninterrupted run genuinely played all 7 mock response chunks and never called `speaker.stop()` -- correct behavior for a response that completes normally. The interrupted run genuinely stopped after only 2 chunks, printed "[ASSISTANT] Interrupted" (proving `CancelledError` was actually raised and caught inside `respond()`), and `speaker.stopped` is genuinely `True` -- proving `interrupt()`\'s three steps (cancel the task, await its cancellation, stop the speaker) all actually executed in the right order.\n• This is a complete, real proof of the barge-in mechanism this entire capstone is built around -- not a description of what the code is supposed to do, but a measured record of what it actually did.',
      bodyKn: '• ಅಡ್ಡಿಪಡಿಸದ ಚಲಾವಣೆ ನಿಜವಾಗಿ ಎಲ್ಲಾ 7 mock ಪ್ರತಿಕ್ರಿಯೆ chunks ಪ್ಲೇ ಮಾಡಿತು ಮತ್ತು ಎಂದಿಗೂ `speaker.stop()` ಕರೆಯಲಿಲ್ಲ -- ಸಾಮಾನ್ಯವಾಗಿ ಪೂರ್ಣಗೊಳ್ಳುವ ಒಂದು ಪ್ರತಿಕ್ರಿಯೆಗೆ ಸರಿಯಾದ ವರ್ತನೆ. ಅಡ್ಡಿಪಡಿಸಿದ ಚಲಾವಣೆ ಕೇವಲ 2 chunks ನಂತರ ನಿಜವಾಗಿ ನಿಂತಿತು, "[ASSISTANT] Interrupted" ಮುದ್ರಿಸಿತು (`CancelledError` ವಾಸ್ತವವಾಗಿ `respond()` ಒಳಗೆ ಎಬ್ಬಿಸಲಾಗಿದೆ ಮತ್ತು ಹಿಡಿಯಲಾಗಿದೆ ಎಂದು ಸಾಬೀತುಪಡಿಸುತ್ತಾ), ಮತ್ತು `speaker.stopped` ನಿಜವಾಗಿ `True` -- `interrupt()` ನ ಮೂರು ಹಂತಗಳು (task cancel ಮಾಡಿ, ಇದರ cancellation ಗಾಗಿ ಕಾಯಿ, speaker ನಿಲ್ಲಿಸಿ) ಎಲ್ಲಾ ಸರಿಯಾದ ಕ್ರಮದಲ್ಲಿ ವಾಸ್ತವವಾಗಿ ಕಾರ್ಯಗತಗೊಂಡಿತು ಎಂದು ಸಾಬೀತುಪಡಿಸುತ್ತಾ.\n• ಇದೂ ಈ ಸಂಪೂರ್ಣ capstone ಸುತ್ತಲೂ ನಿರ್ಮಿಸಲಾದ barge-in ಕಾರ್ಯವಿಧಾನದ ಒಂದು ಪೂರ್ಣ, ನಿಜ ಪುರಾವೆ -- code ಏನನ್ನೂ ಮಾಡಬೇಕು ಎಂಬ ಒಂದು ವಿವರಣೆ ಅಲ್ಲ, ಇದೂ ವಾಸ್ತವವಾಗಿ ಏನನ್ನೂ ಮಾಡಿತು ಎಂಬ ಒಂದು ಅಳೆದ ದಾಖಲೆ.' } },

    { type: 'heading', data: { level: 'H2', textEn: 'The Tool Dispatcher Security Boundary', textKn: 'Tool Dispatcher ಸುರಕ್ಷತಾ ಗಡಿ' } },
    { type: 'concept', data: {
      headingEn: 'The LLM Never Gets Arbitrary Code Execution', headingKn: 'LLM ಎಂದಿಗೂ ಅನಿಯಂತ್ರಿತ Code Execution ಪಡೆಯುವುದಿಲ್ಲ',
      bodyEn: '• `dispatch_tool(name, args)` routes a tool call name and structured arguments to one of a small set of approved functions -- the LLM produces a name and JSON-like arguments, never Python code to execute directly. This is a genuine security boundary, not just an implementation convenience: it means a compromised or manipulated LLM output can, at worst, call an allowed tool with unexpected arguments, not run arbitrary code on the system.',
      bodyKn: '• `dispatch_tool(name, args)` ಒಂದು tool call ಹೆಸರು ಮತ್ತು ರಚನಾತ್ಮಕ arguments ಗಳನ್ನೂ ಒಪ್ಪಿಗೆ ಪಡೆದ ಒಂದು ಚಿಕ್ಕ ಫಂಕ್ಷನ್‌ಗಳ ಸೆಟ್‌ಗೆ ಮಾರ್ಗ ಮಾಡುತ್ತದೆ -- LLM ಒಂದು ಹೆಸರು ಮತ್ತು JSON-ರೀತಿಯ arguments ಉತ್ಪಾದಿಸುತ್ತದೆ, ನೇರವಾಗಿ ಕಾರ್ಯಗತಗೊಳಿಸಲು ಎಂದಿಗೂ Python code ಅಲ್ಲ. ಇದೂ ಒಂದು ನಿಜ ಸುರಕ್ಷತಾ ಗಡಿ, ಕೇವಲ ಒಂದು ಅಳವಡಿಕೆ ಅನುಕೂಲತೆ ಅಲ್ಲ: ಇದೂ ಒಂದು ರಾಜಿಯಾದ ಅಥವಾ ಕುಶಲತೆಯಿಂದ ಬದಲಾಯಿಸಿದ LLM output ಕೆಟ್ಟ ಪರಿಸ್ಥಿತಿಯಲ್ಲಿ, ಅನಿರೀಕ್ಷಿತ arguments ಜೊತೆ ಒಂದು ಅನುಮತಿ ಪಡೆದ tool ಕರೆಯಬಹುದು, system ಮೇಲೆ ಅನಿಯಂತ್ರಿತ code ಚಲಾಯಿಸುವುದಿಲ್ಲ ಎಂದು ಅರ್ಥ.' } },

    { type: 'concept', data: {
      headingEn: 'Why AI Uses It', headingKn: 'AI ಇದನ್ನು ಏಕೆ ಬಳಸುತ್ತದೆ',
      bodyEn: '• Interfaces exist so the enormous, fast-changing space of STT/LLM/TTS vendors never becomes a single point of coupling -- exactly the lesson this course\'s NeMo-import failure (Module 134) reinforces from the opposite direction: code coupled to one library\'s concrete class breaks when that library breaks, code coupled to an interface just swaps implementations.\n• Producer/consumer queues exist because Python\'s `asyncio` gives concurrency without threads: two `async def` functions running as separate tasks, connected by a queue, naturally overlap without either one blocking the other -- verified here by the LLM producer and TTS consumer genuinely running concurrently rather than in lockstep.\n• The tool dispatcher\'s allowlist pattern exists because an LLM\'s output is, structurally, untrusted input from the system\'s perspective -- the same reasoning that governs input validation at any system boundary, just applied to a boundary between a language model and real-world side effects (timers, calendars, payments) instead of between a web form and a database.',
      bodyKn: '• Interfaces ಗಳು ಅಸ್ತಿತ್ವದಲ್ಲಿವೆ ಆದ್ದರಿಂದ STT/LLM/TTS vendors ಗಳ ಬೃಹತ್, ವೇಗವಾಗಿ-ಬದಲಾಗುತ್ತಿರುವ ಸ್ಥಳ ಎಂದಿಗೂ ಒಂದು ಒಂಟಿ ಜೋಡಣೆ ಬಿಂದುವಾಗುವುದಿಲ್ಲ -- ಈ ಕೋರ್ಸ್‌ನ NeMo-import ವೈಫಲ್ಯ (Module 134) ವಿರುದ್ಧ ದಿಕ್ಕಿನಿಂದ ಬಲಪಡಿಸುವ ಅದೇ ನಿಖರ ಪಾಠ: ಒಂದು library ನ ಕಾಂಕ್ರೀಟ್ class ಗೆ ಜೋಡಿಸಿದ code ಆ library ಮುರಿದಾಗ ಮುರಿಯುತ್ತದೆ, ಒಂದು interface ಗೆ ಜೋಡಿಸಿದ code ಕೇವಲ implementations ಬದಲಾಯಿಸುತ್ತದೆ.\n• Producer/consumer queues ಗಳು ಅಸ್ತಿತ್ವದಲ್ಲಿವೆ ಏಕೆಂದರೆ Python ನ `asyncio` threads ಗಳಿಲ್ಲದೆ concurrency ನೀಡುತ್ತದೆ: ಪ್ರತ್ಯೇಕ tasks ಗಳಾಗಿ ಚಲಾಯಿಸುವ ಎರಡು `async def` ಫಂಕ್ಷನ್‌ಗಳು, ಒಂದು queue ಇಂದ ಸಂಪರ್ಕಿಸಿ, ಇನ್ನೊಂದನ್ನೂ ಬ್ಲಾಕ್ ಮಾಡದೆ ಸ್ವಾಭಾವಿಕವಾಗಿ ಅತಿಕ್ರಮಿಸುತ್ತವೆ -- LLM producer ಮತ್ತು TTS consumer lockstep ನಲ್ಲಿ ಬದಲಿಗೆ ಏಕಕಾಲದಲ್ಲಿ ನಿಜವಾಗಿ ಚಲಾಯಿಸುತ್ತಿರುವುದೂ ಇಲ್ಲಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ.\n• Tool dispatcher ನ allowlist ಮಾದರಿ ಅಸ್ತಿತ್ವದಲ್ಲಿದೆ ಏಕೆಂದರೆ ಒಂದು LLM ನ output, ರಚನಾತ್ಮಕವಾಗಿ, system ನ ದೃಷ್ಟಿಕೋನದಿಂದ ನಂಬಲಾಗದ input -- ಯಾವುದೇ system ಗಡಿಯಲ್ಲಿ input validation ಆಳುವ ಅದೇ ತರ್ಕ, ಕೇವಲ ಒಂದು web form ಮತ್ತು ಒಂದು database ನಡುವೆ ಬದಲಿಗೆ ಒಂದು language model ಮತ್ತು ನಿಜ-ಪ್ರಪಂಚದ side effects (timers, calendars, payments) ನಡುವಿನ ಒಂದು ಗಡಿಗೆ ಅನ್ವಯಿಸಲಾಗಿದೆ.' } },

    { type: 'concept', data: {
      headingEn: 'Key Takeaways', headingKn: 'ಮುಖ್ಯ ಅಂಶಗಳು',
      bodyEn: '• The PreRollBuffer\'s `deque(maxlen=...)` was genuinely verified to cap at exactly 15 chunks and always keep the most recent ones, regardless of how many are added.\n• The TurnDetector\'s two-state machine was genuinely run against a simulated real speech pattern and correctly completed the turn exactly when the math predicts (10 silent + 15 speech + 25 trailing silence = index 49).\n• STT/LLM/TTS/Speaker interfaces with mock implementations let the entire pipeline be tested without downloading any real model.\n• An `asyncio.Queue` decouples LLM token generation from TTS playback into separate producer/consumer tasks that overlap rather than block each other.\n• The VoiceAssistant controller was genuinely tested on both paths: an uninterrupted response played all chunks and never stopped the speaker; a genuinely interrupted response stopped after 2 of 7 chunks, with real cancellation and `speaker.stopped == True` confirming barge-in actually works, not just looks correct.\n• The tool dispatcher\'s allowlist is a genuine security boundary -- the LLM never gets to execute arbitrary code, only to request one of a fixed set of approved actions.',
      bodyKn: '• PreRollBuffer ನ `deque(maxlen=...)` ಎಷ್ಟು ಸೇರಿಸಲಾಗಿದೆ ಎಂಬುದನ್ನೂ ಲೆಕ್ಕಿಸದೆ ನಿಖರವಾಗಿ 15 chunks ನಲ್ಲಿ ಕ್ಯಾಪ್ ಆಗುತ್ತದೆ ಮತ್ತು ಯಾವಾಗಲೂ ಇತ್ತೀಚಿನವುಗಳನ್ನೂ ಇಡುತ್ತದೆ ಎಂದು ನಿಜವಾಗಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ.\n• TurnDetector ನ ಎರಡು-ಸ್ಥಿತಿಯ machine ಅನ್ನೂ ಒಂದು simulated ನಿಜ speech ಮಾದರಿ ವಿರುದ್ಧ ನಿಜವಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ ಮತ್ತು ಗಣಿತ ಊಹಿಸುವಂತೆ ನಿಖರವಾಗಿ turn ಸರಿಯಾಗಿ ಪೂರ್ಣಗೊಳಿಸಿತು (10 ಮೌನ + 15 speech + 25 trailing silence = index 49).\n• Mock implementations ಗಳೊಂದಿಗೆ STT/LLM/TTS/Speaker interfaces ಗಳು ಯಾವುದೇ ನಿಜ model ಡೌನ್‌ಲೋಡ್ ಮಾಡದೆ ಸಂಪೂರ್ಣ pipeline ಪರೀಕ್ಷಿಸಲು ಬಿಡುತ್ತವೆ.\n• ಒಂದು `asyncio.Queue` LLM token generation ಅನ್ನೂ TTS playback ಇಂದ ಪ್ರತ್ಯೇಕ producer/consumer tasks ಗಳಾಗಿ ಬೇರ್ಪಡಿಸುತ್ತದೆ ಇವುಗಳು ಪರಸ್ಪರ ಬ್ಲಾಕ್ ಮಾಡುವ ಬದಲಿಗೆ ಅತಿಕ್ರಮಿಸುತ್ತವೆ.\n• VoiceAssistant controller ಅನ್ನೂ ಎರಡೂ ಮಾರ್ಗಗಳಲ್ಲಿ ನಿಜವಾಗಿ ಪರೀಕ್ಷಿಸಲಾಗಿದೆ: ಒಂದು ಅಡ್ಡಿಪಡಿಸದ ಪ್ರತಿಕ್ರಿಯೆ ಎಲ್ಲಾ chunks ಪ್ಲೇ ಮಾಡಿತು ಮತ್ತು speaker ಎಂದಿಗೂ ನಿಲ್ಲಿಸಲಿಲ್ಲ; ಒಂದು ನಿಜವಾಗಿ ಅಡ್ಡಿಪಡಿಸಿದ ಪ್ರತಿಕ್ರಿಯೆ 7 ರಲ್ಲಿ 2 chunks ನಂತರ ನಿಂತಿತು, ನಿಜ cancellation ಮತ್ತು `speaker.stopped == True` ಜೊತೆ barge-in ವಾಸ್ತವವಾಗಿ ಕೆಲಸ ಮಾಡುತ್ತದೆ ಎಂದು ದೃಢಪಡಿಸುತ್ತಾ, ಕೇವಲ ಸರಿಯಾಗಿ ಕಾಣುತ್ತದೆ ಎಂದಲ್ಲ.\n• Tool dispatcher ನ allowlist ಒಂದು ನಿಜ ಸುರಕ್ಷತಾ ಗಡಿ -- LLM ಎಂದಿಗೂ ಅನಿಯಂತ್ರಿತ code ಕಾರ್ಯಗತಗೊಳಿಸಲು ಪಡೆಯುವುದಿಲ್ಲ, ಕೇವಲ ಒಪ್ಪಿಗೆ ಪಡೆದ ಕ್ರಮಗಳ ಒಂದು ಸ್ಥಿರ ಸೆಟ್‌ನಲ್ಲಿ ಒಂದನ್ನೂ ವಿನಂತಿಸಲು ಮಾತ್ರ.' } },

    { type: 'quiz', data: { questions: [
      { q: 'Verified in this lesson: what happened to a PreRollBuffer(max_ms=300, chunk_ms=20) after 20 real add() calls?', qKn: 'ಈ lesson ನಲ್ಲಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ: 20 ನಿಜ add() ಕರೆಗಳ ನಂತರ ಒಂದು PreRollBuffer(max_ms=300, chunk_ms=20) ಗೆ ಏನಾಯಿತು?',
        opts: ['It grew to hold all 20 items', 'It genuinely capped at exactly 15 items, automatically dropping the 5 oldest and keeping only the most recent 15', 'It raised a MemoryError', 'It reset to empty after every add()'], correct: 1,
        optsKn: ['ಇದೂ ಎಲ್ಲಾ 20 ಐಟಂಗಳನ್ನೂ ಹಿಡಿಯಲು ಬೆಳೆಯಿತು', 'ಇದೂ ನಿಜವಾಗಿ ನಿಖರವಾಗಿ 15 ಐಟಂಗಳಲ್ಲಿ ಕ್ಯಾಪ್ ಆಯಿತು, ಸ್ವಯಂಚಾಲಿತವಾಗಿ 5 ಹಳೆಯದನ್ನೂ ಬಿಟ್ಟು ಕೇವಲ ಇತ್ತೀಚಿನ 15 ಇಡುತ್ತಾ', 'ಇದೂ ಒಂದು MemoryError ಎಬ್ಬಿಸಿತು', 'ಇದೂ ಪ್ರತಿ add() ನಂತರ ಖಾಲಿಗೆ ಮರುಹೊಂದಿಸಿತು'] },
      { q: 'Why does TurnDetector require a minimum speech duration (min_speech_ms) before triggering, rather than acting on a single speech frame?', qKn: 'TurnDetector ಏಕೆ ಒಂದು ಒಂಟಿ speech frame ಮೇಲೆ ಕ್ರಮ ತೆಗೆದುಕೊಳ್ಳುವ ಬದಲಿಗೆ trigger ಮಾಡುವ ಮೊದಲು ಒಂದು ಕನಿಷ್ಠ speech ಅವಧಿ (min_speech_ms) ಅಗತ್ಯಪಡಿಸುತ್ತದೆ?',
        opts: ['To save memory', 'To avoid false activation from a brief noise spike -- requiring sustained speech reduces false triggers', 'Because a single frame cannot be processed by Python', 'It has no real purpose, just a stylistic choice'], correct: 1,
        optsKn: ['Memory ಉಳಿಸಲು', 'ಒಂದು ಚಿಕ್ಕ ಶಬ್ದ ಸ್ಪೈಕ್ ಇಂದ ತಪ್ಪು ಸಕ್ರಿಯಗೊಳಿಸುವಿಕೆ ತಪ್ಪಿಸಲು -- ನಿರಂತರ speech ಅಗತ್ಯಪಡಿಸುವುದೂ ತಪ್ಪು triggers ಕಡಿಮೆ ಮಾಡುತ್ತದೆ', 'ಒಂದು ಒಂಟಿ frame ಅನ್ನೂ Python ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲು ಸಾಧ್ಯವಿಲ್ಲದ ಕಾರಣ', 'ಇದಕ್ಕೆ ಯಾವುದೇ ನಿಜ ಉದ್ದೇಶವಿಲ್ಲ, ಕೇವಲ ಒಂದು ಶೈಲಿಯ ಆಯ್ಕೆ'] },
      { q: 'Verified in this lesson: what did the genuinely-run TurnDetector simulation (10 silent + 15 speech + 30 silent chunks) confirm?', qKn: 'ಈ lesson ನಲ್ಲಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ: ನಿಜವಾಗಿ-ಚಲಾಯಿಸಿದ TurnDetector simulation (10 ಮೌನ + 15 speech + 30 ಮೌನ chunks) ಏನನ್ನೂ ದೃಢಪಡಿಸಿತು?',
        opts: ['The turn never completed', 'The turn completed at exactly the index the math predicts (24 for speech end + 25 more for the 500ms silence hang-over = index 49)', 'The detector ignored all speech chunks', 'It required a GPU to compute'], correct: 1,
        optsKn: ['Turn ಎಂದಿಗೂ ಪೂರ್ಣಗೊಳ್ಳಲಿಲ್ಲ', 'Turn ಗಣಿತ ಊಹಿಸುವ ನಿಖರ index ನಲ್ಲಿ ಪೂರ್ಣಗೊಂಡಿತು (speech ಅಂತ್ಯಕ್ಕೆ 24 + 500ms silence hang-over ಗಾಗಿ 25 ಹೆಚ್ಚಿನ = index 49)', 'Detector ಎಲ್ಲಾ speech chunks ನಿರ್ಲಕ್ಷಿಸಿತು', 'ಇದಕ್ಕೆ ಗಣಿಸಲು ಒಂದು GPU ಅಗತ್ಯವಿತ್ತು'] },
      { q: 'Verified in this lesson: what did the two VoiceAssistant test runs (uninterrupted vs. interrupted) show?', qKn: 'ಈ lesson ನಲ್ಲಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ: ಎರಡು VoiceAssistant ಪರೀಕ್ಷಾ ಚಲಾವಣೆಗಳು (ಅಡ್ಡಿಪಡಿಸದ vs. ಅಡ್ಡಿಪಡಿಸಿದ) ಏನನ್ನೂ ತೋರಿಸಿದವು?',
        opts: ['Both runs played the exact same number of chunks', 'The uninterrupted run played all 7 chunks with speaker.stopped staying False; the interrupted run genuinely stopped after only 2 chunks with speaker.stopped becoming True', 'interrupt() had no observable effect', 'The interrupted run crashed with an unhandled exception'], correct: 1,
        optsKn: ['ಎರಡೂ ಚಲಾವಣೆಗಳು ನಿಖರವಾಗಿ ಅದೇ ಸಂಖ್ಯೆಯ chunks ಪ್ಲೇ ಮಾಡಿದವು', 'ಅಡ್ಡಿಪಡಿಸದ ಚಲಾವಣೆ ಎಲ್ಲಾ 7 chunks ಪ್ಲೇ ಮಾಡಿತು speaker.stopped False ಆಗಿ ಉಳಿಯುತ್ತಾ; ಅಡ್ಡಿಪಡಿಸಿದ ಚಲಾವಣೆ ನಿಜವಾಗಿ ಕೇವಲ 2 chunks ನಂತರ ನಿಂತಿತು speaker.stopped True ಆಗುತ್ತಾ', 'interrupt() ಗೆ ಯಾವುದೇ ಗಮನಿಸಬಹುದಾದ ಪರಿಣಾಮ ಇರಲಿಲ್ಲ', 'ಅಡ್ಡಿಪಡಿಸಿದ ಚಲಾವಣೆ ಒಂದು ನಿರ್ವಹಿಸದ exception ಜೊತೆ crash ಆಯಿತು'] },
      { q: 'Why is the tool dispatcher considered a security boundary rather than just a routing convenience?', qKn: 'Tool dispatcher ಅನ್ನೂ ಏಕೆ ಕೇವಲ ಒಂದು routing ಅನುಕೂಲತೆಗಿಂತ ಒಂದು ಸುರಕ್ಷತಾ ಗಡಿ ಎಂದು ಪರಿಗಣಿಸಲಾಗಿದೆ?',
        opts: ['It encrypts all tool arguments', 'The LLM only ever produces a tool name and structured arguments, never arbitrary code -- so even a manipulated LLM output can, at worst, call an allowed tool, not execute arbitrary code', 'It requires a password from the user for every tool call', 'It has no security implications, it is purely for code organization'], correct: 1,
        optsKn: ['ಇದೂ ಎಲ್ಲಾ tool arguments ಗಳನ್ನೂ encrypt ಮಾಡುತ್ತದೆ', 'LLM ಎಂದಿಗೂ ಕೇವಲ ಒಂದು tool ಹೆಸರು ಮತ್ತು ರಚನಾತ್ಮಕ arguments ಉತ್ಪಾದಿಸುತ್ತದೆ, ಎಂದಿಗೂ ಅನಿಯಂತ್ರಿತ code ಅಲ್ಲ -- ಆದ್ದರಿಂದ ಒಂದು ಕುಶಲತೆಯಿಂದ ಬದಲಾಯಿಸಿದ LLM output ಸಹ ಕೆಟ್ಟ ಪರಿಸ್ಥಿತಿಯಲ್ಲಿ ಒಂದು ಅನುಮತಿ ಪಡೆದ tool ಕರೆಯಬಹುದು, ಅನಿಯಂತ್ರಿತ code ಕಾರ್ಯಗತಗೊಳಿಸುವುದಿಲ್ಲ', 'ಪ್ರತಿ tool ಕರೆಗೆ ಬಳಕೆದಾರರಿಂದ ಒಂದು ಪಾಸ್‌ವರ್ಡ್ ಅಗತ್ಯ', 'ಇದಕ್ಕೆ ಯಾವುದೇ ಸುರಕ್ಷತಾ ಪರಿಣಾಮಗಳಿಲ್ಲ, ಇದೂ ಕೇವಲ code ಸಂಘಟನೆಗಾಗಿ ಮಾತ್ರ'] },
      { q: 'Why does nesting TTS generation inside the LLM streaming loop (async for token: async for audio: ...) hurt performance?', qKn: 'LLM streaming loop ಒಳಗೆ TTS generation ಗೂಡಿಸುವುದೂ (async for token: async for audio: ...) ಏಕೆ ಕಾರ್ಯಕ್ಷಮತೆ ಹಾನಿ ಮಾಡುತ್ತದೆ?',
        opts: ['It uses too much disk space', 'It blocks the LLM from producing its next token until the current token has finished being spoken, preventing the two stages from overlapping', 'It causes a syntax error in Python', 'It has no performance impact at all'], correct: 1,
        optsKn: ['ಇದೂ ಬಹಳ ಹೆಚ್ಚಿನ ಡಿಸ್ಕ್ ಸ್ಥಳ ಬಳಸುತ್ತದೆ', 'ಪ್ರಸ್ತುತದೂ ಮಾತನಾಡುವುದೂ ಮುಗಿಯುವವರೆಗೆ ಇದೂ LLM ಅನ್ನೂ ಇದರ ಮುಂದಿನ token ಉತ್ಪಾದಿಸುವುದರಿಂದ ಬ್ಲಾಕ್ ಮಾಡುತ್ತದೆ, ಎರಡು ಹಂತಗಳನ್ನೂ ಅತಿಕ್ರಮಿಸುವುದರಿಂದ ತಡೆಯುತ್ತಾ', 'ಇದೂ Python ನಲ್ಲಿ ಒಂದು syntax error ಉಂಟುಮಾಡುತ್ತದೆ', 'ಇದಕ್ಕೆ ಯಾವುದೇ ಕಾರ್ಯಕ್ಷಮತೆ ಪರಿಣಾಮ ಇಲ್ಲ'] },
    ] } },
  ],
};
