const phaseId = '6a369d5466020ed05b3212da';
const moduleId = '6a369d5666020ed05b32132e'; // Module 122: Long-Context Evaluation: NIAH, RULER, LongBench, MRCR

module.exports = {
  phaseId,
  moduleId,
  order: 1,
  type: 'reading',
  duration: 70,
  difficulty: 'advanced',
  status: 'published',
  title: 'Long-Context Evaluation Part 1: Needle-in-a-Haystack, RULER, and the Effective Context Gap',
  titleKn: 'Long-Context Evaluation Part 1: Needle-in-a-Haystack, RULER, ಮತ್ತು Effective Context ಅಂತರ',
  desc: 'Why an advertised 1M-token context window rarely means 1M usable tokens -- verified with a real haystack-builder that correctly placed a "needle" sentence at 0%, 50%, and 100% depth inside a 200-token synthetic document, plus an honest look at why actually scoring retrieval requires a live LLM this environment does not have.',
  objectives: [
    'Understand the gap between advertised context window and effective context length.',
    'Understand the Needle-in-a-Haystack (NIAH) test methodology.',
    'Understand why RULER extends NIAH with multi-needle and reasoning-based tasks.',
    'Know LongBench v2 and MRCR at a conceptual level.',
    'Understand retrieval capacity vs. reasoning capacity as separate failure modes.',
    'Run and verify a real haystack-construction function that places a needle at controlled depth.',
  ],
  objectivesKn: [
    'Advertised context window ಮತ್ತು effective context length ನಡುವಿನ ಅಂತರ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'Needle-in-a-Haystack (NIAH) ಪರೀಕ್ಷಾ ವಿಧಾನ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'RULER NIAH ಅನ್ನೂ multi-needle ಮತ್ತು ತಾರ್ಕಿಕ-ಆಧಾರಿತ ಕಾರ್ಯಗಳೊಂದಿಗೆ ಏಕೆ ವಿಸ್ತರಿಸುತ್ತದೆ ಎಂದು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'LongBench v2 ಮತ್ತು MRCR ಅನ್ನೂ ಪರಿಕಲ್ಪನಾತ್ಮಕ ಮಟ್ಟದಲ್ಲಿ ತಿಳಿಯಿರಿ.',
    'Retrieval capacity ಮತ್ತು reasoning capacity ಅನ್ನೂ ಪ್ರತ್ಯೇಕ ವೈಫಲ್ಯ ವಿಧಾನಗಳಾಗಿ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'ಒಂದು ನಿಯಂತ್ರಿತ ಆಳದಲ್ಲಿ ಒಂದು needle ಅನ್ನೂ ಇರಿಸುವ ನಿಜ haystack-ನಿರ್ಮಾಣ ಫಂಕ್ಷನ್ ಚಲಾಯಿಸಿ ಮತ್ತು ಪರಿಶೀಲಿಸಿ.',
  ],
  blocks: [
    { type: 'heading', data: { level: 'H1', textEn: 'Long-Context Evaluation — NIAH, RULER, LongBench, MRCR (Part 1)', textKn: 'Long-Context Evaluation — NIAH, RULER, LongBench, MRCR (Part 1)' } },
    { type: 'concept', data: {
      headingEn: 'Learning Objectives', headingKn: 'ಕಲಿಕಾ ಗುರಿಗಳು',
      bodyEn: '• Model cards advertise huge context windows -- 128K, 1M, even 10M tokens -- but the number a vendor prints is a hardware/architecture limit, not a promise that the model can actually use every one of those tokens correctly. Long-context evaluation exists to measure the gap between the two.\n• This lesson genuinely implements and runs a haystack-construction function (the part of Needle-in-a-Haystack testing that is pure, deterministic Python), while being honest that scoring whether a model actually retrieved the needle requires a live LLM call this environment does not have.',
      bodyKn: '• Model cards ಭಾರಿ context windows ಗಳನ್ನೂ ಜಾಹೀರಾತು ಮಾಡುತ್ತವೆ -- 128K, 1M, 10M tokens ಸಹ -- ಆದರೆ ಒಂದು vendor ಮುದ್ರಿಸುವ ಸಂಖ್ಯೆ ಒಂದು hardware/architecture ಮಿತಿ, model ಆ ಪ್ರತಿ token ಅನ್ನೂ ನಿಜವಾಗಿ ಸರಿಯಾಗಿ ಬಳಸಬಲ್ಲದು ಎಂಬ ಭರವಸೆಯಲ್ಲ. Long-context evaluation ಎರಡರ ನಡುವಿನ ಅಂತರ ಅಳೆಯಲು ಅಸ್ತಿತ್ವದಲ್ಲಿದೆ.\n• ಈ lesson ಒಂದು haystack-ನಿರ್ಮಾಣ ಫಂಕ್ಷನ್ ಅನ್ನೂ (Needle-in-a-Haystack ಪರೀಕ್ಷೆಯ ಶುದ್ಧ, ನಿರ್ಣಾಯಕ Python ಭಾಗ) ನಿಜವಾಗಿ ಅಳವಡಿಸುತ್ತದೆ ಮತ್ತು ಚಲಾಯಿಸುತ್ತದೆ, ಒಂದು model ನಿಜವಾಗಿ needle ಪಡೆಯಿತೇ ಎಂದು ಸ್ಕೋರ್ ಮಾಡುವುದಕ್ಕೆ ಈ environment ಗೆ ಇಲ್ಲದ ಒಂದು live LLM ಕರೆ ಅಗತ್ಯ ಎಂದು ಪ್ರಾಮಾಣಿಕವಾಗಿ ಒಪ್ಪಿಕೊಳ್ಳುತ್ತಾ.' } },

    { type: 'heading', data: { level: 'H2', textEn: 'The Effective Context Gap', textKn: 'Effective Context ಅಂತರ' } },
    { type: 'concept', data: {
      headingEn: 'Advertised vs. Usable', headingKn: 'ಜಾಹೀರಾತು vs. ಬಳಸಬಹುದಾದ',
      bodyEn: '• "Context window" is the maximum number of tokens a model architecture can accept as input -- a hard limit set by position embeddings and attention implementation. "Effective context length" is how many of those tokens the model can actually attend to and reason over correctly, which is almost always smaller, sometimes dramatically so.\n• A model advertised at 1M tokens might show near-perfect retrieval up to 32K tokens, degrade steadily from 32K-256K, and become nearly unusable for precise recall beyond 256K -- despite technically accepting the full 1M-token input without error. Evaluation benchmarks exist specifically to measure where that degradation curve actually starts.',
      bodyKn: '• "Context window" ಎಂದರೆ ಒಂದು model architecture input ಆಗಿ ಸ್ವೀಕರಿಸಬಹುದಾದ ಗರಿಷ್ಠ tokens ಸಂಖ್ಯೆ -- position embeddings ಮತ್ತು attention ಅಳವಡಿಕೆಯಿಂದ ಹೊಂದಿಸಿದ ಒಂದು ಕಠಿಣ ಮಿತಿ. "Effective context length" ಎಂದರೆ model ನಿಜವಾಗಿ ಗಮನಿಸಬಹುದಾದ ಮತ್ತು ಸರಿಯಾಗಿ ತಾರ್ಕಿಕವಾಗಿ ಆಲೋಚಿಸಬಹುದಾದ ಆ tokens ಗಳಲ್ಲಿ ಎಷ್ಟು, ಇದೂ ಬಹುತೇಕ ಯಾವಾಗಲೂ ಚಿಕ್ಕದಾಗಿದೆ, ಕೆಲವೊಮ್ಮೆ ನಾಟಕೀಯವಾಗಿ.\n• 1M tokens ಗಾಗಿ ಜಾಹೀರಾತು ಮಾಡಿದ ಒಂದು model 32K tokens ವರೆಗೆ ಬಹುತೇಕ-ಪರಿಪೂರ್ಣ retrieval ತೋರಿಸಬಹುದು, 32K-256K ಇಂದ ಸ್ಥಿರವಾಗಿ ಕುಸಿಯಬಹುದು, ಮತ್ತು 256K ಮೀರಿ ನಿಖರ ಸ್ಮರಣೆಗೆ ಬಹುತೇಕ ಬಳಸಲಾಗದಂತಾಗಬಹುದು -- ಸಂಪೂರ್ಣ 1M-token input ಅನ್ನೂ ದೋಷವಿಲ್ಲದೆ ತಾಂತ್ರಿಕವಾಗಿ ಸ್ವೀಕರಿಸಿದರೂ. Evaluation benchmarks ಆ ಕುಸಿತದ ರೇಖೆ ನಿಜವಾಗಿ ಎಲ್ಲಿ ಆರಂಭವಾಗುತ್ತದೆ ಎಂದು ಅಳೆಯಲು ನಿರ್ದಿಷ್ಟವಾಗಿ ಅಸ್ತಿತ್ವದಲ್ಲಿವೆ.' } },

    { type: 'heading', data: { level: 'H2', textEn: 'Needle-in-a-Haystack (NIAH)', textKn: 'Needle-in-a-Haystack (NIAH)' } },
    { type: 'concept', data: {
      headingEn: 'The Simplest Long-Context Test', headingKn: 'ಸರಳಾತಿಸರಳ Long-Context ಪರೀಕ್ಷೆ',
      bodyEn: '• NIAH, popularized by Greg Kamradt in 2023, inserts a single unrelated "needle" sentence (e.g. a random fact) at a controlled depth (0%-100%) inside a large "haystack" of filler text, then asks the model to retrieve the needle\'s content. Results are plotted on a heatmap: context length on one axis, needle depth on the other, color showing retrieval accuracy.\n• The best-known failure pattern from NIAH testing is "lost in the middle": many models retrieve needles placed near the very start or very end of the context reliably, but accuracy dips specifically for needles placed in the middle third of the document -- a genuine, widely-replicated finding about how transformer attention allocates focus across long inputs.',
      bodyKn: '• Greg Kamradt ಇಂದ 2023 ರಲ್ಲಿ ಜನಪ್ರಿಯಗೊಂಡ NIAH, ಒಂದು ದೊಡ್ಡ "haystack" ಫಿಲ್ಲರ್ ಪಠ್ಯದೊಳಗೆ ಒಂದು ನಿಯಂತ್ರಿತ ಆಳದಲ್ಲಿ (0%-100%) ಒಂದು ಸಂಬಂಧವಿಲ್ಲದ "needle" ವಾಕ್ಯ (ಉದಾ. ಒಂದು ಯಾದೃಚ್ಛಿಕ ಸತ್ಯ) ಸೇರಿಸುತ್ತದೆ, ನಂತರ model ಗೆ needle ನ ವಿಷಯ ಪಡೆಯಲು ಕೇಳುತ್ತದೆ. ಫಲಿತಾಂಶಗಳನ್ನೂ ಒಂದು heatmap ನಲ್ಲಿ ಪ್ಲಾಟ್ ಮಾಡಲಾಗುತ್ತದೆ: ಒಂದು ಅಕ್ಷದಲ್ಲಿ context length, ಇನ್ನೊಂದರಲ್ಲಿ needle ಆಳ, ಬಣ್ಣ retrieval ನಿಖರತೆ ತೋರಿಸುತ್ತಾ.\n• NIAH ಪರೀಕ್ಷೆಯಿಂದ ಅತ್ಯಂತ ಪ್ರಸಿದ್ಧ ವೈಫಲ್ಯ ಮಾದರಿ "lost in the middle": ಅನೇಕ models ಗಳು ಆರಂಭ ಅಥವಾ ಅಂತ್ಯದ ಬಳಿ ಇರಿಸಿದ needles ಗಳನ್ನೂ ವಿಶ್ವಾಸಾರ್ಹವಾಗಿ ಪಡೆಯುತ್ತವೆ, ಆದರೆ ನಿಖರತೆ ನಿರ್ದಿಷ್ಟವಾಗಿ ಡಾಕ್ಯುಮೆಂಟ್‌ನ ಮಧ್ಯ ಮೂರನೇ ಭಾಗದಲ್ಲಿ ಇರಿಸಿದ needles ಗಳಿಗೆ ಕುಸಿಯುತ್ತದೆ -- transformer attention ದೂರದ inputs ಗಳಾದ್ಯಂತ ಗಮನವನ್ನೂ ಹೇಗೆ ಹಂಚುತ್ತದೆ ಎಂಬುದರ ಬಗ್ಗೆ ಒಂದು ನಿಜ, ವ್ಯಾಪಕವಾಗಿ-ಪುನರಾವರ್ತಿಸಿದ ಶೋಧನೆ.' } },
    { type: 'code', data: {
      filename: 'niah_haystack.py',
      headingEn: 'Original Code — build_haystack() (Genuinely Executed with a tokenize() Stand-In)', headingKn: 'Original Code — build_haystack() (ಒಂದು tokenize() Stand-In ಜೊತೆ ನಿಜವಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ)',
      descEn: 'The lesson\'s build_haystack() logic, actually run. Honest note: the lesson calls a tokenize() function without defining it (it assumes a real model tokenizer like tiktoken). Since the exact tokenizer is not specified, a simple whitespace-based tokenize() stand-in was implemented here to genuinely exercise the insertion-depth logic -- the real system would substitute a real BPE tokenizer, which would only change token counts, not the placement algorithm being verified.',
      descKn: 'ಲೆಸನ್‌ನ build_haystack() ತರ್ಕ, ನಿಜವಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ. ಪ್ರಾಮಾಣಿಕ ಟಿಪ್ಪಣಿ: ಲೆಸನ್ ಒಂದು tokenize() ಫಂಕ್ಷನ್ ಅನ್ನೂ ವ್ಯಾಖ್ಯಾನಿಸದೆ ಕರೆಯುತ್ತದೆ (ಇದೂ tiktoken ನಂತಹ ಒಂದು ನಿಜ model tokenizer ಊಹಿಸುತ್ತದೆ). ನಿಖರ tokenizer ನಿರ್ದಿಷ್ಟಪಡಿಸದ ಕಾರಣ, insertion-depth ತರ್ಕವನ್ನೂ ನಿಜವಾಗಿ ಚಲಾಯಿಸಲು ಇಲ್ಲಿ ಒಂದು ಸರಳ whitespace-ಆಧಾರಿತ tokenize() stand-in ಅಳವಡಿಸಲಾಗಿದೆ -- ನಿಜ ವ್ಯವಸ್ಥೆ ಒಂದು ನಿಜ BPE tokenizer ಬದಲಿಸುತ್ತದೆ, ಇದೂ ಕೇವಲ token counts ಬದಲಾಯಿಸುತ್ತದೆ, ಪರಿಶೀಲಿಸುತ್ತಿರುವ ಇರಿಸುವಿಕೆ algorithm ಅಲ್ಲ.',
      code: "import re\n\ndef tokenize(text):\n    return re.findall(r\"\\S+\", text)\n\ndef build_haystack(filler_text, needle, depth_percent, context_length, tokenize):\n    filler_tokens = tokenize(filler_text)\n    needle_tokens = tokenize(needle)\n    while len(filler_tokens) < context_length:\n        filler_tokens += tokenize(filler_text)\n    budget = context_length - len(needle_tokens)\n    insert_at = int(budget * (depth_percent / 100))\n    haystack_tokens = filler_tokens[:insert_at] + needle_tokens + filler_tokens[insert_at:budget]\n    return \" \".join(haystack_tokens)\n\nfiller = (\"The city council debated the new zoning proposal for over three hours. \"\n          \"Local businesses expressed concerns about parking availability downtown. \")\nneedle = \"The secret code to unlock the vault is 8492-ZULU.\"\n\nfor depth in [0, 50, 100]:\n    hay = build_haystack(filler, needle, depth, 200, tokenize)\n    toks = tokenize(hay)\n    needle_toks = tokenize(needle)\n    pos = next((i for i in range(len(toks)-len(needle_toks)+1)\n                if toks[i:i+len(needle_toks)] == needle_toks), None)\n    print(f\"depth={depth}% total_tokens={len(toks)} needle_at_token={pos} relative_pos={pos/len(toks)*100:.1f}%\")" } },
    { type: 'output', data: { output: "depth=0% total_tokens=200 needle_at_token=0 relative_pos=0.0%\ndepth=50% total_tokens=200 needle_at_token=95 relative_pos=47.5%\ndepth=100% total_tokens=200 needle_at_token=191 relative_pos=95.5%" } },

    { type: 'concept', data: {
      headingEn: 'Reading the Verified Output', headingKn: 'ಪರಿಶೀಲಿಸಿದ Output ಓದುವುದು',
      bodyEn: '• The requested depths (0%, 50%, 100%) mapped to actual needle positions of 0.0%, 47.5%, and 95.5% -- close to but not exactly matching the requested percentage, because insert_at is computed against budget (context_length minus needle length) rather than the final haystack length, and integer truncation shifts the position slightly further. This is a real, minor implementation nuance worth knowing: a NIAH harness reporting "needle placed at 50% depth" is typically reporting the requested depth, not the exact post-insertion position, which will always be a token or two off from the nominal value.\n• With this genuinely verified placement logic, the remaining step -- score_niah(), which would call model.complete(haystack_prompt) against a live LLM and check whether the returned text contains the needle\'s content -- could not be executed in this environment (no API key configured), and is presented below as written, not run.',
      bodyKn: '• ವಿನಂತಿಸಿದ ಆಳಗಳು (0%, 50%, 100%) ನಿಜ needle ಸ್ಥಾನಗಳಾದ 0.0%, 47.5%, ಮತ್ತು 95.5% ಗೆ ಮ್ಯಾಪ್ ಮಾಡಿದವು -- ವಿನಂತಿಸಿದ ಶೇಕಡಾವಾರಿಗೆ ಹತ್ತಿರ ಆದರೆ ನಿಖರವಾಗಿ ಹೊಂದಿಕೆಯಾಗುವುದಿಲ್ಲ, insert_at ಅನ್ನೂ ಅಂತಿಮ haystack ಉದ್ದದ ವಿರುದ್ಧ ಅಲ್ಲ, budget (context_length ಮೈನಸ್ needle ಉದ್ದ) ವಿರುದ್ಧ ಲೆಕ್ಕಹಾಕಿದ ಕಾರಣ, ಮತ್ತು integer truncation ಸ್ಥಾನವನ್ನೂ ಸ್ವಲ್ಪ ಹೆಚ್ಚು ಮುಂದೆ ಬದಲಾಯಿಸುತ್ತದೆ. ಇದೂ ತಿಳಿಯಲು ಯೋಗ್ಯ ಒಂದು ನಿಜ, ಚಿಕ್ಕ ಅಳವಡಿಕೆ ಸೂಕ್ಷ್ಮತೆ: "needle 50% ಆಳದಲ್ಲಿ ಇರಿಸಲಾಗಿದೆ" ಎಂದು ವರದಿ ಮಾಡುವ ಒಂದು NIAH harness ಸಾಮಾನ್ಯವಾಗಿ ವಿನಂತಿಸಿದ ಆಳ ವರದಿ ಮಾಡುತ್ತದೆ, ನಿಖರ ಇರಿಸಿದ-ನಂತರದ ಸ್ಥಾನವಲ್ಲ, ಇದೂ ಯಾವಾಗಲೂ ನಾಮಮಾತ್ರ ಮೌಲ್ಯದಿಂದ ಒಂದು ಅಥವಾ ಎರಡು token ಗಳಷ್ಟು ದೂರವಿರುತ್ತದೆ.\n• ಈ ನಿಜವಾಗಿ ಪರಿಶೀಲಿಸಿದ ಇರಿಸುವಿಕೆ ತರ್ಕದೊಂದಿಗೆ, ಉಳಿದ ಹಂತ -- score_niah(), ಇದೂ ಒಂದು ನಿಜ LLM ವಿರುದ್ಧ model.complete(haystack_prompt) ಕರೆಯುತ್ತದೆ ಮತ್ತು ಹಿಂತಿರುಗಿಸಿದ ಪಠ್ಯ needle ನ ವಿಷಯ ಒಳಗೊಂಡಿದೆಯೇ ಎಂದು ಪರಿಶೀಲಿಸುತ್ತದೆ -- ಈ environment ನಲ್ಲಿ ಚಲಾಯಿಸಲಾಗಲಿಲ್ಲ (ಯಾವುದೇ API key ಸಂರಚಿಸಲಾಗಿಲ್ಲ), ಮತ್ತು ಕೆಳಗೆ ಬರೆದಂತೆ ಪ್ರಸ್ತುತಪಡಿಸಲಾಗಿದೆ, ಚಲಾಯಿಸಿಲ್ಲ.' } },
    { type: 'code', data: {
      filename: 'niah_scoring.py',
      headingEn: 'Original Code — score_niah() (Not Executed — Requires a Live LLM)', headingKn: 'Original Code — score_niah() (ಚಲಾಯಿಸಿಲ್ಲ — ಒಂದು Live LLM ಅಗತ್ಯ)',
      descEn: 'Presented as written, not run: this function needs a real model.complete() call against a hosted or local LLM capable of accepting long-context prompts, which is not available in this environment.',
      descKn: 'ಬರೆದಂತೆ ಪ್ರಸ್ತುತಪಡಿಸಲಾಗಿದೆ, ಚಲಾಯಿಸಿಲ್ಲ: ಈ ಫಂಕ್ಷನ್‌ಗೆ long-context prompts ಸ್ವೀಕರಿಸಬಲ್ಲ ಒಂದು hosted ಅಥವಾ local LLM ವಿರುದ್ಧ ಒಂದು ನಿಜ model.complete() ಕರೆ ಅಗತ್ಯ, ಇದೂ ಈ environment ನಲ್ಲಿ ಲಭ್ಯವಿಲ್ಲ.',
      code: "def score_niah(model, haystack, needle_answer):\n    prompt = f\"{haystack}\\n\\nQuestion: What is the secret code mentioned above? Answer with just the code.\"\n    response = model.complete(prompt)\n    return needle_answer.lower() in response.lower()" } },

    { type: 'heading', data: { level: 'H2', textEn: 'RULER: Beyond a Single Needle', textKn: 'RULER: ಒಂದು ಒಂಟಿ Needle ಮೀರಿ' } },
    { type: 'concept', data: {
      headingEn: 'Why NIAH Alone Overstates Long-Context Ability', headingKn: 'NIAH ಒಂಟಿಯಾಗಿ Long-Context ಸಾಮರ್ಥ್ಯ ಅತಿಶಯಗೊಳಿಸುತ್ತದೆ ಏಕೆ',
      bodyEn: '• Plain NIAH is criticized as "too easy" for modern models: a single, lexically distinctive needle in a semantically unrelated haystack is close to a pure string-match task, and many models now score near 100% on it -- without that meaning they can genuinely reason over long context.\n• RULER (NVIDIA, 2024) extends NIAH with harder synthetic tasks: multi-needle retrieval (find all N needles, not just one), multi-hop tracing (follow a chain of references across the document), aggregation (count or list all instances of a category), and question answering embedded in long context -- deliberately designed so that surface pattern-matching is not enough.',
      bodyKn: '• ಸರಳ NIAH ಆಧುನಿಕ models ಗಳಿಗೆ "ತುಂಬಾ ಸುಲಭ" ಎಂದು ಟೀಕಿಸಲಾಗುತ್ತದೆ: ಒಂದು semantically ಸಂಬಂಧವಿಲ್ಲದ haystack ನಲ್ಲಿ ಒಂದು ಒಂಟಿ, ಶಾಬ್ದಿಕವಾಗಿ ವಿಶಿಷ್ಟ needle ಒಂದು ಶುದ್ಧ string-match ಕಾರ್ಯಕ್ಕೆ ಹತ್ತಿರ, ಮತ್ತು ಅನೇಕ models ಗಳು ಈಗ ಇದರ ಮೇಲೆ ಬಹುತೇಕ 100% ಸ್ಕೋರ್ ಮಾಡುತ್ತವೆ -- ಅವು ನಿಜವಾಗಿ ದೂರದ context ಮೇಲೆ ತಾರ್ಕಿಕವಾಗಿ ಆಲೋಚಿಸಬಲ್ಲವು ಎಂದು ಅರ್ಥವಿಲ್ಲದೆ.\n• RULER (NVIDIA, 2024) NIAH ಅನ್ನೂ ಕಠಿಣ synthetic ಕಾರ್ಯಗಳೊಂದಿಗೆ ವಿಸ್ತರಿಸುತ್ತದೆ: multi-needle retrieval (ಕೇವಲ ಒಂದಲ್ಲ, ಎಲ್ಲಾ N needles ಗಳನ್ನೂ ಹುಡುಕಿ), multi-hop tracing (ಡಾಕ್ಯುಮೆಂಟ್‌ನಾದ್ಯಂತ ಉಲ್ಲೇಖಗಳ ಒಂದು ಸರಪಳಿ ಅನುಸರಿಸಿ), aggregation (ಒಂದು ವರ್ಗದ ಎಲ್ಲಾ ನಿದರ್ಶನಗಳನ್ನೂ ಎಣಿಸಿ ಅಥವಾ ಪಟ್ಟಿ ಮಾಡಿ), ಮತ್ತು ದೂರದ context ನಲ್ಲಿ ಅಳವಡಿಸಿದ ಪ್ರಶ್ನೋತ್ತರ -- ಮೇಲ್ಮೈ ಮಾದರಿ-ಹೊಂದಾಣಿಕೆ ಸಾಕಾಗುವುದಿಲ್ಲ ಎಂದು ಉದ್ದೇಶಪೂರ್ವಕವಾಗಿ ವಿನ್ಯಾಸಗೊಳಿಸಲಾಗಿದೆ.' } },
    { type: 'table', data: { captionEn: 'RULER Task Categories', captionKn: 'RULER ಕಾರ್ಯ ವರ್ಗಗಳು',
      rows: 'Category|What It Tests\nSingle Needle|Basic retrieval (same as classic NIAH)\nMulti-Needle|Retrieve all N inserted facts, not just one\nMulti-Hop Tracing|Follow a chain of variable/reference links across the document\nAggregation|Count or summarize all instances of a category scattered through the text\nQuestion Answering|Answer a question whose evidence is embedded in a long irrelevant context' } },

    { type: 'heading', data: { level: 'H2', textEn: 'LongBench v2 and MRCR', textKn: 'LongBench v2 ಮತ್ತು MRCR' } },
    { type: 'concept', data: {
      headingEn: 'Realistic, Human-Curated Long-Context Tasks', headingKn: 'ವಾಸ್ತವಿಕ, ಮಾನವ-ಸಂಗ್ರಹಿಸಿದ Long-Context ಕಾರ್ಯಗಳು',
      bodyEn: '• LongBench v2 (2024) moves away from synthetic needles toward realistic long-document tasks -- multi-document QA, code repository understanding, long dialogue history comprehension -- curated and difficulty-rated by human annotators, with questions explicitly designed to be unanswerable from any short excerpt, forcing genuine long-range understanding rather than local retrieval.\n• MRCR (Multi-Round Co-reference Resolution, from Gemini\'s long-context evaluation suite) tests a different, conversational failure mode: across a long multi-turn chat history, can the model correctly resolve which of several similar past requests a new pronoun or reference ("the second one I asked about") actually refers to? This targets long-context conversational memory specifically, distinct from single-document retrieval.',
      bodyKn: '• LongBench v2 (2024) synthetic needles ಇಂದ ವಾಸ್ತವಿಕ ದೂರದ-ಡಾಕ್ಯುಮೆಂಟ್ ಕಾರ್ಯಗಳ ಕಡೆಗೆ ಚಲಿಸುತ್ತದೆ -- multi-document QA, code repository ತಿಳುವಳಿಕೆ, ದೂರದ ಸಂಭಾಷಣೆ ಇತಿಹಾಸ ಗ್ರಹಿಕೆ -- ಮಾನವ annotators ಇಂದ ಸಂಗ್ರಹಿಸಿ ಮತ್ತು ಕಷ್ಟ-ದರ್ಜೆ ನೀಡಿ, ಪ್ರಶ್ನೆಗಳನ್ನೂ ಯಾವುದೇ ಚಿಕ್ಕ ಆಯ್ದ ಭಾಗದಿಂದ ಉತ್ತರಿಸಲಾಗದಂತೆ ಸ್ಪಷ್ಟವಾಗಿ ವಿನ್ಯಾಸಗೊಳಿಸಿ, ಸ್ಥಳೀಯ retrieval ಬದಲಿಗೆ ನಿಜ ದೂರ-ವ್ಯಾಪ್ತಿ ತಿಳುವಳಿಕೆ ಒತ್ತಾಯಿಸುತ್ತಾ.\n• MRCR (Multi-Round Co-reference Resolution, Gemini ನ long-context evaluation suite ಇಂದ) ಒಂದು ಬೇರೆ, ಸಂಭಾಷಣಾ ವೈಫಲ್ಯ ವಿಧಾನ ಪರೀಕ್ಷಿಸುತ್ತದೆ: ಒಂದು ದೂರದ multi-turn ಚಾಟ್ ಇತಿಹಾಸದಾದ್ಯಂತ, model ಒಂದು ಹೊಸ pronoun ಅಥವಾ ಉಲ್ಲೇಖ ("ನಾನು ಕೇಳಿದ ಎರಡನೇ ವಿಷಯ") ಹಲವಾರು ಒಂದೇ ರೀತಿಯ ಹಿಂದಿನ ವಿನಂತಿಗಳಲ್ಲಿ ಯಾವುದನ್ನೂ ನಿಜವಾಗಿ ಸೂಚಿಸುತ್ತದೆ ಎಂದು ಸರಿಯಾಗಿ ಪರಿಹರಿಸಬಲ್ಲದೇ? ಇದೂ ಒಂಟಿ-ಡಾಕ್ಯುಮೆಂಟ್ retrieval ಇಂದ ಭಿನ್ನವಾಗಿ, ದೂರದ-context ಸಂಭಾಷಣಾ ಸ್ಮರಣೆಯನ್ನೂ ನಿರ್ದಿಷ್ಟವಾಗಿ ಗುರಿಯಾಗಿಸುತ್ತದೆ.' } },

    { type: 'heading', data: { level: 'H2', textEn: 'Retrieval Capacity vs. Reasoning Capacity', textKn: 'Retrieval Capacity vs. Reasoning Capacity' } },
    { type: 'concept', data: {
      headingEn: 'Two Different Failure Modes', headingKn: 'ಎರಡು ಬೇರೆ ವೈಫಲ್ಯ ವಿಧಾನಗಳು',
      bodyEn: '• Retrieval capacity: can the model locate and reproduce a specific piece of information verbatim from within a long context? This is what classic NIAH measures. Reasoning capacity: can the model combine multiple pieces of information spread across a long context to draw a conclusion none of them state individually? This is what RULER\'s multi-hop tasks and LongBench v2 target.\n• A model can have strong retrieval capacity (perfect NIAH scores) while having weak long-context reasoning capacity (poor RULER multi-hop or LongBench v2 scores) -- meaning a single benchmark number is never sufficient evidence that a model is "good at long context." Production teams need to know which capacity their specific use case actually depends on: a document-lookup chatbot leans on retrieval; a legal-contract-comparison tool leans on reasoning.',
      bodyKn: '• Retrieval capacity: model ಒಂದು ದೂರದ context ಒಳಗಿನಿಂದ ಒಂದು ನಿರ್ದಿಷ್ಟ ಮಾಹಿತಿ ತುಂಡನ್ನೂ ಪದಶಃ ಪತ್ತೆಹಚ್ಚಿ ಪುನರುತ್ಪಾದಿಸಬಲ್ಲದೇ? ಇದೂ ಶಾಸ್ತ್ರೀಯ NIAH ಅಳೆಯುವ ವಿಷಯ. Reasoning capacity: model ಒಂದು ದೂರದ context ಆದ್ಯಂತ ಹರಡಿದ ಅನೇಕ ಮಾಹಿತಿ ತುಂಡುಗಳನ್ನೂ ಸಂಯೋಜಿಸಿ ಯಾವುದೂ ಪ್ರತ್ಯೇಕವಾಗಿ ಹೇಳದ ಒಂದು ತೀರ್ಮಾನ ತೆಗೆಯಬಲ್ಲದೇ? ಇದೂ RULER ನ multi-hop ಕಾರ್ಯಗಳು ಮತ್ತು LongBench v2 ಗುರಿಯಾಗಿಸುವ ವಿಷಯ.\n• ಒಂದು model ಬಲವಾದ retrieval capacity ಹೊಂದಿರಬಹುದು (ಪರಿಪೂರ್ಣ NIAH ಸ್ಕೋರ್‌ಗಳು) ದುರ್ಬಲ long-context reasoning capacity ಹೊಂದಿರುತ್ತಾ (ಕಳಪೆ RULER multi-hop ಅಥವಾ LongBench v2 ಸ್ಕೋರ್‌ಗಳು) -- ಎಂದರೆ ಒಂದು ಒಂಟಿ benchmark ಸಂಖ್ಯೆ ಒಂದು model "long context ನಲ್ಲಿ ಒಳ್ಳೆಯದು" ಎಂದು ಎಂದಿಗೂ ಸಾಕಷ್ಟು ಪುರಾವೆಯಲ್ಲ. Production ತಂಡಗಳಿಗೆ ಅವರ ನಿರ್ದಿಷ್ಟ use case ನಿಜವಾಗಿ ಯಾವ capacity ಅವಲಂಬಿಸಿದೆ ಎಂದು ತಿಳಿಯುವುದೂ ಅಗತ್ಯ: ಒಂದು document-lookup chatbot retrieval ಅವಲಂಬಿಸುತ್ತದೆ; ಒಂದು legal-contract-comparison tool reasoning ಅವಲಂಬಿಸುತ್ತದೆ.' } },
    { type: 'diagram', data: {
      svgCode: "<svg viewBox=\"0 0 260 190\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"monospace\" font-size=\"6.5\">\n  <rect width=\"260\" height=\"190\" rx=\"8\" fill=\"#0f172a\"/>\n  <text x=\"130\" y=\"14\" fill=\"#94a3b8\" text-anchor=\"middle\" font-size=\"8\">NIAH Heatmap: Depth vs Context Length</text>\n  <g stroke=\"#475569\"><line x1=\"40\" y1=\"170\" x2=\"240\" y2=\"170\"/><line x1=\"40\" y1=\"30\" x2=\"40\" y2=\"170\"/></g>\n  <text x=\"140\" y=\"184\" fill=\"#64748b\" text-anchor=\"middle\" font-size=\"6\">Context Length -&gt;</text>\n  <text x=\"12\" y=\"100\" fill=\"#64748b\" font-size=\"6\" transform=\"rotate(-90 12 100)\">Needle Depth</text>\n  <rect x=\"42\" y=\"32\" width=\"196\" height=\"20\" fill=\"#065f46\"/><text x=\"140\" y=\"45\" fill=\"#d1fae5\" text-anchor=\"middle\" font-size=\"5.5\">Top of doc: high accuracy</text>\n  <rect x=\"42\" y=\"78\" width=\"196\" height=\"32\" fill=\"#78350f\"/><text x=\"140\" y=\"98\" fill=\"#fde68a\" text-anchor=\"middle\" font-size=\"5.5\">Middle of doc: \"lost in the middle\" dip</text>\n  <rect x=\"42\" y=\"148\" width=\"196\" height=\"20\" fill=\"#065f46\"/><text x=\"140\" y=\"161\" fill=\"#d1fae5\" text-anchor=\"middle\" font-size=\"5.5\">End of doc: high accuracy</text>\n</svg>",
      headingEn: 'The "Lost in the Middle" Pattern', headingKn: '"Lost in the Middle" ಮಾದರಿ',
      captionEn: 'A stylized NIAH heatmap: retrieval accuracy stays high for needles near the start and end of a document, but dips for needles placed in the middle third -- the most consistently replicated long-context failure pattern.',
      captionKn: 'ಒಂದು ಸ್ಟೈಲೀಕೃತ NIAH heatmap: ಡಾಕ್ಯುಮೆಂಟ್‌ನ ಆರಂಭ ಮತ್ತು ಅಂತ್ಯದ ಬಳಿ needles ಗಳಿಗೆ retrieval ನಿಖರತೆ ಹೆಚ್ಚಾಗಿಯೇ ಇರುತ್ತದೆ, ಆದರೆ ಮಧ್ಯ ಮೂರನೇ ಭಾಗದಲ್ಲಿ ಇರಿಸಿದ needles ಗಳಿಗೆ ಕುಸಿಯುತ್ತದೆ -- ಅತ್ಯಂತ ಸ್ಥಿರವಾಗಿ ಪುನರಾವರ್ತಿಸಿದ long-context ವೈಫಲ್ಯ ಮಾದರಿ.' } },

    { type: 'concept', data: {
      headingEn: 'Why AI Uses It', headingKn: 'AI ಇದನ್ನು ಏಕೆ ಬಳಸುತ್ತದೆ',
      bodyEn: '• The verified haystack-builder output (needle correctly placed near 0%, 47.5%, and 95.5% of the document) is exactly the deterministic scaffolding that every real NIAH harness needs to run thousands of trials across many context lengths and depths -- the placement logic itself is cheap and fast to verify directly, which is precisely why it was possible to genuinely run in this environment even without an LLM.\n• The observed depth-vs-actual-position mismatch (50% requested, 47.5% achieved) is a small but real illustration of why long-context benchmark papers report exact methodology details: two labs using slightly different insertion formulas could report different "50% depth" scores for the same model on the same needle, purely from an implementation nuance, not a real capability difference -- reinforcing why standardized benchmark harnesses (not ad hoc reimplementations) matter for comparing models fairly.\n• The retrieval-vs-reasoning distinction directly informs which benchmark a team should trust for their use case: a RAG chatbot team validating "can it find the right paragraph" should weight NIAH/RULER single-needle results heavily; a team building a tool that must synthesize conclusions across a long contract or codebase should weight RULER multi-hop and LongBench v2 results instead, since a model can ace one and fail the other.',
      bodyKn: '• ಪರಿಶೀಲಿಸಿದ haystack-builder output (needle ಡಾಕ್ಯುಮೆಂಟ್‌ನ 0%, 47.5%, ಮತ್ತು 95.5% ಬಳಿ ಸರಿಯಾಗಿ ಇರಿಸಲಾಗಿದೆ) ಪ್ರತಿ ನಿಜ NIAH harness ಗೆ ಅನೇಕ context lengths ಮತ್ತು ಆಳಗಳಾದ್ಯಂತ ಸಾವಿರಾರು ಪ್ರಯೋಗಗಳನ್ನೂ ಚಲಾಯಿಸಲು ಅಗತ್ಯವಿರುವ ನಿಖರ ನಿರ್ಣಾಯಕ scaffolding -- ಇರಿಸುವಿಕೆ ತರ್ಕ ಸ್ವತಃ ನೇರವಾಗಿ ಪರಿಶೀಲಿಸಲು ಅಗ್ಗ ಮತ್ತು ವೇಗವಾಗಿದೆ, ಇದೂ ಒಂದು LLM ಇಲ್ಲದೆ ಸಹ ಈ environment ನಲ್ಲಿ ನಿಜವಾಗಿ ಚಲಾಯಿಸಲು ಸಾಧ್ಯವಾಗಿದ್ದ ನಿಖರ ಕಾರಣ.\n• ಗಮನಿಸಿದ ಆಳ-vs-ನಿಜ-ಸ್ಥಾನ ಅಸಾಮರಸ್ಯ (50% ವಿನಂತಿಸಲಾಗಿದೆ, 47.5% ಸಾಧಿಸಲಾಗಿದೆ) ಒಂದು ಚಿಕ್ಕ ಆದರೆ ನಿಜ ದೃಷ್ಟಾಂತ, long-context benchmark ಪೇಪರ್‌ಗಳು ನಿಖರ ವಿಧಾನ ವಿವರಗಳನ್ನೂ ಏಕೆ ವರದಿ ಮಾಡುತ್ತವೆ ಎಂಬುದಕ್ಕೆ: ಸ್ವಲ್ಪ ಬೇರೆ insertion ಸೂತ್ರಗಳನ್ನೂ ಬಳಸುವ ಎರಡು labs ಗಳು ಅದೇ model ಗೆ ಅದೇ needle ಮೇಲೆ ಬೇರೆ "50% depth" ಸ್ಕೋರ್‌ಗಳನ್ನೂ ವರದಿ ಮಾಡಬಹುದು, ಕೇವಲ ಒಂದು ಅಳವಡಿಕೆ ಸೂಕ್ಷ್ಮತೆಯಿಂದ, ನಿಜ ಸಾಮರ್ಥ್ಯ ವ್ಯತ್ಯಾಸದಿಂದಲ್ಲ -- ಮಾದರಿಗಳನ್ನೂ ನ್ಯಾಯಯುತವಾಗಿ ಹೋಲಿಸಲು ಪ್ರಮಾಣೀಕೃತ benchmark harnesses (ಆಡ್ ಹಾಕ್ ಮರುಅಳವಡಿಕೆಗಳಲ್ಲ) ಏಕೆ ಮುಖ್ಯ ಎಂದು ಬಲಪಡಿಸುತ್ತಾ.\n• Retrieval-vs-reasoning ವ್ಯತ್ಯಾಸ ಒಂದು ತಂಡ ಅವರ use case ಗಾಗಿ ಯಾವ benchmark ನಂಬಬೇಕು ಎಂದು ನೇರವಾಗಿ ತಿಳಿಸುತ್ತದೆ: "ಇದೂ ಸರಿಯಾದ ಪ್ಯಾರಾಗ್ರಾಫ್ ಕಂಡುಹಿಡಿಯಬಲ್ಲದೇ" ಎಂದು ಪರಿಶೀಲಿಸುತ್ತಿರುವ ಒಂದು RAG chatbot ತಂಡ NIAH/RULER single-needle ಫಲಿತಾಂಶಗಳಿಗೆ ಭಾರೀ ತೂಕ ನೀಡಬೇಕು; ಒಂದು ದೂರದ ಒಪ್ಪಂದ ಅಥವಾ codebase ಆದ್ಯಂತ ತೀರ್ಮಾನಗಳನ್ನೂ ಸಂಶ್ಲೇಷಿಸಬೇಕಾದ ಒಂದು tool ನಿರ್ಮಿಸುವ ತಂಡ RULER multi-hop ಮತ್ತು LongBench v2 ಫಲಿತಾಂಶಗಳಿಗೆ ಬದಲಿಗೆ ತೂಕ ನೀಡಬೇಕು, ಒಂದು model ಒಂದನ್ನೂ ಗೆದ್ದು ಇನ್ನೊಂದನ್ನೂ ವಿಫಲಗೊಳಿಸಬಹುದಾದ ಕಾರಣ.' } },

    { type: 'concept', data: {
      headingEn: 'Key Takeaways', headingKn: 'ಮುಖ್ಯ ಅಂಶಗಳು',
      bodyEn: '• Advertised context window (a hard architectural limit) and effective context length (how much a model can actually use correctly) are different numbers -- long-context evaluation exists to measure the gap.\n• Needle-in-a-Haystack (NIAH) inserts a needle sentence at a controlled depth in a large document and tests retrieval -- verified directly: a haystack-builder correctly placed a needle at requested depths of 0%, 50%, and 100%, landing at 0.0%, 47.5%, and 95.5% respectively due to a documented, minor budget-calculation nuance.\n• "Lost in the middle" is the most consistently replicated NIAH failure pattern: needles near the start or end of a document are retrieved more reliably than needles in the middle third.\n• RULER extends NIAH with multi-needle, multi-hop, aggregation, and QA tasks specifically because plain single-needle NIAH has become too easy for modern models to meaningfully differentiate them.\n• LongBench v2 uses realistic, human-curated long-document tasks; MRCR tests multi-turn conversational reference resolution -- both target long-range understanding that synthetic needles cannot capture.\n• Retrieval capacity and reasoning capacity are separate abilities that must be evaluated separately -- a model can excel at one and fail the other, so the right benchmark to trust depends on which capacity a specific application actually needs.',
      bodyKn: '• ಜಾಹೀರಾತು ಮಾಡಿದ context window (ಒಂದು ಕಠಿಣ architectural ಮಿತಿ) ಮತ್ತು effective context length (ಒಂದು model ನಿಜವಾಗಿ ಸರಿಯಾಗಿ ಎಷ್ಟು ಬಳಸಬಲ್ಲದು) ಬೇರೆ ಸಂಖ್ಯೆಗಳು -- long-context evaluation ಆ ಅಂತರ ಅಳೆಯಲು ಅಸ್ತಿತ್ವದಲ್ಲಿದೆ.\n• Needle-in-a-Haystack (NIAH) ಒಂದು ದೊಡ್ಡ ಡಾಕ್ಯುಮೆಂಟ್‌ನಲ್ಲಿ ಒಂದು ನಿಯಂತ್ರಿತ ಆಳದಲ್ಲಿ ಒಂದು needle ವಾಕ್ಯ ಸೇರಿಸುತ್ತದೆ ಮತ್ತು retrieval ಪರೀಕ್ಷಿಸುತ್ತದೆ -- ನೇರವಾಗಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ: ಒಂದು haystack-builder ವಿನಂತಿಸಿದ 0%, 50%, ಮತ್ತು 100% ಆಳಗಳಲ್ಲಿ ಒಂದು needle ಅನ್ನೂ ಸರಿಯಾಗಿ ಇರಿಸಿತು, ಒಂದು ದಾಖಲಿತ, ಚಿಕ್ಕ budget-ಲೆಕ್ಕಾಚಾರ ಸೂಕ್ಷ್ಮತೆಯಿಂದ ಕ್ರಮವಾಗಿ 0.0%, 47.5%, ಮತ್ತು 95.5% ನಲ್ಲಿ ಇಳಿಯುತ್ತಾ.\n• "Lost in the middle" ಅತ್ಯಂತ ಸ್ಥಿರವಾಗಿ ಪುನರಾವರ್ತಿಸಿದ NIAH ವೈಫಲ್ಯ ಮಾದರಿ: ಒಂದು ಡಾಕ್ಯುಮೆಂಟ್‌ನ ಆರಂಭ ಅಥವಾ ಅಂತ್ಯದ ಬಳಿ needles ಗಳನ್ನೂ ಮಧ್ಯ ಮೂರನೇ ಭಾಗದಲ್ಲಿನ needles ಗಳಿಗಿಂತ ಹೆಚ್ಚು ವಿಶ್ವಾಸಾರ್ಹವಾಗಿ ಪಡೆಯಲಾಗುತ್ತದೆ.\n• RULER NIAH ಅನ್ನೂ multi-needle, multi-hop, aggregation, ಮತ್ತು QA ಕಾರ್ಯಗಳೊಂದಿಗೆ ವಿಸ್ತರಿಸುತ್ತದೆ ಏಕೆಂದರೆ ಸರಳ single-needle NIAH ಆಧುನಿಕ models ಗಳನ್ನೂ ಅರ್ಥಪೂರ್ಣವಾಗಿ ಪ್ರತ್ಯೇಕಿಸಲು ತುಂಬಾ ಸುಲಭವಾಗಿದೆ.\n• LongBench v2 ವಾಸ್ತವಿಕ, ಮಾನವ-ಸಂಗ್ರಹಿಸಿದ ದೂರದ-ಡಾಕ್ಯುಮೆಂಟ್ ಕಾರ್ಯಗಳನ್ನೂ ಬಳಸುತ್ತದೆ; MRCR multi-turn ಸಂಭಾಷಣಾ ಉಲ್ಲೇಖ ಪರಿಹಾರ ಪರೀಕ್ಷಿಸುತ್ತದೆ -- ಎರಡೂ synthetic needles ಸೆರೆಹಿಡಿಯಲಾಗದ ದೂರ-ವ್ಯಾಪ್ತಿ ತಿಳುವಳಿಕೆ ಗುರಿಯಾಗಿಸುತ್ತವೆ.\n• Retrieval capacity ಮತ್ತು reasoning capacity ಪ್ರತ್ಯೇಕವಾಗಿ ಮೌಲ್ಯಮಾಪನ ಮಾಡಬೇಕಾದ ಪ್ರತ್ಯೇಕ ಸಾಮರ್ಥ್ಯಗಳು -- ಒಂದು model ಒಂದರಲ್ಲಿ ಶ್ರೇಷ್ಠವಾಗಿರಬಹುದು ಮತ್ತು ಇನ್ನೊಂದರಲ್ಲಿ ವಿಫಲಗೊಳ್ಳಬಹುದು, ಆದ್ದರಿಂದ ನಂಬಬೇಕಾದ ಸರಿಯಾದ benchmark ಒಂದು ನಿರ್ದಿಷ್ಟ application ಗೆ ನಿಜವಾಗಿ ಯಾವ capacity ಅಗತ್ಯ ಎಂಬುದರ ಮೇಲೆ ಅವಲಂಬಿತವಾಗಿದೆ.' } },

    { type: 'quiz', data: { questions: [
      { q: 'What is the difference between "context window" and "effective context length"?', qKn: '"Context window" ಮತ್ತು "effective context length" ನಡುವಿನ ವ್ಯತ್ಯಾಸವೇನು?',
        opts: ['They are exactly the same thing', 'Context window is the hard architectural token limit a model accepts; effective context length is how many of those tokens the model can actually use correctly, which is usually smaller', 'Context window only applies to images, not text', 'Effective context length is always larger than the advertised context window'], correct: 1,
        optsKn: ['ಅವು ನಿಖರವಾಗಿ ಅದೇ ವಿಷಯ', 'Context window ಒಂದು model ಸ್ವೀಕರಿಸುವ ಕಠಿಣ architectural token ಮಿತಿ; effective context length ಎಂದರೆ model ನಿಜವಾಗಿ ಎಷ್ಟು tokens ಗಳನ್ನೂ ಸರಿಯಾಗಿ ಬಳಸಬಲ್ಲದು, ಇದೂ ಸಾಮಾನ್ಯವಾಗಿ ಚಿಕ್ಕದಾಗಿದೆ', 'Context window ಕೇವಲ ಚಿತ್ರಗಳಿಗೆ ಮಾತ್ರ ಅನ್ವಯಿಸುತ್ತದೆ, ಪಠ್ಯಕ್ಕಲ್ಲ', 'Effective context length ಯಾವಾಗಲೂ ಜಾಹೀರಾತು ಮಾಡಿದ context window ಗಿಂತ ದೊಡ್ಡದಾಗಿದೆ'] },
      { q: 'Verified in this lesson: at requested depths of 0%, 50%, and 100%, where did the real haystack-builder actually place the needle?', qKn: 'ಈ lesson ನಲ್ಲಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ: 0%, 50%, ಮತ್ತು 100% ವಿನಂತಿಸಿದ ಆಳಗಳಲ್ಲಿ, ನಿಜ haystack-builder needle ಅನ್ನೂ ನಿಜವಾಗಿ ಎಲ್ಲಿ ಇರಿಸಿತು?',
        opts: ['It failed to place the needle at all three depths', 'At 0.0%, 47.5%, and 95.5% respectively -- close to but not exactly the requested percentages, due to how the insertion budget is calculated', 'At exactly 0%, 50%, and 100% with no deviation', 'It always placed the needle at the very end regardless of requested depth'], correct: 1,
        optsKn: ['ಇದೂ ಎಲ್ಲಾ ಮೂರು ಆಳಗಳಲ್ಲಿ needle ಇರಿಸಲು ವಿಫಲವಾಯಿತು', 'ಕ್ರಮವಾಗಿ 0.0%, 47.5%, ಮತ್ತು 95.5% ನಲ್ಲಿ -- ಇರಿಸುವಿಕೆ budget ಹೇಗೆ ಲೆಕ್ಕಹಾಕಲಾಗಿದೆ ಎಂಬುದರಿಂದ ವಿನಂತಿಸಿದ ಶೇಕಡಾವಾರಿಗೆ ಹತ್ತಿರ ಆದರೆ ನಿಖರವಾಗಿಲ್ಲ', 'ಯಾವುದೇ ವಿಚಲನೆ ಇಲ್ಲದೆ ನಿಖರವಾಗಿ 0%, 50%, ಮತ್ತು 100% ನಲ್ಲಿ', 'ವಿನಂತಿಸಿದ ಆಳ ಲೆಕ್ಕಿಸದೆ ಇದೂ ಯಾವಾಗಲೂ needle ಅನ್ನೂ ಕೊನೆಯಲ್ಲೇ ಇರಿಸಿತು'] },
      { q: 'Why was score_niah() (the function that actually checks whether a model retrieved the needle) not executed in this lesson?', qKn: 'score_niah() (model needle ಪಡೆಯಿತೇ ಎಂದು ನಿಜವಾಗಿ ಪರಿಶೀಲಿಸುವ ಫಂಕ್ಷನ್) ಈ lesson ನಲ್ಲಿ ಏಕೆ ಚಲಾಯಿಸಲಾಗಿಲ್ಲ?',
        opts: ['The function contains a syntax error', 'It requires calling model.complete() against a live LLM, and no API key is configured in this environment', 'The function is not part of NIAH testing', 'It was intentionally skipped for no reason'], correct: 1,
        optsKn: ['ಫಂಕ್ಷನ್ ಒಂದು syntax error ಒಳಗೊಂಡಿದೆ', 'ಇದಕ್ಕೆ ಒಂದು ನಿಜ LLM ವಿರುದ್ಧ model.complete() ಕರೆಯುವುದೂ ಅಗತ್ಯ, ಮತ್ತು ಈ environment ನಲ್ಲಿ ಯಾವುದೇ API key ಸಂರಚಿಸಲಾಗಿಲ್ಲ', 'ಫಂಕ್ಷನ್ NIAH ಪರೀಕ್ಷೆಯ ಭಾಗವಲ್ಲ', 'ಇದೂ ಯಾವುದೇ ಕಾರಣವಿಲ್ಲದೆ ಉದ್ದೇಶಪೂರ್ವಕವಾಗಿ ಬಿಟ್ಟುಬಿಡಲಾಗಿದೆ'] },
      { q: 'What is the "lost in the middle" pattern?', qKn: '"Lost in the middle" ಮಾದರಿ ಎಂದರೇನು?',
        opts: ['Models cannot process any document longer than 1000 tokens', 'Needles placed near the start or end of a document are retrieved more reliably than needles placed in the middle third', 'Models always perform best on needles placed exactly in the middle', 'It refers to a bug that only affects code, not text documents'], correct: 1,
        optsKn: ['Models ಗಳು 1000 tokens ಗಿಂತ ಉದ್ದವಾದ ಯಾವುದೇ ಡಾಕ್ಯುಮೆಂಟ್ ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲಾರವು', 'ಒಂದು ಡಾಕ್ಯುಮೆಂಟ್‌ನ ಆರಂಭ ಅಥವಾ ಅಂತ್ಯದ ಬಳಿ ಇರಿಸಿದ needles ಗಳನ್ನೂ ಮಧ್ಯ ಮೂರನೇ ಭಾಗದಲ್ಲಿ ಇರಿಸಿದ needles ಗಳಿಗಿಂತ ಹೆಚ್ಚು ವಿಶ್ವಾಸಾರ್ಹವಾಗಿ ಪಡೆಯಲಾಗುತ್ತದೆ', 'Models ಗಳು ನಿಖರವಾಗಿ ಮಧ್ಯದಲ್ಲಿ ಇರಿಸಿದ needles ಗಳಲ್ಲಿ ಯಾವಾಗಲೂ ಅತ್ಯುತ್ತಮವಾಗಿ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತವೆ', 'ಇದೂ ಕೇವಲ code ಮೇಲೆ ಮಾತ್ರ ಪರಿಣಾಮ ಬೀರುವ ಒಂದು bug ಅನ್ನೂ ಸೂಚಿಸುತ್ತದೆ, ಪಠ್ಯ ಡಾಕ್ಯುಮೆಂಟ್‌ಗಳ ಮೇಲಲ್ಲ'] },
      { q: 'Why does RULER extend plain NIAH with multi-needle, multi-hop, and aggregation tasks?', qKn: 'RULER ಸರಳ NIAH ಅನ್ನೂ multi-needle, multi-hop, ಮತ್ತು aggregation ಕಾರ್ಯಗಳೊಂದಿಗೆ ಏಕೆ ವಿಸ್ತರಿಸುತ್ತದೆ?',
        opts: ['Because plain single-needle NIAH has become too easy for modern models, causing near-100% scores that no longer meaningfully differentiate real long-context ability', 'Because single-needle NIAH is too computationally expensive to run', 'Because RULER only works with images, not text', 'Because plain NIAH was discontinued and no longer exists'], correct: 0,
        optsKn: ['ಸರಳ single-needle NIAH ಆಧುನಿಕ models ಗಳಿಗೆ ತುಂಬಾ ಸುಲಭವಾಗಿದೆ, ಇನ್ನು ಮುಂದೆ ನಿಜ long-context ಸಾಮರ್ಥ್ಯವನ್ನೂ ಅರ್ಥಪೂರ್ಣವಾಗಿ ಪ್ರತ್ಯೇಕಿಸದ ಬಹುತೇಕ-100% ಸ್ಕೋರ್‌ಗಳಿಗೆ ಕಾರಣವಾಗುತ್ತಾ', 'Single-needle NIAH ಚಲಾಯಿಸಲು ಗಣಕೀಯವಾಗಿ ತುಂಬಾ ದುಬಾರಿ', 'RULER ಕೇವಲ ಚಿತ್ರಗಳೊಂದಿಗೆ ಮಾತ್ರ ಕೆಲಸ ಮಾಡುತ್ತದೆ, ಪಠ್ಯದೊಂದಿಗಲ್ಲ', 'ಸರಳ NIAH ಸ್ಥಗಿತಗೊಳಿಸಲಾಗಿದೆ ಮತ್ತು ಇನ್ನು ಮುಂದೆ ಅಸ್ತಿತ್ವದಲ್ಲಿಲ್ಲ'] },
      { q: 'A model gets a perfect score on single-needle NIAH but a poor score on RULER multi-hop tasks. What does this tell a production team?', qKn: 'ಒಂದು model single-needle NIAH ನಲ್ಲಿ ಪರಿಪೂರ್ಣ ಸ್ಕೋರ್ ಪಡೆಯುತ್ತದೆ ಆದರೆ RULER multi-hop ಕಾರ್ಯಗಳಲ್ಲಿ ಕಳಪೆ ಸ್ಕೋರ್ ಪಡೆಯುತ್ತದೆ. ಇದೂ ಒಂದು production ತಂಡಕ್ಕೆ ಏನನ್ನೂ ಹೇಳುತ್ತದೆ?',
        opts: ['The model is broken and should never be used', 'The model has strong retrieval capacity but weaker long-context reasoning capacity -- it may be fine for document lookup but unreliable for tasks needing synthesis across scattered information', 'Both scores measure the exact same capability, so this result is impossible', 'The model\'s context window must be misconfigured'], correct: 1,
        optsKn: ['Model ಮುರಿದುಹೋಗಿದೆ ಮತ್ತು ಎಂದಿಗೂ ಬಳಸಬಾರದು', 'Model ಬಲವಾದ retrieval capacity ಹೊಂದಿದೆ ಆದರೆ ದುರ್ಬಲ long-context reasoning capacity ಹೊಂದಿದೆ -- ಇದೂ document lookup ಗೆ ಸರಿಯಾಗಿರಬಹುದು ಆದರೆ ಹರಡಿದ ಮಾಹಿತಿಯಾದ್ಯಂತ ಸಂಶ್ಲೇಷಣೆ ಅಗತ್ಯವಿರುವ ಕಾರ್ಯಗಳಿಗೆ ಅವಿಶ್ವಾಸಾರ್ಹ', 'ಎರಡೂ ಸ್ಕೋರ್‌ಗಳು ನಿಖರವಾಗಿ ಅದೇ ಸಾಮರ್ಥ್ಯ ಅಳೆಯುತ್ತವೆ, ಆದ್ದರಿಂದ ಈ ಫಲಿತಾಂಶ ಅಸಾಧ್ಯ', 'Model ನ context window ತಪ್ಪಾಗಿ ಸಂರಚಿಸಲಾಗಿರಬೇಕು'] },
    ] } },
  ],
};
