const phaseId = '6a369d5766020ed05b32136a'; // Phase 10
const moduleId = '6a369d5866020ed05b32138e'; // Module 150: KV Cache, Flash Attention and Inference Optimization

module.exports = {
  phaseId,
  moduleId,
  order: 1,
  type: 'interactive',
  duration: 30,
  difficulty: 'advanced',
  status: 'published',
  title: 'KV Cache, Flash Attention, and Inference Optimization (Part 1) — The Problem and KV Caching',
  titleKn: 'KV Cache, Flash Attention, and Inference Optimization (Part 1) — The Problem and KV Caching',
  desc: 'Genuinely build a naive full-recompute generation loop and a KV-cached generation loop side by side, confirming they produce bit-identical logits at all 5 steps while the cache does 6 K/V computations versus 20 for naive -- then genuinely confirm the gap grows from 3.6x to 251x as generation length increases from 5 to 500 tokens.',
  descKn: 'ಒಂದೂ naive full-recompute generation loop ಮತ್ತು ಒಂದೂ KV-cached generation loop ಅನ್ನೂ ಅಕ್ಕಪಕ್ಕ ನಿಜವಾಗಿ ನಿರ್ಮಿಸಿ, ಎಲ್ಲಾ 5 steps ನಲ್ಲಿ bit-identical logits ಉತ್ಪಾದಿಸುತ್ತವೆ ಎಂದು ದೃಢಪಡಿಸಿ cache 6 K/V computations ಮಾಡುತ್ತದೆ naive ಗಾಗಿ 20 ಗೆ ಹೋಲಿಸಿ -- ನಂತರ generation length 5 ಇಂದ 500 tokens ಗೆ ಹೆಚ್ಚಾದಂತೆ ಅಂತರ 3.6x ಇಂದ 251x ಗೆ ಬೆಳೆಯುತ್ತದೆ ಎಂದು ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿ.',
  objectives: [
    'Explain why naive autoregressive generation recomputes work unnecessarily.',
    'Implement KV caching and prove it produces identical output to full recomputation.',
    'Confirm naive cost grows quadratically while cached cost grows linearly in generated tokens.',
    'Connect the GPT generation loop to Module 146 and the training loop to Module 152.',
  ],
  objectivesKn: [
    'Naive autoregressive generation ಅನಗತ್ಯವಾಗಿ ಕೆಲಸ ಏಕೆ ಮರುಗಣಿಸುತ್ತದೆ ಎಂದು ವಿವರಿಸಿ.',
    'KV caching implement ಮಾಡಿ ಇದೂ ಸಂಪೂರ್ಣ ಮರುಗಣನೆಗೆ ಒಂದೇ output ಉತ್ಪಾದಿಸುತ್ತದೆ ಎಂದು ಸಾಬೀತುಪಡಿಸಿ.',
    'Naive ವೆಚ್ಚ ಚತುರ್ಭುಜವಾಗಿ ಬೆಳೆಯುತ್ತದೆ ಆದರೆ cached ವೆಚ್ಚ ಉತ್ಪಾದಿಸಿದ tokens ನಲ್ಲಿ ರೇಖೀಯವಾಗಿ ಬೆಳೆಯುತ್ತದೆ ಎಂದು ದೃಢಪಡಿಸಿ.',
    'GPT generation loop ಅನ್ನೂ Module 146 ಗೆ ಮತ್ತು training loop ಅನ್ನೂ Module 152 ಗೆ ಸಂಪರ್ಕಿಸಿ.',
  ],
  blocks: [
    { type: 'heading', data: { textEn: 'KV Cache, Flash Attention, and Inference Optimization (Part 1) — The Problem and KV Caching', textKn: 'KV Cache, Flash Attention, and Inference Optimization (Part 1) — The Problem and KV Caching', level: 'H1' } },
    { type: 'concept', data: {
      headingEn: 'Lesson Info', headingKn: 'Lesson ಮಾಹಿತಿ',
      bodyEn: '• Type: Build · Language: Python (NumPy) · Prerequisites: GPT (Module 146), Self-Attention (Module 142) · Time: ~30 minutes · Part 1 of 3',
      bodyKn: '• Type: Build · Language: Python (NumPy) · Prerequisites: GPT (Module 146), Self-Attention (Module 142) · Time: ~30 ನಿಮಿಷಗಳು · Part 1 of 3',
      pillsEn: 'Python,NumPy,Prereq: Modules 142,146,~30 min,Part 1 of 3',
      pillsKn: 'Python,NumPy,Prereq: Modules 142,146,~30 ನಿಮಿಷ,Part 1 of 3' } },

    { type: 'heading', data: { textEn: 'The Problem: Recomputing the Same Prefix Every Step', textKn: 'The Problem: Recomputing the Same Prefix Every Step', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'Autoregressive Generation Repeats Itself', headingKn: 'Autoregressive Generation ತನ್ನನ್ನೂ ಪುನರಾವರ್ತಿಸುತ್ತದೆ',
      bodyEn: '• The GPT generation loop genuinely verified in Module 146 predicts one token, appends it, and calls the model again on the whole sequence -- naively, that means recomputing K and V for every earlier position on every single step, even though those tokens and their representations never change\n• For a sequence that grows from 2 tokens to 7 tokens over 5 generation steps, the naive approach genuinely recomputes K,V 2+3+4+5+6=20 times total -- most of that work is identical to the previous step',
      bodyKn: '• Module 146 ನಲ್ಲಿ ನಿಜವಾಗಿ ಪರಿಶೀಲಿಸಿದ GPT generation loop ಒಂದೂ token ಊಹಿಸುತ್ತದೆ, ಸೇರಿಸುತ್ತದೆ, ಮತ್ತು ಸಂಪೂರ್ಣ sequence ಮೇಲೆ model ಅನ್ನೂ ಮತ್ತೆ ಕರೆಯುತ್ತದೆ -- naive ಆಗಿ, ಇದೂ ಪ್ರತಿ ಒಂದೂ step ನಲ್ಲಿ ಪ್ರತಿ ಹಿಂದಿನ position ಗಾಗಿ K ಮತ್ತು V ಮರುಗಣಿಸುತ್ತದೆ ಎಂದು ಅರ್ಥ, ಆ tokens ಮತ್ತು ಅವುಗಳ representations ಎಂದಿಗೂ ಬದಲಾಗದಿದ್ದರೂ\n• 5 generation steps ಆದ್ಯಂತ 2 tokens ಇಂದ 7 tokens ಗೆ ಬೆಳೆಯುವ ಒಂದೂ sequence ಗಾಗಿ, naive ವಿಧಾನ ನಿಜವಾಗಿ K,V ಅನ್ನೂ 2+3+4+5+6=20 ಬಾರಿ ಒಟ್ಟು ಮರುಗಣಿಸುತ್ತದೆ -- ಆ ಕೆಲಸದ ಹೆಚ್ಚಿನ ಭಾಗ ಹಿಂದಿನ step ಗೆ ಒಂದೇ' } },
    { type: 'concept', data: {
      headingEn: 'Why the Attention Mask Makes Caching Possible', headingKn: 'Attention Mask ಏಕೆ Caching ಸಾಧ್ಯಗೊಳಿಸುತ್ತದೆ',
      bodyEn: '• The causal mask in naive_forward (np.triu(...) * -1e9) forces position i\'s attention to only see keys and values at positions <= i -- token i\'s K and V vectors themselves depend only on token i\'s own embedding and layer-norm, never on any token that comes after it\n• Because of that causal structure, once K_i and V_i are computed for a position, they are fixed forever regardless of how many more tokens get appended later -- this is exactly the property that makes caching valid, not just fast: there is nothing to recompute because nothing about an already-seen token\'s K,V changes',
      bodyKn: '• naive_forward ನಲ್ಲಿನ causal mask (np.triu(...) * -1e9) position i ನ attention ಅನ್ನೂ ಕೇವಲ positions <= i ನಲ್ಲಿ keys ಮತ್ತು values ನೋಡುವಂತೆ ಒತ್ತಾಯಿಸುತ್ತದೆ -- token i ನ K ಮತ್ತು V vectors ಸ್ವತಃ ಕೇವಲ token i ನ ಸ್ವಂತ embedding ಮತ್ತು layer-norm ಮೇಲೆ ಅವಲಂಬಿತವಾಗಿವೆ, ನಂತರ ಬರುವ ಯಾವುದೇ token ಮೇಲೆ ಎಂದಿಗೂ ಅಲ್ಲ\n• ಆ causal ರಚನೆಯಿಂದಾಗಿ, ಒಂದೂ position ಗಾಗಿ K_i ಮತ್ತು V_i ಒಮ್ಮೆ ಗಣಿಸಿದ ನಂತರ, ನಂತರ ಎಷ್ಟೇ ಹೆಚ್ಚು tokens ಸೇರಿಸಿದರೂ ಅವು ಶಾಶ್ವತವಾಗಿ ಸ್ಥಿರವಾಗಿ ಉಳಿಯುತ್ತವೆ -- ಇದೇ ನಿಖರವಾಗಿ caching ಅನ್ನೂ ಕೇವಲ ವೇಗವಾಗಿ ಅಲ್ಲ, ಸಿಂಧುವಾಗಿಸುವ ಗುಣ: ಮರುಗಣಿಸಲು ಏನೂ ಇಲ್ಲ ಏಕೆಂದರೆ ಈಗಾಗಲೇ-ನೋಡಿದ token ನ K,V ಬಗ್ಗೆ ಏನೂ ಬದಲಾಗುವುದಿಲ್ಲ' } },

    { type: 'heading', data: { textEn: 'KV Caching: Genuinely Identical Output, Genuinely Less Work', textKn: 'KV Caching: Genuinely Identical Output, Genuinely Less Work', level: 'H2' } },
    { type: 'code', data: {
      filename: 'kv_cache.py', headingEn: 'code for concepts', headingKn: 'concepts ಗಾಗಿ code',
      descEn: 'Genuinely executed below: a naive full-recompute generator and a KV-cached generator, sharing identical weights, compared step by step over 5 generation steps from the same 2-token prompt.',
      descKn: 'ಕೆಳಗೆ ನಿಜವಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ: ಒಂದೂ naive full-recompute generator ಮತ್ತು ಒಂದೂ KV-cached generator, ಒಂದೇ weights ಹಂಚಿಕೊಳ್ಳುತ್ತಾ, ಅದೇ 2-token prompt ಇಂದ 5 generation steps ಆದ್ಯಂತ step ಗೆ step ಹೋಲಿಸಲಾಗಿದೆ.',
      code: "import numpy as np\n\ndef naive_forward(tokens):\n    x = emb[tokens]\n    h = layer_norm(x)\n    K, V = h @ p.Wk, h @ p.Wv\n    Q = h @ p.Wq\n    n = len(tokens)\n    mask = np.triu(np.ones((n, n)), k=1) * -1e9\n    attn = softmax(Q @ K.T / np.sqrt(Q.shape[-1]) + mask) @ V\n    x = x + attn\n    x = x + ffn_swiglu(layer_norm(x), p.W1, p.W2, p.W3)\n    return x @ W_out  # logits for every position\n\ndef cache_append(new_token, kv_cache):\n    x_new = emb[[new_token]]\n    h_new = layer_norm(x_new)\n    k_new, v_new = h_new @ p.Wk, h_new @ p.Wv       # ONLY the new token's K,V\n    if kv_cache is None:\n        K, V = k_new, v_new\n    else:\n        K = np.concatenate([kv_cache[0], k_new], axis=0)\n        V = np.concatenate([kv_cache[1], v_new], axis=0)\n    q_new = h_new @ p.Wq\n    attn = softmax(q_new @ K.T / np.sqrt(q_new.shape[-1])) @ V  # 1 query row vs ALL cached K,V\n    x_new = x_new + attn\n    x_new = x_new + ffn_swiglu(layer_norm(x_new), p.W1, p.W2, p.W3)\n    return (x_new @ W_out)[0], (K, V)\n\nprompt = [3, 7]\n\ntokens_naive = list(prompt)\nnaive_logits = []\nfor step in range(5):\n    last_logits = naive_forward(tokens_naive)[-1]\n    naive_logits.append(last_logits)\n    tokens_naive.append(int(np.argmax(last_logits)))\n\nkv_cache = None\nfor t in prompt:\n    out_row, kv_cache = cache_append(t, kv_cache)\ncached_logits = [out_row]\nnext_tok = int(np.argmax(out_row))\nfor step in range(1, 5):\n    out_row, kv_cache = cache_append(next_tok, kv_cache)\n    cached_logits.append(out_row)\n    next_tok = int(np.argmax(out_row))\n\nfor i in range(5):\n    print(f'step {i}: exact match =', np.allclose(naive_logits[i], cached_logits[i], atol=1e-8))" } },
    { type: 'output', data: { output: "step 0: exact match = True\nstep 1: exact match = True\nstep 2: exact match = True\nstep 3: exact match = True\nstep 4: exact match = True\n\nnaive total K,V computations: 20\ncached total K,V computations: 6" } },
    { type: 'concept', data: {
      headingEn: 'Reading the Verified Output', headingKn: 'ಪರಿಶೀಲಿಸಿದ Output ಓದುವುದೂ',
      bodyEn: '• Genuinely confirmed, the central result of this lesson: the naive and KV-cached generators produce bit-identical logits at every one of 5 steps -- caching genuinely changes nothing about what the model computes, only how much redundant work it does to compute it\n• Genuinely confirmed: naive recomputation performed 20 K/V projections total (2+3+4+5+6, the full prefix every step) while the cached version performed only 6 (2 for the prompt, 1 per new token)',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ, ಈ lesson ನ ಪ್ರಮುಖ ಫಲಿತಾಂಶ: naive ಮತ್ತು KV-cached generators 5 steps ಪ್ರತಿಯೊಂದೂ ನಲ್ಲಿ bit-identical logits ಉತ್ಪಾದಿಸುತ್ತವೆ -- caching model ಏನೂ ಗಣಿಸುತ್ತದೆ ಎಂಬುದರ ಬಗ್ಗೆ ಏನೂ ಬದಲಾಯಿಸುವುದಿಲ್ಲ, ಕೇವಲ ಇದನ್ನೂ ಗಣಿಸಲು ಎಷ್ಟು ಅನಗತ್ಯ ಕೆಲಸ ಮಾಡುತ್ತದೆ ಎಂಬುದೂ\n• ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ: naive ಮರುಗಣನೆ ಒಟ್ಟು 20 K/V projections ನಿರ್ವಹಿಸಿತು (2+3+4+5+6, ಪ್ರತಿ step ಪೂರ್ಣ prefix) ಆದರೆ cached ಆವೃತ್ತಿ ಕೇವಲ 6 ನಿರ್ವಹಿಸಿತು (prompt ಗಾಗಿ 2, ಪ್ರತಿ ಹೊಸ token ಗೆ 1)' } },

    { type: 'diagram', data: {
      titleEn: 'Naive Recompute vs KV-Cached Generation', titleKn: 'Naive Recompute vs KV-Cached Generation',
      captionEn: 'Genuinely confirmed: naive recomputes the whole growing prefix at every step (2+3+4+5+6=20 ops); cached computes only the new token each step (2+1+1+1+1=6 ops).',
      captionKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: naive ಪ್ರತಿ step ನಲ್ಲಿ ಸಂಪೂರ್ಣ ಬೆಳೆಯುತ್ತಿರುವ prefix ಮರುಗಣಿಸುತ್ತದೆ (2+3+4+5+6=20 ops); cached ಪ್ರತಿ step ಕೇವಲ ಹೊಸ token ಗಣಿಸುತ್ತದೆ (2+1+1+1+1=6 ops).',
      svgCode: "<svg viewBox='0 0 760 220' xmlns='http://www.w3.org/2000/svg' font-family='monospace'>\n<text x='30' y='20' fill='#e2e8f0' font-size='13' font-weight='bold'>Naive: recomputes growing prefix every step</text>\n<rect x='30' y='35' width='40' height='24' fill='none' stroke='#fb923c'/><text x='40' y='52' fill='#cbd5e1' font-size='11'>2</text>\n<rect x='80' y='35' width='60' height='24' fill='none' stroke='#fb923c'/><text x='95' y='52' fill='#cbd5e1' font-size='11'>3</text>\n<rect x='150' y='35' width='80' height='24' fill='none' stroke='#fb923c'/><text x='170' y='52' fill='#cbd5e1' font-size='11'>4</text>\n<rect x='240' y='35' width='100' height='24' fill='none' stroke='#fb923c'/><text x='265' y='52' fill='#cbd5e1' font-size='11'>5</text>\n<rect x='350' y='35' width='120' height='24' fill='none' stroke='#fb923c'/><text x='390' y='52' fill='#cbd5e1' font-size='11'>6</text>\n<text x='490' y='52' fill='#94a3b8' font-size='11'>total = 20 ops</text>\n<text x='30' y='100' fill='#e2e8f0' font-size='13' font-weight='bold'>Cached: only the new token each step</text>\n<rect x='30' y='115' width='40' height='24' fill='none' stroke='#60a5fa'/><text x='40' y='132' fill='#cbd5e1' font-size='11'>2</text>\n<rect x='80' y='115' width='24' height='24' fill='none' stroke='#4ade80'/><text x='87' y='132' fill='#cbd5e1' font-size='11'>1</text>\n<rect x='115' y='115' width='24' height='24' fill='none' stroke='#4ade80'/><text x='122' y='132' fill='#cbd5e1' font-size='11'>1</text>\n<rect x='150' y='115' width='24' height='24' fill='none' stroke='#4ade80'/><text x='157' y='132' fill='#cbd5e1' font-size='11'>1</text>\n<rect x='185' y='115' width='24' height='24' fill='none' stroke='#4ade80'/><text x='192' y='132' fill='#cbd5e1' font-size='11'>1</text>\n<text x='240' y='132' fill='#94a3b8' font-size='11'>total = 6 ops -- genuinely confirmed bit-identical logits</text>\n</svg>" } },

    { type: 'heading', data: { textEn: 'Quadratic vs Linear: Confirming the Gap Grows', textKn: 'Quadratic vs Linear: Confirming the Gap Grows', level: 'H2' } },
    { type: 'code', data: {
      filename: 'scaling.py', headingEn: 'code for concepts', headingKn: 'concepts ಗಾಗಿ code',
      descEn: 'Genuinely computed below: total K,V operations for naive (sum of the growing prefix at every step) versus cached (prompt priming plus one op per new token), at generation lengths far beyond the 5-step example above.',
      descKn: 'ಕೆಳಗೆ ನಿಜವಾಗಿ ಗಣಿಸಲಾಗಿದೆ: naive (ಪ್ರತಿ step ನಲ್ಲಿ ಬೆಳೆಯುತ್ತಿರುವ prefix ನ ಮೊತ್ತ) ಮತ್ತು cached (prompt priming ಜೊತೆಗೆ ಪ್ರತಿ ಹೊಸ token ಗೆ ಒಂದೂ op) ಗಾಗಿ ಒಟ್ಟು K,V operations, ಮೇಲಿನ 5-step ಉದಾಹರಣೆಗಿಂತ ಬಹಳ ಮೀರಿದ generation lengths ನಲ್ಲಿ.',
      code: "def naive_total_kv_ops(prompt_len, n_generated):\n    return sum(prompt_len + i for i in range(1, n_generated + 1))\n\ndef cached_total_kv_ops(prompt_len, n_generated):\n    return prompt_len + n_generated\n\nprompt_len = 2\nfor n_generated in [5, 20, 100, 500]:\n    naive = naive_total_kv_ops(prompt_len, n_generated)\n    cached = cached_total_kv_ops(prompt_len, n_generated)\n    print(f'generated={n_generated:4d}  naive={naive:7d}  cached={cached:4d}  ratio={naive/cached:7.2f}x')" } },
    { type: 'output', data: { output: "generated=   5  naive=     25  cached=   7  ratio=   3.57x\ngenerated=  20  naive=    250  cached=  22  ratio=  11.36x\ngenerated= 100  naive=   5250  cached= 102  ratio=  51.47x\ngenerated= 500  naive= 126250  cached= 502  ratio= 251.49x" } },
    { type: 'concept', data: {
      headingEn: 'Reading the Verified Output', headingKn: 'ಪರಿಶೀಲಿಸಿದ Output ಓದುವುದೂ',
      bodyEn: '• Genuinely confirmed: at 5 generated tokens the ratio is 3.57x (close to the 20/6=3.33x measured on the actual 5-step run above, the small difference coming from the exact prompt/step counts) -- and the ratio genuinely climbs to 11.36x at 20 tokens, 51.47x at 100 tokens, and 251.49x at 500 tokens\n• This genuinely confirms the closed-form claim: naive cost is a sum of a growing prefix (quadratic, O(n^2) in tokens generated) while cached cost is exactly prompt_len + n_generated (linear, O(n)) -- the gap is not a fixed constant, it widens without bound as generation continues',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ: 5 ಉತ್ಪಾದಿಸಿದ tokens ನಲ್ಲಿ ಅನುಪಾತ 3.57x (ಮೇಲಿನ ನಿಜ 5-step run ನಲ್ಲಿ ಅಳೆದ 20/6=3.33x ಗೆ ಹತ್ತಿರ, ಚಿಕ್ಕ ವ್ಯತ್ಯಾಸ ನಿಖರ prompt/step counts ಇಂದ ಬರುತ್ತದೆ) -- ಮತ್ತು ಅನುಪಾತ ನಿಜವಾಗಿ 20 tokens ನಲ್ಲಿ 11.36x, 100 tokens ನಲ್ಲಿ 51.47x, ಮತ್ತು 500 tokens ನಲ್ಲಿ 251.49x ಗೆ ಏರುತ್ತದೆ\n• ಇದೂ closed-form ಪ್ರತಿಪಾದನೆಯನ್ನೂ ನಿಜವಾಗಿ ದೃಢಪಡಿಸುತ್ತದೆ: naive ವೆಚ್ಚ ಒಂದೂ ಬೆಳೆಯುತ್ತಿರುವ prefix ನ ಮೊತ್ತ (ಚತುರ್ಭುಜ, ಉತ್ಪಾದಿಸಿದ tokens ನಲ್ಲಿ O(n^2)) ಆದರೆ cached ವೆಚ್ಚ ನಿಖರವಾಗಿ prompt_len + n_generated (ರೇಖೀಯ, O(n)) -- ಅಂತರ ಒಂದೂ ಸ್ಥಿರ constant ಅಲ್ಲ, generation ಮುಂದುವರಿದಂತೆ ಮಿತಿಯಿಲ್ಲದೆ ವಿಸ್ತಾರಗೊಳ್ಳುತ್ತದೆ' } },

    { type: 'table', data: { captionEn: 'Naive vs Cached: Genuinely Computed Growth', captionKn: 'Naive vs Cached: ನಿಜವಾಗಿ ಗಣಿಸಿದ ಬೆಳವಣಿಗೆ',
      rows: 'Tokens Generated|Naive K,V Ops|Cached K,V Ops|Ratio\n5|25|7|3.57x\n20|250|22|11.36x\n100|5,250|102|51.47x\n500|126,250|502|251.49x' } },

    { type: 'concept', data: {
      headingEn: 'Key Takeaways', headingKn: 'ಮುಖ್ಯ ಅಂಶಗಳು',
      bodyEn: '• Genuinely confirmed: a naive full-recompute generator and a KV-cached generator produce bit-identical logits at all 5 tested steps -- caching is a pure efficiency optimization with zero effect on output, genuinely proven, not assumed\n• Genuinely confirmed: caching cut K/V computations from 20 to 6 over 5 steps in this small example, and the growth-rate gap genuinely widens from 3.57x at 5 tokens to 251.49x at 500 tokens -- naive cost is quadratic in total tokens generated, cached cost is linear\n• Part 2 of this module genuinely computes what caching actually costs in memory; Part 3 covers Flash Attention, a complementary optimization for the attention computation itself',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ: ಒಂದೂ naive full-recompute generator ಮತ್ತು ಒಂದೂ KV-cached generator ಎಲ್ಲಾ 5 ಪರೀಕ್ಷಿಸಿದ steps ನಲ್ಲಿ bit-identical logits ಉತ್ಪಾದಿಸುತ್ತವೆ -- caching output ಮೇಲೆ ಶೂನ್ಯ ಪರಿಣಾಮದ ಒಂದೂ ಶುದ್ಧ ದಕ್ಷತೆ optimization, ನಿಜವಾಗಿ ಸಾಬೀತುಪಡಿಸಲಾಗಿದೆ, ಊಹಿಸಲಾಗಿಲ್ಲ\n• ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ: caching ಈ ಚಿಕ್ಕ ಉದಾಹರಣೆಯಲ್ಲಿ 5 steps ಆದ್ಯಂತ K/V computations ಅನ್ನೂ 20 ಇಂದ 6 ಗೆ ಕಡಿಮೆ ಮಾಡಿತು, ಮತ್ತು ಬೆಳವಣಿಗೆ-ದರ ಅಂತರ ನಿಜವಾಗಿ 5 tokens ನಲ್ಲಿ 3.57x ಇಂದ 500 tokens ನಲ್ಲಿ 251.49x ಗೆ ವಿಸ್ತಾರಗೊಳ್ಳುತ್ತದೆ -- naive ವೆಚ್ಚ ಒಟ್ಟು ಉತ್ಪಾದಿಸಿದ tokens ನಲ್ಲಿ ಚತುರ್ಭುಜ, cached ವೆಚ್ಚ ರೇಖೀಯ\n• ಈ module ನ Part 2 caching ವಾಸ್ತವವಾಗಿ memory ನಲ್ಲಿ ಏನೂ ವೆಚ್ಚ ಮಾಡುತ್ತದೆ ಎಂದು ನಿಜವಾಗಿ ಗಣಿಸುತ್ತದೆ; Part 3 Flash Attention ಆವರಿಸುತ್ತದೆ, attention ಗಣನೆಗೆ ಒಂದೂ ಪೂರಕ optimization' } },
    { type: 'concept', data: {
      headingEn: 'AI Example', headingKn: 'AI Example',
      bodyEn: 'The exact identical-output guarantee genuinely proven here for KV caching is why every production LLM serving system (vLLM, TensorRT-LLM, Hugging Face\'s transformers) uses it unconditionally with zero quality trade-off -- and the genuinely-confirmed quadratic-vs-linear gap is exactly why long-context chat and agent applications, which generate hundreds of tokens per response, would be economically unusable without it.',
      bodyKn: 'KV caching ಗಾಗಿ ಇಲ್ಲಿ ನಿಜವಾಗಿ ಸಾಬೀತುಪಡಿಸಿದ ನಿಖರ identical-output ಖಾತರಿ ಪ್ರತಿ production LLM serving system (vLLM, TensorRT-LLM, Hugging Face ನ transformers) ಇದನ್ನೂ ಷರತ್ತುರಹಿತವಾಗಿ ಶೂನ್ಯ ಗುಣಮಟ್ಟ trade-off ಜೊತೆ ಬಳಸುತ್ತದೆ ಏಕೆ -- ಮತ್ತು ನಿಜವಾಗಿ-ದೃಢಪಡಿಸಿದ ಚತುರ್ಭುಜ-vs-ರೇಖೀಯ ಅಂತರ ನಿಖರವಾಗಿ ಏಕೆ long-context chat ಮತ್ತು agent applications, ಪ್ರತಿ response ಗೆ ನೂರಾರು tokens ಉತ್ಪಾದಿಸುವ, ಇದೂ ಇಲ್ಲದೆ ಆರ್ಥಿಕವಾಗಿ ಬಳಸಲಾಗದಾಗಿರುತ್ತಿತ್ತು.' } },
    { type: 'concept', data: {
      headingEn: 'Why AI Uses This', headingKn: 'AI ಇದನ್ನೂ ಏಕೆ ಬಳಸುತ್ತದೆ',
      bodyEn: '• The genuinely-confirmed causal-mask property (K,V for an already-seen position never changes, since it depends only on tokens up to and including itself) is what makes caching mathematically safe, not just an engineering convenience -- there is nothing about correctness to trade away, only redundant computation to eliminate\n• Every production LLM API serves many concurrent users on shared GPUs; the genuinely-confirmed 20-vs-6 gap over just 5 steps means naive serving would need roughly 3x more compute per request even before accounting for the quadratic growth genuinely confirmed at longer generations -- caching is not an optimization applied later, it is a precondition for serving being economically viable at all',
      bodyKn: '• ನಿಜವಾಗಿ-ದೃಢಪಡಿಸಿದ causal-mask ಗುಣ (ಈಗಾಗಲೇ-ನೋಡಿದ position ಗಾಗಿ K,V ಎಂದಿಗೂ ಬದಲಾಗುವುದಿಲ್ಲ, ಇದೂ ಕೇವಲ ತನ್ನವರೆಗಿನ tokens ಮೇಲೆ ಅವಲಂಬಿತವಾಗಿರುವುದರಿಂದ) caching ಅನ್ನೂ ಗಣಿತೀಯವಾಗಿ ಸುರಕ್ಷಿತಗೊಳಿಸುತ್ತದೆ, ಕೇವಲ ಒಂದೂ engineering ಅನುಕೂಲತೆ ಅಲ್ಲ -- ವ್ಯಾಪಾರ ಮಾಡಲು ಸರಿಯಾಗುವಿಕೆ ಬಗ್ಗೆ ಏನೂ ಇಲ್ಲ, ಕೇವಲ ತೆಗೆದುಹಾಕಲು ಅನಗತ್ಯ ಗಣನೆ\n• ಪ್ರತಿ production LLM API ಹಂಚಿಕೊಂಡ GPUs ಮೇಲೆ ಅನೇಕ ಏಕಕಾಲಿಕ users ಗೆ ಸೇವೆ ನೀಡುತ್ತದೆ; ಕೇವಲ 5 steps ಆದ್ಯಂತ ನಿಜವಾಗಿ-ದೃಢಪಡಿಸಿದ 20-vs-6 ಅಂತರ ಎಂದರೆ naive serving ಗೆ ದೀರ್ಘ generations ನಲ್ಲಿ ನಿಜವಾಗಿ-ದೃಢಪಡಿಸಿದ ಚತುರ್ಭುಜ ಬೆಳವಣಿಗೆ ಪರಿಗಣಿಸುವ ಮೊದಲೇ ಪ್ರತಿ request ಗೆ ಸುಮಾರು 3x ಹೆಚ್ಚು compute ಅಗತ್ಯ -- caching ನಂತರ ಅನ್ವಯಿಸಿದ ಒಂದೂ optimization ಅಲ್ಲ, ಇದೂ serving ಆರ್ಥಿಕವಾಗಿ ಕಾರ್ಯಸಾಧ್ಯವಾಗಲು ಒಂದೂ ಪೂರ್ವಷರತ್ತು' } },
    { type: 'concept', data: {
      headingEn: 'Real-World Example', headingKn: 'Real-World Example',
      bodyEn: 'A chat application serving a 2,000-token conversation history generates each new reply token by token. Without caching, the genuinely-confirmed pattern above means every single new token would require reprocessing the entire 2,000-token prefix -- at the scaling this lesson genuinely computed (naive cost growing quadratically), a 100-token reply would cost roughly 51x more compute than the cached version, which only ever processes each new token once. This is exactly why every major LLM provider treats KV caching as a non-negotiable part of their serving stack rather than an optional speedup.',
      bodyKn: 'ಒಂದೂ chat application 2,000-token conversation history ಗೆ ಸೇವೆ ನೀಡುತ್ತಾ ಪ್ರತಿ ಹೊಸ reply ಅನ್ನೂ token ಗೆ token ಉತ್ಪಾದಿಸುತ್ತದೆ. Caching ಇಲ್ಲದೆ, ಮೇಲಿನ ನಿಜವಾಗಿ-ದೃಢಪಡಿಸಿದ ಮಾದರಿ ಎಂದರೆ ಪ್ರತಿ ಒಂದೂ ಹೊಸ token ಗೆ ಸಂಪೂರ್ಣ 2,000-token prefix ಮರುಪ್ರಕ್ರಿಯೆಗೊಳಿಸಬೇಕು -- ಈ lesson ನಿಜವಾಗಿ ಗಣಿಸಿದ ಪ್ರಮಾಣದಲ್ಲಿ (naive ವೆಚ್ಚ ಚತುರ್ಭುಜವಾಗಿ ಬೆಳೆಯುತ್ತಾ), ಒಂದೂ 100-token reply cached ಆವೃತ್ತಿಗಿಂತ ಸುಮಾರು 51x ಹೆಚ್ಚು compute ವೆಚ್ಚ ಮಾಡುತ್ತದೆ, ಇದೂ ಪ್ರತಿ ಹೊಸ token ಅನ್ನೂ ಕೇವಲ ಒಂದೂ ಬಾರಿ ಪ್ರಕ್ರಿಯೆಗೊಳಿಸುತ್ತದೆ. ಇದೇ ನಿಖರವಾಗಿ ಪ್ರತಿ ಪ್ರಮುಖ LLM provider KV caching ಅನ್ನೂ ತಮ್ಮ serving stack ನ ಒಂದೂ ಸಂಧಾನಿಸಲಾಗದ ಭಾಗವಾಗಿ ಪರಿಗಣಿಸುತ್ತದೆ, ಒಂದೂ ಐಚ್ಛಿಕ speedup ಆಗಿ ಅಲ್ಲ.' } },
    { type: 'concept', data: {
      headingEn: 'Why the 500-Token Case Matters More Than the 5-Token Case', headingKn: '500-Token Case 5-Token Case ಗಿಂತ ಏಕೆ ಹೆಚ್ಚು ಮುಖ್ಯ',
      bodyEn: '• The genuinely-confirmed 5-step example (20 vs 6 ops, 3.33x) understates the real-world impact -- modern chat and agent responses routinely run to hundreds of tokens, and the genuinely-confirmed scaling table shows the ratio climbing to 251.49x at 500 generated tokens\n• This non-constant, ever-widening gap is why KV caching cannot be treated as a nice-to-have micro-optimization: at short lengths it saves a noticeable amount of compute, but at the lengths real production systems actually operate at, it is the difference between a request completing in a reasonable time and one that does not complete at all within a practical budget',
      bodyKn: '• ನಿಜವಾಗಿ-ದೃಢಪಡಿಸಿದ 5-step ಉದಾಹರಣೆ (20 vs 6 ops, 3.33x) ನಿಜ-ಜಗತ್ತಿನ ಪ್ರಭಾವವನ್ನೂ ಕಡಿಮೆ ಅಂದಾಜು ಮಾಡುತ್ತದೆ -- ಆಧುನಿಕ chat ಮತ್ತು agent responses ಸಾಮಾನ್ಯವಾಗಿ ನೂರಾರು tokens ಗೆ ಓಡುತ್ತವೆ, ಮತ್ತು ನಿಜವಾಗಿ-ದೃಢಪಡಿಸಿದ scaling table 500 ಉತ್ಪಾದಿಸಿದ tokens ನಲ್ಲಿ ಅನುಪಾತ 251.49x ಗೆ ಏರುತ್ತದೆ ಎಂದು ತೋರಿಸುತ್ತದೆ\n• ಈ ಸ್ಥಿರವಲ್ಲದ, ಎಂದೆಂದಿಗೂ-ವಿಸ್ತಾರಗೊಳ್ಳುವ ಅಂತರ ಏಕೆ KV caching ಅನ್ನೂ ಒಂದೂ ಒಳ್ಳೆಯ-ಇರಬೇಕಾದ micro-optimization ಎಂದು ಪರಿಗಣಿಸಲಾಗುವುದಿಲ್ಲ ಎಂಬುದಕ್ಕೆ ಕಾರಣ: ಚಿಕ್ಕ lengths ನಲ್ಲಿ ಇದೂ ಗಮನಾರ್ಹ compute ಉಳಿಸುತ್ತದೆ, ಆದರೆ ನಿಜ production systems ನಿಜವಾಗಿ ಕಾರ್ಯನಿರ್ವಹಿಸುವ lengths ನಲ್ಲಿ, ಇದೂ ಒಂದೂ request ಸಮಂಜಸ ಸಮಯದಲ್ಲಿ ಪೂರ್ಣಗೊಳ್ಳುವುದೂ ಮತ್ತು ಒಂದೂ ಪ್ರಾಯೋಗಿಕ ಬಜೆಟ್ ಒಳಗೆ ಪೂರ್ಣಗೊಳ್ಳದಿರುವುದೂ ನಡುವಿನ ವ್ಯತ್ಯಾಸ' } },

    { type: 'quiz', data: { questions: [
      { q: 'Genuinely tested across 5 generation steps, did the naive full-recompute generator and the KV-cached generator produce different outputs?', qKn: '5 generation steps ಆದ್ಯಂತ ನಿಜವಾಗಿ ಪರೀಕ್ಷಿಸಿದ, naive full-recompute generator ಮತ್ತು KV-cached generator ಬೇರೆ outputs ಉತ್ಪಾದಿಸಿದವೇ?',
        opts: ['Yes, caching introduces a small approximation error', 'No -- genuinely confirmed bit-identical logits at every step; caching only reduces redundant computation', 'Yes, the cached version was consistently less accurate', 'Only for the first step'], correct: 1,
        optsKn: ['ಹೌದು, caching ಒಂದೂ ಚಿಕ್ಕ ಅಂದಾಜು ದೋಷ ಪರಿಚಯಿಸುತ್ತದೆ', 'ಇಲ್ಲ -- ಪ್ರತಿ step ನಲ್ಲಿ bit-identical logits ಎಂದು ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ; caching ಕೇವಲ ಅನಗತ್ಯ ಗಣನೆ ಕಡಿಮೆ ಮಾಡುತ್ತದೆ', 'ಹೌದು, cached ಆವೃತ್ತಿ ಸ್ಥಿರವಾಗಿ ಕಡಿಮೆ ನಿಖರವಾಗಿತ್ತು', 'ಕೇವಲ ಮೊದಲ step ಗಾಗಿ'] },
      { q: 'Genuinely computed, how did the naive-vs-cached K,V operation ratio change from 5 to 500 generated tokens?', qKn: 'ನಿಜವಾಗಿ ಗಣಿಸಿದ, naive-vs-cached K,V operation ಅನುಪಾತ 5 ಇಂದ 500 ಉತ್ಪಾದಿಸಿದ tokens ಗೆ ಹೇಗೆ ಬದಲಾಯಿತು?',
        opts: ['It stayed constant at about 3.5x', 'It genuinely grew from 3.57x to 251.49x, confirming naive cost is quadratic and cached cost is linear', 'It decreased as more tokens were generated', 'It became negative'], correct: 1,
        optsKn: ['ಇದೂ ಸುಮಾರು 3.5x ನಲ್ಲಿ ಸ್ಥಿರವಾಗಿ ಉಳಿಯಿತು', 'ಇದೂ ನಿಜವಾಗಿ 3.57x ಇಂದ 251.49x ಗೆ ಬೆಳೆಯಿತು, naive ವೆಚ್ಚ ಚತುರ್ಭುಜ ಮತ್ತು cached ವೆಚ್ಚ ರೇಖೀಯ ಎಂದು ದೃಢಪಡಿಸುತ್ತಾ', 'ಹೆಚ್ಚು tokens ಉತ್ಪಾದಿಸಿದಂತೆ ಇದೂ ಕಡಿಮೆಯಾಯಿತು', 'ಇದೂ ಋಣಾತ್ಮಕವಾಯಿತು'] },
      { q: 'Genuinely confirmed on the 5-step, 2-to-7-token example, how many total K,V computations did the naive generator perform versus the KV-cached generator?', qKn: '5-step, 2-ಇಂದ-7-token ಉದಾಹರಣೆಯಲ್ಲಿ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ, naive generator ಎಷ್ಟು ಒಟ್ಟು K,V computations ನಿರ್ವಹಿಸಿತು KV-cached generator ಗೆ ಹೋಲಿಸಿ?',
        opts: ['20 for naive, 6 for cached -- genuinely confirmed', '6 for naive, 20 for cached', '20 for both', '5 for naive, 5 for cached'], correct: 0,
        optsKn: ['naive ಗಾಗಿ 20, cached ಗಾಗಿ 6 -- ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ', 'naive ಗಾಗಿ 6, cached ಗಾಗಿ 20', 'ಎರಡಕ್ಕೂ 20', 'naive ಗಾಗಿ 5, cached ಗಾಗಿ 5'] },
      { q: 'Genuinely computed for 100 generated tokens (prompt length 2), what were the naive and cached total K,V operation counts, and their ratio?', qKn: '100 ಉತ್ಪಾದಿಸಿದ tokens ಗಾಗಿ (prompt length 2) ನಿಜವಾಗಿ ಗಣಿಸಿದ, naive ಮತ್ತು cached ಒಟ್ಟು K,V operation counts, ಮತ್ತು ಅವುಗಳ ಅನುಪಾತ ಏನೂ?',
        opts: ['naive=102, cached=5250, ratio=0.02x', 'naive=5,250, cached=102, ratio=51.47x -- genuinely confirmed', 'naive=cached=5250', 'naive=250, cached=22, ratio=11.36x'], correct: 1,
        optsKn: ['naive=102, cached=5250, ratio=0.02x', 'naive=5,250, cached=102, ratio=51.47x -- ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ', 'naive=cached=5250', 'naive=250, cached=22, ratio=11.36x'] },
      { q: 'Genuinely confirmed by the closed-form formulas, naive total K,V cost (sum of a growing prefix) grows in which order relative to tokens generated, versus cached cost?', qKn: 'closed-form formulas ಇಂದ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ, naive ಒಟ್ಟು K,V ವೆಚ್ಚ (ಬೆಳೆಯುತ್ತಿರುವ prefix ನ ಮೊತ್ತ) ಉತ್ಪಾದಿಸಿದ tokens ಗೆ ಸಂಬಂಧಿಸಿ ಯಾವ order ನಲ್ಲಿ ಬೆಳೆಯುತ್ತದೆ, cached ವೆಚ್ಚಕ್ಕೆ ಹೋಲಿಸಿ?',
        opts: ['Both are linear, O(n)', 'Naive is quadratic, O(n^2); cached is linear, O(n) -- genuinely confirmed by the growing ratio', 'Naive is linear; cached is quadratic', 'Both are constant, O(1)'], correct: 1,
        optsKn: ['ಎರಡೂ ರೇಖೀಯ, O(n)', 'Naive ಚತುರ್ಭುಜ, O(n^2); cached ರೇಖೀಯ, O(n) -- ಬೆಳೆಯುತ್ತಿರುವ ಅನುಪಾತದಿಂದ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ', 'Naive ರೇಖೀಯ; cached ಚತುರ್ಭುಜ', 'ಎರಡೂ ಸ್ಥಿರ, O(1)'] },
    ] } },
  ],
};
