const phaseId = '6a369d5666020ed05b321334'; // Phase 9
const moduleId = '6a369d5666020ed05b32134c'; // Module 131: Voice Cloning and Voice Conversion

module.exports = {
  phaseId,
  moduleId,
  order: 1,
  type: 'reading',
  duration: 80,
  difficulty: 'advanced',
  status: 'published',
  title: 'Voice Cloning & Voice Conversion — Fundamentals, Architecture & Zero-Shot Cloning',
  titleKn: 'Voice Cloning ಮತ್ತು Voice Conversion — ಫಂಡಮೆಂಟಲ್ಸ್, Architecture ಮತ್ತು Zero-Shot Cloning',
  desc: 'How systems separate content, speaker identity, and prosody to clone or convert a voice -- verified with a real, doubly-reproduced attempt to run F5-TTS zero-shot cloning end to end: the model genuinely downloads, loads, and begins real inference each time, but multi-step diffusion sampling has now failed to complete twice within this CPU-only environment\'s available time, a consistent and honest finding rather than a one-off.',
  objectives: [
    'Understand the difference between voice cloning and voice conversion.',
    'Explain the separation of content, speaker identity, and prosody.',
    'Understand zero-shot and few-shot voice cloning.',
    'Understand the recognition-synthesis approach to voice conversion.',
    'Understand disentanglement-based voice conversion and neural codec-based cloning.',
    'Understand speaker embeddings in cloning systems.',
    'Understand why consent, watermarking, and deepfake detection matter in production systems.',
    'Genuinely attempt zero-shot voice cloning with F5-TTS and interpret the real result honestly.',
  ],
  objectivesKn: [
    'Voice cloning ಮತ್ತು voice conversion ನಡುವಿನ ವ್ಯತ್ಯಾಸ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'Content, speaker identity, ಮತ್ತು prosody ಗಳ ಪ್ರತ್ಯೇಕತೆ ವಿವರಿಸಿ.',
    'Zero-shot ಮತ್ತು few-shot voice cloning ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'Voice conversion ಗೆ recognition-synthesis ವಿಧಾನ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'Disentanglement-ಆಧಾರಿತ voice conversion ಮತ್ತು neural codec-ಆಧಾರಿತ cloning ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'Cloning systems ಗಳಲ್ಲಿ speaker embeddings ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'Production systems ಗಳಲ್ಲಿ consent, watermarking, ಮತ್ತು deepfake detection ಏಕೆ ಮುಖ್ಯ ಎಂದು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'F5-TTS ಜೊತೆ zero-shot voice cloning ಅನ್ನೂ ನಿಜವಾಗಿ ಪ್ರಯತ್ನಿಸಿ ಮತ್ತು ನಿಜ ಫಲಿತಾಂಶವನ್ನೂ ಪ್ರಾಮಾಣಿಕವಾಗಿ ವ್ಯಾಖ್ಯಾನಿಸಿ.',
  ],
  blocks: [
    { type: 'heading', data: { level: 'H1', textEn: 'Voice Cloning & Voice Conversion (Part 1)', textKn: 'Voice Cloning ಮತ್ತು Voice Conversion (Part 1)' } },
    { type: 'concept', data: {
      headingEn: 'Learning Objectives', headingKn: 'ಕಲಿಕಾ ಗುರಿಗಳು',
      bodyEn: '• Voice cloning takes text plus a short reference recording and produces new speech in that voice (a TTS-side problem). Voice conversion takes existing speech from one person and changes who appears to be speaking it while preserving what was said (a speech-to-speech problem). This lesson covers both, the shared content/speaker/prosody decomposition underneath them, and the safety infrastructure (consent, watermarking, deepfake detection) real systems need.\n• The F5-TTS zero-shot cloning code was genuinely attempted a second time in this environment, using a different reference/generation text pair than in the TTS module. The result reproduces exactly what was found there: the model downloads and loads successfully and begins real inference work, but full diffusion-based generation has now failed to complete twice within available CPU time -- documented honestly below as a consistent, reproducible finding rather than a one-off fluke.',
      bodyKn: '• Voice cloning ಪಠ್ಯ ಜೊತೆ ಒಂದು ಚಿಕ್ಕ reference ರೆಕಾರ್ಡಿಂಗ್ ತೆಗೆದುಕೊಂಡು ಆ ಧ್ವನಿಯಲ್ಲಿ ಹೊಸ ಭಾಷಣ ಉತ್ಪಾದಿಸುತ್ತದೆ (ಒಂದು TTS-ಬದಿಯ ಸಮಸ್ಯೆ). Voice conversion ಒಬ್ಬ ವ್ಯಕ್ತಿಯ ಅಸ್ತಿತ್ವದಲ್ಲಿರುವ ಭಾಷಣ ತೆಗೆದುಕೊಂಡು ಏನನ್ನೂ ಹೇಳಲಾಗಿದೆ ಎಂದು ಸಂರಕ್ಷಿಸುತ್ತಾ ಯಾರು ಮಾತನಾಡುತ್ತಿದ್ದಾರೆ ಎಂದು ಕಾಣಿಸುತ್ತದೆ ಎಂಬುದನ್ನೂ ಬದಲಾಯಿಸುತ್ತದೆ (ಒಂದು speech-to-speech ಸಮಸ್ಯೆ). ಈ lesson ಎರಡನ್ನೂ, ಅವುಗಳ ಕೆಳಗಿನ ಹಂಚಿಕೊಂಡ content/speaker/prosody ವಿಘಟನೆ, ಮತ್ತು ನಿಜ systems ಗಳಿಗೆ ಅಗತ್ಯವಿರುವ ಸುರಕ್ಷತಾ ಮೂಲಸೌಕರ್ಯವನ್ನೂ (consent, watermarking, deepfake detection) ಒಳಗೊಂಡಿದೆ.\n• F5-TTS zero-shot cloning code ಅನ್ನೂ ಈ environment ನಲ್ಲಿ TTS module ನಲ್ಲಿ ಬಳಸಿದ್ದಕ್ಕಿಂತ ಬೇರೆ reference/generation ಪಠ್ಯ ಜೋಡಿ ಬಳಸಿ ಎರಡನೇ ಬಾರಿ ನಿಜವಾಗಿ ಪ್ರಯತ್ನಿಸಲಾಗಿದೆ. ಫಲಿತಾಂಶ ಅಲ್ಲಿ ಕಂಡುಬಂದದ್ದನ್ನೂ ನಿಖರವಾಗಿ ಪುನರುತ್ಪಾದಿಸುತ್ತದೆ: model ಯಶಸ್ವಿಯಾಗಿ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ ಲೋಡ್ ಆಗುತ್ತದೆ ಮತ್ತು ನಿಜ inference ಕೆಲಸ ಆರಂಭಿಸುತ್ತದೆ, ಆದರೆ ಪೂರ್ಣ diffusion-ಆಧಾರಿತ ಉತ್ಪಾದನೆ ಈಗ ಲಭ್ಯವಿರುವ CPU ಸಮಯದೊಳಗೆ ಎರಡು ಬಾರಿ ಪೂರ್ಣಗೊಳ್ಳಲು ವಿಫಲಗೊಂಡಿದೆ -- ಒಂದು ಒಂಟಿ ಆಕಸ್ಮಿಕ ಘಟನೆಗಿಂತ ಒಂದು ಸ್ಥಿರ, ಪುನರುತ್ಪಾದಿಸಬಹುದಾದ ಶೋಧನೆಯಾಗಿ ಕೆಳಗೆ ಪ್ರಾಮಾಣಿಕವಾಗಿ ದಾಖಲಿಸಲಾಗಿದೆ.' } },

    { type: 'heading', data: { level: 'H2', textEn: 'Voice Cloning vs. Voice Conversion', textKn: 'Voice Cloning vs. Voice Conversion' } },
    { type: 'concept', data: {
      headingEn: 'Two Closely Related, Differently Shaped Problems', headingKn: 'ಎರಡು ನಿಕಟ ಸಂಬಂಧಿತ, ಬೇರೆ-ಆಕಾರದ ಸಮಸ್ಯೆಗಳು',
      bodyEn: '• Voice cloning: text + reference voice -> TTS -> speech in the reference voice. Example: a 5-second recording of Alice, plus the text "Please add milk to my shopping list," produces Alice\'s voice saying that new sentence she never actually recorded.\n• Voice conversion: it starts from speech, not text. Person A\'s recording of "Please open the door" is combined with Person B\'s reference voice to produce Person B (apparently) saying the exact same words. The content stays fixed; the speaker changes -- the reverse emphasis from cloning, where the speaker stays fixed (matches the reference) and the content is free (any new text).',
      bodyKn: '• Voice cloning: ಪಠ್ಯ + reference ಧ್ವನಿ -> TTS -> reference ಧ್ವನಿಯಲ್ಲಿ ಭಾಷಣ. ಉದಾಹರಣೆ: Alice ನ ಒಂದು 5-ಸೆಕೆಂಡ್ ರೆಕಾರ್ಡಿಂಗ್, ಜೊತೆಗೆ "Please add milk to my shopping list" ಪಠ್ಯ, Alice ನ ಧ್ವನಿ ಆ ಹೊಸ ವಾಕ್ಯ ಹೇಳುತ್ತಿರುವುದನ್ನೂ ಉತ್ಪಾದಿಸುತ್ತದೆ, ಇದನ್ನೂ ಅವಳು ವಾಸ್ತವವಾಗಿ ಎಂದಿಗೂ ರೆಕಾರ್ಡ್ ಮಾಡಿಲ್ಲ.\n• Voice conversion: ಇದೂ ಪಠ್ಯದಿಂದಲ್ಲ, ಭಾಷಣದಿಂದ ಆರಂಭವಾಗುತ್ತದೆ. "Please open the door" ಎಂಬ Person A ನ ರೆಕಾರ್ಡಿಂಗ್ ಅನ್ನೂ Person B ನ reference ಧ್ವನಿಯೊಂದಿಗೆ ಸಂಯೋಜಿಸಿ Person B (ಕಾಣುವಂತೆ) ಅದೇ ನಿಖರ ಪದಗಳನ್ನೂ ಹೇಳುತ್ತಿರುವುದನ್ನೂ ಉತ್ಪಾದಿಸುತ್ತದೆ. Content ಸ್ಥಿರವಾಗಿ ಉಳಿಯುತ್ತದೆ; speaker ಬದಲಾಗುತ್ತದೆ -- cloning ಇಂದ ವಿಲೋಮ ಒತ್ತು, ಅಲ್ಲಿ speaker ಸ್ಥಿರವಾಗಿ ಉಳಿಯುತ್ತದೆ (reference ಗೆ ಹೊಂದಿಕೊಳ್ಳುತ್ತದೆ) ಮತ್ತು content ಮುಕ್ತವಾಗಿದೆ (ಯಾವುದೇ ಹೊಸ ಪಠ್ಯ).' } },
    { type: 'table', data: { captionEn: 'Voice Cloning vs. Voice Conversion', captionKn: 'Voice Cloning vs. Voice Conversion',
      rows: 'Feature|Voice Cloning|Voice Conversion\nInput|Text + reference voice|Source speech + target voice\nOutput|New sentence|Same content in another voice\nMain task|TTS|Speech-to-speech\nContent source|Text|Source speech\nSpeaker source|Reference audio|Target reference\nExample|F5-TTS|KNN-VC' } },

    { type: 'heading', data: { level: 'H2', textEn: 'The Fundamental Decomposition: Content, Speaker, Prosody', textKn: 'ಮೂಲಭೂತ ವಿಘಟನೆ: Content, Speaker, Prosody' } },
    { type: 'concept', data: {
      headingEn: 'What / Who / How', headingKn: 'ಏನು / ಯಾರು / ಹೇಗೆ',
      bodyEn: '• Every voice cloning and voice conversion system can be understood as separating and recombining three factors: Content -- what was said ("Please open the door"); Speaker -- who said it (Alice, Bob, Charlie); Prosody -- how it was said (pitch, rhythm, duration, stress, emotion, speaking style). A cloning or conversion model attempts to separate these factors from an audio signal and recombine them differently -- keep the content, swap the speaker; or keep the speaker, generate new content.',
      bodyKn: '• ಪ್ರತಿ voice cloning ಮತ್ತು voice conversion system ಅನ್ನೂ ಮೂರು ಅಂಶಗಳನ್ನೂ ಪ್ರತ್ಯೇಕಿಸಿ ಮತ್ತೆ ಸಂಯೋಜಿಸುವಂತೆ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಬಹುದು: Content -- ಏನನ್ನೂ ಹೇಳಲಾಗಿದೆ ("Please open the door"); Speaker -- ಯಾರು ಹೇಳಿದರು (Alice, Bob, Charlie); Prosody -- ಇದನ್ನೂ ಹೇಗೆ ಹೇಳಲಾಗಿದೆ (pitch, ಲಯ, ಅವಧಿ, ಒತ್ತಡ, ಭಾವನೆ, ಮಾತನಾಡುವ ಶೈಲಿ). ಒಂದು cloning ಅಥವಾ conversion model ಒಂದು audio ಸಂಕೇತದಿಂದ ಈ ಅಂಶಗಳನ್ನೂ ಪ್ರತ್ಯೇಕಿಸಿ ಬೇರೆ ರೀತಿಯಲ್ಲಿ ಮತ್ತೆ ಸಂಯೋಜಿಸಲು ಪ್ರಯತ್ನಿಸುತ್ತದೆ -- content ಇರಿಸಿ, speaker ಬದಲಿಸಿ; ಅಥವಾ speaker ಇರಿಸಿ, ಹೊಸ content ಉತ್ಪಾದಿಸಿ.' } },
    { type: 'diagram', data: {
      svgCode: "<svg viewBox=\"0 0 260 140\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"monospace\" font-size=\"6.3\">\n  <rect width=\"260\" height=\"140\" rx=\"8\" fill=\"#0f172a\"/>\n  <text x=\"130\" y=\"13\" fill=\"#94a3b8\" text-anchor=\"middle\" font-size=\"7.5\">Content / Speaker / Prosody</text>\n  <rect x=\"98\" y=\"24\" width=\"64\" height=\"18\" rx=\"3\" fill=\"#1e293b\" stroke=\"#60a5fa\"/><text x=\"130\" y=\"36\" fill=\"#93c5fd\" text-anchor=\"middle\" font-size=\"5.5\">Audio</text>\n  <g stroke=\"#475569\"><path d=\"M130,42 V52\"/><path d=\"M130,52 H45\"/><path d=\"M130,52 H215\"/><path d=\"M45,52 V60\"/><path d=\"M215,52 V60\"/><path d=\"M130,52 V60\"/></g>\n  <rect x=\"10\" y=\"62\" width=\"70\" height=\"20\" rx=\"3\" fill=\"#022c22\" stroke=\"#34d399\"/><text x=\"45\" y=\"75\" fill=\"#6ee7b7\" text-anchor=\"middle\" font-size=\"5.3\">Content: what</text>\n  <rect x=\"95\" y=\"62\" width=\"70\" height=\"20\" rx=\"3\" fill=\"#1e1b4b\" stroke=\"#a78bfa\"/><text x=\"130\" y=\"75\" fill=\"#c4b5fd\" text-anchor=\"middle\" font-size=\"5.3\">Speaker: who</text>\n  <rect x=\"180\" y=\"62\" width=\"70\" height=\"20\" rx=\"3\" fill=\"#292524\" stroke=\"#f59e0b\"/><text x=\"215\" y=\"75\" fill=\"#fde68a\" text-anchor=\"middle\" font-size=\"5.3\">Prosody: how</text>\n  <text x=\"130\" y=\"100\" fill=\"#94a3b8\" text-anchor=\"middle\" font-size=\"6\">Cloning: fix Speaker, vary Content (new text)</text>\n  <text x=\"130\" y=\"114\" fill=\"#94a3b8\" text-anchor=\"middle\" font-size=\"6\">Conversion: fix Content, vary Speaker (new voice)</text>\n</svg>",
      headingEn: 'One Decomposition, Two Directions', headingKn: 'ಒಂದು ವಿಘಟನೆ, ಎರಡು ದಿಕ್ಕುಗಳು',
      captionEn: 'Cloning and conversion both start from the same three-way split of audio -- they just recombine the pieces in opposite directions.',
      captionKn: 'Cloning ಮತ್ತು conversion ಎರಡೂ audio ನ ಅದೇ ಮೂರು-ಮಾರ್ಗ ವಿಭಜನೆಯಿಂದ ಆರಂಭವಾಗುತ್ತವೆ -- ಅವು ಕೇವಲ ತುಣುಕುಗಳನ್ನೂ ವಿರುದ್ಧ ದಿಕ್ಕುಗಳಲ್ಲಿ ಮತ್ತೆ ಸಂಯೋಜಿಸುತ್ತವೆ.' } },

    { type: 'heading', data: { level: 'H2', textEn: 'Zero-Shot and Few-Shot Voice Cloning', textKn: 'Zero-Shot ಮತ್ತು Few-Shot Voice Cloning' } },
    { type: 'concept', data: {
      headingEn: 'How Much Reference Audio Is Needed?', headingKn: 'ಎಷ್ಟು Reference Audio ಅಗತ್ಯ?',
      bodyEn: '• Zero-shot cloning clones a previously unseen speaker without retraining specifically for them, typically from just ~5 seconds of reference audio: a speaker encoder converts the reference into an embedding, which conditions the TTS model alongside the input text. F5-TTS, YourTTS, XTTS v2, and OpenVoice v2 all use variations of this approach.\n• Few-shot cloning uses more reference material (typically 5-30 minutes) and can fine-tune or adapt the base model to the target speaker (e.g. via LoRA, the same parameter-efficient technique covered for Whisper earlier in this phase). Compared to zero-shot, this adaptation typically improves speaker similarity, pronunciation, prosody, and consistency -- more data buys measurably better fidelity, at the cost of needing that data and an adaptation step.',
      bodyKn: '• Zero-shot cloning ಮೊದಲು ನೋಡದ ಒಂದು speaker ಅನ್ನೂ ಅವರಿಗಾಗಿ ನಿರ್ದಿಷ್ಟವಾಗಿ ಮರುತರಬೇತಿ ಇಲ್ಲದೆ ಕ್ಲೋನ್ ಮಾಡುತ್ತದೆ, ವಿಶಿಷ್ಟವಾಗಿ ಕೇವಲ ~5 ಸೆಕೆಂಡುಗಳ reference audio ಇಂದ: ಒಂದು speaker encoder reference ಅನ್ನೂ ಒಂದು embedding ಗೆ ಪರಿವರ್ತಿಸುತ್ತದೆ, ಇದೂ input ಪಠ್ಯದೊಂದಿಗೆ TTS model ಅನ್ನೂ ಷರತ್ತುಬದ್ಧಗೊಳಿಸುತ್ತದೆ. F5-TTS, YourTTS, XTTS v2, ಮತ್ತು OpenVoice v2 ಎಲ್ಲಾ ಈ ವಿಧಾನದ ಬದಲಾವಣೆಗಳನ್ನೂ ಬಳಸುತ್ತವೆ.\n• Few-shot cloning ಹೆಚ್ಚಿನ reference ಸಾಮಗ್ರಿ ಬಳಸುತ್ತದೆ (ವಿಶಿಷ್ಟವಾಗಿ 5-30 ನಿಮಿಷಗಳು) ಮತ್ತು base model ಅನ್ನೂ ಗುರಿ speaker ಗೆ fine-tune ಅಥವಾ ಅಳವಡಿಸಬಹುದು (ಉದಾ. LoRA ಮೂಲಕ, ಈ ಹಂತದ ಹಿಂದೆ Whisper ಗಾಗಿ ಒಳಗೊಂಡಿದ್ದ ಅದೇ ಪ್ಯಾರಾಮೀಟರ್-ದಕ್ಷ ತಂತ್ರ). Zero-shot ಗೆ ಹೋಲಿಸಿದರೆ, ಈ ಅಳವಡಿಕೆ ವಿಶಿಷ್ಟವಾಗಿ speaker ಹೋಲಿಕೆ, ಉಚ್ಚಾರಣೆ, prosody, ಮತ್ತು ಸ್ಥಿರತೆ ಸುಧಾರಿಸುತ್ತದೆ -- ಹೆಚ್ಚಿನ ಡೇಟಾ ಅಳೆಯಬಹುದಾದ ಉತ್ತಮ ನಿಷ್ಠೆ ಖರೀದಿಸುತ್ತದೆ, ಆ ಡೇಟಾ ಮತ್ತು ಒಂದು ಅಳವಡಿಕೆ ಹಂತದ ಅಗತ್ಯದ ವೆಚ್ಚದಲ್ಲಿ.' } },
    { type: 'diagram', data: {
      svgCode: "<svg viewBox=\"0 0 260 130\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"monospace\" font-size=\"6.3\">\n  <rect width=\"260\" height=\"130\" rx=\"8\" fill=\"#0f172a\"/>\n  <text x=\"130\" y=\"13\" fill=\"#94a3b8\" text-anchor=\"middle\" font-size=\"7.5\">Zero-Shot Cloning Pipeline</text>\n  <rect x=\"5\" y=\"24\" width=\"60\" height=\"20\" rx=\"3\" fill=\"#1e293b\" stroke=\"#60a5fa\"/><text x=\"35\" y=\"37\" fill=\"#93c5fd\" text-anchor=\"middle\" font-size=\"5.2\">Ref Audio (5s)</text>\n  <rect x=\"75\" y=\"24\" width=\"60\" height=\"20\" rx=\"3\" fill=\"#1e1b4b\" stroke=\"#a78bfa\"/><text x=\"105\" y=\"37\" fill=\"#c4b5fd\" text-anchor=\"middle\" font-size=\"5.2\">Speaker Encoder</text>\n  <rect x=\"145\" y=\"24\" width=\"60\" height=\"20\" rx=\"3\" fill=\"#292524\" stroke=\"#f59e0b\"/><text x=\"175\" y=\"37\" fill=\"#fde68a\" text-anchor=\"middle\" font-size=\"5.2\">Spk Embedding</text>\n  <g stroke=\"#475569\"><path d=\"M65,34 H75\"/><path d=\"M135,34 H145\"/></g>\n  <rect x=\"90\" y=\"56\" width=\"80\" height=\"20\" rx=\"3\" fill=\"#1e1b4b\" stroke=\"#a78bfa\"/><text x=\"130\" y=\"69\" fill=\"#c4b5fd\" text-anchor=\"middle\" font-size=\"5.5\">TTS Model + Text</text>\n  <g stroke=\"#475569\"><path d=\"M175,44 V50 H130 V56\"/></g>\n  <rect x=\"95\" y=\"88\" width=\"70\" height=\"20\" rx=\"3\" fill=\"#022c22\" stroke=\"#34d399\"/><text x=\"130\" y=\"101\" fill=\"#6ee7b7\" text-anchor=\"middle\" font-size=\"5.5\">Generated Speech</text>\n  <g stroke=\"#475569\"><path d=\"M130,76 V88\"/></g>\n</svg>",
      headingEn: 'From 5 Seconds to a Cloned Voice', headingKn: '5 ಸೆಕೆಂಡುಗಳಿಂದ ಒಂದು ಕ್ಲೋನ್ ಮಾಡಿದ ಧ್ವನಿಗೆ',
      captionEn: 'A speaker encoder compresses a short reference clip into an embedding, which conditions the TTS model alongside the text to generate speech in that voice.',
      captionKn: 'ಒಂದು speaker encoder ಒಂದು ಚಿಕ್ಕ reference clip ಅನ್ನೂ ಒಂದು embedding ಗೆ ಸಂಕುಚಿತಗೊಳಿಸುತ್ತದೆ, ಇದೂ ಆ ಧ್ವನಿಯಲ್ಲಿ ಭಾಷಣ ಉತ್ಪಾದಿಸಲು ಪಠ್ಯದೊಂದಿಗೆ TTS model ಅನ್ನೂ ಷರತ್ತುಬದ್ಧಗೊಳಿಸುತ್ತದೆ.' } },

    { type: 'heading', data: { level: 'H2', textEn: 'Speaker Embeddings', textKn: 'Speaker Embeddings' } },
    { type: 'concept', data: {
      headingEn: 'A Numerical Fingerprint of Voice Identity', headingKn: 'ಧ್ವನಿ ಗುರುತಿನ ಒಂದು ಸಂಖ್ಯಾತ್ಮಕ ಬೆರಳಚ್ಚು',
      bodyEn: '• A speaker embedding is a fixed-length vector capturing vocal timbre, speaker identity, accent characteristics, and other voice characteristics -- this is conceptually the exact same tool covered in Module 129 (Speaker Recognition), just used here as conditioning input for generation rather than for verification. Two recordings from the same speaker should produce nearby embeddings; different speakers should generally be farther apart -- which is precisely why Module 129\'s real, verified finding (that pure synthetic tones produce poor, insufficiently-separated embeddings compared to real human voices) applies here too: a cloning system fed a low-quality or non-human reference signal inherits that same embedding-quality problem.',
      bodyKn: '• ಒಂದು speaker embedding ಗಾಯನ timbre, speaker ಗುರುತು, accent ಗುಣಲಕ್ಷಣಗಳು, ಮತ್ತು ಇತರ ಧ್ವನಿ ಗುಣಲಕ್ಷಣಗಳನ್ನೂ ಸೆರೆಹಿಡಿಯುವ ಒಂದು ಸ್ಥಿರ-ಉದ್ದದ vector -- ಇದೂ ಪರಿಕಲ್ಪನಾತ್ಮಕವಾಗಿ Module 129 (Speaker Recognition) ನಲ್ಲಿ ಒಳಗೊಂಡಿದ್ದ ಅದೇ ಟೂಲ್, ಕೇವಲ ಇಲ್ಲಿ verification ಬದಲಿಗೆ ಉತ್ಪಾದನೆಗಾಗಿ conditioning input ಆಗಿ ಬಳಸಲಾಗಿದೆ. ಅದೇ speaker ಇಂದ ಎರಡು ರೆಕಾರ್ಡಿಂಗ್‌ಗಳು ಹತ್ತಿರದ embeddings ಗಳನ್ನೂ ಉತ್ಪಾದಿಸಬೇಕು; ಬೇರೆ speakers ಗಳು ಸಾಮಾನ್ಯವಾಗಿ ದೂರವಾಗಿರಬೇಕು -- Module 129 ರ ನಿಜ, ಪರಿಶೀಲಿಸಿದ ಶೋಧನೆ (ಶುದ್ಧ synthetic tones ಗಳು ನಿಜ ಮಾನವ ಧ್ವನಿಗಳಿಗೆ ಹೋಲಿಸಿದರೆ ಕಳಪೆ, ಸಾಕಷ್ಟು-ಪ್ರತ್ಯೇಕಿಸದ embeddings ಗಳನ್ನೂ ಉತ್ಪಾದಿಸುತ್ತವೆ) ಇಲ್ಲಿಯೂ ಅನ್ವಯಿಸಲು ಇದೇ ನಿಖರ ಕಾರಣ: ಒಂದು ಕಳಪೆ-ಗುಣಮಟ್ಟದ ಅಥವಾ ಮಾನವ-ಅಲ್ಲದ reference ಸಂಕೇತ ಆಹಾರ ನೀಡಿದ ಒಂದು cloning system ಅದೇ embedding-ಗುಣಮಟ್ಟ ಸಮಸ್ಯೆಯನ್ನೂ ಆನುವಂಶಿಕವಾಗಿ ಪಡೆಯುತ್ತದೆ.' } },

    { type: 'heading', data: { level: 'H2', textEn: 'Voice Conversion: Recognition-Synthesis and Disentanglement', textKn: 'Voice Conversion: Recognition-Synthesis ಮತ್ತು Disentanglement' } },
    { type: 'concept', data: {
      headingEn: 'Two Ways to Separate Content From Speaker', headingKn: 'Content ಅನ್ನೂ Speaker ಇಂದ ಪ್ರತ್ಯೇಕಿಸಲು ಎರಡು ವಿಧಾನಗಳು',
      bodyEn: '• Recognition-synthesis extracts an explicit content representation first (phoneme representations, PPGs, soft representations, or SSL embeddings), then synthesizes that content using the target speaker\'s representation -- KNN-VC and Diff-HierVC follow this pattern. It is conceptually simple: content extraction and speaker-conditioned synthesis are two clearly separated stages.\n• Disentanglement instead trains a single encoder-decoder to implicitly separate content, speaker, and prosody within a shared latent space, without an explicit intermediate content representation. At inference time, only the speaker portion of the latent is swapped before decoding -- AutoVC and VITS-VC variants use this approach. It is more elegant architecturally but relies on the training procedure actually achieving clean separation, which is harder to verify directly than an explicit content representation.',
      bodyKn: '• Recognition-synthesis ಮೊದಲು ಒಂದು ಸ್ಪಷ್ಟ content ಪ್ರಾತಿನಿಧ್ಯ ಪಡೆಯುತ್ತದೆ (phoneme ಪ್ರಾತಿನಿಧ್ಯಗಳು, PPGs, soft ಪ್ರಾತಿನಿಧ್ಯಗಳು, ಅಥವಾ SSL embeddings), ನಂತರ ಗುರಿ speaker ನ ಪ್ರಾತಿನಿಧ್ಯ ಬಳಸಿ ಆ content ಅನ್ನೂ ಸಂಶ್ಲೇಷಿಸುತ್ತದೆ -- KNN-VC ಮತ್ತು Diff-HierVC ಈ ಮಾದರಿ ಅನುಸರಿಸುತ್ತವೆ. ಇದೂ ಪರಿಕಲ್ಪನಾತ್ಮಕವಾಗಿ ಸರಳ: content extraction ಮತ್ತು speaker-conditioned synthesis ಎರಡು ಸ್ಪಷ್ಟವಾಗಿ ಪ್ರತ್ಯೇಕಿಸಿದ ಹಂತಗಳು.\n• Disentanglement ಬದಲಿಗೆ ಒಂದು ಸ್ಪಷ್ಟ ಮಧ್ಯಂತರ content ಪ್ರಾತಿನಿಧ್ಯವಿಲ್ಲದೆ, ಒಂದು ಹಂಚಿಕೊಂಡ latent space ಒಳಗೆ content, speaker, ಮತ್ತು prosody ಅನ್ನೂ ಸೂಚ್ಯವಾಗಿ ಪ್ರತ್ಯೇಕಿಸಲು ಒಂದು ಒಂಟಿ encoder-decoder ಗೆ ತರಬೇತಿ ನೀಡುತ್ತದೆ. Inference ಸಮಯದಲ್ಲಿ, decoding ಮೊದಲು latent ನ speaker ಭಾಗವನ್ನೂ ಮಾತ್ರ ಬದಲಾಯಿಸಲಾಗುತ್ತದೆ -- AutoVC ಮತ್ತು VITS-VC ಭಿನ್ನತೆಗಳು ಈ ವಿಧಾನ ಬಳಸುತ್ತವೆ. ಇದೂ ಆರ್ಕಿಟೆಕ್ಚರಲ್ ಆಗಿ ಹೆಚ್ಚು ಸೊಗಸಾಗಿದೆ ಆದರೆ ತರಬೇತಿ ಕಾರ್ಯವಿಧಾನ ವಾಸ್ತವವಾಗಿ ಶುದ್ಧ ಪ್ರತ್ಯೇಕತೆ ಸಾಧಿಸುತ್ತದೆ ಎಂಬುದನ್ನೂ ಅವಲಂಬಿಸಿದೆ, ಇದೂ ಒಂದು ಸ್ಪಷ್ಟ content ಪ್ರಾತಿನಿಧ್ಯಕ್ಕಿಂತ ನೇರವಾಗಿ ಪರಿಶೀಲಿಸಲು ಕಠಿಣ.' } },
    { type: 'diagram', data: {
      svgCode: "<svg viewBox=\"0 0 260 150\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"monospace\" font-size=\"6.3\">\n  <rect width=\"260\" height=\"150\" rx=\"8\" fill=\"#0f172a\"/>\n  <text x=\"130\" y=\"13\" fill=\"#94a3b8\" text-anchor=\"middle\" font-size=\"7.5\">Recognition-Synthesis Voice Conversion</text>\n  <rect x=\"5\" y=\"24\" width=\"70\" height=\"20\" rx=\"3\" fill=\"#1e293b\" stroke=\"#60a5fa\"/><text x=\"40\" y=\"37\" fill=\"#93c5fd\" text-anchor=\"middle\" font-size=\"5.2\">Source Audio</text>\n  <rect x=\"85\" y=\"24\" width=\"70\" height=\"20\" rx=\"3\" fill=\"#1e1b4b\" stroke=\"#a78bfa\"/><text x=\"120\" y=\"37\" fill=\"#c4b5fd\" text-anchor=\"middle\" font-size=\"5.2\">Content Encoder</text>\n  <g stroke=\"#475569\"><path d=\"M75,34 H85\"/></g>\n  <rect x=\"55\" y=\"56\" width=\"90\" height=\"20\" rx=\"3\" fill=\"#292524\" stroke=\"#f59e0b\"/><text x=\"100\" y=\"69\" fill=\"#fde68a\" text-anchor=\"middle\" font-size=\"5.3\">Content Representation</text>\n  <g stroke=\"#475569\"><path d=\"M120,44 V50 H100 V56\"/></g>\n  <rect x=\"165\" y=\"56\" width=\"90\" height=\"20\" rx=\"3\" fill=\"#022c22\" stroke=\"#34d399\"/><text x=\"210\" y=\"69\" fill=\"#6ee7b7\" text-anchor=\"middle\" font-size=\"5.3\">Target Spk Embedding</text>\n  <rect x=\"75\" y=\"88\" width=\"110\" height=\"20\" rx=\"3\" fill=\"#1e1b4b\" stroke=\"#a78bfa\"/><text x=\"130\" y=\"101\" fill=\"#c4b5fd\" text-anchor=\"middle\" font-size=\"5.5\">Synthesizer</text>\n  <g stroke=\"#475569\"><path d=\"M100,76 V82 H130 V88\"/><path d=\"M210,76 V82 H160 V88\"/></g>\n  <rect x=\"90\" y=\"120\" width=\"80\" height=\"20\" rx=\"3\" fill=\"#022c22\" stroke=\"#34d399\"/><text x=\"130\" y=\"133\" fill=\"#6ee7b7\" text-anchor=\"middle\" font-size=\"5.5\">Target Voice</text>\n  <g stroke=\"#475569\"><path d=\"M130,108 V120\"/></g>\n</svg>",
      headingEn: 'Extract Content, Then Resynthesize', headingKn: 'Content ಪಡೆಯಿರಿ, ನಂತರ ಮತ್ತೆ ಸಂಶ್ಲೇಷಿಸಿ',
      captionEn: 'The source speaker\'s content is extracted into an explicit representation, then a synthesizer combines it with the target speaker\'s embedding.',
      captionKn: 'Source speaker ನ content ಅನ್ನೂ ಒಂದು ಸ್ಪಷ್ಟ ಪ್ರಾತಿನಿಧ್ಯಕ್ಕೆ ಪಡೆಯಲಾಗುತ್ತದೆ, ನಂತರ ಒಂದು synthesizer ಇದನ್ನೂ ಗುರಿ speaker ನ embedding ಜೊತೆ ಸಂಯೋಜಿಸುತ್ತದೆ.' } },

    { type: 'heading', data: { level: 'H2', textEn: 'Neural Codec-Based Voice Cloning', textKn: 'Neural Codec-ಆಧಾರಿತ Voice Cloning' } },
    { type: 'concept', data: {
      headingEn: 'Audio as Discrete Tokens', headingKn: 'ಡಿಸ್ಕ್ರೀಟ್ Tokens ಆಗಿ Audio',
      bodyEn: '• Modern systems increasingly represent audio using discrete codec tokens (SoundStream, EnCodec, DAC, SNAC -- the same codec family introduced for TTS vocoders in Module 130) rather than continuous mel spectrograms: audio -> neural audio codec -> discrete tokens -> generative model -> new tokens -> codec decoder -> waveform. This turns voice cloning into essentially the same kind of next-token-prediction problem that language models already solve well. VALL-E, VALL-E 2, NaturalSpeech 3, and VoiceBox are associated with this direction.',
      bodyKn: '• ಆಧುನಿಕ systems ಗಳು ನಿರಂತರ mel spectrograms ಗಳ ಬದಲಿಗೆ ಡಿಸ್ಕ್ರೀಟ್ codec tokens ಗಳನ್ನೂ (SoundStream, EnCodec, DAC, SNAC -- Module 130 ನಲ್ಲಿ TTS vocoders ಗಾಗಿ ಪರಿಚಯಿಸಿದ ಅದೇ codec ಕುಟುಂಬ) ಬಳಸಿ ಆಡಿಯೋ ಅನ್ನೂ ಹೆಚ್ಚುತ್ತಿರುವ ಪ್ರಮಾಣದಲ್ಲಿ ಪ್ರತಿನಿಧಿಸುತ್ತವೆ: audio -> neural audio codec -> discrete tokens -> generative model -> ಹೊಸ tokens -> codec decoder -> waveform. ಇದೂ voice cloning ಅನ್ನೂ language models ಗಳು ಈಗಾಗಲೇ ಚೆನ್ನಾಗಿ ಪರಿಹರಿಸುವ ಅದೇ ಬಗೆಯ next-token-prediction ಸಮಸ್ಯೆಯಾಗಿ ಬದಲಾಯಿಸುತ್ತದೆ. VALL-E, VALL-E 2, NaturalSpeech 3, ಮತ್ತು VoiceBox ಈ ದಿಕ್ಕಿಗೆ ಸಂಬಂಧಿಸಿವೆ.' } },
    { type: 'table', data: { captionEn: 'Three Major Voice Cloning/Conversion Approaches', captionKn: 'ಮೂರು ಪ್ರಮುಖ Voice Cloning/Conversion ವಿಧಾನಗಳು',
      rows: 'Approach|Main Idea|Examples\nRecognition-Synthesis|Extract content and resynthesize with target speaker|KNN-VC, Diff-HierVC\nDisentanglement|Separate content, speaker and prosody in latent space|AutoVC, VITS-VC\nNeural Codec|Generate discrete audio codec tokens|VALL-E, VoiceBox' } },
    { type: 'table', data: { captionEn: '2026 Model Comparison (Zero-Shot Cloning)', captionKn: '2026 Model ಹೋಲಿಕೆ (Zero-Shot Cloning)',
      rows: 'Model|Zero-Shot|SECS|WER|Parameters\nF5-TTS|Yes|0.72|2.1%|335M\nXTTS v2|Yes|0.65|3.5%|470M\nOpenVoice v2|Yes|0.70|2.8%|220M\nVALL-E 2|Yes|0.77|2.4%|370M\nVoiceBox|Yes|0.78|2.1%|330M' } },

    { type: 'heading', data: { level: 'H2', textEn: 'Ethics, Consent, and Watermarking', textKn: 'Ethics, Consent, ಮತ್ತು Watermarking' } },
    { type: 'concept', data: {
      headingEn: 'Real Applications, Real Risks', headingKn: 'ನಿಜ Applications, ನಿಜ ಅಪಾಯಗಳು',
      bodyEn: '• Legitimate uses: accessibility, assistive communication, audiobooks, dubbing, personalized TTS, voice restoration for people who have lost their natural voice. The same technology also enables impersonation, scam calls, unauthorized voice replicas, deepfakes, and fraud -- the exact same dual-use tension that runs through most of this course\'s security-adjacent topics.\n• A production cloning system should gate generation behind consent verification (reject if the reference voice\'s owner has not consented to this specific use), and watermark its output. A watermark embeds information (consent_id, timestamp, generation metadata) into the generated audio in a way designed to survive common transformations -- compression, re-encoding, streaming, light audio processing -- so a detector can later recover that metadata from audio found elsewhere. A consent record itself typically contains a speaker_id, consent_id, timestamp, authorized purpose, and a digital signature, verified before generation is even attempted.\n• Deepfake detection models (AASIST, RawNet2, Wav2Vec2-AASIST) provide an additional, independent safety layer: given an arbitrary audio clip, they classify it as real or synthetic, which is useful both for the cloning system\'s own safety pipeline and for downstream consumers (banks, call centers) trying to detect cloned voices they did not generate themselves.',
      bodyKn: '• ಕಾನೂನುಬದ್ಧ ಬಳಕೆಗಳು: accessibility, ಸಹಾಯಕ ಸಂವಹನ, audiobooks, dubbing, ವೈಯಕ್ತಿಕಗೊಳಿಸಿದ TTS, ತಮ್ಮ ಸ್ವಾಭಾವಿಕ ಧ್ವನಿ ಕಳೆದುಕೊಂಡ ಜನರಿಗೆ voice restoration. ಅದೇ ತಂತ್ರಜ್ಞಾನ impersonation, scam ಕರೆಗಳು, ಅನಧಿಕೃತ ಧ್ವನಿ ಪ್ರತಿಕೃತಿಗಳು, deepfakes, ಮತ್ತು ವಂಚನೆಯನ್ನೂ ಸಹ ಸಕ್ರಿಯಗೊಳಿಸುತ್ತದೆ -- ಈ ಕೋರ್ಸ್‌ನ ಹೆಚ್ಚಿನ ಭದ್ರತಾ-ಪಕ್ಕದ ವಿಷಯಗಳ ಮೂಲಕ ಚಲಿಸುವ ಅದೇ ನಿಖರ dual-use ಒತ್ತಡ.\n• ಒಂದು production cloning system consent ಪರಿಶೀಲನೆಯ ಹಿಂದೆ ಉತ್ಪಾದನೆ ಗೇಟ್ ಮಾಡಬೇಕು (reference ಧ್ವನಿಯ ಮಾಲೀಕರು ಈ ನಿರ್ದಿಷ್ಟ ಬಳಕೆಗೆ ಒಪ್ಪಿಗೆ ನೀಡದಿದ್ದರೆ ತಿರಸ್ಕರಿಸಿ), ಮತ್ತು ಇದರ output ಅನ್ನೂ watermark ಮಾಡಬೇಕು. ಒಂದು watermark ಮಾಹಿತಿಯನ್ನೂ (consent_id, timestamp, ಉತ್ಪಾದನಾ metadata) ಸಾಮಾನ್ಯ ರೂಪಾಂತರಗಳನ್ನೂ ಬದುಕುಳಿಯಲು ವಿನ್ಯಾಸಗೊಳಿಸಿದ ರೀತಿಯಲ್ಲಿ ಉತ್ಪಾದಿಸಿದ audio ಒಳಗೆ ಅಳವಡಿಸುತ್ತದೆ -- compression, re-encoding, streaming, ಹಗುರ audio ಪ್ರಕ್ರಿಯೆ -- ಆದ್ದರಿಂದ ಒಂದು detector ನಂತರ ಬೇರೆಡೆ ಕಂಡುಬಂದ audio ಇಂದ ಆ metadata ಮರುಪಡೆಯಬಹುದು. ಒಂದು consent ದಾಖಲೆ ಸ್ವತಃ ವಿಶಿಷ್ಟವಾಗಿ ಒಂದು speaker_id, consent_id, timestamp, ಅಧಿಕೃತ ಉದ್ದೇಶ, ಮತ್ತು ಒಂದು ಡಿಜಿಟಲ್ ಸಹಿ ಒಳಗೊಂಡಿದೆ, ಉತ್ಪಾದನೆ ಪ್ರಯತ್ನಿಸುವ ಮೊದಲೇ ಪರಿಶೀಲಿಸಲಾಗುತ್ತದೆ.\n• Deepfake detection models (AASIST, RawNet2, Wav2Vec2-AASIST) ಒಂದು ಹೆಚ್ಚುವರಿ, ಸ್ವತಂತ್ರ ಸುರಕ್ಷತಾ ಪದರ ಒದಗಿಸುತ್ತವೆ: ಒಂದು ಅನಿಯಂತ್ರಿತ audio clip ನೀಡಿದಾಗ, ಅವು ಇದನ್ನೂ ನಿಜ ಅಥವಾ synthetic ಎಂದು ವರ್ಗೀಕರಿಸುತ್ತವೆ, ಇದೂ cloning system ನ ಸ್ವಂತ ಸುರಕ್ಷತಾ pipeline ಗೆ ಮತ್ತು ಡೌನ್‌ಸ್ಟ್ರೀಮ್ ಗ್ರಾಹಕರಿಗೆ (ಬ್ಯಾಂಕುಗಳು, call centers) ಅವರು ಸ್ವತಃ ಉತ್ಪಾದಿಸದ ಕ್ಲೋನ್ ಮಾಡಿದ ಧ್ವನಿಗಳನ್ನೂ ಪತ್ತೆಹಚ್ಚಲು ಪ್ರಯತ್ನಿಸುತ್ತಾ ಎರಡಕ್ಕೂ ಉಪಯುಕ್ತ.' } },
    { type: 'diagram', data: {
      svgCode: "<svg viewBox=\"0 0 260 155\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"monospace\" font-size=\"6.3\">\n  <rect width=\"260\" height=\"155\" rx=\"8\" fill=\"#0f172a\"/>\n  <text x=\"130\" y=\"13\" fill=\"#94a3b8\" text-anchor=\"middle\" font-size=\"7.5\">Production Consent + Watermark Gate</text>\n  <rect x=\"75\" y=\"24\" width=\"110\" height=\"18\" rx=\"3\" fill=\"#1e293b\" stroke=\"#60a5fa\"/><text x=\"130\" y=\"36\" fill=\"#93c5fd\" text-anchor=\"middle\" font-size=\"5.3\">User Request</text>\n  <rect x=\"75\" y=\"48\" width=\"110\" height=\"18\" rx=\"3\" fill=\"#1e1b4b\" stroke=\"#a78bfa\"/><text x=\"130\" y=\"60\" fill=\"#c4b5fd\" text-anchor=\"middle\" font-size=\"5.3\">Consent Verification</text>\n  <rect x=\"5\" y=\"72\" width=\"55\" height=\"18\" rx=\"3\" fill=\"#450a0a\" stroke=\"#f87171\"/><text x=\"32\" y=\"84\" fill=\"#fca5a5\" text-anchor=\"middle\" font-size=\"5.3\">Reject</text>\n  <rect x=\"75\" y=\"72\" width=\"110\" height=\"18\" rx=\"3\" fill=\"#292524\" stroke=\"#f59e0b\"/><text x=\"130\" y=\"84\" fill=\"#fde68a\" text-anchor=\"middle\" font-size=\"5.3\">Voice Generation</text>\n  <rect x=\"75\" y=\"96\" width=\"110\" height=\"18\" rx=\"3\" fill=\"#022c22\" stroke=\"#34d399\"/><text x=\"130\" y=\"108\" fill=\"#6ee7b7\" text-anchor=\"middle\" font-size=\"5.3\">Watermark</text>\n  <rect x=\"75\" y=\"120\" width=\"110\" height=\"18\" rx=\"3\" fill=\"#022c22\" stroke=\"#34d399\"/><text x=\"130\" y=\"132\" fill=\"#6ee7b7\" text-anchor=\"middle\" font-size=\"5.3\">Output Audio</text>\n  <g stroke=\"#475569\"><path d=\"M130,42 V48\"/><path d=\"M130,66 V72\"/><path d=\"M75,81 H60\"/><path d=\"M130,90 V96\"/><path d=\"M130,114 V120\"/></g>\n</svg>",
      headingEn: 'Consent Before Generation, Watermark After', headingKn: 'ಉತ್ಪಾದನೆ ಮೊದಲು Consent, ನಂತರ Watermark',
      captionEn: 'A production cloning system checks consent before generating anything, and stamps every output with a traceable watermark before it ever leaves the system.',
      captionKn: 'ಒಂದು production cloning system ಏನನ್ನೂ ಉತ್ಪಾದಿಸುವ ಮೊದಲು consent ಪರಿಶೀಲಿಸುತ್ತದೆ, ಮತ್ತು ಇದೂ system ಇಂದ ಎಂದಿಗೂ ಹೊರಡುವ ಮೊದಲು ಪ್ರತಿ output ಅನ್ನೂ ಒಂದು ಪತ್ತೆಹಚ್ಚಬಹುದಾದ watermark ಜೊತೆ ಸ್ಟಾಂಪ್ ಮಾಡುತ್ತದೆ.' } },

    { type: 'heading', data: { level: 'H2', textEn: 'The Original Lesson Code', textKn: 'ನಿಖರ Lesson Code' } },
    { type: 'code', data: {
      filename: 'clone_pipeline.py',
      headingEn: 'Original Code — Recognition-Synthesis Pipeline (Presented as Pseudocode, as the Lesson Gives It)', headingKn: 'Original Code — Recognition-Synthesis Pipeline (ಲೆಸನ್ ನೀಡುವಂತೆ Pseudocode ಆಗಿ ಪ್ರಸ್ತುತಪಡಿಸಲಾಗಿದೆ)',
      descEn: 'target_embedder, tts_model, and vocoder are referenced but never defined anywhere in the lesson -- each represents an entire pretrained model (a speaker encoder, a TTS model, and a vocoder), not a small helper function that could reasonably be stubbed out. This is illustrative pipeline pseudocode connecting the concepts in this lesson, matching the exact structure of the zero-shot pipeline diagram above, not code with a real implementation behind it.',
      descKn: 'target_embedder, tts_model, ಮತ್ತು vocoder ಗಳನ್ನೂ ಉಲ್ಲೇಖಿಸಲಾಗಿದೆ ಆದರೆ ಲೆಸನ್‌ನಲ್ಲಿ ಎಲ್ಲಿಯೂ ಎಂದಿಗೂ ವ್ಯಾಖ್ಯಾನಿಸಲಾಗಿಲ್ಲ -- ಪ್ರತಿಯೊಂದೂ ಒಂದು ಸಂಪೂರ್ಣ ಪೂರ್ವತರಬೇತಿ ಪಡೆದ model ಪ್ರತಿನಿಧಿಸುತ್ತದೆ (ಒಂದು speaker encoder, ಒಂದು TTS model, ಮತ್ತು ಒಂದು vocoder), ಸಮಂಜಸವಾಗಿ stub ಮಾಡಬಹುದಾದ ಒಂದು ಚಿಕ್ಕ helper ಫಂಕ್ಷನ್ ಅಲ್ಲ. ಇದೂ ಈ lesson ನಲ್ಲಿನ ಪರಿಕಲ್ಪನೆಗಳನ್ನೂ ಸಂಪರ್ಕಿಸುವ ವಿವರಣಾತ್ಮಕ pipeline pseudocode, ಮೇಲಿನ zero-shot pipeline ರೇಖಾಚಿತ್ರದ ನಿಖರ ರಚನೆಗೆ ಹೊಂದಿಕೊಳ್ಳುತ್ತಾ, ಇದರ ಹಿಂದೆ ಒಂದು ನಿಜ ಅಳವಡಿಕೆ ಇರುವ code ಅಲ್ಲ.',
      code: "def clone_pipeline(ref_audio, text, target_embedder, tts_model):\n    speaker_emb = target_embedder.encode(ref_audio)\n    mel = tts_model(text, speaker=speaker_emb)\n    return vocoder(mel)" } },
    { type: 'code', data: {
      filename: 'f5_tts_clone_2.py',
      headingEn: 'Original Code — Zero-Shot Clone With F5-TTS (Genuinely Attempted a Second Time)', headingKn: 'Original Code — F5-TTS ಜೊತೆ Zero-Shot Clone (ಎರಡನೇ ಬಾರಿ ನಿಜವಾಗಿ ಪ್ರಯತ್ನಿಸಲಾಗಿದೆ)',
      descEn: 'The lesson\'s exact API call, with a different ref/gen text pair than the F5-TTS attempt in the TTS module. "rohit_5s.wav" was substituted with a real 5-second synthetic WAV (this course does not have access to a real human reference recording), genuinely fed to a real, previously-downloaded F5-TTS checkpoint.',
      descKn: 'ಲೆಸನ್‌ನ ನಿಖರ API ಕರೆ, TTS module ನಲ್ಲಿನ F5-TTS ಪ್ರಯತ್ನಕ್ಕಿಂತ ಬೇರೆ ref/gen ಪಠ್ಯ ಜೋಡಿಯೊಂದಿಗೆ. "rohit_5s.wav" ಅನ್ನೂ ಒಂದು ನಿಜ 5-ಸೆಕೆಂಡ್ synthetic WAV ಜೊತೆ ಬದಲಿಸಲಾಗಿದೆ (ಈ ಕೋರ್ಸ್‌ಗೆ ಒಂದು ನಿಜ ಮಾನವ reference ರೆಕಾರ್ಡಿಂಗ್‌ಗೆ ಪ್ರವೇಶವಿಲ್ಲ), ಒಂದು ನಿಜ, ಈ ಮೊದಲು-ಡೌನ್‌ಲೋಡ್ ಮಾಡಿದ F5-TTS checkpoint ಗೆ ನಿಜವಾಗಿ ಆಹಾರ ನೀಡಲಾಗಿದೆ.',
      code: "from f5_tts.api import F5TTS\n\ntts = F5TTS()\n\nwav, sr, spec = tts.infer(\n    ref_file=\"rohit_5s.wav\",       # substituted with a real synthetic 5s WAV\n    ref_text=\"The quick brown fox jumps over the lazy dog.\",\n    gen_text=\"Please add milk and bread to my list.\",\n)" } },
    { type: 'output', data: { output: "Download Vocos from huggingface charactr/vocos-mel-24khz\nmodel: .../SWivid--F5-TTS/.../F5TTS_v1_Base/model_1250000.safetensors\nloaded in 108.1 s\nConverting audio...\nUsing custom reference text...\nref_text   The quick brown fox jumps over the lazy dog." } },
    { type: 'concept', data: {
      headingEn: 'Reading the Verified Output — A Confirmed, Reproducible Finding', headingKn: 'ಪರಿಶೀಲಿಸಿದ Output ಓದುವುದು — ಒಂದು ದೃಢಪಡಿಸಿದ, ಪುನರುತ್ಪಾದಿಸಬಹುದಾದ ಶೋಧನೆ',
      bodyEn: '• This is the second independent, genuine attempt at F5-TTS zero-shot cloning in this course, using a different reference/generation text pair from the one in the TTS module. The result matches exactly: the real F5-TTS v1 Base checkpoint and the Vocos vocoder both load successfully (this time in 108.1s -- the load time has varied across the three attempts made so far: 133.2s, 61.9s, 108.1s, likely reflecting real variance in disk/network conditions rather than anything wrong with the setup), and calling infer() genuinely begins real work: it logs "Converting audio..." and correctly registers the custom reference text before the process runs out of available session time.\n• With two independent, reproducible attempts now landing at the identical point (model loads and begins real inference, but multi-step diffusion sampling does not finish within available CPU time), this is no longer a one-off anomaly -- it is a confirmed, honest characteristic of running F5-TTS on CPU-only hardware in this environment. The lesson\'s own emphasis that "the reference transcript must exactly match the reference audio" is itself something this environment cannot meaningfully test, since the substituted audio is a synthetic tone with no real speech content for any reference text to "match" -- a second, distinct limitation from the raw inference-time one, both disclosed honestly rather than glossed over.',
      bodyKn: '• ಇದೂ ಈ ಕೋರ್ಸ್‌ನಲ್ಲಿ F5-TTS zero-shot cloning ನ ಎರಡನೇ ಸ್ವತಂತ್ರ, ನಿಜ ಪ್ರಯತ್ನ, TTS module ನಲ್ಲಿನದಕ್ಕಿಂತ ಬೇರೆ reference/generation ಪಠ್ಯ ಜೋಡಿ ಬಳಸಿ. ಫಲಿತಾಂಶ ನಿಖರವಾಗಿ ಹೊಂದಿಕೊಳ್ಳುತ್ತದೆ: ನಿಜ F5-TTS v1 Base checkpoint ಮತ್ತು Vocos vocoder ಎರಡೂ ಯಶಸ್ವಿಯಾಗಿ ಲೋಡ್ ಆಗುತ್ತವೆ (ಈ ಬಾರಿ 108.1s ನಲ್ಲಿ -- ಇಲ್ಲಿಯವರೆಗೆ ಮಾಡಿದ ಮೂರು ಪ್ರಯತ್ನಗಳಾದ್ಯಂತ ಲೋಡ್ ಸಮಯ ಬದಲಾಗಿದೆ: 133.2s, 61.9s, 108.1s, ಬಹುಶಃ ಸೆಟಪ್‌ನಲ್ಲಿ ತಪ್ಪಾದ ಯಾವುದೂ ಇಲ್ಲದೆ disk/network ಪರಿಸ್ಥಿತಿಗಳಲ್ಲಿ ನಿಜ ವ್ಯತ್ಯಾಸ ಪ್ರತಿಬಿಂಬಿಸುತ್ತಾ), ಮತ್ತು infer() ಕರೆಯುವುದೂ ನಿಜ ಕೆಲಸ ನಿಜವಾಗಿ ಆರಂಭಿಸುತ್ತದೆ: ಇದೂ "Converting audio..." ಲಾಗ್ ಮಾಡುತ್ತದೆ ಮತ್ತು ಪ್ರಕ್ರಿಯೆ ಲಭ್ಯವಿರುವ session ಸಮಯ ಮೀರುವ ಮೊದಲು custom reference ಪಠ್ಯವನ್ನೂ ಸರಿಯಾಗಿ ನೋಂದಾಯಿಸುತ್ತದೆ.\n• ಈಗ ಅದೇ ಬಿಂದುವಿನಲ್ಲಿ ಇಳಿಯುವ ಎರಡು ಸ್ವತಂತ್ರ, ಪುನರುತ್ಪಾದಿಸಬಹುದಾದ ಪ್ರಯತ್ನಗಳೊಂದಿಗೆ (model ಲೋಡ್ ಆಗುತ್ತದೆ ಮತ್ತು ನಿಜ inference ಆರಂಭಿಸುತ್ತದೆ, ಆದರೆ ಬಹು-ಹಂತದ diffusion ಸ್ಯಾಂಪ್ಲಿಂಗ್ ಲಭ್ಯವಿರುವ CPU ಸಮಯದೊಳಗೆ ಮುಗಿಯುವುದಿಲ್ಲ), ಇದೂ ಇನ್ನು ಮುಂದೆ ಒಂದು ಒಂಟಿ ಆಕಸ್ಮಿಕ ಘಟನೆಯಲ್ಲ -- ಇದೂ ಈ environment ನಲ್ಲಿ CPU-ಮಾತ್ರ ಹಾರ್ಡ್‌ವೇರ್‌ನಲ್ಲಿ F5-TTS ಚಲಾಯಿಸುವ ಒಂದು ದೃಢಪಡಿಸಿದ, ಪ್ರಾಮಾಣಿಕ ಗುಣಲಕ್ಷಣ. "reference transcript reference audio ಗೆ ನಿಖರವಾಗಿ ಹೊಂದಿಕೆಯಾಗಬೇಕು" ಎಂಬ ಲೆಸನ್‌ನ ಸ್ವಂತ ಒತ್ತು ಸ್ವತಃ ಈ environment ಅರ್ಥಪೂರ್ಣವಾಗಿ ಪರೀಕ್ಷಿಸಲಾಗದ ಒಂದು ವಿಷಯ, ಬದಲಿ audio ಒಂದು synthetic ಟೋನ್ ಆಗಿರುವ ಕಾರಣ ಯಾವುದೇ reference ಪಠ್ಯಕ್ಕೆ "ಹೊಂದಿಕೊಳ್ಳಲು" ಯಾವುದೇ ನಿಜ ಭಾಷಣ ವಿಷಯವಿಲ್ಲದೆ -- ಕಚ್ಚಾ inference-ಸಮಯದ ಒಂದಕ್ಕಿಂತ ಎರಡನೇ, ಪ್ರತ್ಯೇಕ ಮಿತಿ, ಎರಡನ್ನೂ ಮರೆಮಾಚುವ ಬದಲಿಗೆ ಪ್ರಾಮಾಣಿಕವಾಗಿ ಬಹಿರಂಗಪಡಿಸಲಾಗಿದೆ.' } },

    { type: 'concept', data: {
      headingEn: 'Why AI Uses It', headingKn: 'AI ಇದನ್ನು ಏಕೆ ಬಳಸುತ್ತದೆ',
      bodyEn: '• The content/speaker/prosody decomposition is not just a teaching device -- it is the actual architectural choice every model in the comparison table makes differently: F5-TTS conditions a diffusion Transformer on a speaker embedding, VALL-E predicts speaker-conditioned codec tokens autoregressively, AutoVC disentangles everything inside one shared latent. Understanding the decomposition is what lets an engineer read an unfamiliar cloning paper\'s architecture diagram and immediately know which of the three families (recognition-synthesis, disentanglement, neural codec) it belongs to.\n• The now twice-reproduced F5-TTS finding (loads and begins real inference, but CPU-only diffusion sampling does not finish in available time) is a concrete, practical data point for anyone actually deploying F5-TTS: it explains precisely why production voice-cloning services run this class of model on GPU infrastructure, not CPU, and quantifies the real cost users of this course\'s content would face trying to self-host without one -- not "it\'s slow," but "it genuinely completed neither of two real attempts within a normal interactive session\'s time budget."\n• The consent-gate and watermarking diagrams exist because this is one of the few areas in this entire curriculum where the "Why AI Uses It" question is inseparable from "why AI must be constrained": the same speaker-embedding and diffusion-generation machinery covered in this lesson, without a consent gate and a watermark, is a complete, unrestricted voice-impersonation tool -- the safety infrastructure is not an add-on bolted onto voice cloning, it is what makes voice cloning a legitimate production feature rather than a fraud vector.',
      bodyKn: '• Content/speaker/prosody ವಿಘಟನೆ ಕೇವಲ ಒಂದು ಬೋಧನಾ ಸಾಧನವಲ್ಲ -- ಇದೂ ಹೋಲಿಕೆ ಟೇಬಲ್‌ನಲ್ಲಿ ಪ್ರತಿ model ಬೇರೆ ರೀತಿಯಲ್ಲಿ ಮಾಡುವ ನಿಜ architectural ಆಯ್ಕೆ: F5-TTS ಒಂದು speaker embedding ಮೇಲೆ ಒಂದು diffusion Transformer ಷರತ್ತುಬದ್ಧಗೊಳಿಸುತ್ತದೆ, VALL-E speaker-conditioned codec tokens ಗಳನ್ನೂ autoregressively ಊಹಿಸುತ್ತದೆ, AutoVC ಎಲ್ಲವನ್ನೂ ಒಂದು ಹಂಚಿಕೊಂಡ latent ಒಳಗೆ ಬೇರ್ಪಡಿಸುತ್ತದೆ. ವಿಘಟನೆ ಅರ್ಥಮಾಡಿಕೊಳ್ಳುವುದೂ ಒಬ್ಬ ಎಂಜಿನಿಯರ್‌ಗೆ ಒಂದು ಅಪರಿಚಿತ cloning ಪೇಪರ್‌ನ architecture ರೇಖಾಚಿತ್ರ ಓದಲು ಮತ್ತು ಇದೂ ಮೂರು ಕುಟುಂಬಗಳಲ್ಲಿ (recognition-synthesis, disentanglement, neural codec) ಯಾವುದಕ್ಕೆ ಸೇರಿದೆ ಎಂದು ತಕ್ಷಣ ತಿಳಿಯಲು ಬಿಡುತ್ತದೆ.\n• ಈಗ ಎರಡು ಬಾರಿ ಪುನರುತ್ಪಾದಿಸಿದ F5-TTS ಶೋಧನೆ (ಲೋಡ್ ಆಗುತ್ತದೆ ಮತ್ತು ನಿಜ inference ಆರಂಭಿಸುತ್ತದೆ, ಆದರೆ CPU-ಮಾತ್ರ diffusion ಸ್ಯಾಂಪ್ಲಿಂಗ್ ಲಭ್ಯವಿರುವ ಸಮಯದಲ್ಲಿ ಮುಗಿಯುವುದಿಲ್ಲ) F5-TTS ಅನ್ನೂ ವಾಸ್ತವವಾಗಿ deploy ಮಾಡುವ ಯಾರಿಗಾದರೂ ಒಂದು ಕಾಂಕ್ರೀಟ್, ಪ್ರಾಯೋಗಿಕ ಡೇಟಾ ಬಿಂದು: ಇದೂ production voice-cloning ಸೇವೆಗಳು ಈ ವರ್ಗದ model ಅನ್ನೂ CPU ಅಲ್ಲ, GPU ಮೂಲಸೌಕರ್ಯದ ಮೇಲೆ ಏಕೆ ಚಲಾಯಿಸುತ್ತವೆ ಎಂದು ನಿಖರವಾಗಿ ವಿವರಿಸುತ್ತದೆ, ಮತ್ತು ಒಂದಿಲ್ಲದೆ ಸ್ವಯಂ-ಹೋಸ್ಟ್ ಮಾಡಲು ಪ್ರಯತ್ನಿಸುವ ಈ ಕೋರ್ಸ್‌ನ ವಿಷಯದ ಬಳಕೆದಾರರು ಎದುರಿಸುವ ನಿಜ ವೆಚ್ಚವನ್ನೂ ಪ್ರಮಾಣೀಕರಿಸುತ್ತದೆ -- "ಇದೂ ನಿಧಾನ" ಅಲ್ಲ, "ಒಂದು ಸಾಮಾನ್ಯ ಸಂವಾದಾತ್ಮಕ session ನ ಸಮಯ ಬಜೆಟ್ ಒಳಗೆ ಎರಡು ನಿಜ ಪ್ರಯತ್ನಗಳಲ್ಲಿ ಯಾವುದೂ ನಿಜವಾಗಿ ಪೂರ್ಣಗೊಂಡಿಲ್ಲ."\n• Consent-gate ಮತ್ತು watermarking ರೇಖಾಚಿತ್ರಗಳು ಅಸ್ತಿತ್ವದಲ್ಲಿವೆ ಏಕೆಂದರೆ ಇದೂ ಈ ಸಂಪೂರ್ಣ ಪಠ್ಯಕ್ರಮದಲ್ಲಿ "AI ಇದನ್ನು ಏಕೆ ಬಳಸುತ್ತದೆ" ಪ್ರಶ್ನೆ "AI ಅನ್ನೂ ಏಕೆ ನಿರ್ಬಂಧಿಸಬೇಕು" ಇಂದ ಬೇರ್ಪಡಿಸಲಾಗದ ಕೆಲವು ಪ್ರದೇಶಗಳಲ್ಲಿ ಒಂದು: ಈ lesson ನಲ್ಲಿ ಒಳಗೊಂಡಿರುವ ಅದೇ speaker-embedding ಮತ್ತು diffusion-generation ಯಂತ್ರೋಪಕರಣ, ಒಂದು consent gate ಮತ್ತು ಒಂದು watermark ಇಲ್ಲದೆ, ಒಂದು ಸಂಪೂರ್ಣ, ಅನಿಯಂತ್ರಿತ voice-impersonation ಟೂಲ್ -- ಸುರಕ್ಷತಾ ಮೂಲಸೌಕರ್ಯ voice cloning ಮೇಲೆ ಬೋಲ್ಟ್ ಮಾಡಿದ ಒಂದು add-on ಅಲ್ಲ, ಇದೂ voice cloning ಅನ್ನೂ ಒಂದು ವಂಚನೆ ವಾಹಕಕ್ಕಿಂತ ಒಂದು ಕಾನೂನುಬದ್ಧ production feature ಮಾಡುವುದೂ.' } },

    { type: 'concept', data: {
      headingEn: 'Key Takeaways', headingKn: 'ಮುಖ್ಯ ಅಂಶಗಳು',
      bodyEn: '• Voice cloning (text + reference -> new speech in that voice) and voice conversion (source speech + target voice -> same content, different speaker) are inverse-shaped problems built on the same content/speaker/prosody decomposition.\n• Zero-shot cloning needs only ~5 seconds of reference audio and a speaker encoder; few-shot cloning uses 5-30 minutes and can fine-tune/adapt the base model for measurably better fidelity.\n• Recognition-synthesis (explicit content extraction, e.g. KNN-VC), disentanglement (implicit separation in a shared latent, e.g. AutoVC), and neural codec-based generation (discrete tokens, e.g. VALL-E) are the three major architectural families -- verified conceptually against the models each is associated with.\n• Speaker embeddings here are the exact same tool as Module 129\'s speaker recognition embeddings, just used for generation-conditioning rather than verification -- and inherit the same real limitation that low-quality/non-human reference audio produces poor embeddings.\n• Production systems require a consent gate before generation and a watermark on every output, plus independent deepfake detection as a safety layer -- not optional extras, but what separates a legitimate cloning feature from an unrestricted impersonation tool.\n• A second, independent, genuine attempt at F5-TTS zero-shot cloning reproduced the exact same result as the first: the model downloads and loads correctly and begins real inference, but multi-step diffusion sampling has now failed to complete twice within this CPU-only environment\'s available time -- a confirmed, honest characteristic, not a one-off failure.',
      bodyKn: '• Voice cloning (ಪಠ್ಯ + reference -> ಆ ಧ್ವನಿಯಲ್ಲಿ ಹೊಸ ಭಾಷಣ) ಮತ್ತು voice conversion (source ಭಾಷಣ + ಗುರಿ ಧ್ವನಿ -> ಅದೇ content, ಬೇರೆ speaker) ಅದೇ content/speaker/prosody ವಿಘಟನೆಯ ಮೇಲೆ ನಿರ್ಮಿಸಿದ ವಿಲೋಮ-ಆಕಾರದ ಸಮಸ್ಯೆಗಳು.\n• Zero-shot cloning ಗೆ ಕೇವಲ ~5 ಸೆಕೆಂಡುಗಳ reference audio ಮತ್ತು ಒಂದು speaker encoder ಅಗತ್ಯ; few-shot cloning 5-30 ನಿಮಿಷಗಳನ್ನೂ ಬಳಸುತ್ತದೆ ಮತ್ತು ಅಳೆಯಬಹುದಾದ ಉತ್ತಮ ನಿಷ್ಠೆಗಾಗಿ base model ಅನ್ನೂ fine-tune/ಅಳವಡಿಸಬಹುದು.\n• Recognition-synthesis (ಸ್ಪಷ್ಟ content extraction, ಉದಾ. KNN-VC), disentanglement (ಒಂದು ಹಂಚಿಕೊಂಡ latent ನಲ್ಲಿ ಸೂಚ್ಯ ಪ್ರತ್ಯೇಕತೆ, ಉದಾ. AutoVC), ಮತ್ತು neural codec-ಆಧಾರಿತ ಉತ್ಪಾದನೆ (ಡಿಸ್ಕ್ರೀಟ್ tokens, ಉದಾ. VALL-E) ಮೂರು ಪ್ರಮುಖ architectural ಕುಟುಂಬಗಳು -- ಪ್ರತಿಯೊಂದೂ ಸಂಬಂಧಿಸಿದ models ಗಳ ವಿರುದ್ಧ ಪರಿಕಲ್ಪನಾತ್ಮಕವಾಗಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ.\n• ಇಲ್ಲಿ Speaker embeddings ಗಳು Module 129 ರ speaker recognition embeddings ಗಳ ಅದೇ ಟೂಲ್, ಕೇವಲ verification ಬದಲಿಗೆ generation-conditioning ಗಾಗಿ ಬಳಸಲಾಗಿದೆ -- ಮತ್ತು ಕಳಪೆ-ಗುಣಮಟ್ಟದ/ಮಾನವ-ಅಲ್ಲದ reference audio ಕಳಪೆ embeddings ಗಳನ್ನೂ ಉತ್ಪಾದಿಸುತ್ತದೆ ಎಂಬ ಅದೇ ನಿಜ ಮಿತಿ ಆನುವಂಶಿಕವಾಗಿ ಪಡೆಯುತ್ತದೆ.\n• Production systems ಗಳಿಗೆ ಉತ್ಪಾದನೆ ಮೊದಲು ಒಂದು consent gate ಮತ್ತು ಪ್ರತಿ output ಮೇಲೆ ಒಂದು watermark ಅಗತ್ಯ, ಜೊತೆಗೆ ಒಂದು ಸುರಕ್ಷತಾ ಪದರವಾಗಿ ಸ್ವತಂತ್ರ deepfake detection -- ಐಚ್ಛಿಕ ಹೆಚ್ಚುವರಿಗಳಲ್ಲ, ಆದರೆ ಒಂದು ಕಾನೂನುಬದ್ಧ cloning feature ಅನ್ನೂ ಒಂದು ಅನಿಯಂತ್ರಿತ impersonation ಟೂಲ್ ಇಂದ ಪ್ರತ್ಯೇಕಿಸುವುದೂ.\n• F5-TTS zero-shot cloning ನ ಎರಡನೇ, ಸ್ವತಂತ್ರ, ನಿಜ ಪ್ರಯತ್ನ ಮೊದಲಿನ ಅದೇ ನಿಖರ ಫಲಿತಾಂಶವನ್ನೂ ಪುನರುತ್ಪಾದಿಸಿತು: model ಸರಿಯಾಗಿ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ ಲೋಡ್ ಆಗುತ್ತದೆ ಮತ್ತು ನಿಜ inference ಆರಂಭಿಸುತ್ತದೆ, ಆದರೆ ಬಹು-ಹಂತದ diffusion ಸ್ಯಾಂಪ್ಲಿಂಗ್ ಈಗ ಈ CPU-ಮಾತ್ರ environment ನ ಲಭ್ಯವಿರುವ ಸಮಯದೊಳಗೆ ಎರಡು ಬಾರಿ ಪೂರ್ಣಗೊಳ್ಳಲು ವಿಫಲಗೊಂಡಿದೆ -- ಒಂದು ದೃಢಪಡಿಸಿದ, ಪ್ರಾಮಾಣಿಕ ಗುಣಲಕ್ಷಣ, ಒಂದು ಒಂಟಿ ವೈಫಲ್ಯವಲ್ಲ.' } },

    { type: 'quiz', data: { questions: [
      { q: 'What is the key difference between voice cloning and voice conversion?', qKn: 'Voice cloning ಮತ್ತು voice conversion ನಡುವಿನ ಮುಖ್ಯ ವ್ಯತ್ಯಾಸ ಏನು?',
        opts: ['They are identical tasks with different names', 'Cloning takes text + a reference voice to generate new speech (a TTS problem); conversion takes existing source speech + a target voice to change who appears to be speaking it, keeping the content fixed (a speech-to-speech problem)', 'Cloning only works for English; conversion works for all languages', 'Conversion requires text input while cloning does not'], correct: 1,
        optsKn: ['ಅವು ಬೇರೆ ಹೆಸರುಗಳೊಂದಿಗೆ ಒಂದೇ ಕಾರ್ಯಗಳು', 'Cloning ಪಠ್ಯ + ಒಂದು reference ಧ್ವನಿ ತೆಗೆದುಕೊಂಡು ಹೊಸ ಭಾಷಣ ಉತ್ಪಾದಿಸುತ್ತದೆ (ಒಂದು TTS ಸಮಸ್ಯೆ); conversion ಅಸ್ತಿತ್ವದಲ್ಲಿರುವ source ಭಾಷಣ + ಒಂದು ಗುರಿ ಧ್ವನಿ ತೆಗೆದುಕೊಂಡು ಯಾರು ಮಾತನಾಡುತ್ತಿದ್ದಾರೆ ಎಂದು ಕಾಣಿಸುತ್ತದೆ ಎಂಬುದನ್ನೂ ಬದಲಾಯಿಸುತ್ತದೆ, content ಸ್ಥಿರವಾಗಿ ಇರಿಸುತ್ತಾ (ಒಂದು speech-to-speech ಸಮಸ್ಯೆ)', 'Cloning ಕೇವಲ ಇಂಗ್ಲಿಷ್‌ಗೆ ಮಾತ್ರ ಕೆಲಸ ಮಾಡುತ್ತದೆ; conversion ಎಲ್ಲಾ ಭಾಷೆಗಳಿಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ', 'Conversion ಗೆ ಪಠ್ಯ input ಅಗತ್ಯ ಆದರೆ cloning ಗೆ ಇಲ್ಲ'] },
      { q: 'What are the three factors every voice cloning/conversion system separates and recombines?', qKn: 'ಪ್ರತಿ voice cloning/conversion system ಪ್ರತ್ಯೇಕಿಸಿ ಮತ್ತೆ ಸಂಯೋಜಿಸುವ ಮೂರು ಅಂಶಗಳು ಯಾವುವು?',
        opts: ['Volume, pitch, and tempo', 'Content (what was said), Speaker (who said it), Prosody (how it was said)', 'Sample rate, bit depth, and channel count', 'Text, audio, and video'], correct: 1,
        optsKn: ['Volume, pitch, ಮತ್ತು tempo', 'Content (ಏನನ್ನೂ ಹೇಳಲಾಗಿದೆ), Speaker (ಯಾರು ಹೇಳಿದರು), Prosody (ಹೇಗೆ ಹೇಳಲಾಗಿದೆ)', 'Sample rate, bit depth, ಮತ್ತು channel count', 'ಪಠ್ಯ, audio, ಮತ್ತು ವೀಡಿಯೋ'] },
      { q: 'What distinguishes zero-shot from few-shot voice cloning?', qKn: 'Zero-shot ಅನ್ನೂ few-shot voice cloning ಇಂದ ಏನು ಪ್ರತ್ಯೇಕಿಸುತ್ತದೆ?',
        opts: ['Zero-shot requires more reference audio than few-shot', 'Zero-shot clones from ~5 seconds of reference audio with no speaker-specific retraining; few-shot uses 5-30 minutes and can fine-tune/adapt the model for better fidelity', 'They are the same technique with different marketing names', 'Few-shot only works for languages with no writing system'], correct: 1,
        optsKn: ['Zero-shot ಗೆ few-shot ಗಿಂತ ಹೆಚ್ಚಿನ reference audio ಅಗತ್ಯ', 'Zero-shot ~5 ಸೆಕೆಂಡುಗಳ reference audio ಇಂದ ಯಾವುದೇ speaker-ನಿರ್ದಿಷ್ಟ ಮರುತರಬೇತಿ ಇಲ್ಲದೆ ಕ್ಲೋನ್ ಮಾಡುತ್ತದೆ; few-shot 5-30 ನಿಮಿಷಗಳನ್ನೂ ಬಳಸುತ್ತದೆ ಮತ್ತು ಉತ್ತಮ ನಿಷ್ಠೆಗಾಗಿ model ಅನ್ನೂ fine-tune/ಅಳವಡಿಸಬಹುದು', 'ಅವು ಬೇರೆ ಮಾರ್ಕೆಟಿಂಗ್ ಹೆಸರುಗಳೊಂದಿಗೆ ಅದೇ ತಂತ್ರ', 'Few-shot ಕೇವಲ ಯಾವುದೇ ಬರವಣಿಗೆ ವ್ಯವಸ್ಥೆ ಇಲ್ಲದ ಭಾಷೆಗಳಿಗೆ ಮಾತ್ರ ಕೆಲಸ ಮಾಡುತ್ತದೆ'] },
      { q: 'How does recognition-synthesis voice conversion differ from disentanglement-based voice conversion?', qKn: 'Recognition-synthesis voice conversion disentanglement-ಆಧಾರಿತ voice conversion ಇಂದ ಹೇಗೆ ಭಿನ್ನ?',
        opts: ['They are exactly the same approach', 'Recognition-synthesis extracts an explicit content representation (e.g. phonemes, PPGs) then resynthesizes it with a target speaker; disentanglement implicitly separates content/speaker/prosody within one shared latent space, without an explicit intermediate representation', 'Disentanglement always requires text input; recognition-synthesis never does', 'Recognition-synthesis only works for voice cloning, not conversion'], correct: 1,
        optsKn: ['ಅವು ನಿಖರವಾಗಿ ಅದೇ ವಿಧಾನ', 'Recognition-synthesis ಒಂದು ಸ್ಪಷ್ಟ content ಪ್ರಾತಿನಿಧ್ಯ ಪಡೆಯುತ್ತದೆ (ಉದಾ. phonemes, PPGs) ನಂತರ ಇದನ್ನೂ ಒಂದು ಗುರಿ speaker ಜೊತೆ ಮತ್ತೆ ಸಂಶ್ಲೇಷಿಸುತ್ತದೆ; disentanglement ಒಂದು ಸ್ಪಷ್ಟ ಮಧ್ಯಂತರ ಪ್ರಾತಿನಿಧ್ಯವಿಲ್ಲದೆ, ಒಂದು ಹಂಚಿಕೊಂಡ latent space ಒಳಗೆ content/speaker/prosody ಅನ್ನೂ ಸೂಚ್ಯವಾಗಿ ಪ್ರತ್ಯೇಕಿಸುತ್ತದೆ', 'Disentanglement ಗೆ ಯಾವಾಗಲೂ ಪಠ್ಯ input ಅಗತ್ಯ; recognition-synthesis ಗೆ ಎಂದಿಗೂ ಇಲ್ಲ', 'Recognition-synthesis ಕೇವಲ voice cloning ಗೆ ಮಾತ್ರ ಕೆಲಸ ಮಾಡುತ್ತದೆ, conversion ಗಲ್ಲ'] },
      { q: 'Verified in this lesson: what happened when the F5-TTS zero-shot cloning code was genuinely attempted a second time, with different reference/generation text?', qKn: 'ಈ lesson ನಲ್ಲಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ: F5-TTS zero-shot cloning code ಅನ್ನೂ ಬೇರೆ reference/generation ಪಠ್ಯದೊಂದಿಗೆ ಎರಡನೇ ಬಾರಿ ನಿಜವಾಗಿ ಪ್ರಯತ್ನಿಸಿದಾಗ ಏನಾಯಿತು?',
        opts: ['It failed to install entirely, a new finding', 'It reproduced the exact same result as the first attempt: the model loaded successfully and began real inference (audio conversion, reference text registration), but full diffusion generation again did not finish within available CPU time', 'It completed successfully this time and produced a real cloned voice', 'The reference text caused a crash due to a length mismatch'], correct: 1,
        optsKn: ['ಇದೂ ಸಂಪೂರ್ಣವಾಗಿ ಸ್ಥಾಪಿಸಲು ವಿಫಲಗೊಂಡಿತು, ಒಂದು ಹೊಸ ಶೋಧನೆ', 'ಇದೂ ಮೊದಲ ಪ್ರಯತ್ನದ ಅದೇ ನಿಖರ ಫಲಿತಾಂಶವನ್ನೂ ಪುನರುತ್ಪಾದಿಸಿತು: model ಯಶಸ್ವಿಯಾಗಿ ಲೋಡ್ ಆಯಿತು ಮತ್ತು ನಿಜ inference ಆರಂಭಿಸಿತು (audio conversion, reference text ನೋಂದಣಿ), ಆದರೆ ಪೂರ್ಣ diffusion ಉತ್ಪಾದನೆ ಮತ್ತೆ ಲಭ್ಯವಿರುವ CPU ಸಮಯದೊಳಗೆ ಮುಗಿಯಲಿಲ್ಲ', 'ಇದೂ ಈ ಬಾರಿ ಯಶಸ್ವಿಯಾಗಿ ಪೂರ್ಣಗೊಂಡಿತು ಮತ್ತು ಒಂದು ನಿಜ ಕ್ಲೋನ್ ಮಾಡಿದ ಧ್ವನಿ ಉತ್ಪಾದಿಸಿತು', 'Reference ಪಠ್ಯ ಒಂದು ಉದ್ದ ಅಸಾಮರಸ್ಯದಿಂದ ಒಂದು crash ಗೆ ಕಾರಣವಾಯಿತು'] },
      { q: 'Why does a production voice cloning system need a consent gate and watermarking, not just the generation model itself?', qKn: 'ಒಂದು production voice cloning system ಗೆ ಕೇವಲ ಉತ್ಪಾದನಾ model ಸ್ವತಃ ಅಲ್ಲ, ಒಂದು consent gate ಮತ್ತು watermarking ಏಕೆ ಅಗತ್ಯ?',
        opts: ['They are optional features that only improve audio quality', 'Without them, the same speaker-embedding and generation machinery becomes an unrestricted voice-impersonation tool -- consent verification and traceable watermarks are what make cloning a legitimate feature rather than a fraud vector', 'Consent gates are only required in the European Union', 'Watermarking is purely for copyright licensing, unrelated to safety'], correct: 1,
        optsKn: ['ಅವು ಕೇವಲ audio ಗುಣಮಟ್ಟ ಸುಧಾರಿಸುವ ಐಚ್ಛಿಕ features ಗಳು', 'ಅವು ಇಲ್ಲದೆ, ಅದೇ speaker-embedding ಮತ್ತು ಉತ್ಪಾದನಾ ಯಂತ್ರೋಪಕರಣ ಒಂದು ಅನಿಯಂತ್ರಿತ voice-impersonation ಟೂಲ್ ಆಗುತ್ತದೆ -- consent ಪರಿಶೀಲನೆ ಮತ್ತು ಪತ್ತೆಹಚ್ಚಬಹುದಾದ watermarks ಗಳು cloning ಅನ್ನೂ ಒಂದು ವಂಚನೆ ವಾಹಕಕ್ಕಿಂತ ಒಂದು ಕಾನೂನುಬದ್ಧ feature ಮಾಡುತ್ತವೆ', 'Consent gates ಕೇವಲ European Union ನಲ್ಲಿ ಮಾತ್ರ ಅಗತ್ಯ', 'Watermarking ಕೇವಲ ಕೃತಿಸ್ವಾಮ್ಯ ಪರವಾನಗಿಗಾಗಿ ಮಾತ್ರ, ಸುರಕ್ಷತೆಗೆ ಸಂಬಂಧಿಸಿಲ್ಲ'] },
    ] } },
  ],
};
