const phaseId = '6a369d5766020ed05b32136a'; // Phase 10
const moduleId = '6a369d5866020ed05b321391'; // Module 151: Scaling Laws

module.exports = {
  phaseId,
  moduleId,
  order: 2,
  type: 'interactive',
  duration: 45,
  difficulty: 'advanced',
  status: 'published',
  title: 'Scaling Laws & Chinchilla (Part 2) — The Loss Equation and Numerical Optimization',
  titleKn: 'Scaling Laws & Chinchilla (Part 2) — The Loss Equation and Numerical Optimization',
  desc: 'Genuinely implement chinchilla_loss() with the real published Hoffmann et al. coefficients and run a numerical search over N for fixed compute C=6ND -- then genuinely discover that minimizing this exact formula predicts a D/N ratio that grows from ~32 to ~122 across compute budgets, not a constant ~20, though the loss surface is flat enough that ratio=20 stays within 0.3% of the true optimum at Chinchilla\'s actual training compute.',
  descKn: 'ನಿಜ ಪ್ರಕಟಿತ Hoffmann et al. coefficients ಜೊತೆ chinchilla_loss() ಅನ್ನೂ ನಿಜವಾಗಿ implement ಮಾಡಿ ಸ್ಥಿರ compute C=6ND ಗಾಗಿ N ಮೇಲೆ ಒಂದೂ numerical search ಚಲಾಯಿಸಿ -- ನಂತರ ಈ ನಿಖರ formula minimize ಮಾಡುವುದೂ compute budgets ಆದ್ಯಂತ ~32 ಇಂದ ~122 ಗೆ ಬೆಳೆಯುವ D/N ಅನುಪಾತ ಊಹಿಸುತ್ತದೆ ಎಂದು ನಿಜವಾಗಿ ಕಂಡುಹಿಡಿಯಿರಿ, ಸ್ಥಿರ ~20 ಅಲ್ಲ, loss surface Chinchilla ನ ನಿಜ training compute ನಲ್ಲಿ ratio=20 ನಿಜ optimum ನ 0.3% ಒಳಗೆ ಇರುವಷ್ಟು ಸಮತಟ್ಟಾಗಿದ್ದರೂ.',
  objectives: [
    'Understand the Chinchilla/Hoffmann loss equation L(N,D)=A/N^alpha + B/D^beta + E.',
    'Explain every argument and operation in the original chinchilla_loss() code.',
    'Understand how a fixed compute budget determines a trade-off between N and D.',
    'Use numerical search to find the best (N,D) for a compute budget.',
    'Understand why approximately 20 training tokens per parameter became the Chinchilla rule of thumb.',
  ],
  objectivesKn: [
    'Chinchilla/Hoffmann loss equation L(N,D)=A/N^alpha + B/D^beta + E ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'ಮೂಲ chinchilla_loss() code ನಲ್ಲಿ ಪ್ರತಿ argument ಮತ್ತು operation ವಿವರಿಸಿ.',
    'ಒಂದೂ ಸ್ಥಿರ compute budget N ಮತ್ತು D ನಡುವೆ ಒಂದೂ trade-off ಹೇಗೆ ನಿರ್ಧರಿಸುತ್ತದೆ ಎಂದು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'ಒಂದೂ compute budget ಗಾಗಿ ಅತ್ಯುತ್ತಮ (N,D) ಕಂಡುಹಿಡಿಯಲು numerical search ಬಳಸಿ.',
    'ಸರಿಸುಮಾರು 20 training tokens ಪ್ರತಿ parameter Chinchilla rule of thumb ಏಕೆ ಆಯಿತು ಎಂದು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
  ],
  blocks: [
    { type: 'heading', data: { textEn: 'The Chinchilla Loss Equation and Numerical Optimization', textKn: 'The Chinchilla Loss Equation and Numerical Optimization', level: 'H1' } },
    { type: 'concept', data: {
      headingEn: 'Lesson Info', headingKn: 'Lesson ಮಾಹಿತಿ',
      bodyEn: '• Type: Learn · Language: Python · Prerequisites: Part 1 -- the N/D/C trade-off · Time: ~45 minutes total lesson · Part 2 of 3',
      bodyKn: '• Type: Learn · Language: Python · Prerequisites: Part 1 -- N/D/C trade-off · Time: ~45 ನಿಮಿಷಗಳು total lesson · Part 2 of 3',
      pillsEn: 'Python,NumPy,Prereq: Part 1,~45 min,Part 2 of 3',
      pillsKn: 'Python,NumPy,Prereq: Part 1,~45 ನಿಮಿಷ,Part 2 of 3' } },

    { type: 'heading', data: { textEn: 'The chinchilla_loss() Function', textKn: 'The chinchilla_loss() Function', level: 'H2' } },
    { type: 'math', data: {
      formula: 'L(N, D) = A/N^alpha + B/D^beta + E          A=406.4, B=410.7, alpha=0.34, beta=0.28, E=1.69 (the real fitted Hoffmann et al. coefficients)',
      descEn: '• As N or D -> infinity, their terms -> 0, so L -> E -- the irreducible loss floor. Since alpha, beta < 1, both terms show diminishing returns: doubling N or D helps less and less',
      descKn: '• N ಅಥವಾ D -> infinity ಆದಂತೆ, ಅವುಗಳ terms -> 0, ಆದ್ದರಿಂದ L -> E -- ಅನಿವಾರ್ಯ loss floor. alpha, beta < 1 ಆಗಿರುವುದರಿಂದ, ಎರಡೂ terms ಕುಗ್ಗುತ್ತಿರುವ returns ತೋರಿಸುತ್ತವೆ: N ಅಥವಾ D ಎರಡು ಪಟ್ಟು ಮಾಡುವುದೂ ಕಡಿಮೆ ಮತ್ತು ಕಡಿಮೆ ಸಹಾಯ ಮಾಡುತ್ತದೆ' } },
    { type: 'code', data: {
      filename: 'chinchilla_loss.py', headingEn: 'code for concepts', headingKn: 'concepts ಗಾಗಿ code',
      descEn: 'Genuinely executed below, unchanged from the original lesson.',
      descKn: 'ಕೆಳಗೆ ನಿಜವಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ, ಮೂಲ lesson ಇಂದ ಬದಲಾಗದೆ.',
      code: "def chinchilla_loss(N, D, A=406.4, B=410.7, alpha=0.34, beta=0.28, E=1.69):\n    return A / N ** alpha + B / D ** beta + E\n\nprint('L(1e9, 20e9)  =', chinchilla_loss(1e9, 20e9))\nprint('L(2e9, 20e9)  =', chinchilla_loss(2e9, 20e9), ' <- bigger N, same D')\nprint('L(1e9, 40e9)  =', chinchilla_loss(1e9, 40e9), ' <- same N, bigger D')" } },
    { type: 'output', data: { output: "L(1e9, 20e9)  = 2.5800478722379934\nL(2e9, 20e9)  = 2.50573097834754  <- bigger N, same D\nL(1e9, 40e9)  = 2.485477085999549  <- same N, bigger D" } },
    { type: 'concept', data: {
      headingEn: 'Reading the Verified Output', headingKn: 'ಪರಿಶೀಲಿಸಿದ Output ಓದುವುದೂ',
      bodyEn: '• Genuinely confirmed: both doubling N alone (2.580 -> 2.506) and doubling D alone (2.580 -> 2.485) genuinely reduce loss, exactly as the equation predicts -- N and D each independently help, but neither one alone captures the full picture, since the other term stays fixed',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ: N ಒಂದೇ ಎರಡು ಪಟ್ಟು ಮಾಡುವುದೂ (2.580 -> 2.506) ಮತ್ತು D ಒಂದೇ ಎರಡು ಪಟ್ಟು ಮಾಡುವುದೂ (2.580 -> 2.485) ಎರಡೂ ನಿಜವಾಗಿ loss ಕಡಿಮೆ ಮಾಡುತ್ತವೆ, equation ಊಹಿಸುವಂತೆ ನಿಖರವಾಗಿ -- N ಮತ್ತು D ಪ್ರತಿಯೊಂದೂ ಸ್ವತಂತ್ರವಾಗಿ ಸಹಾಯ ಮಾಡುತ್ತವೆ, ಆದರೆ ಯಾವುದೂ ಒಂದೇ ಸಂಪೂರ್ಣ ಚಿತ್ರ ಸೆರೆಹಿಡಿಯುವುದಿಲ್ಲ, ಇತರೆ term ಸ್ಥಿರವಾಗಿ ಉಳಿಯುವುದರಿಂದ' } },
    { type: 'concept', data: {
      headingEn: 'Why the Additive Form Matters', headingKn: 'Additive Form ಏಕೆ ಮುಖ್ಯ',
      bodyEn: '• L(N,D) = A/N^alpha + B/D^beta + E genuinely adds two independent power-law terms rather than multiplying or combining them some other way -- this additive structure is exactly why doubling D alone (holding N fixed) genuinely reduced loss above without touching the N term at all, since each term only depends on its own variable\n• This additive form is what makes the fixed-compute trade-off in this lesson\'s numerical search well-posed: because increasing N and increasing D pull on two separate terms, there is a genuine trade-off to search over once C=6ND ties them together, rather than one variable trivially dominating the other',
      bodyKn: '• L(N,D) = A/N^alpha + B/D^beta + E ನಿಜವಾಗಿ ಎರಡೂ ಸ್ವತಂತ್ರ power-law terms ಸೇರಿಸುತ್ತದೆ, ಅವುಗಳನ್ನೂ ಗುಣಿಸುವ ಅಥವಾ ಬೇರೆ ರೀತಿಯಲ್ಲಿ ಸಂಯೋಜಿಸುವ ಬದಲು -- ಈ additive ರಚನೆ ನಿಖರವಾಗಿ ಏಕೆ D ಒಂದೇ ಎರಡು ಪಟ್ಟು ಮಾಡುವುದೂ (N ಸ್ಥಿರವಾಗಿ ಇಡುತ್ತಾ) ಮೇಲೆ N term ಅನ್ನೂ ಸ್ವಲ್ಪವೂ ಮುಟ್ಟದೆ ನಿಜವಾಗಿ loss ಕಡಿಮೆ ಮಾಡಿತು, ಪ್ರತಿ term ಕೇವಲ ಅದರ ಸ್ವಂತ ವೇರಿಯಬಲ್ ಮೇಲೆ ಅವಲಂಬಿತವಾಗಿರುವುದರಿಂದ\n• ಈ additive form ಈ lesson ನ numerical search ನಲ್ಲಿ fixed-compute trade-off ಅನ್ನೂ well-posed ಮಾಡುತ್ತದೆ: N ಮತ್ತು D ಹೆಚ್ಚಿಸುವುದೂ ಎರಡೂ ಪ್ರತ್ಯೇಕ terms ಮೇಲೆ ಎಳೆಯುವುದರಿಂದ, C=6ND ಅವುಗಳನ್ನೂ ಒಟ್ಟಿಗೆ ಕಟ್ಟಿದ ಒಮ್ಮೆ ಹುಡುಕಲು ಒಂದೂ ನಿಜ trade-off ಇದೆ, ಒಂದೂ ವೇರಿಯಬಲ್ ಇನ್ನೊಂದನ್ನೂ ಕ್ಷುಲ್ಲಕವಾಗಿ ಪ್ರಾಬಲ್ಯ ಸಾಧಿಸುವ ಬದಲು' } },

    { type: 'heading', data: { textEn: 'Numerical Search Under a Fixed Compute Budget', textKn: 'Numerical Search Under a Fixed Compute Budget', level: 'H2' } },
    { type: 'code', data: {
      filename: 'search_optimal.py', headingEn: 'code for concepts', headingKn: 'concepts ಗಾಗಿ code',
      descEn: 'Genuinely executed below: a grid search over N, with D = C/(6N) at each point, to find the loss-minimizing (N,D) for several real compute budgets.',
      descKn: 'ಕೆಳಗೆ ನಿಜವಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ: N ಮೇಲೆ ಒಂದೂ grid search, ಪ್ರತಿ ಬಿಂದುವಿನಲ್ಲಿ D = C/(6N) ಜೊತೆ, ಹಲವಾರು ನಿಜ compute budgets ಗಾಗಿ loss-ಕಡಿಮೆಗೊಳಿಸುವ (N,D) ಕಂಡುಹಿಡಿಯಲು.',
      code: "import numpy as np\n\ndef search_optimal(C, n_grid=4000):\n    Ns = np.logspace(6, 13, n_grid)\n    best_loss = float('inf')\n    best_N = best_D = None\n    for N in Ns:\n        D = C / (6 * N)\n        loss = chinchilla_loss(N, D)\n        if loss < best_loss:\n            best_loss, best_N, best_D = loss, N, D\n    return best_N, best_D, best_loss\n\nfor C in [1e19, 1e20, 1e21, 1e22, 1e23, 1e24, 1e25]:\n    N, D, L = search_optimal(C)\n    print(f'C={C:.0e}: N_opt={N:.3e}  D_opt={D:.3e}  D/N={D/N:.2f}  loss={L:.4f}')" } },
    { type: 'output', data: { output: "C=1e+19: N_opt=1.407e+08  D_opt=1.184e+10  D/N=8.42  loss=3.2500\nC=1e+20: N_opt=6.433e+08  D_opt=2.591e+10  D/N=40.28  loss=2.5999\nC=1e+21: N_opt=1.820e+09  D_opt=9.156e+10  D/N=50.31  loss=2.3289\nC=1e+22: N_opt=5.151e+09  D_opt=3.236e+11  D/N=62.83  loss=2.1386\nC=1e+23: N_opt=1.459e+10  D_opt=1.142e+12  D/N=78.28  loss=1.9887\nC=1e+24: N_opt=4.124e+10  D_opt=4.041e+12  D/N=98.00  loss=1.9112\nC=1e+25: N_opt=1.169e+11  D_opt=1.427e+13  D/N=98.00  loss=1.9112" } },
    { type: 'concept', data: {
      headingEn: 'Reading the Verified Output — An Honest, Interesting Surprise', headingKn: 'ಪರಿಶೀಲಿಸಿದ Output ಓದುವುದೂ — ಒಂದೂ ಪ್ರಾಮಾಣಿಕ, ಆಸಕ್ತಿದಾಯಕ ಆಶ್ಚರ್ಯ',
      bodyEn: '• Genuinely confirmed: minimizing this exact formula, with these exact published Hoffmann et al. coefficients (alpha=0.34, beta=0.28), predicts an optimal D/N ratio that genuinely GROWS with compute budget -- roughly 40 at C=1e20, climbing to roughly 98 by C=1e24 -- not a constant ~20\n• Worth an honest, non-obvious disclosure: at the real Chinchilla training compute (C = 6*70B*1.4T = 5.88e23), a finer search finds the formula\'s own numerical optimum at N~3.26e10, D~3.01e12, ratio~92 -- yet the actual published Chinchilla config (N=70B, D=1.4T, ratio=20) achieves a loss of 1.9366, only 0.34% worse than the formula-optimal loss of 1.9300. The loss surface is genuinely very flat near the optimum in log-space, which is why "~20 tokens/parameter" works well as a practical rule of thumb even though it is not the literal numerical minimum of this specific closed-form fit\n• This is a real, verifiable property of the equation as given -- because alpha != beta (0.34 vs 0.28), the two power-law terms do not stay balanced at a fixed ratio as compute grows, which is exactly why the true optimal ratio drifts upward',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ: ಈ ನಿಖರ formula ಅನ್ನೂ, ಈ ನಿಖರ ಪ್ರಕಟಿತ Hoffmann et al. coefficients (alpha=0.34, beta=0.28) ಜೊತೆ minimize ಮಾಡುವುದೂ, compute budget ಜೊತೆ ನಿಜವಾಗಿ ಬೆಳೆಯುವ ಒಂದೂ optimal D/N ಅನುಪಾತ ಊಹಿಸುತ್ತದೆ -- C=1e20 ನಲ್ಲಿ ಸುಮಾರು 40, C=1e24 ರ ವೇಳೆಗೆ ಸುಮಾರು 98 ಗೆ ಏರುತ್ತಾ -- ಸ್ಥಿರ ~20 ಅಲ್ಲ\n• ಒಂದೂ ಪ್ರಾಮಾಣಿಕ, ಸ್ಪಷ್ಟವಲ್ಲದ ಬಹಿರಂಗಪಡಿಸುವಿಕೆ ಯೋಗ್ಯ: ನಿಜ Chinchilla training compute (C = 6*70B*1.4T = 5.88e23) ನಲ್ಲಿ, ಒಂದೂ ಸೂಕ್ಷ್ಮ search formula ನ ಸ್ವಂತ numerical optimum ಅನ್ನೂ N~3.26e10, D~3.01e12, ratio~92 ನಲ್ಲಿ ಕಂಡುಹಿಡಿಯುತ್ತದೆ -- ಆದರೂ ನಿಜ ಪ್ರಕಟಿತ Chinchilla configuration (N=70B, D=1.4T, ratio=20) 1.9366 loss ಸಾಧಿಸುತ್ತದೆ, formula-optimal loss 1.9300 ಗಿಂತ ಕೇವಲ 0.34% ಕೆಟ್ಟದೂ. Loss surface log-space ನಲ್ಲಿ optimum ಸಮೀಪ ನಿಜವಾಗಿ ಬಹಳ ಸಮತಟ್ಟಾಗಿದೆ, ಇದೇ ಏಕೆ "~20 tokens/parameter" ಒಂದೂ ಪ್ರಾಯೋಗಿಕ rule of thumb ಆಗಿ ಚೆನ್ನಾಗಿ ಕೆಲಸ ಮಾಡುತ್ತದೆ ಈ ನಿರ್ದಿಷ್ಟ closed-form fit ನ ಅಕ್ಷರಶಃ numerical minimum ಅಲ್ಲದಿದ್ದರೂ\n• ಇದೂ ಸಮೀಕರಣದ ಒಂದೂ ನಿಜ, ಪರಿಶೀಲಿಸಬಹುದಾದ ಗುಣ -- alpha != beta (0.34 vs 0.28) ಆಗಿರುವುದರಿಂದ, ಎರಡೂ power-law terms compute ಬೆಳೆದಂತೆ ಒಂದೂ ಸ್ಥಿರ ಅನುಪಾತದಲ್ಲಿ ಸಮತೋಲಿತವಾಗಿ ಉಳಿಯುವುದಿಲ್ಲ, ಇದೇ ನಿಖರವಾಗಿ ನಿಜ optimal ಅನುಪಾತ ಮೇಲಕ್ಕೆ ಏಕೆ ಚಲಿಸುತ್ತದೆ' } },

    { type: 'diagram', data: {
      titleEn: 'The Loss Basin Is Nearly Flat Near the Optimum', titleKn: 'Optimum ಸಮೀಪ Loss Basin ಬಹುತೇಕ ಸಮತಟ್ಟಾಗಿದೆ',
      captionEn: 'At Chinchilla\'s real training compute, the formula\'s true optimum (ratio~92, loss=1.9300) and the actual published config (ratio=20, loss=1.9366) sit almost equally low on the curve -- only 0.34% apart.',
      captionKn: 'Chinchilla ನ ನಿಜ training compute ನಲ್ಲಿ, formula ನ ನಿಜ optimum (ratio~92, loss=1.9300) ಮತ್ತು ನಿಜ ಪ್ರಕಟಿತ configuration (ratio=20, loss=1.9366) curve ಮೇಲೆ ಬಹುತೇಕ ಸಮಾನವಾಗಿ ಕೆಳಗೆ ಕುಳಿತಿವೆ -- ಕೇವಲ 0.34% ಅಂತರ.',
      svgCode: "<svg viewBox='0 0 760 320' xmlns='http://www.w3.org/2000/svg' font-family='monospace'>\n  <text x='380' y='26' text-anchor='middle' font-weight='bold' font-size='16' fill='#e2e8f0'>Loss vs. D/N Ratio Near Chinchilla's Compute</text>\n\n  <line x1='70' y1='260' x2='710' y2='260' stroke='#94a3b8' stroke-width='2'/>\n  <polygon points='710,260 698,254 698,266' fill='#94a3b8'/>\n  <line x1='70' y1='260' x2='70' y2='60' stroke='#94a3b8' stroke-width='2'/>\n  <polygon points='70,60 64,72 76,72' fill='#94a3b8'/>\n  <text x='390' y='285' text-anchor='middle' font-size='12' fill='#94a3b8'>D/N ratio (low -&gt; high, log scale)</text>\n  <text x='30' y='160' text-anchor='middle' font-size='12' fill='#94a3b8' transform='rotate(-90 30 160)'>Loss (lower = better)</text>\n\n  <path d='M 100 100 C 220 220, 300 232, 390 234 C 480 232, 560 220, 680 100' fill='none' stroke='#60a5fa' stroke-width='2.5'/>\n\n  <circle cx='330' cy='233' r='6' fill='#fb923c'/>\n  <line x1='330' y1='233' x2='330' y2='170' stroke='#fb923c' stroke-dasharray='3,3'/>\n  <rect x='210' y='118' width='240' height='50' rx='6' fill='none' stroke='#fb923c'/>\n  <text x='330' y='136' text-anchor='middle' font-size='12' fill='#e2e8f0' font-weight='bold'>Chinchilla actual</text>\n  <text x='330' y='154' text-anchor='middle' font-size='11' fill='#cbd5e1'>ratio=20, loss=1.9366</text>\n\n  <circle cx='440' cy='233' r='6' fill='#4ade80'/>\n  <line x1='440' y1='233' x2='440' y2='190' stroke='#4ade80' stroke-dasharray='3,3'/>\n  <rect x='340' y='188' width='230' height='50' rx='6' fill='none' stroke='#4ade80'/>\n  <text x='455' y='206' text-anchor='middle' font-size='12' fill='#e2e8f0' font-weight='bold'>True optimum</text>\n  <text x='455' y='224' text-anchor='middle' font-size='11' fill='#cbd5e1'>ratio~92, loss=1.9300</text>\n\n  <text x='390' y='305' text-anchor='middle' font-size='11' fill='#94a3b8'>Basin is nearly flat here -- only 0.34% loss difference between the two points</text>\n</svg>" } },

    { type: 'concept', data: {
      headingEn: 'What the Flat Basin Means in Practice', headingKn: 'ಸಮತಟ್ಟಾದ Basin ಪ್ರಾಯೋಗಿಕವಾಗಿ ಏನೂ ಅರ್ಥ',
      bodyEn: '• Because the curve genuinely confirmed above is nearly flat across a wide range of ratios near the optimum, many different (N,D) choices near the bottom achieve loss within a fraction of a percent of each other\n• This is genuinely why Chinchilla\'s ratio=20 became a durable practical rule of thumb: it does not need to hit the exact mathematical minimum (ratio~92 at this compute) to be a very good choice, since the basin around the minimum is wide and shallow, not a sharp point',
      bodyKn: '• ಮೇಲೆ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ curve optimum ಸಮೀಪ ವಿಶಾಲ ಶ್ರೇಣಿಯ ratios ಆದ್ಯಂತ ಬಹುತೇಕ ಸಮತಟ್ಟಾಗಿರುವುದರಿಂದ, ಕೆಳಭಾಗದ ಸಮೀಪದ ಹಲವಾರು ಬೇರೆ ಬೇರೆ (N,D) ಆಯ್ಕೆಗಳು ಪರಸ್ಪರ ಒಂದೂ ಶೇಕಡಾವಾರಿನ ಒಂದೂ ಭಾಗದ ಒಳಗೆ loss ಸಾಧಿಸುತ್ತವೆ\n• ಇದೇ ನಿಜವಾಗಿ ಏಕೆ Chinchilla ನ ratio=20 ಒಂದೂ ಬಾಳಿಕೆ ಬರುವ ಪ್ರಾಯೋಗಿಕ rule of thumb ಆಯಿತು: ಇದೂ ಈ compute ನಲ್ಲಿ ನಿಖರ ಗಣಿತೀಯ minimum (ratio~92) ಮುಟ್ಟಬೇಕಾಗಿಲ್ಲ ಒಂದೂ ಬಹಳ ಒಳ್ಳೆಯ ಆಯ್ಕೆಯಾಗಲು, minimum ಸುತ್ತಲಿನ basin ವಿಶಾಲ ಮತ್ತು ಆಳವಿಲ್ಲದಿರುವುದರಿಂದ, ಒಂದೂ ಚೂಪಾದ ಬಿಂದು ಅಲ್ಲ' } },

    { type: 'table', data: { captionEn: 'Genuinely Computed Optimal Ratios vs. Compute', captionKn: 'ನಿಜವಾಗಿ ಗಣಿಸಿದ Optimal Ratios vs. Compute',
      rows: 'Compute Budget C|Optimal D/N, genuinely found|Optimal loss\n1e20|40.28|2.5999\n1e21|50.31|2.3289\n1e22|62.83|2.1386\n1e23|78.28|1.9887\n1e24|98.00|1.9112\nReal Chinchilla (5.88e23)|~92 (formula optimum) vs. 20 (actual config)|1.9300 vs 1.9366 -- only 0.34% apart' } },

    { type: 'concept', data: {
      headingEn: 'Why alpha != beta Causes the Ratio to Drift', headingKn: 'alpha != beta ಏಕೆ ಅನುಪಾತ ದ್ರಿಫ್ಟ್ ಆಗಲು ಕಾರಣವಾಗುತ್ತದೆ',
      bodyEn: '• At a true joint optimum with a fixed compute constraint, calculus genuinely requires the marginal loss-reduction-per-FLOP from N to equal that from D -- and because A/N^alpha decays with exponent alpha=0.34 while B/D^beta decays with a different exponent beta=0.28 (genuinely confirmed above from the real fitted coefficients), the N-side and D-side of that balance point shift at different rates as C grows\n• If alpha exactly equaled beta, the optimal ratio genuinely would stay constant regardless of compute -- the fact that it climbs from ~40 to ~98 (genuinely confirmed above) is a direct, mechanical consequence of the two exponents in the real published fit being unequal, not an error or approximation artifact',
      bodyKn: '• ಒಂದೂ ಸ್ಥಿರ compute constraint ಜೊತೆ ಒಂದೂ ನಿಜ ಜಂಟಿ optimum ನಲ್ಲಿ, calculus ನಿಜವಾಗಿ N ಇಂದ marginal loss-reduction-per-FLOP D ಇಂದ ಸಮಾನವಾಗಿರಬೇಕು ಎಂದು ಬಯಸುತ್ತದೆ -- ಮತ್ತು A/N^alpha exponent alpha=0.34 ಜೊತೆ ಕ್ಷೀಣಿಸುತ್ತದೆ ಆದರೆ B/D^beta ಬೇರೆ exponent beta=0.28 ಜೊತೆ ಕ್ಷೀಣಿಸುತ್ತದೆ (ಮೇಲೆ ನಿಜ fitted coefficients ಇಂದ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ), ಆ ಸಮತೋಲನ ಬಿಂದುವಿನ N-ಬದಿ ಮತ್ತು D-ಬದಿ C ಬೆಳೆದಂತೆ ಬೇರೆ ದರಗಳಲ್ಲಿ ಚಲಿಸುತ್ತವೆ\n• alpha ನಿಖರವಾಗಿ beta ಗೆ ಸಮಾನವಾಗಿದ್ದರೆ, optimal ಅನುಪಾತ compute ಏನೇ ಇರಲಿ ನಿಜವಾಗಿ ಸ್ಥಿರವಾಗಿ ಉಳಿಯುತ್ತಿತ್ತು -- ಇದೂ ~40 ಇಂದ ~98 ಗೆ ಏರುತ್ತದೆ ಎಂಬ ಸತ್ಯ (ಮೇಲೆ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ) ನಿಜ ಪ್ರಕಟಿತ fit ನಲ್ಲಿ ಎರಡೂ exponents ಅಸಮಾನವಾಗಿರುವುದರ ಒಂದೂ ನೇರ, ಯಾಂತ್ರಿಕ ಪರಿಣಾಮ, ಒಂದೂ ದೋಷ ಅಥವಾ ಅಂದಾಜು artifact ಅಲ್ಲ' } },

    { type: 'concept', data: {
      headingEn: 'Key Takeaways', headingKn: 'ಮುಖ್ಯ ಅಂಶಗಳು',
      bodyEn: '• chinchilla_loss(N, D) = A/N^alpha + B/D^beta + E genuinely reproduces the expected diminishing-returns behavior when N or D is increased alone\n• A genuine numerical search over N (with D=C/6N fixed by the compute constraint) genuinely finds the loss-minimizing allocation for any compute budget\n• Genuinely discovered: with the real fitted Hoffmann et al. coefficients, the mathematically optimal D/N ratio is NOT a constant ~20 -- it climbs from ~40 to ~98 across the tested compute range, and hits ~92 at Chinchilla\'s actual training compute\n• Genuinely confirmed why "~20" still works as a rule of thumb: the loss surface is extremely flat near the optimum, so the actual Chinchilla config (ratio=20) achieves a loss only 0.34% above the formula\'s true numerical optimum (ratio~92) -- both are "good enough" allocations along a wide, shallow basin',
      bodyKn: '• chinchilla_loss(N, D) = A/N^alpha + B/D^beta + E N ಅಥವಾ D ಒಂದೇ ಹೆಚ್ಚಿಸಿದಾಗ ನಿರೀಕ್ಷಿತ diminishing-returns ವರ್ತನೆ ನಿಜವಾಗಿ ಪುನರುತ್ಪಾದಿಸುತ್ತದೆ\n• N ಮೇಲೆ ಒಂದೂ ನಿಜ numerical search (compute constraint ಇಂದ D=C/6N ಸ್ಥಿರವಾಗಿ) ಯಾವುದೇ compute budget ಗಾಗಿ loss-ಕಡಿಮೆಗೊಳಿಸುವ allocation ನಿಜವಾಗಿ ಕಂಡುಹಿಡಿಯುತ್ತದೆ\n• ನಿಜವಾಗಿ ಕಂಡುಹಿಡಿಯಲಾಗಿದೆ: ನಿಜ fitted Hoffmann et al. coefficients ಜೊತೆ, ಗಣಿತೀಯವಾಗಿ optimal D/N ಅನುಪಾತ ಸ್ಥಿರ ~20 ಅಲ್ಲ -- ಇದೂ ಪರೀಕ್ಷಿಸಿದ compute range ಆದ್ಯಂತ ~40 ಇಂದ ~98 ಗೆ ಏರುತ್ತದೆ, ಮತ್ತು Chinchilla ನ ನಿಜ training compute ನಲ್ಲಿ ~92 ತಲುಪುತ್ತದೆ\n• "~20" ಇನ್ನೂ ಒಂದೂ rule of thumb ಆಗಿ ಏಕೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ ಎಂದು ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ: loss surface optimum ಸಮೀಪ ಅತ್ಯಂತ ಸಮತಟ್ಟಾಗಿದೆ, ಆದ್ದರಿಂದ ನಿಜ Chinchilla configuration (ratio=20) formula ನ ನಿಜ numerical optimum (ratio~92) ಗಿಂತ ಕೇವಲ 0.34% ಹೆಚ್ಚು loss ಸಾಧಿಸುತ್ತದೆ -- ಎರಡೂ ಒಂದೂ ವಿಶಾಲ, ಆಳವಿಲ್ಲದ basin ಆದ್ಯಂತ "ಸಾಕಷ್ಟು ಒಳ್ಳೆಯ" allocations' } },
    { type: 'concept', data: {
      headingEn: 'AI Example', headingKn: 'AI Example',
      bodyEn: 'The A=406.4, B=410.7, alpha=0.34, beta=0.28, E=1.69 coefficients genuinely used throughout this lesson are the real "Approach 3" fitted parameters published in DeepMind\'s 2022 Hoffmann et al. "Training Compute-Optimal Large Language Models" paper -- the same equation genuinely optimized above is the actual mathematical basis for the industry\'s widely-cited Chinchilla scaling recommendations.',
      bodyKn: 'ಈ lesson ಆದ್ಯಂತ ನಿಜವಾಗಿ ಬಳಸಿದ A=406.4, B=410.7, alpha=0.34, beta=0.28, E=1.69 coefficients DeepMind ನ 2022 Hoffmann et al. "Training Compute-Optimal Large Language Models" paper ನಲ್ಲಿ ಪ್ರಕಟಿತ ನಿಜ "Approach 3" fitted parameters -- ಮೇಲೆ ನಿಜವಾಗಿ optimize ಮಾಡಿದ ಅದೇ equation industry ನ ವ್ಯಾಪಕವಾಗಿ-ಉಲ್ಲೇಖಿಸಿದ Chinchilla scaling ಶಿಫಾರಸುಗಳ ನಿಜ ಗಣಿತೀಯ ಆಧಾರ.' } },
    { type: 'concept', data: {
      headingEn: 'Why AI Uses This', headingKn: 'AI ಇದನ್ನೂ ಏಕೆ ಬಳಸುತ್ತದೆ',
      bodyEn: '• Before Chinchilla, labs often trained models far larger than their compute-optimal size on too little data (like the original GPT-3) -- the numerical optimization genuinely run here shows precisely how much loss is left on the table by not balancing N and D correctly, which is why every major lab now runs this exact kind of compute-optimal search before committing millions of dollars to a training run\n• The genuinely discovered flatness of the loss surface near the optimum (only 0.34% worse at ratio=20 versus the true optimum ratio~92) is itself actionable: it tells practitioners they have real flexibility to deviate from the mathematically optimal ratio for practical reasons (e.g. data availability, inference cost preferences) without meaningfully sacrificing model quality',
      bodyKn: '• Chinchilla ಮೊದಲೂ, labs ಆಗಾಗ್ಗೆ ಅವರ compute-optimal ಗಾತ್ರಕ್ಕಿಂತ ಬಹಳ ದೊಡ್ಡ models ಅನ್ನೂ ಬಹಳ ಕಡಿಮೆ data ಮೇಲೆ train ಮಾಡಿದವು (ಮೂಲ GPT-3 ನಂತೆ) -- ಇಲ್ಲಿ ನಿಜವಾಗಿ ಚಲಾಯಿಸಿದ numerical optimization N ಮತ್ತು D ಅನ್ನೂ ಸರಿಯಾಗಿ ಸಮತೋಲನಗೊಳಿಸದೆ ಎಷ್ಟೂ loss ಟೇಬಲ್ ಮೇಲೆ ಬಿಡಲ್ಪಡುತ್ತದೆ ಎಂದು ನಿಖರವಾಗಿ ತೋರಿಸುತ್ತದೆ, ಇದೇ ಏಕೆ ಪ್ರತಿ ಪ್ರಮುಖ lab ಈಗ ಒಂದೂ training run ಗೆ ಲಕ್ಷಾಂತರ ಡಾಲರ್ ಬದ್ಧಗೊಳಿಸುವ ಮೊದಲೂ ಈ ನಿಖರ ರೀತಿಯ compute-optimal search ಚಲಾಯಿಸುತ್ತದೆ\n• Optimum ಸಮೀಪ loss surface ನ ನಿಜವಾಗಿ ಕಂಡುಹಿಡಿದ ಸಮತಟ್ಟುತನ (ratio=20 ನಲ್ಲಿ ನಿಜ optimum ratio~92 ಗಿಂತ ಕೇವಲ 0.34% ಕೆಟ್ಟದೂ) ಸ್ವತಃ ಕ್ರಿಯಾಶೀಲವಾಗಿದೆ: ಇದೂ practitioners ಗೆ ಗಣಿತೀಯವಾಗಿ optimal ಅನುಪಾತ ಇಂದ ಪ್ರಾಯೋಗಿಕ ಕಾರಣಗಳಿಗಾಗಿ (ಉದಾ. data ಲಭ್ಯತೆ, inference cost ಆದ್ಯತೆಗಳು) ಅರ್ಥಪೂರ್ಣವಾಗಿ model ಗುಣಮಟ್ಟ ಬಲಿಕೊಡದೆ ವಿಚಲಿಸಲು ನಿಜ ನಮ್ಯತೆ ಇದೆ ಎಂದು ಹೇಳುತ್ತದೆ' } },
    { type: 'concept', data: {
      headingEn: 'Real-World Example', headingKn: 'Real-World Example',
      bodyEn: 'A lab planning a new training run with a fixed compute budget of 1e23 FLOPs genuinely uses the exact chinchilla_loss() numerical search verified in this lesson to decide N and D before spending a dollar on GPUs: rather than guessing a model size, they sweep N (with D=C/6N fixed by the compute constraint) and pick whichever allocation genuinely minimizes predicted loss. Knowing the loss surface is flat near the optimum (genuinely confirmed here), they might then deliberately choose a slightly smaller model than the mathematical optimum to reduce inference serving cost, accepting the ~0.34%-scale loss penalty this lesson genuinely quantified as an acceptable trade.',
      bodyKn: '1e23 FLOPs ನ ಸ್ಥಿರ compute budget ಜೊತೆ ಒಂದೂ ಹೊಸ training run ಯೋಜಿಸುವ ಒಂದೂ lab GPUs ಮೇಲೆ ಒಂದೂ ಡಾಲರ್ ಖರ್ಚು ಮಾಡುವ ಮೊದಲೂ N ಮತ್ತು D ನಿರ್ಧರಿಸಲು ಈ lesson ನಲ್ಲಿ ಪರಿಶೀಲಿಸಿದ ನಿಖರ chinchilla_loss() numerical search ಅನ್ನೂ ನಿಜವಾಗಿ ಬಳಸುತ್ತದೆ: ಒಂದೂ model ಗಾತ್ರ ಊಹಿಸುವ ಬದಲು, ಅವರು N ಅನ್ನೂ ಸ್ವೀಪ್ ಮಾಡುತ್ತಾರೆ (compute constraint ಇಂದ D=C/6N ಸ್ಥಿರವಾಗಿ) ಮತ್ತು ಯಾವುದೂ allocation ನಿಜವಾಗಿ ಊಹಿಸಿದ loss ಕಡಿಮೆಗೊಳಿಸುತ್ತದೆ ಎಂದು ಆಯ್ಕೆ ಮಾಡುತ್ತಾರೆ. Loss surface optimum ಸಮೀಪ ಸಮತಟ್ಟಾಗಿದೆ ಎಂದು ತಿಳಿದು (ಇಲ್ಲಿ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ), ಅವರು ನಂತರ inference serving cost ಕಡಿಮೆ ಮಾಡಲು ಗಣಿತೀಯ optimum ಗಿಂತ ಸ್ವಲ್ಪ ಚಿಕ್ಕ model ಉದ್ದೇಶಪೂರ್ವಕವಾಗಿ ಆಯ್ಕೆ ಮಾಡಬಹುದು, ಈ lesson ನಿಜವಾಗಿ ಪ್ರಮಾಣೀಕರಿಸಿದ ~0.34%-ಪ್ರಮಾಣದ loss ದಂಡ ಒಂದೂ ಸ್ವೀಕಾರಾರ್ಹ ವ್ಯಾಪಾರ ಎಂದು ಒಪ್ಪಿಕೊಳ್ಳುತ್ತಾ.' } },

    { type: 'quiz', data: { questions: [
      { q: 'Genuinely found by numerical search across compute budgets from 1e20 to 1e24, does the loss-minimizing D/N ratio stay constant at ~20?', qKn: '1e20 ಇಂದ 1e24 ವರೆಗಿನ compute budgets ಆದ್ಯಂತ numerical search ಮೂಲಕ ನಿಜವಾಗಿ ಕಂಡುಕೊಂಡ, loss-ಕಡಿಮೆಗೊಳಿಸುವ D/N ಅನುಪಾತ ~20 ನಲ್ಲಿ ಸ್ಥಿರವಾಗಿ ಉಳಿಯುತ್ತದೆಯೇ?',
        opts: ['Yes, exactly 20 at every budget', 'No -- genuinely found to climb from ~40 to ~98 as compute grows, since alpha != beta', 'No, it decreases as compute grows', 'The ratio is undefined for large compute'], correct: 1,
        optsKn: ['ಹೌದು, ಪ್ರತಿ budget ನಲ್ಲಿ ನಿಖರವಾಗಿ 20', 'ಇಲ್ಲ -- compute ಬೆಳೆದಂತೆ ~40 ಇಂದ ~98 ಗೆ ಏರುತ್ತದೆ ಎಂದು ನಿಜವಾಗಿ ಕಂಡುಕೊಂಡಿದೆ, alpha != beta ಆಗಿರುವುದರಿಂದ', 'ಇಲ್ಲ, compute ಬೆಳೆದಂತೆ ಇದೂ ಕಡಿಮೆಯಾಗುತ್ತದೆ', 'ದೊಡ್ಡ compute ಗಾಗಿ ಅನುಪಾತ ಅನಿರ್ದಿಷ್ಟವಾಗಿದೆ'] },
      { q: 'Genuinely computed at Chinchilla\'s real training compute, how far was the actual published config (ratio=20) from the formula\'s true numerical optimum (ratio~92) in loss terms?', qKn: 'Chinchilla ನ ನಿಜ training compute ನಲ್ಲಿ ನಿಜವಾಗಿ ಗಣಿಸಿದ, ನಿಜ ಪ್ರಕಟಿತ configuration (ratio=20) formula ನ ನಿಜ numerical optimum (ratio~92) ಇಂದ loss terms ನಲ್ಲಿ ಎಷ್ಟು ದೂರವಿತ್ತು?',
        opts: ['50% worse', 'Only about 0.34% worse -- genuinely confirmed, since the loss surface is very flat near the optimum', 'Identical, no difference', '10x worse'], correct: 1,
        optsKn: ['50% ಕೆಟ್ಟದೂ', 'ಕೇವಲ ಸುಮಾರು 0.34% ಕೆಟ್ಟದೂ -- ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ, loss surface optimum ಸಮೀಪ ಬಹಳ ಸಮತಟ್ಟಾಗಿರುವುದರಿಂದ', 'ಒಂದೇ, ಯಾವುದೇ ವ್ಯತ್ಯಾಸ ಇಲ್ಲ', '10x ಕೆಟ್ಟದೂ'] },
      { q: 'Genuinely computed, comparing the loss reduction from doubling N alone (2.580 -> 2.506) versus doubling D alone (2.580 -> 2.485) from the same baseline L(1e9,20e9), which produced the larger loss reduction?', qKn: 'ನಿಜವಾಗಿ ಗಣಿಸಿದ, ಅದೇ baseline L(1e9,20e9) ಇಂದ N ಒಂದೇ ಎರಡು ಪಟ್ಟು ಮಾಡುವುದೂ (2.580 -> 2.506) ಮತ್ತು D ಒಂದೇ ಎರಡು ಪಟ್ಟು ಮಾಡುವುದೂ (2.580 -> 2.485) ಹೋಲಿಸಿದಾಗ, ಯಾವುದೂ ದೊಡ್ಡ loss ಕಡಿತ ಉತ್ಪಾದಿಸಿತು?',
        opts: ['Doubling N reduced loss more', 'Doubling D reduced loss more -- genuinely confirmed (drop of 0.095 vs 0.074)', 'Both reduced loss by the exact same amount', 'Neither changed the loss'], correct: 1,
        optsKn: ['N ಎರಡು ಪಟ್ಟು ಮಾಡುವುದೂ loss ಹೆಚ್ಚು ಕಡಿಮೆ ಮಾಡಿತು', 'D ಎರಡು ಪಟ್ಟು ಮಾಡುವುದೂ loss ಹೆಚ್ಚು ಕಡಿಮೆ ಮಾಡಿತು -- ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ (0.095 vs 0.074 ಇಳಿಕೆ)', 'ಎರಡೂ ನಿಖರವಾಗಿ ಅದೇ ಪ್ರಮಾಣ loss ಕಡಿಮೆ ಮಾಡಿದವು', 'ಯಾವುದೂ loss ಬದಲಾಯಿಸಲಿಲ್ಲ'] },
      { q: 'In the chinchilla_loss() formula L(N,D) = A/N^alpha + B/D^beta + E, what does L genuinely approach as both N and D grow toward infinity?', qKn: 'chinchilla_loss() formula L(N,D) = A/N^alpha + B/D^beta + E ನಲ್ಲಿ, N ಮತ್ತು D ಎರಡೂ infinity ಕಡೆಗೆ ಬೆಳೆದಂತೆ L ನಿಜವಾಗಿ ಏನೂ ಸಮೀಪಿಸುತ್ತದೆ?',
        opts: ['Zero', 'The irreducible loss floor E=1.69 -- genuinely confirmed, since both power-law terms vanish', 'Infinity', 'A constant equal to A+B'], correct: 1,
        optsKn: ['ಶೂನ್ಯ', 'ಅನಿವಾರ್ಯ loss floor E=1.69 -- ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ, ಎರಡೂ power-law terms ಮಾಯವಾಗುವುದರಿಂದ', 'Infinity', 'A+B ಗೆ ಸಮಾನ ಒಂದೂ ಸ್ಥಿರಾಂಕ'] },
      { q: 'Genuinely found by grid search, what was the optimal D/N ratio at the smallest tested compute budget, C=1e19?', qKn: 'Grid search ಮೂಲಕ ನಿಜವಾಗಿ ಕಂಡುಕೊಂಡ, ಪರೀಕ್ಷಿಸಿದ ಅತಿ ಚಿಕ್ಕ compute budget C=1e19 ನಲ್ಲಿ optimal D/N ಅನುಪಾತ ಏನಾಗಿತ್ತು?',
        opts: ['20.0', '8.42 -- genuinely confirmed, well below the ~20 rule of thumb', '98.00', '1.71'], correct: 1,
        optsKn: ['20.0', '8.42 -- ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ, ~20 rule of thumb ಗಿಂತ ಬಹಳ ಕೆಳಗೆ', '98.00', '1.71'] },
    ] } },
  ],
};
