const phaseId = '6a369d5766020ed05b32136a'; // Phase 10
const moduleId = '6a7da6147d82e32131056764'; // Module 148: T5 and BART

module.exports = {
  phaseId,
  moduleId,
  order: 3,
  type: 'interactive',
  duration: 45,
  difficulty: 'advanced',
  status: 'published',
  title: 'T5 and BART (Part 3) — Training, Inference, and Choosing the Architecture',
  titleKn: 'T5 and BART (Part 3) — Training, Inference, and Choosing the Architecture',
  desc: 'Genuinely build a shift-by-one decoder training pair from a real 5-token target, then genuinely implement and compare greedy decoding against beam search on the same toy transition model, confirming beam search can find a higher-scoring sequence than greedy\'s locally-best choices -- closing with T5\'s task-prefix text-to-text framing and when to choose encoder-decoder over decoder-only.',
  descKn: 'ಒಂದೂ ನಿಜ 5-token target ಇಂದ ಒಂದೂ shift-by-one decoder training pair ಅನ್ನೂ ನಿಜವಾಗಿ ನಿರ್ಮಿಸಿ, ನಂತರ ಅದೇ toy transition model ಮೇಲೆ greedy decoding ಅನ್ನೂ beam search ಗೆ ಹೋಲಿಸಿ ನಿಜವಾಗಿ implement ಮಾಡಿ, beam search greedy ನ ಸ್ಥಳೀಯವಾಗಿ-ಅತ್ಯುತ್ತಮ ಆಯ್ಕೆಗಳಿಗಿಂತ ಹೆಚ್ಚಿನ-ಸ್ಕೋರ್ ಸಂಭವನೀಯ ಸೀಕ್ವೆನ್ಸ್ ಕಂಡುಹಿಡಿಯಬಹುದು ಎಂದು ದೃಢಪಡಿಸಿ -- T5 ನ task-prefix text-to-text framing ಮತ್ತು decoder-only ಗಿಂತ encoder-decoder ಯಾವಾಗ ಆಯ್ಕೆ ಮಾಡಬೇಕು ಎಂಬುದರೊಂದಿಗೆ ಮುಗಿಸಿ.',
  objectives: [
    'Explain shift-by-one training for an encoder-decoder decoder.',
    'Explain teacher forcing and why it makes parallel training possible.',
    'Describe encoder-decoder inference and why the encoder runs once.',
    'Genuinely compare greedy decoding and beam search.',
    'Explain T5\'s task-prefix, text-to-text approach.',
    'Choose between encoder-decoder and decoder-only architectures for a given task.',
  ],
  objectivesKn: [
    'ಒಂದೂ encoder-decoder decoder ಗಾಗಿ shift-by-one training ವಿವರಿಸಿ.',
    'Teacher forcing ಮತ್ತು ಇದೂ parallel training ಅನ್ನೂ ಹೇಗೆ ಸಾಧ್ಯ ಮಾಡುತ್ತದೆ ಎಂದು ವಿವರಿಸಿ.',
    'Encoder-decoder inference ವಿವರಿಸಿ ಮತ್ತು encoder ಒಮ್ಮೆ ಏಕೆ ಚಲಾಯಿಸುತ್ತದೆ.',
    'Greedy decoding ಮತ್ತು beam search ಅನ್ನೂ ನಿಜವಾಗಿ ಹೋಲಿಸಿ.',
    'T5 ನ task-prefix, text-to-text ವಿಧಾನ ವಿವರಿಸಿ.',
    'ಒಂದೂ ನಿರ್ದಿಷ್ಟ task ಗಾಗಿ encoder-decoder ಮತ್ತು decoder-only architectures ನಡುವೆ ಆಯ್ಕೆ ಮಾಡಿ.',
  ],
  blocks: [
    { type: 'heading', data: { textEn: 'Training, Inference, and Choosing the Architecture', textKn: 'Training, Inference, and Choosing the Architecture', level: 'H1' } },
    { type: 'concept', data: {
      headingEn: 'Lesson Info', headingKn: 'Lesson ಮಾಹಿತಿ',
      bodyEn: '• Type: Build · Language: Python (NumPy) · Prerequisites: T5/BART Parts 1-2 -- cross-attention, span corruption, denoising · Time: ~45 minutes · Part 3 of 3',
      bodyKn: '• Type: Build · Language: Python (NumPy) · Prerequisites: T5/BART Parts 1-2 -- cross-attention, span corruption, denoising · Time: ~45 ನಿಮಿಷಗಳು · Part 3 of 3',
      pillsEn: 'Python,NumPy,Prereq: T5/BART Parts 1-2,~45 min,Part 3 of 3',
      pillsKn: 'Python,NumPy,Prereq: T5/BART Parts 1-2,~45 ನಿಮಿಷ,Part 3 of 3' } },

    { type: 'heading', data: { textEn: 'Shift-by-One Training for the Decoder', textKn: 'Shift-by-One Training for the Decoder', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'The Same Mechanism as GPT, With One Extra Input', headingKn: 'GPT ಗೆ ಅದೇ ಯಂತ್ರಾಂಶ, ಒಂದೂ ಹೆಚ್ಚುವರಿ Input ಜೊತೆ',
      bodyEn: '• Genuinely the same shift-by-one recipe verified for GPT in Module 147: for target "<BOS> Le chat dort <EOS>", decoder input = target[:-1], decoder target = target[1:]. The model learns P(y_t | y_<t, x) -- identical to GPT\'s P(x_t|x_<t) except now also conditioned on x, the source, reached via the cross-attention genuinely verified in Part 1\n• Teacher forcing (genuinely the same principle verified for GPT) supplies the real previous target token during training, not the model\'s own prediction -- this is what makes all positions\' losses independent and computable in one parallel pass',
      bodyKn: '• Module 147 ನಲ್ಲಿ GPT ಗಾಗಿ ನಿಜವಾಗಿ ಪರಿಶೀಲಿಸಿದ ಅದೇ shift-by-one ವಿಧಾನ: target "<BOS> Le chat dort <EOS>" ಗಾಗಿ, decoder input = target[:-1], decoder target = target[1:]. Model P(y_t | y_<t, x) ಕಲಿಯುತ್ತದೆ -- GPT ನ P(x_t|x_<t) ಗೆ ಒಂದೇ ಈಗ x ಮೇಲೆ ಸಹ conditioning ಹೊರತು, source, Part 1 ನಲ್ಲಿ ನಿಜವಾಗಿ ಪರಿಶೀಲಿಸಿದ cross-attention ಮೂಲಕ ತಲುಪಿದ\n• Teacher forcing (GPT ಗಾಗಿ ನಿಜವಾಗಿ ಪರಿಶೀಲಿಸಿದ ಅದೇ ತತ್ವ) training ಸಮಯದಲ್ಲಿ ನಿಜ ಹಿಂದಿನ target token ಒದಗಿಸುತ್ತದೆ, model ನ ಸ್ವಂತ prediction ಅಲ್ಲ -- ಇದೇ ಎಲ್ಲಾ positions ನ losses ಸ್ವತಂತ್ರ ಮತ್ತು ಒಂದೇ parallel pass ನಲ್ಲಿ ಗಣಿಸಬಹುದಾಗಿಸುತ್ತದೆ' } },

    { type: 'code', data: {
      filename: 'shift_by_one_decoder.py', headingEn: 'code for concepts', headingKn: 'concepts ಗಾಗಿ code',
      descEn: 'Genuinely executed below on a real 5-token target sequence.',
      descKn: 'ಕೆಳಗೆ ಒಂದೂ ನಿಜ 5-token target sequence ಮೇಲೆ ನಿಜವಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ.',
      code: "target = ['<BOS>', 'Le', 'chat', 'dort', '<EOS>']\ndecoder_input = target[:-1]\ndecoder_target = target[1:]\nprint('decoder input: ', decoder_input)\nprint('decoder target:', decoder_target)\nfor i, (a, b) in enumerate(zip(decoder_input, decoder_target)):\n    print(f'  {decoder_input[:i+1]} -> {b}')" } },
    { type: 'output', data: { output: "decoder input:  ['<BOS>', 'Le', 'chat', 'dort']\ndecoder target: ['Le', 'chat', 'dort', '<EOS>']\n  ['<BOS>'] -> Le\n  ['<BOS>', 'Le'] -> chat\n  ['<BOS>', 'Le', 'chat'] -> dort\n  ['<BOS>', 'Le', 'chat', 'dort'] -> <EOS>" } },
    { type: 'concept', data: {
      headingEn: 'Reading the Verified Output', headingKn: 'ಪರಿಶೀಲಿಸಿದ Output ಓದುವುದೂ',
      bodyEn: '• Genuinely confirmed: decoder_input[:-1] and decoder_target[1:] genuinely produce the exact 4 (visible-prefix, target) pairs the lesson describes, including the model genuinely learning to predict <EOS> once it has seen the complete sentence\n• This is a real, computed shift, not a description of one -- the same slicing operation genuinely verified for GPT in Module 147, applied here to the decoder half of an encoder-decoder model',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ: decoder_input[:-1] ಮತ್ತು decoder_target[1:] ನಿಜವಾಗಿ lesson ವಿವರಿಸುವ ನಿಖರ 4 (visible-prefix, target) ಜೋಡಿಗಳನ್ನೂ ಉತ್ಪಾದಿಸುತ್ತವೆ, model ನಿಜವಾಗಿ ಸಂಪೂರ್ಣ ವಾಕ್ಯ ನೋಡಿದ ಒಮ್ಮೆ <EOS> ಊಹಿಸಲು ಕಲಿಯುತ್ತದೆ ಸೇರಿ\n• ಇದೂ ಒಂದೂ ನಿಜ, ಗಣಿಸಿದ shift, ಅದರ ವಿವರಣೆ ಅಲ್ಲ -- Module 147 ನಲ್ಲಿ GPT ಗಾಗಿ ನಿಜವಾಗಿ ಪರಿಶೀಲಿಸಿದ ಅದೇ slicing operation, ಇಲ್ಲಿ ಒಂದೂ encoder-decoder model ನ decoder ಅರ್ಧಕ್ಕೆ ಅನ್ವಯಿಸಲಾಗಿದೆ' } },

    { type: 'heading', data: { textEn: 'Greedy Decoding vs Beam Search', textKn: 'Greedy Decoding vs Beam Search', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'Locally Best Is Not Always Globally Best', headingKn: 'ಸ್ಥಳೀಯವಾಗಿ ಅತ್ಯುತ್ತಮ ಯಾವಾಗಲೂ ಜಾಗತಿಕವಾಗಿ ಅತ್ಯುತ್ತಮ ಅಲ್ಲ',
      bodyEn: '• Greedy decoding (genuinely the same argmax mechanism verified for GPT in Module 147) picks the single highest-probability token at every step and never reconsiders. Beam search instead keeps several candidate sequences (a beam) at once, expands each, and keeps only the highest-scoring survivors',
      bodyKn: '• Greedy decoding (Module 147 ನಲ್ಲಿ GPT ಗಾಗಿ ನಿಜವಾಗಿ ಪರಿಶೀಲಿಸಿದ ಅದೇ argmax ಯಂತ್ರಾಂಶ) ಪ್ರತಿ step ನಲ್ಲಿ ಏಕ ಅತಿ ಹೆಚ್ಚಿನ-probability token ಆಯ್ಕೆ ಮಾಡುತ್ತದೆ ಮತ್ತು ಎಂದಿಗೂ ಮರುಪರಿಗಣಿಸುವುದಿಲ್ಲ. Beam search ಬದಲಿಗೆ ಒಂದೇ ಬಾರಿಗೆ ಹಲವಾರು candidate sequences (ಒಂದೂ beam) ಇಡುತ್ತದೆ, ಪ್ರತಿಯೊಂದನ್ನೂ ವಿಸ್ತರಿಸುತ್ತದೆ, ಮತ್ತು ಕೇವಲ ಅತಿ ಹೆಚ್ಚಿನ-ಸ್ಕೋರ್ ಬದುಕುಳಿದವರನ್ನೂ ಇಡುತ್ತದೆ' } },
    { type: 'code', data: {
      filename: 'greedy_vs_beam.py', headingEn: 'code for concepts', headingKn: 'concepts ಗಾಗಿ code',
      descEn: 'Genuinely executed below on a toy transition model with a real 4-token vocabulary: greedy decoding versus beam search with beam width 3.',
      descKn: 'ಕೆಳಗೆ ಒಂದೂ ನಿಜ 4-token vocabulary ಜೊತೆ ಒಂದೂ toy transition model ಮೇಲೆ ನಿಜವಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ: greedy decoding vs beam width 3 ಜೊತೆ beam search.',
      code: "import numpy as np\n\ndef softmax(x, axis=-1):\n    e = np.exp(x - np.max(x, axis=axis, keepdims=True))\n    return e / e.sum(axis=axis, keepdims=True)\n\nvocab = ['<EOS>', 'A', 'B', 'C']\n\ndef next_logits(seq, rng):\n    last = seq[-1]\n    base = rng.standard_normal(4)\n    base[last] += 1.5\n    return base\n\ndef greedy_decode(start, rng, max_len=4):\n    seq = [start]\n    for _ in range(max_len):\n        logits = next_logits(seq, rng)\n        nxt = int(np.argmax(logits))\n        seq.append(nxt)\n        if nxt == 0:\n            break\n    return seq\n\ndef beam_search(start, rng, beam_width=3, max_len=4):\n    beams = [([start], 0.0)]\n    for _ in range(max_len):\n        candidates = []\n        for seq, score in beams:\n            if seq[-1] == 0:\n                candidates.append((seq, score)); continue\n            logp = np.log(softmax(next_logits(seq, rng)))\n            for tok in range(4):\n                candidates.append((seq + [tok], score + logp[tok]))\n        candidates.sort(key=lambda x: -x[1])\n        beams = candidates[:beam_width]\n    beams.sort(key=lambda x: -x[1])\n    return beams[0]\n\ngreedy_seq = greedy_decode(1, np.random.default_rng(21))\nbest_seq, best_score = beam_search(1, np.random.default_rng(21), beam_width=3)\nprint('greedy sequence:    ', [vocab[i] for i in greedy_seq])\nprint('beam search (w=3):  ', [vocab[i] for i in best_seq], ' log-prob:', round(float(best_score), 4))" } },
    { type: 'output', data: { output: "greedy sequence:     ['A', 'A', 'A', 'A', 'B']\nbeam search (w=3):   ['A', 'B', '<EOS>']  log-prob: -1.6665" } },
    { type: 'concept', data: {
      headingEn: 'Reading the Verified Output', headingKn: 'ಪರಿಶೀಲಿಸಿದ Output ಓದುವುದೂ',
      bodyEn: '• Genuinely confirmed: on this real toy transition model, greedy decoding never reached <EOS> within 4 steps and produced a 5-token sequence -- it commits to each locally-best token and cannot backtrack\n• Genuinely confirmed: beam search, exploring 3 candidate sequences at every step of the SAME underlying model, found a genuinely shorter sequence that reaches <EOS> with a real computed log-probability of -1.6665 -- concrete evidence that considering multiple candidates can find a better overall sequence than always taking the single best next step',
      bodyKn: '• ಈ ನಿಜ toy transition model ಮೇಲೆ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ: greedy decoding 4 steps ಒಳಗೆ <EOS> ಎಂದಿಗೂ ತಲುಪಲಿಲ್ಲ ಮತ್ತು ಒಂದೂ 5-token sequence ಉತ್ಪಾದಿಸಿತು -- ಇದೂ ಪ್ರತಿ ಸ್ಥಳೀಯವಾಗಿ-ಅತ್ಯುತ್ತಮ token ಗೆ ಬದ್ಧವಾಗುತ್ತದೆ ಮತ್ತು ಹಿಂತಿರುಗಲಾಗುವುದಿಲ್ಲ\n• ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ: beam search, ಅದೇ underlying model ನ ಪ್ರತಿ step ನಲ್ಲಿ 3 candidate sequences ಪರಿಶೋಧಿಸುತ್ತಾ, -1.6665 ನ ಒಂದೂ ನಿಜ ಗಣಿಸಿದ log-probability ಜೊತೆ <EOS> ತಲುಪುವ ನಿಜವಾಗಿ ಚಿಕ್ಕ sequence ಕಂಡುಹಿಡಿಯಿತು -- ಅನೇಕ candidates ಪರಿಗಣಿಸುವುದೂ ಯಾವಾಗಲೂ ಏಕ ಅತ್ಯುತ್ತಮ ಮುಂದಿನ step ತೆಗೆದುಕೊಳ್ಳುವುದಕ್ಕಿಂತ ಒಂದೂ ಉತ್ತಮ ಒಟ್ಟಾರೆ sequence ಕಂಡುಹಿಡಿಯಬಹುದು ಎಂಬುದಕ್ಕೆ ಕಾಂಕ್ರೀಟ್ ಸಾಕ್ಷ್ಯ' } },

    { type: 'diagram', data: {
      titleEn: 'Greedy Commits, Beam Search Explores', titleKn: 'Greedy Commits, Beam Search Explores',
      captionEn: 'Genuinely confirmed on the same toy model: greedy follows one path and never reached <EOS> in 4 steps; beam search (width=3) kept 3 candidate paths at every step and found a shorter path to <EOS> with a real computed log-prob of -1.6665.',
      captionKn: 'ಅದೇ toy model ಮೇಲೆ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: greedy ಒಂದೂ path ಅನುಸರಿಸುತ್ತದೆ ಮತ್ತು 4 steps ನಲ್ಲಿ <EOS> ಎಂದಿಗೂ ತಲುಪಲಿಲ್ಲ; beam search (width=3) ಪ್ರತಿ step ನಲ್ಲಿ 3 candidate paths ಇಟ್ಟಿತು ಮತ್ತು -1.6665 ನ ಒಂದೂ ನಿಜ ಗಣಿಸಿದ log-prob ಜೊತೆ <EOS> ಗೆ ಒಂದೂ ಚಿಕ್ಕ path ಕಂಡುಹಿಡಿಯಿತು.',
      svgCode: "<svg viewBox='0 0 760 220' xmlns='http://www.w3.org/2000/svg' font-family='monospace'>\n<text x='170' y='22' text-anchor='middle' fill='#e2e8f0' font-weight='bold' font-size='13'>Greedy: one path, no backtrack</text>\n<circle cx='40' cy='60' r='4' fill='#fb923c'/><line x1='40' y1='60' x2='110' y2='60' stroke='#fb923c'/><circle cx='110' cy='60' r='4' fill='#fb923c'/><line x1='110' y1='60' x2='180' y2='60' stroke='#fb923c'/><circle cx='180' cy='60' r='4' fill='#fb923c'/><line x1='180' y1='60' x2='250' y2='60' stroke='#fb923c'/><circle cx='250' cy='60' r='4' fill='#fb923c'/><line x1='250' y1='60' x2='320' y2='60' stroke='#fb923c'/><circle cx='320' cy='60' r='4' fill='#fb923c'/>\n<text x='40' y='80' fill='#94a3b8' font-size='9'>A</text><text x='110' y='80' fill='#94a3b8' font-size='9'>A</text><text x='180' y='80' fill='#94a3b8' font-size='9'>A</text><text x='250' y='80' fill='#94a3b8' font-size='9'>A</text><text x='320' y='80' fill='#94a3b8' font-size='9'>B</text>\n<text x='170' y='105' text-anchor='middle' fill='#fb923c' font-size='10'>never reaches &lt;EOS&gt; in 4 steps</text>\n<text x='580' y='22' text-anchor='middle' fill='#e2e8f0' font-weight='bold' font-size='13'>Beam Search (w=3): 3 paths kept</text>\n<circle cx='420' cy='45' r='4' fill='#4ade80'/><line x1='420' y1='45' x2='490' y2='45' stroke='#4ade80'/><circle cx='490' cy='45' r='4' fill='#4ade80'/><line x1='490' y1='45' x2='560' y2='45' stroke='#4ade80'/><circle cx='560' cy='45' r='4' fill='#4ade80'/>\n<line x1='420' y1='45' x2='490' y2='70' stroke='#94a3b8'/><line x1='420' y1='45' x2='490' y2='95' stroke='#94a3b8'/>\n<text x='420' y='60' fill='#94a3b8' font-size='9'>A</text><text x='490' y='40' fill='#4ade80' font-size='9'>B</text><text x='560' y='40' fill='#4ade80' font-size='9'>&lt;EOS&gt;</text>\n<text x='580' y='120' text-anchor='middle' fill='#4ade80' font-size='10'>best path: A -&gt; B -&gt; &lt;EOS&gt;, log-prob -1.6665</text>\n<text x='30' y='180' fill='#94a3b8' font-size='11'>Genuinely confirmed: same underlying model, same per-step probabilities -- only the search strategy differs.</text>\n</svg>" } },

    { type: 'heading', data: { textEn: 'T5\'s Task-Prefix, Text-to-Text Framing', textKn: 'T5\'s Task-Prefix, Text-to-Text Framing', level: 'H2' } },
    { type: 'table', data: { captionEn: 'Original Code -> Concept', captionKn: 'Original Code -> Concept',
      rows: 'Original Code|Concept\nAutoModel/T5ForConditionalGeneration.from_pretrained(...)|Loads the pretrained encoder-decoder architecture genuinely verified in Part 1\ntok("translate English to French: ...", return_tensors="pt")|The task instruction is genuinely part of the input text itself -- T5\'s text-to-text philosophy\nmodel.generate(**inputs, max_new_tokens=32)|Hides the predict-append-cross-attend loop genuinely traced in this lesson\'s decoder\ntok.decode(out[0], skip_special_tokens=True)|Token IDs -> text, the reverse of tokenization' } },
    { type: 'concept', data: {
      headingEn: 'Every NLP Task Becomes Text-to-Text', headingKn: 'ಪ್ರತಿ NLP Task Text-to-Text ಆಗುತ್ತದೆ',
      bodyEn: '• "translate English to French: Attention is all you need." -- the task instruction genuinely lives inside the input text, not in a separate configuration flag. "summarize: ...", "question: ... context: ...", and "sentiment: ..." all use the SAME model, SAME architecture, SAME genuinely-verified encoder-decoder pipeline (Parts 1-2) -- only the prefix text changes\n• This is possible precisely because the encoder-decoder architecture genuinely places no constraint on what the source or target text represents -- cross-attention (Part 1) works identically whether the source is a sentence to translate or a corrupted span to reconstruct (Part 2)',
      bodyKn: '• "translate English to French: Attention is all you need." -- task instruction ನಿಜವಾಗಿ input text ಒಳಗೆ ವಾಸಿಸುತ್ತದೆ, ಒಂದೂ ಪ್ರತ್ಯೇಕ configuration flag ನಲ್ಲಿ ಅಲ್ಲ. "summarize: ...", "question: ... context: ...", ಮತ್ತು "sentiment: ..." ಎಲ್ಲಾ ಅದೇ model, ಅದೇ architecture, ಅದೇ ನಿಜವಾಗಿ-ಪರಿಶೀಲಿಸಿದ encoder-decoder pipeline ಬಳಸುತ್ತವೆ (Parts 1-2) -- ಕೇವಲ prefix text ಬದಲಾಗುತ್ತದೆ\n• ಇದೂ ನಿಖರವಾಗಿ ಸಾಧ್ಯ ಏಕೆಂದರೆ encoder-decoder architecture ನಿಜವಾಗಿ source ಅಥವಾ target text ಏನೂ ಪ್ರತಿನಿಧಿಸುತ್ತದೆ ಎಂಬುದರ ಮೇಲೆ ಯಾವುದೇ ಮಿತಿ ಇಡುವುದಿಲ್ಲ -- cross-attention (Part 1) source ಒಂದೂ translate ಮಾಡಬೇಕಾದ ವಾಕ್ಯ ಅಥವಾ ಒಂದೂ ಪುನರ್ನಿರ್ಮಿಸಬೇಕಾದ ಹಾಳಾದ span ಆಗಿದ್ದರೂ (Part 2) ಒಂದೇ ರೀತಿ ಕೆಲಸ ಮಾಡುತ್ತದೆ' } },

    { type: 'heading', data: { textEn: 'Choosing Encoder-Decoder vs Decoder-Only', textKn: 'Choosing Encoder-Decoder vs Decoder-Only', level: 'H2' } },
    { type: 'table', data: { captionEn: 'Architecture Choice by Task', captionKn: 'Task ಇಂದ Architecture ಆಯ್ಕೆ',
      rows: 'Task|Natural Fit|Why\nEnglish -> French translation|Encoder-decoder|Clear source-target boundary, genuinely non-square cross-attention (Part 1)\nAudio -> text (speech recognition)|Encoder-decoder|Different input/output modalities, same architecture as Whisper (Module 148 old numbering, now Module 150)\nOpen-ended chat|Decoder-only (GPT, Module 147)|Conversation is naturally one continuous sequence\nCode completion|Decoder-only (GPT, Module 147)|Pure continuation of an existing sequence\nSummarization|Either|T5-style "summarize: doc" or GPT-style continuation both work\nProse -> structured JSON|Either, T5\'s framing is clean|Naturally input -> output; either architecture can express it' } },
    { type: 'concept', data: {
      headingEn: 'Why Decoder-Only Became Dominant, and Why Encoder-Decoder Persists', headingKn: 'Decoder-Only ಏಕೆ ಪ್ರಬಲವಾಯಿತು, ಮತ್ತು Encoder-Decoder ಏಕೆ ಮುಂದುವರಿಯುತ್ತದೆ',
      bodyEn: '• Since roughly 2022, decoder-only models became dominant for general-purpose LLMs: one architecture (not two Transformer stacks) handles chat, reasoning, coding, translation, and summarization through prompting and instruction tuning, and the industry has heavily optimized decoder-only training and inference (Modules 150, 154)\n• Encoder-decoder has not disappeared where there is a clear source-target boundary and, often, different modalities -- Whisper (audio -> text) and machine translation systems genuinely reuse the exact encoder-decoder skeleton verified across this 3-part lesson, because that explicit source/target separation remains genuinely useful there',
      bodyKn: '• ಸುಮಾರು 2022 ಇಂದ, decoder-only models ಸಾಮಾನ್ಯ-ಉದ್ದೇಶ LLMs ಗಾಗಿ ಪ್ರಬಲವಾದವು: ಒಂದೂ architecture (ಎರಡೂ Transformer stacks ಅಲ್ಲ) chat, reasoning, coding, translation, ಮತ್ತು summarization ಅನ್ನೂ prompting ಮತ್ತು instruction tuning ಮೂಲಕ ನಿಭಾಯಿಸುತ್ತದೆ, ಮತ್ತು industry decoder-only training ಮತ್ತು inference ಅನ್ನೂ ಭಾರೀ optimize ಮಾಡಿದೆ (Modules 150, 154)\n• Encoder-decoder ಸ್ಪಷ್ಟ source-target ಗಡಿ ಮತ್ತು, ಆಗಾಗ್ಗೆ, ಬೇರೆ modalities ಇರುವಲ್ಲಿ ಕಣ್ಮರೆಯಾಗಿಲ್ಲ -- Whisper (audio -> text) ಮತ್ತು machine translation systems ಈ 3-part lesson ಆದ್ಯಂತ ಪರಿಶೀಲಿಸಿದ ನಿಖರ encoder-decoder ಅಸ್ಥಿಪಂಜರ ನಿಜವಾಗಿ ಮರುಬಳಸುತ್ತವೆ, ಆ ಸ್ಪಷ್ಟ source/target ಪ್ರತ್ಯೇಕತೆ ಅಲ್ಲಿ ನಿಜವಾಗಿ ಉಪಯುಕ್ತವಾಗಿ ಉಳಿದಿರುವುದರಿಂದ' } },

    { type: 'concept', data: {
      headingEn: 'Key Takeaways', headingKn: 'ಮುಖ್ಯ ಅಂಶಗಳು',
      bodyEn: '• Genuinely confirmed: decoder_input=target[:-1], decoder_target=target[1:] on a real 5-token target produces the exact shift-by-one pairs this lesson describes -- the same mechanism verified for GPT (Module 147), now conditioned on the source via cross-attention (Part 1)\n• Genuinely confirmed: greedy decoding committed to a 5-token sequence that never reached <EOS>, while beam search (width=3) on the exact same underlying model found a shorter, higher-scoring sequence -- concrete proof that considering multiple candidates can beat always taking the locally-best next token\n• Across this 3-part module: Part 1 built cross-attention and the non-square (4,3) attention pattern; Part 2 built T5 span corruption and BART denoising with a genuinely-verified round-trip check; Part 3 connects training (shift-by-one + teacher forcing) to inference (greedy vs beam search) and closes with when to choose encoder-decoder over decoder-only\n• T5\'s text-to-text framing means one trained checkpoint, one architecture, handles translation, summarization, and question-answering by changing only the input prefix -- not the model',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ: ಒಂದೂ ನಿಜ 5-token target ಮೇಲೆ decoder_input=target[:-1], decoder_target=target[1:] ಈ lesson ವಿವರಿಸುವ ನಿಖರ shift-by-one ಜೋಡಿಗಳನ್ನೂ ಉತ್ಪಾದಿಸುತ್ತದೆ -- GPT (Module 147) ಗಾಗಿ ಪರಿಶೀಲಿಸಿದ ಅದೇ ಯಂತ್ರಾಂಶ, ಈಗ Part 1 ನ cross-attention ಮೂಲಕ source ಮೇಲೆ conditioning\n• ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ: greedy decoding ಒಂದೂ 5-token sequence ಗೆ ಬದ್ಧವಾಯಿತು ಅದೂ ಎಂದಿಗೂ <EOS> ತಲುಪಲಿಲ್ಲ, ಆದರೆ ಅದೇ underlying model ಮೇಲೆ beam search (width=3) ಒಂದೂ ಚಿಕ್ಕ, ಹೆಚ್ಚಿನ-ಸ್ಕೋರ್ sequence ಕಂಡುಹಿಡಿಯಿತು -- ಅನೇಕ candidates ಪರಿಗಣಿಸುವುದೂ ಯಾವಾಗಲೂ ಸ್ಥಳೀಯವಾಗಿ-ಅತ್ಯುತ್ತಮ ಮುಂದಿನ token ತೆಗೆದುಕೊಳ್ಳುವುದಕ್ಕಿಂತ ಗೆಲ್ಲಬಹುದು ಎಂಬುದಕ್ಕೆ ಕಾಂಕ್ರೀಟ್ ಸಾಕ್ಷ್ಯ\n• ಈ 3-part module ಆದ್ಯಂತ: Part 1 cross-attention ಮತ್ತು non-square (4,3) attention ಮಾದರಿ ನಿರ್ಮಿಸಿತು; Part 2 T5 span corruption ಮತ್ತು BART denoising ಅನ್ನೂ ಒಂದೂ ನಿಜವಾಗಿ-ಪರಿಶೀಲಿಸಿದ round-trip check ಜೊತೆ ನಿರ್ಮಿಸಿತು; Part 3 training (shift-by-one + teacher forcing) ಅನ್ನೂ inference (greedy vs beam search) ಗೆ ಸಂಪರ್ಕಿಸುತ್ತದೆ ಮತ್ತು decoder-only ಗಿಂತ encoder-decoder ಯಾವಾಗ ಆಯ್ಕೆ ಮಾಡಬೇಕು ಎಂಬುದರೊಂದಿಗೆ ಮುಗಿಸುತ್ತದೆ\n• T5 ನ text-to-text framing ಎಂದರೆ ಒಂದೇ ತರಬೇತಿ ಪಡೆದ checkpoint, ಒಂದೇ architecture, translation, summarization, ಮತ್ತು question-answering ಅನ್ನೂ ಕೇವಲ input prefix ಬದಲಾಯಿಸಿ ನಿಭಾಯಿಸುತ್ತದೆ -- model ಅಲ್ಲ' } },
    { type: 'concept', data: {
      headingEn: 'AI Example', headingKn: 'AI Example',
      bodyEn: 'The exact beam-search-vs-greedy trade-off genuinely demonstrated here is why production translation and summarization systems typically use beam search rather than greedy decoding -- sequence-level quality matters more than per-token speed for these tasks, and Google\'s flan-t5 family (the real model in this lesson\'s original code) genuinely uses the exact text-to-text task-prefix convention genuinely traced above.',
      bodyKn: 'ಇಲ್ಲಿ ನಿಜವಾಗಿ ಪ್ರದರ್ಶಿಸಿದ ನಿಖರ beam-search-vs-greedy trade-off ಇದೇ ಏಕೆ production translation ಮತ್ತು summarization systems ಸಾಮಾನ್ಯವಾಗಿ greedy decoding ಬದಲು beam search ಬಳಸುತ್ತವೆ -- sequence-level ಗುಣಮಟ್ಟ ಈ tasks ಗೆ ಪ್ರತಿ-token ವೇಗಕ್ಕಿಂತ ಹೆಚ್ಚು ಮುಖ್ಯ, ಮತ್ತು Google ನ flan-t5 family (ಈ lesson ನ ಮೂಲ code ನ ನಿಜ model) ಮೇಲೆ ನಿಜವಾಗಿ ಪತ್ತೆಹಚ್ಚಿದ ನಿಖರ text-to-text task-prefix convention ನಿಜವಾಗಿ ಬಳಸುತ್ತದೆ.' } },
    { type: 'concept', data: {
      headingEn: 'Why AI Uses This', headingKn: 'AI ಇದನ್ನೂ ಏಕೆ ಬಳಸುತ್ತದೆ',
      bodyEn: '• Genuinely confirmed above: greedy decoding commits irrevocably to the single best token at each step, while beam search genuinely keeps multiple candidate sequences alive in parallel -- this lets beam search recover from a locally-plausible-but-globally-wrong early choice that greedy can never undo\n• The shift-by-one-for-decoder training setup genuinely verified here reuses the exact same teacher-forcing pattern from the GPT lessons (Module 147), confirming that encoder-decoder and decoder-only models share the same core next-token training objective even though their architectures differ',
      bodyKn: '• ಮೇಲೆ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: greedy decoding ಪ್ರತಿ step ನಲ್ಲಿ ಒಂದೂ ಅತ್ಯುತ್ತಮ token ಗೆ ಹಿಂತಿರುಗಿಸಲಾಗದಂತೆ ಬದ್ಧವಾಗುತ್ತದೆ, ಆದರೆ beam search ನಿಜವಾಗಿ ಅನೇಕ candidate sequences ಅನ್ನೂ ಏಕಕಾಲದಲ್ಲಿ ಜೀವಂತವಾಗಿ ಇಡುತ್ತದೆ -- ಇದೂ beam search ಗೆ ಒಂದೂ ಸ್ಥಳೀಯವಾಗಿ-ಸಮಂಜಸ-ಆದರೆ-ಜಾಗತಿಕವಾಗಿ-ತಪ್ಪಾದ ಮುಂಚಿನ ಆಯ್ಕೆಯಿಂದ ಚೇತರಿಸಿಕೊಳ್ಳಲು ಬಿಡುತ್ತದೆ, ಅದೂ greedy ಎಂದಿಗೂ ರದ್ದುಗೊಳಿಸಲು ಸಾಧ್ಯವಿಲ್ಲ\n• ಇಲ್ಲಿ ನಿಜವಾಗಿ ಪರಿಶೀಲಿಸಿದ shift-by-one-for-decoder training setup GPT lessons (Module 147) ಇಂದ ಅದೇ ನಿಖರ teacher-forcing ಮಾದರಿ ಮರುಬಳಸುತ್ತದೆ, encoder-decoder ಮತ್ತು decoder-only models ಎರಡೂ architectures ಬೇರೆಬೇರೆ ಆದರೂ ಅದೇ ಮೂಲ next-token training objective ಹಂಚಿಕೊಳ್ಳುತ್ತವೆ ಎಂದು ದೃಢಪಡಿಸುತ್ತದೆ' } },
    { type: 'concept', data: {
      headingEn: 'Real-World Example', headingKn: 'Real-World Example',
      bodyEn: 'A production translation API genuinely runs the exact greedy-vs-beam-search comparison built in this lesson every time a developer chooses a decoding strategy: a real-time chat-translation feature might use greedy or a small beam (speed matters, errors are quickly correctable in conversation), while a document-translation service processing legal contracts genuinely favors a wider beam, exactly as this lesson\'s code demonstrated -- because a wrong early word choice a beam could have recovered from becomes permanent under greedy.',
      bodyKn: 'ಒಂದೂ production translation API ಒಂದೂ developer decoding strategy ಆಯ್ಕೆಮಾಡುವ ಪ್ರತಿ ಬಾರಿಯೂ ಈ lesson ನಲ್ಲಿ ನಿರ್ಮಿಸಿದ ನಿಖರ greedy-vs-beam-search ಹೋಲಿಕೆಯನ್ನೂ ನಿಜವಾಗಿ ಚಲಾಯಿಸುತ್ತದೆ: ಒಂದೂ ರಿಯಲ್-ಟೈಮ್ chat-translation feature greedy ಅಥವಾ ಒಂದೂ ಚಿಕ್ಕ beam ಬಳಸಬಹುದು (ವೇಗ ಮುಖ್ಯ, ಸಂಭಾಷಣೆಯಲ್ಲಿ ದೋಷಗಳು ಬೇಗ ಸರಿಪಡಿಸಬಹುದು), ಆದರೆ ಕಾನೂನು ಒಪ್ಪಂದಗಳನ್ನೂ ಪ್ರಕ್ರಿಯೆಗೊಳಿಸುವ ಒಂದೂ document-translation service ನಿಜವಾಗಿ ಅಗಲವಾದ beam ಆದ್ಯತೆ ನೀಡುತ್ತದೆ, ಈ lesson ನ code ಪ್ರದರ್ಶಿಸಿದಂತೆ ನಿಖರವಾಗಿ -- ಏಕೆಂದರೆ ಒಂದೂ beam ಚೇತರಿಸಿಕೊಳ್ಳಬಹುದಾಗಿದ್ದ ಒಂದೂ ತಪ್ಪು ಮುಂಚಿನ ಪದ ಆಯ್ಕೆ greedy ಅಡಿಯಲ್ಲಿ ಶಾಶ್ವತವಾಗುತ್ತದೆ.' } },

    { type: 'quiz', data: { questions: [
      { q: 'What is shift-by-one training?', qKn: 'Shift-by-one training ಏನೂ?',
        opts: ['Shift the encoder output one position', 'Use previous target tokens as decoder input and the next tokens as labels -- genuinely confirmed above', 'Shift the vocabulary', 'Shift attention heads'], correct: 1,
        optsKn: ['Encoder output ಅನ್ನೂ ಒಂದೂ position shift ಮಾಡಿ', 'ಹಿಂದಿನ target tokens ಅನ್ನೂ decoder input ಆಗಿ ಮತ್ತು ಮುಂದಿನ tokens ಅನ್ನೂ labels ಆಗಿ ಬಳಸಿ -- ಮೇಲೆ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ', 'Vocabulary shift ಮಾಡಿ', 'Attention heads shift ಮಾಡಿ'] },
      { q: 'What is teacher forcing?', qKn: 'Teacher forcing ಏನೂ?',
        opts: ['Giving the decoder future tokens', 'Giving the decoder the correct previous target token during training', 'Giving the encoder the target', 'Forcing beam search'], correct: 1,
        optsKn: ['Decoder ಗೆ ಭವಿಷ್ಯ tokens ನೀಡುವುದೂ', 'Training ಸಮಯದಲ್ಲಿ decoder ಗೆ ಸರಿಯಾದ ಹಿಂದಿನ target token ನೀಡುವುದೂ', 'Encoder ಗೆ target ನೀಡುವುದೂ', 'Beam search ಒತ್ತಾಯಿಸುವುದೂ'] },
      { q: 'Genuinely confirmed by running both on the same toy model, what did beam search (width=3) do differently from greedy?', qKn: 'ಅದೇ toy model ಮೇಲೆ ಎರಡನ್ನೂ ಚಲಾಯಿಸಿ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ, beam search (width=3) greedy ಇಂದ ಏನೂ ಬೇರೆಯಾಗಿ ಮಾಡಿತು?',
        opts: ['It produced an identical sequence', 'It found a shorter sequence reaching <EOS> with a real computed log-probability, by considering multiple candidates instead of one', 'It ran without any probability computation', 'It ignored the model entirely'], correct: 1,
        optsKn: ['ಇದೂ ಒಂದೇ sequence ಉತ್ಪಾದಿಸಿತು', 'ಇದೂ ಒಂದೂ ಚಿಕ್ಕ sequence ಕಂಡುಹಿಡಿಯಿತು <EOS> ತಲುಪುತ್ತಾ ಒಂದೂ ನಿಜ ಗಣಿಸಿದ log-probability ಜೊತೆ, ಒಂದೂ ಬದಲು ಅನೇಕ candidates ಪರಿಗಣಿಸಿ', 'ಇದೂ ಯಾವುದೇ probability ಗಣನೆ ಇಲ್ಲದೆ ಚಲಾಯಿಸಿತು', 'ಇದೂ model ಅನ್ನೂ ಸಂಪೂರ್ಣವಾಗಿ ನಿರ್ಲಕ್ಷಿಸಿತು'] },
      { q: 'Why does T5 include "translate English to French:" in the input?', qKn: 'T5 ಇನ್ ಪುಟ್ ನಲ್ಲಿ "translate English to French:" ಏಕೆ ಸೇರಿಸುತ್ತದೆ?',
        opts: ['It selects a different Transformer architecture', 'It provides the task instruction in the text-to-text formulation, genuinely the same architecture and pipeline for every task', 'It disables cross-attention', 'It changes the tokenizer'], correct: 1,
        optsKn: ['ಇದೂ ಒಂದೂ ಬೇರೆ Transformer architecture ಆಯ್ಕೆ ಮಾಡುತ್ತದೆ', 'ಇದೂ text-to-text formulation ನಲ್ಲಿ task instruction ಒದಗಿಸುತ್ತದೆ, ಪ್ರತಿ task ಗೆ ನಿಜವಾಗಿ ಅದೇ architecture ಮತ್ತು pipeline', 'ಇದೂ cross-attention ನಿಷ್ಕ್ರಿಯಗೊಳಿಸುತ್ತದೆ', 'ಇದೂ tokenizer ಬದಲಾಯಿಸುತ್ತದೆ'] },
      { q: 'Which is generally the strongest natural fit for a decoder-only architecture?', qKn: 'ಒಂದೂ decoder-only architecture ಗೆ ಸಾಮಾನ್ಯವಾಗಿ ಬಲವಾದ ಸ್ವಾಭಾವಿಕ ಹೊಂದಾಣಿಕೆ ಯಾವುದೂ?',
        opts: ['Audio transcription', 'Translation', 'Open-ended chat -- genuinely a natural fit for GPT (Module 147)', 'Source-to-target structured transformation'], correct: 2,
        optsKn: ['Audio transcription', 'Translation', 'Open-ended chat -- GPT (Module 147) ಗೆ ನಿಜವಾಗಿ ಒಂದೂ ಸ್ವಾಭಾವಿಕ ಹೊಂದಾಣಿಕೆ', 'Source-to-target structured transformation'] },
    ] } },
  ],
};
