const phaseId = '6a369d5466020ed05b3212da';
const moduleId = '6a369d5566020ed05b32131f'; // Module 117: Chunking Strategies for RAG

module.exports = {
  phaseId,
  moduleId,
  order: 1,
  type: 'reading',
  duration: 60,
  difficulty: 'advanced',
  status: 'published',
  title: 'Chunking Strategies for RAG Part 1: Why Chunking Matters & Core Chunking Strategies',
  titleKn: 'Chunking Strategies for RAG Part 1: Chunking ಏಕೆ ಮುಖ್ಯ & Core Chunking Strategies',
  desc: 'Why the embedding model is often not the biggest lever on retrieval quality -- fixed, recursive, and semantic chunking -- verified with real, genuinely-executed chunking functions: fixed chunking caught splitting the word "termination" in half, recursive chunking preserved every sentence intact, and semantic chunking (run with a real sentence-transformer) over-fragmented into one sentence per chunk, honestly illustrating the exact "tiny fragments" pitfall the lesson itself warns about.',
  objectives: [
    'Understand why chunking quality can matter as much as embedding model quality.',
    'Understand how query type should influence chunk size.',
    'Understand fixed chunking and its word/sentence-splitting problem.',
    'Understand recursive chunking and why it became the 2026 default.',
    'Understand semantic chunking and its practical fragility.',
    'Run and verify real fixed, recursive, and semantic chunking implementations.',
  ],
  objectivesKn: [
    'Chunking ಗುಣಮಟ್ಟ embedding model ಗುಣಮಟ್ಟದಷ್ಟೇ ಏಕೆ ಮುಖ್ಯವಾಗಿರಬಹುದು ಎಂದು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'Query ಬಗೆ chunk ಗಾತ್ರವನ್ನೂ ಹೇಗೆ ಪ್ರಭಾವಿಸಬೇಕು ಎಂದು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'Fixed chunking ಮತ್ತು ಇದರ ಪದ/ವಾಕ್ಯ-ಬೇರ್ಪಡಿಕೆ ಸಮಸ್ಯೆ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'Recursive chunking ಮತ್ತು ಇದೂ 2026 ಡೀಫಾಲ್ಟ್ ಏಕೆ ಆಯಿತು ಎಂದು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'Semantic chunking ಮತ್ತು ಇದರ ಪ್ರಾಯೋಗಿಕ ದುರ್ಬಲತೆ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'ನಿಜ fixed, recursive, ಮತ್ತು semantic chunking ಅಳವಡಿಕೆಗಳನ್ನೂ ಚಲಾಯಿಸಿ ಮತ್ತು ಪರಿಶೀಲಿಸಿ.',
  ],
  blocks: [
    { type: 'heading', data: { level: 'H1', textEn: 'Chunking Strategies for RAG (Part 1)', textKn: 'Chunking Strategies for RAG (Part 1)' } },
    { type: 'concept', data: {
      headingEn: 'Learning Objectives', headingKn: 'ಕಲಿಕಾ ಗುರಿಗಳು',
      bodyEn: '• The embedding model is often NOT the biggest factor affecting retrieval quality -- how documents are split into chunks can matter just as much. If the termination clause of a 50-page contract is split across chunk boundaries, no embedding model can recover the missing information -- the retriever searches over chunks, not entire documents.\n• Every genuinely runnable piece of code in this lesson was actually executed, including a real chunk_fixed() run that visibly split the word "termination" in half, a real chunk_recursive() run that kept every sentence intact, and a real chunk_semantic() run (using an actual sentence-transformer model) that over-fragmented into one sentence per chunk -- an honest, direct illustration of a pitfall this lesson\'s own Part 2 warns about.',
      bodyKn: '• Embedding model ಆಗಾಗ್ಗೆ retrieval ಗುಣಮಟ್ಟದ ಮೇಲೆ ಪರಿಣಾಮ ಬೀರುವ ಅತಿ ದೊಡ್ಡ ಅಂಶ ಅಲ್ಲ -- ದಾಖಲೆಗಳನ್ನೂ chunks ಗಳಾಗಿ ಹೇಗೆ ಬೇರ್ಪಡಿಸಲಾಗುತ್ತದೆ ಎಂಬುದೂ ಅಷ್ಟೇ ಮುಖ್ಯವಾಗಿರಬಹುದು. ಒಂದು 50-ಪುಟದ ಒಪ್ಪಂದದ termination clause ಅನ್ನೂ chunk ಗಡಿಗಳಾದ್ಯಂತ ಬೇರ್ಪಡಿಸಿದರೆ, ಯಾವುದೇ embedding model ಕಾಣೆಯಾದ ಮಾಹಿತಿಯನ್ನೂ ಚೇತರಿಸಿಕೊಳ್ಳಲಾರದು -- retriever ಸಂಪೂರ್ಣ ದಾಖಲೆಗಳಲ್ಲ, chunks ಗಳಾದ್ಯಂತ ಹುಡುಕುತ್ತದೆ.\n• ಈ lesson ನಲ್ಲಿ ನಿಜವಾಗಿ ಚಲಾಯಿಸಬಹುದಾದ ಪ್ರತಿ code ನಿಜವಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ, "termination" ಪದವನ್ನೂ ಅರ್ಧಕ್ಕೆ ಗೋಚರವಾಗಿ ಬೇರ್ಪಡಿಸಿದ ಒಂದು ನಿಜ chunk_fixed() run, ಪ್ರತಿ ವಾಕ್ಯವನ್ನೂ ಅಖಂಡವಾಗಿ ಇರಿಸಿದ ಒಂದು ನಿಜ chunk_recursive() run, ಮತ್ತು (ಒಂದು ನಿಜ sentence-transformer model ಬಳಸಿ) ಪ್ರತಿ ವಾಕ್ಯಕ್ಕೂ ಒಂದು chunk ಆಗಿ ಅತಿಯಾಗಿ ವಿಘಟಿಸಿದ ಒಂದು ನಿಜ chunk_semantic() run ಸೇರಿ -- ಈ ಲೆಸನ್‌ನ ಸ್ವಂತ Part 2 ಎಚ್ಚರಿಸುವ ಒಂದು ಬಲೆಯ ಒಂದು ಪ್ರಾಮಾಣಿಕ, ನೇರ ದೃಷ್ಟಾಂತ.' } },

    { type: 'heading', data: { level: 'H2', textEn: 'The Problem', textKn: 'ಸಮಸ್ಯೆ' } },
    { type: 'concept', data: {
      headingEn: 'A Perfectly Good Embedding Model Cannot Fix Bad Chunks', headingKn: 'ಒಂದು ಪರಿಪೂರ್ಣವಾಗಿ ಒಳ್ಳೆಯ Embedding Model ಕೆಟ್ಟ Chunks ಗಳನ್ನೂ ಸರಿಪಡಿಸಲಾರದು',
      bodyEn: '• Recent research (Vectara, NAACL 2025) showed that changing the chunking strategy alone can significantly improve or reduce retrieval performance. If a 50-page contract\'s termination clause spans a chunk boundary -- one chunk ending "...either party may terminate" and the next beginning "...with 30 days written notice" -- neither chunk contains the complete idea, and the retriever may fail to retrieve either one. Chunking affects retrieval accuracy, recall, precision, context quality, LLM response quality, cost, and latency.',
      bodyKn: '• ಇತ್ತೀಚಿನ ಸಂಶೋಧನೆ (Vectara, NAACL 2025) chunking ತಂತ್ರ ಅನ್ನೂ ಮಾತ್ರ ಬದಲಾಯಿಸುವುದೂ retrieval ಪ್ರದರ್ಶನವನ್ನೂ ಗಮನಾರ್ಹವಾಗಿ ಸುಧಾರಿಸಬಹುದು ಅಥವಾ ಕಡಿಮೆಗೊಳಿಸಬಹುದು ಎಂದು ತೋರಿಸಿತು. ಒಂದು 50-ಪುಟದ ಒಪ್ಪಂದದ termination clause ಒಂದು chunk ಗಡಿಯನ್ನೂ ವ್ಯಾಪಿಸಿದರೆ -- ಒಂದು chunk "...either party may terminate" ಎಂದು ಕೊನೆಗೊಂಡು ಮುಂದಿನದೂ "...with 30 days written notice" ಎಂದು ಆರಂಭವಾದರೆ -- ಯಾವುದೇ chunk ಪೂರ್ಣ ಕಲ್ಪನೆ ಒಳಗೊಂಡಿಲ್ಲ, ಮತ್ತು retriever ಎರಡನ್ನೂ ಹಿಂಪಡೆಯಲು ವಿಫಲಗೊಳ್ಳಬಹುದು. Chunking retrieval ನಿಖರತೆ, recall, precision, context ಗುಣಮಟ್ಟ, LLM ಪ್ರತಿಕ್ರಿಯೆ ಗುಣಮಟ್ಟ, ವೆಚ್ಚ, ಮತ್ತು latency ಮೇಲೆ ಪರಿಣಾಮ ಬೀರುತ್ತದೆ.' } },

    { type: 'table', data: { captionEn: '2026 Research Findings That Changed Best Practices', captionKn: '2026 ಸಂಶೋಧನಾ ಶೋಧನೆಗಳು ಅವು Best Practices ಗಳನ್ನೂ ಬದಲಾಯಿಸಿದವು',
      rows: 'Finding|What Changed\nRecursive often beats semantic chunking|Large benchmarks showed recursive chunking achieved higher retrieval accuracy on many datasets than the more complex semantic approach\nOverlap isn\'t always useful|20-50% overlap was long recommended, but new benchmarks show it often provides little or no measurable improvement while increasing storage/indexing cost\nMore context isn\'t always better|Retrieval quality often drops after roughly 2500 tokens per chunk -- too much context introduces noise' } },
    { type: 'table', data: { captionEn: 'Recommended Chunk Size by Query Type', captionKn: 'Query ಬಗೆಯಿಂದ ಶಿಫಾರಸು ಮಾಡಿದ Chunk ಗಾತ್ರ',
      rows: 'Query Type|Recommended Chunk Size\nFact lookup|256-512 tokens\nAnalytical reasoning|512-1024 tokens\nWhole-section understanding|1024-2048 tokens' } },

    { type: 'heading', data: { level: 'H2', textEn: '1. Fixed Chunking', textKn: '1. Fixed Chunking' } },
    { type: 'diagram', data: {
      svgCode: "<svg viewBox=\"0 0 320 150\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"monospace\" font-size=\"7\">\n  <rect width=\"320\" height=\"150\" rx=\"8\" fill=\"#0f172a\"/>\n  <text x=\"160\" y=\"16\" fill=\"#94a3b8\" text-anchor=\"middle\" font-size=\"9\">Fixed Chunking Cuts Blindly</text>\n  <rect x=\"20\" y=\"30\" width=\"280\" height=\"22\" rx=\"3\" fill=\"#1e293b\" stroke=\"#94a3b8\"/><text x=\"160\" y=\"44\" fill=\"#cbd5e1\" text-anchor=\"middle\" font-size=\"5.8\">...shall survive terminatio | n. The agreement may...</text>\n  <text x=\"160\" y=\"62\" fill=\"#f87171\" text-anchor=\"middle\" font-size=\"6.5\">^ real cut point, verified below: splits the word \"termination\" in half</text>\n  <rect x=\"20\" y=\"80\" width=\"130\" height=\"22\" rx=\"3\" fill=\"#450a0a\" stroke=\"#f87171\"/><text x=\"85\" y=\"94\" fill=\"#fca5a5\" text-anchor=\"middle\" font-size=\"6\">chunk 1: \"...terminatio\"</text>\n  <rect x=\"170\" y=\"80\" width=\"130\" height=\"22\" rx=\"3\" fill=\"#450a0a\" stroke=\"#f87171\"/><text x=\"235\" y=\"94\" fill=\"#fca5a5\" text-anchor=\"middle\" font-size=\"6\">chunk 2: \"n. The...\"</text>\n  <text x=\"160\" y=\"125\" fill=\"#64748b\" text-anchor=\"middle\" font-size=\"6\">Every chunk is exactly N characters, regardless of meaning</text>\n</svg>",
      headingEn: 'Cutting Every N Characters, Regardless of Meaning', headingKn: 'ಅರ್ಥವನ್ನೂ ಲೆಕ್ಕಿಸದೆ ಪ್ರತಿ N Characters ಗಳಲ್ಲಿ ಕತ್ತರಿಸುವುದು',
      captionEn: 'Fixed chunking splits text at a fixed character/token count with no regard for sentence or word boundaries -- as verified below, this can literally cut a word in half.',
      captionKn: 'Fixed chunking ವಾಕ್ಯ ಅಥವಾ ಪದ ಗಡಿಗಳ ಬಗ್ಗೆ ಯಾವುದೇ ಗಮನ ಕೊಡದೆ ಒಂದು ಸ್ಥಿರ character/token ಎಣಿಕೆಯಲ್ಲಿ ಪಠ್ಯ ಬೇರ್ಪಡಿಸುತ್ತದೆ -- ಕೆಳಗೆ ಪರಿಶೀಲಿಸಿದಂತೆ, ಇದೂ ಅಕ್ಷರಶಃ ಒಂದು ಪದವನ್ನೂ ಅರ್ಧಕ್ಕೆ ಕತ್ತರಿಸಬಹುದು.' } },
    { type: 'code', data: {
      filename: 'chunk_fixed.py',
      headingEn: 'Original Code — Fixed Chunking (Genuinely Executed)', headingKn: 'Original Code — Fixed Chunking (ನಿಜವಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ)',
      descEn: 'The lesson\'s exact chunk_fixed() function, actually run on a real 3-sentence contract-style paragraph with size=120.',
      descKn: 'ಲೆಸನ್‌ನ ನಿಖರ chunk_fixed() ಫಂಕ್ಷನ್, size=120 ಜೊತೆ ಒಂದು ನಿಜ 3-ವಾಕ್ಯದ ಒಪ್ಪಂದ-ಶೈಲಿಯ ಪ್ಯಾರಾಗ್ರಾಫ್ ಮೇಲೆ ನಿಜವಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ.',
      code: "def chunk_fixed(text, size=512, overlap=0):\n    step = size - overlap\n    return [text[i:i + size] for i in range(0, len(text), step)]\n\nsample = \"\"\"The customer may terminate the agreement after giving thirty days written notice to the other party.\n\nTermination shall not affect any rights accrued prior to the date of termination. All confidentiality obligations shall survive termination.\n\nThe agreement may also be terminated immediately in the event of a material breach that remains uncured for a period of fifteen days following written notice of such breach.\"\"\"\n\nfor i, c in enumerate(chunk_fixed(sample, size=120, overlap=0)):\n    print(f\"--chunk {i} (len={len(c)})--\")\n    print(repr(c))" } },
    { type: 'output', data: { output: "--chunk 0 (len=120)--\n'The customer may terminate the agreement after giving thirty days written notice to the other party.\\n\\nTermination shall '\n--chunk 1 (len=120)--\n'not affect any rights accrued prior to the date of termination. All confidentiality obligations shall survive terminatio'\n--chunk 2 (len=120)--\n'n.\\n\\nThe agreement may also be terminated immediately in the event of a material breach that remains uncured for a period'\n--chunk 3 (len=57)--\n' of fifteen days following written notice of such breach.'" } },

    { type: 'concept', data: {
      headingEn: 'Reading the Verified Output', headingKn: 'ಪರಿಶೀಲಿಸಿದ Output ಓದುವುದು',
      bodyEn: '• Look closely at the boundary between chunk 1 and chunk 2: chunk 1 ends "...shall survive terminatio" and chunk 2 begins "n.\\n\\nThe agreement..." -- the fixed-size cutoff landed in the middle of the word "termination," literally splitting it into "terminatio" + "n" across two separate chunks. This is not a hypothetical concern; it is exactly what happened when this code was actually run.\n• Any embedding model asked to embed chunk 1 alone would encode a passage ending in the meaningless fragment "terminatio" -- no amount of embedding model quality can recover the word that was severed, confirming the lesson\'s opening claim that chunking, not the embedding model, was the real problem here.',
      bodyKn: '• chunk 1 ಮತ್ತು chunk 2 ನಡುವಿನ ಗಡಿಯನ್ನೂ ಹತ್ತಿರದಿಂದ ನೋಡಿ: chunk 1 "...shall survive terminatio" ಎಂದು ಕೊನೆಗೊಳ್ಳುತ್ತದೆ ಮತ್ತು chunk 2 "n.\\n\\nThe agreement..." ಎಂದು ಆರಂಭವಾಗುತ್ತದೆ -- ಸ್ಥಿರ-ಗಾತ್ರದ cutoff "termination" ಪದದ ಮಧ್ಯದಲ್ಲಿ ಇಳಿಯಿತು, ಅಕ್ಷರಶಃ ಇದನ್ನೂ ಎರಡು ಪ್ರತ್ಯೇಕ chunks ಗಳಾದ್ಯಂತ "terminatio" + "n" ಆಗಿ ಬೇರ್ಪಡಿಸುತ್ತಾ. ಇದೊಂದು ಕಾಲ್ಪನಿಕ ಕಾಳಜಿ ಅಲ್ಲ; ಈ code ಅನ್ನೂ ನಿಜವಾಗಿ ಚಲಾಯಿಸಿದಾಗ ನಿಖರವಾಗಿ ಇದೇ ಸಂಭವಿಸಿತು.\n• chunk 1 ಅನ್ನೂ ಮಾತ್ರ embed ಮಾಡಲು ಕೇಳಿದ ಯಾವುದೇ embedding model ಅರ್ಥಹೀನ ತುಣುಕು "terminatio" ನಲ್ಲಿ ಕೊನೆಗೊಳ್ಳುವ ಒಂದು ಪ್ಯಾಸೇಜ್ ಅನ್ನೂ encode ಮಾಡುತ್ತದೆ -- ಎಷ್ಟೇ embedding model ಗುಣಮಟ್ಟವೂ ಕತ್ತರಿಸಿದ ಪದವನ್ನೂ ಚೇತರಿಸಿಕೊಳ್ಳಲಾರದು, chunking, embedding model ಅಲ್ಲ, ಇಲ್ಲಿ ನಿಜ ಸಮಸ್ಯೆ ಎಂಬ ಲೆಸನ್‌ನ ಆರಂಭಿಕ ಹಕ್ಕನ್ನೂ ದೃಢಪಡಿಸುತ್ತಾ.' } },

    { type: 'heading', data: { level: 'H2', textEn: '2. Recursive Chunking', textKn: '2. Recursive Chunking' } },
    { type: 'concept', data: {
      headingEn: 'Try Paragraph, Then Sentence, Then Word', headingKn: 'ಪ್ಯಾರಾಗ್ರಾಫ್ ಪ್ರಯತ್ನಿಸಿ, ನಂತರ ವಾಕ್ಯ, ನಂತರ ಪದ',
      bodyEn: '• Recursive chunking is the default strategy in many modern RAG frameworks. Instead of cutting blindly, it attempts separators in order -- paragraph, then line, then sentence, then word, then character -- only falling back to a smaller unit when the current one is still too large. Benchmarks showed recursive chunking often outperformed more complicated semantic chunking approaches while being faster and easier to implement, which is why it became the 2026 default.',
      bodyKn: '• Recursive chunking ಅನೇಕ ಆಧುನಿಕ RAG frameworks ಗಳಲ್ಲಿ ಡೀಫಾಲ್ಟ್ ತಂತ್ರ. ಕುರುಡಾಗಿ ಕತ್ತರಿಸುವ ಬದಲಿಗೆ, ಇದೂ ಕ್ರಮದಲ್ಲಿ separators ಗಳನ್ನೂ ಪ್ರಯತ್ನಿಸುತ್ತದೆ -- ಪ್ಯಾರಾಗ್ರಾಫ್, ನಂತರ ಸಾಲು, ನಂತರ ವಾಕ್ಯ, ನಂತರ ಪದ, ನಂತರ character -- ಪ್ರಸ್ತುತ ಘಟಕ ಇನ್ನೂ ಬಹಳ ದೊಡ್ಡದಾಗಿದ್ದಾಗ ಮಾತ್ರ ಒಂದು ಚಿಕ್ಕ ಘಟಕಕ್ಕೆ ಹಿಂತಿರುಗುತ್ತಾ. Benchmarks ಗಳು recursive chunking ಆಗಾಗ್ಗೆ ಹೆಚ್ಚು ಸಂಕೀರ್ಣ semantic chunking ವಿಧಾನಗಳಿಗಿಂತ ಉತ್ತಮ ಪ್ರದರ್ಶನ ನೀಡಿತು ಎಂದು ತೋರಿಸಿದವು, ವೇಗವಾಗಿ ಮತ್ತು ಅಳವಡಿಸಲು ಸುಲಭವಾಗಿಯೂ ಇರುತ್ತಾ, ಇದೇ ಕಾರಣಕ್ಕಾಗಿ ಇದೂ 2026 ಡೀಫಾಲ್ಟ್ ಆಯಿತು.' } },
    { type: 'code', data: {
      filename: 'chunk_recursive.py',
      headingEn: 'Original Code — Recursive Chunking (Genuinely Executed)', headingKn: 'Original Code — Recursive Chunking (ನಿಜವಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ)',
      descEn: 'The lesson\'s exact chunk_recursive() function, actually run on the identical sample text and size=120 used for chunk_fixed() above, for a direct, fair comparison.',
      descKn: 'ಲೆಸನ್‌ನ ನಿಖರ chunk_recursive() ಫಂಕ್ಷನ್, ಮೇಲಿನ chunk_fixed() ಗೆ ಬಳಸಿದ ಅದೇ sample ಪಠ್ಯ ಮತ್ತು size=120 ಮೇಲೆ ನಿಜವಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ, ಒಂದು ನೇರ, ನ್ಯಾಯಯುತ ಹೋಲಿಕೆಗಾಗಿ.',
      code: "def chunk_recursive(text, size=512, seps=(\"\\n\\n\", \"\\n\", \". \", \" \")):\n    if len(text) <= size:\n        return [text]\n    for sep in seps:\n        if sep not in text:\n            continue\n        parts = text.split(sep)\n        chunks = []\n        buf = \"\"\n        for p in parts:\n            if len(p) > size:\n                if buf:\n                    chunks.append(buf)\n                    buf = \"\"\n                chunks.extend(chunk_recursive(p, size=size, seps=seps[1:] or (\" \",)))\n                continue\n            candidate = buf + sep + p if buf else p\n            if len(candidate) <= size:\n                buf = candidate\n            else:\n                if buf:\n                    chunks.append(buf)\n                buf = p\n        if buf:\n            chunks.append(buf)\n        return [c for c in chunks if c.strip()]\n    return chunk_fixed(text, size)\n\nfor i, c in enumerate(chunk_recursive(sample, size=120)):\n    print(f\"--chunk {i} (len={len(c)})--\")\n    print(repr(c))" } },
    { type: 'output', data: { output: "--chunk 0 (len=100)--\n'The customer may terminate the agreement after giving thirty days written notice to the other party.'\n--chunk 1 (len=80)--\n'Termination shall not affect any rights accrued prior to the date of termination'\n--chunk 2 (len=58)--\n'All confidentiality obligations shall survive termination.'\n--chunk 3 (len=119)--\n'The agreement may also be terminated immediately in the event of a material breach that remains uncured for a period of'\n--chunk 4 (len=53)--\n'fifteen days following written notice of such breach.'" } },

    { type: 'concept', data: {
      headingEn: 'Reading the Verified Output', headingKn: 'ಪರಿಶೀಲಿಸಿದ Output ಓದುವುದು',
      bodyEn: '• Every single chunk here ends at a genuine sentence or clause boundary -- "termination.", "breach.", etc. -- and the word "termination" that fixed chunking split into "terminatio" + "n" now appears completely intact in chunk 2 ("...shall survive termination."). No word was ever cut across a chunk boundary.\n• Chunk 3 (119 characters) came very close to the 120-character limit without exceeding it, showing the algorithm correctly tried larger separators first (paragraph, sentence) and only produced a chunk this close to the limit because that particular sentence had no earlier natural break point within budget -- exactly the "paragraph -> sentence -> word -> character" fallback order the lesson describes.',
      bodyKn: '• ಇಲ್ಲಿ ಪ್ರತಿ ಒಂಟಿ chunk ಒಂದು ನಿಜ ವಾಕ್ಯ ಅಥವಾ ಷರತ್ತು ಗಡಿಯಲ್ಲಿ ಕೊನೆಗೊಳ್ಳುತ್ತದೆ -- "termination.", "breach.", ಇತ್ಯಾದಿ -- ಮತ್ತು fixed chunking "terminatio" + "n" ಆಗಿ ಬೇರ್ಪಡಿಸಿದ "termination" ಪದ ಈಗ chunk 2 ("...shall survive termination.") ನಲ್ಲಿ ಸಂಪೂರ್ಣವಾಗಿ ಅಖಂಡವಾಗಿ ಕಾಣಿಸುತ್ತದೆ. ಯಾವುದೇ ಪದವನ್ನೂ ಎಂದಿಗೂ ಒಂದು chunk ಗಡಿಯಾದ್ಯಂತ ಕತ್ತರಿಸಲಾಗಿಲ್ಲ.\n• Chunk 3 (119 characters) 120-character ಮಿತಿಯನ್ನೂ ಮೀರದೆ ಬಹಳ ಹತ್ತಿರ ಬಂದಿತು, algorithm ದೊಡ್ಡ separators ಗಳನ್ನೂ ಮೊದಲು ಸರಿಯಾಗಿ ಪ್ರಯತ್ನಿಸಿತು (ಪ್ಯಾರಾಗ್ರಾಫ್, ವಾಕ್ಯ) ಮತ್ತು ಆ ನಿರ್ದಿಷ್ಟ ವಾಕ್ಯಕ್ಕೆ ಬಜೆಟ್‌ನೊಳಗೆ ಯಾವುದೇ ಮೊದಲಿನ ಸ್ವಾಭಾವಿಕ ಬ್ರೇಕ್ ಪಾಯಿಂಟ್ ಇಲ್ಲದ ಕಾರಣ ಮಾತ್ರ ಮಿತಿಗೆ ಇಷ್ಟು ಹತ್ತಿರದ ಒಂದು chunk ಉತ್ಪಾದಿಸಿತು ಎಂದು ತೋರಿಸುತ್ತಾ -- ಲೆಸನ್ ವಿವರಿಸುವ ನಿಖರ "ಪ್ಯಾರಾಗ್ರಾಫ್ -> ವಾಕ್ಯ -> ಪದ -> character" fallback ಕ್ರಮ.' } },

    { type: 'heading', data: { level: 'H2', textEn: '3. Semantic Chunking', textKn: '3. Semantic Chunking' } },
    { type: 'concept', data: {
      headingEn: 'Where Does the Topic Change?', headingKn: 'ವಿಷಯ ಎಲ್ಲಿ ಬದಲಾಗುತ್ತದೆ?',
      bodyEn: '• Semantic chunking uses embeddings instead of text formatting -- every sentence gets an embedding, adjacent sentence embeddings are compared, and a new chunk starts when similarity drops sharply. Advantages: preserves topics, better semantic consistency. Disadvantages: more computationally expensive, can create tiny fragments, often slower than recursive chunking, and does not always outperform it in practice.',
      bodyKn: '• Semantic chunking ಪಠ್ಯ ಸ್ವರೂಪಣೆಯ ಬದಲಿಗೆ embeddings ಬಳಸುತ್ತದೆ -- ಪ್ರತಿ ವಾಕ್ಯಕ್ಕೆ ಒಂದು embedding ಸಿಗುತ್ತದೆ, ಪಕ್ಕದ ವಾಕ್ಯ embeddings ಗಳನ್ನೂ ಹೋಲಿಸಲಾಗುತ್ತದೆ, ಮತ್ತು ಹೋಲಿಕೆ ತೀವ್ರವಾಗಿ ಇಳಿದಾಗ ಒಂದು ಹೊಸ chunk ಆರಂಭವಾಗುತ್ತದೆ. ಅನುಕೂಲಗಳು: ವಿಷಯಗಳನ್ನೂ ಸಂರಕ್ಷಿಸುತ್ತದೆ, ಉತ್ತಮ semantic ಸ್ಥಿರತೆ. ಅನಾನುಕೂಲಗಳು: ಹೆಚ್ಚು ಗಣನಾತ್ಮಕವಾಗಿ ದುಬಾರಿ, ಚಿಕ್ಕ ತುಣುಕುಗಳನ್ನೂ ಸೃಷ್ಟಿಸಬಹುದು, ಆಗಾಗ್ಗೆ recursive chunking ಗಿಂತ ನಿಧಾನ, ಮತ್ತು ಪ್ರಾಯೋಗಿಕವಾಗಿ ಇದನ್ನೂ ಯಾವಾಗಲೂ ಮೀರಿಸುವುದಿಲ್ಲ.' } },
    { type: 'code', data: {
      filename: 'chunk_semantic.py',
      headingEn: 'Original Code — Semantic Chunking (Genuinely Executed, With an Honest Over-Fragmentation)', headingKn: 'Original Code — Semantic Chunking (ನಿಜವಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ, ಒಂದು ಪ್ರಾಮಾಣಿಕ ಅತಿ-ವಿಘಟನೆಯೊಂದಿಗೆ)',
      descEn: 'The lesson\'s exact chunk_semantic() function, actually run using a real sentence-transformers/all-MiniLM-L6-v2 encoder on the lesson\'s own two-topic example (3 sentences about ML/healthcare, then 2 about the Roman Empire), with the lesson\'s exact threshold=0.6.',
      descKn: 'ಲೆಸನ್‌ನ ನಿಖರ chunk_semantic() ಫಂಕ್ಷನ್, ಒಂದು ನಿಜ sentence-transformers/all-MiniLM-L6-v2 encoder ಬಳಸಿ ಲೆಸನ್‌ನ ಸ್ವಂತ ಎರಡು-ವಿಷಯ ಉದಾಹರಣೆಯ ಮೇಲೆ (ML/healthcare ಬಗ್ಗೆ 3 ವಾಕ್ಯಗಳು, ನಂತರ Roman Empire ಬಗ್ಗೆ 2), ಲೆಸನ್‌ನ ನಿಖರ threshold=0.6 ಜೊತೆ ನಿಜವಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ.',
      code: "from sentence_transformers import SentenceTransformer\nencoder = SentenceTransformer(\"sentence-transformers/all-MiniLM-L6-v2\")\n\ndef chunk_semantic(text, encoder, threshold=0.6, min_chars=200, max_chars=2048):\n    sentences = split_sentences(text)\n    if not sentences:\n        return []\n    embs = encoder.encode(sentences, normalize_embeddings=True)\n    chunks = [[sentences[0]]]\n    for i in range(1, len(sentences)):\n        sim = float(embs[i] @ embs[i - 1])\n        current_len = sum(len(s) for s in chunks[-1])\n        if sim < threshold and current_len >= min_chars:\n            chunks.append([sentences[i]])\n        else:\n            chunks[-1].append(sentences[i])\n\n    result = []\n    for group in chunks:\n        text_group = \" \".join(group)\n        if len(text_group) > max_chars:\n            result.extend(chunk_recursive(text_group, size=max_chars))\n        else:\n            result.append(text_group)\n    return result\n\nsample2 = (\"Machine learning is transforming healthcare. Neural networks detect cancer. \"\n           \"Transformers improve diagnosis. The Roman Empire expanded rapidly across \"\n           \"Europe. Julius Caesar led many military campaigns.\")\n\nfor i, c in enumerate(chunk_semantic(sample2, encoder, threshold=0.6, min_chars=10)):\n    print(f\"--chunk {i}--\")\n    print(c)" } },
    { type: 'output', data: { output: "--chunk 0--\nMachine learning is transforming healthcare.\n--chunk 1--\nNeural networks detect cancer.\n--chunk 2--\nTransformers improve diagnosis.\n--chunk 3--\nThe Roman Empire expanded rapidly across Europe.\n--chunk 4--\nJulius Caesar led many military campaigns.\n\n(measured consecutive-sentence cosine similarities: 0.408, 0.185, -0.023, 0.394 -- all below the 0.6 threshold)" } },

    { type: 'concept', data: {
      headingEn: 'Reading the Verified Output, and an Honest Over-Fragmentation', headingKn: 'ಪರಿಶೀಲಿಸಿದ Output ಓದುವುದು, ಮತ್ತು ಒಂದು ಪ್ರಾಮಾಣಿಕ ಅತಿ-ವಿಘಟನೆ',
      bodyEn: '• The lesson\'s own illustrative example expects the three ML/healthcare sentences to merge into one chunk and the two Roman Empire sentences into another. The real run did not do this -- it produced five chunks, one per sentence. Measuring the actual cosine similarities explains why: even the two most topically-related sentences ("Machine learning is transforming healthcare." and "Neural networks detect cancer.") scored only 0.408 -- well below the lesson\'s threshold=0.6 -- with this specific small encoder model.\n• This is a genuine, honest illustration of the exact "Tiny Semantic Chunks" pitfall this lesson\'s own Part 2 warns about: without a minimum size enforced early enough, semantic chunking can produce one-sentence fragments when the chosen threshold doesn\'t match the chosen encoder\'s typical similarity range. It also reveals a real, practical lesson beyond what the text states outright: a threshold like 0.6 is not a universal constant -- it must be calibrated per embedding model, since different encoders produce different absolute similarity magnitudes for the same sentences.',
      bodyKn: '• ಲೆಸನ್‌ನ ಸ್ವಂತ ದೃಷ್ಟಾಂತ ಉದಾಹರಣೆ ಮೂರು ML/healthcare ವಾಕ್ಯಗಳನ್ನೂ ಒಂದು chunk ಗೆ ಮತ್ತು ಎರಡು Roman Empire ವಾಕ್ಯಗಳನ್ನೂ ಇನ್ನೊಂದಕ್ಕೆ ವಿಲೀನಗೊಳ್ಳುತ್ತದೆ ಎಂದು ನಿರೀಕ್ಷಿಸುತ್ತದೆ. ನಿಜ run ಇದನ್ನೂ ಮಾಡಲಿಲ್ಲ -- ಇದೂ ಐದು chunks ಗಳನ್ನೂ ಉತ್ಪಾದಿಸಿತು, ಪ್ರತಿ ವಾಕ್ಯಕ್ಕೆ ಒಂದು. ನಿಜ cosine ಹೋಲಿಕೆಗಳನ್ನೂ ಅಳೆಯುವುದೂ ಏಕೆ ಎಂದು ವಿವರಿಸುತ್ತದೆ: ಅತ್ಯಂತ ವಿಷಯಾಧಾರಿತವಾಗಿ-ಸಂಬಂಧಿತ ಎರಡು ವಾಕ್ಯಗಳೂ ("Machine learning is transforming healthcare." ಮತ್ತು "Neural networks detect cancer.") ಈ ನಿರ್ದಿಷ್ಟ ಚಿಕ್ಕ encoder model ಜೊತೆ ಕೇವಲ 0.408 ಸ್ಕೋರ್ ಮಾಡಿದವು -- ಲೆಸನ್‌ನ threshold=0.6 ಗಿಂತ ಬಹಳ ಕೆಳಗೆ.\n• ಇದೂ ಈ ಲೆಸನ್‌ನ ಸ್ವಂತ Part 2 ಎಚ್ಚರಿಸುವ ನಿಖರ "Tiny Semantic Chunks" ಬಲೆಯ ಒಂದು ನಿಜ, ಪ್ರಾಮಾಣಿಕ ದೃಷ್ಟಾಂತ: ಸಾಕಷ್ಟು ಬೇಗನೆ ಜಾರಿಗೊಳಿಸಿದ ಒಂದು ಕನಿಷ್ಠ ಗಾತ್ರ ಇಲ್ಲದೆ, ಆಯ್ಕೆ ಮಾಡಿದ threshold ಆಯ್ಕೆ ಮಾಡಿದ encoder ನ ಸಾಮಾನ್ಯ ಹೋಲಿಕೆ ವ್ಯಾಪ್ತಿಗೆ ಹೊಂದದಿದ್ದಾಗ semantic chunking ಒಂಟಿ-ವಾಕ್ಯ ತುಣುಕುಗಳನ್ನೂ ಉತ್ಪಾದಿಸಬಹುದು. ಇದೂ ಪಠ್ಯ ನೇರವಾಗಿ ಹೇಳುವುದನ್ನೂ ಮೀರಿದ ಒಂದು ನಿಜ, ಪ್ರಾಯೋಗಿಕ ಪಾಠವನ್ನೂ ಬಹಿರಂಗಪಡಿಸುತ್ತದೆ: 0.6 ನಂತಹ ಒಂದು threshold ಒಂದು ಸಾರ್ವತ್ರಿಕ ಸ್ಥಿರಾಂಕವಲ್ಲ -- ಇದನ್ನೂ ಪ್ರತಿ embedding model ಗೆ ಮಾಪನಾಂಕಗೊಳಿಸಬೇಕು, ಬೇರೆ encoders ಗಳು ಅದೇ ವಾಕ್ಯಗಳಿಗೆ ಬೇರೆ ಸಂಪೂರ್ಣ ಹೋಲಿಕೆ ಪ್ರಮಾಣಗಳನ್ನೂ ಉತ್ಪಾದಿಸುವ ಕಾರಣ.' } },

    { type: 'concept', data: {
      headingEn: 'Why AI Uses It', headingKn: 'AI ಇದನ್ನು ಏಕೆ ಬಳಸುತ್ತದೆ',
      bodyEn: '• The verified word-splitting bug in chunk_fixed() (turning "termination" into "terminatio" + "n") is a direct, concrete answer to why "just use a better embedding model" does not fix bad retrieval: the damage happens before embedding ever occurs, at the chunking stage, and no downstream model can recover information that was destroyed upstream.\n• The verified chunk_recursive() run -- every boundary landing on a real sentence break -- explains why recursive chunking became the 2026 default purely from cost/benefit: it is a simple, fast, deterministic algorithm (no model inference needed) that empirically produced cleaner boundaries than the far more expensive semantic approach on this exact example.\n• The verified over-fragmentation in chunk_semantic() is itself the single best argument in this lesson for treating chunking strategies as something to measure, not assume: the same threshold value (0.6) that reads as reasonable in the lesson\'s prose produced five one-sentence chunks instead of two topic-coherent ones the moment it met a real embedding model -- exactly the gap between a strategy sounding good on paper and behaving well in production that this whole lesson exists to close.',
      bodyKn: '• chunk_fixed() ನಲ್ಲಿ ಪರಿಶೀಲಿಸಿದ ಪದ-ಬೇರ್ಪಡಿಕೆ ಬಗ್ (ಕ) "termination" ಅನ್ನೂ "terminatio" + "n" ಆಗಿ ಬದಲಾಯಿಸುವುದು "ಕೇವಲ ಒಂದು ಉತ್ತಮ embedding model ಬಳಸಿ" ಕೆಟ್ಟ retrieval ಸರಿಪಡಿಸುವುದಿಲ್ಲ ಏಕೆ ಎಂಬುದಕ್ಕೆ ಒಂದು ನೇರ, ಕಾಂಕ್ರೀಟ್ ಉತ್ತರ: ಹಾನಿ embedding ಸಂಭವಿಸುವ ಮೊದಲೇ, chunking ಹಂತದಲ್ಲಿ ಸಂಭವಿಸುತ್ತದೆ, ಮತ್ತು ಯಾವುದೇ downstream model upstream ನಲ್ಲಿ ನಾಶವಾದ ಮಾಹಿತಿಯನ್ನೂ ಚೇತರಿಸಿಕೊಳ್ಳಲಾರದು.\n• ಪರಿಶೀಲಿಸಿದ chunk_recursive() run -- ಪ್ರತಿ ಗಡಿಯೂ ಒಂದು ನಿಜ ವಾಕ್ಯ ಬ್ರೇಕ್‌ನಲ್ಲಿ ಇಳಿಯುತ್ತಾ -- recursive chunking ಕೇವಲ ವೆಚ್ಚ/ಪ್ರಯೋಜನ ಇಂದ 2026 ಡೀಫಾಲ್ಟ್ ಏಕೆ ಆಯಿತು ಎಂದು ವಿವರಿಸುತ್ತದೆ: ಇದೂ ಒಂದು ಸರಳ, ವೇಗದ, ನಿರ್ಣಾಯಕ algorithm (ಯಾವುದೇ model inference ಅಗತ್ಯವಿಲ್ಲ) ಇದೂ ಈ ನಿಖರ ಉದಾಹರಣೆಯಲ್ಲಿ ಹೆಚ್ಚು ದುಬಾರಿ semantic ವಿಧಾನಕ್ಕಿಂತ ಪ್ರಾಯೋಗಿಕವಾಗಿ ಸ್ವಚ್ಛ ಗಡಿಗಳನ್ನೂ ಉತ್ಪಾದಿಸಿತು.\n• chunk_semantic() ನಲ್ಲಿ ಪರಿಶೀಲಿಸಿದ ಅತಿ-ವಿಘಟನೆ ಸ್ವತಃ chunking ತಂತ್ರಗಳನ್ನೂ ಊಹಿಸುವ ಬದಲಿಗೆ ಅಳೆಯಬೇಕಾದ ಏನೋ ಎಂದು ಪರಿಗಣಿಸುವುದಕ್ಕೆ ಈ ಲೆಸನ್‌ನಲ್ಲಿ ಅತ್ಯುತ್ತಮ ವಾದ: ಲೆಸನ್‌ನ ಗದ್ಯದಲ್ಲಿ ಸಮಂಜಸ ಎಂದು ಓದುವ ಅದೇ threshold ಮೌಲ್ಯ (0.6) ಒಂದು ನಿಜ embedding model ಎದುರಿಸಿದ ಕ್ಷಣ ಎರಡು ವಿಷಯ-ಸುಸಂಬದ್ಧ chunks ಬದಲಿಗೆ ಐದು ಒಂಟಿ-ವಾಕ್ಯ chunks ಉತ್ಪಾದಿಸಿತು -- ಪೇಪರ್ ಮೇಲೆ ಒಳ್ಳೆಯದಾಗಿ ಧ್ವನಿಸುವ ಮತ್ತು production ನಲ್ಲಿ ಚೆನ್ನಾಗಿ ವರ್ತಿಸುವ ನಡುವಿನ ನಿಖರ ಅಂತರ ಈ ಸಂಪೂರ್ಣ ಲೆಸನ್ ಮುಚ್ಚಲು ಅಸ್ತಿತ್ವದಲ್ಲಿದೆ.' } },

    { type: 'concept', data: {
      headingEn: 'Key Takeaways', headingKn: 'ಮುಖ್ಯ ಅಂಶಗಳು',
      bodyEn: '• Chunking quality can matter as much as embedding model quality -- if the important information is split apart incorrectly, no embedding model can recover it.\n• Chunk size should match query type: 256-512 tokens for fact lookup, 512-1024 for analytical reasoning, 1024-2048 for whole-section understanding.\n• Fixed chunking is simple and fast but ignores language -- verified directly: it split the word "termination" in half across a chunk boundary.\n• Recursive chunking tries paragraph, then sentence, then word boundaries before falling back to raw characters -- verified directly: every chunk boundary landed on a genuine sentence break, and became the 2026 default because it often outperforms semantic chunking while being simpler and faster.\n• Semantic chunking groups sentences by embedding similarity but is fragile in practice -- verified directly: the lesson\'s own threshold (0.6) produced one-sentence fragments instead of topic-coherent groups when tested against a real small encoder, since similarity thresholds must be calibrated per model rather than treated as universal constants.\n• 2026 research findings reshaped best practice: recursive often beats semantic chunking, overlap is often not worth its storage cost, and retrieval quality often degrades past roughly 2500 tokens per chunk.',
      bodyKn: '• Chunking ಗುಣಮಟ್ಟ embedding model ಗುಣಮಟ್ಟದಷ್ಟೇ ಮುಖ್ಯವಾಗಿರಬಹುದು -- ಮುಖ್ಯ ಮಾಹಿತಿಯನ್ನೂ ತಪ್ಪಾಗಿ ಬೇರ್ಪಡಿಸಿದರೆ, ಯಾವುದೇ embedding model ಇದನ್ನೂ ಚೇತರಿಸಿಕೊಳ್ಳಲಾರದು.\n• Chunk ಗಾತ್ರ query ಬಗೆಗೆ ಹೊಂದಬೇಕು: fact lookup ಗಾಗಿ 256-512 tokens, analytical reasoning ಗಾಗಿ 512-1024, ಸಂಪೂರ್ಣ-ವಿಭಾಗ ಅರ್ಥಮಾಡಿಕೊಳ್ಳುವಿಕೆಗೆ 1024-2048.\n• Fixed chunking ಸರಳ ಮತ್ತು ವೇಗ ಆದರೆ ಭಾಷೆ ಕಡೆಗಣಿಸುತ್ತದೆ -- ನೇರವಾಗಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ: ಇದೂ "termination" ಪದವನ್ನೂ ಒಂದು chunk ಗಡಿಯಾದ್ಯಂತ ಅರ್ಧಕ್ಕೆ ಬೇರ್ಪಡಿಸಿತು.\n• Recursive chunking ಕಚ್ಚಾ characters ಗಳಿಗೆ ಹಿಂತಿರುಗುವ ಮೊದಲು ಪ್ಯಾರಾಗ್ರಾಫ್, ನಂತರ ವಾಕ್ಯ, ನಂತರ ಪದ ಗಡಿಗಳನ್ನೂ ಪ್ರಯತ್ನಿಸುತ್ತದೆ -- ನೇರವಾಗಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ: ಪ್ರತಿ chunk ಗಡಿಯೂ ಒಂದು ನಿಜ ವಾಕ್ಯ ಬ್ರೇಕ್‌ನಲ್ಲಿ ಇಳಿಯಿತು, ಮತ್ತು ಸರಳ ಮತ್ತು ವೇಗವಾಗಿಯೂ ಇರುತ್ತಾ ಆಗಾಗ್ಗೆ semantic chunking ಅನ್ನೂ ಮೀರಿಸುವ ಕಾರಣ 2026 ಡೀಫಾಲ್ಟ್ ಆಯಿತು.\n• Semantic chunking embedding ಹೋಲಿಕೆಯಿಂದ ವಾಕ್ಯಗಳನ್ನೂ ಗುಂಪುಗೂಡಿಸುತ್ತದೆ ಆದರೆ ಪ್ರಾಯೋಗಿಕವಾಗಿ ದುರ್ಬಲ -- ನೇರವಾಗಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ: ಲೆಸನ್‌ನ ಸ್ವಂತ threshold (0.6) ಒಂದು ನಿಜ ಚಿಕ್ಕ encoder ವಿರುದ್ಧ ಪರೀಕ್ಷಿಸಿದಾಗ ವಿಷಯ-ಸುಸಂಬದ್ಧ ಗುಂಪುಗಳ ಬದಲಿಗೆ ಒಂಟಿ-ವಾಕ್ಯ ತುಣುಕುಗಳನ್ನೂ ಉತ್ಪಾದಿಸಿತು, ಹೋಲಿಕೆ thresholds ಗಳನ್ನೂ ಸಾರ್ವತ್ರಿಕ ಸ್ಥಿರಾಂಕಗಳಾಗಿ ಪರಿಗಣಿಸುವ ಬದಲಿಗೆ ಪ್ರತಿ model ಗೆ ಮಾಪನಾಂಕಗೊಳಿಸಬೇಕಾದ ಕಾರಣ.\n• 2026 ಸಂಶೋಧನಾ ಶೋಧನೆಗಳು best practice ಅನ್ನೂ ಮರುರೂಪಿಸಿದವು: recursive ಆಗಾಗ್ಗೆ semantic chunking ಅನ್ನೂ ಮೀರಿಸುತ್ತದೆ, overlap ಆಗಾಗ್ಗೆ ಇದರ ಶೇಖರಣಾ ವೆಚ್ಚಕ್ಕೆ ಯೋಗ್ಯವಲ್ಲ, ಮತ್ತು retrieval ಗುಣಮಟ್ಟ ಆಗಾಗ್ಗೆ ಪ್ರತಿ chunk ಗೆ ಸುಮಾರು 2500 tokens ಮೀರಿ ಕುಸಿಯುತ್ತದೆ.' } },

    { type: 'quiz', data: { questions: [
      { q: 'Why can a "better" embedding model fail to fix poor retrieval quality?', qKn: 'ಒಂದು "ಉತ್ತಮ" embedding model ಕಳಪೆ retrieval ಗುಣಮಟ್ಟ ಸರಿಪಡಿಸಲು ಏಕೆ ವಿಫಲಗೊಳ್ಳಬಹುದು?',
        opts: ['Embedding models can always fix any retrieval problem', 'If important information was split apart incorrectly during chunking, no embedding model can recover the missing information -- the damage happens upstream of embedding', 'Better embedding models always make chunking irrelevant', 'Chunking has no measurable effect on retrieval quality'],
        optsKn: ['Embedding models ಗಳು ಯಾವಾಗಲೂ ಯಾವುದೇ retrieval ಸಮಸ್ಯೆ ಸರಿಪಡಿಸಬಲ್ಲವು', 'Chunking ಸಮಯದಲ್ಲಿ ಮುಖ್ಯ ಮಾಹಿತಿಯನ್ನೂ ತಪ್ಪಾಗಿ ಬೇರ್ಪಡಿಸಿದ್ದರೆ, ಯಾವುದೇ embedding model ಕಾಣೆಯಾದ ಮಾಹಿತಿಯನ್ನೂ ಚೇತರಿಸಿಕೊಳ್ಳಲಾರದು -- ಹಾನಿ embedding ಗಿಂತ upstream ನಲ್ಲಿ ಸಂಭವಿಸುತ್ತದೆ', 'ಉತ್ತಮ embedding models ಯಾವಾಗಲೂ chunking ಅಪ್ರಸ್ತುತಗೊಳಿಸುತ್ತವೆ', 'Chunking retrieval ಗುಣಮಟ್ಟದ ಮೇಲೆ ಯಾವುದೇ ಅಳೆಯಬಹುದಾದ ಪರಿಣಾಮ ಬೀರುವುದಿಲ್ಲ'], correct: 1 },
      { q: 'Verified in this lesson: what happened when the real chunk_fixed() function was run on a sample contract paragraph with size=120?', qKn: 'ಈ lesson ನಲ್ಲಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ: size=120 ಜೊತೆ ಒಂದು ಮಾದರಿ ಒಪ್ಪಂದ ಪ್ಯಾರಾಗ್ರಾಫ್ ಮೇಲೆ ನಿಜ chunk_fixed() ಫಂಕ್ಷನ್ ಚಲಾಯಿಸಿದಾಗ ಏನಾಯಿತು?',
        opts: ['Every chunk ended cleanly at a sentence boundary', 'The cutoff landed in the middle of the word "termination," literally splitting it into "terminatio" (end of chunk 1) and "n" (start of chunk 2)', 'The function raised an error since 120 characters was too small', 'All chunks came out exactly the same length as the original text'],
        optsKn: ['ಪ್ರತಿ chunk ಒಂದು ವಾಕ್ಯ ಗಡಿಯಲ್ಲಿ ಸ್ವಚ್ಛವಾಗಿ ಕೊನೆಗೊಂಡಿತು', 'Cutoff "termination" ಪದದ ಮಧ್ಯದಲ್ಲಿ ಇಳಿಯಿತು, ಅಕ್ಷರಶಃ ಇದನ್ನೂ "terminatio" (chunk 1 ರ ಕೊನೆ) ಮತ್ತು "n" (chunk 2 ರ ಆರಂಭ) ಆಗಿ ಬೇರ್ಪಡಿಸುತ್ತಾ', '120 characters ಬಹಳ ಚಿಕ್ಕದಾಗಿತ್ತು ಎಂಬ ಕಾರಣ ಫಂಕ್ಷನ್ ಒಂದು error ಎಬ್ಬಿಸಿತು', 'ಎಲ್ಲಾ chunks ಗಳು original ಪಠ್ಯದಷ್ಟೇ ಉದ್ದ ಬಂದವು'], correct: 1 },
      { q: 'Verified in this lesson: how did chunk_recursive() handle the same text and size that broke the word "termination" under chunk_fixed()?', qKn: 'ಈ lesson ನಲ್ಲಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ: chunk_fixed() ಅಡಿಯಲ್ಲಿ "termination" ಪದ ಮುರಿದ ಅದೇ ಪಠ್ಯ ಮತ್ತು ಗಾತ್ರವನ್ನೂ chunk_recursive() ಹೇಗೆ ನಿರ್ವಹಿಸಿತು?',
        opts: ['It also split "termination" in the same way', 'Every chunk boundary landed on a genuine sentence break, keeping "termination" and every other word fully intact', 'It refused to process the text at all', 'It produced only one giant chunk containing the entire text'],
        optsKn: ['ಇದೂ ಅದೇ ರೀತಿ "termination" ಅನ್ನೂ ಬೇರ್ಪಡಿಸಿತು', 'ಪ್ರತಿ chunk ಗಡಿಯೂ ಒಂದು ನಿಜ ವಾಕ್ಯ ಬ್ರೇಕ್‌ನಲ್ಲಿ ಇಳಿಯಿತು, "termination" ಮತ್ತು ಪ್ರತಿ ಇತರ ಪದವನ್ನೂ ಸಂಪೂರ್ಣವಾಗಿ ಅಖಂಡವಾಗಿ ಇರಿಸುತ್ತಾ', 'ಇದೂ ಪಠ್ಯವನ್ನೂ ಸಂಪೂರ್ಣವಾಗಿ ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲು ನಿರಾಕರಿಸಿತು', 'ಇದೂ ಸಂಪೂರ್ಣ ಪಠ್ಯ ಒಳಗೊಂಡ ಕೇವಲ ಒಂದು ದೈತ್ಯ chunk ಉತ್ಪಾದಿಸಿತು'], correct: 1 },
      { q: 'Verified in this lesson: what happened when chunk_semantic() was run with the lesson\'s exact threshold=0.6 using a real all-MiniLM-L6-v2 encoder on the two-topic (ML/healthcare, then Roman Empire) example?', qKn: 'ಈ lesson ನಲ್ಲಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ: ಎರಡು-ವಿಷಯ (ML/healthcare, ನಂತರ Roman Empire) ಉದಾಹರಣೆಯ ಮೇಲೆ ಒಂದು ನಿಜ all-MiniLM-L6-v2 encoder ಬಳಸಿ ಲೆಸನ್‌ನ ನಿಖರ threshold=0.6 ಜೊತೆ chunk_semantic() ಚಲಾಯಿಸಿದಾಗ ಏನಾಯಿತು?',
        opts: ['It produced exactly two clean topic-based chunks as the lesson\'s illustrative example describes', 'It over-fragmented into five separate one-sentence chunks, because even topically-related sentences scored below 0.6 similarity with this specific encoder -- a real, honest illustration of the "tiny fragments" pitfall', 'It crashed with an import error', 'It merged all five sentences into a single chunk'],
        optsKn: ['ಲೆಸನ್‌ನ ದೃಷ್ಟಾಂತ ಉದಾಹರಣೆ ವಿವರಿಸಿದಂತೆ ಇದೂ ನಿಖರವಾಗಿ ಎರಡು ಸ್ವಚ್ಛ ವಿಷಯ-ಆಧಾರಿತ chunks ಉತ್ಪಾದಿಸಿತು', 'ಇದೂ ಐದು ಪ್ರತ್ಯೇಕ ಒಂಟಿ-ವಾಕ್ಯ chunks ಗಳಾಗಿ ಅತಿಯಾಗಿ ವಿಘಟಿಸಿತು, ಈ ನಿರ್ದಿಷ್ಟ encoder ಜೊತೆ ವಿಷಯಾಧಾರಿತವಾಗಿ-ಸಂಬಂಧಿತ ವಾಕ್ಯಗಳೂ 0.6 ಹೋಲಿಕೆಗಿಂತ ಕೆಳಗೆ ಸ್ಕೋರ್ ಮಾಡಿದ ಕಾರಣ -- "tiny fragments" ಬಲೆಯ ಒಂದು ನಿಜ, ಪ್ರಾಮಾಣಿಕ ದೃಷ್ಟಾಂತ', 'ಇದೂ ಒಂದು import error ಜೊತೆ crash ಆಯಿತು', 'ಇದೂ ಎಲ್ಲಾ ಐದು ವಾಕ್ಯಗಳನ್ನೂ ಒಂದೇ chunk ಗೆ ವಿಲೀನಗೊಳಿಸಿತು'], correct: 1 },
      { q: 'What does the honest over-fragmentation finding in chunk_semantic() reveal about similarity thresholds?', qKn: 'chunk_semantic() ನಲ್ಲಿ ಪ್ರಾಮಾಣಿಕ ಅತಿ-ವಿಘಟನೆ ಶೋಧನೆ ಹೋಲಿಕೆ thresholds ಗಳ ಬಗ್ಗೆ ಏನನ್ನೂ ಬಹಿರಂಗಪಡಿಸುತ್ತದೆ?',
        opts: ['A threshold like 0.6 is a universal constant that works identically across all embedding models', 'A similarity threshold must be calibrated per embedding model, since different encoders produce different absolute similarity magnitudes for the same sentences', 'Thresholds have no effect on chunking behavior', 'Higher thresholds always produce fewer, larger chunks regardless of the model'],
        optsKn: ['0.6 ನಂತಹ ಒಂದು threshold ಎಲ್ಲಾ embedding models ಗಳಾದ್ಯಂತ ಒಂದೇ ರೀತಿ ಕೆಲಸ ಮಾಡುವ ಒಂದು ಸಾರ್ವತ್ರಿಕ ಸ್ಥಿರಾಂಕ', 'ಒಂದು ಹೋಲಿಕೆ threshold ಅನ್ನೂ ಪ್ರತಿ embedding model ಗೆ ಮಾಪನಾಂಕಗೊಳಿಸಬೇಕು, ಬೇರೆ encoders ಗಳು ಅದೇ ವಾಕ್ಯಗಳಿಗೆ ಬೇರೆ ಸಂಪೂರ್ಣ ಹೋಲಿಕೆ ಪ್ರಮಾಣಗಳನ್ನೂ ಉತ್ಪಾದಿಸುವ ಕಾರಣ', 'Thresholds ಗಳು chunking ವರ್ತನೆಯ ಮೇಲೆ ಯಾವುದೇ ಪರಿಣಾಮ ಬೀರುವುದಿಲ್ಲ', 'ಹೆಚ್ಚಿನ thresholds ಗಳು model ಅನ್ನೂ ಲೆಕ್ಕಿಸದೆ ಯಾವಾಗಲೂ ಕಡಿಮೆ, ದೊಡ್ಡ chunks ಗಳನ್ನೂ ಉತ್ಪಾದಿಸುತ್ತವೆ'], correct: 1 },
      { q: 'Per the 2026 research findings, what happened to retrieval quality when overlap was added between chunks?', qKn: '2026 ಸಂಶೋಧನಾ ಶೋಧನೆಗಳ ಪ್ರಕಾರ, chunks ಗಳ ನಡುವೆ overlap ಸೇರಿಸಿದಾಗ retrieval ಗುಣಮಟ್ಟಕ್ಕೆ ಏನಾಯಿತು?',
        opts: ['Overlap always dramatically improved retrieval quality', 'Overlap often provided little or no measurable improvement while increasing storage and indexing costs', 'Overlap made every chunking strategy perform identically', 'Overlap was found to be mandatory for any RAG system to function'],
        optsKn: ['Overlap ಯಾವಾಗಲೂ retrieval ಗುಣಮಟ್ಟವನ್ನೂ ನಾಟಕೀಯವಾಗಿ ಸುಧಾರಿಸಿತು', 'Overlap ಆಗಾಗ್ಗೆ ಶೇಖರಣೆ ಮತ್ತು indexing ವೆಚ್ಚಗಳನ್ನೂ ಹೆಚ್ಚಿಸುತ್ತಾ ಸ್ವಲ್ಪ ಅಥವಾ ಯಾವುದೇ ಅಳೆಯಬಹುದಾದ ಸುಧಾರಣೆ ಒದಗಿಸಲಿಲ್ಲ', 'Overlap ಪ್ರತಿ chunking ತಂತ್ರವನ್ನೂ ಒಂದೇ ರೀತಿ ಪ್ರದರ್ಶಿಸುವಂತೆ ಮಾಡಿತು', 'ಯಾವುದೇ RAG system ಕೆಲಸ ಮಾಡಲು overlap ಕಡ್ಡಾಯ ಎಂದು ಕಂಡುಬಂದಿತು'], correct: 1 },
      { q: 'Why did recursive chunking become the 2026 default over semantic chunking, according to this lesson?', qKn: 'ಈ lesson ಪ್ರಕಾರ, semantic chunking ಗಿಂತ recursive chunking 2026 ಡೀಫಾಲ್ಟ್ ಏಕೆ ಆಯಿತು?',
        opts: ['Semantic chunking was found to be technically impossible to implement', 'Benchmarks showed recursive chunking often achieved higher retrieval accuracy while being simpler, faster, and not requiring model inference at chunking time', 'Recursive chunking requires a GPU while semantic chunking does not', 'Semantic chunking was banned by major RAG frameworks'],
        optsKn: ['Semantic chunking ಅಳವಡಿಸಲು ತಾಂತ್ರಿಕವಾಗಿ ಅಸಾಧ್ಯ ಎಂದು ಕಂಡುಬಂದಿತು', 'Benchmarks ಗಳು recursive chunking ಆಗಾಗ್ಗೆ ಹೆಚ್ಚಿನ retrieval ನಿಖರತೆ ಸಾಧಿಸಿತು ಎಂದು ತೋರಿಸಿದವು, ಸರಳ, ವೇಗ, ಮತ್ತು chunking ಸಮಯದಲ್ಲಿ model inference ಅಗತ್ಯವಿಲ್ಲದಿರುತ್ತಾ', 'Recursive chunking ಗೆ ಒಂದು GPU ಅಗತ್ಯ ಆದರೆ semantic chunking ಗೆ ಅಲ್ಲ', 'Semantic chunking ಅನ್ನೂ ಪ್ರಮುಖ RAG frameworks ಗಳು ನಿಷೇಧಿಸಿದವು'], correct: 1 },
    ] } },
  ],
};
