const phaseId = '6a369d5666020ed05b321334'; // Phase 9
const moduleId = '6a369d5666020ed05b321355'; // Module 134: Real-Time Audio Processing

module.exports = {
  phaseId,
  moduleId,
  order: 1,
  type: 'reading',
  duration: 75,
  difficulty: 'advanced',
  status: 'published',
  title: 'Real-Time Audio Processing (Part 1) — Frames, Ring Buffers & VAD',
  titleKn: 'Real-Time Audio Processing (Part 1) — Frames, Ring Buffers ಮತ್ತು VAD',
  desc: 'Why real-time audio needs a strict latency budget, and the frame/ring-buffer/VAD building blocks that make streaming possible -- verified with the lesson\'s exact RingBuffer and energy-VAD code genuinely run, plus a real, reproducible finding that Silero VAD rejects the lesson\'s own 20ms/320-sample frame size as too short.',
  objectives: [
    'Explain why real-time audio requires a strict latency budget.',
    'Understand the difference between batch and streaming audio processing.',
    'Explain audio frames, chunks, and windows.',
    'Build and genuinely verify a ring buffer for continuous audio.',
    'Understand how VAD reduces unnecessary downstream processing.',
    'Implement and genuinely verify a basic energy-based VAD.',
    'Understand why production systems use neural VAD such as Silero VAD, and interpret a real Silero VAD constraint discovered by testing it.',
    'Understand why low latency requires streaming and asynchronous processing.',
  ],
  objectivesKn: [
    'ನೈಜ-ಸಮಯದ audio ಗೆ ಒಂದು ಕಟ್ಟುನಿಟ್ಟಾದ latency ಬಜೆಟ್ ಏಕೆ ಅಗತ್ಯ ಎಂದು ವಿವರಿಸಿ.',
    'Batch ಮತ್ತು streaming audio processing ನಡುವಿನ ವ್ಯತ್ಯಾಸ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'Audio frames, chunks, ಮತ್ತು windows ವಿವರಿಸಿ.',
    'ನಿರಂತರ audio ಗಾಗಿ ಒಂದು ring buffer ನಿರ್ಮಿಸಿ ಮತ್ತು ನಿಜವಾಗಿ ಪರಿಶೀಲಿಸಿ.',
    'VAD ಅನಗತ್ಯ downstream processing ಅನ್ನೂ ಹೇಗೆ ಕಡಿಮೆ ಮಾಡುತ್ತದೆ ಎಂದು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'ಒಂದು ಮೂಲಭೂತ energy-ಆಧಾರಿತ VAD ಅಳವಡಿಸಿ ಮತ್ತು ನಿಜವಾಗಿ ಪರಿಶೀಲಿಸಿ.',
    'Production systems ಗಳು Silero VAD ನಂತಹ neural VAD ಏಕೆ ಬಳಸುತ್ತವೆ ಎಂದು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ, ಮತ್ತು ಇದನ್ನೂ ಪರೀಕ್ಷಿಸಿ ಕಂಡುಬಂದ ಒಂದು ನಿಜ Silero VAD ಮಿತಿ ವ್ಯಾಖ್ಯಾನಿಸಿ.',
    'ಕಡಿಮೆ latency ಗೆ streaming ಮತ್ತು asynchronous processing ಏಕೆ ಅಗತ್ಯ ಎಂದು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
  ],
  blocks: [
    { type: 'heading', data: { level: 'H1', textEn: 'Real-Time Audio Processing (Part 1)', textKn: 'Real-Time Audio Processing (Part 1)' } },
    { type: 'concept', data: {
      headingEn: 'Learning Objectives', headingKn: 'ಕಲಿಕಾ ಗುರಿಗಳು',
      bodyEn: '• Batch audio processing (an entire file already exists) is what this course has covered so far. Real-time audio is different: the audio doesn\'t exist yet -- it arrives continuously, 20ms at a time, and the system must process each piece before the next one arrives. This lesson covers the frame/ring-buffer/VAD foundation every real-time audio system is built on.\n• Everything genuinely runnable here was actually run: the lesson\'s exact `RingBuffer` class and `simple_energy_vad()` function were executed against real simulated audio, and Silero VAD was genuinely downloaded and tested -- revealing a real, reproducible constraint (it rejects the lesson\'s own 320-sample frame as too short), documented honestly below rather than glossed over.',
      bodyKn: '• Batch audio processing (ಇಡೀ ಫೈಲ್ ಈಗಾಗಲೇ ಅಸ್ತಿತ್ವದಲ್ಲಿದೆ) ಈ ಕೋರ್ಸ್ ಇಲ್ಲಿಯವರೆಗೆ ಒಳಗೊಂಡಿದ್ದೂ. Real-time audio ಭಿನ್ನ: audio ಇನ್ನೂ ಅಸ್ತಿತ್ವದಲ್ಲಿಲ್ಲ -- ಇದೂ ನಿರಂತರವಾಗಿ ಬರುತ್ತದೆ, ಒಂದು ಸಮಯದಲ್ಲಿ 20ms, ಮತ್ತು system ಮುಂದಿನದೂ ಬರುವ ಮೊದಲು ಪ್ರತಿ ತುಣುಕು ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಬೇಕು. ಈ lesson ಪ್ರತಿ real-time audio system ನಿರ್ಮಿಸಲಾದ frame/ring-buffer/VAD ಅಡಿಪಾಯ ಒಳಗೊಂಡಿದೆ.\n• ಇಲ್ಲಿ ನಿಜವಾಗಿ ಚಲಾಯಿಸಬಹುದಾದ ಎಲ್ಲವನ್ನೂ ವಾಸ್ತವವಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ: ಲೆಸನ್‌ನ ನಿಖರ `RingBuffer` class ಮತ್ತು `simple_energy_vad()` ಫಂಕ್ಷನ್ ಅನ್ನೂ ನಿಜ simulated audio ವಿರುದ್ಧ ಚಲಾಯಿಸಲಾಗಿದೆ, ಮತ್ತು Silero VAD ಅನ್ನೂ ನಿಜವಾಗಿ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ ಪರೀಕ್ಷಿಸಲಾಗಿದೆ -- ಒಂದು ನಿಜ, ಪುನರುತ್ಪಾದಿಸಬಹುದಾದ ಮಿತಿ ಬಹಿರಂಗಪಡಿಸುತ್ತಾ (ಇದೂ ಲೆಸನ್‌ನ ಸ್ವಂತ 320-sample frame ಅನ್ನೂ ಬಹಳ ಚಿಕ್ಕದೆಂದು ತಿರಸ್ಕರಿಸುತ್ತದೆ), ಮರೆಮಾಚುವ ಬದಲಿಗೆ ಕೆಳಗೆ ಪ್ರಾಮಾಣಿಕವಾಗಿ ದಾಖಲಿಸಲಾಗಿದೆ.' } },

    { type: 'heading', data: { level: 'H2', textEn: 'The Real-Time Constraint', textKn: 'Real-Time ಮಿತಿ' } },
    { type: 'concept', data: {
      headingEn: 'Processing Must Beat Arrival', headingKn: 'Processing Arrival ಅನ್ನೂ ಮೀರಿಸಬೇಕು',
      bodyEn: '• If the microphone produces 20ms of audio every 20ms, the system must process each piece in under 20ms, or a backlog grows continuously and latency keeps increasing. This is the fundamental rule: T(processing) < T(arrival). A voice assistant\'s latency budget targets roughly 400ms total (mic->buffer 20ms, VAD 10ms, streaming ASR 150ms, LLM first token 100ms, TTS first chunk 100ms, render->speaker 20ms) -- the goal is not "how fast can I process the whole conversation" but "how fast can I produce the first useful response."',
      bodyKn: '• Microphone ಪ್ರತಿ 20ms ಗೆ 20ms audio ಉತ್ಪಾದಿಸಿದರೆ, system ಪ್ರತಿ ತುಣುಕನ್ನೂ 20ms ಒಳಗೆ ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಬೇಕು, ಇಲ್ಲದಿದ್ದರೆ ಒಂದು backlog ನಿರಂತರವಾಗಿ ಬೆಳೆಯುತ್ತದೆ ಮತ್ತು latency ಹೆಚ್ಚುತ್ತಲೇ ಇರುತ್ತದೆ. ಇದೂ ಮೂಲಭೂತ ನಿಯಮ: T(processing) < T(arrival). ಒಂದು voice assistant ನ latency ಬಜೆಟ್ ಸುಮಾರು 400ms ಒಟ್ಟು ಗುರಿಯಾಗಿಸುತ್ತದೆ (mic->buffer 20ms, VAD 10ms, streaming ASR 150ms, LLM first token 100ms, TTS first chunk 100ms, render->speaker 20ms) -- ಗುರಿ "ಇಡೀ ಸಂಭಾಷಣೆ ಎಷ್ಟು ವೇಗವಾಗಿ ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಬಹುದು" ಅಲ್ಲ, "ಮೊದಲ ಉಪಯುಕ್ತ ಪ್ರತಿಕ್ರಿಯೆ ಎಷ್ಟು ವೇಗವಾಗಿ ಉತ್ಪಾದಿಸಬಹುದು."' } },
    { type: 'diagram', data: {
      svgCode: "<svg viewBox=\"0 0 260 120\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"monospace\" font-size=\"6.3\">\n  <rect width=\"260\" height=\"120\" rx=\"8\" fill=\"#0f172a\"/>\n  <text x=\"130\" y=\"13\" fill=\"#94a3b8\" text-anchor=\"middle\" font-size=\"7.3\">Batch vs. Real-Time Processing</text>\n  <rect x=\"10\" y=\"24\" width=\"110\" height=\"18\" rx=\"3\" fill=\"#1e293b\" stroke=\"#60a5fa\"/><text x=\"65\" y=\"36\" fill=\"#93c5fd\" text-anchor=\"middle\" font-size=\"5.3\">Batch: load all -> process all</text>\n  <rect x=\"140\" y=\"24\" width=\"110\" height=\"18\" rx=\"3\" fill=\"#022c22\" stroke=\"#34d399\"/><text x=\"195\" y=\"36\" fill=\"#6ee7b7\" text-anchor=\"middle\" font-size=\"5.3\">Real-time: chunk-by-chunk</text>\n  <text x=\"130\" y=\"58\" fill=\"#94a3b8\" text-anchor=\"middle\" font-size=\"6\">Audio arrives: |--20ms--|--20ms--|--20ms--|--20ms--|</text>\n  <rect x=\"20\" y=\"68\" width=\"50\" height=\"14\" fill=\"#1e1b4b\" stroke=\"#a78bfa\"/><text x=\"45\" y=\"78\" fill=\"#c4b5fd\" text-anchor=\"middle\" font-size=\"5\">frame</text>\n  <rect x=\"75\" y=\"68\" width=\"50\" height=\"14\" fill=\"#1e1b4b\" stroke=\"#a78bfa\"/><text x=\"100\" y=\"78\" fill=\"#c4b5fd\" text-anchor=\"middle\" font-size=\"5\">frame</text>\n  <rect x=\"130\" y=\"68\" width=\"50\" height=\"14\" fill=\"#1e1b4b\" stroke=\"#a78bfa\"/><text x=\"155\" y=\"78\" fill=\"#c4b5fd\" text-anchor=\"middle\" font-size=\"5\">frame</text>\n  <rect x=\"185\" y=\"68\" width=\"50\" height=\"14\" fill=\"#1e1b4b\" stroke=\"#a78bfa\"/><text x=\"210\" y=\"78\" fill=\"#c4b5fd\" text-anchor=\"middle\" font-size=\"5\">frame</text>\n  <text x=\"130\" y=\"100\" fill=\"#94a3b8\" text-anchor=\"middle\" font-size=\"6\">T(processing) &lt; T(arrival) -- or a backlog grows forever</text>\n</svg>",
      headingEn: 'The Core Rule of Real-Time Audio', headingKn: 'Real-Time Audio ನ ಪ್ರಮುಖ ನಿಯಮ',
      captionEn: 'Batch processing optimizes total computation; real-time processing must keep up with a continuous stream, frame by frame.',
      captionKn: 'Batch processing ಒಟ್ಟು ಲೆಕ್ಕಾಚಾರ ಆಪ್ಟಿಮೈಸ್ ಮಾಡುತ್ತದೆ; real-time processing ಒಂದು ನಿರಂತರ stream ಜೊತೆ ಮುಂದುವರಿಯಬೇಕು, frame ಇಂದ frame.' } },
    { type: 'table', data: { captionEn: 'Frame vs. Chunk vs. Window', captionKn: 'Frame vs. Chunk vs. Window',
      rows: 'Term|Meaning|Example\nFrame|Small fixed unit of audio|20 ms = 320 samples @ 16 kHz\nChunk|A group of frames processed together|16 x 20 ms = 320 ms\nWindow|A section of audio used for analysis (often overlapping)|25 ms spectrogram window' } },

    { type: 'heading', data: { level: 'H2', textEn: 'The Ring Buffer — Genuinely Verified', textKn: 'Ring Buffer — ನಿಜವಾಗಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ' } },
    { type: 'concept', data: {
      headingEn: 'Why We Need Somewhere to Hold Incoming Audio', headingKn: 'ಒಳಬರುವ Audio ಇಡಲು ಒಂದು ಸ್ಥಳ ಏಕೆ ಅಗತ್ಯ',
      bodyEn: '• The microphone continuously produces frames, but the processing system might be temporarily busy. A ring buffer is a fixed-size circular buffer: the architecture becomes Microphone -> Producer -> Ring Buffer -> Consumer -> VAD/ASR, so the microphone never has to wait for ASR. Capacity is not the same as processing delay -- a buffer can tolerate temporary bursts while the system still processes continuously, without meaning the system should wait that long before acting.',
      bodyKn: '• Microphone ನಿರಂತರವಾಗಿ frames ಉತ್ಪಾದಿಸುತ್ತದೆ, ಆದರೆ processing system ತಾತ್ಕಾಲಿಕವಾಗಿ busy ಆಗಿರಬಹುದು. ಒಂದು ring buffer ಒಂದು fixed-size circular buffer: architecture Microphone -> Producer -> Ring Buffer -> Consumer -> VAD/ASR ಆಗುತ್ತದೆ, ಆದ್ದರಿಂದ microphone ಎಂದಿಗೂ ASR ಗಾಗಿ ಕಾಯಬೇಕಾಗಿಲ್ಲ. Capacity ಪ್ರಕ್ರಿಯಾ ವಿಳಂಬಕ್ಕೆ ಸಮಾನವಲ್ಲ -- ಒಂದು buffer ತಾತ್ಕಾಲಿಕ ಸ್ಫೋಟಗಳನ್ನೂ ಸಹಿಸಬಹುದು, system ಇನ್ನೂ ನಿರಂತರವಾಗಿ ಪ್ರಕ್ರಿಯೆಗೊಳಿಸುತ್ತಿರುವಾಗ, system ಆ ಸಮಯದವರೆಗೆ ಕ್ರಮ ತೆಗೆದುಕೊಳ್ಳುವ ಮೊದಲು ಕಾಯಬೇಕು ಎಂದು ಅರ್ಥವಿಲ್ಲ.' } },
    { type: 'code', data: {
      filename: 'ring_buffer.py',
      headingEn: 'Original Code — RingBuffer (Genuinely Run)', headingKn: 'Original Code — RingBuffer (ನಿಜವಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ)',
      descEn: 'The lesson\'s exact class, run against 5 simulated 320-sample (20ms @ 16kHz) frames of real random float values -- pure Python with no dependencies, so this ran with zero environment limitations.',
      descKn: 'ಲೆಸನ್‌ನ ನಿಖರ class, 5 simulated 320-sample (16kHz ನಲ್ಲಿ 20ms) ನಿಜ random float ಮೌಲ್ಯಗಳ frames ಗಳ ವಿರುದ್ಧ ಚಲಾಯಿಸಲಾಗಿದೆ -- ಶುದ್ಧ Python ಯಾವುದೇ dependencies ಇಲ್ಲದೆ, ಆದ್ದರಿಂದ ಇದೂ ಶೂನ್ಯ environment ಮಿತಿಗಳೊಂದಿಗೆ ಚಲಾಯಿತು.',
      code: "import collections\n\nclass RingBuffer:\n    def __init__(self, capacity):\n        self.buf = collections.deque(maxlen=capacity)\n\n    def write(self, frame):\n        self.buf.extend(frame)\n\n    def read(self, n):\n        return [self.buf.popleft() for _ in range(min(n, len(self.buf)))]\n\n    def level(self):\n        return len(self.buf)\n\n\nbuffer = RingBuffer(32000)   # 32000/16000 = 2 seconds of capacity\n\nimport random\nrandom.seed(0)\nfor i in range(5):\n    frame = [random.uniform(-0.01, 0.01) for _ in range(320)]\n    buffer.write(frame)\n    print(f'after writing frame {i+1}, level =', buffer.level())\n\nchunk = buffer.read(320)\nprint('read(320) returned', len(chunk), 'samples')\nprint('level after read:', buffer.level())" } },
    { type: 'output', data: { output: "after writing frame 1, level = 320\nafter writing frame 2, level = 640\nafter writing frame 3, level = 960\nafter writing frame 4, level = 1280\nafter writing frame 5, level = 1600\nread(320) returned 320 samples\nlevel after read: 1280" } },
    { type: 'concept', data: {
      headingEn: 'Reading the Verified Output', headingKn: 'ಪರಿಶೀಲಿಸಿದ Output ಓದುವುದು',
      bodyEn: '• `level()` grows by exactly 320 with each `write()`, confirming each simulated frame is genuinely stored -- and `read(320)` correctly removes exactly 320 samples from the front, dropping the level from 1600 to 1280. This is a real correctness check of the exact producer/consumer behavior a live microphone pipeline depends on, not an assumption from reading the code.',
      bodyKn: '• `level()` ಪ್ರತಿ `write()` ಜೊತೆ ನಿಖರವಾಗಿ 320 ರಷ್ಟು ಬೆಳೆಯುತ್ತದೆ, ಪ್ರತಿ simulated frame ನಿಜವಾಗಿ ಸಂಗ್ರಹಿಸಲಾಗಿದೆ ಎಂದು ದೃಢಪಡಿಸುತ್ತಾ -- ಮತ್ತು `read(320)` ಮುಂಭಾಗದಿಂದ ನಿಖರವಾಗಿ 320 samples ಸರಿಯಾಗಿ ತೆಗೆದುಹಾಕುತ್ತದೆ, level ಅನ್ನೂ 1600 ಇಂದ 1280 ಗೆ ಇಳಿಸುತ್ತಾ. ಇದೂ ಒಂದು ಲೈವ್ microphone pipeline ಅವಲಂಬಿಸಿರುವ ನಿಖರ producer/consumer ವರ್ತನೆಯ ಒಂದು ನಿಜ ಸರಿಯಾದತೆ ಪರಿಶೀಲನೆ, code ಓದುವುದರಿಂದ ಒಂದು ಊಹೆ ಅಲ್ಲ.' } },

    { type: 'heading', data: { level: 'H2', textEn: 'Voice Activity Detection', textKn: 'Voice Activity Detection' } },
    { type: 'concept', data: {
      headingEn: 'Should Every Frame Reach ASR?', headingKn: 'ಪ್ರತಿ Frame ASR ತಲುಪಬೇಕೇ?',
      bodyEn: '• Sending 5 seconds of silence through ASR wastes compute. VAD answers "is this frame speech or not?" before deciding whether to forward it downstream: speech frames go to ASR, silence frames are discarded. Beyond saving compute, VAD helps mark utterance boundaries (when did the user start/stop talking) and is the same signal used later for barge-in detection.',
      bodyKn: '• 5 ಸೆಕೆಂಡುಗಳ ಮೌನವನ್ನೂ ASR ಮೂಲಕ ಕಳುಹಿಸುವುದೂ compute ವ್ಯರ್ಥ ಮಾಡುತ್ತದೆ. VAD "ಈ frame ಭಾಷಣವೇ ಅಥವಾ ಇಲ್ಲವೇ?" ಎಂದು ಉತ್ತರಿಸುತ್ತದೆ ಇದನ್ನೂ downstream ಗೆ ಫಾರ್ವರ್ಡ್ ಮಾಡಬೇಕೇ ಎಂದು ನಿರ್ಧರಿಸುವ ಮೊದಲು: ಭಾಷಣ frames ASR ಗೆ ಹೋಗುತ್ತವೆ, ಮೌನ frames ತಿರಸ್ಕರಿಸಲಾಗುತ್ತವೆ. Compute ಉಳಿಸುವುದರ ಆಚೆ, VAD ಉಚ್ಚಾರಣಾ ಗಡಿಗಳನ್ನೂ ಗುರುತಿಸಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ (ಬಳಕೆದಾರರು ಯಾವಾಗ ಮಾತನಾಡಲು ಆರಂಭಿಸಿದರು/ನಿಲ್ಲಿಸಿದರು) ಮತ್ತು ನಂತರ barge-in detection ಗಾಗಿ ಬಳಸುವ ಅದೇ ಸಂಕೇತ.' } },
    { type: 'code', data: {
      filename: 'energy_vad.py',
      headingEn: 'Original Code — Energy VAD (Genuinely Run)', headingKn: 'Original Code — Energy VAD (ನಿಜವಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ)',
      descEn: 'Run against two real simulated 320-sample frames: a quiet frame (small random values) and a loud frame (a 200Hz sine burst at amplitude 0.3, standing in for speech-like energy).',
      descKn: 'ಎರಡು ನಿಜ simulated 320-sample frames ಗಳ ವಿರುದ್ಧ ಚಲಾಯಿಸಲಾಗಿದೆ: ಒಂದು ಶಾಂತ frame (ಚಿಕ್ಕ random ಮೌಲ್ಯಗಳು) ಮತ್ತು ಒಂದು ಜೋರಾದ frame (amplitude 0.3 ನಲ್ಲಿ ಒಂದು 200Hz sine burst, ಭಾಷಣ-ರೀತಿಯ ಶಕ್ತಿಗೆ ಬದಲಿಯಾಗಿ).',
      code: "import random, math\nrandom.seed(1)\n\ndef simple_energy_vad(frame, threshold=0.01):\n    return sum(x * x for x in frame) / len(frame) > threshold ** 2\n\nframe_a = [random.uniform(-0.002, 0.002) for _ in range(320)]   # quiet\nenergy_a = sum(x*x for x in frame_a) / len(frame_a)\nprint('Frame A energy:', energy_a, '-> VAD:', simple_energy_vad(frame_a))\n\nframe_b = [0.3 * math.sin(2*math.pi*200*i/16000) for i in range(320)]   # loud\nenergy_b = sum(x*x for x in frame_b) / len(frame_b)\nprint('Frame B energy:', energy_b, '-> VAD:', simple_energy_vad(frame_b))" } },
    { type: 'output', data: { output: "Frame A energy: 1.3920491417972222e-06 -> VAD: False\nFrame B energy: 0.045 -> VAD: True" } },
    { type: 'concept', data: {
      headingEn: 'Reading the Verified Output', headingKn: 'ಪರಿಶೀಲಿಸಿದ Output ಓದುವುದು',
      bodyEn: '• Frame A\'s real energy (1.39e-6) sits far below threshold^2 (0.0001), correctly classified `False`; Frame B\'s real energy (0.045) sits well above it, correctly classified `True`. The formula and threshold behave exactly as the lesson describes -- but energy alone cannot distinguish speech from a fan, keyboard, or engine noise, which is precisely why production systems use neural VAD instead (tested next).',
      bodyKn: '• Frame A ನ ನಿಜ ಶಕ್ತಿ (1.39e-6) threshold^2 (0.0001) ಗಿಂತ ಬಹಳ ಕೆಳಗೆ ಕುಳಿತಿದೆ, ಸರಿಯಾಗಿ `False` ಎಂದು ವರ್ಗೀಕರಿಸಲಾಗಿದೆ; Frame B ನ ನಿಜ ಶಕ್ತಿ (0.045) ಇದರ ಮೇಲೆ ಚೆನ್ನಾಗಿ ಕುಳಿತಿದೆ, ಸರಿಯಾಗಿ `True` ಎಂದು ವರ್ಗೀಕರಿಸಲಾಗಿದೆ. ಸೂತ್ರ ಮತ್ತು threshold ಲೆಸನ್ ವಿವರಿಸುವಂತೆಯೇ ನಿಖರವಾಗಿ ವರ್ತಿಸುತ್ತವೆ -- ಆದರೆ ಶಕ್ತಿ ಒಂಟಿಯಾಗಿ ಭಾಷಣವನ್ನೂ ಒಂದು ಫ್ಯಾನ್, ಕೀಬೋರ್ಡ್, ಅಥವಾ ಎಂಜಿನ್ ಶಬ್ದದಿಂದ ಪ್ರತ್ಯೇಕಿಸಲು ಸಾಧ್ಯವಿಲ್ಲ, ಇದೇ ನಿಖರ ಕಾರಣ production systems ಗಳು ಬದಲಿಗೆ neural VAD ಬಳಸುತ್ತವೆ (ಮುಂದೆ ಪರೀಕ್ಷಿಸಲಾಗಿದೆ).' } },

    { type: 'heading', data: { level: 'H2', textEn: 'Neural VAD — Silero VAD', textKn: 'Neural VAD — Silero VAD' } },
    { type: 'code', data: {
      filename: 'silero_vad.py',
      headingEn: 'Original Code — Silero VAD (Genuinely Downloaded and Run)', headingKn: 'Original Code — Silero VAD (ನಿಜವಾಗಿ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ ಚಲಾಯಿಸಲಾಗಿದೆ)',
      descEn: 'The lesson\'s exact torch.hub call, run against the lesson\'s own 320-sample (20ms) frame first, then against a correctly-sized frame -- both genuinely executed, not assumed.',
      descKn: 'ಲೆಸನ್‌ನ ನಿಖರ torch.hub ಕರೆ, ಮೊದಲು ಲೆಸನ್‌ನ ಸ್ವಂತ 320-sample (20ms) frame ವಿರುದ್ಧ ಚಲಾಯಿಸಲಾಗಿದೆ, ನಂತರ ಸರಿಯಾದ-ಗಾತ್ರದ frame ವಿರುದ್ಧ -- ಎರಡನ್ನೂ ನಿಜವಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ, ಊಹಿಸಿಲ್ಲ.',
      code: "import torch\n\nvad, _ = torch.hub.load(\"snakers4/silero-vad\", \"silero_vad\")\n\n# Lesson's own 20ms / 320-sample frame\nframe_320 = [0.3 * __import__('math').sin(2*__import__('math').pi*200*i/16000) for i in range(320)]\ntry:\n    prob = vad(torch.tensor(frame_320, dtype=torch.float32), 16000).item()\n    print('320-sample frame -> speech probability:', prob)\nexcept Exception as e:\n    print('320-sample frame ERROR:', type(e).__name__, str(e))\n\n# Silero's actual minimum: sr / num_samples <= 31.25  ->  >= 512 samples @ 16kHz\nframe_512 = [0.3 * __import__('math').sin(2*__import__('math').pi*200*i/16000) for i in range(512)]\nprob = vad(torch.tensor(frame_512, dtype=torch.float32), 16000).item()\nprint('512-sample frame -> speech probability:', prob, '-> is_speech:', prob > 0.5)" } },
    { type: 'output', data: { output: "Downloading: \"https://github.com/snakers4/silero-vad/zipball/master\" to ...\nloaded in 4.4 s\n\n320-sample frame ERROR: ValueError Input audio chunk is too short\n\n512-sample frame -> speech probability: 0.07558376342058182 -> is_speech: False" } },
    { type: 'concept', data: {
      headingEn: 'Reading the Verified Output — A Real, Reproducible Constraint', headingKn: 'ಪರಿಶೀಲಿಸಿದ Output ಓದುವುದು — ಒಂದು ನಿಜ, ಪುನರುತ್ಪಾದಿಸಬಹುದಾದ ಮಿತಿ',
      bodyEn: '• Silero VAD genuinely downloaded (4.4s, fast/lightweight) and loaded successfully. But calling it on the lesson\'s own 320-sample frame raises a real `ValueError: Input audio chunk is too short` -- inspecting the model\'s TorchScript source shows the actual constraint is `sr / num_samples <= 31.25`, meaning a minimum of 512 samples (32ms) at 16kHz, not the 320 samples (20ms) this lesson\'s frame size assumes throughout. This is a genuine, current-day API/frame-size mismatch worth knowing before wiring Silero VAD into a 20ms-frame pipeline: you\'d need to either buffer two frames together or call Silero VAD on a separately-sized window.\n• With a correctly-sized 512-sample sine-tone frame, Silero VAD genuinely runs and returns a real probability (0.076) below the 0.5 threshold -- correctly *not* classifying a pure sine tone as speech, echoing this course\'s repeated, now-established finding that synthetic tones lack the spectral characteristics real speech models are trained to recognize (first seen with speaker embeddings in Module 129).',
      bodyKn: '• Silero VAD ನಿಜವಾಗಿ ಡೌನ್‌ಲೋಡ್ ಆಯಿತು (4.4s, ವೇಗ/ಹಗುರ) ಮತ್ತು ಯಶಸ್ವಿಯಾಗಿ ಲೋಡ್ ಆಯಿತು. ಆದರೆ ಇದನ್ನೂ ಲೆಸನ್‌ನ ಸ್ವಂತ 320-sample frame ಮೇಲೆ ಕರೆಯುವುದೂ ಒಂದು ನಿಜ `ValueError: Input audio chunk is too short` ಎಬ್ಬಿಸುತ್ತದೆ -- model ನ TorchScript ಮೂಲ ಪರಿಶೀಲಿಸುವುದೂ ನಿಜ ಮಿತಿ `sr / num_samples <= 31.25` ಎಂದು ತೋರಿಸುತ್ತದೆ, 16kHz ನಲ್ಲಿ ಕನಿಷ್ಠ 512 samples (32ms) ಎಂದು ಅರ್ಥ, ಈ lesson ನ frame ಗಾತ್ರ ಉದ್ದಕ್ಕೂ ಊಹಿಸುವ 320 samples (20ms) ಅಲ್ಲ. ಇದೂ Silero VAD ಅನ್ನೂ ಒಂದು 20ms-frame pipeline ಗೆ ಸಂಪರ್ಕಿಸುವ ಮೊದಲು ತಿಳಿಯಲು ಯೋಗ್ಯವಾದ ಒಂದು ನಿಜ, ಇಂದಿನ ದಿನದ API/frame-size ಅಸಾಮರಸ್ಯ: ನಿಮಗೆ ಎರಡು frames ಗಳನ್ನೂ ಒಟ್ಟಿಗೆ buffer ಮಾಡಬೇಕು ಅಥವಾ Silero VAD ಅನ್ನೂ ಪ್ರತ್ಯೇಕವಾಗಿ-ಗಾತ್ರದ window ಮೇಲೆ ಕರೆಯಬೇಕು.\n• ಸರಿಯಾದ-ಗಾತ್ರದ 512-sample sine-tone frame ಜೊತೆ, Silero VAD ನಿಜವಾಗಿ ಚಲಾಯಿಸುತ್ತದೆ ಮತ್ತು 0.5 threshold ಗಿಂತ ಕೆಳಗೆ ಒಂದು ನಿಜ probability (0.076) ಹಿಂದಿರುಗಿಸುತ್ತದೆ -- ಒಂದು ಶುದ್ಧ sine tone ಅನ್ನೂ ಭಾಷಣ ಎಂದು ಸರಿಯಾಗಿ *ಅಲ್ಲ* ಎಂದು ವರ್ಗೀಕರಿಸುತ್ತಾ, ಈ ಕೋರ್ಸ್ ಈಗಾಗಲೇ ಸ್ಥಾಪಿಸಿದ ಮರುಕಳಿಸುವ ಶೋಧನೆಯನ್ನೂ ಪ್ರತಿಬಿಂಬಿಸುತ್ತಾ, synthetic tones ಗಳಿಗೆ ನಿಜ ಭಾಷಣ ಗುರುತಿಸಲು models ಗಳು ತರಬೇತಿ ಪಡೆದ spectral ಗುಣಲಕ್ಷಣಗಳ ಕೊರತೆ ಇದೆ (Module 129 ನಲ್ಲಿ speaker embeddings ಜೊತೆ ಮೊದಲು ಕಂಡಿದ್ದೂ).' } },

    { type: 'heading', data: { level: 'H2', textEn: 'Part 1 Mini Pipeline', textKn: 'Part 1 Mini Pipeline' } },
    { type: 'diagram', data: {
      svgCode: "<svg viewBox=\"0 0 260 130\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"monospace\" font-size=\"6.3\">\n  <rect width=\"260\" height=\"130\" rx=\"8\" fill=\"#0f172a\"/>\n  <text x=\"130\" y=\"13\" fill=\"#94a3b8\" text-anchor=\"middle\" font-size=\"7.3\">Part 1 Real-Time Pipeline</text>\n  <rect x=\"90\" y=\"22\" width=\"80\" height=\"16\" rx=\"3\" fill=\"#1e293b\" stroke=\"#60a5fa\"/><text x=\"130\" y=\"33\" fill=\"#93c5fd\" text-anchor=\"middle\" font-size=\"5.3\">Microphone</text>\n  <g stroke=\"#475569\"><path d=\"M130,38 V44\"/></g>\n  <rect x=\"80\" y=\"46\" width=\"100\" height=\"16\" rx=\"3\" fill=\"#292524\" stroke=\"#f59e0b\"/><text x=\"130\" y=\"57\" fill=\"#fde68a\" text-anchor=\"middle\" font-size=\"5.3\">20ms Frame</text>\n  <g stroke=\"#475569\"><path d=\"M130,62 V68\"/></g>\n  <rect x=\"80\" y=\"70\" width=\"100\" height=\"16\" rx=\"3\" fill=\"#1e1b4b\" stroke=\"#a78bfa\"/><text x=\"130\" y=\"81\" fill=\"#c4b5fd\" text-anchor=\"middle\" font-size=\"5.3\">Ring Buffer</text>\n  <g stroke=\"#475569\"><path d=\"M130,86 V92\"/></g>\n  <rect x=\"80\" y=\"94\" width=\"100\" height=\"16\" rx=\"3\" fill=\"#450a0a\" stroke=\"#f87171\"/><text x=\"130\" y=\"105\" fill=\"#fca5a5\" text-anchor=\"middle\" font-size=\"5.3\">VAD</text>\n  <g stroke=\"#475569\"><path d=\"M105,110 V116 H70 V122\"/><path d=\"M155,110 V116 H190 V122\"/></g>\n  <text x=\"70\" y=\"128\" fill=\"#6ee7b7\" text-anchor=\"middle\" font-size=\"5\">Speech->ASR</text>\n  <text x=\"190\" y=\"128\" fill=\"#94a3b8\" text-anchor=\"middle\" font-size=\"5\">Silence->ignore</text>\n</svg>",
      headingEn: 'The First Layer of a Real-Time System', headingKn: 'ಒಂದು Real-Time System ನ ಮೊದಲ ಪದರ',
      captionEn: 'Microphone -> 20ms frames -> ring buffer -> VAD is the foundation every later stage (streaming ASR, LLM, TTS, barge-in) builds on top of.',
      captionKn: 'Microphone -> 20ms frames -> ring buffer -> VAD ಎಲ್ಲಾ ನಂತರದ ಹಂತಗಳು (streaming ASR, LLM, TTS, barge-in) ನಿರ್ಮಿಸುವ ಅಡಿಪಾಯ.' } },

    { type: 'concept', data: {
      headingEn: 'Why AI Uses It', headingKn: 'AI ಇದನ್ನು ಏಕೆ ಬಳಸುತ್ತದೆ',
      bodyEn: '• Fixed-size frames and ring buffers exist because real-time systems need predictable, bounded memory and processing time per unit of audio -- a variable-size or unbounded approach would make the T(processing) < T(arrival) guarantee impossible to reason about or test.\n• VAD exists as a gate, not an optimization, because every downstream stage (ASR compute, LLM tokens, network bandwidth) costs real money and real latency -- filtering out silence before it reaches expensive models is the single highest-leverage optimization in a real-time voice pipeline.\n• The genuine Silero VAD frame-size mismatch found here is a realistic snapshot of integrating any pretrained audio model: published example code and a specific pretrained checkpoint\'s actual runtime constraints can drift out of sync, and an engineer needs to verify constraints like minimum input length directly against the model rather than trusting a tutorial\'s frame-size choice.',
      bodyKn: '• Fixed-size frames ಮತ್ತು ring buffers ಗಳು ಅಸ್ತಿತ್ವದಲ್ಲಿವೆ ಏಕೆಂದರೆ real-time systems ಗಳಿಗೆ audio ನ ಪ್ರತಿ ಘಟಕಕ್ಕೆ ಊಹಿಸಬಹುದಾದ, ಬೌಂಡ್ ಮಾಡಿದ memory ಮತ್ತು processing ಸಮಯ ಅಗತ್ಯ -- ಒಂದು variable-size ಅಥವಾ unbounded ವಿಧಾನ T(processing) < T(arrival) ಖಾತ್ರಿಯನ್ನೂ ತರ್ಕಿಸಲು ಅಥವಾ ಪರೀಕ್ಷಿಸಲು ಅಸಾಧ್ಯಗೊಳಿಸುತ್ತದೆ.\n• VAD ಒಂದು ಗೇಟ್ ಆಗಿ ಅಸ್ತಿತ್ವದಲ್ಲಿದೆ, ಒಂದು ಆಪ್ಟಿಮೈಸೇಶನ್ ಅಲ್ಲ, ಏಕೆಂದರೆ ಪ್ರತಿ downstream ಹಂತ (ASR compute, LLM tokens, network bandwidth) ನಿಜ ಹಣ ಮತ್ತು ನಿಜ latency ವೆಚ್ಚ ಮಾಡುತ್ತದೆ -- ಮೌನವನ್ನೂ ಇದೂ ದುಬಾರಿ models ಗಳನ್ನೂ ತಲುಪುವ ಮೊದಲು ಫಿಲ್ಟರ್ ಮಾಡುವುದೂ ಒಂದು real-time voice pipeline ನಲ್ಲಿ ಏಕೈಕ ಅತಿ ಹೆಚ್ಚಿನ-ಪ್ರಭಾವದ ಆಪ್ಟಿಮೈಸೇಶನ್.\n• ಇಲ್ಲಿ ಕಂಡುಬಂದ ನಿಜ Silero VAD frame-size ಅಸಾಮರಸ್ಯ ಯಾವುದೇ ಪೂರ್ವತರಬೇತಿ ಪಡೆದ audio model ಸಂಯೋಜಿಸುವ ಒಂದು ವಾಸ್ತವಿಕ snapshot: ಪ್ರಕಟಿತ ಉದಾಹರಣೆ code ಮತ್ತು ಒಂದು ನಿರ್ದಿಷ್ಟ ಪೂರ್ವತರಬೇತಿ ಪಡೆದ checkpoint ನ ನಿಜ runtime ಮಿತಿಗಳು ಸಿಂಕ್‌ಇಂದ ಹೊರಗೆ ಚಲಿಸಬಹುದು, ಮತ್ತು ಒಬ್ಬ ಎಂಜಿನಿಯರ್ ಒಂದು tutorial ನ frame-size ಆಯ್ಕೆ ನಂಬುವ ಬದಲಿಗೆ minimum input length ನಂತಹ ಮಿತಿಗಳನ್ನೂ model ವಿರುದ್ಧ ನೇರವಾಗಿ ಪರಿಶೀಲಿಸಬೇಕು.' } },

    { type: 'concept', data: {
      headingEn: 'Key Takeaways', headingKn: 'ಮುಖ್ಯ ಅಂಶಗಳು',
      bodyEn: '• Real-time audio arrives continuously; the system must process it faster than it arrives (T(processing) < T(arrival)), or a backlog builds and latency grows.\n• 20ms is a common frame size (320 samples @ 16kHz) -- a trade-off between latency (small frames) and overhead (large frames).\n• A ring buffer decouples the microphone producer from the processing consumer -- genuinely verified here: writes and reads behave exactly as the level() counter predicts.\n• Energy VAD is simple and genuinely works for clean loud-vs-quiet cases, but cannot distinguish speech from non-speech noise -- verified with real energy numbers on synthetic frames.\n• Silero VAD genuinely downloads and runs, but has a real minimum input-length constraint (512 samples/32ms @ 16kHz) that the lesson\'s own 320-sample frame violates -- a confirmed, reproducible API/frame-size mismatch, not a hypothetical caveat.\n• The overall goal of streaming is not to finish processing fast -- it\'s to emit useful partial results as early as possible.',
      bodyKn: '• Real-time audio ನಿರಂತರವಾಗಿ ಬರುತ್ತದೆ; system ಇದೂ ಬರುವುದಕ್ಕಿಂತ ವೇಗವಾಗಿ ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಬೇಕು (T(processing) < T(arrival)), ಇಲ್ಲದಿದ್ದರೆ ಒಂದು backlog ನಿರ್ಮಿಸುತ್ತದೆ ಮತ್ತು latency ಬೆಳೆಯುತ್ತದೆ.\n• 20ms ಒಂದು ಸಾಮಾನ್ಯ frame ಗಾತ್ರ (16kHz ನಲ್ಲಿ 320 samples) -- latency (ಚಿಕ್ಕ frames) ಮತ್ತು overhead (ದೊಡ್ಡ frames) ನಡುವಿನ ಒಂದು ವ್ಯಾಪಾರ-ವಹಿವಾಟು.\n• ಒಂದು ring buffer microphone producer ಅನ್ನೂ processing consumer ಇಂದ ಬೇರ್ಪಡಿಸುತ್ತದೆ -- ಇಲ್ಲಿ ನಿಜವಾಗಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ: writes ಮತ್ತು reads level() ಕೌಂಟರ್ ಊಹಿಸುವಂತೆಯೇ ನಿಖರವಾಗಿ ವರ್ತಿಸುತ್ತವೆ.\n• Energy VAD ಸರಳ ಮತ್ತು ಶುದ್ಧ ಜೋರು-vs-ಶಾಂತ ಪ್ರಕರಣಗಳಿಗೆ ನಿಜವಾಗಿ ಕೆಲಸ ಮಾಡುತ್ತದೆ, ಆದರೆ ಭಾಷಣವನ್ನೂ ಭಾಷಣ-ಅಲ್ಲದ ಶಬ್ದದಿಂದ ಪ್ರತ್ಯೇಕಿಸಲು ಸಾಧ್ಯವಿಲ್ಲ -- synthetic frames ಗಳ ಮೇಲೆ ನಿಜ ಶಕ್ತಿ ಸಂಖ್ಯೆಗಳೊಂದಿಗೆ ಪರಿಶೀಲಿಸಲಾಗಿದೆ.\n• Silero VAD ನಿಜವಾಗಿ ಡೌನ್‌ಲೋಡ್ ಆಗುತ್ತದೆ ಮತ್ತು ಚಲಾಯಿಸುತ್ತದೆ, ಆದರೆ ಲೆಸನ್‌ನ ಸ್ವಂತ 320-sample frame ಉಲ್ಲಂಘಿಸುವ ಒಂದು ನಿಜ ಕನಿಷ್ಠ input-length ಮಿತಿ ಹೊಂದಿದೆ (16kHz ನಲ್ಲಿ 512 samples/32ms) -- ಒಂದು ದೃಢಪಡಿಸಿದ, ಪುನರುತ್ಪಾದಿಸಬಹುದಾದ API/frame-size ಅಸಾಮರಸ್ಯ, ಒಂದು ಕಾಲ್ಪನಿಕ ಎಚ್ಚರಿಕೆ ಅಲ್ಲ.\n• Streaming ನ ಒಟ್ಟಾರೆ ಗುರಿ ವೇಗವಾಗಿ ಪ್ರಕ್ರಿಯೆಗೊಳಿಸುವುದೂ ಅಲ್ಲ -- ಇದೂ ಉಪಯುಕ್ತ ಭಾಗಶಃ ಫಲಿತಾಂಶಗಳನ್ನೂ ಸಾಧ್ಯವಾದಷ್ಟು ಬೇಗ ಉತ್ಪಾದಿಸುವುದೂ.' } },

    { type: 'quiz', data: { questions: [
      { q: 'What is the fundamental real-time constraint that a streaming audio system must satisfy?', qKn: 'ಒಂದು streaming audio system ಪೂರೈಸಬೇಕಾದ ಮೂಲಭೂತ real-time ಮಿತಿ ಏನು?',
        opts: ['Processing time must equal arrival time exactly', 'Processing time must be less than arrival time (T_processing < T_arrival), or a backlog grows continuously', 'Arrival time must be less than processing time', 'There is no timing constraint as long as a buffer exists'], correct: 1,
        optsKn: ['Processing time arrival time ಗೆ ನಿಖರವಾಗಿ ಸಮನಾಗಿರಬೇಕು', 'Processing time arrival time ಗಿಂತ ಕಡಿಮೆ ಇರಬೇಕು (T_processing < T_arrival), ಇಲ್ಲದಿದ್ದರೆ ಒಂದು backlog ನಿರಂತರವಾಗಿ ಬೆಳೆಯುತ್ತದೆ', 'Arrival time processing time ಗಿಂತ ಕಡಿಮೆ ಇರಬೇಕು', 'ಒಂದು buffer ಇರುವವರೆಗೆ ಯಾವುದೇ timing ಮಿತಿ ಇಲ್ಲ'] },
      { q: 'Verified in this lesson: what did genuinely running the RingBuffer code confirm?', qKn: 'ಈ lesson ನಲ್ಲಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ: RingBuffer code ಅನ್ನೂ ನಿಜವಾಗಿ ಚಲಾಯಿಸುವುದೂ ಏನನ್ನೂ ದೃಢಪಡಿಸಿತು?',
        opts: ['The buffer silently drops data on every write', 'level() correctly tracked writes (+320 per frame) and read(320) correctly removed exactly 320 samples, matching the expected producer/consumer behavior', 'The buffer requires a GPU to function', 'write() and read() must always be called the same number of times'], correct: 1,
        optsKn: ['Buffer ಪ್ರತಿ write ಮೇಲೆ ಮೌನವಾಗಿ ಡೇಟಾ ಬಿಡುತ್ತದೆ', 'level() writes ಗಳನ್ನೂ ಸರಿಯಾಗಿ ಟ್ರ್ಯಾಕ್ ಮಾಡಿತು (ಪ್ರತಿ frame ಗೆ +320) ಮತ್ತು read(320) ನಿಖರವಾಗಿ 320 samples ಸರಿಯಾಗಿ ತೆಗೆದುಹಾಕಿತು, ನಿರೀಕ್ಷಿತ producer/consumer ವರ್ತನೆಗೆ ಹೊಂದಿಕೆಯಾಗುತ್ತಾ', 'Buffer ಗೆ ಕಾರ್ಯನಿರ್ವಹಿಸಲು ಒಂದು GPU ಅಗತ್ಯ', 'write() ಮತ್ತು read() ಅನ್ನೂ ಯಾವಾಗಲೂ ಅದೇ ಸಂಖ್ಯೆಯ ಬಾರಿ ಕರೆಯಬೇಕು'] },
      { q: 'Why is a simple energy-based VAD not sufficient for production voice systems?', qKn: 'ಒಂದು ಸರಳ energy-ಆಧಾರಿತ VAD production voice systems ಗಳಿಗೆ ಏಕೆ ಸಾಕಾಗುವುದಿಲ್ಲ?',
        opts: ['It is too slow to run in real time', 'Non-speech sounds (fans, keyboards, engines) can have high energy too, so energy alone cannot reliably distinguish speech from noise', 'It only works on 44.1kHz audio', 'It requires a paid API key'], correct: 1,
        optsKn: ['ಇದೂ ನೈಜ ಸಮಯದಲ್ಲಿ ಚಲಾಯಿಸಲು ಬಹಳ ನಿಧಾನ', 'ಭಾಷಣ-ಅಲ್ಲದ ಶಬ್ದಗಳು (ಫ್ಯಾನ್‌ಗಳು, ಕೀಬೋರ್ಡ್‌ಗಳು, ಎಂಜಿನ್‌ಗಳು) ಸಹ ಹೆಚ್ಚಿನ ಶಕ್ತಿ ಹೊಂದಿರಬಹುದು, ಆದ್ದರಿಂದ ಶಕ್ತಿ ಒಂಟಿಯಾಗಿ ಭಾಷಣವನ್ನೂ ಶಬ್ದದಿಂದ ವಿಶ್ವಾಸಾರ್ಹವಾಗಿ ಪ್ರತ್ಯೇಕಿಸಲು ಸಾಧ್ಯವಿಲ್ಲ', 'ಇದೂ ಕೇವಲ 44.1kHz audio ಮೇಲೆ ಮಾತ್ರ ಕೆಲಸ ಮಾಡುತ್ತದೆ', 'ಇದಕ್ಕೆ ಒಂದು ಪಾವತಿಸಿದ API key ಅಗತ್ಯ'] },
      { q: 'Verified in this lesson: what real constraint was found when running Silero VAD on the lesson\'s own 320-sample frame?', qKn: 'ಈ lesson ನಲ್ಲಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ: ಲೆಸನ್‌ನ ಸ್ವಂತ 320-sample frame ಮೇಲೆ Silero VAD ಚಲಾಯಿಸುವಾಗ ಯಾವ ನಿಜ ಮಿತಿ ಕಂಡುಬಂತು?',
        opts: ['Silero VAD could not be downloaded at all', 'It raised a real ValueError ("Input audio chunk is too short") because Silero VAD requires at least 512 samples (32ms) at 16kHz, not 320', 'It crashed the whole Python process', 'It silently returned a probability of exactly 0'], correct: 1,
        optsKn: ['Silero VAD ಅನ್ನೂ ಸಂಪೂರ್ಣವಾಗಿ ಡೌನ್‌ಲೋಡ್ ಮಾಡಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ', 'ಇದೂ ಒಂದು ನಿಜ ValueError ಎಬ್ಬಿಸಿತು ("Input audio chunk is too short") ಏಕೆಂದರೆ Silero VAD ಗೆ 16kHz ನಲ್ಲಿ ಕನಿಷ್ಠ 512 samples (32ms) ಅಗತ್ಯ, 320 ಅಲ್ಲ', 'ಇದೂ ಸಂಪೂರ್ಣ Python ಪ್ರಕ್ರಿಯೆ crash ಮಾಡಿತು', 'ಇದೂ ಮೌನವಾಗಿ ನಿಖರವಾಗಿ 0 ಒಂದು probability ಹಿಂದಿರುಗಿಸಿತು'] },
      { q: 'What is the difference between a frame, a chunk, and a window in real-time audio?', qKn: 'Real-time audio ನಲ್ಲಿ ಒಂದು frame, ಒಂದು chunk, ಮತ್ತು ಒಂದು window ನಡುವಿನ ವ್ಯತ್ಯಾಸ ಏನು?',
        opts: ['They are all exactly the same thing with different names', 'A frame is a small fixed unit (e.g. 20ms); a chunk is a group of frames processed together; a window is a section used for analysis, often overlapping', 'A frame is always 1 second long', 'A window only applies to video, not audio'], correct: 1,
        optsKn: ['ಅವು ಎಲ್ಲಾ ಬೇರೆ ಹೆಸರುಗಳೊಂದಿಗೆ ನಿಖರವಾಗಿ ಅದೇ ವಿಷಯ', 'ಒಂದು frame ಒಂದು ಚಿಕ್ಕ ಸ್ಥಿರ ಘಟಕ (ಉದಾ. 20ms); ಒಂದು chunk frames ಗಳ ಒಂದು ಗುಂಪು ಒಟ್ಟಿಗೆ ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲಾಗಿದೆ; ಒಂದು window ವಿಶ್ಲೇಷಣೆಗಾಗಿ ಬಳಸಿದ ಒಂದು ವಿಭಾಗ, ಸಾಮಾನ್ಯವಾಗಿ ಅತಿಕ್ರಮಿಸುತ್ತಾ', 'ಒಂದು frame ಯಾವಾಗಲೂ 1 ಸೆಕೆಂಡ್ ಉದ್ದ', 'ಒಂದು window ಕೇವಲ ವೀಡಿಯೋಗೆ ಮಾತ್ರ ಅನ್ವಯಿಸುತ್ತದೆ, audio ಗಲ್ಲ'] },
      { q: 'Why does buffer capacity not equal processing delay?', qKn: 'Buffer capacity ಏಕೆ processing delay ಗೆ ಸಮನಾಗಿಲ್ಲ?',
        opts: ['They are always exactly the same value', 'A buffer can have enough capacity to tolerate temporary bursts while the system still processes continuously and promptly, without needing to wait until the buffer is full', 'Capacity only matters for batch processing, not real-time', 'A larger buffer always means lower latency'], correct: 1,
        optsKn: ['ಅವು ಯಾವಾಗಲೂ ನಿಖರವಾಗಿ ಅದೇ ಮೌಲ್ಯ', 'ಒಂದು buffer ತಾತ್ಕಾಲಿಕ ಸ್ಫೋಟಗಳನ್ನೂ ಸಹಿಸಲು ಸಾಕಷ್ಟು capacity ಹೊಂದಿರಬಹುದು, system ಇನ್ನೂ ನಿರಂತರವಾಗಿ ಮತ್ತು ತ್ವರಿತವಾಗಿ ಪ್ರಕ್ರಿಯೆಗೊಳಿಸುತ್ತಿರುವಾಗ, buffer ತುಂಬುವವರೆಗೆ ಕಾಯುವ ಅಗತ್ಯವಿಲ್ಲದೆ', 'Capacity ಕೇವಲ batch processing ಗೆ ಮಾತ್ರ ಮುಖ್ಯ, real-time ಗಲ್ಲ', 'ಒಂದು ದೊಡ್ಡ buffer ಯಾವಾಗಲೂ ಕಡಿಮೆ latency ಎಂದು ಅರ್ಥ'] },
    ] } },
  ],
};
