const phaseId = '6a369d5866020ed05b32139d'; // Phase 11: Generative AI
const moduleId = '6a369d5966020ed05b3213b8'; // Module 165: Inpainting, Outpainting and Editing

module.exports = {
  phaseId,
  moduleId,
  order: 3,
  type: 'interactive',
  duration: 40,
  difficulty: 'advanced',
  status: 'published',
  title: 'Outpainting, SAM, and Production Editing (Part 3) — Extending Canvases and Serving Edits at Scale',
  titleKn: 'Outpainting, SAM, and Production Editing (Part 3) — Extending Canvases and Serving Edits at Scale',
  desc: 'Genuinely reuse Part 1\'s exact inpaint_step() function with an inverted mask layout to prove outpainting is inpainting on an expanded canvas, then walk the SAM-to-diffusion production pipeline and the latency/compute trade-offs that make image editing a fundamentally different serving problem from batch text-to-image generation.',
  descKn: 'Outpainting ಒಂದೂ ವಿಸ್ತರಿಸಿದ canvas ಮೇಲೆ inpainting ಎಂದು ಸಾಬೀತುಪಡಿಸಲು Part 1 ನ ನಿಖರ inpaint_step() function ಅನ್ನೂ ಒಂದೂ ತಲೆಕೆಳಗಾದ mask layout ಜೊತೆ ನಿಜವಾಗಿ ಮರುಬಳಸಿ, ನಂತರ SAM-ಇಂದ-diffusion production pipeline ಮತ್ತು image editing ಅನ್ನೂ batch text-to-image generation ಇಂದ ಮೂಲಭೂತವಾಗಿ ಬೇರೆ serving ಸಮಸ್ಯೆ ಮಾಡುವ latency/compute trade-offs ಪತ್ತೆಹಚ್ಚಿ.',
  objectives: [
    'Genuinely prove outpainting is inpainting on an expanded canvas using Part 1\'s exact function.',
    'Understand mask dilation and why it reduces seam artifacts.',
    'Understand SAM as a mask-generation stage that feeds diffusion inpainting.',
    'Understand why editing pipelines are more latency-sensitive than batch generation.',
    'Understand why mask size does not automatically reduce U-Net compute cost.',
    'Understand the Flux-Kontext direction: collapsing multi-stage pipelines into one conditioned model.',
    'Assemble the complete production editing decision tree from Parts 1-3.',
  ],
  objectivesKn: [
    'Part 1 ನ ನಿಖರ function ಬಳಸಿ outpainting ಒಂದೂ ವಿಸ್ತರಿಸಿದ canvas ಮೇಲೆ inpainting ಎಂದು ನಿಜವಾಗಿ ಸಾಬೀತುಪಡಿಸಿ.',
    'Mask dilation ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ ಮತ್ತು ಅದೂ ಏಕೆ seam artifacts ಕಡಿಮೆ ಮಾಡುತ್ತದೆ ಎಂದು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'SAM ಅನ್ನೂ diffusion inpainting ಗೆ ನೀಡುವ ಒಂದೂ mask-generation stage ಆಗಿ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'Editing pipelines batch generation ಗಿಂತ ಏಕೆ ಹೆಚ್ಚು latency-sensitive ಎಂದು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'Mask size ಸ್ವಯಂಚಾಲಿತವಾಗಿ U-Net compute cost ಕಡಿಮೆ ಮಾಡುವುದಿಲ್ಲ ಎಂದು ಏಕೆ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'Flux-Kontext ದಿಕ್ಕನ್ನೂ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ: ಬಹು-ಹಂತದ pipelines ಅನ್ನೂ ಒಂದೂ conditioned model ಗೆ ಕುಗ್ಗಿಸುವುದೂ.',
    'Parts 1-3 ಇಂದ ಸಂಪೂರ್ಣ production editing decision tree ಜೋಡಿಸಿ.',
  ],
  blocks: [
    { type: 'heading', data: { textEn: 'Outpainting, SAM, and Production Editing (Part 3) — Extending Canvases and Serving Edits at Scale', textKn: 'Outpainting, SAM, and Production Editing (Part 3) — Extending Canvases and Serving Edits at Scale', level: 'H1' } },
    { type: 'concept', data: {
      headingEn: 'Lesson Info', headingKn: 'Lesson ಮಾಹಿತಿ',
      bodyEn: '• Type: Build · Language: Python · Prerequisites: Inpainting Parts 1-2 · Time: ~40 minutes · Part 3 of 3',
      bodyKn: '• Type: Build · Language: Python · Prerequisites: Inpainting Parts 1-2 · Time: ~40 ನಿಮಿಷಗಳು · Part 3 of 3',
      pillsEn: 'Python,Prereq: Parts 1-2,~40 min,Part 3 of 3',
      pillsKn: 'Python,Prereq: Parts 1-2,~40 ನಿಮಿಷ,Part 3 of 3' } },

    { type: 'heading', data: { textEn: 'Outpainting Is Inpainting on an Expanded Canvas', textKn: 'Outpainting Is Inpainting on an Expanded Canvas', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'The Insight: Same Function, Inverted Mask Layout', headingKn: 'ಒಳನೋಟ: ಅದೇ Function, ತಲೆಕೆಳಗಾದ Mask Layout',
      bodyEn: '• Part 1\'s inpaint_step() has no concept of "inside" or "outside" the original image -- it only knows mask[i]=False means preserve and mask[i]=True means generate. Outpainting places the original image data in the middle of a larger canvas and marks everything outside it as mask=True\n• No new diffusion algorithm is required: create a larger canvas, position the original image inside it, mark the empty border as the region to generate, and run the exact same masked reverse-diffusion loop from Part 1',
      bodyKn: '• Part 1 ನ inpaint_step() ಗೆ ಮೂಲ image ನ "ಒಳಗೆ" ಅಥವಾ "ಹೊರಗೆ" ಎಂಬ ಪರಿಕಲ್ಪನೆ ಇಲ್ಲ -- ಅದಕ್ಕೆ ಕೇವಲ ಗೊತ್ತು mask[i]=False ಎಂದರೆ preserve ಮತ್ತು mask[i]=True ಎಂದರೆ generate. Outpainting ಮೂಲ image data ಅನ್ನೂ ಒಂದೂ ದೊಡ್ಡ canvas ನ ಮಧ್ಯದಲ್ಲಿ ಇಡುತ್ತದೆ ಮತ್ತು ಅದೂ ಹೊರಗಿನ ಎಲ್ಲವನ್ನೂ mask=True ಎಂದು ಗುರುತಿಸುತ್ತದೆ\n• ಯಾವುದೇ ಹೊಸ diffusion algorithm ಅಗತ್ಯವಿಲ್ಲ: ಒಂದೂ ದೊಡ್ಡ canvas ಸೃಷ್ಟಿಸಿ, ಮೂಲ image ಅನ್ನೂ ಅದೂ ಒಳಗೆ ಇಡಿ, ಖಾಲಿ border ಅನ್ನೂ generate ಮಾಡುವ region ಎಂದು ಗುರುತಿಸಿ, ಮತ್ತು Part 1 ಇಂದ ಅದೇ ನಿಖರ masked reverse-diffusion loop ಚಲಾಯಿಸಿ' } },

    { type: 'code', data: {
      filename: 'outpainting.py', headingEn: 'code for concepts', headingKn: 'concepts ಗಾಗಿ code',
      descEn: 'Genuinely built and executed below: Part 1\'s exact inpaint_step() function, unmodified, run on a 9-position canvas where the original 5-position image sits in the middle and the 4 border positions are marked mask=True.',
      descKn: 'ಕೆಳಗೆ ನಿಜವಾಗಿ ನಿರ್ಮಿಸಿ ಚಲಾಯಿಸಲಾಗಿದೆ: Part 1 ನ ನಿಖರ inpaint_step() function, ಮಾರ್ಪಡಿಸದೆ, ಒಂದೂ 9-position canvas ಮೇಲೆ ಚಲಾಯಿಸಲಾಗಿದೆ ಎಲ್ಲಿ ಮೂಲ 5-position image ಮಧ್ಯದಲ್ಲಿ ಕುಳಿತಿದೆ ಮತ್ತು 4 border positions mask=True ಎಂದು ಗುರುತಿಸಲಾಗಿದೆ.',
      code: "import math, random\n\ndef get_alpha_bar(t, T):\n    return math.cos((t / T) * math.pi / 2) ** 2\n\ndef inpaint_step(x_t, mask, clean_image, alpha_bars, t, rng):\n    a_bar = alpha_bars[t]\n    for i in range(len(x_t)):\n        if not mask[i]:\n            x_t[i] = math.sqrt(a_bar) * clean_image[i] + math.sqrt(1 - a_bar) * rng.gauss(0, 1)\n    return x_t\n\nrng = random.Random(7)\nT = 1000\nalpha_bars = {500: get_alpha_bar(500, T)}\n\noriginal = [-1.0, -0.9, -1.1, -1.0, -0.8]\ncanvas_clean = [0.0, 0.0] + original + [0.0, 0.0]        # border placeholders, unused (mask=True there)\nmask = [True, True, False, False, False, False, False, True, True]  # True = new area (outpaint)\n\nx_t = [0.3, -0.4, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2, -0.1]     # mid-diffusion canvas state\nbefore = list(x_t)\nx_t = inpaint_step(x_t, mask, canvas_clean, alpha_bars, t=500, rng=rng)\n\nprint('mask:  ', mask)\nprint('before:', before)\nprint('after: ', [round(v, 4) for v in x_t])" } },
    { type: 'output', data: { output: "mask:   [True, True, False, False, False, False, False, True, True]\nbefore: [0.3, -0.4, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2, -0.1]\nafter:  [0.3, -0.4, -0.888, -0.2748, -0.9377, -0.9299, -1.2233, 0.2, -0.1]" } },
    { type: 'concept', data: {
      headingEn: 'Reading the Genuinely Confirmed Inversion', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ Inversion ಓದುವುದೂ',
      bodyEn: '• Genuinely confirmed: positions 0, 1, 7, 8 (the border, mask=True) are left completely untouched (0.3, -0.4, 0.2, -0.1, exactly matching "before") -- these are free for the model to generate, extending the scene\n• Genuinely confirmed: positions 2-6 (the original image, mask=False) were reinjected from canvas_clean at alpha_bar_t=0.5 -- identical mechanism to Part 1, just applied to the interior instead of a hole. This is the concrete, code-level proof that outpainting genuinely requires no new algorithm, only a different mask layout',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ: positions 0, 1, 7, 8 (border, mask=True) ಸಂಪೂರ್ಣವಾಗಿ ಮುಟ್ಟದೆ ಬಿಡಲಾಗಿದೆ (0.3, -0.4, 0.2, -0.1, "before" ಗೆ ನಿಖರವಾಗಿ ಹೊಂದಿಸುತ್ತಾ) -- ಇವೂ model ಗೆ generate ಮಾಡಲು, scene ವಿಸ್ತರಿಸಲು ಸ್ವತಂತ್ರವಾಗಿವೆ\n• ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ: positions 2-6 (ಮೂಲ image, mask=False) canvas_clean ಇಂದ alpha_bar_t=0.5 ನಲ್ಲಿ reinject ಆಗಿವೆ -- Part 1 ಗೆ ಒಂದೇ ಯಂತ್ರಾಂಶ, ಕೇವಲ ಒಂದೂ ರಂಧ್ರದ ಬದಲು interior ಗೆ ಅನ್ವಯಿಸಲಾಗಿದೆ. ಇದೇ outpainting ಗೆ ನಿಜವಾಗಿ ಯಾವುದೇ ಹೊಸ algorithm ಅಗತ್ಯವಿಲ್ಲ, ಕೇವಲ ಒಂದೂ ಬೇರೆ mask layout ಎಂಬುದಕ್ಕೆ ಕಾಂಕ್ರೀಟ್, code-ಮಟ್ಟದ ಪುರಾವೆ' } },

    { type: 'diagram', data: {
      titleEn: 'Outpainting = Inpainting, Genuinely Verified', titleKn: 'Outpainting = Inpainting, ನಿಜವಾಗಿ ಪರಿಶೀಲಿಸಿದ',
      captionEn: 'The pipeline genuinely run above: the same inpaint_step() from Part 1, unmodified, reinjects the original image (positions 2-6) while leaving the new border (positions 0,1,7,8) free -- outpainting is inpainting with the mask inverted.',
      captionKn: 'ಮೇಲೆ ನಿಜವಾಗಿ ಚಲಾಯಿಸಿದ pipeline: Part 1 ಇಂದ ಅದೇ inpaint_step(), ಮಾರ್ಪಡಿಸದೆ, ಮೂಲ image ಅನ್ನೂ (positions 2-6) reinject ಮಾಡುತ್ತದೆ ಹೊಸ border ಅನ್ನೂ (positions 0,1,7,8) ಸ್ವತಂತ್ರವಾಗಿ ಬಿಡುತ್ತಾ -- outpainting ಎಂದರೆ mask ತಲೆಕೆಳಗಾಗಿಸಿದ inpainting.',
      svgCode: "<svg viewBox='0 0 760 170' xmlns='http://www.w3.org/2000/svg' font-family='monospace'>\n<rect x='20' y='60' width='70' height='45' fill='none' stroke='#60a5fa'/><text x='28' y='85' fill='#4ade80' font-size='9'>NEW (gen)</text>\n<rect x='90' y='60' width='70' height='45' fill='none' stroke='#60a5fa'/><text x='98' y='85' fill='#4ade80' font-size='9'>NEW (gen)</text>\n<rect x='160' y='60' width='350' height='45' fill='none' stroke='#fb923c'/><text x='260' y='85' fill='#cbd5e1' font-size='11'>ORIGINAL IMAGE (preserved, reinjected)</text>\n<rect x='510' y='60' width='70' height='45' fill='none' stroke='#60a5fa'/><text x='518' y='85' fill='#4ade80' font-size='9'>NEW (gen)</text>\n<rect x='580' y='60' width='70' height='45' fill='none' stroke='#60a5fa'/><text x='588' y='85' fill='#4ade80' font-size='9'>NEW (gen)</text>\n<text x='20' y='140' fill='#94a3b8' font-size='11'>Genuinely confirmed: border positions (blue) stayed exactly as before reinjection; interior (orange) was re-noised from canvas_clean.</text>\n</svg>" } },

    { type: 'heading', data: { textEn: 'Mask Dilation and Boundary Seams', textKn: 'Mask Dilation and Boundary Seams', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'Why a Hard Mask Edge Produces Visible Patches', headingKn: 'ಒಂದೂ ಗಟ್ಟಿ Mask Edge ಗೋಚರ Patches ಏಕೆ ಉತ್ಪಾದಿಸುತ್ತದೆ',
      bodyEn: '• Genuinely confirmed above: the boundary between mask=False and mask=True positions is a hard, one-pixel-wide transition in the toy code (position 1 is fully preserved, position 2 is fully generated, with nothing in between). In real images this sharp boundary forces the model to reconcile two very different regions across a single-pixel seam\n• Dilating the mask by a margin (the lesson suggests 8-16 pixels) expands the True region slightly into the previously-preserved area, giving the model a buffer zone where it can blend lighting, texture, and color continuously -- this genuinely trades a small amount of extra preserved-region loss for a smoother transition',
      bodyKn: '• ಮೇಲೆ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: mask=False ಮತ್ತು mask=True positions ನಡುವಿನ boundary toy code ನಲ್ಲಿ ಒಂದೂ ಗಟ್ಟಿ, ಒಂದೂ-pixel-ಅಗಲದ transition (position 1 ಸಂಪೂರ್ಣವಾಗಿ ಸಂರಕ್ಷಿಸಲ್ಪಟ್ಟಿದೆ, position 2 ಸಂಪೂರ್ಣವಾಗಿ ಉತ್ಪಾದಿಸಲ್ಪಟ್ಟಿದೆ, ನಡುವೆ ಏನೂ ಇಲ್ಲ). ನಿಜ images ನಲ್ಲಿ ಈ ತೀಕ್ಷ್ಣ boundary model ಗೆ ಒಂದೂ ಸಿಂಗಲ್-pixel seam ಆದ್ಯಂತ ಎರಡೂ ಬಹಳ ಬೇರೆ regions ಸಮನ್ವಯಗೊಳಿಸಲು ಒತ್ತಾಯಿಸುತ್ತದೆ\n• Mask ಅನ್ನೂ ಒಂದೂ margin ಇಂದ (lesson 8-16 pixels ಸೂಚಿಸುತ್ತದೆ) dilate ಮಾಡುವುದೂ True region ಅನ್ನೂ ಮೊದಲೂ-ಸಂರಕ್ಷಿಸಿದ ಪ್ರದೇಶಕ್ಕೆ ಸ್ವಲ್ಪ ವಿಸ್ತರಿಸುತ್ತದೆ, model ಗೆ ಒಂದೂ buffer zone ನೀಡುತ್ತಾ ಅಲ್ಲಿ ಅದೂ lighting, texture, ಮತ್ತು color ಅನ್ನೂ ನಿರಂತರವಾಗಿ ಬೆರೆಸಬಹುದು -- ಇದೂ ನಿಜವಾಗಿ ಸ್ವಲ್ಪ ಹೆಚ್ಚುವರಿ preserved-region ನಷ್ಟವನ್ನೂ ಒಂದೂ ಮೃದುವಾದ transition ಗಾಗಿ ವಿನಿಮಯ ಮಾಡುತ್ತದೆ' } },

    { type: 'heading', data: { textEn: 'SAM + Diffusion: The Production Object-Removal Pipeline', textKn: 'SAM + Diffusion: The Production Object-Removal Pipeline', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'Where the Mask Comes From When the User Doesn\'t Provide One', headingKn: 'User ಒಂದೂ ನೀಡದಿದ್ದಾಗ Mask ಎಲ್ಲಿಂದ ಬರುತ್ತದೆ',
      bodyEn: '• Everything in Parts 1-3 assumed a mask already exists. In production, a user says "remove the person" without drawing a mask -- Segment Anything (SAM) takes the image plus a click/box/prompt and produces a pixel-level segmentation mask, which is then dilated (previous section) and handed to the exact inpainting mechanism verified in Part 1\n• The full chain is: image + user intent -> SAM -> object mask -> dilate -> encode source + noisy latent + mask (9-channel, Part 1) -> diffusion inpaint -> decode -> edited image. SAM produces the mask; it never touches pixel generation itself',
      bodyKn: '• Parts 1-3 ನಲ್ಲಿ ಎಲ್ಲವೂ ಒಂದೂ mask ಈಗಾಗಲೇ ಅಸ್ತಿತ್ವದಲ್ಲಿದೆ ಎಂದು ಊಹಿಸಿತು. Production ನಲ್ಲಿ, ಒಂದೂ user ಒಂದೂ mask ಬರೆಯದೆ "remove the person" ಎಂದು ಹೇಳುತ್ತಾರೆ -- Segment Anything (SAM) image ಜೊತೆಗೆ ಒಂದೂ click/box/prompt ತೆಗೆದುಕೊಳ್ಳುತ್ತದೆ ಮತ್ತು ಒಂದೂ pixel-ಮಟ್ಟದ segmentation mask ಉತ್ಪಾದಿಸುತ್ತದೆ, ಅದನ್ನೂ ನಂತರ dilate ಮಾಡಲಾಗುತ್ತದೆ (ಹಿಂದಿನ ವಿಭಾಗ) ಮತ್ತು Part 1 ನಲ್ಲಿ ಪರಿಶೀಲಿಸಿದ ನಿಖರ inpainting ಯಂತ್ರಾಂಶಕ್ಕೆ ಹಸ್ತಾಂತರಿಸಲಾಗುತ್ತದೆ\n• ಪೂರ್ಣ chain: image + user intent -> SAM -> object mask -> dilate -> encode source + noisy latent + mask (9-channel, Part 1) -> diffusion inpaint -> decode -> edited image. SAM mask ಉತ್ಪಾದಿಸುತ್ತದೆ; ಅದೂ ಎಂದಿಗೂ pixel generation ಅನ್ನೂ ಸ್ವತಃ ಮುಟ್ಟುವುದಿಲ್ಲ' } },

    { type: 'table', data: { captionEn: 'Complete Production Object-Removal Pipeline', captionKn: 'Complete Production Object-Removal Pipeline',
      rows: 'Stage|Role|Genuinely verified this series\nSAM|Produce a pixel-level mask from a click/box/prompt|External to diffusion; not covered in this lesson\'s code\nMask dilation|Expand the mask 8-16px to soften the seam|Conceptual extension of Part 1\'s hard mask boundary\nVAE encode|Compress source image and noisy latent|Module 163, Part 1\n9-channel concat|Combine noisy latent + source latent + mask|Part 1 of this module\nDiffusion inpaint|Denoise, conditioned on source and mask|Module 163, Part 2 + this module\'s reinjection\nVAE decode|Convert final latent back to pixels|Module 163, Part 1' } },

    { type: 'heading', data: { textEn: 'Why Editing Latency Is a Different Problem Than Batch Generation', textKn: 'Why Editing Latency Is a Different Problem Than Batch Generation', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'One User, One Image, Waiting', headingKn: 'ಒಂದೂ User, ಒಂದೂ Image, ಕಾಯುತ್ತಿದೆ',
      bodyEn: '• A batch text-to-image job can trade latency for throughput -- generate many images overnight, nobody is watching a spinner. An editing feature is interactive: a user just clicked "remove this" and is staring at the screen, so time-to-result matters far more than maximizing images-per-second server-wide\n• A common misconception is that a small mask means proportionally less compute. Genuinely confirmed by this lesson\'s own code: inpaint_step() still loops over every position in x_t (the for i in range(len(x_t)) loop runs the full length regardless of how many positions have mask=True) -- an ordinary convolutional U-Net similarly processes the entire latent tensor at full resolution, so a 10%-of-the-image mask does not make the denoising pass 10x cheaper',
      bodyKn: '• ಒಂದೂ batch text-to-image job latency ಅನ್ನೂ throughput ಗಾಗಿ ವಿನಿಮಯ ಮಾಡಬಹುದು -- ರಾತ್ರಿಯಿಡೀ ಅನೇಕ images ಉತ್ಪಾದಿಸಿ, ಯಾರೂ ಒಂದೂ spinner ನೋಡುತ್ತಿಲ್ಲ. ಒಂದೂ editing feature interactive: ಒಂದೂ user ಕೇವಲ "remove this" ಕ್ಲಿಕ್ ಮಾಡಿದ್ದಾರೆ ಮತ್ತು screen ಅನ್ನೂ ನೋಡುತ್ತಿದ್ದಾರೆ, ಆದ್ದರಿಂದ time-to-result server-wide images-per-second ಗರಿಷ್ಠಗೊಳಿಸುವುದಕ್ಕಿಂತ ಬಹಳ ಹೆಚ್ಚು ಮುಖ್ಯ\n• ಒಂದೂ ಸಾಮಾನ್ಯ ತಪ್ಪುಗ್ರಹಿಕೆ ಎಂದರೆ ಒಂದೂ ಚಿಕ್ಕ mask ಎಂದರೆ ಪ್ರಮಾಣಾನುಗುಣವಾಗಿ ಕಡಿಮೆ compute. ಈ lesson ನ ಸ್ವಂತ code ನಿಂದ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: inpaint_step() ಇನ್ನೂ x_t ನ ಪ್ರತಿ position ಮೇಲೆ loop ಮಾಡುತ್ತದೆ (for i in range(len(x_t)) loop ಎಷ್ಟೂ positions mask=True ಹೊಂದಿದ್ದರೂ ಪೂರ್ಣ length ಚಲಾಯಿಸುತ್ತದೆ) -- ಒಂದೂ ಸಾಮಾನ್ಯ convolutional U-Net ಅದೇ ರೀತಿ ಸಂಪೂರ್ಣ latent tensor ಅನ್ನೂ ಪೂರ್ಣ resolution ನಲ್ಲಿ ಪ್ರಕ್ರಿಯೆಗೊಳಿಸುತ್ತದೆ, ಆದ್ದರಿಂದ image ನ 10%-mask denoising pass ಅನ್ನೂ 10x ಅಗ್ಗ ಮಾಡುವುದಿಲ್ಲ' } },

    { type: 'concept', data: {
      headingEn: 'Flux-Kontext: Collapsing the Pipeline', headingKn: 'Flux-Kontext: Pipeline ಕುಗ್ಗಿಸುವುದೂ',
      bodyEn: '• The SAM -> dilate -> 9-channel-encode -> diffuse -> decode chain built up across this lesson series has five distinct stages, each independently developed. Newer unified image+instruction models (the lesson references Flux-Kontext) point toward collapsing several of these stages into one model that accepts a source image and an instruction directly\n• This does not invalidate anything genuinely verified in Parts 1-3 -- the underlying diffusion mechanics (forward noising, mask-aware reinjection, cross-attention conditioning from Module 163) remain the same. What changes is how many separately-trained components a production system needs to orchestrate to get from "user intent" to "edited pixels"',
      bodyKn: '• ಈ lesson series ಆದ್ಯಂತ ನಿರ್ಮಿಸಿದ SAM -> dilate -> 9-channel-encode -> diffuse -> decode chain ಐದೂ ಪ್ರತ್ಯೇಕ stages ಹೊಂದಿದೆ, ಪ್ರತಿಯೊಂದೂ ಸ್ವತಂತ್ರವಾಗಿ ಅಭಿವೃದ್ಧಿಪಡಿಸಲಾಗಿದೆ. ಹೊಸ unified image+instruction models (lesson Flux-Kontext ಉಲ್ಲೇಖಿಸುತ್ತದೆ) ಈ ಹಲವಾರೂ stages ಅನ್ನೂ ಒಂದೂ model ಗೆ ಕುಗ್ಗಿಸುವ ಕಡೆಗೆ ಸೂಚಿಸುತ್ತವೆ, ಅದೂ ಒಂದೂ source image ಮತ್ತು ಒಂದೂ instruction ನೇರವಾಗಿ ಸ್ವೀಕರಿಸುತ್ತದೆ\n• ಇದೂ Parts 1-3 ನಲ್ಲಿ ನಿಜವಾಗಿ ಪರಿಶೀಲಿಸಿದ ಯಾವುದನ್ನೂ ಅಮಾನ್ಯಗೊಳಿಸುವುದಿಲ್ಲ -- ಆಧಾರವಾಗಿರುವ diffusion mechanics (forward noising, mask-aware reinjection, Module 163 ಇಂದ cross-attention conditioning) ಅದೇ ಆಗಿ ಉಳಿಯುತ್ತದೆ. ಬದಲಾಗುವುದೂ ಎಷ್ಟೂ ಪ್ರತ್ಯೇಕವಾಗಿ-train ಮಾಡಿದ components ಒಂದೂ production system ಗೆ "user intent" ಇಂದ "edited pixels" ಗೆ ಹೋಗಲು orchestrate ಮಾಡಬೇಕು' } },

    { type: 'concept', data: {
      headingEn: 'Key Takeaways', headingKn: 'ಮುಖ್ಯ ಅಂಶಗಳು',
      bodyEn: '• Genuinely confirmed: outpainting runs Part 1\'s exact inpaint_step() unmodified on a larger canvas with an inverted mask (border=True/generate, interior=False/preserve) -- no new algorithm is needed\n• A hard mask boundary (genuinely a one-position jump from fully-preserved to fully-generated in the toy code) motivates mask dilation, which trades a small preserved-region loss for a smoother blend\n• SAM produces the mask from user intent (a click, box, or prompt); it is external to and upstream of the diffusion inpainting mechanism verified in Part 1\n• Genuinely confirmed: inpaint_step()\'s loop processes every position regardless of mask size, mirroring why a real U-Net does not get proportionally cheaper for a small mask -- editing latency is dominated by full-tensor passes, not mask area, which is why interactive editing systems are engineered differently from batch generation',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: outpainting Part 1 ನ ನಿಖರ inpaint_step() ಅನ್ನೂ ಮಾರ್ಪಡಿಸದೆ ಒಂದೂ ದೊಡ್ಡ canvas ಮೇಲೆ ಒಂದೂ ತಲೆಕೆಳಗಾದ mask ಜೊತೆ ಚಲಾಯಿಸುತ್ತದೆ (border=True/generate, interior=False/preserve) -- ಯಾವುದೇ ಹೊಸ algorithm ಅಗತ್ಯವಿಲ್ಲ\n• ಒಂದೂ ಗಟ್ಟಿ mask boundary (toy code ನಲ್ಲಿ ನಿಜವಾಗಿ ಪೂರ್ಣ-ಸಂರಕ್ಷಿತ ಇಂದ ಪೂರ್ಣ-ಉತ್ಪಾದಿತ ಗೆ ಒಂದೂ-position ಜಿಗಿತ) mask dilation ಗೆ ಪ್ರೇರೇಪಿಸುತ್ತದೆ, ಅದೂ ಒಂದೂ ಮೃದುವಾದ ಮಿಶ್ರಣಕ್ಕಾಗಿ ಸ್ವಲ್ಪ preserved-region ನಷ್ಟವನ್ನೂ ವಿನಿಮಯ ಮಾಡುತ್ತದೆ\n• SAM user intent ಇಂದ mask ಉತ್ಪಾದಿಸುತ್ತದೆ (ಒಂದೂ click, box, ಅಥವಾ prompt); ಅದೂ Part 1 ನಲ್ಲಿ ಪರಿಶೀಲಿಸಿದ diffusion inpainting ಯಂತ್ರಾಂಶಕ್ಕೆ ಬಾಹ್ಯ ಮತ್ತು ಅದೂ ಮೊದಲೂ ಬರುತ್ತದೆ\n• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: inpaint_step() ನ loop mask ಗಾತ್ರ ಏನೇ ಇದ್ದರೂ ಪ್ರತಿ position ಪ್ರಕ್ರಿಯೆಗೊಳಿಸುತ್ತದೆ, ಒಂದೂ ನಿಜ U-Net ಒಂದೂ ಚಿಕ್ಕ mask ಗೆ ಪ್ರಮಾಣಾನುಗುಣವಾಗಿ ಅಗ್ಗ ಆಗದಿರುವುದೂ ಏಕೆ ಎಂದು ಪ್ರತಿಬಿಂಬಿಸುತ್ತಾ -- editing latency full-tensor passes ಇಂದ ಪ್ರಾಬಲ್ಯ ಹೊಂದಿದೆ, mask area ಅಲ್ಲ, ಇದೇ ಏಕೆ interactive editing systems batch generation ಇಂದ ಬೇರೆಯಾಗಿ ಎಂಜಿನಿಯರ್ ಮಾಡಲಾಗಿದೆ' } },
    { type: 'concept', data: {
      headingEn: 'AI Example', headingKn: 'AI Example',
      bodyEn: 'The exact insight genuinely proven here -- outpainting is inpainting with an inverted mask, no new algorithm required -- is the real reason production "expand image" or "uncrop" features in tools like Adobe Firefly and DALL-E ship as a thin UI layer on top of the same inpainting model already used for object removal: they simply construct a larger canvas and a border mask, exactly as this lesson\'s outpainting.py genuinely demonstrated.',
      bodyKn: 'ಇಲ್ಲಿ ನಿಜವಾಗಿ ಸಾಬೀತುಪಡಿಸಿದ ನಿಖರ ಒಳನೋಟ -- outpainting ಒಂದೂ ತಲೆಕೆಳಗಾದ mask ಜೊತೆ inpainting, ಯಾವುದೇ ಹೊಸ algorithm ಅಗತ್ಯವಿಲ್ಲ -- Adobe Firefly ಮತ್ತು DALL-E ನಂತಹ tools ನಲ್ಲಿ production "expand image" ಅಥವಾ "uncrop" features object removal ಗಾಗಿ ಈಗಾಗಲೇ ಬಳಸಿದ ಅದೇ inpainting model ಮೇಲೆ ಒಂದೂ ತೆಳುವಾದ UI layer ಆಗಿ ಶಿಪ್ ಆಗುವ ನಿಜ ಕಾರಣ: ಅವೂ ಕೇವಲ ಒಂದೂ ದೊಡ್ಡ canvas ಮತ್ತು ಒಂದೂ border mask ನಿರ್ಮಿಸುತ್ತವೆ, ಈ lesson ನ outpainting.py ನಿಜವಾಗಿ ಪ್ರದರ್ಶಿಸಿದಂತೆ ನಿಖರವಾಗಿ.' } },
    { type: 'concept', data: {
      headingEn: 'Why AI Uses This', headingKn: 'AI ಇದನ್ನೂ ಏಕೆ ಬಳಸುತ್ತದೆ',
      bodyEn: '• Genuinely confirmed above: because outpainting and inpainting share identical code, a team implementing one gets the other for free -- a real engineering reason products ship both features together rather than building two separate systems\n• Genuinely confirmed that inpaint_step()\'s loop cost does not shrink with mask size means production systems cannot rely on small edits being proportionally cheap -- this is why interactive editing products invest in latency optimizations (caching VAE encodings, reducing diffusion steps) rather than assuming mask size alone solves the latency problem',
      bodyKn: '• ಮೇಲೆ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: outpainting ಮತ್ತು inpainting ಒಂದೇ code ಹಂಚಿಕೊಳ್ಳುವುದರಿಂದ, ಒಂದನ್ನೂ implement ಮಾಡುವ ಒಂದೂ ತಂಡ ಇನ್ನೊಂದನ್ನೂ ಉಚಿತವಾಗಿ ಪಡೆಯುತ್ತದೆ -- products ಎರಡೂ features ಒಟ್ಟಿಗೆ ಶಿಪ್ ಮಾಡಲು ಒಂದೂ ನಿಜ engineering ಕಾರಣ, ಎರಡೂ ಪ್ರತ್ಯೇಕ systems ನಿರ್ಮಿಸುವ ಬದಲು\n• inpaint_step() ನ loop ವೆಚ್ಚ mask ಗಾತ್ರದ ಜೊತೆ ಕುಗ್ಗುವುದಿಲ್ಲ ಎಂದು ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ ಎಂದರೆ production systems ಚಿಕ್ಕ edits ಪ್ರಮಾಣಾನುಗುಣವಾಗಿ ಅಗ್ಗ ಎಂದು ಅವಲಂಬಿಸಲು ಸಾಧ್ಯವಿಲ್ಲ -- ಇದೇ ಏಕೆ interactive editing products latency optimizations ನಲ್ಲಿ ಹೂಡಿಕೆ ಮಾಡುತ್ತವೆ (VAE encodings cache ಮಾಡುವುದೂ, diffusion steps ಕಡಿಮೆ ಮಾಡುವುದೂ) ಕೇವಲ mask ಗಾತ್ರ latency ಸಮಸ್ಯೆಯನ್ನೂ ಪರಿಹರಿಸುತ್ತದೆ ಎಂದು ಊಹಿಸುವ ಬದಲು' } },
    { type: 'concept', data: {
      headingEn: 'Real-World Example', headingKn: 'Real-World Example',
      bodyEn: 'A production "canvas expansion" feature that lets a user drag the edge of a photo outward to reveal more scene genuinely constructs exactly the setup verified in this lesson\'s outpainting.py: a larger canvas, the original photo placed inside it, and a border region marked mask=True. Behind the scenes, the same SAM-optional, dilate-then-diffuse pipeline used for object removal handles the request, and the same full-tensor compute cost applies regardless of how thin the new border strip is -- which is why "expand by 10 pixels" and "expand by 200 pixels" often take similar server time per diffusion step, even though intuition might suggest otherwise.',
      bodyKn: 'ಒಂದೂ user ಗೆ ಹೆಚ್ಚಿನ scene ಬಹಿರಂಗಪಡಿಸಲು ಒಂದೂ photo ನ ಅಂಚನ್ನೂ ಹೊರಗೆ ಎಳೆಯಲು ಬಿಡುವ ಒಂದೂ production "canvas expansion" feature ಈ lesson ನ outpainting.py ನಲ್ಲಿ ಪರಿಶೀಲಿಸಿದ ನಿಖರ setup ಅನ್ನೂ ನಿಜವಾಗಿ ನಿರ್ಮಿಸುತ್ತದೆ: ಒಂದೂ ದೊಡ್ಡ canvas, ಮೂಲ photo ಅದೂ ಒಳಗೆ ಇಟ್ಟಿದೆ, ಮತ್ತು ಒಂದೂ border region mask=True ಎಂದು ಗುರುತಿಸಲಾಗಿದೆ. ಪರದೆಯ ಹಿಂದೆ, object removal ಗಾಗಿ ಬಳಸಿದ ಅದೇ SAM-ಐಚ್ಛಿಕ, dilate-then-diffuse pipeline ವಿನಂತಿಯನ್ನೂ ನಿರ್ವಹಿಸುತ್ತದೆ, ಮತ್ತು ಹೊಸ border strip ಎಷ್ಟೂ ತೆಳುವಾಗಿದ್ದರೂ ಅದೇ full-tensor compute cost ಅನ್ವಯಿಸುತ್ತದೆ -- ಇದೇ ಏಕೆ "10 pixels ವಿಸ್ತರಿಸಿ" ಮತ್ತು "200 pixels ವಿಸ್ತರಿಸಿ" ಆಗಾಗ ಪ್ರತಿ diffusion step ಗೆ ಒಂದೇ ರೀತಿಯ server time ತೆಗೆದುಕೊಳ್ಳುತ್ತವೆ, intuition ಬೇರೆ ಸೂಚಿಸಿದರೂ.' } },

    { type: 'quiz', data: { questions: [
      { q: 'Genuinely confirmed: in the outpainting.py run, what happened to positions 0, 1, 7, 8 (the border, mask=True)?', qKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: outpainting.py run ನಲ್ಲಿ, positions 0, 1, 7, 8 (border, mask=True) ಗೆ ಏನೂ ಆಯಿತು?',
        opts: ['They were overwritten from canvas_clean', 'They were left completely untouched, exactly as before the function ran -- genuinely confirmed', 'They were set to zero', 'They caused an error'], correct: 1,
        optsKn: ['ಅವೂ canvas_clean ಇಂದ ಮತ್ತೆ ಬರೆಯಲ್ಪಟ್ಟವು', 'ಅವೂ ಸಂಪೂರ್ಣವಾಗಿ ಮುಟ್ಟದೆ ಬಿಡಲಾಗಿತ್ತು, function ಚಲಾಯಿಸುವ ಮೊದಲಿನಂತೆಯೇ -- ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ', 'ಅವೂ ಶೂನ್ಯಕ್ಕೆ ಹೊಂದಿಸಲಾಗಿತ್ತು', 'ಅವೂ ಒಂದೂ error ಉಂಟುಮಾಡಿದವು'] },
      { q: 'What proves that outpainting requires no new diffusion algorithm beyond inpainting?', qKn: 'Outpainting ಗೆ inpainting ಮೀರಿ ಯಾವುದೇ ಹೊಸ diffusion algorithm ಅಗತ್ಯವಿಲ್ಲ ಎಂದು ಏನೂ ಸಾಬೀತುಪಡಿಸುತ್ತದೆ?',
        opts: ['A separate outpainting-specific function was needed', 'Part 1\'s exact inpaint_step() function, completely unmodified, genuinely produced correct outpainting behavior with only the mask layout inverted', 'Outpainting does not use diffusion at all', 'Outpainting requires SAM but inpainting does not'], correct: 1,
        optsKn: ['ಒಂದೂ ಪ್ರತ್ಯೇಕ outpainting-ನಿರ್ದಿಷ್ಟ function ಅಗತ್ಯವಿತ್ತು', 'Part 1 ನ ನಿಖರ inpaint_step() function, ಸಂಪೂರ್ಣವಾಗಿ ಮಾರ್ಪಡಿಸದೆ, ಕೇವಲ mask layout ತಲೆಕೆಳಗಾಗಿಸಿ ಸರಿಯಾದ outpainting ವರ್ತನೆ ನಿಜವಾಗಿ ಉತ್ಪಾದಿಸಿತು', 'Outpainting diffusion ಬಳಸುವುದೇ ಇಲ್ಲ', 'Outpainting ಗೆ SAM ಅಗತ್ಯ ಆದರೆ inpainting ಗೆ ಇಲ್ಲ'] },
      { q: 'What role does SAM play in the production object-removal pipeline?', qKn: 'Production object-removal pipeline ನಲ್ಲಿ SAM ಯಾವ ಪಾತ್ರ ವಹಿಸುತ್ತದೆ?',
        opts: ['It generates the final pixels', 'It produces a pixel-level mask from user intent (click/box/prompt), upstream of and external to the diffusion inpainting mechanism', 'It replaces the VAE decoder', 'It computes the CFG guidance scale'], correct: 1,
        optsKn: ['ಅದೂ ಅಂತಿಮ pixels ಉತ್ಪಾದಿಸುತ್ತದೆ', 'ಅದೂ user intent (click/box/prompt) ಇಂದ ಒಂದೂ pixel-ಮಟ್ಟದ mask ಉತ್ಪಾದಿಸುತ್ತದೆ, diffusion inpainting ಯಂತ್ರಾಂಶಕ್ಕೆ ಮೊದಲೂ ಮತ್ತು ಬಾಹ್ಯ', 'ಅದೂ VAE decoder ಬದಲಾಯಿಸುತ್ತದೆ', 'ಅದೂ CFG guidance scale ಗಣಿಸುತ್ತದೆ'] },
      { q: 'Genuinely confirmed by inpaint_step()\'s loop: why doesn\'t a small mask make editing proportionally cheaper?', qKn: 'inpaint_step() ನ loop ನಿಂದ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: ಒಂದೂ ಚಿಕ್ಕ mask ಏಕೆ editing ಅನ್ನೂ ಪ್ರಮಾಣಾನುಗುಣವಾಗಿ ಅಗ್ಗ ಮಾಡುವುದಿಲ್ಲ?',
        opts: ['Small masks are always cheaper in practice', 'The loop (and a real U-Net) processes every position/pixel of the full tensor regardless of how many positions are marked mask=True', 'SAM is slower for small masks', 'Small masks require more diffusion steps'], correct: 1,
        optsKn: ['ಆಚರಣೆಯಲ್ಲಿ ಚಿಕ್ಕ masks ಯಾವಾಗಲೂ ಅಗ್ಗ', 'Loop (ಮತ್ತು ಒಂದೂ ನಿಜ U-Net) ಎಷ್ಟೂ positions mask=True ಎಂದು ಗುರುತಿಸಿದ್ದರೂ ಪೂರ್ಣ tensor ನ ಪ್ರತಿ position/pixel ಪ್ರಕ್ರಿಯೆಗೊಳಿಸುತ್ತದೆ', 'ಚಿಕ್ಕ masks ಗೆ SAM ನಿಧಾನ', 'ಚಿಕ್ಕ masks ಗೆ ಹೆಚ್ಚು diffusion steps ಅಗತ್ಯ'] },
      { q: 'Why does mask dilation help reduce visible seam artifacts?', qKn: 'Mask dilation ಗೋಚರ seam artifacts ಕಡಿಮೆ ಮಾಡಲು ಏಕೆ ಸಹಾಯ ಮಾಡುತ್ತದೆ?',
        opts: ['It makes the model run faster', 'It expands the generated region slightly into the preserved area, giving the model a buffer zone to blend lighting and texture continuously instead of across a hard one-position boundary', 'It removes the need for a mask entirely', 'It increases the CFG guidance scale'], correct: 1,
        optsKn: ['ಅದೂ model ಅನ್ನೂ ವೇಗವಾಗಿ ಚಲಾಯಿಸುತ್ತದೆ', 'ಅದೂ ಉತ್ಪಾದಿಸಿದ region ಅನ್ನೂ ಸಂರಕ್ಷಿಸಿದ ಪ್ರದೇಶಕ್ಕೆ ಸ್ವಲ್ಪ ವಿಸ್ತರಿಸುತ್ತದೆ, model ಗೆ lighting ಮತ್ತು texture ಅನ್ನೂ ಒಂದೂ ಗಟ್ಟಿ ಒಂದೂ-position boundary ಆದ್ಯಂತ ಬದಲು ನಿರಂತರವಾಗಿ ಬೆರೆಸಲು ಒಂದೂ buffer zone ನೀಡುತ್ತಾ', 'ಅದೂ ಒಂದೂ mask ಅಗತ್ಯವನ್ನೂ ಸಂಪೂರ್ಣವಾಗಿ ತೆಗೆಯುತ್ತದೆ', 'ಅದೂ CFG guidance scale ಹೆಚ್ಚಿಸುತ್ತದೆ'] },
    ] } },
  ],
};
