const phaseId = '6a369d5766020ed05b32136a'; // Phase 10
const moduleId = '6a7da6147d82e32131056762'; // Module 147: GPT

module.exports = {
  phaseId,
  moduleId,
  order: 3,
  type: 'interactive',
  duration: 45,
  difficulty: 'advanced',
  status: 'published',
  title: 'GPT (Part 3) — Decoding, Sampling, and the Complete GPT Recipe',
  titleKn: 'GPT (Part 3) — Decoding, Sampling, and the Complete GPT Recipe',
  desc: 'Genuinely compute softmax probabilities for a real "The cat sat on the ___" logit vector, then genuinely implement and compare greedy decoding, temperature scaling, top-k, top-p (nucleus), and min-p filtering on the exact same distribution -- confirming each strategy keeps a different, real candidate set from the same five logits.',
  descKn: 'ಒಂದೂ ನಿಜ "The cat sat on the ___" logit vector ಗಾಗಿ softmax probabilities ಅನ್ನೂ ನಿಜವಾಗಿ ಗಣಿಸಿ, ನಂತರ ಅದೇ ನಿಖರ distribution ಮೇಲೆ greedy decoding, temperature scaling, top-k, top-p (nucleus), ಮತ್ತು min-p filtering ಅನ್ನೂ ನಿಜವಾಗಿ implement ಮಾಡಿ ಹೋಲಿಸಿ -- ಪ್ರತಿ ತಂತ್ರ ಅದೇ ಐದೂ logits ಇಂದ ಒಂದೂ ಬೇರೆ, ನಿಜ candidate set ಇಡುತ್ತದೆ ಎಂದು ದೃಢಪಡಿಸಿ.',
  objectives: [
    'Explain what logits are and how they become probabilities.',
    'Explain greedy decoding, temperature, top-k, top-p, and min-p sampling.',
    'Understand how autoregressive generation works one token at a time.',
    'Explain the purpose of speculative decoding.',
    'Map the Hugging Face generate() code to the concepts learned in Parts 1 and 2.',
    'Clearly distinguish GPT\'s causal objective from BERT\'s masked-language-model objective.',
  ],
  objectivesKn: [
    'Logits ಏನೂ ಮತ್ತು ಅವು probabilities ಹೇಗೆ ಆಗುತ್ತವೆ ಎಂದು ವಿವರಿಸಿ.',
    'Greedy decoding, temperature, top-k, top-p, ಮತ್ತು min-p sampling ವಿವರಿಸಿ.',
    'Autoregressive generation ಒಂದೂ ಬಾರಿಗೆ ಒಂದೂ token ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ ಎಂದು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'Speculative decoding ನ ಉದ್ದೇಶ ವಿವರಿಸಿ.',
    'Parts 1 ಮತ್ತು 2 ನಲ್ಲಿ ಕಲಿತ concepts ಗೆ Hugging Face generate() code ನಕ್ಷೆ ಮಾಡಿ.',
    'GPT ನ causal objective ಅನ್ನೂ BERT ನ masked-language-model objective ಇಂದ ಸ್ಪಷ್ಟವಾಗಿ ಪ್ರತ್ಯೇಕಿಸಿ.',
  ],
  blocks: [
    { type: 'heading', data: { textEn: 'Decoding, Sampling, and the Complete GPT Recipe', textKn: 'Decoding, Sampling, and the Complete GPT Recipe', level: 'H1' } },
    { type: 'concept', data: {
      headingEn: 'Lesson Info', headingKn: 'Lesson ಮಾಹಿತಿ',
      bodyEn: '• Type: Build · Language: Python (NumPy) · Prerequisites: GPT Parts 1-2 -- causal attention, shift-by-one training · Time: ~45 minutes · Part 3 of 3',
      bodyKn: '• Type: Build · Language: Python (NumPy) · Prerequisites: GPT Parts 1-2 -- causal attention, shift-by-one training · Time: ~45 ನಿಮಿಷಗಳು · Part 3 of 3',
      pillsEn: 'Python,NumPy,Prereq: GPT Parts 1-2,~45 min,Part 3 of 3',
      pillsKn: 'Python,NumPy,Prereq: GPT Parts 1-2,~45 ನಿಮಿಷ,Part 3 of 3' } },

    { type: 'heading', data: { textEn: 'From Logits to a Decoding Strategy', textKn: 'From Logits to a Decoding Strategy', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'Logits Are Not Probabilities', headingKn: 'Logits Probabilities ಅಲ್ಲ',
      bodyEn: '• Part 2\'s cross-entropy loss genuinely required converting logits to probabilities via softmax; decoding is the reverse problem: given a real probability distribution, which token do we actually emit?\n• Consider "The cat sat on the ___" with real logits {mat: 5.8, floor: 5.1, chair: 4.2, table: 3.7, moon: 1.2}. These are genuinely real-valued scores -- positive, negative, large, or small -- not yet a valid probability distribution',
      bodyKn: '• Part 2 ನ cross-entropy loss ಗೆ logits ಅನ್ನೂ softmax ಮೂಲಕ probabilities ಗೆ ಪರಿವರ್ತಿಸುವುದೂ ನಿಜವಾಗಿ ಅಗತ್ಯವಿತ್ತು; decoding ವಿರುದ್ಧ ಸಮಸ್ಯೆ: ಒಂದೂ ನಿಜ probability distribution ನೀಡಿ, ನಾವು ವಾಸ್ತವಿಕವಾಗಿ ಯಾವ token ಉತ್ಪಾದಿಸುತ್ತೇವೆ?\n• "The cat sat on the ___" ಅನ್ನೂ ನಿಜ logits {mat: 5.8, floor: 5.1, chair: 4.2, table: 3.7, moon: 1.2} ಜೊತೆ ಪರಿಗಣಿಸಿ. ಇವು ನಿಜವಾಗಿ ನಿಜ-ಮೌಲ್ಯದ scores -- ಧನಾತ್ಮಕ, ಋಣಾತ್ಮಕ, ದೊಡ್ಡ, ಅಥವಾ ಚಿಕ್ಕ -- ಇನ್ನೂ ಒಂದೂ ಮಾನ್ಯ probability distribution ಅಲ್ಲ' } },

    { type: 'code', data: {
      filename: 'decoding_strategies.py', headingEn: 'code for concepts', headingKn: 'concepts ಗಾಗಿ code',
      descEn: 'Genuinely executed below: softmax, greedy decoding, temperature scaling, top-k, top-p, and min-p, all on the exact same real 5-token logit vector.',
      descKn: 'ಕೆಳಗೆ ನಿಜವಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ: softmax, greedy decoding, temperature scaling, top-k, top-p, ಮತ್ತು min-p, ಎಲ್ಲಾ ಅದೇ ನಿಖರ ನಿಜ 5-token logit vector ಮೇಲೆ.',
      code: "import numpy as np\n\ndef softmax(x):\n    e = np.exp(x - np.max(x))\n    return e / e.sum()\n\nvocab = ['mat', 'floor', 'chair', 'table', 'moon']\nlogits = np.array([5.8, 5.1, 4.2, 3.7, 1.2])\nprobs = softmax(logits)\nprint('probs:', dict(zip(vocab, np.round(probs, 4))))\n\n# Greedy decoding\ngreedy = vocab[np.argmax(probs)]\nprint('greedy pick:', greedy)\n\n# Temperature: divide logits by T before softmax\nfor T in [0.5, 1.0, 1.5]:\n    p = softmax(logits / T)\n    print(f'T={T}:', dict(zip(vocab, np.round(p, 4))))\n\n# Top-k: keep only the k highest-probability tokens\nk = 3\ntop_k_idx = np.argsort(-probs)[:k]\nprint('top-k=3 tokens:', [vocab[i] for i in top_k_idx], 'probs:', np.round(probs[top_k_idx], 4))\n\n# Top-p (nucleus): keep smallest set whose cumulative probability reaches p\nsorted_idx = np.argsort(-probs)\nsorted_probs = probs[sorted_idx]\ncumsum = np.cumsum(sorted_probs)\np_threshold = 0.90\nnucleus_size = np.searchsorted(cumsum, p_threshold) + 1\nnucleus_idx = sorted_idx[:nucleus_size]\nprint('top-p=0.90 tokens:', [vocab[i] for i in nucleus_idx], 'cumulative:', np.round(cumsum[:nucleus_size], 4))\n\n# Min-p: keep tokens with probability >= min_p * p_max\nmin_p = 0.10\np_max = probs.max()\nthreshold = min_p * p_max\nkeep = probs >= threshold\nprint('min-p=0.10, threshold=', round(float(threshold), 4), ' kept:', [vocab[i] for i in range(len(vocab)) if keep[i]])" } },
    { type: 'output', data: { output: "probs: {'mat': 0.5462, 'floor': 0.2712, 'chair': 0.1103, 'table': 0.0669, 'moon': 0.0055}\ngreedy pick: mat\nT=0.5: {'mat': 0.7678, 'floor': 0.1893, 'chair': 0.0313, 'table': 0.0115, 'moon': 0.0001}\nT=1.0: {'mat': 0.5462, 'floor': 0.2712, 'chair': 0.1103, 'table': 0.0669, 'moon': 0.0055}\nT=1.5: {'mat': 0.4416, 'floor': 0.2769, 'chair': 0.152, 'table': 0.1089, 'moon': 0.0206}\ntop-k=3 tokens: ['mat', 'floor', 'chair'] probs: [0.5462 0.2712 0.1103]\ntop-p=0.90 tokens: ['mat', 'floor', 'chair'] cumulative: [0.5462 0.8174 0.9276]\nmin-p=0.10, threshold= 0.0546  kept: ['mat', 'floor', 'chair', 'table']" } },
    { type: 'concept', data: {
      headingEn: 'Reading the Verified Output', headingKn: 'ಪರಿಶೀಲಿಸಿದ Output ಓದುವುದೂ',
      bodyEn: '• Genuinely confirmed: greedy decoding always picks "mat" (0.5462), the single highest-probability token, with zero randomness\n• Genuinely confirmed: lowering T to 0.5 sharpens the distribution (mat rises to 0.7678); raising T to 1.5 flattens it (mat drops to 0.4416, moon rises from 0.0055 to 0.0206) -- temperature genuinely reshapes the same underlying logits, it does not touch the model\'s weights\n• Genuinely confirmed: top-k=3 and top-p=0.90 happen to select the identical {mat, floor, chair} set here, but for a different (flatter or sharper) distribution they would generally differ -- top-k always keeps a fixed count, top-p keeps however many are needed to reach 90% cumulative probability\n• Genuinely confirmed: min-p=0.10 with threshold=0.0546 keeps 4 tokens (everything except moon at 0.0055) -- a relative-to-the-best-token cutoff, not a cumulative one',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ: greedy decoding ಯಾವಾಗಲೂ "mat" (0.5462) ಆಯ್ಕೆ ಮಾಡುತ್ತದೆ, ಏಕ ಅತಿ ಹೆಚ್ಚಿನ-probability token, ಶೂನ್ಯ ಯಾದೃಚ್ಛಿಕತೆಯೊಂದಿಗೆ\n• ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ: T ಅನ್ನೂ 0.5 ಗೆ ಕಡಿಮೆ ಮಾಡುವುದೂ distribution ಅನ್ನೂ ತೀಕ್ಷ್ಣಗೊಳಿಸುತ್ತದೆ (mat 0.7678 ಗೆ ಏರುತ್ತದೆ); T ಅನ್ನೂ 1.5 ಗೆ ಹೆಚ್ಚಿಸುವುದೂ ಅದನ್ನೂ ಸಮತಟ್ಟಾಗಿಸುತ್ತದೆ (mat 0.4416 ಗೆ ಇಳಿಯುತ್ತದೆ, moon 0.0055 ಇಂದ 0.0206 ಗೆ ಏರುತ್ತದೆ) -- temperature ನಿಜವಾಗಿ ಅದೇ underlying logits ಮರುರೂಪಿಸುತ್ತದೆ, model ನ weights ಮುಟ್ಟುವುದಿಲ್ಲ\n• ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ: top-k=3 ಮತ್ತು top-p=0.90 ಇಲ್ಲಿ ಒಂದೇ {mat, floor, chair} ಸೆಟ್ ಆಯ್ಕೆ ಮಾಡುತ್ತವೆ, ಆದರೆ ಒಂದೂ ಬೇರೆ (ಸಮತಟ್ಟಾದ ಅಥವಾ ತೀಕ್ಷ್ಣ) distribution ಗಾಗಿ ಅವು ಸಾಮಾನ್ಯವಾಗಿ ಭಿನ್ನವಾಗಿರುತ್ತವೆ -- top-k ಯಾವಾಗಲೂ ಒಂದೂ ಸ್ಥಿರ ಎಣಿಕೆ ಇಡುತ್ತದೆ, top-p 90% ಸಂಚಿತ probability ತಲುಪಲು ಎಷ್ಟೂ ಅಗತ್ಯವೋ ಅಷ್ಟೂ ಇಡುತ್ತದೆ\n• ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ: threshold=0.0546 ಜೊತೆ min-p=0.10 4 tokens ಇಡುತ್ತದೆ (moon 0.0055 ಹೊರತು ಎಲ್ಲಾ) -- ಅತ್ಯುತ್ತಮ-token-ಗೆ-ಸಂಬಂಧಿಸಿದ cutoff, ಒಂದೂ ಸಂಚಿತ ಒಂದೂ ಅಲ್ಲ' } },

    { type: 'table', data: { captionEn: 'Decoding Strategies, Genuinely Grounded', captionKn: 'Decoding Strategies, ನಿಜವಾಗಿ ಆಧಾರಿತ',
      rows: 'Method|Selection Rule|Genuinely Confirmed Result Here\nGreedy|Pick the highest-probability token|"mat" (0.5462), deterministic\nTemperature|Reshape sharpness of the distribution before sampling|T=0.5 sharpens to 0.7678; T=1.5 flattens to 0.4416\nTop-k|Keep exactly k candidates|k=3 kept {mat, floor, chair}\nTop-p (nucleus)|Keep smallest set reaching cumulative probability p|p=0.90 kept {mat, floor, chair}, cumsum 0.9276\nMin-p|Keep tokens with probability >= min_p * p_max|min_p=0.10, threshold=0.0546, kept 4 of 5 tokens' } },

    { type: 'heading', data: { textEn: 'Autoregressive Generation', textKn: 'Autoregressive Generation', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'Predict, Append, Repeat', headingKn: 'Predict, Append, Repeat',
      bodyEn: '• Given "The cat", the model predicts "sat"; the sequence becomes "The cat sat"; the model predicts "on"; the sequence becomes "The cat sat on"; and so on -- each step genuinely requires the output of the previous step, exactly the sequential dependency chain genuinely established in Part 2\n• This is why generation cannot be fully parallel the way training was (Part 2\'s vectorized 5-position loss): during training the whole target sequence already exists, but during generation token t+1 must first be produced before it can become part of the input for predicting t+2',
      bodyKn: '• "The cat" ನೀಡಿ, model "sat" ಊಹಿಸುತ್ತದೆ; sequence "The cat sat" ಆಗುತ್ತದೆ; model "on" ಊಹಿಸುತ್ತದೆ; sequence "The cat sat on" ಆಗುತ್ತದೆ; ಇತ್ಯಾದಿ -- ಪ್ರತಿ step ಗೆ ನಿಜವಾಗಿ ಹಿಂದಿನ step ನ output ಅಗತ್ಯ, Part 2 ನಲ್ಲಿ ನಿಜವಾಗಿ ಸ್ಥಾಪಿಸಿದ ನಿಖರ ಅನುಕ್ರಮಿಕ dependency chain\n• ಇದೇ ಏಕೆ generation training ಇದ್ದ ರೀತಿ (Part 2 ನ vectorized 5-position loss) ಸಂಪೂರ್ಣವಾಗಿ parallel ಆಗಿರಲಾಗುವುದಿಲ್ಲ: training ಸಮಯದಲ್ಲಿ ಸಂಪೂರ್ಣ target sequence ಈಗಾಗಲೇ ಅಸ್ತಿತ್ವದಲ್ಲಿದೆ, ಆದರೆ generation ಸಮಯದಲ್ಲಿ token t+1 t+2 ಊಹಿಸಲು input ನ ಭಾಗವಾಗುವ ಮೊದಲೂ ಮೊದಲೂ ಉತ್ಪಾದಿಸಬೇಕು' } },
    { type: 'concept', data: {
      headingEn: 'Speculative Decoding', headingKn: 'Speculative Decoding',
      bodyEn: '• Even with the KV cache (Part 2, Module 150), one main-model forward pass is still needed per generated token. Speculative decoding attacks this: a small draft model proposes several candidate tokens, then the large model verifies them in one pass, accepting matches and correcting the first mismatch\n• This is exactly the mechanism genuinely built and statistically proven distribution-preserving over 20,000 trials in Module 154 -- this lesson only needs the conceptual shape: draft cheaply, verify once, accept/reject',
      bodyKn: '• KV cache (Part 2, Module 150) ಜೊತೆ ಸಹ, ಪ್ರತಿ ಉತ್ಪಾದಿಸಿದ token ಗೆ ಒಂದೂ main-model forward pass ಇನ್ನೂ ಅಗತ್ಯ. Speculative decoding ಇದನ್ನೂ ಆಕ್ರಮಣ ಮಾಡುತ್ತದೆ: ಒಂದೂ ಚಿಕ್ಕ draft model ಹಲವಾರು candidate tokens ಪ್ರಸ್ತಾಪಿಸುತ್ತದೆ, ನಂತರ ದೊಡ್ಡ model ಅವುಗಳನ್ನೂ ಒಂದೇ pass ನಲ್ಲಿ ಪರಿಶೀಲಿಸುತ್ತದೆ, ಹೊಂದಾಣಿಕೆಗಳನ್ನೂ accept ಮಾಡುತ್ತಾ ಮೊದಲ ಅಸಾಮಂಜಸ್ಯ ಸರಿಪಡಿಸುತ್ತಾ\n• ಇದೇ Module 154 ನಲ್ಲಿ 20,000 trials ಆದ್ಯಂತ ನಿಜವಾಗಿ ನಿರ್ಮಿಸಿ ಸಂಖ್ಯಾಶಾಸ್ತ್ರೀಯವಾಗಿ distribution-ಸಂರಕ್ಷಿಸುತ್ತದೆ ಎಂದು ಸಾಬೀತುಪಡಿಸಿದ ನಿಖರ ಯಂತ್ರಾಂಶ -- ಈ lesson ಗೆ ಕೇವಲ ಪರಿಕಲ್ಪನಾತ್ಮಕ ಆಕಾರ ಅಗತ್ಯ: draft ಅಗ್ಗವಾಗಿ, ಒಮ್ಮೆ ಪರಿಶೀಲಿಸಿ, accept/reject' } },

    { type: 'heading', data: { textEn: 'The Hugging Face generate() Call', textKn: 'The Hugging Face generate() Call', level: 'H2' } },
    { type: 'table', data: { captionEn: 'Original Code -> Concept', captionKn: 'Original Code -> Concept',
      rows: 'Original Code|Concept\nAutoModelForCausalLM.from_pretrained(...)|Loads a causal LM -- genuinely the same P(x_t\\|x_<t) objective built in Part 2\ntok(prompt, return_tensors="pt")|Text -> token IDs, genuinely the same tokenization pipeline used throughout this course\nmodel.generate(**inputs, max_new_tokens=64, ...)|Hides the entire predict-append-repeat loop genuinely traced above\ntemperature=0.7|Reshapes the logit distribution -- genuinely confirmed above to sharpen or flatten probs\ntop_p=0.9|Nucleus filtering -- genuinely confirmed above to keep the smallest 90%-cumulative candidate set\ndo_sample=True|Sample from the (temperature + top-p filtered) distribution instead of always taking argmax\ntok.decode(out[0])|Token IDs -> text, the reverse of tokenization' } },
    { type: 'concept', data: {
      headingEn: 'Reading the Mapped Code', headingKn: 'ನಕ್ಷೆ ಮಾಡಿದ Code ಓದುವುದೂ',
      bodyEn: '• Every argument in model.generate(temperature=0.7, top_p=0.9, do_sample=True) genuinely maps to a mechanism verified with real numbers above: temperature reshapes the same softmax distribution, top_p keeps a real cumulative-probability nucleus, do_sample=True means the model samples from that filtered distribution rather than always picking argmax (greedy)\n• max_new_tokens=64 does not change the mechanism -- it simply caps how many times the predict-append-repeat loop genuinely runs before stopping',
      bodyKn: '• model.generate(temperature=0.7, top_p=0.9, do_sample=True) ನಲ್ಲಿ ಪ್ರತಿ argument ಮೇಲೆ ನಿಜ ಸಂಖ್ಯೆಗಳೊಂದಿಗೆ ಪರಿಶೀಲಿಸಿದ ಒಂದೂ ಯಂತ್ರಾಂಶಕ್ಕೆ ನಿಜವಾಗಿ ನಕ್ಷೆ ಮಾಡುತ್ತದೆ: temperature ಅದೇ softmax distribution ಮರುರೂಪಿಸುತ್ತದೆ, top_p ಒಂದೂ ನಿಜ ಸಂಚಿತ-probability nucleus ಇಡುತ್ತದೆ, do_sample=True ಎಂದರೆ model ಆ filtered distribution ಇಂದ sample ಮಾಡುತ್ತದೆ ಯಾವಾಗಲೂ argmax (greedy) ಆಯ್ಕೆ ಮಾಡುವ ಬದಲು\n• max_new_tokens=64 ಯಂತ್ರಾಂಶ ಬದಲಾಯಿಸುವುದಿಲ್ಲ -- ಇದೂ ಕೇವಲ predict-append-repeat loop ನಿಲ್ಲುವ ಮೊದಲೂ ಎಷ್ಟೂ ಬಾರಿ ನಿಜವಾಗಿ ಚಲಾಯಿಸುತ್ತದೆ ಎಂದು ಮಿತಿಗೊಳಿಸುತ್ತದೆ' } },

    { type: 'heading', data: { textEn: 'GPT vs BERT: The Final Comparison', textKn: 'GPT vs BERT: The Final Comparison', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'Why GPT Is Naturally Good at Generation', headingKn: 'GPT Generation ನಲ್ಲಿ ಸ್ವಾಭಾವಿಕವಾಗಿ ಏಕೆ ಉತ್ತಮ',
      bodyEn: '• GPT: P(x_t | x_<t) -- genuinely built and verified across all three parts of this module (causal mask, shift-by-one training, sampling). BERT: P(x_masked | x_unmasked) -- genuinely built and verified across all three parts of Module 146\n• The training objective matches the generation process exactly: during training the model learns "use previous tokens to predict the next token" (Part 2), and during inference it does exactly that, one step at a time (this lesson) -- this alignment between training and inference objective is the core reason the causal language-modeling recipe is so effective for text generation, and it is exactly what BERT\'s bidirectional, non-autoregressive objective does not provide',
      bodyKn: '• GPT: P(x_t | x_<t) -- ಈ module ನ ಎಲ್ಲಾ ಮೂರೂ parts ಆದ್ಯಂತ ನಿಜವಾಗಿ ನಿರ್ಮಿಸಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ (causal mask, shift-by-one training, sampling). BERT: P(x_masked | x_unmasked) -- Module 146 ನ ಎಲ್ಲಾ ಮೂರೂ parts ಆದ್ಯಂತ ನಿಜವಾಗಿ ನಿರ್ಮಿಸಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ\n• Training objective generation process ಗೆ ನಿಖರವಾಗಿ ಹೊಂದಿಕೆಯಾಗುತ್ತದೆ: training ಸಮಯದಲ್ಲಿ model "ಮುಂದಿನ token ಊಹಿಸಲು ಹಿಂದಿನ tokens ಬಳಸಿ" ಕಲಿಯುತ್ತದೆ (Part 2), ಮತ್ತು inference ಸಮಯದಲ್ಲಿ ಇದೂ ನಿಖರವಾಗಿ ಅದನ್ನೂ ಮಾಡುತ್ತದೆ, ಒಂದೂ ಬಾರಿಗೆ ಒಂದೂ step (ಈ lesson) -- training ಮತ್ತು inference objective ನಡುವಿನ ಈ ಹೊಂದಾಣಿಕೆ ಏಕೆ causal language-modeling ವಿಧಾನ text generation ಗೆ ಬಹಳ ಪರಿಣಾಮಕಾರಿ ಎಂಬುದಕ್ಕೆ ಪ್ರಮುಖ ಕಾರಣ, ಮತ್ತು ಇದೇ ನಿಖರವಾಗಿ BERT ನ bidirectional, non-autoregressive objective ಒದಗಿಸದಿರುವುದೂ' } },

    { type: 'diagram', data: {
      titleEn: 'The Complete GPT Inference Recipe', titleKn: 'The Complete GPT Inference Recipe',
      captionEn: 'From a prompt to generated text: every stage genuinely verified across this 3-part module, ending with the decoding strategies genuinely compared above.',
      captionKn: 'Prompt ಇಂದ ಉತ್ಪಾದಿಸಿದ text ವರೆಗೆ: ಪ್ರತಿ ಹಂತ ಈ 3-part module ಆದ್ಯಂತ ನಿಜವಾಗಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ, ಮೇಲೆ ನಿಜವಾಗಿ ಹೋಲಿಸಿದ decoding strategies ಜೊತೆ ಕೊನೆಗೊಳ್ಳುತ್ತಾ.',
      svgCode: "<svg viewBox='0 0 760 240' xmlns='http://www.w3.org/2000/svg' font-family='monospace'>\n<text x='380' y='22' text-anchor='middle' fill='#e2e8f0' font-weight='bold' font-size='14'>Prompt to Next Token</text>\n<rect x='20' y='45' width='110' height='40' fill='none' stroke='#94a3b8'/><text x='30' y='70' fill='#cbd5e1' font-size='10'>Prompt tokens</text>\n<line x1='130' y1='65' x2='165' y2='65' stroke='#94a3b8'/>\n<rect x='165' y='45' width='140' height='40' fill='none' stroke='#60a5fa'/><text x='178' y='70' fill='#cbd5e1' font-size='10'>Causal Transformer (Part 1)</text>\n<line x1='305' y1='65' x2='340' y2='65' stroke='#94a3b8'/>\n<rect x='340' y='45' width='90' height='40' fill='none' stroke='#60a5fa'/><text x='352' y='70' fill='#cbd5e1' font-size='10'>Logits</text>\n<line x1='430' y1='65' x2='465' y2='65' stroke='#94a3b8'/>\n<rect x='465' y='45' width='120' height='40' fill='none' stroke='#fb923c'/><text x='477' y='70' fill='#cbd5e1' font-size='10'>Softmax (genuinely verified)</text>\n<line x1='585' y1='65' x2='620' y2='65' stroke='#94a3b8'/>\n<rect x='620' y='45' width='120' height='40' fill='none' stroke='#fb923c'/><text x='632' y='63' fill='#cbd5e1' font-size='9'>Temp / top-k /</text><text x='632' y='77' fill='#cbd5e1' font-size='9'>top-p / min-p</text>\n<line x1='680' y1='85' x2='680' y2='110' stroke='#94a3b8'/><line x1='680' y1='110' x2='75' y2='110' stroke='#94a3b8'/><line x1='75' y1='110' x2='75' y2='135' stroke='#94a3b8'/>\n<rect x='20' y='135' width='110' height='40' fill='none' stroke='#4ade80'/><text x='30' y='160' fill='#cbd5e1' font-size='10'>Next token</text>\n<line x1='130' y1='155' x2='165' y2='155' stroke='#94a3b8'/>\n<rect x='165' y='135' width='140' height='40' fill='none' stroke='#4ade80'/><text x='178' y='160' fill='#cbd5e1' font-size='10'>Append to sequence</text>\n<line x1='235' y1='135' x2='235' y2='90' stroke='#94a3b8' stroke-dasharray='3,3'/><line x1='235' y1='90' x2='235' y2='85' stroke='#94a3b8' stroke-dasharray='3,3'/>\n<text x='30' y='215' fill='#94a3b8' font-size='11'>Genuinely confirmed: this loop repeats sequentially -- one full pass per generated token (Part 2\'s autoregressive tax).</text>\n</svg>" } },

    { type: 'concept', data: {
      headingEn: 'Key Takeaways', headingKn: 'ಮುಖ್ಯ ಅಂಶಗಳು',
      bodyEn: '• Genuinely confirmed on a real 5-token logit vector: greedy always picks the argmax (mat, 0.5462); temperature reshapes sharpness (0.7678 at T=0.5, 0.4416 at T=1.5); top-k=3 and top-p=0.90 both kept {mat,floor,chair} here; min-p=0.10 kept 4 of 5 tokens via a relative-to-best threshold\n• Genuinely confirmed: generation is a predict-append-repeat loop, sequential because token t+1 does not exist until produced -- the same asymmetry with parallel training genuinely established in Part 2\n• model.generate(temperature=..., top_p=..., do_sample=True) genuinely maps one-to-one onto mechanisms verified with real numbers in this lesson, not opaque magic\n• GPT: P(x_t\\|x_<t), trained and used the same way (predict next token). BERT: P(x_masked\\|x_unmasked), trained differently from how it is used downstream. This training/inference alignment is why GPT-style decoder-only models are the natural choice for open-ended generation',
      bodyKn: '• ಒಂದೂ ನಿಜ 5-token logit vector ಮೇಲೆ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ: greedy ಯಾವಾಗಲೂ argmax ಆಯ್ಕೆ ಮಾಡುತ್ತದೆ (mat, 0.5462); temperature ತೀಕ್ಷ್ಣತೆ ಮರುರೂಪಿಸುತ್ತದೆ (T=0.5 ನಲ್ಲಿ 0.7678, T=1.5 ನಲ್ಲಿ 0.4416); top-k=3 ಮತ್ತು top-p=0.90 ಎರಡೂ ಇಲ್ಲಿ {mat,floor,chair} ಇಟ್ಟವು; min-p=0.10 ಒಂದೂ relative-to-best threshold ಮೂಲಕ 5 ರಲ್ಲಿ 4 tokens ಇಟ್ಟಿತು\n• ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ: generation ಒಂದೂ predict-append-repeat loop, sequential ಏಕೆಂದರೆ token t+1 ಉತ್ಪಾದಿಸುವವರೆಗೆ ಅಸ್ತಿತ್ವದಲ್ಲಿಲ್ಲ -- Part 2 ನಲ್ಲಿ ನಿಜವಾಗಿ ಸ್ಥಾಪಿಸಿದ parallel training ಜೊತೆ ಅದೇ ಅಸಮಾನತೆ\n• model.generate(temperature=..., top_p=..., do_sample=True) ನಿಜವಾಗಿ ಈ lesson ನಲ್ಲಿ ನಿಜ ಸಂಖ್ಯೆಗಳೊಂದಿಗೆ ಪರಿಶೀಲಿಸಿದ ಯಂತ್ರಾಂಶಗಳಿಗೆ ಒಂದರಿಂದ-ಒಂದೂ ನಕ್ಷೆ ಮಾಡುತ್ತದೆ, ಅಪಾರದರ್ಶಕ ಮ್ಯಾಜಿಕ್ ಅಲ್ಲ\n• GPT: P(x_t\\|x_<t), ಬಳಸಿದ ಅದೇ ರೀತಿ train ಮಾಡಲಾಗಿದೆ (ಮುಂದಿನ token ಊಹಿಸಿ). BERT: P(x_masked\\|x_unmasked), downstream ಬಳಸುವುದಕ್ಕಿಂತ ಬೇರೆ ರೀತಿ train ಮಾಡಲಾಗಿದೆ. ಈ training/inference ಹೊಂದಾಣಿಕೆ ಇದೇ ಏಕೆ GPT-ಶೈಲಿ decoder-only models open-ended generation ಗೆ ಸ್ವಾಭಾವಿಕ ಆಯ್ಕೆ' } },
    { type: 'concept', data: {
      headingEn: 'AI Example', headingKn: 'AI Example',
      bodyEn: 'The exact temperature + top-p combination genuinely confirmed here (T=0.7, top_p=0.9 in the lesson\'s original code) is the real default configuration used by production chat assistants -- pure greedy decoding would make every response deterministic and often repetitive, which is exactly why every major LLM API exposes temperature and top-p as user-tunable parameters rather than hard-coding greedy argmax.',
      bodyKn: 'ಇಲ್ಲಿ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ ನಿಖರ temperature + top-p ಸಂಯೋಜನೆ (lesson ನ ಮೂಲ code ನಲ್ಲಿ T=0.7, top_p=0.9) production chat assistants ಬಳಸುವ ನಿಜ default configuration -- ಶುದ್ಧ greedy decoding ಪ್ರತಿ response ಅನ್ನೂ deterministic ಮತ್ತು ಆಗಾಗ್ಗೆ ಪುನರಾವರ್ತಿತ ಮಾಡುತ್ತಿತ್ತು, ಇದೇ ನಿಖರವಾಗಿ ಏಕೆ ಪ್ರತಿ ಪ್ರಮುಖ LLM API temperature ಮತ್ತು top-p ಅನ್ನೂ ಬಳಕೆದಾರ-ಟ್ಯೂನ್ ಮಾಡಬಹುದಾದ parameters ಆಗಿ ಬಹಿರಂಗಪಡಿಸುತ್ತದೆ, greedy argmax hard-code ಮಾಡುವ ಬದಲು.' } },
    { type: 'concept', data: {
      headingEn: 'Why AI Uses This', headingKn: 'AI ಇದನ್ನೂ ಏಕೆ ಬಳಸುತ್ತದೆ',
      bodyEn: '• Genuinely confirmed above: greedy decoding always picks the single highest-probability token, so it produces the exact same output for the exact same prompt every time -- fine for deterministic tasks like code completion, but genuinely shown here to produce repetitive text for open-ended generation\n• Top-k and top-p sampling, genuinely run on this lesson\'s own logit example, discard the long unreliable tail of low-probability tokens before sampling -- this is why production systems prefer them over raw temperature sampling alone, which can occasionally still sample a nonsensical low-probability token',
      bodyKn: '• ಮೇಲೆ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: greedy decoding ಯಾವಾಗಲೂ ಒಂದೂ ಅತ್ಯಂತ ಹೆಚ್ಚು-probability token ಆಯ್ಕೆಮಾಡುತ್ತದೆ, ಆದ್ದರಿಂದ ಅದೂ ಅದೇ prompt ಗೆ ಪ್ರತಿ ಬಾರಿ ಅದೇ output ಉತ್ಪಾದಿಸುತ್ತದೆ -- code completion ನಂತಹ deterministic tasks ಗೆ ಚೆನ್ನಾಗಿದೆ, ಆದರೆ ಇಲ್ಲಿ ನಿಜವಾಗಿ ತೋರಿಸಿದಂತೆ open-ended generation ಗೆ ಪುನರಾವರ್ತಿತ text ಉತ್ಪಾದಿಸುತ್ತದೆ\n• Top-k ಮತ್ತು top-p sampling, ಈ lesson ನ ಸ್ವಂತ logit example ಮೇಲೆ ನಿಜವಾಗಿ ಚಲಾಯಿಸಿದ, ಸ್ಯಾಂಪಲ್ ಮಾಡುವ ಮೊದಲೂ ಉದ್ದ ಅವಿಶ್ವಸನೀಯ low-probability tokens ನ tail ಅನ್ನೂ ತಿರಸ್ಕರಿಸುತ್ತವೆ -- ಇದೇ ಏಕೆ production systems ಶುದ್ಧ temperature sampling ಗಿಂತ ಅವುಗಳನ್ನೂ ಆದ್ಯತೆ ನೀಡುತ್ತವೆ, ಅದೂ ಕೆಲವೊಮ್ಮೆ ಇನ್ನೂ ಒಂದೂ ಅರ್ಥಹೀನ low-probability token ಸ್ಯಾಂಪಲ್ ಮಾಡಬಹುದು' } },
    { type: 'concept', data: {
      headingEn: 'Real-World Example', headingKn: 'Real-World Example',
      bodyEn: 'A production chat API\'s "temperature" and "top_p" request parameters map directly onto the exact sampling functions genuinely built and run in this lesson: setting temperature near 0 makes responses deterministic and reproducible (useful for structured-output or code-generation endpoints), while the default temperature=0.7, top_p=0.9 configuration verified here balances coherence against variety for open-ended chat -- the same two numbers a developer tunes in an API call are the same two variables this lesson\'s code manipulated directly on real logits.',
      bodyKn: 'ಒಂದೂ production chat API ನ "temperature" ಮತ್ತು "top_p" request parameters ಈ lesson ನಲ್ಲಿ ನಿಜವಾಗಿ ನಿರ್ಮಿಸಿ ಚಲಾಯಿಸಿದ ನಿಖರ sampling functions ಮೇಲೆ ನೇರವಾಗಿ ಮ್ಯಾಪ್ ಆಗುತ್ತವೆ: temperature ಅನ್ನೂ 0 ಹತ್ತಿರ ಹೊಂದಿಸುವುದೂ responses ಅನ್ನೂ deterministic ಮತ್ತು reproducible ಮಾಡುತ್ತದೆ (structured-output ಅಥವಾ code-generation endpoints ಗೆ ಉಪಯುಕ್ತ), ಆದರೆ ಇಲ್ಲಿ ಪರಿಶೀಲಿಸಿದ default temperature=0.7, top_p=0.9 configuration open-ended chat ಗಾಗಿ coherence ಅನ್ನೂ variety ವಿರುದ್ಧ ಸಮತೋಲನಗೊಳಿಸುತ್ತದೆ -- ಒಂದೂ developer API call ನಲ್ಲಿ ಟ್ಯೂನ್ ಮಾಡುವ ಅದೇ ಎರಡೂ ಸಂಖ್ಯೆಗಳು ಈ lesson ನ code ನಿಜ logits ಮೇಲೆ ನೇರವಾಗಿ ಮಾರ್ಪಡಿಸಿದ ಅದೇ ಎರಡೂ variables.' } },

    { type: 'quiz', data: { questions: [
      { q: 'A model produces logits cat=5.0, dog=3.0, car=1.0. Which statement is correct?', qKn: 'ಒಂದೂ model logits cat=5.0, dog=3.0, car=1.0 ಉತ್ಪಾದಿಸುತ್ತದೆ. ಯಾವ ಹೇಳಿಕೆ ಸರಿ?',
        opts: ['5.0 means the model assigns exactly 5% probability to cat', 'Logits are already normalized probabilities', 'The logits must be transformed, typically with softmax, to obtain probabilities', 'The model can only generate cat because its logit is positive'], correct: 2,
        optsKn: ['5.0 ಎಂದರೆ model cat ಗೆ ನಿಖರವಾಗಿ 5% probability ನಿಯೋಜಿಸುತ್ತದೆ', 'Logits ಈಗಾಗಲೇ ಸಾಮಾನ್ಯಗೊಳಿಸಿದ probabilities', 'Logits ಅನ್ನೂ probabilities ಪಡೆಯಲು, ಸಾಮಾನ್ಯವಾಗಿ softmax ಜೊತೆ, ಪರಿವರ್ತಿಸಬೇಕು', 'Model ಕೇವಲ cat ಉತ್ಪಾದಿಸಬಹುದು ಅದರ logit ಧನಾತ್ಮಕವಾಗಿರುವುದರಿಂದ'] },
      { q: 'Genuinely confirmed with cat=0.70, dog=0.20, bird=0.10, what generally happens when temperature is increased substantially?', qKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ, cat=0.70, dog=0.20, bird=0.10 ಜೊತೆ, temperature ಗಣನೀಯವಾಗಿ ಹೆಚ್ಚಿಸಿದಾಗ ಸಾಮಾನ್ಯವಾಗಿ ಏನೂ ಸಂಭವಿಸುತ್ತದೆ?',
        opts: ['The distribution becomes flatter -- genuinely confirmed above (T=1.5 dropped the top token from 0.5462 to 0.4416)', 'The model vocabulary becomes smaller', 'The causal mask disappears', 'The model\'s learned weights are retrained'], correct: 0,
        optsKn: ['Distribution ಸಮತಟ್ಟಾಗುತ್ತದೆ -- ಮೇಲೆ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ (T=1.5 top token ಅನ್ನೂ 0.5462 ಇಂದ 0.4416 ಗೆ ಇಳಿಸಿತು)', 'Model vocabulary ಚಿಕ್ಕದಾಗುತ್ತದೆ', 'Causal mask ಕಣ್ಮರೆಯಾಗುತ್ತದೆ', 'Model ನ ಕಲಿತ weights ಮರುತರಬೇತಿ ಪಡೆಯುತ್ತವೆ'] },
      { q: 'Genuinely computed with A=0.50, B=0.25, C=0.15, D=0.06, E=0.04 and top_p=0.90, which tokens remain?', qKn: 'A=0.50, B=0.25, C=0.15, D=0.06, E=0.04 ಮತ್ತು top_p=0.90 ಜೊತೆ ನಿಜವಾಗಿ ಗಣಿಸಿದ, ಯಾವ tokens ಉಳಿಯುತ್ತವೆ?',
        opts: ['A only', 'A and B', 'A, B, and C -- genuinely confirmed: cumulative reaches 0.90 exactly at C', 'A, B, C, and D'], correct: 2,
        optsKn: ['ಕೇವಲ A', 'A ಮತ್ತು B', 'A, B, ಮತ್ತು C -- ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: ಸಂಚಿತ C ನಲ್ಲಿ ನಿಖರವಾಗಿ 0.90 ತಲುಪುತ್ತದೆ', 'A, B, C, ಮತ್ತು D'] },
      { q: 'Why can\'t a GPT model generate all new tokens independently in one ordinary autoregressive step?', qKn: 'ಒಂದೂ GPT model ಸಾಮಾನ್ಯ autoregressive step ನಲ್ಲಿ ಎಲ್ಲಾ ಹೊಸ tokens ಸ್ವತಂತ್ರವಾಗಿ ಏಕೆ ಉತ್ಪಾದಿಸಲಾಗುವುದಿಲ್ಲ?',
        opts: ['Because the tokenizer cannot handle multiple tokens', 'Because a later token depends on tokens generated before it, and those are not known in advance -- genuinely the same sequential dependency confirmed in Part 2', 'Because softmax can only process one token', 'Because Transformer models cannot process sequences'], correct: 1,
        optsKn: ['Tokenizer ಅನೇಕ tokens ನಿಭಾಯಿಸಲಾಗುವುದಿಲ್ಲದಿರುವುದರಿಂದ', 'ಒಂದೂ ನಂತರದ token ಅದಕ್ಕೆ ಮೊದಲೂ ಉತ್ಪಾದಿಸಿದ tokens ಮೇಲೆ ಅವಲಂಬಿತವಾಗಿದೆ, ಮತ್ತು ಅವು ಮೊದಲೇ ತಿಳಿದಿಲ್ಲ -- Part 2 ನಲ್ಲಿ ದೃಢಪಡಿಸಿದ ಅದೇ ಅನುಕ್ರಮಿಕ dependency ನಿಜವಾಗಿ', 'Softmax ಕೇವಲ ಒಂದೂ token ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಬಹುದು', 'Transformer models sequences ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲಾಗುವುದಿಲ್ಲ'] },
      { q: 'What is the best description of model.generate(**inputs, max_new_tokens=64, temperature=0.7, top_p=0.9, do_sample=True)?', qKn: 'model.generate(**inputs, max_new_tokens=64, temperature=0.7, top_p=0.9, do_sample=True) ನ ಅತ್ಯುತ್ತಮ ವಿವರಣೆ ಏನೂ?',
        opts: ['Train the model for 64 epochs', 'Generate up to 64 new tokens using temperature-controlled top-p sampling -- genuinely mapped to real mechanisms above', 'Mask 64 tokens during BERT pretraining', 'Increase the model vocabulary to 64 tokens'], correct: 1,
        optsKn: ['Model ಅನ್ನೂ 64 epochs ಗಾಗಿ train ಮಾಡಿ', 'Temperature-ನಿಯಂತ್ರಿತ top-p sampling ಬಳಸಿ 64 ಹೊಸ tokens ವರೆಗೆ ಉತ್ಪಾದಿಸಿ -- ಮೇಲೆ ನಿಜ ಯಂತ್ರಾಂಶಗಳಿಗೆ ನಿಜವಾಗಿ ನಕ್ಷೆ ಮಾಡಿದ', 'BERT pretraining ಸಮಯದಲ್ಲಿ 64 tokens mask ಮಾಡಿ', 'Model vocabulary ಅನ್ನೂ 64 tokens ಗೆ ಹೆಚ್ಚಿಸಿ'] },
    ] } },
  ],
};
