const phaseId = '6a369d5c66020ed05b32143f'; // Phase 14: LLM Engineering
const moduleId = '6a369d5c66020ed05b321448'; // Module 210: Structured Outputs

module.exports = {
  phaseId,
  moduleId,
  order: 0,
  type: 'interactive',
  duration: 40,
  difficulty: 'advanced',
  status: 'published',
  title: 'Structured Outputs — Part 1: JSON Mode, Schemas, Validation, and Pydantic',
  titleKn: 'Structured Outputs — ಭಾಗ 1: JSON Mode, Schemas, Validation, ಮತ್ತು Pydantic',
  desc: 'Genuinely implement validate_value() and validate_object(), genuinely run a retry pipeline where a malformed model output is caught and corrected, and genuinely confirm Pydantic raises the exact same class of error while adding typed Python objects and auto-generated schemas.',
  descKn: 'validate_value() ಮತ್ತು validate_object() ಅನ್ನು ನಿಜವಾಗಿ ಜಾರಿಗೊಳಿಸಿ, ಒಂದು malformed model output ಹಿಡಿಯಲ್ಪಟ್ಟು ಸರಿಪಡಿಸಲ್ಪಡುವ ಒಂದು retry pipeline ಅನ್ನು ನಿಜವಾಗಿ ಓಡಿಸಿ, ಮತ್ತು Pydantic ಅದೇ ವರ್ಗದ error ಅನ್ನು ಎಸೆಯುತ್ತದೆ ಎಂದು ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿ, ಜೊತೆಗೆ typed Python objects ಮತ್ತು auto-generated schemas ಸೇರಿಸುತ್ತಾ.',
  objectives: [
    'Distinguish prompt-based JSON, JSON mode, structured output, and constrained decoding as four progressively stronger levels of control.',
    'Explain why syntactically valid JSON is not the same as schema-valid JSON, and why schema-valid JSON is not the same as factually correct JSON.',
    'Read a JSON Schema: type, properties, required, minimum, and enum constraints.',
    'Genuinely implement validate_value() and validate_object() and confirm they correctly flag a wrong type, a below-minimum number, and an invalid enum value.',
    'Genuinely run a two-attempt retry pipeline (extract_product) where attempt 1 fails schema validation and attempt 2 succeeds.',
    'Genuinely confirm Pydantic raises a structurally equivalent error for the same bad input, while additionally providing a typed Python object and auto-generated JSON Schema from one class definition.',
  ],
  objectivesKn: [
    'Prompt-based JSON, JSON mode, structured output, ಮತ್ತು constrained decoding ಅನ್ನು ನಾಲ್ಕು ಕ್ರಮೇಣ ಬಲಿಷ್ಠ ಹಂತಗಳಾಗಿ ಪ್ರತ್ಯೇಕಿಸಿ.',
    'Syntactically valid JSON ಎಂಬುದು schema-valid JSON ಗೆ ಸಮಾನ ಅಲ್ಲ, ಮತ್ತು schema-valid JSON ಎಂಬುದು facts-ಶುದ್ಧ JSON ಗೆ ಸಮಾನ ಅಲ್ಲ ಎಂದು ಏಕೆ ಎಂದು ವಿವರಿಸಿ.',
    'ಒಂದು JSON Schema ಓದಿ: type, properties, required, minimum, ಮತ್ತು enum constraints.',
    'validate_value() ಮತ್ತು validate_object() ಅನ್ನು ನಿಜವಾಗಿ ಜಾರಿಗೊಳಿಸಿ ಮತ್ತು ಅವು ಒಂದು ತಪ್ಪು type, ಒಂದು minimum ಗಿಂತ ಕೆಳಗಿನ ಸಂಖ್ಯೆ, ಮತ್ತು ಒಂದು ಅಮಾನ್ಯ enum value ಅನ್ನು ಸರಿಯಾಗಿ ಗುರುತಿಸುತ್ತವೆ ಎಂದು ದೃಢಪಡಿಸಿ.',
    'ಒಂದು ಎರಡು-ಪ್ರಯತ್ನದ retry pipeline (extract_product) ಅನ್ನು ನಿಜವಾಗಿ ಓಡಿಸಿ, ಅಲ್ಲಿ ಪ್ರಯತ್ನ 1 schema validation ವಿಫಲವಾಗುತ್ತದೆ ಮತ್ತು ಪ್ರಯತ್ನ 2 ಯಶಸ್ವಿಯಾಗುತ್ತದೆ.',
    'ಅದೇ ಕೆಟ್ಟ input ಗಾಗಿ Pydantic ಒಂದು ರಚನಾತ್ಮಕವಾಗಿ ಸಮಾನ error ಎಸೆಯುತ್ತದೆ ಎಂದು ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿ, ಜೊತೆಗೆ ಒಂದೇ class definition ಇಂದ ಒಂದು typed Python object ಮತ್ತು auto-generated JSON Schema ಒದಗಿಸುತ್ತಾ.',
  ],
  blocks: [
    { type: 'heading', data: { textEn: 'Structured Outputs — Part 1: JSON Mode, Schemas, Validation, and Pydantic', textKn: 'Structured Outputs — ಭಾಗ 1: JSON Mode, Schemas, Validation, ಮತ್ತು Pydantic', level: 'H1' } },
    { type: 'concept', data: {
      headingEn: 'Lesson Info', headingKn: 'ಪಾಠದ ಮಾಹಿತಿ',
      bodyEn: '• Type: Build · Language: Python · Prerequisite: Module 209 (Few-Shot, CoT, Tree-of-Thought) · Time: ~40 minutes · Part 1 of 3',
      bodyKn: '• ಪ್ರಕಾರ: Build · ಭಾಷೆ: Python · ಪೂರ್ವಾಪೇಕ್ಷಿತ: Module 209 · ಸಮಯ: ~40 ನಿಮಿಷಗಳು · ಭಾಗ 1 ರಲ್ಲಿ 3',
      pillsEn: 'JSON Schema,Pydantic,Structured Output,Validation,Constrained Decoding',
      pillsKn: 'JSON Schema,Pydantic,Validation' } },

    { type: 'heading', data: { textEn: 'The Problem: Semantically Correct Is Not the Same as Machine-Readable', textKn: 'ಸಮಸ್ಯೆ: Semantically Correct ಎಂಬುದು Machine-Readable ಗೆ ಸಮಾನ ಅಲ್ಲ', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'A Model Can Understand the Text Perfectly and Still Produce Unusable Output', headingKn: 'ಒಂದು Model Text ಅನ್ನು ಪೂರ್ಣವಾಗಿ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಬಹುದು ಮತ್ತು ಇನ್ನೂ ಬಳಸಲಾಗದ Output ಉತ್ಪಾದಿಸಬಹುದು',
      bodyEn: 'Given "The Sony WH-1000XM5 costs $348 and is currently in stock", the model might correctly respond "The Sony WH-1000XM5 headphones cost $348 and are currently available." -- a semantically correct sentence. But an application wants {"product": "Sony WH-1000XM5", "price": 348.0, "in_stock": true}. The real question is not "can the model understand the text?" but "can it produce data satisfying an exact machine-readable contract?" The source demonstrates this exact gap: a correct human-readable answer can still be entirely unusable to code expecting particular fields and types.',
      bodyKn: '"The Sony WH-1000XM5 costs $348 and is currently in stock" ಕೊಟ್ಟರೆ, model ಸರಿಯಾಗಿ "The Sony WH-1000XM5 headphones cost $348 and are currently available." ಎಂದು ಉತ್ತರಿಸಬಹುದು -- ಒಂದು semantically correct ವಾಕ್ಯ. ಆದರೆ ಒಂದು application {"product": "Sony WH-1000XM5", "price": 348.0, "in_stock": true} ಬಯಸುತ್ತದೆ. ನಿಜ ಪ್ರಶ್ನೆ "model text ಅರ್ಥಮಾಡಿಕೊಳ್ಳಬಹುದೇ?" ಅಲ್ಲ, ಆದರೆ "ಇದು ಒಂದು ನಿಖರ machine-readable contract ತೃಪ್ತಿಪಡಿಸುವ data ಉತ್ಪಾದಿಸಬಹುದೇ?" Source ಈ ನಿಖರ ಅಂತರ ತೋರಿಸುತ್ತದೆ: ಒಂದು ಸರಿಯಾದ ಮಾನವ-ಓದಬಹುದಾದ ಉತ್ತರ ಇನ್ನೂ ನಿರ್ದಿಷ್ಟ fields ಮತ್ತು types ನಿರೀಕ್ಷಿಸುವ code ಗೆ ಸಂಪೂರ್ಣವಾಗಿ ಬಳಸಲಾಗದೆ ಇರಬಹುದು.' } },

    { type: 'heading', data: { textEn: 'The Structured-Output Ladder: Four Progressively Stronger Levels', textKn: 'Structured-Output Ladder: ನಾಲ್ಕು ಕ್ರಮೇಣ ಬಲಿಷ್ಠ ಹಂತಗಳು', level: 'H2' } },
    { type: 'diagram', data: {
      titleEn: 'From free-form generation to constrained decoding', titleKn: 'Free-form generation ಇಂದ constrained decoding ವರೆಗೆ',
      mermaidCode: "flowchart TD\n  A[Free-form generation] --> B[Level 1: Prompt-based JSON]\n  B --> C[Level 2: JSON Mode -- syntax guaranteed]\n  C --> D[Level 3: Structured Output -- schema enforced]\n  D --> E[Level 4: Constrained Decoding -- enforced during generation]" } },
    { type: 'concept', data: {
      headingEn: 'Level 1 (Prompt-Based) Only Influences the Model; It Does Not Constrain It', headingKn: 'Level 1 (Prompt-Based) Model ಅನ್ನು ಪ್ರಭಾವಿಸುತ್ತದೆ ಮಾತ್ರ; ಇದು ಅದನ್ನು ನಿರ್ಬಂಧಿಸುವುದಿಲ್ಲ',
      bodyEn: 'Simply writing "Return your answer as JSON" might produce clean {"product": "...", "price": 348}, or it might produce "Here is the requested information:\\n```json\\n{...}\\n```" -- text surrounding the JSON that breaks json.loads(response) because the response contains characters outside the JSON object. Level 2, JSON Mode (response_format={"type": "json_object"}), is stronger: the provider GUARANTEES syntactically parsable JSON. But the resulting JSON might use "item" instead of "product", "cost" instead of "price", represent price as a string, or omit in_stock entirely -- syntactic validity says nothing about matching the application\'s expected shape.',
      bodyKn: 'ಕೇವಲ "Return your answer as JSON" ಬರೆಯುವುದು ಶುದ್ಧ {"product": "...", "price": 348} ಉತ್ಪಾದಿಸಬಹುದು, ಅಥವಾ ಅದು "Here is the requested information:\\n```json\\n{...}\\n```" ಉತ್ಪಾದಿಸಬಹುದು -- JSON ಸುತ್ತಲಿನ text json.loads(response) ಅನ್ನು ಮುರಿಯುತ್ತದೆ ಏಕೆಂದರೆ response JSON object ಹೊರಗಿನ characters ಒಳಗೊಂಡಿದೆ. Level 2, JSON Mode (response_format={"type": "json_object"}), ಬಲಿಷ್ಠ: provider syntactically parse ಮಾಡಬಹುದಾದ JSON ಗ್ಯಾರಂಟಿ ಮಾಡುತ್ತದೆ. ಆದರೆ ಫಲಿತಾಂಶ JSON "product" ಬದಲಿಗೆ "item", "price" ಬದಲಿಗೆ "cost" ಬಳಸಬಹುದು, price ಅನ್ನು ಒಂದು string ಆಗಿ ಪ್ರತಿನಿಧಿಸಬಹುದು, ಅಥವಾ in_stock ಅನ್ನು ಸಂಪೂರ್ಣವಾಗಿ ಬಿಡಬಹುದು -- syntactic validity application ya ನಿರೀಕ್ಷಿತ ಆಕಾರಕ್ಕೆ ಹೊಂದಿಕೆಯಾಗುತ್ತದೆ ಎಂದು ಏನೂ ಹೇಳುವುದಿಲ್ಲ.' } },
    { type: 'concept', data: {
      headingEn: 'Level 3 (Structured Output) Adds a Schema Contract; Level 4 (Constrained Decoding) Enforces It During Generation', headingKn: 'Level 3 (Structured Output) ಒಂದು Schema Contract ಸೇರಿಸುತ್ತದೆ; Level 4 (Constrained Decoding) ಇದನ್ನು Generation ಸಮಯದಲ್ಲಿ ಜಾರಿಗೊಳಿಸುತ್ತದೆ',
      bodyEn: 'Structured output adds an explicit contract -- {"type":"object","properties":{"product":{"type":"string"},"price":{"type":"number"},"in_stock":{"type":"boolean"}},"required":[...]} -- so {"product":"Sony WH-1000XM5","price":348,"in_stock":true} passes but {"product":"Sony WH-1000XM5","price":"expensive"} fails because a string is not a number. Level 4, constrained decoding (covered in depth in Part 2), goes further still: it prevents invalid tokens from ever being generated in the first place, rather than validating after the fact.',
      bodyKn: 'Structured output ಒಂದು ಸ್ಪಷ್ಟ contract ಸೇರಿಸುತ್ತದೆ -- {"type":"object","properties":{"product":{"type":"string"},"price":{"type":"number"},"in_stock":{"type":"boolean"}},"required":[...]} -- ಆದ್ದರಿಂದ {"product":"Sony WH-1000XM5","price":348,"in_stock":true} ಪಾಸ್ ಆಗುತ್ತದೆ ಆದರೆ {"product":"Sony WH-1000XM5","price":"expensive"} ವಿಫಲವಾಗುತ್ತದೆ ಏಕೆಂದರೆ ಒಂದು string ಒಂದು number ಅಲ್ಲ. Level 4, constrained decoding (ಭಾಗ 2 ರಲ್ಲಿ ಆಳವಾಗಿ ಒಳಗೊಳ್ಳಲಾಗಿದೆ), ಇನ್ನೂ ಮುಂದೆ ಹೋಗುತ್ತದೆ: ಇದು ಅಮಾನ್ಯ tokens ಎಂದಿಗೂ ಮೊದಲೂ ಉತ್ಪಾದಿಸಲ್ಪಡುವುದನ್ನು ತಡೆಯುತ್ತದೆ, ಆದ ನಂತರ validate ಮಾಡುವ ಬದಲಿಗೆ.' } },

    { type: 'heading', data: { textEn: 'Reading a JSON Schema', textKn: 'ಒಂದು JSON Schema ಓದುವುದು', level: 'H2' } },
    { type: 'code', data: {
      filename: 'product_schema.py', headingEn: 'The lesson\'s target schema for this whole three-part lesson', headingKn: 'Ee ಮೂರು-ಭಾಗದ lesson ಗೆ ಗುರಿ schema',
      descEn: 'The root must be an object with a string product, a non-negative number price, a boolean in_stock, and an optional enum-constrained condition; product/price/in_stock are required.',
      descKn: 'Root ಒಂದು object ಆಗಿರಬೇಕು, ಒಂದು string product, ಒಂದು ಋಣಾತ್ಮಕವಲ್ಲದ number price, ಒಂದು boolean in_stock, ಮತ್ತು ಒಂದು ಐಚ್ಛಿಕ enum-ನಿರ್ಬಂಧಿತ condition ಜೊತೆ; product/price/in_stock ಅಗತ್ಯ.',
      code: "PRODUCT_SCHEMA = {\n    'type': 'object',\n    'properties': {\n        'product': {'type': 'string'},\n        'price': {'type': 'number', 'minimum': 0},\n        'in_stock': {'type': 'boolean'},\n        'condition': {\n            'type': 'string',\n            'enum': ['new', 'used', 'refurbished']\n        }\n    },\n    'required': ['product', 'price', 'in_stock']\n}\nprint('required fields:', PRODUCT_SCHEMA['required'])\nprint('price constraints:', PRODUCT_SCHEMA['properties']['price'])\nprint('condition enum:', PRODUCT_SCHEMA['properties']['condition']['enum'])" } },
    { type: 'output', data: { output: "required fields: ['product', 'price', 'in_stock']\nprice constraints: {'type': 'number', 'minimum': 0}\ncondition enum: ['new', 'used', 'refurbished']" } },
    { type: 'concept', data: {
      headingEn: 'Every JSON Value Type Maps to a Corresponding Python Type', headingKn: 'ಪ್ರತಿ JSON Value Type ಒಂದು ಅನುಗುಣ Python Type ಗೆ Map ಆಗುತ್ತದೆ',
      bodyEn: 'type: "object" means the root must look like {} not [] or a bare string. properties describes which fields are allowed and their individual constraints. required lists fields that MUST be present -- condition is deliberately absent from required, so it is optional; if present, it must be one of exactly three strings. minimum on price means the value must be numeric AND non-negative -- two separate checks bundled under one schema key.',
      bodyKn: 'type: "object" ಎಂದರೆ root {} ಆಗಿ ಕಾಣಬೇಕು, [] ಅಥವಾ ಒಂದು ಬರಿಯ string ಅಲ್ಲ. properties ಯಾವ fields ಅನುಮತಿಸಲ್ಪಟ್ಟಿವೆ ಮತ್ತು ಅವುಗಳ ಪ್ರತ್ಯೇಕ constraints ವಿವರಿಸುತ್ತದೆ. required MUST ಇರುವ fields ಪಟ್ಟಿ ಮಾಡುತ್ತದೆ -- condition ಉದ್ದೇಶಪೂರ್ವಕವಾಗಿ required ಇಂದ ಇಲ್ಲ, ಆದ್ದರಿಂದ ಇದು ಐಚ್ಛಿಕ; ಇದ್ದರೆ, ಇದು ನಿಖರವಾಗಿ ಮೂರು strings ಗಳಲ್ಲಿ ಒಂದಾಗಿರಬೇಕು. price ಮೇಲಿನ minimum ಎಂದರೆ value numeric ಮತ್ತು ಋಣಾತ್ಮಕವಲ್ಲದ್ದೂ ಆಗಿರಬೇಕು -- ಒಂದೇ schema key ಅಡಿಯಲ್ಲಿ ಕಟ್ಟಲಾದ ಎರಡು ಪ್ರತ್ಯೇಕ ಪರಿಶೀಲನೆಗಳು.' } },

    { type: 'heading', data: { textEn: 'Genuinely Implementing validate_value() and validate_object()', textKn: 'validate_value() ಮತ್ತು validate_object() ಅನ್ನು ನಿಜವಾಗಿ ಜಾರಿಗೊಳಿಸುವುದು', level: 'H2' } },
    { type: 'code', data: {
      filename: 'validator.py', headingEn: 'A small type-checking, minimum-checking, enum-checking validator', headingKn: 'ಒಂದು ಚಿಕ್ಕ Type-Checking, Minimum-Checking, Enum-Checking Validator',
      descEn: 'validate_value() checks one field against its schema; validate_object() checks required fields and delegates each present field to validate_value().',
      descKn: 'validate_value() ಒಂದು field ಅನ್ನು ಇದರ schema ಎದುರೂ ಪರಿಶೀಲಿಸುತ್ತದೆ; validate_object() required fields ಪರಿಶೀಲಿಸುತ್ತದೆ ಮತ್ತು ಪ್ರತಿ ಇರುವ field ಅನ್ನು validate_value() ಗೆ delegate ಮಾಡುತ್ತದೆ.',
      code: "def validate_value(value, schema, path='root'):\n    errors = []\n    expected_type = schema.get('type')\n    python_types = {\n        'string': str, 'number': (int, float), 'boolean': bool,\n        'integer': int, 'object': dict, 'array': list,\n    }\n    expected_python_type = python_types.get(expected_type)\n    if expected_python_type is not None:\n        if not isinstance(value, expected_python_type):\n            return [f'{path}: expected {expected_type}, received {type(value).__name__}']\n\n    if expected_type == 'number':\n        minimum = schema.get('minimum')\n        if minimum is not None and value < minimum:\n            errors.append(f'{path}: value {value} must be >= {minimum}')\n\n    if expected_type == 'string':\n        enum = schema.get('enum')\n        if enum is not None and value not in enum:\n            errors.append(f'{path}: {value!r} must be one of {enum}')\n\n    return errors\n\ndef validate_object(data, schema):\n    errors = []\n    if not isinstance(data, dict):\n        return ['root: expected JSON object']\n    properties = schema.get('properties', {})\n    required = schema.get('required', [])\n    for field in required:\n        if field not in data:\n            errors.append(f'root.{field}: required field missing')\n    for field, value in data.items():\n        field_schema = properties.get(field)\n        if field_schema is None:\n            continue\n        errors.extend(validate_value(value, field_schema, path=f'root.{field}'))\n    return errors" } },
    { type: 'code', data: {
      filename: 'test_validator.py', headingEn: 'Genuinely testing three failure cases and one passing case', headingKn: 'ಮೂರು ವೈಫಲ್ಯ Cases ಮತ್ತು ಒಂದು Pass Case ಅನ್ನು ನಿಜವಾಗಿ ಪರೀಕ್ಷಿಸುವುದು',
      descEn: 'A wrong-type price ("348 dollars" instead of a number), an invalid enum condition ("brand-new" instead of new/used/refurbished), a missing required field, and a fully valid object.',
      descKn: 'ಒಂದು ತಪ್ಪು-type price ("348 dollars" ಒಂದು number ಬದಲಿಗೆ), ಒಂದು ಅಮಾನ್ಯ enum condition ("brand-new" new/used/refurbished ಬದಲಿಗೆ), ಒಂದು ಕಾಣೆಯಾದ required field, ಮತ್ತು ಒಂದು ಪೂರ್ಣವಾಗಿ valid object.',
      code: "attempt0 = {'product': 'Sony WH-1000XM5', 'price': '348 dollars', 'in_stock': True, 'condition': 'brand-new'}\nprint('attempt0 (bad price + bad enum):', validate_object(attempt0, PRODUCT_SCHEMA))\n\nattempt1 = {'product': 'Sony WH-1000XM5', 'price': 348.0, 'in_stock': True, 'condition': 'new'}\nprint('attempt1 (fully valid):', validate_object(attempt1, PRODUCT_SCHEMA))\n\nmissing = {'product': 'Sony', 'in_stock': True}\nprint('missing price field:', validate_object(missing, PRODUCT_SCHEMA))" } },
    { type: 'output', data: { output: "attempt0 (bad price + bad enum): ['root.price: expected number, received str', \"root.condition: 'brand-new' must be one of ['new', 'used', 'refurbished']\"]\nattempt1 (fully valid): []\nmissing price field: ['root.price: required field missing']" } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: The Validator Catches a Wrong Type, an Invalid Enum, and a Missing Field, All in One Pass', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: Validator ಒಂದು ತಪ್ಪು Type, ಒಂದು ಅಮಾನ್ಯ Enum, ಮತ್ತು ಒಂದು ಕಾಣೆಯಾದ Field ಅನ್ನು, ಎಲ್ಲಾ ಒಂದು Pass ನಲ್ಲಿ, ಹಿಡಿಯುತ್ತದೆ',
      bodyEn: 'Genuinely confirmed attempt0 produces TWO errors in one call -- price is a str not a number/int/float, AND "brand-new" is not in the allowed enum -- both surfaced together, not stopping at the first. Genuinely confirmed attempt1, changing only price to 348.0 (a real float) and condition to "new" (an allowed enum value), produces an empty error list -- validation passes exactly when every field satisfies its schema, no more, no less. Genuinely confirmed the missing-price case reports "required field missing" rather than crashing on a KeyError when validate_value() would otherwise be called on an absent key -- validate_object()\'s required-field loop runs BEFORE the per-field validate_value() loop specifically to catch this.',
      bodyKn: 'Nijavagi ದೃಢಪಡಿಸಲಾಗಿದೆ attempt0 ಒಂದು call ನಲ್ಲಿ ಎರಡು errors ಉತ್ಪಾದಿಸುತ್ತದೆ -- price ಒಂದು str, number/int/float ಅಲ್ಲ, ಮತ್ತು "brand-new" ಅನುಮತಿಸಿದ enum ನಲ್ಲಿ ಇಲ್ಲ -- ಎರಡೂ ಒಟ್ಟಿಗೆ ಹೊರಬರುತ್ತವೆ, ಮೊದಲನೆಯದರಲ್ಲಿ ನಿಲ್ಲದೆ. attempt1, ಕೇವಲ price ಅನ್ನು 348.0 (ಒಂದು ನಿಜ float) ಗೆ ಮತ್ತು condition ಅನ್ನು "new" (ಒಂದು ಅನುಮತಿಸಿದ enum value) ಗೆ ಬದಲಾಯಿಸಿ, ಒಂದು ಖಾಲಿ error list ಉತ್ಪಾದಿಸುತ್ತದೆ ಎಂದು ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ -- ಪ್ರತಿ field ಇದರ schema ತೃಪ್ತಿಪಡಿಸಿದಾಗ ನಿಖರವಾಗಿ validation ಪಾಸ್ ಆಗುತ್ತದೆ, ಹೆಚ್ಚೂ ಇಲ್ಲ, ಕಡಿಮೆಯೂ ಇಲ್ಲ. Missing-price case validate_value() ಇಲ್ಲದ key ಮೇಲೆ ಕರೆಯಲ್ಪಟ್ಟಾಗ KeyError ಮೇಲೆ crash ಆಗುವ ಬದಲಿಗೆ "required field missing" ವರದಿ ಮಾಡುತ್ತದೆ ಎಂದು ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ -- validate_object() ya required-field loop ಇದನ್ನೇ ಹಿಡಿಯಲು ನಿರ್ದಿಷ್ಟವಾಗಿ ಪ್ರತಿ-field validate_value() loop ಮೊದಲೂ ಓಡುತ್ತದೆ.' } },

    { type: 'heading', data: { textEn: 'The Enum Confusion Failure Mode', textKn: 'Enum Confusion ವೈಫಲ್ಯ ಮೋಡ್', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'Schema Validation Cares About Formal Correctness, Not Semantic Similarity', headingKn: 'Schema Validation Formal Correctness ಬಗ್ಗೆ ಕಾಳಜಿ ವಹಿಸುತ್ತದೆ, Semantic Similarity ಅಲ್ಲ',
      bodyEn: 'Genuinely confirmed above: "brand-new" fails the enum check even though it is semantically almost identical to the allowed "new". This is not a bug in the validator -- it is exactly the point. A schema enforces a closed, finite set of acceptable string literals; a model that is perfectly reasonable in natural language ("brand-new" reads fine to a human) can still violate a machine contract that only accepts an exact match. The source specifically calls this out as one of the core structured-output failure modes worth designing against, alongside hallucinated values (covered later in this module).',
      bodyKn: 'Mele ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ: "brand-new" enum check ವಿಫಲವಾಗುತ್ತದೆ ಇದು semantically ಅನುಮತಿಸಿದ "new" ಗೆ ಬಹುತೇಕ ಒಂದೇ ಆಗಿದ್ದರೂ. ಇದು validator ನಲ್ಲಿ ಒಂದು bug ಅಲ್ಲ -- ಇದೇ ನಿಖರ ಅಂಶ. ಒಂದು schema ಒಂದು ಮುಚ್ಚಿದ, ಸೀಮಿತ ಸ್ವೀಕಾರಾರ್ಹ string literals ಸೆಟ್ ಜಾರಿಗೊಳಿಸುತ್ತದೆ; ಸ್ವಾಭಾವಿಕ ಭಾಷೆಯಲ್ಲಿ ಪೂರ್ಣವಾಗಿ ಸಮಂಜಸ ಆಗಿರುವ ಒಂದು model ("brand-new" ಒಂದು ಮಾನವನಿಗೆ ಚೆನ್ನಾಗಿ ಓದುತ್ತದೆ) ಇನ್ನೂ ಕೇವಲ ನಿಖರ ಹೊಂದಾಣಿಕೆ ಸ್ವೀಕರಿಸುವ ಒಂದು machine contract ಉಲ್ಲಂಘಿಸಬಹುದು. Source ಇದನ್ನು ವಿಶೇಷವಾಗಿ hallucinated values (ಈ module ನಲ್ಲಿ ನಂತರ ಒಳಗೊಳ್ಳಲಾಗಿದೆ) ಜೊತೆ, ವಿನ್ಯಾಸ ಮಾಡುವಾಗ ಎಚ್ಚರವಹಿಸಬೇಕಾದ ಮುಖ್ಯ structured-output ವೈಫಲ್ಯ modes ಗಳಲ್ಲಿ ಒಂದಾಗಿ ಕರೆಯುತ್ತದೆ.' } },

    { type: 'heading', data: { textEn: 'Genuinely Running the Full Retry Pipeline End to End', textKn: 'ಪೂರ್ಣ Retry Pipeline ಅನ್ನು End To End ನಿಜವಾಗಿ ಓಡಿಸುವುದು', level: 'H2' } },
    { type: 'code', data: {
      filename: 'extract_product.py', headingEn: 'A simulated model that produces a bad response on attempt 0, then a good one on attempt 1', headingKn: 'ಒಂದು Simulated Model ಇದು Attempt 0 ನಲ್ಲಿ ಒಂದು ಕೆಟ್ಟ Response ಉತ್ಪಾದಿಸುತ್ತದೆ, ನಂತರ Attempt 1 ನಲ್ಲಿ ಒಂದು ಉತ್ತಮ Response',
      descEn: 'Loop: generate, parse JSON, validate against schema, return on success, retry on failure -- max_attempts=3.',
      descKn: 'Loop: generate ಮಾಡಿ, JSON parse ಮಾಡಿ, schema ಎದುರೂ validate ಮಾಡಿ, ಯಶಸ್ಸಿನಲ್ಲಿ ಹಿಂತಿರುಗಿಸಿ, ವೈಫಲ್ಯದಲ್ಲಿ retry ಮಾಡಿ -- max_attempts=3.',
      code: "def fake_model(text, attempt):\n    if attempt == 0:\n        return json.dumps({\n            'product': 'Sony WH-1000XM5', 'price': '348 dollars',\n            'in_stock': True, 'condition': 'brand-new',\n        })\n    return json.dumps({\n        'product': 'Sony WH-1000XM5', 'price': 348.0,\n        'in_stock': True, 'condition': 'new',\n    })\n\ndef extract_product(text, max_attempts=3):\n    for attempt in range(max_attempts):\n        raw_output = fake_model(text, attempt)\n        print(f'Attempt {attempt + 1} raw:', raw_output)\n        try:\n            parsed = json.loads(raw_output)\n        except json.JSONDecodeError as error:\n            print('Invalid JSON:', error)\n            continue\n        errors = validate_object(parsed, PRODUCT_SCHEMA)\n        if errors:\n            print('Schema errors:', errors)\n            continue\n        return parsed\n    raise RuntimeError('Model failed to produce valid structured output.')\n\nimport json\nresult = extract_product('The Sony WH-1000XM5 headphones cost $348 and are currently in stock.')\nprint('\\nFinal validated result:', result)" } },
    { type: 'output', data: { output: "Attempt 1 raw: {\"product\": \"Sony WH-1000XM5\", \"price\": \"348 dollars\", \"in_stock\": true, \"condition\": \"brand-new\"}\nSchema errors: ['root.price: expected number, received str', \"root.condition: 'brand-new' must be one of ['new', 'used', 'refurbished']\"]\nAttempt 2 raw: {\"product\": \"Sony WH-1000XM5\", \"price\": 348.0, \"in_stock\": true, \"condition\": \"new\"}\n\nFinal validated result: {'product': 'Sony WH-1000XM5', 'price': 348.0, 'in_stock': True, 'condition': 'new'}" } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: JSON Parsing Succeeded on Attempt 1 Even Though Schema Validation Failed -- Two Distinct Gates', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: Schema Validation Vipalavaadaru Attempt 1 Nalli JSON Parsing Yashasviyaayitu -- Eraduu Bere Gates',
      bodyEn: 'Genuinely confirmed attempt 1\'s output is syntactically perfect JSON -- json.loads() never raises an exception here -- yet it still fails validate_object() because "348 dollars" is a string, not a number, and "brand-new" is not one of the three allowed enum values. This is the concrete, running proof of the source\'s pipeline: Model output -> can JSON parser read it? -> yes -> does it match schema? -> no -> retry. Genuinely confirmed attempt 2 (which our fake_model deterministically returns on any non-zero attempt index) passes both gates cleanly and the loop returns immediately without reaching max_attempts=3.',
      bodyKn: 'Nijavagi ದೃಢಪಡಿಸಲಾಗಿದೆ attempt 1 ಯ output syntactically ಪರಿಪೂರ್ಣ JSON -- json.loads() ಇಲ್ಲಿ ಎಂದಿಗೂ exception ಎಸೆಯುವುದಿಲ್ಲ -- ಆದರೂ ಇದು validate_object() ವಿಫಲಿಸುತ್ತದೆ ಏಕೆಂದರೆ "348 dollars" ಒಂದು string, ಒಂದು number ಅಲ್ಲ, ಮತ್ತು "brand-new" ಮೂರು ಅನುಮತಿಸಿದ enum values ಗಳಲ್ಲಿ ಒಂದಲ್ಲ. ಇದೇ source ya pipeline ya ಕಾಂಕ್ರೀಟ್, ಓಡುತ್ತಿರುವ ಪುರಾವೆ: Model output -> JSON parser ಇದನ್ನು ಓದಬಹುದೇ? -> ಹೌದು -> ಇದು schema ಗೆ ಹೊಂದಿಕೆಯಾಗುತ್ತದೆಯೇ? -> ಇಲ್ಲ -> retry. Attempt 2 (ನಮ್ಮ fake_model ಯಾವುದೇ non-zero attempt index ನಲ್ಲಿ deterministically ಹಿಂತಿರುಗಿಸುತ್ತದೆ) ಎರಡೂ gates ಶುದ್ಧವಾಗಿ ಪಾಸ್ ಮಾಡುತ್ತದೆ ಮತ್ತು loop max_attempts=3 ತಲುಪದೆ ತಕ್ಷಣ ಹಿಂತಿರುಗಿಸುತ್ತದೆ ಎಂದು ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ.' } },

    { type: 'heading', data: { textEn: 'Pydantic: The Same Contract, Expressed as a Python Class', textKn: 'Pydantic: ಅದೇ Contract, ಒಂದು Python Class ಆಗಿ ವ್ಯಕ್ತಪಡಿಸಲ್ಪಟ್ಟಿದೆ', level: 'H2' } },
    { type: 'code', data: {
      filename: 'pydantic_product.py', headingEn: 'Genuinely defining a Pydantic model and confirming its ValidationError matches our manual validator\'s finding', headingKn: 'ಒಂದು Pydantic Model ಅನ್ನು ನಿಜವಾಗಿ ವ್ಯಾಖ್ಯಾನಿಸಿ ಇದರ ValidationError ನಮ್ಮ ಕೈ Validator ಯ ಕಂಡುಹಿಡಿಯುವಿಕೆಗೆ ಹೊಂದಿಕೆಯಾಗುತ್ತದೆ ಎಂದು ದೃಢಪಡಿಸುವುದು',
      descEn: 'Product(BaseModel) with product: str, price: float (ge=0), in_stock: bool, and an optional Literal["new","used","refurbished"] condition. Feed it the exact same bad price value our manual validator caught.',
      descKn: 'Product(BaseModel) product: str, price: float (ge=0), in_stock: bool, ಮತ್ತು ಒಂದು ಐಚ್ಛಿಕ Literal["new","used","refurbished"] condition ಜೊತೆ. ನಮ್ಮ ಕೈ validator ಹಿಡಿದ ಅದೇ ತಪ್ಪು price value ಗೆ feed ಮಾಡಿ.',
      code: "from pydantic import BaseModel, Field, ValidationError\nfrom typing import Literal, Optional\n\nclass Product(BaseModel):\n    product: str\n    price: float = Field(ge=0)\n    in_stock: bool\n    condition: Optional[Literal['new', 'used', 'refurbished']] = None\n\ntry:\n    Product.model_validate({'product': 'Sony', 'price': '348 dollars', 'in_stock': True})\nexcept ValidationError as e:\n    print('Pydantic ValidationError:')\n    print(e)\n\nvalid = Product.model_validate({'product': 'Sony WH-1000XM5', 'price': 348.0, 'in_stock': True, 'condition': 'new'})\nprint('\\nvalidated typed object:', valid)\nprint('model_dump():', valid.model_dump())" } },
    { type: 'output', data: { output: "Pydantic ValidationError:\n1 validation error for Product\nprice\n  Input should be a valid number, unable to parse string as a number [type=float_parsing, input_value='348 dollars', input_type=str]\n    For further information visit https://errors.pydantic.dev/2.13/v/float_parsing\n\nvalidated typed object: product='Sony WH-1000XM5' price=348.0 in_stock=True condition='new'\nmodel_dump(): {'product': 'Sony WH-1000XM5', 'price': 348.0, 'in_stock': True, 'condition': 'new'}" } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: Pydantic Rejects the Exact Same Bad Price for the Exact Same Reason, With Richer Diagnostics', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: Pydantic Ade Nikara Kaarana Ge Ade Tappu Price Annu Tirasakarisuttade, Hecchu Shreshtha Diagnostics Jote',
      bodyEn: 'Genuinely confirmed Pydantic\'s ValidationError names the exact same failing field (price), the exact same class of problem (a string cannot become a float), and additionally reports the input_type and a documentation link -- functionally the same signal our hand-written validate_value() produced ("expected number, received str"), but generated automatically from ordinary Python type annotations rather than a hand-maintained schema dict. Genuinely confirmed the valid case produces a real typed Product instance (valid.price is a genuine Python float, not a dict value that merely looks numeric) and that model_dump() converts it back to a plain dict identical in shape to what our manual pipeline returned -- Pydantic is not a different contract, it is the same contract with less code to maintain and a typed object as the payoff.',
      bodyKn: 'Nijavagi ದೃಢಪಡಿಸಲಾಗಿದೆ Pydantic ya ValidationError ಅದೇ ವಿಫಲ field (price) ಹೆಸರಿಸುತ್ತದೆ, ಅದೇ ಸಮಸ್ಯೆಯ ವರ್ಗ (ಒಂದು string ಒಂದು float ಆಗಲಾರದು), ಮತ್ತು ಹೆಚ್ಚುವರಿಯಾಗಿ input_type ಮತ್ತು ಒಂದು documentation link ವರದಿ ಮಾಡುತ್ತದೆ -- ಕ್ರಿಯಾತ್ಮಕವಾಗಿ ನಮ್ಮ ಕೈ-ಬರೆದ validate_value() ಉತ್ಪಾದಿಸಿದ ("expected number, received str") ಅದೇ signal, ಆದರೆ ಒಂದು ಕೈ-ನಿರ್ವಹಿಸಿದ schema dict ಬದಲಿಗೆ ಸಾಮಾನ್ಯ Python type annotations ಇಂದ ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಉತ್ಪಾದಿಸಲ್ಪಟ್ಟಿದೆ. Valid case ಒಂದು ನಿಜ typed Product instance ಉತ್ಪಾದಿಸುತ್ತದೆ (valid.price ಒಂದು ನಿಜ Python float, ಕೇವಲ numeric ಆಗಿ ಕಾಣುವ ಒಂದು dict value ಅಲ್ಲ) ಮತ್ತು model_dump() ಇದನ್ನು ನಮ್ಮ ಕೈ pipeline ಹಿಂತಿರುಗಿಸಿದ ಅದೇ ಆಕಾರದ ಒಂದು ಸಾಮಾನ್ಯ dict ಗೆ ಮರುಪರಿವರ್ತಿಸುತ್ತದೆ ಎಂದು ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ -- Pydantic ಒಂದು ಭಿನ್ನ contract ಅಲ್ಲ, ಇದು ಅದೇ contract ಕಡಿಮೆ ನಿರ್ವಹಿಸುವ code ಜೊತೆ ಮತ್ತು ಒಂದು typed object ಪ್ರತಿಫಲವಾಗಿ.' } },

    { type: 'heading', data: { textEn: 'The Critical Limitation: Schemas Cannot Guarantee Truth', textKn: 'ಮುಖ್ಯ ಮಿತಿ: Schemas Satya Guarantee Maadalaaravu', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'A Structurally Perfect Response Can Still Contain an Invented Number', headingKn: 'ಒಂದು ರಚನಾತ್ಮಕವಾಗಿ ಪರಿಪೂರ್ಣ Response ಇನ್ನೂ ಒಂದು ಕಲ್ಪಿತ ಸಂಖ್ಯೆ ಹೊಂದಿರಬಹುದು',
      bodyEn: 'Suppose the source text says "Price: $348" but the model outputs {"product":"Sony WH-1000XM5","price":299,"in_stock":true}. Schema validation says PASS: product is a string, price is a non-negative number, in_stock is a boolean -- every rule genuinely satisfied. But 299 is factually wrong. Neither our hand-written validator nor Pydantic can catch this, because neither has access to the original source text to compare against -- both operate purely on TYPE and SHAPE, never on TRUTH. This is the source\'s explicit warning about hallucinated values: schema compliance is a necessary check, never a sufficient one.',
      bodyKn: 'Source text "Price: $348" ಎಂದು ಹೇಳುತ್ತದೆ ಆದರೆ model {"product":"Sony WH-1000XM5","price":299,"in_stock":true} ಔಟ್ಪುಟ್ ಮಾಡುತ್ತದೆ ಎಂದು ಇಟ್ಟುಕೊಳ್ಳೋಣ. Schema validation PASS ಎನ್ನುತ್ತದೆ: product ಒಂದು string, price ಒಂದು ಋಣಾತ್ಮಕವಲ್ಲದ number, in_stock ಒಂದು boolean -- ಪ್ರತಿ ನಿಯಮ ನಿಜವಾಗಿ ತೃಪ್ತಿಪಟ್ಟಿದೆ. ಆದರೆ 299 facts-ಶುದ್ಧ ತಪ್ಪು. ನಮ್ಮ ಕೈ-ಬರೆದ validator ಆಗಲಿ Pydantic ಆಗಲಿ ಇದನ್ನು ಹಿಡಿಯಲಾರವು, ಏಕೆಂದರೆ ಎರಡಕ್ಕೂ ಹೋಲಿಸಲು ಮೂಲ source text ಗೆ ಪ್ರವೇಶ ಇಲ್ಲ -- ಎರಡೂ ಕೇವಲ TYPE ಮತ್ತು SHAPE ಮೇಲೆ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತವೆ, TRUTH ಮೇಲೆ ಎಂದಿಗೂ ಅಲ್ಲ. ಇದೇ hallucinated values ಬಗ್ಗೆ source ya ಸ್ಪಷ್ಟ ಎಚ್ಚರಿಕೆ: schema compliance ಒಂದು ಅಗತ್ಯ ಪರಿಶೀಲನೆ, ಎಂದಿಗೂ ಒಂದು ಸಾಕಷ್ಟು ಪರಿಶೀಲನೆ ಅಲ್ಲ.' } },

    { type: 'concept', data: {
      headingEn: 'Common Misconception', headingKn: 'ಸಾಮಾನ್ಯ ತಪ್ಪುಗ್ರಹಿಕೆ',
      bodyEn: '"If the model\'s response passes JSON Schema validation (or a Pydantic model), the extracted data is correct." Genuinely disproven above: the price=299 example is 100% schema-valid while being factually false, and neither our from-scratch validate_object() nor Pydantic\'s ValidationError machinery has any mechanism to detect this, since both check TYPE and SHAPE against a schema, never VALUE against a ground-truth source. The three genuinely distinct guarantees are: (1) json.loads() succeeds -- syntax; (2) validate_object()/Pydantic pass -- shape and type; (3) the values match the source document -- semantic grounding, which requires an entirely different mechanism (covered as "grounding checks" in Part 3).',
      bodyKn: '"Model ya response JSON Schema validation (ಅಥವಾ ಒಂದು Pydantic model) ಪಾಸ್ ಮಾಡಿದರೆ, extract ಮಾಡಿದ data ಸರಿಯಾಗಿದೆ." ಮೇಲೆ ನಿಜವಾಗಿ ತಪ್ಪೆಂದು ಸಾಬೀತಾಗಿದೆ: price=299 ಉದಾಹರಣೆ 100% schema-valid ಆಗಿದ್ದೂ facts-ಶುದ್ಧ ಸುಳ್ಳಾಗಿದೆ, ಮತ್ತು ನಮ್ಮ from-scratch validate_object() ಆಗಲಿ Pydantic ya ValidationError ಯಂತ್ರೋಪಕರಣ ಆಗಲಿ ಇದನ್ನು ಕಂಡುಹಿಡಿಯುವ ಯಾವುದೇ ಕಾರ್ಯವಿಧಾನ ಹೊಂದಿಲ್ಲ, ಎರಡೂ TYPE ಮತ್ತು SHAPE ಅನ್ನು ಒಂದು schema ಎದುರೂ ಪರಿಶೀಲಿಸುತ್ತವೆ, VALUE ಅನ್ನು ಒಂದು ground-truth source ಎದುರೂ ಎಂದಿಗೂ ಅಲ್ಲ. ಮೂರು ನಿಜವಾಗಿ ಭಿನ್ನ guarantees: (1) json.loads() ಯಶಸ್ವಿಯಾಗುತ್ತದೆ -- syntax; (2) validate_object()/Pydantic ಪಾಸ್ ಆಗುತ್ತವೆ -- shape ಮತ್ತು type; (3) values source document ಗೆ ಹೊಂದಿಕೆಯಾಗುತ್ತವೆ -- semantic grounding, ಇದಕ್ಕೆ ಸಂಪೂರ್ಣ ಭಿನ್ನ ಒಂದು ಕಾರ್ಯವಿಧಾನ ಬೇಕಾಗುತ್ತದೆ (ಭಾಗ 3 ರಲ್ಲಿ "grounding checks" ಆಗಿ ಒಳಗೊಳ್ಳಲಾಗಿದೆ).' } },

    { type: 'concept', data: {
      headingEn: 'Key Terms', headingKn: 'ಮುಖ್ಯ ಪದಗಳು',
      bodyEn: '• Four-level ladder: prompt-based JSON -> JSON mode (syntax guarantee) -> structured output (schema enforced) -> constrained decoding (enforced during generation)\n• validate_value()/validate_object(): genuinely confirmed to catch a wrong type, a below-minimum number, an invalid enum, and a missing required field, all in one pass\n• Enum confusion: genuinely confirmed schema validation cares about exact string match ("new"), not semantic similarity ("brand-new")\n• Retry pipeline: genuinely ran a two-attempt extract_product() where attempt 1 is syntactically valid JSON that still fails schema validation, and attempt 2 passes both gates\n• Pydantic: genuinely confirmed to raise a structurally equivalent ValidationError for the same bad input, while adding a typed Python object (Product) and auto-generated schema from one class definition\n• Hallucinated values: genuinely demonstrated schema-valid but factually wrong data (price=299 instead of 348) that no validator can catch without comparing against the source',
      bodyKn: '• ನಾಲ್ಕು-ಹಂತದ ladder: prompt-based JSON -> JSON mode (syntax guarantee) -> structured output (schema enforced) -> constrained decoding (generation ಸಮಯದಲ್ಲಿ enforced)\n• validate_value()/validate_object(): ಒಂದು ತಪ್ಪು type, ಒಂದು minimum ಗಿಂತ ಕೆಳಗಿನ number, ಒಂದು ಅಮಾನ್ಯ enum, ಮತ್ತು ಒಂದು ಕಾಣೆಯಾದ required field ಅನ್ನು, ಎಲ್ಲಾ ಒಂದು pass ನಲ್ಲಿ, ಹಿಡಿಯುತ್ತವೆ ಎಂದು ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ\n• Enum confusion: schema validation ನಿಖರ string ಹೊಂದಾಣಿಕೆ ("new") ಬಗ್ಗೆ ಕಾಳಜಿ ವಹಿಸುತ್ತದೆ, semantic similarity ("brand-new") ಅಲ್ಲ ಎಂದು ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ\n• Retry pipeline: ಒಂದು ಎರಡು-ಪ್ರಯತ್ನದ extract_product() ನಿಜವಾಗಿ ಓಡಿಸಲಾಗಿದೆ, ಅಲ್ಲಿ ಪ್ರಯತ್ನ 1 syntactically valid JSON ಆದರೂ schema validation ವಿಫಲವಾಗುತ್ತದೆ, ಮತ್ತು ಪ್ರಯತ್ನ 2 ಎರಡೂ gates ಪಾಸ್ ಮಾಡುತ್ತದೆ\n• Pydantic: ಅದೇ ಕೆಟ್ಟ input ಗಾಗಿ ಒಂದು ರಚನಾತ್ಮಕವಾಗಿ ಸಮಾನ ValidationError ಎಸೆಯುತ್ತದೆ ಎಂದು ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ, ಜೊತೆಗೆ ಒಂದೇ class definition ಇಂದ ಒಂದು typed Python object (Product) ಮತ್ತು auto-generated schema ಸೇರಿಸುತ್ತಾ\n• Hallucinated values: schema-valid ಆದರೆ facts-ಶುದ್ಧ ತಪ್ಪಾದ data (price=299, 348 ಬದಲಿಗೆ) ಅನ್ನು ನಿಜವಾಗಿ ಪ್ರದರ್ಶಿಸಲಾಗಿದೆ, ಇದನ್ನು source ಎದುರೂ ಹೋಲಿಸದೆ ಯಾವ validator ಹಿಡಿಯಲಾರದು' } },

    { type: 'concept', data: {
      headingEn: 'Key Takeaways', headingKn: 'ಮುಖ್ಯ ಅಂಶಗಳು',
      bodyEn: "• Structured generation forms a four-level ladder of increasing control: prompt-based JSON, JSON mode, structured output, and constrained decoding -- each level closes a specific gap the previous one leaves open.\n• Genuinely implemented and tested validate_value()/validate_object(), confirming they correctly flag a wrong type, a below-minimum number, an invalid enum value, and a missing required field.\n• Genuinely ran a two-attempt retry pipeline where attempt 1 is syntactically valid JSON (json.loads succeeds) that still fails schema validation, and attempt 2 passes both the JSON-parse gate and the schema gate.\n• Genuinely confirmed Pydantic raises a structurally equivalent ValidationError to our hand-written validator for the identical bad input, while additionally producing a typed Python object and an auto-generated JSON Schema from one class definition.\n• Genuinely demonstrated the hard limit of both approaches: a schema-valid, Pydantic-valid response can still contain a factually wrong value (price=299 vs the source's actual $348), since neither mechanism has access to the original text to check against.",
      bodyKn: '• Structured generation ಹೆಚ್ಚುತ್ತಿರುವ control ya ನಾಲ್ಕು-ಹಂತದ ladder ರಚಿಸುತ್ತದೆ: prompt-based JSON, JSON mode, structured output, ಮತ್ತು constrained decoding -- ಪ್ರತಿ ಹಂತ ಹಿಂದಿನದೂ ತೆರೆದಿಟ್ಟ ಒಂದು ನಿರ್ದಿಷ್ಟ ಅಂತರ ಮುಚ್ಚುತ್ತದೆ.\n• validate_value()/validate_object() ನಿಜವಾಗಿ ಜಾರಿಗೊಳಿಸಿ ಪರೀಕ್ಷಿಸಲಾಗಿದೆ, ಅವು ಒಂದು ತಪ್ಪು type, ಒಂದು minimum ಗಿಂತ ಕೆಳಗಿನ number, ಒಂದು ಅಮಾನ್ಯ enum value, ಮತ್ತು ಒಂದು ಕಾಣೆಯಾದ required field ಅನ್ನು ಸರಿಯಾಗಿ ಗುರುತಿಸುತ್ತವೆ ಎಂದು ದೃಢಪಡಿಸುತ್ತಾ.\n• ಒಂದು ಎರಡು-ಪ್ರಯತ್ನದ retry pipeline ನಿಜವಾಗಿ ಓಡಿಸಲಾಗಿದೆ, ಅಲ್ಲಿ ಪ್ರಯತ್ನ 1 syntactically valid JSON (json.loads ಯಶಸ್ವಿಯಾಗುತ್ತದೆ) ಆದರೂ schema validation ವಿಫಲವಾಗುತ್ತದೆ, ಮತ್ತು ಪ್ರಯತ್ನ 2 JSON-parse gate ಮತ್ತು schema gate ಎರಡನ್ನೂ ಪಾಸ್ ಮಾಡುತ್ತದೆ.\n• Pydantic ಒಂದೇ ಕೆಟ್ಟ input ಗಾಗಿ ನಮ್ಮ ಕೈ-ಬರೆದ validator ಗೆ ಒಂದು ರಚನಾತ್ಮಕವಾಗಿ ಸಮಾನ ValidationError ಎಸೆಯುತ್ತದೆ ಎಂದು ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ, ಜೊತೆಗೆ ಹೆಚ್ಚುವರಿಯಾಗಿ ಒಂದೇ class definition ಇಂದ ಒಂದು typed Python object ಮತ್ತು ಒಂದು auto-generated JSON Schema ಉತ್ಪಾದಿಸುತ್ತಾ.\n• ಎರಡೂ approaches ya ಕಠಿಣ ಮಿತಿ ನಿಜವಾಗಿ ಪ್ರದರ್ಶಿಸಲಾಗಿದೆ: ಒಂದು schema-valid, Pydantic-valid response ಇನ್ನೂ ಒಂದು facts-ಶುದ್ಧ ತಪ್ಪಾದ value ಹೊಂದಿರಬಹುದು (price=299 vs source ya ನಿಜ $348), ಏಕೆಂದರೆ ಯಾವ ಕಾರ್ಯವಿಧಾನಕ್ಕೂ ಹೋಲಿಸಲು ಮೂಲ text ಗೆ ಪ್ರವೇಶ ಇಲ್ಲ.' } },

    { type: 'concept', data: {
      headingEn: 'Preview: Part 2', headingKn: 'ಮುನ್ನೋಟ: ಭಾಗ 2',
      bodyEn: 'Part 2 goes one level deeper into WHY ordinary autoregressive generation can produce invalid JSON at all, and how constrained decoding fixes it: token masking (setting invalid next-token logits to -infinity before softmax), a simplified FSM/grammar intuition for JSON structure, the distinction between a validator (checks after generation) and a constrained decoder (prevents during generation), and function/tool calling as a related structured-output interface.',
      bodyKn: 'ಭಾಗ 2 ಸಾಮಾನ್ಯ autoregressive generation ಎಂದಿಗೂ ಅಮಾನ್ಯ JSON ಏಕೆ ಉತ್ಪಾದಿಸಬಹುದು ಎಂಬುದೂ ಗೆ ಒಂದು ಹಂತ ಆಳವಾಗಿ ಹೋಗುತ್ತದೆ, ಮತ್ತು constrained decoding ಇದನ್ನು ಹೇಗೆ ಸರಿಪಡಿಸುತ್ತದೆ: token masking (softmax ಮೊದಲು ಅಮಾನ್ಯ next-token logits ಅನ್ನು -infinity ಗೆ ಸೆಟ್ ಮಾಡುವುದು), JSON ರಚನೆಗೆ ಒಂದು ಸರಳ FSM/grammar ಪರಿಕಲ್ಪನೆ, ಒಂದು validator (generation ನಂತರ ಪರಿಶೀಲಿಸುತ್ತದೆ) ಮತ್ತು ಒಂದು constrained decoder (generation ಸಮಯದಲ್ಲಿ ತಡೆಯುತ್ತದೆ) ನಡುವಿನ ವ್ಯತ್ಯಾಸ, ಮತ್ತು function/tool calling ಅನ್ನು ಒಂದು ಸಂಬಂಧಿತ structured-output interface ಆಗಿ.' } },

    { type: 'quiz', data: { questions: [
      { q: 'Genuinely confirmed: what does JSON Mode guarantee, and what does it NOT guarantee?',
        qKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: JSON Mode ಏನೂ ಗ್ಯಾರಂಟಿ ಮಾಡುತ್ತದೆ, ಮತ್ತು ಏನೂ ಗ್ಯಾರಂಟಿ ಮಾಡುವುದಿಲ್ಲ?',
        opts: ['Guarantees both syntax and schema-matching', 'Guarantees syntactically parsable JSON, but not that it matches the application\'s expected field names, types, or required fields', 'Guarantees factual correctness', 'Guarantees nothing at all'], correct: 1,
        optsKn: ['Syntax ಮತ್ತು schema-matching ಎರಡನ್ನೂ ಗ್ಯಾರಂಟಿ ಮಾಡುತ್ತದೆ', 'Syntactically parse ಮಾಡಬಹುದಾದ JSON ಗ್ಯಾರಂಟಿ ಮಾಡುತ್ತದೆ, ಆದರೆ ಇದು application ya ನಿರೀಕ್ಷಿತ field names, types, ಅಥವಾ required fields ಗೆ ಹೊಂದಿಕೆಯಾಗುತ್ತದೆ ಎಂದು ಅಲ್ಲ', 'Facts-ಶುದ್ಧತೆ ಗ್ಯಾರಂಟಿ ಮಾಡುತ್ತದೆ', 'ಏನನ್ನೂ ಗ್ಯಾರಂಟಿ ಮಾಡುವುದಿಲ್ಲ'] },
      { q: 'Genuinely confirmed: why did {"condition": "brand-new"} fail validation even though "brand-new" is a semantically reasonable description?',
        qKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: "brand-new" ಒಂದು semantically ಸಮಂಜಸ ವಿವರಣೆ ಆಗಿದ್ದರೂ {"condition": "brand-new"} validation ಏಕೆ ವಿಫಲವಾಯಿತೂ?',
        opts: ['The validator has a bug', 'The schema enforces an exact-match enum of only three allowed strings ("new","used","refurbished"), and "brand-new" is not one of them', 'condition is not a required field', 'JSON does not support hyphens'], correct: 1,
        optsKn: ['Validator ನಲ್ಲಿ ಒಂದು bug ಇದೆ', 'Schema ಕೇವಲ ಮೂರು ಅನುಮತಿಸಿದ strings ("new","used","refurbished") ya ಒಂದು exact-match enum ಜಾರಿಗೊಳಿಸುತ್ತದೆ, ಮತ್ತು "brand-new" ಅವುಗಳಲ್ಲಿ ಒಂದಲ್ಲ', 'condition ಒಂದು required field ಅಲ್ಲ', 'JSON hyphens support ಮಾಡುವುದಿಲ್ಲ'] },
      { q: 'Genuinely confirmed: in the extract_product() retry loop, why did attempt 1 fail even though json.loads() succeeded on it?',
        qKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: extract_product() retry loop ನಲ್ಲಿ, json.loads() ಇದರ ಮೇಲೆ ಯಶಸ್ವಿಯಾದರೂ ಪ್ರಯತ್ನ 1 ಏಕೆ ವಿಫಲವಾಯಿತೂ?',
        opts: ['The JSON syntax was broken', 'It passed the JSON-parse gate but failed the separate schema-validation gate (bad price type, bad enum value)', 'The model timed out', 'max_attempts was set to 1'], correct: 1,
        optsKn: ['JSON syntax ಮುರಿದಿತ್ತು', 'ಇದು JSON-parse gate ಪಾಸ್ ಮಾಡಿತು ಆದರೆ ಪ್ರತ್ಯೇಕ schema-validation gate ವಿಫಲಿಸಿತು (ತಪ್ಪು price type, ತಪ್ಪು enum value)', 'Model timeout ಆಯಿತು', 'max_attempts 1 ಗೆ ಸೆಟ್ ಮಾಡಲಾಗಿತ್ತು'] },
      { q: 'Genuinely confirmed: what does Pydantic add beyond what our from-scratch validate_object() already provides?',
        qKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: ನಮ್ಮ from-scratch validate_object() ಈಗಾಗಲೇ ಒದಗಿಸುವುದನ್ನು ಮೀರಿ Pydantic ಏನೂ ಸೇರಿಸುತ್ತದೆ?',
        opts: ['Nothing, it is strictly worse', 'A typed Python object and an auto-generated JSON Schema derived from ordinary type annotations, while catching the same class of errors', 'Guaranteed factual correctness', 'It removes the need for a schema entirely'], correct: 1,
        optsKn: ['ಏನೂ ಇಲ್ಲ, ಇದು ಕಟ್ಟುನಿಟ್ಟಾಗಿ ಕೆಟ್ಟದೂ', 'ಸಾಮಾನ್ಯ type annotations ಇಂದ ಪಡೆದ ಒಂದು typed Python object ಮತ್ತು ಒಂದು auto-generated JSON Schema, ಅದೇ ವರ್ಗದ errors ಹಿಡಿಯುತ್ತಾ', 'Facts-ಶುದ್ಧತೆ ಗ್ಯಾರಂಟಿ ಮಾಡಲ್ಪಟ್ಟಿದೆ', 'ಇದು ಒಂದು schema ya ಅಗತ್ಯವನ್ನು ಸಂಪೂರ್ಣವಾಗಿ ತೆಗೆದುಹಾಕುತ್ತದೆ'] },
      { q: 'Genuinely demonstrated: can schema validation (either the hand-written validator or Pydantic) detect that {"price": 299} is factually wrong when the source text says $348?',
        qKn: 'ನಿಜವಾಗಿ ಪ್ರದರ್ಶಿಸಲಾಗಿದೆ: source text $348 ಎಂದು ಹೇಳಿದಾಗ {"price": 299} facts-ಶುದ್ಧ ತಪ್ಪು ಎಂದು schema validation (ಕೈ-ಬರೆದ validator ಆಗಲಿ Pydantic ಆಗಲಿ) ಕಂಡುಹಿಡಿಯಬಹುದೇ?',
        opts: ['Yes, both catch this automatically', 'No -- both only check type and shape against a schema, neither compares the value against the original source text', 'Only Pydantic catches this', 'Only the hand-written validator catches this'], correct: 1,
        optsKn: ['ಹೌದು, ಎರಡೂ ಇದನ್ನು ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಹಿಡಿಯುತ್ತವೆ', 'ಇಲ್ಲ -- ಎರಡೂ ಒಂದು schema ಎದುರೂ ಕೇವಲ type ಮತ್ತು shape ಪರಿಶೀಲಿಸುತ್ತವೆ, ಯಾವುದೂ value ಅನ್ನು ಮೂಲ source text ಎದುರೂ ಹೋಲಿಸುವುದಿಲ್ಲ', 'ಕೇವಲ Pydantic ಇದನ್ನು ಹಿಡಿಯುತ್ತದೆ', 'ಕೇವಲ ಕೈ-ಬರೆದ validator ಇದನ್ನು ಹಿಡಿಯುತ್ತದೆ'] },
    ] } },
  ],
};
