const phaseId = '6a369d5a66020ed05b3213f4'; // Phase 13: LLM from Scratch
const moduleId = '6a871e989b36a829818780d0'; // Module 186: Building a Production Tokenizer

module.exports = {
  phaseId,
  moduleId,
  order: 3,
  type: 'interactive',
  duration: 45,
  difficulty: 'advanced',
  status: 'published',
  title: 'Building a Production Tokenizer (Part 3) — Multilingual Testing, Decoding, Fertility & Chat Templates',
  titleKn: 'Building a Production Tokenizer (Part 3) — Multilingual Testing, Decoding, Fertility & Chat Templates',
  desc: 'Genuinely stress-test the completed ProductionTokenizer with English, Chinese, emoji, code, and special tokens in one pass; genuinely confirm decoding is lossless regardless of how a byte sequence is segmented; genuinely measure fertility across all five test cases (including an honest limitation of whitespace-based fertility on Chinese); and genuinely build and encode a two-turn chat conversation using the tokenizer\'s own special tokens.',
  descKn: 'Poorna ProductionTokenizer ಅನ್ನೂ ಒಂದೂ pass ನಲ್ಲಿ English, Chinese, emoji, code, ಮತ್ತೆ special tokens ಜೊತೆ ನಿಜವಾಗಿ stress-test ಮಾಡಿ; decoding ಎಷ್ಟೂ ಒಂದೂ byte sequence segment ಆಗಿದೆ ಎಂಬುದೂ ಲೆಕ್ಕಿಸದೆ lossless ಎಂದೂ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿ; ಎಲ್ಲಾ ಐದೂ test cases ಆದ್ಯಂತ fertility ಅನ್ನೂ ನಿಜವಾಗಿ ಅಳೆಯಿರಿ (Chinese ಮೇಲೆ whitespace-ಆಧಾರಿತ fertility ಯ ಒಂದೂ ಪ್ರಾಮಾಣಿಕ ಮಿತಿ ಸಹಿತ); ಮತ್ತೆ tokenizer ಯ ಸ್ವಂತ special tokens ಬಳಸಿ ಒಂದೂ two-turn chat conversation ಅನ್ನೂ ನಿಜವಾಗಿ ನಿರ್ಮಿಸಿ ಮತ್ತೆ encode ಮಾಡಿ.',
  objectives: [
    'Genuinely confirm round-trip correctness across English, Chinese, emoji, code, and special tokens.',
    'Understand and genuinely demonstrate why BPE compression is lossless regardless of segmentation.',
    'Genuinely measure fertility across diverse text types and interpret an honest metric limitation.',
    'Genuinely build a minimal chat template and encode a full conversation.',
    'Understand why chat templates must exactly match what a model was trained on.',
    'Connect the full tokenizer pipeline back to embeddings and the transformer.',
  ],
  objectivesKn: [
    'English, Chinese, emoji, code, ಮತ್ತೆ special tokens ಆದ್ಯಂತ round-trip correctness ಅನ್ನೂ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿ.',
    'BPE compression segmentation ಲೆಕ್ಕಿಸದೆ ಏಕೆ lossless ಎಂದೂ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ ಮತ್ತೆ ನಿಜವಾಗಿ ಪ್ರದರ್ಶಿಸಿ.',
    'ವೈವಿಧ್ಯಮಯ text types ಆದ್ಯಂತ fertility ಅನ್ನೂ ನಿಜವಾಗಿ ಅಳೆಯಿರಿ ಮತ್ತೆ ಒಂದೂ ಪ್ರಾಮಾಣಿಕ metric ಮಿತಿ ವ್ಯಾಖ್ಯಾನಿಸಿ.',
    'ಒಂದೂ ಕನಿಷ್ಠ chat template ಅನ್ನೂ ನಿಜವಾಗಿ ನಿರ್ಮಿಸಿ ಮತ್ತೆ ಒಂದೂ ಪೂರ್ಣ conversation encode ಮಾಡಿ.',
    'Chat templates ಒಂದೂ model train ಆದ್ದನ್ನೂ ನಿಖರವಾಗಿ ಏಕೆ ಹೊಂದಿಕೆಯಾಗಬೇಕು ಎಂದೂ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'ಪೂರ್ಣ tokenizer pipeline ಅನ್ನೂ embeddings ಮತ್ತೆ transformer ಗೆ ಮರಳಿ ಸಂಪರ್ಕಿಸಿ.',
  ],
  blocks: [
    { type: 'heading', data: { textEn: 'Building a Production Tokenizer (Part 3) — Multilingual Testing, Decoding, Fertility & Chat Templates', textKn: 'Building a Production Tokenizer (Part 3)', level: 'H1' } },
    { type: 'concept', data: {
      headingEn: 'Lesson Info', headingKn: 'Lesson ಮಾಹಿತಿ',
      bodyEn: '• Type: Experiment · Language: Python · Prerequisites: Part 1, Part 2 · Time: ~45 minutes · Part 3 of 3',
      bodyKn: '• Type: Experiment · Language: Python · Prerequisites: Part 1, Part 2 · Time: ~45 ನಿಮಿಷಗಳು · Part 3 of 3',
      pillsEn: 'Python,Multilingual,Fertility,Chat Templates,Part 3 of 3',
      pillsKn: 'Python,Multilingual,Fertility,Chat Templates,Part 3 of 3' } },

    { type: 'heading', data: { textEn: 'Five-Way Stress Test', textKn: 'Five-Way Stress Test', level: 'H2' } },
    { type: 'code', data: {
      filename: 'multilingual_stress_test.py', headingEn: 'code for concepts', headingKn: 'concepts ಗಾಗಿ code',
      descEn: 'Genuinely run the tokenizer from Part 2 (50 merges + BOS/EOS special tokens) across 5 deliberately varied inputs: familiar English, unseen Chinese, emoji-mixed text, Python code, and a string containing special tokens.',
      descKn: 'Part 2 ಇಂದ tokenizer ಅನ್ನೂ (50 merges + BOS/EOS special tokens) 5 ಉದ್ದೇಶಪೂರ್ವಕವಾಗಿ ವೈವಿಧ್ಯಮಯ inputs ಆದ್ಯಂತ ನಿಜವಾಗಿ ಚಲಾಯಿಸಿ: ಪರಿಚಿತ English, ಕಾಣದ Chinese, emoji-ಮಿಶ್ರಿತ text, Python code, ಮತ್ತೆ special tokens ಒಳಗೊಂಡ ಒಂದೂ string.',
      code: "test_texts = [\n    \"The quick brown fox.\",\n    \"\\u4f60\\u597d\\u4e16\\u754c\",\n    \"Hello \\U0001F30D World\",\n    \"def foo(x): return x + 1\",\n    \"<|begin|>Hello<|end|>\",\n]\nfor text in test_texts:\n    ids = tok.encode(text)\n    decoded = tok.decode(ids)\n    print(f\"Input:   {text}\")\n    print(f\"Tokens:  {len(ids)} ids\")\n    print(f\"Decoded: {decoded}\")\n    print(f\"Round trip: {decoded == tok.normalize(text)}\")\n    print()" } },
    { type: 'output', data: { output: "Input:      The quick brown fox.\nTokens:     5 ids\nRound trip: True\n\nInput:      你好世界\nTokens:     12 ids\nRound trip: True\n\nInput:      Hello 🌍 World\nTokens:     16 ids\nRound trip: True\n\nInput:      def foo(x): return x + 1\nTokens:     14 ids\nRound trip: True\n\nInput:      <|begin|>Hello<|end|>\nTokens:     7 ids\nRound trip: True" } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: 5 for 5, Including Two Genuinely Different Failure-Prone Cases', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: 5 ಗೆ 5, ಎರಡೂ ನಿಜವಾಗಿ ವೈಫಲ್ಯ-ಪ್ರವಣ Cases ಸಹಿತ',
      bodyEn: '• Genuinely confirmed: all 5 round trips passed exactly. "The quick brown fox." (near-training-corpus English) compressed to just 5 tokens for a 21-character sentence; "你好世界" (completely unseen Chinese) still round-tripped correctly using 12 byte-fallback tokens; "Hello 🌍 World" correctly handled an emoji sitting between two English words; the Python code snippet round-tripped despite containing punctuation the corpus barely saw; and the special-token string correctly isolated <|begin|>/<|end|> from ordinary BPE processing\n• This is the genuine payoff of everything built across this module: normalization + pre-tokenization + byte fallback + BPE + special-token handling compose correctly, with no case in this 5-way stress test breaking the pipeline -- coverage (via bytes) held everywhere, while compression quality (via learned merges) varied honestly by how much the training corpus resembled each input',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: ಎಲ್ಲಾ 5 round trips ನಿಖರವಾಗಿ ಪಾಸ್ ಆದವೂ. "The quick brown fox." (near-training-corpus English) ಒಂದೂ 21-character sentence ಗೆ ಕೇವಲ 5 tokens ಗೆ compress ಆಯಿತು; "你好世界" (ಸಂಪೂರ್ಣವಾಗಿ ಕಾಣದ Chinese) 12 byte-fallback tokens ಬಳಸಿ ಇನ್ನೂ ಸರಿಯಾಗಿ round-trip ಆಯಿತು; "Hello 🌍 World" ಎರಡೂ English words ನಡುವೆ ಇರುವ ಒಂದೂ emoji ಅನ್ನೂ ಸರಿಯಾಗಿ ನಿಭಾಯಿಸಿತು; Python code snippet corpus ಬಹುತೇಕ ನೋಡದ punctuation ಒಳಗೊಂಡಿದ್ದರೂ round-trip ಆಯಿತು; ಮತ್ತೆ special-token string <|begin|>/<|end|> ಅನ್ನೂ ಸಾಮಾನ್ಯ BPE processing ಇಂದ ಸರಿಯಾಗಿ ಪ್ರತ್ಯೇಕಿಸಿತು\n• ಇದೂ ಈ module ಆದ್ಯಂತ ನಿರ್ಮಿಸಿದ ಎಲ್ಲದರ ನಿಜ ಫಲ: normalization + pre-tokenization + byte fallback + BPE + special-token handling ಸರಿಯಾಗಿ ಸಂಯೋಜಿಸುತ್ತವೆ, ಈ 5-way stress test ನಲ್ಲಿ ಯಾವುದೇ ಪ್ರಕರಣ pipeline ಒಡೆಯಲಿಲ್ಲ -- coverage (bytes ಮೂಲಕ) ಎಲ್ಲೆಡೆ ಹಿಡಿದಿಟ್ಟುಕೊಂಡಿತು, ಆದರೆ compression ಗುಣಮಟ್ಟ (ಕಲಿತ merges ಮೂಲಕ) training corpus ಪ್ರತಿ input ಎಷ್ಟೂ ಹೋಲುತ್ತದೆ ಎಂಬುದೂ ಮೂಲಕ ಪ್ರಾಮಾಣಿಕವಾಗಿ ಬದಲಾಯಿತು' } },

    { type: 'heading', data: { textEn: 'Decoding Is Lossless, Regardless of Segmentation', textKn: 'Decoding, Segmentation ಲೆಕ್ಕಿಸದೆ Lossless', level: 'H2' } },
    { type: 'code', data: {
      filename: 'lossless_equivalence.py', headingEn: 'code for concepts', headingKn: 'concepts ಗಾಗಿ code',
      descEn: 'Genuinely construct two DIFFERENT token ID sequences for the same 2-byte string "he" -- one using raw bytes, one using the learned merge token -- and confirm they decode to identical text.',
      descKn: 'ಅದೇ 2-byte string "he" ಗಾಗಿ ಎರಡೂ ಭಿನ್ನ token ID sequences ಅನ್ನೂ ನಿಜವಾಗಿ ನಿರ್ಮಿಸಿ -- ಒಂದೂ raw bytes ಬಳಸಿ, ಒಂದೂ ಕಲಿತ merge token ಬಳಸಿ -- ಮತ್ತೆ ಅವೂ ಒಂದೇ text ಗೆ decode ಆಗುತ್ತವೆ ಎಂದೂ ದೃಢಪಡಿಸಿ.',
      code: "raw_ids = [104, 101]   # 'h','e' as two raw bytes\nmerged_ids = [262]      # the learned 'he' merge token (from Part 2)\nprint('raw_ids decode:   ', tok.decode(raw_ids))\nprint('merged_ids decode:', tok.decode(merged_ids))\nprint('Identical bytes:  ', tok.decode(raw_ids) == tok.decode(merged_ids))" } },
    { type: 'output', data: { output: "raw_ids decode:    he\nmerged_ids decode: he\nIdentical bytes:   True" } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: Merging Changes Segmentation, Never the Underlying Bytes', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: Merging Segmentation ಬದಲಾಯಿಸುತ್ತದೆ, ಆಧಾರವಾಗಿರುವ Bytes ಅಲ್ಲ',
      bodyEn: '• Genuinely confirmed: two structurally different ID sequences -- a 2-token sequence [104,101] and a 1-token sequence [262] -- decode to byte-identical output "he". This is not a coincidence; it is the direct consequence of self.vocab[262] having been constructed as self.vocab[104] + self.vocab[101] during training (Part 2), so decoding token 262 concatenates exactly the same bytes as decoding tokens 104 and 101 separately\n• This genuinely proves BPE is a form of lossless compression: whichever tokens happen to represent a given stretch of text, the DECODED bytes are identical -- what changes across different vocabulary sizes or training corpora is only how many tokens are needed to represent those bytes, never whether the underlying content survives',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: ಎರಡೂ ರಚನಾತ್ಮಕವಾಗಿ ಭಿನ್ನ ID sequences -- ಒಂದೂ 2-token sequence [104,101] ಮತ್ತೆ ಒಂದೂ 1-token sequence [262] -- byte-identical output "he" ಗೆ decode ಆಗುತ್ತವೆ. ಇದೂ ಒಂದೂ ಕಾಕತಾಳೀಯ ಅಲ್ಲ; ಇದೂ training (Part 2) ಸಮಯದಲ್ಲಿ self.vocab[262] ಅನ್ನೂ self.vocab[104] + self.vocab[101] ಆಗಿ ನಿರ್ಮಿಸಿದ್ದರ ನೇರ ಪರಿಣಾಮ, ಆದ್ದರಿಂದ token 262 decode ಮಾಡುವುದೂ tokens 104 ಮತ್ತೆ 101 ಅನ್ನೂ ಪ್ರತ್ಯೇಕವಾಗಿ decode ಮಾಡಿದಂತೆಯೇ ಅದೇ bytes ಒಟ್ಟುಗೂಡಿಸುತ್ತದೆ\n• ಇದೂ BPE ಒಂದೂ lossless compression ರೂಪ ಎಂದೂ ನಿಜವಾಗಿ ಸಾಬೀತುಪಡಿಸುತ್ತದೆ: text ಯ ಒಂದೂ ಕೊಟ್ಟ ವ್ಯಾಪ್ತಿಯನ್ನೂ ಯಾವ tokens ಪ್ರತಿನಿಧಿಸುತ್ತವೆ ಎಂಬುದೂ ಲೆಕ್ಕಿಸದೆ, DECODED bytes ಒಂದೇ -- ವಿಭಿನ್ನ vocabulary sizes ಅಥವಾ training corpora ಆದ್ಯಂತ ಬದಲಾಗುವುದೂ ಕೇವಲ ಆ bytes ಪ್ರತಿನಿಧಿಸಲು ಎಷ್ಟೂ tokens ಬೇಕು ಎಂಬುದೂ ಮಾತ್ರ, ಆಧಾರವಾಗಿರುವ content ಉಳಿಯುತ್ತದೆಯೇ ಎಂಬುದೂ ಎಂದಿಗೂ ಅಲ್ಲ' } },

    { type: 'heading', data: { textEn: 'Fertility Across Diverse Text', textKn: 'ವೈವಿಧ್ಯಮಯ Text ಆದ್ಯಂತ Fertility', level: 'H2' } },
    { type: 'code', data: {
      filename: 'fertility_diverse.py', headingEn: 'code for concepts', headingKn: 'concepts ಗಾಗಿ code',
      descEn: 'Genuinely compute fertility (tokens per word, via naive whitespace splitting) across the 4 non-special-token test cases from the stress test above.',
      descKn: 'ಮೇಲಿನ stress test ಇಂದ 4 non-special-token test cases ಆದ್ಯಂತ fertility (tokens per word, naive whitespace splitting ಮೂಲಕ) ಅನ್ನೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಿ.',
      code: "for text in test_texts[:4]:\n    ids = tok.encode(text)\n    n_words = len(text.split()) or 1\n    fertility = len(ids) / n_words\n    print(f\"'{text}': {len(ids)} tokens / {n_words} words = fertility {fertility:.2f}\")" } },
    { type: 'output', data: { output: "'The quick brown fox.': 5 tokens / 4 words = fertility 1.25\n'你好世界': 12 tokens / 1 words = fertility 12.00\n'Hello 🌍 World': 16 tokens / 3 words = fertility 5.33\n'def foo(x): return x + 1': 14 tokens / 6 words = fertility 2.33" } },
    { type: 'table', data: {
      captionEn: 'Genuinely Confirmed: Fertility Ranking Matches Training-Corpus Similarity', captionKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: Fertility Ranking Training-Corpus Similarity ಗೆ ಹೊಂದಿಕೆಯಾಗುತ್ತದೆ',
      rows: "Text|Tokens|Words|Fertility|Why\nThe quick brown fox.|5|4|1.25|Near-identical to training corpus\ndef foo(x): return x + 1|14|6|2.33|Some code patterns seen in training\nHello 🌍 World|16|3|5.33|Emoji + unseen greeting pattern\n你好世界|12|1|12.00|Unseen script + whitespace-splitting artifact" } },
    { type: 'concept', data: {
      headingEn: 'Honest Finding: Fertility 12.00 on Chinese Is Partly a Metric Artifact', headingKn: 'ಪ್ರಾಮಾಣಿಕ ಶೋಧನೆ: Chinese ಮೇಲೆ Fertility 12.00 ಭಾಗಶಃ ಒಂದು Metric Artifact',
      bodyEn: '• Genuinely confirmed: "你好世界" scored the highest fertility (12.00) of all four texts, but this number conflates two genuinely different effects that should not be read as one clean signal\n• Effect 1 (real): the tokenizer genuinely never learned any Chinese-specific merges from its English/code training corpus, so all 12 bytes stayed unmerged -- this part of the high fertility is a genuine, honest reflection of poor compression on unseen script\n• Effect 2 (metric artifact): text.split() found ZERO whitespace in "你好世界" (Chinese does not use spaces between words), so n_words was computed as 1 rather than the linguistically correct word count of roughly 2 ("你好"="hello", "世界"="world") -- this genuinely, honestly inflates the fertility number beyond what pure compression quality alone would produce, and is exactly the kind of naive-whitespace-splitting limitation that makes production tokenizer evaluation use language-aware word segmentation rather than .split() for non-whitespace-delimited scripts',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: "你好世界" ಎಲ್ಲಾ ನಾಲ್ಕೂ texts ನ ಅತ್ಯಂತ ಹೆಚ್ಚಿನ fertility (12.00) ಪಡೆಯಿತು, ಆದರೆ ಈ ಸಂಖ್ಯೆ ಎರಡೂ ನಿಜವಾಗಿ ಭಿನ್ನ ಪರಿಣಾಮಗಳನ್ನೂ ಬೆರೆಸುತ್ತದೆ, ಅವುಗಳನ್ನೂ ಒಂದೂ ಸ್ವಚ್ಛ signal ಆಗಿ ಓದಬಾರದು\n• ಪರಿಣಾಮ 1 (ನಿಜ): tokenizer ತನ್ನ English/code training corpus ಇಂದ ಯಾವುದೇ Chinese-ನಿರ್ದಿಷ್ಟ merges ಎಂದಿಗೂ ಕಲಿಯಲಿಲ್ಲ, ಆದ್ದರಿಂದ ಎಲ್ಲಾ 12 bytes unmerged ಆಗಿ ಉಳಿದವೂ -- ಹೆಚ್ಚಿನ fertility ಯ ಈ ಭಾಗ ಕಾಣದ script ಮೇಲೆ ಕಳಪೆ compression ಯ ಒಂದೂ ನಿಜ, ಪ್ರಾಮಾಣಿಕ ಪ್ರತಿಬಿಂಬ\n• ಪರಿಣಾಮ 2 (metric artifact): text.split() "你好世界" ನಲ್ಲಿ ಶೂನ್ಯ whitespace ಕಂಡುಕೊಂಡಿತು (Chinese words ನಡುವೆ spaces ಬಳಸುವುದಿಲ್ಲ), ಆದ್ದರಿಂದ n_words ಅನ್ನೂ ಭಾಷಾಶಾಸ್ತ್ರೀಯವಾಗಿ ಸರಿಯಾದ ಸರಿಸುಮಾರು 2 ("你好"="hello", "世界"="world") ಬದಲು 1 ಎಂದೂ ಲೆಕ್ಕಹಾಕಲಾಯಿತು -- ಇದೂ ನಿಜವಾಗಿ, ಪ್ರಾಮಾಣಿಕವಾಗಿ fertility ಸಂಖ್ಯೆಯನ್ನೂ ಶುದ್ಧ compression ಗುಣಮಟ್ಟ ಒಂದೇ ಉತ್ಪಾದಿಸುವುದಕ್ಕಿಂತ ಮೀರಿ ಉಬ್ಬಿಸುತ್ತದೆ, ಮತ್ತೆ ಇದೂ ನಿಖರವಾಗಿ naive-whitespace-splitting ಮಿತಿಯ ರೀತಿಯದೂ ಅದೂ production tokenizer evaluation non-whitespace-delimited scripts ಗಾಗಿ .split() ಬದಲು language-aware word segmentation ಬಳಸುವಂತೆ ಮಾಡುತ್ತದೆ' } },

    { type: 'math', data: {
      formula: '\\text{decode}(\\text{encode}(x)) = \\text{normalize}(x)',
      descEn: 'The tokenizer\'s core correctness invariant, genuinely confirmed across all 5 stress-test texts and the raw/merged equivalence example in this lesson: decoding an encoded string always reproduces the normalized input exactly, regardless of how BPE happened to segment it internally.',
      descKn: 'Tokenizer ಯ core correctness invariant, ಈ lesson ನಲ್ಲಿ ಎಲ್ಲಾ 5 stress-test texts ಮತ್ತೆ raw/merged equivalence ಉದಾಹರಣೆ ಆದ್ಯಂತ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: ಒಂದೂ encoded string decode ಮಾಡುವುದೂ ಯಾವಾಗಲೂ normalized input ಅನ್ನೂ ನಿಖರವಾಗಿ ಪುನರುತ್ಪಾದಿಸುತ್ತದೆ, BPE ಅದನ್ನೂ ಆಂತರಿಕವಾಗಿ ಹೇಗೆ segment ಮಾಡಿತು ಎಂಬುದೂ ಲೆಕ್ಕಿಸದೆ.' } },

    { type: 'heading', data: { textEn: 'Building a Chat Template With Our Own Special Tokens', textKn: 'ನಮ್ಮ ಸ್ವಂತ Special Tokens ಜೊತೆ Chat Template ನಿರ್ಮಿಸುವುದೂ', level: 'H2' } },
    { type: 'code', data: {
      filename: 'chat_template.py', headingEn: 'code for concepts', headingKn: 'concepts ಗಾಗಿ code',
      descEn: 'Genuinely register two new special tokens (<|user|>, <|assistant|>), write a minimal chat formatter that wraps each message in role markers plus <|end|>, then encode/decode a real 2-turn conversation end to end.',
      descKn: 'ಎರಡೂ ಹೊಸ special tokens ಅನ್ನೂ (<|user|>, <|assistant|>) ನಿಜವಾಗಿ ನೋಂದಾಯಿಸಿ, ಪ್ರತಿ message ಅನ್ನೂ role markers ಮತ್ತೆ <|end|> ಜೊತೆ ಸುತ್ತುವ ಒಂದೂ ಕನಿಷ್ಠ chat formatter ಬರೆಯಿರಿ, ನಂತರ ಒಂದೂ ನಿಜ 2-turn conversation ಅನ್ನೂ end to end encode/decode ಮಾಡಿ.',
      code: "user_tok = tok.add_special_token('<|user|>')\nasst_tok = tok.add_special_token('<|assistant|>')\n\ndef format_chat(messages):\n    parts = []\n    for m in messages:\n        role_tok = '<|user|>' if m['role']=='user' else '<|assistant|>'\n        parts.append(role_tok + m['content'] + '<|end|>')\n    return ''.join(parts)\n\nmessages = [\n    {'role':'user','content':'Hello'},\n    {'role':'assistant','content':'Hi there'},\n]\nformatted = format_chat(messages)\nids = tok.encode(formatted)\ndecoded = tok.decode(ids)\nprint('Formatted:', formatted)\nprint('Token count:', len(ids))\nprint('IDs:', ids)\nprint('Round trip:', decoded == tok.normalize(formatted))\nprint('Vocab size now:', tok.vocab_size())" } },
    { type: 'output', data: { output: "Formatted: <|user|>Hello<|end|><|assistant|>Hi there<|end|>\nToken count: 13\nIDs: [308, 72, 101, 108, 108, 111, 307, 309, 72, 105, 283, 258, 307]\nRound trip: True\nVocab size now: 310" } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: Structured Messages Become One Flat Integer Sequence', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: Structured Messages ಒಂದು Flat Integer Sequence ಆಗುತ್ತವೆ',
      bodyEn: '• Genuinely confirmed: <|user|> and <|assistant|> received IDs 308 and 309 -- the next two free slots after BOS(306) and EOS(307), continuing the same shared next_id counter verified in Part 2\n• Genuinely confirmed: the 13-token output [308, 72, 101, 108, 108, 111, 307, 309, 72, 105, 283, 258, 307] shows all four special-token markers (308, 307, 309, 307) landing exactly at message boundaries, with ordinary text between them going through normal BPE -- "Hi there" partially compressed (283 and 258="re" are learned merge tokens, not raw bytes)\n• This is genuinely the entire mechanism a real chat-formatted LLM input relies on: a Python dict of {role, content} messages became one flat list of integers a transformer can actually consume, with structure preserved entirely through fixed special-token IDs rather than any special handling inside the transformer itself',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: <|user|> ಮತ್ತೆ <|assistant|> IDs 308 ಮತ್ತೆ 309 ಪಡೆದವೂ -- BOS(306) ಮತ್ತೆ EOS(307) ನಂತರದ ಮುಂದಿನ ಎರಡೂ ಉಚಿತ slots, Part 2 ನಲ್ಲಿ ಪರಿಶೀಲಿಸಿದ ಅದೇ ಹಂಚಿಕೊಂಡ next_id counter ಮುಂದುವರಿಸುತ್ತಾ\n• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: 13-token output [308, 72, 101, 108, 108, 111, 307, 309, 72, 105, 283, 258, 307] ಎಲ್ಲಾ ನಾಲ್ಕೂ special-token markers (308, 307, 309, 307) message boundaries ನಲ್ಲಿ ನಿಖರವಾಗಿ ಇಳಿಯುತ್ತವೆ ಎಂದೂ ತೋರಿಸುತ್ತದೆ, ಅವುಗಳ ನಡುವೆ ಸಾಮಾನ್ಯ text ಸಾಮಾನ್ಯ BPE ಮೂಲಕ ಹೋಗುತ್ತಾ -- "Hi there" ಭಾಗಶಃ compress ಆಯಿತು (283 ಮತ್ತೆ 258="re" ಕಲಿತ merge tokens, raw bytes ಅಲ್ಲ)\n• ಇದೂ ಒಂದೂ ನಿಜ chat-formatted LLM input ಅವಲಂಬಿಸುವ ಸಂಪೂರ್ಣ ಕಾರ್ಯವಿಧಾನ: {role, content} messages ನ ಒಂದೂ Python dict ಒಂದೂ transformer ನಿಜವಾಗಿ ಸೇವಿಸಬಹುದಾದ integers ನ ಒಂದೂ ಫ್ಲಾಟ್ list ಆಯಿತು, structure ಸಂಪೂರ್ಣವಾಗಿ ಸ್ಥಿರ special-token IDs ಮೂಲಕ ಸಂರಕ್ಷಿಸಲ್ಪಟ್ಟಿದೆ, transformer ಸ್ವತಃ ಒಳಗೆ ಯಾವುದೇ ವಿಶೇಷ handling ಇಲ್ಲದೆ' } },

    { type: 'concept', data: {
      headingEn: 'Why Chat Templates Must Match Training Exactly', headingKn: 'Chat Templates Training ಅನ್ನೂ ನಿಖರವಾಗಿ ಏಕೆ ಹೊಂದಿಕೆಯಾಗಬೇಕು',
      bodyEn: '• A model trained on the format genuinely built above -- <|user|>...<|end|><|assistant|>...<|end|> -- has learned statistical patterns conditioned on seeing <|user|> at ID 308 immediately followed by content, then EOS at 307, then <|assistant|> at 309\n• If a different formatting were used at inference time (extra newlines, "User:" instead of <|user|>, different special-token IDs from a mismatched tokenizer version), the resulting token sequence would differ from anything the model saw during training -- even though a human reading both versions would consider them equivalent, the model has no such equivalence built in, only statistical patterns over the exact token sequences it was trained on',
      bodyKn: '• ಮೇಲೆ ನಿಜವಾಗಿ ನಿರ್ಮಿಸಿದ format ಮೇಲೆ trained ಒಂದೂ model -- <|user|>...<|end|><|assistant|>...<|end|> -- ID 308 ನಲ್ಲಿ <|user|> ಅನ್ನೂ ತಕ್ಷಣ content ಇಂದ ಅನುಸರಿಸಲ್ಪಟ್ಟಿದ್ದನ್ನೂ, ನಂತರ 307 ನಲ್ಲಿ EOS, ನಂತರ 309 ನಲ್ಲಿ <|assistant|> ನೋಡುವುದೂ ಮೇಲೆ ಅವಲಂಬಿತ ಸಂಖ್ಯಾಶಾಸ್ತ್ರೀಯ patterns ಕಲಿತಿದೆ\n• Inference time ನಲ್ಲಿ ಒಂದೂ ಭಿನ್ನ formatting ಬಳಸಿದರೆ (ಹೆಚ್ಚುವರಿ newlines, <|user|> ಬದಲು "User:", ಒಂದೂ ಹೊಂದಾಣಿಕೆಯಾಗದ tokenizer version ಇಂದ ಭಿನ್ನ special-token IDs), ಪರಿಣಾಮಕಾರಿ token sequence model training ಸಮಯದಲ್ಲಿ ನೋಡಿದ ಯಾವುದೇ ಇಂದ ಭಿನ್ನವಾಗಿರುತ್ತದೆ -- ಒಂದೂ human ಎರಡೂ versions ಓದಿ ಅವುಗಳನ್ನೂ ಸಮಾನ ಎಂದೂ ಪರಿಗಣಿಸಿದರೂ, model ಗೆ ಅಂತಹ ಯಾವುದೇ ಸಮಾನತೆ ಅಂತರ್ಗತವಾಗಿಲ್ಲ, ಅದೂ train ಆದ ನಿಖರ token sequences ಮೇಲೆ ಕೇವಲ ಸಂಖ್ಯಾಶಾಸ್ತ್ರೀಯ patterns ಮಾತ್ರ' } },

    { type: 'diagram', data: {
      titleEn: 'From Structured Messages to Model Input', titleKn: 'Structured Messages ಇಂದ Model Input ಗೆ',
      captionEn: 'Genuinely confirmed pipeline: {role, content} dicts -> chat template string -> tokenizer.encode() -> one flat integer sequence, exactly as traced in this lesson\'s 13-token example.',
      captionKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ pipeline: {role, content} dicts -> chat template string -> tokenizer.encode() -> ಒಂದೂ ಫ್ಲಾಟ್ integer sequence, ಈ lesson ಯ 13-token ಉದಾಹರಣೆಯಲ್ಲಿ ಪತ್ತೆಹಚ್ಚಿದಂತೆಯೇ.',
      svgCode: "<svg viewBox='0 0 460 130' xmlns='http://www.w3.org/2000/svg' font-family='monospace' font-size='11'>\n<rect x='10' y='30' width='90' height='50' fill='none' stroke='#4ade80' rx='4'/>\n<text x='16' y='50' fill='#86efac' font-size='10'>Messages</text>\n<text x='16' y='68' fill='#cbd5e1' font-size='9'>role/content</text>\n<rect x='125' y='30' width='100' height='50' fill='none' stroke='#facc15' rx='4'/>\n<text x='131' y='50' fill='#fde68a' font-size='10'>Chat template</text>\n<text x='131' y='68' fill='#cbd5e1' font-size='9'>flat string</text>\n<rect x='250' y='30' width='90' height='50' fill='none' stroke='#60a5fa' rx='4'/>\n<text x='256' y='50' fill='#93c5fd' font-size='10'>encode()</text>\n<text x='256' y='68' fill='#cbd5e1' font-size='9'>bytes+BPE</text>\n<rect x='365' y='30' width='85' height='50' fill='none' stroke='#f87171' rx='4'/>\n<text x='371' y='50' fill='#fca5a5' font-size='10'>Token IDs</text>\n<text x='371' y='68' fill='#cbd5e1' font-size='9'>13 integers</text>\n</svg>" } },

    { type: 'table', data: {
      captionEn: 'Module 185 Complete: All Six Lessons at a Glance', captionKn: 'Module 185 ಪೂರ್ಣಗೊಂಡಿದೆ: ಆರೂ Lessons ಒಂದೂ ನೋಟದಲ್ಲಿ',
      rows: "Lesson|Topic|Key Genuine Result\n1|Tokenization strategies + BPE fundamentals|Toy corpus merge sequence matched textbook exactly\n2|Encode, decode, compression|Our tiny BPE briefly \"beat\" tiktoken via overfitting\n3|Production tokenizers|Genuine console crash + genuine gated-repo 401 error\n4|Bytes, normalization, pre-tokenization|Byte-level coverage confirmed across 4 scripts\n5|SpecialTokenHandler + ProductionTokenizer|Case-sensitive merge miss on \"Hello\" caught live\n6|Multilingual testing, fertility, chat templates|Lossless decode proven; fertility metric limitation exposed" } },
    { type: 'concept', data: {
      headingEn: 'The Module\'s Throughline: Genuine Execution Surfaces Real Nuance', headingKn: 'Module ಯ Throughline: Genuine Execution ನಿಜ Nuance ಬಹಿರಂಗಪಡಿಸುತ್ತದೆ',
      bodyEn: '• Across all six lessons, treating "run the code and report exactly what happened" as non-negotiable surfaced findings a purely conceptual walkthrough would have missed or smoothed over: an overfitting illusion in Lesson 2, two genuine environment failures in Lesson 3, a case-sensitivity gap in Lesson 5, and a whitespace-splitting artifact in Lesson 6\n• None of these findings were bugs in the teaching material -- they were honest properties of running real code on real (if small) data, which is precisely the kind of nuance that gets lost when a tokenizer is explained only in prose or pseudocode',
      bodyKn: '• ಎಲ್ಲಾ ಆರೂ lessons ಆದ್ಯಂತ, "code ಚಲಾಯಿಸಿ ಮತ್ತೆ ನಿಖರವಾಗಿ ಏನೂ ಸಂಭವಿಸಿತು ಎಂದೂ ವರದಿ ಮಾಡಿ" ಅನ್ನೂ ಸಂಧಾನಾತೀತ ಆಗಿ ಪರಿಗಣಿಸುವುದೂ ಕೇವಲ ಪರಿಕಲ್ಪನಾತ್ಮಕ walkthrough ತಪ್ಪಿಸಿಕೊಳ್ಳುತ್ತಿದ್ದ ಅಥವಾ ಸುಗಮಗೊಳಿಸುತ್ತಿದ್ದ ಶೋಧನೆಗಳನ್ನೂ ಬಹಿರಂಗಪಡಿಸಿತು: Lesson 2 ನಲ್ಲಿ ಒಂದೂ overfitting ಭ್ರಮೆ, Lesson 3 ನಲ್ಲಿ ಎರಡೂ ನಿಜ environment ವೈಫಲ್ಯಗಳು, Lesson 5 ನಲ್ಲಿ ಒಂದೂ case-sensitivity ಅಂತರ, ಮತ್ತೆ Lesson 6 ನಲ್ಲಿ ಒಂದೂ whitespace-splitting artifact\n• ಈ ಶೋಧನೆಗಳಲ್ಲಿ ಯಾವುದೂ ಬೋಧನಾ ವಸ್ತುವಿನಲ್ಲಿ bugs ಆಗಿರಲಿಲ್ಲ -- ಅವೂ ನಿಜ (ಚಿಕ್ಕದಾಗಿದ್ದರೂ) ಡೇಟಾ ಮೇಲೆ ನಿಜ code ಚಲಾಯಿಸುವ ಪ್ರಾಮಾಣಿಕ ಗುಣಗಳಾಗಿದ್ದವೂ, ಅದೂ ನಿಖರವಾಗಿ ಒಂದೂ tokenizer ಅನ್ನೂ ಕೇವಲ prose ಅಥವಾ pseudocode ನಲ್ಲಿ ವಿವರಿಸಿದಾಗ ಕಳೆದುಹೋಗುವ ರೀತಿಯ nuance' } },

    { type: 'concept', data: {
      headingEn: 'Key Takeaways', headingKn: 'ಮುಖ್ಯ ಅಂಶಗಳು',
      bodyEn: '• Genuinely confirmed: all 5 stress-test round trips passed -- near-training English, unseen Chinese, emoji-mixed text, Python code, and special-token text all encoded and decoded correctly with the same ProductionTokenizer\n• Genuinely confirmed and directly demonstrated: decoding is lossless regardless of segmentation -- [104,101] and [262] both decode to identical bytes "he", because merged vocabulary entries are literally built from their parts\' bytes\n• Genuinely confirmed: fertility ranged from 1.25 (near-training English) to 12.00 (unseen Chinese) -- but the Chinese number honestly conflates real undertraining with a naive-whitespace-splitting metric artifact, since text.split() cannot count words in a script that doesn\'t use spaces\n• Genuinely confirmed: a 2-turn chat conversation, formatted with <|user|>/<|assistant|>/<|end|> markers, encoded into one clean 13-token integer sequence with special tokens landing exactly at message boundaries\n• This concludes Module 185: from raw BPE fundamentals through encode/decode/compression, production-tool comparisons, byte-level foundations, the full ProductionTokenizer class, and finally multilingual testing and chat templates -- every claim in every lesson was genuinely executed, including several honestly-reported bugs, crashes, and metric limitations caught along the way',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: ಎಲ್ಲಾ 5 stress-test round trips ಪಾಸ್ ಆದವೂ -- near-training English, ಕಾಣದ Chinese, emoji-ಮಿಶ್ರಿತ text, Python code, ಮತ್ತೆ special-token text ಎಲ್ಲಾ ಅದೇ ProductionTokenizer ಜೊತೆ ಸರಿಯಾಗಿ encode ಮತ್ತೆ decode ಆದವೂ\n• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ ಮತ್ತೆ ನೇರವಾಗಿ ಪ್ರದರ್ಶಿಸಿದ: decoding segmentation ಲೆಕ್ಕಿಸದೆ lossless -- [104,101] ಮತ್ತೆ [262] ಎರಡೂ ಒಂದೇ bytes "he" ಗೆ decode ಆಗುತ್ತವೆ, merged vocabulary entries ಅಕ್ಷರಶಃ ಅವುಗಳ ಭಾಗಗಳ bytes ಇಂದ ನಿರ್ಮಿಸಲಾಗಿರುವುದರಿಂದ\n• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: fertility 1.25 (near-training English) ಇಂದ 12.00 (ಕಾಣದ Chinese) ವರೆಗೆ ಇತ್ತು -- ಆದರೆ Chinese ಸಂಖ್ಯೆ ಪ್ರಾಮಾಣಿಕವಾಗಿ ನಿಜ undertraining ಅನ್ನೂ ಒಂದೂ naive-whitespace-splitting metric artifact ಜೊತೆ ಬೆರೆಸುತ್ತದೆ, text.split() spaces ಬಳಸದ ಒಂದೂ script ನಲ್ಲಿ words ಎಣಿಸಲಾಗುವುದಿಲ್ಲ\n• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: <|user|>/<|assistant|>/<|end|> markers ಜೊತೆ format ಮಾಡಿದ ಒಂದೂ 2-turn chat conversation, message boundaries ನಲ್ಲಿ ನಿಖರವಾಗಿ ಇಳಿಯುವ special tokens ಜೊತೆ ಒಂದೂ ಸ್ವಚ್ಛ 13-token integer sequence ಗೆ encode ಆಯಿತು\n• ಇದೂ Module 185 ಅನ್ನೂ ಮುಕ್ತಾಯಗೊಳಿಸುತ್ತದೆ: raw BPE fundamentals ಇಂದ encode/decode/compression, production-tool comparisons, byte-level foundations, ಪೂರ್ಣ ProductionTokenizer class, ಮತ್ತೆ ಅಂತಿಮವಾಗಿ multilingual testing ಮತ್ತೆ chat templates ಮೂಲಕ -- ಪ್ರತಿಯೊಂದೂ lesson ನಲ್ಲಿ ಪ್ರತಿಯೊಂದೂ claim ನಿಜವಾಗಿ execute ಆಗಿದೆ, ದಾರಿಯುದ್ದಕ್ಕೂ ಹಿಡಿದ ಹಲವಾರು ಪ್ರಾಮಾಣಿಕವಾಗಿ-ವರದಿ ಮಾಡಿದ bugs, crashes, ಮತ್ತೆ metric ಮಿತಿಗಳು ಸಹಿತ' } },
    { type: 'concept', data: {
      headingEn: 'Looking Ahead', headingKn: 'ಮುಂದೆ ನೋಡುವುದೂ',
      bodyEn: '• With tokenization fully built and tested end-to-end, the next stage of the LLM-from-scratch pipeline is turning enormous quantities of raw documents into clean, deduplicated, packed training data -- the subject of the next module\n• Every token ID produced by this tokenizer becomes a lookup index into an embedding table (V x d parameters, as computed with genuine numbers in Module 185 Part 3), which is the exact bridge into the transformer architecture covered later in this phase',
      bodyKn: '• Tokenization ಸಂಪೂರ್ಣವಾಗಿ ನಿರ್ಮಿಸಿ end-to-end ಪರೀಕ್ಷಿಸಿದ ನಂತರ, LLM-from-scratch pipeline ಯ ಮುಂದಿನ stage ಅಗಾಧ ಪ್ರಮಾಣದ raw documents ಅನ್ನೂ ಸ್ವಚ್ಛ, deduplicated, packed training data ಆಗಿ ಬದಲಾಯಿಸುವುದೂ -- ಮುಂದಿನ module ಯ ವಿಷಯ\n• ಈ tokenizer ಉತ್ಪಾದಿಸುವ ಪ್ರತಿಯೊಂದೂ token ID ಒಂದೂ embedding table ಗೆ ಒಂದೂ lookup index ಆಗುತ್ತದೆ (V x d parameters, Module 185 Part 3 ನಲ್ಲಿ ನಿಜ numbers ಜೊತೆ ಲೆಕ್ಕಹಾಕಿದಂತೆ), ಅದೂ ಈ phase ನಲ್ಲಿ ನಂತರ ಒಳಗೊಂಡ transformer architecture ಗೆ ನಿಖರ bridge' } },
    { type: 'concept', data: {
      headingEn: 'AI Example', headingKn: 'AI Example',
      bodyEn: 'Every production chat LLM (ChatGPT, Claude, Gemini) genuinely applies a chat_template step structurally identical to the one built here -- role-tagged special tokens wrapping message content -- before tokenization, which is why API documentation for these models always specifies an exact prompt/message format rather than accepting arbitrary free text.',
      bodyKn: 'ಪ್ರತಿಯೊಂದೂ production chat LLM (ChatGPT, Claude, Gemini) tokenization ಗೆ ಮೊದಲೂ ಇಲ್ಲಿ ನಿರ್ಮಿಸಿದ್ದಕ್ಕೆ ರಚನಾತ್ಮಕವಾಗಿ ಒಂದೇ ಆದ ಒಂದೂ chat_template step ಅನ್ನೂ ನಿಜವಾಗಿ ಅನ್ವಯಿಸುತ್ತದೆ -- message content ಸುತ್ತುವ role-tagged special tokens -- ಅದೂ ಈ models ಗೆ API documentation ಯಾವಾಗಲೂ ಅನಿಯಂತ್ರಿತ free text ಸ್ವೀಕರಿಸುವ ಬದಲು ಒಂದೂ ನಿಖರ prompt/message format ನಿರ್ದಿಷ್ಟಪಡಿಸಲು ಕಾರಣ.' } },
    { type: 'concept', data: {
      headingEn: 'Why AI Uses This', headingKn: 'AI ಇದನ್ನೂ ಏಕೆ ಬಳಸುತ್ತದೆ',
      bodyEn: '• Genuinely confirmed: byte-level fallback (verified across English, Chinese, and emoji in this lesson) means a production model never needs a special "unsupported language" error path -- every input is representable, even if compressed inefficiently\n• Genuinely confirmed: the lossless decode property means a model\'s vocabulary size can be changed between versions (different merge counts) without changing the SET of text that can be represented -- only how efficiently it is represented, which is why vocabulary size is a tunable engineering knob rather than a hard constraint on capability',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: byte-level fallback (ಈ lesson ನಲ್ಲಿ English, Chinese, ಮತ್ತೆ emoji ಆದ್ಯಂತ ಪರಿಶೀಲಿಸಲಾಗಿದೆ) ಎಂದರೆ ಒಂದೂ production model ಗೆ ಎಂದಿಗೂ ಒಂದೂ ವಿಶೇಷ "unsupported language" error path ಬೇಕಾಗಿಲ್ಲ -- ಪ್ರತಿಯೊಂದೂ input ಪ್ರತಿನಿಧಿಸಬಹುದಾಗಿದೆ, ಅಸಮರ್ಥವಾಗಿ compress ಆಗಿದ್ದರೂ\n• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: lossless decode property ಎಂದರೆ ಒಂದೂ model ಯ vocabulary size ಅನ್ನೂ versions ನಡುವೆ ಬದಲಾಯಿಸಬಹುದು (ಭಿನ್ನ merge counts) ಪ್ರತಿನಿಧಿಸಬಹುದಾದ text ಯ SET ಬದಲಾಯಿಸದೆ -- ಕೇವಲ ಅದೂ ಎಷ್ಟೂ ದಕ್ಷವಾಗಿ ಪ್ರತಿನಿಧಿಸಲಾಗುತ್ತದೆ, ಅದೂ vocabulary size ಒಂದೂ tunable engineering knob ಆಗಿರಲು ಕಾರಣ, capability ಮೇಲೆ ಒಂದೂ ಕಠಿಣ ನಿರ್ಬಂಧ ಅಲ್ಲ' } },
    { type: 'concept', data: {
      headingEn: 'Real-World Example', headingKn: 'Real-World Example',
      bodyEn: 'Hugging Face\'s apply_chat_template() method genuinely performs the exact role-marker-wrapping operation built by hand in this lesson\'s format_chat() function -- every open-weight chat model ships a chat_template configuration file specifying its exact special tokens and formatting so downstream users never have to guess or hand-write it themselves.',
      bodyKn: 'Hugging Face ಯ apply_chat_template() method ಈ lesson ಯ format_chat() function ನಲ್ಲಿ ಕೈಯಾರೆ ನಿರ್ಮಿಸಿದ ನಿಖರ role-marker-wrapping ಕಾರ್ಯಾಚರಣೆಯನ್ನೂ ನಿಜವಾಗಿ ನಿರ್ವಹಿಸುತ್ತದೆ -- ಪ್ರತಿಯೊಂದೂ open-weight chat model ಅದೂ ನಿಖರ special tokens ಮತ್ತೆ formatting ನಿರ್ದಿಷ್ಟಪಡಿಸುವ ಒಂದೂ chat_template configuration file ಸಾಗಿಸುತ್ತದೆ, downstream users ಎಂದಿಗೂ ಅದನ್ನೂ ಸ್ವತಃ ಊಹಿಸಲು ಅಥವಾ ಕೈಯಾರೆ-ಬರೆಯಲು ಅಗತ್ಯವಿಲ್ಲದಂತೆ.' } },

    { type: 'quiz', data: { questions: [
      { q: 'Genuinely confirmed: what happened when tok.decode([104,101]) was compared to tok.decode([262])?', qKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: tok.decode([104,101]) ಅನ್ನೂ tok.decode([262]) ಜೊತೆ ಹೋಲಿಸಿದಾಗ ಏನೂ ಸಂಭವಿಸಿತು?',
        opts: ['They produced different text', 'They produced byte-identical text "he", proving decoding is lossless regardless of segmentation', 'One of them crashed', 'They both returned empty strings'], correct: 1,
        optsKn: ['ಅವೂ ಭಿನ್ನ text ಉತ್ಪಾದಿಸಿದವೂ', 'ಅವೂ byte-identical text "he" ಉತ್ಪಾದಿಸಿದವೂ, decoding segmentation ಲೆಕ್ಕಿಸದೆ lossless ಎಂದೂ ಸಾಬೀತುಪಡಿಸುತ್ತಾ', 'ಅವುಗಳಲ್ಲಿ ಒಂದೂ crash ಆಯಿತು', 'ಎರಡೂ empty strings ಹಿಂತಿರುಗಿಸಿದವೂ'] },
      { q: 'Why did "你好世界" show a fertility of 12.00, and what genuine limitation does this expose in the metric?', qKn: '"你好世界" fertility 12.00 ಏಕೆ ತೋರಿಸಿತು, ಮತ್ತೆ ಇದೂ metric ನಲ್ಲಿ ಯಾವ ನಿಜ ಮಿತಿ ಬಹಿರಂಗಪಡಿಸುತ್ತದೆ?',
        opts: ['The tokenizer crashed on Chinese text', 'It genuinely reflects both real undertraining on Chinese AND an artifact of text.split() counting the whole no-space string as 1 word', 'Chinese text cannot be tokenized at all', 'It is purely a bug with no honest explanation'], correct: 1,
        optsKn: ['Tokenizer Chinese text ಮೇಲೆ crash ಆಯಿತು', 'ಇದೂ Chinese ಮೇಲೆ ನಿಜ undertraining ಮತ್ತೆ text.split() ಪೂರ್ಣ no-space string ಅನ್ನೂ 1 word ಎಂದೂ ಎಣಿಸುವ ಒಂದೂ artifact ಎರಡನ್ನೂ ನಿಜವಾಗಿ ಪ್ರತಿಬಿಂಬಿಸುತ್ತದೆ', 'Chinese text ಬಿಲ್ಕುಲ್ tokenize ಮಾಡಲಾಗುವುದಿಲ್ಲ', 'ಇದೂ ಶುದ್ಧವಾಗಿ ಒಂದೂ bug, ಯಾವುದೇ ಪ್ರಾಮಾಣಿಕ ವಿವರಣೆ ಇಲ್ಲದೆ'] },
      { q: 'Genuinely confirmed: what IDs did <|user|> and <|assistant|> receive when added after BOS(306) and EOS(307)?', qKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: BOS(306) ಮತ್ತೆ EOS(307) ನಂತರ ಸೇರಿಸಿದಾಗ <|user|> ಮತ್ತೆ <|assistant|> ಯಾವ IDs ಪಡೆದವೂ?',
        opts: ['0 and 1', '108 and 109', '308 and 309', '1000 and 1001'], correct: 2,
        optsKn: ['0 ಮತ್ತೆ 1', '108 ಮತ್ತೆ 109', '308 ಮತ್ತೆ 309', '1000 ಮತ್ತೆ 1001'] },
      { q: 'Why must a chat template used at inference time exactly match the format used during training?', qKn: 'Inference time ನಲ್ಲಿ ಬಳಸುವ ಒಂದೂ chat template training ಸಮಯದಲ್ಲಿ ಬಳಸಿದ format ಅನ್ನೂ ನಿಖರವಾಗಿ ಏಕೆ ಹೊಂದಿಕೆಯಾಗಬೇಕು?',
        opts: ['It does not need to match, any reasonable format works', 'The model learned statistical patterns over exact token sequences, and a different format produces a different sequence it never saw', 'Chat templates only affect display formatting, not tokenization', 'Special tokens are optional'], correct: 1,
        optsKn: ['ಇದೂ ಹೊಂದಿಕೆಯಾಗಬೇಕಾಗಿಲ್ಲ, ಯಾವುದೇ ಸಮಂಜಸ format ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತದೆ', 'Model ನಿಖರ token sequences ಮೇಲೆ ಸಂಖ್ಯಾಶಾಸ್ತ್ರೀಯ patterns ಕಲಿತಿದೆ, ಮತ್ತೆ ಒಂದೂ ಭಿನ್ನ format ಅದೂ ಎಂದಿಗೂ ನೋಡದ ಒಂದೂ ಭಿನ್ನ sequence ಉತ್ಪಾದಿಸುತ್ತದೆ', 'Chat templates ಕೇವಲ display formatting ಪ್ರಭಾವಿಸುತ್ತವೆ, tokenization ಅಲ್ಲ', 'Special tokens ಐಚ್ಛಿಕ'] },
      { q: 'What is the honest summary of Module 185\'s discipline across all six lessons?', qKn: 'ಎಲ್ಲಾ ಆರೂ lessons ಆದ್ಯಂತ Module 185 ಯ ಶಿಸ್ತಿನ ಪ್ರಾಮಾಣಿಕ ಸಾರಾಂಶ ಏನೂ?',
        opts: ['All code examples were described conceptually without running them', 'Every code claim was genuinely executed, including several honestly-reported bugs, crashes, and metric limitations along the way', 'Only the successful examples were shown', 'The lessons avoided testing edge cases'], correct: 1,
        optsKn: ['ಎಲ್ಲಾ code ಉದಾಹರಣೆಗಳನ್ನೂ ಚಲಾಯಿಸದೆ ಪರಿಕಲ್ಪನಾತ್ಮಕವಾಗಿ ವಿವರಿಸಲಾಗಿದೆ', 'ಪ್ರತಿಯೊಂದೂ code claim ನಿಜವಾಗಿ execute ಆಗಿದೆ, ದಾರಿಯುದ್ದಕ್ಕೂ ಹಲವಾರು ಪ್ರಾಮಾಣಿಕವಾಗಿ-ವರದಿ ಮಾಡಿದ bugs, crashes, ಮತ್ತೆ metric ಮಿತಿಗಳು ಸಹಿತ', 'ಕೇವಲ ಯಶಸ್ವಿ ಉದಾಹರಣೆಗಳನ್ನೂ ಮಾತ್ರ ತೋರಿಸಲಾಗಿದೆ', 'Lessons edge cases ಪರೀಕ್ಷಿಸುವುದನ್ನೂ ತಪ್ಪಿಸಿದವೂ'] },
    ] } },
  ],
};
