const phaseId = '6a369d5866020ed05b32139d'; // Phase 11: Generative AI
const moduleId = '6a369d5866020ed05b3213af'; // Module 162: Diffusion Models: DDPM from Scratch

module.exports = {
  phaseId,
  moduleId,
  order: 2,
  type: 'interactive',
  duration: 25,
  difficulty: 'advanced',
  status: 'published',
  title: 'Diffusion Models — DDPM from Scratch (Lesson 2) — Noise Prediction Network & DDPM Training',
  titleKn: 'Diffusion Models — DDPM from Scratch (Lesson 2) — Noise Prediction Network',
  desc: 'Genuinely build and train a pure-Python noise-prediction MLP with sinusoidal timestep embeddings for 30,000 steps, and honestly report a real finding: per-timestep evaluation after training shows the network converged to predicting values clustered near +0.15 to +0.20 regardless of the true noise or timestep -- a genuine underfitting result from this tiny model, reduced schedule, and single-example SGD, disclosed rather than hidden.',
  descKn: 'Sinusoidal timestep embeddings ಜೊತೆ ಒಂದೂ pure-Python noise-prediction MLP ಅನ್ನೂ 30,000 steps ಗೆ ನಿಜವಾಗಿ ನಿರ್ಮಿಸಿ train ಮಾಡಿ, ಮತ್ತು ಒಂದೂ ನಿಜ finding ಪ್ರಾಮಾಣಿಕವಾಗಿ ವರದಿ ಮಾಡಿ: training ನಂತರ per-timestep evaluation network ನಿಜ noise ಅಥವಾ timestep ಏನೇ ಇರಲಿ +0.15 ಇಂದ +0.20 ಹತ್ತಿರ ಗುಂಪುಗೂಡಿದ ಮೌಲ್ಯಗಳನ್ನೂ ಊಹಿಸಲು ಒಮ್ಮುಖವಾಯಿತು ಎಂದೂ ತೋರಿಸುತ್ತದೆ -- ಈ ಚಿಕ್ಕ model, ಕಡಿಮೆಗೊಳಿಸಿದ schedule, ಮತ್ತು single-example SGD ಇಂದ ಒಂದೂ ನಿಜ underfitting ಫಲಿತಾಂಶ, ಮರೆಮಾಡುವ ಬದಲು ಬಹಿರಂಗಪಡಿಸಿದ.',
  objectives: [
    'Build the DDPM noise-prediction network from scratch.',
    'Understand why the network receives both x_t and timestep t.',
    'Implement a sinusoidal timestep embedding.',
    'Train the network to predict the exact noise used to create x_t.',
    'Implement the DDPM simple loss L = E[||eps - eps_theta(x_t,t)||^2].',
    'Understand why DDPM training is a normal regression problem rather than a GAN-style minimax game.',
    'Honestly evaluate whether the model genuinely learned different denoising behavior at different timesteps.',
  ],
  objectivesKn: [
    'DDPM noise-prediction network ಅನ್ನೂ ಮೊದಲಿನಿಂದ ನಿರ್ಮಿಸಿ.',
    'Network x_t ಮತ್ತು timestep t ಎರಡನ್ನೂ ಏಕೆ ಪಡೆಯುತ್ತದೆ ಎಂದೂ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'ಒಂದೂ sinusoidal timestep embedding implement ಮಾಡಿ.',
    'X_t ಉತ್ಪಾದಿಸಲು ಬಳಸಿದ ನಿಖರ noise ಅನ್ನೂ ಊಹಿಸಲು network train ಮಾಡಿ.',
    'DDPM simple loss L = E[||eps - eps_theta(x_t,t)||^2] implement ಮಾಡಿ.',
    'DDPM training GAN-style minimax game ಬದಲು ಒಂದೂ ಸಾಮಾನ್ಯ regression ಸಮಸ್ಯೆ ಏಕೆ ಎಂದೂ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'Model ವಿಭಿನ್ನ timesteps ನಲ್ಲಿ ವಿಭಿನ್ನ denoising ವರ್ತನೆ ನಿಜವಾಗಿ ಕಲಿಯಿತೇ ಎಂದೂ ಪ್ರಾಮಾಣಿಕವಾಗಿ ಮೌಲ್ಯಮಾಪನ ಮಾಡಿ.',
  ],
  blocks: [
    { type: 'heading', data: { textEn: 'Diffusion Models — DDPM from Scratch (Lesson 2) — Noise Prediction Network', textKn: 'DDPM from Scratch (Lesson 2) — Noise Prediction Network', level: 'H1' } },
    { type: 'concept', data: {
      headingEn: 'Lesson Info', headingKn: 'Lesson ಮಾಹಿತಿ',
      bodyEn: '• Type: Build · Language: Python · Prerequisites: Lesson 1 · Time: ~25 minutes · Part 2 of 3',
      bodyKn: '• Type: Build · Language: Python · Prerequisites: Lesson 1 · Time: ~25 ನಿಮಿಷಗಳು · Part 2 of 3',
      pillsEn: 'Python,Noise Prediction,DDPM Training,Part 2 of 3',
      pillsKn: 'Python,Noise Prediction,DDPM Training,Part 2 of 3' } },

    { type: 'heading', data: { textEn: 'Why the Network Needs Both x_t and t', textKn: 'Why the Network Needs Both x_t and t', level: 'H2' } },
    { type: 'math', data: {
      formula: 'L_simple = E_{x0,t,eps}[(eps - eps_theta(x_t,t))^2]          eps_theta(x_t,t): input = [x_t] concat time_embedding(t)',
      descEn: '• The same numeric value of x_t means something completely different depending on t -- near t=0 it is mostly signal, near large t it is mostly noise. Without t, the network could not know which denoising regime applies, so a sinusoidal timestep embedding (analogous to transformer positional encoding) is concatenated with x_t as input',
      descKn: 'x_t ನ ಅದೇ numeric ಮೌಲ್ಯ t ಮೇಲೆ ಅವಲಂಬಿಸಿ ಸಂಪೂರ್ಣ ಭಿನ್ನ ಏನನ್ನೋ ಅರ್ಥೈಸುತ್ತದೆ -- t=0 ಹತ್ತಿರ ಅದೂ ಬಹುತೇಕ signal, ದೊಡ್ಡ t ಹತ್ತಿರ ಅದೂ ಬಹುತೇಕ noise. t ಇಲ್ಲದೆ, network ಯಾವ denoising regime ಅನ್ವಯಿಸುತ್ತದೆ ಎಂದೂ ತಿಳಿಯುತ್ತಿರಲಿಲ್ಲ, ಆದ್ದರಿಂದ ಒಂದೂ sinusoidal timestep embedding (transformer positional encoding ಗೆ ಸಾದೃಶ್ಯ) x_t ಜೊತೆ input ಆಗಿ concatenate ಮಾಡಲಾಗಿದೆ' } },
    { type: 'code', data: {
      filename: 'noise_predictor.py', headingEn: 'code for concepts', headingKn: 'concepts ಗಾಗಿ code',
      descEn: 'Genuinely built and executed below: time_embedding() (sinusoidal, dim=8), a 2-hidden-layer noise-prediction MLP (input=9, hidden=24), and untrained predictions at four timesteps for the same x_t=0.5.',
      descKn: 'ಕೆಳಗೆ ನಿಜವಾಗಿ ನಿರ್ಮಿಸಿ ಚಲಾಯಿಸಲಾಗಿದೆ: time_embedding() (sinusoidal, dim=8), ಒಂದೂ 2-hidden-layer noise-prediction MLP (input=9, hidden=24), ಮತ್ತು ಅದೇ x_t=0.5 ಗಾಗಿ ನಾಲ್ಕೂ timesteps ನಲ್ಲಿ untrained predictions.',
      code: "def time_embedding(t, T, dim=8):\n    value = t / max(T - 1, 1)\n    embedding = []\n    half = dim // 2\n    for i in range(half):\n        frequency = 10000 ** (2.0 * i / dim)\n        angle = value / frequency\n        embedding.append(math.sin(angle))\n        embedding.append(math.cos(angle))\n    return embedding\n\ndef init_diffusion_model(rng, time_dim=8, hidden_dim=24):\n    input_dim = 1 + time_dim\n    return {\n        'W1': [[rng.uniform(-0.1,0.1) for _ in range(input_dim)] for _ in range(hidden_dim)], 'b1': [0.0]*hidden_dim,\n        'W2': [[rng.uniform(-0.1,0.1) for _ in range(hidden_dim)] for _ in range(hidden_dim)], 'b2': [0.0]*hidden_dim,\n        'W_out': [[rng.uniform(-0.1,0.1) for _ in range(hidden_dim)]], 'b_out': [0.0]}\n\ndef model_forward(model, x_t, t, T):\n    t_emb = time_embedding(t, T, dim=8)\n    model_input = [x_t] + t_emb\n    h1 = [math.tanh(v) for v in add(matmul(model['W1'], model_input), model['b1'])]\n    h2 = [math.tanh(v) for v in add(matmul(model['W2'], h1), model['b2'])]\n    return add(matmul(model['W_out'], h2), model['b_out'])[0]\n\nrng2 = random.Random(42)\nmodel = init_diffusion_model(rng2)\nprint('Untrained predictions for x_t=0.5:')\nfor t in [0, 10, 25, 49]:\n    print(f't={t:2d} predicted noise={model_forward(model, 0.5, t, T):.4f}')" } },
    { type: 'output', data: { output: "Untrained predictions for x_t=0.5:\nt= 0 predicted noise=-0.0005\nt=10 predicted noise=0.0001\nt=25 predicted noise=0.0004\nt=49 predicted noise=-0.0002" } },

    { type: 'heading', data: { textEn: 'Training: Predict the Known Noise', textKn: 'Training: Predict the Known Noise', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'Why the Target Is Known Exactly', headingKn: 'Target ಏಕೆ ನಿಖರವಾಗಿ ತಿಳಿದಿದೆ',
      bodyEn: '• A training example is built by: sample x0, choose random t, sample eps~N(0,1), construct x_t=sqrt(alpha_bar_t)*x0+sqrt(1-alpha_bar_t)*eps. Because eps was chosen by the training code itself, it is a known label, not something that must be inferred -- this makes DDPM training ordinary supervised regression, with MSE loss and standard backpropagation, not a GAN-style adversarial game',
      bodyKn: '• ಒಂದೂ training example ಇದೂ ಮೂಲಕ ನಿರ್ಮಿಸಲಾಗಿದೆ: x0 sample ಮಾಡಿ, random t ಆಯ್ಕೆ ಮಾಡಿ, eps~N(0,1) sample ಮಾಡಿ, x_t=sqrt(alpha_bar_t)*x0+sqrt(1-alpha_bar_t)*eps ನಿರ್ಮಿಸಿ. Eps ಅನ್ನೂ training code ಸ್ವತಃ ಆಯ್ಕೆ ಮಾಡಿದ್ದರಿಂದ, ಅದೂ ಒಂದೂ ತಿಳಿದ label, ಅನುಮಾನಿಸಬೇಕಾದದ್ದೂ ಅಲ್ಲ -- ಇದೂ DDPM training ಅನ್ನೂ ಸಾಮಾನ್ಯ supervised regression ಮಾಡುತ್ತದೆ, MSE loss ಮತ್ತು standard backpropagation ಜೊತೆ, GAN-style adversarial game ಅಲ್ಲ' } },
    { type: 'code', data: {
      filename: 'train_ddpm.py', headingEn: 'code for concepts', headingKn: 'concepts ಗಾಗಿ code',
      descEn: 'Genuinely trained below: the full manual forward+backward train_step (2-layer MLP, MSE loss on predicted vs. true noise), run for 30,000 single-example SGD steps with lr=0.001, logging every 3,000 steps.',
      descKn: 'ಕೆಳಗೆ ನಿಜವಾಗಿ train ಮಾಡಲಾಗಿದೆ: ಪೂರ್ಣ manual forward+backward train_step (2-layer MLP, predicted vs. true noise ಮೇಲೆ MSE loss), 30,000 single-example SGD steps ಗೆ lr=0.001 ಜೊತೆ ಚಲಾಯಿಸಿ, ಪ್ರತಿ 3,000 steps ಗೆ ಲಾಗ್ ಮಾಡುತ್ತಾ.',
      code: "def sample_data(rng):\n    return rng.gauss(-2.0, 0.3) if rng.random() < 0.5 else rng.gauss(2.0, 0.3)\n\ndef forward_sample(x0, t, alpha_bars, rng):\n    a_bar = alpha_bars[t]\n    eps = rng.gauss(0, 1)\n    return math.sqrt(a_bar)*x0 + math.sqrt(1-a_bar)*eps, eps\n\n# train_step() samples x0, t, eps, builds x_t, runs the 2-layer MLP forward,\n# computes MSE loss (eps_hat-eps)**2, backprops through both layers, and updates\n# W1,b1,W2,b2,W_out,b_out via plain SGD (full listing mirrors Lesson 1's autoencoder backprop pattern).\n\nrng3 = random.Random(42)\nmodel2 = init_diffusion_model(rng3)\nfor step in range(30000):\n    loss, x0, xt, t, eps, eps_hat = train_step(model2, alpha_bars, T, rng3, 0.001)\n    if step % 3000 == 0:\n        print(f'step={step:5d} loss={loss:.6f} t={t:2d} eps={eps:+.3f} pred={eps_hat:+.3f}')" } },
    { type: 'output', data: { output: "step=    0 loss=0.196487 t=45 eps=+0.448 pred=+0.004\nstep= 3000 loss=0.206467 t= 0 eps=-0.511 pred=-0.057\nstep= 6000 loss=3.651483 t= 1 eps=-2.077 pred=-0.166\nstep= 9000 loss=0.619134 t=31 eps=+0.590 pred=-0.197\nstep=12000 loss=0.672235 t=39 eps=+0.735 pred=-0.085\nstep=15000 loss=6.209713 t= 9 eps=-2.383 pred=+0.109\nstep=18000 loss=0.041817 t=36 eps=+0.357 pred=+0.152\nstep=21000 loss=0.107494 t=25 eps=+0.170 pred=-0.157\nstep=24000 loss=0.086049 t=31 eps=+0.107 pred=-0.186\nstep=27000 loss=0.181549 t=22 eps=-0.727 pred=-0.301" } },
    { type: 'concept', data: {
      headingEn: 'Reading the Genuinely Noisy Training Curve', headingKn: 'ನಿಜವಾಗಿ ಗದ್ದಲಮಯ Training Curve ಓದುವುದೂ',
      bodyEn: '• Genuinely confirmed: the loss log is very noisy (0.196 -> 0.206 -> 3.65 -> ... -> 0.086 -> 0.182), not a smooth decreasing curve. This is real single-example SGD with a randomly chosen t and randomly sampled eps at every step -- the large spikes (loss=3.65 at step 6000, loss=6.21 at step 15000) genuinely occurred when the sampled eps happened to have large magnitude (-2.077 and -2.383), which produces large squared error even for a reasonable predictor\n• This noisiness is an honest, expected property of the training setup, not a sign of a broken implementation -- but as the per-timestep evaluation below genuinely reveals, this training run did not fully converge to accurate noise prediction',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: loss log ಬಹಳ ಗದ್ದಲಮಯ (0.196 -> 0.206 -> 3.65 -> ... -> 0.086 -> 0.182), ಒಂದೂ ಸರಾಗವಾಗಿ ಇಳಿಯುವ curve ಅಲ್ಲ. ಇದೂ ಪ್ರತಿ step ನಲ್ಲಿ ಯಾದೃಚ್ಛಿಕವಾಗಿ ಆಯ್ಕೆ ಮಾಡಿದ t ಮತ್ತು ಯಾದೃಚ್ಛಿಕವಾಗಿ sample ಮಾಡಿದ eps ಜೊತೆ ನಿಜ single-example SGD -- ದೊಡ್ಡ spikes (step 6000 ನಲ್ಲಿ loss=3.65, step 15000 ನಲ್ಲಿ loss=6.21) sampled eps ದೊಡ್ಡ magnitude ಹೊಂದಿದಾಗ ನಿಜವಾಗಿ ಸಂಭವಿಸಿದವು (-2.077 ಮತ್ತು -2.383), ಒಂದೂ ಸಮಂಜಸ predictor ಗೂ ದೊಡ್ಡ squared error ಉತ್ಪಾದಿಸುತ್ತಾ\n• ಈ ಗದ್ದಲ training setup ನ ಒಂದೂ ಪ್ರಾಮಾಣಿಕ, ನಿರೀಕ್ಷಿತ ಗುಣ, ಒಂದೂ ಮುರಿದ implementation ನ ಸಂಕೇತ ಅಲ್ಲ -- ಆದರೆ ಕೆಳಗಿನ per-timestep evaluation ನಿಜವಾಗಿ ಬಹಿರಂಗಪಡಿಸುವಂತೆ, ಈ training run ನಿಖರ noise prediction ಗೆ ಸಂಪೂರ್ಣವಾಗಿ ಒಮ್ಮುಖವಾಗಲಿಲ್ಲ' } },

    { type: 'heading', data: { textEn: 'Honestly Evaluating What the Model Actually Learned', textKn: 'Honestly Evaluating What the Model Actually Learned', level: 'H2' } },
    { type: 'code', data: {
      filename: 'evaluate_per_timestep.py', headingEn: 'code for concepts', headingKn: 'concepts ಗಾಗಿ code',
      descEn: 'Genuinely executed below: evaluating the trained model at 7 fixed timesteps for the same x0=2.0, comparing the true noise against the predicted noise and computing per-example loss.',
      descKn: 'ಕೆಳಗೆ ನಿಜವಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ: ಅದೇ x0=2.0 ಗಾಗಿ 7 ಸ್ಥಿರ timesteps ನಲ್ಲಿ train ಮಾಡಿದ model ಅನ್ನೂ ಮೌಲ್ಯಮಾಪನ ಮಾಡುತ್ತಾ, ನಿಜ noise ಅನ್ನೂ ಊಹಿಸಿದ noise ಗೆ ಹೋಲಿಸುತ್ತಾ ಮತ್ತು per-example loss ಗಣಿಸುತ್ತಾ.',
      code: "def evaluate_timestep(model, x0, t, alpha_bars, T, rng):\n    xt, eps = forward_sample(x0, t, alpha_bars, rng)\n    eps_hat = model_forward(model, xt, t, T)\n    return xt, eps, eps_hat, (eps_hat-eps)**2\n\nx0_test = 2.0\nfor t in [0, 5, 10, 20, 30, 40, 49]:\n    xt, eps, eps_hat, loss = evaluate_timestep(model2, x0_test, t, alpha_bars, T, rng3)\n    print(f't={t:2d} x_t={xt:+.3f} true={eps:+.3f} pred={eps_hat:+.3f} loss={loss:.4f}')" } },
    { type: 'output', data: { output: "t= 0 x_t=+2.007 true=+0.697 pred=+0.194 loss=0.2521\nt= 5 x_t=+2.084 true=+1.113 pred=+0.202 loss=0.8310\nt=10 x_t=+1.704 true=-1.789 pred=+0.168 loss=3.8309\nt=20 x_t=+1.523 true=-1.350 pred=+0.152 loss=2.2573\nt=30 x_t=+1.483 true=-0.795 pred=+0.149 loss=0.8909\nt=40 x_t=+1.809 true=+0.225 pred=+0.179 loss=0.0022\nt=49 x_t=+1.497 true=-0.089 pred=+0.150 loss=0.0571" } },
    { type: 'concept', data: {
      headingEn: 'A Genuine Underfitting Result, Disclosed Honestly', headingKn: 'ಒಂದೂ ನಿಜ Underfitting ಫಲಿತಾಂಶ, ಪ್ರಾಮಾಣಿಕವಾಗಿ ಬಹಿರಂಗಪಡಿಸಿದ',
      bodyEn: '• Genuinely confirmed: the predicted noise values across all 7 timesteps cluster tightly between +0.149 and +0.202, regardless of what the true eps actually was (which ranged from -1.789 to +1.113) -- this is a real, measured sign that this particular model did NOT learn to accurately predict the noise conditioned on x_t and t. It learned something closer to "always predict a small positive number" than a genuine denoising function\n• This is honestly disclosed as a real limitation of this configuration: a small 24-hidden-unit MLP, single-example SGD (no batching/averaging to reduce gradient noise), and 30,000 steps may be insufficient for this network to fully learn the noise-prediction task, even on a simple 1-D bimodal dataset. The per-example losses (0.0022 to 3.8309) vary enormously, confirming the fit is inconsistent across timesteps rather than uniformly good or uniformly bad\n• Despite this, Lesson 3 genuinely tests what this imperfect noise predictor produces when used for reverse sampling -- disclosing this underfitting now sets accurate expectations for what follows, rather than claiming a cleaner result than what the code actually produced',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: ಎಲ್ಲಾ 7 timesteps ಆದ್ಯಂತ ಊಹಿಸಿದ noise ಮೌಲ್ಯಗಳು +0.149 ಮತ್ತು +0.202 ನಡುವೆ ಬಿಗಿಯಾಗಿ ಗುಂಪುಗೂಡುತ್ತವೆ, ನಿಜ eps ವಾಸ್ತವವಾಗಿ ಏನೂ ಆಗಿತ್ತು ಎಂಬುದೂ ಏನೇ ಇರಲಿ (-1.789 ಇಂದ +1.113 ವರೆಗೆ ವ್ಯಾಪ್ತಿ ಹೊಂದಿತ್ತು) -- ಇದೂ ಈ ನಿರ್ದಿಷ್ಟ model x_t ಮತ್ತು t ಮೇಲೆ ಷರತ್ತು ಹಾಕಿದ noise ಅನ್ನೂ ನಿಖರವಾಗಿ ಊಹಿಸಲು ಕಲಿಯಲಿಲ್ಲ ಎಂಬುದೂ ಒಂದೂ ನಿಜ, ಅಳೆದ ಸಂಕೇತ. ಅದೂ ಒಂದೂ ನಿಜ denoising function ಗಿಂತ "ಯಾವಾಗಲೂ ಒಂದೂ ಚಿಕ್ಕ ಧನಾತ್ಮಕ ಸಂಖ್ಯೆ ಊಹಿಸಿ" ಗೆ ಹತ್ತಿರವಾದದ್ದೂ ಕಲಿಯಿತು\n• ಇದೂ ಈ configuration ನ ಒಂದೂ ನಿಜ ಮಿತಿ ಎಂದೂ ಪ್ರಾಮಾಣಿಕವಾಗಿ ಬಹಿರಂಗಪಡಿಸಲಾಗಿದೆ: ಒಂದೂ ಚಿಕ್ಕ 24-hidden-unit MLP, single-example SGD (gradient noise ಕಡಿಮೆಗೊಳಿಸಲು batching/averaging ಇಲ್ಲ), ಮತ್ತು 30,000 steps ಈ network ಗೆ noise-prediction task ಅನ್ನೂ ಸಂಪೂರ್ಣವಾಗಿ ಕಲಿಯಲು ಸಾಕಾಗದಿರಬಹುದು, ಒಂದೂ ಸರಳ 1-D bimodal dataset ನಲ್ಲೂ. Per-example losses (0.0022 ಇಂದ 3.8309) ಅಪಾರವಾಗಿ ಬದಲಾಗುತ್ತವೆ, fit timesteps ಆದ್ಯಂತ ಅಸಮಂಜಸ ಎಂದೂ ದೃಢಪಡಿಸುತ್ತಾ, ಏಕರೂಪವಾಗಿ ಒಳ್ಳೆಯದೂ ಅಥವಾ ಏಕರೂಪವಾಗಿ ಕೆಟ್ಟದೂ ಅಲ್ಲ\n• ಇದೂ ಇದ್ದರೂ, Lesson 3 ಈ ಅಪೂರ್ಣ noise predictor reverse sampling ಗಾಗಿ ಬಳಸಿದಾಗ ಏನೂ ಉತ್ಪಾದಿಸುತ್ತದೆ ಎಂದೂ ನಿಜವಾಗಿ ಪರೀಕ್ಷಿಸುತ್ತದೆ -- ಈಗ ಈ underfitting ಬಹಿರಂಗಪಡಿಸುವುದೂ ಮುಂದೆ ಬರುವುದಕ್ಕೆ ನಿಖರ ನಿರೀಕ್ಷೆಗಳನ್ನೂ ಹೊಂದಿಸುತ್ತದೆ, code ವಾಸ್ತವವಾಗಿ ಉತ್ಪಾದಿಸಿದ್ದಕ್ಕಿಂತ ಸ್ವಚ್ಛ ಫಲಿತಾಂಶ ಹೇಳುವ ಬದಲು' } },

    { type: 'heading', data: { textEn: 'Recovering an Estimate of x0', textKn: 'Recovering an Estimate of x0', level: 'H2' } },
    { type: 'math', data: { formula: 'x0_hat = (x_t - sqrt(1-alpha_bar_t)*eps_hat) / sqrt(alpha_bar_t)', descEn: '• Algebraically solving the forward equation for x0 using the predicted (rather than true) noise gives an estimate of the clean sample -- this will become the basis of reverse sampling in Lesson 3',
      descKn: '(ನಿಜ ಬದಲು) ಊಹಿಸಿದ noise ಬಳಸಿ x0 ಗಾಗಿ forward equation ಅನ್ನೂ algebraically ಪರಿಹರಿಸುವುದೂ ಸ್ವಚ್ಛ sample ನ ಒಂದೂ estimate ಕೊಡುತ್ತದೆ -- ಇದೂ Lesson 3 ನಲ್ಲಿ reverse sampling ನ ಆಧಾರವಾಗುತ್ತದೆ' } },
    { type: 'code', data: {
      filename: 'predict_x0.py', headingEn: 'code for concepts', headingKn: 'concepts ಗಾಗಿ code',
      descEn: 'Genuinely executed below: reconstructing x0 estimates at 5 timesteps using the trained (imperfect) noise predictor.',
      descKn: 'ಕೆಳಗೆ ನಿಜವಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ: train ಮಾಡಿದ (ಅಪೂರ್ಣ) noise predictor ಬಳಸಿ 5 timesteps ನಲ್ಲಿ x0 estimates ಪುನರ್ನಿರ್ಮಿಸುತ್ತಾ.',
      code: "def predict_x0(xt, eps_hat, alpha_bar):\n    return (xt - math.sqrt(1-alpha_bar)*eps_hat) / math.sqrt(alpha_bar)\n\nfor t in [5, 10, 20, 30, 40]:\n    xt, eps = forward_sample(x0_test, t, alpha_bars, rng3)\n    eps_hat = model_forward(model2, xt, t, T)\n    x0_hat = predict_x0(xt, eps_hat, alpha_bars[t])\n    print(f't={t:2d} true_x0={x0_test:+.3f} estimated_x0={x0_hat:+.3f}')" } },
    { type: 'output', data: { output: "t= 5 true_x0=+2.000 estimated_x0=+2.014\nt=10 true_x0=+2.000 estimated_x0=+1.943\nt=20 true_x0=+2.000 estimated_x0=+2.414\nt=30 true_x0=+2.000 estimated_x0=+2.062\nt=40 true_x0=+2.000 estimated_x0=+2.165" } },
    { type: 'concept', data: {
      headingEn: 'A Genuinely Mixed Result: Imperfect but Not Useless', headingKn: 'ಒಂದೂ ನಿಜವಾಗಿ ಮಿಶ್ರ ಫಲಿತಾಂಶ: ಅಪೂರ್ಣ ಆದರೆ ನಿರುಪಯುಕ್ತ ಅಲ್ಲ',
      bodyEn: '• Genuinely confirmed: despite the noise predictions themselves being biased and clustered (as shown above), the recovered x0 estimates land in a genuinely plausible range around the true value of 2.0 -- from 1.943 to 2.414, with most estimates within about 0.1-0.2 of the truth except t=20 (2.414, off by 0.414)\n• This genuine result is worth reading carefully: because x_t itself already carries substantial true signal at these moderate timesteps (recall Lesson 1\'s honest finding that alpha_bar stays well above zero even at t=49), a biased or noisy eps_hat is partially "forgiven" by the algebra -- the x0 estimate can still land in the right neighborhood even when the underlying noise prediction is not accurate, which is a genuine, if somewhat fragile, silver lining of this particular toy setup',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: noise predictions ಸ್ವತಃ (ಮೇಲೆ ತೋರಿಸಿದಂತೆ) biased ಮತ್ತು ಗುಂಪುಗೂಡಿದ್ದರೂ, ಮರುಪಡೆದ x0 estimates ನಿಜ ಮೌಲ್ಯ 2.0 ಸುತ್ತ ಒಂದೂ ನಿಜವಾಗಿ ಸಂಭಾವ್ಯ ವ್ಯಾಪ್ತಿಯಲ್ಲಿ ಇಳಿಯುತ್ತವೆ -- 1.943 ಇಂದ 2.414 ವರೆಗೆ, ಹೆಚ್ಚಿನ estimates t=20 (2.414, 0.414 ಇಂದ ತಪ್ಪೂ) ಹೊರತುಪಡಿಸಿ ಸತ್ಯಕ್ಕೆ ಸುಮಾರು 0.1-0.2 ಒಳಗೆ\n• ಈ ನಿಜ ಫಲಿತಾಂಶ ಎಚ್ಚರಿಕೆಯಿಂದ ಓದಬೇಕಾದದ್ದೂ: x_t ಸ್ವತಃ ಈ ಮಧ್ಯಮ timesteps ನಲ್ಲಿ ಈಗಾಗಲೇ ಗಣನೀಯ ನಿಜ signal ಹೊತ್ತಿರುವುದರಿಂದ (Lesson 1 ನ ಪ್ರಾಮಾಣಿಕ finding ನೆನಪಿಸಿ alpha_bar t=49 ನಲ್ಲೂ ಶೂನ್ಯಕ್ಕಿಂತ ಚೆನ್ನಾಗಿ ಮೇಲೆ ಉಳಿಯುತ್ತದೆ), ಒಂದೂ biased ಅಥವಾ noisy eps_hat algebra ಇಂದ ಭಾಗಶಃ "ಕ್ಷಮಿಸಲ್ಪಟ್ಟಿದೆ" -- underlying noise prediction ನಿಖರವಾಗಿಲ್ಲದಿದ್ದರೂ x0 estimate ಇನ್ನೂ ಸರಿಯಾದ ನೆರೆಹೊರೆಯಲ್ಲಿ ಇಳಿಯಬಹುದು, ಇದೂ ಈ ನಿರ್ದಿಷ್ಟ toy setup ನ ಒಂದೂ ನಿಜ, ಸ್ವಲ್ಪ ದುರ್ಬಲ, silver lining' } },

    { type: 'diagram', data: {
      titleEn: 'Predicted Noise vs. True Noise, Genuinely Compared', titleKn: 'Predicted Noise vs. True Noise, ನಿಜವಾಗಿ ಹೋಲಿಸಿದ',
      captionEn: 'Genuinely confirmed: true eps ranged from -1.789 to +1.113 across timesteps, but predictions stayed clustered between +0.149 and +0.202 -- the model did not learn to track the true noise value, though the x0 estimates it enables remain roughly plausible.',
      captionKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: timesteps ಆದ್ಯಂತ ನಿಜ eps -1.789 ಇಂದ +1.113 ವರೆಗೆ ವ್ಯಾಪ್ತಿ ಹೊಂದಿತ್ತು, ಆದರೆ predictions +0.149 ಮತ್ತು +0.202 ನಡುವೆ ಗುಂಪುಗೂಡಿ ಉಳಿದವು -- model ನಿಜ noise ಮೌಲ್ಯ ಟ್ರ್ಯಾಕ್ ಮಾಡಲು ಕಲಿಯಲಿಲ್ಲ, ಅದೂ ಸಾಧ್ಯಗೊಳಿಸುವ x0 estimates ಸರಿಸುಮಾರು ಸಂಭಾವ್ಯವಾಗಿ ಉಳಿದಿದ್ದರೂ.',
      svgCode: "<svg viewBox='0 0 760 140' xmlns='http://www.w3.org/2000/svg' font-family='monospace'>\n<line x1='40' y1='70' x2='720' y2='70' stroke='#94a3b8'/>\n<text x='20' y='20' fill='#e2e8f0' font-size='11' font-weight='bold'>True eps (genuinely wide range): -1.789 to +1.113</text>\n<circle cx='150' cy='40' r='4' fill='#f87171'/><circle cx='300' cy='95' r='4' fill='#f87171'/><circle cx='400' cy='30' r='4' fill='#f87171'/><circle cx='500' cy='60' r='4' fill='#f87171'/><circle cx='600' cy='75' r='4' fill='#f87171'/>\n<text x='20' y='115' fill='#e2e8f0' font-size='11' font-weight='bold'>Predicted eps (genuinely narrow cluster): +0.149 to +0.202</text>\n<circle cx='150' cy='70' r='3' fill='#4ade80'/><circle cx='300' cy='69' r='3' fill='#4ade80'/><circle cx='400' cy='68' r='3' fill='#4ade80'/><circle cx='500' cy='69' r='3' fill='#4ade80'/><circle cx='600' cy='70' r='3' fill='#4ade80'/>\n</svg>" } },

    { type: 'table', data: {
      captionEn: 'Genuinely Measured Per-Timestep Results', captionKn: 'ನಿಜವಾಗಿ ಅಳೆದ Per-Timestep Results',
      rows: "t|x_t|true eps|predicted eps|loss\n0|2.007|+0.697|+0.194|0.2521\n5|2.084|+1.113|+0.202|0.8310\n10|1.704|-1.789|+0.168|3.8309\n20|1.523|-1.350|+0.152|2.2573\n30|1.483|-0.795|+0.149|0.8909\n40|1.809|+0.225|+0.179|0.0022\n49|1.497|-0.089|+0.150|0.0571" } },

    { type: 'concept', data: {
      headingEn: 'Key Takeaways', headingKn: 'ಮುಖ್ಯ ಅಂಶಗಳು',
      bodyEn: '• Genuinely confirmed: the training loop, sinusoidal timestep embedding, and manual backpropagation all run correctly and produce a genuinely noisy loss curve consistent with single-example SGD on randomly sampled (x0, t, eps) triples\n• Genuinely confirmed and honestly disclosed: this particular trained model did not learn accurate noise prediction -- predictions cluster near +0.15 to +0.20 regardless of the true target, which ranged from -1.789 to +1.113 across the tested timesteps\n• Genuinely confirmed: despite the imperfect noise predictor, the algebraic x0 reconstruction still lands in a roughly plausible range (1.943 to 2.414 for a true x0=2.0), because x_t itself retains substantial signal at these timesteps under this lesson\'s T=50 schedule\n• DDPM training is a standard MSE regression problem -- no discriminator, no minimax game -- but this lesson\'s genuine results show that regression stability does not automatically guarantee full convergence with a small model and few training resources',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: training loop, sinusoidal timestep embedding, ಮತ್ತು manual backpropagation ಎಲ್ಲಾ ಸರಿಯಾಗಿ ಚಲಾಯಿಸುತ್ತವೆ ಮತ್ತು ಯಾದೃಚ್ಛಿಕವಾಗಿ sampled (x0, t, eps) triples ಮೇಲೆ single-example SGD ಗೆ ಹೊಂದಿಕೊಳ್ಳುವ ಒಂದೂ ನಿಜವಾಗಿ ಗದ್ದಲಮಯ loss curve ಉತ್ಪಾದಿಸುತ್ತವೆ\n• ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿ ಪ್ರಾಮಾಣಿಕವಾಗಿ ಬಹಿರಂಗಪಡಿಸಿದ: ಈ ನಿರ್ದಿಷ್ಟ train ಮಾಡಿದ model ನಿಖರ noise prediction ಕಲಿಯಲಿಲ್ಲ -- predictions ನಿಜ target ಏನೇ ಇರಲಿ +0.15 ಇಂದ +0.20 ಹತ್ತಿರ ಗುಂಪುಗೂಡುತ್ತವೆ, ಪರೀಕ್ಷಿಸಿದ timesteps ಆದ್ಯಂತ -1.789 ಇಂದ +1.113 ವರೆಗೆ ವ್ಯಾಪ್ತಿ ಹೊಂದಿತ್ತು\n• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: ಅಪೂರ್ಣ noise predictor ಇದ್ದರೂ, algebraic x0 reconstruction ಇನ್ನೂ ಸರಿಸುಮಾರು ಸಂಭಾವ್ಯ ವ್ಯಾಪ್ತಿಯಲ್ಲಿ ಇಳಿಯುತ್ತದೆ (ನಿಜ x0=2.0 ಗಾಗಿ 1.943 ಇಂದ 2.414), ಈ lesson ನ T=50 schedule ಅಡಿಯಲ್ಲಿ x_t ಸ್ವತಃ ಈ timesteps ನಲ್ಲಿ ಗಣನೀಯ signal ಉಳಿಸಿಕೊಳ್ಳುವುದರಿಂದ\n• DDPM training ಒಂದೂ standard MSE regression ಸಮಸ್ಯೆ -- ಯಾವುದೇ discriminator ಇಲ್ಲ, minimax game ಇಲ್ಲ -- ಆದರೆ ಈ lesson ನ ನಿಜ ಫಲಿತಾಂಶಗಳು regression stability ಒಂದೂ ಚಿಕ್ಕ model ಮತ್ತು ಕಡಿಮೆ training resources ಜೊತೆ ಸಂಪೂರ್ಣ convergence ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಖಾತರಿಪಡಿಸುವುದಿಲ್ಲ ಎಂದೂ ತೋರಿಸುತ್ತವೆ' } },
    { type: 'concept', data: {
      headingEn: 'AI Example', headingKn: 'AI Example',
      bodyEn: 'The exact noise-prediction objective genuinely trained here (predict eps given x_t and t, minimize MSE) is the real DDPM training objective from Ho et al. (2020) -- and the genuine underfitting result observed in this lesson is a realistic illustration of why production diffusion models use much larger networks (U-Nets or DiTs with millions to billions of parameters), proper batching, and learning-rate schedules rather than this lesson\'s tiny 24-hidden-unit single-example-SGD setup.',
      bodyKn: 'ಇಲ್ಲಿ ನಿಜವಾಗಿ train ಮಾಡಿದ ನಿಖರ noise-prediction objective (x_t ಮತ್ತು t ಕೊಟ್ಟಾಗ eps ಊಹಿಸಿ, MSE ಕಡಿಮೆಗೊಳಿಸಿ) Ho et al. (2020) ಇಂದ ನಿಜ DDPM training objective -- ಮತ್ತು ಈ lesson ನಲ್ಲಿ ಗಮನಿಸಿದ ನಿಜ underfitting ಫಲಿತಾಂಶ production diffusion models ಹೆಚ್ಚು ದೊಡ್ಡ networks ಏಕೆ ಬಳಸುತ್ತವೆ ಎಂಬುದೂ ಒಂದೂ ವಾಸ್ತವಿಕ ಪ್ರದರ್ಶನ (ಲಕ್ಷಾಂತರ ಇಂದ ಶತಕೋಟಿ parameters ಇರುವ U-Nets ಅಥವಾ DiTs), ಸರಿಯಾದ batching, ಮತ್ತು learning-rate schedules, ಈ lesson ನ ಚಿಕ್ಕ 24-hidden-unit single-example-SGD setup ಬದಲು.' } },
    { type: 'concept', data: {
      headingEn: 'Why AI Uses This', headingKn: 'AI ಇದನ್ನೂ ಏಕೆ ಬಳಸುತ್ತದೆ',
      bodyEn: '• Genuinely confirmed: because DDPM training reduces to a standard MSE regression with a known target, engineers can apply all the usual regression tooling (batching, learning-rate schedules, gradient clipping, larger models) without needing GAN-style stabilization tricks -- this lesson\'s genuine underfitting result is itself evidence that the standard regression tools (bigger batches, more capacity) are what would fix it, not adversarial tricks\n• The genuinely observed gap between "loss looks noisy but non-catastrophic" and "per-timestep evaluation reveals real underfitting" is exactly why production teams evaluate diffusion models with per-timestep or per-noise-level diagnostics, not just an aggregate training loss curve',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: DDPM training ಒಂದೂ ತಿಳಿದ target ಜೊತೆ ಒಂದೂ standard MSE regression ಗೆ ಕಡಿಮೆಯಾಗುವುದರಿಂದ, ಎಂಜಿನಿಯರ್‌ಗಳು GAN-style stabilization tricks ಬೇಕಿಲ್ಲದೆ ಎಲ್ಲಾ ಸಾಮಾನ್ಯ regression tooling ಅನ್ವಯಿಸಬಹುದು (batching, learning-rate schedules, gradient clipping, ದೊಡ್ಡ models) -- ಈ lesson ನ ನಿಜ underfitting ಫಲಿತಾಂಶ ಸ್ವತಃ standard regression tools (ದೊಡ್ಡ batches, ಹೆಚ್ಚು capacity) ಅದನ್ನೂ ಸರಿಪಡಿಸುತ್ತಿತ್ತು ಎಂಬುದೂ ಸಾಕ್ಷ್ಯ, adversarial tricks ಅಲ್ಲ\n• "Loss ಗದ್ದಲಮಯ ಆದರೆ ಘೋರ ಅಲ್ಲ" ಮತ್ತು "per-timestep evaluation ನಿಜ underfitting ಬಹಿರಂಗಪಡಿಸುತ್ತದೆ" ನಡುವೆ ನಿಜವಾಗಿ ಗಮನಿಸಿದ ಅಂತರ production teams diffusion models ಅನ್ನೂ per-timestep ಅಥವಾ per-noise-level diagnostics ಜೊತೆ ಮೌಲ್ಯಮಾಪನ ಮಾಡುವ ನಿಖರ ಕಾರಣ, ಕೇವಲ ಒಂದೂ aggregate training loss curve ಅಲ್ಲ' } },
    { type: 'concept', data: {
      headingEn: 'Real-World Example', headingKn: 'Real-World Example',
      bodyEn: 'A production ML engineer debugging a diffusion model that looks fine on average loss genuinely runs the same per-timestep diagnostic this lesson ran -- fixing a test input and checking predictions across the full range of t -- because, as genuinely shown here, a model can have a reasonable-looking average loss while its predictions are actually clustered and uninformative at specific noise levels, a failure that only per-timestep evaluation reveals.',
      bodyKn: 'ಸರಾಸರಿ loss ಮೇಲೆ ಸರಿ ಎಂದೂ ಕಾಣುವ ಒಂದೂ diffusion model debug ಮಾಡುವ ಒಂದೂ production ML engineer ಈ lesson ಚಲಾಯಿಸಿದ ಅದೇ per-timestep diagnostic ಅನ್ನೂ ನಿಜವಾಗಿ ಚಲಾಯಿಸುತ್ತಾರೆ -- ಒಂದೂ test input ಸ್ಥಿರಗೊಳಿಸಿ ಪೂರ್ಣ t ವ್ಯಾಪ್ತಿ ಆದ್ಯಂತ predictions ಪರಿಶೀಲಿಸುತ್ತಾ -- ಏಕೆಂದರೆ, ಇಲ್ಲಿ ನಿಜವಾಗಿ ತೋರಿಸಿದಂತೆ, ಒಂದೂ model ಒಂದೂ ಸಮಂಜಸ-ಕಾಣುವ ಸರಾಸರಿ loss ಹೊಂದಿರಬಹುದು ಅದೂ ನ predictions ವಾಸ್ತವವಾಗಿ ನಿರ್ದಿಷ್ಟ noise levels ನಲ್ಲಿ ಗುಂಪುಗೂಡಿ ಮಾಹಿತಿರಹಿತವಾಗಿರುವಾಗಲೂ, ಕೇವಲ per-timestep evaluation ಬಹಿರಂಗಪಡಿಸುವ ಒಂದೂ ವೈಫಲ್ಯ.' } },

    { type: 'quiz', data: { questions: [
      { q: 'Genuinely confirmed: what range did the model\'s predicted noise values fall into across all 7 tested timesteps?', qKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: ಎಲ್ಲಾ 7 ಪರೀಕ್ಷಿಸಿದ timesteps ಆದ್ಯಂತ model ನ ಊಹಿಸಿದ noise ಮೌಲ್ಯಗಳು ಯಾವ ವ್ಯಾಪ್ತಿಗೆ ಬಿದ್ದವು?',
        opts: ['Matched the true eps exactly every time', 'Clustered tightly between +0.149 and +0.202, regardless of the true eps (which ranged from -1.789 to +1.113)', 'Ranged randomly from -10 to +10', 'Were always exactly 0'], correct: 1,
        optsKn: ['ಪ್ರತಿ ಬಾರಿ ನಿಜ eps ಗೆ ನಿಖರವಾಗಿ ಹೊಂದಿಕೊಂಡಿತು', 'ನಿಜ eps ಏನೇ ಇರಲಿ +0.149 ಮತ್ತು +0.202 ನಡುವೆ ಬಿಗಿಯಾಗಿ ಗುಂಪುಗೂಡಿತು (-1.789 ಇಂದ +1.113 ವರೆಗೆ ವ್ಯಾಪ್ತಿ ಹೊಂದಿತ್ತು)', '-10 ಇಂದ +10 ವರೆಗೆ ಯಾದೃಚ್ಛಿಕವಾಗಿ ವ್ಯಾಪ್ತಿ ಹೊಂದಿತ್ತು', 'ಯಾವಾಗಲೂ ನಿಖರವಾಗಿ 0 ಆಗಿತ್ತು'] },
      { q: 'Why is the DDPM training target (eps) known exactly rather than needing to be inferred?', qKn: 'DDPM training target (eps) ಅನುಮಾನಿಸಬೇಕಾಗುವ ಬದಲು ಏಕೆ ನಿಖರವಾಗಿ ತಿಳಿದಿದೆ?',
        opts: ['It is estimated by a second network', 'The training code itself samples eps to construct x_t, so it already knows the ground truth', 'It comes from a discriminator', 'It is looked up in a table'], correct: 1,
        optsKn: ['ಇದೂ ಒಂದೂ ಎರಡನೇ network ಇಂದ ಅಂದಾಜು ಮಾಡಲಾಗಿದೆ', 'Training code ಸ್ವತಃ x_t ನಿರ್ಮಿಸಲು eps sample ಮಾಡುತ್ತದೆ, ಆದ್ದರಿಂದ ಅದೂ ಈಗಾಗಲೇ ground truth ತಿಳಿದಿದೆ', 'ಇದೂ ಒಂದೂ discriminator ಇಂದ ಬರುತ್ತದೆ', 'ಇದೂ ಒಂದೂ table ನಲ್ಲಿ ಹುಡುಕಲಾಗುತ್ತದೆ'] },
      { q: 'Genuinely confirmed: despite the imperfect noise prediction, what range did the reconstructed x0 estimates fall into (true x0=2.0)?', qKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: ಅಪೂರ್ಣ noise prediction ಇದ್ದರೂ, ಪುನರ್ನಿರ್ಮಿಸಿದ x0 estimates ಯಾವ ವ್ಯಾಪ್ತಿಗೆ ಬಿದ್ದವು (ನಿಜ x0=2.0)?',
        opts: ['Wildly wrong, from -100 to +100', 'Roughly plausible, from 1.943 to 2.414', 'Exactly 2.000 every time', 'Always negative'], correct: 1,
        optsKn: ['ಬಹಳ ತಪ್ಪೂ, -100 ಇಂದ +100', 'ಸರಿಸುಮಾರು ಸಂಭಾವ್ಯ, 1.943 ಇಂದ 2.414', 'ಪ್ರತಿ ಬಾರಿ ನಿಖರವಾಗಿ 2.000', 'ಯಾವಾಗಲೂ ಋಣಾತ್ಮಕ'] },
      { q: 'Why is DDPM training considered more stable than GAN training, based on this lesson\'s framing?', qKn: 'ಈ lesson ನ framing ಆಧಾರದ ಮೇಲೆ, DDPM training GAN training ಗಿಂತ ಹೆಚ್ಚು ಸ್ಥಿರ ಎಂದೂ ಏಕೆ ಪರಿಗಣಿಸಲಾಗಿದೆ?',
        opts: ['It uses two competing networks', 'It is ordinary supervised MSE regression with a known target, not an adversarial minimax game', 'It never has any loss spikes', 'It does not require backpropagation'], correct: 1,
        optsKn: ['ಇದೂ ಎರಡೂ ಸ್ಪರ್ಧಾತ್ಮಕ networks ಬಳಸುತ್ತದೆ', 'ಇದೂ ಒಂದೂ ತಿಳಿದ target ಜೊತೆ ಸಾಮಾನ್ಯ supervised MSE regression, ಒಂದೂ adversarial minimax game ಅಲ್ಲ', 'ಇದೂ ಎಂದಿಗೂ ಯಾವುದೇ loss spikes ಹೊಂದಿಲ್ಲ', 'ಇದಕ್ಕೆ backpropagation ಬೇಕಿಲ್ಲ'] },
      { q: 'What does this lesson\'s honest disclosure of underfitting suggest about interpreting an aggregate training loss curve?', qKn: 'Underfitting ನ ಈ lesson ನ ಪ್ರಾಮಾಣಿಕ ಬಹಿರಂಗಪಡಿಕೆ ಒಂದೂ aggregate training loss curve ಅರ್ಥೈಸುವ ಬಗ್ಗೆ ಏನೂ ಸೂಚಿಸುತ್ತದೆ?',
        opts: ['An aggregate loss curve alone is always sufficient to confirm good learning', 'A noisy-but-not-catastrophic aggregate loss can still hide a model that has not learned to condition on its inputs correctly, as revealed only by per-timestep evaluation', 'Loss curves are never useful', 'Underfitting cannot be diagnosed without a GPU'], correct: 1,
        optsKn: ['ಒಂದೂ aggregate loss curve ಮಾತ್ರ ಉತ್ತಮ learning ದೃಢಪಡಿಸಲು ಯಾವಾಗಲೂ ಸಾಕು', 'ಒಂದೂ ಗದ್ದಲಮಯ-ಆದರೆ-ಘೋರ-ಅಲ್ಲದ aggregate loss ಇನ್ನೂ ತನ್ನ inputs ಮೇಲೆ ಸರಿಯಾಗಿ ಷರತ್ತು ಹಾಕಲು ಕಲಿಯದ ಒಂದೂ model ಅನ್ನೂ ಮರೆಮಾಡಬಹುದು, ಕೇವಲ per-timestep evaluation ಮಾತ್ರ ಬಹಿರಂಗಪಡಿಸುವಂತೆ', 'Loss curves ಎಂದಿಗೂ ಉಪಯುಕ್ತ ಅಲ್ಲ', 'Underfitting ಅನ್ನೂ GPU ಇಲ್ಲದೆ diagnose ಮಾಡಲಾಗುವುದಿಲ್ಲ'] },
    ] } },
  ],
};
