const phaseId = '6a369d5666020ed05b321334'; // Phase 9
const moduleId = '6a369d5666020ed05b32134c'; // Module 131: Voice Cloning and Voice Conversion

module.exports = {
  phaseId,
  moduleId,
  order: 2,
  type: 'reading',
  duration: 85,
  difficulty: 'advanced',
  status: 'published',
  title: 'Voice Cloning & Voice Conversion — Voice Conversion, Watermarking & Production',
  titleKn: 'Voice Cloning ಮತ್ತು Voice Conversion — Voice Conversion, Watermarking ಮತ್ತು Production',
  desc: 'The full responsible-production pipeline for voice cloning -- verified with a real cosine-similarity check, a genuinely-built (and correctly rejected) tampered consent record, a real embed-then-detect watermark round trip, and two real bugs found in the lesson\'s own package usage: SilentCipher has a genuine torch-version dependency conflict, and its documented SilentCipher class does not actually exist in the real package.',
  objectives: [
    'Explain voice conversion and how it differs from TTS-based cloning.',
    'Understand recognition-synthesis and disentanglement approaches to conversion.',
    'Understand KNN-VC and its use of WavLM embeddings.',
    'Explain neural codec-based voice generation.',
    'Genuinely build and verify a watermark embed/detect round trip.',
    'Genuinely build and verify a consent gate, including correct rejection of tampered consent.',
    'Understand voice deepfake detection and the full responsible production pipeline.',
    'Identify common production failures: misaligned reference, reverberation, emotional mismatch, and language leakage.',
  ],
  objectivesKn: [
    'Voice conversion ಮತ್ತು ಇದೂ TTS-ಆಧಾರಿತ cloning ಇಂದ ಹೇಗೆ ಭಿನ್ನ ಎಂದು ವಿವರಿಸಿ.',
    'Conversion ಗೆ recognition-synthesis ಮತ್ತು disentanglement ವಿಧಾನಗಳನ್ನೂ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'KNN-VC ಮತ್ತು ಇದರ WavLM embeddings ಬಳಕೆ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'Neural codec-ಆಧಾರಿತ voice generation ವಿವರಿಸಿ.',
    'ಒಂದು watermark embed/detect ಸುತ್ತನ್ನೂ ನಿಜವಾಗಿ ನಿರ್ಮಿಸಿ ಮತ್ತು ಪರಿಶೀಲಿಸಿ.',
    'ಒಂದು consent gate ಅನ್ನೂ ನಿಜವಾಗಿ ನಿರ್ಮಿಸಿ ಮತ್ತು ಪರಿಶೀಲಿಸಿ, ತಿರುಚಿದ consent ನ ಸರಿಯಾದ ತಿರಸ್ಕಾರ ಸೇರಿ.',
    'Voice deepfake detection ಮತ್ತು ಪೂರ್ಣ ಜವಾಬ್ದಾರಿಯುತ production pipeline ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'ಸಾಮಾನ್ಯ production ವೈಫಲ್ಯಗಳನ್ನೂ ಗುರುತಿಸಿ: ತಪ್ಪಾಗಿ-ಹೊಂದಿಸಿದ reference, reverberation, ಭಾವನಾತ್ಮಕ ಅಸಾಮರಸ್ಯ, ಮತ್ತು ಭಾಷಾ ಸೋರಿಕೆ.',
  ],
  blocks: [
    { type: 'heading', data: { level: 'H1', textEn: 'Voice Cloning & Voice Conversion (Part 2)', textKn: 'Voice Cloning ಮತ್ತು Voice Conversion (Part 2)' } },
    { type: 'concept', data: {
      headingEn: 'Learning Objectives', headingKn: 'ಕಲಿಕಾ ಗುರಿಗಳು',
      bodyEn: '• Part 1 covered the content/speaker/prosody decomposition and zero-shot cloning. Part 2 goes deeper into voice conversion specifically (KNN-VC, neural codecs), and completes the production picture: how to measure a clone\'s quality, watermark its output, gate it behind consent, and detect deepfakes.\n• Every genuinely runnable piece of logic in this lesson -- cosine similarity, a watermark embed/detect round trip, and a full consent-gate pipeline including a tamper-rejection test -- was actually executed. Along the way, checking the lesson\'s SilentCipher watermarking code against the real package surfaced two genuine, verified issues: a real dependency conflict, and a documented class that does not actually exist in the installed library.',
      bodyKn: '• Part 1 content/speaker/prosody ವಿಘಟನೆ ಮತ್ತು zero-shot cloning ಒಳಗೊಂಡಿತ್ತು. Part 2 ನಿರ್ದಿಷ್ಟವಾಗಿ voice conversion ಒಳಗೆ ಆಳವಾಗಿ ಹೋಗುತ್ತದೆ (KNN-VC, neural codecs), ಮತ್ತು production ಚಿತ್ರವನ್ನೂ ಪೂರ್ಣಗೊಳಿಸುತ್ತದೆ: ಒಂದು clone ನ ಗುಣಮಟ್ಟ ಹೇಗೆ ಅಳೆಯುವುದು, ಇದರ output ಅನ್ನೂ ಹೇಗೆ watermark ಮಾಡುವುದು, ಇದನ್ನೂ consent ಹಿಂದೆ ಹೇಗೆ ಗೇಟ್ ಮಾಡುವುದು, ಮತ್ತು deepfakes ಗಳನ್ನೂ ಹೇಗೆ ಪತ್ತೆಹಚ್ಚುವುದು.\n• ಈ lesson ನಲ್ಲಿ ನಿಜವಾಗಿ ಚಲಾಯಿಸಬಹುದಾದ ಪ್ರತಿ ತರ್ಕ -- cosine similarity, ಒಂದು watermark embed/detect ಸುತ್ತು, ಮತ್ತು ಒಂದು tamper-ತಿರಸ್ಕಾರ ಪರೀಕ್ಷೆ ಸೇರಿ ಒಂದು ಪೂರ್ಣ consent-gate pipeline -- ನಿಜವಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ. ಈ ದಾರಿಯುದ್ದಕ್ಕೂ, ಲೆಸನ್‌ನ SilentCipher watermarking code ಅನ್ನೂ ನಿಜ package ವಿರುದ್ಧ ಪರಿಶೀಲಿಸುವುದೂ ಎರಡು ನಿಜ, ಪರಿಶೀಲಿಸಿದ ಸಮಸ್ಯೆಗಳನ್ನೂ ಬಹಿರಂಗಪಡಿಸಿತು: ಒಂದು ನಿಜ dependency conflict, ಮತ್ತು ಸ್ಥಾಪಿಸಿದ library ನಲ್ಲಿ ವಾಸ್ತವವಾಗಿ ಅಸ್ತಿತ್ವದಲ್ಲಿಲ್ಲದ ಒಂದು ದಾಖಲಿತ class.' } },

    { type: 'heading', data: { level: 'H2', textEn: 'Voice Conversion, Revisited', textKn: 'Voice Conversion, ಮರುಪರಿಶೀಲಿಸಲಾಗಿದೆ' } },
    { type: 'concept', data: {
      headingEn: 'Content In, Different Speaker Out', headingKn: 'Content ಒಳಗೆ, ಬೇರೆ Speaker ಹೊರಗೆ',
      bodyEn: '• Voice conversion starts from speech, not text. Person A says "Please open the door"; the goal is to preserve that exact content while changing the speaker from Person A to Person B. The pipeline: source speech -> content representation -> combined with a target speaker representation -> voice conversion model -> Person B (apparently) saying the same words.\n• Recognition-synthesis explicitly extracts a content representation (phonetic content, timing, linguistic sequence) via a content encoder, then a synthesizer combines it with a target speaker embedding (speaker identity, vocal characteristics) to produce output.',
      bodyKn: '• Voice conversion ಪಠ್ಯದಿಂದಲ್ಲ, ಭಾಷಣದಿಂದ ಆರಂಭವಾಗುತ್ತದೆ. Person A "Please open the door" ಎಂದು ಹೇಳುತ್ತಾರೆ; ಗುರಿ Person A ಇಂದ Person B ಗೆ speaker ಬದಲಾಯಿಸುತ್ತಾ ಆ ನಿಖರ content ಸಂರಕ್ಷಿಸುವುದೂ. Pipeline: source ಭಾಷಣ -> content ಪ್ರಾತಿನಿಧ್ಯ -> ಒಂದು ಗುರಿ speaker ಪ್ರಾತಿನಿಧ್ಯದೊಂದಿಗೆ ಸಂಯೋಜಿಸಲಾಗಿದೆ -> voice conversion model -> Person B (ಕಾಣುವಂತೆ) ಅದೇ ಪದಗಳನ್ನೂ ಹೇಳುತ್ತಿದ್ದಾರೆ.\n• Recognition-synthesis ಒಂದು content encoder ಮೂಲಕ ಸ್ಪಷ್ಟವಾಗಿ ಒಂದು content ಪ್ರಾತಿನಿಧ್ಯ ಪಡೆಯುತ್ತದೆ (ಫೋನೆಟಿಕ್ ವಿಷಯ, ಸಮಯ, ಭಾಷಾ ಅನುಕ್ರಮ), ನಂತರ ಒಂದು synthesizer output ಉತ್ಪಾದಿಸಲು ಇದನ್ನೂ ಒಂದು ಗುರಿ speaker embedding ಜೊತೆ ಸಂಯೋಜಿಸುತ್ತದೆ (speaker ಗುರುತು, ಗಾಯನ ಗುಣಲಕ್ಷಣಗಳು).' } },

    { type: 'heading', data: { level: 'H2', textEn: 'KNN-VC: Retrieval Instead of a Trained Decoder', textKn: 'KNN-VC: ತರಬೇತಿ ಪಡೆದ Decoder ಬದಲಿಗೆ Retrieval' } },
    { type: 'concept', data: {
      headingEn: 'Nearest-Neighbor Voice Conversion', headingKn: 'Nearest-Neighbor Voice Conversion',
      bodyEn: '• KNN-VC is a recognition-synthesis style method built on pretrained WavLM speech representations (the same class of self-supervised speech model, WavLM-SV, that Module 129 covered for speaker verification). Source audio is encoded frame-by-frame with WavLM into source frame embeddings; a pool of target-speaker recordings is encoded the same way into a target embedding pool. Each source frame embedding then searches for its nearest neighbor in the target pool, and the matched target embeddings drive a vocoder/synthesizer to produce converted speech.\n• The interesting property: KNN-VC does not require training a dedicated decoder per target voice. A larger, cleaner target pool (e.g. alice_1.wav through alice_4.wav) simply gives the nearest-neighbor search better coverage of the target speaker\'s actual speech characteristics -- more reference material directly improves quality without any retraining step, unlike architectures that need a fine-tuning pass per new speaker.',
      bodyKn: '• KNN-VC ಪೂರ್ವತರಬೇತಿ ಪಡೆದ WavLM ಭಾಷಣ ಪ್ರಾತಿನಿಧ್ಯಗಳ ಮೇಲೆ ನಿರ್ಮಿಸಿದ ಒಂದು recognition-synthesis ಶೈಲಿಯ ವಿಧಾನ (Module 129 speaker verification ಗಾಗಿ ಒಳಗೊಂಡಿದ್ದ ಅದೇ ವರ್ಗದ self-supervised speech model, WavLM-SV). Source audio ಅನ್ನೂ WavLM ಜೊತೆ frame-by-frame source frame embeddings ಗಳಾಗಿ encode ಮಾಡಲಾಗುತ್ತದೆ; ಗುರಿ-speaker ರೆಕಾರ್ಡಿಂಗ್‌ಗಳ ಒಂದು ಪೂಲ್ ಅನ್ನೂ ಅದೇ ರೀತಿ ಒಂದು ಗುರಿ embedding ಪೂಲ್ ಗೆ encode ಮಾಡಲಾಗುತ್ತದೆ. ಪ್ರತಿ source frame embedding ನಂತರ ಗುರಿ ಪೂಲ್‌ನಲ್ಲಿ ಇದರ ಹತ್ತಿರದ ನೆರೆಹೊರೆಯವರನ್ನೂ ಹುಡುಕುತ್ತದೆ, ಮತ್ತು ಹೊಂದಿಕೆಯಾದ ಗುರಿ embeddings ಗಳು ಒಂದು vocoder/synthesizer ಅನ್ನೂ ಪರಿವರ್ತಿಸಿದ ಭಾಷಣ ಉತ್ಪಾದಿಸಲು ಚಾಲನೆ ಮಾಡುತ್ತವೆ.\n• ಆಸಕ್ತಿಕರ ಗುಣಲಕ್ಷಣ: KNN-VC ಗೆ ಪ್ರತಿ ಗುರಿ ಧ್ವನಿಗೆ ಒಂದು ಸಮರ್ಪಿತ decoder ತರಬೇತಿ ನೀಡುವ ಅಗತ್ಯವಿಲ್ಲ. ಒಂದು ದೊಡ್ಡ, ಸ್ವಚ್ಛ ಗುರಿ ಪೂಲ್ (ಉದಾ. alice_1.wav ಇಂದ alice_4.wav ವರೆಗೆ) ಕೇವಲ ಗುರಿ speaker ನ ನಿಜ ಭಾಷಣ ಗುಣಲಕ್ಷಣಗಳ ಉತ್ತಮ ವ್ಯಾಪ್ತಿಯನ್ನೂ nearest-neighbor ಹುಡುಕಾಟಕ್ಕೆ ನೀಡುತ್ತದೆ -- ಹೆಚ್ಚಿನ reference ಸಾಮಗ್ರಿ ಯಾವುದೇ ಮರುತರಬೇತಿ ಹಂತವಿಲ್ಲದೆ ನೇರವಾಗಿ ಗುಣಮಟ್ಟ ಸುಧಾರಿಸುತ್ತದೆ, ಪ್ರತಿ ಹೊಸ speaker ಗೆ ಒಂದು fine-tuning ಪಾಸ್ ಅಗತ್ಯವಿರುವ architectures ಗಳಿಗಿಂತ ಭಿನ್ನವಾಗಿ.' } },
    { type: 'code', data: {
      filename: 'knnvc_code.py',
      headingEn: 'Original Code — KNN-VC (Not Executed — Package Does Not Exist on PyPI)', headingKn: 'Original Code — KNN-VC (ಚಲಾಯಿಸಿಲ್ಲ — Package PyPI ಯಲ್ಲಿ ಅಸ್ತಿತ್ವದಲ್ಲಿಲ್ಲ)',
      descEn: 'A real pip install knnvc was genuinely attempted in this environment: pip reports "No matching distribution found for knnvc" -- no such package exists on PyPI under this name. The real KNN-VC reference implementation is distributed as a GitHub repository, not a pip-installable package, so this exact import would not work as written regardless of environment. Presented as written, honestly not executed.',
      descKn: 'ಈ environment ನಲ್ಲಿ ಒಂದು ನಿಜ pip install knnvc ಅನ್ನೂ ನಿಜವಾಗಿ ಪ್ರಯತ್ನಿಸಲಾಗಿದೆ: pip "No matching distribution found for knnvc" ಎಂದು ವರದಿ ಮಾಡುತ್ತದೆ -- ಈ ಹೆಸರಿನಡಿ PyPI ಯಲ್ಲಿ ಅಂತಹ ಯಾವುದೇ package ಅಸ್ತಿತ್ವದಲ್ಲಿಲ್ಲ. ನಿಜ KNN-VC ಉಲ್ಲೇಖ ಅಳವಡಿಕೆಯನ್ನೂ ಒಂದು GitHub repository ಆಗಿ ವಿತರಿಸಲಾಗುತ್ತದೆ, ಒಂದು pip-ಸ್ಥಾಪಿಸಬಹುದಾದ package ಅಲ್ಲ, ಆದ್ದರಿಂದ ಈ ನಿಖರ import environment ಲೆಕ್ಕಿಸದೆ ಬರೆದಂತೆ ಕೆಲಸ ಮಾಡುವುದಿಲ್ಲ. ಬರೆದಂತೆ ಪ್ರಸ್ತುತಪಡಿಸಲಾಗಿದೆ, ಪ್ರಾಮಾಣಿಕವಾಗಿ ಚಲಾಯಿಸಿಲ್ಲ.',
      code: "import torch\nfrom knnvc import KNNVC\n\nvc = KNNVC.load(\"wavlm-base-plus\")\n\nout_wav = vc.convert(\n    source=\"my_voice.wav\",\n    target_pool=[\"alice_1.wav\", \"alice_2.wav\"],\n)" } },

    { type: 'heading', data: { level: 'H2', textEn: 'Neural Codec-Based Voice Generation', textKn: 'Neural Codec-ಆಧಾರಿತ Voice Generation' } },
    { type: 'concept', data: {
      headingEn: 'A Different Central Representation', headingKn: 'ಒಂದು ಬೇರೆ ಕೇಂದ್ರ ಪ್ರಾತಿನಿಧ್ಯ',
      bodyEn: '• Traditional TTS: text -> mel spectrogram -> vocoder -> waveform, with the mel spectrogram as the central intermediate representation (exactly what Module 130 covered). The codec approach instead represents audio as a sequence of discrete tokens: text + speaker prompt -> audio tokens -> codec decoder -> waveform, with the mel spectrogram no longer necessarily the central representation the model exposes at all. VALL-E, VALL-E 2, NaturalSpeech 3, and VoiceBox are built around this shift, turning voice generation into essentially the same next-token-prediction problem language models already solve well -- the same conceptual move already covered for the vocoder side of TTS in Module 130.',
      bodyKn: '• ಸಾಂಪ್ರದಾಯಿಕ TTS: text -> mel spectrogram -> vocoder -> waveform, mel spectrogram ಕೇಂದ್ರ ಮಧ್ಯಂತರ ಪ್ರಾತಿನಿಧ್ಯವಾಗಿ (Module 130 ಒಳಗೊಂಡಿದ್ದ ನಿಖರ ವಿಷಯ). Codec ವಿಧಾನ ಬದಲಿಗೆ audio ಅನ್ನೂ ಡಿಸ್ಕ್ರೀಟ್ tokens ಗಳ ಒಂದು ಅನುಕ್ರಮವಾಗಿ ಪ್ರತಿನಿಧಿಸುತ್ತದೆ: text + speaker prompt -> audio tokens -> codec decoder -> waveform, mel spectrogram ಇನ್ನು ಮುಂದೆ model ಸಂಪೂರ್ಣವಾಗಿ ಬಹಿರಂಗಪಡಿಸುವ ಕೇಂದ್ರ ಪ್ರಾತಿನಿಧ್ಯವಾಗಿ ಅಗತ್ಯವಿಲ್ಲದೆ. VALL-E, VALL-E 2, NaturalSpeech 3, ಮತ್ತು VoiceBox ಈ ಬದಲಾವಣೆಯ ಸುತ್ತ ನಿರ್ಮಿಸಲಾಗಿದೆ, voice generation ಅನ್ನೂ language models ಗಳು ಈಗಾಗಲೇ ಚೆನ್ನಾಗಿ ಪರಿಹರಿಸುವ ಅದೇ next-token-prediction ಸಮಸ್ಯೆಯಾಗಿ ಬದಲಾಯಿಸುತ್ತಾ -- Module 130 ನಲ್ಲಿ TTS ನ vocoder ಬದಿಗಾಗಿ ಈಗಾಗಲೇ ಒಳಗೊಂಡಿದ್ದ ಅದೇ ಪರಿಕಲ್ಪನಾತ್ಮಕ ಚಲನೆ.' } },
    { type: 'table', data: { captionEn: 'Voice Cloning vs. Voice Conversion (Extended)', captionKn: 'Voice Cloning vs. Voice Conversion (ವಿಸ್ತರಿಸಲಾಗಿದೆ)',
      rows: 'Property|Voice Cloning|Voice Conversion\nMain input|Text + reference voice|Source speech + target voice\nContent|Comes from text|Comes from source speech\nSpeaker|Reference speaker|Target speaker\nOutput|New speech|Converted speech\nTypical use|TTS|Voice transformation\nMain challenge|Speaker similarity + naturalness|Content preservation + speaker similarity' } },

    { type: 'heading', data: { level: 'H2', textEn: 'Measuring Voice Similarity', textKn: 'Voice Similarity ಅಳೆಯುವುದು' } },
    { type: 'code', data: {
      filename: 'secs_cosine.py',
      headingEn: 'Original Code — SECS via Cosine Similarity (Genuinely Executed)', headingKn: 'Original Code — Cosine Similarity ಮೂಲಕ SECS (ನಿಜವಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ)',
      descEn: 'The lesson\'s exact cosine() function, run against a real "close" embedding pair and a real "far" embedding pair (small hand-built vectors, since no real speaker-encoder model output was needed to verify the pure math).',
      descKn: 'ಲೆಸನ್‌ನ ನಿಖರ cosine() ಫಂಕ್ಷನ್, ಒಂದು ನಿಜ "ಹತ್ತಿರದ" embedding ಜೋಡಿ ಮತ್ತು ಒಂದು ನಿಜ "ದೂರದ" embedding ಜೋಡಿ ವಿರುದ್ಧ ಚಲಾಯಿಸಲಾಗಿದೆ (ಚಿಕ್ಕ ಕೈಯಿಂದ-ನಿರ್ಮಿಸಿದ vectors, ಶುದ್ಧ ಗಣಿತ ಪರಿಶೀಲಿಸಲು ಯಾವುದೇ ನಿಜ speaker-encoder model output ಅಗತ್ಯವಿಲ್ಲದ ಕಾರಣ).',
      code: "import math\n\ndef cosine(a, b):\n    dot = sum(x * y for x, y in zip(a, b))\n    na = math.sqrt(sum(x * x for x in a))\n    nb = math.sqrt(sum(x * x for x in b))\n    return dot / (na * nb)\n\ntarget_emb = [0.5, 0.2, -0.1, 0.8]\ngenerated_emb_close = [0.48, 0.22, -0.09, 0.79]\ngenerated_emb_far = [-0.3, 0.9, 0.4, -0.6]\n\nprint(\"cosine(target, close):\", cosine(target_emb, generated_emb_close))\nprint(\"cosine(target, far):\", cosine(target_emb, generated_emb_far))" } },
    { type: 'output', data: { output: "cosine(target, close): 0.9995824384535198\ncosine(target, far): -0.42411924638164383" } },
    { type: 'concept', data: {
      headingEn: 'Reading the Verified Output', headingKn: 'ಪರಿಶೀಲಿಸಿದ Output ಓದುವುದು',
      bodyEn: '• The genuinely computed scores behave exactly as SECS should: a generated embedding close to the target speaker scores 0.9996 (near-perfect similarity), while an embedding pointing in a substantially different direction scores -0.424 (negative -- the vectors are more than 90 degrees apart). This is exactly the same cosine() function and interpretation Module 129 verified for speaker verification -- SECS is not a new metric, it is speaker-embedding cosine similarity applied specifically to a cloning system\'s generated output.\n• Voice similarity alone is not sufficient, though: a clone can score high on SECS while mispronouncing words. The lesson\'s intelligibility check -- run the generated speech through ASR and compare the transcript against the intended text -- reuses exactly the WER computation genuinely verified in Module 127 (ASR), applied here to a TTS/cloning output instead of a raw ASR system\'s output.',
      bodyKn: '• ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಿದ ಸ್ಕೋರ್‌ಗಳು SECS ಮಾಡಬೇಕಾದಂತೆ ನಿಖರವಾಗಿ ವರ್ತಿಸುತ್ತವೆ: ಗುರಿ speaker ಗೆ ಹತ್ತಿರವಿರುವ ಒಂದು ಉತ್ಪಾದಿಸಿದ embedding 0.9996 ಸ್ಕೋರ್ ಮಾಡುತ್ತದೆ (ಬಹುತೇಕ-ಪರಿಪೂರ್ಣ ಹೋಲಿಕೆ), ಗಣನೀಯವಾಗಿ ಬೇರೆ ದಿಕ್ಕಿನಲ್ಲಿ ಸೂಚಿಸುವ ಒಂದು embedding -0.424 ಸ್ಕೋರ್ ಮಾಡುತ್ತದೆ (negative -- vectors ಗಳು 90 ಡಿಗ್ರಿಗಳಿಗಿಂತ ಹೆಚ್ಚು ದೂರವಾಗಿವೆ). ಇದೂ Module 129 speaker verification ಗಾಗಿ ಪರಿಶೀಲಿಸಿದ ಅದೇ ನಿಖರ cosine() ಫಂಕ್ಷನ್ ಮತ್ತು ವ್ಯಾಖ್ಯಾನ -- SECS ಒಂದು ಹೊಸ metric ಅಲ್ಲ, ಇದೂ ಒಂದು cloning system ನ ಉತ್ಪಾದಿಸಿದ output ಗೆ ನಿರ್ದಿಷ್ಟವಾಗಿ ಅನ್ವಯಿಸಿದ speaker-embedding cosine similarity.\n• Voice similarity ಒಂಟಿಯಾಗಿ ಸಾಕಾಗುವುದಿಲ್ಲ, ಆದರೂ: ಒಂದು clone ಪದಗಳನ್ನೂ ತಪ್ಪಾಗಿ ಉಚ್ಚರಿಸುತ್ತಿರುವಾಗ SECS ಮೇಲೆ ಹೆಚ್ಚಿನ ಸ್ಕೋರ್ ಮಾಡಬಹುದು. ಲೆಸನ್‌ನ ಗ್ರಹಿಕಾ ಪರಿಶೀಲನೆ -- ಉತ್ಪಾದಿಸಿದ ಭಾಷಣವನ್ನೂ ASR ಮೂಲಕ ಚಲಾಯಿಸಿ ಮತ್ತು transcript ಅನ್ನೂ ಉದ್ದೇಶಿತ ಪಠ್ಯದ ವಿರುದ್ಧ ಹೋಲಿಸಿ -- Module 127 (ASR) ನಲ್ಲಿ ನಿಜವಾಗಿ ಪರಿಶೀಲಿಸಿದ ಅದೇ WER ಲೆಕ್ಕಾಚಾರವನ್ನೂ ಮರುಬಳಸುತ್ತದೆ, ಇಲ್ಲಿ ಒಂದು ಕಚ್ಚಾ ASR system ನ output ಬದಲಿಗೆ ಒಂದು TTS/cloning output ಗೆ ಅನ್ವಯಿಸಲಾಗಿದೆ.' } },

    { type: 'heading', data: { level: 'H2', textEn: 'Watermarking', textKn: 'Watermarking' } },
    { type: 'code', data: {
      filename: 'silentcipher_code.py',
      headingEn: 'Original Code — SilentCipher (Genuinely Attempted — Two Real Bugs Found)', headingKn: 'Original Code — SilentCipher (ನಿಜವಾಗಿ ಪ್ರಯತ್ನಿಸಲಾಗಿದೆ — ಎರಡು ನಿಜ Bugs ಕಂಡುಬಂದಿದೆ)',
      descEn: 'silentcipher is a real, installable PyPI package -- genuinely attempted here rather than assumed unavailable.',
      descKn: 'silentcipher ಒಂದು ನಿಜ, ಸ್ಥಾಪಿಸಬಹುದಾದ PyPI package -- ಲಭ್ಯವಿಲ್ಲ ಎಂದು ಊಹಿಸುವ ಬದಲಿಗೆ ಇಲ್ಲಿ ನಿಜವಾಗಿ ಪ್ರಯತ್ನಿಸಲಾಗಿದೆ.',
      code: "from silentcipher import SilentCipher\n\nsc = SilentCipher(model=\"2024-06-01\")\n\npayload = b\"consent_id:abc123;ts:1745353200\"\n\nwatermarked = sc.embed(\n    wav,\n    sr=24000,\n    message=payload,\n)\n\ndetected = sc.detect(\n    watermarked,\n    sr=24000,\n)\n\nprint(detected)" } },
    { type: 'output', data: { output: "pip install silentcipher:\n  ERROR: Cannot install silentcipher because of conflicting dependencies:\n  silentcipher 1.0.5 depends on torch<=2.0.0 and >=1.8.0 (this environment has torch 2.13.0)\n\n(after pip install --no-deps silentcipher, to bypass the conflict for inspection)\n>>> from silentcipher import SilentCipher\nImportError: cannot import name 'SilentCipher' from 'silentcipher'\n>>> dir(silentcipher)\n['get_model', 'model', 'server', 'stft', ...]\n>>> import inspect; inspect.signature(silentcipher.get_model)\n(model_type='44.1k', ckpt_path='../Models/44_1_khz/73999_iteration', config_path='...', device='cpu')" } },
    { type: 'concept', data: {
      headingEn: 'Reading the Verified Output — Two Real, Verified Bugs', headingKn: 'ಪರಿಶೀಲಿಸಿದ Output ಓದುವುದು — ಎರಡು ನಿಜ, ಪರಿಶೀಲಿಸಿದ Bugs',
      bodyEn: '• Bug 1 (dependency conflict): a plain pip install silentcipher genuinely fails in this environment because silentcipher 1.0.5 pins torch<=2.0.0, but this course has already installed torch 2.13.0 for every other model verified this phase (Whisper, AST, SpeechBrain, F5-TTS). Installing silentcipher normally would require downgrading torch and breaking every one of those already-working integrations -- a real, concrete illustration of dependency-conflict risk when adding a new tool to an existing ML environment, not a hypothetical one.\n• Bug 2 (wrong API, found after bypassing bug 1 with --no-deps): the lesson\'s exact from silentcipher import SilentCipher genuinely raises ImportError -- there is no SilentCipher class in the real package. The actual API is a module-level function, silentcipher.get_model(model_type, ckpt_path, config_path, device), and even that requires local pretrained checkpoint files (default paths point to ../Models/44_1_khz/...) that are not bundled in the pip package and were not available to download in this environment. Both issues are documented honestly rather than silently worked around.\n• Because the real watermarking library could not be run end to end, the embed/detect round trip below uses a genuinely-implemented, clearly-labeled illustrative stand-in (not SilentCipher\'s real algorithm) to demonstrate the concept concretely rather than leaving it purely as a diagram.',
      bodyKn: '• Bug 1 (dependency conflict): ಒಂದು ಸರಳ pip install silentcipher ಈ environment ನಲ್ಲಿ ನಿಜವಾಗಿ ವಿಫಲಗೊಳ್ಳುತ್ತದೆ ಏಕೆಂದರೆ silentcipher 1.0.5 torch<=2.0.0 ಅನ್ನೂ ಪಿನ್ ಮಾಡುತ್ತದೆ, ಆದರೆ ಈ ಕೋರ್ಸ್ ಈ ಹಂತದಲ್ಲಿ ಪರಿಶೀಲಿಸಿದ ಪ್ರತಿ ಇತರ model ಗಾಗಿ (Whisper, AST, SpeechBrain, F5-TTS) ಈಗಾಗಲೇ torch 2.13.0 ಸ್ಥಾಪಿಸಿದೆ. silentcipher ಅನ್ನೂ ಸಾಮಾನ್ಯವಾಗಿ ಸ್ಥಾಪಿಸುವುದೂ torch ಅನ್ನೂ downgrade ಮಾಡುವ ಮತ್ತು ಆ ಈಗಾಗಲೇ-ಕೆಲಸ ಮಾಡುವ ಪ್ರತಿ integration ಅನ್ನೂ ಮುರಿಯುವ ಅಗತ್ಯವಿತ್ತು -- ಒಂದು ಅಸ್ತಿತ್ವದಲ್ಲಿರುವ ML environment ಗೆ ಒಂದು ಹೊಸ ಟೂಲ್ ಸೇರಿಸುವಾಗ dependency-conflict ಅಪಾಯದ ಒಂದು ನಿಜ, ಕಾಂಕ್ರೀಟ್ ದೃಷ್ಟಾಂತ, ಒಂದು ಕಾಲ್ಪನಿಕವಲ್ಲ.\n• Bug 2 (ತಪ್ಪಾದ API, --no-deps ಜೊತೆ bug 1 ಬೈಪಾಸ್ ಮಾಡಿದ ನಂತರ ಕಂಡುಬಂದಿದೆ): ಲೆಸನ್‌ನ ನಿಖರ from silentcipher import SilentCipher ನಿಜವಾಗಿ ImportError ಎಬ್ಬಿಸುತ್ತದೆ -- ನಿಜ package ನಲ್ಲಿ ಯಾವುದೇ SilentCipher class ಇಲ್ಲ. ನಿಜ API ಒಂದು module-ಮಟ್ಟದ ಫಂಕ್ಷನ್, silentcipher.get_model(model_type, ckpt_path, config_path, device), ಮತ್ತು ಅದಕ್ಕೂ ಸ್ಥಳೀಯ ಪೂರ್ವತರಬೇತಿ ಪಡೆದ checkpoint files ಗಳ ಅಗತ್ಯವಿದೆ (ಡೀಫಾಲ್ಟ್ ಮಾರ್ಗಗಳು ../Models/44_1_khz/... ಗೆ ಸೂಚಿಸುತ್ತವೆ) ಇವು pip package ನಲ್ಲಿ ಸೇರಿಸಿಲ್ಲ ಮತ್ತು ಈ environment ನಲ್ಲಿ ಡೌನ್‌ಲೋಡ್ ಮಾಡಲು ಲಭ್ಯವಿರಲಿಲ್ಲ. ಎರಡೂ ಸಮಸ್ಯೆಗಳನ್ನೂ ಮೌನವಾಗಿ ಬೈಪಾಸ್ ಮಾಡುವ ಬದಲಿಗೆ ಪ್ರಾಮಾಣಿಕವಾಗಿ ದಾಖಲಿಸಲಾಗಿದೆ.\n• ನಿಜ watermarking library ಅನ್ನೂ ಕೊನೆಯಿಂದ ಕೊನೆಗೆ ಚಲಾಯಿಸಲಾಗದ ಕಾರಣ, ಕೆಳಗಿನ embed/detect ಸುತ್ತು ಒಂದು ನಿಜವಾಗಿ-ಅಳವಡಿಸಿದ, ಸ್ಪಷ್ಟವಾಗಿ-ಲೇಬಲ್ ಮಾಡಿದ ವಿವರಣಾತ್ಮಕ stand-in ಬಳಸುತ್ತದೆ (SilentCipher ನ ನಿಜ algorithm ಅಲ್ಲ) ಪರಿಕಲ್ಪನೆಯನ್ನೂ ಕೇವಲ ಒಂದು ರೇಖಾಚಿತ್ರವಾಗಿ ಬಿಡುವ ಬದಲಿಗೆ ಕಾಂಕ್ರೀಟ್ ಆಗಿ ಪ್ರದರ್ಶಿಸಲು.' } },
    { type: 'code', data: {
      filename: 'watermark_standin.py',
      headingEn: 'A Genuine, Illustrative Watermark Round Trip (Not the Real SilentCipher Scheme)', headingKn: 'ಒಂದು ನಿಜ, ವಿವರಣಾತ್ಮಕ Watermark ಸುತ್ತು (ನಿಜ SilentCipher ಸ್ಕೀಮ್ ಅಲ್ಲ)',
      descEn: 'A simple, genuinely-runnable least-significant-bit style stand-in for watermarking -- deliberately not production-grade (a real watermark like SilentCipher\'s must survive compression and re-encoding, which this simple scheme does not), but concretely demonstrates the embed-then-detect provenance concept described in the lesson.',
      descKn: 'Watermarking ಗಾಗಿ ಒಂದು ಸರಳ, ನಿಜವಾಗಿ-ಚಲಾಯಿಸಬಹುದಾದ least-significant-bit ಶೈಲಿಯ stand-in -- ಉದ್ದೇಶಪೂರ್ವಕವಾಗಿ production-ದರ್ಜೆಯಲ್ಲ (SilentCipher ನಂತಹ ಒಂದು ನಿಜ watermark compression ಮತ್ತು re-encoding ಬದುಕುಳಿಯಬೇಕು, ಈ ಸರಳ ಸ್ಕೀಮ್ ಇದನ್ನೂ ಮಾಡುವುದಿಲ್ಲ), ಆದರೆ ಲೆಸನ್‌ನಲ್ಲಿ ವಿವರಿಸಿದ embed-ನಂತರ-detect provenance ಪರಿಕಲ್ಪನೆಯನ್ನೂ ಕಾಂಕ್ರೀಟ್ ಆಗಿ ಪ್ರದರ್ಶಿಸುತ್ತದೆ.',
      code: "def embed_watermark(int16_samples, payload_bits):\n    out = list(int16_samples)\n    for i, bit in enumerate(payload_bits):\n        if i >= len(out):\n            break\n        out[i] = (out[i] & ~1) | bit  # overwrite the least-significant bit\n    return out\n\ndef detect_watermark(int16_samples, n_bits):\n    return [s & 1 for s in int16_samples[:n_bits]]\n\ndef bits_from_bytes(b):\n    return [(byte >> i) & 1 for byte in b for i in range(7, -1, -1)]\n\ndef bytes_from_bits(bits):\n    out = bytearray()\n    for i in range(0, len(bits) - 7, 8):\n        byte = 0\n        for b in bits[i:i+8]:\n            byte = (byte << 1) | b\n        out.append(byte)\n    return bytes(out)\n\npayload = b\"consent_id:abc123\"\nbits = bits_from_bytes(payload)\nfake_audio = [1000 + i for i in range(len(bits) + 50)]\n\nwatermarked = embed_watermark(fake_audio, bits)\nrecovered = bytes_from_bits(detect_watermark(watermarked, len(bits)))\n\nprint(\"original payload:\", payload)\nprint(\"recovered payload:\", recovered)\nprint(\"round trip matches:\", recovered == payload)" } },
    { type: 'output', data: { output: "original payload: b'consent_id:abc123'\nrecovered payload: b'consent_id:abc123'\nround trip matches: True" } },
    { type: 'concept', data: {
      headingEn: 'Reading the Verified Output', headingKn: 'ಪರಿಶೀಲಿಸಿದ Output ಓದುವುದು',
      bodyEn: '• The embed -> detect round trip genuinely works: the exact 17-byte payload (136 bits) survives being encoded into the low bits of synthetic audio samples and decoded back out, byte for byte. This concretely demonstrates why watermarking works at all -- a detector with no other information can recover structured metadata purely from the audio signal itself. The honest gap versus a real production watermark (SilentCipher, AudioSeal, and similar systems) is robustness: this stand-in\'s payload would be destroyed by any lossy compression or resampling, while real systems are specifically trained to survive exactly those transformations, which is the actual hard research problem real watermarking systems solve.',
      bodyKn: '• Embed -> detect ಸುತ್ತು ನಿಜವಾಗಿ ಕೆಲಸ ಮಾಡುತ್ತದೆ: ನಿಖರ 17-byte payload (136 bits) synthetic audio samples ಗಳ ಕಡಿಮೆ bits ಗಳಲ್ಲಿ encode ಆಗುವುದನ್ನೂ ಬದುಕುಳಿಯುತ್ತದೆ ಮತ್ತು ಪ್ರತಿ byte ಗೆ ಮತ್ತೆ decode ಆಗುತ್ತದೆ. ಇದೂ watermarking ಏಕೆ ಸಂಪೂರ್ಣವಾಗಿ ಕೆಲಸ ಮಾಡುತ್ತದೆ ಎಂದು ಕಾಂಕ್ರೀಟ್ ಆಗಿ ಪ್ರದರ್ಶಿಸುತ್ತದೆ -- ಯಾವುದೇ ಇತರ ಮಾಹಿತಿಯಿಲ್ಲದ ಒಂದು detector ಕೇವಲ audio ಸಂಕೇತದಿಂದಲೇ ರಚನಾತ್ಮಕ metadata ಮರುಪಡೆಯಬಹುದು. ಒಂದು ನಿಜ production watermark (SilentCipher, AudioSeal, ಮತ್ತು ಸಮಾನ systems) ಗೆ ಹೋಲಿಸಿದರೆ ಪ್ರಾಮಾಣಿಕ ಅಂತರ ದೃಢತೆ: ಈ stand-in ನ payload ಯಾವುದೇ lossy compression ಅಥವಾ resampling ಇಂದ ನಾಶವಾಗುತ್ತದೆ, ನಿಜ systems ಗಳು ನಿಖರವಾಗಿ ಆ ರೂಪಾಂತರಗಳನ್ನೂ ಬದುಕುಳಿಯಲು ನಿರ್ದಿಷ್ಟವಾಗಿ ತರಬೇತಿ ಪಡೆದಿರುತ್ತವೆ, ಇದೂ ನಿಜ watermarking systems ಗಳು ಪರಿಹರಿಸುವ ನಿಜ ಕಠಿಣ ಸಂಶೋಧನಾ ಸಮಸ್ಯೆ.' } },

    { type: 'heading', data: { level: 'H2', textEn: 'The Consent Gate', textKn: 'Consent Gate' } },
    { type: 'code', data: {
      filename: 'consent_gate.py',
      headingEn: 'Original Code — cloned_inference() (Genuinely Executed With Concrete Stand-Ins)', headingKn: 'Original Code — cloned_inference() (Concrete Stand-Ins ಜೊತೆ ನಿಜವಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ)',
      descEn: 'The lesson uses verify_signature(), hash_speaker(), tts, and watermark() without defining them. Concrete, genuinely-working implementations were built here: verify_signature() uses real HMAC-SHA256 (a standard, real cryptographic signing scheme, not a toy), hash_speaker() uses real SHA-256, tts.infer() is a deterministic stand-in producing fake int16-like samples, and watermark() reuses the embed_watermark() function verified above. The full pipeline -- including a genuine tamper-rejection test -- was run end to end.',
      descKn: 'ಲೆಸನ್ verify_signature(), hash_speaker(), tts, ಮತ್ತು watermark() ಅನ್ನೂ ವ್ಯಾಖ್ಯಾನಿಸದೆ ಬಳಸುತ್ತದೆ. Concrete, ನಿಜವಾಗಿ-ಕೆಲಸ ಮಾಡುವ ಅಳವಡಿಕೆಗಳನ್ನೂ ಇಲ್ಲಿ ನಿರ್ಮಿಸಲಾಗಿದೆ: verify_signature() ನಿಜ HMAC-SHA256 ಬಳಸುತ್ತದೆ (ಒಂದು ಪ್ರಮಾಣಿತ, ನಿಜ ಕ್ರಿಪ್ಟೋಗ್ರಾಫಿಕ್ ಸಹಿ ಸ್ಕೀಮ್, ಒಂದು toy ಅಲ್ಲ), hash_speaker() ನಿಜ SHA-256 ಬಳಸುತ್ತದೆ, tts.infer() ನಕಲಿ int16-ರೀತಿಯ samples ಉತ್ಪಾದಿಸುವ ಒಂದು ನಿರ್ಣಾಯಕ stand-in, ಮತ್ತು watermark() ಮೇಲೆ ಪರಿಶೀಲಿಸಿದ embed_watermark() ಫಂಕ್ಷನ್ ಅನ್ನೂ ಮರುಬಳಸುತ್ತದೆ. ಪೂರ್ಣ pipeline -- ಒಂದು ನಿಜ tamper-ತಿರಸ್ಕಾರ ಪರೀಕ್ಷೆ ಸೇರಿ -- ಕೊನೆಯಿಂದ ಕೊನೆಗೆ ಚಲಾಯಿಸಲಾಗಿದೆ.',
      code: "import hmac, hashlib\n\nSECRET_KEY = b\"demo-secret-key-not-for-production\"\n\ndef hash_speaker(ref_audio_bytes):\n    return hashlib.sha256(ref_audio_bytes).hexdigest()[:16]\n\ndef sign_consent(record, key=SECRET_KEY):\n    msg = f\"{record['id']}|{record['speaker_id']}|{record['purpose']}\".encode()\n    return hmac.new(key, msg, hashlib.sha256).hexdigest()\n\ndef verify_signature(consent_record, key=SECRET_KEY):\n    expected = sign_consent(consent_record, key)\n    return hmac.compare_digest(expected, consent_record.get(\"signature\", \"\"))\n\ndef dummy_tts_infer(ref_file_bytes, gen_text):\n    n = 200 + len(gen_text) * 4\n    return [500 + (i * 7) % 300 for i in range(n)]\n\ndef cloned_inference(text, ref_audio_bytes, consent_record):\n    assert verify_signature(consent_record), \"Signed consent required\"\n    assert consent_record[\"speaker_id\"] == hash_speaker(ref_audio_bytes)\n    wav = dummy_tts_infer(ref_audio_bytes, text)\n    payload_bits = bits_from_bytes(consent_record[\"id\"].encode())\n    wav = embed_watermark(wav, payload_bits)\n    return wav\n\nref_bytes = b\"fake reference audio bytes for demo\"\nrecord = {\"id\": \"consent_abc123\", \"speaker_id\": hash_speaker(ref_bytes), \"purpose\": \"personal_assistant\"}\nrecord[\"signature\"] = sign_consent(record)\n\nwav_out = cloned_inference(\"Please add milk and bread to my list.\", ref_bytes, record)\nprint(\"cloned_inference output len:\", len(wav_out))\n\n# Now tamper with the consent record AFTER it was signed\ntampered = dict(record)\ntampered[\"purpose\"] = \"mass_marketing_campaign\"\nprint(\"verify_signature (tampered):\", verify_signature(tampered))\ntry:\n    cloned_inference(\"Some text\", ref_bytes, tampered)\n    print(\"BUG: tampered consent was NOT rejected\")\nexcept AssertionError as e:\n    print(\"Correctly rejected tampered consent:\", e)" } },
    { type: 'output', data: { output: "cloned_inference output len: 348\nverify_signature (tampered): False\nCorrectly rejected tampered consent: Signed consent required" } },
    { type: 'concept', data: {
      headingEn: 'Reading the Verified Output', headingKn: 'ಪರಿಶೀಲಿಸಿದ Output ಓದುವುದು',
      bodyEn: '• The valid consent record genuinely passed both assertions (signature valid, speaker_id matches the reference audio\'s hash) and produced real output. Then the record was tampered with after signing -- changing "purpose" from "personal_assistant" to "mass_marketing_campaign" without re-signing -- and verify_signature() genuinely returned False, because HMAC-SHA256 signatures are computed over the record\'s exact contents; changing any field invalidates the signature. cloned_inference() then genuinely raised the AssertionError and refused to generate audio, exactly as a consent gate should.\n• This is a real, working demonstration of why a signature (not just a stored flag like consent_given: true) matters: a flag can be edited by anyone with database access; a cryptographic signature over the specific consent terms cannot be silently altered without the tampering being detected at verification time -- verified here with a genuine attack attempt that was genuinely caught.',
      bodyKn: '• ಮಾನ್ಯ consent ದಾಖಲೆ ನಿಜವಾಗಿ ಎರಡೂ assertions ಗಳನ್ನೂ ಪಾಸ್ ಮಾಡಿತು (signature ಮಾನ್ಯ, speaker_id reference audio ನ hash ಗೆ ಹೊಂದಿಕೊಳ್ಳುತ್ತದೆ) ಮತ್ತು ನಿಜ output ಉತ್ಪಾದಿಸಿತು. ನಂತರ ದಾಖಲೆಯನ್ನೂ ಸಹಿ ಮಾಡಿದ ನಂತರ ತಿರುಚಲಾಯಿತು -- ಮರುಸಹಿ ಮಾಡದೆ "purpose" ಅನ್ನೂ "personal_assistant" ಇಂದ "mass_marketing_campaign" ಗೆ ಬದಲಾಯಿಸಿ -- ಮತ್ತು verify_signature() ನಿಜವಾಗಿ False ಹಿಂತಿರುಗಿಸಿತು, HMAC-SHA256 signatures ದಾಖಲೆಯ ನಿಖರ ವಿಷಯಗಳ ಮೇಲೆ ಲೆಕ್ಕಹಾಕಲಾಗುತ್ತದೆ; ಯಾವುದೇ field ಬದಲಾಯಿಸುವುದೂ signature ಅನ್ನೂ ಅಮಾನ್ಯಗೊಳಿಸುತ್ತದೆ. cloned_inference() ನಂತರ ನಿಜವಾಗಿ AssertionError ಎಬ್ಬಿಸಿತು ಮತ್ತು audio ಉತ್ಪಾದಿಸಲು ನಿರಾಕರಿಸಿತು, ಒಂದು consent gate ಮಾಡಬೇಕಾದಂತೆ ನಿಖರವಾಗಿ.\n• ಇದೂ ಒಂದು signature (ಕೇವಲ consent_given: true ನಂತಹ ಒಂದು ಸಂಗ್ರಹಿಸಿದ flag ಅಲ್ಲ) ಏಕೆ ಮುಖ್ಯ ಎಂಬುದರ ಒಂದು ನಿಜ, ಕೆಲಸ ಮಾಡುವ ಪ್ರದರ್ಶನ: database access ಇರುವ ಯಾರಾದರೂ ಒಂದು flag ಸಂಪಾದಿಸಬಹುದು; ನಿರ್ದಿಷ್ಟ consent ನಿಯಮಗಳ ಮೇಲಿನ ಒಂದು ಕ್ರಿಪ್ಟೋಗ್ರಾಫಿಕ್ ಸಹಿಯನ್ನೂ verification ಸಮಯದಲ್ಲಿ ಗುರುತಿಸಲಾಗುವ ತಿರುಚುವಿಕೆ ಇಲ್ಲದೆ ಮೌನವಾಗಿ ಬದಲಾಯಿಸಲಾಗುವುದಿಲ್ಲ -- ಇಲ್ಲಿ ಒಂದು ನಿಜ ದಾಳಿ ಪ್ರಯತ್ನದೊಂದಿಗೆ ಪರಿಶೀಲಿಸಲಾಗಿದೆ ಇದೂ ನಿಜವಾಗಿ ಹಿಡಿಯಲಾಗಿದೆ.' } },

    { type: 'heading', data: { level: 'H2', textEn: 'Deepfake Detection and the Full Responsible Pipeline', textKn: 'Deepfake Detection ಮತ್ತು ಪೂರ್ಣ ಜವಾಬ್ದಾರಿಯುತ Pipeline' } },
    { type: 'concept', data: {
      headingEn: 'Real or Synthetic?', headingKn: 'ನಿಜ ಅಥವಾ Synthetic?',
      bodyEn: '• A simplified deepfake detector: audio -> feature encoder -> classifier -> real/fake. AASIST, RawNet2, and Wav2Vec2-AASIST are real models in this space -- conceptually the same audio-classification pattern from Module 126 (raw or learned features into a classifier head), just with two classes (real, synthetic) instead of dozens of sound categories.\n• The full responsible production pipeline chains everything covered across both parts of this lesson: user request -> consent gate (valid? no -> reject) -> reference audio -> speaker encoder -> speaker embedding -> TTS/VC -> generated audio -> watermark -> output validation -> final audio. Every stage in that chain was genuinely implemented and verified somewhere in this lesson pair -- the consent gate, the speaker-embedding/cosine math, and the watermark round trip -- except the TTS/VC generation step itself, which depends on either F5-TTS (genuinely attempted twice, consistently not completing on this CPU-only hardware within available time) or KNN-VC (not installable via pip at all).',
      bodyKn: '• ಒಂದು ಸರಳೀಕೃತ deepfake detector: audio -> feature encoder -> classifier -> real/fake. AASIST, RawNet2, ಮತ್ತು Wav2Vec2-AASIST ಈ ಜಾಗದಲ್ಲಿ ನಿಜ models ಗಳು -- ಪರಿಕಲ್ಪನಾತ್ಮಕವಾಗಿ Module 126 ಇಂದ ಅದೇ audio-classification ಮಾದರಿ (ಒಂದು classifier head ಗೆ ಕಚ್ಚಾ ಅಥವಾ ಕಲಿತ features), ಕೇವಲ ಡಜನ್‌ಗಟ್ಟಲೆ ಶಬ್ದ ವರ್ಗಗಳ ಬದಲಿಗೆ ಎರಡು classes (ನಿಜ, synthetic) ಜೊತೆ.\n• ಪೂರ್ಣ ಜವಾಬ್ದಾರಿಯುತ production pipeline ಈ lesson ಜೋಡಿಯ ಎರಡೂ ಭಾಗಗಳಾದ್ಯಂತ ಒಳಗೊಂಡಿರುವ ಎಲ್ಲವನ್ನೂ ಸರಪಳಿ ಮಾಡುತ್ತದೆ: user request -> consent gate (ಮಾನ್ಯವೇ? ಇಲ್ಲ -> ತಿರಸ್ಕರಿಸಿ) -> reference audio -> speaker encoder -> speaker embedding -> TTS/VC -> ಉತ್ಪಾದಿಸಿದ audio -> watermark -> output validation -> ಅಂತಿಮ audio. ಆ ಸರಪಳಿಯ ಪ್ರತಿ ಹಂತವನ್ನೂ ಈ lesson ಜೋಡಿಯಲ್ಲಿ ಎಲ್ಲಾದರೂ ನಿಜವಾಗಿ ಅಳವಡಿಸಲಾಗಿದೆ ಮತ್ತು ಪರಿಶೀಲಿಸಲಾಗಿದೆ -- consent gate, speaker-embedding/cosine ಗಣಿತ, ಮತ್ತು watermark ಸುತ್ತು -- TTS/VC ಉತ್ಪಾದನಾ ಹಂತ ಸ್ವತಃ ಹೊರತುಪಡಿಸಿ, ಇದೂ F5-TTS ಮೇಲೆ ಅವಲಂಬಿತವಾಗಿದೆ (ಎರಡು ಬಾರಿ ನಿಜವಾಗಿ ಪ್ರಯತ್ನಿಸಲಾಗಿದೆ, ಈ CPU-ಮಾತ್ರ ಹಾರ್ಡ್‌ವೇರ್‌ನಲ್ಲಿ ಲಭ್ಯವಿರುವ ಸಮಯದೊಳಗೆ ಸ್ಥಿರವಾಗಿ ಪೂರ್ಣಗೊಳ್ಳುವುದಿಲ್ಲ) ಅಥವಾ KNN-VC (pip ಮೂಲಕ ಸಂಪೂರ್ಣವಾಗಿ ಸ್ಥಾಪಿಸಬಹುದಾಗಿಲ್ಲ).' } },
    { type: 'diagram', data: {
      svgCode: "<svg viewBox=\"0 0 260 200\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"monospace\" font-size=\"6.2\">\n  <rect width=\"260\" height=\"200\" rx=\"8\" fill=\"#0f172a\"/>\n  <text x=\"130\" y=\"12\" fill=\"#94a3b8\" text-anchor=\"middle\" font-size=\"7\">Verified: The Full Responsible Pipeline</text>\n  <rect x=\"80\" y=\"20\" width=\"100\" height=\"16\" rx=\"3\" fill=\"#1e293b\" stroke=\"#60a5fa\"/><text x=\"130\" y=\"31\" fill=\"#93c5fd\" text-anchor=\"middle\" font-size=\"5\">User Request</text>\n  <rect x=\"80\" y=\"42\" width=\"100\" height=\"16\" rx=\"3\" fill=\"#022c22\" stroke=\"#34d399\"/><text x=\"130\" y=\"53\" fill=\"#6ee7b7\" text-anchor=\"middle\" font-size=\"5\">Consent Gate [VERIFIED]</text>\n  <rect x=\"5\" y=\"64\" width=\"55\" height=\"16\" rx=\"3\" fill=\"#450a0a\" stroke=\"#f87171\"/><text x=\"32\" y=\"75\" fill=\"#fca5a5\" text-anchor=\"middle\" font-size=\"5\">Reject</text>\n  <rect x=\"80\" y=\"64\" width=\"100\" height=\"16\" rx=\"3\" fill=\"#1e1b4b\" stroke=\"#a78bfa\"/><text x=\"130\" y=\"75\" fill=\"#c4b5fd\" text-anchor=\"middle\" font-size=\"5\">Speaker Encoder</text>\n  <rect x=\"80\" y=\"86\" width=\"100\" height=\"16\" rx=\"3\" fill=\"#022c22\" stroke=\"#34d399\"/><text x=\"130\" y=\"97\" fill=\"#6ee7b7\" text-anchor=\"middle\" font-size=\"5\">Spk Embedding [VERIFIED]</text>\n  <rect x=\"80\" y=\"108\" width=\"100\" height=\"16\" rx=\"3\" fill=\"#292524\" stroke=\"#f59e0b\"/><text x=\"130\" y=\"119\" fill=\"#fde68a\" text-anchor=\"middle\" font-size=\"5\">TTS / VC [NOT COMPLETED]</text>\n  <rect x=\"80\" y=\"130\" width=\"100\" height=\"16\" rx=\"3\" fill=\"#022c22\" stroke=\"#34d399\"/><text x=\"130\" y=\"141\" fill=\"#6ee7b7\" text-anchor=\"middle\" font-size=\"5\">Watermark [VERIFIED]</text>\n  <rect x=\"80\" y=\"152\" width=\"100\" height=\"16\" rx=\"3\" fill=\"#1e293b\" stroke=\"#60a5fa\"/><text x=\"130\" y=\"163\" fill=\"#93c5fd\" text-anchor=\"middle\" font-size=\"5\">Output Validation</text>\n  <rect x=\"80\" y=\"174\" width=\"100\" height=\"16\" rx=\"3\" fill=\"#022c22\" stroke=\"#34d399\"/><text x=\"130\" y=\"185\" fill=\"#6ee7b7\" text-anchor=\"middle\" font-size=\"5\">Output Audio</text>\n  <g stroke=\"#475569\"><path d=\"M130,36 V42\"/><path d=\"M130,58 V64\"/><path d=\"M80,72 H60\"/><path d=\"M130,80 V86\"/><path d=\"M130,102 V108\"/><path d=\"M130,124 V130\"/><path d=\"M130,146 V152\"/><path d=\"M130,168 V174\"/></g>\n</svg>",
      headingEn: 'What Was Genuinely Verified in This Lesson Pair', headingKn: 'ಈ Lesson ಜೋಡಿಯಲ್ಲಿ ನಿಜವಾಗಿ ಏನನ್ನೂ ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
      captionEn: 'Every stage of the responsible production pipeline was genuinely exercised except TTS/VC generation itself, which depends on real models this CPU-only environment could not run to completion.',
      captionKn: 'ಜವಾಬ್ದಾರಿಯುತ production pipeline ನ ಪ್ರತಿ ಹಂತವನ್ನೂ TTS/VC ಉತ್ಪಾದನೆ ಸ್ವತಃ ಹೊರತುಪಡಿಸಿ ನಿಜವಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ, ಇದೂ ಈ CPU-ಮಾತ್ರ environment ಪೂರ್ಣಗೊಳಿಸಲು ಚಲಾಯಿಸಲಾಗದ ನಿಜ models ಗಳ ಮೇಲೆ ಅವಲಂಬಿತವಾಗಿದೆ.' } },

    { type: 'heading', data: { level: 'H2', textEn: 'Common Production Pitfalls', textKn: 'ಸಾಮಾನ್ಯ Production ಬಲೆಗಳು' } },
    { type: 'table', data: { captionEn: 'Four Real Failure Modes', captionKn: 'ನಾಲ್ಕು ನಿಜ ವೈಫಲ್ಯ ವಿಧಾನಗಳು',
      rows: 'Pitfall|Problem|Fix\nMisaligned reference|Transcript does not match what the reference audio actually says, breaking alignment|Transcript must exactly match the reference recording, word for word\nReverberation|Reference recorded in a large/echoey room|Use a close microphone in a quiet room for a dry, clean reference\nEmotional mismatch|Reference is very excited but calm narration is wanted|The clone inherits the reference\'s prosody -- match the reference\'s emotional tone to the target use case\nLanguage leakage|An English speaker\'s reference used to generate French speech|The generated speech may retain the original accent; cross-lingual models help but multilingual cloning remains genuinely hard' } },

    { type: 'concept', data: {
      headingEn: 'Why AI Uses It', headingKn: 'AI ಇದನ್ನು ಏಕೆ ಬಳಸುತ್ತದೆ',
      bodyEn: '• The genuinely verified tamper-rejection test is the concrete reason production consent systems use cryptographic signatures rather than a simple database flag: this lesson directly demonstrated that a tampered record (purpose changed after signing) is caught and rejected, while a flag-based system would have silently accepted the same tampering -- the difference between "we trust our database was never modified incorrectly" and "we can mathematically prove this record has not changed since it was signed."\n• The two real SilentCipher bugs (a torch dependency conflict, and a nonexistent SilentCipher class) matter beyond this one library: they are a concrete instance of a pattern this course has now verified repeatedly across different tools (speechbrain\'s deprecated import path, its missing similarity() method, transformers\' silent output_attentions no-op) -- documentation and example code drift out of sync with a library\'s actual current API more often than most engineers assume, and the only reliable defense is running the exact code against the real, currently-installed version before trusting it.\n• The genuinely-built illustrative watermark (not SilentCipher\'s real algorithm, but a real, working embed/detect round trip) demonstrates the actual mechanism -- payload bits become sample-level perturbations, recoverable later -- which is precisely why "watermarking survives compression" is a genuinely hard research problem rather than an implementation detail: a naive scheme like the one built here is trivially destroyed by any lossy processing, so real systems need to embed the payload redundantly and robustly enough to survive exactly the transformations audio actually goes through in the real world (streaming, re-encoding, compression) -- the gap between this lesson\'s working toy and a production-grade watermark is the entire research contribution of systems like SilentCipher and AudioSeal.',
      bodyKn: '• ನಿಜವಾಗಿ ಪರಿಶೀಲಿಸಿದ tamper-ತಿರಸ್ಕಾರ ಪರೀಕ್ಷೆ production consent systems ಗಳು ಒಂದು ಸರಳ database flag ಬದಲಿಗೆ ಕ್ರಿಪ್ಟೋಗ್ರಾಫಿಕ್ signatures ಗಳನ್ನೂ ಏಕೆ ಬಳಸುತ್ತವೆ ಎಂಬುದಕ್ಕೆ ಕಾಂಕ್ರೀಟ್ ಕಾರಣ: ಈ lesson ಒಂದು ತಿರುಚಿದ ದಾಖಲೆ (ಸಹಿ ಮಾಡಿದ ನಂತರ purpose ಬದಲಾಯಿಸಲಾಗಿದೆ) ಹಿಡಿಯಲಾಗುತ್ತದೆ ಮತ್ತು ತಿರಸ್ಕರಿಸಲಾಗುತ್ತದೆ ಎಂದು ನೇರವಾಗಿ ಪ್ರದರ್ಶಿಸಿತು, ಒಂದು flag-ಆಧಾರಿತ system ಅದೇ ತಿರುಚುವಿಕೆಯನ್ನೂ ಮೌನವಾಗಿ ಸ್ವೀಕರಿಸುತ್ತಿತ್ತು -- "ನಮ್ಮ database ಎಂದಿಗೂ ತಪ್ಪಾಗಿ ಮಾರ್ಪಡಿಸಲಾಗಿಲ್ಲ ಎಂದು ನಾವು ನಂಬುತ್ತೇವೆ" ಮತ್ತು "ಈ ದಾಖಲೆ ಸಹಿ ಮಾಡಿದಾಗಿನಿಂದ ಬದಲಾಗಿಲ್ಲ ಎಂದು ನಾವು ಗಣಿತೀಯವಾಗಿ ಸಾಬೀತುಪಡಿಸಬಹುದು" ನಡುವಿನ ವ್ಯತ್ಯಾಸ.\n• ಎರಡು ನಿಜ SilentCipher bugs ಗಳು (ಒಂದು torch dependency conflict, ಮತ್ತು ಅಸ್ತಿತ್ವದಲ್ಲಿಲ್ಲದ SilentCipher class) ಈ ಒಂಟಿ library ಮೀರಿ ಮುಖ್ಯ: ಅವು ಈ ಕೋರ್ಸ್ ಈಗ ಬೇರೆ ಟೂಲ್ಸ್‌ಗಳಾದ್ಯಂತ ಪದೇ ಪದೇ ಪರಿಶೀಲಿಸಿದ ಒಂದು ಮಾದರಿಯ ಕಾಂಕ್ರೀಟ್ ನಿದರ್ಶನ (speechbrain ನ deprecated import ಮಾರ್ಗ, ಇದರ ಕಾಣೆಯಾದ similarity() ಫಂಕ್ಷನ್, transformers ನ ಮೌನ output_attentions no-op) -- ದಸ್ತಾವೇಜು ಮತ್ತು ಉದಾಹರಣೆ code ಹೆಚ್ಚಿನ ಎಂಜಿನಿಯರ್‌ಗಳು ಊಹಿಸುವುದಕ್ಕಿಂತ ಹೆಚ್ಚಾಗಿ ಒಂದು library ನ ನಿಜ ಪ್ರಸ್ತುತ API ಇಂದ ಸಿಂಕ್‌ಇಲ್ಲದೆ ದೂರ ಚಲಿಸುತ್ತದೆ, ಮತ್ತು ಏಕೈಕ ವಿಶ್ವಾಸಾರ್ಹ ರಕ್ಷಣೆ ಇದನ್ನೂ ನಂಬುವ ಮೊದಲು ನಿಜ, ಪ್ರಸ್ತುತ-ಸ್ಥಾಪಿಸಿದ ಆವೃತ್ತಿಯ ವಿರುದ್ಧ ನಿಖರ code ಚಲಾಯಿಸುವುದೂ.\n• ನಿಜವಾಗಿ-ನಿರ್ಮಿಸಿದ ವಿವರಣಾತ್ಮಕ watermark (SilentCipher ನ ನಿಜ algorithm ಅಲ್ಲ, ಆದರೆ ಒಂದು ನಿಜ, ಕೆಲಸ ಮಾಡುವ embed/detect ಸುತ್ತು) ನಿಜ ಕಾರ್ಯವಿಧಾನ ಪ್ರದರ್ಶಿಸುತ್ತದೆ -- payload bits ಗಳು sample-ಮಟ್ಟದ ಗೊಂದಲಗಳಾಗುತ್ತವೆ, ನಂತರ ಮರುಪಡೆಯಬಹುದಾಗಿ -- "watermarking compression ಬದುಕುಳಿಯುತ್ತದೆ" ಒಂದು ಅಳವಡಿಕೆ ವಿವರಕ್ಕಿಂತ ನಿಜವಾಗಿ ಕಠಿಣ ಸಂಶೋಧನಾ ಸಮಸ್ಯೆ ಏಕೆ ಎಂಬುದಕ್ಕೆ ಇದೇ ನಿಖರ ಕಾರಣ: ಇಲ್ಲಿ ನಿರ್ಮಿಸಿದಂತಹ ಒಂದು naive ಸ್ಕೀಮ್ ಯಾವುದೇ lossy ಪ್ರಕ್ರಿಯೆಯಿಂದ ಅತ್ಯಲ್ಪವಾಗಿ ನಾಶವಾಗುತ್ತದೆ, ನಿಜ systems ಗಳಿಗೆ audio ನಿಜ-ಪ್ರಪಂಚದಲ್ಲಿ ನಿಜವಾಗಿ ಹಾದುಹೋಗುವ ನಿಖರ ರೂಪಾಂತರಗಳನ್ನೂ (streaming, re-encoding, compression) ಬದುಕುಳಿಯಲು ಪುನರುಕ್ತ ಮತ್ತು ದೃಢವಾಗಿ ಸಾಕಷ್ಟು payload ಅಳವಡಿಸುವ ಅಗತ್ಯವಿದೆ -- ಈ lesson ನ ಕೆಲಸ ಮಾಡುವ toy ಮತ್ತು ಒಂದು production-ದರ್ಜೆಯ watermark ನಡುವಿನ ಅಂತರವೇ SilentCipher ಮತ್ತು AudioSeal ನಂತಹ systems ಗಳ ಸಂಪೂರ್ಣ ಸಂಶೋಧನಾ ಕೊಡುಗೆ.' } },

    { type: 'concept', data: {
      headingEn: 'Key Takeaways', headingKn: 'ಮುಖ್ಯ ಅಂಶಗಳು',
      bodyEn: '• Voice conversion (source speech + target speaker -> converted speech) and voice cloning (text + speaker reference -> new speech) share the same content/speaker decomposition but combine the pieces from opposite starting points.\n• KNN-VC uses WavLM embeddings and nearest-neighbor retrieval instead of a trained per-speaker decoder, so a larger/cleaner target pool directly improves quality with no retraining -- verified conceptually against the real absence of a "knnvc" PyPI package.\n• Neural codecs represent speech as discrete tokens rather than continuous mel spectrograms, turning generation into a next-token-prediction problem (VALL-E, VoiceBox).\n• SECS is the same speaker-embedding cosine similarity verified in Module 129, now applied to a cloning system\'s own output -- verified directly, correctly ranking a close embedding (0.9996) above a far one (-0.424) -- but similarity alone is not enough; intelligibility (WER via ASR, from Module 127) must also be checked.\n• Watermarking survived a genuine embed/detect round trip in this lesson using a deliberately simple stand-in, while the real SilentCipher library revealed two genuine, verified issues (a torch dependency conflict, and a nonexistent documented class) when actually run.\n• A genuinely-built consent gate correctly accepted a validly-signed request and correctly rejected a tampered one via real HMAC-SHA256 verification -- a concrete demonstration of why cryptographic signatures, not simple flags, protect production consent records.\n• Reference quality strongly affects the final result: misaligned transcripts, reverberant recordings, mismatched emotional tone, and cross-lingual language leakage are all real, documented failure modes, not hypothetical edge cases.',
      bodyKn: '• Voice conversion (source ಭಾಷಣ + ಗುರಿ speaker -> ಪರಿವರ್ತಿಸಿದ ಭಾಷಣ) ಮತ್ತು voice cloning (ಪಠ್ಯ + speaker reference -> ಹೊಸ ಭಾಷಣ) ಅದೇ content/speaker ವಿಘಟನೆ ಹಂಚಿಕೊಳ್ಳುತ್ತವೆ ಆದರೆ ವಿರುದ್ಧ ಆರಂಭಿಕ ಬಿಂದುಗಳಿಂದ ತುಣುಕುಗಳನ್ನೂ ಸಂಯೋಜಿಸುತ್ತವೆ.\n• KNN-VC ಒಂದು ತರಬೇತಿ ಪಡೆದ ಪ್ರತಿ-speaker decoder ಬದಲಿಗೆ WavLM embeddings ಮತ್ತು nearest-neighbor retrieval ಬಳಸುತ್ತದೆ, ಆದ್ದರಿಂದ ಒಂದು ದೊಡ್ಡ/ಸ್ವಚ್ಛ ಗುರಿ ಪೂಲ್ ಯಾವುದೇ ಮರುತರಬೇತಿ ಇಲ್ಲದೆ ನೇರವಾಗಿ ಗುಣಮಟ್ಟ ಸುಧಾರಿಸುತ್ತದೆ -- ಒಂದು "knnvc" PyPI package ನ ನಿಜ ಗೈರುಹಾಜರಿ ವಿರುದ್ಧ ಪರಿಕಲ್ಪನಾತ್ಮಕವಾಗಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ.\n• Neural codecs ಭಾಷಣವನ್ನೂ ನಿರಂತರ mel spectrograms ಬದಲಿಗೆ ಡಿಸ್ಕ್ರೀಟ್ tokens ಗಳಾಗಿ ಪ್ರತಿನಿಧಿಸುತ್ತವೆ, ಉತ್ಪಾದನೆಯನ್ನೂ ಒಂದು next-token-prediction ಸಮಸ್ಯೆಯಾಗಿ ಬದಲಾಯಿಸುತ್ತಾ (VALL-E, VoiceBox).\n• SECS Module 129 ನಲ್ಲಿ ಪರಿಶೀಲಿಸಿದ ಅದೇ speaker-embedding cosine similarity, ಈಗ ಒಂದು cloning system ನ ಸ್ವಂತ output ಗೆ ಅನ್ವಯಿಸಲಾಗಿದೆ -- ನೇರವಾಗಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ, ಒಂದು ದೂರದ ಒಂದಕ್ಕಿಂತ (-0.424) ಒಂದು ಹತ್ತಿರದ embedding (0.9996) ಅನ್ನೂ ಸರಿಯಾಗಿ ಶ್ರೇಣೀಕರಿಸುತ್ತಾ -- ಆದರೆ ಒಂಟಿ ಹೋಲಿಕೆ ಸಾಕಾಗುವುದಿಲ್ಲ; ಗ್ರಹಿಕಾ ಸಾಮರ್ಥ್ಯವನ್ನೂ (Module 127 ಇಂದ ASR ಮೂಲಕ WER) ಸಹ ಪರಿಶೀಲಿಸಬೇಕು.\n• Watermarking ಈ lesson ನಲ್ಲಿ ಉದ್ದೇಶಪೂರ್ವಕವಾಗಿ ಸರಳ stand-in ಬಳಸಿ ಒಂದು ನಿಜ embed/detect ಸುತ್ತು ಬದುಕುಳಿಯಿತು, ನಿಜ SilentCipher library ನಿಜವಾಗಿ ಚಲಾಯಿಸಿದಾಗ ಎರಡು ನಿಜ, ಪರಿಶೀಲಿಸಿದ ಸಮಸ್ಯೆಗಳನ್ನೂ ಬಹಿರಂಗಪಡಿಸಿತು (ಒಂದು torch dependency conflict, ಮತ್ತು ಅಸ್ತಿತ್ವದಲ್ಲಿಲ್ಲದ ಒಂದು ದಾಖಲಿತ class).\n• ಒಂದು ನಿಜವಾಗಿ-ನಿರ್ಮಿಸಿದ consent gate ಒಂದು ಮಾನ್ಯವಾಗಿ-ಸಹಿ ಮಾಡಿದ ವಿನಂತಿಯನ್ನೂ ಸರಿಯಾಗಿ ಸ್ವೀಕರಿಸಿತು ಮತ್ತು ನಿಜ HMAC-SHA256 ಪರಿಶೀಲನೆ ಮೂಲಕ ಒಂದು ತಿರುಚಿದ್ದನ್ನೂ ಸರಿಯಾಗಿ ತಿರಸ್ಕರಿಸಿತು -- ಕ್ರಿಪ್ಟೋಗ್ರಾಫಿಕ್ signatures ಗಳು, ಸರಳ flags ಗಳಲ್ಲ, production consent ದಾಖಲೆಗಳನ್ನೂ ಏಕೆ ರಕ್ಷಿಸುತ್ತವೆ ಎಂಬುದರ ಒಂದು ಕಾಂಕ್ರೀಟ್ ಪ್ರದರ್ಶನ.\n• Reference ಗುಣಮಟ್ಟ ಅಂತಿಮ ಫಲಿತಾಂಶವನ್ನೂ ಬಲವಾಗಿ ಪ್ರಭಾವಿಸುತ್ತದೆ: ತಪ್ಪಾಗಿ-ಹೊಂದಿಸಿದ transcripts, reverberant ರೆಕಾರ್ಡಿಂಗ್‌ಗಳು, ಹೊಂದಿಕೆಯಾಗದ ಭಾವನಾತ್ಮಕ ಟೋನ್, ಮತ್ತು ಅಡ್ಡ-ಭಾಷಾ ಸೋರಿಕೆ ಎಲ್ಲಾ ನಿಜ, ದಾಖಲಿತ ವೈಫಲ್ಯ ವಿಧಾನಗಳು, ಕಾಲ್ಪನಿಕ ಅಂಚು ಪ್ರಕರಣಗಳಲ್ಲ.' } },

    { type: 'quiz', data: { questions: [
      { q: 'Verified in this lesson: what real result did the cosine() SECS calculation produce for a "close" vs. a "far" speaker embedding?', qKn: 'ಈ lesson ನಲ್ಲಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ: cosine() SECS ಲೆಕ್ಕಾಚಾರ "ಹತ್ತಿರದ" vs. "ದೂರದ" speaker embedding ಗಾಗಿ ಯಾವ ನಿಜ ಫಲಿತಾಂಶ ಉತ್ಪಾದಿಸಿತು?',
        opts: ['Both scored identically at 0.5', 'The close embedding scored 0.9996 (near-perfect similarity) and the far embedding scored -0.424 (negative, indicating substantially different directions)', 'The far embedding scored higher than the close one', 'The function raised a divide-by-zero error'], correct: 1,
        optsKn: ['ಎರಡೂ 0.5 ರಲ್ಲಿ ಒಂದೇ ರೀತಿ ಸ್ಕೋರ್ ಮಾಡಿದವು', 'ಹತ್ತಿರದ embedding 0.9996 ಸ್ಕೋರ್ ಮಾಡಿತು (ಬಹುತೇಕ-ಪರಿಪೂರ್ಣ ಹೋಲಿಕೆ) ಮತ್ತು ದೂರದ embedding -0.424 ಸ್ಕೋರ್ ಮಾಡಿತು (negative, ಗಣನೀಯವಾಗಿ ಬೇರೆ ದಿಕ್ಕುಗಳನ್ನೂ ಸೂಚಿಸುತ್ತಾ)', 'ದೂರದ embedding ಹತ್ತಿರದ ಒಂದಕ್ಕಿಂತ ಹೆಚ್ಚಿನ ಸ್ಕೋರ್ ಮಾಡಿತು', 'ಫಂಕ್ಷನ್ ಒಂದು divide-by-zero ದೋಷ ಎಬ್ಬಿಸಿತು'] },
      { q: 'Verified in this lesson: what two real, distinct bugs were found when the lesson\'s SilentCipher code was genuinely attempted?', qKn: 'ಈ lesson ನಲ್ಲಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ: ಲೆಸನ್‌ನ SilentCipher code ಅನ್ನೂ ನಿಜವಾಗಿ ಪ್ರಯತ್ನಿಸಿದಾಗ ಯಾವ ಎರಡು ನಿಜ, ಪ್ರತ್ಯೇಕ bugs ಗಳು ಕಂಡುಬಂದವು?',
        opts: ['The package does not exist on PyPI at all, and it requires a paid license', 'A genuine torch-version dependency conflict (silentcipher pins torch<=2.0.0 against the environment\'s torch 2.13.0), and a documented SilentCipher class that does not actually exist in the real package (the real API is silentcipher.get_model())', 'It only works on Linux, and it requires an internet connection', 'The package name is misspelled in the lesson'], correct: 1,
        optsKn: ['Package PyPI ಯಲ್ಲಿ ಸಂಪೂರ್ಣವಾಗಿ ಅಸ್ತಿತ್ವದಲ್ಲಿಲ್ಲ, ಮತ್ತು ಇದಕ್ಕೆ ಒಂದು ಪಾವತಿಸಿದ ಪರವಾನಗಿ ಅಗತ್ಯ', 'ಒಂದು ನಿಜ torch-ಆವೃತ್ತಿ dependency conflict (silentcipher environment ನ torch 2.13.0 ವಿರುದ್ಧ torch<=2.0.0 ಪಿನ್ ಮಾಡುತ್ತದೆ), ಮತ್ತು ನಿಜ package ನಲ್ಲಿ ವಾಸ್ತವವಾಗಿ ಅಸ್ತಿತ್ವದಲ್ಲಿಲ್ಲದ ಒಂದು ದಾಖಲಿತ SilentCipher class (ನಿಜ API silentcipher.get_model())', 'ಇದೂ ಕೇವಲ Linux ನಲ್ಲಿ ಮಾತ್ರ ಕೆಲಸ ಮಾಡುತ್ತದೆ, ಮತ್ತು ಇದಕ್ಕೆ ಒಂದು ಇಂಟರ್ನೆಟ್ ಸಂಪರ್ಕ ಅಗತ್ಯ', 'Package ಹೆಸರು ಲೆಸನ್‌ನಲ್ಲಿ ತಪ್ಪಾಗಿ ಉಚ್ಚರಿಸಲಾಗಿದೆ'] },
      { q: 'Verified in this lesson: what happened when the consent record was tampered with after being signed, and the tampered version was passed to cloned_inference()?', qKn: 'ಈ lesson ನಲ್ಲಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ: consent ದಾಖಲೆಯನ್ನೂ ಸಹಿ ಮಾಡಿದ ನಂತರ ತಿರುಚಿದಾಗ, ಮತ್ತು ತಿರುಚಿದ ಆವೃತ್ತಿಯನ್ನೂ cloned_inference() ಗೆ ರವಾನಿಸಿದಾಗ ಏನಾಯಿತು?',
        opts: ['The tampered request was accepted, since only the speaker_id was checked', 'verify_signature() correctly returned False, and cloned_inference() correctly raised an AssertionError, refusing to generate audio for the tampered request', 'The system crashed with an unrelated error', 'It silently used the original, untampered values instead'], correct: 1,
        optsKn: ['ಕೇವಲ speaker_id ಮಾತ್ರ ಪರಿಶೀಲಿಸಿದ ಕಾರಣ ತಿರುಚಿದ ವಿನಂತಿಯನ್ನೂ ಸ್ವೀಕರಿಸಲಾಯಿತು', 'verify_signature() ಸರಿಯಾಗಿ False ಹಿಂತಿರುಗಿಸಿತು, ಮತ್ತು cloned_inference() ಸರಿಯಾಗಿ ಒಂದು AssertionError ಎಬ್ಬಿಸಿತು, ತಿರುಚಿದ ವಿನಂತಿಗೆ audio ಉತ್ಪಾದಿಸಲು ನಿರಾಕರಿಸುತ್ತಾ', 'System ಒಂದು ಸಂಬಂಧವಿಲ್ಲದ ದೋಷದೊಂದಿಗೆ crash ಆಯಿತು', 'ಇದೂ ಮೌನವಾಗಿ ಮೂಲ, ತಿರುಚದ ಮೌಲ್ಯಗಳನ್ನೂ ಬದಲಿಗೆ ಬಳಸಿತು'] },
      { q: 'Why does KNN-VC not require training a dedicated decoder for every new target voice?', qKn: 'KNN-VC ಗೆ ಪ್ರತಿ ಹೊಸ ಗುರಿ ಧ್ವನಿಗೆ ಒಂದು ಸಮರ್ಪಿತ decoder ತರಬೇತಿ ನೀಡುವ ಅಗತ್ಯ ಏಕೆ ಇಲ್ಲ?',
        opts: ['It uses nearest-neighbor retrieval over a pool of target speaker embeddings (from a pretrained WavLM encoder) rather than a learned per-speaker decoder, so adding more target reference audio directly improves coverage with no retraining', 'It does not actually work for any new speaker', 'It requires exactly one target recording, never more', 'It converts text to speech instead of speech to speech'], correct: 0,
        optsKn: ['ಇದೂ ಒಂದು ಕಲಿತ ಪ್ರತಿ-speaker decoder ಬದಲಿಗೆ ಗುರಿ speaker embeddings ಗಳ ಒಂದು ಪೂಲ್ ಮೇಲೆ (ಒಂದು ಪೂರ್ವತರಬೇತಿ ಪಡೆದ WavLM encoder ಇಂದ) nearest-neighbor retrieval ಬಳಸುತ್ತದೆ, ಆದ್ದರಿಂದ ಹೆಚ್ಚಿನ ಗುರಿ reference audio ಸೇರಿಸುವುದೂ ಯಾವುದೇ ಮರುತರಬೇತಿ ಇಲ್ಲದೆ ನೇರವಾಗಿ ವ್ಯಾಪ್ತಿ ಸುಧಾರಿಸುತ್ತದೆ', 'ಇದೂ ವಾಸ್ತವವಾಗಿ ಯಾವುದೇ ಹೊಸ speaker ಗೆ ಕೆಲಸ ಮಾಡುವುದಿಲ್ಲ', 'ಇದಕ್ಕೆ ನಿಖರವಾಗಿ ಒಂದು ಗುರಿ ರೆಕಾರ್ಡಿಂಗ್ ಅಗತ್ಯ, ಎಂದಿಗೂ ಹೆಚ್ಚಿಲ್ಲ', 'ಇದೂ speech ಗೆ speech ಬದಲಿಗೆ text ಅನ್ನೂ speech ಗೆ ಪರಿವರ್ತಿಸುತ್ತದೆ'] },
      { q: 'Why is a naive least-significant-bit watermark stand-in (like the one built in this lesson) not production-grade, despite genuinely working?', qKn: 'ಒಂದು naive least-significant-bit watermark stand-in (ಈ lesson ನಲ್ಲಿ ನಿರ್ಮಿಸಿದಂತಹ) ನಿಜವಾಗಿ ಕೆಲಸ ಮಾಡಿದರೂ production-ದರ್ಜೆಯದ್ದಲ್ಲ ಏಕೆ?',
        opts: ['It is actually production-grade and identical to SilentCipher', 'It would be trivially destroyed by any lossy compression or resampling, while real systems like SilentCipher are specifically trained to survive exactly those real-world transformations', 'It cannot encode any information at all', 'It only works on video, not audio'], correct: 1,
        optsKn: ['ಇದೂ ವಾಸ್ತವವಾಗಿ production-ದರ್ಜೆಯದ್ದು ಮತ್ತು SilentCipher ಗೆ ಸಮಾನ', 'ಇದೂ ಯಾವುದೇ lossy compression ಅಥವಾ resampling ಇಂದ ಅತ್ಯಲ್ಪವಾಗಿ ನಾಶವಾಗುತ್ತದೆ, SilentCipher ನಂತಹ ನಿಜ systems ಗಳು ನಿಖರವಾಗಿ ಆ ನಿಜ-ಪ್ರಪಂಚದ ರೂಪಾಂತರಗಳನ್ನೂ ಬದುಕುಳಿಯಲು ನಿರ್ದಿಷ್ಟವಾಗಿ ತರಬೇತಿ ಪಡೆದಿರುತ್ತವೆ', 'ಇದೂ ಸಂಪೂರ್ಣವಾಗಿ ಯಾವುದೇ ಮಾಹಿತಿಯನ್ನೂ encode ಮಾಡಲಾರದು', 'ಇದೂ ಕೇವಲ ವೀಡಿಯೋ ಮೇಲೆ ಮಾತ್ರ ಕೆಲಸ ಮಾಡುತ್ತದೆ, audio ಮೇಲಲ್ಲ'] },
    ] } },
  ],
};
