const phaseId = '6a369d5766020ed05b32136a'; // Phase 10
const moduleId = '6a369d5766020ed05b32136d'; // Module 141: Why Transformers: The Problems with RNNs

module.exports = {
  phaseId,
  moduleId,
  order: 3,
  type: 'reading',
  duration: 55,
  difficulty: 'intermediate',
  status: 'published',
  title: 'Why Transformers (Part 3) — The Trade-Off, Flash Attention & State-Space Models',
  titleKn: 'Why Transformers (Part 3) — The Trade-Off, Flash Attention & State-Space Models',
  desc: 'Genuinely compute the lesson\'s pairwise-attention-relationship table (100 tokens -> 10,000 pairs, up to 100,000 tokens -> 10,000,000,000 pairs) to confirm the O(N^2) quadratic bottleneck exactly, then work through why Transformers still won the trade-off, what Flash Attention actually changes (memory movement, not complexity class), and how state-space models like Mamba bring recurrence back with parallel-friendly structure.',
  descKn: 'Lesson ನ pairwise-attention-relationship table ಅನ್ನೂ ನಿಜವಾಗಿ ಗಣಿಸಿ (100 tokens -> 10,000 pairs, 100,000 tokens ವರೆಗೆ -> 10,000,000,000 pairs) O(N^2) quadratic bottleneck ಅನ್ನೂ ನಿಖರವಾಗಿ ದೃಢಪಡಿಸಿ, ನಂತರ Transformers ಆ trade-off ಏಕೆ ಗೆದ್ದವು, Flash Attention ನಿಜವಾಗಿ ಏನೂ ಬದಲಾಯಿಸುತ್ತದೆ (memory movement, complexity class ಅಲ್ಲ), ಮತ್ತು Mamba ನಂತಹ state-space models parallel-friendly ರಚನೆಯೊಂದಿಗೆ recurrence ಅನ್ನೂ ಹೇಗೆ ಹಿಂತಿರುಗಿಸುತ್ತವೆ ಎಂಬುದನ್ನೂ ಕೆಲಸ ಮಾಡಿ.',
  objectives: [
    'Explain why self-attention has O(N^2) memory and computation cost, and genuinely confirm the growth rate.',
    'Compare RNNs and Transformers in terms of computation, memory, and use cases.',
    'Understand why Transformers scale better despite their O(N^2) attention cost.',
    'Understand what Flash Attention actually optimizes, and what it does not change.',
    'Recognize inductive bias as a design axis across CNNs, RNNs, and Transformers.',
    'Understand the basic recurrent form of a state-space model and how it relates to both RNNs and Transformers.',
  ],
  objectivesKn: [
    'Self-attention O(N^2) memory ಮತ್ತು computation cost ಏಕೆ ಹೊಂದಿದೆ ಎಂದು ವಿವರಿಸಿ, ಮತ್ತು ಬೆಳವಣಿಗೆ ದರ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿ.',
    'ಗಣನೆ, ಮೆಮೊರಿ, ಮತ್ತು use cases ಪ್ರಕಾರ RNNs ಮತ್ತು Transformers ಹೋಲಿಸಿ.',
    'O(N^2) attention cost ಇದ್ದರೂ Transformers ಏಕೆ ಉತ್ತಮವಾಗಿ ಸ್ಕೇಲ್ ಮಾಡುತ್ತವೆ ಎಂದು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'Flash Attention ನಿಜವಾಗಿ ಏನೂ ಆಪ್ಟಿಮೈಜ್ ಮಾಡುತ್ತದೆ, ಮತ್ತು ಏನೂ ಬದಲಾಯಿಸುವುದಿಲ್ಲ ಎಂದು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'CNNs, RNNs, ಮತ್ತು Transformers ಆದ್ಯಂತ ಒಂದು ವಿನ್ಯಾಸ ಅಕ್ಷವಾಗಿ inductive bias ಗುರುತಿಸಿ.',
    'ಒಂದು state-space model ನ ಮೂಲಭೂತ recurrent ರೂಪ ಮತ್ತು ಇದೂ RNNs ಮತ್ತು Transformers ಎರಡಕ್ಕೂ ಹೇಗೆ ಸಂಬಂಧಿಸಿದೆ ಎಂದು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
  ],
  blocks: [
    { type: 'heading', data: { textEn: 'The Trade-Off: Transformers Aren\'t Free', textKn: 'The Trade-Off: Transformers Aren\'t Free', level: 'H1' } },
    { type: 'concept', data: {
      headingEn: 'Lesson Info', headingKn: 'Lesson ಮಾಹಿತಿ',
      bodyEn: '• Type: Learn · Language: Python · Prerequisites: Parts 1 & 2 -- RNN recurrence, vanishing gradients, self-attention, serial depth · Time: ~55 minutes · Part 3 of 3',
      bodyKn: '• Type: Learn · Language: Python · Prerequisites: Parts 1 & 2 -- RNN recurrence, vanishing gradients, self-attention, serial depth · Time: ~55 ನಿಮಿಷಗಳು · Part 3 of 3',
      pillsEn: 'Python,Prereq: Part 1 & 2,~55 min,Part 3 of 3',
      pillsKn: 'Python,Prereq: Part 1 & 2,~55 ನಿಮಿಷ,Part 3 of 3' } },

    { type: 'heading', data: { textEn: 'Attention Is Quadratic', textKn: 'Attention Is Quadratic', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'The Cost Self-Attention Doesn\'t Advertise', headingKn: 'Self-Attention ಜಾಹೀರಾತು ಮಾಡದ ವೆಚ್ಚ',
      bodyEn: '• The Transformer solves the RNN\'s sequential-computation problem, but introduces a different one\n• If you have N tokens, self-attention considers relationships between every pair of positions, producing N x N attention scores\n• Therefore self-attention has O(N^2) memory/computation behavior for the attention matrix -- doubling sequence length approximately quadruples pairwise attention relationships',
      bodyKn: '• Transformer RNN ನ sequential-computation ಸಮಸ್ಯೆ ಪರಿಹರಿಸುತ್ತದೆ, ಆದರೆ ಒಂದು ಭಿನ್ನ ಸಮಸ್ಯೆ ಪರಿಚಯಿಸುತ್ತದೆ\n• N tokens ಇದ್ದರೆ, self-attention ಪ್ರತಿ ಸ್ಥಾನಗಳ ಜೋಡಿ ನಡುವಿನ ಸಂಬಂಧಗಳನ್ನೂ ಪರಿಗಣಿಸುತ್ತದೆ, N x N attention scores ಉತ್ಪಾದಿಸುತ್ತಾ\n• ಆದ್ದರಿಂದ self-attention attention matrix ಗಾಗಿ O(N^2) memory/computation ವರ್ತನೆ ಹೊಂದಿದೆ -- sequence length ಎರಡುಪಟ್ಟು ಮಾಡುವುದೂ ಸ್ಥೂಲವಾಗಿ pairwise attention ಸಂಬಂಧಗಳನ್ನೂ ನಾಲ್ಕುಪಟ್ಟು ಮಾಡುತ್ತದೆ' } },
    { type: 'math', data: {
      formula: 'pairwise_relationships(N) = N x N = N^2',
      descEn: '• This is the exact formula behind the quadratic bottleneck: for N tokens, the attention matrix has N^2 entries', descKn: '• ಇದೇ quadratic bottleneck ಹಿಂದಿನ ನಿಖರ formula: N tokens ಗಾಗಿ, attention matrix N^2 entries ಹೊಂದಿದೆ' } },
    { type: 'code', data: {
      filename: 'quadratic_growth.py', headingEn: 'Genuinely Run — Confirming the Sequence-Length Table', headingKn: 'Genuinely Run — Sequence-Length Table ದೃಢಪಡಿಸುವುದೂ',
      descEn: 'Genuinely executed below for the exact token counts this lesson\'s table lists.',
      descKn: 'ಈ lesson ನ table ಪಟ್ಟಿ ಮಾಡುವ ನಿಖರ token counts ಗಾಗಿ ಕೆಳಗೆ ನಿಜವಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ.',
      code: "for n in [100, 1000, 2000, 10000, 100000]:\n    print(f\"{n:>7,} tokens -> {n*n:>15,} pairwise relationships\")" } },
    { type: 'output', data: { output: "    100 tokens ->          10,000 pairwise relationships\n  1,000 tokens ->       1,000,000 pairwise relationships\n  2,000 tokens ->       4,000,000 pairwise relationships\n 10,000 tokens ->     100,000,000 pairwise relationships\n100,000 tokens ->  10,000,000,000 pairwise relationships" } },
    { type: 'concept', data: {
      headingEn: 'Reading the Verified Output', headingKn: 'ಪರಿಶೀಲಿಸಿದ Output ಓದುವುದೂ',
      bodyEn: '• Genuinely confirms every entry in the lesson\'s table exactly: 100 tokens really does produce 10,000 pairs, and 100,000 tokens really does produce 10,000,000,000 pairs\n• Genuinely observe the quadratic pattern directly: going from 1,000 to 2,000 tokens (2x the length) genuinely produces 4,000,000 vs 1,000,000 pairs -- exactly 4x, confirming that doubling sequence length quadruples the attention cost, not doubles it',
      bodyKn: '• Lesson ನ table ನಲ್ಲಿ ಪ್ರತಿ entry ಅನ್ನೂ ನಿಖರವಾಗಿ ದೃಢಪಡಿಸುತ್ತದೆ: 100 tokens ನಿಜವಾಗಿಯೂ 10,000 pairs ಉತ್ಪಾದಿಸುತ್ತದೆ, ಮತ್ತು 100,000 tokens ನಿಜವಾಗಿಯೂ 10,000,000,000 pairs ಉತ್ಪಾದಿಸುತ್ತದೆ\n• Quadratic ಮಾದರಿ ಅನ್ನೂ ನೇರವಾಗಿ ನಿಜವಾಗಿ ಗಮನಿಸಿ: 1,000 ಇಂದ 2,000 tokens ಗೆ ಹೋಗುವುದೂ (2x ಉದ್ದ) ನಿಜವಾಗಿ 4,000,000 vs 1,000,000 pairs ಉತ್ಪಾದಿಸುತ್ತದೆ -- ನಿಖರವಾಗಿ 4x, sequence length ಎರಡುಪಟ್ಟು ಮಾಡುವುದೂ attention cost ಅನ್ನೂ ಎರಡುಪಟ್ಟು ಅಲ್ಲ ನಾಲ್ಕುಪಟ್ಟು ಮಾಡುತ್ತದೆ ಎಂದು ದೃಢಪಡಿಸುತ್ತಾ' } },

    { type: 'heading', data: { textEn: 'RNN vs. Transformer Trade-Off', textKn: 'RNN vs. Transformer Trade-Off', level: 'H2' } },
    { type: 'table', data: { captionEn: 'Property -> RNN vs. Transformer', captionKn: 'Property -> RNN vs. Transformer',
      rows: 'Property|RNN|Transformer\nSequential processing|Yes|No\nParallel training|Poor|Excellent\nLong-range dependency|Difficult|Direct attention\nSerial depth|O(N)|Much lower\nAttention memory|None|O(N^2)\nLong context|Memory-efficient|Expensive\nGPU utilization|Poorer|Excellent\nTraining scalability|Limited|Excellent' } },
    { type: 'concept', data: {
      headingEn: 'A Different Trade-Off, Not Simply "Better"', headingKn: 'ಒಂದು ಭಿನ್ನ Trade-Off, ಕೇವಲ "ಉತ್ತಮ" ಅಲ್ಲ',
      bodyEn: '• Transformers aren\'t simply "RNNs but better" -- they\'re a different trade-off\n• The Transformer essentially traded O(N) sequential computation for highly parallel computation, while accepting O(N^2) attention cost\n• Modern hardware strongly favors the first trade: the genuinely measured 9.18x serial-vs-parallel gap from Part 1, at toy scale, is the same effect that changed the scaling equation for real large-scale training',
      bodyKn: '• Transformers ಕೇವಲ "ಉತ್ತಮ RNNs" ಅಲ್ಲ -- ಇವು ಒಂದು ಭಿನ್ನ trade-off\n• Transformer ಮೂಲಭೂತವಾಗಿ O(N) sequential computation ಅನ್ನೂ ಬಹಳ parallel computation ಗಾಗಿ ವಿನಿಮಯ ಮಾಡಿಕೊಂಡಿತು, O(N^2) attention cost ಸ್ವೀಕರಿಸುತ್ತಾ\n• ಆಧುನಿಕ hardware ಮೊದಲ ವಿನಿಮಯ ಬಲವಾಗಿ ಬೆಂಬಲಿಸುತ್ತದೆ: Part 1 ಇಂದ ನಿಜವಾಗಿ ಅಳೆಯಲಾದ 9.18x serial-vs-parallel ಅಂತರ, toy ಪ್ರಮಾಣದಲ್ಲಿ, ನಿಜ ದೊಡ್ಡ-ಪ್ರಮಾಣದ training ಗಾಗಿ scaling equation ಬದಲಾಯಿಸಿದ ಅದೇ ಪರಿಣಾಮ' } },

    { type: 'heading', data: { textEn: 'Flash Attention', textKn: 'Flash Attention', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'Faster Memory Movement, Not a New Complexity Class', headingKn: 'ವೇಗದ Memory Movement, ಒಂದು ಹೊಸ Complexity Class ಅಲ್ಲ',
      bodyEn: '• Flash Attention does not magically change ordinary attention from quadratic to linear\n• Instead, it dramatically improves how attention is computed and stored in memory by using tiling and better memory access\n• Normal attention: Q x K^T -> huge attention matrix -> softmax -> x V, materializing the full intermediate attention matrix\n• Flash Attention avoids unnecessarily materializing/storing that full intermediate matrix in the same way, so the formula is: same fundamental attention complexity + better memory management = much faster practical attention',
      bodyKn: '• Flash Attention ಸಾಮಾನ್ಯ attention ಅನ್ನೂ quadratic ಇಂದ linear ಗೆ ಮಾಂತ್ರಿಕವಾಗಿ ಬದಲಾಯಿಸುವುದಿಲ್ಲ\n• ಬದಲಿಗೆ, ಇದೂ tiling ಮತ್ತು ಉತ್ತಮ memory access ಬಳಸಿ attention ಅನ್ನೂ ಹೇಗೆ ಗಣಿಸಲಾಗುತ್ತದೆ ಮತ್ತು memory ನಲ್ಲಿ ಸಂಗ್ರಹಿಸಲಾಗುತ್ತದೆ ಎಂಬುದನ್ನೂ ನಾಟಕೀಯವಾಗಿ ಸುಧಾರಿಸುತ್ತದೆ\n• ಸಾಮಾನ್ಯ attention: Q x K^T -> ಬೃಹತ್ attention matrix -> softmax -> x V, ಪೂರ್ಣ ಮಧ್ಯಂತರ attention matrix ಅನ್ನೂ materialize ಮಾಡುತ್ತಾ\n• Flash Attention ಆ ಪೂರ್ಣ ಮಧ್ಯಂತರ matrix ಅನ್ನೂ ಅದೇ ರೀತಿ ಅನಗತ್ಯವಾಗಿ materialize/ಸಂಗ್ರಹಿಸುವುದೂ ತಪ್ಪಿಸುತ್ತದೆ, ಆದ್ದರಿಂದ formula: ಅದೇ ಮೂಲಭೂತ attention complexity + ಉತ್ತಮ memory management = ಬಹಳ ವೇಗದ ಪ್ರಾಯೋಗಿಕ attention' } },
    { type: 'diagram', data: {
      svgCode: '<svg viewBox="0 0 600 200" xmlns="http://www.w3.org/2000/svg"><rect width="600" height="200" fill="none"/><text x="20" y="25" font-size="13" fill="#333">Normal attention:</text><rect x="30" y="40" width="100" height="30" fill="#eef4fb" stroke="#4f8fd1"/><text x="45" y="60" font-size="11">Q x K^T</text><line x1="130" y1="55" x2="170" y2="55" stroke="#888"/><rect x="170" y="35" width="140" height="40" fill="#fbeee0" stroke="#e08a3c"/><text x="180" y="60" font-size="11">full N x N matrix</text><line x1="310" y1="55" x2="350" y2="55" stroke="#888"/><rect x="350" y="40" width="90" height="30" fill="#eef4fb" stroke="#4f8fd1"/><text x="365" y="60" font-size="11">softmax, xV</text><text x="30" y="100" font-size="12" fill="#e08a3c">materializes full matrix in memory</text><text x="20" y="135" font-size="13" fill="#333">Flash Attention:</text><rect x="30" y="150" width="70" height="30" fill="#eef7ee" stroke="#4caf50"/><text x="38" y="170" font-size="10">tile 1</text><rect x="110" y="150" width="70" height="30" fill="#eef7ee" stroke="#4caf50"/><text x="118" y="170" font-size="10">tile 2</text><rect x="190" y="150" width="70" height="30" fill="#eef7ee" stroke="#4caf50"/><text x="198" y="170" font-size="10">tile 3</text><line x1="260" y1="165" x2="300" y2="165" stroke="#888"/><rect x="300" y="150" width="130" height="30" fill="#eef4fb" stroke="#4f8fd1"/><text x="310" y="170" font-size="10">running softmax output</text><text x="30" y="195" font-size="12" fill="#4caf50">never stores the full N x N matrix at once</text></svg>',
      titleEn: 'Flash Attention Tiles the Computation, It Doesn\'t Change the O(N^2) Score Count',
      titleKn: 'Flash Attention ಗಣನೆಯನ್ನೂ Tile ಮಾಡುತ್ತದೆ, O(N^2) Score Count ಬದಲಾಯಿಸುವುದಿಲ್ಲ',
      captionEn: 'Every one of the N^2 attention scores genuinely confirmed above still gets computed under Flash Attention -- what changes is that they are processed in small tiles with a running softmax, so the full N x N matrix is never materialized in slow memory at once.',
      captionKn: 'ಮೇಲೆ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ N^2 attention scores ಪ್ರತಿಯೊಂದೂ Flash Attention ಅಡಿಯಲ್ಲಿ ಇನ್ನೂ ಗಣಿಸಲ್ಪಡುತ್ತದೆ -- ಬದಲಾಗುವುದೂ ಇದೂ ಒಂದು running softmax ಜೊತೆ ಚಿಕ್ಕ tiles ನಲ್ಲಿ ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲ್ಪಡುತ್ತದೆ, ಆದ್ದರಿಂದ ಪೂರ್ಣ N x N matrix ಎಂದಿಗೂ ನಿಧಾನ memory ನಲ್ಲಿ ಒಂದೇ ಬಾರಿಗೆ materialize ಆಗುವುದಿಲ್ಲ.' } },

    { type: 'heading', data: { textEn: 'Inductive Bias', textKn: 'Inductive Bias', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'How Much Structure Does the Architecture Assume?', headingKn: 'Architecture ಎಷ್ಟು ರಚನೆ ಊಹಿಸುತ್ತದೆ?',
      bodyEn: '• An inductive bias is an assumption built into a model about how data behaves\n• CNNs assume nearby pixels are related and patterns can appear in different locations\n• RNNs assume sequence information naturally flows from earlier positions to later positions\n• Transformers make a much weaker locality assumption: any position can potentially interact with any other position -- token 1 <-> token 2, token 1 <-> token 100, token 1 <-> token 1000, token 500 <-> token 900, every pair is a potential relationship',
      bodyKn: '• ಒಂದು inductive bias ಒಂದು model ನಲ್ಲಿ ನಿರ್ಮಿಸಲಾದ ಡೇಟಾ ಹೇಗೆ ವರ್ತಿಸುತ್ತದೆ ಎಂಬ ಒಂದು ಊಹೆ\n• CNNs ಹತ್ತಿರದ pixels ಸಂಬಂಧಿಸಿವೆ ಮತ್ತು ಮಾದರಿಗಳು ಬೇರೆ ಸ್ಥಳಗಳಲ್ಲಿ ಕಾಣಿಸಿಕೊಳ್ಳಬಹುದು ಎಂದು ಊಹಿಸುತ್ತವೆ\n• RNNs sequence ಮಾಹಿತಿ ಸ್ವಾಭಾವಿಕವಾಗಿ ಹಿಂದಿನ ಸ್ಥಾನಗಳಿಂದ ನಂತರದ ಸ್ಥಾನಗಳಿಗೆ ಹರಿಯುತ್ತದೆ ಎಂದು ಊಹಿಸುತ್ತವೆ\n• Transformers ಬಹಳ ದುರ್ಬಲ locality ಊಹೆ ಮಾಡುತ್ತವೆ: ಯಾವುದೇ ಸ್ಥಾನ ಯಾವುದೇ ಇತರ ಸ್ಥಾನದೊಂದಿಗೆ ಸಂವಹಿಸಬಹುದು -- token 1 <-> token 2, token 1 <-> token 100, token 1 <-> token 1000, token 500 <-> token 900, ಪ್ರತಿ ಜೋಡಿ ಒಂದು ಸಂಭಾವ್ಯ ಸಂಬಂಧ' } },
    { type: 'table', data: { captionEn: 'Architecture -> Core Inductive Bias', captionKn: 'Architecture -> Core Inductive Bias',
      rows: 'Architecture|Core Inductive Bias\nCNN|Locality -- nearby elements relate; patterns are position-invariant\nRNN|Temporal locality -- information flows in one direction, step by step\nTransformer|Weak/near-none -- any position can attend to any other position' } },
    { type: 'concept', data: {
      headingEn: 'The Cost of Less Inductive Bias', headingKn: 'ಕಡಿಮೆ Inductive Bias ನ ವೆಚ್ಚ',
      bodyEn: '• Less baked-in structure means Transformers often need substantial amounts of data to learn patterns that a CNN or RNN would get "for free" from its architecture\n• But once enough data and compute are available, the architecture scales extremely well\n• This is one reason Transformers became dominant across language, vision, audio, biology, and robotics -- the same basic architecture can process very different types of sequences or representations',
      bodyKn: '• ಕಡಿಮೆ ಅಂತರ್ಗತ ರಚನೆ ಎಂದರೆ Transformers ಗೆ ಒಂದು CNN ಅಥವಾ RNN ಇದರ architecture ಇಂದ "ಉಚಿತವಾಗಿ" ಪಡೆಯುವ ಮಾದರಿಗಳನ್ನೂ ಕಲಿಯಲು ಸಾಮಾನ್ಯವಾಗಿ ಗಣನೀಯ ಪ್ರಮಾಣದ ಡೇಟಾ ಬೇಕಾಗುತ್ತದೆ\n• ಆದರೆ ಸಾಕಷ್ಟು ಡೇಟಾ ಮತ್ತು compute ಲಭ್ಯವಾದ ಒಮ್ಮೆ, architecture ಅತ್ಯಂತ ಚೆನ್ನಾಗಿ ಸ್ಕೇಲ್ ಆಗುತ್ತದೆ\n• ಇದೂ Transformers language, vision, audio, biology, ಮತ್ತು robotics ಆದ್ಯಂತ ಪ್ರಬಲವಾಗಿರುವುದಕ್ಕೆ ಒಂದು ಕಾರಣ -- ಅದೇ ಮೂಲಭೂತ architecture ಬಹಳ ಭಿನ್ನ ವಿಧದ sequences ಅಥವಾ representations ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಬಹುದು' } },

    { type: 'heading', data: { textEn: 'When Should You Still Use an RNN?', textKn: 'When Should You Still Use an RNN?', level: 'H2' } },
    { type: 'table', data: { captionEn: 'Situation -> Pick', captionKn: 'Situation -> Pick',
      rows: 'Situation|Pick\nStreaming inference, one token at a time, constant memory|RNN or SSM\nExtremely long sequences|Linear attention / Mamba / Hyena\nEdge device without strong matrix accelerator|RNN may be attractive\nLarge-scale training|Transformer\nBatched inference|Transformer\nContext up to ~128K|Transformer, with appropriate attention optimizations' } },
    { type: 'concept', data: {
      headingEn: 'Not "RNNs Are Useless"', headingKn: '"RNNs ನಿಷ್ಪ್ರಯೋಜಕ" ಅಲ್ಲ',
      bodyEn: '• The central message isn\'t "RNNs are useless" -- it\'s that RNNs are no longer the default architecture for large-scale sequence modeling\n• For streaming inference at constant memory per step, or edge devices without a strong matrix accelerator, the sequential-but-cheap-per-step nature of recurrence genuinely can be the better fit',
      bodyKn: '• ಕೇಂದ್ರ ಸಂದೇಶ "RNNs ನಿಷ್ಪ್ರಯೋಜಕ" ಅಲ್ಲ -- ಇದೂ RNNs ಇನ್ನು ದೊಡ್ಡ-ಪ್ರಮಾಣದ sequence modeling ಗಾಗಿ default architecture ಅಲ್ಲ ಎಂಬುದೂ\n• ಪ್ರತಿ step ಗೆ ಸ್ಥಿರ memory ನಲ್ಲಿ streaming inference ಗಾಗಿ, ಅಥವಾ ಬಲವಾದ matrix accelerator ಇಲ್ಲದ edge devices ಗಾಗಿ, recurrence ನ ಅನುಕ್ರಮಿಕ-ಆದರೆ-ಪ್ರತಿ-step-ಅಗ್ಗದ ಸ್ವಭಾವ ನಿಜವಾಗಿ ಉತ್ತಮ ಹೊಂದಾಣಿಕೆಯಾಗಬಹುದು' } },

    { type: 'heading', data: { textEn: 'State-Space Models', textKn: 'State-Space Models', level: 'H2' } },
    { type: 'math', data: {
      formula: 'h_t = A h_{t-1} + B x_t          y_t = C h_t',
      descEn: '• This is the simplified recurrent form behind modern state-space models (SSMs): it preserves a recurrent/state-based idea (h_t still depends on h_{t-1}, just like an RNN) but uses mathematical structure -- fixed matrices A, B, C -- that allows the recurrence to be reformulated as a convolution and computed in parallel during training\n• Modern SSMs such as Mamba introduce structured mechanisms that make this much more computationally attractive than a plain nonlinear RNN',
      descKn: '• ಇದೇ ಆಧುನಿಕ state-space models (SSMs) ಹಿಂದಿನ ಸರಳೀಕೃತ recurrent ರೂಪ: ಇದೂ ಒಂದು recurrent/state-based ಕಲ್ಪನೆ ಸಂರಕ್ಷಿಸುತ್ತದೆ (h_t ಇನ್ನೂ h_{t-1} ಮೇಲೆ ಅವಲಂಬಿತವಾಗಿದೆ, ಒಂದು RNN ನಂತೆಯೇ) ಆದರೆ ಗಣಿತದ ರಚನೆ ಬಳಸುತ್ತದೆ -- ಸ್ಥಿರ matrices A, B, C -- ಇದೂ recurrence ಅನ್ನೂ ಒಂದು convolution ಆಗಿ ಮರುರೂಪಿಸಲು ಮತ್ತು training ಸಮಯದಲ್ಲಿ ಸಮಾನಾಂತರವಾಗಿ ಗಣಿಸಲು ಅನುಮತಿಸುತ್ತದೆ\n• Mamba ನಂತಹ ಆಧುನಿಕ SSMs ಒಂದು ಸಾಮಾನ್ಯ nonlinear RNN ಗಿಂತ ಇದನ್ನೂ ಗಣನೀಯವಾಗಿ ಹೆಚ್ಚು computationally ಆಕರ್ಷಕಗೊಳಿಸುವ ರಚನಾತ್ಮಕ ಯಂತ್ರಾಂಶಗಳನ್ನೂ ಪರಿಚಯಿಸುತ್ತವೆ' } },
    { type: 'concept', data: {
      headingEn: 'The Evolution Isn\'t "RNN -> Dead"', headingKn: 'ವಿಕಾಸ "RNN -> ಸತ್ತ" ಅಲ್ಲ',
      bodyEn: '• The evolution is closer to: RNN -> LSTM / GRU -> Transformer -> Hybrid architectures -> SSMs + Transformers\n• Recurrence remains useful when its memory efficiency matters -- an SSM processes one step at a time like an RNN at inference time, but its structured form lets it train in parallel like a Transformer',
      bodyKn: '• ವಿಕಾಸ ಇದಕ್ಕೆ ಹತ್ತಿರವಾಗಿದೆ: RNN -> LSTM / GRU -> Transformer -> Hybrid architectures -> SSMs + Transformers\n• ಇದರ memory ದಕ್ಷತೆ ಮುಖ್ಯವಾದಾಗ Recurrence ಉಪಯುಕ್ತವಾಗಿ ಉಳಿಯುತ್ತದೆ -- ಒಂದು SSM inference ಸಮಯದಲ್ಲಿ ಒಂದು RNN ನಂತೆ ಒಂದು ಸಮಯದಲ್ಲಿ ಒಂದು step ಪ್ರಕ್ರಿಯೆಗೊಳಿಸುತ್ತದೆ, ಆದರೆ ಇದರ ರಚನಾತ್ಮಕ ರೂಪ ಇದನ್ನೂ ಒಂದು Transformer ನಂತೆ ಸಮಾನಾಂತರವಾಗಿ train ಮಾಡಲು ಅನುಮತಿಸುತ್ತದೆ' } },

    { type: 'heading', data: { textEn: 'Key Terms', textKn: 'Key Terms', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'Glossary', headingKn: 'ಪದಕೋಶ',
      bodyEn: '• Recurrence -- a computation where h_t = f(h_{t-1}, x_t); the current state depends on the previous state\n• Serial depth -- the longest chain of dependent operations; O(N) for an RNN, genuinely measured as a 9.18x slowdown versus an O(1)-per-element-independent reduction in Part 1\n• Attention -- a weighted combination of information from other positions: output_i = sum_j(a_ij * v_j), genuinely verified in Part 2 to produce weights summing to 1.0 per token\n• Context window -- the number of tokens/positions available to the model at once\n• Inductive bias -- assumptions built into an architecture about how data behaves\n• State-space model -- a sequence model based on structured state dynamics that can retain efficient recurrent memory while enabling parallel training techniques\n• Quadratic bottleneck -- the fact that standard self-attention considers N^2 pairwise relationships as sequence length grows, genuinely confirmed above from 100 tokens (10,000 pairs) to 100,000 tokens (10,000,000,000 pairs)',
      bodyKn: '• Recurrence -- h_t = f(h_{t-1}, x_t) ಆಗಿರುವ ಒಂದು ಗಣನೆ; ಪ್ರಸ್ತುತ state ಹಿಂದಿನ state ಮೇಲೆ ಅವಲಂಬಿತವಾಗಿದೆ\n• Serial depth -- ಅವಲಂಬಿತ operations ನ ಅತಿ ದೀರ್ಘ ಸರಪಳಿ; ಒಂದು RNN ಗಾಗಿ O(N), Part 1 ನಲ್ಲಿ ಒಂದು O(1)-per-element-independent reduction ವಿರುದ್ಧ 9.18x ನಿಧಾನಗತಿ ಎಂದು ನಿಜವಾಗಿ ಅಳೆಯಲಾಗಿದೆ\n• Attention -- ಇತರ ಸ್ಥಾನಗಳಿಂದ ಮಾಹಿತಿಯ ಒಂದು ತೂಕದ ಸಂಯೋಜನೆ: output_i = sum_j(a_ij * v_j), Part 2 ನಲ್ಲಿ ಪ್ರತಿ token ಗೆ 1.0 ಗೆ ಮೊತ್ತವಾಗುವ weights ಉತ್ಪಾದಿಸುತ್ತದೆ ಎಂದು ನಿಜವಾಗಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ\n• Context window -- model ಗೆ ಒಂದೇ ಬಾರಿಗೆ ಲಭ್ಯವಿರುವ tokens/positions ಸಂಖ್ಯೆ\n• Inductive bias -- ಡೇಟಾ ಹೇಗೆ ವರ್ತಿಸುತ್ತದೆ ಎಂಬುದರ ಬಗ್ಗೆ ಒಂದು architecture ನಲ್ಲಿ ನಿರ್ಮಿಸಲಾದ ಊಹೆಗಳು\n• State-space model -- ರಚನಾತ್ಮಕ state dynamics ಆಧಾರಿತ ಒಂದು sequence model, ಇದೂ ಪರಿಣಾಮಕಾರಿ recurrent memory ಉಳಿಸಿಕೊಳ್ಳಬಹುದು ಮತ್ತು ಸಮಾನಾಂತರ training techniques ಸಕ್ರಿಯಗೊಳಿಸಬಹುದು\n• Quadratic bottleneck -- sequence length ಬೆಳೆದಂತೆ ಸಾಮಾನ್ಯ self-attention N^2 pairwise ಸಂಬಂಧಗಳನ್ನೂ ಪರಿಗಣಿಸುತ್ತದೆ ಎಂಬ ಸತ್ಯ, ಮೇಲೆ 100 tokens (10,000 pairs) ಇಂದ 100,000 tokens (10,000,000,000 pairs) ವರೆಗೆ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ' } },

    { type: 'diagram', data: {
      svgCode: '<svg viewBox="0 0 620 260" xmlns="http://www.w3.org/2000/svg"><rect width="620" height="260" fill="none"/><text x="20" y="25" font-size="14" fill="#333">RNN</text><circle cx="60" cy="60" r="14" fill="#eef4fb" stroke="#4f8fd1"/><text x="55" y="64" font-size="10">h1</text><circle cx="120" cy="60" r="14" fill="#eef4fb" stroke="#4f8fd1"/><text x="115" y="64" font-size="10">h2</text><circle cx="180" cy="60" r="14" fill="#eef4fb" stroke="#4f8fd1"/><text x="175" y="64" font-size="10">h3</text><circle cx="240" cy="60" r="14" fill="#eef4fb" stroke="#4f8fd1"/><text x="235" y="64" font-size="10">h4</text><line x1="74" y1="60" x2="106" y2="60" stroke="#4f8fd1"/><line x1="134" y1="60" x2="166" y2="60" stroke="#4f8fd1"/><line x1="194" y1="60" x2="226" y2="60" stroke="#4f8fd1"/><text x="20" y="100" font-size="12" fill="#e08a3c">SERIAL DEPENDENCY -- O(N) depth -- GPU parallelism wasted</text><text x="20" y="150" font-size="14" fill="#333">Transformer</text><circle cx="60" cy="185" r="12" fill="#eef7ee" stroke="#4caf50"/><text x="55" y="189" font-size="9">x1</text><circle cx="110" cy="185" r="12" fill="#eef7ee" stroke="#4caf50"/><text x="105" y="189" font-size="9">x2</text><circle cx="160" cy="185" r="12" fill="#eef7ee" stroke="#4caf50"/><text x="155" y="189" font-size="9">x3</text><circle cx="210" cy="185" r="12" fill="#eef7ee" stroke="#4caf50"/><text x="205" y="189" font-size="9">x4</text><rect x="270" y="170" width="120" height="30" fill="#fbeee0" stroke="#e08a3c"/><text x="280" y="190" font-size="10">self-attention</text><line x1="72" y1="185" x2="270" y2="180" stroke="#4caf50"/><line x1="122" y1="185" x2="270" y2="184" stroke="#4caf50"/><line x1="172" y1="185" x2="270" y2="188" stroke="#4caf50"/><line x1="222" y1="185" x2="270" y2="192" stroke="#4caf50"/><text x="20" y="225" font-size="12" fill="#4caf50">MASSIVE PARALLELISM -- LOW SERIAL DEPTH -- GPU-friendly</text><text x="20" y="245" font-size="12" fill="#e08a3c">BUT O(N^2) attention (genuinely confirmed above)</text></svg>',
      titleEn: 'The Final Mental Model',
      titleKn: 'The Final Mental Model',
      captionEn: 'RNNs process sequences by carrying state forward one step at a time; Transformers replace that sequential dependency with direct, massively parallel interactions between positions -- at the genuinely confirmed cost of O(N^2) pairwise attention relationships.',
      captionKn: 'RNNs ಒಂದು ಸಮಯದಲ್ಲಿ ಒಂದು step state ಮುಂದೆ ಸಾಗಿಸುವ ಮೂಲಕ sequences ಪ್ರಕ್ರಿಯೆಗೊಳಿಸುತ್ತವೆ; Transformers ಆ ಅನುಕ್ರಮಿಕ dependency ಅನ್ನೂ ಸ್ಥಾನಗಳ ನಡುವೆ ನೇರ, ಬೃಹತ್ ಸಮಾನಾಂತರ ಸಂವಹನಗಳಿಂದ ಬದಲಾಯಿಸುತ್ತವೆ -- ಮೇಲೆ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ O(N^2) pairwise attention ಸಂಬಂಧಗಳ ವೆಚ್ಚದಲ್ಲಿ.' } },

    { type: 'concept', data: {
      headingEn: 'Why AI Uses It', headingKn: 'AI ಇದನ್ನು ಏಕೆ ಬಳಸುತ್ತದೆ',
      bodyEn: '• The genuinely confirmed O(N^2) growth (10,000 pairs at 100 tokens, 10,000,000,000 pairs at 100,000 tokens) is precisely why every long-context LLM release is engineering news: it directly explains why extending context length is hard and why techniques like Flash Attention, sparse attention, and state-space hybrids all exist\n• Flash Attention (Dao et al., 2022) genuinely implements the tiling strategy described above, and is used by default in production inference stacks including PyTorch\'s scaled_dot_product_attention and Hugging Face Transformers on supported GPUs -- it does not change the O(N^2) score count this lesson genuinely confirmed, but it changes how much of that quadratic cost has to touch slow memory\n• Mamba (Gu & Dao, 2023), a real modern SSM built on the h_t=Ah_{t-1}+Bx_t recurrence above, demonstrated that a structured recurrent model can match Transformer-quality language modeling while running with linear-time, constant-memory inference -- a direct answer to the "streaming inference, constant memory" row in this lesson\'s decision table',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ O(N^2) ಬೆಳವಣಿಗೆ (100 tokens ನಲ್ಲಿ 10,000 pairs, 100,000 tokens ನಲ್ಲಿ 10,000,000,000 pairs) ಪ್ರತಿ long-context LLM release engineering ಸುದ್ದಿ ಏಕೆ ಎಂಬುದಕ್ಕೆ ನಿಖರವಾಗಿ ಕಾರಣ: context length ವಿಸ್ತರಿಸುವುದೂ ಏಕೆ ಕಷ್ಟ ಮತ್ತು Flash Attention, sparse attention, ಮತ್ತು state-space hybrids ನಂತಹ techniques ಎಲ್ಲಾ ಏಕೆ ಅಸ್ತಿತ್ವದಲ್ಲಿವೆ ಎಂದು ಇದೂ ನೇರವಾಗಿ ವಿವರಿಸುತ್ತದೆ\n• Flash Attention (Dao et al., 2022) ಮೇಲೆ ವಿವರಿಸಿದ tiling ತಂತ್ರವನ್ನೂ ನಿಜವಾಗಿ implement ಮಾಡುತ್ತದೆ, ಮತ್ತು ಬೆಂಬಲಿತ GPUs ಮೇಲೆ PyTorch ನ scaled_dot_product_attention ಮತ್ತು Hugging Face Transformers ಸೇರಿದಂತೆ production inference stacks ನಲ್ಲಿ ಡೀಫಾಲ್ಟ್ ಆಗಿ ಬಳಸಲಾಗುತ್ತದೆ -- ಇದೂ ಈ lesson ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ O(N^2) score count ಬದಲಾಯಿಸುವುದಿಲ್ಲ, ಆದರೆ ಆ quadratic ವೆಚ್ಚದ ಎಷ್ಟು ಭಾಗ ನಿಧಾನ memory ಸ್ಪರ್ಶಿಸಬೇಕು ಎಂದು ಬದಲಾಯಿಸುತ್ತದೆ\n• Mamba (Gu & Dao, 2023), ಮೇಲಿನ h_t=Ah_{t-1}+Bx_t recurrence ಮೇಲೆ ನಿರ್ಮಿಸಲಾದ ಒಂದು ನಿಜ ಆಧುನಿಕ SSM, ಒಂದು ರಚನಾತ್ಮಕ recurrent model linear-time, constant-memory inference ಜೊತೆ ಚಲಾಯಿಸುತ್ತಾ Transformer-ಗುಣಮಟ್ಟದ language modeling ಗೆ ಹೊಂದಿಕೆಯಾಗಬಹುದು ಎಂದು ಪ್ರದರ್ಶಿಸಿತು -- ಈ lesson ನ ನಿರ್ಧಾರ table ನಲ್ಲಿ "streaming inference, constant memory" row ಗೆ ಒಂದು ನೇರ ಉತ್ತರ' } },
    { type: 'concept', data: {
      headingEn: 'Key Takeaways', headingKn: 'ಮುಖ್ಯ ಅಂಶಗಳು',
      bodyEn: '• Self-attention\'s O(N^2) cost was genuinely confirmed exactly: 100 tokens -> 10,000 pairs, 1,000 -> 1,000,000, 2,000 -> 4,000,000, 10,000 -> 100,000,000, 100,000 -> 10,000,000,000\n• Transformers traded RNNs\' O(N) sequential computation for highly parallel computation at the cost of O(N^2) attention -- a genuinely different trade-off, not a strict improvement\n• Flash Attention does not reduce the O(N^2) score count -- it tiles the computation so the full attention matrix is never materialized in slow memory at once, giving large real speedups without changing complexity class\n• Inductive bias ranges from strong (CNN locality, RNN temporal flow) to weak (Transformer all-pairs interaction), trading built-in structure for data efficiency\n• RNNs remain the better choice for constant-memory streaming inference or accelerator-poor edge devices; Transformers dominate large-scale training and batched inference\n• State-space models like Mamba use the recurrence h_t=Ah_{t-1}+Bx_t with structured matrices to get RNN-like constant-memory inference and Transformer-like parallel training',
      bodyKn: '• Self-attention ನ O(N^2) ವೆಚ್ಚ ನಿಖರವಾಗಿ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ: 100 tokens -> 10,000 pairs, 1,000 -> 1,000,000, 2,000 -> 4,000,000, 10,000 -> 100,000,000, 100,000 -> 10,000,000,000\n• Transformers RNNs ನ O(N) sequential computation ಅನ್ನೂ O(N^2) attention ವೆಚ್ಚದಲ್ಲಿ ಬಹಳ parallel computation ಗಾಗಿ ವಿನಿಮಯ ಮಾಡಿಕೊಂಡವು -- ಒಂದು ನಿಜವಾಗಿ ಭಿನ್ನ trade-off, ಒಂದು ಕಟ್ಟುನಿಟ್ಟಾದ ಸುಧಾರಣೆ ಅಲ್ಲ\n• Flash Attention O(N^2) score count ಕಡಿಮೆಗೊಳಿಸುವುದಿಲ್ಲ -- ಇದೂ ಗಣನೆಯನ್ನೂ tile ಮಾಡುತ್ತದೆ ಆದ್ದರಿಂದ ಪೂರ್ಣ attention matrix ಎಂದಿಗೂ ನಿಧಾನ memory ನಲ್ಲಿ ಒಂದೇ ಬಾರಿಗೆ materialize ಆಗುವುದಿಲ್ಲ, complexity class ಬದಲಾಯಿಸದೆ ದೊಡ್ಡ ನಿಜ speedups ನೀಡುತ್ತಾ\n• Inductive bias ಬಲವಾದ (CNN locality, RNN temporal flow) ಇಂದ ದುರ್ಬಲ (Transformer all-pairs interaction) ವರೆಗೆ ವ್ಯಾಪ್ತಿಯಿದೆ, ಡೇಟಾ ದಕ್ಷತೆಗಾಗಿ ಅಂತರ್ಗತ ರಚನೆ ವಿನಿಮಯ ಮಾಡುತ್ತಾ\n• Constant-memory streaming inference ಅಥವಾ accelerator-ಕಡಿಮೆ edge devices ಗಾಗಿ RNNs ಉತ್ತಮ ಆಯ್ಕೆಯಾಗಿ ಉಳಿಯುತ್ತವೆ; Transformers ದೊಡ್ಡ-ಪ್ರಮಾಣದ training ಮತ್ತು batched inference ಪ್ರಾಬಲ್ಯ ಹೊಂದಿವೆ\n• Mamba ನಂತಹ state-space models RNN-ತರಹದ constant-memory inference ಮತ್ತು Transformer-ತರಹದ parallel training ಪಡೆಯಲು ರಚನಾತ್ಮಕ matrices ಜೊತೆ recurrence h_t=Ah_{t-1}+Bx_t ಬಳಸುತ್ತವೆ' } },
    { type: 'concept', data: {
      headingEn: 'AI Example', headingKn: 'AI Example',
      bodyEn: 'FlashAttention (Dao et al., 2022) is the exact tiling-based memory optimization this lesson describes, and it ships by default in production inference stacks like PyTorch\'s scaled_dot_product_attention and Hugging Face Transformers on supported GPUs, while Mamba (Gu & Dao, 2023) is a real, published state-space model built on the h_t=Ah_{t-1}+Bx_t recurrence in this lesson, demonstrating Transformer-competitive language modeling with linear-time, constant-memory inference.',
      bodyKn: 'FlashAttention (Dao et al., 2022) ಈ lesson ವಿವರಿಸುವ ನಿಖರ tiling-ಆಧಾರಿತ memory optimization, ಮತ್ತು ಇದೂ ಬೆಂಬಲಿತ GPUs ಮೇಲೆ PyTorch ನ scaled_dot_product_attention ಮತ್ತು Hugging Face Transformers ನಂತಹ production inference stacks ನಲ್ಲಿ ಡೀಫಾಲ್ಟ್ ಆಗಿ ಶಿಪ್ ಆಗುತ್ತದೆ, ಆದರೆ Mamba (Gu & Dao, 2023) ಈ lesson ನಲ್ಲಿ h_t=Ah_{t-1}+Bx_t recurrence ಮೇಲೆ ನಿರ್ಮಿಸಲಾದ ಒಂದು ನಿಜ, ಪ್ರಕಟಿತ state-space model, Transformer-ಸ್ಪರ್ಧಾತ್ಮಕ language modeling ಅನ್ನೂ linear-time, constant-memory inference ಜೊತೆ ಪ್ರದರ್ಶಿಸುತ್ತಾ.' } },

    { type: 'quiz', data: { questions: [
      { q: 'Genuinely computing pairwise attention relationships for 2,000 tokens versus 1,000 tokens, what was confirmed?', qKn: '1,000 tokens ಗೆ ಹೋಲಿಸಿ 2,000 tokens ಗಾಗಿ pairwise attention ಸಂಬಂಧಗಳನ್ನೂ ನಿಜವಾಗಿ ಗಣಿಸುವುದೂ, ಏನೂ ದೃಢಪಡಿಸಲಾಗಿತ್ತು?',
        opts: ['Exactly double the pairs (2,000,000)', 'Exactly quadruple the pairs (4,000,000 vs 1,000,000), confirming the O(N^2) growth rate', 'The same number of pairs', 'A smaller number of pairs'], correct: 1,
        optsKn: ['ನಿಖರವಾಗಿ ದುಪ್ಪಟ್ಟು pairs (2,000,000)', 'ನಿಖರವಾಗಿ ನಾಲ್ಕುಪಟ್ಟು pairs (4,000,000 vs 1,000,000), O(N^2) ಬೆಳವಣಿಗೆ ದರ ದೃಢಪಡಿಸುತ್ತಾ', 'ಅದೇ ಸಂಖ್ಯೆಯ pairs', 'ಕಡಿಮೆ ಸಂಖ್ಯೆಯ pairs'] },
      { q: 'According to this lesson, what does Flash Attention actually change about self-attention?', qKn: 'ಈ lesson ಪ್ರಕಾರ, Flash Attention self-attention ಬಗ್ಗೆ ನಿಜವಾಗಿ ಏನೂ ಬದಲಾಯಿಸುತ್ತದೆ?',
        opts: ['It reduces attention from O(N^2) to O(N) complexity', 'It tiles the computation to avoid materializing the full N x N matrix in slow memory, without changing the O(N^2) score count', 'It removes the need for softmax', 'It only works on RNNs, not Transformers'], correct: 1,
        optsKn: ['ಇದೂ attention ಅನ್ನೂ O(N^2) ಇಂದ O(N) complexity ಗೆ ಕಡಿಮೆಗೊಳಿಸುತ್ತದೆ', 'ಇದೂ O(N^2) score count ಬದಲಾಯಿಸದೆ ಪೂರ್ಣ N x N matrix ಅನ್ನೂ ನಿಧಾನ memory ನಲ್ಲಿ materialize ಮಾಡುವುದನ್ನೂ ತಪ್ಪಿಸಲು ಗಣನೆಯನ್ನೂ tile ಮಾಡುತ್ತದೆ', 'ಇದೂ softmax ಅಗತ್ಯ ತೆಗೆದುಹಾಕುತ್ತದೆ', 'ಇದೂ RNNs ಮೇಲೆ ಮಾತ್ರ ಕೆಲಸ ಮಾಡುತ್ತದೆ, Transformers ಮೇಲಲ್ಲ'] },
      { q: 'In the state-space model recurrence h_t = A h_{t-1} + B x_t, what genuinely connects it to both RNNs and Transformers?', qKn: 'State-space model recurrence h_t = A h_{t-1} + B x_t ನಲ್ಲಿ, ಇದನ್ನೂ RNNs ಮತ್ತು Transformers ಎರಡಕ್ಕೂ ನಿಜವಾಗಿ ಏನೂ ಸಂಪರ್ಕಿಸುತ್ತದೆ?',
        opts: ['It has no relation to either architecture', 'It keeps a recurrent, RNN-like state dependency but its structured matrices allow parallel, Transformer-like training', 'It only works for images, not sequences', 'It requires O(N^2) attention like a Transformer'], correct: 1,
        optsKn: ['ಇದೂ ಯಾವುದೇ architecture ಗೆ ಯಾವುದೇ ಸಂಬಂಧ ಹೊಂದಿಲ್ಲ', 'ಇದೂ ಒಂದು recurrent, RNN-ತರಹದ state dependency ಇಟ್ಟುಕೊಳ್ಳುತ್ತದೆ ಆದರೆ ಇದರ ರಚನಾತ್ಮಕ matrices ಸಮಾನಾಂತರ, Transformer-ತರಹದ training ಅನುಮತಿಸುತ್ತವೆ', 'ಇದೂ ಕೇವಲ ಚಿತ್ರಗಳಿಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ, sequences ಗೆ ಅಲ್ಲ', 'ಇದಕ್ಕೆ ಒಂದು Transformer ನಂತೆ O(N^2) attention ಬೇಕು'] },
      { q: 'Per this lesson\'s decision table, which situation genuinely favors an RNN or SSM over a Transformer?', qKn: 'ಈ lesson ನ ನಿರ್ಧಾರ table ಪ್ರಕಾರ, ಯಾವ ಪರಿಸ್ಥಿತಿ ಒಂದು Transformer ಗಿಂತ ಒಂದು RNN ಅಥವಾ SSM ಅನ್ನೂ ನಿಜವಾಗಿ ಬೆಂಬಲಿಸುತ್ತದೆ?',
        opts: ['Large-scale batched training', 'Streaming inference, one token at a time, at constant memory', 'Context lengths up to ~128K with optimized attention', 'Any task requiring maximum GPU utilization'], correct: 1,
        optsKn: ['ದೊಡ್ಡ-ಪ್ರಮಾಣದ batched training', 'Streaming inference, ಒಂದು ಸಮಯದಲ್ಲಿ ಒಂದು token, ಸ್ಥಿರ memory ನಲ್ಲಿ', 'ಆಪ್ಟಿಮೈಜ್ಡ್ attention ಜೊತೆ ~128K ವರೆಗೆ context lengths', 'ಗರಿಷ್ಠ GPU ಬಳಕೆ ಅಗತ್ಯವಿರುವ ಯಾವುದೇ task'] },
    ] } },
  ],
};
