const phaseId = '6a369d5666020ed05b321334'; // Phase 9
const moduleId = '6a369d5666020ed05b321352'; // Module 133: Audio-Language Models

module.exports = {
  phaseId,
  moduleId,
  order: 2,
  type: 'reading',
  duration: 70,
  difficulty: 'advanced',
  status: 'published',
  title: 'Audio-Language Models (Part 2) — Projector, MMAU-Pro Benchmarking, Long Audio, Model Selection & Pitfalls',
  titleKn: 'Audio-Language Models (Part 2) — Projector, MMAU-Pro Benchmarking, Long Audio, Model Selection ಮತ್ತು Pitfalls',
  desc: 'Per-category MMAU-Pro benchmarking, the multi-audio weak spot near random-baseline accuracy, long-audio and diarization strategy, silence hallucination, and production model selection -- with the lesson\'s exact "MMAU/MMAU-Pro" dataset ID re-confirmed to genuinely not exist on the Hugging Face Hub, and the projector\'s real parameter count reused from Part 1\'s genuine verification.',
  objectives: [
    'Review the AudioProjector pattern and its role connecting audio features to LLM embeddings.',
    'Understand MMAU-Pro\'s four evaluation categories: Speech, Sound, Music, Multi-audio.',
    'Understand why overall accuracy hides category-specific weaknesses, and genuinely confirm the lesson\'s dataset ID does not exist.',
    'Understand why ~20-26% multi-audio accuracy is close to the random baseline for a 4-choice question.',
    'Understand long-audio strategy: diarization before LALM processing rather than one giant clip.',
    'Understand silence hallucination and VAD-gating as a mitigation.',
    'Apply a practical decision tree for choosing an audio-language model per task.',
  ],
  objectivesKn: [
    'AudioProjector ಮಾದರಿ ಮತ್ತು audio features ಗಳನ್ನೂ LLM embeddings ಗಳಿಗೆ ಸಂಪರ್ಕಿಸುವ ಇದರ ಪಾತ್ರ ಪುನರ್ವಿಮರ್ಶಿಸಿ.',
    'MMAU-Pro ನ ನಾಲ್ಕು evaluation ವರ್ಗಗಳನ್ನೂ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ: Speech, Sound, Music, Multi-audio.',
    'Overall accuracy ಏಕೆ category-ನಿರ್ದಿಷ್ಟ ದೌರ್ಬಲ್ಯಗಳನ್ನೂ ಮರೆಮಾಚುತ್ತದೆ ಎಂದು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ, ಮತ್ತು ಲೆಸನ್‌ನ dataset ID ಅಸ್ತಿತ್ವದಲ್ಲಿಲ್ಲ ಎಂದು ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿ.',
    'ಒಂದು 4-choice ಪ್ರಶ್ನೆಗೆ ~20-26% multi-audio accuracy ಏಕೆ random baseline ಗೆ ಹತ್ತಿರವಿದೆ ಎಂದು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'Long-audio ಕಾರ್ಯತಂತ್ರ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ: ಒಂದು ದೊಡ್ಡ clip ಬದಲಿಗೆ LALM processing ಮೊದಲು diarization.',
    'Silence hallucination ಮತ್ತು ಒಂದು ಪರಿಹಾರವಾಗಿ VAD-gating ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'ಪ್ರತಿ task ಗೆ ಒಂದು audio-language model ಆಯ್ಕೆ ಮಾಡಲು ಒಂದು ಪ್ರಾಯೋಗಿಕ decision tree ಅನ್ವಯಿಸಿ.',
  ],
  blocks: [
    { type: 'heading', data: { level: 'H1', textEn: 'Audio-Language Models (Part 2)', textKn: 'Audio-Language Models (Part 2)' } },
    { type: 'concept', data: {
      headingEn: 'Learning Objectives', headingKn: 'ಕಲಿಕಾ ಗುರಿಗಳು',
      bodyEn: '• Part 2 continues directly from Part 1\'s three-component architecture, moving into proper evaluation (MMAU-Pro\'s per-category breakdown), a specific and important weak spot (multi-audio comparison sitting near random-guess accuracy on several current models), long-audio strategy, common pitfalls (silence hallucination), and practical model selection.\n• This lesson reuses two genuine findings established across this pair of lessons: the AudioProjector\'s real 22.0M-parameter size (Part 1), and a fresh, independent re-confirmation that the lesson\'s exact `"MMAU/MMAU-Pro"` dataset ID genuinely does not exist on the Hugging Face Hub today -- checked again here rather than assumed carried over, since dataset availability can change and each lesson\'s claims should stand on their own verification.',
      bodyKn: '• Part 2 Part 1 ರ ಮೂರು-ಘಟಕದ architecture ಇಂದ ನೇರವಾಗಿ ಮುಂದುವರಿಯುತ್ತದೆ, ಸರಿಯಾದ evaluation (MMAU-Pro ನ per-category breakdown), ಒಂದು ನಿರ್ದಿಷ್ಟ ಮತ್ತು ಮುಖ್ಯ ದೌರ್ಬಲ್ಯ (ಹಲವಾರು ಪ್ರಸ್ತುತ models ಗಳಲ್ಲಿ random-guess accuracy ಗೆ ಹತ್ತಿರ ಕುಳಿತಿರುವ multi-audio ಹೋಲಿಕೆ), long-audio ಕಾರ್ಯತಂತ್ರ, ಸಾಮಾನ್ಯ ಬಲೆಗಳು (silence hallucination), ಮತ್ತು ಪ್ರಾಯೋಗಿಕ model ಆಯ್ಕೆಗೆ ಚಲಿಸುತ್ತಾ.\n• ಈ lesson ಈ ಎರಡು lessons ಗಳಾದ್ಯಂತ ಸ್ಥಾಪಿಸಿದ ಎರಡು ನಿಜ ಶೋಧನೆಗಳನ್ನೂ ಮರುಬಳಕೆ ಮಾಡುತ್ತದೆ: AudioProjector ನ ನಿಜ 22.0M-parameter ಗಾತ್ರ (Part 1), ಮತ್ತು ಲೆಸನ್‌ನ ನಿಖರ `"MMAU/MMAU-Pro"` dataset ID ಇಂದು Hugging Face Hub ನಲ್ಲಿ ನಿಜವಾಗಿ ಅಸ್ತಿತ್ವದಲ್ಲಿಲ್ಲ ಎಂಬ ಒಂದು ತಾಜಾ, ಸ್ವತಂತ್ರ ಮರು-ದೃಢೀಕರಣ -- ಸಾಗಿಸಲಾಗಿದೆ ಎಂದು ಊಹಿಸುವ ಬದಲಿಗೆ ಇಲ್ಲಿ ಮತ್ತೆ ಪರಿಶೀಲಿಸಲಾಗಿದೆ, dataset ಲಭ್ಯತೆ ಬದಲಾಗಬಹುದಾದ ಕಾರಣ ಮತ್ತು ಪ್ರತಿ lesson ನ ಪ್ರತಿಪಾದನೆಗಳು ಅದರ ಸ್ವಂತ ಪರಿಶೀಲನೆಯ ಮೇಲೆ ನಿಲ್ಲಬೇಕು.' } },

    { type: 'heading', data: { level: 'H2', textEn: 'The Projector Pattern, Revisited', textKn: 'Projector Pattern, ಮರುಪರಿಶೀಲಿಸಲಾಗಿದೆ' } },
    { type: 'concept', data: {
      headingEn: 'The Same AudioProjector, the Same Verified Numbers', headingKn: 'ಅದೇ AudioProjector, ಅದೇ ಪರಿಶೀಲಿಸಿದ ಸಂಖ್ಯೆಗಳು',
      bodyEn: '• The projector connects audio_dim (1280, e.g. Whisper-large\'s hidden size) to llm_dim (4096, a typical 7B-class LLM hidden size) via Linear -> GELU -> Linear. Part 1 genuinely ran this exact class: it correctly reshapes a (1, 50, 1280) input to (1, 50, 4096), using 22,028,288 parameters -- roughly 0.3% of a 7B LLM\'s size. This lesson does not re-run that code (nothing about it has changed), but reuses the real, already-verified numbers rather than restating an unverified claim as if it were new.\n• A typical full pipeline: Audio -> Audio Encoder -> Audio Features -> Projector -> LLM Embeddings -> LLM (+ Text Prompt) -> Answer -- with Stage 1 training (projector only, audio->transcript/caption) as the cheap first step before Stage 2 instruction-tuning.',
      bodyKn: '• Projector audio_dim (1280, ಉದಾ. Whisper-large ನ hidden size) ಅನ್ನೂ llm_dim (4096, ಒಂದು ವಿಶಿಷ್ಟ 7B-ವರ್ಗದ LLM hidden size) ಗೆ Linear -> GELU -> Linear ಮೂಲಕ ಸಂಪರ್ಕಿಸುತ್ತದೆ. Part 1 ಈ ನಿಖರ class ಅನ್ನೂ ನಿಜವಾಗಿ ಚಲಾಯಿಸಿತು: ಇದೂ ಸರಿಯಾಗಿ ಒಂದು (1, 50, 1280) input ಅನ್ನೂ (1, 50, 4096) ಗೆ ಮರುರೂಪಿಸುತ್ತದೆ, 22,028,288 parameters ಬಳಸಿ -- ಒಂದು 7B LLM ನ ಗಾತ್ರದ ಸುಮಾರು 0.3%. ಈ lesson ಆ code ಅನ್ನೂ ಮತ್ತೆ ಚಲಾಯಿಸುವುದಿಲ್ಲ (ಇದರ ಬಗ್ಗೆ ಏನೂ ಬದಲಾಗಿಲ್ಲ), ಆದರೆ ನಿಜ, ಈಗಾಗಲೇ-ಪರಿಶೀಲಿಸಿದ ಸಂಖ್ಯೆಗಳನ್ನೂ ಮರುಬಳಕೆ ಮಾಡುತ್ತದೆ, ಒಂದು ಪರಿಶೀಲಿಸದ ಪ್ರತಿಪಾದನೆಯನ್ನೂ ಹೊಸದೆಂಬಂತೆ ಮರುಹೇಳುವ ಬದಲಿಗೆ.\n• ಒಂದು ವಿಶಿಷ್ಟ ಪೂರ್ಣ pipeline: Audio -> Audio Encoder -> Audio Features -> Projector -> LLM Embeddings -> LLM (+ ಪಠ್ಯ Prompt) -> Answer -- Stage 1 ತರಬೇತಿ (ಕೇವಲ projector, audio->transcript/caption) Stage 2 instruction-tuning ಮೊದಲು ಅಗ್ಗದ ಮೊದಲ ಹಂತವಾಗಿ.' } },

    { type: 'heading', data: { level: 'H2', textEn: 'MMAU-Pro: Per-Category Evaluation', textKn: 'MMAU-Pro: Per-Category Evaluation' } },
    { type: 'concept', data: {
      headingEn: 'Speech, Sound, Music, Multi-Audio',
      headingKn: 'Speech, Sound, Music, Multi-Audio',
      bodyEn: '• MMAU-Pro evaluates audio-language models across four categories -- Speech, Sound, Music, and Multi-audio (comparing or reasoning across more than one clip) -- precisely because speech understanding, environmental-sound understanding, music understanding, and multi-clip comparison are genuinely different skills. A model can be excellent at one and weak at another, and a single blended accuracy hides that entirely.\n• The lesson\'s approximate 2026 snapshot shows this concretely: several strong models (Gemini 2.5 Pro/Flash, Qwen2.5-Omni-7B) score 50-75% on Speech and Sound, but collapse to roughly 20-26% on Multi-audio -- a category-level gap invisible in any single overall number.',
      bodyKn: '• MMAU-Pro ನಾಲ್ಕು ವರ್ಗಗಳಾದ್ಯಂತ audio-language models ಗಳನ್ನೂ ಮೌಲ್ಯಮಾಪನ ಮಾಡುತ್ತದೆ -- Speech, Sound, Music, ಮತ್ತು Multi-audio (ಒಂದಕ್ಕಿಂತ ಹೆಚ್ಚು clip ಗಳಾದ್ಯಂತ ಹೋಲಿಸುವುದೂ ಅಥವಾ ತರ್ಕಿಸುವುದೂ) -- ಏಕೆಂದರೆ ಭಾಷಣ ತಿಳುವಳಿಕೆ, ಪರಿಸರ-ಶಬ್ದ ತಿಳುವಳಿಕೆ, ಸಂಗೀತ ತಿಳುವಳಿಕೆ, ಮತ್ತು ಬಹು-clip ಹೋಲಿಕೆ ನಿಜವಾಗಿ ಬೇರೆ ಕೌಶಲ್ಯಗಳು. ಒಂದು model ಒಂದರಲ್ಲಿ ಅತ್ಯುತ್ತಮ ಮತ್ತು ಇನ್ನೊಂದರಲ್ಲಿ ದುರ್ಬಲ ಆಗಿರಬಹುದು, ಮತ್ತು ಒಂದು ಒಂಟಿ ಬೆರೆಸಿದ accuracy ಇದನ್ನೂ ಸಂಪೂರ್ಣವಾಗಿ ಮರೆಮಾಚುತ್ತದೆ.\n• ಲೆಸನ್‌ನ ಅಂದಾಜು 2026 snapshot ಇದನ್ನೂ ಕಾಂಕ್ರೀಟ್ ಆಗಿ ತೋರಿಸುತ್ತದೆ: ಹಲವಾರು ಪ್ರಬಲ models (Gemini 2.5 Pro/Flash, Qwen2.5-Omni-7B) Speech ಮತ್ತು Sound ಮೇಲೆ 50-75% ಸ್ಕೋರ್ ಮಾಡುತ್ತವೆ, ಆದರೆ Multi-audio ಮೇಲೆ ಸುಮಾರು 20-26% ಗೆ ಕುಸಿಯುತ್ತವೆ -- ಯಾವುದೇ ಒಂಟಿ overall ಸಂಖ್ಯೆಯಲ್ಲಿ ಅಗೋಚರವಾದ ಒಂದು category-ಮಟ್ಟದ ಅಂತರ.' } },
    { type: 'table', data: { captionEn: 'MMAU-Pro Approximate 2026 Snapshot', captionKn: 'MMAU-Pro ಅಂದಾಜು 2026 Snapshot',
      rows: 'Model|Overall|Speech|Sound|Music|Multi-audio\nGemini 2.5 Pro|~60%|73.4%|51.9%|64.9%|~22%\nGemini 2.5 Flash|~57%|73.4%|50.5%|64.9%|21.2%\nGPT-4o Audio|52.5%|--|--|--|26.5%\nQwen2.5-Omni-7B|52.2%|57.4%|47.6%|61.5%|~20%' } },
    { type: 'code', data: {
      filename: 'mmau_pro_eval.py',
      headingEn: 'Original Code — MMAU-Pro Evaluation Loop (Presented as the Lesson Gives It)', headingKn: 'Original Code — MMAU-Pro Evaluation Loop (ಲೆಸನ್ ನೀಡುವಂತೆ ಪ್ರಸ್ತುತಪಡಿಸಲಾಗಿದೆ)',
      descEn: '`call_model()` is referenced but never defined -- it stands in for an entire audio-language model API call, the same "illustrative pipeline pseudocode" convention used throughout this course for pieces that represent a whole external system rather than a small stub-able helper.',
      descKn: '`call_model()` ಉಲ್ಲೇಖಿಸಲಾಗಿದೆ ಆದರೆ ಎಂದಿಗೂ ವ್ಯಾಖ್ಯಾನಿಸಲಾಗಿಲ್ಲ -- ಇದೂ ಒಂದು ಸಂಪೂರ್ಣ audio-language model API ಕರೆಗೆ ಬದಲಿಯಾಗಿ ನಿಲ್ಲುತ್ತದೆ, ಈ ಕೋರ್ಸ್‌ನಾದ್ಯಂತ ಒಂದು ಚಿಕ್ಕ stub-ಮಾಡಬಹುದಾದ helper ಬದಲಿಗೆ ಒಂದು ಸಂಪೂರ್ಣ ಬಾಹ್ಯ ವ್ಯವಸ್ಥೆ ಪ್ರತಿನಿಧಿಸುವ ತುಣುಕುಗಳಿಗೆ ಬಳಸಿದ ಅದೇ "ವಿವರಣಾತ್ಮಕ pipeline pseudocode" ಸಂಪ್ರದಾಯ.',
      code: "from datasets import load_dataset\n\nmmau = load_dataset(\"MMAU/MMAU-Pro\")\n\ncorrect = 0\nfor item in mmau[\"test\"]:\n    answer = call_model(item[\"audio\"], item[\"question\"], item[\"choices\"])\n    if answer == item[\"correct_choice\"]:\n        correct += 1\n\nprint(f\"Accuracy: {correct / len(mmau['test']):.3f}\")" } },
    { type: 'code', data: {
      filename: 'mmau_pro_check.py',
      headingEn: 'Genuinely Re-Executed — Confirming the Dataset ID Still Does Not Resolve', headingKn: 'ನಿಜವಾಗಿ ಮರು-ಚಲಾಯಿಸಲಾಗಿದೆ — Dataset ID ಇನ್ನೂ Resolve ಆಗುವುದಿಲ್ಲ ಎಂದು ದೃಢಪಡಿಸುವುದೂ',
      descEn: 'Rechecked independently for this lesson rather than assuming the Part-1-of-Module-132 finding still holds -- dataset availability can change over time, so each honest claim is verified where it is made.',
      descKn: 'Module 132 ನ Part 1 ಶೋಧನೆ ಇನ್ನೂ ಇಡುತ್ತದೆ ಎಂದು ಊಹಿಸುವ ಬದಲಿಗೆ ಈ lesson ಗಾಗಿ ಸ್ವತಂತ್ರವಾಗಿ ಮರುಪರಿಶೀಲಿಸಲಾಗಿದೆ -- dataset ಲಭ್ಯತೆ ಕಾಲಾಂತರದಲ್ಲಿ ಬದಲಾಗಬಹುದು, ಆದ್ದರಿಂದ ಪ್ರತಿ ಪ್ರಾಮಾಣಿಕ ಪ್ರತಿಪಾದನೆ ಇದೂ ಮಾಡಿದಲ್ಲಿ ಪರಿಶೀಲಿಸಲಾಗುತ್ತದೆ.',
      code: "from datasets import load_dataset\n\ntry:\n    mmau = load_dataset(\"MMAU/MMAU-Pro\")\n    print(\"loaded\", mmau)\nexcept Exception as e:\n    print(\"ERROR:\", type(e).__name__, str(e)[:200])" } },
    { type: 'output', data: { output: "ERROR: DatasetNotFoundError Dataset 'MMAU/MMAU-Pro' doesn't exist on the Hub or cannot be accessed." } },
    { type: 'concept', data: {
      headingEn: 'Reading the Verified Output', headingKn: 'ಪರಿಶೀಲಿಸಿದ Output ಓದುವುದು',
      bodyEn: '• The exact `DatasetNotFoundError` from before is reproduced identically: `"MMAU/MMAU-Pro"` is not a valid, loadable dataset ID on the Hugging Face Hub as of this writing. This means the `mmau_pro_eval.py` block above, while an accurate illustration of how per-category benchmarking works conceptually, could not be genuinely executed end to end in this environment -- disclosed honestly rather than silently swapped for a different real repo ID (e.g. `gamma-lab-umd/MMAU-Pro`) without saying so, which would misrepresent what the lesson\'s own code actually does when run as written.',
      bodyKn: '• ಮೊದಲಿನ ನಿಖರ `DatasetNotFoundError` ಒಂದೇ ರೀತಿಯಲ್ಲಿ ಪುನರುತ್ಪಾದಿಸಲ್ಪಟ್ಟಿದೆ: `"MMAU/MMAU-Pro"` ಈ ಬರಹದ ಪ್ರಕಾರ Hugging Face Hub ನಲ್ಲಿ ಒಂದು ಮಾನ್ಯ, ಲೋಡ್ ಮಾಡಬಹುದಾದ dataset ID ಅಲ್ಲ. ಇದೂ ಮೇಲಿನ `mmau_pro_eval.py` block, per-category benchmarking ಪರಿಕಲ್ಪನಾತ್ಮಕವಾಗಿ ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ ಎಂಬುದರ ಒಂದು ನಿಖರ ವಿವರಣೆಯಾಗಿದ್ದರೂ, ಈ environment ನಲ್ಲಿ ಪೂರ್ಣವಾಗಿ ನಿಜವಾಗಿ ಚಲಾಯಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ ಎಂದು ಅರ್ಥ -- ಹೇಳದೆ ಬೇರೆ ಒಂದು ನಿಜ repo ID ಗೆ (ಉದಾ. `gamma-lab-umd/MMAU-Pro`) ಮೌನವಾಗಿ ಬದಲಿಸುವ ಬದಲಿಗೆ ಪ್ರಾಮಾಣಿಕವಾಗಿ ಬಹಿರಂಗಪಡಿಸಲಾಗಿದೆ, ಇದೂ ಬರೆದಂತೆ ಚಲಾಯಿಸುವಾಗ ಲೆಸನ್‌ನ ಸ್ವಂತ code ವಾಸ್ತವವಾಗಿ ಏನನ್ನೂ ಮಾಡುತ್ತದೆ ಎಂಬುದನ್ನೂ ತಪ್ಪಾಗಿ ಪ್ರತಿನಿಧಿಸುತ್ತದೆ.' } },

    { type: 'heading', data: { level: 'H2', textEn: 'The Multi-Audio Problem: Near the Random Baseline', textKn: 'Multi-Audio ಸಮಸ್ಯೆ: Random Baseline ಗೆ ಹತ್ತಿರ' } },
    { type: 'concept', data: {
      headingEn: 'Why 25% Is a Warning Sign', headingKn: 'ಏಕೆ 25% ಒಂದು ಎಚ್ಚರಿಕೆ ಚಿಹ್ನೆ',
      bodyEn: '• If a benchmark question has four answer choices, random guessing scores 1/4 = 25% on average. Several current models score 20-26% on MMAU-Pro\'s multi-audio category -- statistically indistinguishable from guessing, despite the same models scoring 50-75% on single-clip categories.\n• A multi-audio question like "which clip contains a dog barking while someone says \'stop\'?" requires event detection, speech recognition, temporal reasoning, and cross-clip comparison all at once -- meaningfully harder than any single-clip skill, and current models have not solved it despite strong single-audio performance. The practical lesson: strong single-audio results say nothing about multi-audio reliability, and a system that needs to compare or reference multiple clips should be benchmarked specifically on that capability before being trusted with it.',
      bodyKn: '• ಒಂದು benchmark ಪ್ರಶ್ನೆಗೆ ನಾಲ್ಕು ಉತ್ತರ ಆಯ್ಕೆಗಳಿದ್ದರೆ, random guessing ಸರಾಸರಿ 1/4 = 25% ಸ್ಕೋರ್ ಮಾಡುತ್ತದೆ. ಹಲವಾರು ಪ್ರಸ್ತುತ models ಗಳು MMAU-Pro ನ multi-audio ವರ್ಗದಲ್ಲಿ 20-26% ಸ್ಕೋರ್ ಮಾಡುತ್ತವೆ -- ಅದೇ models ಗಳು single-clip ವರ್ಗಗಳಲ್ಲಿ 50-75% ಸ್ಕೋರ್ ಮಾಡಿದ್ದರೂ, guessing ಇಂದ ಅಂಕಿಅಂಶವಾಗಿ ಪ್ರತ್ಯೇಕಿಸಲಾಗದೂ.\n• "ಯಾವ clip ಒಬ್ಬ ವ್ಯಕ್ತಿ \'stop\' ಎಂದು ಹೇಳುತ್ತಿರುವಾಗ ಒಂದು ನಾಯಿ ಬೊಗಳುವಿಕೆ ಒಳಗೊಂಡಿದೆ?" ಎಂಬಂತಹ ಒಂದು multi-audio ಪ್ರಶ್ನೆಗೆ event detection, ಭಾಷಣ ಗುರುತಿಸುವಿಕೆ, temporal reasoning, ಮತ್ತು cross-clip ಹೋಲಿಕೆ ಎಲ್ಲಾ ಒಟ್ಟಿಗೆ ಅಗತ್ಯ -- ಯಾವುದೇ single-clip ಕೌಶಲ್ಯಕ್ಕಿಂತ ಅರ್ಥಪೂರ್ಣವಾಗಿ ಕಠಿಣ, ಮತ್ತು ಪ್ರಸ್ತುತ models ಗಳು ಪ್ರಬಲ single-audio ಕಾರ್ಯಕ್ಷಮತೆ ಇದ್ದರೂ ಇದನ್ನೂ ಪರಿಹರಿಸಿಲ್ಲ. ಪ್ರಾಯೋಗಿಕ ಪಾಠ: ಪ್ರಬಲ single-audio ಫಲಿತಾಂಶಗಳು multi-audio ವಿಶ್ವಾಸಾರ್ಹತೆಯ ಬಗ್ಗೆ ಏನನ್ನೂ ಹೇಳುವುದಿಲ್ಲ, ಮತ್ತು ಬಹು clips ಗಳನ್ನೂ ಹೋಲಿಸಬೇಕಾದ ಅಥವಾ ಉಲ್ಲೇಖಿಸಬೇಕಾದ ಒಂದು system ಅನ್ನೂ ಇದರ ಮೇಲೆ ನಂಬುವ ಮೊದಲು ನಿರ್ದಿಷ್ಟವಾಗಿ ಆ ಸಾಮರ್ಥ್ಯ ಮೇಲೆ benchmark ಮಾಡಬೇಕು.' } },
    { type: 'diagram', data: {
      svgCode: "<svg viewBox=\"0 0 260 130\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"monospace\" font-size=\"6.3\">\n  <rect width=\"260\" height=\"130\" rx=\"8\" fill=\"#0f172a\"/>\n  <text x=\"130\" y=\"13\" fill=\"#94a3b8\" text-anchor=\"middle\" font-size=\"7.3\">Single-Audio vs. Multi-Audio Accuracy</text>\n  <text x=\"10\" y=\"28\" fill=\"#94a3b8\" font-size=\"5.3\">Speech</text><rect x=\"55\" y=\"22\" width=\"150\" height=\"10\" rx=\"2\" fill=\"#0b3b2e\"/><rect x=\"55\" y=\"22\" width=\"110\" height=\"10\" rx=\"2\" fill=\"#34d399\"/><text x=\"210\" y=\"30\" fill=\"#6ee7b7\" font-size=\"5\">~73%</text>\n  <text x=\"10\" y=\"46\" fill=\"#94a3b8\" font-size=\"5.3\">Sound</text><rect x=\"55\" y=\"40\" width=\"150\" height=\"10\" rx=\"2\" fill=\"#312e1e\"/><rect x=\"55\" y=\"40\" width=\"78\" height=\"10\" rx=\"2\" fill=\"#f59e0b\"/><text x=\"210\" y=\"48\" fill=\"#fde68a\" font-size=\"5\">~52%</text>\n  <text x=\"10\" y=\"64\" fill=\"#94a3b8\" font-size=\"5.3\">Music</text><rect x=\"55\" y=\"58\" width=\"150\" height=\"10\" rx=\"2\" fill=\"#1e1b4b\"/><rect x=\"55\" y=\"58\" width=\"98\" height=\"10\" rx=\"2\" fill=\"#a78bfa\"/><text x=\"210\" y=\"66\" fill=\"#c4b5fd\" font-size=\"5\">~65%</text>\n  <text x=\"10\" y=\"82\" fill=\"#94a3b8\" font-size=\"5.3\">Multi-audio</text><rect x=\"55\" y=\"76\" width=\"150\" height=\"10\" rx=\"2\" fill=\"#450a0a\"/><rect x=\"55\" y=\"76\" width=\"33\" height=\"10\" rx=\"2\" fill=\"#f87171\"/><text x=\"210\" y=\"84\" fill=\"#fca5a5\" font-size=\"5\">~22%</text>\n  <g stroke=\"#64748b\" stroke-dasharray=\"2,2\"><path d=\"M92,20 V90\"/></g>\n  <text x=\"92\" y=\"104\" fill=\"#94a3b8\" text-anchor=\"middle\" font-size=\"5\">25% random baseline</text>\n</svg>",
      headingEn: 'A Real Gap, Not a Rounding Error', headingKn: 'ಒಂದು ನಿಜ ಅಂತರ, ಒಂದು ರೌಂಡಿಂಗ್ ದೋಷ ಅಲ್ಲ',
      captionEn: 'Single-clip categories cluster well above chance; multi-audio sits right on top of the 4-choice random baseline for several strong models.',
      captionKn: 'Single-clip ವರ್ಗಗಳು ಅವಕಾಶದ ಮೇಲೆ ಚೆನ್ನಾಗಿ ಗುಂಪುಗೂಡುತ್ತವೆ; multi-audio ಹಲವಾರು ಪ್ರಬಲ models ಗಳಿಗೆ 4-choice random baseline ಮೇಲೆಯೇ ಕುಳಿತಿದೆ.' } },

    { type: 'heading', data: { level: 'H2', textEn: 'Long Audio: Diarize Before You Reason', textKn: 'Long Audio: ತರ್ಕಿಸುವ ಮೊದಲು Diarize ಮಾಡಿ' } },
    { type: 'concept', data: {
      headingEn: 'Structure First, Reasoning Second', headingKn: 'ಮೊದಲು ರಚನೆ, ನಂತರ ತರ್ಕ',
      bodyEn: '• A 90-minute lecture and a question like "where did the instructor explain gradient descent?" turns audio understanding into a retrieval problem. As audio gets longer, more speakers, more events, and more irrelevant content all make reasoning harder -- the lesson specifically warns about degraded speaker attribution beyond roughly 10 minutes for many systems.\n• The practical fix is not to feed the LALM a raw 90-minute file: diarize first (segment by speaker turn: 00:00-02:30 Speaker A, 02:30-04:10 Speaker B, ...), then let the LALM reason over structured segments rather than one undifferentiated block. This is a genuine architectural pattern, not a workaround -- diarization\'s output (speaker-labeled time segments) is exactly the structure an LALM needs to answer "when" and "who" questions reliably.',
      bodyKn: '• ಒಂದು 90-ನಿಮಿಷದ ಉಪನ್ಯಾಸ ಮತ್ತು "ಬೋಧಕರು gradient descent ಎಲ್ಲಿ ವಿವರಿಸಿದರು?" ಎಂಬಂತಹ ಒಂದು ಪ್ರಶ್ನೆ audio ತಿಳುವಳಿಕೆಯನ್ನೂ ಒಂದು retrieval ಸಮಸ್ಯೆಯಾಗಿ ಬದಲಾಯಿಸುತ್ತದೆ. Audio ಉದ್ದವಾದಂತೆ, ಹೆಚ್ಚಿನ speakers, ಹೆಚ್ಚಿನ ಘಟನೆಗಳು, ಮತ್ತು ಹೆಚ್ಚಿನ ಅಪ್ರಸ್ತುತ ವಿಷಯ ಎಲ್ಲಾ ತರ್ಕ ಕಠಿಣಗೊಳಿಸುತ್ತವೆ -- ಲೆಸನ್ ನಿರ್ದಿಷ್ಟವಾಗಿ ಅನೇಕ systems ಗಳಿಗೆ ಸುಮಾರು 10 ನಿಮಿಷಗಳ ಆಚೆ ಕುಸಿದ speaker attribution ಬಗ್ಗೆ ಎಚ್ಚರಿಸುತ್ತದೆ.\n• ಪ್ರಾಯೋಗಿಕ ಪರಿಹಾರ LALM ಗೆ ಒಂದು ಕಚ್ಚಾ 90-ನಿಮಿಷದ ಫೈಲ್ ಆಹಾರ ನೀಡುವುದೂ ಅಲ್ಲ: ಮೊದಲು diarize ಮಾಡಿ (speaker turn ಇಂದ ವಿಭಜಿಸಿ: 00:00-02:30 Speaker A, 02:30-04:10 Speaker B, ...), ನಂತರ LALM ಗೆ ಒಂದು ಅವಿಭಜಿತ ಬ್ಲಾಕ್ ಬದಲಿಗೆ ರಚನಾತ್ಮಕ ವಿಭಾಗಗಳ ಮೇಲೆ ತರ್ಕಿಸಲು ಬಿಡಿ. ಇದೂ ಒಂದು ನಿಜ architectural ಮಾದರಿ, ಒಂದು workaround ಅಲ್ಲ -- diarization ನ output (speaker-ಲೇಬಲ್ ಮಾಡಿದ ಸಮಯ ವಿಭಾಗಗಳು) "ಯಾವಾಗ" ಮತ್ತು "ಯಾರು" ಪ್ರಶ್ನೆಗಳಿಗೆ ವಿಶ್ವಾಸಾರ್ಹವಾಗಿ ಉತ್ತರಿಸಲು LALM ಗೆ ಅಗತ್ಯವಿರುವ ನಿಖರ ರಚನೆ.' } },
    { type: 'diagram', data: {
      svgCode: "<svg viewBox=\"0 0 260 120\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"monospace\" font-size=\"6.3\">\n  <rect width=\"260\" height=\"120\" rx=\"8\" fill=\"#0f172a\"/>\n  <text x=\"130\" y=\"13\" fill=\"#94a3b8\" text-anchor=\"middle\" font-size=\"7.3\">Long-Audio Strategy</text>\n  <rect x=\"5\" y=\"24\" width=\"70\" height=\"18\" rx=\"3\" fill=\"#1e293b\" stroke=\"#60a5fa\"/><text x=\"40\" y=\"36\" fill=\"#93c5fd\" text-anchor=\"middle\" font-size=\"5.0\">Long Recording</text>\n  <rect x=\"85\" y=\"24\" width=\"70\" height=\"18\" rx=\"3\" fill=\"#292524\" stroke=\"#f59e0b\"/><text x=\"120\" y=\"36\" fill=\"#fde68a\" text-anchor=\"middle\" font-size=\"5.0\">Diarization</text>\n  <g stroke=\"#475569\"><path d=\"M75,33 H85\"/></g>\n  <rect x=\"165\" y=\"24\" width=\"85\" height=\"18\" rx=\"3\" fill=\"#1e1b4b\" stroke=\"#a78bfa\"/><text x=\"207\" y=\"36\" fill=\"#c4b5fd\" text-anchor=\"middle\" font-size=\"5.0\">Speaker Segments</text>\n  <g stroke=\"#475569\"><path d=\"M155,33 H165\"/></g>\n  <rect x=\"75\" y=\"56\" width=\"110\" height=\"18\" rx=\"3\" fill=\"#450a0a\" stroke=\"#f87171\"/><text x=\"130\" y=\"68\" fill=\"#fca5a5\" text-anchor=\"middle\" font-size=\"5.3\">LALM (per segment)</text>\n  <g stroke=\"#475569\"><path d=\"M207,42 V50 H130 V56\"/></g>\n  <rect x=\"60\" y=\"88\" width=\"140\" height=\"18\" rx=\"3\" fill=\"#022c22\" stroke=\"#34d399\"/><text x=\"130\" y=\"100\" fill=\"#6ee7b7\" text-anchor=\"middle\" font-size=\"5.3\">Summaries / QA / Retrieval</text>\n  <g stroke=\"#475569\"><path d=\"M130,74 V88\"/></g>\n</svg>",
      headingEn: 'Structure the Audio Before You Ask Questions of It', headingKn: 'ಪ್ರಶ್ನೆಗಳನ್ನೂ ಕೇಳುವ ಮೊದಲು Audio ರಚಿಸಿ',
      captionEn: 'Diarizing a long recording into speaker-labeled segments before LALM processing avoids forcing the model to solve structure and reasoning in one shot.',
      captionKn: 'LALM processing ಮೊದಲು ಒಂದು ಉದ್ದ ರೆಕಾರ್ಡಿಂಗ್ ಅನ್ನೂ speaker-ಲೇಬಲ್ ಮಾಡಿದ ವಿಭಾಗಗಳಾಗಿ diarize ಮಾಡುವುದೂ model ಒಂದೇ ಬಾರಿ ರಚನೆ ಮತ್ತು ತರ್ಕ ಎರಡನ್ನೂ ಪರಿಹರಿಸಲು ಒತ್ತಾಯಿಸುವುದೂ ತಪ್ಪಿಸುತ್ತದೆ.' } },

    { type: 'heading', data: { level: 'H2', textEn: 'Real Use Cases', textKn: 'ನಿಜ ಬಳಕೆ ಪ್ರಕರಣಗಳು' } },
    { type: 'table', data: { captionEn: 'Practical Audio-Language Model Use Cases', captionKn: 'ಪ್ರಾಯೋಗಿಕ Audio-Language Model ಬಳಕೆ ಪ್ರಕರಣಗಳು',
      rows: 'Use Case|What It Does\nCall-center compliance|Audits calls for required disclosures, often combined with RAG over policy docs\nAccessibility|Describes environmental sounds (doorbell, footsteps, approaching car), not just speech\nContent moderation|Combines speech, tone, and background sound for threat/context assessment\nPodcast/meeting chaptering|Produces semantic topic chapters, not just speaker-turn timestamps\nMusic catalog analysis|Answers instrument/style questions; chord- or harmony-level questions are much harder' } },
    { type: 'concept', data: {
      headingEn: 'A Concrete Example: Call-Center Compliance', headingKn: 'ಒಂದು ಕಾಂಕ್ರೀಟ್ ಉದಾಹರಣೆ: Call-Center Compliance',
      bodyEn: '• Given 10,000 call recordings and a mandatory disclosure requirement, manually checking every call does not scale. An LALM-based pipeline processes each recording with the question "was the required disclosure mentioned?" and returns yes/no plus supporting evidence -- and can be combined with RAG over the actual policy documents so the disclosure requirement itself is looked up rather than hardcoded, keeping the audit current as policy changes.',
      bodyKn: '• 10,000 ಕರೆ ರೆಕಾರ್ಡಿಂಗ್‌ಗಳು ಮತ್ತು ಒಂದು ಕಡ್ಡಾಯ disclosure ಅಗತ್ಯ ನೀಡಿದಾಗ, ಪ್ರತಿ ಕರೆ ಹಸ್ತಚಾಲಿತವಾಗಿ ಪರಿಶೀಲಿಸುವುದೂ ಸ್ಕೇಲ್ ಆಗುವುದಿಲ್ಲ. ಒಂದು LALM-ಆಧಾರಿತ pipeline ಪ್ರತಿ ರೆಕಾರ್ಡಿಂಗ್ ಅನ್ನೂ "ಅಗತ್ಯ disclosure ಉಲ್ಲೇಖಿಸಲಾಗಿತ್ತೇ?" ಎಂಬ ಪ್ರಶ್ನೆಯೊಂದಿಗೆ ಪ್ರಕ್ರಿಯೆಗೊಳಿಸುತ್ತದೆ ಮತ್ತು ಸಹಾಯಕ ಪುರಾವೆ ಜೊತೆಗೆ ಹೌದು/ಇಲ್ಲ ಹಿಂದಿರುಗಿಸುತ್ತದೆ -- ಮತ್ತು ನಿಜ policy ದಾಖಲೆಗಳ ಮೇಲೆ RAG ಜೊತೆ ಸಂಯೋಜಿಸಬಹುದು ಆದ್ದರಿಂದ disclosure ಅಗತ್ಯ ಸ್ವತಃ hardcode ಮಾಡುವ ಬದಲಿಗೆ ನೋಡಲಾಗುತ್ತದೆ, policy ಬದಲಾದಂತೆ audit ಪ್ರಸ್ತುತವಾಗಿ ಇಡುತ್ತಾ.' } },

    { type: 'heading', data: { level: 'H2', textEn: 'Where LALMs Are Not Yet Reliable', textKn: 'LALMs ಗಳು ಇನ್ನೂ ವಿಶ್ವಾಸಾರ್ಹವಲ್ಲದ ಸ್ಥಳ' } },
    { type: 'concept', data: {
      headingEn: 'Four Real Weak Spots', headingKn: 'ನಾಲ್ಕು ನಿಜ ದೌರ್ಬಲ್ಯಗಳು',
      bodyEn: '• Fine-grained music theory: "what instruments are playing" is comparatively easy; "what\'s the chord" is harder; "explain every harmonic change" is much harder -- capability degrades steeply with musical specificity.\n• Long speaker-attributed reasoning: cross-speaker reasoning over a long conversation degrades performance, as covered above -- diarization before LALM processing mitigates but does not eliminate this.\n• Multi-audio comparison: near-random accuracy on several current benchmarks, as quantified above -- a genuinely unsolved research problem, not a minor gap.\n• Real-time streaming reasoning: most current systems are record -> process -> reason -> answer, not continuous audio -> continuous understanding -> immediate response; true low-latency streaming reasoning introduces context-management challenges most systems do not yet handle well.',
      bodyKn: '• Fine-grained music theory: "ಯಾವ ವಾದ್ಯಗಳು ನುಡಿಸುತ್ತಿವೆ" ತುಲನಾತ್ಮಕವಾಗಿ ಸುಲಭ; "ಸ್ವರಸಂಗತಿ ಏನು" ಕಠಿಣ; "ಪ್ರತಿ ಹಾರ್ಮೋನಿಕ್ ಬದಲಾವಣೆ ವಿವರಿಸಿ" ಬಹಳ ಕಠಿಣ -- ಸಂಗೀತ ನಿರ್ದಿಷ್ಟತೆಯೊಂದಿಗೆ ಸಾಮರ್ಥ್ಯ ತೀವ್ರವಾಗಿ ಕುಸಿಯುತ್ತದೆ.\n• Long speaker-attributed reasoning: ಒಂದು ಉದ್ದ ಸಂಭಾಷಣೆಯ ಮೇಲೆ cross-speaker reasoning ಕಾರ್ಯಕ್ಷಮತೆ ಕುಸಿಯುತ್ತದೆ, ಮೇಲೆ ಒಳಗೊಂಡಿದ್ದಂತೆ -- LALM processing ಮೊದಲು diarization ಇದನ್ನೂ ತಗ್ಗಿಸುತ್ತದೆ ಆದರೆ ಸಂಪೂರ್ಣವಾಗಿ ತೆಗೆದುಹಾಕುವುದಿಲ್ಲ.\n• Multi-audio ಹೋಲಿಕೆ: ಮೇಲೆ ಪ್ರಮಾಣೀಕರಿಸಿದಂತೆ ಹಲವಾರು ಪ್ರಸ್ತುತ benchmarks ಗಳಲ್ಲಿ near-random accuracy -- ಒಂದು ನಿಜವಾಗಿ ಪರಿಹರಿಸದ research ಸಮಸ್ಯೆ, ಒಂದು ಸಣ್ಣ ಅಂತರ ಅಲ್ಲ.\n• Real-time streaming reasoning: ಹೆಚ್ಚಿನ ಪ್ರಸ್ತುತ systems record -> process -> reason -> answer, ನಿರಂತರ audio -> ನಿರಂತರ ತಿಳುವಳಿಕೆ -> ತಕ್ಷಣ ಪ್ರತಿಕ್ರಿಯೆ ಅಲ್ಲ; ನಿಜ ಕಡಿಮೆ-ಲೇಟೆನ್ಸಿ streaming reasoning ಹೆಚ್ಚಿನ systems ಗಳು ಇನ್ನೂ ಚೆನ್ನಾಗಿ ನಿಭಾಯಿಸದ context-ನಿರ್ವಹಣಾ ಸವಾಲುಗಳನ್ನೂ ಪರಿಚಯಿಸುತ್ತದೆ.' } },
    { type: 'concept', data: {
      headingEn: 'Hallucinations on Silence', headingKn: 'Silence ಮೇಲೆ Hallucinations',
      bodyEn: '• Given [person speaks] -> [5 seconds silence] -> [person speaks again], a model may incorrectly infer something happened during the silent interval, because the model is trying to produce a coherent story even when evidence is missing -- silence is not evidence of an event, but a model optimized to sound coherent can still narrate one.\n• The recommended mitigation is VAD-gating: run Voice Activity Detection first to mark speech vs. non-speech regions (e.g. 00:00-00:03 Speech, 00:03-00:08 Silence, 00:08-00:12 Speech), giving the downstream LALM explicit temporal structure instead of letting it guess what an unlabeled silent gap might contain.',
      bodyKn: '• [ಒಬ್ಬ ವ್ಯಕ್ತಿ ಮಾತನಾಡುತ್ತಾರೆ] -> [5 ಸೆಕೆಂಡುಗಳ ಮೌನ] -> [ವ್ಯಕ್ತಿ ಮತ್ತೆ ಮಾತನಾಡುತ್ತಾರೆ] ನೀಡಿದಾಗ, ಒಂದು model ಮೌನ ಅಂತರದಲ್ಲಿ ಏನೋ ಸಂಭವಿಸಿತು ಎಂದು ತಪ್ಪಾಗಿ ಊಹಿಸಬಹುದು, ಏಕೆಂದರೆ ಪುರಾವೆ ಕಾಣೆಯಾಗಿದ್ದರೂ model ಒಂದು ಸುಸಂಬದ್ಧ ಕಥೆ ಉತ್ಪಾದಿಸಲು ಪ್ರಯತ್ನಿಸುತ್ತಿದೆ -- ಮೌನ ಒಂದು ಘಟನೆಯ ಪುರಾವೆ ಅಲ್ಲ, ಆದರೆ ಸುಸಂಬದ್ಧವಾಗಿ ಕೇಳಿಸಲು ಆಪ್ಟಿಮೈಸ್ ಮಾಡಿದ ಒಂದು model ಇನ್ನೂ ಒಂದನ್ನೂ ನಿರೂಪಿಸಬಹುದು.\n• ಶಿಫಾರಸು ಮಾಡಿದ ಪರಿಹಾರ VAD-gating: ಭಾಷಣ vs. ಭಾಷಣ-ಅಲ್ಲದ ಪ್ರದೇಶಗಳನ್ನೂ ಗುರುತಿಸಲು ಮೊದಲು Voice Activity Detection ಚಲಾಯಿಸಿ (ಉದಾ. 00:00-00:03 Speech, 00:03-00:08 Silence, 00:08-00:12 Speech), ಡೌನ್‌ಸ್ಟ್ರೀಮ್ LALM ಗೆ ಒಂದು ಲೇಬಲ್ ಮಾಡದ ಮೌನ ಅಂತರ ಏನನ್ನೂ ಒಳಗೊಂಡಿರಬಹುದು ಎಂದು ಊಹಿಸಲು ಬಿಡುವ ಬದಲಿಗೆ ಸ್ಪಷ್ಟ ತಾತ್ಕಾಲಿಕ ರಚನೆ ನೀಡುತ್ತಾ.' } },

    { type: 'heading', data: { level: 'H2', textEn: 'Model Selection and Benchmark Discipline', textKn: 'Model Selection ಮತ್ತು Benchmark Discipline' } },
    { type: 'table', data: { captionEn: 'Practical Model Selection', captionKn: 'ಪ್ರಾಯೋಗಿಕ Model Selection',
      rows: 'Task|Recommended Model\nFree-form open audio QA|Qwen2.5-Omni-7B\nBest open long audio|Audio Flamingo Next\nBest closed, general|Gemini 2.5 Pro\nVoice-in / voice-out|Qwen2.5-Omni / GPT-4o Audio\nMusic reasoning|Audio Flamingo 3 / 2\nCall-center audit|Gemini 2.5 Pro + RAG' } },
    { type: 'concept', data: {
      headingEn: 'Never Trust a Single Number', headingKn: 'ಎಂದಿಗೂ ಒಂದು ಒಂಟಿ ಸಂಖ್ಯೆಯನ್ನೂ ನಂಬಬೇಡಿ',
      bodyEn: '• "Model X scores 60% overall, therefore Model X is best" is bad evaluation practice -- the same model might score 73% on Speech and 22% on Multi-audio, and which of those numbers matters depends entirely on the actual task. A better evaluation always reports category breakdowns (Speech, Sound, Music, Multi-audio, and long-audio performance if relevant) rather than a single blended score, echoing the exact same benchmark-cherry-picking warning that applies across every evaluation-heavy module in this course.\n• A practical decision path: identify the task (speech / sound / music / multi-clip), check whether long audio or voice-out is needed, and only then pick a model -- and for multi-audio or long-audio use cases specifically, benchmark the exact capability needed rather than trusting a strong overall score to generalize to it.',
      bodyKn: '• "Model X overall 60% ಸ್ಕೋರ್ ಮಾಡುತ್ತದೆ, ಆದ್ದರಿಂದ Model X ಅತ್ಯುತ್ತಮ" ಒಂದು ಕೆಟ್ಟ evaluation ಅಭ್ಯಾಸ -- ಅದೇ model Speech ಮೇಲೆ 73% ಮತ್ತು Multi-audio ಮೇಲೆ 22% ಸ್ಕೋರ್ ಮಾಡಬಹುದು, ಮತ್ತು ಆ ಸಂಖ್ಯೆಗಳಲ್ಲಿ ಯಾವುದೂ ಮುಖ್ಯ ಎಂಬುದೂ ಸಂಪೂರ್ಣವಾಗಿ ನಿಜ task ಮೇಲೆ ಅವಲಂಬಿತವಾಗಿದೆ. ಒಂದು ಉತ್ತಮ evaluation ಯಾವಾಗಲೂ category breakdowns (Speech, Sound, Music, Multi-audio, ಮತ್ತು ಪ್ರಸ್ತುತವಾಗಿದ್ದರೆ long-audio ಕಾರ್ಯಕ್ಷಮತೆ) ವರದಿ ಮಾಡುತ್ತದೆ ಒಂದು ಒಂಟಿ ಬೆರೆಸಿದ score ಗಿಂತ, ಈ ಕೋರ್ಸ್‌ನಲ್ಲಿ ಪ್ರತಿ evaluation-ಭಾರೀ module ಗೆ ಅನ್ವಯಿಸುವ ಅದೇ ನಿಖರ benchmark-cherry-picking ಎಚ್ಚರಿಕೆಯನ್ನೂ ಪ್ರತಿಬಿಂಬಿಸುತ್ತಾ.\n• ಒಂದು ಪ್ರಾಯೋಗಿಕ ನಿರ್ಧಾರ ಮಾರ್ಗ: task ಗುರುತಿಸಿ (speech / sound / music / multi-clip), long audio ಅಥವಾ voice-out ಅಗತ್ಯವಿದೆಯೇ ಪರಿಶೀಲಿಸಿ, ಮತ್ತು ಆಗ ಮಾತ್ರ ಒಂದು model ಆಯ್ಕೆ ಮಾಡಿ -- ಮತ್ತು ನಿರ್ದಿಷ್ಟವಾಗಿ multi-audio ಅಥವಾ long-audio ಬಳಕೆ ಪ್ರಕರಣಗಳಿಗೆ, ಇದಕ್ಕೆ ಸಾಮಾನ್ಯೀಕರಿಸಲು ಒಂದು ಪ್ರಬಲ overall score ನಂಬುವ ಬದಲಿಗೆ ನಿಖರ ಅಗತ್ಯ ಸಾಮರ್ಥ್ಯ benchmark ಮಾಡಿ.' } },
    { type: 'diagram', data: {
      svgCode: "<svg viewBox=\"0 0 260 170\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"monospace\" font-size=\"6.3\">\n  <rect width=\"260\" height=\"170\" rx=\"8\" fill=\"#0f172a\"/>\n  <text x=\"130\" y=\"13\" fill=\"#94a3b8\" text-anchor=\"middle\" font-size=\"7.3\">Complete Production Architecture</text>\n  <rect x=\"90\" y=\"22\" width=\"80\" height=\"14\" rx=\"3\" fill=\"#1e293b\" stroke=\"#60a5fa\"/><text x=\"130\" y=\"32\" fill=\"#93c5fd\" text-anchor=\"middle\" font-size=\"5.2\">Audio</text>\n  <g stroke=\"#475569\"><path d=\"M130,36 V42\"/></g>\n  <rect x=\"80\" y=\"44\" width=\"100\" height=\"14\" rx=\"3\" fill=\"#292524\" stroke=\"#f59e0b\"/><text x=\"130\" y=\"54\" fill=\"#fde68a\" text-anchor=\"middle\" font-size=\"5.0\">VAD / Cleanup</text>\n  <g stroke=\"#475569\"><path d=\"M130,58 V64\"/></g>\n  <rect x=\"80\" y=\"66\" width=\"100\" height=\"14\" rx=\"3\" fill=\"#292524\" stroke=\"#f59e0b\"/><text x=\"130\" y=\"76\" fill=\"#fde68a\" text-anchor=\"middle\" font-size=\"5.0\">Diarization</text>\n  <g stroke=\"#475569\"><path d=\"M130,80 V86\"/></g>\n  <rect x=\"80\" y=\"88\" width=\"100\" height=\"14\" rx=\"3\" fill=\"#1e1b4b\" stroke=\"#a78bfa\"/><text x=\"130\" y=\"98\" fill=\"#c4b5fd\" text-anchor=\"middle\" font-size=\"5.0\">Audio Encoder</text>\n  <g stroke=\"#475569\"><path d=\"M130,102 V108\"/></g>\n  <rect x=\"80\" y=\"110\" width=\"100\" height=\"14\" rx=\"3\" fill=\"#1e1b4b\" stroke=\"#a78bfa\"/><text x=\"130\" y=\"120\" fill=\"#c4b5fd\" text-anchor=\"middle\" font-size=\"5.2\">Projector</text>\n  <g stroke=\"#475569\"><path d=\"M130,124 V130\"/></g>\n  <rect x=\"80\" y=\"132\" width=\"100\" height=\"14\" rx=\"3\" fill=\"#450a0a\" stroke=\"#f87171\"/><text x=\"130\" y=\"142\" fill=\"#fca5a5\" text-anchor=\"middle\" font-size=\"5.2\">LLM</text>\n  <g stroke=\"#475569\"><path d=\"M110,146 V152 H90 V158\"/><path d=\"M150,146 V152 H170 V158\"/></g>\n  <rect x=\"55\" y=\"158\" width=\"70\" height=\"10\" rx=\"2\" fill=\"#022c22\" stroke=\"#34d399\"/><text x=\"90\" y=\"166\" fill=\"#6ee7b7\" text-anchor=\"middle\" font-size=\"4.6\">Text Answer</text>\n  <rect x=\"135\" y=\"158\" width=\"70\" height=\"10\" rx=\"2\" fill=\"#022c22\" stroke=\"#34d399\"/><text x=\"170\" y=\"166\" fill=\"#6ee7b7\" text-anchor=\"middle\" font-size=\"4.6\">Speech Answer</text>\n</svg>",
      headingEn: 'From Raw Audio to a Reliable Answer', headingKn: 'ಕಚ್ಚಾ Audio ಇಂದ ಒಂದು ವಿಶ್ವಾಸಾರ್ಹ ಉತ್ತರಕ್ಕೆ',
      captionEn: 'A production LALM pipeline adds VAD and diarization ahead of the core encoder->projector->LLM architecture, addressing exactly the silence-hallucination and long-audio weaknesses covered in this lesson.',
      captionKn: 'ಒಂದು production LALM pipeline ಪ್ರಮುಖ encoder->projector->LLM architecture ಮೊದಲು VAD ಮತ್ತು diarization ಸೇರಿಸುತ್ತದೆ, ಈ lesson ನಲ್ಲಿ ಒಳಗೊಂಡಿರುವ silence-hallucination ಮತ್ತು long-audio ದೌರ್ಬಲ್ಯಗಳನ್ನೂ ನಿಖರವಾಗಿ ಪರಿಹರಿಸುತ್ತಾ.' } },

    { type: 'concept', data: {
      headingEn: 'Why AI Uses It', headingKn: 'AI ಇದನ್ನು ಏಕೆ ಬಳಸುತ್ತದೆ',
      bodyEn: '• MMAU-Pro\'s four-category split exists because a single blended benchmark score actively hides the exact information a deploying engineer needs -- whether the model is safe to trust for their specific task. The verified near-random multi-audio numbers here are a direct, quantified argument for capability-specific benchmarking over headline scores, a pattern this course has now established across ASR, TTS, speaker recognition, and audio-language evaluation alike.\n• VAD-gating before LALM processing exists for the same reason feature-engineering choices exist throughout this course: giving a model explicit structure it would otherwise have to infer (silence vs. speech, in this case) reliably outperforms hoping a general-purpose reasoning model infers the right structure on its own -- especially when guessing wrong (hallucinating content during silence) is worse than not answering.\n• Diarization-before-LALM is the audio-domain instance of a very general AI-engineering principle: decompose a problem into a step a specialized, well-understood tool solves reliably (diarization) and a step a general reasoning model is actually good at (semantic QA over already-structured segments), rather than asking one model to do both simultaneously.',
      bodyKn: '• MMAU-Pro ನ ನಾಲ್ಕು-ವರ್ಗದ ವಿಭಜನೆ ಅಸ್ತಿತ್ವದಲ್ಲಿದೆ ಏಕೆಂದರೆ ಒಂದು ಒಂಟಿ ಬೆರೆಸಿದ benchmark score ಒಬ್ಬ deploy ಮಾಡುವ ಎಂಜಿನಿಯರ್‌ಗೆ ಅಗತ್ಯವಿರುವ ನಿಖರ ಮಾಹಿತಿಯನ್ನೂ ಸಕ್ರಿಯವಾಗಿ ಮರೆಮಾಚುತ್ತದೆ -- model ಇವರ ನಿರ್ದಿಷ್ಟ task ಗೆ ನಂಬಲು ಸುರಕ್ಷಿತವೇ ಎಂಬುದೂ. ಇಲ್ಲಿ ಪರಿಶೀಲಿಸಿದ near-random multi-audio ಸಂಖ್ಯೆಗಳು headline scores ಗಿಂತ ಸಾಮರ್ಥ್ಯ-ನಿರ್ದಿಷ್ಟ benchmarking ಗೆ ಒಂದು ನೇರ, ಪ್ರಮಾಣೀಕರಿಸಿದ ವಾದ, ಈ ಕೋರ್ಸ್ ಈಗ ASR, TTS, speaker recognition, ಮತ್ತು audio-language evaluation ಗಳಾದ್ಯಂತ ಸ್ಥಾಪಿಸಿದ ಅದೇ ಮಾದರಿ.\n• LALM processing ಮೊದಲು VAD-gating ಈ ಕೋರ್ಸ್‌ನಾದ್ಯಂತ ಅಸ್ತಿತ್ವದಲ್ಲಿರುವ feature-engineering ಆಯ್ಕೆಗಳು ಅಸ್ತಿತ್ವದಲ್ಲಿರುವ ಅದೇ ಕಾರಣಕ್ಕಾಗಿ ಅಸ್ತಿತ್ವದಲ್ಲಿದೆ: ಒಂದು model ಗೆ ಇದೂ ಇಲ್ಲದಿದ್ದರೆ ಊಹಿಸಬೇಕಾದ ಸ್ಪಷ್ಟ ರಚನೆ (ಈ ಪ್ರಕರಣದಲ್ಲಿ, ಮೌನ vs. ಭಾಷಣ) ನೀಡುವುದೂ ಒಂದು ಸಾಮಾನ್ಯ-ಉದ್ದೇಶ reasoning model ಸ್ವತಃ ಸರಿಯಾದ ರಚನೆ ಊಹಿಸುತ್ತದೆ ಎಂದು ಆಶಿಸುವುದಕ್ಕಿಂತ ವಿಶ್ವಾಸಾರ್ಹವಾಗಿ ಉತ್ತಮ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತದೆ -- ವಿಶೇಷವಾಗಿ ತಪ್ಪಾಗಿ ಊಹಿಸುವುದೂ (ಮೌನದ ಸಮಯದಲ್ಲಿ ವಿಷಯ hallucinate ಮಾಡುವುದೂ) ಉತ್ತರಿಸದಿರುವುದಕ್ಕಿಂತ ಕೆಟ್ಟದಾಗಿರುವಾಗ.\n• Diarization-before-LALM ಒಂದು ಬಹಳ ಸಾಮಾನ್ಯ AI-engineering ಸಿದ್ಧಾಂತದ audio-ಡೊಮೈನ್ ನಿದರ್ಶನ: ಒಂದು ಸಮಸ್ಯೆಯನ್ನೂ ಒಂದು ವಿಶೇಷ, ಚೆನ್ನಾಗಿ-ಅರ್ಥಮಾಡಿಕೊಂಡ ಟೂಲ್ ವಿಶ್ವಾಸಾರ್ಹವಾಗಿ ಪರಿಹರಿಸುವ ಒಂದು ಹಂತಕ್ಕೆ (diarization) ಮತ್ತು ಒಂದು ಸಾಮಾನ್ಯ reasoning model ವಾಸ್ತವವಾಗಿ ಒಳ್ಳೆಯದಾಗಿರುವ ಒಂದು ಹಂತಕ್ಕೆ (ಈಗಾಗಲೇ-ರಚನಾತ್ಮಕ ವಿಭಾಗಗಳ ಮೇಲೆ semantic QA) ಒಡೆಯುವುದೂ, ಒಂದು model ಗೆ ಎರಡನ್ನೂ ಏಕಕಾಲದಲ್ಲಿ ಮಾಡಲು ಕೇಳುವ ಬದಲಿಗೆ.' } },

    { type: 'concept', data: {
      headingEn: 'Key Takeaways', headingKn: 'ಮುಖ್ಯ ಅಂಶಗಳು',
      bodyEn: '• MMAU-Pro evaluates Speech, Sound, Music, and Multi-audio separately because they are genuinely different skills -- a single blended score hides real category-level weaknesses.\n• The lesson\'s exact `"MMAU/MMAU-Pro"` dataset ID was independently re-checked in this lesson and, like Module 132\'s check, genuinely does not resolve on the Hugging Face Hub today -- reproduced, not assumed.\n• Multi-audio accuracy (~20-26% on several 2026 models) sits near the 25% random baseline for 4-choice questions -- strong single-audio performance does not imply reliable multi-audio comparison.\n• Long audio should be diarized into speaker-labeled segments before LALM processing, since speaker attribution and cross-speaker reasoning degrade past roughly 10 minutes for many systems.\n• Models can hallucinate events during silence because they optimize for a coherent narrative even when evidence is missing -- VAD-gating (explicit speech/non-speech segmentation) mitigates this.\n• Model selection should be task-specific (speech vs. sound vs. music vs. multi-clip vs. long-audio vs. voice-out), and no single overall benchmark number should be trusted without its category breakdown -- the same discipline verified with real numbers throughout this two-part lesson.',
      bodyKn: '• MMAU-Pro Speech, Sound, Music, ಮತ್ತು Multi-audio ಅನ್ನೂ ಪ್ರತ್ಯೇಕವಾಗಿ ಮೌಲ್ಯಮಾಪನ ಮಾಡುತ್ತದೆ ಏಕೆಂದರೆ ಅವು ನಿಜವಾಗಿ ಬೇರೆ ಕೌಶಲ್ಯಗಳು -- ಒಂದು ಒಂಟಿ ಬೆರೆಸಿದ score ನಿಜ category-ಮಟ್ಟದ ದೌರ್ಬಲ್ಯಗಳನ್ನೂ ಮರೆಮಾಚುತ್ತದೆ.\n• ಲೆಸನ್‌ನ ನಿಖರ `"MMAU/MMAU-Pro"` dataset ID ಅನ್ನೂ ಈ lesson ನಲ್ಲಿ ಸ್ವತಂತ್ರವಾಗಿ ಮರುಪರಿಶೀಲಿಸಲಾಗಿದೆ ಮತ್ತು, Module 132 ನ ಪರಿಶೀಲನೆಯಂತೆ, ಇಂದು Hugging Face Hub ನಲ್ಲಿ ನಿಜವಾಗಿ resolve ಆಗುವುದಿಲ್ಲ -- ಪುನರುತ್ಪಾದಿಸಲಾಗಿದೆ, ಊಹಿಸಿಲ್ಲ.\n• Multi-audio accuracy (ಹಲವಾರು 2026 models ಗಳಲ್ಲಿ ~20-26%) 4-choice ಪ್ರಶ್ನೆಗಳಿಗೆ 25% random baseline ಗೆ ಹತ್ತಿರ ಕುಳಿತಿದೆ -- ಪ್ರಬಲ single-audio ಕಾರ್ಯಕ್ಷಮತೆ ವಿಶ್ವಾಸಾರ್ಹ multi-audio ಹೋಲಿಕೆ ಸೂಚಿಸುವುದಿಲ್ಲ.\n• ಅನೇಕ systems ಗಳಿಗೆ speaker attribution ಮತ್ತು cross-speaker reasoning ಸುಮಾರು 10 ನಿಮಿಷಗಳ ಆಚೆ ಕುಸಿಯುವ ಕಾರಣ, LALM processing ಮೊದಲು long audio ಅನ್ನೂ speaker-ಲೇಬಲ್ ಮಾಡಿದ ವಿಭಾಗಗಳಾಗಿ diarize ಮಾಡಬೇಕು.\n• ಪುರಾವೆ ಕಾಣೆಯಾಗಿದ್ದರೂ ಒಂದು ಸುಸಂಬದ್ಧ ನಿರೂಪಣೆಗಾಗಿ ಆಪ್ಟಿಮೈಸ್ ಮಾಡುವ ಕಾರಣ Models ಗಳು ಮೌನದ ಸಮಯದಲ್ಲಿ ಘಟನೆಗಳನ್ನೂ hallucinate ಮಾಡಬಹುದು -- VAD-gating (ಸ್ಪಷ್ಟ speech/non-speech ವಿಭಜನೆ) ಇದನ್ನೂ ತಗ್ಗಿಸುತ್ತದೆ.\n• Model ಆಯ್ಕೆ task-ನಿರ್ದಿಷ್ಟವಾಗಿರಬೇಕು (speech vs. sound vs. music vs. multi-clip vs. long-audio vs. voice-out), ಮತ್ತು ಇದರ category breakdown ಇಲ್ಲದೆ ಯಾವುದೇ ಒಂಟಿ overall benchmark ಸಂಖ್ಯೆಯನ್ನೂ ನಂಬಬಾರದು -- ಈ ಎರಡು-ಭಾಗದ lesson ಉದ್ದಕ್ಕೂ ನಿಜ ಸಂಖ್ಯೆಗಳೊಂದಿಗೆ ಪರಿಶೀಲಿಸಿದ ಅದೇ ಶಿಸ್ತು.' } },

    { type: 'quiz', data: { questions: [
      { q: 'Why does MMAU-Pro evaluate Speech, Sound, Music, and Multi-audio as separate categories rather than one overall score?', qKn: 'MMAU-Pro ಏಕೆ Speech, Sound, Music, ಮತ್ತು Multi-audio ಅನ್ನೂ ಒಂದು overall score ಬದಲಿಗೆ ಪ್ರತ್ಯೇಕ ವರ್ಗಗಳಾಗಿ ಮೌಲ್ಯಮಾಪನ ಮಾಡುತ್ತದೆ?',
        opts: ['Because overall scores are computationally impossible to calculate', 'Because they are genuinely different skills, and a model can be strong in one and weak in another -- a blended score hides that', 'Because each category uses a different audio file format', 'Because only Speech and Sound are real capabilities; Music and Multi-audio are marketing terms'], correct: 1,
        optsKn: ['Overall scores ಗಣಿಸಲು ಕಂಪ್ಯೂಟೇಶನಲ್ ಆಗಿ ಅಸಾಧ್ಯವಾಗಿರುವ ಕಾರಣ', 'ಅವು ನಿಜವಾಗಿ ಬೇರೆ ಕೌಶಲ್ಯಗಳಾಗಿರುವ ಕಾರಣ, ಮತ್ತು ಒಂದು model ಒಂದರಲ್ಲಿ ಪ್ರಬಲ ಮತ್ತು ಇನ್ನೊಂದರಲ್ಲಿ ದುರ್ಬಲ ಆಗಿರಬಹುದು -- ಒಂದು ಬೆರೆಸಿದ score ಇದನ್ನೂ ಮರೆಮಾಚುತ್ತದೆ', 'ಪ್ರತಿ ವರ್ಗ ಬೇರೆ audio ಫೈಲ್ ಫಾರ್ಮ್ಯಾಟ್ ಬಳಸುವ ಕಾರಣ', 'ಕೇವಲ Speech ಮತ್ತು Sound ನಿಜ ಸಾಮರ್ಥ್ಯಗಳಾಗಿರುವ ಕಾರಣ; Music ಮತ್ತು Multi-audio ಮಾರ್ಕೆಟಿಂಗ್ ಪದಗಳು'] },
      { q: 'Verified in this lesson: when load_dataset("MMAU/MMAU-Pro") was re-checked independently for Part 2, what happened?', qKn: 'ಈ lesson ನಲ್ಲಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ: load_dataset("MMAU/MMAU-Pro") ಅನ್ನೂ Part 2 ಗಾಗಿ ಸ್ವತಂತ್ರವಾಗಿ ಮರುಪರಿಶೀಲಿಸಿದಾಗ, ಏನಾಯಿತು?',
        opts: ['It loaded successfully this time, showing the dataset had since been added', 'It reproduced the identical DatasetNotFoundError -- the exact ID still does not resolve on the Hugging Face Hub', 'It returned a different error about authentication', 'The check was skipped since Module 132 already confirmed it'], correct: 1,
        optsKn: ['ಇದೂ ಈ ಬಾರಿ ಯಶಸ್ವಿಯಾಗಿ ಲೋಡ್ ಆಯಿತು, dataset ಅಂದಿನಿಂದ ಸೇರಿಸಲಾಗಿದೆ ಎಂದು ತೋರಿಸುತ್ತಾ', 'ಇದೂ ಒಂದೇ DatasetNotFoundError ಪುನರುತ್ಪಾದಿಸಿತು -- ನಿಖರ ID ಇನ್ನೂ Hugging Face Hub ನಲ್ಲಿ resolve ಆಗುವುದಿಲ್ಲ', 'ಇದೂ authentication ಬಗ್ಗೆ ಒಂದು ಬೇರೆ ದೋಷ ಹಿಂದಿರುಗಿಸಿತು', 'Module 132 ಈಗಾಗಲೇ ಇದನ್ನೂ ದೃಢಪಡಿಸಿದ ಕಾರಣ ಪರಿಶೀಲನೆ ಬಿಟ್ಟುಬಿಡಲಾಗಿದೆ'] },
      { q: 'Why is ~20-26% multi-audio accuracy a meaningful warning sign for several 2026 models on MMAU-Pro?', qKn: 'MMAU-Pro ಮೇಲೆ ಹಲವಾರು 2026 models ಗಳಿಗೆ ~20-26% multi-audio accuracy ಏಕೆ ಒಂದು ಅರ್ಥಪೂರ್ಣ ಎಚ್ಚರಿಕೆ ಚಿಹ್ನೆ?',
        opts: ['It is a perfect score for this category', 'It is close to the 25% random-guessing baseline for a 4-choice question, meaning the models are barely better than chance at comparing/reasoning across multiple clips', 'It means the audio files were corrupted', 'It only affects models trained before 2024'], correct: 1,
        optsKn: ['ಇದೂ ಈ ವರ್ಗಕ್ಕೆ ಒಂದು ಪರಿಪೂರ್ಣ score', 'ಇದೂ ಒಂದು 4-choice ಪ್ರಶ್ನೆಗೆ 25% random-guessing baseline ಗೆ ಹತ್ತಿರವಿದೆ, models ಗಳು ಬಹು clips ಗಳಾದ್ಯಂತ ಹೋಲಿಸುವಲ್ಲಿ/ತರ್ಕಿಸುವಲ್ಲಿ ಅವಕಾಶಕ್ಕಿಂತ ಸ್ವಲ್ಪ ಉತ್ತಮ ಎಂದು ಅರ್ಥ', 'ಇದೂ audio ಫೈಲ್‌ಗಳು ಭ್ರಷ್ಟಗೊಂಡಿವೆ ಎಂದು ಅರ್ಥ', 'ಇದೂ ಕೇವಲ 2024 ಕ್ಕಿಂತ ಮೊದಲು ತರಬೇತಿ ಪಡೆದ models ಗಳ ಮೇಲೆ ಮಾತ್ರ ಪರಿಣಾಮ ಬೀರುತ್ತದೆ'] },
      { q: 'Why should a long recording be diarized before being fed to an audio-language model?', qKn: 'ಒಂದು ಉದ್ದ ರೆಕಾರ್ಡಿಂಗ್ ಅನ್ನೂ ಒಂದು audio-language model ಗೆ ಆಹಾರ ನೀಡುವ ಮೊದಲು ಏಕೆ diarize ಮಾಡಬೇಕು?',
        opts: ['Diarization compresses the audio file size', 'Speaker attribution and cross-speaker reasoning degrade past roughly 10 minutes for many systems, so structured, speaker-labeled segments are more reliable than one undifferentiated block', 'It is required by law for any audio over 10 minutes', 'LALMs cannot process audio longer than 90 seconds at all'], correct: 1,
        optsKn: ['Diarization audio ಫೈಲ್ ಗಾತ್ರ ಸಂಕುಚಿತಗೊಳಿಸುತ್ತದೆ', 'ಅನೇಕ systems ಗಳಿಗೆ speaker attribution ಮತ್ತು cross-speaker reasoning ಸುಮಾರು 10 ನಿಮಿಷಗಳ ಆಚೆ ಕುಸಿಯುತ್ತದೆ, ಆದ್ದರಿಂದ ರಚನಾತ್ಮಕ, speaker-ಲೇಬಲ್ ಮಾಡಿದ ವಿಭಾಗಗಳು ಒಂದು ಅವಿಭಜಿತ ಬ್ಲಾಕ್‌ಗಿಂತ ಹೆಚ್ಚು ವಿಶ್ವಾಸಾರ್ಹ', 'ಇದೂ 10 ನಿಮಿಷಗಳಿಗಿಂತ ಹೆಚ್ಚಿನ ಯಾವುದೇ audio ಗೆ ಕಾನೂನಿನ ಪ್ರಕಾರ ಅಗತ್ಯ', 'LALMs ಗಳು 90 ಸೆಕೆಂಡುಗಳಿಗಿಂತ ಉದ್ದದ audio ಅನ್ನೂ ಸಂಪೂರ್ಣವಾಗಿ ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲಾಗುವುದಿಲ್ಲ'] },
      { q: 'Why can a model hallucinate an event during a silent gap in audio?', qKn: 'ಒಂದು model audio ನಲ್ಲಿ ಒಂದು ಮೌನ ಅಂತರದಲ್ಲಿ ಒಂದು ಘಟನೆ ಏಕೆ hallucinate ಮಾಡಬಹುದು?',
        opts: ['Silence always contains a hidden event that the model correctly detects', 'The model can try to produce a coherent narrative even when evidence is missing, incorrectly treating the absence of sound as if it implies something happened', 'VAD always mislabels silence as speech', 'Hallucination on silence only happens with text-only models, not LALMs'], correct: 1,
        optsKn: ['ಮೌನ ಯಾವಾಗಲೂ model ಸರಿಯಾಗಿ ಪತ್ತೆಹಚ್ಚುವ ಒಂದು ಗುಪ್ತ ಘಟನೆ ಒಳಗೊಂಡಿದೆ', 'Model ಪುರಾವೆ ಕಾಣೆಯಾಗಿದ್ದರೂ ಒಂದು ಸುಸಂಬದ್ಧ ನಿರೂಪಣೆ ಉತ್ಪಾದಿಸಲು ಪ್ರಯತ್ನಿಸಬಹುದು, ಶಬ್ದದ ಅನುಪಸ್ಥಿತಿಯನ್ನೂ ಏನೋ ಸಂಭವಿಸಿತು ಎಂದು ಸೂಚಿಸುತ್ತದೆ ಎಂದು ತಪ್ಪಾಗಿ ಪರಿಗಣಿಸುತ್ತಾ', 'VAD ಯಾವಾಗಲೂ ಮೌನವನ್ನೂ ಭಾಷಣ ಎಂದು ತಪ್ಪಾಗಿ ಲೇಬಲ್ ಮಾಡುತ್ತದೆ', 'ಮೌನದ ಮೇಲೆ Hallucination ಕೇವಲ ಪಠ್ಯ-ಮಾತ್ರ models ಗಳೊಂದಿಗೆ ಮಾತ್ರ ಸಂಭವಿಸುತ್ತದೆ, LALMs ಗಳೊಂದಿಗಲ್ಲ'] },
      { q: 'Why is "Model X scores 60% overall, therefore it is the best choice" considered bad evaluation practice in this lesson?', qKn: '"Model X 60% overall ಸ್ಕೋರ್ ಮಾಡುತ್ತದೆ, ಆದ್ದರಿಂದ ಇದೂ ಅತ್ಯುತ್ತಮ ಆಯ್ಕೆ" ಎಂಬುದೂ ಈ lesson ನಲ್ಲಿ ಏಕೆ ಒಂದು ಕೆಟ್ಟ evaluation ಅಭ್ಯಾಸ ಎಂದು ಪರಿಗಣಿಸಲಾಗಿದೆ?',
        opts: ['Because 60% is always a failing score regardless of context', 'Because that same model could score very differently across categories (e.g. 73% Speech vs. 22% Multi-audio), and which number matters depends entirely on the actual task', 'Because overall scores cannot be computed for audio models', 'Because only closed models like GPT-4o Audio can be evaluated this way'], correct: 1,
        optsKn: ['60% ಸಂದರ್ಭವನ್ನೂ ಲೆಕ್ಕಿಸದೆ ಯಾವಾಗಲೂ ಒಂದು ವಿಫಲ score ಆಗಿರುವ ಕಾರಣ', 'ಅದೇ model ವರ್ಗಗಳಾದ್ಯಂತ ಬಹಳ ಭಿನ್ನವಾಗಿ ಸ್ಕೋರ್ ಮಾಡಬಹುದಾದ ಕಾರಣ (ಉದಾ. 73% Speech vs. 22% Multi-audio), ಮತ್ತು ಯಾವ ಸಂಖ್ಯೆ ಮುಖ್ಯ ಎಂಬುದೂ ಸಂಪೂರ್ಣವಾಗಿ ನಿಜ task ಮೇಲೆ ಅವಲಂಬಿತವಾಗಿದೆ', 'Audio models ಗಳಿಗೆ overall scores ಗಣಿಸಲು ಸಾಧ್ಯವಿಲ್ಲದ ಕಾರಣ', 'ಕೇವಲ GPT-4o Audio ನಂತಹ closed models ಗಳನ್ನೂ ಮಾತ್ರ ಈ ರೀತಿ ಮೌಲ್ಯಮಾಪನ ಮಾಡಬಹುದಾದ ಕಾರಣ'] },
    ] } },
  ],
};
