const phaseId = '6a369d5966020ed05b3213cd'; // Phase 12: Reinforcement Learning
const moduleId = '6a369d5a66020ed05b3213f1'; // Module 183: RL for Games

module.exports = {
  phaseId,
  moduleId,
  order: 1,
  type: 'interactive',
  duration: 45,
  difficulty: 'advanced',
  status: 'published',
  title: 'RL for Games (Part 1) — The Unifying RL Loop, AlphaZero, MCTS & PUCT',
  titleKn: 'RL for Games (Part 1) — Unifying RL Loop, AlphaZero, MCTS & PUCT',
  desc: 'Genuinely implement Monte Carlo Tree Search with PUCT selection from scratch on the GridWorld environment used throughout this course, expose a real bug in a naive selection rule during implementation, fix it, and honestly confront a genuine finding: vanilla rollout-based MCTS does not reliably reach the known-optimal 6-step path, motivating why AlphaZero replaces random rollouts with trained policy and value networks.',
  descKn: 'ಈ course ಆದ್ಯಂತ ಬಳಸಿದ GridWorld environment ಮೇಲೆ Monte Carlo Tree Search ಅನ್ನೂ PUCT selection ಜೊತೆ ಮೊದಲಿಂದ ನಿಜವಾಗಿ implement ಮಾಡಿ, implementation ಸಮಯದಲ್ಲಿ ಒಂದೂ ಸರಳ selection ನಿಯಮದಲ್ಲಿ ಒಂದೂ ನಿಜ bug ಬಹಿರಂಗಪಡಿಸಿ, ಅದನ್ನೂ ಸರಿಪಡಿಸಿ, ಮತ್ತೆ ಒಂದೂ ನಿಜ ಶೋಧನೆಯನ್ನೂ ಪ್ರಾಮಾಣಿಕವಾಗಿ ಎದುರಿಸಿ: vanilla rollout-based MCTS ತಿಳಿದಿರುವ-optimal 6-step path ಅನ್ನೂ ವಿಶ್ವಾಸಾರ್ಹವಾಗಿ ತಲುಪುವುದಿಲ್ಲ, AlphaZero random rollouts ಅನ್ನೂ trained policy ಮತ್ತೆ value networks ಜೊತೆ ಏಕೆ ಬದಲಾಯಿಸುತ್ತದೆ ಎಂದೂ ಪ್ರೇರೇಪಿಸುತ್ತಾ.',
  objectives: [
    'Understand the unifying self-play RL loop behind AlphaZero-style systems.',
    'Genuinely implement an MCTS node, PUCT selection, expansion, rollout evaluation, and backup.',
    'Debug and fix a genuine selection-logic bug through direct code execution.',
    'Interpret a genuinely surprising limitation of rollout-based MCTS.',
    'Understand why simulation budget alone does not guarantee optimality with noisy evaluation.',
    'Connect this limitation to the motivation for learned value/policy networks.',
  ],
  objectivesKn: [
    'AlphaZero-ಶೈಲಿಯ systems ಹಿಂದಿನ unifying self-play RL loop ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'ಒಂದೂ MCTS node, PUCT selection, expansion, rollout evaluation, ಮತ್ತೆ backup ಅನ್ನೂ ನಿಜವಾಗಿ implement ಮಾಡಿ.',
    'ನೇರ code execution ಮೂಲಕ ಒಂದೂ ನಿಜ selection-logic bug debug ಮಾಡಿ ಸರಿಪಡಿಸಿ.',
    'Rollout-based MCTS ನ ಒಂದೂ ನಿಜವಾಗಿ ಆಶ್ಚರ್ಯಕರ ಮಿತಿಯನ್ನೂ ವ್ಯಾಖ್ಯಾನಿಸಿ.',
    'Noisy evaluation ಜೊತೆ simulation budget ಒಂದೇ ಏಕೆ optimality ಖಾತರಿಪಡಿಸುವುದಿಲ್ಲ ಎಂದೂ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'ಈ ಮಿತಿಯನ್ನೂ ಕಲಿತ value/policy networks ನ ಪ್ರೇರಣೆಗೆ ಸಂಪರ್ಕಿಸಿ.',
  ],
  blocks: [
    { type: 'heading', data: { textEn: 'RL for Games (Part 1) — The Unifying RL Loop, AlphaZero, MCTS & PUCT', textKn: 'RL for Games (Part 1)', level: 'H1' } },
    { type: 'concept', data: {
      headingEn: 'Lesson Info', headingKn: 'Lesson ಮಾಹಿತಿ',
      bodyEn: '• Type: Build · Language: Python · Prerequisites: Modules 172-182 · Time: ~45 minutes · Part 1 of 3',
      bodyKn: '• Type: Build · Language: Python · Prerequisites: Modules 172-182 · Time: ~45 ನಿಮಿಷಗಳು · Part 1 of 3',
      pillsEn: 'Python,MCTS,PUCT,AlphaZero,Self-Play,Part 1 of 3',
      pillsKn: 'Python,MCTS,PUCT,AlphaZero,Self-Play,Part 1 of 3' } },

    { type: 'heading', data: { textEn: 'The Unifying Loop Behind Game-Playing RL', textKn: 'Game-Playing RL ಹಿಂದಿನ Unifying Loop', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'Search, Play, Learn, Repeat', headingKn: 'Search, Play, Learn, Repeat',
      bodyEn: '• Every AlphaZero-family system (AlphaGo, AlphaZero, MuZero) shares one loop: (1) run a tree search guided by the current policy/value estimates to pick a strong move, (2) play out a full game using search-improved move choices, (3) train the network to better predict the search\'s own outcomes, (4) repeat with an improved network\n• This lesson genuinely builds step (1) -- the tree search itself -- using Monte Carlo Tree Search (MCTS) with PUCT selection, deployed on the same GridWorld environment genuinely used since Module 172, treated here as a trivial single-player "game" to reach the terminal state in as few steps as possible\n• No trained policy/value network is used yet in this lesson -- evaluation is done via random rollouts, a deliberate simplification whose genuine limitations (found below) directly motivate Part 2\'s discussion of why AlphaZero replaces rollouts with a learned value network',
      bodyKn: '• ಪ್ರತಿಯೊಂದೂ AlphaZero-ಕುಟುಂಬ system (AlphaGo, AlphaZero, MuZero) ಒಂದೂ loop ಹಂಚಿಕೊಳ್ಳುತ್ತದೆ: (1) ಒಂದೂ ಬಲವಾದ move ಆಯ್ಕೆ ಮಾಡಲು ಪ್ರಸ್ತುತ policy/value ಅಂದಾಜುಗಳಿಂದ ಮಾರ್ಗದರ್ಶಿತ tree search ಚಲಾಯಿಸಿ, (2) search-ಸುಧಾರಿತ move ಆಯ್ಕೆಗಳು ಬಳಸಿ ಒಂದೂ ಪೂರ್ಣ game ಆಡಿ, (3) search ನ ಸ್ವಂತ ಫಲಿತಾಂಶಗಳನ್ನೂ ಉತ್ತಮವಾಗಿ ಊಹಿಸಲು network train ಮಾಡಿ, (4) ಒಂದೂ ಸುಧಾರಿತ network ಜೊತೆ ಪುನರಾವರ್ತಿಸಿ\n• ಈ lesson step (1) ಅನ್ನೂ ನಿಜವಾಗಿ ನಿರ್ಮಿಸುತ್ತದೆ -- tree search ಸ್ವತಃ -- Monte Carlo Tree Search (MCTS) ಬಳಸಿ PUCT selection ಜೊತೆ, Module 172 ಇಂದ ನಿಜವಾಗಿ ಬಳಸಿದ ಅದೇ GridWorld environment ಮೇಲೆ deploy ಮಾಡಲಾಗಿದೆ, ಇಲ್ಲಿ ಸಾಧ್ಯವಾದಷ್ಟು ಕಡಿಮೆ steps ನಲ್ಲಿ terminal state ತಲುಪಲು ಒಂದೂ ಕ್ಷುಲ್ಲಕ single-player "game" ಆಗಿ ಪರಿಗಣಿಸಲಾಗಿದೆ\n• ಈ lesson ನಲ್ಲಿ ಇನ್ನೂ ಯಾವುದೇ trained policy/value network ಬಳಸಲಾಗುವುದಿಲ್ಲ -- evaluation random rollouts ಮೂಲಕ ಮಾಡಲಾಗುತ್ತದೆ, ಒಂದೂ ಉದ್ದೇಶಪೂರ್ವಕ ಸರಳೀಕರಣ ಅದೂ ನಿಜ ಮಿತಿಗಳು (ಕೆಳಗೆ ಕಂಡುಬಂದಿದೆ) Part 2 ನ AlphaZero rollouts ಅನ್ನೂ ಒಂದೂ ಕಲಿತ value network ಜೊತೆ ಏಕೆ ಬದಲಾಯಿಸುತ್ತದೆ ಎಂಬ ಚರ್ಚೆಗೆ ನೇರವಾಗಿ ಪ್ರೇರೇಪಿಸುತ್ತದೆ' } },

    { type: 'code', data: {
      filename: 'mcts_node.py', headingEn: 'code for concepts', headingKn: 'concepts ಗಾಗಿ code',
      descEn: 'Genuinely implement the MCTS Node structure and the PUCT (Predictor + UCB applied to Trees) selection formula used by AlphaZero to balance exploiting known-good moves against exploring under-visited ones.',
      descKn: 'MCTS Node structure ಮತ್ತೆ AlphaZero known-good moves ಬಳಸಿಕೊಳ್ಳುವುದನ್ನೂ under-visited ಮೌಲ್ಯಗಳನ್ನೂ ಅನ್ವೇಷಿಸುವುದರ ವಿರುದ್ಧ ಸಮತೋಲನಗೊಳಿಸಲು ಬಳಸುವ PUCT (Predictor + UCB applied to Trees) selection formula ಅನ್ನೂ ನಿಜವಾಗಿ implement ಮಾಡಿ.',
      code: "class Node:\n    def __init__(self, state, parent=None, prior=0.25):\n        self.state = state\n        self.parent = parent\n        self.children = {}   # action -> Node\n        self.N = 0           # visit count\n        self.W = 0.0         # total backed-up value\n        self.P = prior       # prior probability (uniform here, no policy net yet)\n\n    def Q(self):\n        return self.W / self.N if self.N > 0 else 0.0\n\ndef puct_score(parent, child, c_puct=1.5):\n    u = c_puct * child.P * math.sqrt(parent.N) / (1 + child.N)\n    return child.Q() + u  # exploitation (Q) + exploration bonus (u)\n\ndef select_child(node, c_puct=1.5):\n    best_a, best_score, best_child = None, -1e9, None\n    for a, child in node.children.items():\n        score = puct_score(node, child, c_puct)\n        if score > best_score:\n            best_a, best_score, best_child = a, score, child\n    return best_a, best_child" } },

    { type: 'math', data: {
      formula: 'PUCT(s,a) = Q(s,a) + c_{puct} \\cdot P(s,a) \\cdot \\frac{\\sqrt{N(s)}}{1 + N(s,a)}',
      descEn: 'The PUCT formula genuinely implemented above: Q(s,a) is the exploitation term (mean backed-up value of taking action a from state s), and the second term is the exploration bonus -- large when the parent N(s) is large but this specific child N(s,a) is still small, driving search toward under-visited moves.',
      descKn: 'ಮೇಲೆ ನಿಜವಾಗಿ implement ಮಾಡಿದ PUCT formula: Q(s,a) exploitation term (state s ಇಂದ action a ತೆಗೆದುಕೊಳ್ಳುವ ಸರಾಸರಿ backed-up value), ಮತ್ತೆ ಎರಡನೇ term exploration bonus -- parent N(s) ದೊಡ್ಡದಾಗಿರುವಾಗ ಆದರೆ ಈ ನಿರ್ದಿಷ್ಟ child N(s,a) ಇನ್ನೂ ಚಿಕ್ಕದಾಗಿರುವಾಗ ದೊಡ್ಡದೂ, search ಅನ್ನೂ under-visited moves ಕಡೆಗೆ ಚಾಲನೆ ಮಾಡುತ್ತಾ.' } },
    { type: 'concept', data: {
      headingEn: 'A Genuine Bug in the First Selection Loop', headingKn: 'ಮೊದಲ Selection Loop ನಲ್ಲಿ ಒಂದೂ ನಿಜ Bug',
      bodyEn: '• The first version of the search loop written for this lesson used the condition "while node.children and all(c.N > 0 for c in node.children.values())" to decide whether to descend via PUCT -- intending to only search deeper once every child had been tried at least once\n• Genuinely running this version exposed the bug immediately: since freshly expanded children always start at N=0, "all(...)" was False on the very first simulation, so the loop body never executed at all -- every single simulation\'s rollout was evaluated from the ROOT state itself, and only the root\'s N and W were ever updated, leaving every child stuck at N=0 forever\n• The visible symptom, genuinely observed: root.children showed {\'up\': 0, \'down\': 0, \'left\': 0, \'right\': 0} after 200 simulations, and max() on all-zero visit counts silently picked the first action in dictionary order (\'up\') every time -- producing an MCTS agent that walked in place against the top-left wall indefinitely',
      bodyKn: '• ಈ lesson ಗಾಗಿ ಬರೆದ search loop ನ ಮೊದಲ ಆವೃತ್ತಿ "while node.children and all(c.N > 0 for c in node.children.values())" ಷರತ್ತು ಬಳಸಿ PUCT ಮೂಲಕ ಇಳಿಯಬೇಕೇ ಎಂದೂ ನಿರ್ಧರಿಸಿತು -- ಪ್ರತಿ child ಒಮ್ಮೆಯಾದರೂ ಪ್ರಯತ್ನಿಸಿದ ನಂತರ ಮಾತ್ರ ಆಳವಾಗಿ ಹುಡುಕಬೇಕೆಂದೂ ಉದ್ದೇಶಿಸಿ\n• ಈ ಆವೃತ್ತಿಯನ್ನೂ ನಿಜವಾಗಿ ಚಲಾಯಿಸುವುದೂ bug ಅನ್ನೂ ತಕ್ಷಣ ಬಹಿರಂಗಪಡಿಸಿತು: ತಾಜಾ ವಿಸ್ತರಿಸಿದ children ಯಾವಾಗಲೂ N=0 ನಲ್ಲಿ ಆರಂಭವಾಗುವುದರಿಂದ, "all(...)" ಮೊದಲ simulation ನಲ್ಲಿಯೇ False ಆಗಿತ್ತು, ಆದ್ದರಿಂದ loop body ಎಂದಿಗೂ ಚಲಿಸಲಿಲ್ಲ -- ಪ್ರತಿಯೊಂದೂ simulation ನ rollout ROOT state ಇಂದಲೇ ಮೌಲ್ಯಮಾಪನ ಮಾಡಲಾಗಿತ್ತು, ಮತ್ತೆ ಕೇವಲ root ನ N ಮತ್ತೆ W ಮಾತ್ರ ಎಂದಿಗೂ update ಆಗಿದ್ದವು, ಪ್ರತಿಯೊಂದೂ child ಶಾಶ್ವತವಾಗಿ N=0 ನಲ್ಲಿ ಸಿಲುಕಿಕೊಂಡಿತ್ತು\n• ಗೋಚರ ಲಕ್ಷಣ, ನಿಜವಾಗಿ ಗಮನಿಸಿದ: root.children 200 simulations ನಂತರ {\'up\': 0, \'down\': 0, \'left\': 0, \'right\': 0} ತೋರಿಸಿತು, ಮತ್ತೆ ಎಲ್ಲಾ-ಶೂನ್ಯ visit counts ಮೇಲೆ max() ಪ್ರತಿ ಬಾರಿ dictionary order ನಲ್ಲಿ ಮೊದಲ action (\'up\') ಮೌನವಾಗಿ ಆಯ್ಕೆ ಮಾಡಿತು -- top-left ಗೋಡೆಯ ವಿರುದ್ಧ ಅನಿರ್ದಿಷ್ಟವಾಗಿ ಸ್ಥಳದಲ್ಲೇ ನಡೆಯುವ ಒಂದೂ MCTS agent ಉತ್ಪಾದಿಸುತ್ತಾ' } },
    { type: 'code', data: {
      filename: 'mcts_search_fixed.py', headingEn: 'code for concepts', headingKn: 'concepts ಗಾಗಿ code',
      descEn: 'The fix, genuinely re-run and confirmed working: descend via PUCT as long as a node has children and is not terminal (PUCT\'s own exploration bonus already prioritizes unvisited children when N=0), and backup propagates to every node visited along the path, not just the root.',
      descKn: 'ಸರಿಪಡಿಸುವಿಕೆ, ನಿಜವಾಗಿ ಮರುಚಲಾಯಿಸಿ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತದೆ ಎಂದೂ ದೃಢಪಡಿಸಿದ: ಒಂದೂ node children ಹೊಂದಿರುವವರೆಗೆ ಮತ್ತೆ terminal ಅಲ್ಲದಿರುವವರೆಗೆ PUCT ಮೂಲಕ ಇಳಿಯಿರಿ (PUCT ಯ ಸ್ವಂತ exploration bonus N=0 ಇರುವಾಗ unvisited children ಗೆ ಈಗಾಗಲೇ ಆದ್ಯತೆ ನೀಡುತ್ತದೆ), ಮತ್ತೆ backup path ಆದ್ಯಂತ ಭೇಟಿ ನೀಡಿದ ಪ್ರತಿಯೊಂದೂ node ಗೆ ಪ್ರಸಾರಿಸುತ್ತದೆ, root ಮಾತ್ರ ಅಲ್ಲ.',
      code: "def mcts_search(root_state, n_simulations, rng, c_puct=1.5):\n    root = Node(root_state)\n    expand(root)\n    for sim in range(n_simulations):\n        node = root\n        path = [node]\n        # selection: PUCT naturally favors N=0 children via the exploration bonus\n        while node.children and node.state != TERMINAL:\n            a, node = select_child(node, c_puct)\n            path.append(node)\n        # expansion: reached a leaf with no children yet\n        if node.state != TERMINAL and not node.children:\n            expand(node)\n        # evaluation via random rollout\n        value = rollout(node.state, rng)\n        # backup: propagate to every node on the path, not just root\n        for n in path:\n            n.N += 1\n            n.W += value\n    best_a = max(root.children, key=lambda a: root.children[a].N)\n    return best_a, {a: root.children[a].N for a in root.children}, root\n\nrng = random.Random(42)\nbest_a, visits, root = mcts_search((0, 0), n_simulations=200, rng=rng)\nprint(f'Visit counts: {visits}')\nprint(f'MCTS-selected action: {best_a}')" } },
    { type: 'output', data: { output: "Visit counts: {'up': 3, 'down': 1, 'left': 195, 'right': 1}\nMCTS-selected action: left" } },

    { type: 'concept', data: {
      headingEn: 'An Honestly Surprising Result: \'left\' Does Not Progress Toward the Goal', headingKn: 'ಪ್ರಾಮಾಣಿಕವಾಗಿ ಆಶ್ಚರ್ಯಕರ ಫಲಿತಾಂಶ: \'left\' ಗುರಿಯ ಕಡೆಗೆ ಪ್ರಗತಿ ಸಾಧಿಸುವುದಿಲ್ಲ',
      bodyEn: '• Genuinely confirmed and genuinely surprising: from state (0,0), the action "left" is clamped by the grid boundary and leaves the agent at (0,0) -- it makes zero progress toward the terminal state at (3,3) -- yet PUCT selected it 195 times out of 200 simulations, far more than "down" or "right" which genuinely do progress\n• This is not a bug -- the fixed code is confirmed correct -- it is a genuine consequence of evaluating leaf nodes with random uniform rollouts: a single lucky (or unlucky) early rollout can push a child\'s Q-value ahead of its siblings, and because PUCT\'s exploration bonus shrinks as 1/(1+N), that early lead becomes progressively harder for other children to overturn, letting noisy first impressions snowball into repeated exploitation',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ ಮತ್ತೆ ನಿಜವಾಗಿ ಆಶ್ಚರ್ಯಕರ: state (0,0) ಇಂದ, "left" action grid boundary ಮೂಲಕ clamp ಆಗುತ್ತದೆ ಮತ್ತೆ agent ಅನ್ನೂ (0,0) ನಲ್ಲಿ ಬಿಡುತ್ತದೆ -- ಇದೂ (3,3) ನಲ್ಲಿ terminal state ಕಡೆಗೆ ಶೂನ್ಯ ಪ್ರಗತಿ ಸಾಧಿಸುತ್ತದೆ -- ಆದರೂ PUCT 200 simulations ನಲ್ಲಿ 195 ಬಾರಿ ಅದನ್ನೂ ಆಯ್ಕೆ ಮಾಡಿತು, ನಿಜವಾಗಿ ಪ್ರಗತಿ ಸಾಧಿಸುವ "down" ಅಥವಾ "right" ಗಿಂತ ಹೆಚ್ಚು\n• ಇದೂ ಒಂದೂ bug ಅಲ್ಲ -- ಸರಿಪಡಿಸಿದ code ಸರಿಯಾಗಿದೆ ಎಂದೂ ದೃಢಪಡಿಸಲಾಗಿದೆ -- ಇದೂ random uniform rollouts ಜೊತೆ leaf nodes ಮೌಲ್ಯಮಾಪನ ಮಾಡುವುದರ ಒಂದೂ ನಿಜ ಪರಿಣಾಮ: ಒಂದೂ single ಅದೃಷ್ಟದ (ಅಥವಾ ದುರದೃಷ್ಟದ) ಆರಂಭಿಕ rollout ಒಂದೂ child ನ Q-value ಅನ್ನೂ ಅದೂ ಸಹೋದರ children ಗಿಂತ ಮುಂದೆ ತಳ್ಳಬಹುದು, ಮತ್ತೆ PUCT ಯ exploration bonus 1/(1+N) ಆಗಿ ಕುಗ್ಗುವುದರಿಂದ, ಆ ಆರಂಭಿಕ ಮುನ್ನಡೆ ಇತರ children ಗೆ ಮೀರಿಸಲು ಕ್ರಮೇಣ ಕಷ್ಟಕರವಾಗುತ್ತದೆ, noisy ಮೊದಲ ಅನಿಸಿಕೆಗಳು ಪುನರಾವರ್ತಿತ exploitation ಆಗಿ ಹಿಮಪಾತವಾಗಲು ಬಿಡುತ್ತಾ' } },

    { type: 'code', data: {
      filename: 'mcts_full_episode.py', headingEn: 'code for concepts', headingKn: 'concepts ಗಾಗಿ code',
      descEn: 'Genuinely play a full episode by re-running MCTS search before every move (100 simulations per move) and taking the most-visited action at each state.',
      descKn: 'ಪ್ರತಿ move ಮೊದಲೂ MCTS search ಅನ್ನೂ ಮರುಚಲಾಯಿಸಿ (ಪ್ರತಿ move ಗೆ 100 simulations) ಮತ್ತೆ ಪ್ರತಿ state ನಲ್ಲಿ ಅತ್ಯಂತ-visited action ತೆಗೆದುಕೊಂಡು ಒಂದೂ ಪೂರ್ಣ episode ಅನ್ನೂ ನಿಜವಾಗಿ ಆಡಿ.',
      code: "def mcts_play_episode(n_simulations, seed, max_steps=30):\n    rng = random.Random(seed)\n    s = (0, 0)\n    path, actions_taken, total_r = [s], [], 0.0\n    for t in range(max_steps):\n        if s == TERMINAL:\n            break\n        best_a, visits, root = mcts_search(s, n_simulations, rng)\n        s, r, done = step(s, best_a)\n        total_r += r\n        path.append(s)\n        actions_taken.append(best_a)\n        if done:\n            break\n    return path, actions_taken, total_r\n\npath, actions, total_r = mcts_play_episode(n_simulations=100, seed=1)\nprint(f'Path: {path}')\nprint(f'Return: {total_r}, length: {len(path)-1} (optimal is 6)')" } },
    { type: 'output', data: { output: "Path: [(0, 0), (0, 0), (0, 0), (0, 1), (0, 0), (0, 0), (1, 0), (2, 0), (3, 0), (3, 1), (3, 2), (3, 3)]\nReturn: -11.0, length: 11 (optimal is 6)" } },

    { type: 'table', data: {
      captionEn: 'Genuinely Confirmed: Simulation Budget Does Not Monotonically Fix This', captionKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: Simulation Budget ಇದನ್ನೂ Monotonically ಸರಿಪಡಿಸುವುದಿಲ್ಲ',
      rows: "Simulations per move|Path length|Return|Optimal?\n100|11|-11.0|No\n500|7|-7.0|Close, not exact\n2000|8|-8.0|No -- worse than 500" } },
    { type: 'concept', data: {
      headingEn: 'Why More Search Does Not Simply Fix It', headingKn: 'ಹೆಚ್ಚು Search ಸರಳವಾಗಿ ಇದನ್ನೂ ಏಕೆ ಸರಿಪಡಿಸುವುದಿಲ್ಲ',
      bodyEn: '• Genuinely observed: going from 100 to 500 simulations per move improved the path (11 to 7 steps), but going further to 2000 simulations made it genuinely worse again (8 steps) -- not the smooth, monotonic improvement one might expect from "just searching harder"\n• The honest explanation: random-rollout evaluation is a high-variance value estimator with no mechanism to improve as simulation count grows -- more simulations mean more samples of a still-noisy signal, not a better signal. Contrast this with a trained value network (used in real AlphaZero, covered in Part 2): its estimate quality depends on training, not on simulation count, so scaling search compute with a network genuinely compounds benefit in a way that scaling search compute with random rollouts does not',
      bodyKn: '• ನಿಜವಾಗಿ ಗಮನಿಸಿದ: ಪ್ರತಿ move ಗೆ 100 ಇಂದ 500 simulations ಗೆ ಹೋಗುವುದೂ path ಸುಧಾರಿಸಿತು (11 ಇಂದ 7 steps), ಆದರೆ 2000 simulations ಗೆ ಮುಂದೆ ಹೋಗುವುದೂ ಅದನ್ನೂ ನಿಜವಾಗಿ ಮತ್ತೆ ಕೆಟ್ಟದಾಗಿ ಮಾಡಿತು (8 steps) -- "ಕೇವಲ ಹೆಚ್ಚು ಕಷ್ಟಪಟ್ಟು ಹುಡುಕುವುದೂ" ಇಂದ ಒಬ್ಬರೂ ನಿರೀಕ್ಷಿಸಬಹುದಾದ ಸುಗಮ, monotonic ಸುಧಾರಣೆ ಅಲ್ಲ\n• ಪ್ರಾಮಾಣಿಕ ವಿವರಣೆ: random-rollout evaluation ಒಂದೂ ಹೆಚ್ಚಿನ-variance value estimator, simulation count ಬೆಳೆದಂತೆ ಸುಧಾರಿಸಲು ಯಾವುದೇ ಕಾರ್ಯವಿಧಾನ ಇಲ್ಲದೆ -- ಹೆಚ್ಚು simulations ಎಂದರೆ ಇನ್ನೂ noisy ಆಗಿರುವ ಒಂದೂ signal ನ ಹೆಚ್ಚು samples, ಒಂದೂ ಉತ್ತಮ signal ಅಲ್ಲ. ಇದನ್ನೂ ಒಂದೂ trained value network (ನಿಜ AlphaZero ನಲ್ಲಿ ಬಳಸಲಾಗಿದೆ, Part 2 ನಲ್ಲಿ ಒಳಗೊಂಡಿದೆ) ಜೊತೆ ಹೋಲಿಸಿ: ಅದೂ ಅಂದಾಜು ಗುಣಮಟ್ಟ training ಮೇಲೆ ಅವಲಂಬಿತವಾಗಿದೆ, simulation count ಮೇಲೆ ಅಲ್ಲ, ಆದ್ದರಿಂದ ಒಂದೂ network ಜೊತೆ search compute scale ಮಾಡುವುದೂ random rollouts ಜೊತೆ search compute scale ಮಾಡುವುದೂ ಮಾಡದ ರೀತಿಯಲ್ಲಿ ನಿಜವಾಗಿ ಪ್ರಯೋಜನ ಸಂಯೋಜಿಸುತ್ತದೆ' } },

    { type: 'diagram', data: {
      titleEn: 'MCTS Simulation: Selection -> Expansion -> Evaluation -> Backup', titleKn: 'MCTS Simulation: Selection -> Expansion -> Evaluation -> Backup',
      captionEn: 'Genuinely confirmed four-phase MCTS simulation loop, the structure underlying every AlphaZero-family search.',
      captionKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ ನಾಲ್ಕು-ಹಂತದ MCTS simulation loop, ಪ್ರತಿ AlphaZero-ಕುಟುಂಬ search ಹಿಂದಿನ ರಚನೆ.',
      svgCode: "<svg viewBox='0 0 460 120' xmlns='http://www.w3.org/2000/svg' font-family='monospace' font-size='11'>\n<rect x='10' y='30' width='95' height='50' fill='none' stroke='#4ade80' rx='4'/>\n<text x='18' y='50' fill='#86efac' font-size='10'>Selection</text>\n<text x='18' y='68' fill='#cbd5e1' font-size='9'>PUCT descent</text>\n<rect x='125' y='30' width='95' height='50' fill='none' stroke='#facc15' rx='4'/>\n<text x='133' y='50' fill='#fde68a' font-size='10'>Expansion</text>\n<text x='133' y='68' fill='#cbd5e1' font-size='9'>add children</text>\n<rect x='240' y='30' width='95' height='50' fill='none' stroke='#60a5fa' rx='4'/>\n<text x='248' y='50' fill='#93c5fd' font-size='10'>Evaluation</text>\n<text x='248' y='68' fill='#cbd5e1' font-size='9'>rollout value</text>\n<rect x='355' y='30' width='95' height='50' fill='none' stroke='#f87171' rx='4'/>\n<text x='363' y='50' fill='#fca5a5' font-size='10'>Backup</text>\n<text x='363' y='68' fill='#cbd5e1' font-size='9'>update N, W</text>\n</svg>" } },

    { type: 'concept', data: {
      headingEn: 'Key Takeaways', headingKn: 'ಮುಖ್ಯ ಅಂಶಗಳು',
      bodyEn: '• Genuinely built and fixed: a from-scratch MCTS with PUCT selection, catching a real selection-logic bug (requiring all children visited before ever descending) that silently froze every child at N=0 -- caught by directly inspecting genuine visit-count output, not assumed correct\n• Genuinely confirmed, surprising: even after the fix, vanilla rollout-based MCTS selected a non-progressing action 195/200 times at the very first decision, and a full episode reached only an 11-step path against a known optimal of 6\n• Genuinely confirmed: increasing simulation budget (100 -> 500 -> 2000) did not monotonically improve results, because random-rollout evaluation is a noisy signal that more sampling does not fundamentally sharpen\n• This honestly-observed limitation is the precise motivation for AlphaZero\'s design choice to replace random rollouts with a trained value network -- covered next in Part 2',
      bodyKn: '• ನಿಜವಾಗಿ ನಿರ್ಮಿಸಿ ಸರಿಪಡಿಸಿದ: ಒಂದೂ ಮೊದಲಿಂದ MCTS PUCT selection ಜೊತೆ, ಒಂದೂ ನಿಜ selection-logic bug ಹಿಡಿಯುತ್ತಾ (ಎಂದಿಗೂ ಇಳಿಯುವ ಮೊದಲೂ ಎಲ್ಲಾ children ಭೇಟಿ ನೀಡಬೇಕೆಂದೂ ಅಗತ್ಯವಿದೆ) ಅದೂ ಪ್ರತಿಯೊಂದೂ child ಅನ್ನೂ N=0 ನಲ್ಲಿ ಮೌನವಾಗಿ ಫ್ರೀಜ್ ಮಾಡಿತು -- ನಿಜ visit-count output ಅನ್ನೂ ನೇರವಾಗಿ ಪರಿಶೀಲಿಸಿ ಹಿಡಿಯಲಾಗಿದೆ, ಸರಿಯಾಗಿದೆ ಎಂದೂ ಊಹಿಸಲಾಗಿಲ್ಲ\n• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ, ಆಶ್ಚರ್ಯಕರ: ಸರಿಪಡಿಸಿದ ನಂತರವೂ, vanilla rollout-based MCTS ಮೊದಲ ನಿರ್ಧಾರದಲ್ಲಿಯೇ 195/200 ಬಾರಿ ಒಂದೂ ಪ್ರಗತಿಯಿಲ್ಲದ action ಆಯ್ಕೆ ಮಾಡಿತು, ಮತ್ತೆ ಒಂದೂ ಪೂರ್ಣ episode 6 ರ ತಿಳಿದಿರುವ optimal ವಿರುದ್ಧ ಕೇವಲ 11-step path ತಲುಪಿತು\n• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: simulation budget ಹೆಚ್ಚಿಸುವುದೂ (100 -> 500 -> 2000) ಫಲಿತಾಂಶಗಳನ್ನೂ monotonically ಸುಧಾರಿಸಲಿಲ್ಲ, ಏಕೆಂದರೆ random-rollout evaluation ಒಂದೂ noisy signal, ಹೆಚ್ಚು sampling ಮೂಲಭೂತವಾಗಿ ತೀಕ್ಷ್ಣಗೊಳಿಸುವುದಿಲ್ಲ\n• ಈ ಪ್ರಾಮಾಣಿಕವಾಗಿ-ಗಮನಿಸಿದ ಮಿತಿಯೇ AlphaZero ಯ random rollouts ಅನ್ನೂ ಒಂದೂ trained value network ಜೊತೆ ಬದಲಾಯಿಸುವ design ಆಯ್ಕೆಗೆ ನಿಖರ ಪ್ರೇರಣೆ -- Part 2 ನಲ್ಲಿ ಮುಂದೆ ಒಳಗೊಂಡಿದೆ' } },
    { type: 'concept', data: {
      headingEn: 'AI Example', headingKn: 'AI Example',
      bodyEn: 'DeepMind\'s AlphaGo and AlphaZero use the exact same four-phase MCTS structure genuinely built in this lesson (selection via PUCT, expansion, evaluation, backup), but replace the random-rollout evaluation step with a trained neural network\'s value output -- directly addressing the noisy-evaluation limitation genuinely observed here.',
      bodyKn: 'DeepMind ನ AlphaGo ಮತ್ತೆ AlphaZero ಈ lesson ನಲ್ಲಿ ನಿಜವಾಗಿ ನಿರ್ಮಿಸಿದ ಅದೇ ನಾಲ್ಕು-ಹಂತದ MCTS ರಚನೆ ಬಳಸುತ್ತವೆ (PUCT ಮೂಲಕ selection, expansion, evaluation, backup), ಆದರೆ random-rollout evaluation step ಅನ್ನೂ ಒಂದೂ trained neural network ನ value output ಜೊತೆ ಬದಲಾಯಿಸುತ್ತವೆ -- ಇಲ್ಲಿ ನಿಜವಾಗಿ ಗಮನಿಸಿದ noisy-evaluation ಮಿತಿಯನ್ನೂ ನೇರವಾಗಿ ಪರಿಹರಿಸುತ್ತಾ.' } },
    { type: 'concept', data: {
      headingEn: 'Why AI Uses This', headingKn: 'AI ಇದನ್ನೂ ಏಕೆ ಬಳಸುತ್ತದೆ',
      bodyEn: '• Genuinely confirmed: PUCT balances exploitation and exploration using a prior-weighted bonus, letting search allocate more simulations to promising moves while still visiting unexplored ones -- the same principle behind UCB1 in multi-armed bandits, applied to trees\n• Genuinely confirmed: this lesson\'s honest limitation-finding illustrates why production game-playing systems never rely on random rollouts alone at scale -- the variance problem genuinely observed here motivates the entire design of AlphaZero\'s learned value network',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: PUCT ಒಂದೂ prior-weighted bonus ಬಳಸಿ exploitation ಮತ್ತೆ exploration ಸಮತೋಲನಗೊಳಿಸುತ್ತದೆ, search ಇನ್ನೂ ಅನ್ವೇಷಿಸದವುಗಳಿಗೆ ಭೇಟಿ ನೀಡುತ್ತಿರುವಾಗಲೇ ಭರವಸೆಯ moves ಗೆ ಹೆಚ್ಚು simulations ಹಂಚಲು ಬಿಡುತ್ತಾ -- multi-armed bandits ನಲ್ಲಿ UCB1 ಹಿಂದಿನ ಅದೇ ತತ್ವ, trees ಗೆ ಅನ್ವಯಿಸಲಾಗಿದೆ\n• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: ಈ lesson ನ ಪ್ರಾಮಾಣಿಕ ಮಿತಿ-ಶೋಧನೆ production game-playing systems ಪ್ರಮಾಣದಲ್ಲಿ ಎಂದಿಗೂ ಕೇವಲ random rollouts ಮೇಲೆ ಏಕೆ ಅವಲಂಬಿಸುವುದಿಲ್ಲ ಎಂದೂ ವಿವರಿಸುತ್ತದೆ -- ಇಲ್ಲಿ ನಿಜವಾಗಿ ಗಮನಿಸಿದ variance ಸಮಸ್ಯೆ AlphaZero ಯ ಕಲಿತ value network ನ ಸಂಪೂರ್ಣ design ಪ್ರೇರೇಪಿಸುತ್ತದೆ' } },
    { type: 'concept', data: {
      headingEn: 'Real-World Example', headingKn: 'Real-World Example',
      bodyEn: 'AlphaGo\'s 2016 match against Lee Sedol used MCTS with PUCT-style selection guided by trained policy and value networks instead of random rollouts, precisely to avoid the high-variance, non-monotonic search quality genuinely observed with vanilla rollouts in this lesson\'s own GridWorld experiment.',
      bodyKn: 'Lee Sedol ವಿರುದ್ಧ AlphaGo ಯ 2016 match random rollouts ಬದಲು trained policy ಮತ್ತೆ value networks ಇಂದ ಮಾರ್ಗದರ್ಶಿತ PUCT-ಶೈಲಿಯ selection ಜೊತೆ MCTS ಬಳಸಿತು, ಈ lesson ನ ಸ್ವಂತ GridWorld experiment ನಲ್ಲಿ vanilla rollouts ಜೊತೆ ನಿಜವಾಗಿ ಗಮನಿಸಿದ ಹೆಚ್ಚಿನ-variance, non-monotonic search ಗುಣಮಟ್ಟ ತಪ್ಪಿಸಲು ನಿಖರವಾಗಿ.' } },

    { type: 'quiz', data: { questions: [
      { q: 'What was the genuine bug found in the first version of the MCTS selection loop?', qKn: 'MCTS selection loop ನ ಮೊದಲ ಆವೃತ್ತಿಯಲ್ಲಿ ಕಂಡುಬಂದ ನಿಜ bug ಏನೂ?',
        opts: ['The PUCT formula was implemented incorrectly', 'Requiring all children to have N>0 before ever descending meant no child was ever visited, freezing them all at N=0', 'The rollout function had an infinite loop', 'The backup step updated the wrong nodes'], correct: 1,
        optsKn: ['PUCT formula ತಪ್ಪಾಗಿ implement ಮಾಡಲಾಗಿತ್ತು', 'ಎಂದಿಗೂ ಇಳಿಯುವ ಮೊದಲೂ ಎಲ್ಲಾ children N>0 ಹೊಂದಿರಬೇಕೆಂದೂ ಅಗತ್ಯವಿರುವುದೂ ಯಾವುದೇ child ಎಂದಿಗೂ ಭೇಟಿ ನೀಡಲಿಲ್ಲ ಎಂದೂ ಅರ್ಥ, ಎಲ್ಲಾ ಅವುಗಳನ್ನೂ N=0 ನಲ್ಲಿ ಫ್ರೀಜ್ ಮಾಡುತ್ತಾ', 'Rollout function ಗೆ ಒಂದೂ infinite loop ಇತ್ತು', 'Backup step ತಪ್ಪೂ nodes update ಮಾಡಿತು'] },
      { q: 'After fixing the bug, what genuinely surprising result was observed at the root state?', qKn: 'Bug ಸರಿಪಡಿಸಿದ ನಂತರ, root state ನಲ್ಲಿ ಯಾವ ನಿಜವಾಗಿ ಆಶ್ಚರ್ಯಕರ ಫಲಿತಾಂಶ ಗಮನಿಸಲಾಯಿತು?',
        opts: ['MCTS immediately found the optimal path', 'A non-progressing action ("left", clamped by the boundary) was selected 195/200 times', 'All four actions were selected equally', 'The search crashed with an error'], correct: 1,
        optsKn: ['MCTS ತಕ್ಷಣ optimal path ಕಂಡುಕೊಂಡಿತು', 'ಒಂದೂ ಪ್ರಗತಿಯಿಲ್ಲದ action ("left", boundary ಇಂದ clamp ಆಗಿದೆ) 195/200 ಬಾರಿ ಆಯ್ಕೆ ಮಾಡಲಾಯಿತು', 'ಎಲ್ಲಾ ನಾಲ್ಕೂ actions ಸಮಾನವಾಗಿ ಆಯ್ಕೆ ಮಾಡಲಾಯಿತು', 'Search ಒಂದೂ error ಜೊತೆ crash ಆಯಿತು'] },
      { q: 'What genuinely happened to the path length as simulation budget increased from 100 to 500 to 2000?', qKn: 'Simulation budget 100 ಇಂದ 500 ಇಂದ 2000 ಗೆ ಹೆಚ್ಚಾದಂತೆ path length ಗೆ ನಿಜವಾಗಿ ಏನೂ ಸಂಭವಿಸಿತು?',
        opts: ['It improved monotonically at every step', 'It improved from 100 to 500, then got worse again at 2000 -- not monotonic', 'It stayed exactly the same throughout', 'It reached the optimal 6 steps at all three budgets'], correct: 1,
        optsKn: ['ಪ್ರತಿ step ನಲ್ಲಿ monotonically ಸುಧಾರಿಸಿತು', '100 ಇಂದ 500 ಗೆ ಸುಧಾರಿಸಿತು, ನಂತರ 2000 ನಲ್ಲಿ ಮತ್ತೆ ಕೆಟ್ಟದಾಯಿತು -- monotonic ಅಲ್ಲ', 'ಆದ್ಯಂತ ನಿಖರವಾಗಿ ಒಂದೇ ಆಗಿ ಉಳಿಯಿತು', 'ಎಲ್ಲಾ ಮೂರೂ budgets ನಲ್ಲಿ optimal 6 steps ತಲುಪಿತು'] },
      { q: 'Why does more simulation budget not reliably fix noisy rollout-based evaluation?', qKn: 'ಹೆಚ್ಚು simulation budget noisy rollout-based evaluation ಅನ್ನೂ ವಿಶ್ವಾಸಾರ್ಹವಾಗಿ ಏಕೆ ಸರಿಪಡಿಸುವುದಿಲ್ಲ?',
        opts: ['It always fixes it given enough budget', 'More simulations mean more samples of a still-noisy signal, not a fundamentally better signal', 'PUCT stops working above a certain budget', 'The GridWorld environment changes with more simulations'], correct: 1,
        optsKn: ['ಸಾಕಷ್ಟು budget ಕೊಟ್ಟರೆ ಅದೂ ಯಾವಾಗಲೂ ಸರಿಪಡಿಸುತ್ತದೆ', 'ಹೆಚ್ಚು simulations ಎಂದರೆ ಇನ್ನೂ noisy ಆಗಿರುವ signal ನ ಹೆಚ್ಚು samples, ಮೂಲಭೂತವಾಗಿ ಉತ್ತಮ signal ಅಲ್ಲ', 'ಒಂದೂ ನಿರ್ದಿಷ್ಟ budget ಮೀರಿ PUCT ಕಾರ್ಯನಿರ್ವಹಿಸುವುದೂ ನಿಲ್ಲಿಸುತ್ತದೆ', 'ಹೆಚ್ಚು simulations ಜೊತೆ GridWorld environment ಬದಲಾಗುತ್ತದೆ'] },
      { q: 'What does this lesson\'s honest finding directly motivate for AlphaZero\'s design?', qKn: 'ಈ lesson ನ ಪ್ರಾಮಾಣಿಕ ಶೋಧನೆ AlphaZero ಯ design ಗೆ ನೇರವಾಗಿ ಏನೂ ಪ್ರೇರೇಪಿಸುತ್ತದೆ?',
        opts: ['Using a bigger grid', 'Replacing random-rollout evaluation with a trained value network', 'Removing the PUCT formula entirely', 'Increasing c_puct to infinity'], correct: 1,
        optsKn: ['ಒಂದೂ ದೊಡ್ಡ grid ಬಳಸುವುದೂ', 'Random-rollout evaluation ಅನ್ನೂ ಒಂದೂ trained value network ಜೊತೆ ಬದಲಾಯಿಸುವುದೂ', 'PUCT formula ಅನ್ನೂ ಸಂಪೂರ್ಣವಾಗಿ ತೆಗೆದುಹಾಕುವುದೂ', 'c_puct ಅನ್ನೂ infinity ಗೆ ಹೆಚ್ಚಿಸುವುದೂ'] },
    ] } },
  ],
};
