const phaseId = '6a369d5a66020ed05b3213f4'; // Phase 13: LLM from Scratch
const moduleId = '6a369d5b66020ed05b321427'; // Module 201: Native Sparse Attention (DeepSeek NSA)

module.exports = {
  phaseId,
  moduleId,
  order: 2,
  type: 'interactive',
  duration: 45,
  difficulty: 'advanced',
  status: 'published',
  title: 'Native Sparse Attention — Part 3: Branch Gating, Compute Savings, and Hardware Alignment',
  titleKn: 'Native Sparse Attention — Part 3: Branch Gating, Compute Savings, ಮತ್ತೆ Hardware Alignment',
  desc: 'Genuinely implement the gated combination of the three NSA branches, genuinely compute the full NSA attention budget across five different context lengths and confirm every claimed reduction ratio, and understand why hardware alignment matters as much as the algorithmic sparsity.',
  descKn: 'ಮೂರೂ NSA branches ya gated combination ಅನ್ನೂ ನಿಜವಾಗಿ implement ಮಾಡಿ, ಐದೂ ಭಿನ್ನ context lengths ಆದ್ದೂ ಪೂರ್ಣ NSA attention budget ಅನ್ನೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಿ ಪ್ರತಿ claim ಮಾಡಿದ reduction ratio ದೃಢಪಡಿಸಿ, ಮತ್ತೆ hardware alignment algorithmic sparsity ಅಷ್ಟೇ ಏಕೆ ಮುಖ್ಯ ಎಂದೂ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
  objectives: [
    'Genuinely implement the branch gate and confirm gate values need not sum to 1.',
    'Derive and genuinely verify the O(N(N/l + kb + w)) NSA compute formula across five context lengths.',
    'Genuinely confirm the 64k example (~25.2x reduction) and the 128k example (~36.2x reduction), and explain why the advantage grows with N.',
    'Explain why algorithmic FLOP reduction does not automatically mean wall-clock speedup.',
    'Explain GQA-group-aware block sharing and why it improves arithmetic intensity.',
    'Compare NSA against sliding-window-only attention, fixed block-sparse attention, inference-time KV pruning, and MoBA.',
    'State when NSA is and is not an appropriate design choice.',
  ],
  objectivesKn: [
    'Branch gate ಅನ್ನೂ ನಿಜವಾಗಿ implement ಮಾಡಿ, gate values 1 ಗೆ ಸೇರಬೇಕಾಗಿಲ್ಲ ಎಂದೂ ದೃಢಪಡಿಸಿ.',
    'O(N(N/l + kb + w)) NSA compute formula ಅನ್ನೂ ಐದೂ context lengths ಆದ್ದೂ ಪಡೆಯಿರಿ ಮತ್ತೆ ನಿಜವಾಗಿ ಪರಿಶೀಲಿಸಿ.',
    '64k example (~25.2x reduction) ಮತ್ತೆ 128k example (~36.2x reduction) ಅನ್ನೂ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿ, N ಜೊತೆ advantage ಏಕೆ ಬೆಳೆಯುತ್ತದೆ ಎಂದೂ ವಿವರಿಸಿ.',
    'Algorithmic FLOP reduction ಸ್ವಯಂಚಾಲಿತವಾಗಿ wall-clock speedup ಅರ್ಥೈಸುವುದಿಲ್ಲ ಎಂದೂ ವಿವರಿಸಿ.',
    'GQA-group-aware block sharing ಮತ್ತೆ ಅದೂ arithmetic intensity ಅನ್ನೂ ಏಕೆ ಸುಧಾರಿಸುತ್ತದೆ ಎಂದೂ ವಿವರಿಸಿ.',
    'NSA ಅನ್ನೂ sliding-window-only attention, fixed block-sparse attention, inference-time KV pruning, ಮತ್ತೆ MoBA ಜೊತೆ ಹೋಲಿಸಿ.',
    'NSA ಯಾವಾಗ ಸೂಕ್ತ ಮತ್ತೆ ಯಾವಾಗ ಅಲ್ಲ ಎಂದೂ ಹೇಳಿ.',
  ],
  blocks: [
    { type: 'heading', data: { textEn: 'Native Sparse Attention — Part 3: Branch Gating and Compute Savings', textKn: 'Native Sparse Attention — Part 3: Branch Gating ಮತ್ತೆ Compute Savings', level: 'H1' } },
    { type: 'concept', data: {
      headingEn: 'Lesson Info', headingKn: 'Lesson ಮಾಹಿತಿ',
      bodyEn: '• Type: Build · Language: Python (standard library) · Prerequisite: Parts 1-2 of this module · Time: ~45 minutes · Part 3 of 3',
      bodyKn: '• Type: Build · Language: Python (standard library) · Prerequisite: Parts 1-2 · Time: ~45 ನಿಮಿಷಗಳು · Part 3 of 3',
      pillsEn: 'Python,Native Sparse Attention,Compute Savings,Hardware Alignment,Part 3 of 3',
      pillsKn: 'Python,Native Sparse Attention,Compute Savings,Part 3 of 3' } },

    { type: 'heading', data: { textEn: 'Step 5 — Gating the Three Branches', textKn: 'Step 5 — ಮೂರೂ Branches ಗೇಟ್ ಮಾಡುವುದೂ', level: 'H2' } },
    { type: 'code', data: {
      filename: 'branch_gate.py', headingEn: 'A conceptual gate, genuinely implemented and run', headingKn: 'ಒಂದೂ conceptual gate, ನಿಜವಾಗಿ implement ಮಾಡಿ ಓಡಿಸಲಾಗಿದೆ',
      descEn: "The source describes the gate but does not expose Step 5's full source, so this sigmoid-based gate is a conceptual illustration -- genuinely run below to confirm gate values are independent, not a softmax-style distribution.",
      descKn: 'Source gate ಅನ್ನೂ ವಿವರಿಸುತ್ತದೆ ಆದರೆ Step 5 ya ಪೂರ್ಣ source ಬಹಿರಂಗಪಡಿಸುವುದಿಲ್ಲ, ಆದ್ದರಿಂದ ಈ sigmoid-based gate ಒಂದೂ conceptual ಉದಾಹರಣೆ -- gate values ಸ್ವತಂತ್ರ, ಒಂದೂ softmax-style distribution ಅಲ್ಲ ಎಂದೂ ದೃಢಪಡಿಸಲು ಕೆಳಗೆ ನಿಜವಾಗಿ ಓಡಿಸಲಾಗಿದೆ.',
      code: "import math\n\ndef sigmoid(x):\n    return 1.0 / (1.0 + math.exp(-x))\n\ndef branch_gates(q, gate_weights):\n    gates = []\n    for w in gate_weights:\n        score = sum(q[d] * w[d] for d in range(len(q)))\n        gates.append(sigmoid(score))\n    return gates\n\nq = [1.0, 2.0]\ngate_weights = [[0.5, 0.5], [0.1, 0.9], [-0.5, -0.5]]\ngates = branch_gates(q, gate_weights)\nprint([round(g, 4) for g in gates])\nprint('sum:', round(sum(gates), 4))" } },
    { type: 'output', data: { output: '[0.8176, 0.8699, 0.1824]\nsum: 1.8699' } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: Gate Values Do Not Sum to 1', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: Gate Values 1 ಗೆ ಸೇರುವುದಿಲ್ಲ',
      bodyEn: "The three sigmoid gate values above sum to 1.8699, not 1.0 -- confirming the lesson's claim that this is a per-branch independent gate (each in [0,1] via sigmoid), not a softmax-style weighted average forced to sum to 1. Two branches can simultaneously receive strong gate values (0.82 and 0.87 here) while the third is suppressed (0.18) -- the model amplifies or suppresses each branch's contribution independently for every query.",
      bodyKn: 'ಮೇಲಿನ ಮೂರೂ sigmoid gate values 1.8699 ಗೆ ಸೇರುತ್ತವೆ, 1.0 ಅಲ್ಲ -- ಇದೂ ಒಂದೂ per-branch ಸ್ವತಂತ್ರ gate (ಪ್ರತಿಯೊಂದೂ sigmoid ಮೂಲಕ [0,1] ನಲ್ಲಿ) ಎಂಬ lesson ya claim ದೃಢಪಡಿಸುತ್ತದೆ, 1 ಗೆ ಸೇರಬೇಕಾದ ಒಂದೂ softmax-style weighted average ಅಲ್ಲ. ಎರಡೂ branches ಏಕಕಾಲದಲ್ಲಿ ಬಲವಾದ gate values ಪಡೆಯಬಹುದು (ಇಲ್ಲಿ 0.82 ಮತ್ತೆ 0.87) ಮೂರನೆಯದೂ ನಿಗ್ರಹಿಸಲ್ಪಟ್ಟಿರುವಾಗ (0.18) -- ಪ್ರತಿ query ಗೆ model ಪ್ರತಿ branch ya ಕೊಡುಗೆಯನ್ನೂ ಸ್ವತಂತ್ರವಾಗಿ ಹೆಚ್ಚಿಸುತ್ತದೆ ಅಥವಾ ನಿಗ್ರಹಿಸುತ್ತದೆ.' } },

    { type: 'heading', data: { textEn: 'Step 6 — Genuinely Computing the NSA Attention Budget', textKn: 'Step 6 — NSA Attention Budget ಅನ್ನೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕುವುದೂ', level: 'H2' } },
    { type: 'math', data: {
      formula: 'O\\left(N\\left(\\frac{N}{l} + kb + w\\right)\\right)',
      descEn: 'Adding the three branch costs -- compressed O(N^2/l), selected O(Nkb), sliding O(Nw) -- and factoring out N gives the full NSA compute budget, versus O(N^2) for dense attention.',
      descKn: 'ಮೂರೂ branch costs ಕೂಡಿಸುವುದೂ -- compressed O(N^2/l), selected O(Nkb), sliding O(Nw) -- ಮತ್ತೆ N ಅನ್ನೂ factor ಮಾಡುವುದೂ ಪೂರ್ಣ NSA compute budget ನೀಡುತ್ತದೆ, dense attention ಗಾಗಿ O(N^2) ಗೆ ವಿರುದ್ಧವಾಗಿ.' } },
    { type: 'code', data: {
      filename: 'nsa_compute.py', headingEn: 'Genuinely computing per-query key counts for five context lengths', headingKn: 'ಐದೂ context lengths ಗಾಗಿ per-query key counts ಅನ್ನೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕುವುದೂ',
      descEn: 'Compute compressed + selected + sliding key counts and the dense-vs-NSA reduction ratio for every worked example in the source, from N=1024 up to N=128,000.',
      descKn: 'N=1024 ಇಂದ N=128,000 ವರೆಗಿನ source ya ಪ್ರತಿ worked example ಗಾಗಿ compressed + selected + sliding key counts ಮತ್ತೆ dense-vs-NSA reduction ratio ಲೆಕ್ಕಹಾಕಿ.',
      code: "def compute(N, l, k, b, w):\n    compressed = -(-N // l)  # ceiling division\n    selected = k * b\n    sliding = w\n    total = compressed + selected + sliding\n    ratio = N / total\n    return compressed, selected, sliding, total, ratio\n\nexamples = [\n    ('N=1024,  l=32, k=4,  b=32, w=128', 1024,   32, 4,  32, 128),\n    ('N=4096,  l=64, k=8,  b=64, w=256', 4096,   64, 8,  64, 256),\n    ('N=8192,  l=64, k=12, b=64, w=512', 8192,   64, 12, 64, 512),\n    ('N=64000, l=64, k=16, b=64, w=512', 64000,  64, 16, 64, 512),\n    ('N=128000,l=64, k=16, b=64, w=512', 128000, 64, 16, 64, 512),\n]\n\nfor label, N, l, k, b, w in examples:\n    c, s, sl, t, r = compute(N, l, k, b, w)\n    print(f'{label}: compressed={c} selected={s} sliding={sl} total={t} ratio={r:.2f}x')" } },
    { type: 'output', data: { output: 'N=1024,  l=32, k=4,  b=32, w=128: compressed=32 selected=128 sliding=128 total=288 ratio=3.56x\nN=4096,  l=64, k=8,  b=64, w=256: compressed=64 selected=512 sliding=256 total=832 ratio=4.92x\nN=8192,  l=64, k=12, b=64, w=512: compressed=128 selected=768 sliding=512 total=1408 ratio=5.82x\nN=64000, l=64, k=16, b=64, w=512: compressed=1000 selected=1024 sliding=512 total=2536 ratio=25.24x\nN=128000,l=64, k=16, b=64, w=512: compressed=2000 selected=1024 sliding=512 total=3536 ratio=36.20x' } },

    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: Every Worked Example Matches the Source', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: ಪ್ರತಿ Worked Example Source ಜೊತೆ ಹೊಂದಿಕೆಯಾಗುತ್ತದೆ',
      bodyEn: "All five ratios above match the source's claims exactly: 1024-token toy example ~3.56x, 4096-token mini exercise ~4.92x, 8192-token example ~5.82x, the headline 64k example ~25.2x, and 128k ~36.2x. Note the pattern: with k, b, and w held fixed, only the compressed term (N/l) grows with N -- so selected (kb=1024) and sliding (w=512) stay constant while the dense cost keeps growing, which is exactly why NSA's relative advantage improves at longer context.",
      bodyKn: 'ಮೇಲಿನ ಎಲ್ಲಾ ಐದೂ ratios source ya claims ಜೊತೆ ನಿಖರವಾಗಿ ಹೊಂದಿಕೆಯಾಗುತ್ತವೆ: 1024-token toy example ~3.56x, 4096-token mini exercise ~4.92x, 8192-token example ~5.82x, headline 64k example ~25.2x, ಮತ್ತೆ 128k ~36.2x. Pattern ಗಮನಿಸಿ: k, b, ಮತ್ತೆ w ಸ್ಥಿರವಾಗಿಟ್ಟುಕೊಂಡು, ಕೇವಲ compressed term (N/l) N ಜೊತೆ ಬೆಳೆಯುತ್ತದೆ -- ಆದ್ದರಿಂದ selected (kb=1024) ಮತ್ತೆ sliding (w=512) ಸ್ಥಿರವಾಗಿ ಉಳಿಯುತ್ತವೆ ಆದರೆ dense cost ಬೆಳೆಯುತ್ತಲೇ ಇರುತ್ತದೆ, ದೀರ್ಘ context ನಲ್ಲಿ NSA ya ಸಾಪೇಕ್ಷ ಅನುಕೂಲ ಸುಧಾರಿಸುವುದಕ್ಕೆ ಇದೇ ಕಾರಣ.' } },

    { type: 'heading', data: { textEn: 'Algorithmic Reduction ≠ Wall-Clock Speedup', textKn: 'Algorithmic Reduction ≠ Wall-Clock Speedup', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'Why "25x Fewer Comparisons" Does Not Mean "25x Faster"', headingKn: '"25x ಕಡಿಮೆ Comparisons" ಏಕೆ "25x ವೇಗ" ಎಂದೂ ಅರ್ಥವಲ್ಲ',
      bodyEn: 'A 25x reduction in attended key positions is a genuine algorithmic result, confirmed above by direct computation. But real hardware performance also depends on memory loads, kernel launches, indexing overhead, block-gathering cost, synchronization, and cache behavior -- none of which the simple key-count formula captures. This is exactly why NSA is designed jointly with its GPU kernel implementation, not treated as a pure algorithm applied on top of an unmodified attention kernel.',
      bodyKn: 'Attend ಮಾಡಿದ key positions ಗಳಲ್ಲಿ 25x reduction ಒಂದೂ ನಿಜ algorithmic ಫಲಿತಾಂಶ, ಮೇಲೆ ನೇರ ಲೆಕ್ಕಾಚಾರದಿಂದ ದೃಢಪಡಿಸಲಾಗಿದೆ. ಆದರೆ ನಿಜ hardware performance memory loads, kernel launches, indexing overhead, block-gathering cost, synchronization, ಮತ್ತೆ cache behavior ಮೇಲೂ ಅವಲಂಬಿಸಿದೆ -- ಇವಾವುದನ್ನೂ ಸರಳ key-count formula ಸೆರೆಹಿಡಿಯುವುದಿಲ್ಲ. NSA ಅದೂ ya GPU kernel implementation ಜೊತೆ ಜಂಟಿಯಾಗಿ ವಿನ್ಯಾಸಗೊಳಿಸಲಾಗಿದೆ, ಒಂದೂ ಬದಲಾಗದ attention kernel ಮೇಲೆ ಅನ್ವಯಿಸಿದ ಶುದ್ಧ algorithm ಆಗಿ ಪರಿಗಣಿಸಲಾಗಿಲ್ಲ ಎಂಬುದಕ್ಕೆ ಇದೇ ಕಾರಣ.' } },

    { type: 'heading', data: { textEn: 'Hardware Alignment: GQA-Group Block Sharing', textKn: 'Hardware Alignment: GQA-Group Block Sharing', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'Loading a Block Once, Reusing It Across Query Heads', headingKn: 'ಒಂದೂ Block ಒಮ್ಮೆ Load ಮಾಡಿ, Query Heads ಆದ್ದೂ ಮರುಬಳಸುವುದೂ',
      bodyEn: 'In Grouped-Query Attention, several query heads already share the same K/V heads. NSA exploits this: if four query heads in one GQA group select the same blocks (which they can, since block selection is typically shared within a group), the kernel loads that block\'s K/V once and reuses it for all four heads, instead of reloading identical data four times. This raises arithmetic intensity -- more useful matrix multiplication per byte moved from memory -- which is exactly the property that lets sparse algorithmic savings translate into real speedup, especially during memory-bandwidth-bound decode.',
      bodyKn: 'Grouped-Query Attention ನಲ್ಲಿ, ಹಲವೂ query heads ಈಗಾಗಲೇ ಅದೇ K/V heads ಹಂಚಿಕೊಳ್ಳುತ್ತವೆ. NSA ಇದನ್ನೂ ಬಳಸಿಕೊಳ್ಳುತ್ತದೆ: ಒಂದೂ GQA group ನಲ್ಲಿನ ನಾಲ್ಕೂ query heads ಅದೇ blocks ಆಯ್ಕೆ ಮಾಡಿದರೆ (ಇದೂ ಸಾಧ್ಯ, block selection ಸಾಮಾನ್ಯವಾಗಿ group ಒಳಗೆ ಹಂಚಿಕೊಳ್ಳಲಾಗುತ್ತದೆ), kernel ಆ block ya K/V ಒಮ್ಮೆ load ಮಾಡುತ್ತದೆ ಮತ್ತೆ ಎಲ್ಲಾ ನಾಲ್ಕೂ heads ಗೆ ಮರುಬಳಸುತ್ತದೆ, ಅದೇ ಡೇಟಾವನ್ನೂ ನಾಲ್ಕೂ ಬಾರಿ ಮತ್ತೆ load ಮಾಡುವ ಬದಲು. ಇದೂ arithmetic intensity ಹೆಚ್ಚಿಸುತ್ತದೆ -- memory ಇಂದ ಸ್ಥಳಾಂತರಿಸಿದ ಪ್ರತಿ byte ಗೆ ಹೆಚ್ಚು ಉಪಯುಕ್ತ matrix multiplication -- sparse algorithmic savings ನಿಜ speedup ಆಗಿ ಪರಿವರ್ತಿಸಲು ಈ ಗುಣವೇ ಕಾರಣ, ವಿಶೇಷವಾಗಿ memory-bandwidth-bound decode ಸಮಯದಲ್ಲಿ.' } },

    { type: 'diagram', data: {
      titleEn: 'Group-Level Block Loading', titleKn: 'Group-Level Block Loading',
      captionEn: 'Without group sharing, each of 4 query heads separately loads the same block K/V (4 loads). With GQA-group-aware sharing, the block is loaded once and reused by all 4 heads in the group -- fewer bytes moved per unit of useful compute.',
      captionKn: 'Group sharing ಇಲ್ಲದೆ, 4 query heads ಪ್ರತಿಯೊಂದೂ ಪ್ರತ್ಯೇಕವಾಗಿ ಅದೇ block K/V load ಮಾಡುತ್ತವೆ (4 loads). GQA-group-aware sharing ಜೊತೆ, block ಒಮ್ಮೆ load ಆಗುತ್ತದೆ ಮತ್ತೆ group ನಲ್ಲಿನ ಎಲ್ಲಾ 4 heads ಮರುಬಳಸುತ್ತವೆ -- ಪ್ರತಿ ಉಪಯುಕ್ತ compute ಗೆ ಕಡಿಮೆ bytes ಸ್ಥಳಾಂತರ.',
      svgCode: "<svg viewBox='0 0 700 180' xmlns='http://www.w3.org/2000/svg'><text x='170' y='20' fill='#f59e0b' font-size='12' text-anchor='middle'>Without sharing: 4 separate loads</text><rect x='40' y='35' width='60' height='30' fill='#0f172a' stroke='#f59e0b'/><text x='70' y='55' fill='#e2e8f0' font-size='9' text-anchor='middle'>load A</text><rect x='110' y='35' width='60' height='30' fill='#0f172a' stroke='#f59e0b'/><text x='140' y='55' fill='#e2e8f0' font-size='9' text-anchor='middle'>load A</text><rect x='180' y='35' width='60' height='30' fill='#0f172a' stroke='#f59e0b'/><text x='210' y='55' fill='#e2e8f0' font-size='9' text-anchor='middle'>load A</text><rect x='250' y='35' width='60' height='30' fill='#0f172a' stroke='#f59e0b'/><text x='280' y='55' fill='#e2e8f0' font-size='9' text-anchor='middle'>load A</text><text x='170' y='100' fill='#22c55e' font-size='12' text-anchor='middle'>With GQA-group sharing: 1 load, 4 reuses</text><rect x='140' y='115' width='60' height='30' fill='#0f172a' stroke='#22c55e'/><text x='170' y='135' fill='#e2e8f0' font-size='9' text-anchor='middle'>load A</text><line x1='170' y1='145' x2='60' y2='165' stroke='#64748b' stroke-width='1.5'/><line x1='170' y1='145' x2='130' y2='165' stroke='#64748b' stroke-width='1.5'/><line x1='170' y1='145' x2='210' y2='165' stroke='#64748b' stroke-width='1.5'/><line x1='170' y1='145' x2='280' y2='165' stroke='#64748b' stroke-width='1.5'/><text x='60' y='175' fill='#94a3b8' font-size='8' text-anchor='middle'>head1</text><text x='130' y='175' fill='#94a3b8' font-size='8' text-anchor='middle'>head2</text><text x='210' y='175' fill='#94a3b8' font-size='8' text-anchor='middle'>head3</text><text x='280' y='175' fill='#94a3b8' font-size='8' text-anchor='middle'>head4</text></svg>" } },

    { type: 'heading', data: { textEn: 'NSA vs Sliding-Window-Only Attention', textKn: 'NSA vs Sliding-Window-Only Attention', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'Local Coverage Is Not Enough', headingKn: 'Local Coverage ಸಾಕಾಗುವುದಿಲ್ಲ',
      bodyEn: 'A sliding-window-only design is differentiable, genuinely sparse, and gives strong local context -- but Part 1 already confirmed it permanently cannot see anything outside its fixed window, so its long-range recall can fail entirely regardless of relevance. NSA keeps that same reliable local channel (the sliding branch) but adds the compressed+selected pathway specifically to recover distant, genuinely important information that a pure window would silently drop.',
      bodyKn: 'ಒಂದೂ sliding-window-only design differentiable, ನಿಜವಾಗಿ sparse, ಮತ್ತೆ ಬಲವಾದ local context ನೀಡುತ್ತದೆ -- ಆದರೆ Part 1 ಈಗಾಗಲೇ ಅದೂ ಅದೂ ya ಸ್ಥಿರ window ಹೊರಗಿನ ಏನನ್ನೂ ಶಾಶ್ವತವಾಗಿ ನೋಡಲಾಗುವುದಿಲ್ಲ ಎಂದೂ ದೃಢಪಡಿಸಿತೂ, ಆದ್ದರಿಂದ relevance ಲೆಕ್ಕಿಸದೆ ಅದೂ ya ದೀರ್ಘ-ಶ್ರೇಣಿ recall ಸಂಪೂರ್ಣವಾಗಿ ವಿಫಲವಾಗಬಹುದು. NSA ಅದೇ ವಿಶ್ವಾಸಾರ್ಹ local channel (sliding branch) ಇಟ್ಟುಕೊಳ್ಳುತ್ತದೆ ಆದರೆ ಒಂದೂ ಶುದ್ಧ window ಮೌನವಾಗಿ ಬಿಟ್ಟುಬಿಡುವ ದೂರದ, ನಿಜವಾಗಿ ಮುಖ್ಯ ಮಾಹಿತಿ ಮರುಪಡೆಯಲು ನಿರ್ದಿಷ್ಟವಾಗಿ compressed+selected pathway ಸೇರಿಸುತ್ತದೆ.' } },

    { type: 'table', data: {
      captionEn: 'NSA vs Alternative Sparse-Attention Strategies', captionKn: 'NSA vs ಪರ್ಯಾಯ Sparse-Attention Strategies',
      rows: "Method|Trainable sparse structure|Query-adaptive|Long-range retrieval\nSliding window only|Yes|No (fixed position)|Weak -- fails outside window\nFixed block-sparse|Yes|No (fixed pattern)|Partial -- misses unindexed content\nInference-time KV pruning|No (dense-trained)|Sometimes|Partial -- train/inference mismatch\nMoBA (MoE-style routing)|Partial|Yes|Good\nNSA (compressed+selected+sliding)|Native|Yes|Strong" } },

    { type: 'heading', data: { textEn: 'NSA vs Fixed Block-Sparse and Inference-Time KV Pruning', textKn: 'NSA vs Fixed Block-Sparse ಮತ್ತೆ Inference-Time KV Pruning', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'Query-Adaptive vs Fixed, and Trained-In vs Bolted-On', headingKn: 'Query-Adaptive vs Fixed, ಮತ್ತೆ Trained-In vs Bolted-On',
      bodyEn: "A fixed block-sparse pattern (e.g. \"attend locally plus every 4th block\") is cheap and predictable, but it is not content-aware -- it reads the same positions regardless of what the query actually needs. NSA's top-k selection is query-adaptive: Part 2 genuinely confirmed that top_k_indices ranks blocks purely by learned relevance score, so different queries can select entirely different distant blocks. Inference-time KV pruning has a different problem: the model was trained assuming dense attention, then pruning is applied only at serving time, creating a train/inference mismatch. NSA trains with its sparse structure from the start, so there is no such mismatch -- this is the 'native' in Native Sparse Attention.",
      bodyKn: 'ಒಂದೂ fixed block-sparse pattern ("locally attend ಮತ್ತೆ ಪ್ರತಿ 4ನೇ block" ನಂತಹ) ಅಗ್ಗ ಮತ್ತೆ ಊಹಿಸಬಹುದಾದದೂ, ಆದರೆ ಇದೂ content-aware ಅಲ್ಲ -- query ಗೆ ನಿಜವಾಗಿ ಏನೂ ಬೇಕೂ ಎಂಬುದನ್ನೂ ಲೆಕ್ಕಿಸದೆ ಅದೇ positions ಓದುತ್ತದೆ. NSA ya top-k selection query-adaptive: Part 2 ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿತೂ top_k_indices blocks ಅನ್ನೂ ಕೇವಲ learned relevance score ಇಂದ rank ಮಾಡುತ್ತದೆ, ಆದ್ದರಿಂದ ಭಿನ್ನ queries ಸಂಪೂರ್ಣ ಭಿನ್ನ ದೂರದ blocks ಆಯ್ಕೆ ಮಾಡಬಹುದು. Inference-time KV pruning ಒಂದೂ ಭಿನ್ನ ಸಮಸ್ಯೆ ಹೊಂದಿದೆ: model dense attention ಊಹಿಸಿ train ಆಗಿತ್ತೂ, ನಂತರ serving time ನಲ್ಲಿ ಮಾತ್ರ pruning ಅನ್ವಯಿಸಲಾಗುತ್ತದೆ, ಒಂದೂ train/inference mismatch ಸೃಷ್ಟಿಸುತ್ತದೆ. NSA ಆರಂಭದಿಂದಲೇ ಅದೂ ya sparse structure ಜೊತೆ train ಆಗುತ್ತದೆ, ಆದ್ದರಿಂದ ಅಂತಹ mismatch ಇಲ್ಲ -- Native Sparse Attention ನಲ್ಲಿನ "Native" ಇದೇ.' } },

    { type: 'heading', data: { textEn: 'When Is NSA a Good Fit?', textKn: 'NSA ಯಾವಾಗ ಒಂದೂ ಒಳ್ಳೆಯ ಆಯ್ಕೆ?', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'Long-Context Pre-Training, Not a Drop-In Retrofit', headingKn: 'ದೀರ್ಘ-Context Pre-Training, ಒಂದೂ Drop-In Retrofit ಅಲ್ಲ',
      bodyEn: "NSA's genuinely computed advantage grows with context length -- confirmed above, the reduction ratio rose from ~3.56x at N=1024 to ~36.2x at N=128,000 with the same k, b, w. This makes NSA most valuable during long-context pre-training or serving, where the sparse structure has enough sequence length to amortize its routing/kernel overhead. It is a poor fit for simply swapping in on top of an already-trained dense-attention model without further training, because that model never learned how to compress, route, or gate the three branches -- those behaviors do not emerge automatically. At short/moderate context, dense FlashAttention is already efficient, so the added architectural complexity may not be worth it.",
      bodyKn: 'NSA ya ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಿದ advantage context length ಜೊತೆ ಬೆಳೆಯುತ್ತದೆ -- ಮೇಲೆ ದೃಢಪಡಿಸಿದಂತೆ, ಅದೇ k, b, w ಜೊತೆ reduction ratio N=1024 ನಲ್ಲಿ ~3.56x ಇಂದ N=128,000 ನಲ್ಲಿ ~36.2x ಗೆ ಏರಿತೂ. ಇದೂ NSA ಅನ್ನೂ ದೀರ್ಘ-context pre-training ಅಥವಾ serving ಸಮಯದಲ್ಲಿ ಅತ್ಯಂತ ಮೌಲ್ಯಯುತ ಮಾಡುತ್ತದೆ, ಅಲ್ಲಿ sparse structure ಗೆ ಅದೂ ya routing/kernel overhead amortize ಮಾಡಲು ಸಾಕಷ್ಟು sequence length ಇದೆ. ಈಗಾಗಲೇ train ಆದ dense-attention model ಮೇಲೆ ಹೆಚ್ಚಿನ training ಇಲ್ಲದೆ ಕೇವಲ swap ಮಾಡಲು ಇದೂ ಕಳಪೆ ಆಯ್ಕೆ, ಏಕೆಂದರೆ ಆ model ಎಂದಿಗೂ ಮೂರೂ branches ಅನ್ನೂ compress, route, ಅಥವಾ gate ಮಾಡಲು ಕಲಿತಿಲ್ಲ -- ಆ ವರ್ತನೆಗಳು ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಹೊರಹೊಮ್ಮುವುದಿಲ್ಲ. ಚಿಕ್ಕ/ಮಧ್ಯಮ context ನಲ್ಲಿ, dense FlashAttention ಈಗಾಗಲೇ ಪರಿಣಾಮಕಾರಿ, ಆದ್ದರಿಂದ ಸೇರಿಸಿದ architectural complexity ಮೌಲ್ಯಯುತವಾಗದಿರಬಹುದು.' } },

    { type: 'heading', data: { textEn: 'Three Hyperparameters, Three Different Levers', textKn: 'ಮೂರೂ Hyperparameters, ಮೂರೂ ಭಿನ್ನ Levers', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'l, k, and w Each Control a Different Tradeoff', headingKn: 'l, k, ಮತ್ತೆ w ಪ್ರತಿಯೊಂದೂ ಒಂದೂ ಭಿನ್ನ Tradeoff ನಿಯಂತ್ರಿಸುತ್ತದೆ',
      bodyEn: "Genuinely confirmed above: larger l shrinks the compressed term (N/l) but makes each summary coarser, hurting routing resolution. Larger k reopens more blocks at full resolution -- genuinely visible in the table above, since raising k from 4 (N=1024 example) to 16 (64k/128k examples) directly raised the selected cost from kb=128 to kb=1024. Larger w gives more guaranteed local coverage at a proportional cost, since sliding cost is exactly w regardless of N. None of the three can be pushed arbitrarily high for free -- each buys a specific kind of quality at a specific compute cost.",
      bodyKn: 'ಮೇಲೆ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದಂತೆ: ದೊಡ್ಡ l compressed term (N/l) ಕುಗ್ಗಿಸುತ್ತದೆ ಆದರೆ ಪ್ರತಿ summary ಒರಟಾಗಿಸುತ್ತದೆ, routing resolution ಗೆ ಹಾನಿ ಮಾಡುತ್ತದೆ. ದೊಡ್ಡ k ಹೆಚ್ಚು blocks ಗಳನ್ನೂ full resolution ನಲ್ಲಿ ಮತ್ತೆ ತೆರೆಯುತ್ತದೆ -- ಮೇಲಿನ ಕೋಷ್ಟಕದಲ್ಲಿ ನೇರವಾಗಿ ಕಾಣಿಸುತ್ತದೆ, k ಅನ್ನೂ 4 ಇಂದ (N=1024 example) 16 ಗೆ (64k/128k examples) ಹೆಚ್ಚಿಸುವುದೂ selected cost ಅನ್ನೂ kb=128 ಇಂದ kb=1024 ಗೆ ನೇರವಾಗಿ ಹೆಚ್ಚಿಸಿತೂ. ದೊಡ್ಡ w N ಲೆಕ್ಕಿಸದೆ ಸಮಾನುಪಾತದ cost ಗೆ ಹೆಚ್ಚು ಖಚಿತ local coverage ನೀಡುತ್ತದೆ, ಏಕೆಂದರೆ sliding cost ನಿಖರವಾಗಿ w. ಮೂರರಲ್ಲಿ ಯಾವುದನ್ನೂ ಉಚಿತವಾಗಿ ಎಷ್ಟೇ ಹೆಚ್ಚಿಸಲಾಗುವುದಿಲ್ಲ -- ಪ್ರತಿಯೊಂದೂ ಒಂದೂ ನಿರ್ದಿಷ್ಟ compute cost ಗೆ ಒಂದೂ ನಿರ್ದಿಷ್ಟ ರೀತಿಯ ಗುಣಮಟ್ಟ ಖರೀದಿಸುತ್ತದೆ.' } },
    { type: 'concept', data: {
      headingEn: 'Common Misconceptions, Revisited With What Was Actually Confirmed', headingKn: 'ಸಾಮಾನ್ಯ ತಪ್ಪುಗ್ರಹಿಕೆಗಳು, ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ್ದೂ ಜೊತೆ ಮತ್ತೆ ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
      bodyEn: "• 'Top-k selects individual tokens' -- false; Part 2 genuinely confirmed top_k_indices returns block indices, and gather_selected_blocks expands each into l contiguous tokens.\n• 'Compressed attention only saves compute' -- false; the same genuinely-run attention() call produces both out_cmp and the exact weights reused for routing.\n• 'The gate picks one winning branch' -- false; genuinely confirmed the three sigmoid gates (0.82, 0.87, 0.18) can be simultaneously large for two branches.\n• 'A 25x FLOP reduction means 25x faster' -- false; confirmed only as an algorithmic key-count ratio, with hardware alignment (GQA-group block sharing) required to realize it in practice.\n• 'NSA can replace attention in any pretrained model for free' -- false; NSA's branches and gate were never trained on a dense-attention checkpoint, so their behavior does not emerge automatically.",
      bodyKn: "• 'Top-k ಪ್ರತ್ಯೇಕ tokens ಆಯ್ಕೆ ಮಾಡುತ್ತದೆ' -- ತಪ್ಪೂ; Part 2 ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿತೂ top_k_indices block indices ಹಿಂತಿರುಗಿಸುತ್ತದೆ, ಮತ್ತೆ gather_selected_blocks ಪ್ರತಿಯೊಂದನ್ನೂ l ಸಂಲಗ್ನ tokens ಗೆ ವಿಸ್ತರಿಸುತ್ತದೆ.\n• 'Compressed attention ಕೇವಲ compute ಉಳಿಸುತ್ತದೆ' -- ತಪ್ಪೂ; ಅದೇ ನಿಜವಾಗಿ-ಓಡಿಸಿದ attention() call out_cmp ಮತ್ತೆ routing ಗಾಗಿ ಮರುಬಳಸಿದ ನಿಖರ weights ಎರಡನ್ನೂ ಉತ್ಪಾದಿಸುತ್ತದೆ.\n• 'Gate ಒಂದೂ ಗೆಲ್ಲುವ branch ಆಯ್ಕೆ ಮಾಡುತ್ತದೆ' -- ತಪ್ಪೂ; ಮೂರೂ sigmoid gates (0.82, 0.87, 0.18) ಎರಡೂ branches ಗೆ ಏಕಕಾಲದಲ್ಲಿ ದೊಡ್ಡದಾಗಿರಬಹುದು ಎಂದೂ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ.\n• '25x FLOP reduction ಎಂದರೆ 25x ವೇಗ' -- ತಪ್ಪೂ; ಇದೂ ಕೇವಲ ಒಂದೂ algorithmic key-count ratio ಆಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ, ಇದನ್ನೂ ಪ್ರಾಯೋಗಿಕವಾಗಿ ಸಾಧಿಸಲು hardware alignment (GQA-group block sharing) ಅಗತ್ಯ.\n• 'NSA ಯಾವುದೇ pretrained model ನಲ್ಲಿ attention ಅನ್ನೂ ಉಚಿತವಾಗಿ ಬದಲಾಯಿಸಬಹುದು' -- ತಪ್ಪೂ; NSA ya branches ಮತ್ತೆ gate ಎಂದಿಗೂ ಒಂದೂ dense-attention checkpoint ಮೇಲೆ train ಆಗಿಲ್ಲ, ಆದ್ದರಿಂದ ಅವುಗಳ ವರ್ತನೆ ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಹೊರಹೊಮ್ಮುವುದಿಲ್ಲ." } },

    { type: 'table', data: {
      captionEn: 'Part 3 Genuinely Confirmed Results', captionKn: 'Part 3 ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ ಫಲಿತಾಂಶಗಳು',
      rows: "Context length (N)|Genuinely computed NSA keys/query|Genuinely computed reduction vs dense\n1,024|288|3.56x\n4,096|832|4.92x\n8,192|1,408|5.82x\n64,000|2,536|25.24x\n128,000|3,536|36.20x" } },

    { type: 'concept', data: {
      headingEn: 'Key Terms', headingKn: 'ಮುಖ್ಯ ಪದಗಳು',
      bodyEn: '• Branch gate: a learned, per-query, per-branch weighting (sigmoid-based here) that does not need to sum to 1 -- genuinely confirmed to sum to 1.87 in the worked example\n• NSA compute budget: O(N(N/l + kb + w)), confirmed to give ratios of 3.56x-36.2x across five genuinely computed context lengths\n• Hardware alignment: designing the sparse pattern (block-level, GQA-group-shareable) so the actual GPU kernel can exploit it, not just reduce FLOPs on paper\n• Arithmetic intensity: useful compute per byte moved from memory -- raised by loading a selected block once and reusing it across a GQA group\n• Query-adaptive sparsity: which blocks get attended depends on the specific query\'s learned relevance scores, not a fixed schedule',
      bodyKn: '• Branch gate: ಒಂದೂ learned, per-query, per-branch weighting (ಇಲ್ಲಿ sigmoid-based) ಇದೂ 1 ಗೆ ಸೇರಬೇಕಾಗಿಲ್ಲ -- worked example ನಲ್ಲಿ 1.87 ಗೆ ಸೇರುತ್ತದೆ ಎಂದೂ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ\n• NSA compute budget: O(N(N/l + kb + w)), ಐದೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಿದ context lengths ಆದ್ದೂ 3.56x-36.2x ratios ನೀಡುತ್ತದೆ ಎಂದೂ ದೃಢಪಡಿಸಲಾಗಿದೆ\n• Hardware alignment: sparse pattern ಅನ್ನೂ (block-level, GQA-group-shareable) ವಿನ್ಯಾಸಗೊಳಿಸುವುದೂ ಆದ್ದರಿಂದ ನಿಜ GPU kernel ಅದನ್ನೂ ಬಳಸಿಕೊಳ್ಳಬಹುದು, ಕೇವಲ ಕಾಗದದ ಮೇಲೆ FLOPs ಕಡಿಮೆ ಮಾಡುವುದಲ್ಲ\n• Arithmetic intensity: memory ಇಂದ ಸ್ಥಳಾಂತರಿಸಿದ ಪ್ರತಿ byte ಗೆ ಉಪಯುಕ್ತ compute -- ಒಂದೂ selected block ಒಮ್ಮೆ load ಮಾಡಿ GQA group ಆದ್ದೂ ಮರುಬಳಸುವುದರಿಂದ ಹೆಚ್ಚಾಗುತ್ತದೆ\n• Query-adaptive sparsity: ಯಾವ blocks attend ಆಗುತ್ತವೆ ಎಂಬುದೂ ನಿರ್ದಿಷ್ಟ query ya learned relevance scores ಮೇಲೆ ಅವಲಂಬಿಸಿದೆ, ಒಂದೂ ಸ್ಥಿರ schedule ಅಲ್ಲ' } },

    { type: 'concept', data: {
      headingEn: 'Key Takeaways', headingKn: 'ಮುಖ್ಯ ಅಂಶಗಳು',
      bodyEn: "• The branch gate was genuinely implemented and confirmed to produce independent per-branch values summing to 1.87, not 1.0 -- the model can amplify multiple branches simultaneously rather than choosing a single winner.\n• The full NSA compute formula O(N(N/l + kb + w)) was genuinely computed across five context lengths, exactly reproducing every ratio the source claims: 3.56x, 4.92x, 5.82x, 25.24x, and 36.20x.\n• The advantage grows with N because only the compressed term scales with sequence length while selected and sliding costs stay fixed -- confirmed directly by the widening ratios.\n• Algorithmic FLOP reduction is necessary but not sufficient for real speedup; NSA's hardware alignment (block-level access, GQA-group block sharing) is what lets the algorithmic savings actually show up in wall-clock time.\n• Compared with sliding-window-only, fixed block-sparse, and inference-time KV pruning, NSA's combination of query-adaptive routing and training-time sparsity gives it the strongest long-range retrieval among the compared methods -- but it is best suited to long-context pre-training, not a retrofit onto an already dense-trained model.",
      bodyKn: '• Branch gate ಅನ್ನೂ ನಿಜವಾಗಿ implement ಮಾಡಲಾಯಿತೂ ಮತ್ತೆ 1.0 ಅಲ್ಲ, 1.87 ಗೆ ಸೇರುವ ಸ್ವತಂತ್ರ per-branch values ಉತ್ಪಾದಿಸುತ್ತದೆ ಎಂದೂ ದೃಢಪಡಿಸಲಾಯಿತೂ -- model ಒಂದೂ ಗೆಲುವನ್ನೂ ಆಯ್ಕೆ ಮಾಡುವ ಬದಲು ಏಕಕಾಲದಲ್ಲಿ ಅನೇಕ branches ಅನ್ನೂ ಹೆಚ್ಚಿಸಬಹುದು.\n• ಪೂರ್ಣ NSA compute formula O(N(N/l + kb + w)) ಅನ್ನೂ ಐದೂ context lengths ಆದ್ದೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಲಾಯಿತೂ, source claim ಮಾಡುವ ಪ್ರತಿ ratio ಅನ್ನೂ ನಿಖರವಾಗಿ ಪುನರುತ್ಪಾದಿಸಿತೂ: 3.56x, 4.92x, 5.82x, 25.24x, ಮತ್ತೆ 36.20x.\n• Advantage N ಜೊತೆ ಬೆಳೆಯುತ್ತದೆ ಏಕೆಂದರೆ ಕೇವಲ compressed term sequence length ಜೊತೆ ಪ್ರಮಾಣಿಸುತ್ತದೆ ಆದರೆ selected ಮತ್ತೆ sliding costs ಸ್ಥಿರವಾಗಿ ಉಳಿಯುತ್ತವೆ -- ವಿಸ್ತರಿಸುತ್ತಿರುವ ratios ಇಂದ ನೇರವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ.\n• Algorithmic FLOP reduction ನಿಜ speedup ಗೆ ಅಗತ್ಯ ಆದರೆ ಸಾಕಾಗುವುದಿಲ್ಲ; NSA ya hardware alignment (block-level access, GQA-group block sharing) algorithmic savings ನಿಜವಾಗಿ wall-clock time ನಲ್ಲಿ ಕಾಣಿಸಿಕೊಳ್ಳಲು ಅನುಮತಿಸುತ್ತದೆ.\n• Sliding-window-only, fixed block-sparse, ಮತ್ತೆ inference-time KV pruning ಜೊತೆ ಹೋಲಿಸಿದಾಗ, NSA ya query-adaptive routing ಮತ್ತೆ training-time sparsity ಸಂಯೋಜನೆ ಹೋಲಿಸಿದ ವಿಧಾನಗಳಲ್ಲಿ ಅತ್ಯಂತ ಬಲವಾದ ದೀರ್ಘ-ಶ್ರೇಣಿ retrieval ನೀಡುತ್ತದೆ -- ಆದರೆ ಇದೂ ದೀರ್ಘ-context pre-training ಗೆ ಅತ್ಯಂತ ಸೂಕ್ತ, ಈಗಾಗಲೇ dense-trained model ಮೇಲೆ ಒಂದೂ retrofit ಅಲ್ಲ.' } },

    { type: 'quiz', data: { questions: [
      { q: 'Genuinely confirmed: what did the three sigmoid branch gates sum to in the worked example?',
        qKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: worked example ನಲ್ಲಿ ಮೂರೂ sigmoid branch gates ಏನಿಗೆ ಸೇರಿದವೂ?',
        opts: ['Exactly 1.0, like a softmax', '1.87, confirming gates are independent and need not sum to 1', '0.0', '3.0'], correct: 1,
        optsKn: ['ಒಂದೂ softmax ನಂತೆ, ನಿಖರವಾಗಿ 1.0', '1.87, gates ಸ್ವತಂತ್ರ ಮತ್ತೆ 1 ಗೆ ಸೇರಬೇಕಾಗಿಲ್ಲ ಎಂದೂ ದೃಢಪಡಿಸುತ್ತದೆ', '0.0', '3.0'] },
      { q: 'Genuinely confirmed: for N=128,000, l=64, k=16, b=64, w=512, what was the computed reduction ratio vs dense attention?',
        qKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: N=128,000, l=64, k=16, b=64, w=512 ಗೆ, dense attention ಎದುರೂ ಲೆಕ್ಕಹಾಕಿದ reduction ratio ಏನೂ?',
        opts: ['~3.56x', '~25.24x', '~36.20x', '~5.82x'], correct: 2,
        optsKn: ['~3.56x', '~25.24x', '~36.20x', '~5.82x'] },
      { q: "Why does NSA's advantage over dense attention grow as context length N increases (with k, b, w fixed)?",
        qKn: '(k, b, w ಸ್ಥಿರವಾಗಿಟ್ಟುಕೊಂಡು) context length N ಹೆಚ್ಚಾದಂತೆ dense attention ಎದುರೂ NSA ya advantage ಏಕೆ ಬೆಳೆಯುತ್ತದೆ?',
        opts: ['The sliding window grows with N', 'Only the compressed term (N/l) scales with N, while selected (kb) and sliding (w) costs stay constant, so dense cost pulls further ahead', 'Selected blocks get larger with N', 'It does not actually grow -- the ratio is constant'], correct: 1,
        optsKn: ['Sliding window N ಜೊತೆ ಬೆಳೆಯುತ್ತದೆ', 'ಕೇವಲ compressed term (N/l) N ಜೊತೆ ಪ್ರಮಾಣಿಸುತ್ತದೆ, ಆದರೆ selected (kb) ಮತ್ತೆ sliding (w) costs ಸ್ಥಿರವಾಗಿ ಉಳಿಯುತ್ತವೆ, ಆದ್ದರಿಂದ dense cost ಇನ್ನೂ ಮುಂದೆ ಎಳೆಯುತ್ತದೆ', 'Selected blocks N ಜೊತೆ ದೊಡ್ಡದಾಗುತ್ತವೆ', 'ಇದೂ ನಿಜವಾಗಿ ಬೆಳೆಯುವುದಿಲ್ಲ -- ratio ಸ್ಥಿರ'] },
      { q: 'Why can a genuine 25x algorithmic reduction in attended keys fail to produce a 25x wall-clock speedup?',
        qKn: '25x ಗಳಿಸಿದ keys ಗಳಲ್ಲಿ ಒಂದೂ ನಿಜ algorithmic reduction ಏಕೆ ಒಂದೂ 25x wall-clock speedup ಉತ್ಪಾದಿಸಲು ವಿಫಲವಾಗಬಹುದು?',
        opts: ['Because Python is always slow', 'Because real hardware performance also depends on memory loads, kernel launches, indexing overhead, and synchronization, which the FLOP count does not capture', 'Because GPUs cannot do sparse computation', 'Because dense attention is actually faster'], correct: 1,
        optsKn: ['ಏಕೆಂದರೆ Python ಯಾವಾಗಲೂ ನಿಧಾನ', 'ಏಕೆಂದರೆ ನಿಜ hardware performance memory loads, kernel launches, indexing overhead, ಮತ್ತೆ synchronization ಮೇಲೂ ಅವಲಂಬಿಸಿದೆ, ಇವನ್ನೂ FLOP count ಸೆರೆಹಿಡಿಯುವುದಿಲ್ಲ', 'ಏಕೆಂದರೆ GPUs sparse computation ಮಾಡಲಾಗುವುದಿಲ್ಲ', 'ಏಕೆಂದರೆ dense attention ನಿಜವಾಗಿ ವೇಗ'] },
      { q: 'Why is NSA a poor fit for simply replacing attention in an already-trained dense model without further training?',
        qKn: 'ಹೆಚ್ಚಿನ training ಇಲ್ಲದೆ ಈಗಾಗಲೇ train ಆದ ಒಂದೂ dense model ನಲ್ಲಿ attention ಅನ್ನೂ ಕೇವಲ ಬದಲಾಯಿಸಲು NSA ಏಕೆ ಕಳಪೆ ಆಯ್ಕೆ?',
        opts: ['NSA cannot run on GPUs', 'The model never learned how to compress, route, or gate the three branches -- those behaviors do not emerge automatically', 'NSA requires a different vocabulary', 'NSA only works with 8-bit weights'], correct: 1,
        optsKn: ['NSA GPUs ಮೇಲೆ ಓಡಲಾಗುವುದಿಲ್ಲ', 'Model ಎಂದಿಗೂ ಮೂರೂ branches ಅನ್ನೂ compress, route, ಅಥವಾ gate ಮಾಡಲು ಕಲಿತಿಲ್ಲ -- ಆ ವರ್ತನೆಗಳು ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಹೊರಹೊಮ್ಮುವುದಿಲ್ಲ', 'NSA ಗೆ ಒಂದೂ ಭಿನ್ನ vocabulary ಬೇಕು', 'NSA ಕೇವಲ 8-bit weights ಜೊತೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ'] },
    ] } },
  ],
};
