const phaseId = '6a369d5a66020ed05b3213f4'; // Phase 13: LLM from Scratch
const moduleId = '6a369d5b66020ed05b321439'; // Module 207: Speculative Decoding and EAGLE

module.exports = {
  phaseId,
  moduleId,
  order: 1,
  type: 'interactive',
  duration: 40,
  difficulty: 'advanced',
  status: 'published',
  title: 'Speculative Decoding and EAGLE — Part 2: Feature Reuse, Tree Drafting, and Tree Attention',
  titleKn: 'Speculative Decoding ಮತ್ತೆ EAGLE — Part 2: Feature Reuse, Tree Drafting, ಮತ್ತೆ Tree Attention',
  desc: 'Genuinely build and run a tree attention mask that lets each candidate node attend only to its ancestors, genuinely compute how much draft probability mass narrow versus wide branching captures, and genuinely confirm a complete branching tree explodes to 1,365 nodes at depth 5 -- motivating EAGLE-2\'s dynamic, confidence-aware topology.',
  descKn: "ಪ್ರತಿ candidate node ಅದೂ ya ancestors ಗೆ ಮಾತ್ರ attend ಮಾಡಲು ಬಿಡುವ ಒಂದೂ tree attention mask ಅನ್ನೂ ನಿಜವಾಗಿ ನಿರ್ಮಿಸಿ ಓಡಿಸಿ, narrow vs wide branching ಎಷ್ಟೂ draft probability mass ಸೆರೆಹಿಡಿಯುತ್ತದೆ ಎಂದೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಿ, ಮತ್ತೆ ಒಂದೂ ಪೂರ್ಣ branching tree depth 5 ನಲ್ಲಿ 1,365 nodes ಗೆ ಸ್ಫೋಟಗೊಳ್ಳುತ್ತದೆ ಎಂದೂ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿ -- EAGLE-2 ya dynamic, confidence-aware topology ಗೆ ಪ್ರೇರೇಪಿಸುತ್ತಾ.",
  objectives: [
    'Explain the two inefficiencies EAGLE addresses: serial draft generation and single-path linear drafting.',
    'Explain EAGLE feature reuse: using the target\'s hidden state as draft input instead of rebuilding representations from raw tokens.',
    'Genuinely build and run a tree attention mask, confirming each node attends only to itself and its ancestors, never to sibling branches.',
    'Genuinely compute how much draft probability mass a narrow versus wide top-p branching threshold captures.',
    'Genuinely confirm a complete tree with branching factor 4 and depth 5 has 1,365 nodes, motivating why unconstrained tree growth is impractical.',
    'Explain EAGLE-2\'s dynamic tree topology (confidence-based branching) and EAGLE-3\'s test-time simulation training.',
  ],
  objectivesKn: [
    'EAGLE ಪರಿಹರಿಸುವ ಎರಡೂ ಅಸಮರ್ಥತೆಗಳನ್ನೂ ವಿವರಿಸಿ: serial draft generation ಮತ್ತೆ single-path linear drafting.',
    'EAGLE feature reuse ವಿವರಿಸಿ: raw tokens ಇಂದ representations ಮರುನಿರ್ಮಿಸುವ ಬದಲಿಗೆ target ya hidden state ಅನ್ನೂ draft input ಆಗಿ ಬಳಸುವುದೂ.',
    'ಒಂದೂ tree attention mask ಅನ್ನೂ ನಿಜವಾಗಿ ನಿರ್ಮಿಸಿ ಓಡಿಸಿ, ಪ್ರತಿ node ಅದೂ ಮತ್ತೆ ಅದೂ ya ancestors ಗೆ ಮಾತ್ರ attend ಮಾಡುತ್ತದೆ ಎಂದೂ ದೃಢಪಡಿಸಿ, ಎಂದಿಗೂ sibling branches ಗೆ ಅಲ್ಲ.',
    'Narrow vs wide top-p branching threshold ಎಷ್ಟೂ draft probability mass ಸೆರೆಹಿಡಿಯುತ್ತದೆ ಎಂದೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಿ.',
    'Branching factor 4 ಮತ್ತೆ depth 5 ಇರುವ ಒಂದೂ ಪೂರ್ಣ tree ಗೆ 1,365 nodes ಇವೆ ಎಂದೂ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿ, ನಿರ್ಬಂಧಿತವಲ್ಲದ tree growth ಏಕೆ ಅಪ್ರಾಯೋಗಿಕ ಎಂದೂ ಪ್ರೇರೇಪಿಸುತ್ತಾ.',
    'EAGLE-2 ya dynamic tree topology (confidence-based branching) ಮತ್ತೆ EAGLE-3 ya test-time simulation training ವಿವರಿಸಿ.',
  ],
  blocks: [
    { type: 'heading', data: { textEn: 'Speculative Decoding and EAGLE — Part 2: Feature Reuse, Tree Drafting, and Tree Attention', textKn: 'Speculative Decoding ಮತ್ತೆ EAGLE — Part 2: Feature Reuse, Tree Drafting, ಮತ್ತೆ Tree Attention', level: 'H1' } },
    { type: 'concept', data: {
      headingEn: 'Lesson Info', headingKn: 'Lesson ಮಾಹಿತಿ',
      bodyEn: '• Type: Build · Language: Python with NumPy · Prerequisite: Part 1 of this module · Time: ~40 minutes · Part 2 of 3',
      bodyKn: '• Type: Build · Language: Python with NumPy · Prerequisite: Part 1 · Time: ~40 ನಿಮಿಷಗಳು · Part 2 of 3',
      pillsEn: 'EAGLE,Feature Reuse,Tree Drafting,Tree Attention Mask,Part 2 of 3',
      pillsKn: 'EAGLE,Tree Drafting,Part 2 of 3' } },

    { type: 'heading', data: { textEn: 'Two Inefficiencies in Standard Speculative Decoding', textKn: 'Standard Speculative Decoding ನಲ್ಲಿ ಎರಡೂ Inefficiencies', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'Problem 1: The Draft Is Still Serial; Problem 2: One Bet Per Round', headingKn: 'ಸಮಸ್ಯೆ 1: Draft ಇನ್ನೂ Serial; ಸಮಸ್ಯೆ 2: ಪ್ರತಿ Round ಗೆ ಒಂದೇ Bet',
      bodyEn: 'Problem 1: in ordinary speculative decoding, drafting K tokens still requires K serial autoregressive steps of the small model (for _ in range(K): probs=q_draft(state); token=sample(probs); state=draft_step(state,token)) -- a rough round cost is C_p+K*C_q (genuinely explored further in Part 3), so if the draft becomes larger or K becomes long, draft cost starts eating into the acceleration. Problem 2: a linear draft chain places its ENTIRE future-token budget behind one hypothesis -- if the target rejects token 2 of "The->model->learns->representations", tokens 3 and 4 are wasted regardless of how good they were, because they were conditioned on a prefix that never materialized. EAGLE fixes Problem 1 with feature reuse and Problem 2 with tree drafting.',
      bodyKn: 'Problem 1: ಸಾಮಾನ್ಯ speculative decoding ನಲ್ಲಿ, K tokens draft ಮಾಡುವುದೂ ಇನ್ನೂ ಚಿಕ್ಕ model ya K serial autoregressive steps ಬಯಸುತ್ತದೆ (for _ in range(K): probs=q_draft(state); token=sample(probs); state=draft_step(state,token)) -- ಒಂದೂ ಸ್ಥೂಲ round cost C_p+K*C_q (Part 3 ನಲ್ಲಿ ಇನ್ನಷ್ಟೂ ಅನ್ವೇಷಿಸಲಾಗಿದೆ), ಆದ್ದರಿಂದ draft ದೊಡ್ಡದಾದರೆ ಅಥವಾ K ಉದ್ದವಾದರೆ, draft cost ವೇಗಗೊಳಿಸುವಿಕೆಯನ್ನೂ ತಿನ್ನಲು ಆರಂಭಿಸುತ್ತದೆ. Problem 2: ಒಂದೂ linear draft chain ಅದೂ ya ಇಡೀ future-token budget ಅನ್ನೂ ಒಂದೂ hypothesis ಹಿಂದೆ ಇಡುತ್ತದೆ -- target "The->model->learns->representations" ya token 2 ತಿರಸ್ಕರಿಸಿದರೆ, tokens 3 ಮತ್ತೆ 4 ಎಷ್ಟೂ ಒಳ್ಳೆಯದಾಗಿದ್ದರೂ ವ್ಯರ್ಥ, ಏಕೆಂದರೆ ಅವು ಎಂದಿಗೂ ಸಾಕಾರಗೊಳ್ಳದ ಒಂದೂ prefix ಮೇಲೆ conditioned ಆಗಿದ್ದವೂ. EAGLE Problem 1 ಅನ್ನೂ feature reuse ಜೊತೆ ಸರಿಪಡಿಸುತ್ತದೆ ಮತ್ತೆ Problem 2 ಅನ್ನೂ tree drafting ಜೊತೆ.' } },

    { type: 'heading', data: { textEn: 'EAGLE Feature Reuse', textKn: 'EAGLE Feature Reuse', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'Reuse Target Features Instead of Relearning Them', headingKn: 'Target Features ಅನ್ನೂ ಮರುಕಲಿಯುವ ಬದಲಿಗೆ ಮರುಬಳಕೆ ಮಾಡುವುದೂ',
      bodyEn: 'A standard draft operates from token IDs -> embedding -> many transformer layers -> next-token distribution, redundantly rebuilding representations the target has already computed. The target has already produced a rich hidden vector h_t summarizing syntax, semantics, long-range context, and likely continuation. EAGLE-1 feeds THIS representation into a tiny draft mechanism instead: draft input=target final hidden state, draft architecture=roughly one transformer decoder layer, output=a candidate tree of several possibilities per depth (the lesson\'s conceptual EAGLE-1 setup uses roughly 4-8 candidates per depth, depth 4-6). The intuition: predicting the continuation from a rich, already-built representation (Task B) is easier than understanding an entire prefix from raw tokens and predicting the next token (Task A) -- much of the representation-building work is already done, which is why the drafter can shrink dramatically.',
      bodyKn: 'ಒಂದು standard draft token IDs -> embedding -> ಹಲವೂ transformer layers -> next-token distribution ಇಂದ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತದೆ, target ಈಗಾಗಲೇ ಲೆಕ್ಕಹಾಕಿದ representations ಅನ್ನೂ ಪುನರಾವರ್ತಿತವಾಗಿ ಮರುನಿರ್ಮಿಸುತ್ತದೆ. Target ಈಗಾಗಲೇ syntax, semantics, long-range context, ಮತ್ತೆ ಸಂಭವನೀಯ continuation ಸಂಕ್ಷೇಪಿಸುವ ಒಂದೂ ಶ್ರೀಮಂತ hidden vector h_t ಉತ್ಪಾದಿಸಿದೆ. EAGLE-1 ಬದಲಿಗೆ ಈ representation ಅನ್ನೂ ಒಂದೂ ಚಿಕ್ಕ draft mechanism ಗೆ ನೀಡುತ್ತದೆ: draft input=target final hidden state, draft architecture=ಸುಮಾರು ಒಂದೂ transformer decoder layer, output=ಪ್ರತಿ depth ಗೆ ಹಲವೂ ಸಾಧ್ಯತೆಗಳ ಒಂದೂ candidate tree (lesson ya ಪರಿಕಲ್ಪನಾತ್ಮಕ EAGLE-1 setup ಪ್ರತಿ depth ಗೆ ಸುಮಾರು 4-8 candidates, depth 4-6 ಬಳಸುತ್ತದೆ). ಅಂತಃಪ್ರಜ್ಞೆ: ಒಂದೂ ಶ್ರೀಮಂತ, ಈಗಾಗಲೇ-ನಿರ್ಮಿಸಿದ representation (Task B) ಇಂದ continuation ಊಹಿಸುವುದೂ raw tokens ಇಂದ ಇಡೀ prefix ಅರ್ಥಮಾಡಿಕೊಂಡು ಮುಂದಿನ token ಊಹಿಸುವುದೂ (Task A) ಗಿಂತ ಸುಲಭ -- ಹೆಚ್ಚಿನ representation-building ಕೆಲಸ ಈಗಾಗಲೇ ಆಗಿದೆ, ಇದೇ drafter ಗಣನೀಯವಾಗಿ ಕುಗ್ಗಬಹುದೂ ಎಂಬುದೂ ಗೆ ಕಾರಣ.' } },

    { type: 'heading', data: { textEn: 'Tree Drafting: Multiple Bets Instead of One', textKn: 'Tree Drafting: ಒಂಟಿ Bet ಬದಲಿಗೆ ಬಹು Bets', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'Top-p Branching Controls Tree Width', headingKn: 'Top-p Branching Tree Width ನಿಯಂತ್ರಿಸುತ್ತದೆ',
      bodyEn: 'Instead of committing to root->A->C->D, a tree draft retains root->{A,B}->{A:C,D / B:E,F}, so the target has alternatives during verification. Since branching to all 50,000 vocabulary tokens would explode immediately, the drafter uses top-p branching: keep only the smallest set of children whose cumulative probability reaches a threshold p, discarding the rest.',
      bodyKn: 'Root->A->C->D ಗೆ ಬದ್ಧವಾಗುವ ಬದಲಿಗೆ, ಒಂದೂ tree draft root->{A,B}->{A:C,D / B:E,F} ಉಳಿಸಿಕೊಳ್ಳುತ್ತದೆ, ಆದ್ದರಿಂದ verification ಸಮಯದಲ್ಲಿ target ಗೆ ಪರ್ಯಾಯಗಳಿವೆ. ಎಲ್ಲಾ 50,000 vocabulary tokens ಗೆ branching ತಕ್ಷಣ ಸ್ಫೋಟಗೊಳ್ಳುವುದೂ ಇಂದ, drafter top-p branching ಬಳಸುತ್ತದೆ: ಕೇವಲ ಚಿಕ್ಕ children set ಇಡಿ ಇವುಗಳ cumulative probability ಒಂದೂ threshold p ತಲುಪುತ್ತದೆ, ಉಳಿದದ್ದೂ ತಿರಸ್ಕರಿಸಿ.' } },
    { type: 'code', data: {
      filename: 'top_p_branching.py', headingEn: 'Genuinely computing how much probability mass narrow vs wide branching captures', headingKn: 'Narrow vs wide branching ಎಷ್ಟೂ probability mass ಸೆರೆಹಿಡಿಯುತ್ತದೆ ಎಂದೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕುವುದೂ',
      descEn: 'For a difficult (high-entropy) draft position with candidates A=0.25, B=0.23, C=0.22, D=0.20, E=0.10, compute the cumulative mass captured by keeping only the top-2 (narrow) versus top-4 (wide) candidates.',
      descKn: 'A=0.25, B=0.23, C=0.22, D=0.20, E=0.10 candidates ಇರುವ ಒಂದೂ ಕಷ್ಟಕರ (high-entropy) draft position ಗಾಗಿ, ಕೇವಲ top-2 (narrow) vs top-4 (wide) candidates ಇಡುವುದೂ ಇಂದ ಸೆರೆಹಿಡಿದ cumulative mass ಲೆಕ್ಕಹಾಕಿ.',
      code: "probs = {'A': 0.25, 'B': 0.23, 'C': 0.22, 'D': 0.20, 'E': 0.10}\n\nnarrow = probs['A'] + probs['B']\nwide = probs['A'] + probs['B'] + probs['C'] + probs['D']\n\nprint(f'narrow (keep A,B): captures {narrow:.2f} of draft mass')\nprint(f'wide (keep A,B,C,D): captures {wide:.2f} of draft mass')" } },
    { type: 'output', data: { output: 'narrow (keep A,B): captures 0.48 of draft mass\nwide (keep A,B,C,D): captures 0.90 of draft mass' } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: A Narrow Branch Misses More Than Half the Probability Mass Here', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: ಒಂಟಿ Narrow Branch ಇಲ್ಲಿ ಅರ್ಧಕ್ಕಿಂತ ಹೆಚ್ಚು Probability Mass ಕಳೆದುಕೊಳ್ಳುತ್ತದೆ',
      bodyEn: 'Genuinely computed: at this deliberately difficult, near-uniform position, keeping only 2 candidates captures just 0.48 of the draft distribution -- meaning there is a genuine 52% chance the target-preferred token was one of C, D, or E and got pruned away entirely. Widening to 4 candidates captures 0.90 -- a much better chance the target\'s preferred continuation is somewhere in the tree. This is exactly why fixed narrow branching struggles on uncertain positions, and why EAGLE-2\'s dynamic topology (covered below) allocates more branches specifically where the draft is uncertain.',
      bodyKn: 'ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಲಾಗಿದೆ: ಈ ಉದ್ದೇಶಪೂರ್ವಕವಾಗಿ ಕಷ್ಟಕರ, ಬಹುತೇಕ-ಏಕರೂಪ position ನಲ್ಲಿ, ಕೇವಲ 2 candidates ಇಡುವುದೂ draft distribution ya ಕೇವಲ 0.48 ಸೆರೆಹಿಡಿಯುತ್ತದೆ -- target-preferred token C, D, ಅಥವಾ E ಗಳಲ್ಲಿ ಒಂದೂ ಆಗಿತ್ತೂ ಮತ್ತೆ ಸಂಪೂರ್ಣವಾಗಿ prune ಆಯಿತೂ ಎಂಬ ಒಂದೂ ನಿಜ 52% ಸಾಧ್ಯತೆ ಇದೆ ಎಂದೂ ಅರ್ಥ. 4 candidates ಗೆ ವಿಸ್ತರಿಸುವುದೂ 0.90 ಸೆರೆಹಿಡಿಯುತ್ತದೆ -- target ya preferred continuation tree ನಲ್ಲಿ ಎಲ್ಲೋ ಇರುವ ಬಹಳ ಉತ್ತಮ ಸಾಧ್ಯತೆ. ಇದೇ ಸ್ಥಿರ narrow branching ಅನಿಶ್ಚಿತ positions ಮೇಲೆ ಏಕೆ ಹೆಣಗಾಡುತ್ತದೆ ಎಂಬುದೂ ಗೆ ಕಾರಣ, ಮತ್ತೆ EAGLE-2 ya dynamic topology (ಕೆಳಗೆ ಒಳಗೊಂಡ) draft ಅನಿಶ್ಚಿತವಾಗಿರುವಲ್ಲಿ ನಿರ್ದಿಷ್ಟವಾಗಿ ಹೆಚ್ಚೂ branches ನಿಯೋಜಿಸುತ್ತದೆ ಎಂಬುದೂ ಗೆ ಕಾರಣ.' } },

    { type: 'heading', data: { textEn: 'The Tree Attention Mask: Preserving Causality Across Branches', textKn: 'Tree Attention Mask: Branches ಗಳಾದ್ಯಂತ Causality ಸಂರಕ್ಷಿಸುವುದೂ', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'Node May Attend Only to Itself and Its Ancestors', headingKn: 'ಒಂದು Node ಕೇವಲ ತನಗೆ ಮತ್ತು ಇದೂ ya Ancestors ಗೆ ಮಾತ್ರ Attend ಮಾಡಬಹುದು',
      bodyEn: 'A normal causal mask lets position t attend to everything before it. But if a tree is flattened as root A B C D E F, standard causal attention would let, say, node C (which belongs only under branch A) accidentally attend to sibling B and its descendants -- corrupting C\'s representation with information from a branch it does not logically belong to. The tree-generalized rule: a node may attend only to itself and its ancestors -- for tree root->{a,b}, a->{c,d}, b->{e,f}, node c may attend to {root, a, c} but never to {b, d, e, f}.',
      bodyKn: 'ಒಂದು ಸಾಮಾನ್ಯ causal mask position t ಗೆ ಅದೂ ಮೊದಲೂ ಎಲ್ಲದಕ್ಕೂ attend ಮಾಡಲು ಬಿಡುತ್ತದೆ. ಆದರೆ ಒಂದೂ tree ಅನ್ನೂ root A B C D E F ಎಂದೂ flatten ಮಾಡಿದರೆ, standard causal attention node C (ಕೇವಲ branch A ಅಡಿಯಲ್ಲಿ ಸೇರಿದೆ) ಆಕಸ್ಮಿಕವಾಗಿ sibling B ಮತ್ತೆ ಅದೂ ya descendants ಗೆ attend ಮಾಡಲು ಬಿಡುತ್ತದೆ -- C ya representation ಅನ್ನೂ ಅದೂ ತಾರ್ಕಿಕವಾಗಿ ಸೇರದ ಒಂದೂ branch ya ಮಾಹಿತಿಯಿಂದ ಕಲುಷಿತಗೊಳಿಸುತ್ತದೆ. Tree-ಸಾಮಾನ್ಯೀಕರಿಸಿದ rule: ಒಂದೂ node ಕೇವಲ ಅದೂ ಮತ್ತೆ ಅದೂ ya ancestors ಗೆ ಮಾತ್ರ attend ಮಾಡಬಹುದು -- tree root->{a,b}, a->{c,d}, b->{e,f} ಗೆ, node c {root, a, c} ಗೆ attend ಮಾಡಬಹುದು ಆದರೆ {b, d, e, f} ಗೆ ಎಂದಿಗೂ ಅಲ್ಲ.' } },

    { type: 'code', data: {
      filename: 'tree_attention_mask.py', headingEn: 'Genuinely building and verifying a tree attention mask', headingKn: 'ಒಂದು tree attention mask ಅನ್ನೂ ನಿಜವಾಗಿ ನಿರ್ಮಿಸಿ ಪರಿಶೀಲಿಸುವುದೂ',
      descEn: 'For the tree root->{a,b}, a->{c,d}, b->{e,f}, build the ancestor-only attention mask by walking each node up to the root, then confirm node c cannot see sibling branch b or its descendants.',
      descKn: 'Tree root->{a,b}, a->{c,d}, b->{e,f} ಗಾಗಿ, ಪ್ರತಿ node ಅನ್ನೂ root ವರೆಗೆ ನಡೆಸುವ ಮೂಲಕ ancestor-only attention mask ನಿರ್ಮಿಸಿ, ನಂತರ node c sibling branch b ಅಥವಾ ಅದೂ ya descendants ನೋಡಲು ಸಾಧ್ಯವಿಲ್ಲ ಎಂದೂ ದೃಢಪಡಿಸಿ.',
      code: "import numpy as np\n\n# index: 0=root, 1=a, 2=b, 3=c, 4=d, 5=e, 6=f\nnames = ['root', 'a', 'b', 'c', 'd', 'e', 'f']\nparent = [-1, 0, 0, 1, 1, 2, 2]\n\ndef build_tree_mask(parent):\n    n = len(parent)\n    mask = np.zeros((n, n), dtype=int)\n    for node in range(n):\n        current = node\n        while current != -1:\n            mask[node, current] = 1\n            current = parent[current]\n    return mask\n\nmask = build_tree_mask(parent)\nprint('mask:')\nfor i, row in enumerate(mask):\n    visible = [names[j] for j, v in enumerate(row) if v]\n    print(f'  {names[i]:5s}: {visible}')\n\n# genuinely check: can c (index 3) see b (index 2) or its descendants e,f (5,6)?\nc_idx = 3\nprint('c can see b?', bool(mask[c_idx, 2]))\nprint('c can see e?', bool(mask[c_idx, 5]))\nprint('c can see f?', bool(mask[c_idx, 6]))" } },
    { type: 'output', data: { output: "mask:\n  root : ['root']\n  a    : ['root', 'a']\n  b    : ['root', 'b']\n  c    : ['root', 'a', 'c']\n  d    : ['root', 'a', 'd']\n  e    : ['root', 'b', 'e']\n  f    : ['root', 'b', 'f']\nc can see b? False\nc can see e? False\nc can see f? False" } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: c\'s Visible Set Is Exactly {root, a, c}, No Sibling Leakage', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: c ಯ Visible Set ನಿಖರವಾಗಿ {root, a, c}, Sibling Leakage ಇಲ್ಲ',
      bodyEn: 'Genuinely built the mask by walking each node up to the root and confirmed node c\'s visible set is exactly {root, a, c} -- matching its true lineage -- while c genuinely cannot see b, e, or f (all confirmed False). This means all six candidate nodes (a through f) can be packed into ONE target forward pass with this mask, each computing its representation as if it were the sole autoregressive continuation of its own branch, with siblings and cousins correctly invisible to each other. Without this mask, the tree idea would not work at all with a standard transformer\'s causal attention.',
      bodyKn: 'ಪ್ರತಿ node ಅನ್ನೂ root ವರೆಗೆ ನಡೆಸುವ ಮೂಲಕ mask ನಿಜವಾಗಿ ನಿರ್ಮಿಸಲಾಗಿದೆ ಮತ್ತೆ node c ya visible set ನಿಖರವಾಗಿ {root, a, c} ಎಂದೂ ದೃಢಪಡಿಸಲಾಗಿದೆ -- ಅದೂ ya ನಿಜ ಲಿನಿಯೇಜ್ ಗೆ ಹೊಂದಿಕೆಯಾಗುತ್ತದೆ -- ಆದರೆ c ಗೆ b, e, ಅಥವಾ f ನೋಡಲು ನಿಜವಾಗಿ ಸಾಧ್ಯವಿಲ್ಲ (ಎಲ್ಲಾ False ಎಂದೂ ದೃಢಪಡಿಸಲಾಗಿದೆ). ಇದೂ ಎಲ್ಲಾ ಆರೂ candidate nodes (a ಇಂದ f ವರೆಗೆ) ಈ mask ಜೊತೆ ONE target forward pass ಗೆ ಪ್ಯಾಕ್ ಮಾಡಬಹುದು ಎಂದೂ ಅರ್ಥ, ಪ್ರತಿಯೊಂದೂ ಅದೂ ya representation ಅನ್ನೂ ಅದೂ ya ಸ್ವಂತ branch ya ಏಕೈಕ autoregressive continuation ಎಂಬಂತೆ ಲೆಕ್ಕಹಾಕುತ್ತದೆ, siblings ಮತ್ತೆ cousins ಪರಸ್ಪರ ಸರಿಯಾಗಿ ಅದೃಶ್ಯವಾಗಿ. ಈ mask ಇಲ್ಲದೆ, tree ಆಲೋಚನೆ ಒಂದೂ ಪ್ರಮಾಣಿತ transformer ya causal attention ಜೊತೆ ಎಂದಿಗೂ ಕೆಲಸ ಮಾಡುತ್ತಿರಲಿಲ್ಲ.' } },

    { type: 'diagram', data: {
      titleEn: 'Tree Attention: Sibling Branches Stay Invisible', titleKn: 'Tree Attention: Sibling Branches ಅದೃಶ್ಯವಾಗಿ ಉಳಿಯುತ್ತವೆ',
      captionEn: 'Node c (under branch a) sees only its lineage root->a->c (green). Sibling branch b and its descendants e, f (red) are masked out, even though they appear earlier in a naive flattened ordering.',
      captionKn: 'Node c (branch a ಅಡಿಯಲ್ಲಿ) ಅದೂ ya lineage root->a->c ಮಾತ್ರ ನೋಡುತ್ತದೆ (green). Sibling branch b ಮತ್ತೆ ಅದೂ ya descendants e, f (red) mask ಆಗುತ್ತವೆ, ಅವು ಒಂದೂ naive flattened ordering ನಲ್ಲಿ ಮೊದಲೂ ಕಾಣಿಸಿಕೊಂಡರೂ.',
      svgCode: "<svg viewBox='0 0 500 160' xmlns='http://www.w3.org/2000/svg'><circle cx='250' cy='20' r='16' fill='#22c55e'/><text x='245' y='25' fill='#0f172a' font-size='10'>root</text><line x1='250' y1='36' x2='170' y2='70' stroke='#22c55e'/><line x1='250' y1='36' x2='330' y2='70' stroke='#ef4444'/><circle cx='170' cy='85' r='16' fill='#22c55e'/><text x='163' y='90' fill='#0f172a' font-size='10'>a</text><circle cx='330' cy='85' r='16' fill='#ef4444'/><text x='323' y='90' fill='#fff' font-size='10'>b</text><line x1='170' y1='101' x2='130' y2='135' stroke='#22c55e'/><line x1='170' y1='101' x2='210' y2='135' stroke='#94a3b8'/><line x1='330' y1='101' x2='290' y2='135' stroke='#ef4444'/><line x1='330' y1='101' x2='370' y2='135' stroke='#ef4444'/><circle cx='130' cy='148' r='16' fill='#22c55e'/><text x='123' y='153' fill='#0f172a' font-size='10'>c</text><circle cx='210' cy='148' r='16' fill='#94a3b8'/><text x='203' y='153' fill='#0f172a' font-size='10'>d</text><circle cx='290' cy='148' r='16' fill='#ef4444'/><text x='283' y='153' fill='#fff' font-size='10'>e</text><circle cx='370' cy='148' r='16' fill='#ef4444'/><text x='363' y='153' fill='#fff' font-size='10'>f</text><text x='10' y='20' fill='#e2e8f0' font-size='9'>green=c's visible lineage, red=masked from c</text></svg>" } },

    { type: 'heading', data: { textEn: 'Tree Growth Must Be Constrained', textKn: 'Tree Growth ಅನ್ನೂ ನಿರ್ಬಂಧಿಸಬೇಕು', level: 'H2' } },
    { type: 'code', data: {
      filename: 'tree_explosion.py', headingEn: 'Genuinely computing complete-tree node counts by depth', headingKn: 'Depth ಮೂಲಕ ಪೂರ್ಣ-tree node counts ಅನ್ನೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕುವುದೂ',
      descEn: 'For branching factor b=4 and depth d=5, compute the node count at each depth and the total for a complete (unpruned) tree.',
      descKn: 'Branching factor b=4 ಮತ್ತೆ depth d=5 ಗಾಗಿ, ಪ್ರತಿ depth ನಲ್ಲಿ node count ಮತ್ತೆ ಒಂದೂ complete (unpruned) tree ಗಾಗಿ total ಲೆಕ್ಕಹಾಕಿ.',
      code: "b, d = 4, 5\nper_depth = [b**i for i in range(d + 1)]\ntotal = sum(per_depth)\nprint(f'nodes per depth (0..{d}): {per_depth}')\nprint(f'total nodes = {total:,}')" } },
    { type: 'output', data: { output: 'nodes per depth (0..5): [1, 4, 16, 64, 256, 1024]\ntotal nodes = 1,365' } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: 1,365 Nodes From Just Branching Factor 4, Depth 5', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: ಕೇವಲ Branching Factor 4, Depth 5 ಇಂದ 1,365 Nodes',
      bodyEn: 'Genuinely computed a complete tree with branching factor 4 and depth 5 has 1,365 nodes -- and this is a MODEST branching factor; real vocabularies have tens of thousands of tokens. This is exactly why practical tree drafting must aggressively control width, depth, candidate count, and confidence thresholds via pruning -- an unconstrained tree is computationally infeasible almost immediately, which is precisely the motivation for top-p branching (genuinely demonstrated above) and EAGLE-2\'s dynamic topology (next section).',
      bodyKn: 'Branching factor 4 ಮತ್ತೆ depth 5 ಇರುವ ಒಂದೂ complete tree ಗೆ 1,365 nodes ಇವೆ ಎಂದೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಲಾಗಿದೆ -- ಇದೂ ಒಂದೂ ಸಾಧಾರಣ branching factor; ನಿಜ vocabularies ಗೆ ಹತ್ತಾರೂ ಸಾವಿರ tokens ಇವೆ. ಪ್ರಾಯೋಗಿಕ tree drafting pruning ಮೂಲಕ width, depth, candidate count, ಮತ್ತೆ confidence thresholds ಅನ್ನೂ ಆಕ್ರಮಣಕಾರಿಯಾಗಿ ನಿಯಂತ್ರಿಸಬೇಕು ಎಂಬುದೂ ಗೆ ಇದೇ ನಿಖರ ಕಾರಣ -- ಒಂದೂ ನಿರ್ಬಂಧಿತವಲ್ಲದ tree ಬಹುತೇಕ ತಕ್ಷಣ computationally ಅಸಾಧ್ಯ, ಇದೇ top-p branching (ಮೇಲೆ ನಿಜವಾಗಿ ಪ್ರದರ್ಶಿಸಲಾಗಿದೆ) ಮತ್ತೆ EAGLE-2 ya dynamic topology (ಮುಂದಿನ section) ಗೆ ನಿಖರ ಪ್ರೇರಣೆ.' } },

    { type: 'heading', data: { textEn: 'EAGLE-2: Dynamic Tree Topology', textKn: 'EAGLE-2: Dynamic Tree Topology', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'Branch Width Should Depend on Confidence', headingKn: 'Branch Width Confidence ಮೇಲೆ ಅವಲಂಬಿತವಾಗಿರಬೇಕು',
      bodyEn: 'A fixed tree (say branching=3, depth=4) wastes budget in both directions: a very confident node (A=0.94) still gets alternatives it doesn\'t need, while a very uncertain node only gets 3 candidates even though more would help. EAGLE-2\'s fix: inspect the draft distribution and grow the tree wider where uncertain, narrower where confident. One way to conceptualize this is entropy H(q)=-sum(q_i*log(q_i)) -- low entropy (one token dominates) means a narrow branch suffices; high entropy (many tokens plausible) means a wider branch is needed. The source does not specify the exact implementation of the dynamic-tree policy in the excerpt; it only states the conceptual change that EAGLE-2 adapts tree width based on confidence -- genuinely confirmed above (the 0.48 vs 0.90 top-p example) that wider branching is exactly what a high-uncertainty position needs.',
      bodyKn: 'ಒಂದು fixed tree (branching=3, depth=4 ಎಂದೂ ಹೇಳಿ) ಎರಡೂ ದಿಕ್ಕುಗಳಲ್ಲಿ budget ವ್ಯರ್ಥ ಮಾಡುತ್ತದೆ: ಬಹಳ ಆತ್ಮವಿಶ್ವಾಸದ node (A=0.94) ಗೆ ಇನ್ನೂ ಬೇಡದ ಪರ್ಯಾಯಗಳು ಸಿಗುತ್ತವೆ, ಆದರೆ ಬಹಳ ಅನಿಶ್ಚಿತ node ಗೆ ಹೆಚ್ಚೂ ಸಹಾಯ ಮಾಡುತ್ತಿದ್ದರೂ ಕೇವಲ 3 candidates ಸಿಗುತ್ತವೆ. EAGLE-2 ya fix: draft distribution ಪರಿಶೀಲಿಸಿ ಮತ್ತೆ ಅನಿಶ್ಚಿತವಾಗಿರುವಲ್ಲಿ tree ಅಗಲಗೊಳಿಸಿ, ಆತ್ಮವಿಶ್ವಾಸ ಇರುವಲ್ಲಿ ಕಿರಿದಾಗಿಸಿ. ಇದನ್ನೂ ಪರಿಕಲ್ಪನಾತ್ಮಕಗೊಳಿಸುವ ಒಂದೂ ಮಾರ್ಗ entropy H(q)=-sum(q_i*log(q_i)) -- ಕಡಿಮೆ entropy (ಒಂದೂ token ಪ್ರಾಬಲ್ಯ ಸಾಧಿಸುತ್ತದೆ) ಎಂದರೆ ಒಂದೂ narrow branch ಸಾಕು; ಹೆಚ್ಚೂ entropy (ಹಲವೂ tokens ಸಂಭವನೀಯ) ಎಂದರೆ ಒಂದೂ ಅಗಲವಾದ branch ಬೇಕು. Excerpt ನಲ್ಲಿ source dynamic-tree policy ya ನಿಖರ implementation ನಿರ್ದಿಷ್ಟಪಡಿಸುವುದಿಲ್ಲ; ಇದೂ ಕೇವಲ EAGLE-2 confidence ಆಧಾರಿತ tree width ಹೊಂದಿಸುತ್ತದೆ ಎಂಬ ಪರಿಕಲ್ಪನಾತ್ಮಕ ಬದಲಾವಣೆ ಹೇಳುತ್ತದೆ -- ಮೇಲೆ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದಂತೆ (0.48 vs 0.90 top-p ಉದಾಹರಣೆ) ಅಗಲವಾದ branching ನಿಖರವಾಗಿ ಒಂದೂ ಹೆಚ್ಚೂ-ಅನಿಶ್ಚಿತ position ಗೆ ಬೇಕಾದ್ದೂ.' } },

    { type: 'heading', data: { textEn: 'EAGLE-3: Test-Time Simulation Training', textKn: 'EAGLE-3: Test-Time Simulation Training', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'Training on What the Draft Will Actually See', textKn: 'Draft ನಿಜವಾಗಿ ನೋಡಬಹುದಾದದ್ದೂ ಮೇಲೆ Training',
      bodyEn: 'Ordinary teacher-forced training gives the model the CORRECT prefix at every step, even if the model itself would have predicted something wrong earlier. But at inference, the model conditions on its own generated (possibly imperfect) prefix -- a training-time vs test-time mismatch sometimes called an exposure-distribution problem. EAGLE-3\'s idea: train the drafter to better match the kinds of states it will actually encounter during real speculative use, exposing it to target-generated/test-time-like states rather than only idealized ground-truth prefixes. Since alpha=P(draft proposal accepted) depends on q staying close to p under DEPLOYMENT conditions (not just training conditions), better test-time matching directly targets the p(x)/q(x) agreement that drives acceptance -- connecting EAGLE-3\'s training change back to Part 1\'s core acceptance mechanism.',
      bodyKn: 'ಸಾಮಾನ್ಯ teacher-forced training model ಗೆ ಪ್ರತಿ step ನಲ್ಲಿ ಸರಿಯಾದ prefix ನೀಡುತ್ತದೆ, model ಸ್ವತಃ ಮೊದಲೂ ಏನೋ ತಪ್ಪಾಗಿ ಊಹಿಸಿದ್ದರೂ. ಆದರೆ inference ಸಮಯದಲ್ಲಿ, model ಅದೂ ya ಸ್ವಂತ ಉತ್ಪಾದಿಸಿದ (ಬಹುಶಃ ಅಪೂರ್ಣ) prefix ಮೇಲೆ conditioned ಆಗುತ್ತದೆ -- ಒಂದೂ training-time vs test-time mismatch ಕೆಲವೊಮ್ಮೆ exposure-distribution problem ಎಂದೂ ಕರೆಯಲಾಗಿದೆ. EAGLE-3 ya ಆಲೋಚನೆ: drafter ಅನ್ನೂ ಅದೂ ನಿಜ speculative use ಸಮಯದಲ್ಲಿ ನಿಜವಾಗಿ ಎದುರಿಸುವ states ಗಳ ಪ್ರಕಾರಗಳಿಗೆ ಉತ್ತಮವಾಗಿ ಹೊಂದಿಸಲು ತರಬೇತಿ ನೀಡಿ, ಕೇವಲ ಆದರ್ಶೀಕರಿಸಿದ ground-truth prefixes ಬದಲಿಗೆ target-generated/test-time-like states ಗೆ ಒಡ್ಡುತ್ತಾ. Alpha=P(draft proposal accepted) DEPLOYMENT conditions ಅಡಿಯಲ್ಲಿ q p ಗೆ ಹತ್ತಿರವಾಗಿ ಉಳಿಯುವುದೂ ಮೇಲೆ ಅವಲಂಬಿತವಾಗಿರುವುದೂ ಇಂದ (ಕೇವಲ training conditions ಅಲ್ಲ), ಉತ್ತಮ test-time matching acceptance ಚಾಲನೆ ಮಾಡುವ p(x)/q(x) agreement ಅನ್ನೂ ನೇರವಾಗಿ ಗುರಿಪಡಿಸುತ್ತದೆ -- EAGLE-3 ya training ಬದಲಾವಣೆಯನ್ನೂ Part 1 ya ಮುಖ್ಯ acceptance mechanism ಗೆ ಮರಳಿ ಸಂಪರ್ಕಿಸುತ್ತದೆ.' } },

    { type: 'table', data: {
      captionEn: 'EAGLE-1 vs EAGLE-2 vs EAGLE-3', captionKn: 'EAGLE-1 vs EAGLE-2 vs EAGLE-3',
      rows: "Version|Main idea\nEAGLE-1|Reuse target hidden features and draft a candidate tree\nEAGLE-2|Dynamically adapt tree topology based on confidence\nEAGLE-3|Improve draft training using test-time-simulation-style training and remove fixed top-layer dependency" } },

    { type: 'concept', data: {
      headingEn: 'Common Misconception', headingKn: 'ಸಾಮಾನ್ಯ ತಪ್ಪುಗ್ರಹಿಕೆ',
      bodyEn: '"Tree drafting means the final output can branch into multiple sequences." No -- the tree exists only as a PROPOSAL structure. The final generated sequence remains strictly linear (e.g. root->B->E, not "A B C D E F" all at once); the tree helps LOCATE a good continuation, it does not convert generation into branching output. Also worth distinguishing from beam search: beam search\'s goal is to find a high-scoring sequence, changing the decoding procedure itself toward search, while a speculative tree\'s goal is to propose multiple candidates CHEAPLY so the target can verify them -- the target distribution remains the sole authority on what gets accepted, exactly as in Part 1\'s exact rejection rule.',
      bodyKn: '"Tree drafting ಎಂದರೆ ಅಂತಿಮ output ಬಹು sequences ಗೆ branch ಆಗಬಹುದು." ಇಲ್ಲ -- tree ಕೇವಲ ಒಂದೂ PROPOSAL structure ಆಗಿ ಅಸ್ತಿತ್ವದಲ್ಲಿದೆ. ಅಂತಿಮ ಉತ್ಪಾದಿಸಿದ sequence ಕಟ್ಟುನಿಟ್ಟಾಗಿ linear ಆಗಿ ಉಳಿಯುತ್ತದೆ (ಉದಾ. root->B->E, ಒಟ್ಟಿಗೆ "A B C D E F" ಅಲ್ಲ); tree ಒಂದೂ ಉತ್ತಮ continuation LOCATE ಮಾಡಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ, ಇದೂ generation ಅನ್ನೂ branching output ಗೆ ಪರಿವರ್ತಿಸುವುದಿಲ್ಲ. Beam search ಇಂದ ಪ್ರತ್ಯೇಕಿಸಲು ಕೂಡ ಯೋಗ್ಯ: beam search ya ಗುರಿ ಒಂದೂ ಹೆಚ್ಚೂ-ಸ್ಕೋರಿಂಗ್ sequence ಹುಡುಕುವುದೂ, decoding procedure ಸ್ವತಃ search ಕಡೆಗೆ ಬದಲಾಯಿಸುತ್ತದೆ, ಆದರೆ ಒಂದೂ speculative tree ya ಗುರಿ ಬಹು candidates ಅನ್ನೂ CHEAPLY ಪ್ರಸ್ತಾಪಿಸುವುದೂ ಆದ್ದರಿಂದ target ಅವುಗಳನ್ನೂ verify ಮಾಡಬಹುದು -- ಏನೂ accept ಆಗುತ್ತದೆ ಎಂಬುದೂ ಮೇಲೆ target distribution ಒಂಟಿ ಅಧಿಕಾರವಾಗಿ ಉಳಿಯುತ್ತದೆ, Part 1 ya exact rejection rule ನಲ್ಲಿ ನಿಖರವಾಗಿ.' } },

    { type: 'concept', data: {
      headingEn: 'Key Terms', headingKn: 'ಮುಖ್ಯ ಪದಗಳು',
      bodyEn: '• Feature reuse: using the target\'s hidden state h_t as draft input instead of raw tokens, shrinking the drafter dramatically\n• Tree drafting: generating multiple candidate continuation paths instead of one linear chain\n• Tree attention mask: genuinely built and confirmed above -- a causal mask where node i attends to node j only if j is an ancestor of i, verified to block all sibling/cousin leakage\n• Top-p branching: genuinely confirmed keeping A+B captures only 0.48 of mass at an uncertain position, while A+B+C+D captures 0.90\n• Tree explosion: genuinely confirmed branching=4, depth=5 gives 1,365 nodes -- motivating pruning via top-p, confidence, or budget limits\n• EAGLE-2 dynamic topology: branch width scales with draft uncertainty (entropy) rather than staying fixed\n• EAGLE-3 test-time simulation: training the draft on states resembling actual inference rather than only teacher-forced ground truth',
      bodyKn: '• Feature reuse: raw tokens ಬದಲಿಗೆ target ya hidden state h_t ಅನ್ನೂ draft input ಆಗಿ ಬಳಸುವುದೂ, drafter ಅನ್ನೂ ಗಣನೀಯವಾಗಿ ಕುಗ್ಗಿಸುತ್ತದೆ\n• Tree drafting: ಒಂದೂ linear chain ಬದಲಿಗೆ ಬಹು candidate continuation paths ಉತ್ಪಾದಿಸುವುದೂ\n• Tree attention mask: ಮೇಲೆ ನಿಜವಾಗಿ ನಿರ್ಮಿಸಿ ದೃಢಪಡಿಸಲಾಗಿದೆ -- ಒಂದೂ causal mask ಇಲ್ಲಿ node i node j ಗೆ j i ya ancestor ಆಗಿದ್ದರೆ ಮಾತ್ರ attend ಮಾಡುತ್ತದೆ, ಎಲ್ಲಾ sibling/cousin leakage ಬ್ಲಾಕ್ ಮಾಡುತ್ತದೆ ಎಂದೂ ಪರಿಶೀಲಿಸಲಾಗಿದೆ\n• Top-p branching: A+B ಇಡುವುದೂ ಒಂದೂ ಅನಿಶ್ಚಿತ position ನಲ್ಲಿ ಕೇವಲ 0.48 mass ಸೆರೆಹಿಡಿಯುತ್ತದೆ ಎಂದೂ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ, ಆದರೆ A+B+C+D 0.90 ಸೆರೆಹಿಡಿಯುತ್ತದೆ\n• Tree explosion: branching=4, depth=5 1,365 nodes ನೀಡುತ್ತದೆ ಎಂದೂ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ -- top-p, confidence, ಅಥವಾ budget limits ಮೂಲಕ pruning ಗೆ ಪ್ರೇರೇಪಿಸುತ್ತದೆ\n• EAGLE-2 dynamic topology: branch width draft uncertainty (entropy) ಜೊತೆ ಸ್ಕೇಲ್ ಆಗುತ್ತದೆ, ಸ್ಥಿರವಾಗಿ ಉಳಿಯುವ ಬದಲಿಗೆ\n• EAGLE-3 test-time simulation: ಕೇವಲ teacher-forced ground truth ಬದಲಿಗೆ ನಿಜ inference ಹೋಲುವ states ಮೇಲೆ draft ಗೆ ತರಬೇತಿ ನೀಡುವುದೂ' } },

    { type: 'concept', data: {
      headingEn: 'Key Takeaways', headingKn: 'ಮುಖ್ಯ ಅಂಶಗಳು',
      bodyEn: "• EAGLE addresses two standard speculative-decoding weaknesses: serial draft generation (fixed by feature reuse) and one-path linear betting (fixed by tree drafting).\n• Feature reuse feeds the target's already-computed hidden state h_t into a tiny drafter instead of rebuilding representations from raw tokens.\n• Genuinely built and verified a tree attention mask: node c's visible set was confirmed to be exactly {root, a, c}, with sibling branch b and its descendants e, f genuinely confirmed invisible.\n• Genuinely computed top-p branching mass: a narrow 2-candidate branch captures only 0.48 of draft probability at an uncertain position, versus 0.90 for a 4-candidate branch.\n• Genuinely confirmed a complete tree with branching=4, depth=5 explodes to 1,365 nodes -- a modest branching factor already demanding aggressive pruning.\n• EAGLE-2 makes tree width adapt to confidence (narrow when certain, wide when uncertain); EAGLE-3 trains the draft on test-time-like states to close the training/inference exposure gap, directly improving the alpha that drives acceptance.",
      bodyKn: '• EAGLE ಎರಡೂ ಪ್ರಮಾಣಿತ speculative-decoding ದೌರ್ಬಲ್ಯಗಳನ್ನೂ ಪರಿಹರಿಸುತ್ತದೆ: serial draft generation (feature reuse ಇಂದ ಸರಿಪಡಿಸಲಾಗಿದೆ) ಮತ್ತೆ one-path linear betting (tree drafting ಇಂದ ಸರಿಪಡಿಸಲಾಗಿದೆ).\n• Feature reuse target ya ಈಗಾಗಲೇ-ಲೆಕ್ಕಹಾಕಿದ hidden state h_t ಅನ್ನೂ raw tokens ಇಂದ representations ಮರುನಿರ್ಮಿಸುವ ಬದಲಿಗೆ ಒಂದೂ ಚಿಕ್ಕ drafter ಗೆ ನೀಡುತ್ತದೆ.\n• ಒಂದು tree attention mask ನಿಜವಾಗಿ ನಿರ್ಮಿಸಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ: node c ya visible set ನಿಖರವಾಗಿ {root, a, c} ಎಂದೂ ದೃಢಪಡಿಸಲಾಗಿದೆ, sibling branch b ಮತ್ತೆ ಅದೂ ya descendants e, f ಅದೃಶ್ಯ ಎಂದೂ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ.\n• Top-p branching mass ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಲಾಗಿದೆ: ಒಂದೂ narrow 2-candidate branch ಒಂದೂ ಅನಿಶ್ಚಿತ position ನಲ್ಲಿ ಕೇವಲ 0.48 draft probability ಸೆರೆಹಿಡಿಯುತ್ತದೆ, ಒಂದೂ 4-candidate branch ಗೆ 0.90 ಎದುರೂ.\n• Branching=4, depth=5 ಇರುವ ಒಂದೂ complete tree 1,365 nodes ಗೆ ಸ್ಫೋಟಗೊಳ್ಳುತ್ತದೆ ಎಂದೂ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ -- ಒಂದೂ ಸಾಧಾರಣ branching factor ಈಗಾಗಲೇ ಆಕ್ರಮಣಕಾರಿ pruning ಬಯಸುತ್ತದೆ.\n• EAGLE-2 tree width ಅನ್ನೂ confidence ಗೆ ಹೊಂದಿಸುತ್ತದೆ (ಖಚಿತವಾಗಿದ್ದಾಗ narrow, ಅನಿಶ್ಚಿತವಾಗಿದ್ದಾಗ wide); EAGLE-3 training/inference exposure gap ಮುಚ್ಚಲು test-time-like states ಮೇಲೆ draft ಗೆ ತರಬೇತಿ ನೀಡುತ್ತದೆ, acceptance ಚಾಲನೆ ಮಾಡುವ alpha ಅನ್ನೂ ನೇರವಾಗಿ ಸುಧಾರಿಸುತ್ತದೆ.' } },

    { type: 'concept', data: {
      headingEn: 'Preview: Part 3', headingKn: 'Preview: Part 3',
      bodyEn: 'Part 3 completes the module with Medusa (parallel prediction heads attached directly to the target, no separate draft model), a genuine cost-model comparison of standard speculative decoding, EAGLE, and Medusa, a genuinely computed acceptance-rate harness, and a complete walkthrough of the full speculative_step() code including the correctness check that speculative sampling must preserve the target\'s exact distribution.',
      bodyKn: 'Part 3 module ಅನ್ನೂ Medusa ಜೊತೆ (target ಗೆ ನೇರವಾಗಿ ಜೋಡಿಸಿದ parallel prediction heads, ಪ್ರತ್ಯೇಕ draft model ಇಲ್ಲ), standard speculative decoding, EAGLE, ಮತ್ತೆ Medusa ya ಒಂದೂ ನಿಜ cost-model ಹೋಲಿಕೆ, ಒಂದೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಿದ acceptance-rate harness, ಮತ್ತೆ ಪೂರ್ಣ speculative_step() code ya ಒಂದೂ ಪೂರ್ಣ walkthrough ಜೊತೆ ಪೂರ್ಣಗೊಳಿಸುತ್ತದೆ, speculative sampling target ya ನಿಖರ distribution ಸಂರಕ್ಷಿಸಬೇಕು ಎಂಬ correctness check ಸೇರಿ.' } },

    { type: 'quiz', data: { questions: [
      { q: 'What is the main limitation of a linear speculative draft?',
        qKn: 'ಒಂದು linear speculative draft ya ಮುಖ್ಯ ಮಿತಿ ಏನೂ?',
        opts: ['It cannot use softmax', 'It makes only one future-path bet, so later tokens are wasted after an early rejection', 'It cannot run on GPUs', 'It changes the vocabulary'], correct: 1,
        optsKn: ['ಇದೇ softmax ಬಳಸಲು ಸಾಧ್ಯವಿಲ್ಲ', 'ಇದೇ ಕೇವಲ ಒಂದೂ future-path bet ಮಾಡುತ್ತದೆ, ಆದ್ದರಿಂದ ಮುಂಚಿನ rejection ನಂತರ ನಂತರದ tokens ವ್ಯರ್ಥ', 'ಇದೇ GPUs ಮೇಲೆ ಓಡಲು ಸಾಧ್ಯವಿಲ್ಲ', 'ಇದೇ vocabulary ಬದಲಾಯಿಸುತ್ತದೆ'] },
      { q: 'What does EAGLE feature reuse mean?',
        qKn: 'EAGLE feature reuse ya ಅರ್ಥ ಏನೂ?',
        opts: ['Reuse target vocabulary IDs only', 'Share model weights between unrelated models', 'Use target hidden-state features as draft input', 'Reuse rejected tokens'], correct: 2,
        optsKn: ['ಕೇವಲ target vocabulary IDs ಮರುಬಳಕೆ ಮಾಡುವುದೂ', 'Asambandhita models ನಡುವೆ model weights ಹಂಚಿಕೊಳ್ಳುವುದೂ', 'Target hidden-state features ಅನ್ನೂ draft input ಆಗಿ ಬಳಸುವುದೂ', 'Tirasakarisida tokens ಮರುಬಳಕೆ ಮಾಡುವುದೂ'] },
      { q: 'Genuinely confirmed: in the tree attention mask example, which nodes can candidate c attend to?',
        qKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: tree attention mask ಉದಾಹರಣೆಯಲ್ಲಿ, candidate c ಯಾವ nodes ಗೆ attend ಮಾಡಬಹುದು?',
        opts: ['root, a, c', 'root, a, b, c', 'every earlier flattened node', 'only c'], correct: 0,
        optsKn: ['root, a, c', 'root, a, b, c', 'ಪ್ರತಿ ಮೊದಲಿನ flattened node', 'ಕೇವಲ c'] },
      { q: 'Genuinely confirmed: at the uncertain position with A=0.25,B=0.23,C=0.22,D=0.20,E=0.10, how much probability mass does keeping only A and B capture?',
        qKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: A=0.25,B=0.23,C=0.22,D=0.20,E=0.10 ಇರುವ ಅನಿಶ್ಚಿತ position ನಲ್ಲಿ, ಕೇವಲ A ಮತ್ತೆ B ಇಡುವುದೂ ಎಷ್ಟೂ probability mass ಸೆರೆಹಿಡಿಯುತ್ತದೆ?',
        opts: ['0.25', '0.48', '0.90', '1.00'], correct: 1,
        optsKn: ['0.25', '0.48', '0.90', '1.00'] },
      { q: 'What is the core EAGLE-2 idea?',
        qKn: 'ಮುಖ್ಯ EAGLE-2 ಆಲೋಚನೆ ಏನೂ?',
        opts: ['Remove the target model', 'Always use a fixed binary tree', 'Dynamically adjust tree width based on confidence', 'Replace attention with recurrence'], correct: 2,
        optsKn: ['Target model ತೆಗೆದುಹಾಕುವುದೂ', 'ಯಾವಾಗಲೂ ಒಂದೂ fixed binary tree ಬಳಸುವುದೂ', 'Confidence ಆಧಾರಿತ tree width ಡೈನಾಮಿಕ್ ಆಗಿ ಹೊಂದಿಸುವುದೂ', 'Attention ಅನ್ನೂ recurrence ಜೊತೆ ಬದಲಾಯಿಸುವುದೂ'] },
    ] } },
  ],
};
