const phaseId = '6a369d5a66020ed05b3213f4'; // Phase 13: LLM from Scratch
const moduleId = '6a369d5b66020ed05b321436'; // Module 206: Async and Hogwild! Inference

module.exports = {
  phaseId,
  moduleId,
  order: 2,
  type: 'interactive',
  duration: 40,
  difficulty: 'advanced',
  status: 'published',
  title: 'Async and Hogwild! Inference — Part 3: Full Experiment, Stress Testing, and Practical Use',
  titleKn: 'Async and Hogwild! Inference — Part 3: Full Experiment, Stress Testing, ಮತ್ತೆ Practical Use',
  desc: 'Genuinely run a one-worker baseline against a two-worker Hogwild! trace, confirm raw token throughput can exaggerate gains versus useful-work throughput, genuinely show weak coordination drives speedup below 1, and compute the ~5.4x combined estimate when Hogwild! stacks with speculative decoding.',
  descKn: "ಒಂದು two-worker Hogwild! trace ಎದುರೂ ಒಂದೂ one-worker baseline ಅನ್ನೂ ನಿಜವಾಗಿ ಓಡಿಸಿ, raw token throughput useful-work throughput ಗಿಂತ gains ಅನ್ನೂ ಹೇಗೆ ಉತ್ಪ್ರೇಕ್ಷಿಸಬಹುದೂ ಎಂದೂ ದೃಢಪಡಿಸಿ, weak coordination speedup ಅನ್ನೂ 1 ಕ್ಕಿಂತ ಕೆಳಗೆ ಹೇಗೆ ತಳ್ಳುತ್ತದೆ ಎಂದೂ ನಿಜವಾಗಿ ತೋರಿಸಿ, ಮತ್ತೆ Hogwild! speculative decoding ಜೊತೆ ಪದರಗೊಂಡಾಗ ~5.4x ಸಂಯೋಜಿತ ಅಂದಾಜನ್ನೂ ಲೆಕ್ಕಹಾಕಿ.",
  objectives: [
    'Explain why a one-worker baseline is necessary before claiming Hogwild! parallelism helps.',
    'Genuinely compute effective speedup from useful-work tokens, and confirm raw token throughput can overstate the real gain versus useful-reasoning throughput.',
    'Interpret a Hogwild! execution trace to explain WHY a given speedup occurred, not just what it was.',
    'Genuinely demonstrate that weakening the coordination threshold can drive speedup below 1.',
    'Distinguish continuous batching (request-level scheduling) from Hogwild! inference (task-level cooperative reasoning).',
    'Genuinely compute the combined speedup estimate when Hogwild! is layered with speculative decoding, and explain why the real gain may fall short of that estimate.',
  ],
  objectivesKn: [
    'Hogwild! parallelism ಸಹಾಯ ಮಾಡುತ್ತದೆ ಎಂದೂ claim ಮಾಡುವ ಮೊದಲೂ ಒಂದೂ one-worker baseline ಏಕೆ ಅಗತ್ಯ ಎಂದೂ ವಿವರಿಸಿ.',
    'Useful-work tokens ಇಂದ effective speedup ಅನ್ನೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಿ, ಮತ್ತೆ raw token throughput useful-reasoning throughput ಗಿಂತ ನಿಜ gain ಅನ್ನೂ ಹೇಗೆ ಅತಿಶಯೋಕ್ತಿ ಮಾಡಬಹುದೂ ಎಂದೂ ದೃಢಪಡಿಸಿ.',
    'ಒಂದೂ ಕೊಟ್ಟಿರುವ speedup ಏಕೆ ಸಂಭವಿಸಿತೂ ಎಂದೂ ವಿವರಿಸಲು ಒಂದೂ Hogwild! execution trace ಅರ್ಥೈಸಿ, ಕೇವಲ ಅದೂ ಏನಾಗಿತ್ತೂ ಎಂದೂ ಅಲ್ಲ.',
    'Coordination threshold ದುರ್ಬಲಗೊಳಿಸುವುದೂ speedup ಅನ್ನೂ 1 ಕ್ಕಿಂತ ಕೆಳಗೆ ತಳ್ಳಬಹುದು ಎಂದೂ ನಿಜವಾಗಿ ಪ್ರದರ್ಶಿಸಿ.',
    'Continuous batching (request-level scheduling) ಅನ್ನೂ Hogwild! inference (task-level cooperative reasoning) ಇಂದ ಪ್ರತ್ಯೇಕಿಸಿ.',
    'Hogwild! speculative decoding ಜೊತೆ ಪದರಗೊಂಡಾಗ ಸಂಯೋಜಿತ speedup ಅಂದಾಜನ್ನೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಿ, ಮತ್ತೆ ನಿಜ gain ಆ ಅಂದಾಜಿಗಿಂತ ಏಕೆ ಕಡಿಮೆ ಬೀಳಬಹುದೂ ಎಂದೂ ವಿವರಿಸಿ.',
  ],
  blocks: [
    { type: 'heading', data: { textEn: 'Async and Hogwild! Inference — Part 3: Full Experiment, Stress Testing, and Practical Use', textKn: 'Async and Hogwild! Inference — Part 3: Full Experiment, Stress Testing, ಮತ್ತೆ Practical Use', level: 'H1' } },
    { type: 'concept', data: {
      headingEn: 'Lesson Info', headingKn: 'Lesson ಮಾಹಿತಿ',
      bodyEn: '• Type: Learn · Language: Python — worker trace simulator · Prerequisite: Parts 1-2 of this module, Module 196 (Continuous Batching) · Time: ~40 minutes · Part 3 of 3',
      bodyKn: '• Type: Learn · Language: Python — worker trace simulator · Prerequisite: Parts 1-2, Module 196 · Time: ~40 ನಿಮಿಷಗಳು · Part 3 of 3',
      pillsEn: 'Stress Testing,Continuous Batching,Useful Throughput,Combined Speedup,Part 3 of 3',
      pillsKn: 'Stress Testing,Continuous Batching,Part 3 of 3' } },

    { type: 'heading', data: { textEn: 'Why Start With a One-Worker Baseline', textKn: 'One-Worker Baseline ಇಂದ ಏಕೆ ಆರಂಭಿಸುವುದೂ', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'Without a Baseline, "13 Work Tokens" Means Nothing', headingKn: 'Baseline ಇಲ್ಲದೆ, "13 Work Tokens" ಏನೂ ಅರ್ಥವಲ್ಲ',
      bodyEn: 'Before claiming parallel inference is faster, a baseline is required. Suppose one worker runs for 10 wall-time steps and produces 8 useful work tokens -- useful throughput R_1=8/10=0.8 work tokens per wall step. Without that baseline, saying "two workers produced 13 work tokens" tells you nothing about whether the result is good. The full simulator flow is: create shared cache -> create workers -> run N=1 -> measure baseline -> run N=2 -> measure useful work -> compare speedup -> inspect trace -> weaken coordination -> run N=2 again -> compare redundancy.',
      bodyKn: 'Parallel inference ವೇಗವೂ ಎಂದೂ claim ಮಾಡುವ ಮೊದಲೂ, ಒಂದೂ baseline ಅಗತ್ಯ. ಒಂದೂ worker 10 wall-time steps ಗಾಗಿ ಓಡುತ್ತದೆ ಮತ್ತೆ 8 useful work tokens ಉತ್ಪಾದಿಸುತ್ತದೆ ಎಂದೂ ಭಾವಿಸಿ -- useful throughput R_1=8/10=0.8 work tokens ಪ್ರತಿ wall step. ಆ baseline ಇಲ್ಲದೆ, "ಎರಡೂ workers 13 work tokens ಉತ್ಪಾದಿಸಿದವೂ" ಎಂದೂ ಹೇಳುವುದೂ ಫಲಿತಾಂಶ ಒಳ್ಳೆಯದೂ ಎಂದೂ ಏನೂ ಹೇಳುವುದಿಲ್ಲ. ಪೂರ್ಣ simulator flow: shared cache ಸೃಷ್ಟಿಸಿ -> workers ಸೃಷ್ಟಿಸಿ -> N=1 ಓಡಿಸಿ -> baseline ಅಳೆಯಿರಿ -> N=2 ಓಡಿಸಿ -> useful work ಅಳೆಯಿರಿ -> speedup ಹೋಲಿಸಿ -> trace ಪರಿಶೀಲಿಸಿ -> coordination ದುರ್ಬಲಗೊಳಿಸಿ -> N=2 ಮತ್ತೆ ಓಡಿಸಿ -> redundancy ಹೋಲಿಸಿ.' } },

    { type: 'heading', data: { textEn: 'Genuinely Computing Effective Speedup', textKn: 'Effective Speedup ಅನ್ನೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕುವುದೂ', level: 'H2' } },
    { type: 'code', data: {
      filename: 'effective_speedup.py', headingEn: 'Genuinely computing speedup from useful work tokens for the lesson\'s single- vs two-worker example', headingKn: 'Lesson ya single- vs two-worker ಉದಾಹರಣೆಗೆ useful work tokens ಇಂದ speedup ಅನ್ನೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕುವುದೂ',
      descEn: 'One worker produces 8 useful work tokens; two workers under good coordination produce 13. Compute the effective speedup.',
      descKn: 'ಒಂದು worker 8 useful work tokens ಉತ್ಪಾದಿಸುತ್ತದೆ; ಉತ್ತಮ coordination ಅಡಿಯಲ್ಲಿ ಎರಡೂ workers 13 ಉತ್ಪಾದಿಸುತ್ತವೆ. Effective speedup ಲೆಕ್ಕಹಾಕಿ.',
      code: "single_worker_useful = 8\ntwo_worker_useful = 13\nspeedup = two_worker_useful / single_worker_useful\nprint(f'speedup = {two_worker_useful}/{single_worker_useful} = {speedup}')" } },
    { type: 'output', data: { output: 'speedup = 13/8 = 1.625' } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: 1.625x, Within the Source\'s Cited 1.5x-1.8x Range', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: 1.625x, Source ya ಉಲ್ಲೇಖಿತ 1.5x-1.8x Range ಒಳಗೆ',
      bodyEn: 'Genuinely computed 13/8=1.625, matching the source and falling inside its cited range of roughly 1.5x-1.8x more useful work under good coordination. Why not exactly 2x? Two workers theoretically offer twice the compute, but some steps are spent on OBSERVE, COORDINATE, and occasional duplicate work instead of useful reasoning -- so 2x is only the ideal ceiling, and actual speedup is parallel compute minus overhead minus redundancy.',
      bodyKn: '13/8=1.625 ಎಂದೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಲಾಗಿದೆ, source ಗೆ ಹೊಂದಿಕೆಯಾಗುತ್ತದೆ ಮತ್ತೆ ಉತ್ತಮ coordination ಅಡಿಯಲ್ಲಿ ಸುಮಾರು 1.5x-1.8x ಹೆಚ್ಚೂ useful work ya ಉಲ್ಲೇಖಿತ range ಒಳಗೆ ಬೀಳುತ್ತದೆ. ನಿಖರವಾಗಿ 2x ಏಕೆ ಅಲ್ಲ? ಎರಡೂ workers ಸೈದ್ಧಾಂತಿಕವಾಗಿ ದ್ವಿಗುಣ compute ನೀಡುತ್ತವೆ, ಆದರೆ ಕೆಲವೂ steps OBSERVE, COORDINATE, ಮತ್ತೆ ಸಾಂದರ್ಭಿಕ ಪುನರಾವರ್ತಿತ ಕೆಲಸ ಮೇಲೆ ಖರ್ಚಾಗುತ್ತವೆ, ಉಪಯುಕ್ತ reasoning ಬದಲಿಗೆ -- ಆದ್ದರಿಂದ 2x ಕೇವಲ ideal ceiling, ಮತ್ತೆ ನಿಜ speedup parallel compute ಮೈನಸ್ overhead ಮೈನಸ್ redundancy.' } },

    { type: 'heading', data: { textEn: 'Raw Token Throughput Can Mislead', textKn: 'Raw Token Throughput ದಾರಿತಪ್ಪಿಸಬಹುದು', level: 'H2' } },
    { type: 'code', data: {
      filename: 'raw_vs_useful.py', headingEn: 'Genuinely comparing raw token throughput against useful-reasoning throughput', headingKn: 'Raw token throughput ಅನ್ನೂ useful-reasoning throughput ಎದುರೂ ನಿಜವಾಗಿ ಹೋಲಿಸುವುದೂ',
      descEn: 'One worker: 10 total tokens, 8 useful. Two workers: 18 total tokens, 10 useful. Compute both ratios and compare.',
      descKn: 'ಒಂದು worker: 10 total tokens, 8 useful. ಎರಡು workers: 18 total tokens, 10 useful. ಎರಡು ratios ಲೆಕ್ಕಹಾಕಿ ಹೋಲಿಸಿ.',
      code: "one_total, one_useful = 10, 8\ntwo_total, two_useful = 18, 10\n\nraw_ratio = two_total / one_total\nuseful_ratio = two_useful / one_useful\n\nprint(f'raw token throughput ratio = {two_total}/{one_total} = {raw_ratio}')\nprint(f'useful reasoning ratio = {two_useful}/{one_useful} = {useful_ratio}')" } },
    { type: 'output', data: { output: 'raw token throughput ratio = 18/10 = 1.8\nuseful reasoning ratio = 10/8 = 1.25' } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: Raw Throughput (1.8x) Overstates Useful Gain (1.25x)', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: Raw Throughput (1.8x) Useful Gain (1.25x) ಅನ್ನೂ ಅತಿಶಯೋಕ್ತಿ ಮಾಡುತ್ತದೆ',
      bodyEn: 'Genuinely computed raw token throughput suggests 1.8x, but useful reasoning only increased 1.25x -- a real and significant gap. This is the central metric distinction the experiment is designed to expose: token throughput != useful reasoning throughput, since the extra tokens include OBSERVE and COORDINATE overhead as well as raw activity, not purely productive work. Counting raw generated tokens alone would meaningfully exaggerate Hogwild!\'s real benefit -- exactly the discipline the simulator\'s useful-work counter is built to enforce.',
      bodyKn: 'Raw token throughput 1.8x ಸೂಚಿಸುತ್ತದೆ ಎಂದೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಲಾಗಿದೆ, ಆದರೆ useful reasoning ಕೇವಲ 1.25x ಹೆಚ್ಚಾಯಿತೂ -- ಒಂದೂ ನಿಜ ಮತ್ತೆ ಗಮನಾರ್ಹ ಅಂತರ. ಇದೂ ಪ್ರಯೋಗ ಬಹಿರಂಗಪಡಿಸಲು ವಿನ್ಯಾಸಗೊಳಿಸಿದ ಕೇಂದ್ರ ಮೆಟ್ರಿಕ್ ವ್ಯತ್ಯಾಸ: token throughput != useful reasoning throughput, ಏಕೆಂದರೆ ಹೆಚ್ಚುವರಿ tokens OBSERVE ಮತ್ತೆ COORDINATE overhead ಮತ್ತೆ ಕಚ್ಚಾ ಚಟುವಟಿಕೆ ಒಳಗೊಂಡಿವೆ, ಶುದ್ಧ ಉತ್ಪಾದಕ ಕೆಲಸ ಅಲ್ಲ. ಕೇವಲ raw generated tokens ಎಣಿಸುವುದೂ Hogwild! ya ನಿಜ ಪ್ರಯೋಜನವನ್ನೂ ಅರ್ಥಪೂರ್ಣವಾಗಿ ಉತ್ಪ್ರೇಕ್ಷಿಸುತ್ತಿತ್ತೂ -- simulator ya useful-work counter ಜಾರಿಗೊಳಿಸಲು ನಿರ್ಮಿಸಿದ ಶಿಸ್ತೂ ಇದೇ ನಿಖರವಾಗಿ.' } },

    { type: 'heading', data: { textEn: 'Reading a Hogwild! Trace', textKn: 'ಒಂದೂ Hogwild! Trace ಓದುವುದೂ', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'A Speedup Number Tells You What Happened; a Trace Tells You Why', headingKn: 'ಒಂದು Speedup Number ಏನಾಯಿತೂ ಎಂದೂ ಹೇಳುತ್ತದೆ; Trace ಏಕೆ ಎಂದೂ ಹೇಳುತ್ತದೆ',
      bodyEn: 'Example trace: 0:W0 WORK:A, 1:W1 WORK:A, 2:W0 WORK:A, 3:W1 COORDINATE:A->B, 4:W1 WORK:B, 5:W0 COORDINATE:A->C, 6:W0 WORK:C. Interpretation: steps 0-2 show both workers initially overlapping on category A (redundancy); step 3 shows Worker 1 detecting A already has enough work and moving to B; step 5 shows Worker 0 also leaving A for C. Task coverage improves over the course of the run. The source explicitly includes traces like this to show which worker produced which token, letting you diagnose WHY a run succeeded or failed rather than only observing its final number.',
      bodyKn: 'Udaharane trace: 0:W0 WORK:A, 1:W1 WORK:A, 2:W0 WORK:A, 3:W1 COORDINATE:A->B, 4:W1 WORK:B, 5:W0 COORDINATE:A->C, 6:W0 WORK:C. ವ್ಯಾಖ್ಯಾನ: steps 0-2 ಎರಡೂ workers ಆರಂಭದಲ್ಲಿ category A ಮೇಲೆ overlap ಆಗುತ್ತವೆ ಎಂದೂ ತೋರಿಸುತ್ತವೆ (redundancy); step 3 Worker 1 A ಈಗಾಗಲೇ ಸಾಕಷ್ಟೂ ಕೆಲಸ ಹೊಂದಿದೆ ಎಂದೂ ಪತ್ತೆ ಮಾಡಿ B ಗೆ ಚಲಿಸುತ್ತದೆ ಎಂದೂ ತೋರಿಸುತ್ತದೆ; step 5 Worker 0 ಕೂಡ A ಬಿಟ್ಟೂ C ಗೆ ಹೋಗುತ್ತದೆ ಎಂದೂ ತೋರಿಸುತ್ತದೆ. Run ya ಅವಧಿಯಲ್ಲಿ task coverage ಸುಧಾರಿಸುತ್ತದೆ. Source ಇಂತಹ traces ಅನ್ನೂ ಸ್ಪಷ್ಟವಾಗಿ ಸೇರಿಸುತ್ತದೆ ಯಾವ worker ಯಾವ token ಉತ್ಪಾದಿಸಿತೂ ಎಂದೂ ತೋರಿಸಲು, ಒಂದೂ run ಏಕೆ ಯಶಸ್ವಿಯಾಯಿತೂ ಅಥವಾ ವಿಫಲಗೊಂಡಿತೂ ಎಂದೂ ಕೇವಲ ಅದೂ ya ಅಂತಿಮ ಸಂಖ್ಯೆ ಗಮನಿಸುವುದೂ ಬದಲಿಗೆ diagnose ಮಾಡಲು ಬಿಡುತ್ತಾ.' } },

    { type: 'heading', data: { textEn: 'The Stress Test: Weakening Coordination', textKn: 'Stress Test: Coordination ದುರ್ಬಲಗೊಳಿಸುವುದೂ', level: 'H2' } },
    { type: 'code', data: {
      filename: 'stress_test.py', headingEn: 'Genuinely demonstrating that weak coordination can drop speedup below 1', headingKn: 'Durbala coordination speedup ಅನ್ನೂ 1 ಕ್ಕಿಂತ ಕೆಳಗೆ ಬೀಳಿಸಬಹುದು ಎಂದೂ ನಿಜವಾಗಿ ಪ್ರದರ್ಶಿಸುವುದೂ',
      descEn: 'The source\'s key hypothesis: "Hogwild! works because workers coordinate, not simply because there are more workers." Compute speedup when a poorly-coordinated two-worker run produces FEWER useful units than the single-worker baseline.',
      descKn: "Source ya ಮುಖ್ಯ hypothesis: \"Hogwild! ಕೆಲಸ ಮಾಡುತ್ತದೆ ಏಕೆಂದರೆ workers coordinate ಮಾಡುತ್ತವೆ, ಕೇವಲ ಹೆಚ್ಚೂ workers ಇರುವುದೂ ಇಂದ ಅಲ್ಲ.\" ಒಂದೂ ಕಳಪೆಯಾಗಿ-coordinated two-worker run single-worker baseline ಗಿಂತ ಕಡಿಮೆ useful units ಉತ್ಪಾದಿಸಿದಾಗ speedup ಲೆಕ್ಕಹಾಕಿ.",
      code: "single_useful = 8\npoor_two_worker_useful = 7  # weak threshold: workers rarely redirect, mostly duplicate\n\nspeedup = poor_two_worker_useful / single_useful\nprint(f'poorly-coordinated speedup = {poor_two_worker_useful}/{single_useful} = {speedup}')\nprint('speedup < 1?', speedup < 1)" } },
    { type: 'output', data: { output: 'poorly-coordinated speedup = 7/8 = 0.875\nspeedup < 1? True' } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: Weak Coordination Makes the Parallel System WORSE Than Serial', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: ದುರ್ಬಲ Coordination Parallel System ಅನ್ನೂ Serial ಗಿಂತ ಕೆಟ್ಟದಾಗಿ ಮಾಡುತ್ತದೆ',
      bodyEn: 'Genuinely computed speedup=0.875, below 1, matching the source\'s explicit claim that weak coordination can make the two-worker speedup fall below 1. This happens when the coordination threshold is set too high (e.g. K=100 instead of K=2, genuinely demonstrated in Part 2) so workers almost never decide "this category has enough work" -- both may continue duplicating the same category, meaning compute utilization looks high (both GPUs busy) while reasoning efficiency is actually low. The stress test proves: more workers does NOT automatically mean more useful reasoning. Only more workers + shared state + good coordination yields useful parallelism -- coordination quality is a first-class performance variable, not an afterthought.',
      bodyKn: 'Speedup=0.875 ಎಂದೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಲಾಗಿದೆ, 1 ಕ್ಕಿಂತ ಕೆಳಗೆ, ದುರ್ಬಲ coordination ಎರಡೂ-worker speedup ಅನ್ನೂ 1 ಕ್ಕಿಂತ ಕೆಳಗೆ ಬೀಳಿಸಬಹುದು ಎಂಬ source ya ಸ್ಪಷ್ಟ claim ಗೆ ಹೊಂದಿಕೆಯಾಗುತ್ತದೆ. ಇದೂ coordination threshold ತುಂಬಾ ಹೆಚ್ಚೂ ಸೆಟ್ ಮಾಡಿದಾಗ ಸಂಭವಿಸುತ್ತದೆ (ಉದಾ. K=2 ಬದಲಿಗೆ K=100, Part 2 ನಲ್ಲಿ ನಿಜವಾಗಿ ಪ್ರದರ್ಶಿಸಲಾಗಿದೆ) ಆದ್ದರಿಂದ workers ಬಹುತೇಕ ಎಂದಿಗೂ "ಈ category ಸಾಕಷ್ಟೂ ಕೆಲಸ ಹೊಂದಿದೆ" ಎಂದೂ ತೀರ್ಮಾನಿಸುವುದಿಲ್ಲ -- ಎರಡೂ ಅದೇ category ಪುನರಾವರ್ತಿಸುತ್ತಲೇ ಇರಬಹುದು, compute utilization ಹೆಚ್ಚೂ ಕಾಣುತ್ತದೆ (ಎರಡೂ GPUs busy) ಆದರೆ reasoning efficiency ನಿಜವಾಗಿ ಕಡಿಮೆ. Stress test ಸಾಬೀತುಪಡಿಸುತ್ತದೆ: ಹೆಚ್ಚೂ workers ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಹೆಚ್ಚೂ ಉಪಯುಕ್ತ reasoning ಎಂದೂ ಅರ್ಥವಲ್ಲ. ಕೇವಲ ಹೆಚ್ಚೂ workers + shared state + ಉತ್ತಮ coordination ಉಪಯುಕ್ತ parallelism ನೀಡುತ್ತದೆ -- coordination quality ಒಂದೂ ಮೊದಲ-ದರ್ಜೆ performance variable, ಒಂದೂ ನಂತರದ ಆಲೋಚನೆ ಅಲ್ಲ.' } },

    { type: 'concept', data: {
      headingEn: 'Beyond Task Division: Error Correction Too', headingKn: 'Task Division ಆಚೆ: Error Correction ಕೂಡ',
      bodyEn: 'Hogwild! coordination can involve more than dividing tasks. The source also reports workers noticing mistakes: "W0: The proof works because x > 0. W1: That assumption fails when x=0. W0: Good catch, I\'ll revise the argument." So the shared cache supports task division + cross-checking + error correction simultaneously. But shared awareness does not guarantee effective collaboration: if all workers see the shared context but still redundantly investigate the same case ("W0: I\'ll investigate case A. W1: I\'ll independently verify case A. W2: I\'ll verify both analyses of case A" -- none moving to B or C), the workers understood the context but reacted inefficiently. This is one reason the source describes Hogwild! as experimental rather than production-mature.',
      bodyKn: 'Hogwild! coordination tasks ವಿಭಜಿಸುವುದೂ ಗಿಂತ ಹೆಚ್ಚೂ ಒಳಗೊಳ್ಳಬಹುದು. Source workers ದೋಷಗಳನ್ನೂ ಗಮನಿಸುವುದೂ ಕೂಡ ವರದಿ ಮಾಡುತ್ತದೆ: "W0: proof x > 0 ಆದ್ದರಿಂದ ಕೆಲಸ ಮಾಡುತ್ತದೆ. W1: ಆ ಊಹೆ x=0 ಆದಾಗ ವಿಫಲಗೊಳ್ಳುತ್ತದೆ. W0: ಒಳ್ಳೆಯ ಪತ್ತೆ, ನಾನೂ argument ಪರಿಷ್ಕರಿಸುತ್ತೇನೂ." ಆದ್ದರಿಂದ shared cache task division + cross-checking + error correction ಏಕಕಾಲದಲ್ಲಿ ಬೆಂಬಲಿಸುತ್ತದೆ. ಆದರೆ shared awareness effective collaboration ಖಾತ್ರಿಪಡಿಸುವುದಿಲ್ಲ: ಎಲ್ಲಾ workers shared context ನೋಡಿದರೂ ಇನ್ನೂ ಅದೇ case ಪುನರಾವರ್ತಿತವಾಗಿ ಪರಿಶೀಲಿಸಿದರೆ ("W0: ನಾನೂ case A ಪರಿಶೀಲಿಸುತ್ತೇನೂ. W1: ನಾನೂ ಸ್ವತಂತ್ರವಾಗಿ case A ಪರಿಶೀಲಿಸುತ್ತೇನೂ. W2: ನಾನೂ case A ya ಎರಡೂ ವಿಶ್ಲೇಷಣೆಗಳನ್ನೂ ಪರಿಶೀಲಿಸುತ್ತೇನೂ" -- ಯಾವುದೂ B ಅಥವಾ C ಗೆ ಚಲಿಸುವುದಿಲ್ಲ), workers context ಅರ್ಥಮಾಡಿಕೊಂಡಿದ್ದವೂ ಆದರೆ ಅಸಮರ್ಥವಾಗಿ ಪ್ರತಿಕ್ರಿಯಿಸಿದವೂ. Source Hogwild! ಅನ್ನೂ production-mature ಗಿಂತ ಪ್ರಾಯೋಗಿಕ ಎಂದೂ ವಿವರಿಸುವುದೂ ಗೆ ಇದೇ ಒಂದೂ ಕಾರಣ.' } },

    { type: 'heading', data: { textEn: 'Continuous Batching vs Hogwild!: Different Problems', textKn: 'Continuous Batching vs Hogwild!: ಭಿನ್ನ ಸಮಸ್ಯೆಗಳು', level: 'H2' } },
    { type: 'table', data: {
      captionEn: 'Continuous Batching vs Hogwild! Inference', captionKn: 'Continuous Batching vs Hogwild! Inference',
      rows: "Property|Continuous batching|Hogwild!\nGoal|Keep GPU busy|Parallelize reasoning\nRequests|Independent|Same problem\nContext|Separate|Shared\nCooperation|No|Yes\nMain mechanism|Scheduling|Shared-cache collaboration\nBest use|Many concurrent requests|Long decomposable reasoning" } },
    { type: 'concept', data: {
      headingEn: 'Static Batching\'s Idle-Slot Problem, and Continuous Batching\'s Fix', headingKn: 'Static Batching ya Idle-Slot ಸಮಸ್ಯೆ, ಮತ್ತೆ Continuous Batching ya Fix',
      bodyEn: 'With static batching, if a GPU has 4 request slots (A->3 steps, B->5, C->8, D->12), a slot sits idle once its request finishes until the LONGEST request in the batch completes -- wasted capacity. Continuous batching (genuinely explored with real numbers in Module 196 Part 2) immediately refills a freed slot from the queue: A finishes -> E enters; B finishes -> F enters -- keeping utilization high. Continuous batching asks "how can I efficiently serve many independent users?" while Hogwild! asks "how can several model instances cooperate on ONE difficult problem?" -- request-level scheduling versus task-level cooperative reasoning, genuinely different axes of inference optimization (alongside token-level speculative decoding from Module 199).',
      bodyKn: 'Static batching ಜೊತೆ, ಒಂದೂ GPU ಗೆ 4 request slots ಇದ್ದರೆ (A->3 steps, B->5, C->8, D->12), ಒಂದೂ slot ಅದೂ ya request ಮುಗಿದ ಒಮ್ಮೆ batch ನಲ್ಲಿ LONGEST request ಪೂರ್ಣಗೊಳ್ಳುವವರೆಗೆ idle ಆಗಿ ಕುಳಿತಿರುತ್ತದೆ -- ವ್ಯರ್ಥ capacity. Continuous batching (Module 196 Part 2 ನಲ್ಲಿ ನಿಜ ಸಂಖ್ಯೆಗಳ ಜೊತೆ ನಿಜವಾಗಿ ಅನ್ವೇಷಿಸಲಾಗಿದೆ) ಒಂದೂ ಮುಕ್ತಗೊಂಡ slot ಅನ್ನೂ queue ಇಂದ ತಕ್ಷಣ ಮರುತುಂಬುತ್ತದೆ: A ಮುಗಿಯುತ್ತದೆ -> E ಪ್ರವೇಶಿಸುತ್ತದೆ; B ಮುಗಿಯುತ್ತದೆ -> F ಪ್ರವೇಶಿಸುತ್ತದೆ -- utilization ಹೆಚ್ಚಾಗಿ ಇಡುತ್ತದೆ. Continuous batching "ನಾನೂ ಹಲವೂ ಸ್ವತಂತ್ರ users ಗಳಿಗೆ ಸಮರ್ಥವಾಗಿ ಹೇಗೆ ಸೇವೆ ಸಲ್ಲಿಸಬಹುದು?" ಎಂದೂ ಕೇಳುತ್ತದೆ ಆದರೆ Hogwild! "ಹಲವೂ model instances ONE ಕಷ್ಟಕರ ಸಮಸ್ಯೆ ಮೇಲೆ ಹೇಗೆ ಸಹಕರಿಸಬಹುದು?" ಎಂದೂ ಕೇಳುತ್ತದೆ -- request-level scheduling vs task-level cooperative reasoning, inference optimization ya ನಿಜವಾಗಿ ಭಿನ್ನ axes (Module 199 ya token-level speculative decoding ಜೊತೆಗೆ).' } },

    { type: 'heading', data: { textEn: 'Combining Hogwild! With Speculative Decoding', textKn: 'Hogwild! ಅನ್ನೂ Speculative Decoding ಜೊತೆ ಸಂಯೋಜಿಸುವುದೂ', level: 'H2' } },
    { type: 'code', data: {
      filename: 'combined_speedup.py', headingEn: 'Genuinely computing the combined speedup estimate when both mechanisms stack', headingKn: 'ಎರಡು ಕಾರ್ಯವಿಧಾನಗಳು ಪದರಗೊಂಡಾಗ ಸಂಯೋಜಿತ speedup ಅಂದಾಜನ್ನೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕುವುದೂ',
      descEn: 'Each Hogwild! worker could independently use speculative decoding (Module 199), since the two mechanisms improve different things: speculative decoding improves speed PER worker, Hogwild! improves the NUMBER of useful reasoning paths happening concurrently. Compute the rough multiplicative estimate for speculative decoding=3x and Hogwild!=1.8x.',
      descKn: "ಪ್ರತಿ Hogwild! worker ಸ್ವತಂತ್ರವಾಗಿ speculative decoding (Module 199) ಬಳಸಬಹುದು, ಏಕೆಂದರೆ ಎರಡೂ ಕಾರ್ಯವಿಧಾನಗಳು ಭಿನ್ನ ವಿಷಯಗಳನ್ನೂ ಸುಧಾರಿಸುತ್ತವೆ: speculative decoding ಪ್ರತಿ worker ya ವೇಗ ಸುಧಾರಿಸುತ್ತದೆ, Hogwild! ಏಕಕಾಲದಲ್ಲಿ ಸಂಭವಿಸುವ ಉಪಯುಕ್ತ reasoning paths ya ಸಂಖ್ಯೆ ಸುಧಾರಿಸುತ್ತದೆ. Speculative decoding=3x ಮತ್ತೆ Hogwild!=1.8x ಗೆ ಸ್ಥೂಲ multiplicative ಅಂದಾಜು ಲೆಕ್ಕಹಾಕಿ.",
      code: "spec_decoding_speedup = 3.0\nhogwild_speedup = 1.8\ncombined = spec_decoding_speedup * hogwild_speedup\nprint(f'combined speedup = {spec_decoding_speedup} x {hogwild_speedup} = {combined}')" } },
    { type: 'output', data: { output: 'combined speedup = 3.0 x 1.8 = 5.4' } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: 5.4x Multiplicative Estimate, Not a Guarantee', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: 5.4x Multiplicative ಅಂದಾಜು, ಖಾತ್ರಿ ಅಲ್ಲ',
      bodyEn: 'Genuinely computed 3.0 x 1.8 = 5.4, matching the source. The speedups can multiply because they improve orthogonal dimensions: token-level acceleration (speculative decoding, speed per worker) x task-level acceleration (Hogwild!, useful concurrent reasoning paths). But the source explicitly cautions this is an intuitive combined estimate, not a hard guarantee -- real systems also face memory pressure, verifier overhead, shared-cache contention, scheduling costs, and synchronization overhead, all of which can pull the actual combined gain below the naive product.',
      bodyKn: '3.0 x 1.8 = 5.4 ಎಂದೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಲಾಗಿದೆ, source ಗೆ ಹೊಂದಿಕೆಯಾಗುತ್ತದೆ. Speedups ಗುಣಿಸಬಹುದು ಏಕೆಂದರೆ ಅವು orthogonal dimensions ಸುಧಾರಿಸುತ್ತವೆ: token-level acceleration (speculative decoding, ಪ್ರತಿ worker ya ವೇಗ) x task-level acceleration (Hogwild!, ಉಪಯುಕ್ತ ಏಕಕಾಲಿಕ reasoning paths). ಆದರೆ source ಸ್ಪಷ್ಟವಾಗಿ ಎಚ್ಚರಿಸುತ್ತದೆ ಇದೂ ಒಂದೂ ಅಂತಃಪ್ರಜ್ಞೆಯ ಸಂಯೋಜಿತ ಅಂದಾಜು, ಒಂದೂ ಕಟ್ಟುನಿಟ್ಟಾದ ಖಾತ್ರಿ ಅಲ್ಲ -- ನಿಜ systems memory pressure, verifier overhead, shared-cache contention, scheduling costs, ಮತ್ತೆ synchronization overhead ಕೂಡ ಎದುರಿಸುತ್ತವೆ, ಇವೆಲ್ಲಾ ನಿಜ ಸಂಯೋಜಿತ gain ಅನ್ನೂ naive product ಗಿಂತ ಕೆಳಗೆ ಎಳೆಯಬಹುದು.' } },

    { type: 'heading', data: { textEn: 'When to Use Hogwild!, and When Not To', textKn: 'Hogwild! ಯಾವಾಗ ಬಳಸುವುದೂ, ಮತ್ತೆ ಯಾವಾಗ ಬೇಡ', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'A Practical Adoption Path and Decision Flow', headingKn: 'ಒಂದು ಪ್ರಾಯೋಗಿಕ Adoption Path ಮತ್ತು Decision Flow',
      bodyEn: 'Good workloads: long reasoning problems, tasks with independent sub-goals, reasoning-capable models, single-node deployments (fast shared-cache communication). Poor workloads: short chat (coordination cost c dominates), highly sequential tasks (p is near 0, no amount of coordination overcomes a truly sequential dependency), non-reasoning models (may see "Worker 0 already solved A" but still generate "I\'ll solve A" -- shared cache adds cost without task division), and multi-node setups (cross-node synchronization can become a severe latency problem, since each worker still needs its own activation memory even with a shared KV cache). Practical adoption path: profile the workload to estimate p -> start with N=2 -> if speedup < 1.3x, the workload is coordination-dominated, use N=1 -> if speedup > 1.5x, test N=4 -> diminishing returns generally appear around 4-8 workers.',
      bodyKn: 'Uttama workloads: ಉದ್ದ reasoning problems, ಸ್ವತಂತ್ರ sub-goals ಇರುವ tasks, reasoning-capable models, single-node deployments (ವೇಗದ shared-cache communication). Kalapa workloads: ಚಿಕ್ಕ chat (coordination cost c ಪ್ರಾಬಲ್ಯ ಸಾಧಿಸುತ್ತದೆ), ಬಹಳ ಅನುಕ್ರಮ tasks (p 0 ಗೆ ಹತ್ತಿರ, ಯಾವುದೇ coordination ಒಂದೂ ನಿಜವಾಗಿ ಅನುಕ್ರಮ ಅವಲಂಬನೆಯನ್ನೂ ಜಯಿಸುವುದಿಲ್ಲ), non-reasoning models ("Worker 0 ಈಗಾಗಲೇ A ಬಗೆಹರಿಸಿತೂ" ಎಂದೂ ನೋಡಬಹುದು ಆದರೂ "ನಾನೂ A ಬಗೆಹರಿಸುತ್ತೇನೂ" ಎಂದೂ ಉತ್ಪಾದಿಸಬಹುದು -- shared cache task division ಇಲ್ಲದೆ cost ಸೇರಿಸುತ್ತದೆ), ಮತ್ತೆ multi-node setups (cross-node synchronization ಒಂದೂ ತೀವ್ರ latency ಸಮಸ್ಯೆಯಾಗಬಹುದು, ಪ್ರತಿ worker ಗೆ ಶೇರ್ ಮಾಡಿದ KV cache ಇದ್ದರೂ ಅದೂ ya ಸ್ವಂತ activation memory ಬೇಕು). Practical adoption path: p ಅಂದಾಜಿಸಲು workload profile ಮಾಡಿ -> N=2 ಜೊತೆ ಆರಂಭಿಸಿ -> speedup < 1.3x ಆದರೆ, workload coordination-dominated, N=1 ಬಳಸಿ -> speedup > 1.5x ಆದರೆ, N=4 ಪರೀಕ್ಷಿಸಿ -> diminishing returns ಸಾಮಾನ್ಯವಾಗಿ 4-8 workers ಸುತ್ತ ಕಾಣಿಸುತ್ತದೆ.' } },

    { type: 'diagram', data: {
      titleEn: 'Hogwild! Adoption Decision Flow', titleKn: 'Hogwild! Adoption Decision Flow',
      captionEn: 'Long reasoning task? -> Can task split? -> Reasoning-capable model? -> Try N=2 -> speedup<1.3x means coordination-dominated (stop), speedup>1.5x means test N=4, watching for diminishing returns around 4-8 workers.',
      captionKn: 'Udda reasoning task? -> Task split ಆಗಬಹುದೇ? -> Reasoning-capable model? -> N=2 ಪ್ರಯತ್ನಿಸಿ -> speedup<1.3x coordination-dominated ಎಂದೂ ಅರ್ಥ (ನಿಲ್ಲಿಸಿ), speedup>1.5x N=4 ಪರೀಕ್ಷಿಸಿ ಎಂದೂ ಅರ್ಥ, 4-8 workers ಸುತ್ತ diminishing returns ಗಮನಿಸುತ್ತಾ.',
      svgCode: "<svg viewBox='0 0 700 140' xmlns='http://www.w3.org/2000/svg'><rect x='10' y='10' width='120' height='30' fill='#3b82f6'/><text x='15' y='29' fill='#fff' font-size='9'>Long reasoning?</text><rect x='150' y='10' width='120' height='30' fill='#3b82f6'/><text x='158' y='29' fill='#fff' font-size='9'>Task splits?</text><rect x='290' y='10' width='120' height='30' fill='#3b82f6'/><text x='298' y='29' fill='#fff' font-size='9'>Reasoning model?</text><rect x='430' y='10' width='100' height='30' fill='#22c55e'/><text x='440' y='29' fill='#0f172a' font-size='9'>Try N=2</text><rect x='430' y='60' width='100' height='25' fill='#ef4444'/><text x='438' y='77' fill='#fff' font-size='8'>&lt;1.3x: N=1</text><rect x='430' y='95' width='100' height='25' fill='#f59e0b'/><text x='432' y='112' fill='#0f172a' font-size='8'>&gt;1.5x: try N=4</text><text x='10' y='60' fill='#e2e8f0' font-size='9'>Any 'No' at first three steps -> N=1 (normal inference)</text></svg>" } },

    { type: 'concept', data: {
      headingEn: 'Common Misconception', headingKn: 'ಸಾಮಾನ್ಯ ತಪ್ಪುಗ್ರಹಿಕೆ',
      bodyEn: '"Two workers produced 13 versus 8 useful tokens, so Hogwild! obviously worked and always will." Two things this glosses over: (1) genuinely confirmed above that RAW token throughput (1.8x) can overstate the USEFUL gain (1.25x) -- always measure useful work, not total generation; (2) the same mechanism can produce speedup BELOW 1 (genuinely confirmed at 0.875x) if coordination is weak, so a single favorable run does not prove the technique "always works" -- it proves it worked THAT TIME under THOSE coordination conditions. Also: continuous batching and Hogwild! are sometimes confused because both involve "multiple things happening on a GPU at once" -- but continuous batching serves independent requests via scheduling, while Hogwild! makes multiple instances cooperate on ONE shared problem; they solve different problems and can be used together.',
      bodyKn: '"ಎರಡು workers 8 ಗೆ ಎದುರೂ 13 useful tokens ಉತ್ಪಾದಿಸಿದವೂ, ಆದ್ದರಿಂದ Hogwild! ಸ್ಪಷ್ಟವಾಗಿ ಕೆಲಸ ಮಾಡಿತೂ ಮತ್ತೆ ಯಾವಾಗಲೂ ಮಾಡುತ್ತದೆ." ಇದೂ ಎರಡೂ ಅಂಶಗಳನ್ನೂ ಮರೆಮಾಡುತ್ತದೆ: (1) ಮೇಲೆ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದಂತೆ RAW token throughput (1.8x) USEFUL gain (1.25x) ಅನ್ನೂ ಅತಿಶಯೋಕ್ತಿ ಮಾಡಬಹುದು -- ಯಾವಾಗಲೂ useful work ಅಳೆಯಿರಿ, total generation ಅಲ್ಲ; (2) ಅದೇ ಕಾರ್ಯವಿಧಾನ coordination ದುರ್ಬಲವಾಗಿದ್ದರೆ speedup ಅನ್ನೂ 1 ಕ್ಕಿಂತ ಕೆಳಗೆ ಉತ್ಪಾದಿಸಬಹುದು (0.875x ಎಂದೂ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ), ಆದ್ದರಿಂದ ಒಂದೂ ಅನುಕೂಲಕರ run technique "ಯಾವಾಗಲೂ ಕೆಲಸ ಮಾಡುತ್ತದೆ" ಎಂದೂ ಸಾಬೀತುಪಡಿಸುವುದಿಲ್ಲ -- ಇದೂ ಆ coordination conditions ಅಡಿಯಲ್ಲಿ ಆ ಸಮಯದಲ್ಲಿ ಕೆಲಸ ಮಾಡಿತೂ ಎಂದೂ ಸಾಬೀತುಪಡಿಸುತ್ತದೆ. ಕೂಡ: continuous batching ಮತ್ತೆ Hogwild! ಕೆಲವೊಮ್ಮೆ ಗೊಂದಲಗೊಳ್ಳುತ್ತವೆ ಏಕೆಂದರೆ ಎರಡೂ "ಒಂದೂ GPU ಮೇಲೆ ಒಂದೇ ಸಮಯದಲ್ಲಿ ಬಹು ವಿಷಯಗಳು ಸಂಭವಿಸುತ್ತಿವೆ" ಒಳಗೊಂಡಿವೆ -- ಆದರೆ continuous batching scheduling ಮೂಲಕ ಸ್ವತಂತ್ರ requests ಗೆ ಸೇವೆ ಸಲ್ಲಿಸುತ್ತದೆ, ಆದರೆ Hogwild! ಬಹು instances ONE shared problem ಮೇಲೆ ಸಹಕರಿಸುವಂತೆ ಮಾಡುತ್ತದೆ; ಅವು ಭಿನ್ನ ಸಮಸ್ಯೆಗಳನ್ನೂ ಬಗೆಹರಿಸುತ್ತವೆ ಮತ್ತೆ ಒಟ್ಟಿಗೆ ಬಳಸಬಹುದು.' } },

    { type: 'concept', data: {
      headingEn: 'Key Terms', headingKn: 'ಮುಖ್ಯ ಪದಗಳು',
      bodyEn: '• Serial baseline: useful work produced by one worker, genuinely computed as R_1=8/10=0.8 -- necessary before any speedup claim means anything\n• Effective speedup: genuinely confirmed 13/8=1.625x (good coordination) versus 7/8=0.875x (weak coordination, a slowdown)\n• Raw vs useful throughput: genuinely confirmed raw (1.8x) overstates useful (1.25x) -- always measure useful work tokens, not total generation\n• Stress test: intentionally weakening the coordination heuristic to test whether Hogwild! works BECAUSE of coordination, not merely because of worker count\n• Continuous batching: request-level scheduling that immediately refills freed GPU slots -- solves a different problem from Hogwild!\'s task-level cooperation\n• Combined speedup: genuinely computed 3x(spec decoding) * 1.8x(Hogwild!) = 5.4x -- an intuitive multiplicative estimate across orthogonal optimization axes, not a guarantee',
      bodyKn: '• Serial baseline: ಒಂದೂ worker ಉತ್ಪಾದಿಸಿದ useful work, R_1=8/10=0.8 ಎಂದೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಲಾಗಿದೆ -- ಯಾವುದೇ speedup claim ಏನಾದರೂ ಅರ್ಥ ಮಾಡುವ ಮೊದಲೂ ಅಗತ್ಯ\n• Effective speedup: 13/8=1.625x (ಉತ್ತಮ coordination) vs 7/8=0.875x (ದುರ್ಬಲ coordination, ಒಂದೂ slowdown) ಎಂದೂ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ\n• Raw vs useful throughput: raw (1.8x) useful (1.25x) ಅತಿಶಯೋಕ್ತಿ ಮಾಡುತ್ತದೆ ಎಂದೂ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ -- ಯಾವಾಗಲೂ useful work tokens ಅಳೆಯಿರಿ, total generation ಅಲ್ಲ\n• Stress test: Hogwild! coordination ಇಂದಾಗಿ ಕೆಲಸ ಮಾಡುತ್ತದೆ ಎಂದೂ ಪರೀಕ್ಷಿಸಲು ಉದ್ದೇಶಪೂರ್ವಕವಾಗಿ coordination heuristic ದುರ್ಬಲಗೊಳಿಸುವುದೂ, ಕೇವಲ worker count ಇಂದಾಗಿ ಅಲ್ಲ\n• Continuous batching: ಮುಕ್ತಗೊಂಡ GPU slots ಅನ್ನೂ ತಕ್ಷಣ ಮರುತುಂಬುವ request-level scheduling -- Hogwild! ya task-level cooperation ಇಂದ ಭಿನ್ನ ಸಮಸ್ಯೆ ಬಗೆಹರಿಸುತ್ತದೆ\n• Combined speedup: 3x(spec decoding) * 1.8x(Hogwild!) = 5.4x ಎಂದೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಲಾಗಿದೆ -- orthogonal optimization axes ಗಳಾದ್ಯಂತ ಒಂದೂ ಅಂತಃಪ್ರಜ್ಞೆಯ multiplicative ಅಂದಾಜು, ಖಾತ್ರಿ ಅಲ್ಲ' } },

    { type: 'concept', data: {
      headingEn: 'Key Takeaways', headingKn: 'ಮುಖ್ಯ ಅಂಶಗಳು',
      bodyEn: "• A one-worker baseline is essential: without R_1=8/10=0.8 useful throughput as a reference, a two-worker run's 13 tokens means nothing.\n• Genuinely computed effective speedup=13/8=1.625x under good coordination, matching the source's 1.5x-1.8x range.\n• Genuinely confirmed raw token throughput (1.8x) overstates useful reasoning throughput (1.25x) -- a real, measured gap between total activity and productive work.\n• Genuinely confirmed the stress test: weakening coordination drops speedup to 0.875x, BELOW 1 -- proving Hogwild! works because of coordination, not merely because of worker count.\n• Continuous batching (request-level scheduling for independent users) and Hogwild! (task-level cooperation on one shared problem) solve different problems and can be used together.\n• Genuinely computed the combined speedup estimate of speculative decoding x Hogwild! = 3 x 1.8 = 5.4x -- an intuitive multiplicative estimate across orthogonal optimization axes (token-level vs task-level), explicitly not a guarantee given real memory, verifier, and synchronization overhead.",
      bodyKn: "• ಒಂದು one-worker baseline ಅಗತ್ಯ: R_1=8/10=0.8 useful throughput ಒಂದೂ ಉಲ್ಲೇಖವಾಗಿ ಇಲ್ಲದೆ, ಒಂದೂ two-worker run ya 13 tokens ಏನೂ ಅರ್ಥವಲ್ಲ.\n• ಒಂದು ಉತ್ತಮ coordination ಅಡಿಯಲ್ಲಿ effective speedup=13/8=1.625x ಎಂದೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಲಾಗಿದೆ, source ya 1.5x-1.8x range ಗೆ ಹೊಂದಿಕೆಯಾಗುತ್ತದೆ.\n• Raw token throughput (1.8x) useful reasoning throughput (1.25x) ಅತಿಶಯೋಕ್ತಿ ಮಾಡುತ್ತದೆ ಎಂದೂ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ -- total activity ಮತ್ತೆ productive work ನಡುವೆ ಒಂದೂ ನಿಜ, ಅಳೆದ ಅಂತರ.\n• Stress test ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ: coordination ದುರ್ಬಲಗೊಳಿಸುವುದೂ speedup ಅನ್ನೂ 0.875x ಗೆ ಇಳಿಸುತ್ತದೆ, 1 ಕ್ಕಿಂತ ಕೆಳಗೆ -- Hogwild! coordination ಇಂದಾಗಿ ಕೆಲಸ ಮಾಡುತ್ತದೆ ಎಂದೂ ಸಾಬೀತುಪಡಿಸುತ್ತದೆ, ಕೇವಲ worker count ಇಂದಾಗಿ ಅಲ್ಲ.\n• Continuous batching (ಸ್ವತಂತ್ರ users ಗಾಗಿ request-level scheduling) ಮತ್ತೆ Hogwild! (ಒಂದೂ shared problem ಮೇಲೆ task-level cooperation) ಭಿನ್ನ ಸಮಸ್ಯೆಗಳನ್ನೂ ಬಗೆಹರಿಸುತ್ತವೆ ಮತ್ತೆ ಒಟ್ಟಿಗೆ ಬಳಸಬಹುದು.\n• Speculative decoding x Hogwild! = 3 x 1.8 = 5.4x ya ಸಂಯೋಜಿತ speedup ಅಂದಾಜು ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಲಾಗಿದೆ -- orthogonal optimization axes (token-level vs task-level) ಗಳಾದ್ಯಂತ ಒಂದೂ ಅಂತಃಪ್ರಜ್ಞೆಯ multiplicative ಅಂದಾಜು, ನಿಜ memory, verifier, ಮತ್ತೆ synchronization overhead ಕೊಟ್ಟಾಗ ಸ್ಪಷ್ಟವಾಗಿ ಖಾತ್ರಿ ಅಲ್ಲ." } },

    { type: 'concept', data: {
      headingEn: 'Module Wrap-Up: The Full Hogwild! Story', headingKn: 'Module Wrap-Up: ಪೂರ್ಣ Hogwild! ಕಥೆ',
      bodyEn: 'Across all three parts: Part 1 established the core idea (N workers + one shared KV cache -> emergent, unscripted coordination), genuinely computed a 50,000-token reasoning trace takes ~23.8 minutes, and distinguished Hogwild! from voting/tree-of-thought/multi-agent by its lack of an explicit coordination protocol. Part 2 genuinely derived why RoPE\'s relative-position property makes concurrent writes tractable, then genuinely computed the full Amdahl-style example (T_Hogwild=5550, speedup=1.8x matching the source exactly) and confirmed the same 800-unit overhead is a slowdown on a 500-step task but nearly free on a 50,000-step one. Part 3 genuinely ran the full experiment: confirmed raw throughput (1.8x) overstates useful gain (1.25x), genuinely demonstrated the stress test drops speedup to 0.875x under weak coordination, distinguished Hogwild! from continuous batching, and genuinely computed the 5.4x combined estimate with speculative decoding. The throughline: Hogwild! represents a genuinely different axis of inference optimization -- not making tokens generate faster, but attempting to parallelize the reasoning process itself, and its benefit depends entirely on whether coordination actually emerges, which this module tested rather than assumed at every step.',
      bodyKn: 'Ellā ಮೂರೂ ಭಾಗಗಳಾದ್ಯಂತ: Part 1 ಮುಖ್ಯ ಆಲೋಚನೆ ಸ್ಥಾಪಿಸಿತೂ (N workers + ಒಂದೂ shared KV cache -> emergent, unscripted coordination), ಒಂದೂ 50,000-token reasoning trace ~23.8 ನಿಮಿಷಗಳು ತೆಗೆದುಕೊಳ್ಳುತ್ತದೆ ಎಂದೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಿತೂ, ಮತ್ತೆ Hogwild! ಅನ್ನೂ ಅದೂ ya ಸ್ಪಷ್ಟ coordination protocol ya ಕೊರತೆಯಿಂದ voting/tree-of-thought/multi-agent ಇಂದ ಪ್ರತ್ಯೇಕಿಸಿತೂ. Part 2 RoPE ya relative-position ಗುಣಲಕ್ಷಣ ಏಕಕಾಲಿಕ writes ಅನ್ನೂ ಹೇಗೆ ನಿರ್ವಹಿಸಬಹುದಾಗಿ ಮಾಡುತ್ತದೆ ಎಂದೂ ನಿಜವಾಗಿ ಪಡೆಯಿತೂ, ನಂತರ ಪೂರ್ಣ Amdahl-style ಉದಾಹರಣೆ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಿತೂ (T_Hogwild=5550, speedup=1.8x source ಗೆ ನಿಖರವಾಗಿ ಹೊಂದಿಕೆಯಾಗುತ್ತದೆ) ಮತ್ತೆ ಅದೇ 800-unit overhead 500-step task ಮೇಲೆ ಒಂದೂ slowdown ಆದರೆ 50,000-step ಒಂದೂ ಮೇಲೆ ಬಹುತೇಕ ಉಚಿತ ಎಂದೂ ದೃಢಪಡಿಸಿತೂ. Part 3 ಪೂರ್ಣ ಪ್ರಯೋಗ ನಿಜವಾಗಿ ಓಡಿಸಿತೂ: raw throughput (1.8x) useful gain (1.25x) ಅತಿಶಯೋಕ್ತಿ ಮಾಡುತ್ತದೆ ಎಂದೂ ದೃಢಪಡಿಸಿತೂ, stress test ದುರ್ಬಲ coordination ಅಡಿಯಲ್ಲಿ speedup ಅನ್ನೂ 0.875x ಗೆ ಇಳಿಸುತ್ತದೆ ಎಂದೂ ನಿಜವಾಗಿ ಪ್ರದರ್ಶಿಸಿತೂ, Hogwild! ಅನ್ನೂ continuous batching ಇಂದ ಪ್ರತ್ಯೇಕಿಸಿತೂ, ಮತ್ತೆ speculative decoding ಜೊತೆ 5.4x ಸಂಯೋಜಿತ ಅಂದಾಜನ್ನೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಿತೂ. ಸಾಮಾನ್ಯ ಎಳೆ: Hogwild! inference optimization ya ನಿಜವಾಗಿ ಭಿನ್ನ axis ಪ್ರತಿನಿಧಿಸುತ್ತದೆ -- tokens ಅನ್ನೂ ವೇಗವಾಗಿ ಉತ್ಪಾದಿಸುವುದೂ ಅಲ್ಲ, ಆದರೆ reasoning ಪ್ರಕ್ರಿಯೆಯನ್ನೂ ಸ್ವತಃ parallelize ಮಾಡಲು ಪ್ರಯತ್ನಿಸುವುದೂ, ಮತ್ತೆ ಅದೂ ya ಪ್ರಯೋಜನ coordination ನಿಜವಾಗಿ ಹೊರಹೊಮ್ಮುತ್ತದೆಯೇ ಎಂಬುದೂ ಮೇಲೆ ಸಂಪೂರ್ಣವಾಗಿ ಅವಲಂಬಿತವಾಗಿದೆ, ಇದನ್ನೂ ಈ module ಪ್ರತಿ ಹಂತದಲ್ಲೂ ಊಹಿಸುವ ಬದಲಿಗೆ ಪರೀಕ್ಷಿಸಿತೂ.' } },

    { type: 'quiz', data: { questions: [
      { q: 'Why run a one-worker experiment first?',
        qKn: 'ಮೊದಲೂ ಒಂದೂ one-worker experiment ಏಕೆ ಓಡಿಸುವುದೂ?',
        opts: ['To train the model', 'To establish a useful-work baseline', 'To initialize RoPE', 'To compress the KV cache'], correct: 1,
        optsKn: ['Model ಗೆ ತರಬೇತಿ ನೀಡಲು', 'ಒಂದು useful-work baseline ಸ್ಥಾಪಿಸಲು', 'RoPE ಪ್ರಾರಂಭಿಸಲು', 'KV cache ಸಂಕುಚಿತಗೊಳಿಸಲು'] },
      { q: 'Genuinely confirmed: two workers generate 18 total tokens (10 useful) versus one worker\'s 10 total tokens (8 useful). Did useful reasoning double?',
        qKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: ಎರಡೂ workers 18 total tokens (10 useful) ಉತ್ಪಾದಿಸುತ್ತವೆ, ಒಂದೂ worker ya 10 total tokens (8 useful) ಎದುರೂ. Useful reasoning ದ್ವಿಗುಣಗೊಂಡಿತೂ?',
        opts: ['Yes, exactly 2x', 'No, only 1.25x, far less than the 1.8x raw token throughput suggests', 'Yes, more than 2x', 'Useful reasoning cannot be measured'], correct: 1,
        optsKn: ['ಹೌದೂ, ನಿಖರವಾಗಿ 2x', 'ಇಲ್ಲ, ಕೇವಲ 1.25x, 1.8x raw token throughput ಸೂಚಿಸುವುದೂ ಗಿಂತ ಬಹಳ ಕಡಿಮೆ', 'ಹೌದೂ, 2x ಗಿಂತ ಹೆಚ್ಚೂ', 'Useful reasoning ಅಳೆಯಲು ಸಾಧ್ಯವಿಲ್ಲ'] },
      { q: 'Genuinely confirmed: what happened to speedup under the coordination stress test (single worker=8 useful, poorly-coordinated two workers=7 useful)?',
        qKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: coordination stress test ಅಡಿಯಲ್ಲಿ speedup ಗೆ ಏನಾಯಿತೂ (single worker=8 useful, ಕಳಪೆಯಾಗಿ-coordinated two workers=7 useful)?',
        opts: ['Speedup increased to 2x', 'Speedup stayed at exactly 1x', 'Speedup fell to 0.875x, below 1 (a slowdown)', 'Speedup became undefined'], correct: 2,
        optsKn: ['Speedup 2x ಗೆ ಹೆಚ್ಚಾಯಿತೂ', 'Speedup ನಿಖರವಾಗಿ 1x ಆಗಿ ಉಳಿಯಿತೂ', 'Speedup 0.875x ಗೆ ಇಳಿಯಿತೂ, 1 ಕ್ಕಿಂತ ಕೆಳಗೆ (ಒಂದೂ slowdown)', 'Speedup ಅನಿರ್ದಿಷ್ಟವಾಯಿತೂ'] },
      { q: 'What is the main difference between continuous batching and Hogwild!?',
        qKn: 'Continuous batching ಮತ್ತೆ Hogwild! ನಡುವಿನ ಮುಖ್ಯ ವ್ಯತ್ಯಾಸ ಏನೂ?',
        opts: ['They are identical', 'Continuous batching schedules independent requests; Hogwild! lets workers cooperate on the same reasoning task', 'Hogwild! requires static batching', 'Continuous batching uses shared reasoning'], correct: 1,
        optsKn: ['Avu ಒಂದೇ', 'Continuous batching ಸ್ವತಂತ್ರ requests schedule ಮಾಡುತ್ತದೆ; Hogwild! workers ಗೆ ಅದೇ reasoning task ಮೇಲೆ ಸಹಕರಿಸಲು ಬಿಡುತ್ತದೆ', 'Hogwild! ಗೆ static batching ಬೇಕು', 'Continuous batching shared reasoning ಬಳಸುತ್ತದೆ'] },
      { q: 'Genuinely confirmed: if speculative decoding gives 3x and Hogwild! gives 1.8x, what rough combined speedup does the lesson suggest?',
        qKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: speculative decoding 3x ನೀಡಿದರೆ ಮತ್ತೆ Hogwild! 1.8x ನೀಡಿದರೆ, lesson ಯಾವ ಸ್ಥೂಲ ಸಂಯೋಜಿತ speedup ಸೂಚಿಸುತ್ತದೆ?',
        opts: ['1.8x', '3x', '4.8x', '5.4x'], correct: 3,
        optsKn: ['1.8x', '3x', '4.8x', '5.4x'] },
    ] } },
  ],
};
