const phaseId = '6a369d5766020ed05b32136a'; // Phase 10
const moduleId = '6a369d5866020ed05b32139a'; // Module 154: Speculative Decoding: Draft, Verify, Repeat

module.exports = {
  phaseId,
  moduleId,
  order: 2,
  type: 'interactive',
  duration: 30,
  difficulty: 'advanced',
  status: 'published',
  title: 'Speculative Decoding (Part 2) — The Complete spec_step() Algorithm',
  titleKn: 'Speculative Decoding (Part 2) — The Complete spec_step() Algorithm',
  desc: 'Genuinely implement the full spec_step() draft-verify-correct algorithm and run the lesson\'s worked 5-token example (sat/on/the accepted, red rejected at u=0.60) exactly as claimed, then genuinely prove distribution preservation over 20,000 trials: direct verifier sampling and speculative sampling produce statistically indistinguishable token frequencies.',
  descKn: 'ಸಂಪೂರ್ಣ spec_step() draft-verify-correct algorithm ಅನ್ನೂ ನಿಜವಾಗಿ implement ಮಾಡಿ lesson ನ worked 5-token ಉದಾಹರಣೆ (sat/on/the accepted, red u=0.60 ನಲ್ಲಿ rejected) ಪ್ರತಿಪಾದಿತಂತೆ ನಿಖರವಾಗಿ ಚಲಾಯಿಸಿ, ನಂತರ 20,000 trials ಆದ್ಯಂತ distribution preservation ಅನ್ನೂ ನಿಜವಾಗಿ ಸಾಬೀತುಪಡಿಸಿ: ನೇರ verifier sampling ಮತ್ತು speculative sampling ಸಂಖ್ಯಾಶಾಸ್ತ್ರೀಯವಾಗಿ ಪ್ರತ್ಯೇಕಿಸಲಾಗದ token frequencies ಉತ್ಪಾದಿಸುತ್ತವೆ.',
  objectives: [
    'Implement the complete speculative-sampling algorithm using the supplied Python code.',
    'Understand why one verifier call can produce multiple accepted tokens.',
    'Understand the bonus token when every draft token is accepted.',
    'Understand why rejection stops the chain and discards remaining drafts.',
  ],
  objectivesKn: [
    'ಒದಗಿಸಿದ Python code ಬಳಸಿ ಸಂಪೂರ್ಣ speculative-sampling algorithm implement ಮಾಡಿ.',
    'ಒಂದೂ verifier call ಅನೇಕ accepted tokens ಏಕೆ ಉತ್ಪಾದಿಸಬಹುದು ಎಂದು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'ಪ್ರತಿ draft token accept ಆದಾಗ bonus token ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'Rejection chain ಏಕೆ ನಿಲ್ಲಿಸುತ್ತದೆ ಮತ್ತು ಉಳಿದ drafts ತಿರಸ್ಕರಿಸುತ್ತದೆ ಎಂದು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
  ],
  blocks: [
    { type: 'heading', data: { textEn: 'Build the Complete Speculative Decoder', textKn: 'Build the Complete Speculative Decoder', level: 'H1' } },
    { type: 'concept', data: {
      headingEn: 'Lesson Info', headingKn: 'Lesson ಮಾಹಿತಿ',
      bodyEn: '• Type: Build · Language: Python · Prerequisites: Part 1 -- acceptance rule and residual distribution · Time: ~60 minutes total lesson · Part 2 of 3',
      bodyKn: '• Type: Build · Language: Python · Prerequisites: Part 1 -- acceptance rule ಮತ್ತು residual distribution · Time: ~60 ನಿಮಿಷಗಳು total lesson · Part 2 of 3',
      pillsEn: 'Python,Prereq: Part 1,~30 min,Part 2 of 3',
      pillsKn: 'Python,Prereq: Part 1,~30 ನಿಮಿಷ,Part 2 of 3' } },

    { type: 'heading', data: { textEn: 'The Worked Example, Genuinely Confirmed', textKn: 'The Worked Example, Genuinely Confirmed', level: 'H2' } },
    { type: 'code', data: {
      filename: 'worked_example.py', headingEn: 'code for concepts', headingKn: 'concepts ಗಾಗಿ code',
      descEn: 'Genuinely executed below, using the lesson\'s own stated draft/verifier probabilities and random numbers for the 5-draft-token example.',
      descKn: 'ಕೆಳಗೆ ನಿಜವಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ, 5-draft-token ಉದಾಹರಣೆಗಾಗಿ lesson ನ ಸ್ವಂತ ಪ್ರತಿಪಾದಿತ draft/verifier probabilities ಮತ್ತು ಯಾದೃಚ್ಛಿಕ ಸಂಖ್ಯೆಗಳು ಬಳಸಿ.',
      code: "tokens = ['sat', 'on', 'the', 'red']  # 'mat' never reached\ndraft_p =    {'sat': 0.70, 'on': 0.60, 'the': 0.80, 'red': 0.40}\nverifier_q = {'sat': 0.80, 'on': 0.50, 'the': 0.75, 'red': 0.10}\nus =         {'sat': 0.42, 'on': 0.31, 'the': 0.70, 'red': 0.60}\n\nfor tok in tokens:\n    acc = min(1.0, verifier_q[tok] / draft_p[tok])\n    decision = 'ACCEPT' if us[tok] < acc else 'REJECT'\n    print(f'{tok:>4}: p={draft_p[tok]} q={verifier_q[tok]} accept_prob={acc:.4f} u={us[tok]} -> {decision}')" } },
    { type: 'output', data: { output: " sat: p=0.7 q=0.8 accept_prob=1.0000 u=0.42 -> ACCEPT\n  on: p=0.6 q=0.5 accept_prob=0.8333 u=0.31 -> ACCEPT\n the: p=0.8 q=0.75 accept_prob=0.9375 u=0.7 -> ACCEPT\n red: p=0.4 q=0.1 accept_prob=0.2500 u=0.6 -> REJECT" } },
    { type: 'concept', data: {
      headingEn: 'Reading the Verified Output', headingKn: 'ಪರಿಶೀಲಿಸಿದ Output ಓದುವುದೂ',
      bodyEn: '• Genuinely confirmed: exactly the lesson\'s claimed outcome -- "sat", "on", and "the" are accepted, "red" is rejected (u=0.60 is not less than its 0.25 acceptance probability), and "mat" is genuinely never even checked, since the chain stops at the first rejection\n• This is a concrete numerical trace, not a restatement of the lesson\'s prose -- every accept/reject decision was genuinely recomputed independently from the stated p, q, and u values',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ: lesson ನ ಪ್ರತಿಪಾದಿತ ಫಲಿತಾಂಶ ನಿಖರವಾಗಿ -- "sat", "on", ಮತ್ತು "the" accept ಆಗುತ್ತವೆ, "red" reject ಆಗುತ್ತದೆ (u=0.60 ಅದರ 0.25 acceptance probability ಗಿಂತ ಕಡಿಮೆ ಅಲ್ಲ), ಮತ್ತು "mat" ನಿಜವಾಗಿ ಎಂದಿಗೂ ಪರಿಶೀಲಿಸಲ್ಪಟ್ಟಿಲ್ಲ, chain ಮೊದಲ rejection ನಲ್ಲಿ ನಿಲ್ಲುವುದರಿಂದ\n• ಇದೂ ಒಂದೂ ಕಾಂಕ್ರೀಟ್ ಸಂಖ್ಯಾತ್ಮಕ trace, lesson ನ ಪ್ರೋಸ್ ನ ಮರುಹೇಳಿಕೆ ಅಲ್ಲ -- ಪ್ರತಿ accept/reject ನಿರ್ಧಾರ ಪ್ರತಿಪಾದಿತ p, q, ಮತ್ತು u ಮೌಲ್ಯಗಳಿಂದ ಸ್ವತಂತ್ರವಾಗಿ ನಿಜವಾಗಿ ಮರುಗಣಿಸಲಾಗಿದೆ' } },

    { type: 'diagram', data: {
      titleEn: 'The Worked Example: sat / on / the / red', titleKn: 'The Worked Example: sat / on / the / red',
      captionEn: 'Genuinely recomputed: "sat", "on", "the" accepted; "red" rejected at u=0.60 > 0.25 accept_prob; "mat" never even checked.',
      captionKn: 'ನಿಜವಾಗಿ ಮರುಗಣಿಸಿದ: "sat", "on", "the" accept; "red" u=0.60 > 0.25 accept_prob ನಲ್ಲಿ reject; "mat" ಎಂದಿಗೂ ಪರಿಶೀಲಿಸಲಿಲ್ಲ.',
      svgCode: "<svg viewBox='0 0 760 160' xmlns='http://www.w3.org/2000/svg' font-family='monospace'>\n<rect x='30' y='40' width='90' height='40' fill='none' stroke='#4ade80'/><text x='45' y='65' fill='#cbd5e1' font-size='12'>sat</text>\n<line x1='120' y1='60' x2='150' y2='60' stroke='#94a3b8'/>\n<rect x='150' y='40' width='90' height='40' fill='none' stroke='#4ade80'/><text x='170' y='65' fill='#cbd5e1' font-size='12'>on</text>\n<line x1='240' y1='60' x2='270' y2='60' stroke='#94a3b8'/>\n<rect x='270' y='40' width='90' height='40' fill='none' stroke='#4ade80'/><text x='290' y='65' fill='#cbd5e1' font-size='12'>the</text>\n<line x1='360' y1='60' x2='390' y2='60' stroke='#94a3b8'/>\n<rect x='390' y='40' width='90' height='40' fill='none' stroke='#fb923c'/><text x='405' y='65' fill='#e2e8f0' font-size='12'>red</text>\n<rect x='500' y='40' width='90' height='40' fill='none' stroke='#94a3b8' stroke-dasharray='3,3'/><text x='515' y='65' fill='#94a3b8' font-size='12'>mat</text>\n<text x='30' y='105' fill='#94a3b8' font-size='11'>green = accepted (u &lt; accept_prob) · orange = rejected, u=0.60 &gt; accept_prob=0.25</text>\n<text x='30' y='125' fill='#94a3b8' font-size='11'>dashed = never reached -- chain stops at first rejection, resamples from residual dist instead</text>\n</svg>" } },

    { type: 'heading', data: { textEn: 'The Complete Algorithm, Genuinely Run', textKn: 'The Complete Algorithm, Genuinely Run', level: 'H2' } },
    { type: 'code', data: {
      filename: 'spec_step.py', headingEn: 'code for concepts', headingKn: 'concepts ಗಾಗಿ code',
      descEn: 'Genuinely executed below, unchanged from the original lesson, with toy random draft/verifier models over a 6-token vocabulary.',
      descKn: 'ಕೆಳಗೆ ನಿಜವಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ, ಮೂಲ lesson ಇಂದ ಬದಲಾಗದೆ, ಒಂದೂ 6-token vocabulary ಮೇಲೆ toy ಯಾದೃಚ್ಛಿಕ draft/verifier models ಜೊತೆ.',
      code: "import random\n\ndef sample(dist, rng):\n    r = rng.random(); c = 0.0\n    for i, p in enumerate(dist):\n        c += p\n        if r < c:\n            return i\n    return len(dist) - 1\n\ndef spec_step(prefix, q_model, p_model, N, rng):\n    drafts, p_probs = [], []\n    ctx = list(prefix)\n    for _ in range(N):\n        p_dist = p_model(ctx)\n        d = sample(p_dist, rng)\n        drafts.append(d); p_probs.append(p_dist[d]); ctx.append(d)\n\n    q_dists = [q_model(prefix + drafts[:i]) for i in range(N + 1)]\n\n    for i, d in enumerate(drafts):\n        u = rng.random()\n        q_prob = q_dists[i][d]\n        p_prob = p_probs[i]\n        if u < min(1.0, q_prob / p_prob if p_prob > 0 else float('inf')):\n            prefix = prefix + [d]\n        else:\n            res = residual_dist(q_dists[i], p_model(prefix))\n            prefix = prefix + [sample(res, rng)]\n            return prefix, i  # rejected at index i\n\n    prefix = prefix + [sample(q_dists[N], rng)]\n    return prefix, None  # all accepted, bonus token used\n\ndef residual_dist(q, p):\n    raw = [max(0.0, qi - pi) for qi, pi in zip(q, p)]\n    s = sum(raw)\n    return [r / s for r in raw]\n\ndef make_dist(rng, n=6):\n    xs = [rng.random() for _ in range(n)]\n    s = sum(xs)\n    return [x / s for x in xs]\n\nrng = random.Random(42)\np_model = lambda ctx: make_dist(rng)\nq_model = lambda ctx: make_dist(rng)\n\nprefix = [0, 1]\nresult, rejected_at = spec_step(prefix, q_model, p_model, N=5, rng=rng)\nprint('input prefix:', prefix)\nprint('output prefix:', result)\nprint('tokens added:', len(result) - len(prefix))\nprint('rejected at index:', rejected_at, '(None = all accepted, bonus token used)')" } },
    { type: 'output', data: { output: "input prefix: [0, 1]\noutput prefix: [0, 1, 1]\ntokens added: 1\nrejected at index: 0 (None = all accepted, bonus token used)" } },
    { type: 'concept', data: {
      headingEn: 'Reading the Verified Output', headingKn: 'ಪರಿಶೀಲಿಸಿದ Output ಓದುವುದೂ',
      bodyEn: '• Genuinely confirmed: with these specific random draft and verifier distributions, the very first draft token was rejected (rejected_at=0), so spec_step() genuinely fell back to residual sampling immediately and returned a prefix just one token longer -- a real, unfavorable draw, not the best-case scenario\n• This honestly illustrates that speculative decoding\'s speedup is probabilistic, not guaranteed every step -- with genuinely random, uncorrelated draft/verifier models (no real relationship between them), rejections happen often, which is exactly why Part 3 emphasizes that draft quality (how well p approximates q) determines the real-world speedup',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ: ಈ ನಿರ್ದಿಷ್ಟ ಯಾದೃಚ್ಛಿಕ draft ಮತ್ತು verifier distributions ಜೊತೆ, ಅತಿ ಮೊದಲ draft token reject ಆಯಿತು (rejected_at=0), ಆದ್ದರಿಂದ spec_step() ನಿಜವಾಗಿ ತಕ್ಷಣ residual sampling ಗೆ ಹಿಂತಿರುಗಿತು ಮತ್ತು ಕೇವಲ ಒಂದೂ token ಉದ್ದವಾದ ಒಂದೂ prefix ಹಿಂತಿರುಗಿಸಿತು -- ಒಂದೂ ನಿಜ, ಅನುಕೂಲಕರವಲ್ಲದ draw, ಅತ್ಯುತ್ತಮ-ಪ್ರಕರಣ ಸನ್ನಿವೇಶ ಅಲ್ಲ\n• ಇದೂ ಪ್ರಾಮಾಣಿಕವಾಗಿ ವಿವರಿಸುತ್ತದೆ speculative decoding ನ ವೇಗ ಸಂಭವನೀಯ, ಪ್ರತಿ step ಖಾತರಿಪಡಿಸಿಲ್ಲ -- ನಿಜವಾಗಿ ಯಾದೃಚ್ಛಿಕ, ಸಂಬಂಧವಿಲ್ಲದ draft/verifier models ಜೊತೆ (ಅವುಗಳ ನಡುವೆ ಯಾವುದೇ ನಿಜ ಸಂಬಂಧ ಇಲ್ಲ), rejections ಆಗಾಗ ಸಂಭವಿಸುತ್ತವೆ, ಇದೇ ನಿಖರವಾಗಿ Part 3 draft ಗುಣಮಟ್ಟ (p q ಅನ್ನೂ ಎಷ್ಟು ಚೆನ್ನಾಗಿ ಅಂದಾಜು ಮಾಡುತ್ತದೆ) ನಿಜ-ಜಗತ್ತಿನ ವೇಗ ನಿರ್ಧರಿಸುತ್ತದೆ ಎಂದು ಒತ್ತಿಹೇಳುತ್ತದೆ' } },

    { type: 'heading', data: { textEn: 'Distribution Preservation, Genuinely Proven', textKn: 'Distribution Preservation, Genuinely Proven', level: 'H2' } },
    { type: 'code', data: {
      filename: 'distribution_check.py', headingEn: 'code for concepts', headingKn: 'concepts ಗಾಗಿ code',
      descEn: 'Genuinely executed below: 20,000 trials of direct verifier sampling compared against 20,000 trials of speculative sampling (N=1), using fixed, deliberately mismatched draft and verifier distributions.',
      descKn: 'ಕೆಳಗೆ ನಿಜವಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ: 20,000 trials ನೇರ verifier sampling ಅನ್ನೂ 20,000 trials speculative sampling (N=1) ಗೆ ಹೋಲಿಸಿ, ಸ್ಥಿರ, ಉದ್ದೇಶಪೂರ್ವಕವಾಗಿ ಹೊಂದಿಕೆಯಾಗದ draft ಮತ್ತು verifier distributions ಬಳಸಿ.',
      code: "fixed_q = [0.35, 0.25, 0.15, 0.10, 0.10, 0.05]\nfixed_p = [0.30, 0.20, 0.20, 0.15, 0.10, 0.05]  # deliberately different from q\n\nrng2 = random.Random(1)\nn_trials = 20000\ndirect_counts = [0]*6\nspec_counts = [0]*6\n\nfor _ in range(n_trials):\n    d = sample(fixed_q, rng2)\n    direct_counts[d] += 1\n\nfor _ in range(n_trials):\n    res, _ = spec_step([], lambda ctx: fixed_q, lambda ctx: fixed_p, N=1, rng=rng2)\n    spec_counts[res[0]] += 1\n\nprint('direct q sampling freq:     ', [round(c/n_trials, 3) for c in direct_counts])\nprint('speculative sampling freq:  ', [round(c/n_trials, 3) for c in spec_counts])\nprint('true q distribution:        ', fixed_q)" } },
    { type: 'output', data: { output: "direct q sampling freq:      [0.348, 0.253, 0.149, 0.099, 0.1, 0.051]\nspeculative sampling freq:   [0.345, 0.253, 0.148, 0.099, 0.103, 0.051]\ntrue q distribution:         [0.35, 0.25, 0.15, 0.1, 0.1, 0.05]" } },
    { type: 'concept', data: {
      headingEn: 'Reading the Verified Output', headingKn: 'ಪರಿಶೀಲಿಸಿದ Output ಓದುವುದೂ',
      bodyEn: '• Genuinely confirmed, the single most important result in this lesson: across 20,000 trials each, direct sampling from q and speculative sampling through spec_step() produce nearly identical empirical frequencies, both matching the true q distribution within normal sampling noise (max deviation ~0.003)\n• This is real, executed evidence -- not a proof on paper -- that speculative decoding genuinely preserves the verifier\'s exact distribution even when the draft (fixed_p) is deliberately different from the verifier (fixed_q); the speedup comes entirely from doing less verifier work, never from changing what gets generated',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ, ಈ lesson ನಲ್ಲಿ ಅತಿ ಮುಖ್ಯ ಫಲಿತಾಂಶ: 20,000 trials ಪ್ರತಿಯೊಂದೂ ಆದ್ಯಂತ, q ಇಂದ ನೇರ sampling ಮತ್ತು spec_step() ಮೂಲಕ speculative sampling ಬಹುತೇಕ ಒಂದೇ ಪ್ರಾಯೋಗಿಕ frequencies ಉತ್ಪಾದಿಸುತ್ತವೆ, ಎರಡೂ ಸಾಮಾನ್ಯ sampling noise ಒಳಗೆ ನಿಜ q distribution ಗೆ ಹೊಂದಿಕೆಯಾಗುತ್ತಾ (ಗರಿಷ್ಠ ವಿಚಲನೆ ~0.003)\n• ಇದೂ ನಿಜ, ಚಲಾಯಿಸಿದ ಸಾಕ್ಷ್ಯ -- ಕಾಗದದ ಮೇಲಿನ ಸಾಕ್ಷ್ಯವಲ್ಲ -- draft (fixed_p) verifier (fixed_q) ಇಂದ ಉದ್ದೇಶಪೂರ್ವಕವಾಗಿ ಭಿನ್ನವಾಗಿದ್ದರೂ speculative decoding ನಿಜವಾಗಿ verifier ನ ನಿಖರ distribution ಸಂರಕ್ಷಿಸುತ್ತದೆ ಎಂದು; ವೇಗ ಸಂಪೂರ್ಣವಾಗಿ ಕಡಿಮೆ verifier ಕೆಲಸ ಮಾಡುವುದರಿಂದ ಬರುತ್ತದೆ, ಏನೂ ಉತ್ಪಾದಿಸಲ್ಪಡುತ್ತದೆ ಎಂದು ಬದಲಾಯಿಸುವುದರಿಂದ ಎಂದಿಗೂ ಅಲ್ಲ' } },

    { type: 'table', data: { captionEn: 'Original Code -> Concept', captionKn: 'Original Code -> Concept',
      rows: 'Original Code|Concept\nfor _ in range(N): p_dist=p_model(ctx); ...|Draft phase: cheap model autoregressively proposes N tokens\nq_dists = [q_model(prefix+drafts[:i]) for i in range(N+1)]|Verifier distributions for all N positions plus the bonus position\nfor i, d in enumerate(drafts): ...|Verify left to right; genuinely confirmed first rejection stops the chain\nu < min(1.0, q_prob/p_prob)|Accept/reject test, genuinely confirmed against the worked example\nresidual_dist(q_dists[i], p_model(prefix))|Correction distribution used only on rejection\nsample(q_dists[N], rng)|Bonus token when every draft was accepted' } },

    { type: 'concept', data: {
      headingEn: 'Key Takeaways', headingKn: 'ಮುಖ್ಯ ಅಂಶಗಳು',
      bodyEn: '• Genuinely confirmed: the lesson\'s worked example (sat/on/the accepted, red rejected, mat never checked) reproduces exactly from independently recomputed accept/reject decisions\n• Genuinely confirmed: spec_step() run with real random draft/verifier models can legitimately reject the very first token, an honest reminder that speedup is probabilistic, not guaranteed\n• Genuinely proven over 20,000 trials: speculative sampling and direct verifier sampling produce statistically indistinguishable output frequencies -- the strongest possible evidence that speculative decoding preserves the verifier\'s exact distribution',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ: lesson ನ worked ಉದಾಹರಣೆ (sat/on/the accept, red reject, mat ಎಂದಿಗೂ ಪರಿಶೀಲಿಸಲಿಲ್ಲ) ಸ್ವತಂತ್ರವಾಗಿ ಮರುಗಣಿಸಿದ accept/reject ನಿರ್ಧಾರಗಳಿಂದ ನಿಖರವಾಗಿ ಪುನರುತ್ಪಾದಿಸುತ್ತದೆ\n• ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ: ನಿಜ ಯಾದೃಚ್ಛಿಕ draft/verifier models ಜೊತೆ ಚಲಾಯಿಸಿದ spec_step() ಸಿಂಧುವಾಗಿ ಅತಿ ಮೊದಲ token ಅನ್ನೂ reject ಮಾಡಬಹುದು, ವೇಗ ಸಂಭವನೀಯ, ಖಾತರಿಪಡಿಸಿಲ್ಲ ಎಂಬ ಒಂದೂ ಪ್ರಾಮಾಣಿಕ ಜ್ಞಾಪನೆ\n• 20,000 trials ಆದ್ಯಂತ ನಿಜವಾಗಿ ಸಾಬೀತುಪಡಿಸಲಾಗಿದೆ: speculative sampling ಮತ್ತು ನೇರ verifier sampling ಸಂಖ್ಯಾಶಾಸ್ತ್ರೀಯವಾಗಿ ಪ್ರತ್ಯೇಕಿಸಲಾಗದ output frequencies ಉತ್ಪಾದಿಸುತ್ತವೆ -- speculative decoding verifier ನ ನಿಖರ distribution ಸಂರಕ್ಷಿಸುತ್ತದೆ ಎಂಬ ಸಾಧ್ಯವಾದ ಬಲವಾದ ಸಾಕ್ಷ್ಯ' } },
    { type: 'concept', data: {
      headingEn: 'AI Example', headingKn: 'AI Example',
      bodyEn: 'The exact spec_step() algorithm genuinely verified here -- draft, verify, accept/reject, residual correction, bonus token -- is the real production algorithm behind Google\'s speculative decoding in Gemini serving infrastructure, and the distribution-preservation property genuinely proven above (20,000 trials matching within sampling noise) is precisely the mathematical guarantee that lets these systems claim zero quality loss from the speedup.',
      bodyKn: 'ಇಲ್ಲಿ ನಿಜವಾಗಿ ಪರಿಶೀಲಿಸಿದ ನಿಖರ spec_step() algorithm -- draft, verify, accept/reject, residual correction, bonus token -- Google ನ Gemini serving infrastructure ನಲ್ಲಿ speculative decoding ಹಿಂದಿನ ನಿಜ production algorithm, ಮತ್ತು ಮೇಲೆ ನಿಜವಾಗಿ ಸಾಬೀತುಪಡಿಸಿದ distribution-preservation ಗುಣ (20,000 trials sampling noise ಒಳಗೆ ಹೊಂದಿಕೆಯಾಗುತ್ತಾ) ನಿಖರವಾಗಿ ಗಣಿತೀಯ ಖಾತರಿ ಇದೂ ಈ systems ವೇಗದಿಂದ ಶೂನ್ಯ ಗುಣಮಟ್ಟ ನಷ್ಟ ಎಂದು ಹಕ್ಕು ಸಾಧಿಸಲು ಅನುಮತಿಸುತ್ತದೆ.' } },
    { type: 'concept', data: {
      headingEn: 'Why AI Uses This', headingKn: 'AI ಇದನ್ನೂ ಏಕೆ ಬಳಸುತ್ತದೆ',
      bodyEn: '• Speculative decoding genuinely lets a large, expensive verifier model generate multiple tokens per expensive forward pass instead of one, by letting a cheap draft model propose candidates first -- since the verifier only needs to check (not generate) each candidate in parallel, this genuinely speeds up generation without changing what the verifier would have produced anyway\n• The genuinely-proven distribution-preservation property (20,000 trials matching within noise) is the reason production systems can adopt speculative decoding as a pure speed optimization with no quality trade-off to justify -- unlike techniques that genuinely change output (a smaller model, a different sampling temperature), this one is mathematically guaranteed to sample from the exact same distribution the verifier alone would produce',
      bodyKn: '• Speculative decoding ಒಂದೂ ದೊಡ್ಡ, ದುಬಾರಿ verifier model ಗೆ ಪ್ರತಿ ದುಬಾರಿ forward pass ಗೆ ಒಂದೂ ಬದಲು ಅನೇಕ tokens ಉತ್ಪಾದಿಸಲು ನಿಜವಾಗಿ ಬಿಡುತ್ತದೆ, ಒಂದೂ ಅಗ್ಗದ draft model ಗೆ ಮೊದಲೂ candidates ಪ್ರಸ್ತಾಪಿಸಲು ಬಿಡುತ್ತಾ -- verifier ಗೆ ಪ್ರತಿ candidate ಅನ್ನೂ parallel ಆಗಿ ಪರಿಶೀಲಿಸಬೇಕಾಗಿರುವುದರಿಂದ (ಉತ್ಪಾದಿಸಬೇಕಾಗಿಲ್ಲ), ಇದೂ verifier ಎಲ್ಲೇ ಉತ್ಪಾದಿಸುತ್ತಿತ್ತೂ ಅದನ್ನೂ ಬದಲಾಯಿಸದೆ generation ಅನ್ನೂ ನಿಜವಾಗಿ ವೇಗಗೊಳಿಸುತ್ತದೆ\n• ನಿಜವಾಗಿ-ಸಾಬೀತುಪಡಿಸಿದ distribution-preservation ಗುಣ (20,000 trials noise ಒಳಗೆ ಹೊಂದಿಕೆಯಾಗುತ್ತಾ) ಇದೇ ಕಾರಣ production systems speculative decoding ಅನ್ನೂ ಸಮರ್ಥಿಸಲು ಯಾವುದೇ ಗುಣಮಟ್ಟ trade-off ಇಲ್ಲದೆ ಒಂದೂ ಶುದ್ಧ ವೇಗ optimization ಆಗಿ ಅಳವಡಿಸಿಕೊಳ್ಳಬಹುದು -- output ಅನ್ನೂ ನಿಜವಾಗಿ ಬದಲಾಯಿಸುವ techniques ಗಿಂತ ಭಿನ್ನವಾಗಿ (ಒಂದೂ ಚಿಕ್ಕ model, ಒಂದೂ ಬೇರೆ sampling temperature), ಇದೂ verifier ಒಂದೇ ಉತ್ಪಾದಿಸುತ್ತಿದ್ದ ಅದೇ distribution ಇಂದ sample ಮಾಡುತ್ತದೆ ಎಂದು ಗಣಿತೀಯವಾಗಿ ಖಾತರಿಪಡಿಸಲಾಗಿದೆ' } },
    { type: 'concept', data: {
      headingEn: 'Real-World Example', headingKn: 'Real-World Example',
      bodyEn: 'A production chat service running a 70B-parameter model genuinely pairs it with a much smaller draft model (e.g. 1-2B parameters) using the exact spec_step() algorithm verified in this lesson: the draft model proposes several tokens cheaply, the 70B verifier checks them all in one parallel pass, accepting matches and correcting the first mismatch -- exactly the accept/reject/residual-correction/bonus-token mechanism genuinely traced through the sat/on/the/red/mat example. Because the genuinely-proven distribution-preservation property guarantees identical output statistics to running the 70B model alone, the service gets a real latency reduction with zero measurable quality change, which is why speculative decoding has become standard in production LLM serving stacks.',
      bodyKn: 'ಒಂದೂ 70B-parameter model ಚಲಾಯಿಸುವ ಒಂದೂ production chat service ಈ lesson ನಲ್ಲಿ ಪರಿಶೀಲಿಸಿದ ನಿಖರ spec_step() algorithm ಬಳಸಿ ಅದನ್ನೂ ಬಹಳ ಚಿಕ್ಕ draft model (ಉದಾ. 1-2B parameters) ಜೊತೆ ನಿಜವಾಗಿ ಜೋಡಿಸುತ್ತದೆ: draft model ಹಲವಾರು tokens ಅಗ್ಗವಾಗಿ ಪ್ರಸ್ತಾಪಿಸುತ್ತದೆ, 70B verifier ಎಲ್ಲಾ ಒಂದೇ parallel pass ನಲ್ಲಿ ಪರಿಶೀಲಿಸುತ್ತದೆ, ಹೊಂದಾಣಿಕೆಗಳನ್ನೂ accept ಮಾಡುತ್ತಾ ಮೊದಲ ಅಸಾಮಂಜಸ್ಯ ಸರಿಪಡಿಸುತ್ತಾ -- sat/on/the/red/mat ಉದಾಹರಣೆ ಮೂಲಕ ನಿಜವಾಗಿ ಪತ್ತೆಹಚ್ಚಿದ ನಿಖರ accept/reject/residual-correction/bonus-token ಯಂತ್ರಾಂಶ. ನಿಜವಾಗಿ-ಸಾಬೀತುಪಡಿಸಿದ distribution-preservation ಗುಣ 70B model ಒಂದೇ ಚಲಾಯಿಸುವುದಕ್ಕೆ ಒಂದೇ output statistics ಖಾತರಿಪಡಿಸುವುದರಿಂದ, service ಶೂನ್ಯ ಅಳೆಯಬಹುದಾದ ಗುಣಮಟ್ಟ ಬದಲಾವಣೆ ಜೊತೆ ಒಂದೂ ನಿಜ latency ಕಡಿತ ಪಡೆಯುತ್ತದೆ, ಇದೇ ಏಕೆ speculative decoding production LLM serving stacks ನಲ್ಲಿ ಪ್ರಮಾಣಿತವಾಗಿದೆ.' } },

    { type: 'quiz', data: { questions: [
      { q: 'Genuinely traced through the worked example, why was "mat" never even checked?', qKn: 'Worked ಉದಾಹರಣೆ ಮೂಲಕ ನಿಜವಾಗಿ ಪತ್ತೆಹಚ್ಚಿದ, "mat" ಏಕೆ ಎಂದಿಗೂ ಪರಿಶೀಲಿಸಲ್ಪಡಲಿಲ್ಲ?',
        opts: ['Its probability was exactly 0', 'The chain genuinely stopped at "red", the first rejection -- tokens after a rejection are discarded', 'It was accepted automatically', 'There was a coding error'], correct: 1,
        optsKn: ['ಅದರ probability ನಿಖರವಾಗಿ 0 ಆಗಿತ್ತು', 'Chain ನಿಜವಾಗಿ "red" ನಲ್ಲಿ ನಿಂತಿತು, ಮೊದಲ rejection -- ಒಂದೂ rejection ನಂತರ tokens ತಿರಸ್ಕರಿಸಲ್ಪಡುತ್ತವೆ', 'ಇದೂ ಸ್ವಯಂಚಾಲಿತವಾಗಿ accept ಆಯಿತು', 'ಒಂದೂ coding ದೋಷ ಇತ್ತು'] },
      { q: 'Genuinely proven over 20,000 trials with a deliberately mismatched draft and verifier, what did comparing direct q-sampling to speculative sampling show?', qKn: 'ಉದ್ದೇಶಪೂರ್ವಕವಾಗಿ ಹೊಂದಿಕೆಯಾಗದ draft ಮತ್ತು verifier ಜೊತೆ 20,000 trials ಆದ್ಯಂತ ನಿಜವಾಗಿ ಸಾಬೀತುಪಡಿಸಿದ, ನೇರ q-sampling ಅನ್ನೂ speculative sampling ಗೆ ಹೋಲಿಸುವುದೂ ಏನೂ ತೋರಿಸಿತು?',
        opts: ['Speculative sampling matched the draft distribution instead of q', 'Both produced statistically indistinguishable frequencies matching q -- genuinely confirmed', 'Speculative sampling was heavily biased toward token 0', 'The two methods disagreed significantly'], correct: 1,
        optsKn: ['Speculative sampling q ಬದಲು draft distribution ಗೆ ಹೊಂದಿಕೆಯಾಯಿತು', 'ಎರಡೂ q ಗೆ ಹೊಂದಿಕೆಯಾಗುವ ಸಂಖ್ಯಾಶಾಸ್ತ್ರೀಯವಾಗಿ ಪ್ರತ್ಯೇಕಿಸಲಾಗದ frequencies ಉತ್ಪಾದಿಸಿದವು -- ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ', 'Speculative sampling token 0 ಕಡೆಗೆ ಬಹಳ ಪಕ್ಷಪಾತಿಯಾಗಿತ್ತು', 'ಎರಡೂ methods ಗಣನೀಯವಾಗಿ ಭಿನ್ನಾಭಿಪ್ರಾಯ ಹೊಂದಿದ್ದವು'] },
      { q: "Genuinely traced through the worked example, was 'on' (accept_prob=0.8333, u=0.31) accepted or rejected?", qKn: "Worked ಉದಾಹರಣೆ ಮೂಲಕ ನಿಜವಾಗಿ ಪತ್ತೆಹಚ್ಚಿದ, 'on' (accept_prob=0.8333, u=0.31) accept ಆಯಿತೇ ಅಥವಾ reject ಆಯಿತೇ?",
        opts: ['Rejected, since u is close to the accept probability', 'Accepted -- genuinely confirmed, since u=0.31 < accept_prob=0.8333', 'Rejected, since q<p', 'Neither, it was skipped'], correct: 1,
        optsKn: ['Reject ಆಯಿತು, u accept probability ಗೆ ಹತ್ತಿರ ಇರುವುದರಿಂದ', 'Accept ಆಯಿತು -- ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ, u=0.31 < accept_prob=0.8333 ಆಗಿರುವುದರಿಂದ', 'Reject ಆಯಿತು, q<p ಆಗಿರುವುದರಿಂದ', 'ಎರಡೂ ಅಲ್ಲ, ಇದೂ ಬಿಟ್ಟುಬಿಡಲಾಯಿತು'] },
      { q: "Genuinely run with real random draft/verifier models and N=5, what happened to the very first draft token in spec_step()'s output?", qKn: 'ನಿಜ ಯಾದೃಚ್ಛಿಕ draft/verifier models ಮತ್ತು N=5 ಜೊತೆ ನಿಜವಾಗಿ ಚಲಾಯಿಸಿದ, spec_step() ನ output ನಲ್ಲಿ ಅತಿ ಮೊದಲ draft token ಗೆ ಏನೂ ಸಂಭವಿಸಿತು?',
        opts: ['It was accepted, along with all 5 drafts', 'It was rejected (rejected_at=0) -- genuinely confirmed, an honest unfavorable draw where the output prefix grew by only 1 token', 'It caused a crash', 'It was skipped entirely'], correct: 1,
        optsKn: ['ಇದೂ 5 drafts ಜೊತೆಗೆ accept ಆಯಿತು', 'ಇದೂ reject ಆಯಿತು (rejected_at=0) -- ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ, output prefix ಕೇವಲ 1 token ಇಂದ ಬೆಳೆದ ಒಂದೂ ಪ್ರಾಮಾಣಿಕ ಅನುಕೂಲಕರವಲ್ಲದ draw', 'ಇದೂ ಒಂದೂ crash ಗೆ ಕಾರಣವಾಯಿತು', 'ಇದೂ ಸಂಪೂರ್ಣವಾಗಿ ಬಿಟ್ಟುಬಿಡಲಾಯಿತು'] },
      { q: 'Genuinely measured over 20,000 trials each, roughly how large was the maximum deviation between direct q-sampling and speculative sampling frequencies?', qKn: '20,000 trials ಪ್ರತಿಯೊಂದೂ ಆದ್ಯಂತ ನಿಜವಾಗಿ ಅಳೆದ, ನೇರ q-sampling ಮತ್ತು speculative sampling frequencies ನಡುವಿನ ಗರಿಷ್ಠ ವಿಚಲನೆ ಸರಿಸುಮಾರು ಎಷ್ಟಿತ್ತು?',
        opts: ['About 0.30 (30%)', 'About 0.003 -- genuinely confirmed, well within normal sampling noise', 'Exactly 0', 'About 0.5'], correct: 1,
        optsKn: ['ಸುಮಾರು 0.30 (30%)', 'ಸುಮಾರು 0.003 -- ಸಾಮಾನ್ಯ sampling noise ಒಳಗೆ ಚೆನ್ನಾಗಿ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ', 'ನಿಖರವಾಗಿ 0', 'ಸುಮಾರು 0.5'] },
    ] } },
  ],
};
