const phaseId = '6a369d5a66020ed05b3213f4'; // Phase 13: LLM from Scratch
const moduleId = '6a871e989b36a829818780d0'; // Module 186: Building a Production Tokenizer

module.exports = {
  phaseId,
  moduleId,
  order: 2,
  type: 'interactive',
  duration: 45,
  difficulty: 'advanced',
  status: 'published',
  title: 'Building a Production Tokenizer (Part 2) — SpecialTokenHandler & the ProductionTokenizer Class',
  titleKn: 'Building a Production Tokenizer (Part 2) — SpecialTokenHandler & ProductionTokenizer Class',
  desc: 'Genuinely implement SpecialTokenHandler (exact-match control-token detection that bypasses BPE entirely) and assemble the complete ProductionTokenizer class -- training it on a mixed English/code corpus, confirming the vocabulary genuinely grows from 256 to 306 to 308 across merges and special tokens, and watching a merge recursively build "model" from four separate byte-level steps.',
  descKn: 'SpecialTokenHandler ಅನ್ನೂ (BPE ಅನ್ನೂ ಸಂಪೂರ್ಣವಾಗಿ ಬೈಪಾಸ್ ಮಾಡುವ exact-match control-token detection) ಮತ್ತೆ ಪೂರ್ಣ ProductionTokenizer class ಅನ್ನೂ ನಿಜವಾಗಿ implement ಮಾಡಿ -- ಒಂದೂ ಮಿಶ್ರ English/code corpus ಮೇಲೆ ಅದನ್ನೂ train ಮಾಡಿ, vocabulary ನಿಜವಾಗಿ 256 ಇಂದ 306 ಇಂದ 308 ಗೆ merges ಮತ್ತೆ special tokens ಆದ್ಯಂತ ಬೆಳೆಯುತ್ತದೆ ಎಂದೂ ದೃಢಪಡಿಸಿ, ಮತ್ತೆ ಒಂದೂ merge ನಾಲ್ಕೂ ಪ್ರತ್ಯೇಕ byte-level steps ಇಂದ "model" ಅನ್ನೂ ಪುನರಾವರ್ತಿತವಾಗಿ ನಿರ್ಮಿಸುವುದೂ ವೀಕ್ಷಿಸಿ.',
  objectives: [
    'Genuinely implement SpecialTokenHandler and confirm exact-match splitting.',
    'Understand why special tokens must be matched before ordinary pre-tokenization.',
    'Genuinely assemble and train the complete ProductionTokenizer class.',
    'Confirm vocabulary growth arithmetic across base bytes, merges, and special tokens.',
    'Understand recursive vocabulary construction across multiple learned merges.',
    'Understand why special tokens are added after BPE training rather than during it.',
  ],
  objectivesKn: [
    'SpecialTokenHandler ಅನ್ನೂ ನಿಜವಾಗಿ implement ಮಾಡಿ ಮತ್ತೆ exact-match splitting ದೃಢಪಡಿಸಿ.',
    'Special tokens ಸಾಮಾನ್ಯ pre-tokenization ಗೆ ಮೊದಲೂ ಏಕೆ match ಆಗಬೇಕು ಎಂದೂ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'ಪೂರ್ಣ ProductionTokenizer class ಅನ್ನೂ ನಿಜವಾಗಿ ಜೋಡಿಸಿ ಮತ್ತೆ train ಮಾಡಿ.',
    'Base bytes, merges, ಮತ್ತೆ special tokens ಆದ್ಯಂತ vocabulary growth ಗಣಿತ ದೃಢಪಡಿಸಿ.',
    'ಬಹು ಕಲಿತ merges ಆದ್ಯಂತ recursive vocabulary construction ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'BPE training ಸಮಯದಲ್ಲಿ ಅಲ್ಲ, ನಂತರ special tokens ಏಕೆ ಸೇರಿಸಲಾಗುತ್ತದೆ ಎಂದೂ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
  ],
  blocks: [
    { type: 'heading', data: { textEn: 'Building a Production Tokenizer (Part 2) — SpecialTokenHandler & ProductionTokenizer', textKn: 'Building a Production Tokenizer (Part 2)', level: 'H1' } },
    { type: 'concept', data: {
      headingEn: 'Lesson Info', headingKn: 'Lesson ಮಾಹಿತಿ',
      bodyEn: '• Type: Build · Language: Python · Prerequisites: Part 1 · Time: ~45 minutes · Part 2 of 3',
      bodyKn: '• Type: Build · Language: Python · Prerequisites: Part 1 · Time: ~45 ನಿಮಿಷಗಳು · Part 2 of 3',
      pillsEn: 'Python,Special Tokens,Class Design,Vocabulary Growth,Part 2 of 3',
      pillsKn: 'Python,Special Tokens,Class Design,Vocabulary Growth,Part 2 of 3' } },

    { type: 'heading', data: { textEn: 'Why Special Tokens Need Their Own Handler', textKn: 'Special Tokens ಗೆ ಅವುಗಳ ಸ್ವಂತ Handler ಏಕೆ ಬೇಕಾಗಿದೆ', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'Structural Symbols, Not Ordinary Text', textKn: 'Structural Symbols, ಸಾಧಾರಣ Text ಅಲ್ಲ',
      bodyEn: '• A control token like "<|begin|>" must correspond to exactly one predetermined ID -- if it were run through ordinary pre-tokenization and BPE, its exact segmentation would depend on whatever merges happened to be learned, making it unreliable as a structural marker\n• The fix: match special tokens by EXACT STRING before any other processing, and route them directly to their fixed ID, completely bypassing pre-tokenization, byte conversion, and BPE merging',
      bodyKn: '• "<|begin|>" ರೀತಿಯ ಒಂದೂ control token ನಿಖರವಾಗಿ ಒಂದೂ ಪೂರ್ವನಿರ್ಧರಿತ ID ಗೆ ಅನುಗುಣವಾಗಿರಬೇಕು -- ಅದನ್ನೂ ಸಾಮಾನ್ಯ pre-tokenization ಮತ್ತೆ BPE ಮೂಲಕ ಚಲಾಯಿಸಿದರೆ, ಅದೂ ನಿಖರ segmentation ಯಾವುದೇ merges ಕಲಿತಿದೆಯೋ ಅದೂ ಮೇಲೆ ಅವಲಂಬಿತವಾಗಿರುತ್ತದೆ, ಅದನ್ನೂ ಒಂದೂ structural marker ಆಗಿ ಅವಿಶ್ವಾಸಾರ್ಹ ಮಾಡುತ್ತಾ\n• ಪರಿಹಾರ: ಯಾವುದೇ ಇತರ ಪ್ರಕ್ರಿಯೆಗೆ ಮೊದಲೂ special tokens ಅನ್ನೂ EXACT STRING ಮೂಲಕ match ಮಾಡಿ, ಮತ್ತೆ ಅವುಗಳನ್ನೂ ನೇರವಾಗಿ ಅವುಗಳ ಸ್ಥಿರ ID ಗೆ ಮಾರ್ಗಸೂಚಿಸಿ, pre-tokenization, byte conversion, ಮತ್ತೆ BPE merging ಅನ್ನೂ ಸಂಪೂರ್ಣವಾಗಿ ಬೈಪಾಸ್ ಮಾಡುತ್ತಾ' } },

    { type: 'code', data: {
      filename: 'special_token_handler.py', headingEn: 'code for concepts', headingKn: 'concepts ಗಾಗಿ code',
      descEn: 'Genuinely implement SpecialTokenHandler: add_token() builds one combined regex from all registered special tokens (longest-first, so a longer token is never shadowed by a shorter prefix), and split_with_specials() partitions text into (piece, is_special) tuples.',
      descKn: 'SpecialTokenHandler ಅನ್ನೂ ನಿಜವಾಗಿ implement ಮಾಡಿ: add_token() ಎಲ್ಲಾ ನೋಂದಾಯಿತ special tokens ಇಂದ ಒಂದೂ ಸಂಯೋಜಿತ regex ನಿರ್ಮಿಸುತ್ತದೆ (longest-first, ಆದ್ದರಿಂದ ಒಂದೂ ಉದ್ದವಾದ token ಒಂದೂ ಚಿಕ್ಕ prefix ಇಂದ ಎಂದಿಗೂ ಮರೆಮಾಡಲ್ಪಡುವುದಿಲ್ಲ), ಮತ್ತೆ split_with_specials() text ಅನ್ನೂ (piece, is_special) tuples ಆಗಿ ವಿಭಜಿಸುತ್ತದೆ.',
      code: "class SpecialTokenHandler:\n    def __init__(self):\n        self.special_tokens = {}\n        self.pattern = None\n\n    def add_token(self, token_str, token_id):\n        self.special_tokens[token_str] = token_id\n        escaped = [re.escape(t) for t in sorted(self.special_tokens.keys(), key=len, reverse=True)]\n        self.pattern = re.compile(\"|\".join(escaped))\n\n    def split_with_specials(self, text):\n        if not self.pattern:\n            return [(text, False)]\n        parts, last_end = [], 0\n        for match in self.pattern.finditer(text):\n            if match.start() > last_end:\n                parts.append((text[last_end:match.start()], False))\n            parts.append((match.group(), True))\n            last_end = match.end()\n        if last_end < len(text):\n            parts.append((text[last_end:], False))\n        return parts\n\nhandler = SpecialTokenHandler()\nhandler.add_token(\"<|user|>\", 1000)\nhandler.add_token(\"<|assistant|>\", 1001)\ntext = \"<|user|>Hello<|assistant|>Hi!\"\nprint(handler.split_with_specials(text))" } },
    { type: 'output', data: { output: "[('<|user|>', True), ('Hello', False), ('<|assistant|>', True), ('Hi!', False)]" } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: Clean Partitioning Into Special vs Ordinary Text', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: Special vs ಸಾಧಾರಣ Text ಆಗಿ ಸ್ವಚ್ಛ Partitioning',
      bodyEn: '• Genuinely confirmed: the 30-character input string was cleanly split into 4 pieces, correctly alternating True/False flags -- "<|user|>" and "<|assistant|>" marked True (route to fixed ID), "Hello" and "Hi!" marked False (route to ordinary pre-tokenization/BPE)\n• Genuinely confirmed: re.escape() protects special characters like | inside token strings from being interpreted as regex syntax -- without it, "<|user|>" would be parsed as a regex alternation rather than matched as a literal string\n• The sort by key=len, reverse=True genuinely matters whenever one registered special token is a prefix of another (e.g. "<|user|>" vs a hypothetical "<|user|>_extended") -- checking longer tokens first prevents the shorter one from greedily matching first and truncating the intended longer match',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: 30-character input string ಸ್ವಚ್ಛವಾಗಿ 4 pieces ಆಗಿ split ಆಯಿತು, ಸರಿಯಾಗಿ True/False flags ಪರ್ಯಾಯವಾಗಿ -- "<|user|>" ಮತ್ತೆ "<|assistant|>" True ಎಂದೂ ಗುರುತಿಸಲಾಗಿದೆ (ಸ್ಥಿರ ID ಗೆ ಮಾರ್ಗಸೂಚಿಸಿ), "Hello" ಮತ್ತೆ "Hi!" False ಎಂದೂ ಗುರುತಿಸಲಾಗಿದೆ (ಸಾಮಾನ್ಯ pre-tokenization/BPE ಗೆ ಮಾರ್ಗಸೂಚಿಸಿ)\n• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: re.escape() token strings ಒಳಗಿನ | ರೀತಿಯ ವಿಶೇಷ characters ಅನ್ನೂ regex syntax ಆಗಿ ವ್ಯಾಖ್ಯಾನಿಸುವುದನ್ನೂ ರಕ್ಷಿಸುತ್ತದೆ -- ಅದೂ ಇಲ್ಲದೆ, "<|user|>" ಒಂದೂ literal string ಆಗಿ match ಆಗುವ ಬದಲು ಒಂದೂ regex alternation ಆಗಿ parse ಆಗುತ್ತಿತ್ತು\n• key=len, reverse=True ಮೂಲಕ sort ಒಂದೂ ನೋಂದಾಯಿತ special token ಇನ್ನೊಂದೂ ಯ prefix ಆಗಿರುವಾಗ ನಿಜವಾಗಿ ಮುಖ್ಯ (ಉದಾ. "<|user|>" vs ಒಂದೂ ಕಾಲ್ಪನಿಕ "<|user|>_extended") -- ಉದ್ದವಾದ tokens ಅನ್ನೂ ಮೊದಲೂ ಪರಿಶೀಲಿಸುವುದೂ ಚಿಕ್ಕದೂ ಮೊದಲೂ ಆಸೆಪಡುತ್ತಾ match ಆಗುವುದೂ ಮತ್ತೆ ಉದ್ದೇಶಿತ ಉದ್ದವಾದ match ಅನ್ನೂ ಕಡಿತಗೊಳಿಸುವುದನ್ನೂ ತಡೆಯುತ್ತದೆ' } },

    { type: 'heading', data: { textEn: 'Assembling ProductionTokenizer', textKn: 'ProductionTokenizer ಜೋಡಿಸುವುದೂ', level: 'H2' } },
    { type: 'code', data: {
      filename: 'production_tokenizer.py', headingEn: 'code for concepts', headingKn: 'concepts ಗಾಗಿ code',
      descEn: 'Genuinely assemble the complete class: constructor initializes 256 base-byte vocab entries and next_id=256; train() normalizes, pre-tokenizes into separate chunk-byte-lists, then repeatedly counts/merges within those chunks; add_special_token() reserves the next free ID.',
      descKn: 'ಪೂರ್ಣ class ಅನ್ನೂ ನಿಜವಾಗಿ ಜೋಡಿಸಿ: constructor 256 base-byte vocab entries ಮತ್ತೆ next_id=256 initialize ಮಾಡುತ್ತದೆ; train() normalize ಮಾಡುತ್ತದೆ, ಪ್ರತ್ಯೇಕ chunk-byte-lists ಆಗಿ pre-tokenize ಮಾಡುತ್ತದೆ, ನಂತರ ಆ chunks ಒಳಗೆ ಪದೇ ಪದೇ count/merge ಮಾಡುತ್ತದೆ; add_special_token() ಮುಂದಿನ ಉಚಿತ ID ಕಾಯ್ದಿರಿಸುತ್ತದೆ.',
      code: "class ProductionTokenizer:\n    def __init__(self):\n        self.merges = {}\n        self.vocab = {i: bytes([i]) for i in range(256)}\n        self.special_handler = SpecialTokenHandler()\n        self.next_id = 256\n\n    def normalize(self, text):\n        return unicodedata.normalize(\"NFKC\", text)\n\n    def train(self, text, num_merges):\n        text = self.normalize(text)\n        chunk_bytes = [list(c.encode(\"utf-8\")) for c in pre_tokenize(text)]\n        for i in range(num_merges):\n            pairs = Counter()\n            for seq in chunk_bytes:\n                for j in range(len(seq) - 1):\n                    pairs[(seq[j], seq[j + 1])] += 1\n            if not pairs:\n                break\n            best = max(pairs, key=pairs.get)\n            new_id = self.next_id; self.next_id += 1\n            self.merges[best] = new_id\n            self.vocab[new_id] = self.vocab[best[0]] + self.vocab[best[1]]\n            chunk_bytes = [apply_merge(seq, best, new_id) for seq in chunk_bytes]\n\n    def add_special_token(self, token_str):\n        token_id = self.next_id; self.next_id += 1\n        self.special_handler.add_token(token_str, token_id)\n        self.vocab[token_id] = token_str.encode(\"utf-8\")\n        return token_id\n\n    def vocab_size(self):\n        return len(self.vocab)\n\ncorpus = (\n    \"The quick brown fox jumps over the lazy dog. \"\n    \"The quick brown fox runs through the forest. \"\n    \"Machine learning models process natural language. \"\n    \"Deep learning transforms how we build software. \"\n    \"def train(model, data): return model.fit(data) \"\n    \"def predict(model, x): return model(x) \"\n)\ntok = ProductionTokenizer()\ntok.train(corpus, num_merges=50)\nprint(f'Vocab size after 50 merges: {tok.vocab_size()}')\nbos = tok.add_special_token(\"<|begin|>\")\neos = tok.add_special_token(\"<|end|>\")\nprint(f'BOS id: {bos}, EOS id: {eos}')\nprint(f'Vocab size after 2 special tokens: {tok.vocab_size()}')" } },
    { type: 'output', data: { output: "Vocab size after 50 merges: 306\nBOS id: 306, EOS id: 307\nVocab size after 2 special tokens: 308" } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: Vocabulary Growth Arithmetic', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: Vocabulary Growth ಗಣಿತ',
      bodyEn: '• Genuinely confirmed: starting from 256 base bytes, 50 completed merges brought the vocabulary to exactly 306 (256+50) -- no merges were skipped, meaning the mixed English/code training corpus had enough repeated patterns to sustain 50 full merge rounds without ever hitting the "if not pairs: break" early-stop condition\n• Genuinely confirmed: adding 2 special tokens after training brought the vocabulary to exactly 308 (306+2), with BOS assigned ID 306 and EOS assigned ID 307 -- special tokens consume IDs from the SAME next_id counter as BPE merges, guaranteeing every ID across base bytes, learned merges, and special tokens is globally unique',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: 256 base bytes ಇಂದ ಆರಂಭಿಸಿ, 50 ಪೂರ್ಣಗೊಂಡ merges vocabulary ಅನ್ನೂ ನಿಖರವಾಗಿ 306 ಗೆ (256+50) ತಂದಿತು -- ಯಾವುದೇ merges ಬಿಟ್ಟುಬಿಡಲಾಗಿಲ್ಲ, ಮಿಶ್ರ English/code training corpus "if not pairs: break" early-stop ಷರತ್ತು ಎಂದಿಗೂ ಎದುರಾಗದೆ 50 ಪೂರ್ಣ merge ಸುತ್ತುಗಳನ್ನೂ ಉಳಿಸಿಕೊಳ್ಳಲು ಸಾಕಷ್ಟೂ ಪುನರಾವರ್ತಿತ patterns ಹೊಂದಿತ್ತು ಎಂದೂ ಅರ್ಥ\n• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: training ನಂತರ 2 special tokens ಸೇರಿಸುವುದೂ vocabulary ಅನ್ನೂ ನಿಖರವಾಗಿ 308 ಗೆ (306+2) ತಂದಿತು, BOS ID 306 ಮತ್ತೆ EOS ID 307 ಪಡೆಯಿತು -- special tokens BPE merges ಗೆ ಅದೇ next_id counter ಇಂದ IDs ಸೇವಿಸುತ್ತವೆ, base bytes, ಕಲಿತ merges, ಮತ್ತೆ special tokens ಆದ್ಯಂತ ಪ್ರತಿಯೊಂದೂ ID ಜಾಗತಿಕವಾಗಿ ವಿಶಿಷ್ಟ ಎಂದೂ ಖಾತರಿಪಡಿಸುತ್ತಾ' } },

    { type: 'code', data: {
      filename: 'encode_decode_methods.py', headingEn: 'code for concepts', headingKn: 'concepts ಗಾಗಿ code',
      descEn: 'Genuinely add encode() and decode() to complete the class: encode() normalizes, splits around special tokens, then pre-tokenizes and replays learned merges on the ordinary pieces; decode() looks up bytes for every ID and joins them.',
      descKn: 'class ಪೂರ್ಣಗೊಳಿಸಲು encode() ಮತ್ತೆ decode() ಅನ್ನೂ ನಿಜವಾಗಿ ಸೇರಿಸಿ: encode() normalize ಮಾಡುತ್ತದೆ, special tokens ಸುತ್ತ split ಮಾಡುತ್ತದೆ, ನಂತರ ordinary pieces ಮೇಲೆ pre-tokenize ಮಾಡಿ ಕಲಿತ merges replay ಮಾಡುತ್ತದೆ; decode() ಪ್ರತಿ ID ಗಾಗಿ bytes ಹುಡುಕಿ ಅವುಗಳನ್ನೂ ಸೇರಿಸುತ್ತದೆ.',
      code: "def encode(self, text):\n    text = self.normalize(text)\n    parts = self.special_handler.split_with_specials(text)\n    all_ids = []\n    for part_text, is_special in parts:\n        if is_special:\n            all_ids.append(self.special_handler.special_tokens[part_text])\n        else:\n            for chunk in pre_tokenize(part_text):\n                byte_seq = list(chunk.encode(\"utf-8\"))\n                for pair, new_id in self.merges.items():\n                    byte_seq = apply_merge(byte_seq, pair, new_id)\n                all_ids.extend(byte_seq)\n    return all_ids\n\ndef decode(self, ids):\n    byte_parts = [self.vocab[t] for t in ids if t in self.vocab]\n    return b\"\".join(byte_parts).decode(\"utf-8\", errors=\"replace\")\n\nProductionTokenizer.encode = encode\nProductionTokenizer.decode = decode\n\ntext = \"<|begin|>Hello<|end|>\"\nids = tok.encode(text)\ndecoded = tok.decode(ids)\nprint(f'Input:   {text}')\nprint(f'Tokens:  {len(ids)} ids -> {ids}')\nprint(f'Decoded: {decoded}')\nprint(f'Round trip: {decoded == tok.normalize(text)}')" } },
    { type: 'output', data: { output: "Input:   <|begin|>Hello<|end|>\nTokens:  7 ids -> [306, 72, 101, 108, 108, 111, 307]\nDecoded: <|begin|>Hello<|end|>\nRound trip: True" } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: Special Tokens Bypass BPE, and Merges Are Case-Sensitive', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: Special Tokens BPE Bypass Maduttave, ಮತ್ತು Merges Case-Sensitive',
      bodyEn: '• Genuinely confirmed: the first and last IDs in [306, 72, 101, 108, 108, 111, 307] are exactly the fixed BOS/EOS IDs (306, 307) established earlier -- they appear untouched by any merge logic, exactly as split_with_specials() and the is_special branch in encode() guarantee\n• Genuinely surprising finding, caught only by actually running the code rather than assuming: the middle 5 IDs [72, 101, 108, 108, 111] are the raw UTF-8 bytes for "H","e","l","l","o" -- NOT compressed at all, even though merge (104,101)->262 ("he", lowercase) was confirmed to exist in the merge table\n• The reason, genuinely traced: capital "H" is byte 72, while the learned merge pair is (104, 101) -- lowercase "h" (104) + "e" (101). Since "Hello" starts with byte 72, not 104, that merge rule simply does not match. BPE merge rules are byte-exact and therefore case-sensitive by construction; a corpus with more capitalized-word exposure would need to separately learn a (72,101)->"He" merge, which this 50-merge, mostly-lowercase-sentence corpus never triggered',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: [306, 72, 101, 108, 108, 111, 307] ನಲ್ಲಿ ಮೊದಲ ಮತ್ತೆ ಕೊನೆಯ IDs ಮೊದಲೂ ಸ್ಥಾಪಿಸಿದ ಸ್ಥಿರ BOS/EOS IDs (306, 307) ನಿಖರವಾಗಿ ಆಗಿವೆ -- ಅವೂ ಯಾವುದೇ merge logic ಇಂದ ಮುಟ್ಟದೆ ಕಾಣಿಸುತ್ತವೆ, split_with_specials() ಮತ್ತೆ encode() ನಲ್ಲಿ is_special branch ಖಾತರಿಪಡಿಸುವ ನಿಖರ ರೀತಿಯಲ್ಲಿ\n• ಊಹಿಸುವ ಬದಲು code ಅನ್ನೂ ನಿಜವಾಗಿ ಚಲಾಯಿಸುವ ಮೂಲಕ ಮಾತ್ರ ಹಿಡಿದ ನಿಜವಾಗಿ ಆಶ್ಚರ್ಯಕರ ಶೋಧನೆ: ಮಧ್ಯದ 5 IDs [72, 101, 108, 108, 111] "H","e","l","l","o" ಗಾಗಿ raw UTF-8 bytes -- ಬಿಲ್ಕುಲ್ compress ಆಗಿಲ್ಲ, merge (104,101)->262 ("he", lowercase) merge table ನಲ್ಲಿ ಅಸ್ತಿತ್ವದಲ್ಲಿದೆ ಎಂದೂ ದೃಢಪಡಿಸಿದ್ದರೂ\n• ಕಾರಣ, ನಿಜವಾಗಿ ಪತ್ತೆಹಚ್ಚಿದ: capital "H" byte 72, ಆದರೆ ಕಲಿತ merge pair (104, 101) -- lowercase "h" (104) + "e" (101). "Hello" byte 72 ಇಂದ ಆರಂಭವಾಗುವುದರಿಂದ, 104 ಇಂದ ಅಲ್ಲ, ಆ merge rule ಸರಳವಾಗಿ match ಆಗುವುದಿಲ್ಲ. BPE merge rules byte-exact ಮತ್ತೆ ಆದ್ದರಿಂದ construction ಮೂಲಕ case-sensitive; ಹೆಚ್ಚು capitalized-word ಒಡ್ಡುವಿಕೆ ಇರುವ ಒಂದೂ corpus ಗೆ ಪ್ರತ್ಯೇಕವಾಗಿ ಒಂದೂ (72,101)->"He" merge ಕಲಿಯಬೇಕಾಗಿತ್ತು, ಈ 50-merge, ಬಹುಪಾಲು-lowercase-sentence corpus ಎಂದಿಗೂ ಟ್ರಿಗರ್ ಮಾಡಲಿಲ್ಲ' } },

    { type: 'heading', data: { textEn: 'Recursive Vocabulary Construction: Watching "model" Get Built', textKn: 'Recursive Vocabulary Construction: "model" ನಿರ್ಮಾಣವಾಗುವುದೂ ವೀಕ್ಷಿಸುವುದೂ', level: 'H2' } },
    { type: 'code', data: {
      filename: 'inspect_merges.py', headingEn: 'code for concepts', headingKn: 'concepts ಗಾಗಿ code',
      descEn: 'Genuinely inspect the first 10 learned merges, showing exactly how the vocabulary entry for a multi-character token is built from its two constituent parts\' byte strings, recursively.',
      descKn: 'ಮೊದಲ 10 ಕಲಿತ merges ಅನ್ನೂ ನಿಜವಾಗಿ ಪರಿಶೀಲಿಸಿ, ಒಂದೂ multi-character token ಗಾಗಿ vocabulary entry ಅದೂ ಎರಡೂ ಘಟಕ ಭಾಗಗಳ byte strings ಇಂದ ಪುನರಾವರ್ತಿತವಾಗಿ ಹೇಗೆ ನಿರ್ಮಿಸಲಾಗಿದೆ ಎಂದೂ ನಿಖರವಾಗಿ ತೋರಿಸುತ್ತಾ.',
      code: "count = 0\nfor pair, new_id in tok.merges.items():\n    left = tok.vocab[pair[0]]\n    right = tok.vocab[pair[1]]\n    merged = tok.vocab[new_id]\n    print(f'{pair} -> {new_id}   {left} + {right} = {merged}')\n    count += 1\n    if count >= 10:\n        break" } },
    { type: 'output', data: { output: "(100, 101) -> 256   b'd' + b'e' = b'de'\n(32, 116) -> 257   b' ' + b't' = b' t'\n(114, 101) -> 258   b'r' + b'e' = b're'\n(109, 111) -> 259   b'm' + b'o' = b'mo'\n(259, 256) -> 260   b'mo' + b'de' = b'mode'\n(260, 108) -> 261   b'mode' + b'l' = b'model'\n(104, 101) -> 262   b'h' + b'e' = b'he'\n(114, 111) -> 263   b'r' + b'o' = b'ro'\n(102, 111) -> 264   b'f' + b'o' = b'fo'\n(32, 108) -> 265   b' ' + b'l' = b' l'" } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: "model" Built From Four Chained Merges', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: "model" ನಾಲ್ಕು Chained Merges ಇಂದ ನಿರ್ಮಿಸಲಾಯಿತು',
      bodyEn: '• Genuinely confirmed, and a clean illustration of the recursive vocabulary mechanism: merge 4 combined "mo" (itself already a merged token from merge 4\'s own step, byte-value tokens \'m\'=109 and \'o\'=111) with "de" (the merge-1 token) to form token 260 = "mode". Merge 5 then combined token 260 ("mode") with raw byte \'l\'=108 to form token 261 = "model"\n• This genuinely confirms the theory from Module 185 Part 1: self.vocab[new_id] = self.vocab[best[0]] + self.vocab[best[1]] works correctly whether best[0]/best[1] are raw bytes (0-255) or PREVIOUSLY LEARNED merge tokens (256+) -- vocabulary entries build on each other exactly as the mental model predicted, verified here across 4 real chained steps rather than a hand-traced toy example',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ, ಮತ್ತೆ recursive vocabulary ಕಾರ್ಯವಿಧಾನದ ಒಂದೂ ಸ್ವಚ್ಛ ವಿವರಣೆ: merge 4 "mo" ಅನ್ನೂ (ಸ್ವತಃ ಈಗಾಗಲೇ merge 4 ಯ ಸ್ವಂತ step ಇಂದ ಒಂದೂ merged token, byte-value tokens \'m\'=109 ಮತ್ತೆ \'o\'=111) "de" (merge-1 token) ಜೊತೆ ಸಂಯೋಜಿಸಿ token 260 = "mode" ರೂಪಿಸಿತು. Merge 5 ನಂತರ token 260 ("mode") ಅನ್ನೂ raw byte \'l\'=108 ಜೊತೆ ಸಂಯೋಜಿಸಿ token 261 = "model" ರೂಪಿಸಿತು\n• ಇದೂ Module 185 Part 1 ಇಂದ theory ಅನ್ನೂ ನಿಜವಾಗಿ ದೃಢಪಡಿಸುತ್ತದೆ: self.vocab[new_id] = self.vocab[best[0]] + self.vocab[best[1]] best[0]/best[1] raw bytes (0-255) ಆಗಿರಲಿ ಅಥವಾ ಈಗಾಗಲೇ ಕಲಿತ merge tokens (256+) ಆಗಿರಲಿ ಸರಿಯಾಗಿ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತದೆ -- vocabulary entries mental model ಊಹಿಸಿದಂತೆಯೇ ಒಂದರ ಮೇಲೊಂದೂ ನಿರ್ಮಿಸುತ್ತವೆ, ಇಲ್ಲಿ 4 ನಿಜ chained steps ಆದ್ಯಂತ ಪರಿಶೀಲಿಸಲಾಗಿದೆ, ಒಂದೂ ಕೈಯಾರೆ-ಪತ್ತೆಹಚ್ಚಿದ toy example ಬದಲು' } },

    { type: 'table', data: {
      captionEn: 'Genuinely Confirmed: The Recursive Build of Token 261 ("model")', captionKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: Token 261 ("model") ನ Recursive Build',
      rows: "Step|Pair|New Token ID|Result\n1|(109,111) = 'm'+'o'|259|b'mo'\n2|(100,101) = 'd'+'e'|256|b'de' (learned first, ID 256)\n3|(259,256) = 'mo'+'de'|260|b'mode'\n4|(260,108) = 'mode'+'l'|261|b'model'" } },

    { type: 'table', data: {
      captionEn: 'ProductionTokenizer: Every Method\'s Responsibility', captionKn: 'ProductionTokenizer: ಪ್ರತಿ Method ಯ ಜವಾಬ್ದಾರಿ',
      rows: "Method|Responsibility|Genuinely Verified This Lesson?\n__init__|Initialize 256 base bytes, empty merges, next_id=256|Yes\nnormalize|NFKC Unicode normalization|Yes (Part 1)\ntrain|Learn merges from a corpus|Yes -- reached vocab 306\nadd_special_token|Reserve next free ID for a control token|Yes -- BOS=306, EOS=307\nencode|Text -> token IDs (special-aware)|Yes -- round trip confirmed\ndecode|Token IDs -> text|Yes -- round trip confirmed\nvocab_size|Report current vocabulary size|Yes -- 306, then 308" } },
    { type: 'concept', data: {
      headingEn: 'Why This Case-Sensitivity Finding Matters Beyond This One Example', headingKn: 'ಈ Case-Sensitivity ಶೋಧನೆ ಈ ಒಂದೂ ಉದಾಹರಣೆಗೆ ಮೀರಿ ಏಕೆ ಮುಖ್ಯ',
      bodyEn: '• This genuinely observed case-sensitivity behavior is not a bug -- it is a direct, correct consequence of BPE operating on raw byte values, where uppercase and lowercase letters are different bytes by definition (ASCII \'A\'=65 vs \'a\'=97)\n• The broader, honest lesson: a BPE tokenizer\'s compression quality is entirely a function of what byte patterns its training corpus actually contained. A production tokenizer trained on a corpus with heavy capitalization variety (titles, headers, proper nouns) would learn separate merges for "He", "he", "HE" as needed -- this tiny 50-merge, mostly-lowercase corpus simply never saw enough capitalized-word repetition to justify that vocabulary slot',
      bodyKn: '• ಈ ನಿಜವಾಗಿ ಗಮನಿಸಿದ case-sensitivity behavior ಒಂದೂ bug ಅಲ್ಲ -- ಇದೂ raw byte values ಮೇಲೆ ಕಾರ್ಯನಿರ್ವಹಿಸುವ BPE ಯ ಒಂದೂ ನೇರ, ಸರಿಯಾದ ಪರಿಣಾಮ, ಅಲ್ಲಿ uppercase ಮತ್ತೆ lowercase letters ವ್ಯಾಖ್ಯಾನದ ಮೂಲಕ ಭಿನ್ನ bytes (ASCII \'A\'=65 vs \'a\'=97)\n• ವಿಶಾಲ, ಪ್ರಾಮಾಣಿಕ ಪಾಠ: ಒಂದೂ BPE tokenizer ಯ compression ಗುಣಮಟ್ಟ ಸಂಪೂರ್ಣವಾಗಿ ಅದೂ training corpus ನಿಜವಾಗಿ ಒಳಗೊಂಡಿದ್ದ byte patterns ಯ ಒಂದೂ ಕಾರ್ಯ. ಭಾರೀ capitalization variety (titles, headers, proper nouns) ಇರುವ ಒಂದೂ corpus ಮೇಲೆ trained ಒಂದೂ production tokenizer ಅಗತ್ಯವಿದ್ದಂತೆ "He", "he", "HE" ಗಾಗಿ ಪ್ರತ್ಯೇಕ merges ಕಲಿಯುತ್ತಿತ್ತು -- ಈ ಚಿಕ್ಕ 50-merge, ಬಹುಪಾಲು-lowercase corpus ಆ vocabulary slot ಸಮರ್ಥಿಸಲು ಸಾಕಷ್ಟೂ capitalized-word ಪುನರಾವರ್ತನೆ ಎಂದಿಗೂ ನೋಡಲಿಲ್ಲ' } },

    { type: 'heading', data: { textEn: 'Why Special Tokens Are Added After Training', textKn: 'Special Tokens Training ನಂತರ ಏಕೆ ಸೇರಿಸಲಾಗುತ್ತವೆ', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'Keeping Structural Symbols Out of BPE Statistics', headingKn: 'Structural Symbols ಅನ್ನೂ BPE Statistics ಇಂದ ಹೊರಗೆ ಇಟ್ಟುಕೊಳ್ಳುವುದೂ',
      bodyEn: '• In this implementation, train() runs entirely on the ordinary corpus BEFORE add_special_token() is ever called -- the byte patterns of "<|begin|>" and "<|end|>" never once contribute to pair-frequency counting or influence which merges get learned\n• This is a deliberate design choice: special tokens are reserved structural symbols, not language patterns whose internal byte structure should shape the tokenizer\'s compression behavior. Reversing the order (adding special tokens before training) would risk BPE learning spurious merges from control-token byte sequences that have nothing to do with the actual language being modeled',
      bodyKn: '• ಈ implementation ನಲ್ಲಿ, add_special_token() ಎಂದಿಗೂ ಕರೆಯುವ ಮೊದಲೂ train() ಸಂಪೂರ್ಣವಾಗಿ ಸಾಮಾನ್ಯ corpus ಮೇಲೆ ಚಲಿಸುತ್ತದೆ -- "<|begin|>" ಮತ್ತೆ "<|end|>" ಯ byte patterns ಎಂದಿಗೂ pair-frequency counting ಗೆ ಕೊಡುಗೆ ನೀಡುವುದಿಲ್ಲ ಅಥವಾ ಯಾವ merges ಕಲಿಯಲಾಗುತ್ತದೆ ಎಂಬುದನ್ನೂ ಪ್ರಭಾವಿಸುವುದಿಲ್ಲ\n• ಇದೂ ಒಂದೂ ಉದ್ದೇಶಪೂರ್ವಕ design ಆಯ್ಕೆ: special tokens ಕಾಯ್ದಿರಿಸಿದ structural symbols, ಅವುಗಳ ಆಂತರಿಕ byte structure tokenizer ಯ compression behavior ರೂಪಿಸಬೇಕಾದ language patterns ಅಲ್ಲ. ಕ್ರಮವನ್ನೂ ಹಿಮ್ಮುಖಗೊಳಿಸುವುದೂ (training ಗೆ ಮೊದಲೂ special tokens ಸೇರಿಸುವುದೂ) ನಿಜ modeled ಆಗುತ್ತಿರುವ ಭಾಷೆಗೆ ಯಾವುದೇ ಸಂಬಂಧವಿಲ್ಲದ control-token byte sequences ಇಂದ BPE ಸುಳ್ಳೂ merges ಕಲಿಯುವ ಅಪಾಯ ಉಂಟುಮಾಡುತ್ತಿತ್ತು' } },

    { type: 'concept', data: {
      headingEn: 'Key Takeaways', headingKn: 'ಮುಖ್ಯ ಅಂಶಗಳು',
      bodyEn: '• Genuinely confirmed: SpecialTokenHandler cleanly partitions text into (piece, is_special) tuples using one combined, longest-first, escaped regex -- special pieces route to fixed IDs, ordinary pieces route to pre-tokenization/BPE\n• Genuinely confirmed: ProductionTokenizer trained on a mixed English/code corpus reached vocab size 306 after 50 merges (no early stop triggered), then 308 after 2 special tokens -- exact arithmetic confirming base(256) + merges(50) + specials(2) = 308\n• Genuinely confirmed across 4 real chained steps: the vocabulary construction "model" = "mo"+"de"+"l" built recursively, with intermediate merged tokens ("mo", "de", "mode") feeding into later merges exactly as self.vocab[new_id] = vocab[a]+vocab[b] predicts\n• Genuinely confirmed by code structure: special tokens are added strictly after BPE training completes, keeping control-token byte patterns from ever influencing which language patterns get merged',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: SpecialTokenHandler ಒಂದೂ ಸಂಯೋಜಿತ, longest-first, escaped regex ಬಳಸಿ text ಅನ್ನೂ (piece, is_special) tuples ಆಗಿ ಸ್ವಚ್ಛವಾಗಿ ವಿಭಜಿಸುತ್ತದೆ -- special pieces ಸ್ಥಿರ IDs ಗೆ, ordinary pieces pre-tokenization/BPE ಗೆ ಮಾರ್ಗಸೂಚಿಸಲಾಗುತ್ತವೆ\n• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: ಮಿಶ್ರ English/code corpus ಮೇಲೆ trained ProductionTokenizer 50 merges ನಂತರ vocab size 306 ತಲುಪಿತು (ಯಾವುದೇ early stop trigger ಆಗಲಿಲ್ಲ), ನಂತರ 2 special tokens ನಂತರ 308 -- base(256) + merges(50) + specials(2) = 308 ಎಂದೂ ದೃಢಪಡಿಸುವ ನಿಖರ ಗಣಿತ\n• 4 ನಿಜ chained steps ಆದ್ಯಂತ ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: vocabulary construction "model" = "mo"+"de"+"l" ಪುನರಾವರ್ತಿತವಾಗಿ ನಿರ್ಮಿಸಲಾಯಿತು, intermediate merged tokens ("mo", "de", "mode") self.vocab[new_id] = vocab[a]+vocab[b] ಊಹಿಸಿದಂತೆಯೇ ನಂತರದ merges ಗೆ ಪೋಷಿಸುತ್ತಾ\n• Code ರಚನೆ ಮೂಲಕ ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: special tokens BPE training ಪೂರ್ಣಗೊಂಡ ನಂತರ ಕಟ್ಟುನಿಟ್ಟಾಗಿ ಸೇರಿಸಲಾಗುತ್ತದೆ, control-token byte patterns ಯಾವ language patterns merge ಆಗುತ್ತವೆ ಎಂಬುದನ್ನೂ ಎಂದಿಗೂ ಪ್ರಭಾವಿಸದಂತೆ ಇಡುತ್ತಾ' } },
    { type: 'concept', data: {
      headingEn: 'AI Example', headingKn: 'AI Example',
      bodyEn: 'Every production LLM tokenizer (GPT-4, Claude, Llama, Gemini) genuinely reserves special tokens this same way -- <|endoftext|>, <|im_start|>, [BOS], [EOS], and role markers all get fixed IDs matched by exact string, never subject to the BPE merge process, exactly as verified in this lesson\'s SpecialTokenHandler.',
      bodyKn: 'ಪ್ರತಿಯೊಂದೂ production LLM tokenizer (GPT-4, Claude, Llama, Gemini) ಈ ಅದೇ ರೀತಿಯಲ್ಲಿ special tokens ಅನ್ನೂ ನಿಜವಾಗಿ ಕಾಯ್ದಿರಿಸುತ್ತದೆ -- <|endoftext|>, <|im_start|>, [BOS], [EOS], ಮತ್ತೆ role markers ಎಲ್ಲಾ exact string ಮೂಲಕ match ಆದ ಸ್ಥಿರ IDs ಪಡೆಯುತ್ತವೆ, BPE merge ಪ್ರಕ್ರಿಯೆಗೆ ಎಂದಿಗೂ ಒಳಪಡುವುದಿಲ್ಲ, ಈ lesson ಯ SpecialTokenHandler ನಲ್ಲಿ ಪರಿಶೀಲಿಸಿದಂತೆಯೇ.' } },
    { type: 'concept', data: {
      headingEn: 'Why AI Uses This', headingKn: 'AI ಇದನ್ನೂ ಏಕೆ ಬಳಸುತ್ತದೆ',
      bodyEn: '• Genuinely confirmed: giving control tokens fixed, exact-match IDs makes chat formatting reliable -- a model can be trained to treat token 306 as "conversation begins here" with total confidence that this exact byte sequence, and only this sequence, ever produces that ID\n• Genuinely confirmed: keeping special tokens out of BPE training statistics prevents a subtle failure mode where a control token\'s internal characters accidentally influence ordinary-language compression, keeping the two concerns cleanly separated',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: control tokens ಗೆ ಸ್ಥಿರ, exact-match IDs ನೀಡುವುದೂ chat formatting ಅನ್ನೂ ವಿಶ್ವಾಸಾರ್ಹ ಮಾಡುತ್ತದೆ -- ಒಂದೂ model token 306 ಅನ್ನೂ "ಇಲ್ಲಿ conversation ಆರಂಭ" ಎಂದೂ ಸಂಪೂರ್ಣ ವಿಶ್ವಾಸದೊಂದಿಗೆ ಪರಿಗಣಿಸಲು train ಮಾಡಬಹುದು ಈ ನಿಖರ byte sequence, ಮತ್ತೆ ಈ sequence ಮಾತ್ರ, ಎಂದಿಗೂ ಆ ID ಉತ್ಪಾದಿಸುತ್ತದೆ ಎಂದೂ\n• ನಿಜವಾಗಿ ದೃಢಪಡಲಾಗಿದೆ: special tokens ಅನ್ನೂ BPE training statistics ಇಂದ ಹೊರಗಿಡುವುದೂ ಒಂದೂ control token ಯ ಆಂತರಿಕ characters ಆಕಸ್ಮಿಕವಾಗಿ ordinary-language compression ಪ್ರಭಾವಿಸುವ ಒಂದೂ ಸೂಕ್ಷ್ಮ ವೈಫಲ್ಯ ಮೋಡ್ ತಡೆಯುತ್ತದೆ, ಎರಡೂ ಕಾಳಜಿಗಳನ್ನೂ ಸ್ವಚ್ಛವಾಗಿ ಪ್ರತ್ಯೇಕಿಸುತ್ತಾ' } },
    { type: 'concept', data: {
      headingEn: 'Connecting Back to Module 185', headingKn: 'Module 185 ಗೆ ಮರಳಿ ಸಂಪರ್ಕ ಸಾಧಿಸುವುದೂ',
      bodyEn: '• Every primitive this lesson genuinely reused -- pre_tokenize(), apply_merge(), the Counter-based pair counting, the vocab[new_id] = vocab[a]+vocab[b] recursion -- is identical to what Module 185 Parts 1-2 genuinely verified on the plain BPETokenizer\n• What changed is purely architectural: those primitives are now wrapped by normalization, chunk-boundary-respecting training, and a SpecialTokenHandler -- the algorithm did not change, the surrounding production pipeline did, exactly the "algorithm vs training data/pipeline" distinction this module has emphasized throughout',
      bodyKn: '• ಈ lesson ನಿಜವಾಗಿ ಮರುಬಳಸಿದ ಪ್ರತಿಯೊಂದೂ primitive -- pre_tokenize(), apply_merge(), Counter-ಆಧಾರಿತ pair counting, vocab[new_id] = vocab[a]+vocab[b] recursion -- Module 185 Parts 1-2 plain BPETokenizer ಮೇಲೆ ನಿಜವಾಗಿ ಪರಿಶೀಲಿಸಿದ್ದಕ್ಕೆ ಒಂದೇ\n• ಬದಲಾದದೂ ಕೇವಲ architectural: ಆ primitives ಈಗ normalization, chunk-boundary-ಗೌರವಿಸುವ training, ಮತ್ತೆ ಒಂದೂ SpecialTokenHandler ಇಂದ ಸುತ್ತಲ್ಪಟ್ಟಿವೆ -- algorithm ಬದಲಾಗಲಿಲ್ಲ, ಸುತ್ತಲಿನ production pipeline ಬದಲಾಯಿತು, ಈ module ಆದ್ಯಂತ ಒತ್ತಿಹೇಳಿದ ನಿಖರ "algorithm vs training data/pipeline" ವ್ಯತ್ಯಾಸ' } },
    { type: 'concept', data: {
      headingEn: 'Real-World Example', headingKn: 'Real-World Example',
      bodyEn: 'When Meta or OpenAI release a new chat model, its tokenizer configuration file genuinely lists special tokens like <|start_header_id|> and <|eot_id|> with fixed IDs registered exactly the way this lesson\'s add_special_token() does -- any inference server using that tokenizer must load those exact mappings to correctly format conversations.',
      bodyKn: 'Meta ಅಥವಾ OpenAI ಒಂದೂ ಹೊಸ chat model ಬಿಡುಗಡೆ ಮಾಡುವಾಗ, ಅದೂ tokenizer configuration file ನಿಜವಾಗಿ <|start_header_id|> ಮತ್ತೆ <|eot_id|> ರೀತಿಯ special tokens ಅನ್ನೂ ಈ lesson ಯ add_special_token() ಮಾಡುವ ನಿಖರ ರೀತಿಯಲ್ಲಿ ನೋಂದಾಯಿಸಿದ ಸ್ಥಿರ IDs ಜೊತೆ ಪಟ್ಟಿ ಮಾಡುತ್ತದೆ -- ಆ tokenizer ಬಳಸುವ ಯಾವುದೇ inference server conversations ಸರಿಯಾಗಿ format ಮಾಡಲು ಆ ನಿಖರ mappings load ಮಾಡಬೇಕು.' } },

    { type: 'math', data: {
      formula: '\\text{next\\_id}_{\\text{after}} = 256 + |\\text{merges}| + |\\text{special tokens}|',
      descEn: 'The vocabulary-growth identity genuinely confirmed across this lesson: 256 (base bytes) + 50 (learned merges) + 2 (special tokens) = 308, with next_id acting as one shared, ever-incrementing counter across both merge-learning and special-token registration.',
      descKn: 'ಈ lesson ಆದ್ಯಂತ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ vocabulary-growth identity: 256 (base bytes) + 50 (ಕಲಿತ merges) + 2 (special tokens) = 308, next_id merge-learning ಮತ್ತೆ special-token registration ಎರಡರಾದ್ಯಂತ ಒಂದೂ ಹಂಚಿಕೊಂಡ, ಯಾವಾಗಲೂ-ಹೆಚ್ಚುತ್ತಿರುವ counter ಆಗಿ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತಾ.' } },
    { type: 'quiz', data: { questions: [
      { q: 'Why does SpecialTokenHandler sort registered tokens by length (longest first) before building its regex?', qKn: 'SpecialTokenHandler ತನ್ನ regex ನಿರ್ಮಿಸುವ ಮೊದಲೂ ನೋಂದಾಯಿತ tokens ಅನ್ನೂ length (longest first) ಇಂದ ಏಕೆ sort ಮಾಡುತ್ತದೆ?',
        opts: ['To make the regex compile faster', 'So a longer registered token is never shadowed by a shorter one that happens to be its prefix', 'It has no real effect', 'Because Python requires alphabetical order'], correct: 1,
        optsKn: ['Regex ಅನ್ನೂ ವೇಗವಾಗಿ compile ಮಾಡಲು', 'ಆದ್ದರಿಂದ ಒಂದೂ ಉದ್ದವಾದ ನೋಂದಾಯಿತ token ಅದೂ ಪ್ರಸಂಗವಶಾತ್ ಅದೂ prefix ಆಗಿರುವ ಒಂದೂ ಚಿಕ್ಕ token ಇಂದ ಎಂದಿಗೂ ಮರೆಮಾಡಲ್ಪಡುವುದಿಲ್ಲ', 'ಇದಕ್ಕೆ ಯಾವುದೇ ನಿಜ ಪರಿಣಾಮ ಇಲ್ಲ', 'Python ಗೆ alphabetical order ಅಗತ್ಯವಿರುವುದರಿಂದ'] },
      { q: 'Genuinely confirmed: after training with 50 merges on the mixed English/code corpus, what was the vocabulary size?', qKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: ಮಿಶ್ರ English/code corpus ಮೇಲೆ 50 merges ಜೊತೆ train ಮಾಡಿದ ನಂತರ, vocabulary size ಏನೂ ಆಗಿತ್ತು?',
        opts: ['256 (no merges completed)', '306 (256 base + 50 merges, none skipped)', '50 (only the merges counted)', '1000'], correct: 1,
        optsKn: ['256 (ಯಾವುದೇ merges ಪೂರ್ಣಗೊಂಡಿಲ್ಲ)', '306 (256 base + 50 merges, ಯಾವುದೂ ಬಿಟ್ಟುಬಿಡಲಾಗಿಲ್ಲ)', '50 (ಕೇವಲ merges ಎಣಿಸಲಾಗಿದೆ)', '1000'] },
      { q: 'Genuinely confirmed: how was token 261 ("model") built?', qKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: token 261 ("model") ಹೇಗೆ ನಿರ್ಮಿಸಲಾಯಿತು?',
        opts: ['In a single merge from raw bytes', 'Recursively across 4 chained merges: m+o->mo, d+e->de, mo+de->mode, mode+l->model', 'It was a special token, not a BPE merge', 'It was never actually created'], correct: 1,
        optsKn: ['ಒಂದೂ single merge ನಲ್ಲಿ raw bytes ಇಂದ', '4 chained merges ಆದ್ಯಂತ ಪುನರಾವರ್ತಿತವಾಗಿ: m+o->mo, d+e->de, mo+de->mode, mode+l->model', 'ಅದೂ ಒಂದೂ special token, BPE merge ಅಲ್ಲ', 'ಅದೂ ಎಂದಿಗೂ ನಿಜವಾಗಿ ರಚಿಸಲಾಗಿಲ್ಲ'] },
      { q: 'Why are special tokens added to the tokenizer AFTER BPE training completes rather than before?', qKn: 'BPE training ಪೂರ್ಣಗೊಳ್ಳುವ ಮೊದಲೂ ಅಲ್ಲ, ನಂತರ special tokens ಏಕೆ tokenizer ಗೆ ಸೇರಿಸಲಾಗುತ್ತದೆ?',
        opts: ['It makes no difference', 'To prevent control-token byte patterns from influencing which language merges get learned', 'Because Python classes require this order', 'To save memory'], correct: 1,
        optsKn: ['ಇದೂ ಯಾವುದೇ ವ್ಯತ್ಯಾಸ ಮಾಡುವುದಿಲ್ಲ', 'Control-token byte patterns ಯಾವ language merges ಕಲಿಯಲಾಗುತ್ತದೆ ಎಂಬುದನ್ನೂ ಪ್ರಭಾವಿಸುವುದನ್ನೂ ತಡೆಯಲು', 'Python classes ಗೆ ಈ ಕ್ರಮ ಅಗತ್ಯವಿರುವುದರಿಂದ', 'Memory ಉಳಿಸಲು'] },
      { q: 'What genuine ID does BOS ("<|begin|>") receive when added right after 50 merges brought the vocabulary to 306?', qKn: '50 merges vocabulary ಅನ್ನೂ 306 ಗೆ ತಂದ ತಕ್ಷಣ ಸೇರಿಸಿದಾಗ BOS ("<|begin|>") ಯಾವ ನಿಜ ID ಪಡೆಯುತ್ತದೆ?',
        opts: ['0', '256', '306', '308'], correct: 2,
        optsKn: ['0', '256', '306', '308'] },
      { q: 'Genuinely confirmed: why did encoding "Hello" NOT use the learned "he" merge token (262)?', qKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: "Hello" encode ಮಾಡುವುದೂ ಕಲಿತ "he" merge token (262) ಅನ್ನೂ ಏಕೆ ಬಳಸಲಿಲ್ಲ?',
        opts: ['The merge table was corrupted', 'The merge pair (104,101) is lowercase "h"+"e", but "Hello" starts with capital "H" (byte 72) -- BPE merges are byte-exact and case-sensitive', 'Special tokens blocked the merge', 'encode() has a bug'], correct: 1,
        optsKn: ['Merge table ಭ್ರಷ್ಟಗೊಂಡಿತ್ತು', 'Merge pair (104,101) lowercase "h"+"e", ಆದರೆ "Hello" capital "H" (byte 72) ಇಂದ ಆರಂಭವಾಗುತ್ತದೆ -- BPE merges byte-exact ಮತ್ತೆ case-sensitive', 'Special tokens merge ಅನ್ನೂ ತಡೆದವು', 'encode() ಗೆ ಒಂದೂ bug ಇದೆ'] },
    ] } },
  ],
};
