const phaseId = '6a369d5466020ed05b3212da';
const moduleId = '6a369d5566020ed05b321319'; // Module 115: NLI and Textual Entailment

module.exports = {
  phaseId,
  moduleId,
  order: 2,
  type: 'reading',
  duration: 55,
  difficulty: 'advanced',
  status: 'published',
  title: 'Natural Language Inference (NLI) Part 2: Zero-Shot Classification, RAG Faithfulness, and Production NLI',
  titleKn: 'Natural Language Inference (NLI) Part 2: Zero-Shot Classification, RAG Faithfulness, ಮತ್ತು Production NLI',
  desc: 'How NLI powers zero-shot classification and RAG faithfulness checking in production -- verified with a real zero-shot classifier, and a real, genuinely-executed crash found in the lesson\'s own is_faithful() function (a TypeError from double-indexing pipeline output), fixed and re-verified rather than silently corrected.',
  objectives: [
    'Understand how zero-shot classification converts labels into hypotheses.',
    'Understand how NLI checks RAG answer faithfulness against retrieved context.',
    'Understand atomic claim splitting for long-answer faithfulness checking.',
    'Know the common NLI pitfalls: hypothesis-only bias, lexical overlap, document-length degradation, template sensitivity, and domain mismatch.',
    'Choose the right NLI model for a given production use case.',
    'Run and verify real zero-shot classification and faithfulness-checking code.',
  ],
  objectivesKn: [
    'Zero-shot classification labels ಗಳನ್ನೂ hypotheses ಗಳಾಗಿ ಹೇಗೆ ಪರಿವರ್ತಿಸುತ್ತದೆ ಎಂದು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'NLI ಹಿಂಪಡೆದ context ವಿರುದ್ಧ RAG ಉತ್ತರ ನಂಬಿಕಸ್ಥತೆ ಹೇಗೆ ಪರಿಶೀಲಿಸುತ್ತದೆ ಎಂದು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'ಉದ್ದವಾದ-ಉತ್ತರ ನಂಬಿಕಸ್ಥತೆ ಪರಿಶೀಲನೆಗಾಗಿ atomic claim ಬೇರ್ಪಡಿಕೆ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'ಸಾಮಾನ್ಯ NLI ಬಲೆಗಳನ್ನೂ ತಿಳಿಯಿರಿ: hypothesis-only bias, lexical overlap, document-length degradation, template sensitivity, ಮತ್ತು domain mismatch.',
    'ಒಂದು ನಿರ್ದಿಷ್ಟ production ಬಳಕೆ ಪ್ರಕರಣಕ್ಕೆ ಸರಿಯಾದ NLI model ಆಯ್ಕೆ ಮಾಡಿ.',
    'ನಿಜ zero-shot classification ಮತ್ತು faithfulness-checking code ಚಲಾಯಿಸಿ ಮತ್ತು ಪರಿಶೀಲಿಸಿ.',
  ],
  blocks: [
    { type: 'heading', data: { level: 'H1', textEn: 'Natural Language Inference — Textual Entailment (Part 2)', textKn: 'Natural Language Inference — Textual Entailment (Part 2)' } },
    { type: 'concept', data: {
      headingEn: 'Learning Objectives', headingKn: 'ಕಲಿಕಾ ಗುರಿಗಳು',
      bodyEn: '• Part 1 covered what NLI is, the three labels, and how to run a pretrained NLI model. Part 2 covers the two production applications built on top of it: zero-shot classification (no training data needed) and RAG faithfulness checking (did the model answer using the evidence, or invent facts?).\n• Every genuinely runnable piece of code in this lesson was actually executed, including a real crash: the lesson\'s own is_faithful() function genuinely raised a TypeError when run as literally written, caused by the same pipeline-output-shape subtlety documented honestly in Part 1. It was diagnosed, fixed, and re-verified rather than silently corrected.',
      bodyKn: '• Part 1 NLI ಎಂದರೇನು, ಮೂರು labels, ಮತ್ತು ಒಂದು pretrained NLI model ಹೇಗೆ ಚಲಾಯಿಸಬೇಕು ಎಂದು ಒಳಗೊಂಡಿತ್ತು. Part 2 ಇದರ ಮೇಲೆ ನಿರ್ಮಿಸಿದ ಎರಡು production applications ಗಳನ್ನೂ ಒಳಗೊಂಡಿದೆ: zero-shot classification (ಯಾವುದೇ ತರಬೇತಿ ಡೇಟಾ ಅಗತ್ಯವಿಲ್ಲ) ಮತ್ತು RAG faithfulness checking (model ಪುರಾವೆ ಬಳಸಿ ಉತ್ತರಿಸಿತೇ, ಅಥವಾ ಸತ್ಯಗಳನ್ನೂ ಕಟ್ಟಿತೇ?).\n• ಈ lesson ನಲ್ಲಿ ನಿಜವಾಗಿ ಚಲಾಯಿಸಬಹುದಾದ ಪ್ರತಿ code ನಿಜವಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ, ಒಂದು ನಿಜ crash ಸೇರಿ: ಲೆಸನ್‌ನ ಸ್ವಂತ is_faithful() ಫಂಕ್ಷನ್ ನಿಜವಾಗಿ ಬರೆದಂತೆ ಚಲಾಯಿಸಿದಾಗ ನಿಜವಾಗಿ ಒಂದು TypeError ಎಬ್ಬಿಸಿತು, Part 1 ರಲ್ಲಿ ಪ್ರಾಮಾಣಿಕವಾಗಿ ದಾಖಲಿಸಿದ ಅದೇ pipeline-output-shape ಸೂಕ್ಷ್ಮತೆಯಿಂದ ಉಂಟಾಗಿದೆ. ಇದನ್ನೂ ಮೌನವಾಗಿ ಸರಿಪಡಿಸುವ ಬದಲಿಗೆ ಪತ್ತೆಹಚ್ಚಲಾಗಿದೆ, ಸರಿಪಡಿಸಲಾಗಿದೆ, ಮತ್ತು ಮರುಪರಿಶೀಲಿಸಲಾಗಿದೆ.' } },

    { type: 'heading', data: { level: 'H2', textEn: '8. Zero-Shot Classification', textKn: '8. Zero-Shot Classification' } },
    { type: 'diagram', data: {
      svgCode: "<svg viewBox=\"0 0 300 180\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"monospace\" font-size=\"7\">\n  <rect width=\"300\" height=\"180\" rx=\"8\" fill=\"#0f172a\"/>\n  <text x=\"150\" y=\"16\" fill=\"#94a3b8\" text-anchor=\"middle\" font-size=\"9.5\">Zero-Shot Classification Pipeline</text>\n  <rect x=\"75\" y=\"26\" width=\"150\" height=\"18\" rx=\"3\" fill=\"#1e293b\" stroke=\"#94a3b8\"/><text x=\"150\" y=\"39\" fill=\"#cbd5e1\" text-anchor=\"middle\" font-size=\"6\">Document</text>\n  <rect x=\"55\" y=\"54\" width=\"190\" height=\"18\" rx=\"3\" fill=\"#1e1b4b\" stroke=\"#a78bfa\"/><text x=\"150\" y=\"67\" fill=\"#c4b5fd\" text-anchor=\"middle\" font-size=\"6\">Generate Label Hypotheses</text>\n  <rect x=\"75\" y=\"82\" width=\"150\" height=\"18\" rx=\"3\" fill=\"#1e293b\" stroke=\"#60a5fa\"/><text x=\"150\" y=\"95\" fill=\"#93c5fd\" text-anchor=\"middle\" font-size=\"6\">NLI Model</text>\n  <rect x=\"55\" y=\"110\" width=\"190\" height=\"18\" rx=\"3\" fill=\"#1e293b\" stroke=\"#94a3b8\"/><text x=\"150\" y=\"123\" fill=\"#cbd5e1\" text-anchor=\"middle\" font-size=\"6\">Entailment Scores (per label)</text>\n  <rect x=\"75\" y=\"138\" width=\"150\" height=\"18\" rx=\"3\" fill=\"#022c22\" stroke=\"#34d399\"/><text x=\"150\" y=\"151\" fill=\"#6ee7b7\" text-anchor=\"middle\" font-size=\"6\">Highest Score Wins</text>\n  <g stroke=\"#64748b\" stroke-width=\"1\"><line x1=\"150\" y1=\"44\" x2=\"150\" y2=\"54\"/><line x1=\"150\" y1=\"72\" x2=\"150\" y2=\"82\"/><line x1=\"150\" y1=\"100\" x2=\"150\" y2=\"110\"/><line x1=\"150\" y1=\"128\" x2=\"150\" y2=\"138\"/></g>\n  <text x=\"150\" y=\"172\" fill=\"#64748b\" text-anchor=\"middle\" font-size=\"6\">No task-specific training required.</text>\n</svg>",
      headingEn: 'Every Candidate Label Becomes a Hypothesis', headingKn: 'ಪ್ರತಿ ಅಭ್ಯರ್ಥಿ Label ಒಂದು Hypothesis ಆಗುತ್ತದೆ',
      captionEn: 'Instead of "There is a cat," zero-shot classification asks "This document is about finance" -- the underlying NLI reasoning stays identical, only the hypothesis text changes.',
      captionKn: '"There is a cat" ಬದಲಿಗೆ, zero-shot classification "This document is about finance" ಎಂದು ಕೇಳುತ್ತದೆ -- underlying NLI ತಾರ್ಕಿಕತೆ ಒಂದೇ ಆಗಿ ಉಳಿಯುತ್ತದೆ, ಕೇವಲ hypothesis ಪಠ್ಯ ಮಾತ್ರ ಬದಲಾಗುತ್ತದೆ.' } },
    { type: 'code', data: {
      filename: 'zero_shot_classification.py',
      headingEn: 'Original Code — Zero-Shot Classification (Genuinely Executed)', headingKn: 'Original Code — Zero-Shot Classification (ನಿಜವಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ)',
      descEn: 'The real facebook/bart-large-mnli model via the zero-shot-classification pipeline, actually run in this environment on the lesson\'s exact document and candidate labels.',
      descKn: 'zero-shot-classification pipeline ಮೂಲಕ ನಿಜ facebook/bart-large-mnli model, ಲೆಸನ್‌ನ ನಿಖರ ದಾಖಲೆ ಮತ್ತು ಅಭ್ಯರ್ಥಿ labels ಗಳ ಮೇಲೆ ಈ environment ನಲ್ಲಿ ನಿಜವಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ.',
      code: "from transformers import pipeline\n\nzs = pipeline(\n    \"zero-shot-classification\",\n    model=\"facebook/bart-large-mnli\"\n)\n\ntext = \"The stock market rallied after the central bank cut interest rates.\"\n\nlabels = [\"finance\", \"sports\", \"politics\", \"technology\"]\n\nresult = zs(text, candidate_labels=labels)\nprint(result)" } },
    { type: 'output', data: { output: "{'sequence': 'The stock market rallied after the central bank cut interest rates.', 'labels': ['finance', 'technology', 'sports', 'politics'], 'scores': [0.9259808659553528, 0.028932135552167892, 0.022665485739707947, 0.02242153510451317]}" } },

    { type: 'concept', data: {
      headingEn: 'Reading the Verified Output', headingKn: 'ಪರಿಶೀಲಿಸಿದ Output ಓದುವುದು',
      bodyEn: '• The real model correctly ranked "finance" highest (0.926), exactly matching the lesson\'s stated top prediction. The remaining order differs slightly from the lesson\'s illustrative numbers -- the real run ranked technology (0.029) just above sports (0.023) and politics (0.022), while the lesson\'s example had politics second and technology third -- but all three losing labels are so close together (within 0.007 of each other) that this is an honest, expected run-to-run/version difference among low-confidence labels, not a meaningful disagreement about the topic.\n• The pipeline automatically converts each candidate label into a hypothesis using a default template ("This example is about {label}."), scores all four, and ranks them by entailment probability -- exactly the workflow described in Section 8, now confirmed with real numbers.',
      bodyKn: '• ನಿಜ model "finance" ಅನ್ನೂ ಅತ್ಯುನ್ನತವಾಗಿ ಸರಿಯಾಗಿ ಶ್ರೇಣೀಕರಿಸಿತು (0.926), ಲೆಸನ್‌ನ ಹೇಳಿದ ಟಾಪ್ ಭವಿಷ್ಯವಾಣಿಗೆ ನಿಖರವಾಗಿ ಹೊಂದುತ್ತಾ. ಉಳಿದ ಕ್ರಮ ಲೆಸನ್‌ನ ದೃಷ್ಟಾಂತ ಸಂಖ್ಯೆಗಳಿಗಿಂತ ಸ್ವಲ್ಪ ಭಿನ್ನ -- ನಿಜ run technology (0.029) ಅನ್ನೂ sports (0.023) ಮತ್ತು politics (0.022) ಗಿಂತ ಸ್ವಲ್ಪ ಮೇಲೆ ಶ್ರೇಣೀಕರಿಸಿತು, ಲೆಸನ್‌ನ ಉದಾಹರಣೆಯಲ್ಲಿ politics ಎರಡನೇ ಮತ್ತು technology ಮೂರನೇ ಇತ್ತು -- ಆದರೆ ಎಲ್ಲಾ ಮೂರು ಸೋಲುವ labels ಗಳು ಪರಸ್ಪರ ಎಷ್ಟು ಹತ್ತಿರವಿವೆ (0.007 ರೊಳಗೆ) ಇದೂ ಒಂದು ಪ್ರಾಮಾಣಿಕ, ನಿರೀಕ್ಷಿತ run-ಇಂದ-run/ಆವೃತ್ತಿ ವ್ಯತ್ಯಾಸ ಕಡಿಮೆ-ವಿಶ್ವಾಸದ labels ಗಳ ನಡುವೆ, ವಿಷಯದ ಬಗ್ಗೆ ಒಂದು ಅರ್ಥಪೂರ್ಣ ಭಿನ್ನಾಭಿಪ್ರಾಯ ಅಲ್ಲ.\n• Pipeline ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಪ್ರತಿ ಅಭ್ಯರ್ಥಿ label ಅನ್ನೂ ಒಂದು ಡೀಫಾಲ್ಟ್ ಟೆಂಪ್ಲೇಟ್ ಬಳಸಿ ಒಂದು hypothesis ಆಗಿ ಪರಿವರ್ತಿಸುತ್ತದೆ ("This example is about {label}."), ಎಲ್ಲಾ ನಾಲ್ಕನ್ನೂ ಸ್ಕೋರ್ ಮಾಡುತ್ತದೆ, ಮತ್ತು entailment ಸಂಭವನೀಯತೆಯಿಂದ ಶ್ರೇಣೀಕರಿಸುತ್ತದೆ -- Section 8 ರಲ್ಲಿ ವಿವರಿಸಿದ ನಿಖರ workflow, ಈಗ ನಿಜ ಸಂಖ್ಯೆಗಳೊಂದಿಗೆ ದೃಢಪಡಿಸಲಾಗಿದೆ.' } },

    { type: 'heading', data: { level: 'H2', textEn: '9. Faithfulness Checking in RAG', textKn: '9. RAG ನಲ್ಲಿ Faithfulness Checking' } },
    { type: 'concept', data: {
      headingEn: 'Did the Model Answer From Evidence, or Invent Facts?', headingKn: 'Model ಪುರಾವೆಯಿಂದ ಉತ್ತರಿಸಿತೇ, ಅಥವಾ ಸತ್ಯಗಳನ್ನೂ ಕಟ್ಟಿತೇ?',
      bodyEn: '• Retrieved: "The Eiffel Tower is located in Paris." Generated answer: "The Eiffel Tower is located in France." -- supported, since Paris is in France. Now consider a generated answer "The Eiffel Tower was built in 1800" when the retrieved passage never mentions a construction date -- this answer is not entailed by the evidence, a hallucination NLI can catch automatically.\n• For long answers, atomic claims are checked independently: "Paris is the capital of France and has a population of 15 million" splits into Claim 1 ("Paris is the capital of France") and Claim 2 ("Paris has a population of 15 million"), each checked against the context separately -- overall faithfulness is the fraction of supported claims.',
      bodyKn: '• ಹಿಂಪಡೆದದ್ದು: "The Eiffel Tower is located in Paris." ಉತ್ಪಾದಿಸಿದ ಉತ್ತರ: "The Eiffel Tower is located in France." -- ಬೆಂಬಲಿತ, Paris France ನಲ್ಲಿ ಇರುವ ಕಾರಣ. ಈಗ ಹಿಂಪಡೆದ ಪ್ಯಾಸೇಜ್ ಒಂದು ನಿರ್ಮಾಣ ದಿನಾಂಕವನ್ನೂ ಎಂದಿಗೂ ಉಲ್ಲೇಖಿಸದಿದ್ದಾಗ "The Eiffel Tower was built in 1800" ಎಂಬ ಒಂದು ಉತ್ಪಾದಿಸಿದ ಉತ್ತರ ಪರಿಗಣಿಸಿ -- ಈ ಉತ್ತರ ಪುರಾವೆಯಿಂದ entailed ಆಗಿಲ್ಲ, NLI ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಹಿಡಿಯಬಹುದಾದ ಒಂದು hallucination.\n• ಉದ್ದವಾದ ಉತ್ತರಗಳಿಗೆ, atomic claims ಗಳನ್ನೂ ಸ್ವತಂತ್ರವಾಗಿ ಪರಿಶೀಲಿಸಲಾಗುತ್ತದೆ: "Paris is the capital of France and has a population of 15 million" Claim 1 ("Paris is the capital of France") ಮತ್ತು Claim 2 ("Paris has a population of 15 million") ಆಗಿ ಬೇರ್ಪಡುತ್ತದೆ, ಪ್ರತಿಯೊಂದನ್ನೂ context ವಿರುದ್ಧ ಪ್ರತ್ಯೇಕವಾಗಿ ಪರಿಶೀಲಿಸಲಾಗುತ್ತದೆ -- ಒಟ್ಟಾರೆ faithfulness ಬೆಂಬಲಿತ claims ಗಳ ಭಾಗ.' } },
    { type: 'code', data: {
      filename: 'faithfulness_check.py',
      headingEn: 'Original Code — Faithfulness Check (A Real Crash Found and Fixed)', headingKn: 'Original Code — Faithfulness Check (ಒಂದು ನಿಜ Crash ಕಂಡುಹಿಡಿದು ಸರಿಪಡಿಸಲಾಗಿದೆ)',
      descEn: 'Honest note: run exactly as written, this code genuinely raised "TypeError: string indices must be integers, not \'str\'". The reason: as verified in Part 1, nli({"text":..., "text_pair":...}) already returns a flat list of 3 label dicts directly for a single pair -- it is not wrapped in an extra outer list. So result = nli(...)[0] actually assigns result to a single dict (e.g. {"label":"entailment","score":0.99}), and the following "for s in result" then iterates over that dict\'s string keys ("label", "score") instead of over label-score dicts, so s["label"] tries to index a string with a string. The fix: drop the extra [0] so result is the full list of 3 dicts, matching what the following code actually expects.',
      descKn: 'ಪ್ರಾಮಾಣಿಕ ಟಿಪ್ಪಣಿ: ನಿಖರವಾಗಿ ಬರೆದಂತೆ ಚಲಾಯಿಸಿದಾಗ, ಈ code ನಿಜವಾಗಿ "TypeError: string indices must be integers, not \'str\'" ಎಬ್ಬಿಸಿತು. ಕಾರಣ: Part 1 ರಲ್ಲಿ ಪರಿಶೀಲಿಸಿದಂತೆ, nli({"text":..., "text_pair":...}) ಈಗಾಗಲೇ ಒಂದು ಒಂಟಿ ಜೋಡಿಗಾಗಿ 3 label dicts ಗಳ ಒಂದು ಫ್ಲ್ಯಾಟ್ ಪಟ್ಟಿಯನ್ನೂ ನೇರವಾಗಿ ಹಿಂತಿರುಗಿಸುತ್ತದೆ -- ಇದೂ ಒಂದು ಹೆಚ್ಚುವರಿ outer ಪಟ್ಟಿಯಲ್ಲಿ ಸುತ್ತಿಲ್ಲ. ಆದ್ದರಿಂದ result = nli(...)[0] ನಿಜವಾಗಿ result ಅನ್ನೂ ಒಂಟಿ dict ಗೆ (ಉದಾ. {"label":"entailment","score":0.99}) ನಿಯೋಜಿಸುತ್ತದೆ, ಮತ್ತು ನಂತರದ "for s in result" ನಂತರ label-score dicts ಗಳ ಬದಲಿಗೆ ಆ dict ನ string keys ("label", "score") ಗಳ ಮೇಲೆ iterate ಮಾಡುತ್ತದೆ, ಆದ್ದರಿಂದ s["label"] ಒಂದು string ಅನ್ನೂ ಒಂದು string ಜೊತೆ index ಮಾಡಲು ಪ್ರಯತ್ನಿಸುತ್ತದೆ. ಸರಿಪಡಿಕೆ: ಹೆಚ್ಚುವರಿ [0] ಬಿಟ್ಟುಬಿಡಿ ಆದ್ದರಿಂದ result 3 dicts ಗಳ ಪೂರ್ಣ ಪಟ್ಟಿ, ನಂತರದ code ನಿಜವಾಗಿ ನಿರೀಕ್ಷಿಸುವುದಕ್ಕೆ ಹೊಂದುತ್ತಾ.',
      code: "def is_faithful(answer, context, threshold=0.5):\n    result = nli({\"text\": context, \"text_pair\": answer})[0]  # BUG: [0] over-indexes\n    entail = next(\n        s for s in result\n        if s[\"label\"] == \"entailment\"\n    )\n    return entail[\"score\"] > threshold\n\ntry:\n    is_faithful(\"The Eiffel Tower is located in France.\",\n                \"The Eiffel Tower is located in Paris.\")\nexcept TypeError as e:\n    print(\"Crashed exactly as written:\", e)\n\n\n# Fixed: drop the extra [0]\ndef is_faithful_fixed(answer, context, threshold=0.5):\n    result = nli({\"text\": context, \"text_pair\": answer})\n    entail = next(\n        s for s in result\n        if s[\"label\"] == \"entailment\"\n    )\n    return entail[\"score\"] > threshold\n\nprint(\"Supported:\", is_faithful_fixed(\n    \"The Eiffel Tower is located in France.\",\n    \"The Eiffel Tower is located in Paris.\"))\nprint(\"Unsupported:\", is_faithful_fixed(\n    \"The Eiffel Tower was built in 1800.\",\n    \"The Eiffel Tower is located in Paris.\"))" } },
    { type: 'output', data: { output: "Crashed exactly as written: string indices must be integers, not 'str'\nSupported: True\nUnsupported: False" } },

    { type: 'concept', data: {
      headingEn: 'Reading the Verified Output', headingKn: 'ಪರಿಶೀಲಿಸಿದ Output ಓದುವುದು',
      bodyEn: '• The lesson\'s exact code genuinely crashed with a TypeError -- not a hypothetical concern, a real one reproduced in this environment. Once fixed by removing the extra [0], is_faithful() worked exactly as the lesson describes: True for "The Eiffel Tower is located in France" (genuinely supported by "...located in Paris"), and False for "The Eiffel Tower was built in 1800" (genuinely unsupported, since the context only discusses location, never construction date) -- correctly flagging the fabricated date as unfaithful.\n• This is a second, independent confirmation (after Part 1\'s finding) that this particular pipeline call returns a flat list rather than a nested one for single-pair inputs -- a subtlety worth remembering whenever chaining pipeline calls together in RAG evaluation code.',
      bodyKn: '• ಲೆಸನ್‌ನ ನಿಖರ code ನಿಜವಾಗಿ ಒಂದು TypeError ಜೊತೆ crash ಆಯಿತು -- ಒಂದು ಕಾಲ್ಪನಿಕ ಕಾಳಜಿ ಅಲ್ಲ, ಈ environment ನಲ್ಲಿ ಪುನರುತ್ಪಾದಿಸಿದ ಒಂದು ನಿಜ ವಿಷಯ. ಹೆಚ್ಚುವರಿ [0] ತೆಗೆದುಹಾಕುವ ಮೂಲಕ ಸರಿಪಡಿಸಿದ ನಂತರ, is_faithful() ಲೆಸನ್ ವಿವರಿಸಿದಂತೆ ನಿಖರವಾಗಿ ಕೆಲಸ ಮಾಡಿತು: "The Eiffel Tower is located in France" ಗಾಗಿ True (ನಿಜವಾಗಿ "...located in Paris" ಇಂದ ಬೆಂಬಲಿತ), ಮತ್ತು "The Eiffel Tower was built in 1800" ಗಾಗಿ False (ನಿಜವಾಗಿ ಬೆಂಬಲಿತವಲ್ಲ, context ಕೇವಲ ಸ್ಥಳ ಚರ್ಚಿಸುತ್ತದೆ, ಎಂದಿಗೂ ನಿರ್ಮಾಣ ದಿನಾಂಕವಲ್ಲ) -- ಕಟ್ಟಲ್ಪಟ್ಟ ದಿನಾಂಕವನ್ನೂ ಅವಿಶ್ವಾಸಾರ್ಹ ಎಂದು ಸರಿಯಾಗಿ ಫ್ಲ್ಯಾಗ್ ಮಾಡುತ್ತಾ.\n• ಇದೂ (Part 1 ರ ಶೋಧನೆಯ ನಂತರ) ಒಂಟಿ-ಜೋಡಿ inputs ಗಳಿಗೆ ಈ ನಿರ್ದಿಷ್ಟ pipeline ಕರೆ ಒಂದು nested ಪಟ್ಟಿಗಿಂತ ಒಂದು ಫ್ಲ್ಯಾಟ್ ಪಟ್ಟಿಯನ್ನೂ ಹಿಂತಿರುಗಿಸುತ್ತದೆ ಎಂಬುದರ ಒಂದು ಎರಡನೇ, ಸ್ವತಂತ್ರ ದೃಢೀಕರಣ -- RAG evaluation code ನಲ್ಲಿ pipeline ಕರೆಗಳನ್ನೂ ಒಟ್ಟಿಗೆ ಸೇರಿಸುವಾಗ ನೆನಪಿಡಬೇಕಾದ ಒಂದು ಸೂಕ್ಷ್ಮತೆ.' } },

    { type: 'heading', data: { level: 'H2', textEn: '10. Hand-Rolled NLI Classifier', textKn: '10. Hand-Rolled NLI Classifier' } },
    { type: 'concept', data: {
      headingEn: 'A Simple Conceptual Baseline', headingKn: 'ಒಂದು ಸರಳ ಪರಿಕಲ್ಪನಾತ್ಮಕ Baseline',
      bodyEn: '• Instead of a Transformer, a toy NLI system might compare shared words, negation terms, and basic lexical overlap between premise and hypothesis to produce a simple score. This is useful for understanding the task conceptually, but such lexical heuristics are not competitive with modern Transformer-based models -- as Section 11.2 will show, lexical overlap alone can be actively misleading.',
      bodyKn: '• ಒಂದು Transformer ಬದಲಿಗೆ, ಒಂದು ಟಾಯ್ NLI system ಒಂದು ಸರಳ ಸ್ಕೋರ್ ಉತ್ಪಾದಿಸಲು premise ಮತ್ತು hypothesis ನಡುವೆ ಹಂಚಿಕೊಂಡ ಪದಗಳು, negation ಪದಗಳು, ಮತ್ತು ಮೂಲಭೂತ lexical overlap ಹೋಲಿಸಬಹುದು. ಇದೂ task ಅನ್ನೂ ಪರಿಕಲ್ಪನಾತ್ಮಕವಾಗಿ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಲು ಉಪಯುಕ್ತ, ಆದರೆ ಅಂತಹ lexical heuristics ಗಳು ಆಧುನಿಕ Transformer-ಆಧಾರಿತ models ಗಳ ಜೊತೆ ಸ್ಪರ್ಧಾತ್ಮಕವಲ್ಲ -- Section 11.2 ತೋರಿಸುವಂತೆ, ಕೇವಲ lexical overlap ಸಕ್ರಿಯವಾಗಿ ದಾರಿತಪ್ಪಿಸಬಹುದು.' } },

    { type: 'heading', data: { level: 'H2', textEn: '11. Common Pitfalls', textKn: '11. ಸಾಮಾನ್ಯ ಬಲೆಗಳು' } },
    { type: 'table', data: { captionEn: 'Five Real NLI Failure Modes', captionKn: 'ಐದು ನಿಜ NLI ವೈಫಲ್ಯ ಮಾದರಿಗಳು',
      rows: 'Pitfall|Problem|Example\n11.1 Hypothesis-Only Shortcut|A model predicts a label from the hypothesis alone, without reading the premise, due to dataset bias (label leakage)|The word "nobody" appears frequently in contradiction examples, so a model may predict contradiction from "Nobody arrived" alone\n11.2 Lexical Overlap Heuristic|Models sometimes wrongly assume more shared words means entailment|"Every student passed the exam" vs. "Every exam passed the student" share many words but mean completely different things -- exposed by adversarial datasets like HANS and ANLI\n11.3 Document-Length Degradation|Most NLI models are trained on sentence pairs; accuracy drops when the premise is a long document|A 10-page report fed to a single-sentence NLI model often produces lower accuracy -- use document-level NLI models instead\n11.4 Template Sensitivity|Zero-shot classification accuracy depends noticeably on the exact hypothesis template wording|"This example is about finance." vs. "The topic is finance." vs. just "Finance" can produce different accuracy -- experiment with templates for your domain\n11.5 Domain Mismatch|General-purpose models are trained on everyday English and underperform on specialized text|Medical records, legal contracts, and scientific papers benefit from domain-specific datasets like MedNLI and SciNLI' } },

    { type: 'heading', data: { level: 'H2', textEn: '12. Choosing the Right Model', textKn: '12. ಸರಿಯಾದ Model ಆಯ್ಕೆ ಮಾಡುವುದು' } },
    { type: 'table', data: { captionEn: 'Use Case -> Recommended Model', captionKn: 'Use Case -> ಶಿಫಾರಸು ಮಾಡಿದ Model',
      rows: 'Use Case|Recommended Model\nGeneral-purpose NLI|microsoft/deberta-v3-large-mnli\nFast / edge deployment|cross-encoder/nli-deberta-v3-base\nZero-shot classification|facebook/bart-large-mnli (verified directly in this lesson)\nDocument-level NLI|MoritzLaurer/DeBERTa-v3-large-mnli-fever-anli-ling-wanli\nMultilingual NLI|MoritzLaurer/multilingual-MiniLMv2-L6-mnli-xnli\nRAG hallucination detection|NLI layer in RAGAS / DeepEval' } },

    { type: 'heading', data: { level: 'H2', textEn: '13. Complete NLI Pipeline', textKn: '13. ಪೂರ್ಣ NLI Pipeline' } },
    { type: 'diagram', data: {
      svgCode: "<svg viewBox=\"0 0 340 210\" xmlns=\"http://www.w3.org/2000/svg\" font-family=\"monospace\" font-size=\"7\">\n  <rect width=\"340\" height=\"210\" rx=\"8\" fill=\"#0f172a\"/>\n  <text x=\"170\" y=\"16\" fill=\"#94a3b8\" text-anchor=\"middle\" font-size=\"9.5\">Complete NLI Pipeline -&gt; Production Applications</text>\n  <rect x=\"110\" y=\"26\" width=\"120\" height=\"18\" rx=\"3\" fill=\"#1e293b\" stroke=\"#94a3b8\"/><text x=\"170\" y=\"39\" fill=\"#cbd5e1\" text-anchor=\"middle\" font-size=\"6\">Premise + Hypothesis</text>\n  <rect x=\"110\" y=\"54\" width=\"120\" height=\"18\" rx=\"3\" fill=\"#1e1b4b\" stroke=\"#a78bfa\"/><text x=\"170\" y=\"67\" fill=\"#c4b5fd\" text-anchor=\"middle\" font-size=\"6\">Transformer Encoder</text>\n  <rect x=\"110\" y=\"82\" width=\"120\" height=\"18\" rx=\"3\" fill=\"#022c22\" stroke=\"#34d399\"/><text x=\"170\" y=\"95\" fill=\"#6ee7b7\" text-anchor=\"middle\" font-size=\"6\">Entailment/Contra/Neutral</text>\n  <rect x=\"20\" y=\"120\" width=\"90\" height=\"36\" rx=\"3\" fill=\"#1e293b\" stroke=\"#60a5fa\"/><text x=\"65\" y=\"136\" fill=\"#93c5fd\" text-anchor=\"middle\" font-size=\"5.8\">Zero-Shot</text><text x=\"65\" y=\"148\" fill=\"#93c5fd\" text-anchor=\"middle\" font-size=\"5.8\">Classification</text>\n  <rect x=\"125\" y=\"120\" width=\"90\" height=\"36\" rx=\"3\" fill=\"#450a0a\" stroke=\"#f87171\"/><text x=\"170\" y=\"136\" fill=\"#fca5a5\" text-anchor=\"middle\" font-size=\"5.8\">RAG</text><text x=\"170\" y=\"148\" fill=\"#fca5a5\" text-anchor=\"middle\" font-size=\"5.8\">Faithfulness</text>\n  <rect x=\"230\" y=\"120\" width=\"90\" height=\"36\" rx=\"3\" fill=\"#292524\" stroke=\"#f59e0b\"/><text x=\"275\" y=\"136\" fill=\"#fde68a\" text-anchor=\"middle\" font-size=\"5.8\">Fact</text><text x=\"275\" y=\"148\" fill=\"#fde68a\" text-anchor=\"middle\" font-size=\"5.8\">Checking</text>\n  <g stroke=\"#64748b\" stroke-width=\"1\"><line x1=\"170\" y1=\"44\" x2=\"170\" y2=\"54\"/><line x1=\"170\" y1=\"72\" x2=\"170\" y2=\"82\"/><line x1=\"170\" y1=\"100\" x2=\"65\" y2=\"120\"/><line x1=\"170\" y1=\"100\" x2=\"170\" y2=\"120\"/><line x1=\"170\" y1=\"100\" x2=\"275\" y2=\"120\"/></g>\n  <text x=\"170\" y=\"185\" fill=\"#64748b\" text-anchor=\"middle\" font-size=\"6\">Same 3-way classifier, three different downstream uses --</text>\n  <text x=\"170\" y=\"197\" fill=\"#64748b\" text-anchor=\"middle\" font-size=\"6\">this lesson verified both zero-shot and faithfulness directly.</text>\n</svg>",
      headingEn: 'One Classifier, Many Production Applications', headingKn: 'ಒಂದು Classifier, ಅನೇಕ Production Applications',
      captionEn: 'The same premise/hypothesis -> Transformer -> 3-way classifier core powers zero-shot classification, RAG faithfulness, hallucination detection, QA verification, and fact checking -- only what gets fed in as the "hypothesis" changes.',
      captionKn: 'ಅದೇ premise/hypothesis -> Transformer -> 3-way classifier ಕೋರ್ zero-shot classification, RAG faithfulness, hallucination detection, QA verification, ಮತ್ತು fact checking ಗಳಿಗೆ ಶಕ್ತಿ ನೀಡುತ್ತದೆ -- ಕೇವಲ "hypothesis" ಆಗಿ ಏನೂ ನೀಡಲಾಗಿದೆ ಎಂಬುದೂ ಮಾತ್ರ ಬದಲಾಗುತ್ತದೆ.' } },

    { type: 'concept', data: {
      headingEn: 'Why AI Uses It', headingKn: 'AI ಇದನ್ನು ಏಕೆ ಬಳಸುತ್ತದೆ',
      bodyEn: '• The verified zero-shot classification result (finance 0.926, correctly dwarfing the other three labels) is exactly why teams reach for NLI before building a custom classifier for a new domain: no labeled training data was needed to correctly categorize a financial news sentence, only a list of candidate label strings.\n• The genuine TypeError found in is_faithful() is a concrete argument for testing RAG-evaluation code against real pipeline output rather than trusting a comment or a mental model of "how it probably works" -- a faithfulness checker that silently crashes in production would either block every single answer from being served, or (if wrapped in a broad try/except) silently fail open and let unfaithful answers through undetected, which is arguably worse than no faithfulness check at all.\n• The fixed is_faithful() correctly distinguishing a supported claim (Eiffel Tower in France) from an unsupported one (a fabricated construction date) is a direct, working demonstration of why NLI has become the standard automatic hallucination detector in RAG evaluation frameworks: it gives a cheap, fast, reference-free way to flag exactly the kind of confident-sounding fabrication that word-overlap metrics like BLEU or ROUGE cannot detect at all.',
      bodyKn: '• ಪರಿಶೀಲಿಸಿದ zero-shot classification ಫಲಿತಾಂಶ (finance 0.926, ಇತರ ಮೂರು labels ಗಳನ್ನೂ ಸರಿಯಾಗಿ ಕುಬ್ಜಗೊಳಿಸುತ್ತಾ) ತಂಡಗಳು ಒಂದು ಹೊಸ ಡೊಮೈನ್‌ಗಾಗಿ ಒಂದು ಕಸ್ಟಮ್ classifier ನಿರ್ಮಿಸುವ ಮೊದಲು NLI ಗೆ ಏಕೆ ತಲುಪುತ್ತವೆ ಎಂಬುದಕ್ಕೆ ನಿಖರ ಕಾರಣ: ಒಂದು ಆರ್ಥಿಕ ಸುದ್ದಿ ವಾಕ್ಯವನ್ನೂ ಸರಿಯಾಗಿ ವರ್ಗೀಕರಿಸಲು ಯಾವುದೇ ಲೇಬಲ್ ಮಾಡಿದ ತರಬೇತಿ ಡೇಟಾ ಅಗತ್ಯವಿರಲಿಲ್ಲ, ಕೇವಲ ಅಭ್ಯರ್ಥಿ label strings ಗಳ ಒಂದು ಪಟ್ಟಿ ಮಾತ್ರ.\n• is_faithful() ನಲ್ಲಿ ಕಂಡುಬಂದ ನಿಜ TypeError RAG-evaluation code ಅನ್ನೂ ಒಂದು comment ಅಥವಾ "ಇದೂ ಬಹುಶಃ ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ" ಎಂಬ ಒಂದು ಮಾನಸಿಕ ಮಾದರಿಯನ್ನೂ ನಂಬುವ ಬದಲಿಗೆ ನಿಜ pipeline output ವಿರುದ್ಧ ಪರೀಕ್ಷಿಸುವುದಕ್ಕೆ ಒಂದು ಕಾಂಕ್ರೀಟ್ ವಾದ -- production ನಲ್ಲಿ ಮೌನವಾಗಿ crash ಆಗುವ ಒಂದು faithfulness checker ಪ್ರತಿ ಒಂಟಿ ಉತ್ತರವನ್ನೂ ಸೇವೆ ಸಲ್ಲಿಸುವುದನ್ನೂ ಬ್ಲಾಕ್ ಮಾಡುತ್ತದೆ, ಅಥವಾ (ಒಂದು ವಿಶಾಲ try/except ನಲ್ಲಿ ಸುತ್ತಿದ್ದರೆ) ಮೌನವಾಗಿ open ಆಗಿ ವಿಫಲಗೊಳ್ಳುತ್ತದೆ ಮತ್ತು ಪತ್ತೆಹಚ್ಚದೆ ಅವಿಶ್ವಾಸಾರ್ಹ ಉತ್ತರಗಳನ್ನೂ ಹಾದುಹೋಗಲು ಬಿಡುತ್ತದೆ, ಇದೂ ಯಾವುದೇ faithfulness check ಇಲ್ಲದಿರುವುದಕ್ಕಿಂತ ಬಹುಶಃ ಕೆಟ್ಟದಾಗಿದೆ.\n• ಸರಿಪಡಿಸಿದ is_faithful() ಒಂದು ಬೆಂಬಲಿತ ಹಕ್ಕನ್ನೂ (Eiffel Tower France ನಲ್ಲಿ) ಒಂದು ಬೆಂಬಲಿತವಲ್ಲದ್ದರಿಂದ (ಒಂದು ಕಟ್ಟಲ್ಪಟ್ಟ ನಿರ್ಮಾಣ ದಿನಾಂಕ) ಸರಿಯಾಗಿ ಪ್ರತ್ಯೇಕಿಸುವುದೂ NLI RAG evaluation frameworks ಗಳಲ್ಲಿ ಪ್ರಮಾಣಿತ ಸ್ವಯಂಚಾಲಿತ hallucination detector ಆಗಿ ಏಕೆ ಆಗಿದೆ ಎಂಬುದಕ್ಕೆ ಒಂದು ನೇರ, ಕೆಲಸ ಮಾಡುವ ಪ್ರದರ್ಶನ: ಇದೂ BLEU ಅಥವಾ ROUGE ನಂತಹ word-overlap metrics ಗಳು ಸಂಪೂರ್ಣವಾಗಿ ಪತ್ತೆಹಚ್ಚಲಾಗದ ನಿಖರ ಬಗೆಯ ಆತ್ಮವಿಶ್ವಾಸಪೂರ್ಣ-ಧ್ವನಿಸುವ ಕಟ್ಟುವಿಕೆಯನ್ನೂ ಫ್ಲ್ಯಾಗ್ ಮಾಡಲು ಒಂದು ಅಗ್ಗದ, ವೇಗದ, reference-free ಮಾರ್ಗ ನೀಡುತ್ತದೆ.' } },

    { type: 'concept', data: {
      headingEn: 'Key Takeaways', headingKn: 'ಮುಖ್ಯ ಅಂಶಗಳು',
      bodyEn: '• Zero-shot classification converts each candidate label into a hypothesis and picks the one with the highest entailment score -- verified directly: "finance" correctly won at 0.926 with no task-specific training.\n• RAG faithfulness checking uses NLI to verify a generated answer against retrieved context, splitting long answers into atomic claims checked independently -- verified directly, including a genuine crash (TypeError) in the lesson\'s own is_faithful() code, caused by over-indexing an already-flat pipeline result, fixed and re-verified to correctly distinguish a supported claim from a fabricated one.\n• Five real pitfalls limit NLI reliability in practice: hypothesis-only shortcuts (label leakage), lexical overlap heuristics (high word overlap does not mean entailment), document-length degradation, template sensitivity in zero-shot classification, and domain mismatch (general models underperforming on medical/legal/scientific text).\n• Model choice depends on the use case: DeBERTa-v3-large-mnli for general NLI, a cross-encoder for edge deployment, BART-large-mnli for zero-shot (verified in this lesson), document-level or multilingual variants for those specific needs, and the NLI layer inside RAGAS/DeepEval for hallucination detection.\n• The same core pipeline (premise + hypothesis -> Transformer -> 3-way classifier) powers zero-shot classification, RAG faithfulness, hallucination detection, QA verification, and fact checking -- only what is fed in as the hypothesis changes across applications.',
      bodyKn: '• Zero-shot classification ಪ್ರತಿ ಅಭ್ಯರ್ಥಿ label ಅನ್ನೂ ಒಂದು hypothesis ಆಗಿ ಪರಿವರ್ತಿಸುತ್ತದೆ ಮತ್ತು ಅತ್ಯುನ್ನತ entailment ಸ್ಕೋರ್ ಇರುವುದನ್ನೂ ಆಯ್ಕೆ ಮಾಡುತ್ತದೆ -- ನೇರವಾಗಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ: "finance" ಯಾವುದೇ task-ನಿರ್ದಿಷ್ಟ ತರಬೇತಿ ಇಲ್ಲದೆ 0.926 ರಲ್ಲಿ ಸರಿಯಾಗಿ ಗೆದ್ದಿತು.\n• RAG faithfulness checking ಒಂದು ಉತ್ಪಾದಿಸಿದ ಉತ್ತರವನ್ನೂ ಹಿಂಪಡೆದ context ವಿರುದ್ಧ ಪರಿಶೀಲಿಸಲು NLI ಬಳಸುತ್ತದೆ, ಉದ್ದವಾದ ಉತ್ತರಗಳನ್ನೂ ಸ್ವತಂತ್ರವಾಗಿ ಪರಿಶೀಲಿಸಿದ atomic claims ಗಳಾಗಿ ಬೇರ್ಪಡಿಸುತ್ತಾ -- ನೇರವಾಗಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ, ಲೆಸನ್‌ನ ಸ್ವಂತ is_faithful() code ನಲ್ಲಿ ಒಂದು ನಿಜ crash (TypeError) ಸೇರಿ, ಈಗಾಗಲೇ-ಫ್ಲ್ಯಾಟ್ pipeline ಫಲಿತಾಂಶವನ್ನೂ ಅತಿ-ಇಂಡೆಕ್ಸ್ ಮಾಡುವುದರಿಂದ ಉಂಟಾಗಿದೆ, ಒಂದು ಬೆಂಬಲಿತ ಹಕ್ಕನ್ನೂ ಒಂದು ಕಟ್ಟಲ್ಪಟ್ಟದ್ದರಿಂದ ಸರಿಯಾಗಿ ಪ್ರತ್ಯೇಕಿಸಲು ಸರಿಪಡಿಸಿ ಮರುಪರಿಶೀಲಿಸಲಾಗಿದೆ.\n• ಐದು ನಿಜ ಬಲೆಗಳು ಪ್ರಾಯೋಗಿಕವಾಗಿ NLI ವಿಶ್ವಾಸಾರ್ಹತೆಯನ್ನೂ ಮಿತಿಗೊಳಿಸುತ್ತವೆ: hypothesis-only shortcuts (label leakage), lexical overlap heuristics (ಹೆಚ್ಚಿನ ಪದ overlap ಎಂದರೆ entailment ಎಂದಲ್ಲ), document-length degradation, zero-shot classification ನಲ್ಲಿ template sensitivity, ಮತ್ತು domain mismatch (ಸಾಮಾನ್ಯ models ಗಳು ವೈದ್ಯಕೀಯ/ಕಾನೂನು/ವೈಜ್ಞಾನಿಕ ಪಠ್ಯದ ಮೇಲೆ ಕಡಿಮೆ ಪ್ರದರ್ಶನ ನೀಡುತ್ತವೆ).\n• Model ಆಯ್ಕೆ ಬಳಕೆ ಪ್ರಕರಣದ ಮೇಲೆ ಅವಲಂಬಿತವಾಗಿದೆ: ಸಾಮಾನ್ಯ NLI ಗಾಗಿ DeBERTa-v3-large-mnli, edge deployment ಗಾಗಿ ಒಂದು cross-encoder, zero-shot ಗಾಗಿ BART-large-mnli (ಈ lesson ನಲ್ಲಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ), ಆ ನಿರ್ದಿಷ್ಟ ಅಗತ್ಯಗಳಿಗೆ document-level ಅಥವಾ multilingual ರೂಪಾಂತರಗಳು, ಮತ್ತು hallucination detection ಗಾಗಿ RAGAS/DeepEval ಒಳಗಿನ NLI ಪದರ.\n• ಅದೇ ಕೋರ್ pipeline (premise + hypothesis -> Transformer -> 3-way classifier) zero-shot classification, RAG faithfulness, hallucination detection, QA verification, ಮತ್ತು fact checking ಗಳಿಗೆ ಶಕ್ತಿ ನೀಡುತ್ತದೆ -- applications ಗಳಾದ್ಯಂತ hypothesis ಆಗಿ ಏನೂ ನೀಡಲಾಗಿದೆ ಎಂಬುದೂ ಮಾತ್ರ ಬದಲಾಗುತ್ತದೆ.' } },

    { type: 'quiz', data: { questions: [
      { q: 'How does zero-shot classification use NLI to classify a document without task-specific training?', qKn: 'Zero-shot classification task-ನಿರ್ದಿಷ್ಟ ತರಬೇತಿ ಇಲ್ಲದೆ ಒಂದು ದಾಖಲೆ ವರ್ಗೀಕರಿಸಲು NLI ಅನ್ನೂ ಹೇಗೆ ಬಳಸುತ್ತದೆ?',
        opts: ['It fine-tunes a new model for each candidate label', 'It converts each candidate label into a hypothesis (e.g. "This text is about finance") and picks the label whose hypothesis has the highest entailment score against the document', 'It counts keyword matches between the document and each label name', 'It requires the user to manually pre-label similar documents first'],
        optsKn: ['ಇದೂ ಪ್ರತಿ ಅಭ್ಯರ್ಥಿ label ಗಾಗಿ ಒಂದು ಹೊಸ model fine-tune ಮಾಡುತ್ತದೆ', 'ಇದೂ ಪ್ರತಿ ಅಭ್ಯರ್ಥಿ label ಅನ್ನೂ ಒಂದು hypothesis ಆಗಿ ಪರಿವರ್ತಿಸುತ್ತದೆ (ಉದಾ. "This text is about finance") ಮತ್ತು ದಾಖಲೆಯ ವಿರುದ್ಧ ಅತ್ಯುನ್ನತ entailment ಸ್ಕೋರ್ ಇರುವ hypothesis ನ label ಆಯ್ಕೆ ಮಾಡುತ್ತದೆ', 'ಇದೂ ದಾಖಲೆ ಮತ್ತು ಪ್ರತಿ label ಹೆಸರಿನ ನಡುವೆ keyword ಹೊಂದಾಣಿಕೆಗಳನ್ನೂ ಎಣಿಸುತ್ತದೆ', 'ಇದಕ್ಕೆ ಬಳಕೆದಾರ ಮೊದಲು ಹೋಲುವ ದಾಖಲೆಗಳನ್ನೂ ಹಸ್ತಚಾಲಿತವಾಗಿ ಪೂರ್ವ-ಲೇಬಲ್ ಮಾಡಬೇಕು'], correct: 1 },
      { q: 'Verified in this lesson: what did the real zero-shot classifier predict for "The stock market rallied after the central bank cut interest rates." with candidate labels finance/sports/politics/technology?', qKn: 'ಈ lesson ನಲ್ಲಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ: finance/sports/politics/technology ಅಭ್ಯರ್ಥಿ labels ಗಳೊಂದಿಗೆ "The stock market rallied after the central bank cut interest rates." ಗಾಗಿ ನಿಜ zero-shot classifier ಏನನ್ನೂ ಭವಿಷ್ಯವಾಣಿ ಮಾಡಿತು?',
        opts: ['Sports, since the word "rallied" is a sports term', 'Finance, with a score of 0.926 -- far ahead of the other three labels', 'Technology, since interest rates are set by algorithms', 'The classifier could not decide and returned all four labels tied'], correct: 1,
        optsKn: ['Sports, "rallied" ಪದ ಒಂದು ಕ್ರೀಡಾ ಪದದ ಕಾರಣ', 'Finance, 0.926 ಸ್ಕೋರ್ ಜೊತೆ -- ಇತರ ಮೂರು labels ಗಳಿಗಿಂತ ಬಹಳ ಮುಂದೆ', 'Technology, interest rates ಗಳನ್ನೂ algorithms ಗಳು ಹೊಂದಿಸುವ ಕಾರಣ', 'Classifier ನಿರ್ಧರಿಸಲಾಗದೆ ಎಲ್ಲಾ ನಾಲ್ಕು labels ಗಳನ್ನೂ ಸಮಬಲ ಎಂದು ಹಿಂತಿರುಗಿಸಿತು'] },
      { q: 'Verified in this lesson: what error did the lesson\'s own is_faithful() function genuinely raise when run exactly as written?', qKn: 'ಈ lesson ನಲ್ಲಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ: ನಿಖರವಾಗಿ ಬರೆದಂತೆ ಚಲಾಯಿಸಿದಾಗ ಲೆಸನ್‌ನ ಸ್ವಂತ is_faithful() ಫಂಕ್ಷನ್ ನಿಜವಾಗಿ ಯಾವ error ಎಬ್ಬಿಸಿತು?',
        opts: ['No error -- it worked perfectly as written', 'A TypeError ("string indices must be integers, not \'str\'"), because result = nli(...)[0] over-indexed an already-flat list of label dicts, turning result into a single dict whose string keys were then iterated over incorrectly', 'A ModuleNotFoundError, since the nli pipeline was never imported', 'A ZeroDivisionError from the threshold comparison'],
        optsKn: ['ಯಾವುದೇ error ಇಲ್ಲ -- ಬರೆದಂತೆ ಇದೂ ಪರಿಪೂರ್ಣವಾಗಿ ಕೆಲಸ ಮಾಡಿತು', 'ಒಂದು TypeError ("string indices must be integers, not \'str\'"), ಏಕೆಂದರೆ result = nli(...)[0] ಈಗಾಗಲೇ-ಫ್ಲ್ಯಾಟ್ label dicts ಗಳ ಒಂದು ಪಟ್ಟಿಯನ್ನೂ ಅತಿ-ಇಂಡೆಕ್ಸ್ ಮಾಡಿತು, result ಅನ್ನೂ ಒಂಟಿ dict ಆಗಿ ಬದಲಾಯಿಸಿತು ಅದರ string keys ಗಳನ್ನೂ ನಂತರ ತಪ್ಪಾಗಿ iterate ಮಾಡಲಾಯಿತು', 'ಒಂದು ModuleNotFoundError, nli pipeline ಎಂದಿಗೂ import ಆಗದ ಕಾರಣ', 'threshold ಹೋಲಿಕೆಯಿಂದ ಒಂದು ZeroDivisionError'], correct: 1 },
      { q: 'After fixing is_faithful() by removing the extra [0], what did it correctly return for the answer "The Eiffel Tower was built in 1800" given context "The Eiffel Tower is located in Paris"?', qKn: 'ಹೆಚ್ಚುವರಿ [0] ತೆಗೆದುಹಾಕುವ ಮೂಲಕ is_faithful() ಸರಿಪಡಿಸಿದ ನಂತರ, context "The Eiffel Tower is located in Paris" ನೀಡಿದ "The Eiffel Tower was built in 1800" ಉತ್ತರಕ್ಕೆ ಇದೂ ಸರಿಯಾಗಿ ಏನನ್ನೂ ಹಿಂತಿರುಗಿಸಿತು?',
        opts: ['True, since 1800 is a plausible date', 'False, correctly flagging the answer as unsupported since the context never mentions a construction date', 'An error, since dates cannot be checked by NLI', 'True, since the Eiffel Tower and Paris are both mentioned'], correct: 1,
        optsKn: ['True, 1800 ಒಂದು ಸಮಂಜಸ ದಿನಾಂಕ ಎಂಬ ಕಾರಣ', 'False, context ಎಂದಿಗೂ ಒಂದು ನಿರ್ಮಾಣ ದಿನಾಂಕ ಉಲ್ಲೇಖಿಸದ ಕಾರಣ ಉತ್ತರವನ್ನೂ ಬೆಂಬಲಿತವಲ್ಲ ಎಂದು ಸರಿಯಾಗಿ ಫ್ಲ್ಯಾಗ್ ಮಾಡುತ್ತಾ', 'ಒಂದು error, ದಿನಾಂಕಗಳನ್ನೂ NLI ಇಂದ ಪರಿಶೀಲಿಸಲಾಗದ ಕಾರಣ', 'True, Eiffel Tower ಮತ್ತು Paris ಎರಡೂ ಉಲ್ಲೇಖಿಸಲ್ಪಟ್ಟಿರುವ ಕಾರಣ'] },
      { q: 'What is the "Hypothesis-Only Shortcut" pitfall (11.1)?', qKn: '"Hypothesis-Only Shortcut" ಬಲೆ (11.1) ಎಂದರೇನು?',
        opts: ['The model always ignores the hypothesis entirely', 'Due to dataset bias, a model can predict a label from the hypothesis alone (e.g. the word "nobody" often signals contradiction) without ever needing to read the premise', 'The hypothesis is always longer than the premise', 'It refers to models that only accept single-word hypotheses'], correct: 1,
        optsKn: ['Model ಯಾವಾಗಲೂ hypothesis ಅನ್ನೂ ಸಂಪೂರ್ಣವಾಗಿ ಕಡೆಗಣಿಸುತ್ತದೆ', 'Dataset bias ಕಾರಣ, ಒಂದು model ಕೇವಲ hypothesis ಇಂದ ಮಾತ್ರ ಒಂದು label ಭವಿಷ್ಯವಾಣಿ ಮಾಡಬಲ್ಲದು (ಉದಾ. "nobody" ಪದ ಆಗಾಗ್ಗೆ contradiction ಸೂಚಿಸುತ್ತದೆ) premise ಅನ್ನೂ ಎಂದಿಗೂ ಓದುವ ಅಗತ್ಯವಿಲ್ಲದೆ', 'Hypothesis ಯಾವಾಗಲೂ premise ಗಿಂತ ಉದ್ದವಾಗಿದೆ', 'ಇದೂ ಕೇವಲ ಒಂಟಿ-ಪದದ hypotheses ಗಳನ್ನೂ ಮಾತ್ರ ಒಪ್ಪಿಕೊಳ್ಳುವ models ಗಳನ್ನೂ ಸೂಚಿಸುತ್ತದೆ'] },
      { q: 'Why does "Every student passed the exam" vs. "Every exam passed the student" illustrate the "Lexical Overlap Heuristic" pitfall?', qKn: '"Every student passed the exam" vs. "Every exam passed the student" "Lexical Overlap Heuristic" ಬಲೆಯನ್ನೂ ಏಕೆ ದೃಷ್ಟಾಂತಿಸುತ್ತದೆ?',
        opts: ['Because the two sentences are identical in meaning', 'Because they share nearly every word, yet mean completely different things -- a model relying on word overlap alone might wrongly predict entailment', 'Because "student" and "exam" are never related concepts', 'Because this pair cannot be processed by any NLI model'], correct: 1,
        optsKn: ['ಏಕೆಂದರೆ ಎರಡು ವಾಕ್ಯಗಳು ಅರ್ಥದಲ್ಲಿ ಒಂದೇ', 'ಏಕೆಂದರೆ ಅವು ಬಹುತೇಕ ಪ್ರತಿ ಪದವನ್ನೂ ಹಂಚಿಕೊಳ್ಳುತ್ತವೆ, ಆದರೂ ಸಂಪೂರ್ಣವಾಗಿ ಬೇರೆ ವಿಷಯಗಳನ್ನೂ ಅರ್ಥೈಸುತ್ತವೆ -- ಕೇವಲ ಪದ overlap ಅವಲಂಬಿಸುವ ಒಂದು model ತಪ್ಪಾಗಿ entailment ಭವಿಷ್ಯವಾಣಿ ಮಾಡಬಹುದು', 'ಏಕೆಂದರೆ "student" ಮತ್ತು "exam" ಎಂದಿಗೂ ಸಂಬಂಧಿತ ಪರಿಕಲ್ಪನೆಗಳಲ್ಲ', 'ಏಕೆಂದರೆ ಈ ಜೋಡಿಯನ್ನೂ ಯಾವುದೇ NLI model ಇಂದ ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲಾಗುವುದಿಲ್ಲ'] },
      { q: 'Why might a general-purpose NLI model underperform on medical records or legal contracts?', qKn: 'ವೈದ್ಯಕೀಯ ದಾಖಲೆಗಳು ಅಥವಾ ಕಾನೂನು ಒಪ್ಪಂದಗಳ ಮೇಲೆ ಒಂದು ಸಾಮಾನ್ಯ-ಉದ್ದೇಶದ NLI model ಏಕೆ ಕಡಿಮೆ ಪ್ರದರ್ಶನ ನೀಡಬಹುದು?',
        opts: ['NLI models cannot process any text longer than one sentence', 'It was trained on everyday English, not specialized domain vocabulary and reasoning patterns -- domain-specific datasets like MedNLI and SciNLI generally produce better results', 'Legal and medical text cannot be tokenized by any NLI model', 'General-purpose models always outperform domain-specific ones regardless of the text'], correct: 1,
        optsKn: ['NLI models ಗಳು ಒಂದು ವಾಕ್ಯಕ್ಕಿಂತ ಉದ್ದವಾದ ಯಾವುದೇ ಪಠ್ಯ ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲಾರವು', 'ಇದೂ ದೈನಂದಿನ English ಮೇಲೆ ತರಬೇತಿ ಪಡೆದಿದೆ, ವಿಶೇಷ ಡೊಮೈನ್ ಶಬ್ದಕೋಶ ಮತ್ತು ತಾರ್ಕಿಕ ಮಾದರಿಗಳ ಮೇಲಲ್ಲ -- MedNLI ಮತ್ತು SciNLI ನಂತಹ ಡೊಮೈನ್-ನಿರ್ದಿಷ್ಟ datasets ಗಳು ಸಾಮಾನ್ಯವಾಗಿ ಉತ್ತಮ ಫಲಿತಾಂಶಗಳನ್ನೂ ಉತ್ಪಾದಿಸುತ್ತವೆ', 'ಕಾನೂನು ಮತ್ತು ವೈದ್ಯಕೀಯ ಪಠ್ಯವನ್ನೂ ಯಾವುದೇ NLI model ಇಂದ tokenize ಮಾಡಲಾಗುವುದಿಲ್ಲ', 'ಸಾಮಾನ್ಯ-ಉದ್ದೇಶದ models ಗಳು ಪಠ್ಯವನ್ನೂ ಲೆಕ್ಕಿಸದೆ ಯಾವಾಗಲೂ ಡೊಮೈನ್-ನಿರ್ದಿಷ್ಟವಾದವುಗಳಿಗಿಂತ ಉತ್ತಮ ಪ್ರದರ್ಶನ ನೀಡುತ್ತವೆ'] },
      { q: 'Why is NLI-based faithfulness checking able to catch a hallucination that word-overlap metrics like BLEU or ROUGE would miss?', qKn: 'BLEU ಅಥವಾ ROUGE ನಂತಹ word-overlap metrics ಗಳು ತಪ್ಪಿಸಿಕೊಳ್ಳುವ ಒಂದು hallucination ಅನ್ನೂ NLI-ಆಧಾರಿತ faithfulness checking ಏಕೆ ಹಿಡಿಯಬಲ್ಲದು?',
        opts: ['Because BLEU and ROUGE cannot process any English text', 'Because NLI checks whether the claim is actually entailed by the evidence\'s meaning, whereas word-overlap metrics only measure surface lexical similarity and cannot tell a fabricated but fluently-worded fact from a genuinely supported one', 'Because NLI models are always faster than BLEU or ROUGE', 'Because BLEU and ROUGE were designed specifically to detect hallucinations'], correct: 1,
        optsKn: ['ಏಕೆಂದರೆ BLEU ಮತ್ತು ROUGE ಯಾವುದೇ English ಪಠ್ಯ ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲಾರವು', 'ಏಕೆಂದರೆ NLI ಹಕ್ಕು ನಿಜವಾಗಿ ಪುರಾವೆಯ ಅರ್ಥದಿಂದ entailed ಆಗಿದೆಯೇ ಎಂದು ಪರಿಶೀಲಿಸುತ್ತದೆ, ಆದರೆ word-overlap metrics ಗಳು ಕೇವಲ ಮೇಲ್ಮೈ ಲೆಕ್ಸಿಕಲ್ ಹೋಲಿಕೆ ಮಾತ್ರ ಅಳೆಯುತ್ತವೆ ಮತ್ತು ಒಂದು ಕಟ್ಟಲ್ಪಟ್ಟ ಆದರೆ ಸಲೀಸಾಗಿ-ಪದಪ್ರಯೋಗಿಸಿದ ಸತ್ಯವನ್ನೂ ಒಂದು ನಿಜವಾಗಿ ಬೆಂಬಲಿತದ್ದರಿಂದ ಹೇಳಲಾರವು', 'ಏಕೆಂದರೆ NLI models ಗಳು ಯಾವಾಗಲೂ BLEU ಅಥವಾ ROUGE ಗಿಂತ ವೇಗವಾಗಿವೆ', 'ಏಕೆಂದರೆ BLEU ಮತ್ತು ROUGE ಗಳನ್ನೂ ನಿರ್ದಿಷ್ಟವಾಗಿ hallucinations ಪತ್ತೆಹಚ್ಚಲು ವಿನ್ಯಾಸಗೊಳಿಸಲಾಗಿತ್ತು'] },
    ] } },
  ],
};
