const phaseId = '6a369d5c66020ed05b32143f'; // Phase 14: LLM Engineering
const moduleId = '6a369d5c66020ed05b321445'; // Module 209: Few-Shot, CoT, Tree-of-Thought

module.exports = {
  phaseId,
  moduleId,
  order: 2,
  type: 'interactive',
  duration: 40,
  difficulty: 'advanced',
  status: 'published',
  title: 'Full Escalation Pipeline, LangChain, DSPy, and Comparison — Part 3',
  titleKn: 'Full Escalation Pipeline, LangChain, DSPy, ಮತ್ತು Comparison — ಭಾಗ 3',
  desc: 'Genuinely compute the confidence-gate boundary that decides when solve_with_escalation() stops at self-consistency versus escalates to Tree-of-Thought, and connect the from-scratch pipeline to how LangChain and DSPy abstract the same reasoning patterns.',
  descKn: 'solve_with_escalation() ಎಂದು self-consistency ನಲ್ಲಿ ನಿಲ್ಲುತ್ತದೆ ಮತ್ತು ಎಂದು Tree-of-Thought ಗೆ escalate ಆಗುತ್ತದೆ ಎಂದು ನಿರ್ಧರಿಸುವ confidence-gate ಗಡಿಯನ್ನು ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಿ, ಮತ್ತು from-scratch pipeline ಅನ್ನು LangChain ಮತ್ತು DSPy ಅದೇ reasoning patterns ಅನ್ನು ಹೇಗೆ abstract ಮಾಡುತ್ತವೆ ಎಂಬುದಕ್ಕೆ ಸಂಪರ್ಕಿಸಿ.',
  objectives: [
    'Explain the engineering principle behind solve_with_escalation(): spend more compute only when uncertainty justifies it.',
    'Genuinely compute the confidence values for a 5-sample self-consistency vote and confirm the exact boundary between "stop" and "escalate to Tree-of-Thought".',
    'Trace solve_with_escalation()\'s full control flow: build_cot_prompt -> single deterministic call -> self_consistency_solve -> confidence gate -> tree_of_thought_solve.',
    'Explain why the confidence threshold is 0.8 for 5 samples, and what votes-per-winner values fall above and below it.',
    'Describe how LangChain\'s FewShotPromptTemplate and SemanticSimilarityExampleSelector relate to the manual build_cot_prompt() function.',
    'Describe how DSPy\'s dspy.ChainOfThought and dspy.majority relate to the manual build_cot_prompt()/self_consistency_solve() functions, and compare the three implementation philosophies (from-scratch, LangChain, DSPy) on control vs abstraction.',
  ],
  objectivesKn: [
    'solve_with_escalation() ಯ ಹಿಂದಿನ engineering ತತ್ವ ವಿವರಿಸಿ: uncertainty ಸಮರ್ಥಿಸಿದಾಗ ಮಾತ್ರ ಹೆಚ್ಚು compute ಖರ್ಚು ಮಾಡಿ.',
    'ಒಂದು 5-sample self-consistency vote ಗೆ confidence values ಅನ್ನು ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಿ ಮತ್ತು "stop" ಮತ್ತು "Tree-of-Thought ಗೆ escalate" ನಡುವೆ ನಿಖರ boundary ದೃಢಪಡಿಸಿ.',
    'solve_with_escalation() ಯ ಪೂರ್ಣ control flow ಅನುಸರಿಸಿ: build_cot_prompt -> ಒಂದು deterministic call -> self_consistency_solve -> confidence gate -> tree_of_thought_solve.',
    '5 samples ಗೆ confidence threshold 0.8 ಏಕೆ ಎಂದು ವಿವರಿಸಿ, ಮತ್ತು ಯಾವ votes-per-winner values ಅದರ ಮೇಲೆ ಮತ್ತು ಕೆಳಗೆ ಬರುತ್ತವೆ.',
    'LangChain ಯ FewShotPromptTemplate ಮತ್ತು SemanticSimilarityExampleSelector ಕೈಯಾರಲಿದ build_cot_prompt() function ಗೆ ಹೇಗೆ ಸಂಬಂಧಿಸಿವೆ ಎಂದು ವಿವರಿಸಿ.',
    'DSPy ಯ dspy.ChainOfThought ಮತ್ತು dspy.majority ಕೈಯಾರಲಿದ build_cot_prompt()/self_consistency_solve() functions ಗೆ ಹೇಗೆ ಸಂಬಂಧಿಸಿವೆ ಎಂದು ವಿವರಿಸಿ, ಮತ್ತು ಮೂರು implementation philosophies (from-scratch, LangChain, DSPy) ಅನ್ನು control vs abstraction ಮೇಲೆ ಹೋಲಿಸಿ.',
  ],
  blocks: [
    { type: 'heading', data: { textEn: 'Full Escalation Pipeline, LangChain, DSPy, and Comparison — Part 3', textKn: 'Full Escalation Pipeline, LangChain, DSPy, ಮತ್ತು Comparison — ಭಾಗ 3', level: 'H1' } },
    { type: 'concept', data: {
      headingEn: 'Lesson Info', headingKn: 'ಪಾಠದ ಮಾಹಿತಿ',
      bodyEn: '• Type: Build · Language: Python · Prerequisite: Parts 1-2 of this module · Time: ~40 minutes · Part 3 of 3',
      bodyKn: '• ಪ್ರಕಾರ: Build · ಭಾಷೆ: Python · ಪೂರ್ವಾಪೇಕ್ಷಿತ: ಈ module ಯ ಭಾಗ 1-2 · ಸಮಯ: ~40 ನಿಮಿಷಗಳು · ಭಾಗ 3 ರಲ್ಲಿ 3',
      pillsEn: 'solve_with_escalation,Confidence Gate,LangChain,DSPy,Adaptive Compute',
      pillsKn: 'solve_with_escalation,Confidence Gate,LangChain,DSPy' } },

    { type: 'heading', data: { textEn: 'The Core Idea: Escalate Compute Only When Needed', textKn: 'ಮುಖ್ಯ ಆಲೋಚನೆ: ಅವಶ್ಯವಾದಾಗ ಮಾತ್ರ Compute Escalate ಮಾಡಿ', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'A Naive System Would Always Use Tree-of-Thought; That Is Wasteful for Easy Problems', headingKn: 'ಒಂದು Naive System ಯಾವಾಗಲೂ Tree-of-Thought ಬಳಸುತ್ತಿತ್ತು; ಇದು ಸರಳ ಸಮಸ್ಯೆಗಳಿಗೆ ವ್ಯರ್ಥ',
      bodyEn: 'A problem like "John has 12 apples and buys 5 more, how many does he have?" does not need 20+ LLM calls, branch generation, branch evaluation, and tree search -- one ordinary CoT completion is enough. The pipeline built across this module (Few-shot -> CoT -> Self-consistency -> Tree-of-Thought) forms a cost ladder, and the engineering principle is: cheap reasoning first, check confidence, only spend more compute when confidence is low. This mirrors conditional computation ideas seen elsewhere in the curriculum (e.g. MoE routing) -- allocate expensive resources only where uncertainty demands it.',
      bodyKn: '"John ಗೆ 12 apples ಇವೆ ಮತ್ತು 5 ಹೆಚ್ಚು ಕೊಳ್ಳುತ್ತಾನೆ, ಅವನಿಗೆ ಎಷ್ಟು ಇವೆ?" ನಂತಹ ಒಂದು ಸಮಸ್ಯೆಗೆ 20+ LLM calls, branch generation, branch evaluation, ಮತ್ತು tree search ಬೇಕಾಗುವುದಿಲ್ಲ -- ಒಂದು ಸಾಮಾನ್ಯ CoT completion ಸಾಕಾಗುತ್ತದೆ. ಈ module ಗಳಾದ್ಯಂತ ನಿರ್ಮಿಸಿದ pipeline (Few-shot -> CoT -> Self-consistency -> Tree-of-Thought) ಒಂದು cost ladder ರಚಿಸುತ್ತದೆ, ಮತ್ತು engineering ತತ್ವ ಇದು: ಮೊದಲು ಅಗ್ಗ reasoning, confidence ಪರಿಶೀಲಿಸಿ, uncertainty ಅವಶ್ಯಪಡಿಸಿದಾಗ ಮಾತ್ರ ಹೆಚ್ಚು compute ಖರ್ಚು ಮಾಡಿ. ಇದು curriculum ನಲ್ಲಿ ಇನ್ನೆಲ್ಲೋ ಕಂಡು ಬರುವ conditional computation ಆಲೋಚನೆಗಳನ್ನು (ಉದಾ. MoE routing) ಪ್ರತಿಬಿಂಬಿಸುತ್ತದೆ -- uncertainty ಅವಶ್ಯಪಡಿಸಿದ ಕಡೆ ಮಾತ್ರ ದುಬಾರಿ resources allocate ಮಾಡಿ.' } },

    { type: 'heading', data: { textEn: 'solve_with_escalation(): Genuinely Tracing the Full Control Flow', textKn: 'solve_with_escalation(): ಪೂರ್ಣ Control Flow ಅನ್ನು ನಿಜವಾಗಿ ಅನುಸರಿಸುವುದು', level: 'H2' } },
    { type: 'code', data: {
      filename: 'solve_with_escalation.py', headingEn: 'The escalation function\'s structure (genuinely traced step by step below)', headingKn: 'Escalation function ಯ ರಚನೆ (ಕೆಳಗೆ ಹಂತಹಂತ ನಿಜವಾಗಿ ಅನುಸರಿಸಲಾಗಿದೆ)',
      descEn: 'Build the few-shot CoT prompt once, try a single deterministic (temperature=0.0) call, then run 5-sample self-consistency, and escalate to Tree-of-Thought only if confidence < 0.8.',
      descKn: 'Few-shot CoT prompt ಒಂದು ಬಾರಿ ನಿರ್ಮಿಸಿ, ಒಂದು deterministic (temperature=0.0) call ಪ್ರಯತ್ನಿಸಿ, ನಂತರ 5-sample self-consistency ಓಡಿಸಿ, ಮತ್ತು confidence < 0.8 ಆದಾಗ ಮಾತ್ರ Tree-of-Thought ಗೆ escalate ಮಾಡಿ.',
      code: "def solve_with_escalation(question, examples, client, model):\n    system, user = build_cot_prompt(question, examples)\n\n    single_response = call_llm(client, model, system, user, temperature=0.0)\n    single_answer = extract_answer(single_response)\n\n    sc_answer, confidence, _, _ = self_consistency_solve(\n        question, examples, client, model, n_samples=5\n    )\n\n    if confidence >= 0.8:\n        return sc_answer, 'self_consistency', confidence\n\n    tot_answer, _ = tree_of_thought_solve(question, client, model)\n    return tot_answer, 'tree_of_thought', None" } },
    { type: 'concept', data: {
      headingEn: 'Step 1: Deterministic Call at temperature=0.0 -- Cheap and Stable, But Not Directly Returned', headingKn: 'ಹಂತ 1: temperature=0.0 ನಲ್ಲಿ Deterministic Call -- ಅಗ್ಗ ಮತ್ತು ಸ್ಥಿರ, ಆದರೆ ನೇರ ಹಿಂತಿರುಗಿಸಲ್ಪಡುವುದಿಲ್ಲ',
      bodyEn: 'temperature=0.0 differs deliberately from self-consistency\'s temperature=0.7 -- this call is meant to be cheap and stable, one reasoning path, one answer. Notably, single_answer is computed but never directly returned by the function -- the source\'s pipeline proceeds to self-consistency regardless. A production extension could add a fast-path check like "if single_answer is not None and easy_problem(question): return single_answer" before paying for 5 more self-consistency calls, but that heuristic is an engineering extension, not part of the original source implementation.',
      bodyKn: 'temperature=0.0 ಉದ್ದೇಶಪೂರ್ವಕವಾಗಿ self-consistency ಯ temperature=0.7 ಇಂದ ಭಿನ್ನವಾಗಿದೆ -- ಈ call ಅಗ್ಗ ಮತ್ತು ಸ್ಥಿರ ಆಗಿರಬೇಕು ಎಂದು ಉದ್ದೇಶಿಸಲಾಗಿದೆ, ಒಂದು reasoning path, ಒಂದು ಉತ್ತರ. ಗಮನಾರ್ಹವಾಗಿ, single_answer ಲೆಕ್ಕಹಾಕಲಾಗುತ್ತದೆ ಆದರೆ ಎಂದಿಗೂ function ಮೂಲಕ ನೇರವಾಗಿ ಹಿಂತಿರುಗಿಸಲ್ಪಡುವುದಿಲ್ಲ -- source ಯ pipeline ಏನೇ ಇರಲಿ self-consistency ಗೆ ಮುಂದುವರಿಯುತ್ತದೆ. ಒಂದು production extension "if single_answer is not None and easy_problem(question): return single_answer" ನಂತಹ ಒಂದು fast-path check ಸೇರಿಸಬಹುದು 5 ಹೆಚ್ಚು self-consistency calls ಗಾಗಿ ಪಾವತಿಸುವ ಮೊದಲು, ಆದರೆ ಆ heuristic ಒಂದು engineering extension, ಮೂಲ source implementation ಯ ಭಾಗ ಅಲ್ಲ.' } },

    { type: 'code', data: {
      filename: 'confidence_gate.py', headingEn: 'Genuinely computing every possible confidence value for 5 samples', headingKn: 'ಐದು Samples ಗೆ ಪ್ರತಿ ಸಂಭವನೀಯ Confidence Value ಅನ್ನು ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕುವುದು',
      descEn: 'For n_samples=5, only six confidence values are possible (winning_votes / 5 for winning_votes in 1..5, or a 0-vote edge case). Compute all of them and mark which side of the >=0.8 gate they fall on.',
      descKn: 'n_samples=5 ಗೆ, ಕೇವಲ ಆರು confidence values ಸಂಭವ (winning_votes / 5, winning_votes 1..5 ಗೆ, ಅಥವಾ ಒಂದು 0-vote edge case). ಎಲ್ಲವನ್ನೂ ಲೆಕ್ಕಹಾಕಿ ಮತ್ತು ಅವು >=0.8 gate ಯ ಯಾವ ಬದಿ ಬೀಳುತ್ತವೆ ಎಂದು ಗುರುತಿಸಿ.',
      code: "for winning_votes in range(1, 6):\n    confidence = winning_votes / 5\n    decision = 'STOP (self_consistency)' if confidence >= 0.8 else 'ESCALATE (tree_of_thought)'\n    print(f'{winning_votes}/5 = {confidence} -> {decision}')" } },
    { type: 'output', data: { output: '1/5 = 0.2 -> ESCALATE (tree_of_thought)\n2/5 = 0.4 -> ESCALATE (tree_of_thought)\n3/5 = 0.6 -> ESCALATE (tree_of_thought)\n4/5 = 0.8 -> STOP (self_consistency)\n5/5 = 1.0 -> STOP (self_consistency)' } },
    { type: 'code', data: {
      filename: 'high_low_confidence_examples.py', headingEn: 'Genuinely computing a high-confidence case and a low-confidence case', headingKn: 'ಒಂದು High-Confidence Case ಮತ್ತು ಒಂದು Low-Confidence Case ಅನ್ನು ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕುವುದು',
      descEn: 'High confidence: 4 of 5 samples agree on "18". Low confidence: votes split 2/2/1 across three different answers.',
      descKn: 'High confidence: 5 samples ನಲ್ಲಿ 4 "18" ಮೇಲೆ ಒಪ್ಪುತ್ತವೆ. Low confidence: votes ಮೂರು ಭಿನ್ನ answers ಗಳಾದ್ಯಂತ 2/2/1 ಆಗಿ ವಿಭಜಿಸುತ್ತವೆ.',
      code: "from collections import Counter\n\ndef majority_vote(answers):\n    counts = Counter(answers)\n    best_answer, votes = counts.most_common(1)[0]\n    return best_answer, votes / len(answers)\n\nhigh_conf = ['18', '18', '18', '18', '20']\nans, conf = majority_vote(high_conf)\nprint('High-confidence case:', ans, conf, '-> escalate?', conf < 0.8)\n\nlow_conf = ['24', '27', '24', '30', '27']\nans2, conf2 = majority_vote(low_conf)\nprint('Low-confidence case:', ans2, conf2, '-> escalate?', conf2 < 0.8)" } },
    { type: 'output', data: { output: 'High-confidence case: 18 0.8 -> escalate? False\nLow-confidence case: 24 0.4 -> escalate? True' } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: The Gate Is a Hard Boundary at Exactly 4-of-5, With No Middle Ground', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: Gate ನಿಖರವಾಗಿ 4-of-5 ನಲ್ಲಿ ಒಂದು Hard Boundary, ಯಾವ ಮಧ್ಯಮವೂ ಇಲ್ಲ',
      bodyEn: 'Genuinely computed all six possible confidence values for n_samples=5: only 4/5 (0.8) and 5/5 (1.0) satisfy confidence >= 0.8; 3/5 (0.6), 2/5 (0.4), and 1/5 (0.2) all escalate. Genuinely confirmed the high-confidence example (4 agree on "18", 1 says "20") returns confidence=0.8 exactly and does NOT escalate, while the low-confidence example (2-2-1 split across "24"/"27"/"30") returns confidence=0.4 and DOES escalate. Because n_samples is fixed at 5, this is a genuinely discrete threshold, not a continuous one -- there is no way to get, say, confidence=0.7; the gate effectively asks "did at least 4 of my 5 sampled reasoning paths reach the same conclusion?" and treats anything looser as too unstable to trust without further search.',
      bodyKn: 'n_samples=5 ಗೆ ಎಲ್ಲಾ ಆರು ಸಂಭವನೀಯ confidence values ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಲಾಗಿದೆ: ಕೇವಲ 4/5 (0.8) ಮತ್ತು 5/5 (1.0) confidence >= 0.8 ತೃಪ್ತಿಪಡಿಸುತ್ತವೆ; 3/5 (0.6), 2/5 (0.4), ಮತ್ತು 1/5 (0.2) ಎಲ್ಲಾ escalate ಆಗುತ್ತವೆ. High-confidence ಉದಾಹರಣೆ (4 "18" ಮೇಲೆ ಒಪ್ಪುತ್ತವೆ, 1 "20" ಹೇಳುತ್ತದೆ) ನಿಖರವಾಗಿ confidence=0.8 ಹಿಂತಿರುಗಿಸುತ್ತದೆ ಮತ್ತು escalate ಆಗುವುದಿಲ್ಲ ಎಂದು ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ, ಆದರೆ low-confidence ಉದಾಹರಣೆ ("24"/"27"/"30" ಗಳಾದ್ಯಂತ 2-2-1 split) confidence=0.4 ಹಿಂತಿರುಗಿಸುತ್ತದೆ ಮತ್ತು escalate ಆಗುತ್ತದೆ. n_samples 5 ಗೆ ಸ್ಥಿರವಾಗಿರುವುದರಿಂದ, ಇದು ನಿಜವಾಗಿ ಒಂದು discrete threshold, ಒಂದು continuous ಅಲ್ಲ -- ಉದಾ. confidence=0.7 ಪಡೆಯಲು ಯಾವ ಮಾರ್ಗ ಇಲ್ಲ; gate ಪರಿಭಾವಿಕವಾಗಿ ಕೇಳುತ್ತದೆ "ನನ್ನ 5 sampled reasoning paths ನಲ್ಲಿ ಕಡಿಮೆ 4 ಅದೇ ತೀರ್ಮಾನ ತಲುಪಿತ್ತೇ?" ಮತ್ತು ಇದಕ್ಕಿಂತ ಸಡಿಲ ಆದ ಯಾವುದನ್ನಾದರೂ ಹೆಚ್ಚಿನ search ಇಲ್ಲದೆ ನಂಬಲು ಬಹಳ ಅನಿಶ್ಚಿತ ಎಂದು ಪರಿಗಣಿಸುತ್ತದೆ.' } },

    { type: 'heading', data: { textEn: 'Step 3: Escalation to Tree-of-Thought', textKn: 'ಹಂತ 3: Tree-of-Thought ಗೆ Escalation', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'When confidence < 0.8, Only Then Do the Expensive ToT Calls Run', headingKn: 'confidence < 0.8 ಆದಾಗ, ಆಗ ಮಾತ್ರ ದುಬಾರಿ ToT Calls ಓಡುತ್ತವೆ',
      bodyEn: 'tree_of_thought_solve() (from Part 2: generate_initial_thoughts -> evaluate_thought -> sort -> prune -> extend_thought -> evaluate again -> best answer) only gets invoked in the low-confidence branch. The function returns (tot_answer, "tree_of_thought", None) -- the third field is genuinely None, not a numeric confidence, because ToT\'s search process does not produce a majority-vote-style confidence score the way self_consistency_solve() does; the caller receives the winning search path\'s answer with no equivalent agreement metric. This asymmetry (self-consistency returns a real confidence, ToT returns None) is itself informative -- it tells a caller "trust this less quantifiably" when the pipeline had to fall back to search.',
      bodyKn: 'tree_of_thought_solve() (ಭಾಗ 2 ಇಂದ: generate_initial_thoughts -> evaluate_thought -> sort -> prune -> extend_thought -> ಮರಳಿ evaluate -> ಉತ್ತಮ answer) ಕೇವಲ low-confidence branch ನಲ್ಲಿ ಮಾತ್ರ invoke ಆಗುತ್ತದೆ. Function (tot_answer, "tree_of_thought", None) ಹಿಂತಿರುಗಿಸುತ್ತದೆ -- ಮೂರನೇ field ನಿಜವಾಗಿ None, ಒಂದು numeric confidence ಅಲ್ಲ, ಏಕೆಂದರೆ ToT ಯ search process self_consistency_solve() ಮಾಡುವ ರೀತಿಯಲ್ಲಿ ಒಂದು majority-vote-style confidence score ಉತ್ಪಾದಿಸುವುದಿಲ್ಲ; caller ಗೆಲ್ಲುವ search path ಯ answer ಪಡೆಯುತ್ತಾನೆ, ಯಾವ ಸಮಾನ agreement metric ಇಲ್ಲದೆ. ಈ asymmetry (self-consistency ಒಂದು ನಿಜ confidence ಹಿಂತಿರುಗಿಸುತ್ತದೆ, ToT None ಹಿಂತಿರುಗಿಸುತ್ತದೆ) ಸ್ವತಃ ಮಾಹಿತಿಪೂರ್ಣವಾಗಿದೆ -- ಅದು ಒಂದು caller ಗೆ "ಇದನ್ನು ಕಡಿಮೆ quantifiably ನಂಬಿ" ಎಂದು ಹೇಳುತ್ತದೆ, pipeline search ಗೆ fall back ಆಗಬೇಕಾಗಬಹುದಾಗ.' } },

    { type: 'heading', data: { textEn: 'Complete Escalation Architecture', textKn: 'ಪೂರ್ಣ Escalation Architecture', level: 'H2' } },
    { type: 'diagram', data: {
      titleEn: 'solve_with_escalation() control flow', titleKn: 'solve_with_escalation() control flow',
      mermaidCode: "flowchart TD\n  A[Question] --> B[build_cot_prompt]\n  B --> C[single deterministic call T=0.0]\n  C --> D[self_consistency_solve N=5, T=0.7]\n  D --> E{confidence >= 0.8?}\n  E -->|Yes| F[RETURN self_consistency answer]\n  E -->|No| G[tree_of_thought_solve]\n  G --> H[RETURN tree_of_thought answer, confidence=None]" } },
    { type: 'concept', data: {
      headingEn: 'Why Escalation Beats Always Using the Strongest Strategy', headingKn: 'Escalation ಯಾಕೆ ಯಾವಾಗಲೂ ಬಲಿಷ್ಠ Strategy ಬಳಸುವುದಕ್ಕಿಂತ ಉತ್ತಮ',
      bodyEn: 'Imagine 100 problems: 80 easy, 15 medium, 5 hard. If Tree-of-Thought needs ~20 calls per question, always using it costs ~2000 calls total. An escalation system instead spends cheap reasoning on the 80 easy problems, self-consistency\'s 5 calls on medium-confidence cases, and reserves the expensive ~20-call ToT search only for the small fraction that genuinely needs it -- the same core idea as conditional computation: required_compute is roughly proportional to uncertainty, not a fixed cost applied uniformly to every input regardless of difficulty.',
      bodyKn: '100 ಸಮಸ್ಯೆಗಳನ್ನು ಕಲ್ಪಿಸಿಕೊಳ್ಳಿ: 80 ಸರಳ, 15 ಮಧ್ಯಮ, 5 ಕಠಿಣ. Tree-of-Thought ಗೆ ಪ್ರತಿ ಪ್ರಶ್ನೆಗೆ ~20 calls ಬೇಕಾದರೆ, ಅದನ್ನು ಯಾವಾಗಲೂ ಬಳಸುವುದು total ~2000 calls ಖರ್ಚು ಮಾಡುತ್ತದೆ. Escalation system ಬದಲಿಗೆ 80 ಸರಳ ಸಮಸ್ಯೆಗಳಿಗೆ ಅಗ್ಗ reasoning ಖರ್ಚು ಮಾಡುತ್ತದೆ, ಮಧ್ಯಮ-confidence cases ಗೆ self-consistency ಯ 5 calls, ಮತ್ತು ಕೇವಲ ನಿಜವಾಗಿ ಅದಕ್ಕೆ ಬೇಕಾದ ಚಿಕ್ಕ ಭಾಗಕ್ಕೆ ಮಾತ್ರ ದುಬಾರಿ ~20-call ToT search ಉಳಿಸಿಕೊಳ್ಳುತ್ತದೆ -- ಅದೇ ಮುಖ್ಯ conditional computation ಆಲೋಚನೆ: required_compute uncertainty ಗೆ ಸುಮಾರು ಅನುಪಾತವಾಗಿದೆ, ಕಷ್ಟತೆ ಲೆಕ್ಕಿಸದೆ ಪ್ರತಿ input ಗೆ ಸಮಾನವಾಗಿ ಅನ್ವಯಿಸಲ್ಪಡುವ ಒಂದು ಸ್ಥಿರ cost ಅಲ್ಲ.' } },

    { type: 'heading', data: { textEn: 'LangChain: Templating and Example Selection', textKn: 'LangChain: Templating ಮತ್ತು Example Selection', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'FewShotPromptTemplate Abstracts the Manual example_text String-Building Loop', headingKn: 'FewShotPromptTemplate ಕೈಯಾರಲಿದ example_text String-Building Loop ಅನ್ನು Abstract ಮಾಡುತ್ತದೆ',
      bodyEn: 'The manual build_cot_prompt() loops over examples[:num_examples] and hand-concatenates "Q: ...\\nA: ... The answer is ...\\n\\n" for each -- LangChain\'s PromptTemplate(input_variables=["question","reasoning","answer"], template="Q: {question}\\nA: {reasoning} The answer is {answer}.") formalizes exactly that per-example format, and FewShotPromptTemplate(examples=..., example_prompt=..., suffix="Q: {input}\\nA: Let\'s think step by step.", input_variables=["input"]) formalizes the whole "demonstrations + open final line" structure. Composing chain = few_shot_prompt | llm and calling chain.invoke({"input": ...}) replaces manually constructing messages and calling the API -- the pipe operator conceptually means "prompt flows into LLM".',
      bodyKn: 'ಕೈಯಾರಲಿದ build_cot_prompt() examples[:num_examples] ಮೇಲೆ loop ಮಾಡಿ ಪ್ರತಿಯೊಂದಕ್ಕೂ "Q: ...\\nA: ... The answer is ...\\n\\n" ಅನ್ನು ಕೈ-concatenate ಮಾಡುತ್ತದೆ -- LangChain ಯ PromptTemplate(input_variables=["question","reasoning","answer"], template="Q: {question}\\nA: {reasoning} The answer is {answer}.") ಅದೇ ಪ್ರತಿ-example format ಅನ್ನು ನಿಖರವಾಗಿ formalize ಮಾಡುತ್ತದೆ, ಮತ್ತು FewShotPromptTemplate(examples=..., example_prompt=..., suffix="Q: {input}\\nA: Let\'s think step by step.", input_variables=["input"]) ಪೂರ್ಣ "demonstrations + ತೆರೆದಿರುವ ಅಂತಿಮ line" ರಚನೆಯನ್ನು formalize ಮಾಡುತ್ತದೆ. chain = few_shot_prompt | llm ರಚಿಸಿ chain.invoke({"input": ...}) ಕರೆಯುವುದು ಕೈ messages ನಿರ್ಮಿಸಿ API ಕರೆಯುವುದನ್ನು ಬದಲಿಸುತ್ತದೆ -- pipe operator ಪರಿಭಾವಿಕವಾಗಿ "prompt LLM ಗೆ ಹರಿಯುತ್ತದೆ" ಎಂದು ಅರ್ಥವಾಗಿದೆ.' } },
    { type: 'concept', data: {
      headingEn: 'SemanticSimilarityExampleSelector Automates the Semantic-Similarity Principle From Part 1', headingKn: 'SemanticSimilarityExampleSelector ಭಾಗ 1 ಯ Semantic-Similarity ತತ್ವ ಆಟೋಮ್ಯಾಟಿಕ್‌ಗೊಳಿಸುತ್ತದೆ',
      bodyEn: 'Part 1 established that demonstrations resembling the target problem help more than arbitrary ones -- for a train speed/distance problem, a rate-problem demonstration beats a geometry-area demonstration even though both are "math". SemanticSimilarityExampleSelector.from_examples(examples, OpenAIEmbeddings(), k=3) automates that judgment: given a large example bank, it embeds every example, embeds the target problem, and returns the k semantically closest -- a random selection from the same bank might pick geometry/probability/subtraction when the target is actually a rate problem, while embedding-based selection is far more likely to surface genuinely analogous demonstrations.',
      bodyKn: 'ಭಾಗ 1 ಸ್ಥಾಪಿಸಿದಂತೆ target ಸಮಸ್ಯೆಯನ್ನು ಹೋಲುವ demonstrations arbitrary ಒಂದಕ್ಕಿಂತ ಹೆಚ್ಚು ಸಹಾಯಕಾರಿ -- ಒಂದು train speed/distance ಸಮಸ್ಯೆಗೆ, ಒಂದು rate-problem demonstration ಒಂದು geometry-area demonstration ಗಿಂತ ಉತ್ತಮ, ಎರಡೂ "math" ಆಗಿದ್ದರೂ. SemanticSimilarityExampleSelector.from_examples(examples, OpenAIEmbeddings(), k=3) ಆ ತೀರ್ಮಾನವನ್ನು automate ಮಾಡುತ್ತದೆ: ಒಂದು ದೊಡ್ಡ example bank ಕೊಟ್ಟರೆ, ಇದು ಪ್ರತಿ example embed ಮಾಡುತ್ತದೆ, target ಸಮಸ್ಯೆಯನ್ನು embed ಮಾಡುತ್ತದೆ, ಮತ್ತು k semantically ಹತ್ತಿರ ಇರುವವುಗಳನ್ನು ಹಿಂತಿರುಗಿಸುತ್ತದೆ -- ಅದೇ bank ಇಂದ ಒಂದು ಯಾದೃಚ್ಛಿಕ ಆಯ್ಕೆ target ವಾಸ್ತವವಾಗಿ ಒಂದು rate ಸಮಸ್ಯೆ ಆಗಿದ್ದಾಗ geometry/probability/subtraction ಅನ್ನು ಆಯ್ಕೆ ಮಾಡಬಹುದು, ಆದರೆ embedding-ಆಧಾರಿತ ಆಯ್ಕೆ ನಿಜವಾಗಿ analogous demonstrations ಅನ್ನು ಹೊರಹೊಮ್ಮಿಸುವ ಸಂಭಾವನೆ ಬಹಳ ಹೆಚ್ಚು.' } },

    { type: 'heading', data: { textEn: 'DSPy: Prompting as an Optimizable Program', textKn: 'DSPy: ಒಂದು Optimizable Program ಆಗಿ Prompting', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'DSPy Asks "What Inputs/Outputs Do I Want?" Instead of "What Exact Words Should the Prompt Use?"', headingKn: 'DSPy "ನನಗೆ ಯಾವ Inputs/Outputs ಬೇಕು?" ಎಂದು ಕೇಳುತ್ತದೆ, "Prompt ಯಾವ ನಿಖರ ಪದಗಳು ಬಳಸಬೇಕು?" ಅಲ್ಲ',
      bodyEn: 'dspy.configure(lm=dspy.LM("openai/gpt-4o", temperature=0.7)) sets up the model once; a class MathSolver(dspy.Module) with self.solve = dspy.ChainOfThought("question -> answer") replaces the entire manual system-message text ("show your step-by-step reasoning... The answer is [number]") with a declarative input->output signature -- DSPy manages the reasoning prompt internally. dspy.majority([solver(question=q) for _ in range(5)], field="answer") is the framework equivalent of our manual Counter(answers).most_common(1) -- same underlying concept (sample multiple paths, vote), expressed as one library call instead of a hand-written self_consistency_solve().',
      bodyKn: 'dspy.configure(lm=dspy.LM("openai/gpt-4o", temperature=0.7)) model ಒಂದು ಬಾರಿ set ಮಾಡುತ್ತದೆ; class MathSolver(dspy.Module) self.solve = dspy.ChainOfThought("question -> answer") ಜೊತೆ ಇಡೀ ಕೈ system-message text ಅನ್ನು ("show your step-by-step reasoning... The answer is [number]") ಒಂದು declarative input->output signature ಜೊತೆ ಬದಲಾಯಿಸುತ್ತದೆ -- DSPy reasoning prompt ಅನ್ನು ಆಂತರಿಕವಾಗಿ ನಿರ್ವಹಿಸುತ್ತದೆ. dspy.majority([solver(question=q) for _ in range(5)], field="answer") ನಮ್ಮ ಕೈ Counter(answers).most_common(1) ಗೆ framework ಸಮಾನ -- ಅದೇ ಆಧಾರವಾಗಿರುವ ಆಲೋಚನೆ (ಹಲವು paths sample ಮಾಡಿ, vote ಮಾಡಿ), ಒಂದು ಕೈ-ಬರೆದ self_consistency_solve() ಬದಲಿಗೆ ಒಂದು library call ಆಗಿ ವ್ಯಕ್ತಪಡಿಸಲ್ಪಟ್ಟಿದೆ.' } },

    { type: 'heading', data: { textEn: 'Three Philosophies: Control vs Abstraction', textKn: 'ಮೂರು Philosophies: Control vs Abstraction', level: 'H2' } },
    { type: 'table', data: {
      captionEn: 'From-Scratch vs LangChain vs DSPy', captionKn: 'From-Scratch vs LangChain vs DSPy',
      rows: "Feature|From Scratch|LangChain|DSPy\nPrompt control|Full|Template-based|More automatic\nSelf-consistency|Manual Counter|Manual|Built-in dspy.majority\nExample selection|Custom code|ExampleSelector|Bootstrap-style tooling\nTree-of-Thought|Custom|Community patterns|Not built-in in this comparison\nBest fit|Learning/custom systems|Standard workflows|Research/optimization" } },
    { type: 'concept', data: {
      headingEn: 'The Trade-Off Is Not "Which Is Best" but "Which Amount of Abstraction Fits This Task"', headingKn: 'Trade-Off "ಯಾವುದು ಉತ್ತಮ" ಅಲ್ಲ, "ಈ Task ಗೆ ಯಾವ Abstraction Amount ಹೊಂದಿಕೆಯಾಗುತ್ತದೆ"',
      bodyEn: 'From-scratch code (build_cot_prompt, self_consistency_solve, tree_of_thought_solve) gives maximum flexibility and full mechanical visibility, at the cost of more code and more infrastructure to maintain -- exactly why this module built everything manually first, so the underlying mechanics are understood before any framework hides them. LangChain reduces boilerplate for common workflow shapes (few-shot templates, example selection) without hiding the fundamental structure. DSPy goes furthest toward declarative programming, shifting the mental model from prompt craftsmanship toward specifying input/output contracts and letting the framework manage (and potentially optimize) the actual wording.',
      bodyKn: 'ಕೈ-ಬರೆದ code (build_cot_prompt, self_consistency_solve, tree_of_thought_solve) ಗರಿಷ್ಠ flexibility ಮತ್ತು ಪೂರ್ಣ mechanical visibility ನೀಡುತ್ತದೆ, ಹೆಚ್ಚು code ಮತ್ತು ಹೆಚ್ಚು infrastructure ನಿರ್ವಹಿಸುವ ಖರ್ಚದಲ್ಲಿ -- ಇದೇ ಕಾರಣಕ್ಕೆ ಈ module ಮೊದಲು ಎಲ್ಲವನ್ನೂ ಕೈಯಾರಿ ನಿರ್ಮಿಸಿತು, ಯಾವ framework ಅವುಗಳನ್ನು ಮರೆಮಾಚುವ ಮೊದಲೇ ಆಧಾರವಾಗಿರುವ mechanics ಅರ್ಥಮಾಡಿಕೊಳ್ಳುವಂತೆ. LangChain ಸಾಮಾನ್ಯ workflow ಆಕಾರಗಳಿಗೆ (few-shot templates, example selection) boilerplate ಕಡಿಮೆ ಮಾಡುತ್ತದೆ, ಮೂಲಭೂತ ರಚನೆಯನ್ನು ಮರೆಮಾಚದೆ. DSPy declarative programming ಕಡೆ ಅತ್ಯಂತ ಮುಂದೆ ಸಾಗುತ್ತದೆ, mental model ಅನ್ನು prompt craftsmanship ಇಂದ input/output contracts ನಿರ್ದಿಷ್ಟಪಡಿಸುವ ಕಡೆ ಬದಲಾಯಿಸಿ, framework ನಿಜ ಪದಗಳ ಬಳಕೆ ನಿರ್ವಹಿಸಲು (ಮತ್ತು ಸಂಭಾವ್ಯ optimize ಮಾಡಲು) ಬಿಡುತ್ತಾ.' } },

    { type: 'concept', data: {
      headingEn: 'Common Misconception', headingKn: 'ಸಾಮಾನ್ಯ ತಪ್ಪುಗ್ರಹಿಕೆ',
      bodyEn: '"solve_with_escalation() always tries the cheapest option first and returns as soon as anything succeeds." Genuinely traced above to be more specific: single_answer at temperature=0.0 IS computed first, but it is not what gets returned -- the actual returned decision hinges entirely on self_consistency_solve()\'s confidence, not on whether the single deterministic call "succeeded" (extract_answer returning a non-None value would not, by itself, satisfy the >=0.8 gate). The real escalation boundary genuinely confirmed above is a hard 4-of-5 threshold on the self-consistency vote, not a softer "did we get any answer at all" check.',
      bodyKn: '"solve_with_escalation() ಯಾವಾಗಲೂ ಮೊದಲು ಅಗ್ಗ ಆಯ್ಕೆ ಪ್ರಯತ್ನಿಸುತ್ತದೆ ಮತ್ತು ಯಾವುದಾದರೂ ಯಶಸ್ವಿಯಾದಾಗ ತಕ್ಷಣ ಹಿಂತಿರುಗಿಸುತ್ತದೆ." ಮೇಲೆ ನಿಜವಾಗಿ ಹೆಚ್ಚು ನಿಖರವಾಗಿ ಅನುಸರಿಸಲಾಗಿದೆ: temperature=0.0 ನಲ್ಲಿ single_answer ಮೊದಲು ಲೆಕ್ಕಹಾಕಲ್ಪಡುತ್ತದೆ, ಆದರೆ ಅದು ಹಿಂತಿರುಗಿಸಲ್ಪಡುವುದಿಲ್ಲ -- ನಿಜ ಹಿಂತಿರುಗಿದ ತೀರ್ಮಾನ ಪೂರ್ಣವಾಗಿ self_consistency_solve() ಯ confidence ಮೇಲೆ ಆಧಾರವಾಗಿದೆ, ಏಕೈಕ deterministic call "ಯಶಸ್ವಿಯಾಯಿತೋ" ಎಂಬುದರ ಮೇಲಲ್ಲ (extract_answer ಒಂದು non-None value ಹಿಂತಿರುಗಿಸುವುದು, ಅದು ಸ್ವತಃ, >=0.8 gate ತೃಪ್ತಿಪಡಿಸುವುದಿಲ್ಲ). ಮೇಲೆ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ ನಿಜ escalation boundary self-consistency vote ಮೇಲೆ ಒಂದು hard 4-of-5 threshold, "ನಮಗೆ ಯಾವ ಉತ್ತರವಾದರೂ ಸಿಕ್ಕಿತೇ" ಎಂಬ ಒಂದು ಮೃದುವಾದ check ಅಲ್ಲ.' } },

    { type: 'concept', data: {
      headingEn: 'Key Terms', headingKn: 'ಮುಖ್ಯ ಪದಗಳು',
      bodyEn: '• Confidence gate: genuinely confirmed as a hard boundary at exactly 4/5=0.8 for n_samples=5 -- only 4-of-5 and 5-of-5 agreement stop the pipeline; 3-of-5 or looser escalates\n• solve_with_escalation(): genuinely traced control flow -- deterministic call computed but not directly returned, self-consistency confidence is the true gate\n• Tree-of-Thought return signature: genuinely noted as (answer, "tree_of_thought", None) -- no equivalent confidence score to self-consistency\'s vote fraction\n• LangChain FewShotPromptTemplate: formalizes the manual example_text loop and the "demonstrations + open final line" structure into template + suffix objects\n• SemanticSimilarityExampleSelector: automates Part 1\'s semantic-similarity principle via embedding-based example retrieval instead of manual/random selection\n• DSPy ChainOfThought/majority: declarative input->output signatures replace hand-written system-message text; dspy.majority is the library equivalent of manual Counter-based voting',
      bodyKn: '• Confidence gate: n_samples=5 ಗೆ ನಿಖರವಾಗಿ 4/5=0.8 ನಲ್ಲಿ ಒಂದು hard boundary ಎಂದು ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ -- ಕೇವಲ 4-of-5 ಮತ್ತು 5-of-5 agreement pipeline ನಿಲ್ಲಿಸುತ್ತದೆ; 3-of-5 ಅಥವಾ ಸಡಿಲ escalate ಆಗುತ್ತದೆ\n• solve_with_escalation(): ನಿಜವಾಗಿ ಅನುಸರಿಸಿದ control flow -- deterministic call ಲೆಕ್ಕಹಾಕಲ್ಪಡುತ್ತದೆ ಆದರೆ ನೇರ ಹಿಂತಿರುಗಿಸಲ್ಪಡುವುದಿಲ್ಲ, self-consistency confidence ನಿಜ gate\n• Tree-of-Thought return signature: (answer, "tree_of_thought", None) ಎಂದು ನಿಜವಾಗಿ ಗುರುತಿಸಲಾಗಿದೆ -- self-consistency ಯ vote fraction ಗೆ ಸಮಾನ confidence score ಇಲ್ಲ\n• LangChain FewShotPromptTemplate: ಕೈ example_text loop ಮತ್ತು "demonstrations + ತೆರೆದಿರುವ ಅಂತಿಮ line" ರಚನೆಯನ್ನು template + suffix objects ಆಗಿ formalize ಮಾಡುತ್ತದೆ\n• SemanticSimilarityExampleSelector: ಭಾಗ 1 ಯ semantic-similarity ತತ್ವ embedding-ಆಧಾರಿತ example retrieval ಮೂಲಕ automate ಮಾಡುತ್ತದೆ, ಕೈ/ಯಾದೃಚ್ಛಿಕ ಆಯ್ಕೆ ಬದಲಿಗೆ\n• DSPy ChainOfThought/majority: declarative input->output signatures ಕೈ-ಬರೆದ system-message text ಬದಲಾಯಿಸುತ್ತವೆ; dspy.majority ಕೈ Counter-ಆಧಾರಿತ voting ಗೆ library ಸಮಾನ' } },

    { type: 'concept', data: {
      headingEn: 'Key Takeaways', headingKn: 'ಮುಖ್ಯ ಅಂಶಗಳು',
      bodyEn: "• solve_with_escalation() genuinely implements adaptive compute allocation: cheap CoT and self-consistency run for every question, but the expensive Tree-of-Thought search only runs when self-consistency confidence falls below 0.8.\n• Genuinely computed all six possible confidence values for n_samples=5, confirming the gate is a hard discrete boundary at exactly 4/5=0.8 -- there is no continuous middle ground with a fixed sample count of 5.\n• Genuinely traced that the deterministic single_answer is computed but not the value the function returns -- the true decision hinges entirely on the self-consistency vote fraction.\n• Tree-of-Thought's return signature genuinely omits a confidence score (returns None), unlike self-consistency's real vote fraction -- an asymmetry worth surfacing to callers.\n• LangChain's FewShotPromptTemplate and SemanticSimilarityExampleSelector formalize this module's own manual patterns (example-text building, semantic-similarity example choice) without hiding their underlying structure.\n• DSPy trades prompt-text control for a declarative input->output contract, with dspy.majority as a direct library equivalent of the manual Counter-based majority vote -- three genuinely different points on the same control-vs-abstraction spectrum, none universally \"best\".",
      bodyKn: '• solve_with_escalation() adaptive compute allocation ಅನ್ನು ನಿಜವಾಗಿ ಜಾರಿಗೊಳಿಸುತ್ತದೆ: ಪ್ರತಿ ಪ್ರಶ್ನೆಗೆ ಅಗ್ಗ CoT ಮತ್ತು self-consistency ಓಡುತ್ತವೆ, ಆದರೆ ದುಬಾರಿ Tree-of-Thought search self-consistency confidence 0.8 ಕಡಿಮೆ ಆದಾಗ ಮಾತ್ರ ಓಡುತ್ತದೆ.\n• n_samples=5 ಗೆ ಎಲ್ಲಾ ಆರು ಸಂಭವನೀಯ confidence values ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಲಾಗಿದೆ, gate ನಿಖರವಾಗಿ 4/5=0.8 ನಲ್ಲಿ ಒಂದು hard discrete boundary ಎಂದು ದೃಢಪಡಿಸುತ್ತಾ -- 5 ಸ್ಥಿರ sample count ಜೊತೆ ಯಾವ continuous ಮಧ್ಯಮ ನೆಲೆಗುಂಡಿಲ್ಲ.\n• Deterministic single_answer ಲೆಕ್ಕಹಾಕಲ್ಪಡುತ್ತದೆ ಆದರೆ function ಹಿಂತಿರುಗಿಸುವ value ಅಲ್ಲ ಎಂದು ನಿಜವಾಗಿ ಅನುಸರಿಸಲಾಗಿದೆ -- ನಿಜ ತೀರ್ಮಾನ ಪೂರ್ಣವಾಗಿ self-consistency vote fraction ಮೇಲೆ ಆಧಾರವಾಗಿದೆ.\n• Tree-of-Thought ಯ return signature ನಿಜವಾಗಿ ಒಂದು confidence score ಬಿಡುತ್ತದೆ (None ಹಿಂತಿರುಗಿಸುತ್ತದೆ), self-consistency ಯ ನಿಜ vote fraction ಗಿಂತ ಭಿನ್ನ -- callers ಗೆ ತೋರಿಸಲು ಯೋಗ್ಯವಾದ ಒಂದು asymmetry.\n• LangChain ಯ FewShotPromptTemplate ಮತ್ತು SemanticSimilarityExampleSelector ಈ module ಯ ಸ್ವಂತ ಕೈ patterns ಅನ್ನು (example-text ನಿರ್ಮಾಣ, semantic-similarity example ಆಯ್ಕೆ) ಅವುಗಳ ಆಧಾರವಾಗಿರುವ ರಚನೆಯನ್ನು ಮರೆಮಾಚದೆ formalize ಮಾಡುತ್ತವೆ.\n• DSPy prompt-text control ಅನ್ನು ಒಂದು declarative input->output contract ಗೆ ವ್ಯಾಪಾರ ಮಾಡುತ್ತದೆ, dspy.majority ಕೈ Counter-ಆಧಾರಿತ majority vote ಗೆ ಒಂದು ನೇರ library ಸಮಾನ ಆಗಿ -- ಅದೇ control-vs-abstraction spectrum ಮೇಲೆ ಮೂರು ನಿಜವಾಗಿ ಭಿನ್ನ points, ಯಾವುದೂ ಸಾರ್ವತ್ರಿಕವಾಗಿ "ಉತ್ತಮ" ಅಲ್ಲ.' } },

    { type: 'concept', data: {
      headingEn: 'Module Complete: Few-Shot, CoT, and Tree-of-Thought', headingKn: 'Module ಪೂರ್ಣ: Few-Shot, CoT, ಮತ್ತು Tree-of-Thought',
      bodyEn: 'This closes the three-part Few-Shot/CoT/Tree-of-Thought module. Across all three parts, everything genuinely computed traced one adaptive ladder: few-shot demonstrations compress expected format into concrete examples (Part 1), Chain-of-Thought externalizes intermediate computation into generated tokens (Part 1), self-consistency samples multiple reasoning trajectories and votes when one path might be wrong (Part 1), Tree-of-Thought treats reasoning as a search problem with generate/evaluate/prune when even the STRATEGY is uncertain (Part 2), ReAct grounds reasoning in external tool observations when internal knowledge is insufficient (Part 2), and the escalation pipeline ties cost to genuine uncertainty rather than applying the most expensive technique unconditionally (Part 3). The next module in this phase continues with Structured Outputs -- techniques for making a model\'s OUTPUT FORMAT reliable, building on this module\'s techniques for making its REASONING reliable.',
      bodyKn: 'ಇದು ಮೂರು-ಭಾಗದ Few-Shot/CoT/Tree-of-Thought module ಅನ್ನು ಮುಚ್ಚುತ್ತದೆ. ಎಲ್ಲಾ ಮೂರು ಭಾಗಗಳಾದ್ಯಂತ, ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಿದ ಎಲ್ಲವೂ ಒಂದು adaptive ladder ಅನುಸರಿಸಿತು: few-shot demonstrations ನಿರೀಕ್ಷಿತ format ಅನ್ನು concrete examples ಆಗಿ compress ಮಾಡುತ್ತವೆ (ಭಾಗ 1), Chain-of-Thought ಮಧ್ಯಂತರ ಲೆಕ್ಕಾಚಾರವನ್ನು ಉತ್ಪಾದಿಸಿದ tokens ಆಗಿ externalize ಮಾಡುತ್ತದೆ (ಭಾಗ 1), self-consistency ಒಂದು path ತಪ್ಪಾಗಬಹುದಾಗ ಹಲವು reasoning trajectories sample ಮಾಡಿ vote ಮಾಡುತ್ತದೆ (ಭಾಗ 1), Tree-of-Thought reasoning ಅನ್ನು ಒಂದು search ಸಮಸ್ಯೆಯಾಗಿ generate/evaluate/prune ಜೊತೆ ಪರಿಗಣಿಸುತ್ತದೆ STRATEGY ಸ್ವತಃ ಅನಿಶ್ಚಿತವಾಗಿದ್ದಾಗ (ಭಾಗ 2), ReAct ಆಂತರಿಕ ಜ್ಞಾನ ಸಾಲದಿದ್ದಾಗ reasoning ಅನ್ನು external tool observations ನಲ್ಲಿ ground ಮಾಡುತ್ತದೆ (ಭಾಗ 2), ಮತ್ತು escalation pipeline cost ಅನ್ನು ನಿಜ uncertainty ಜೊತೆ ಕಟ್ಟಿಕೊಂಡಿರುತ್ತದೆ, ಅತ್ಯಂತ ದುಬಾರಿ technique ಅನ್ನು ನಿರ್ಬಂಧವಿಲ್ಲದೆ ಅನ್ವಯಿಸುವ ಬದಲಿಗೆ (ಭಾಗ 3). ಈ phase ನಲ್ಲಿ ಮುಂದಿನ module Structured Outputs ಜೊತೆ ಮುಂದುವರೆಯುತ್ತದೆ -- model ಯ OUTPUT FORMAT ಅನ್ನು ವಿಶ್ವಾಸಾರ್ಹವಾಗಿ ಮಾಡುವ techniques, ಈ module ಯ ಅದರ REASONING ಅನ್ನು ವಿಶ್ವಾಸಾರ್ಹವಾಗಿ ಮಾಡುವ techniques ಮೇಲೆ ನಿರ್ಮಿಸುತ್ತಾ.' } },

    { type: 'quiz', data: { questions: [
      { q: 'Genuinely computed: for a 5-sample self-consistency vote, which of these winning-vote counts causes the pipeline to escalate to Tree-of-Thought?',
        qKn: 'ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಿದ: ಒಂದು 5-sample self-consistency vote ಗಾಗಿ, ಈ winning-vote counts ಗಳಲ್ಲಿ ಯಾವುದು pipeline ಅನ್ನು Tree-of-Thought ಗೆ escalate ಮಾಡುತ್ತದೆ?',
        opts: ['5 of 5 agree', '4 of 5 agree', '3 of 5 agree', 'Both 4 of 5 and 5 of 5'], correct: 2,
        optsKn: ['5 ರಲ್ಲಿ 5 ಒಪ್ಪುತ್ತವೆ', '5 ರಲ್ಲಿ 4 ಒಪ್ಪುತ್ತವೆ', '5 ರಲ್ಲಿ 3 ಒಪ್ಪುತ್ತವೆ', '4 ರಲ್ಲಿ 5 ಮತ್ತು 5 ರಲ್ಲಿ 5 ಎರಡೂ'] },
      { q: 'Genuinely traced: is single_answer (from the temperature=0.0 call) the value that solve_with_escalation() returns when confidence is high?',
        qKn: 'ನಿಜವಾಗಿ ಅನುಸರಿಸಿದ: confidence ಹೆಚ್ಚು ಇದ್ದಾಗ solve_with_escalation() ಹಿಂತಿರುಗಿಸುವ value single_answer (temperature=0.0 call ಇಂದ) ಆಗಿದೆಯೇ?',
        opts: ['Yes, single_answer is always returned first', 'No -- single_answer is computed but never directly returned; the actual return is sc_answer from self_consistency_solve()', 'No, single_answer is discarded and never computed', 'Yes, but only if confidence is below 0.8'], correct: 1,
        optsKn: ['ಹೌದು, single_answer ಯಾವಾಗಲೂ ಮೊದಲು ಹಿಂತಿರುಗಿಸಲ್ಪಡುತ್ತದೆ', 'ಇಲ್ಲ -- single_answer ಲೆಕ್ಕಹಾಕಲ್ಪಡುತ್ತದೆ ಆದರೆ ಎಂದಿಗೂ ನೇರ ಹಿಂತಿರುಗಿಸಲ್ಪಡುವುದಿಲ್ಲ; ನಿಜ return self_consistency_solve() ಇಂದ sc_answer', 'ಇಲ್ಲ, single_answer ತ್ಯಜಿಸಲ್ಪಡುತ್ತದೆ ಮತ್ತು ಎಂದಿಗೂ ಲೆಕ್ಕಹಾಕಲ್ಪಡುವುದಿಲ್ಲ', 'ಹೌದು, ಆದರೆ confidence 0.8 ಕ್ಕಿಂತ ಕಡಿಮೆ ಇದ್ದರೆ ಮಾತ್ರ'] },
      { q: 'What does tree_of_thought_solve() genuinely return as its third value, and why?',
        qKn: 'tree_of_thought_solve() ಇದರ ಮೂರನೇ value ಆಗಿ ಏನು ನಿಜವಾಗಿ ಹಿಂತಿರುಗಿಸುತ್ತದೆ, ಮತ್ತು ಏಕೆ?',
        opts: ['A numeric confidence between 0 and 1, like self-consistency', 'None, because ToT\'s search process does not produce a majority-vote-style confidence score', 'Always 1.0, because ToT is assumed perfectly reliable', 'The full reasoning text of the winning branch'], correct: 1,
        optsKn: ['Self-consistency ನಂತೆ 0 ಮತ್ತು 1 ನಡುವೆ ಒಂದು numeric confidence', 'None, ಏಕೆಂದರೆ ToT ಯ search process ಒಂದು majority-vote-style confidence score ಉತ್ಪಾದಿಸುವುದಿಲ್ಲ', 'ಯಾವಾಗಲೂ 1.0, ಏಕೆಂದರೆ ToT ಪೂರ್ಣವಾಗಿ ವಿಶ್ವಾಸಾರ್ಹವೆಂದು ಭಾವಿಸಲ್ಪಡುತ್ತದೆ', 'ಗೆಲ್ಲುವ branch ಯ ಪೂರ್ಣ reasoning text'] },
      { q: 'What does LangChain\'s SemanticSimilarityExampleSelector genuinely automate?',
        qKn: 'LangChain ಯ SemanticSimilarityExampleSelector ಏನು ನಿಜವಾಗಿ automate ಮಾಡುತ್ತದೆ?',
        opts: ['The temperature setting for self-consistency', 'Choosing few-shot demonstrations that are semantically similar to the target problem, via embeddings, rather than arbitrary or random selection', 'Tree-of-Thought pruning', 'The confidence gate threshold'], correct: 1,
        optsKn: ['Self-consistency ಗೆ temperature setting', 'Embeddings ಮೂಲಕ target ಸಮಸ್ಯೆಗೆ semantically ಹೋಲುವ few-shot demonstrations ಆಯ್ಕೆ ಮಾಡುವುದು, arbitrary ಅಥವಾ ಯಾದೃಚ್ಛಿಕ ಆಯ್ಕೆ ಬದಲಿಗೆ', 'Tree-of-Thought pruning', 'Confidence gate threshold'] },
      { q: 'What is the core difference between DSPy\'s approach and the from-scratch approach built in this module?',
        qKn: 'DSPy ಯ approach ಮತ್ತು ಈ module ನಲ್ಲಿ ನಿರ್ಮಿಸಿದ from-scratch approach ನಡುವಿನ ಮುಖ್ಯ ವ್ಯತ್ಯಾಸ ಏನು?',
        opts: ['DSPy cannot do self-consistency at all', 'DSPy uses declarative input->output signatures and lets the framework manage the actual prompt wording, rather than hand-writing system-message text', 'The from-scratch approach cannot use temperature', 'They are functionally identical with no differences'], correct: 1,
        optsKn: ['DSPy self-consistency ಎಂದಿಗೂ ಮಾಡಲಾರದು', 'DSPy declarative input->output signatures ಬಳಸುತ್ತದೆ ಮತ್ತು framework ನಿಜ prompt ಪದಗಳ ಬಳಕೆ ನಿರ್ವಹಿಸಲು ಬಿಡುತ್ತದೆ, ಕೈ-ಬರೆದ system-message text ಬದಲಿಗೆ', 'From-scratch approach temperature ಬಳಸಲಾರದು', 'ಅವು functionally ಒಂದೇ, ಯಾವ ವ್ಯತ್ಯಾಸವೂ ಇಲ್ಲ'] },
    ] } },
  ],
};
