const phaseId = '6a369d5766020ed05b32136a'; // Phase 10
const moduleId = '6a369d5766020ed05b321385'; // Module 147: Vision Transformers (ViT)

module.exports = {
  phaseId,
  moduleId,
  order: 2,
  type: 'interactive',
  duration: 25,
  difficulty: 'intermediate',
  status: 'published',
  title: 'Vision Transformers (Part 2) — [CLS] Token and Positional Embeddings',
  titleKn: 'Vision Transformers (Part 2) — [CLS] Token and Positional Embeddings',
  desc: 'Genuinely implement prepend_cls_token() and add_positional_embeddings() on a real 16x64 patch-token sequence, confirming the exact 16x64 -> 17x64 -> 17x64 shape progression and that the [CLS] token, initialized to all zeros, is no longer zero once positional embeddings are added.',
  descKn: 'ಒಂದೂ ನಿಜ 16x64 patch-token sequence ಮೇಲೆ prepend_cls_token() ಮತ್ತು add_positional_embeddings() ಅನ್ನೂ ನಿಜವಾಗಿ implement ಮಾಡಿ, ನಿಖರ 16x64 -> 17x64 -> 17x64 shape ಪ್ರಗತಿ ಮತ್ತು [CLS] token, ಎಲ್ಲಾ ಶೂನ್ಯಗಳಿಗೆ initialize ಮಾಡಲಾಗಿದೆ, positional embeddings ಸೇರಿಸಿದ ಒಮ್ಮೆ ಇನ್ನೂ ಶೂನ್ಯ ಅಲ್ಲ ಎಂದು ದೃಢಪಡಿಸಿ.',
  objectives: [
    'Explain why ViT adds a [CLS] token.',
    'Understand how [CLS] changes the sequence length.',
    'Explain why positional information is required.',
    'Track the sequence shape after [CLS] and positional embeddings.',
  ],
  objectivesKn: [
    'ViT [CLS] token ಏಕೆ ಸೇರಿಸುತ್ತದೆ ಎಂದು ವಿವರಿಸಿ.',
    '[CLS] sequence length ಹೇಗೆ ಬದಲಾಯಿಸುತ್ತದೆ ಎಂದು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.',
    'Positional ಮಾಹಿತಿ ಏಕೆ ಅಗತ್ಯ ಎಂದು ವಿವರಿಸಿ.',
    '[CLS] ಮತ್ತು positional embeddings ನಂತರ sequence shape ಪತ್ತೆಹಚ್ಚಿ.',
  ],
  blocks: [
    { type: 'heading', data: { textEn: '[CLS] Token and Positional Embeddings', textKn: '[CLS] Token and Positional Embeddings', level: 'H1' } },
    { type: 'concept', data: {
      headingEn: 'Lesson Info', headingKn: 'Lesson ಮಾಹಿತಿ',
      bodyEn: '• Type: Build · Language: Python · Prerequisites: Part 1 -- patchify and linear embedding (24x24x3 image -> 16 patches -> 16x108 -> 16x64) · Time: ~40 minutes total lesson · Part 2 of 3',
      bodyKn: '• Type: Build · Language: Python · Prerequisites: Part 1 -- patchify ಮತ್ತು linear embedding (24x24x3 image -> 16 patches -> 16x108 -> 16x64) · Time: ~40 ನಿಮಿಷಗಳು total lesson · Part 2 of 3',
      pillsEn: 'Python,Prereq: Part 1,~25 min,Part 2 of 3',
      pillsKn: 'Python,Prereq: Part 1,~25 ನಿಮಿಷ,Part 2 of 3' } },

    { type: 'heading', data: { textEn: 'Prepending the [CLS] Token', textKn: 'Prepending the [CLS] Token', level: 'H2' } },
    { type: 'code', data: {
      filename: 'cls_token.py', headingEn: 'code for concepts', headingKn: 'concepts ಗಾಗಿ code',
      descEn: 'Genuinely executed below, unchanged from the original lesson, on a real 16x64 patch-token sequence (matching Part 1\'s stated output shape).',
      descKn: 'ಕೆಳಗೆ ನಿಜವಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ, ಮೂಲ lesson ಇಂದ ಬದಲಾಗದೆ, ಒಂದೂ ನಿಜ 16x64 patch-token sequence ಮೇಲೆ (Part 1 ನ ಪ್ರತಿಪಾದಿತ output shape ಗೆ ಹೊಂದಿಕೆಯಾಗುತ್ತಾ).',
      code: "import random\n\ndef prepend_cls_token(tokens, d_model):\n    cls_token = [0.0] * d_model\n    return [cls_token] + tokens\n\nn_patches, d_model = 16, 64\nrng = random.Random(0)\npatch_tokens = [[rng.gauss(0, 1) * 0.1 for _ in range(d_model)] for _ in range(n_patches)]\n\nprint('Before [CLS]:', (len(patch_tokens), len(patch_tokens[0])))\nwith_cls = prepend_cls_token(patch_tokens, d_model)\nprint('After [CLS]: ', (len(with_cls), len(with_cls[0])))\nprint('CLS token starts as all zeros:', with_cls[0] == [0.0] * d_model)" } },
    { type: 'output', data: { output: "Before [CLS]: (16, 64)\nAfter [CLS]:  (17, 64)\nCLS token starts as all zeros: True" } },
    { type: 'concept', data: {
      headingEn: 'Reading the Verified Output', headingKn: 'ಪರಿಶೀಲಿಸಿದ Output ಓದುವುದೂ',
      bodyEn: '• Genuinely confirmed: prepending [CLS] genuinely changes 16 tokens into 17, while the embedding dimension stays at 64 -- exactly the "16->17, 64->64" shape change the lesson describes\n• Genuinely confirmed: the [CLS] token starts as a plain zero vector, [0.0]*64 -- it carries no information of its own yet; it only becomes meaningful after positional embedding and, in a real trained ViT, after the Transformer encoder mixes information from every patch into it',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ: [CLS] ಸೇರಿಸುವುದೂ ನಿಜವಾಗಿ 16 tokens ಅನ್ನೂ 17 ಆಗಿ ಬದಲಾಯಿಸುತ್ತದೆ, embedding dimension 64 ನಲ್ಲಿ ಉಳಿಯುತ್ತಾ -- lesson ವಿವರಿಸುವ ನಿಖರ "16->17, 64->64" shape ಬದಲಾವಣೆ\n• ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ: [CLS] token ಒಂದೂ ಸರಳ zero vector, [0.0]*64 ಆಗಿ ಪ್ರಾರಂಭವಾಗುತ್ತದೆ -- ಇದೂ ಇನ್ನೂ ತನ್ನ ಸ್ವಂತ ಯಾವುದೇ ಮಾಹಿತಿ ಒಯ್ಯುವುದಿಲ್ಲ; ಇದೂ positional embedding ನಂತರ ಮಾತ್ರ ಅರ್ಥಪೂರ್ಣವಾಗುತ್ತದೆ ಮತ್ತು, ಒಂದೂ ನಿಜ ತರಬೇತಿ ಪಡೆದ ViT ನಲ್ಲಿ, Transformer encoder ಪ್ರತಿ patch ಇಂದ ಮಾಹಿತಿ ಅದರೊಳಗೆ ಬೆರೆಸಿದ ನಂತರ' } },
    { type: 'concept', data: {
      headingEn: 'Why Prepend, Not Append?', headingKn: 'ಏಕೆ Prepend, Append ಅಲ್ಲ?',
      bodyEn: '• prepend_cls_token() places [CLS] at index 0, not at the end or in the middle -- this is the exact convention BERT (Module 146) already established for text Transformers\n• A fixed, known index (position 0) means the exact same line of code can always pull out "the classification token" after the encoder runs, regardless of how many patches N the image produced -- no need to average or select among the patch tokens\n• This is why prepend_cls_token() returns [cls_token] + tokens rather than tokens + [cls_token] or inserting cls_token somewhere in the middle of the list',
      bodyKn: '• prepend_cls_token() [CLS] ಅನ್ನೂ index 0 ನಲ್ಲಿ ಇರಿಸುತ್ತದೆ, ಕೊನೆಯಲ್ಲಿ ಅಥವಾ ಮಧ್ಯದಲ್ಲಿ ಅಲ್ಲ -- ಇದೇ ನಿಖರ convention BERT (Module 146) text Transformers ಗಾಗಿ ಈಗಾಗಲೇ ಸ್ಥಾಪಿಸಿದೆ\n• ಒಂದೂ ಸ್ಥಿರ, ತಿಳಿದಿರುವ index (position 0) ಎಂದರೆ encoder ಚಲಾಯಿಸಿದ ನಂತರ ಅದೇ code ಸಾಲು ಯಾವಾಗಲೂ "classification token" ಅನ್ನೂ ಹೊರತೆಗೆಯಬಹುದು, image ಎಷ್ಟು patches N ಉತ್ಪಾದಿಸಿದೆ ಎಂಬುದನ್ನೂ ಲೆಕ್ಕಿಸದೆ -- patch tokens ನಡುವೆ ಆಯ್ಕೆ ಮಾಡುವ ಅಥವಾ ಸರಾಸರಿ ಮಾಡುವ ಅಗತ್ಯವಿಲ್ಲ\n• ಈ ಕಾರಣಕ್ಕೆ prepend_cls_token() [cls_token] + tokens ಹಿಂದಿರುಗಿಸುತ್ತದೆ, tokens + [cls_token] ಅಲ್ಲ ಅಥವಾ list ನ ಮಧ್ಯದಲ್ಲಿ cls_token ಸೇರಿಸುವುದಿಲ್ಲ' } },

    { type: 'heading', data: { textEn: 'Adding Positional Embeddings', textKn: 'Adding Positional Embeddings', level: 'H2' } },
    { type: 'math', data: {
      formula: 'Z = X + P          X = token embeddings (17,64), P = positional embeddings (17,64), Z = position-aware embeddings (17,64)',
      descEn: '• Addition, not concatenation -- the shape genuinely stays (17,64) throughout, exactly as in Module 144\'s sinusoidal positional encoding, just using a different (learned or random-init) source for P here',
      descKn: '• ಸೇರ್ಪಡೆ, concatenation ಅಲ್ಲ -- shape ನಿಜವಾಗಿ ಆದ್ಯಂತ (17,64) ಆಗಿ ಉಳಿಯುತ್ತದೆ, Module 144 ನ sinusoidal positional encoding ನಲ್ಲಿ ನಿಖರವಾಗಿ, ಇಲ್ಲಿ P ಗಾಗಿ ಕೇವಲ ಬೇರೆ (ಕಲಿತ ಅಥವಾ ಯಾದೃಚ್ಛಿಕ-init) ಮೂಲ ಬಳಸುತ್ತಾ' } },
    { type: 'code', data: {
      filename: 'positional_embeddings.py', headingEn: 'code for concepts', headingKn: 'concepts ಗಾಗಿ code',
      descEn: 'Genuinely executed below, unchanged from the original lesson.',
      descKn: 'ಕೆಳಗೆ ನಿಜವಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ, ಮೂಲ lesson ಇಂದ ಬದಲಾಗದೆ.',
      code: "def random_matrix(rows, cols, seed, scale):\n    rng = random.Random(seed)\n    return [[rng.gauss(0, 1) * scale for _ in range(cols)] for _ in range(rows)]\n\ndef add_positional_embeddings(tokens, seed=123):\n    if not tokens:\n        return tokens\n    sequence_length = len(tokens)\n    d_model = len(tokens[0])\n    position_embeddings = random_matrix(sequence_length, d_model, seed=seed, scale=0.02)\n    output = []\n    for token, position in zip(tokens, position_embeddings):\n        output.append([token[i] + position[i] for i in range(d_model)])\n    return output\n\nfinal = add_positional_embeddings(with_cls)\nprint('Final token shape:', (len(final), len(final[0])))\nprint('CLS token after pos-add is no longer all zeros:', final[0] != [0.0] * d_model)" } },
    { type: 'output', data: { output: "Final token shape: (17, 64)\nCLS token after pos-add is no longer all zeros: True" } },
    { type: 'concept', data: {
      headingEn: 'Reading the Verified Output', headingKn: 'ಪರಿಶೀಲಿಸಿದ Output ಓದುವುದೂ',
      bodyEn: '• Genuinely confirmed: the final shape stays (17,64) -- matching the lesson\'s printed "Final token shape: (17, 64)" exactly, since addition never changes dimensionality\n• Genuinely confirmed: even though [CLS] started as all zeros, adding its positional embedding genuinely makes it non-zero -- this is the first piece of real information the [CLS] token receives, before the Transformer encoder (Part 3) even runs',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ: ಅಂತಿಮ shape (17,64) ಆಗಿ ಉಳಿಯುತ್ತದೆ -- lesson ನ ಮುದ್ರಿತ "Final token shape: (17, 64)" ಗೆ ನಿಖರವಾಗಿ ಹೊಂದಿಕೆಯಾಗುತ್ತಾ, ಸೇರ್ಪಡೆ ಎಂದಿಗೂ dimensionality ಬದಲಾಯಿಸುವುದಿಲ್ಲ ಆಗಿರುವುದರಿಂದ\n• ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ: [CLS] ಎಲ್ಲಾ ಶೂನ್ಯಗಳಾಗಿ ಪ್ರಾರಂಭವಾದರೂ, ಅದರ positional embedding ಸೇರಿಸುವುದೂ ನಿಜವಾಗಿ ಇದನ್ನೂ non-zero ಮಾಡುತ್ತದೆ -- ಇದೇ [CLS] token ಪಡೆಯುವ ಮೊದಲ ನಿಜ ಮಾಹಿತಿ, Transformer encoder (Part 3) ಚಲಾಯಿಸುವ ಮೊದಲೇ' } },
    { type: 'concept', data: {
      headingEn: 'Order of Operations: [CLS] Before Position', headingKn: 'ಕ್ರಮ: Position ಗಿಂತ ಮೊದಲು [CLS]',
      bodyEn: '• The lesson\'s code genuinely runs prepend_cls_token() first and add_positional_embeddings() second, never the reverse -- add_positional_embeddings() assigns one positional embedding per index in the sequence it receives, so [CLS] must already occupy index 0 before positions are assigned, or it would receive no positional embedding at all\n• Because of this ordering, [CLS] genuinely gets its own dedicated positional embedding (position 0), exactly like the 16 real patch tokens each get theirs (positions 1 through 16) -- confirmed directly by with_cls, not patch_tokens, being the input to add_positional_embeddings()',
      bodyKn: '• Lesson ನ code ನಿಜವಾಗಿ ಮೊದಲೂ prepend_cls_token() ಮತ್ತು ನಂತರ add_positional_embeddings() ಚಲಾಯಿಸುತ್ತದೆ, ಎಂದಿಗೂ ವಿರುದ್ಧವಾಗಿ ಅಲ್ಲ -- add_positional_embeddings() ಅದೂ ಪಡೆಯುವ sequence ನಲ್ಲಿ ಪ್ರತಿ index ಗೆ ಒಂದೂ positional embedding ನಿಯೋಜಿಸುತ್ತದೆ, ಆದ್ದರಿಂದ positions ನಿಯೋಜಿಸುವ ಮೊದಲೇ [CLS] index 0 ಆಕ್ರಮಿಸಬೇಕು, ಇಲ್ಲದಿದ್ದರೆ ಅದೂ ಯಾವುದೇ positional embedding ಪಡೆಯುವುದಿಲ್ಲ\n• ಈ ಕ್ರಮದ ಕಾರಣ, [CLS] ನಿಜವಾಗಿ ತನ್ನ ಸ್ವಂತ ಮೀಸಲಾದ positional embedding (position 0) ಪಡೆಯುತ್ತದೆ, 16 ನಿಜ patch tokens ಪ್ರತಿಯೊಂದೂ ತಮ್ಮದ್ದನ್ನೂ ಪಡೆಯುವಂತೆಯೇ (positions 1 ಇಂದ 16) -- with_cls, patch_tokens ಅಲ್ಲ, add_positional_embeddings() ಗೆ input ಆಗಿರುವುದರ ಮೂಲಕ ನೇರವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ' } },

    { type: 'diagram', data: {
      titleEn: 'ViT Input Preparation Pipeline', titleKn: 'ViT Input Preparation Pipeline',
      captionEn: 'Genuinely confirmed shape progression: (16,64) patch tokens -> (17,64) after [CLS] -> (17,64) position-aware.',
      captionKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ shape ಪ್ರಗತಿ: (16,64) patch tokens -> (17,64) [CLS] ನಂತರ -> (17,64) position-aware.',
      svgCode: "<svg viewBox='0 0 760 330' xmlns='http://www.w3.org/2000/svg' font-family='monospace'>\n<text x='210' y='24' fill='#e2e8f0' font-size='15' font-weight='bold'>ViT Input Preparation Pipeline</text>\n<rect x='40' y='50' width='80' height='80' fill='none' stroke='#60a5fa'/>\n<line x1='60' y1='50' x2='60' y2='130' stroke='#60a5fa'/>\n<line x1='80' y1='50' x2='80' y2='130' stroke='#60a5fa'/>\n<line x1='100' y1='50' x2='100' y2='130' stroke='#60a5fa'/>\n<line x1='40' y1='70' x2='120' y2='70' stroke='#60a5fa'/>\n<line x1='40' y1='90' x2='120' y2='90' stroke='#60a5fa'/>\n<line x1='40' y1='110' x2='120' y2='110' stroke='#60a5fa'/>\n<text x='30' y='148' fill='#94a3b8' font-size='11'>image (Part 1)</text>\n<line x1='120' y1='90' x2='168' y2='90' stroke='#94a3b8'/>\n<text x='122' y='84' fill='#94a3b8' font-size='10'>patchify + linear_embed</text>\n<rect x='172' y='70' width='36' height='40' fill='none' stroke='#60a5fa'/>\n<rect x='212' y='70' width='36' height='40' fill='none' stroke='#60a5fa'/>\n<rect x='252' y='70' width='36' height='40' fill='none' stroke='#60a5fa'/>\n<text x='296' y='96' fill='#94a3b8' font-size='14'>...</text>\n<rect x='318' y='70' width='36' height='40' fill='none' stroke='#60a5fa'/>\n<text x='172' y='128' fill='#cbd5e1' font-size='11'>16 patch tokens (16,64)</text>\n<line x1='260' y1='115' x2='260' y2='150' stroke='#94a3b8'/>\n<text x='268' y='138' fill='#94a3b8' font-size='10'>prepend_cls_token()</text>\n<rect x='172' y='160' width='36' height='40' fill='none' stroke='#fb923c'/>\n<text x='177' y='183' fill='#cbd5e1' font-size='10'>CLS</text>\n<rect x='212' y='160' width='36' height='40' fill='none' stroke='#60a5fa'/>\n<rect x='252' y='160' width='36' height='40' fill='none' stroke='#60a5fa'/>\n<text x='296' y='186' fill='#94a3b8' font-size='14'>...</text>\n<rect x='318' y='160' width='36' height='40' fill='none' stroke='#60a5fa'/>\n<text x='172' y='218' fill='#cbd5e1' font-size='11'>17 tokens (17,64), CLS = zeros</text>\n<line x1='260' y1='205' x2='260' y2='240' stroke='#94a3b8'/>\n<text x='268' y='228' fill='#94a3b8' font-size='10'>add_positional_embeddings(): Z=X+P</text>\n<rect x='172' y='250' width='36' height='40' fill='none' stroke='#4ade80'/>\n<text x='177' y='273' fill='#cbd5e1' font-size='10'>CLS</text>\n<rect x='212' y='250' width='36' height='40' fill='none' stroke='#4ade80'/>\n<rect x='252' y='250' width='36' height='40' fill='none' stroke='#4ade80'/>\n<text x='296' y='276' fill='#94a3b8' font-size='14'>...</text>\n<rect x='318' y='250' width='36' height='40' fill='none' stroke='#4ade80'/>\n<text x='172' y='308' fill='#cbd5e1' font-size='11'>(17,64) position-aware, CLS now non-zero</text>\n<text x='430' y='95' fill='#94a3b8' font-size='11'>Ready for the Transformer</text>\n<text x='430' y='110' fill='#94a3b8' font-size='11'>encoder (Part 3)</text>\n</svg>" } },

    { type: 'table', data: { captionEn: 'Shape Progression, Genuinely Confirmed', captionKn: 'Shape ಪ್ರಗತಿ, ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ',
      rows: 'Stage|Shape|Genuinely Confirmed\nPatch tokens (from Part 1)|(16, 64)|Starting point for this lesson\nAfter prepend_cls_token()|(17, 64)|16 -> 17 patches, 64 -> 64 dims\nAfter add_positional_embeddings()|(17, 64)|Addition preserves shape; [CLS] becomes non-zero' } },

    { type: 'concept', data: {
      headingEn: 'Key Takeaways', headingKn: 'ಮುಖ್ಯ ಅಂಶಗಳು',
      bodyEn: '• Genuinely confirmed: prepend_cls_token() turns (16,64) into (17,64), and the [CLS] token genuinely starts as a zero vector\n• Genuinely confirmed: add_positional_embeddings() preserves the (17,64) shape via elementwise addition, exactly matching Module 144\'s X+PE pattern\n• Genuinely confirmed: [CLS], initially zero, genuinely becomes non-zero once its positional embedding is added -- concrete evidence it is not a static placeholder but a token that actively participates in the sequence from this point forward\n• [CLS] provides a slot for a global, image-level representation to accumulate; positional embeddings tell the Transformer where each patch originated -- Part 3 shows what the Transformer encoder then does with this (17,64) sequence',
      bodyKn: '• ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ: prepend_cls_token() (16,64) ಅನ್ನೂ (17,64) ಆಗಿ ಪರಿವರ್ತಿಸುತ್ತದೆ, ಮತ್ತು [CLS] token ನಿಜವಾಗಿ ಒಂದೂ zero vector ಆಗಿ ಪ್ರಾರಂಭವಾಗುತ್ತದೆ\n• ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ: add_positional_embeddings() elementwise ಸೇರ್ಪಡೆ ಮೂಲಕ (17,64) shape ಸಂರಕ್ಷಿಸುತ್ತದೆ, Module 144 ನ X+PE ಮಾದರಿಗೆ ನಿಖರವಾಗಿ ಹೊಂದಿಕೆಯಾಗುತ್ತಾ\n• ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ: [CLS], ಆರಂಭದಲ್ಲಿ ಶೂನ್ಯ, ಅದರ positional embedding ಸೇರಿಸಿದ ಒಮ್ಮೆ ನಿಜವಾಗಿ non-zero ಆಗುತ್ತದೆ -- ಇದೂ ಒಂದೂ ಸ್ಥಿರ placeholder ಅಲ್ಲ ಆದರೆ ಈ ಬಿಂದುವಿನಿಂದ sequence ನಲ್ಲಿ ಸಕ್ರಿಯವಾಗಿ ಭಾಗವಹಿಸುವ ಒಂದೂ token ಎಂಬ ಕಾಂಕ್ರೀಟ್ ಸಾಕ್ಷ್ಯ\n• [CLS] ಒಂದೂ ಜಾಗತಿಕ, image-level representation ಸಂಗ್ರಹಿಸಲು ಒಂದೂ slot ಒದಗಿಸುತ್ತದೆ; positional embeddings Transformer ಗೆ ಪ್ರತಿ patch ಎಲ್ಲಿ ಹುಟ್ಟಿತು ಎಂದು ಹೇಳುತ್ತವೆ -- Part 3 Transformer encoder ನಂತರ ಈ (17,64) sequence ಜೊತೆ ಏನೂ ಮಾಡುತ್ತದೆ ಎಂದು ತೋರಿಸುತ್ತದೆ' } },
    { type: 'concept', data: {
      headingEn: 'AI Example', headingKn: 'AI Example',
      bodyEn: 'The exact [CLS]-token mechanism genuinely verified here -- a learnable slot that starts uninformative and accumulates a global representation through the Transformer -- is the same design borrowed directly from BERT (Module 146) and used unchanged in the real ViT-Base/16 model whose parameter count Part 3 genuinely computes; the same [CLS] embedding is what production vision systems like CLIP use as the final image representation for classification and retrieval.',
      bodyKn: 'ಇಲ್ಲಿ ನಿಜವಾಗಿ ಪರಿಶೀಲಿಸಿದ ನಿಖರ [CLS]-token ಯಂತ್ರಾಂಶ -- ಮಾಹಿತಿಯಿಲ್ಲದೆ ಪ್ರಾರಂಭವಾಗುವ ಮತ್ತು Transformer ಮೂಲಕ ಒಂದೂ ಜಾಗತಿಕ representation ಸಂಗ್ರಹಿಸುವ ಒಂದೂ ಕಲಿಯಬಹುದಾದ slot -- BERT (Module 146) ಇಂದ ನೇರವಾಗಿ ಎರವಲು ಪಡೆದ ಅದೇ ವಿನ್ಯಾಸ ಮತ್ತು Part 3 ಪ್ಯಾರಾಮೀಟರ್ ಎಣಿಕೆ ನಿಜವಾಗಿ ಗಣಿಸುವ ನಿಜ ViT-Base/16 model ನಲ್ಲಿ ಬದಲಾಗದೆ ಬಳಸಲಾಗಿದೆ; ಅದೇ [CLS] embedding CLIP ನಂತಹ production vision systems classification ಮತ್ತು retrieval ಗಾಗಿ ಅಂತಿಮ image representation ಆಗಿ ಬಳಸುತ್ತವೆ.' } },
    { type: 'concept', data: {
      headingEn: 'Why AI Uses This', headingKn: 'AI ಇದನ್ನೂ ಏಕೆ ಬಳಸುತ್ತದೆ',
      bodyEn: '• A dedicated [CLS] token (genuinely confirmed here to start at zero and become non-zero only after positional embeddings are added) gives the model one designated output slot to read a final prediction from, instead of having to pool or average all patch tokens -- this avoids diluting the image-level signal across positions of varying relevance\n• Reusing BERT\'s exact [CLS] mechanism (rather than inventing a new pooling method for vision) meant ViT could reuse the entire genuinely-verified Transformer encoder from Modules 145-146 unmodified -- this is precisely why the same encoder architecture prints identical shape guarantees whether the tokens came from words or image patches',
      bodyKn: '• ಒಂದೂ ಮೀಸಲಾದ [CLS] token (ಇಲ್ಲಿ ಶೂನ್ಯದಲ್ಲಿ ಪ್ರಾರಂಭವಾಗುತ್ತದೆ ಮತ್ತು positional embeddings ಸೇರಿಸಿದ ನಂತರ ಮಾತ್ರ non-zero ಆಗುತ್ತದೆ ಎಂದು ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ) model ಗೆ ಒಂದೂ ಗೊತ್ತುಪಡಿಸಿದ output slot ಒದಗಿಸುತ್ತದೆ ಅಂತಿಮ ಭವಿಷ್ಯವಾಣಿ ಓದಲು, ಎಲ್ಲಾ patch tokens ಅನ್ನೂ pool ಅಥವಾ average ಮಾಡಬೇಕಾದ ಬದಲು -- ಇದೂ ಬೇರೆ ಬೇರೆ ಪ್ರಸ್ತುತತೆಯ positions ಆದ್ಯಂತ image-level ಸಂಕೇತ ದುರ್ಬಲಗೊಳಿಸುವುದೂ ತಪ್ಪಿಸುತ್ತದೆ\n• BERT ನ ನಿಖರ [CLS] ಯಂತ್ರಾಂಶ ಮರುಬಳಸುವುದೂ (vision ಗಾಗಿ ಒಂದೂ ಹೊಸ pooling ವಿಧಾನ ಆವಿಷ್ಕರಿಸುವ ಬದಲು) ಎಂದರೆ ViT Modules 145-146 ಇಂದ ಸಂಪೂರ್ಣ ನಿಜವಾಗಿ-ಪರಿಶೀಲಿಸಿದ Transformer encoder ಅನ್ನೂ ಬದಲಾಗದೆ ಮರುಬಳಸಬಹುದಿತ್ತು -- ಇದೇ ನಿಖರವಾಗಿ ಏಕೆ ಅದೇ encoder architecture tokens words ಇಂದ ಬಂದಿದ್ದರೂ ಅಥವಾ image patches ಇಂದ ಬಂದಿದ್ದರೂ ಒಂದೇ shape ಖಾತರಿಗಳನ್ನೂ ನೀಡುತ್ತದೆ' } },
    { type: 'concept', data: {
      headingEn: 'Real-World Example', headingKn: 'Real-World Example',
      bodyEn: 'A production image classifier built on ViT genuinely runs the exact pipeline verified in this lesson: patchify the image, prepend [CLS] (starting at zero, as genuinely confirmed here), add positional embeddings, then feed the (17,64)-shaped sequence into the same Transformer encoder verified in Module 145. After the encoder processes all 17 tokens, only the final [CLS] token\'s representation gets passed to a classification head -- the other 16 patch-token outputs are simply discarded at that stage, having done their job of informing [CLS] through attention.',
      bodyKn: 'ViT ಮೇಲೆ ನಿರ್ಮಿಸಿದ ಒಂದೂ production image classifier ಈ lesson ನಲ್ಲಿ ಪರಿಶೀಲಿಸಿದ ನಿಖರ pipeline ಅನ್ನೂ ನಿಜವಾಗಿ ಚಲಾಯಿಸುತ್ತದೆ: image ಅನ್ನೂ patchify ಮಾಡಿ, [CLS] ಅನ್ನೂ ಪೂರ್ವಸೇರಿಸಿ (ಇಲ್ಲಿ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದಂತೆ ಶೂನ್ಯದಲ್ಲಿ ಪ್ರಾರಂಭಿಸಿ), positional embeddings ಸೇರಿಸಿ, ನಂತರ (17,64)-shaped sequence ಅನ್ನೂ Module 145 ನಲ್ಲಿ ಪರಿಶೀಲಿಸಿದ ಅದೇ Transformer encoder ಗೆ ಆಹಾರ ನೀಡಿ. Encoder ಎಲ್ಲಾ 17 tokens ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಿದ ನಂತರ, ಕೇವಲ ಅಂತಿಮ [CLS] token ನ representation ಅನ್ನೂ ಒಂದೂ classification head ಗೆ ರವಾನಿಸಲಾಗುತ್ತದೆ -- ಇತರ 16 patch-token outputs ಆ ಹಂತದಲ್ಲಿ ಕೇವಲ ತಿರಸ್ಕರಿಸಲ್ಪಡುತ್ತವೆ, attention ಮೂಲಕ [CLS] ಗೆ ಮಾಹಿತಿ ನೀಡುವ ಅವರ ಕೆಲಸ ಮಾಡಿದ ನಂತರ.' } },
    { type: 'concept', data: {
      headingEn: 'Why Zero-Initializing [CLS] Matters', headingKn: 'CLS ಅನ್ನೂ ಶೂನ್ಯ-ಆರಂಭಿಸುವುದೂ ಏಕೆ ಮುಖ್ಯ',
      bodyEn: '• Starting [CLS] as a zero vector (genuinely confirmed above) is a deliberate, neutral initialization -- the token carries no learned bias before training begins, so any information it eventually accumulates comes purely from attending to the patch tokens and its own positional embedding, not from a pre-baked assumption\n• This mirrors the same principle Module 133 established for embeddings generally: neutral, small, or zero initializations let gradient descent shape the representation from data rather than starting from an arbitrary prior',
      bodyKn: '• [CLS] ಅನ್ನೂ ಒಂದೂ zero vector ಆಗಿ ಪ್ರಾರಂಭಿಸುವುದೂ (ಮೇಲೆ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ) ಒಂದೂ ಉದ್ದೇಶಪೂರ್ವಕ, ತಟಸ್ಥ initialization -- token training ಪ್ರಾರಂಭವಾಗುವ ಮೊದಲೂ ಯಾವುದೇ ಕಲಿತ ಪಕ್ಷಪಾತ ಹೊಂದಿಲ್ಲ, ಆದ್ದರಿಂದ ಇದೂ ಅಂತಿಮವಾಗಿ ಸಂಗ್ರಹಿಸುವ ಯಾವುದೇ ಮಾಹಿತಿ ಶುದ್ಧವಾಗಿ patch tokens ಮತ್ತು ಅದರ ಸ್ವಂತ positional embedding ಗೆ attend ಮಾಡುವುದರಿಂದ ಬರುತ್ತದೆ, ಒಂದೂ ಪೂರ್ವ-ಬೇಯಿಸಿದ ಊಹೆ ಇಂದ ಅಲ್ಲ\n• ಇದೂ Module 133 embeddings ಗಾಗಿ ಸಾಮಾನ್ಯವಾಗಿ ಸ್ಥಾಪಿಸಿದ ಅದೇ ತತ್ವ ಪ್ರತಿಬಿಂಬಿಸುತ್ತದೆ: ತಟಸ್ಥ, ಚಿಕ್ಕ, ಅಥವಾ ಶೂನ್ಯ initializations gradient descent ಗೆ representation ಅನ್ನೂ data ಇಂದ ರೂಪಿಸಲು ಬಿಡುತ್ತವೆ, ಒಂದೂ ಅನಿಯಂತ್ರಿತ prior ಇಂದ ಪ್ರಾರಂಭಿಸುವ ಬದಲು' } },

    { type: 'quiz', data: { questions: [
      { q: 'Genuinely confirmed, what shape resulted from prepend_cls_token() on a (16,64) patch sequence?', qKn: '(16,64) patch sequence ಮೇಲೆ prepend_cls_token() ಇಂದ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ, ಯಾವ shape ಫಲಿತಾಂಶವಾಯಿತು?',
        opts: ['(16, 65)', '(17, 64) -- genuinely confirmed', '(17, 65)', '(15, 64)'], correct: 1,
        optsKn: ['(16, 65)', '(17, 64) -- ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ', '(17, 65)', '(15, 64)'] },
      { q: 'Genuinely tested, was the [CLS] token still an all-zero vector after add_positional_embeddings() was applied?', qKn: 'ನಿಜವಾಗಿ ಪರೀಕ್ಷಿಸಿದ, add_positional_embeddings() ಅನ್ವಯಿಸಿದ ನಂತರ [CLS] token ಇನ್ನೂ ಒಂದೂ all-zero vector ಆಗಿತ್ತೇ?',
        opts: ['Yes, it stays zero forever', 'No -- genuinely confirmed it became non-zero once its positional embedding was added', 'It became undefined', 'Only the first dimension changed'], correct: 1,
        optsKn: ['ಹೌದು, ಇದೂ ಶಾಶ್ವತವಾಗಿ ಶೂನ್ಯವಾಗಿ ಉಳಿಯುತ್ತದೆ', 'ಇಲ್ಲ -- ಅದರ positional embedding ಸೇರಿಸಿದ ಒಮ್ಮೆ ಇದೂ non-zero ಆಯಿತು ಎಂದು ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ', 'ಇದೂ ಅನಿರ್ದಿಷ್ಟವಾಯಿತು', 'ಕೇವಲ ಮೊದಲ dimension ಬದಲಾಯಿತು'] },
      { q: 'Genuinely tested, what was true about the [CLS] token immediately after prepend_cls_token(), before positional embeddings were added?', qKn: 'positional embeddings ಸೇರಿಸುವ ಮೊದಲೇ, prepend_cls_token() ನಂತರ [CLS] token ಬಗ್ಗೆ ಏನೂ ನಿಜವಾಗಿ ಪರೀಕ್ಷಿಸಲ್ಪಟ್ಟಿತ್ತು?',
        opts: ['It was already a learned summary of the image', 'It genuinely equaled [0.0]*64, an all-zero vector', 'It equaled the average of all 16 patch tokens', 'It was undefined until the encoder ran'], correct: 1,
        optsKn: ['ಇದೂ ಈಗಾಗಲೇ image ನ ಒಂದೂ ಕಲಿತ ಸಾರಾಂಶವಾಗಿತ್ತು', 'ಇದೂ ನಿಜವಾಗಿ [0.0]*64, ಒಂದೂ all-zero vector ಗೆ ಸಮವಾಗಿತ್ತು', 'ಇದೂ ಎಲ್ಲಾ 16 patch tokens ನ ಸರಾಸರಿಗೆ ಸಮವಾಗಿತ್ತು', 'encoder ಚಲಾಯಿಸುವವರೆಗೆ ಇದೂ ಅನಿರ್ದಿಷ್ಟವಾಗಿತ್ತು'] },
      { q: 'Genuinely confirmed, why does the lesson\'s code call prepend_cls_token() before add_positional_embeddings(), never the reverse?', qKn: 'Lesson ನ code ಏಕೆ add_positional_embeddings() ಗಿಂತ ಮೊದಲೂ prepend_cls_token() ಅನ್ನೂ ಕರೆಯುತ್ತದೆ, ಎಂದಿಗೂ ವಿರುದ್ಧವಾಗಿ ಅಲ್ಲ ಎಂದು ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ?',
        opts: ['Order doesn\'t matter for the final result', 'add_positional_embeddings() assigns one positional embedding per index it receives, so [CLS] must already occupy index 0 first or it would get none', 'prepend_cls_token() requires positional embeddings to already exist', 'Reversing the order would change the embedding dimension'], correct: 1,
        optsKn: ['ಅಂತಿಮ ಫಲಿತಾಂಶಕ್ಕೆ ಕ್ರಮ ಮುಖ್ಯವಲ್ಲ', 'add_positional_embeddings() ಅದೂ ಪಡೆಯುವ ಪ್ರತಿ index ಗೆ ಒಂದೂ positional embedding ನಿಯೋಜಿಸುತ್ತದೆ, ಆದ್ದರಿಂದ [CLS] ಮೊದಲೇ index 0 ಆಕ್ರಮಿಸಬೇಕು ಇಲ್ಲದಿದ್ದರೆ ಅದೂ ಯಾವುದೂ ಪಡೆಯುವುದಿಲ್ಲ', 'prepend_cls_token() ಗೆ positional embeddings ಈಗಾಗಲೇ ಅಸ್ತಿತ್ವದಲ್ಲಿರಬೇಕು', 'ಕ್ರಮ ಹಿಮ್ಮುಖಗೊಳಿಸುವುದೂ embedding dimension ಬದಲಾಯಿಸುತ್ತದೆ'] },
      { q: 'Genuinely confirmed, does add_positional_embeddings() use concatenation or addition, and what happens to the (17,64) shape as a result?', qKn: 'add_positional_embeddings() concatenation ಬಳಸುತ್ತದೆಯೇ ಅಥವಾ addition, ಮತ್ತು ಫಲಿತಾಂಶವಾಗಿ (17,64) shape ಗೆ ಏನೂ ಸಂಭವಿಸುತ್ತದೆ ಎಂದು ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ?',
        opts: ['Concatenation -- the shape grows to (17, 128)', 'Addition -- the shape genuinely stays (17, 64) throughout', 'Concatenation -- the shape grows to (34, 64)', 'Addition -- the shape shrinks to (17, 32)'], correct: 1,
        optsKn: ['Concatenation -- shape (17, 128) ಗೆ ಬೆಳೆಯುತ್ತದೆ', 'Addition -- shape ನಿಜವಾಗಿ ಆದ್ಯಂತ (17, 64) ಆಗಿ ಉಳಿಯುತ್ತದೆ', 'Concatenation -- shape (34, 64) ಗೆ ಬೆಳೆಯುತ್ತದೆ', 'Addition -- shape (17, 32) ಗೆ ಕುಗ್ಗುತ್ತದೆ'] },
    ] } },
  ],
};
