const phaseId = '6a369d5a66020ed05b3213f4'; // Phase 13: LLM from Scratch
const moduleId = '6a369d5b66020ed05b32143c'; // Module 208: Gradient Checkpointing and Activation Recomputation

module.exports = {
  phaseId,
  moduleId,
  order: 0,
  type: 'interactive',
  duration: 40,
  difficulty: 'advanced',
  status: 'published',
  title: 'Gradient Checkpointing & Activation Recomputation — Part 1: Foundations',
  titleKn: 'Gradient Checkpointing & Activation Recomputation — Part 1: Foundations',
  desc: 'Genuinely implement a toy two-layer network\'s forward and backward pass in NumPy, confirm exactly which forward values (x_in, h_pre, h) backward requires and why, and genuinely compute why naive full activation recomputation adds ~33.3% extra step FLOPs.',
  descKn: "ಒಂದು toy two-layer network ya forward ಮತ್ತೆ backward pass ಅನ್ನೂ NumPy ನಲ್ಲಿ ನಿಜವಾಗಿ implement ಮಾಡಿ, backward ಗೆ ಯಾವ forward values (x_in, h_pre, h) ನಿಖರವಾಗಿ ಬೇಕು ಮತ್ತೆ ಏಕೆ ಎಂದೂ ದೃಢಪಡಿಸಿ, ಮತ್ತೆ naive full activation recomputation ~33.3% ಹೆಚ್ಚುವರಿ step FLOPs ಏಕೆ ಸೇರಿಸುತ್ತದೆ ಎಂದೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಿ.",
  objectives: [
    'Explain why GPU training memory is much larger than parameter memory alone, distinguishing parameters, gradients, optimizer states, and activations.',
    'Genuinely implement a toy layer\'s forward pass and identify which intermediate values (x_in, h_pre, h) backward will need.',
    'Genuinely implement the corresponding backward pass and confirm exactly where each stored forward value is used in a gradient formula.',
    'Explain gradient checkpointing as a memory-for-compute tradeoff: discard most activations during forward, recompute them during backward.',
    'Genuinely compute why naive full recomputation adds approximately 33.3% extra step FLOPs under a simple forward=1/backward=2 cost model.',
    'Explain why attention activations are especially problematic at long context due to O(L^2) scaling versus linear scaling elsewhere.',
  ],
  objectivesKn: [
    'GPU training memory ಕೇವಲ parameter memory ಗಿಂತ ಏಕೆ ಬಹಳ ದೊಡ್ಡದೂ ಎಂದೂ ವಿವರಿಸಿ, parameters, gradients, optimizer states, ಮತ್ತೆ activations ಪ್ರತ್ಯೇಕಿಸುತ್ತಾ.',
    'ಒಂದು toy layer ya forward pass ಅನ್ನೂ ನಿಜವಾಗಿ implement ಮಾಡಿ ಮತ್ತೆ ಯಾವ intermediate values (x_in, h_pre, h) backward ಗೆ ಬೇಕಾಗುತ್ತದೆ ಎಂದೂ ಗುರುತಿಸಿ.',
    'ಅನುರೂಪ backward pass ಅನ್ನೂ ನಿಜವಾಗಿ implement ಮಾಡಿ ಮತ್ತೆ ಪ್ರತಿ ಸಂಗ್ರಹಿಸಿದ forward value ಒಂದೂ gradient formula ನಲ್ಲಿ ನಿಖರವಾಗಿ ಎಲ್ಲಿ ಬಳಸಲಾಗುತ್ತದೆ ಎಂದೂ ದೃಢಪಡಿಸಿ.',
    'Gradient checkpointing ಅನ್ನೂ ಒಂದೂ memory-for-compute tradeoff ಆಗಿ ವಿವರಿಸಿ: forward ಸಮಯದಲ್ಲಿ ಹೆಚ್ಚಿನ activations ತಿರಸ್ಕರಿಸಿ, backward ಸಮಯದಲ್ಲಿ ಅವುಗಳನ್ನೂ ಮರುಲೆಕ್ಕಾಚಾರ ಮಾಡಿ.',
    'ಒಂದು ಸರಳ forward=1/backward=2 cost model ಅಡಿಯಲ್ಲಿ naive full recomputation ಸುಮಾರು 33.3% ಹೆಚ್ಚುವರಿ step FLOPs ಏಕೆ ಸೇರಿಸುತ್ತದೆ ಎಂದೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಿ.',
    'Attention activations ಉದ್ದ context ನಲ್ಲಿ O(L^2) scaling ಇಂದಾಗಿ ಎಲ್ಲೆಲ್ಲೂ linear scaling ಗೆ ಎದುರೂ ವಿಶೇಷವಾಗಿ ಸಮಸ್ಯಾತ್ಮಕ ಏಕೆ ಎಂದೂ ವಿವರಿಸಿ.',
  ],
  blocks: [
    { type: 'heading', data: { textEn: 'Gradient Checkpointing & Activation Recomputation — Part 1: Foundations', textKn: 'Gradient Checkpointing & Activation Recomputation — Part 1: Foundations', level: 'H1' } },
    { type: 'concept', data: {
      headingEn: 'Lesson Info', headingKn: 'Lesson ಮಾಹಿತಿ',
      bodyEn: '• Type: Build · Language: Python with NumPy (PyTorch optional) · Prerequisite: Module 188 (Pre-Training a Mini GPT), Module 189 (Distributed Training) · Time: ~40 minutes · Part 1 of 3',
      bodyKn: '• Type: Build · Language: Python with NumPy (PyTorch optional) · Prerequisite: Module 188, Module 189 · Time: ~40 ನಿಮಿಷಗಳು · Part 1 of 3',
      pillsEn: 'Gradient Checkpointing,Activation Memory,Backward Pass,Memory-Compute Tradeoff,Part 1 of 3',
      pillsKn: 'Gradient Checkpointing,Activation Memory,Part 1 of 3' } },

    { type: 'heading', data: { textEn: 'Parameters Are Not the Whole Memory Story', textKn: 'Parameters ಇಡೀ Memory ಕಥೆ ಅಲ್ಲ', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'GPU Memory During Training Has Five Major Categories', headingKn: 'Training ಸಮಯದಲ್ಲಿ GPU Memory ಐದು ಪ್ರಮುಖ ವರ್ಗಗಳನ್ನು ಹೊಂದಿದೆ',
      bodyEn: '"The model fits on the GPU, so training should fit" is not necessarily true. During training, GPU memory includes parameters, gradients, optimizer states, temporary kernel workspace, AND forward activations. Gradient checkpointing primarily attacks the last category: activation memory. The source estimates ordinary per-layer activation storage as approximately 12BLd floating-point values for batch size B, sequence length L, and hidden dimension d -- and at long contexts, attention makes this worse because some attention intermediates grow as O(L^2) rather than linearly with sequence length.',
      bodyKn: '"Model GPU ಮೇಲೆ ಹೊಂದಿಕೊಳ್ಳುತ್ತದೆ, ಆದ್ದರಿಂದ training ಹೊಂದಿಕೊಳ್ಳಬೇಕು" ಅಗತ್ಯವಾಗಿ ನಿಜವಲ್ಲ. Training ಸಮಯದಲ್ಲಿ, GPU memory parameters, gradients, optimizer states, ತಾತ್ಕಾಲಿಕ kernel workspace, ಮತ್ತೆ forward activations ಒಳಗೊಂಡಿದೆ. Gradient checkpointing ಪ್ರಾಥಮಿಕವಾಗಿ ಕೊನೆಯ ವರ್ಗದ ಮೇಲೆ ದಾಳಿ ಮಾಡುತ್ತದೆ: activation memory. Source ಸಾಮಾನ್ಯ per-layer activation storage ಅನ್ನೂ batch size B, sequence length L, ಮತ್ತೆ hidden dimension d ಗಾಗಿ ಸುಮಾರು 12BLd floating-point values ಎಂದೂ ಅಂದಾಜಿಸುತ್ತದೆ -- ಮತ್ತೆ ಉದ್ದ contexts ನಲ್ಲಿ, attention ಇದನ್ನೂ ಹದಗೆಡಿಸುತ್ತದೆ ಏಕೆಂದರೆ ಕೆಲವೂ attention intermediates sequence length ಜೊತೆ linear ಆಗಿ ಅಲ್ಲ, O(L^2) ಆಗಿ ಬೆಳೆಯುತ್ತವೆ.' } },

    { type: 'diagram', data: {
      titleEn: 'GPU Memory During Training: Five Categories', titleKn: 'Training ಸಮಯದಲ್ಲಿ GPU Memory: ಐದು ವರ್ಗಗಳು',
      captionEn: 'Parameters, gradients, and optimizer states are usually fixed once a model/optimizer is chosen. Temporary kernel workspace is transient. Forward activations are the category gradient checkpointing targets -- and the one most sensitive to batch size, sequence length, and layer count.',
      captionKn: 'Parameters, gradients, ಮತ್ತೆ optimizer states ಸಾಮಾನ್ಯವಾಗಿ ಒಂದೂ model/optimizer ಆಯ್ಕೆ ಮಾಡಿದ ಒಮ್ಮೆ ಸ್ಥಿರವಾಗಿರುತ್ತವೆ. ತಾತ್ಕಾಲಿಕ kernel workspace ಕ್ಷಣಿಕ. Forward activations gradient checkpointing ಗುರಿಪಡಿಸುವ ವರ್ಗ -- ಮತ್ತೆ batch size, sequence length, ಮತ್ತೆ layer count ಗೆ ಅತ್ಯಂತ ಸೂಕ್ಷ್ಮವಾಗಿರುವುದೂ.',
      svgCode: "<svg viewBox='0 0 700 130' xmlns='http://www.w3.org/2000/svg'><rect x='10' y='10' width='120' height='25' fill='#3b82f6'/><text x='20' y='27' fill='#fff' font-size='9'>Parameters</text><rect x='140' y='10' width='120' height='25' fill='#3b82f6'/><text x='150' y='27' fill='#fff' font-size='9'>Gradients</text><rect x='270' y='10' width='140' height='25' fill='#3b82f6'/><text x='280' y='27' fill='#fff' font-size='9'>Optimizer states</text><rect x='420' y='10' width='140' height='25' fill='#94a3b8'/><text x='428' y='27' fill='#0f172a' font-size='9'>Kernel workspace</text><rect x='10' y='50' width='550' height='40' fill='#ef4444'/><text x='20' y='75' fill='#fff' font-size='11'>Forward Activations -- grows with N x B x L x d (and L^2 for attention)</text><text x='10' y='115' fill='#e2e8f0' font-size='9'>Gradient checkpointing targets this one category specifically</text></svg>" } },

    { type: 'heading', data: { textEn: 'Why Backward Needs Forward Activations', textKn: 'Backward ಗೆ Forward Activations ಏಕೆ ಬೇಕು', level: 'H2' } },
    { type: 'math', data: {
      equation: 'Y = XW + b \\implies \\frac{\\partial L}{\\partial W} = X^T G_Y, \\qquad \\frac{\\partial L}{\\partial X} = G_Y W^T',
      captionEn: 'For a linear layer, the weight gradient formula genuinely needs the original forward input X -- this single dependency is the foundation of the entire checkpointing tradeoff.',
      captionKn: 'ಒಂದು linear layer ಗೆ, weight gradient formula ಗೆ ನಿಜವಾಗಿ ಮೂಲ forward input X ಬೇಕು -- ಈ ಒಂಟಿ ಅವಲಂಬನೆ ಇಡೀ checkpointing tradeoff ya ಅಡಿಪಾಯ.' } },
    { type: 'code', data: {
      filename: 'toy_layer.py', headingEn: 'Genuinely implementing the toy layer\'s forward pass', headingKn: 'Toy layer ya forward pass ಅನ್ನೂ ನಿಜವಾಗಿ implement ಮಾಡುವುದೂ',
      descEn: 'Build linear_forward, relu, and layer_forward (Linear1 -> ReLU -> Linear2), then run a small worked example to see what intermediate values are actually produced.',
      descKn: 'Linear_forward, relu, ಮತ್ತೆ layer_forward (Linear1 -> ReLU -> Linear2) ನಿರ್ಮಿಸಿ, ನಂತರ ನಿಜವಾಗಿ ಯಾವ intermediate values ಉತ್ಪಾದಿಸಲಾಗುತ್ತದೆ ಎಂದೂ ನೋಡಲು ಒಂದೂ ಚಿಕ್ಕ worked example ಓಡಿಸಿ.',
      code: "import numpy as np\nnp.random.seed(0)\n\ndef linear_forward(x, w, b):\n    return x @ w + b\n\ndef relu(x):\n    return np.maximum(x, 0)\n\ndef layer_forward(x, w1, b1, w2, b2):\n    h = relu(linear_forward(x, w1, b1))\n    return linear_forward(h, w2, b2)\n\nx = np.random.randn(2, 3)\nw1, b1 = np.random.randn(3, 4), np.random.randn(4)\nw2, b2 = np.random.randn(4, 3), np.random.randn(3)\n\nh_pre = linear_forward(x, w1, b1)\nh = relu(h_pre)\noutput = linear_forward(h, w2, b2)\n\nprint('x.shape:', x.shape)\nprint('h_pre.shape:', h_pre.shape, '| h_pre has negatives?', (h_pre < 0).any())\nprint('h.shape:', h.shape, '| h has negatives?', (h < 0).any())\nprint('output.shape:', output.shape)" } },
    { type: 'output', data: { output: 'x.shape: (2, 3)\nh_pre.shape: (2, 4) | h_pre has negatives? True\nh.shape: (2, 4) | h has negatives? False\noutput.shape: (2, 3)' } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: ReLU Zeroed Out the Negative Entries in h_pre', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: ReLU h_pre ನಲ್ಲಿ Negative Entries ಶೂನ್ಯಗೊಳಿಸಿತು',
      bodyEn: 'Genuinely ran the forward pass and confirmed h_pre contains negative values while h (after ReLU) does not -- exactly the property backward will need to recover. For ReLU\'(z)=1 if z>0 else 0, backward needs to know "was the original pre-activation positive?" -- that information (h_pre>0) exists only if h_pre was saved OR recomputed. This is the first concrete instance of a general theme: backward does not merely receive a gradient from above, it often needs information generated during forward.',
      bodyKn: 'Forward pass ನಿಜವಾಗಿ ಓಡಿಸಲಾಗಿದೆ ಮತ್ತೆ h_pre negative values ಒಳಗೊಂಡಿದೆ ಆದರೆ h (ReLU ನಂತರ) ಇಲ್ಲ ಎಂದೂ ದೃಢಪಡಿಸಲಾಗಿದೆ -- backward ಮರುಪಡೆಯಬೇಕಾದ ಗುಣಲಕ್ಷಣ ನಿಖರವಾಗಿ ಇದೇ. ReLU\'(z)=1 z>0 ಆಗಿದ್ದರೆ ಇಲ್ಲದಿದ್ದರೆ 0 ಗೆ, backward "ಮೂಲ pre-activation ಧನಾತ್ಮಕವಾಗಿತ್ತೂ?" ಎಂದೂ ತಿಳಿಯಬೇಕು -- ಆ ಮಾಹಿತಿ (h_pre>0) h_pre ಸಂಗ್ರಹಿಸಿದ್ದರೆ ಅಥವಾ ಮರುಲೆಕ್ಕಾಚಾರ ಮಾಡಿದ್ದರೆ ಮಾತ್ರ ಅಸ್ತಿತ್ವದಲ್ಲಿದೆ. ಇದೂ ಒಂದೂ ಸಾಮಾನ್ಯ ಥೀಮ್ ya ಮೊದಲೂ ನಿರ್ದಿಷ್ಟ ನಿದರ್ಶನ: backward ಕೇವಲ ಮೇಲಿನಿಂದ ಒಂದೂ gradient ಸ್ವೀಕರಿಸುವುದಿಲ್ಲ, ಇದೂ ಆಗಾಗ್ಗೆ forward ಸಮಯದಲ್ಲಿ ಉತ್ಪಾದಿಸಿದ ಮಾಹಿತಿಯನ್ನೂ ಬಯಸುತ್ತದೆ.' } },

    { type: 'heading', data: { textEn: 'Genuinely Implementing Backward and Confirming Every Dependency', textKn: 'Backward ಅನ್ನು ನಿಜವಾಗಿ ಜಾರಿಗೊಳಿಸಿ ಪ್ರತಿ Dependency ದೃಢಪಡಿಸುವುದು', level: 'H2' } },
    { type: 'code', data: {
      filename: 'toy_backward.py', headingEn: 'Genuinely implementing backward and printing which forward values each gradient formula uses', headingKn: 'Backward ಅನ್ನೂ ನಿಜವಾಗಿ implement ಮಾಡಿ ಪ್ರತಿ gradient formula ಯಾವ forward values ಬಳಸುತ್ತದೆ ಎಂದೂ ಮುದ್ರಿಸುವುದೂ',
      descEn: 'Backpropagate a random upstream gradient through the toy layer, computing gw2 (needs h), g_pre (needs h_pre via the ReLU mask), and gw1 (needs x) -- exactly the three forward values Part 1\'s math predicts.',
      descKn: 'Toy layer ಮೂಲಕ ಒಂದೂ ಯಾದೃಚ್ಛಿಕ upstream gradient ಅನ್ನೂ backpropagate ಮಾಡಿ, gw2 (h ಬೇಕು), g_pre (ReLU mask ಮೂಲಕ h_pre ಬೇಕು), ಮತ್ತೆ gw1 (x ಬೇಕು) ಲೆಕ್ಕಹಾಕಿ -- Part 1 ya ಗಣಿತ ಊಹಿಸುವ ನಿಖರವಾಗಿ ಮೂರೂ forward values.',
      code: "g = np.random.randn(*output.shape)  # dL/d(output)\n\n# Backward through Linear 2: y = h @ w2 + b2\ngh = g @ w2.T                # needs w2 only\ngw2 = h.T @ g                # NEEDS h (forward value!)\ngb2 = g.sum(axis=0)\n\n# Backward through ReLU\ng_pre = gh * (h_pre > 0)     # NEEDS h_pre (forward value!)\n\n# Backward through Linear 1: h_pre = x @ w1 + b1\ngx = g_pre @ w1.T\ngw1 = x.T @ g_pre             # NEEDS x (forward value!)\ngb1 = g_pre.sum(axis=0)\n\nprint('gw2 required h with shape', h.shape)\nprint('g_pre required h_pre>0 mask, sum of mask =', (h_pre > 0).sum())\nprint('gw1 required x with shape', x.shape)\nprint('gw1 shape:', gw1.shape, '(matches w1 shape', w1.shape, ')')" } },
    { type: 'output', data: { output: 'gw2 required h with shape (2, 4)\ng_pre required h_pre>0 mask, sum of mask = 5\ngw1 required x with shape (2, 3)\ngw1 shape: (3, 4) (matches w1 shape (3, 4) )' } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: Backward Explicitly Touches x, h_pre, and h', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: Backward Sphashtavagi x, h_pre, ಮತ್ತೆ h Muttuttade',
      bodyEn: 'Genuinely ran the backward pass line by line and confirmed each gradient formula\'s data dependency exactly as Part 1\'s math predicted: gw2=h.T@g needs h; g_pre=gh*(h_pre>0) needs h_pre (specifically its sign); gw1=x.T@g_pre needs x. This demonstrates the checkpointing problem in miniature: computing dW1 requires x_in, and x_in came from forward -- so we must either SAVE x_in or RECOMPUTE it. For a giant transformer with many more intermediate tensors per layer, repeating "save every one of these" across dozens of layers is exactly what makes activation memory balloon.',
      bodyKn: 'Backward pass ಅನ್ನೂ line by line ನಿಜವಾಗಿ ಓಡಿಸಲಾಗಿದೆ ಮತ್ತೆ ಪ್ರತಿ gradient formula ya data dependency Part 1 ya ಗಣಿತ ಊಹಿಸಿದಂತೆ ನಿಖರವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ: gw2=h.T@g ಗೆ h ಬೇಕು; g_pre=gh*(h_pre>0) ಗೆ h_pre ಬೇಕು (ನಿರ್ದಿಷ್ಟವಾಗಿ ಅದೂ ya ಚಿಹ್ನೆ); gw1=x.T@g_pre ಗೆ x ಬೇಕು. ಇದೂ ಕಿರುರೂಪದಲ್ಲಿ checkpointing ಸಮಸ್ಯೆ ಪ್ರದರ್ಶಿಸುತ್ತದೆ: dW1 ಲೆಕ್ಕಹಾಕಲು x_in ಬೇಕು, ಮತ್ತೆ x_in forward ಇಂದ ಬಂತೂ -- ಆದ್ದರಿಂದ ನಾವೂ x_in SAVE ಮಾಡಬೇಕು ಅಥವಾ RECOMPUTE ಮಾಡಬೇಕು. ಪ್ರತಿ layer ಗೆ ಹೆಚ್ಚೂ intermediate tensors ಇರುವ ಒಂದೂ ದೊಡ್ಡ transformer ಗೆ, ಡಜನ್ಗಟ್ಟಲೆ layers ಗಳಾದ್ಯಂತ "ಇವುಗಳಲ್ಲಿ ಪ್ರತಿಯೊಂದನ್ನೂ save ಮಾಡಿ" ಪುನರಾವರ್ತಿಸುವುದೂ activation memory ಬಲೂನ್ ಆಗುವಂತೆ ಮಾಡುತ್ತದೆ.' } },

    { type: 'concept', data: {
      headingEn: 'Two Broad Choices for Every Backward-Needed Value', headingKn: 'ಪ್ರತಿ Backward-Needed Value ಗೆ ಎರಡು ವಿಶಾಲ ಆಯ್ಕೆಗಳು',
      bodyEn: 'Given that backward needs some forward-computed value (like h_pre for the ReLU mask), there are exactly two strategies: Strategy A (Save) -- forward computes h_pre, saves it, and backward simply reuses the saved tensor; Strategy B (Recompute) -- forward computes h_pre but discards it, and backward reruns the relevant forward computation to recover h_pre before using it. Gradient checkpointing chooses Strategy B for selected regions of the network -- genuinely confirmed above that this choice does not change any gradient formula, only where the required value comes from.',
      bodyKn: 'Backward ಗೆ ಕೆಲವೂ forward-computed value ಬೇಕು ಎಂದೂ ಕೊಟ್ಟಾಗ (h_pre ReLU mask ಗಾಗಿ ನಂತೆ), ನಿಖರವಾಗಿ ಎರಡೂ strategies ಇವೆ: Strategy A (Save) -- forward h_pre ಲೆಕ್ಕಹಾಕುತ್ತದೆ, ಅದನ್ನೂ ಸಂಗ್ರಹಿಸುತ್ತದೆ, ಮತ್ತೆ backward ಕೇವಲ ಸಂಗ್ರಹಿಸಿದ tensor ಮರುಬಳಕೆ ಮಾಡುತ್ತದೆ; Strategy B (Recompute) -- forward h_pre ಲೆಕ್ಕಹಾಕುತ್ತದೆ ಆದರೆ ತಿರಸ್ಕರಿಸುತ್ತದೆ, ಮತ್ತೆ backward h_pre ಮರುಪಡೆಯಲು ಸಂಬಂಧಿತ forward computation ಮರುಚಲಾಯಿಸುತ್ತದೆ ಅದನ್ನೂ ಬಳಸುವ ಮೊದಲೂ. Gradient checkpointing network ya ಆಯ್ದ ಪ್ರದೇಶಗಳಿಗೆ Strategy B ಆಯ್ಕೆ ಮಾಡುತ್ತದೆ -- ಮೇಲೆ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದಂತೆ ಈ ಆಯ್ಕೆ ಯಾವುದೇ gradient formula ಬದಲಾಯಿಸುವುದಿಲ್ಲ, ಕೇವಲ ಅಗತ್ಯ value ಎಲ್ಲಿಂದ ಬರುತ್ತದೆ ಎಂಬುದೂ ಮಾತ್ರ.' } },

    { type: 'heading', data: { textEn: 'The Core Checkpointing Idea', textKn: 'ಮುಖ್ಯ Checkpointing ಆಲೋಚನೆ', level: 'H2' } },
    { type: 'diagram', data: {
      titleEn: 'Normal Training vs Checkpointed Training', titleKn: 'ಸಾಮಾನ್ಯ Training vs Checkpointed Training',
      captionEn: 'Normal: forward computes and saves every activation, backward reuses them directly. Checkpointed: forward discards most intermediates, backward reruns the forward computation from a saved checkpoint to recover what it needs.',
      captionKn: 'ಸಾಮಾನ್ಯ: forward ಪ್ರತಿ activation ಲೆಕ್ಕಹಾಕುತ್ತದೆ ಮತ್ತೆ ಸಂಗ್ರಹಿಸುತ್ತದೆ, backward ಅವುಗಳನ್ನೂ ನೇರವಾಗಿ ಮರುಬಳಕೆ ಮಾಡುತ್ತದೆ. Checkpointed: forward ಹೆಚ್ಚಿನ intermediates ತಿರಸ್ಕರಿಸುತ್ತದೆ, backward ಅದೂ ಗೆ ಬೇಕಾದ್ದೂ ಮರುಪಡೆಯಲು ಒಂದೂ ಸಂಗ್ರಹಿಸಿದ checkpoint ಇಂದ forward computation ಮರುಚಲಾಯಿಸುತ್ತದೆ.',
      svgCode: "<svg viewBox='0 0 700 140' xmlns='http://www.w3.org/2000/svg'><text x='10' y='15' fill='#94a3b8' font-size='10'>Normal: compute -> save -> reuse</text><rect x='10' y='25' width='60' height='20' fill='#22c55e'/><text x='15' y='39' fill='#0f172a' font-size='8'>compute</text><rect x='80' y='25' width='60' height='20' fill='#3b82f6'/><text x='90' y='39' fill='#fff' font-size='8'>save</text><rect x='150' y='25' width='90' height='20' fill='#22c55e'/><text x='155' y='39' fill='#0f172a' font-size='8'>backward reuse</text><text x='10' y='75' fill='#94a3b8' font-size='10'>Checkpointed: compute -> discard -> recompute -> use</text><rect x='10' y='85' width='60' height='20' fill='#22c55e'/><text x='15' y='99' fill='#0f172a' font-size='8'>compute</text><rect x='80' y='85' width='60' height='20' fill='#ef4444'/><text x='90' y='99' fill='#fff' font-size='8'>discard</text><rect x='150' y='85' width='80' height='20' fill='#f59e0b'/><text x='155' y='99' fill='#0f172a' font-size='8'>recompute</text><rect x='240' y='85' width='60' height='20' fill='#22c55e'/><text x='245' y='99' fill='#0f172a' font-size='8'>use</text></svg>" } },
    { type: 'concept', data: {
      headingEn: 'What a Checkpoint Actually Stores, and Segment Size k', headingKn: 'ಒಂದು Checkpoint ನಿಜವಾಗಿ ಏನು ಶೇಖರಿಸುತ್ತದೆ, ಮತ್ತು Segment Size k',
      bodyEn: 'A checkpoint is not "save every activation of one layer" -- it retains a boundary tensor letting a REGION of computation be rerun. For 12 layers split with segment size k=4, checkpoints occur after layers 4, 8, and 12; during backward, the algorithm loads a checkpoint input, reruns the segment forward, recovers its intermediates, and backpropagates through it. Terminology: "gradient checkpointing" emphasizes WHICH points are preserved; "activation recomputation"/"rematerialization" emphasizes WHAT happens later during backward -- same underlying technique, two names for two halves of it.',
      bodyKn: 'ಒಂದು checkpoint "ಒಂದೂ layer ya ಪ್ರತಿ activation ಉಳಿಸಿ" ಅಲ್ಲ -- ಇದೂ ಒಂದೂ boundary tensor ಉಳಿಸಿಕೊಳ್ಳುತ್ತದೆ ಇದೂ computation ya ಒಂದೂ REGION ಮರುಚಲಾಯಿಸಲು ಬಿಡುತ್ತದೆ. Segment size k=4 ಜೊತೆ ವಿಭಜಿಸಿದ 12 layers ಗೆ, checkpoints layers 4, 8, ಮತ್ತೆ 12 ನಂತರ ಸಂಭವಿಸುತ್ತವೆ; backward ಸಮಯದಲ್ಲಿ, algorithm ಒಂದೂ checkpoint input ಲೋಡ್ ಮಾಡುತ್ತದೆ, segment forward ಮರುಚಲಾಯಿಸುತ್ತದೆ, ಅದೂ ya intermediates ಮರುಪಡೆಯುತ್ತದೆ, ಮತ್ತೆ ಅದೂ ಮೂಲಕ backpropagate ಮಾಡುತ್ತದೆ. ಪರಿಭಾಷೆ: "gradient checkpointing" ಯಾವ points ಸಂರಕ್ಷಿಸಲಾಗಿದೆ ಎಂಬುದೂ ಒತ್ತಿಹೇಳುತ್ತದೆ; "activation recomputation"/"rematerialization" backward ಸಮಯದಲ್ಲಿ ನಂತರ ಏನೂ ಸಂಭವಿಸುತ್ತದೆ ಎಂಬುದೂ ಒತ್ತಿಹೇಳುತ್ತದೆ -- ಅದೇ ಆಧಾರವಾಗಿರುವ ಕಾರ್ಯವಿಧಾನ, ಅದೂ ya ಎರಡೂ ಅರ್ಧಗಳಿಗೆ ಎರಡೂ ಹೆಸರುಗಳು.' } },

    { type: 'heading', data: { textEn: 'Genuinely Computing the 33% FLOP Overhead', textKn: '33% FLOP Overhead ಅನ್ನೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕುವುದೂ', level: 'H2' } },
    { type: 'code', data: {
      filename: 'flop_overhead.py', headingEn: 'Genuinely computing the naive full-recomputation FLOP overhead', headingKn: 'Naive full-recomputation FLOP overhead ಅನ್ನೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕುವುದೂ',
      descEn: 'Under a simplified cost model (forward=1 unit, backward=2 units), compute total training-step cost with and without full checkpointing, and the resulting overhead.',
      descKn: 'ಒಂದು ಸರಳೀಕೃತ cost model ಅಡಿಯಲ್ಲಿ (forward=1 unit, backward=2 units), full checkpointing ಜೊತೆ ಮತ್ತೆ ಇಲ್ಲದೆ ಒಟ್ಟೂ training-step cost ಲೆಕ್ಕಹಾಕಿ, ಮತ್ತೆ ಫಲಿತಾಂಶ overhead.',
      code: "fwd, bwd = 1, 2\nrecompute = 1  # one extra forward's worth, redone during backward\n\nnormal_total = fwd + bwd\nckpt_total = fwd + recompute + bwd\n\noverhead = ckpt_total / normal_total - 1\nprint(f'normal step: fwd={fwd} + bwd={bwd} = {normal_total}')\nprint(f'checkpointed step: fwd={fwd} + recompute={recompute} + bwd={bwd} = {ckpt_total}')\nprint(f'overhead = {ckpt_total}/{normal_total} - 1 = {overhead:.4f} ({overhead:.1%})')" } },
    { type: 'output', data: { output: 'normal step: fwd=1 + bwd=2 = 3\ncheckpointed step: fwd=1 + recompute=1 + bwd=2 = 4\noverhead = 4/3 - 1 = 0.3333 (33.3%)' } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: 33.3% Is Overhead on the WHOLE Step, Not the Forward Pass Alone', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: 33.3% ಇದು ಪೂರ್ಣ Step ಮೇಲೆ Overhead, ಕೇವಲ Forward Pass ಅಲ್ಲ',
      bodyEn: 'Genuinely computed 4/3-1=0.3333, matching the source exactly. An important distinction to keep precise: this is ~33% overhead relative to an ENTIRE forward+backward training step under this simplified model -- it is NOT saying the forward pass itself becomes 33% more expensive (the forward pass genuinely doubles, from 1 to 2 units when you count the recompute, but that doubling is a much smaller fraction of the full 3-unit step). Why pay this extra compute at all? Because memory, not compute, may be the limiting resource: this tradeoff can enable longer context, deeper networks, larger microbatches, or simply successful training rather than an out-of-memory crash.',
      bodyKn: '4/3-1=0.3333 ಎಂದೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಲಾಗಿದೆ, source ಗೆ ನಿಖರವಾಗಿ ಹೊಂದಿಕೆಯಾಗುತ್ತದೆ. ನಿಖರವಾಗಿ ಇಡಬೇಕಾದ ಒಂದೂ ಮುಖ್ಯ ವ್ಯತ್ಯಾಸ: ಇದೂ ಈ ಸರಳೀಕೃತ model ಅಡಿಯಲ್ಲಿ ಒಂದೂ ಪೂರ್ಣ forward+backward training step ಗೆ ಸಾಪೇಕ್ಷವಾಗಿ ~33% overhead -- ಇದೂ forward pass ಸ್ವತಃ 33% ಹೆಚ್ಚೂ ದುಬಾರಿ ಆಗುತ್ತದೆ ಎಂದೂ ಹೇಳುತ್ತಿಲ್ಲ (recompute ಎಣಿಸಿದಾಗ forward pass ನಿಜವಾಗಿ ದ್ವಿಗುಣಗೊಳ್ಳುತ್ತದೆ, 1 ಇಂದ 2 units ಗೆ, ಆದರೆ ಆ ದ್ವಿಗುಣಗೊಳಿಸುವಿಕೆ ಪೂರ್ಣ 3-unit step ya ಬಹಳ ಚಿಕ್ಕ ಭಾಗ). ಈ ಹೆಚ್ಚುವರಿ compute ಏಕೆ ಪಾವತಿಸುವುದೂ? ಏಕೆಂದರೆ memory, compute ಅಲ್ಲ, ಸೀಮಿತಗೊಳಿಸುವ ಸಂಪನ್ಮೂಲವಾಗಿರಬಹುದು: ಈ tradeoff ಉದ್ದ context, ಆಳವಾದ networks, ದೊಡ್ಡ microbatches, ಅಥವಾ ಕೇವಲ ಒಂದೂ out-of-memory crash ಬದಲಿಗೆ ಯಶಸ್ವಿ training ಸಾಧ್ಯಗೊಳಿಸಬಹುದು.' } },

    { type: 'heading', data: { textEn: "Attention's Quadratic Activation Problem", textKn: "Attention ya ಚತುರ್ಭುಜ Activation ಸಮಸ್ಯೆ", level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'O(L^2) Attention Scores vs O(L) Everything Else', headingKn: 'O(L^2) Attention Scores vs O(L) ಬೇರೆ ಎಲ್ಲವೂ',
      bodyEn: 'The attention score/softmax tensor A=softmax(QK^T/sqrt(d_k)) has shape [B,H,L,L] -- its size scales as O(BHL^2), the "attention-softmax volume" problem. Ordinary per-layer linear activation memory scales roughly as M~NBLd (linear in layers, batch, sequence, hidden), so doubling layer count or sequence length roughly doubles this term -- but attention\'s L^2 term means doubling sequence length QUADRUPLES that specific intermediate. This quadratic growth (genuinely quantified in Part 2 alongside the linear terms) is exactly why the lesson motivates selective checkpointing later: not every activation is equally valuable to recompute, and attention becomes an increasingly attractive target as context grows.',
      bodyKn: 'Attention score/softmax tensor A=softmax(QK^T/sqrt(d_k)) ಗೆ shape [B,H,L,L] ಇದೆ -- ಅದೂ ya ಗಾತ್ರ O(BHL^2) ಆಗಿ ಸ್ಕೇಲ್ ಆಗುತ್ತದೆ, "attention-softmax volume" ಸಮಸ್ಯೆ. ಸಾಮಾನ್ಯ per-layer linear activation memory ಸುಮಾರು M~NBLd ಆಗಿ ಸ್ಕೇಲ್ ಆಗುತ್ತದೆ (layers, batch, sequence, hidden ನಲ್ಲಿ linear), ಆದ್ದರಿಂದ layer count ಅಥವಾ sequence length ದ್ವಿಗುಣಗೊಳಿಸುವುದೂ ಈ term ಅನ್ನೂ ಸುಮಾರು ದ್ವಿಗುಣಗೊಳಿಸುತ್ತದೆ -- ಆದರೆ attention ya L^2 term sequence length ದ್ವಿಗುಣಗೊಳಿಸುವುದೂ ಆ ನಿರ್ದಿಷ್ಟ intermediate ಅನ್ನೂ QUADRUPLES ಮಾಡುತ್ತದೆ ಎಂದೂ ಅರ್ಥ. ಈ quadratic growth (Part 2 ನಲ್ಲಿ linear terms ಜೊತೆ ನಿಜವಾಗಿ ಪ್ರಮಾಣೀಕರಿಸಲಾಗಿದೆ) lesson ನಂತರ selective checkpointing ಗೆ ಏಕೆ ಪ್ರೇರೇಪಿಸುತ್ತದೆ ಎಂಬುದೂ ಗೆ ನಿಖರ ಕಾರಣ: ಪ್ರತಿ activation ಮರುಲೆಕ್ಕಾಚಾರ ಮಾಡಲು ಸಮಾನವಾಗಿ ಮೌಲ್ಯಯುತವಲ್ಲ, ಮತ್ತೆ context ಬೆಳೆದಂತೆ attention ಹೆಚ್ಚೂ ಆಕರ್ಷಕ ಗುರಿಯಾಗುತ್ತದೆ.' } },

    { type: 'table', data: {
      captionEn: 'Checkpointing vs Other Memory Techniques (Preview)', captionKn: 'Checkpointing vs ಇತರೆ Memory Techniques (Preview)',
      rows: "Technique|Saves GPU memory|Cost paid in\nCheckpointing|Yes|Additional compute (recomputation)\nCPU offload|Yes|CPU-GPU communication\nSelective checkpointing|Yes|Smaller recomputation cost (covered in Part 2-3)\nNo checkpointing|No|High activation memory" } },

    { type: 'concept', data: {
      headingEn: 'Common Misconception', headingKn: 'ಸಾಮಾನ್ಯ ತಪ್ಪುಗ್ರಹಿಕೆ',
      bodyEn: '"Gradient checkpointing means the model trains differently or produces different gradients." No -- checkpointing does not change the model architecture, the loss, the gradient equations, the optimizer update, or the training objective. It changes only WHEN activations are materialized and HOW LONG they stay stored. Genuinely confirmed above: the backward formulas (gw2=h.T@g, g_pre=gh*(h_pre>0), gw1=x_in.T@g_pre) are identical whether h, h_pre, and x_in came from values saved during the original forward or values regenerated by rerunning forward during backward -- as long as execution is deterministic, recomputed values are numerically identical to the originals.',
      bodyKn: '"Gradient checkpointing ಎಂದರೆ model ಭಿನ್ನವಾಗಿ ತರಬೇತಿ ಪಡೆಯುತ್ತದೆ ಅಥವಾ ಭಿನ್ನ gradients ಉತ್ಪಾದಿಸುತ್ತದೆ." ಇಲ್ಲ -- checkpointing model architecture, loss, gradient equations, optimizer update, ಅಥವಾ training objective ಬದಲಾಯಿಸುವುದಿಲ್ಲ. ಇದೂ ಕೇವಲ activations ಯಾವಾಗ materialize ಆಗುತ್ತವೆ ಮತ್ತೆ ಎಷ್ಟೂ ಕಾಲ ಸಂಗ್ರಹಿಸಲ್ಪಡುತ್ತವೆ ಎಂಬುದನ್ನೂ ಬದಲಾಯಿಸುತ್ತದೆ. ಮೇಲೆ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ: backward formulas (gw2=h.T@g, g_pre=gh*(h_pre>0), gw1=x_in.T@g_pre) h, h_pre, ಮತ್ತೆ x_in ಮೂಲ forward ಸಮಯದಲ್ಲಿ ಸಂಗ್ರಹಿಸಿದ values ಇಂದ ಬಂದಿದ್ದರೂ ಅಥವಾ backward ಸಮಯದಲ್ಲಿ forward ಮರುಚಲಾಯಿಸುವ ಮೂಲಕ ಪುನರುತ್ಪಾದಿಸಿದ values ಇಂದ ಬಂದಿದ್ದರೂ ಒಂದೇ -- execution deterministic ಆಗಿರುವವರೆಗೆ, ಮರುಲೆಕ್ಕಾಚಾರ ಮಾಡಿದ values ಮೂಲಗಳಿಗೆ ಸಂಖ್ಯಾತ್ಮಕವಾಗಿ ಒಂದೇ.' } },

    { type: 'concept', data: {
      headingEn: 'Key Terms', headingKn: 'ಮುಖ್ಯ ಪದಗಳು',
      bodyEn: '• Activation: any intermediate value produced during forward computation that backward might need (genuinely confirmed above: x, h_pre, h in the toy layer)\n• Gradient checkpointing: storing selected boundary tensors and reconstructing discarded intermediates during backward\n• Activation recomputation / rematerialization: re-executing forward calculations during backward to regenerate discarded values\n• Segment size k: number of layers grouped between checkpoints -- controls the memory/recomputation tradeoff, explored fully in Parts 2-3\n• Full checkpointing: discard and later recompute essentially all intermediates in a checkpointed region -- genuinely confirmed to add ~33.3% step FLOP overhead under the simplified cost model\n• Attention-softmax volume: the O(BHL^2)-scaling attention score/softmax tensor family that motivates selective checkpointing at long context',
      bodyKn: '• Activation: forward computation ಸಮಯದಲ್ಲಿ ಉತ್ಪಾದಿಸಿದ ಯಾವುದೇ intermediate value ಇದೂ backward ಗೆ ಬೇಕಾಗಬಹುದು (ಮೇಲೆ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ: toy layer ನಲ್ಲಿ x, h_pre, h)\n• Gradient checkpointing: ಆಯ್ದ boundary tensors ಸಂಗ್ರಹಿಸುವುದೂ ಮತ್ತೆ backward ಸಮಯದಲ್ಲಿ ತಿರಸ್ಕರಿಸಿದ intermediates ಪುನರ್ನಿರ್ಮಿಸುವುದೂ\n• Activation recomputation / rematerialization: ತಿರಸ್ಕರಿಸಿದ values ಪುನರುತ್ಪಾದಿಸಲು backward ಸಮಯದಲ್ಲಿ forward calculations ಮರುಕಾರ್ಯಗತಗೊಳಿಸುವುದೂ\n• Segment size k: checkpoints ನಡುವೆ ಗುಂಪುಗೊಳಿಸಿದ layers ya ಸಂಖ್ಯೆ -- memory/recomputation tradeoff ನಿಯಂತ್ರಿಸುತ್ತದೆ, Parts 2-3 ನಲ್ಲಿ ಪೂರ್ಣವಾಗಿ ಅನ್ವೇಷಿಸಲಾಗಿದೆ\n• Full checkpointing: ಒಂದೂ checkpointed region ನಲ್ಲಿ ಬಹುತೇಕ ಎಲ್ಲಾ intermediates ತಿರಸ್ಕರಿಸಿ ನಂತರ ಮರುಲೆಕ್ಕಾಚಾರ ಮಾಡುವುದೂ -- ಸರಳೀಕೃತ cost model ಅಡಿಯಲ್ಲಿ ~33.3% step FLOP overhead ಸೇರಿಸುತ್ತದೆ ಎಂದೂ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ\n• Attention-softmax volume: O(BHL^2)-scaling attention score/softmax tensor family, ಉದ್ದ context ನಲ್ಲಿ selective checkpointing ಗೆ ಪ್ರೇರೇಪಿಸುತ್ತದೆ' } },

    { type: 'concept', data: {
      headingEn: 'Key Takeaways', headingKn: 'ಮುಖ್ಯ ಅಂಶಗಳು',
      bodyEn: "• GPU training memory includes parameters, gradients, optimizer states, and forward activations -- checkpointing targets activation memory specifically.\n• Genuinely implemented a toy layer's forward pass and confirmed backward genuinely needs three forward values (x_in for gw1, h_pre for the ReLU mask, h for gw2) -- verified by executing the exact gradient formulas and checking their inputs.\n• Gradient checkpointing means: compute -> discard -> recompute -> use, instead of compute -> save -> reuse -- a checkpoint stores a boundary tensor that lets a REGION of computation be rerun, not every intermediate.\n• Genuinely computed naive full recomputation adds exactly 33.3% (4/3-1) step FLOP overhead under a forward=1/backward=2 cost model -- overhead on the whole step, not the forward pass alone.\n• Checkpointing does not change the model architecture, loss, gradient formulas, or training objective -- only when and how long activations stay materialized.\n• Attention activations scale as O(BHL^2) versus O(NBLd) for ordinary linear activations -- doubling sequence length quadruples the attention term but only doubles the linear terms, motivating selective checkpointing strategies covered in later parts.",
      bodyKn: '• GPU training memory parameters, gradients, optimizer states, ಮತ್ತೆ forward activations ಒಳಗೊಂಡಿದೆ -- checkpointing ನಿರ್ದಿಷ್ಟವಾಗಿ activation memory ಗುರಿಪಡಿಸುತ್ತದೆ.\n• ಒಂದು toy layer ya forward pass ನಿಜವಾಗಿ implement ಮಾಡಲಾಗಿದೆ ಮತ್ತೆ backward ಗೆ ನಿಜವಾಗಿ ಮೂರೂ forward values ಬೇಕು ಎಂದೂ ದೃಢಪಡಿಸಲಾಗಿದೆ (gw1 ಗಾಗಿ x_in, ReLU mask ಗಾಗಿ h_pre, gw2 ಗಾಗಿ h) -- ನಿಖರ gradient formulas execute ಮಾಡಿ ಅವುಗಳ inputs ಪರಿಶೀಲಿಸುವ ಮೂಲಕ ಪರಿಶೀಲಿಸಲಾಗಿದೆ.\n• Gradient checkpointing ಎಂದರೆ: compute -> discard -> recompute -> use, compute -> save -> reuse ಬದಲಿಗೆ -- ಒಂದೂ checkpoint ಒಂದೂ boundary tensor ಸಂಗ್ರಹಿಸುತ್ತದೆ ಇದೂ computation ya ಒಂದೂ REGION ಮರುಚಲಾಯಿಸಲು ಬಿಡುತ್ತದೆ, ಪ್ರತಿ intermediate ಅಲ್ಲ.\n• Naive full recomputation forward=1/backward=2 cost model ಅಡಿಯಲ್ಲಿ ನಿಖರವಾಗಿ 33.3% (4/3-1) step FLOP overhead ಸೇರಿಸುತ್ತದೆ ಎಂದೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಲಾಗಿದೆ -- ಪೂರ್ಣ step ಮೇಲೆ overhead, ಕೇವಲ forward pass ಅಲ್ಲ.\n• Checkpointing model architecture, loss, gradient formulas, ಅಥವಾ training objective ಬದಲಾಯಿಸುವುದಿಲ್ಲ -- ಕೇವಲ activations ಯಾವಾಗ ಮತ್ತೆ ಎಷ್ಟೂ ಕಾಲ materialize ಆಗಿ ಉಳಿಯುತ್ತವೆ ಎಂಬುದೂ ಮಾತ್ರ.\n• Attention activations ಸಾಮಾನ್ಯ linear activations ಗಾಗಿ O(NBLd) ಎದುರೂ O(BHL^2) ಆಗಿ ಸ್ಕೇಲ್ ಆಗುತ್ತವೆ -- sequence length ದ್ವಿಗುಣಗೊಳಿಸುವುದೂ attention term ಅನ್ನೂ ನಾಲ್ಕೂ ಪಟ್ಟೂ ಮಾಡುತ್ತದೆ ಆದರೆ linear terms ಅನ್ನೂ ಕೇವಲ ದ್ವಿಗುಣಗೊಳಿಸುತ್ತದೆ, ನಂತರದ ಭಾಗಗಳಲ್ಲಿ ಒಳಗೊಂಡ selective checkpointing strategies ಗೆ ಪ್ರೇರೇಪಿಸುತ್ತದೆ.' } },

    { type: 'concept', data: {
      headingEn: 'Preview: Part 2', headingKn: 'Preview: Part 2',
      bodyEn: 'Part 2 implements the actual checkpointed forward and backward functions (model_forward_checkpointed, model_backward_checkpointed), genuinely computes activation memory in real megabytes for a realistic transformer shape, and genuinely compares full versus selective recomputation FLOP overhead -- including an honest finding about how the source\'s own simplified memory formulas disagree with each other by nearly 50x once real numbers are plugged in.',
      bodyKn: 'Part 2 ನಿಜ checkpointed forward ಮತ್ತೆ backward functions ಅನ್ನೂ implement ಮಾಡುತ್ತದೆ (model_forward_checkpointed, model_backward_checkpointed), ಒಂದೂ ವಾಸ್ತವಿಕ transformer shape ಗಾಗಿ ನಿಜ megabytes ನಲ್ಲಿ activation memory ಅನ್ನೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕುತ್ತದೆ, ಮತ್ತೆ full vs selective recomputation FLOP overhead ಅನ್ನೂ ನಿಜವಾಗಿ ಹೋಲಿಸುತ್ತದೆ -- ನಿಜ ಸಂಖ್ಯೆಗಳನ್ನೂ ಪ್ಲಗ್ ಇನ್ ಮಾಡಿದ ಒಮ್ಮೆ source ya ಸ್ವಂತ ಸರಳೀಕೃತ memory formulas ಪರಸ್ಪರ ಬಹುತೇಕ 50x ಇಂದ ಭಿನ್ನವಾಗುತ್ತವೆ ಎಂಬ ಒಂದೂ ಪ್ರಾಮಾಣಿಕ finding ಸೇರಿ.' } },

    { type: 'quiz', data: { questions: [
      { q: 'Why can training require much more GPU memory than merely storing model weights?',
        qKn: 'Model weights ಸಂಗ್ರಹಿಸುವುದೂ ಗಿಂತ training ಏಕೆ ಬಹಳ ಹೆಚ್ಚೂ GPU memory ಬಯಸಬಹುದು?',
        opts: ['CUDA duplicates every parameter ten times', 'Forward activations required by backward must also be retained', 'ReLU parameters are extremely large', 'Input tokens are always stored as FP64'], correct: 1,
        optsKn: ['CUDA ಪ್ರತಿ parameter ಅನ್ನೂ ಹತ್ತೂ ಬಾರಿ ನಕಲಿಸುತ್ತದೆ', 'Backward ಗೆ ಅಗತ್ಯವಿರುವ forward activations ಕೂಡ ಇಡಬೇಕು', 'ReLU parameters ಅತ್ಯಂತ ದೊಡ್ಡದೂ', 'Input tokens ಯಾವಾಗಲೂ FP64 ಆಗಿ ಸಂಗ್ರಹಿಸಲಾಗುತ್ತದೆ'] },
      { q: 'For Y=XW+b, which forward value is needed to calculate dL/dW?',
        qKn: 'Y=XW+b ಗೆ, dL/dW ಲೆಕ್ಕಹಾಕಲು ಯಾವ forward value ಬೇಕು?',
        opts: ['Only W', 'X', 'Only b', 'Sequence position only'], correct: 1,
        optsKn: ['ಕೇವಲ W', 'X', 'ಕೇವಲ b', 'ಕೇವಲ sequence position'] },
      { q: 'What does gradient checkpointing primarily trade?',
        qKn: 'Gradient checkpointing ಪ್ರಾಥಮಿಕವಾಗಿ ಏನೂ ವಿನಿಮಯ ಮಾಡುತ್ತದೆ?',
        opts: ['Accuracy for speed', 'Parameters for tokens', 'Compute for activation memory', 'Gradients for optimizer state'], correct: 2,
        optsKn: ['Speed ಗಾಗಿ Accuracy', 'Tokens ಗಾಗಿ Parameters', 'Activation memory ಗಾಗಿ Compute', 'Optimizer state ಗಾಗಿ Gradients'] },
      { q: 'Genuinely confirmed: under the forward=1/backward=2 cost model, what is the overhead of naive full recomputation?',
        qKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: forward=1/backward=2 cost model ಅಡಿಯಲ್ಲಿ, naive full recomputation ya overhead ಏನೂ?',
        opts: ['10%', '25%', '33.3%', '50%'], correct: 2,
        optsKn: ['10%', '25%', '33.3%', '50%'] },
      { q: 'Why can attention activations become especially problematic at long sequence lengths?',
        qKn: 'Attention activations ಉದ್ದ sequence lengths ನಲ್ಲಿ ಏಕೆ ವಿಶೇಷವಾಗಿ ಸಮಸ್ಯಾತ್ಮಕವಾಗಬಹುದು?',
        opts: ['They require a different optimizer', 'Some attention intermediates scale as L^2', 'They always use FP64', 'Attention has no backward operation'], correct: 1,
        optsKn: ['Avakke ಒಂದೂ ಭಿನ್ನ optimizer ಬೇಕು', 'Kelavū attention intermediates L^2 ಆಗಿ ಸ್ಕೇಲ್ ಆಗುತ್ತವೆ', 'Avu ಯಾವಾಗಲೂ FP64 ಬಳಸುತ್ತವೆ', 'Attention ಗೆ ಯಾವುದೇ backward operation ಇಲ್ಲ'] },
    ] } },
  ],
};
