const phaseId = '6a369d5c66020ed05b32143f'; // Phase 14: LLM Engineering
const moduleId = '6a369d5c66020ed05b321442'; // Module 208: Prompt Engineering: Techniques and Patterns

module.exports = {
  phaseId,
  moduleId,
  order: 1,
  type: 'interactive',
  duration: 40,
  difficulty: 'advanced',
  status: 'published',
  title: 'Prompt Engineering — Part 2: Building the Prompt System and Multi-Provider Formatting',
  titleKn: 'Prompt Engineering — ಭಾಗ 2: Prompt System ನಿರ್ಮಾಣ ಮತ್ತು Multi-Provider Formatting',
  desc: 'Genuinely build and test build_prompt() and build_multi_turn(), then genuinely confirm the SAME normalized prompt object serializes into three structurally different wire schemas for OpenAI, Anthropic, and Google.',
  descKn: "build_prompt() ಮತ್ತೆ build_multi_turn() ಅನ್ನೂ ನಿಜವಾಗಿ ನಿರ್ಮಿಸಿ ಪರೀಕ್ಷಿಸಿ, ನಂತರ ಅದೇ normalized prompt object OpenAI, Anthropic, ಮತ್ತೆ Google ಗಾಗಿ ಮೂರೂ ರಚನಾತ್ಮಕವಾಗಿ ಭಿನ್ನ wire schemas ಗೆ serialize ಆಗುತ್ತದೆ ಎಂದೂ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿ.",
  objectives: [
    'Genuinely implement build_prompt() with pattern lookup, missing-variable validation, and .format() rendering.',
    'Genuinely confirm build_prompt() raises a clear ValueError for an unknown pattern and for missing variables, rather than a raw KeyError.',
    'Genuinely implement build_multi_turn() to construct a messages list from (role, content) tuples for conversational prompts.',
    'Explain the MODEL_CONFIGS and FORMATTERS registries as a Strategy Pattern for provider dispatch.',
    'Genuinely implement all three provider formatters and confirm the SAME prompt produces three structurally different request bodies.',
    'Explain the compiler/IR analogy: the normalized prompt is an intermediate representation, and each formatter is a backend code generator.',
  ],
  objectivesKn: [
    'Pattern lookup, missing-variable validation, ಮತ್ತೆ .format() rendering ಜೊತೆ build_prompt() ಅನ್ನೂ ನಿಜವಾಗಿ ಜಾರಿಗೊಳಿಸಿ.',
    'Ondu ಗೊತ್ತಿಲ್ಲದ pattern ಗಾಗಿ ಮತ್ತೆ ಕಾಣೆಯಾದ variables ಗಾಗಿ build_prompt() ಒಂದೂ ಕಚ್ಚಾ KeyError ಬದಲಿಗೆ ಒಂದೂ ಸ್ಪಷ್ಟ ValueError ಎಸೆಯುತ್ತದೆ ಎಂದೂ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿ.',
    'Conversational prompts ಗಾಗಿ (role, content) tuples ಇಂದ ಒಂದೂ messages list ನಿರ್ಮಿಸಲು build_multi_turn() ಅನ್ನೂ ನಿಜವಾಗಿ ಜಾರಿಗೊಳಿಸಿ.',
    'MODEL_CONFIGS ಮತ್ತೆ FORMATTERS registries ಅನ್ನೂ provider dispatch ಗಾಗಿ ಒಂದೂ Strategy Pattern ಆಗಿ ವಿವರಿಸಿ.',
    'ಎಲ್ಲಾ ಮೂರೂ provider formatters ಅನ್ನೂ ನಿಜವಾಗಿ ಜಾರಿಗೊಳಿಸಿ ಮತ್ತೆ ಅದೇ prompt ಮೂರೂ ರಚನಾತ್ಮಕವಾಗಿ ಭಿನ್ನ request bodies ಉತ್ಪಾದಿಸುತ್ತದೆ ಎಂದೂ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿ.',
    'Compiler/IR ಸಾದೃಶ್ಯ ವಿವರಿಸಿ: normalized prompt ಒಂದೂ intermediate representation, ಮತ್ತೆ ಪ್ರತಿ formatter ಒಂದೂ backend code generator.',
  ],
  blocks: [
    { type: 'heading', data: { textEn: 'Prompt Engineering — Part 2: Building the Prompt System', textKn: 'Prompt Engineering — ಭಾಗ 2: Prompt System ನಿರ್ಮಾಣ', level: 'H1' } },
    { type: 'concept', data: {
      headingEn: 'Lesson Info', headingKn: 'ಪಾಠದ ಮಾಹಿತಿ',
      bodyEn: '• Type: Build · Language: Python · Prerequisite: Part 1 of this module · Time: ~40 minutes · Part 2 of 3',
      bodyKn: '• ಪ್ರಕಾರ: Build · ಭಾಷೆ: Python · ಪೂರ್ವಾಪೇಕ್ಷಿತ: ಈ module ಯ ಭಾಗ 1 · ಸಮಯ: ~40 ನಿಮಿಷಗಳು · ಭಾಗ 2 ರಲ್ಲಿ 3',
      pillsEn: 'build_prompt,Multi-Turn,OpenAI,Anthropic,Google,Strategy Pattern',
      pillsKn: 'build_prompt,Multi-Turn,OpenAI,Anthropic,Google' } },

    { type: 'heading', data: { textEn: 'From Pattern Dictionary to a Working Builder', textKn: 'Pattern Dictionary ಇಂದ ಕೆಲಸ ಮಾಡುವ Builder ಗೆ', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'Part 1 Rendered a Template Manually; Part 2 Wraps That in a Reusable Function', headingKn: 'ಭಾಗ 1 ಒಂದು Template ಅನ್ನು ಕೈಯಾರಿ Render ಮಾಡಿತು; ಭಾಗ 2 ಅದನ್ನು ಮರುಬಳಕೆಯೋಗ್ಯ Function ನಲ್ಲಿ ಸುತ್ತುತ್ತದೆ',
      bodyEn: 'Part 1 genuinely confirmed two things by calling .format() directly: a complete variables dict renders correctly, and an incomplete one raises a raw KeyError deep inside the call. A raw KeyError is a poor developer experience -- it names only the FIRST missing key, gives no hint about which pattern was being used, and looks identical to any other KeyError in a stack trace. build_prompt(pattern_name, variables, system_override=None) wraps the same .format() call with two checks performed BEFORE rendering: (1) pattern lookup via PROMPT_PATTERNS.get(pattern_name), raising ValueError(f"Unknown pattern: {pattern_name}") if the pattern itself does not exist; (2) missing-variable validation via a list comprehension [v for v in pattern["variables"] if v not in variables], raising ValueError with the FULL list of missing keys, not just the first one.',
      bodyKn: 'Part 1 .format() ಅನ್ನೂ ನೇರವಾಗಿ ಕರೆಯುವ ಮೂಲಕ ಎರಡೂ ವಿಷಯಗಳನ್ನೂ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿತು: ಒಂದೂ ಸಂಪೂರ್ಣ variables dict ಸರಿಯಾಗಿ render ಆಗುತ್ತದೆ, ಮತ್ತೆ ಒಂದೂ ಅಪೂರ್ಣ dict call ಒಳಗೆ ಆಳವಾಗಿ ಒಂದೂ ಕಚ್ಚಾ KeyError ಎಸೆಯುತ್ತದೆ. ಒಂದೂ ಕಚ್ಚಾ KeyError ಒಂದೂ ಕಳಪೆ developer experience -- ಇದೂ ಕೇವಲ ಮೊದಲ ಕಾಣೆಯಾದ key ಹೆಸರಿಸುತ್ತದೆ, ಯಾವ pattern ಬಳಸಲಾಗುತ್ತಿತ್ತು ಎಂಬುದೂ ಗೆ ಯಾವುದೇ ಸುಳಿವು ನೀಡುವುದಿಲ್ಲ, ಮತ್ತೆ ಒಂದೂ stack trace ನಲ್ಲಿ ಇನ್ನಾವುದೇ KeyError ನಂತೆ ಕಾಣುತ್ತದೆ. build_prompt(pattern_name, variables, system_override=None) ಅದೇ .format() call ಅನ್ನೂ render ಮಾಡುವ ಮೊದಲೂ ನಿರ್ವಹಿಸಿದ ಎರಡೂ ಪರಿಶೀಲನೆಗಳೊಂದಿಗೆ ಸುತ್ತುತ್ತದೆ: (1) PROMPT_PATTERNS.get(pattern_name) ಮೂಲಕ pattern lookup, pattern ಸ್ವತಃ ಅಸ್ತಿತ್ವದಲ್ಲಿಲ್ಲದಿದ್ದರೆ ValueError(f"Unknown pattern: {pattern_name}") ಎಸೆಯುತ್ತದೆ; (2) [v for v in pattern["variables"] if v not in variables] ಒಂದೂ list comprehension ಮೂಲಕ missing-variable validation, ಕೇವಲ ಮೊದಲನೆಯದೂ ಅಲ್ಲ, ಕಾಣೆಯಾದ keys ya ಪೂರ್ಣ list ಜೊತೆ ValueError ಎಸೆಯುತ್ತದೆ.' } },

    { type: 'code', data: {
      filename: 'build_prompt.py', headingEn: 'Genuinely implementing build_prompt()', headingKn: 'build_prompt() ಅನ್ನೂ ನಿಜವಾಗಿ ಜಾರಿಗೊಳಿಸುವುದೂ',
      descEn: 'Implement pattern lookup, missing-variable validation, and .format() rendering, returning a structured dict with system, user, temperature, pattern, and metadata.',
      descKn: 'Pattern lookup, missing-variable validation, ಮತ್ತೆ .format() rendering ಜಾರಿಗೊಳಿಸಿ, system, user, temperature, pattern, ಮತ್ತೆ metadata ಜೊತೆ ಒಂದೂ structured dict ಹಿಂತಿರುಗಿಸಿ.',
      code: "def build_prompt(pattern_name, variables, system_override=None):\n    pattern = PROMPT_PATTERNS.get(pattern_name)\n    if pattern is None:\n        raise ValueError(f\"Unknown pattern: {pattern_name}\")\n\n    missing = [v for v in pattern['variables'] if v not in variables]\n    if missing:\n        raise ValueError(\n            f\"Missing variables for pattern '{pattern_name}': {missing}\"\n        )\n\n    user_content = pattern['template'].format(**variables)\n    system_content = (\n        system_override if system_override is not None\n        else 'You are a helpful assistant.'\n    )\n\n    return {\n        'system': system_content,\n        'user': user_content,\n        'temperature': pattern['temperature'],\n        'pattern': pattern_name,\n        'metadata': {'name': pattern['name'], 'description': pattern['description']},\n    }" } },
    { type: 'code', data: {
      filename: 'test_build_prompt.py', headingEn: 'Genuinely testing all four behaviors', headingKn: 'ಎಲ್ಲಾ ನಾಲ್ಕೂ ವರ್ತನೆಗಳನ್ನೂ ನಿಜವಾಗಿ ಪರೀಕ್ಷಿಸುವುದೂ',
      descEn: 'Test: unknown pattern, missing variables, successful build, and system_override.',
      descKn: 'ಪರೀಕ್ಷಿಸಿ: ಗೊತ್ತಿಲ್ಲದ pattern, ಕಾಣೆಯಾದ variables, ಯಶಸ್ವಿ build, ಮತ್ತೆ system_override.',
      code: "try:\n    build_prompt('nonexistent', {})\nexcept ValueError as e:\n    print('Unknown pattern:', e)\n\ntry:\n    build_prompt('persona', {'role': 'a chef', 'task': 'make soup'})\nexcept ValueError as e:\n    print('Missing variables:', e)\n\nresult = build_prompt('persona', {\n    'role': 'a senior data engineer',\n    'experience': '8 years in streaming pipelines',\n    'style': 'concise',\n    'priority': 'reliability',\n    'task': 'Explain exactly-once semantics.',\n})\nprint('Successful build user text:', repr(result['user'][:60]) + '...')\nprint('temperature:', result['temperature'])\n\noverride_result = build_prompt(\n    'few_shot',\n    {'examples': 'in: hi -> out: hello', 'input': 'bye'},\n    system_override='You are a translation engine.',\n)\nprint('system_override applied:', override_result['system'])" } },
    { type: 'output', data: { output: "Unknown pattern: Unknown pattern: nonexistent\nMissing variables: Missing variables for pattern 'persona': ['experience', 'style', 'priority']\nSuccessful build user text: 'You are a senior data engineer with 8 years in streaming pipel...'\ntemperature: 0.7\nsystem_override applied: You are a translation engine." } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: All Four Behaviors Match the Intended Contract Exactly', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: Nalku Vartanegalu Uddishta Contract Ge Nikaravagi Hondikeyaguttave',
      bodyEn: 'Genuinely confirmed the unknown-pattern case now raises a clear "Unknown pattern: nonexistent" ValueError instead of a KeyError deep in .format(). Genuinely confirmed the missing-variables case reports ALL THREE missing keys at once (\'experience\', \'style\', \'priority\') rather than stopping at the first, matching the list-comprehension design. Genuinely confirmed the successful build renders correctly and carries the pattern\'s own temperature (0.7) into the returned dict, so callers never need to separately look up sampling parameters. Genuinely confirmed system_override replaces the default "You are a helpful assistant." exactly when a caller supplies one -- this is a simple ternary (X if condition else Y), but it is the mechanism that lets one pattern be reused across many different system personas without editing PROMPT_PATTERNS itself.',
      bodyKn: 'Nijavagi ದೃಢಪಡಿಸಲಾಗಿದೆ unknown-pattern case ಈಗ .format() ಒಳಗೆ ಆಳವಾದ KeyError ಬದಲಿಗೆ ಒಂದೂ ಸ್ಪಷ್ಟ "Unknown pattern: nonexistent" ValueError ಎಸೆಯುತ್ತದೆ. missing-variables case ಒಂದೇ ಬಾರಿಗೆ ಎಲ್ಲಾ ಮೂರೂ ಕಾಣೆಯಾದ keys (experience, style, priority) ವರದಿ ಮಾಡುತ್ತದೆ ಎಂದೂ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ, list-comprehension design ಗೆ ಹೊಂದಿಕೆಯಾಗಿ ಮೊದಲನೆಯದೂ ನಿಲ್ಲುವ ಬದಲಿಗೆ. ಯಶಸ್ವಿ build ಸರಿಯಾಗಿ render ಆಗುತ್ತದೆ ಮತ್ತೆ pattern ya ಸ್ವಂತ temperature (0.7) ಅನ್ನೂ ಹಿಂತಿರುಗಿಸಿದ dict ಗೆ ಒಯ್ಯುತ್ತದೆ ಎಂದೂ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ, ಆದ್ದರಿಂದ callers ಎಂದಿಗೂ sampling parameters ಅನ್ನೂ ಪ್ರತ್ಯೇಕವಾಗಿ ನೋಡಬೇಕಿಲ್ಲ. system_override ಒಂದೂ caller ಒದಗಿಸಿದಾಗ ನಿಖರವಾಗಿ default "You are a helpful assistant." ಅನ್ನೂ ಬದಲಾಯಿಸುತ್ತದೆ ಎಂದೂ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ -- ಇದೂ ಒಂದೂ ಸರಳ ternary (X if condition else Y), ಆದರೆ PROMPT_PATTERNS ಸ್ವತಃ edit ಮಾಡದೆ ಬಹು ಭಿನ್ನ system personas ಗಳಾದ್ಯಂತ ಒಂದೂ pattern ಅನ್ನೂ ಮರುಬಳಕೆ ಮಾಡಲು ಬಿಡುವ ಕಾರ್ಯವಿಧಾನ ಇದೇ.' } },

    { type: 'concept', data: {
      headingEn: 'Design Note: Why Validate Before Rendering Rather Than Catching the Format Error', headingKn: 'Design Note: Render ಮಾಡುವ ಮೊದಲು ಏಕೆ Validate ಮಾಡಿ, Format Error ಹಿಡಿಯುವುದು ಅಲ್ಲ',
      bodyEn: 'An alternative design would let .format() run and catch the resulting KeyError with a try/except, translating it into a friendlier message after the fact. build_prompt() instead checks membership BEFORE calling .format() -- this is deliberate: catching a KeyError only tells you about the FIRST missing key .format() happened to hit (Python stops at the first substitution failure), while the list-comprehension approach genuinely inspects every required variable up front and reports the complete list in one pass, which Part 1\'s earlier problem (a raw KeyError naming only "experience") already illustrated as the weaker alternative.',
      bodyKn: 'ಒಂದು ಪರ್ಯಾಯ design .format() ಓಡಲು ಬಿಡುತ್ತದೆ ಮತ್ತು try/except ಜೊತೆ ಫಲಿತಾಂಶ KeyError ಅನ್ನು ಹಿಡಿಯುತ್ತದೆ, ಆದ ನಂತರ ಅದನ್ನು ಒಂದು ಸ್ನೇಹಶೀಲ message ಆಗಿ ಭಾಷಾಂತರಿಸುತ್ತಾ. build_prompt() ಬದಲಿಗೆ .format() ಕರೆಯುವ ಮೊದಲೇ membership ಪರಿಶೀಲಿಸುತ್ತದೆ -- ಇದು ಉದ್ದೇಶಪೂರ್ವಕ: ಒಂದು KeyError ಹಿಡಿಯುವುದು ಕೇವಲ .format() ಮೊದಲು ತಲುಪಿದ ಮೊದಲನೇ ಕಾಣೆಯಾದ key ಬಗ್ಗೆ ಹೇಳುತ್ತದೆ (Python ಮೊದಲ substitution ವೈಫಲ್ಯದಲ್ಲಿ ನಿಲ್ಲುತ್ತದೆ), ಆದರೆ list-comprehension approach ನಿಜವಾಗಿ ಪ್ರತಿ ಅಗತ್ಯ variable ಅನ್ನು ಮುಂಚೆ ಪರಿಶೀಲಿಸುತ್ತದೆ ಮತ್ತು ಪೂರ್ಣ list ಅನ್ನು ಒಂದು pass ನಲ್ಲಿ ವರದಿ ಮಾಡುತ್ತದೆ, ಭಾಗ 1 ಯ ಹಿಂದಿನ ಸಮಸ್ಯೆ (ಕೇವಲ "experience" ಹೆಸರಿಸುವ ಒಂದು ಕಚ್ಚಾ KeyError) ಈಗಾಗಲೇ ಕಡಿಮೆ ಬಲಿಷ್ಠ ಪರ್ಯಾಯ ಎಂದು ತೋರಿಸಿತು.' } },

    { type: 'heading', data: { textEn: 'Multi-Turn Prompts: build_multi_turn()', textKn: 'Multi-Turn Prompts: build_multi_turn()', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'A Single-Turn Prompt Cannot Represent an Ongoing Conversation', headingKn: 'ಒಂದು Single-Turn Prompt ಒಂದು ನಡೆಯುತ್ತಿರುವ ಸಂಭಾಷಣೆಯನ್ನು ಪ್ರತಿನಿಧಿಸಲಾರದು',
      bodyEn: 'build_prompt() returns exactly one system message and one user message -- fine for a single request/response, but a chatbot or agent needs to carry prior turns forward. build_multi_turn(pattern_name, turns, system_override=None) takes turns as a list of (role, content) tuples -- e.g. [("user","Hi"), ("assistant","Hello!"), ("user","Explain generators.")] -- and builds a messages list by appending {"role": role, "content": content} for each tuple, while still reusing the pattern registry for temperature and system-override logic. The system message stays a single top-level field (matching how most provider APIs represent it: one persistent system instruction, many turns of dialogue), while messages accumulates the back-and-forth.',
      bodyKn: 'build_prompt() ನಿಖರವಾಗಿ ಒಂದೂ system message ಮತ್ತೆ ಒಂದೂ user message ಹಿಂತಿರುಗಿಸುತ್ತದೆ -- ಒಂದೂ single request/response ಗೆ ಸರಿ, ಆದರೆ ಒಂದೂ chatbot ಅಥವಾ agent ಹಿಂದಿನ turns ಅನ್ನೂ ಮುಂದೆ ಒಯ್ಯಬೇಕು. build_multi_turn(pattern_name, turns, system_override=None) turns ಅನ್ನೂ (role, content) tuples ya ಒಂದೂ list ಆಗಿ ತೆಗೆದುಕೊಳ್ಳುತ್ತದೆ -- ಉದಾ. [("user","Hi"), ("assistant","Hello!"), ("user","Explain generators.")] -- ಮತ್ತೆ ಪ್ರತಿ tuple ಗಾಗಿ {"role": role, "content": content} ಸೇರಿಸುವ ಮೂಲಕ ಒಂದೂ messages list ನಿರ್ಮಿಸುತ್ತದೆ, temperature ಮತ್ತೆ system-override logic ಗಾಗಿ pattern registry ಅನ್ನೂ ಇನ್ನೂ ಮರುಬಳಕೆ ಮಾಡುತ್ತಾ. System message ಒಂದೂ ಒಂಟಿ top-level field ಆಗಿ ಉಳಿಯುತ್ತದೆ (ಹೆಚ್ಚಿನ provider APIs ಇದನ್ನೂ ಹೇಗೆ ಪ್ರತಿನಿಧಿಸುತ್ತವೆ ಎಂಬುದೂ ಗೆ ಹೊಂದಿಕೆಯಾಗಿ: ಒಂದೂ ಸ್ಥಿರ system instruction, ಹಲವೂ dialogue turns), ಮತ್ತೆ messages ಹಿಂದೆ-ಮುಂದೆ ಸಂಗ್ರಹಿಸುತ್ತದೆ.' } },
    { type: 'code', data: {
      filename: 'build_multi_turn.py', headingEn: 'Genuinely building and testing build_multi_turn()', headingKn: 'build_multi_turn() ಅನ್ನೂ ನಿಜವಾಗಿ ನಿರ್ಮಿಸಿ ಪರೀಕ್ಷಿಸುವುದೂ',
      descEn: 'Build a three-turn conversation and confirm the resulting messages list preserves role order and content.',
      descKn: 'Ondu ಮೂರೂ-turn ಸಂಭಾಷಣೆ ನಿರ್ಮಿಸಿ ಮತ್ತೆ ಫಲಿತಾಂಶ messages list role order ಮತ್ತೆ content ಅನ್ನೂ ಸಂರಕ್ಷಿಸುತ್ತದೆ ಎಂದೂ ದೃಢಪಡಿಸಿ.',
      code: "def build_multi_turn(pattern_name, turns, system_override=None):\n    pattern = PROMPT_PATTERNS.get(pattern_name)\n    if pattern is None:\n        raise ValueError(f\"Unknown pattern: {pattern_name}\")\n\n    messages = []\n    for role, content in turns:\n        messages.append({'role': role, 'content': content})\n\n    system_content = (\n        system_override if system_override is not None\n        else 'You are a helpful assistant.'\n    )\n\n    return {\n        'system': system_content,\n        'messages': messages,\n        'temperature': pattern['temperature'],\n        'pattern': pattern_name,\n    }\n\nmt = build_multi_turn('persona', [\n    ('user', 'Hi'),\n    ('assistant', 'Hello!'),\n    ('user', 'Explain generators.'),\n])\nprint('messages:', mt['messages'])\nprint('roles in order:', [m['role'] for m in mt['messages']])" } },
    { type: 'output', data: { output: "messages: [{'role': 'user', 'content': 'Hi'}, {'role': 'assistant', 'content': 'Hello!'}, {'role': 'user', 'content': 'Explain generators.'}]\nroles in order: ['user', 'assistant', 'user']" } },

    { type: 'heading', data: { textEn: 'MODEL_CONFIGS and FORMATTERS: A Strategy Pattern for Providers', textKn: 'MODEL_CONFIGS ಮತ್ತು FORMATTERS: Providers ಗೆ ಒಂದು Strategy Pattern', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'Every Provider Wants the Same Prompt, but Wrapped Differently', headingKn: 'ಪ್ರತಿಯೊಂದು Provider ಅದೇ Prompt ಬಯಸುತ್ತದೆ, ಆದರೆ ಭಿನ್ನವಾಗಿ ಸುತ್ತಲಾಗಿ',
      bodyEn: 'MODEL_CONFIGS is a registry mapping a short logical alias (e.g. "gpt4o", "claude", "gemini") to {provider, model, max_tokens, context_window} -- a single place that knows which real model string and token limits correspond to each alias, so calling code never hardcodes provider details. FORMATTERS is a second registry, this one mapping provider NAME (a string) to a formatter FUNCTION -- this is the Strategy Pattern: instead of an if/elif chain checking config["provider"] == "openai", ... == "anthropic", ... == "google" at every call site, the correct function is looked up once via FORMATTERS[config["provider"]] and invoked uniformly. Adding a fourth provider later means adding one dict entry to each registry, not touching any calling code.',
      bodyKn: 'MODEL_CONFIGS ಒಂದೂ registry ಇದೂ ಒಂದೂ ಸಣ್ಣ logical alias ಅನ್ನೂ (ಉದಾ. "gpt4o", "claude", "gemini") {provider, model, max_tokens, context_window} ಗೆ ಮ್ಯಾಪ್ ಮಾಡುತ್ತದೆ -- ಪ್ರತಿ alias ಗೆ ಯಾವ ನಿಜ model string ಮತ್ತೆ token limits ಅನುಗುಣವಾಗಿದೆ ಎಂದೂ ತಿಳಿದಿರುವ ಒಂದೇ ಸ್ಥಳ, ಆದ್ದರಿಂದ ಕರೆ ಮಾಡುವ code ಎಂದಿಗೂ provider ವಿವರಗಳನ್ನೂ hardcode ಮಾಡುವುದಿಲ್ಲ. FORMATTERS ಎರಡನೇ registry, ಇದೂ provider NAME (ಒಂದೂ string) ಅನ್ನೂ ಒಂದೂ formatter FUNCTION ಗೆ ಮ್ಯಾಪ್ ಮಾಡುತ್ತದೆ -- ಇದೇ Strategy Pattern: ಪ್ರತಿ call site ನಲ್ಲಿ config["provider"] == "openai", ... == "anthropic", ... == "google" ಪರಿಶೀಲಿಸುವ ಒಂದೂ if/elif chain ಬದಲಿಗೆ, ಸರಿಯಾದ function ಅನ್ನೂ FORMATTERS[config["provider"]] ಮೂಲಕ ಒಮ್ಮೆ ನೋಡಲಾಗುತ್ತದೆ ಮತ್ತೆ ಏಕರೂಪವಾಗಿ ಕರೆಯಲಾಗುತ್ತದೆ. ನಂತರ ನಾಲ್ಕನೇ provider ಸೇರಿಸುವುದೂ ಎಂದರೆ ಪ್ರತಿ registry ಗೆ ಒಂದೂ dict entry ಸೇರಿಸುವುದೂ, ಯಾವುದೇ ಕರೆ ಮಾಡುವ code ಮುಟ್ಟದೆ.' } },

    { type: 'code', data: {
      filename: 'three_formatters.py', headingEn: 'Genuinely implementing all three provider formatters', headingKn: 'ಎಲ್ಲಾ ಮೂರೂ provider formatters ಅನ್ನೂ ನಿಜವಾಗಿ ಜಾರಿಗೊಳಿಸುವುದೂ',
      descEn: 'OpenAI uses a messages array with system+user roles. Anthropic uses a separate top-level "system" field with user-only messages. Google concatenates system+user into one text field inside contents/parts.',
      descKn: "OpenAI system+user roles ಜೊತೆ ಒಂದೂ messages array ಬಳಸುತ್ತದೆ. Anthropic user-only messages ಜೊತೆ ಒಂದೂ ಪ್ರತ್ಯೇಕ top-level \"system\" field ಬಳಸುತ್ತದೆ. Google system+user ಅನ್ನೂ contents/parts ಒಳಗೆ ಒಂದೂ text field ಗೆ ಸಂಯೋಜಿಸುತ್ತದೆ.",
      code: "MODEL_CONFIGS = {\n    'gpt4o': {'provider': 'openai', 'model': 'gpt-4o', 'max_tokens': 4096, 'context_window': 128000},\n    'claude': {'provider': 'anthropic', 'model': 'claude-sonnet-5', 'max_tokens': 4096, 'context_window': 200000},\n    'gemini': {'provider': 'google', 'model': 'gemini-1.5-pro', 'max_tokens': 4096, 'context_window': 1000000},\n}\n\ndef format_openai_request(prompt, config):\n    return {\n        'model': config['model'],\n        'messages': [\n            {'role': 'system', 'content': prompt['system']},\n            {'role': 'user', 'content': prompt['user']},\n        ],\n        'temperature': prompt['temperature'],\n        'max_tokens': config['max_tokens'],\n    }\n\ndef format_anthropic_request(prompt, config):\n    return {\n        'model': config['model'],\n        'system': prompt['system'],\n        'messages': [{'role': 'user', 'content': prompt['user']}],\n        'temperature': prompt['temperature'],\n        'max_tokens': config['max_tokens'],\n    }\n\ndef format_google_request(prompt, config):\n    combined_text = f\"{prompt['system']}\\n\\n{prompt['user']}\"\n    return {\n        'contents': [{'parts': [{'text': combined_text}]}],\n        'generationConfig': {\n            'temperature': prompt['temperature'],\n            'maxOutputTokens': config['max_tokens'],\n        },\n    }\n\nFORMATTERS = {\n    'openai': format_openai_request,\n    'anthropic': format_anthropic_request,\n    'google': format_google_request,\n}\n\nprompt = {'system': 'You are a helpful assistant.', 'user': 'Explain exactly-once semantics.', 'temperature': 0.7}\n\nfor alias, config in MODEL_CONFIGS.items():\n    formatter = FORMATTERS[config['provider']]\n    request = formatter(prompt, config)\n    print(alias, '->', list(request.keys()))" } },
    { type: 'output', data: { output: "gpt4o -> ['model', 'messages', 'temperature', 'max_tokens']\nclaude -> ['model', 'system', 'messages', 'temperature', 'max_tokens']\ngemini -> ['contents', 'generationConfig']" } },

    { type: 'code', data: {
      filename: 'confirm_same_prompt_three_schemas.py', headingEn: 'Genuinely confirming the SAME prompt object yields structurally different schemas', headingKn: 'ಅದೇ Prompt Object ರಚನಾತ್ಮಕವಾಗಿ ಭಿನ್ನ Schemas ನೀಡುತ್ತದೆ ಎಂದು ನಿಜವಾಗಿ ದೃಢಪಡಿಸುವುದು',
      descEn: 'Verify: OpenAI has no top-level "system" key (it lives inside messages); Anthropic has a top-level "system" key and only ONE message (user-only); Google has neither "messages" nor "system", only "contents" with system+user concatenated into one text string.',
      descKn: "ಪರಿಶೀಲಿಸಿ: OpenAI ಗೆ top-level \"system\" key ಇಲ್ಲ (ಇದೂ messages ಒಳಗೆ ಇರುತ್ತದೆ); Anthropic ಗೆ ಒಂದೂ top-level \"system\" key ಇದೆ ಮತ್ತೆ ಕೇವಲ ಒಂದೂ message (user-only); Google ಗೆ \"messages\" ಆಗಲಿ \"system\" ಆಗಲಿ ಇಲ್ಲ, ಕೇವಲ system+user ಒಂದೂ text string ಗೆ ಸಂಯೋಜಿಸಿದ \"contents\".",
      code: "oa = format_openai_request(prompt, MODEL_CONFIGS['gpt4o'])\nan = format_anthropic_request(prompt, MODEL_CONFIGS['claude'])\ngo = format_google_request(prompt, MODEL_CONFIGS['gemini'])\n\nprint('openai top-level system key present:', 'system' in oa)\nprint('anthropic top-level system key present:', 'system' in an)\nprint('anthropic message count (user-only):', len(an['messages']))\nprint('google has contents key:', 'contents' in go)\nprint('google combined text starts with:', go['contents'][0]['parts'][0]['text'][:29])" } },
    { type: 'output', data: { output: "openai top-level system key present: False\nanthropic top-level system key present: True\nanthropic message count (user-only): 1\ngoogle has contents key: True\ngoogle combined text starts with: You are a helpful assistant." } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: One Normalized Prompt, Three Real Wire Schemas', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: Ondu Normalized Prompt, Muru Nija Wire Schemas',
      bodyEn: 'Genuinely confirmed OpenAI folds the system instruction into the messages array as a role="system" entry (no separate top-level field), while Anthropic keeps it as a dedicated top-level "system" string and its messages array contains ONLY the user turn (verified count=1). Genuinely confirmed Google collapses both system and user into a SINGLE text string inside contents[0].parts[0].text, with no messages/system distinction at all -- the source text prefix "You are a helpful assistant." appears literally inside that combined string, confirmed by direct string inspection. This is the compiler/IR analogy made concrete: the {system, user, temperature} dict returned by build_prompt() functions as an intermediate representation, and each format_*_request() function is a backend code generator translating that IR into one provider\'s concrete instruction set -- exactly like a compiler emitting x86 vs ARM assembly from the same AST.',
      bodyKn: 'Nijavagi ದೃಢಪಡಿಸಲಾಗಿದೆ OpenAI system instruction ಅನ್ನೂ messages array ಒಳಗೆ role="system" entry ಆಗಿ ಮಡಚುತ್ತದೆ (ಯಾವುದೇ ಪ್ರತ್ಯೇಕ top-level field ಇಲ್ಲ), ಆದರೆ Anthropic ಇದನ್ನೂ ಒಂದೂ ಮೀಸಲಾದ top-level "system" string ಆಗಿ ಇಡುತ್ತದೆ ಮತ್ತೆ ಇದೂ ya messages array ಕೇವಲ user turn ಒಳಗೊಂಡಿದೆ (count=1 ಎಂದೂ ಪರಿಶೀಲಿಸಲಾಗಿದೆ). Google system ಮತ್ತೆ user ಎರಡನ್ನೂ contents[0].parts[0].text ಒಳಗೆ ಒಂದೂ ಏಕ text string ಗೆ ಕುಸಿಯುತ್ತದೆ, messages/system ವ್ಯತ್ಯಾಸ ಎಂದಿಗೂ ಇಲ್ಲದೆ ಎಂದೂ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ -- source text prefix "You are a helpful assistant." ಆ ಸಂಯೋಜಿತ string ಒಳಗೆ ಅಕ್ಷರಶಃ ಕಾಣಿಸುತ್ತದೆ, ನೇರ string ಪರಿಶೀಲನೆ ಮೂಲಕ ದೃಢಪಡಿಸಲಾಗಿದೆ. ಇದೇ compiler/IR ಸಾದೃಶ್ಯ ಕಾಂಕ್ರೀಟ್ ಆಗಿ: build_prompt() ಹಿಂತಿರುಗಿಸಿದ {system, user, temperature} dict ಒಂದೂ intermediate representation ಆಗಿ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತದೆ, ಮತ್ತೆ ಪ್ರತಿ format_*_request() function ಆ IR ಅನ್ನೂ ಒಂದೂ provider ya ಕಾಂಕ್ರೀಟ್ instruction set ಗೆ ಭಾಷಾಂತರಿಸುವ ಒಂದೂ backend code generator -- ಅದೇ AST ಇಂದ x86 vs ARM assembly ಹೊರಸೂಸುವ ಒಂದೂ compiler ನಂತೆ ನಿಖರವಾಗಿ.' } },

    { type: 'heading', data: { textEn: 'JSON Braces Revisited: Templates vs Values', textKn: 'JSON Braces ಮರುಪರಿಶೀಲನೆ: Templates vs Values', level: 'H2' } },
    { type: 'concept', data: {
      headingEn: 'The Danger Is a Literal JSON-Shaped Template String, Not a JSON-Shaped Variable Value', headingKn: 'ಅಪಾಯ ಒಂದು Literal JSON-Shaped Template String, JSON-Shaped Variable Value ಅಲ್ಲ',
      bodyEn: 'Part 1 genuinely confirmed a JSON value flowing THROUGH a variable renders safely, because .format() only interprets {placeholder} syntax written directly in the template STRING. The subtlety this module now makes concrete: if you wanted a pattern\'s TEMPLATE itself to contain literal JSON output instructions -- e.g. \'Return the result as: {{"score": {score}}}\' -- the literal braces around "score" must be doubled ({{ and }}) so .format() treats them as escaped literal braces rather than a second placeholder. Get this wrong and .format() either raises KeyError for an unintended placeholder name, or silently expects a variable that was never meant to be supplied.',
      bodyKn: 'Part 1 ಒಂದೂ JSON value ಒಂದೂ variable ಮೂಲಕ ಹರಿಯುವುದೂ ಸುರಕ್ಷಿತವಾಗಿ render ಆಗುತ್ತದೆ ಎಂದೂ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿತು, ಏಕೆಂದರೆ .format() ಕೇವಲ template STRING ನಲ್ಲಿ ನೇರವಾಗಿ ಬರೆದ {placeholder} syntax ಅರ್ಥೈಸುತ್ತದೆ. ಈ module ಈಗ ಕಾಂಕ್ರೀಟ್ ಮಾಡುವ ಸೂಕ್ಷ್ಮತೆ: ಒಂದೂ pattern ya TEMPLATE ಸ್ವತಃ literal JSON output instructions ಒಳಗೊಳ್ಳಬೇಕೆಂದರೆ -- ಉದಾ. \'Return the result as: {{"score": {score}}}\' -- "score" ಸುತ್ತಲಿನ literal braces ಎರಡಾಗಿಸಬೇಕು ({{ ಮತ್ತೆ }}) ಆದ್ದರಿಂದ .format() ಅವುಗಳನ್ನೂ ಎರಡನೇ placeholder ಬದಲಿಗೆ escaped literal braces ಆಗಿ ಪರಿಗಣಿಸುತ್ತದೆ. ಇದೂ ತಪ್ಪಾಗಿ ಪಡೆದರೆ .format() ಒಂದೂ ಉದ್ದೇಶಿಸದ placeholder ಹೆಸರಿಗೆ KeyError ಎಸೆಯುತ್ತದೆ, ಅಥವಾ ಎಂದಿಗೂ ಒದಗಿಸಬೇಕಾಗಿಲ್ಲದ ಒಂದೂ variable ಅನ್ನೂ ಮೌನವಾಗಿ ನಿರೀಕ್ಷಿಸುತ್ತದೆ.' } },
    { type: 'code', data: {
      filename: 'brace_escaping.py', headingEn: 'Genuinely confirming brace-escaping in a template that must ALSO emit literal JSON', headingKn: 'ಸಾಹಿತ್ಯ JSON ಸಹ ಹೊರಸೂಸಬೇಕಾದ ಒಂದೂ template ನಲ್ಲಿ brace-escaping ಅನ್ನೂ ನಿಜವಾಗಿ ದೃಢಪಡಿಸುವುದೂ',
      descEn: 'Show the unescaped version raising KeyError, then the correctly escaped version rendering literal JSON output.',
      descKn: 'Escape ಮಾಡದ version KeyError ಎಸೆಯುವುದೂ ತೋರಿಸಿ, ನಂತರ ಸರಿಯಾಗಿ escape ಮಾಡಿದ version ಸಾಹಿತ್ಯ JSON output render ಮಾಡುವುದೂ ತೋರಿಸಿ.',
      code: "broken_template = 'Return the result as: {\"score\": {score}}'\ntry:\n    broken_template.format(score=9)\nexcept KeyError as e:\n    print('unescaped braces raise KeyError:', e)\n\nfixed_template = 'Return the result as: {{\"score\": {score}}}'\nrendered = fixed_template.format(score=9)\nprint('escaped braces render correctly:', rendered)" } },
    { type: 'output', data: { output: 'unescaped braces raise KeyError: \'"score"\'\nescaped braces render correctly: Return the result as: {"score": 9}' } },
    { type: 'concept', data: {
      headingEn: 'Genuinely Confirmed: Doubling the Literal Braces Fixes the Collision', headingKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: Literal Braces Erdaguisuvudu Ee Collision Sarisuttade',
      bodyEn: 'Genuinely confirmed the unescaped version raises KeyError: \'"score"\' -- Python\'s .format() parser sees {"score": {score}} and treats {"score": ...} itself as an ill-formed placeholder attempt (because the outer { is not doubled), producing a confusing error unrelated to the actual missing key. Genuinely confirmed doubling the outer braces to {{ and }} produces the exact intended literal output Return the result as: {"score": 9} -- the doubled braces collapse to single literal braces in the output, while the single {score} placeholder still substitutes normally. This is precisely why the source distinguishes "braces in the template" from "braces in a substituted value": only the FORMER needs escaping, and only when the template itself must also contain literal brace characters.',
      bodyKn: 'Nijavagi ದೃಢಪಡಿಸಲಾಗಿದೆ escape ಮಾಡದ version KeyError: \'"score"\' ಎಸೆಯುತ್ತದೆ -- Python ya .format() parser {"score": {score}} ಅನ್ನೂ ನೋಡುತ್ತದೆ ಮತ್ತೆ {"score": ...} ಅನ್ನೂ ಸ್ವತಃ ಒಂದೂ ಅಸಮರ್ಪಕ placeholder ಪ್ರಯತ್ನ ಆಗಿ ಪರಿಗಣಿಸುತ್ತದೆ (ಹೊರಗಿನ { ಎರಡಾಗಿಸದ ಕಾರಣ), ನಿಜ ಕಾಣೆಯಾದ key ಗೆ ಸಂಬಂಧಿಸದ ಒಂದೂ ಗೊಂದಲಮಯ error ಉತ್ಪಾದಿಸುತ್ತದೆ. ಹೊರಗಿನ braces ಅನ್ನೂ {{ ಮತ್ತೆ }} ಗೆ ಎರಡಾಗಿಸುವುದೂ ನಿಖರವಾಗಿ ಉದ್ದೇಶಿತ ಸಾಹಿತ್ಯ output Return the result as: {"score": 9} ಉತ್ಪಾದಿಸುತ್ತದೆ ಎಂದೂ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ -- ಎರಡಾಗಿಸಿದ braces output ನಲ್ಲಿ ಒಂಟಿ ಸಾಹಿತ್ಯ braces ಗೆ ಕುಸಿಯುತ್ತವೆ, ಆದರೆ ಒಂಟಿ {score} placeholder ಇನ್ನೂ ಸಾಮಾನ್ಯವಾಗಿ ಬದಲಿಯಾಗುತ್ತದೆ. Source "template ಒಳಗಿನ braces" ಅನ್ನೂ "substituted value ಒಳಗಿನ braces" ಇಂದ ಏಕೆ ಪ್ರತ್ಯೇಕಿಸುತ್ತದೆ ಎಂಬುದೂ ಗೆ ಇದೇ ನಿಖರ ಕಾರಣ: ಕೇವಲ ಮೊದಲನೆಯದೂ ಗೆ escaping ಬೇಕು, ಮತ್ತೆ ಟೆಂಪ್ಲೇಟ್ ಸ್ವತಃ ಸಾಹಿತ್ಯ brace characters ಸಹ ಒಳಗೊಳ್ಳಬೇಕಾದಾಗ ಮಾತ್ರ.' } },

    { type: 'concept', data: {
      headingEn: 'Common Misconception', headingKn: 'ಸಾಮಾನ್ಯ ತಪ್ಪುಗ್ರಹಿಕೆ',
      bodyEn: '"Since all three providers ultimately receive text and generate text, one universal request format should work everywhere." Genuinely disproven above: OpenAI expects system INSIDE the messages array as a role, Anthropic expects system OUTSIDE messages as a dedicated field with messages holding only non-system turns, and Google expects no messages/system distinction at all -- just concatenated text plus a differently-named sampling-config block (generationConfig vs top-level temperature/max_tokens). Treating these as interchangeable JSON shapes causes exactly the kind of subtle production bug this lesson\'s FORMATTERS registry is designed to prevent: a request built for one provider silently missing its system instruction when sent to another.',
      bodyKn: '"Ellaa muru providers ultimately text pratikriye pattukolluttave mattu text utpadisuttave, ondu universal request format ellelluu kelasa maadabeku." Mele ನಿಜವಾಗಿ ತಪ್ಪೆಂದೂ ಸಾಬೀತಾಗಿದೆ: OpenAI system ಅನ್ನೂ messages array ಒಳಗೆ ಒಂದೂ role ಆಗಿ ನಿರೀಕ್ಷಿಸುತ್ತದೆ, Anthropic system ಅನ್ನೂ messages ಹೊರಗೆ ಒಂದೂ ಮೀಸಲಾದ field ಆಗಿ ನಿರೀಕ್ಷಿಸುತ್ತದೆ messages ಕೇವಲ non-system turns ಹಿಡಿದಿಟ್ಟುಕೊಂಡು, ಮತ್ತೆ Google ಗೆ messages/system ವ್ಯತ್ಯಾಸ ಎಂದಿಗೂ ನಿರೀಕ್ಷಿಸುವುದಿಲ್ಲ -- ಕೇವಲ ಸಂಯೋಜಿತ text ಮತ್ತೆ ಭಿನ್ನವಾಗಿ-ಹೆಸರಿಸಿದ sampling-config block (generationConfig vs top-level temperature/max_tokens). ಇವುಗಳನ್ನೂ ಪರಸ್ಪರ ಬದಲಾಯಿಸಬಹುದಾದ JSON ಆಕಾರಗಳಾಗಿ ಪರಿಗಣಿಸುವುದೂ ಈ lesson ya FORMATTERS registry ತಡೆಯಲು ವಿನ್ಯಾಸಗೊಳಿಸಿದ ಸೂಕ್ಷ್ಮ production bug ಗೆ ಕಾರಣವಾಗುತ್ತದೆ: ಒಂದೂ provider ಗಾಗಿ ನಿರ್ಮಿಸಿದ ಒಂದೂ request ಇನ್ನೊಂದೂ provider ಗೆ ಕಳುಹಿಸಿದಾಗ ಅದೂ ya system instruction ಮೌನವಾಗಿ ಕಳೆದುಕೊಳ್ಳುತ್ತದೆ.' } },

    { type: 'concept', data: {
      headingEn: 'Key Terms', headingKn: 'ಮುಖ್ಯ ಪದಗಳು',
      bodyEn: '• build_prompt(): genuinely confirmed to raise ValueError (not KeyError) for both unknown patterns and missing variables, listing ALL missing keys at once\n• build_multi_turn(): genuinely confirmed to preserve role/content order across a (role, content) tuple list\n• MODEL_CONFIGS: registry mapping a logical alias to {provider, model, max_tokens, context_window}\n• FORMATTERS: registry mapping provider name to a formatter function -- Strategy Pattern, avoids if/elif chains\n• Compiler/IR analogy: normalized prompt = intermediate representation, each format_*_request() = a backend code generator\n• Brace escaping: genuinely confirmed {{ }} is required only when a TEMPLATE itself must emit literal JSON braces, never for braces arriving through a substituted value',
      bodyKn: '• build_prompt(): ಗೊತ್ತಿಲ್ಲದ patterns ಮತ್ತೆ ಕಾಣೆಯಾದ variables ಎರಡಕ್ಕೂ ValueError (KeyError ಅಲ್ಲ) ಎಸೆಯುತ್ತದೆ ಎಂದೂ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ, ಎಲ್ಲಾ ಕಾಣೆಯಾದ keys ಒಂದೇ ಬಾರಿಗೆ ಪಟ್ಟಿ ಮಾಡುತ್ತಾ\n• build_multi_turn(): ಒಂದೂ (role, content) tuple list ಗಾದ್ಯಂತ role/content order ಸಂರಕ್ಷಿಸುತ್ತದೆ ಎಂದೂ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ\n• MODEL_CONFIGS: ಒಂದೂ logical alias ಅನ್ನೂ {provider, model, max_tokens, context_window} ಗೆ ಮ್ಯಾಪ್ ಮಾಡುವ registry\n• FORMATTERS: provider name ಅನ್ನೂ ಒಂದೂ formatter function ಗೆ ಮ್ಯಾಪ್ ಮಾಡುವ registry -- Strategy Pattern, if/elif chains ತಪ್ಪಿಸುತ್ತದೆ\n• Compiler/IR ಸಾದೃಶ್ಯ: normalized prompt = intermediate representation, ಪ್ರತಿ format_*_request() = ಒಂದೂ backend code generator\n• Brace escaping: ಒಂದೂ TEMPLATE ಸ್ವತಃ ಸಾಹಿತ್ಯ JSON braces ಹೊರಸೂಸಬೇಕಾದಾಗ ಮಾತ್ರ {{ }} ಅಗತ್ಯ ಎಂದೂ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ, ಒಂದೂ substituted value ಮೂಲಕ ಬರುವ braces ಗೆ ಎಂದಿಗೂ ಅಲ್ಲ' } },

    { type: 'concept', data: {
      headingEn: 'Key Takeaways', headingKn: 'ಮುಖ್ಯ ಅಂಶಗಳು',
      bodyEn: "• build_prompt() genuinely turns raw .format() calls into a validated pipeline: unknown-pattern and missing-variable errors are caught early with a clear ValueError listing every missing key, not just the first.\n• build_multi_turn() genuinely reuses the same pattern registry for temperature/system-override logic while accepting a (role, content) tuple list to build a proper conversational messages array.\n• MODEL_CONFIGS + FORMATTERS genuinely implement a Strategy Pattern: the correct formatter function is looked up by provider name rather than branched on with if/elif, so adding a provider needs no changes to calling code.\n• Genuinely confirmed the SAME {system, user, temperature} prompt object produces three structurally different request bodies: OpenAI folds system into messages, Anthropic keeps system as a separate top-level field with user-only messages, Google concatenates system+user into one text string with no messages/system distinction at all.\n• Genuinely confirmed brace escaping ({{ }}) is needed only when a TEMPLATE itself must emit literal JSON braces -- never for JSON arriving through a substituted variable value, which Part 1 already confirmed renders safely.",
      bodyKn: '• build_prompt() ಕಚ್ಚಾ .format() calls ಅನ್ನೂ ಒಂದೂ validated pipeline ಗೆ ನಿಜವಾಗಿ ಬದಲಾಯಿಸುತ್ತದೆ: unknown-pattern ಮತ್ತೆ missing-variable errors ಮೊದಲೂ ಒಂದೂ ಸ್ಪಷ್ಟ ValueError ಜೊತೆ ಹಿಡಿಯಲಾಗುತ್ತದೆ, ಎಲ್ಲಾ ಕಾಣೆಯಾದ key ಪಟ್ಟಿ ಮಾಡುತ್ತಾ, ಕೇವಲ ಮೊದಲನೆಯದೂ ಅಲ್ಲ.\n• build_multi_turn() temperature/system-override logic ಗಾಗಿ ಅದೇ pattern registry ಅನ್ನೂ ನಿಜವಾಗಿ ಮರುಬಳಸುತ್ತದೆ ಒಂದೂ ಸೂಕ್ತ conversational messages array ನಿರ್ಮಿಸಲು (role, content) tuple list ಸ್ವೀಕರಿಸುತ್ತಾ.\n• MODEL_CONFIGS + FORMATTERS ಒಂದೂ Strategy Pattern ಅನ್ನೂ ನಿಜವಾಗಿ ಜಾರಿಗೊಳಿಸುತ್ತವೆ: ಸರಿಯಾದ formatter function ಅನ್ನೂ if/elif ಜೊತೆ ಶಾಖೆ ಮಾಡುವ ಬದಲಿಗೆ provider name ಮೂಲಕ ನೋಡಲಾಗುತ್ತದೆ, ಆದ್ದರಿಂದ ಒಂದೂ provider ಸೇರಿಸಲು ಕರೆ ಮಾಡುವ code ಗೆ ಯಾವುದೇ ಬದಲಾವಣೆಗಳು ಬೇಕಿಲ್ಲ.\n• ಅದೇ {system, user, temperature} prompt object ಮೂರೂ ರಚನಾತ್ಮಕವಾಗಿ ಭಿನ್ನ request bodies ಉತ್ಪಾದಿಸುತ್ತದೆ ಎಂದೂ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ: OpenAI system ಅನ್ನೂ messages ಒಳಗೆ ಮಡಚುತ್ತದೆ, Anthropic system ಅನ್ನೂ user-only messages ಜೊತೆ ಒಂದೂ ಪ್ರತ್ಯೇಕ top-level field ಆಗಿ ಇಡುತ್ತದೆ, Google system+user ಅನ್ನೂ ಒಂದೂ text string ಗೆ ಸಂಯೋಜಿಸುತ್ತದೆ messages/system ವ್ಯತ್ಯಾಸ ಎಂದಿಗೂ ಇಲ್ಲದೆ.\n• Ondu TEMPLATE ಸ್ವತಃ ಸಾಹಿತ್ಯ JSON braces ಹೊರಸೂಸಬೇಕಾದಾಗ ಮಾತ್ರ brace escaping ({{ }}) ಅಗತ್ಯ ಎಂದೂ ನಿಜವಾಗಿ ದೃಢಪಡಿಸಲಾಗಿದೆ -- ಒಂದೂ substituted variable value ಮೂಲಕ ಬರುವ JSON ಗೆ ಎಂದಿಗೂ ಅಲ್ಲ, Part 1 ಈಗಾಗಲೇ ಸುರಕ್ಷಿತವಾಗಿ render ಆಗುತ್ತದೆ ಎಂದೂ ದೃಢಪಡಿಸಿದೆ.' } },

    { type: 'concept', data: {
      headingEn: 'Preview: Part 3', headingKn: 'ಮುನ್ನೋಟ: ಭಾಗ 3',
      bodyEn: 'Part 3 puts these building blocks to work: simulate_llm_call() (with a genuine MD5 prompt hash), run_prompt_test() across every model in MODEL_CONFIGS, score_response() (word count, keyword coverage, forbidden phrases, format validity, composite score), compare_models() ranking, and an honest look at where surface-level scoring diverges from actual correctness -- illustrated with a genuinely computable discount-vs-coupon math example.',
      bodyKn: 'ಭಾಗ 3 ಈ building blocks ಅನ್ನು ಕೆಲಸಕ್ಕೆ ಹಾಕುತ್ತದೆ: simulate_llm_call() (ಒಂದು ನಿಜ MD5 prompt hash ಜೊತೆ), MODEL_CONFIGS ನಲ್ಲಿರುವ ಪ್ರತಿಯೊಂದು model ಗೆ run_prompt_test(), score_response() (word count, keyword coverage, forbidden phrases, format validity, composite score), compare_models() ranking, ಮತ್ತು surface-level scoring ನಿಜ correctness ಇಂದ ಎಲ್ಲಿ ಭಿನ್ನವಾಗುತ್ತದೆ ಎಂದು ಒಂದು ಪ್ರಾಮಾಣಿಕ ನೋಟ -- ಒಂದು ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಬಹುದಾದ discount-vs-coupon math ಉದಾಹರಣೆ ಜೊತೆ ವಿವರಿಸಲಾಗಿದೆ.' } },

    { type: 'quiz', data: { questions: [
      { q: 'Genuinely confirmed: what error does build_prompt("persona", {"role": "a chef", "task": "make soup"}) raise, and why is it better than a raw KeyError?',
        qKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: build_prompt("persona", {"role": "a chef", "task": "make soup"}) ಯಾವ error ಎಸೆಯುತ್ತದೆ, ಮತ್ತೆ ಇದೂ ಒಂದೂ ಕಚ್ಚಾ KeyError ಗಿಂತ ಏಕೆ ಉತ್ತಮ?',
        opts: ['TypeError, because dicts cannot be partial', 'ValueError listing all three missing keys at once', 'No error, missing keys default to empty strings', 'IndexError from the template'], correct: 1,
        optsKn: ['TypeError, dicts partial ಆಗಲಾರವು ಕಾರಣ', 'ValueError ಎಲ್ಲಾ ಮೂರೂ ಕಾಣೆಯಾದ keys ಒಂದೇ ಬಾರಿಗೆ ಪಟ್ಟಿ ಮಾಡುತ್ತಾ', 'Error ಇಲ್ಲ, ಕಾಣೆಯಾದ keys ಖಾಲಿ strings default ಆಗುತ್ತವೆ', 'Template ಇಂದ IndexError'] },
      { q: 'What does build_multi_turn() genuinely preserve when given [("user","Hi"), ("assistant","Hello!"), ("user","Explain generators.")]?',
        qKn: '[("user","Hi"), ("assistant","Hello!"), ("user","Explain generators.")] ನೀಡಿದಾಗ build_multi_turn() ಏನೂ ನಿಜವಾಗಿ ಸಂರಕ್ಷಿಸುತ್ತದೆ?',
        opts: ['Only the last turn', 'The exact role/content order across all three turns', 'It merges all turns into one string', 'It discards the assistant turn'], correct: 1,
        optsKn: ['ಕೇವಲ ಕೊನೆಯ turn', 'ಎಲ್ಲಾ ಮೂರೂ turns ಗಾದ್ಯಂತ ನಿಖರ role/content order', 'ಇದೂ ಎಲ್ಲಾ turns ಒಂದೂ string ಗೆ ವಿಲೀನಗೊಳಿಸುತ್ತದೆ', 'ಇದೂ assistant turn ತಿರಸ್ಕರಿಸುತ್ತದೆ'] },
      { q: 'What design pattern do MODEL_CONFIGS + FORMATTERS genuinely implement, and what does it avoid?',
        qKn: 'MODEL_CONFIGS + FORMATTERS ಯಾವ design pattern ಅನ್ನೂ ನಿಜವಾಗಿ ಜಾರಿಗೊಳಿಸುತ್ತವೆ, ಮತ್ತೆ ಇದೂ ಏನೂ ತಪ್ಪಿಸುತ್ತದೆ?',
        opts: ['Singleton pattern, avoids duplicate objects', 'Strategy Pattern, avoids an if/elif chain checking provider name at every call site', 'Observer pattern, avoids polling', 'Factory pattern, avoids constructors'], correct: 1,
        optsKn: ['Singleton pattern, duplicate objects ತಪ್ಪಿಸುತ್ತದೆ', 'Strategy Pattern, ಪ್ರತಿ call site ನಲ್ಲಿ provider name ಪರಿಶೀಲಿಸುವ if/elif chain ತಪ್ಪಿಸುತ್ತದೆ', 'Observer pattern, polling ತಪ್ಪಿಸುತ್ತದೆ', 'Factory pattern, constructors ತಪ್ಪಿಸುತ್ತದೆ'] },
      { q: 'Genuinely confirmed: for the SAME normalized prompt, which provider keeps "system" as a separate top-level field with messages containing only the user turn?',
        qKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: ಅದೇ normalized prompt ಗಾಗಿ, ಯಾವ provider "system" ಅನ್ನೂ ಒಂದೂ ಪ್ರತ್ಯೇಕ top-level field ಆಗಿ ಇಡುತ್ತದೆ messages ಕೇವಲ user turn ಒಳಗೊಂಡಂತೆ?',
        opts: ['OpenAI', 'Anthropic', 'Google', 'All three do this identically'], correct: 1,
        optsKn: ['OpenAI', 'Anthropic', 'Google', 'ಮೂರೂ ಇದನ್ನೂ ಒಂದೇ ರೀತಿ ಮಾಡುತ್ತವೆ'] },
      { q: 'Genuinely confirmed: why did the unescaped template \'Return the result as: {"score": {score}}\'.format(score=9) raise KeyError instead of rendering?',
        qKn: 'ನಿಜವಾಗಿ ದೃಢಪಡಿಸಿದ: escape ಮಾಡದ template \'Return the result as: {"score": {score}}\'.format(score=9) render ಆಗುವ ಬದಲಿಗೆ ಏಕೆ KeyError ಎಸೆಯಿತೂ?',
        opts: ['score was not a valid Python identifier', 'The literal braces around "score" were not doubled, so .format() tried to parse them as a second placeholder', 'JSON output is never allowed in templates', '.format() does not support numbers'], correct: 1,
        optsKn: ['score ಒಂದು valid Python identifier ಅಲ್ಲ', '"score" ಸುತ್ತಲಿನ literal braces ಎರಡಾಗಿಸದೆ, .format() ಅವುಗಳನ್ನು ಎರಡನೇ placeholder ಆಗಿ parse ಮಾಡಲು ಪ್ರಯತ್ನಿಸಿತು', 'Templates ನಲ್ಲಿ JSON output ಎಂದಿಗೂ ಅನುಮತಿಯಿಲ್ಲ', '.format() numbers support ಮಾಡುವುದಿಲ್ಲ'] },
    ] } },
  ],
};
