const phaseId = '6a369d5666020ed05b321334'; // Phase 9

const m132 = '6a369d5666020ed05b32134f'; // Module 132: Music Generation
const m133 = '6a369d5666020ed05b321352'; // Module 133: Audio-Language Models

const l132_1 = '6a6e04db746d00283e132ca5'; // Music Generation Part 1
const l132_2 = '6a6e068e3fe74a9bd1e1a80a'; // Music Generation Part 2
const l133_1 = '6a6e08425adfe0d429f38f7e'; // Audio-Language Models Part 1
const l133_2 = '6a6e0a14d389ab224873a9d4'; // Audio-Language Models Part 2

module.exports = [
  // ── Module 132, Lesson 1: MusicGen, Neural Audio Tokens & Foundations ──
  { phaseId, moduleId: m132, lessonId: l132_1, order: 1, difficulty: 'intermediate',
    title: 'Simulating RVQ by Hand',
    problem: "Residual Vector Quantization (RVQ) quantizes progressively finer residuals with each codebook.\n1. Pick a toy scalar value, e.g. 7.83, and a coarse codebook of allowed values [0, 2, 4, 6, 8, 10]. Quantize 7.83 to the nearest codebook value (q0) and compute the residual (7.83 - q0).\n2. Quantize that residual using a finer codebook, e.g. [-1, -0.5, 0, 0.5, 1] (q1), and compute the new residual.\n3. Add q0 + q1 back together. How much closer is this two-stage reconstruction to 7.83 than q0 alone?\n4. Explain in your own words why stacking multiple codebooks (each quantizing the previous one's error) lets you represent a value more precisely than a single codebook of the same total size could." },
  { phaseId, moduleId: m132, lessonId: l132_1, order: 2, difficulty: 'advanced',
    title: 'Attempting audiocraft Installation',
    problem: "Genuinely attempt pip install audiocraft in your own environment.\n1. Does it succeed? If not, capture the exact error message.\n2. This course found a reproducible blis/Cython compile error when installing audiocraft (via its spacy -> thinc -> blis dependency chain). Does your environment hit the same error, a different one, or does it succeed where this course's environment failed?\n3. If it does succeed for you, attempt the lesson's musicgen_basic.py code (MusicGen.get_pretrained('facebook/musicgen-small')) and report what happens -- document the real outcome rather than assuming success." },
  { phaseId, moduleId: m132, lessonId: l132_1, order: 3, difficulty: 'advanced',
    title: 'Genuinely Running Frechet Audio Distance',
    problem: "Following the lesson's genuinely-verified fad_eval.py: pip install frechet-audio-distance, then from frechet_audio_distance import FrechetAudioDistance; fad = FrechetAudioDistance().\n1. Time how long the import takes -- this course found it can take 20-36 seconds due to laion_clap's heavy dependency chain. Does your environment show similar timing?\n2. Instantiating FrechetAudioDistance() downloads a VGGish checkpoint via torch.hub, which may require trusting the repo (a y/n prompt in older torch, or a config file write). Does it succeed in your environment?\n3. Create two small folders of synthetic WAV files (a handful of short sine tones each) as background_dir and eval_dir, and call fad.score(background_dir, eval_dir) -- note the method is score(), not get_fad_score(). What result do you get? This course found a real scipy sqrtm() incompatibility bug that causes the score to silently return -1 -- does your environment reproduce that, or does it return a real numeric score?" },
  { phaseId, moduleId: m132, lessonId: l132_1, order: 4, difficulty: 'intermediate',
    title: 'The Delay Pattern: Why MusicGen Needs It',
    problem: "MusicGen predicts multiple RVQ codebooks (q0-q3) per audio frame using a single autoregressive Transformer.\n1. If a model predicted all 4 codebooks for one frame simultaneously (no delay), what information would q1's prediction be missing that it needs from q0 (referencing how RVQ codebooks quantize each other's residuals)?\n2. If instead the model predicted all of q0's tokens across the whole sequence, then all of q1's tokens, then q2, then q3 (fully sequential by codebook rather than by frame), what would happen to the total sequence length compared to interleaving them with a small delay?\n3. Describe the delay pattern's compromise in one sentence: what does it let the model condition on, while keeping the total sequence length manageable?" },
  { phaseId, moduleId: m132, lessonId: l132_1, order: 5, difficulty: 'beginner',
    title: 'Text-to-Music vs. Melody-Conditioned vs. Continuation',
    problem: "1. For each of the three music-generation problem types, write the exact input(s) and output.\n2. If a user hums a tune into their phone and says 'make this into a jazz piano piece', which of the three types is this?\n3. If a user has an 8-bar loop and wants the model to generate the next 8 bars in the same style, which type is this, and what part of the original audio does the model condition on?" },

  // ── Module 132, Lesson 2: Melody Conditioning, Evaluation & LLM + Music Pipelines ──
  { phaseId, moduleId: m132, lessonId: l132_2, order: 1, difficulty: 'advanced',
    title: 'Genuinely Verifying crossfade()',
    problem: "Run the lesson's exact crossfade(a, b, sr, fade_s=1.0) function.\n1. Create two 3-second synthetic tensors at sr=32000 (matching MusicGen's native rate) using different sine frequencies, and crossfade them.\n2. Compute the expected output length as len(a) + len(b) - int(fade_s*sr), and confirm the actual output shape matches.\n3. Print a few sample values right at the crossfade boundary (index len(a)-int(fade_s*sr) through len(a)) -- do they show a genuine blend (values that are a mix of both signals), or does the code just concatenate without truly overlapping and summing?\n4. Change fade_s to 0.1 (a much shorter crossfade). Recompute the expected and actual output length. Does a shorter crossfade produce a longer or shorter total output for the same two input segments?" },
  { phaseId, moduleId: m132, lessonId: l132_2, order: 2, difficulty: 'intermediate',
    title: 'Genuinely Testing build_prompt() and create_music_prompt()',
    problem: "Run the lesson's build_prompt(spec) and create_music_prompt(user_request) functions.\n1. Build a music_spec dict with genre, mood, instruments (a list), tempo_bpm, and duration_s, and run build_prompt() on it. Print the resulting string -- does it read as a natural, MusicGen-style descriptive prompt?\n2. Remove tempo_bpm from the spec (or set it to None) and rerun build_prompt(). Does the function correctly omit the BPM phrase, or does it error?\n3. Run create_music_prompt() with a vague request like 'something for a road trip'. Print the resulting LLM instruction template. What would you expect a real LLM to fill in for genre/mood/instruments given that vague request?\n4. Chain the two: imagine (or actually call, if you have LLM API access) an LLM response to create_music_prompt()'s output, parse it into a spec dict, then run it through build_prompt(). Does the two-stage pipeline produce a more detailed prompt than the user's original one-line request?" },
  { phaseId, moduleId: m132, lessonId: l132_2, order: 3, difficulty: 'intermediate',
    title: 'Checking the MMAU-Pro Dataset ID',
    problem: "This course found that load_dataset('MMAU/MMAU-Pro') genuinely raises a DatasetNotFoundError.\n1. Reproduce this exact check in your own environment: from datasets import load_dataset; load_dataset('MMAU/MMAU-Pro'). Do you get the same error?\n2. Search the Hugging Face Hub (via its website or the huggingface_hub API) for datasets with 'MMAU-Pro' in the name. Do you find any valid repo IDs under different owner names?\n3. Why does this course document this as a real finding rather than silently substituting a working dataset ID? What would be lost if the lesson had just quietly 'fixed' the lesson's own code without saying so?" },
  { phaseId, moduleId: m132, lessonId: l132_2, order: 4, difficulty: 'beginner',
    title: 'FAD vs. CLAP: What Each Metric Actually Measures',
    problem: "1. In one sentence, what question does FAD (Frechet Audio Distance) answer about a generated audio clip?\n2. In one sentence, what question does CLAP-style text-audio alignment answer instead?\n3. If a MusicGen output has an excellent (low) FAD score but a poor CLAP alignment score, what would that combination mean about the generated music in practice -- realistic-sounding but not matching what was asked for, or the reverse?" },
  { phaseId, moduleId: m132, lessonId: l132_2, order: 5, difficulty: 'advanced',
    title: 'Designing a Long-Form Generation Loop',
    problem: "Using your genuinely-verified crossfade() function, design (in pseudocode or real code) a generate_long_form(total_seconds, segment_seconds=8, overlap_seconds=1) function that would call a (stub) MusicGen generate function repeatedly and stitch segments together.\n1. How many segments are needed to cover total_seconds=60 with segment_seconds=8 and overlap_seconds=1 (accounting for the fact that each new segment only adds segment_seconds - overlap_seconds of new audio after the first)?\n2. What information from the *previous* segment would you want to condition the *next* segment's generation on, to reduce the prompt-drift and tempo-drift failure modes covered in the lesson?\n3. Using your crossfade() function, write the loop that actually stitches N segments together pairwise into one continuous output, and confirm the final output's total length matches your prediction from step 1." },

  // ── Module 133, Lesson 1: Qwen2.5-Omni, Audio Flamingo, GPT-4o Audio ──
  { phaseId, moduleId: m133, lessonId: l133_1, order: 1, difficulty: 'intermediate',
    title: 'Genuinely Verifying the AudioProjector',
    problem: "Run the lesson's exact AudioProjector(audio_dim=1280, llm_dim=4096) class.\n1. Instantiate it and count its total parameters with sum(p.numel() for p in proj.parameters()). Confirm you get the same 22,028,288 (22.0M) this course found.\n2. Feed it a random tensor shaped torch.randn(1, 50, 1280) and confirm the output shape is (1, 50, 4096).\n3. Change audio_dim to 512 (a smaller audio encoder's hidden size) and llm_dim to 2048 (a smaller LLM). Recompute the parameter count. Does it scale roughly linearly, quadratically, or some other way with these two dimensions (hint: think about what a nn.Linear layer's parameter count formula is)?\n4. Compute this new projector's parameter count as a percentage of a 1B-parameter LLM. Is it still a small fraction, as the lesson claims is typical?" },
  { phaseId, moduleId: m133, lessonId: l133_1, order: 2, difficulty: 'advanced',
    title: 'Reproducing the AutoModelForCausalLM Mismatch',
    problem: "This course found that AutoModelForCausalLM.from_pretrained('Qwen/Qwen2.5-Omni-7B', ...) fails because the model's real architecture is Qwen2_5OmniModel, not a plain causal LM.\n1. Reproduce this check without downloading the full multi-GB checkpoint: from transformers import AutoConfig; cfg = AutoConfig.from_pretrained('Qwen/Qwen2.5-Omni-7B'); print(cfg.architectures). Do you see the same ['Qwen2_5OmniModel'] result?\n2. Attempt AutoModelForCausalLM.from_config(cfg) (config-only, no weight download) and confirm you get the same ValueError this course documented.\n3. Find the correct class name in the transformers library (hint: search for classes with 'Omni' and 'ConditionalGeneration' in their name) and confirm it exists in your installed transformers version.\n4. Why does checking AutoConfig.from_pretrained() first (a small download) before attempting the full model load (a huge download) save real time and bandwidth when debugging an unfamiliar model's loading code?" },
  { phaseId, moduleId: m133, lessonId: l133_1, order: 3, difficulty: 'intermediate',
    title: 'ASR vs. Audio-Language Model: Designing Test Questions',
    problem: "1. Write three questions about a hypothetical audio clip (containing speech plus environmental sounds) that ONLY an audio-language model could answer correctly, not a transcript-only ASR pipeline.\n2. For each question, explain specifically what non-speech information (timing, environmental sound, speaker tone) the question requires that a plain transcript discards.\n3. Now write one question about the same clip that ASR alone genuinely *can* answer just as well as an audio-language model. What does this tell you about when the extra complexity of an audio-language model is actually worth it versus overkill?" },
  { phaseId, moduleId: m133, lessonId: l133_1, order: 4, difficulty: 'beginner',
    title: 'The Three Training Stages',
    problem: "1. For Stage 1 (Alignment), what is frozen and what is trained? What kind of training pairs does it use?\n2. For Stage 2 (Instruction Following), what changes about the training data compared to Stage 1?\n3. For Stage 3 (Voice In/Out), what new component is added to the architecture, and what does it enable that Stage 2's model couldn't do?" },
  { phaseId, moduleId: m133, lessonId: l133_1, order: 5, difficulty: 'intermediate',
    title: 'Open vs. Closed Audio-Language Models',
    problem: "1. List two open models and two closed models from the lesson's 2026 model landscape table.\n2. For an open model, what could you genuinely verify about its architecture (like the AudioProjector exercise above) that you cannot verify for a closed model?\n3. If you were building a product that needs to run fully offline (no internet access at inference time), would you be able to use a closed model like GPT-4o Audio? Explain what constraint this places on your model choice." },

  // ── Module 133, Lesson 2: Projector, MMAU-Pro, Long Audio, Model Selection ──
  { phaseId, moduleId: m133, lessonId: l133_2, order: 1, difficulty: 'intermediate',
    title: 'Re-Verifying the MMAU-Pro Dataset ID',
    problem: "This lesson independently re-checked load_dataset('MMAU/MMAU-Pro') rather than assuming Module 132's finding still held.\n1. Run the same check yourself: does it still raise DatasetNotFoundError in your environment today?\n2. Why does this course re-verify the same fact in a later lesson instead of just citing the earlier lesson's finding? What could change between the two checks that would make re-verification necessary (think about what a 'dataset ID doesn't exist' finding is actually a claim about)?\n3. In general, what's the difference between a finding that's stable forever (like a math formula) and one that could genuinely change over time (like a dataset's existence on a public hub)? Which category does this MMAU-Pro finding fall into?" },
  { phaseId, moduleId: m133, lessonId: l133_2, order: 2, difficulty: 'advanced',
    title: 'Simulating the Multi-Audio Random-Baseline Problem',
    problem: "The lesson reports several models scoring 20-26% on MMAU-Pro's multi-audio category, close to the 25% random baseline for 4-choice questions.\n1. Write a simple simulate_random_baseline(n_questions=1000, n_choices=4) function that randomly guesses an answer for each of n_questions and computes accuracy. Run it and confirm it lands close to 25%.\n2. Run it 10 times and report the range of accuracies you observe. How much does random noise alone move the result away from exactly 25%?\n3. Given that range, if a real model scores 27% on a multi-audio benchmark, is that meaningfully better than random, or could it plausibly just be noise? What sample size (number of questions) would you want before trusting a small difference like that?" },
  { phaseId, moduleId: m133, lessonId: l133_2, order: 3, difficulty: 'intermediate',
    title: 'Designing a Diarization-First Long-Audio Pipeline',
    problem: "1. Sketch (in pseudocode) a pipeline that takes a 90-minute lecture recording, runs diarization first, then feeds each diarized segment (not the raw full recording) to an audio-language model for question answering.\n2. Why does feeding structured, speaker-labeled segments to the LALM instead of the raw 90-minute file help specifically with 'who said X' and 'when did Y happen' questions?\n3. If a question spans two different diarized segments (e.g. 'what did the instructor say right after the student asked a question?'), how would your pipeline need to handle segment boundaries to answer it correctly?" },
  { phaseId, moduleId: m133, lessonId: l133_2, order: 4, difficulty: 'beginner',
    title: 'Silence Hallucination and VAD-Gating',
    problem: "1. In your own words, explain why a model can hallucinate content during a silent audio segment even though 'nothing happened' should be the obvious answer.\n2. Describe how VAD-gating (from Module 134) mitigates this specific failure mode when applied before an audio-language model.\n3. Would VAD-gating fully eliminate silence hallucination, or could a model still hallucinate about a segment that VAD correctly labels as speech but is actually ambiguous/hard-to-understand audio? Explain the difference between these two failure cases." },
  { phaseId, moduleId: m133, lessonId: l133_2, order: 5, difficulty: 'intermediate',
    title: 'Model Selection Decision Tree',
    problem: "For each of the following three scenarios, use the lesson's model selection table and decision tree to pick a model and justify your choice in one sentence:\n1. A call-center compliance auditing product that needs to check 10,000 calls per day for a specific mandatory disclosure phrase.\n2. A voice-in/voice-out assistant embedded in a car dashboard with no cloud connectivity.\n3. A music-catalog tagging tool that needs to identify instruments and playing style across a library of songs.\nFor each, also name one category (Speech, Sound, Music, or Multi-audio) from MMAU-Pro that you'd specifically want to check before trusting the model in production, given what this module found about category-level performance gaps." },
];
