const phaseId = '6a369d5166020ed05b321259'; // Phase 6: Deep Learning Core

const m54 = '6a369d5166020ed05b32125c';
const m55 = '6a369d5166020ed05b32125f';
const m56 = '6a369d5166020ed05b321262';
const m57 = '6a369d5166020ed05b321265';
const m58 = '6a369d5166020ed05b321268';
const m59 = '6a369d5166020ed05b32126b';
const m60 = '6a369d5166020ed05b32126e';
const m61 = '6a369d5166020ed05b321271';
const m62 = '6a369d5166020ed05b321274';
const m63 = '6a369d5166020ed05b321277';
const m64 = '6a369d5266020ed05b32127a';
const m65 = '6a369d5266020ed05b32127d';
const m66 = '6a369d5266020ed05b321280';

const l54 = '6aaabf19aed16ac0c1a70ec5';
const l55 = '6aaabf9a2402c5cb2faf6a8e';
const l56 = '6aaac05e21939197c4d9253e';
const l57 = '6aaae77172ac05b6bcf6990c';
const l58 = '6aaae7ee9add4253dd280296';
const l59 = '6aaae8ce4e43ea97fb12b1d5';
const l60 = '6aaae984410d56d124fe607d';
const l61 = '6aaaea42d64386d0b2bcd181';
const l62 = '6aaaeb0ef77a800e26403936';
const l63 = '6aaaebc9a2789cc5a476ed50';
const l64 = '6aaaec7a8bc68cf8312696ca';
const l65 = '6aaaedd42ffe5f107b8e8800';
const l66 = '6aaaee86a0f420519c3701cb';

module.exports = [
  // ── Module 54: Introduction to Deep Learning ──
  { phaseId, moduleId: m54, lessonId: l54, order: 1, difficulty: 'beginner',
    title: 'Reproducing the Single-Neuron XOR Ceiling',
    titleKn: 'Single-Neuron XOR Ceiling ಅನ್ನೂ ಮರುಉತ್ಪಾದಿಸುವುದೂ',
    problem: "The lesson genuinely tried 2000 random single-neuron weight settings on XOR and found a best accuracy of 75%.\n1. Run the lesson's exact single-neuron search loop yourself. Do you also get stuck around 75%, or can you occasionally beat it with a different random seed?\n2. List all 4 XOR input/output pairs. For any single straight decision boundary (one line in 2D space), show that it's impossible to separate all 4 points correctly — this is why 75% (3 out of 4) is the ceiling, not 100%.\n3. The lesson's 2-layer network reached 100% accuracy on the same problem. What changed structurally that made this possible?",
    problemKn: "ಪಾಠ XOR ಮೇಲೆ 2000 ಯಾದೃಚ್ಛಿಕ single-neuron weight settings ನಿಜವಾಗಿ ಪ್ರಯತ್ನಿಸಿ 75% ಅತ್ಯುತ್ತಮ ನಿಖರತೆ ಕಂಡುಕೊಂಡಿತು.\n1. ಪಾಠದ ನಿಖರ single-neuron search loop ನೀವೇ ಚಲಾಯಿಸಿ. ನೀವೂ ಸುಮಾರು 75% ಗೆ ಸಿಲುಕುತ್ತೀರಾ, ಅಥವಾ ಬೇರೆ random seed ಜೊತೆ ಕೆಲವೊಮ್ಮೆ ಅದನ್ನೂ ಮೀರಿಸಬಹುದೇ?\n2. ಎಲ್ಲಾ 4 XOR input/output pairs ಪಟ್ಟಿ ಮಾಡಿ. ಯಾವುದೇ ಒಂದೂ ನೇರ ನಿರ್ಧಾರ ಗಡಿಗೆ (2D ನಲ್ಲಿ ಒಂದೂ ರೇಖೆ), ಎಲ್ಲಾ 4 ಬಿಂದುಗಳನ್ನೂ ಸರಿಯಾಗಿ ಪ್ರತ್ಯೇಕಿಸುವುದೂ ಅಸಾಧ್ಯ ಎಂದು ತೋರಿಸಿ.\n3. ಅದೇ ಸಮಸ್ಯೆಯ ಮೇಲೆ ಪಾಠದ 2-layer network 100% ನಿಖರತೆ ತಲುಪಿತು. ಇದನ್ನೂ ಸಾಧ್ಯವಾಗಿಸಿದ ರಚನಾತ್ಮಕ ಬದಲಾವಣೆ ಏನೂ?" },
  { phaseId, moduleId: m54, lessonId: l54, order: 2, difficulty: 'beginner',
    title: 'Hand-Computing a Single Neuron',
    titleKn: 'ಒಂದೂ Single Neuron ಅನ್ನೂ ಕೈಯಾರೆ ಲೆಕ್ಕಾಚಾರ',
    problem: "Using the lesson's exact single neuron: x=[0.5,-0.2,0.1], w=[0.4,0.9,-0.5], b=0.1.\n1. Manually compute z = w·x + b step by step (multiply each pair, sum, add bias). Confirm it matches the lesson's genuine output of 0.06999999999999999.\n2. Manually compute sigmoid(z) = 1/(1+e^-z) using a calculator or by hand with e ≈ 2.71828. Confirm it's close to the lesson's 0.5174928576663897.\n3. If you increased b to 2.0 instead of 0.1, would the sigmoid output move closer to 1 or closer to 0? Explain why using the shape of the sigmoid function.",
    problemKn: "ಪಾಠದ ನಿಖರ single neuron ಬಳಸಿ: x=[0.5,-0.2,0.1], w=[0.4,0.9,-0.5], b=0.1.\n1. z = w·x + b ಅನ್ನೂ ಹಂತ ಹಂತವಾಗಿ ಕೈಯಾರೆ ಲೆಕ್ಕಾಚಾರ ಮಾಡಿ. ಇದೂ ಪಾಠದ ನಿಜ output 0.0699999... ಗೆ ಹೊಂದುತ್ತದೆ ಎಂದು ಖಚಿತಪಡಿಸಿ.\n2. sigmoid(z) = 1/(1+e^-z) ಅನ್ನೂ ಕೈಯಾರೆ ಲೆಕ್ಕಾಚಾರ ಮಾಡಿ, e ≈ 2.71828 ಬಳಸಿ. ಇದೂ 0.5175 ಗೆ ಹತ್ತಿರವಾಗಿದೆ ಎಂದು ಖಚಿತಪಡಿಸಿ.\n3. b ಅನ್ನೂ 0.1 ಬದಲಿಗೆ 2.0 ಗೆ ಹೆಚ್ಚಿಸಿದರೆ, sigmoid output 1 ಗೆ ಹತ್ತಿರವಾಗುತ್ತದೆಯೇ ಅಥವಾ 0 ಗೆ? sigmoid function ya ಆಕಾರ ಬಳಸಿ ವಿವರಿಸಿ." },
  { phaseId, moduleId: m54, lessonId: l54, order: 3, difficulty: 'intermediate',
    title: 'Why Depth Matters — Building Your Own 2-Layer XOR Solver',
    titleKn: 'Depth ಏಕೆ ಮುಖ್ಯ — ನಿಮ್ಮ ಸ್ವಂತ 2-Layer XOR Solver ನಿರ್ಮಿಸುವುದೂ',
    problem: "Run the lesson's exact 2-layer network code that solved XOR.\n1. Confirm you get accuracy 1.0 with final predictions close to [0.015, 0.983, 0.983, 0.014] matching true labels [0,1,1,0].\n2. Change the hidden layer size from 2 neurons to just 1 neuron. Retrain and report the accuracy. Does 1 hidden neuron still solve XOR?\n3. Based on your result, what's the minimum number of hidden neurons this lesson's architecture needs to reliably solve XOR?",
    problemKn: "XOR ಪರಿಹರಿಸಿದ ಪಾಠದ ನಿಖರ 2-layer network code ಚಲಾಯಿಸಿ.\n1. ನಿಮಗೆ ನಿಜ predictions [0.015, 0.983, 0.983, 0.014] ಜೊತೆ accuracy 1.0 ಸಿಗುತ್ತದೆ ಎಂದು ಖಚಿತಪಡಿಸಿ.\n2. hidden layer size ಅನ್ನೂ 2 neurons ಇಂದ ಕೇವಲ 1 neuron ಗೆ ಬದಲಾಯಿಸಿ. ಮರುತರಬೇತಿ ನೀಡಿ ಮತ್ತು accuracy ವರದಿ ಮಾಡಿ. 1 hidden neuron ಇನ್ನೂ XOR ಪರಿಹರಿಸುತ್ತದೆಯೇ?\n3. ನಿಮ್ಮ ಫಲಿತಾಂಶ ಆಧರಿಸಿ, ಈ ಪಾಠದ architecture XOR ಅನ್ನೂ ವಿಶ್ವಾಸಾರ್ಹವಾಗಿ ಪರಿಹರಿಸಲು ಕನಿಷ್ಠ ಎಷ್ಟು hidden neurons ಬೇಕು?" },

  // ── Module 55: Multilayer Networks and Forward Pass ──
  { phaseId, moduleId: m55, lessonId: l55, order: 1, difficulty: 'beginner',
    title: 'Verifying Shapes Through the Sequential Container',
    titleKn: 'Sequential Container ಮೂಲಕ Shapes ಪರಿಶೀಲಿಸುವುದೂ',
    problem: "The lesson's Sequential([DenseLayer(4,8,relu), DenseLayer(8,4,relu), DenseLayer(4,1,sigmoid)]) on a batch of shape (5,4) genuinely produced shapes (5,8) -> (5,4) -> (5,1).\n1. Run this exact code and confirm the same shape sequence.\n2. For a DenseLayer(n_in, n_out), explain in your own words why the OUTPUT shape's last dimension is always n_out regardless of batch size.\n3. If you changed the batch size from 5 to 20, which shapes in the sequence change and which stay the same?",
    problemKn: "(5,4) shape ya batch ಮೇಲೆ ಪಾಠದ Sequential([DenseLayer(4,8,relu), DenseLayer(8,4,relu), DenseLayer(4,1,sigmoid)]) ನಿಜವಾಗಿ (5,8) -> (5,4) -> (5,1) shapes ಉತ್ಪಾದಿಸಿತು.\n1. ಈ ನಿಖರ code ಚಲಾಯಿಸಿ ಮತ್ತು ಅದೇ shape ಅನುಕ್ರಮ ಖಚಿತಪಡಿಸಿ.\n2. DenseLayer(n_in, n_out) ಗೆ, OUTPUT shape ya ಕೊನೆಯ dimension ಯಾವಾಗಲೂ batch size ಲೆಕ್ಕಿಸದೆ n_out ಆಗಿರುವುದೂ ಏಕೆ ಎಂದು ನಿಮ್ಮ ಸ್ವಂತ ಪದಗಳಲ್ಲಿ ವಿವರಿಸಿ.\n3. batch size ಅನ್ನೂ 5 ಇಂದ 20 ಗೆ ಬದಲಾಯಿಸಿದರೆ, ಅನುಕ್ರಮದಲ್ಲಿ ಯಾವ shapes ಬದಲಾಗುತ್ತವೆ ಮತ್ತು ಯಾವುವು ಒಂದೇ ಆಗಿ ಉಳಿಯುತ್ತವೆ?" },
  { phaseId, moduleId: m55, lessonId: l55, order: 2, difficulty: 'intermediate',
    title: 'Counting Trainable Parameters by Hand',
    titleKn: 'Trainable Parameters ಅನ್ನೂ ಕೈಯಾರೆ ಎಣಿಸುವುದೂ',
    problem: "The lesson's 3-layer network (4->8, 8->4, 4->1) genuinely reported: Layer 0: 40 params, Layer 1: 36 params, Layer 2: 5 params, Total: 81.\n1. For a DenseLayer(n_in, n_out), derive the formula for its parameter count (weights + biases) and confirm it gives 40, 36, and 5 for the three layers.\n2. The lesson's deeper network (4->16, 16->16, 16->8, 8->1) reported a total of 497 parameters. Using your formula, verify this total by computing each layer's contribution.\n3. Which single layer in the deeper network contributes the most parameters, and why does the 16->16 layer cost more than the 4->16 layer despite having fewer output units difference?",
    problemKn: "ಪಾಠದ 3-layer network (4->8, 8->4, 4->1) ನಿಜವಾಗಿ ವರದಿ ಮಾಡಿತು: Layer 0: 40 params, Layer 1: 36 params, Layer 2: 5 params, Total: 81.\n1. DenseLayer(n_in, n_out) ಗೆ, ಅದರ parameter count (weights + biases) ಗಾಗಿ formula ಪಡೆಯಿರಿ ಮತ್ತು ಇದೂ ಮೂರು layers ಗೆ 40, 36, ಮತ್ತು 5 ನೀಡುತ್ತದೆ ಎಂದು ಖಚಿತಪಡಿಸಿ.\n2. ಪಾಠದ ಆಳವಾದ network (4->16, 16->16, 16->8, 8->1) 497 parameters ya ಒಟ್ಟು ವರದಿ ಮಾಡಿತು. ನಿಮ್ಮ formula ಬಳಸಿ, ಪ್ರತಿ layer ya ಕೊಡುಗೆ ಲೆಕ್ಕಾಚಾರ ಮಾಡಿ ಈ ಒಟ್ಟನ್ನೂ ಪರಿಶೀಲಿಸಿ.\n3. ಆಳವಾದ network ನಲ್ಲಿ ಯಾವ ಒಂದೂ layer ಅತ್ಯಧಿಕ parameters ಕೊಡುಗೆ ನೀಡುತ್ತದೆ, ಮತ್ತು 16->16 layer 4->16 layer ಗಿಂತ ಏಕೆ ಹೆಚ್ಚು ವೆಚ್ಚ ಮಾಡುತ್ತದೆ?" },
  { phaseId, moduleId: m55, lessonId: l55, order: 3, difficulty: 'beginner',
    title: 'Building Your Own DenseLayer Chain',
    titleKn: 'ನಿಮ್ಮ ಸ್ವಂತ DenseLayer Chain ನಿರ್ಮಿಸುವುದೂ',
    problem: "1. Using the lesson's exact DenseLayer class, build a 4-layer Sequential network that takes input of shape (n, 10) and produces output of shape (n, 1), choosing your own hidden sizes for the two middle layers.\n2. Run it on a batch of 3 random examples and print the shape after each layer.\n3. Compute the total trainable parameter count for your network using param_count().",
    problemKn: "1. ಪಾಠದ ನಿಖರ DenseLayer class ಬಳಸಿ, (n, 10) shape input ತೆಗೆದುಕೊಂಡು (n, 1) shape output ಉತ್ಪಾದಿಸುವ ಒಂದೂ 4-layer Sequential network ನಿರ್ಮಿಸಿ, ಎರಡೂ ಮಧ್ಯದ layers ಗೆ ನಿಮ್ಮ ಸ್ವಂತ hidden sizes ಆಯ್ಕೆ ಮಾಡಿ.\n2. 3 ಯಾದೃಚ್ಛಿಕ examples ya batch ಮೇಲೆ ಇದೂ ಚಲಾಯಿಸಿ ಮತ್ತು ಪ್ರತಿ layer ನಂತರ shape ಪ್ರಿಂಟ್ ಮಾಡಿ.\n3. param_count() ಬಳಸಿ ನಿಮ್ಮ network ya ಒಟ್ಟೂ trainable parameter count ಲೆಕ್ಕಾಚಾರ ಮಾಡಿ." },

  // ── Module 56: Backpropagation from Scratch ──
  { phaseId, moduleId: m56, lessonId: l56, order: 1, difficulty: 'intermediate',
    title: 'Reproducing the Training Curve',
    titleKn: 'Training Curve ಅನ್ನೂ ಮರುಉತ್ಪಾದಿಸುವುದೂ',
    problem: "The lesson's Network.backward() trained on XOR and genuinely showed: epoch 0: loss=0.24213, epoch 4000: loss=0.00013, final accuracy=1.0.\n1. Run the lesson's exact Network class and training loop. Confirm your loss decreases in the same general pattern (starts around 0.2, ends near 0.0001).\n2. Print the loss at every 500 epochs instead of every 1000. Is the decrease smooth, or does it plateau at any point?\n3. What would you expect to see in the printed loss if the learning rate (lr) passed to backward() were set far too high, like 5.0 instead of the lesson's value? Try it and report what actually happens.",
    problemKn: "ಪಾಠದ Network.backward() XOR ಮೇಲೆ ತರಬೇತಿ ಪಡೆದು ನಿಜವಾಗಿ ತೋರಿಸಿತು: epoch 0: loss=0.24213, epoch 4000: loss=0.00013, final accuracy=1.0.\n1. ಪಾಠದ ನಿಖರ Network class ಮತ್ತು training loop ಚಲಾಯಿಸಿ. ನಿಮ್ಮ loss ಅದೇ ಸಾಮಾನ್ಯ ಮಾದರಿಯಲ್ಲಿ ಕಡಿಮೆಯಾಗುತ್ತದೆ ಎಂದು ಖಚಿತಪಡಿಸಿ.\n2. loss ಅನ್ನೂ ಪ್ರತಿ 1000 ಬದಲಿಗೆ ಪ್ರತಿ 500 epochs ಗೆ ಪ್ರಿಂಟ್ ಮಾಡಿ. ಇಳಿಕೆ ಸುಗಮವಾಗಿದೆಯೇ, ಅಥವಾ ಯಾವುದೇ ಬಿಂದುವಿನಲ್ಲಿ ಸ್ಥಿರಗೊಳ್ಳುತ್ತದೆಯೇ?\n3. backward() ಗೆ ರವಾನಿಸಿದ learning rate (lr) ಪಾಠದ ಮೌಲ್ಯಕ್ಕಿಂತ 5.0 ರಂತೆ ಬಹಳ ಹೆಚ್ಚಾಗಿದ್ದರೆ ಮುದ್ರಿತ loss ನಲ್ಲಿ ಏನೂ ಕಾಣಿಸಬಹುದು ಎಂದು ನೀವೂ ನಿರೀಕ್ಷಿಸುತ್ತೀರಿ? ಪ್ರಯತ್ನಿಸಿ ಮತ್ತು ನಿಜವಾಗಿ ಏನಾಗುತ್ತದೆ ಎಂದು ವರದಿ ಮಾಡಿ." },
  { phaseId, moduleId: m56, lessonId: l56, order: 2, difficulty: 'advanced',
    title: 'Genuinely Running the Numerical Gradient Check',
    titleKn: 'Numerical Gradient Check ಅನ್ನೂ ನಿಜವಾಗಿ ಚಲಾಯಿಸುವುದೂ',
    problem: "The lesson's numerical gradient check compared analytic vs numeric dW and found a max absolute difference of about 1.76e-12 -- essentially zero.\n1. Run the lesson's exact finite-difference check code (eps=1e-5) against your own backward() implementation. Report your max absolute difference.\n2. Change eps from 1e-5 to 1e-2 (a much coarser step). Does the max absolute difference get noticeably worse? Why does a larger eps introduce more numerical error into a finite-difference approximation?\n3. If your analytic gradient had a genuine bug (e.g. you forgot to multiply by the activation derivative), would this numerical check catch it? Deliberately introduce such a bug and confirm the max difference blows up to a non-trivial number.",
    problemKn: "ಪಾಠದ numerical gradient check analytic vs numeric dW ಹೋಲಿಸಿ ಸುಮಾರು 1.76e-12 ya ಗರಿಷ್ಠ absolute ವ್ಯತ್ಯಾಸ ಕಂಡುಕೊಂಡಿತು -- ಬಹುತೇಕ ಶೂನ್ಯ.\n1. ನಿಮ್ಮ ಸ್ವಂತ backward() implementation ವಿರುದ್ಧ ಪಾಠದ ನಿಖರ finite-difference check code (eps=1e-5) ಚಲಾಯಿಸಿ. ನಿಮ್ಮ ಗರಿಷ್ಠ absolute ವ್ಯತ್ಯಾಸ ವರದಿ ಮಾಡಿ.\n2. eps ಅನ್ನೂ 1e-5 ಇಂದ 1e-2 ಗೆ ಬದಲಾಯಿಸಿ. ಗರಿಷ್ಠ absolute ವ್ಯತ್ಯಾಸ ಗಮನಾರ್ಹವಾಗಿ ಕೆಟ್ಟದಾಗುತ್ತದೆಯೇ?\n3. ನಿಮ್ಮ analytic gradient ಒಂದೂ ನಿಜ bug ಹೊಂದಿದ್ದರೆ (ಉದಾ activation derivative ಜೊತೆ ಗುಣಿಸಲು ಮರೆತರೆ), ಈ numerical check ಇದನ್ನೂ ಹಿಡಿಯುತ್ತದೆಯೇ? ಉದ್ದೇಶಪೂರ್ವಕವಾಗಿ ಅಂತಹ bug ಪರಿಚಯಿಸಿ ಮತ್ತು ಗರಿಷ್ಠ ವ್ಯತ್ಯಾಸ ಗಣನೀಯ ಸಂಖ್ಯೆಗೆ ಏರುತ್ತದೆ ಎಂದು ಖಚಿತಪಡಿಸಿ." },
  { phaseId, moduleId: m56, lessonId: l56, order: 3, difficulty: 'intermediate',
    title: 'Why the Activation Derivative Differs by Layer',
    titleKn: 'Activation Derivative Layer ಪ್ರಕಾರ ಏಕೆ ಭಿನ್ನವಾಗಿದೆ',
    problem: "The lesson's Network class stores a separate activation_deriv for each DenseLayer (e.g. relu_deriv for hidden layers, sigmoid_deriv for the output layer).\n1. Why can't a single shared activation_deriv function work for a network that mixes ReLU hidden layers with a sigmoid output layer?\n2. Write out relu_deriv(z) and sigmoid_deriv(a) as Python one-liners and explain why sigmoid_deriv takes the ACTIVATED value (a) while relu_deriv can take the PRE-activation value (z).\n3. If you accidentally swapped which activation_deriv belongs to which layer, would the numerical gradient check from the previous exercise still pass? Explain your reasoning.",
    problemKn: "ಪಾಠದ Network class ಪ್ರತಿ DenseLayer ಗೆ ಪ್ರತ್ಯೇಕ activation_deriv ಸಂಗ್ರಹಿಸುತ್ತದೆ.\n1. ReLU hidden layers ಮತ್ತು ಒಂದೂ sigmoid output layer ಬೆರೆಸುವ network ಗೆ ಒಂದೇ ಹಂಚಿದ activation_deriv function ಏಕೆ ಕೆಲಸ ಮಾಡುವುದಿಲ್ಲ?\n2. relu_deriv(z) ಮತ್ತು sigmoid_deriv(a) ಅನ್ನೂ Python one-liners ಆಗಿ ಬರೆಯಿರಿ ಮತ್ತು sigmoid_deriv ACTIVATED ಮೌಲ್ಯ (a) ಏಕೆ ತೆಗೆದುಕೊಳ್ಳುತ್ತದೆ ಎಂದು ವಿವರಿಸಿ.\n3. ಯಾವ activation_deriv ಯಾವ layer ಗೆ ಸೇರಿದೆ ಎಂದು ನೀವೂ ಆಕಸ್ಮಿಕವಾಗಿ ಅದಲುಬದಲು ಮಾಡಿದರೆ, ಹಿಂದಿನ ವ್ಯಾಯಾಮದ numerical gradient check ಇನ್ನೂ ಪಾಸ್ ಆಗುತ್ತದೆಯೇ? ನಿಮ್ಮ ತರ್ಕ ವಿವರಿಸಿ." },

  // ── Module 57: Activation Functions ──
  { phaseId, moduleId: m57, lessonId: l57, order: 1, difficulty: 'beginner',
    title: 'Comparing Sigmoid, ReLU, and GELU Side by Side',
    titleKn: 'Sigmoid, ReLU, ಮತ್ತು GELU ಅನ್ನೂ ಜೊತೆಯಾಗಿ ಹೋಲಿಸುವುದೂ',
    problem: "The lesson computed all three activations on x=[-3,-1,0,1,3], genuinely getting sigmoid=[0.0474,0.2689,0.5,0.7311,0.9526], relu=[0,0,0,1,3], gelu=[-0.0036,-0.1588,0,0.8412,2.9964].\n1. Run the lesson's exact code and confirm these numbers.\n2. At x=-1, ReLU outputs exactly 0 but GELU outputs -0.1588 (a small negative number). Explain this difference in your own words -- what does it mean for GELU to be 'smooth' near zero compared to ReLU's hard cutoff?\n3. At x=3, all three functions give a positive output but different magnitudes (0.9526, 3, 2.9964). Why does sigmoid saturate near 1 while ReLU and GELU keep growing with x?",
    problemKn: "ಪಾಠ x=[-3,-1,0,1,3] ಮೇಲೆ ಮೂರೂ activations ಲೆಕ್ಕಾಚಾರ ಮಾಡಿತು.\n1. ಪಾಠದ ನಿಖರ code ಚಲಾಯಿಸಿ ಮತ್ತು ಈ ಸಂಖ್ಯೆಗಳನ್ನೂ ಖಚಿತಪಡಿಸಿ.\n2. x=-1 ನಲ್ಲಿ, ReLU ನಿಖರವಾಗಿ 0 ಉತ್ಪಾದಿಸುತ್ತದೆ ಆದರೆ GELU -0.1588 ಉತ್ಪಾದಿಸುತ್ತದೆ. ಈ ವ್ಯತ್ಯಾಸವನ್ನೂ ನಿಮ್ಮ ಸ್ವಂತ ಪದಗಳಲ್ಲಿ ವಿವರಿಸಿ.\n3. x=3 ನಲ್ಲಿ, ಮೂರೂ functions ಧನಾತ್ಮಕ output ನೀಡುತ್ತವೆ ಆದರೆ ವಿಭಿನ್ನ ಪ್ರಮಾಣಗಳಲ್ಲಿ. sigmoid 1 ಹತ್ತಿರ ಏಕೆ saturate ಆಗುತ್ತದೆ ಆದರೆ ReLU ಮತ್ತು GELU x ಜೊತೆ ಬೆಳೆಯುತ್ತಲೇ ಇರುತ್ತವೆ?" },
  { phaseId, moduleId: m57, lessonId: l57, order: 2, difficulty: 'intermediate',
    title: 'The Vanishing Gradient, Genuinely Measured',
    titleKn: 'Vanishing Gradient, ನಿಜವಾಗಿ ಅಳೆಯಲಾಗಿದೆ',
    problem: "The lesson genuinely measured sigmoid_deriv(0)=0.25, sigmoid_deriv(5)=0.00664806, sigmoid_deriv(10)=4.53958077e-05.\n1. Run this exact code and confirm the three values.\n2. Sigmoid's maximum possible derivative is 0.25 (at x=0). If you stack 20 sigmoid layers and each contributes at most a factor of 0.25 to the backprop chain, what's the theoretical maximum gradient magnitude after 20 layers (0.25^20)? Compare this to the lesson's actually measured 1.08e-17 for 20 stacked sigmoid layers -- is the actual value even smaller than this theoretical ceiling?\n3. Run the lesson's 20-layer sigmoid-vs-ReLU comparison. Confirm sigmoid gives ~1e-17 while ReLU gives exactly 0.0. Why does ReLU's gradient hit exactly zero rather than just being 'small'?",
    problemKn: "ಪಾಠ ನಿಜವಾಗಿ sigmoid_deriv(0)=0.25, sigmoid_deriv(5)=0.00664806, sigmoid_deriv(10)=4.53958077e-05 ಅಳೆಯಿತು.\n1. ಈ ನಿಖರ code ಚಲಾಯಿಸಿ ಮತ್ತು ಮೂರೂ ಮೌಲ್ಯಗಳನ್ನೂ ಖಚಿತಪಡಿಸಿ.\n2. Sigmoid ya ಗರಿಷ್ಠ ಸಾಧ್ಯ derivative 0.25 (x=0 ನಲ್ಲಿ). 20 sigmoid layers stack ಮಾಡಿದರೆ, 20 layers ನಂತರ ಸೈದ್ಧಾಂತಿಕ ಗರಿಷ್ಠ gradient magnitude ಏನೂ (0.25^20)? ಇದನ್ನೂ ಪಾಠದ ನಿಜ ಅಳೆದ 1.08e-17 ಜೊತೆ ಹೋಲಿಸಿ.\n3. ಪಾಠದ 20-layer sigmoid-vs-ReLU ಹೋಲಿಕೆ ಚಲಾಯಿಸಿ. sigmoid ~1e-17 ನೀಡುತ್ತದೆ ಆದರೆ ReLU ನಿಖರವಾಗಿ 0.0 ನೀಡುತ್ತದೆ ಎಂದು ಖಚಿತಪಡಿಸಿ. ReLU ya gradient ಕೇವಲ 'ಚಿಕ್ಕದಾಗಿರುವ' ಬದಲಿಗೆ ನಿಖರವಾಗಿ ಶೂನ್ಯ ಏಕೆ ಹೊಡೆಯುತ್ತದೆ?" },
  { phaseId, moduleId: m57, lessonId: l57, order: 3, difficulty: 'advanced',
    title: 'Genuinely Triggering Dying ReLU',
    titleKn: 'Dying ReLU ಅನ್ನೂ ನಿಜವಾಗಿ ಪ್ರಚೋದಿಸುವುದೂ',
    problem: "Run the lesson's 20-layer ReLU stack experiment (random weights, no careful initialization) and confirm the final gradient magnitude is exactly 0.0.\n1. Reduce the depth from 20 layers to 5 layers, keeping everything else the same. Is the gradient still exactly 0.0, or does some signal survive?\n2. The lesson's Module 66 (Debugging Neural Networks) separately showed dead ReLU units caused by large negative biases. How is that dead-unit phenomenon related to (but different from) this depth-caused vanishing gradient?\n3. Name one practical fix from the lesson (or your own knowledge) that reduces the risk of ReLU gradients vanishing across many layers.",
    problemKn: "ಪಾಠದ 20-layer ReLU stack experiment (ಯಾದೃಚ್ಛಿಕ weights, ಜಾಗರೂಕ initialization ಇಲ್ಲದೆ) ಚಲಾಯಿಸಿ ಮತ್ತು ಅಂತಿಮ gradient magnitude ನಿಖರವಾಗಿ 0.0 ಎಂದು ಖಚಿತಪಡಿಸಿ.\n1. depth ಅನ್ನೂ 20 layers ಇಂದ 5 layers ಗೆ ಕಡಿಮೆ ಮಾಡಿ, ಉಳಿದೆಲ್ಲವೂ ಒಂದೇ ಇಟ್ಟುಕೊಂಡು. gradient ಇನ್ನೂ ನಿಖರವಾಗಿ 0.0 ಆಗಿದೆಯೇ, ಅಥವಾ ಕೆಲವು signal ಬದುಕುಳಿಯುತ್ತದೆಯೇ?\n2. ಪಾಠದ Module 66 (Debugging Neural Networks) ದೊಡ್ಡ ಋಣಾತ್ಮಕ biases ಇಂದ ಉಂಟಾದ dead ReLU units ಪ್ರತ್ಯೇಕವಾಗಿ ತೋರಿಸಿತು. ಆ dead-unit ವಿದ್ಯಮಾನ ಈ depth-caused vanishing gradient ಗೆ ಹೇಗೂ ಸಂಬಂಧಿಸಿದೆ (ಆದರೆ ಭಿನ್ನವಾಗಿದೆ)?\n3. ReLU gradients ಅನೇಕ layers ಆದ್ಯಂತ ಮಾಯವಾಗುವ ಅಪಾಯ ಕಡಿಮೆ ಮಾಡುವ ಒಂದೂ ಪ್ರಾಯೋಗಿಕ ಪರಿಹಾರ ಹೆಸರಿಸಿ." },

  // ── Module 58: Loss Functions ──
  { phaseId, moduleId: m58, lessonId: l58, order: 1, difficulty: 'intermediate',
    title: 'MSE vs Cross-Entropy on a Confidently Wrong Prediction',
    titleKn: 'MSE vs Cross-Entropy ಒಂದೂ Confidently Wrong Prediction ಮೇಲೆ',
    problem: "The lesson fed a confidently wrong prediction (true label=1, z=-5, pred=0.0067) through both MSE and BCE, genuinely finding the BCE gradient magnitude was 75.2x larger than MSE's.\n1. Run the lesson's exact code and confirm pred=0.0066928509242848554, MSE loss=0.9867, BCE loss=5.0067, and the ~75.2x gradient ratio.\n2. Why does BCE punish a confidently wrong prediction so much more harshly than MSE, in terms of how each loss's gradient behaves as pred approaches 0 while y_true=1?\n3. In practical terms, why does this matter for how fast a classifier trained with BCE learns to correct a badly wrong prediction compared to one trained with MSE?",
    problemKn: "ಪಾಠ ಒಂದೂ confidently wrong prediction (true label=1, z=-5, pred=0.0067) ಅನ್ನೂ MSE ಮತ್ತು BCE ಎರಡರ ಮೂಲಕವೂ ರವಾನಿಸಿ, BCE gradient magnitude MSE ಗಿಂತ 75.2x ದೊಡ್ಡದಾಗಿದೆ ಎಂದು ನಿಜವಾಗಿ ಕಂಡುಕೊಂಡಿತು.\n1. ಪಾಠದ ನಿಖರ code ಚಲಾಯಿಸಿ ಮತ್ತು ಈ ಮೌಲ್ಯಗಳನ್ನೂ ಖಚಿತಪಡಿಸಿ.\n2. pred 0 ಗೆ ಹತ್ತಿರವಾಗುತ್ತಿರುವಾಗ y_true=1 ಇದ್ದಾಗ, BCE ಏಕೆ MSE ಗಿಂತ ಬಹಳ ಹೆಚ್ಚು ಕಠಿಣವಾಗಿ ಒಂದೂ confidently wrong prediction ಅನ್ನೂ ಶಿಕ್ಷಿಸುತ್ತದೆ?\n3. ಪ್ರಾಯೋಗಿಕವಾಗಿ, BCE ಜೊತೆ ತರಬೇತಿ ಪಡೆದ ಒಂದೂ classifier ಒಂದೂ ಕೆಟ್ಟದಾಗಿ ತಪ್ಪಾದ prediction ಸರಿಪಡಿಸಲು ಎಷ್ಟು ವೇಗವಾಗಿ ಕಲಿಯುತ್ತದೆ ಎಂಬುದಕ್ಕೆ ಇದೂ ಏಕೆ ಮುಖ್ಯ?" },
  { phaseId, moduleId: m58, lessonId: l58, order: 2, difficulty: 'intermediate',
    title: 'Contrastive Loss With a Harder Negative',
    titleKn: 'ಒಂದೂ Harder Negative ಜೊತೆ Contrastive Loss',
    problem: "The lesson's contrastive loss (margin=0.2) genuinely gave: cosine(anchor,positive)=0.9913, cosine(anchor,negative)=-0.6777, loss=0. With a harder negative, cosine(anchor,harder_negative)=0.9801 and loss became 0.1888.\n1. Run the lesson's exact code and confirm both loss values.\n2. Explain why the easy negative produced zero loss but the harder negative produced a positive loss, in terms of the margin formula max(0, margin - (sim_pos - sim_neg)).\n3. Compute by hand: if sim_pos stayed at 0.9913 but the negative's similarity to the anchor were exactly 0.7913, what would the contrastive loss be? Verify your hand calculation in code.",
    problemKn: "ಪಾಠದ contrastive loss (margin=0.2) ನಿಜವಾಗಿ ನೀಡಿತು: cosine(anchor,positive)=0.9913, cosine(anchor,negative)=-0.6777, loss=0. ಹೆಚ್ಚು ಕಠಿಣ negative ಜೊತೆ, loss 0.1888 ಆಯಿತು.\n1. ಪಾಠದ ನಿಖರ code ಚಲಾಯಿಸಿ ಮತ್ತು ಎರಡೂ loss ಮೌಲ್ಯಗಳನ್ನೂ ಖಚಿತಪಡಿಸಿ.\n2. max(0, margin - (sim_pos - sim_neg)) formula ಆಧರಿಸಿ, ಸುಲಭ negative ಶೂನ್ಯ loss ಏಕೆ ಉತ್ಪಾದಿಸಿತು ಆದರೆ ಕಠಿಣ negative ಧನಾತ್ಮಕ loss ಉತ್ಪಾದಿಸಿತು ಎಂದು ವಿವರಿಸಿ.\n3. ಕೈಯಾರೆ ಲೆಕ್ಕಾಚಾರ ಮಾಡಿ: sim_pos 0.9913 ಆಗಿಯೇ ಉಳಿದರೆ ಆದರೆ negative ya similarity ನಿಖರವಾಗಿ 0.7913 ಆಗಿದ್ದರೆ, contrastive loss ಏನೂ ಆಗಿರುತ್ತದೆ? code ನಲ್ಲಿ ನಿಮ್ಮ ಕೈ ಲೆಕ್ಕಾಚಾರ ಪರಿಶೀಲಿಸಿ." },
  { phaseId, moduleId: m58, lessonId: l58, order: 3, difficulty: 'beginner',
    title: 'Matching Loss Functions to Tasks',
    titleKn: 'Loss Functions ಅನ್ನೂ Tasks ಜೊತೆ ಹೊಂದಿಸುವುದೂ',
    problem: "Based on the lesson, decide which loss function fits each scenario and explain why:\n1. Predicting a continuous house price from features.\n2. Classifying an email as spam or not spam.\n3. Training an embedding model so that images of the same person end up close together and images of different people end up far apart.",
    problemKn: "ಪಾಠ ಆಧರಿಸಿ, ಪ್ರತಿ ಸನ್ನಿವೇಶಕ್ಕೆ ಯಾವ loss function ಸೂಕ್ತ ಎಂದು ನಿರ್ಧರಿಸಿ ಮತ್ತು ಏಕೆ ಎಂದು ವಿವರಿಸಿ:\n1. features ಇಂದ ಒಂದೂ ನಿರಂತರ house price ಊಹಿಸುವುದೂ.\n2. ಒಂದೂ email spam ಅಥವಾ spam ಅಲ್ಲ ಎಂದು ವರ್ಗೀಕರಿಸುವುದೂ.\n3. ಒಂದೇ ವ್ಯಕ್ತಿಯ images ಹತ್ತಿರ ಬರುವಂತೆ ಮತ್ತು ಬೇರೆ ವ್ಯಕ್ತಿಗಳ images ದೂರವಾಗುವಂತೆ ಒಂದೂ embedding model ತರಬೇತಿ ನೀಡುವುದೂ." },

  // ── Module 59: Optimizers ──
  { phaseId, moduleId: m59, lessonId: l59, order: 1, difficulty: 'intermediate',
    title: 'Reproducing the Ravine: SGD vs Momentum',
    titleKn: 'Ravine ಮರುಉತ್ಪಾದಿಸುವುದೂ: SGD vs Momentum',
    problem: "The lesson genuinely found: plain SGD (lr=0.05, 50 steps) reached loss=0.000664, but momentum with the SAME lr=0.05 reached a WORSE loss=0.727495, while momentum with lr=0.02 reached loss=0.180883.\n1. Run all three configurations exactly as the lesson did and confirm these numbers.\n2. This is counterintuitive -- momentum is supposed to help, but here it did worse at lr=0.05. Explain why momentum can overshoot in a ravine-shaped loss landscape when the same learning rate that worked for plain SGD is reused.\n3. Try momentum with lr=0.01 (even lower than 0.02). Does it get closer to plain SGD's final loss, or does momentum still lag behind even at lower learning rates within 50 steps?",
    problemKn: "ಪಾಠ ನಿಜವಾಗಿ ಕಂಡುಕೊಂಡಿತು: plain SGD (lr=0.05, 50 steps) loss=0.000664 ತಲುಪಿತು, ಆದರೆ momentum ಅದೇ lr=0.05 ಜೊತೆ ಕೆಟ್ಟ loss=0.727495 ತಲುಪಿತು.\n1. ಪಾಠ ಮಾಡಿದಂತೆ ನಿಖರವಾಗಿ ಎಲ್ಲಾ ಮೂರೂ configurations ಚಲಾಯಿಸಿ ಮತ್ತು ಈ ಸಂಖ್ಯೆಗಳನ್ನೂ ಖಚಿತಪಡಿಸಿ.\n2. ಇದೂ ಪ್ರತಿ-ಅರ್ಥಗರ್ಭಿತ -- momentum ಸಹಾಯ ಮಾಡಬೇಕು, ಆದರೆ ಇಲ್ಲಿ lr=0.05 ನಲ್ಲಿ ಇದೂ ಕೆಟ್ಟದಾಗಿ ಕೆಲಸ ಮಾಡಿತು. plain SGD ಗೆ ಕೆಲಸ ಮಾಡಿದ ಅದೇ learning rate ಮರುಬಳಕೆ ಮಾಡಿದಾಗ momentum ಒಂದೂ ravine-shaped loss landscape ನಲ್ಲಿ ಏಕೆ overshoot ಆಗಬಹುದು ಎಂದು ವಿವರಿಸಿ.\n3. lr=0.01 ಜೊತೆ momentum ಪ್ರಯತ್ನಿಸಿ. ಇದೂ plain SGD ya ಅಂತಿಮ loss ಗೆ ಹತ್ತಿರವಾಗುತ್ತದೆಯೇ?" },
  { phaseId, moduleId: m59, lessonId: l59, order: 2, difficulty: 'intermediate',
    title: 'Adam\'s Slow Start, Genuinely Traced',
    titleKn: 'Adam ya Slow Start, ನಿಜವಾಗಿ ಪತ್ತೆಹಚ್ಚಲಾಗಿದೆ',
    problem: "The lesson's Adam optimizer on the same ravine problem showed: step 50: loss=79.25, step 100: loss=13.85, step 200: loss=0.067, step 300: loss=0.000009.\n1. Run the lesson's exact Adam code for 300 steps and confirm these four checkpoints.\n2. Compare step 50's loss (79.25) to plain SGD's loss after just 50 steps (0.000664, from the earlier exercise). Why does Adam start out looking so much WORSE than plain SGD despite typically being considered a stronger optimizer?\n3. Adam eventually surpasses both plain SGD's and momentum's final losses by step 300. What do the bias-correction terms m_hat and v_hat in the lesson's code do, and why might they cause conservative (slow) updates in the first several steps?",
    problemKn: "ಅದೇ ravine ಸಮಸ್ಯೆಯ ಮೇಲೆ ಪಾಠದ Adam optimizer ತೋರಿಸಿತು: step 50: loss=79.25, step 300: loss=0.000009.\n1. ಪಾಠದ ನಿಖರ Adam code 300 steps ಗೆ ಚಲಾಯಿಸಿ ಮತ್ತು ಈ ನಾಲ್ಕೂ checkpoints ಖಚಿತಪಡಿಸಿ.\n2. step 50 ya loss (79.25) ಅನ್ನೂ plain SGD ya 50 steps ನಂತರದ loss (0.000664) ಜೊತೆ ಹೋಲಿಸಿ. ಸಾಮಾನ್ಯವಾಗಿ ಬಲವಾದ optimizer ಎಂದು ಪರಿಗಣಿಸಲ್ಪಟ್ಟರೂ Adam ಆರಂಭದಲ್ಲಿ ಏಕೆ ಇಷ್ಟೂ ಕೆಟ್ಟದಾಗಿ ಕಾಣುತ್ತದೆ?\n3. ಪಾಠದ code ನಲ್ಲಿ m_hat ಮತ್ತು v_hat bias-correction terms ಏನೂ ಮಾಡುತ್ತವೆ, ಮತ್ತು ಮೊದಲ ಹಲವಾರು steps ನಲ್ಲಿ ಅವು ಏಕೆ ಸಂಪ್ರದಾಯಸ್ಥ (ನಿಧಾನ) updates ಗೆ ಕಾರಣವಾಗಬಹುದು?" },
  { phaseId, moduleId: m59, lessonId: l59, order: 3, difficulty: 'advanced',
    title: 'Choosing an Optimizer for a New Problem',
    titleKn: 'ಒಂದೂ ಹೊಸ ಸಮಸ್ಯೆಗೆ ಒಂದೂ Optimizer ಆಯ್ಕೆ ಮಾಡುವುದೂ',
    problem: "Based on the genuine results from this lesson (SGD final loss 0.000664 in 50 steps, momentum worse at the same lr, Adam needing 300 steps to beat both):\n1. If you only have a tiny compute budget (50 steps) and a well-conditioned loss landscape, which optimizer from this lesson would you pick and why?\n2. If you have a much larger compute budget (thousands of steps) and don't know how well-conditioned your landscape is, which optimizer's behavior (from the trends you observed) seems safer as a default?\n3. Design and run a quick experiment: take the lesson's ravine loss/grad functions and time (using Python's time module) how long 300 steps of each of the three optimizers takes to run. Does the extra bookkeeping in Adam (m, v, bias correction) cost meaningfully more wall-clock time than plain SGD for this small problem?",
    problemKn: "ಈ ಪಾಠದ ನಿಜ ಫಲಿತಾಂಶಗಳ ಆಧಾರದ ಮೇಲೆ:\n1. ನಿಮಗೆ ಕೇವಲ ಒಂದೂ ಚಿಕ್ಕ compute budget (50 steps) ಮತ್ತು ಒಂದೂ well-conditioned loss landscape ಇದ್ದರೆ, ಈ ಪಾಠದಿಂದ ಯಾವ optimizer ಆಯ್ಕೆ ಮಾಡುತ್ತೀರಿ ಮತ್ತು ಏಕೆ?\n2. ನಿಮಗೆ ಬಹಳ ದೊಡ್ಡ compute budget ಇದ್ದರೆ, ಯಾವ optimizer ya ವರ್ತನೆ ಒಂದೂ default ಆಗಿ ಹೆಚ್ಚು ಸುರಕ್ಷಿತವಾಗಿ ಕಾಣುತ್ತದೆ?\n3. ಒಂದೂ ತ್ವರಿತ ಪ್ರಯೋಗ ವಿನ್ಯಾಸಗೊಳಿಸಿ ಮತ್ತು ಚಲಾಯಿಸಿ: ಪಾಠದ ravine loss/grad functions ತೆಗೆದುಕೊಂಡು, ಮೂರೂ optimizers ya ಪ್ರತಿಯೊಂದರ 300 steps ಎಷ್ಟು ಸಮಯ ತೆಗೆದುಕೊಳ್ಳುತ್ತದೆ ಎಂದು ಸಮಯ ನಿಗದಿಪಡಿಸಿ." },

  // ── Module 60: Regularization ──
  { phaseId, moduleId: m60, lessonId: l60, order: 1, difficulty: 'beginner',
    title: 'Verifying Dropout\'s Scaling',
    titleKn: 'Dropout ya Scaling ಪರಿಶೀಲಿಸುವುದೂ',
    problem: "The lesson's dropout(x, keep_prob=0.5) on x=ones((1,10)) genuinely produced values of 2.0 (not 1.0) for kept units, and across 10000 calls the mean was 0.99918 -- close to the original mean of 1.0.\n1. Run the lesson's exact dropout function and confirm kept units show as 2.0, not 1.0.\n2. Explain the role of dividing by keep_prob (the /keep_prob in the code) -- why does this keep the EXPECTED value of the output equal to the original input, even though individual calls look nothing like the input?\n3. Change keep_prob from 0.5 to 0.2 and rerun the 10000-call mean experiment. Does the mean across many calls still land close to 1.0? What do individual kept values look like now?",
    problemKn: "x=ones((1,10)) ಮೇಲೆ ಪಾಠದ dropout(x, keep_prob=0.5) ನಿಜವಾಗಿ ಉಳಿಸಿಕೊಂಡ units ಗೆ 2.0 (1.0 ಅಲ್ಲ) ಮೌಲ್ಯಗಳನ್ನೂ ಉತ್ಪಾದಿಸಿತು.\n1. ಪಾಠದ ನಿಖರ dropout function ಚಲಾಯಿಸಿ ಮತ್ತು ಉಳಿಸಿಕೊಂಡ units 2.0 ಎಂದು ತೋರಿಸುತ್ತದೆ ಎಂದು ಖಚಿತಪಡಿಸಿ.\n2. /keep_prob ya ಪಾತ್ರ ವಿವರಿಸಿ -- ಇದೂ output ya EXPECTED ಮೌಲ್ಯ ಮೂಲ input ಗೆ ಸಮಾನವಾಗಿ ಇಡುವುದೂ ಹೇಗೂ?\n3. keep_prob ಅನ್ನೂ 0.5 ಇಂದ 0.2 ಗೆ ಬದಲಾಯಿಸಿ ಮತ್ತು 10000-call mean experiment ಮರುಚಲಾಯಿಸಿ. mean ಇನ್ನೂ 1.0 ಗೆ ಹತ್ತಿರ ಇಳಿಯುತ್ತದೆಯೇ?" },
  { phaseId, moduleId: m60, lessonId: l60, order: 2, difficulty: 'intermediate',
    title: 'Weight Decay\'s Modest but Real Effect',
    titleKn: 'Weight Decay ya ಸಾಧಾರಣ ಆದರೆ ನಿಜ ಪರಿಣಾಮ',
    problem: "The lesson genuinely found: weight_decay=0.0 gave test_loss=3.3103 and weight_norm=13.748; weight_decay=0.1 gave test_loss=3.2081 and weight_norm=8.248.\n1. Run the lesson's exact train() function for all three weight_decay values (0.0, 0.01, 0.1) and confirm the reported test losses and weight norms.\n2. As weight_decay increases, weight_norm consistently decreases (13.748 -> 10.235 -> 8.248) while test_loss only modestly improves. Why does weight decay directly shrink weight_norm but only indirectly (and weakly, in this case) affect test performance?\n3. Try an even larger weight_decay=1.0. Does test_loss keep improving, get worse, or plateau? What does this suggest about there being a 'right amount' of regularization rather than 'more is always better'?",
    problemKn: "ಪಾಠ ನಿಜವಾಗಿ ಕಂಡುಕೊಂಡಿತು: weight_decay=0.0 test_loss=3.3103 ಮತ್ತು weight_norm=13.748 ನೀಡಿತು; weight_decay=0.1 test_loss=3.2081 ಮತ್ತು weight_norm=8.248 ನೀಡಿತು.\n1. ಎಲ್ಲಾ ಮೂರೂ weight_decay ಮೌಲ್ಯಗಳಿಗೆ ಪಾಠದ ನಿಖರ train() function ಚಲಾಯಿಸಿ ಮತ್ತು ವರದಿಯಾದ test losses ಮತ್ತು weight norms ಖಚಿತಪಡಿಸಿ.\n2. weight_decay ಹೆಚ್ಚಾದಂತೆ, weight_norm ಸ್ಥಿರವಾಗಿ ಕಡಿಮೆಯಾಗುತ್ತದೆ ಆದರೆ test_loss ಕೇವಲ ಸಾಧಾರಣವಾಗಿ ಸುಧಾರಿಸುತ್ತದೆ. weight decay ನೇರವಾಗಿ weight_norm ಕುಗ್ಗಿಸುತ್ತದೆ ಆದರೆ test performance ಮೇಲೆ ಏಕೆ ಕೇವಲ ಪರೋಕ್ಷವಾಗಿ ಪರಿಣಾಮ ಬೀರುತ್ತದೆ?\n3. ಇನ್ನೂ ದೊಡ್ಡ weight_decay=1.0 ಪ್ರಯತ್ನಿಸಿ. test_loss ಸುಧಾರಿಸುತ್ತಲೇ ಇರುತ್ತದೆಯೇ, ಕೆಟ್ಟದಾಗುತ್ತದೆಯೇ, ಅಥವಾ ಸ್ಥಿರಗೊಳ್ಳುತ್ತದೆಯೇ?" },
  { phaseId, moduleId: m60, lessonId: l60, order: 3, difficulty: 'beginner',
    title: 'BatchNorm Genuinely Equalizing Wild Scales',
    titleKn: 'BatchNorm ನಿಜವಾಗಿ Wild Scales ಸಮೀಕರಿಸುವುದೂ',
    problem: "The lesson's raw batch had wildly different feature scales (means [1.875, 1250, 0.001875], stds [0.74, 559, 0.00074]). After batchnorm, every feature had normalized mean ~0 and std ~1.\n1. Run the lesson's exact batch and batchnorm() function and confirm the raw stats and the normalized stats (mean ~[-0,0,-0], std ~[1,1,0.99]).\n2. Why would feeding the RAW batch (without batchnorm) directly into a neural network layer be problematic, given how different the three features' scales are?\n3. The normalized std for the third feature came out to 0.990981, not exactly 1.0. Given the eps=1e-8 added inside the sqrt, explain why this tiny deviation from exactly 1.0 happens.",
    problemKn: "ಪಾಠದ raw batch ಬಹಳ ವಿಭಿನ್ನ feature scales ಹೊಂದಿತ್ತು. batchnorm ನಂತರ, ಪ್ರತಿ feature ~0 ya ಸಾಮಾನ್ಯೀಕರಿಸಿದ mean ಮತ್ತು ~1 ya std ಹೊಂದಿತ್ತು.\n1. ಪಾಠದ ನಿಖರ batch ಮತ್ತು batchnorm() function ಚಲಾಯಿಸಿ ಮತ್ತು raw stats ಮತ್ತು normalized stats ಖಚಿತಪಡಿಸಿ.\n2. ಮೂರೂ features ya scales ಎಷ್ಟೂ ವಿಭಿನ್ನವಾಗಿವೆ ಎಂಬುದನ್ನೂ ಗಮನದಲ್ಲಿಟ್ಟು, RAW batch ಅನ್ನೂ (batchnorm ಇಲ್ಲದೆ) ನೇರವಾಗಿ ಒಂದೂ neural network layer ಗೆ ನೀಡುವುದೂ ಏಕೆ ಸಮಸ್ಯಾತ್ಮಕವಾಗಿರುತ್ತದೆ?\n3. ಮೂರನೇ feature ya normalized std 1.0 ಬದಲಿಗೆ 0.990981 ಆಗಿ ಬಂದಿತು. sqrt ಒಳಗೆ ಸೇರಿಸಲಾದ eps=1e-8 ಆಧರಿಸಿ, ಈ ಚಿಕ್ಕ ವಿಚಲನ ಏಕೆ ಸಂಭವಿಸುತ್ತದೆ ಎಂದು ವಿವರಿಸಿ." },

  // ── Module 61: Weight Initialization and Training Stability ──
  { phaseId, moduleId: m61, lessonId: l61, order: 1, difficulty: 'intermediate',
    title: 'The Genuinely Frozen Zero-Init Network',
    titleKn: 'ನಿಜವಾಗಿ Frozen ಆದ Zero-Init Network',
    problem: "The lesson's zero-initialized network genuinely got STUCK: after training, W2 stayed exactly [0,0,0,0] and all 4 predictions collapsed to the same value 0.33616.\n1. Run the lesson's exact zero-init code and confirm W2 stays all zeros and predictions are identical for every input.\n2. Explain the symmetry-breaking problem: if every neuron in a layer starts with identical (zero) weights, why do they compute IDENTICAL gradients during backprop, and why does that keep them identical forever, no matter how many epochs you train?\n3. The lesson's random-init version (std=0.01) broke this symmetry and trained normally. What's the smallest change you could make to the zero-init code (one line) to fix it, without changing the overall architecture?",
    problemKn: "ಪಾಠದ zero-initialized network ನಿಜವಾಗಿ ಸಿಲುಕಿಕೊಂಡಿತು: ತರಬೇತಿಯ ನಂತರ, W2 ನಿಖರವಾಗಿ [0,0,0,0] ಆಗಿಯೇ ಉಳಿಯಿತು ಮತ್ತು ಎಲ್ಲಾ 4 predictions ಒಂದೇ ಮೌಲ್ಯ 0.33616 ಗೆ ಕುಸಿದವು.\n1. ಪಾಠದ ನಿಖರ zero-init code ಚಲಾಯಿಸಿ ಮತ್ತು W2 ಎಲ್ಲಾ ಶೂನ್ಯಗಳಾಗಿ ಉಳಿಯುತ್ತದೆ ಎಂದು ಖಚಿತಪಡಿಸಿ.\n2. symmetry-breaking ಸಮಸ್ಯೆ ವಿವರಿಸಿ: ಒಂದೂ layer ನಲ್ಲಿ ಪ್ರತಿ neuron ಒಂದೇ (ಶೂನ್ಯ) weights ಜೊತೆ ಪ್ರಾರಂಭಿಸಿದರೆ, backprop ಸಮಯದಲ್ಲಿ ಅವು ಏಕೆ IDENTICAL gradients ಲೆಕ್ಕಾಚಾರ ಮಾಡುತ್ತವೆ?\n3. ಪಾಠದ random-init ಆವೃತ್ತಿ (std=0.01) ಈ symmetry ಮುರಿಯಿತು ಮತ್ತು ಸಾಮಾನ್ಯವಾಗಿ ತರಬೇತಿ ಪಡೆಯಿತು. ಒಟ್ಟೂ architecture ಬದಲಾಯಿಸದೆ zero-init code ಸರಿಪಡಿಸಲು ನೀವೂ ಮಾಡಬಹುದಾದ ಅತ್ಯಂತ ಚಿಕ್ಕ ಬದಲಾವಣೆ (ಒಂದೇ ಸಾಲು) ಏನೂ?" },
  { phaseId, moduleId: m61, lessonId: l61, order: 2, difficulty: 'advanced',
    title: 'Genuinely Exploding and Vanishing at Initialization Scale',
    titleKn: 'Initialization Scale ನಲ್ಲಿ ನಿಜವಾಗಿ Exploding ಮತ್ತು Vanishing',
    problem: "The lesson's 15-layer scale experiment genuinely showed: std=1.0 init exploded to 4.29e12 by layer 14; std=0.01 init vanished to 0.0 by layer 9; He init (sqrt(2/fan_in)) stayed stable around 0.6-0.8 throughout.\n1. Run the lesson's exact three-way comparison and confirm these three trajectories.\n2. He initialization scales the std by sqrt(2/fan_in). For a layer with fan_in=100, compute the exact He-init std value used, and explain why a LARGER fan_in leads to a SMALLER initialization std.\n3. If you had a 30-layer network instead of 15, would you expect std=1.0 init to explode even more severely, less severely, or about the same by the final layer? Test it and report the actual numbers.",
    problemKn: "ಪಾಠದ 15-layer scale experiment ನಿಜವಾಗಿ ತೋರಿಸಿತು: std=1.0 init layer 14 ರಷ್ಟರಲ್ಲಿ 4.29e12 ಗೆ ಸ್ಫೋಟಿಸಿತು; std=0.01 init layer 9 ರಷ್ಟರಲ್ಲಿ 0.0 ಗೆ ಮಾಯವಾಯಿತು; He init ಸ್ಥಿರವಾಗಿ ಉಳಿಯಿತು.\n1. ಪಾಠದ ನಿಖರ ಮೂರು-ಮಾರ್ಗ ಹೋಲಿಕೆ ಚಲಾಯಿಸಿ ಮತ್ತು ಈ ಮೂರೂ ಪಥಗಳನ್ನೂ ಖಚಿತಪಡಿಸಿ.\n2. He initialization std ಅನ್ನೂ sqrt(2/fan_in) ಇಂದ scale ಮಾಡುತ್ತದೆ. fan_in=100 ಇರುವ ಒಂದೂ layer ಗೆ, ಬಳಸಿದ ನಿಖರ He-init std ಮೌಲ್ಯ ಲೆಕ್ಕಾಚಾರ ಮಾಡಿ, ಮತ್ತು ದೊಡ್ಡ fan_in ಚಿಕ್ಕ initialization std ಗೆ ಏಕೆ ಕಾರಣವಾಗುತ್ತದೆ ಎಂದು ವಿವರಿಸಿ.\n3. 15 ಬದಲಿಗೆ 30-layer network ಇದ್ದರೆ, std=1.0 init ಇನ್ನೂ ಹೆಚ್ಚು ತೀವ್ರವಾಗಿ ಸ್ಫೋಟಿಸುತ್ತದೆ ಎಂದು ನೀವೂ ನಿರೀಕ್ಷಿಸುತ್ತೀರಾ? ಪರೀಕ್ಷಿಸಿ ಮತ್ತು ನಿಜ ಸಂಖ್ಯೆಗಳನ್ನೂ ವರದಿ ಮಾಡಿ." },
  { phaseId, moduleId: m61, lessonId: l61, order: 3, difficulty: 'intermediate',
    title: 'Random Init Genuinely Breaking Symmetry',
    titleKn: 'Random Init ನಿಜವಾಗಿ Symmetry ಮುರಿಯುವುದೂ',
    problem: "The lesson's random-init (std=0.01) network trained for 2000 epochs and produced a W1 matrix where different columns had genuinely different values (unlike the frozen all-zero case).\n1. Run the lesson's exact random-init training code and print the final W1 matrix. Confirm the 4 columns are NOT identical to each other.\n2. Even though the initial std is tiny (0.01), the network still successfully broke symmetry and trained. Why does even a tiny amount of randomness suffice to break symmetry, when EXACT zero does not?\n3. Compute the standard deviation of the values within just the first column of the final trained W1. Is it larger or smaller than the initial 0.01 std the weights started with? What does that tell you about how much the weights moved during training?",
    problemKn: "ಪಾಠದ random-init (std=0.01) network 2000 epochs ತರಬೇತಿ ಪಡೆದು ಒಂದೂ W1 matrix ಉತ್ಪಾದಿಸಿತು, ಅಲ್ಲಿ ವಿಭಿನ್ನ columns ನಿಜವಾಗಿ ವಿಭಿನ್ನ ಮೌಲ್ಯಗಳನ್ನೂ ಹೊಂದಿದ್ದವು.\n1. ಪಾಠದ ನಿಖರ random-init training code ಚಲಾಯಿಸಿ ಮತ್ತು ಅಂತಿಮ W1 matrix ಪ್ರಿಂಟ್ ಮಾಡಿ. 4 columns ಪರಸ್ಪರ IDENTICAL ಅಲ್ಲ ಎಂದು ಖಚಿತಪಡಿಸಿ.\n2. ಆರಂಭಿಕ std ಚಿಕ್ಕದಾಗಿದ್ದರೂ (0.01), network ಇನ್ನೂ ಯಶಸ್ವಿಯಾಗಿ symmetry ಮುರಿಯಿತು ಮತ್ತು ತರಬೇತಿ ಪಡೆಯಿತು. NIKKAKA ಶೂನ್ಯ ಮಾಡದಿರುವಾಗ ಒಂದೂ ಚಿಕ್ಕ ಪ್ರಮಾಣದ ಯಾದೃಚ್ಛಿಕತೆ ಏಕೆ symmetry ಮುರಿಯಲು ಸಾಕಾಗುತ್ತದೆ?\n3. ಅಂತಿಮ ತರಬೇತಿ ಪಡೆದ W1 ya ಮೊದಲ column ಒಳಗಿನ ಮೌಲ್ಯಗಳ standard deviation ಲೆಕ್ಕಾಚಾರ ಮಾಡಿ. ಇದೂ weights ಪ್ರಾರಂಭವಾದ ಆರಂಭಿಕ 0.01 std ಗಿಂತ ದೊಡ್ಡದಾಗಿದೆಯೇ ಅಥವಾ ಚಿಕ್ಕದಾಗಿದೆಯೇ?" },

  // ── Module 62: Learning Rate Schedules and Warmup ──
  { phaseId, moduleId: m62, lessonId: l62, order: 1, difficulty: 'beginner',
    title: 'Comparing Three Schedules at Genuine Checkpoints',
    titleKn: 'ನಿಜ Checkpoints ನಲ್ಲಿ ಮೂರೂ Schedules ಹೋಲಿಸುವುದೂ',
    problem: "The lesson computed step_decay, cosine_annealing, and warmup_then_cosine across 30 epochs, genuinely showing at epoch 0: step_decay=0.1, cosine=0.1, warmup+cosine=0.02 (much lower, because warmup starts low).\n1. Run the lesson's exact three schedule functions and print all three at epochs 0, 5, 10, 15, 20, and 29. Confirm your numbers match the lesson's genuine output.\n2. At epoch 5, warmup_then_cosine reaches exactly 0.1 (the peak), matching where warmup_epochs=5 ends. Explain why the lesson designed warmup to ramp up LINEARLY from a low value to the target lr over exactly warmup_epochs steps.\n3. step_decay only changes in sudden jumps (at epochs 10, 20, etc.) while cosine changes smoothly every epoch. Name one practical downside of the sudden-jump behavior of step_decay compared to a smooth schedule.",
    problemKn: "ಪಾಠ 30 epochs ಆದ್ಯಂತ step_decay, cosine_annealing, ಮತ್ತು warmup_then_cosine ಲೆಕ್ಕಾಚಾರ ಮಾಡಿತು.\n1. ಪಾಠದ ನಿಖರ ಮೂರೂ schedule functions ಚಲಾಯಿಸಿ ಮತ್ತು epochs 0, 5, 10, 15, 20, ಮತ್ತು 29 ನಲ್ಲಿ ಎಲ್ಲಾ ಮೂರನ್ನೂ ಪ್ರಿಂಟ್ ಮಾಡಿ.\n2. epoch 5 ನಲ್ಲಿ, warmup_then_cosine ನಿಖರವಾಗಿ 0.1 (peak) ತಲುಪುತ್ತದೆ, warmup_epochs=5 ಮುಗಿಯುವ ಸ್ಥಳಕ್ಕೆ ಹೊಂದಿಕೊಳ್ಳುತ್ತದೆ. warmup ಅನ್ನೂ ಪಾಠ ಏಕೆ ಒಂದೂ ಕಡಿಮೆ ಮೌಲ್ಯ ಇಂದ ರೇಖೀಯವಾಗಿ target lr ಗೆ ramp ಮಾಡುವಂತೆ ವಿನ್ಯಾಸಗೊಳಿಸಿತು ಎಂದು ವಿವರಿಸಿ.\n3. step_decay ಕೇವಲ ಹಠಾತ್ ಜಿಗಿತಗಳಲ್ಲಿ ಬದಲಾಗುತ್ತದೆ ಆದರೆ cosine ಪ್ರತಿ epoch ಸುಗಮವಾಗಿ ಬದಲಾಗುತ್ತದೆ. smooth schedule ಗೆ ಹೋಲಿಸಿದರೆ step_decay ya ಹಠಾತ್-ಜಿಗಿತ ವರ್ತನೆ ya ಒಂದೂ ಪ್ರಾಯೋಗಿಕ ಅನನುಕೂಲ ಹೆಸರಿಸಿ." },
  { phaseId, moduleId: m62, lessonId: l62, order: 2, difficulty: 'advanced',
    title: 'Genuinely Reproducing the Blowup Without Warmup',
    titleKn: 'Warmup ಇಲ್ಲದೆ Blowup ಅನ್ನೂ ನಿಜವಾಗಿ ಮರುಉತ್ಪಾದಿಸುವುದೂ',
    problem: "The lesson genuinely found that using a high lr=0.11 with NO warmup caused the ravine optimization to blow up to loss=14086878.5883 after 30 steps. Adding warmup for 5 epochs (ramping to the SAME target lr=0.11) instead reached a stable loss of 875.05, and warmup plus cosine decay reached loss=0.0112.\n1. Run all three of the lesson's exact experiments (no warmup, warmup only, warmup+decay) and confirm these three final losses.\n2. Why does starting immediately at lr=0.11 cause catastrophic divergence, while ramping UP to that same lr=0.11 over 5 epochs does not?\n3. Warmup alone (875.05) is much better than no warmup (14 million) but still far worse than warmup+decay (0.0112). What extra benefit does adding decay AFTER warmup provide that warmup alone doesn't?",
    problemKn: "ಪಾಠ ನಿಜವಾಗಿ ಕಂಡುಕೊಂಡಿತು: high lr=0.11 ಅನ್ನೂ warmup ಇಲ್ಲದೆ ಬಳಸಿದಾಗ ravine optimization 30 steps ನಂತರ loss=14086878.59 ಗೆ ಸ್ಫೋಟಿಸಿತು. 5 epochs warmup ಸೇರಿಸಿದಾಗ ಬದಲಿಗೆ loss=875.05 ಗೆ ಸ್ಥಿರವಾಯಿತು, ಮತ್ತು warmup+decay loss=0.0112 ತಲುಪಿತು.\n1. ಪಾಠದ ಎಲ್ಲಾ ಮೂರೂ ನಿಖರ ಪ್ರಯೋಗಗಳನ್ನೂ ಚಲಾಯಿಸಿ ಮತ್ತು ಈ ಮೂರೂ ಅಂತಿಮ losses ಖಚಿತಪಡಿಸಿ.\n2. lr=0.11 ನಲ್ಲಿ ತಕ್ಷಣ ಪ್ರಾರಂಭಿಸುವುದೂ ಘೋರ divergence ಗೆ ಏಕೆ ಕಾರಣವಾಗುತ್ತದೆ, ಆದರೆ 5 epochs ಆದ್ಯಂತ ಅದೇ lr=0.11 ಗೆ ramp ಮಾಡುವುದೂ ಆಗುವುದಿಲ್ಲ?\n3. ಕೇವಲ warmup (875.05) ಇಲ್ಲದಿರುವುದಕ್ಕಿಂತ (14 ಮಿಲಿಯನ್) ಬಹಳ ಉತ್ತಮ ಆದರೆ warmup+decay (0.0112) ಗಿಂತ ಇನ್ನೂ ಬಹಳ ಕೆಟ್ಟದಾಗಿದೆ. warmup ನಂತರ decay ಸೇರಿಸುವುದೂ ಯಾವ ಹೆಚ್ಚುವರಿ ಪ್ರಯೋಜನ ನೀಡುತ್ತದೆ?" },
  { phaseId, moduleId: m62, lessonId: l62, order: 3, difficulty: 'beginner',
    title: 'Designing Your Own Schedule',
    titleKn: 'ನಿಮ್ಮ ಸ್ವಂತ Schedule ವಿನ್ಯಾಸಗೊಳಿಸುವುದೂ',
    problem: "1. Write a new schedule function linear_decay(epoch, initial_lr=0.1, total_epochs=30) that decreases linearly from initial_lr at epoch 0 to 0 at the final epoch.\n2. Plot (or print at epochs 0, 10, 20, 29) your linear_decay alongside the lesson's step_decay and cosine_annealing. How does its shape compare to cosine's?\n3. Run the lesson's warmup_cosine_lr ravine experiment, but swap in your linear_decay for the post-warmup portion instead of cosine. Does it still reach a low final loss, or does it behave differently near the end of training?",
    problemKn: "1. epoch 0 ನಲ್ಲಿ initial_lr ಇಂದ ಅಂತಿಮ epoch ನಲ್ಲಿ 0 ಗೆ ರೇಖೀಯವಾಗಿ ಕಡಿಮೆಯಾಗುವ ಒಂದೂ ಹೊಸ schedule function linear_decay(epoch, initial_lr=0.1, total_epochs=30) ಬರೆಯಿರಿ.\n2. ಪಾಠದ step_decay ಮತ್ತು cosine_annealing ಜೊತೆಗೆ ನಿಮ್ಮ linear_decay ಪ್ಲಾಟ್ ಮಾಡಿ (ಅಥವಾ epochs 0, 10, 20, 29 ನಲ್ಲಿ ಪ್ರಿಂಟ್ ಮಾಡಿ). ಇದರ ಆಕಾರ cosine ಗೆ ಹೇಗೂ ಹೋಲಿಸುತ್ತದೆ?\n3. ಪಾಠದ warmup_cosine_lr ravine experiment ಚಲಾಯಿಸಿ, ಆದರೆ post-warmup ಭಾಗಕ್ಕೆ cosine ಬದಲಿಗೆ ನಿಮ್ಮ linear_decay ಬದಲಾಯಿಸಿ. ಇದೂ ಇನ್ನೂ ಕಡಿಮೆ ಅಂತಿಮ loss ತಲುಪುತ್ತದೆಯೇ?" },

  // ── Module 63: Exercise — Mini Framework and Two Moons ──
  { phaseId, moduleId: m63, lessonId: l63, order: 1, difficulty: 'intermediate',
    title: 'Generating and Verifying the Two Moons Dataset',
    titleKn: 'Two Moons Dataset ಉತ್ಪಾದಿಸುವುದೂ ಮತ್ತು ಪರಿಶೀಲಿಸುವುದೂ',
    problem: "The lesson's make_moons(200) genuinely produced train shape (160,2), test shape (40,2), and class balance 0.49375 (close to 50/50).\n1. Run the lesson's exact make_moons function and confirm these shapes and the class balance.\n2. Why is XOR-like data considered 'easier' than two-moons data for a neural network, even though both are non-linearly-separable? (Hint: think about how many straight-line segments are needed to separate the classes.)\n3. Increase noise from 0.15 to 0.4 in make_moons. Does the class balance stay close to 50/50, and does the dataset visually (or by printing a few points from each class) look harder to separate?",
    problemKn: "ಪಾಠದ make_moons(200) ನಿಜವಾಗಿ train shape (160,2), test shape (40,2), ಮತ್ತು class balance 0.49375 ಉತ್ಪಾದಿಸಿತು.\n1. ಪಾಠದ ನಿಖರ make_moons function ಚಲಾಯಿಸಿ ಮತ್ತು ಈ shapes ಮತ್ತು class balance ಖಚಿತಪಡಿಸಿ.\n2. ಎರಡೂ non-linearly-separable ಆಗಿದ್ದರೂ, XOR-like data two-moons data ಗಿಂತ ಏಕೆ 'ಸುಲಭ' ಎಂದು ಪರಿಗಣಿಸಲಾಗುತ್ತದೆ?\n3. make_moons ನಲ್ಲಿ noise ಅನ್ನೂ 0.15 ಇಂದ 0.4 ಗೆ ಹೆಚ್ಚಿಸಿ. class balance 50/50 ಗೆ ಹತ್ತಿರ ಉಳಿಯುತ್ತದೆಯೇ?" },
  { phaseId, moduleId: m63, lessonId: l63, order: 2, difficulty: 'advanced',
    title: 'Assembling and Training the Complete Mini Framework',
    titleKn: 'ಪೂರ್ಣ Mini Framework ಜೋಡಿಸುವುದೂ ಮತ್ತು ತರಬೇತಿ ನೀಡುವುದೂ',
    problem: "The lesson's assembled framework (Dense layers + Adam optimizer) trained on two-moons for 500 epochs, genuinely reaching train_acc=1.0 by epoch 100 and a final held-out test accuracy of 0.975.\n1. Run the lesson's complete framework end to end and confirm you reach the same train_acc=1.0 and test accuracy close to 0.975.\n2. The lesson's Dense layer uses He initialization (std=sqrt(2/n_in)), which you studied in Module 61. Try replacing it with zero initialization instead and rerun training. Does the network still learn, given what you know about symmetry breaking?\n3. What's the gap between train_acc (1.0) and test_acc (0.975)? Is this gap large enough to be concerning for overfitting, or is it within a normal range for a small held-out test set of 40 examples?",
    problemKn: "ಪಾಠದ ಜೋಡಿಸಿದ framework (Dense layers + Adam optimizer) two-moons ಮೇಲೆ 500 epochs ತರಬೇತಿ ಪಡೆದು, epoch 100 ರಷ್ಟರಲ್ಲಿ train_acc=1.0 ಮತ್ತು ಅಂತಿಮ test accuracy 0.975 ತಲುಪಿತು.\n1. ಪಾಠದ ಪೂರ್ಣ framework ಎಂಡ್ ಟು ಎಂಡ್ ಚಲಾಯಿಸಿ ಮತ್ತು ಅದೇ ಫಲಿತಾಂಶಗಳನ್ನೂ ಖಚಿತಪಡಿಸಿ.\n2. ಪಾಠದ Dense layer He initialization ಬಳಸುತ್ತದೆ. ಇದನ್ನೂ zero initialization ಜೊತೆ ಬದಲಾಯಿಸಿ ಮತ್ತು ಮರುತರಬೇತಿ ನೀಡಿ. symmetry breaking ಬಗ್ಗೆ ನಿಮಗೆ ತಿಳಿದಿರುವುದನ್ನೂ ಗಮನದಲ್ಲಿಟ್ಟು, network ಇನ್ನೂ ಕಲಿಯುತ್ತದೆಯೇ?\n3. train_acc (1.0) ಮತ್ತು test_acc (0.975) ನಡುವಿನ ಅಂತರ ಏನೂ? ಇದೂ overfitting ಗೆ ಕಳವಳಕಾರಿಯಷ್ಟು ದೊಡ್ಡದಾಗಿದೆಯೇ?" },
  { phaseId, moduleId: m63, lessonId: l63, order: 3, difficulty: 'intermediate',
    title: 'Testing on Truly Held-Out Data',
    titleKn: 'ನಿಜವಾಗಿ Held-Out Data ಮೇಲೆ ಪರೀಕ್ಷಿಸುವುದೂ',
    problem: "1. Explain in your own words why the lesson computes accuracy separately on X_train and X_test, rather than just reporting the training accuracy.\n2. If you deliberately trained the network for 5000 epochs instead of 500 (much longer), would you expect train_acc to change, test_acc to change, or both? Run it and report what actually happens to the gap between them.\n3. Modify the split ratio in make_moons's train/test split so that only 10% of data is held out for testing (18 examples) instead of 20% (40 examples). Does test accuracy become more or less reliable as an estimate of true generalization with fewer test examples?",
    problemKn: "1. ಪಾಠ ಕೇವಲ training accuracy ವರದಿ ಮಾಡುವ ಬದಲಿಗೆ X_train ಮತ್ತು X_test ಮೇಲೆ ಪ್ರತ್ಯೇಕವಾಗಿ accuracy ಲೆಕ್ಕಾಚಾರ ಮಾಡುವುದೂ ಏಕೆ ಎಂದು ನಿಮ್ಮ ಸ್ವಂತ ಪದಗಳಲ್ಲಿ ವಿವರಿಸಿ.\n2. network ಅನ್ನೂ 500 ಬದಲಿಗೆ ಉದ್ದೇಶಪೂರ್ವಕವಾಗಿ 5000 epochs ತರಬೇತಿ ನೀಡಿದರೆ, train_acc ಬದಲಾಗುತ್ತದೆ ಎಂದು ನೀವೂ ನಿರೀಕ್ಷಿಸುತ್ತೀರಾ, test_acc ಬದಲಾಗುತ್ತದೆಯೇ, ಅಥವಾ ಎರಡೂ? ಚಲಾಯಿಸಿ ಮತ್ತು ಅಂತರಕ್ಕೆ ನಿಜವಾಗಿ ಏನಾಗುತ್ತದೆ ಎಂದು ವರದಿ ಮಾಡಿ.\n3. make_moons ya train/test split ratio ಅನ್ನೂ ಮಾರ್ಪಡಿಸಿ ಇದರಿಂದ ಕೇವಲ 10% data ಪರೀಕ್ಷೆಗೆ (18 examples) ಇರುತ್ತದೆ. ಕಡಿಮೆ test examples ಜೊತೆ test accuracy ಹೆಚ್ಚು ವಿಶ್ವಾಸಾರ್ಹವಾಗುತ್ತದೆಯೇ ಅಥವಾ ಕಡಿಮೆಯೇ?" },

  // ── Module 64: Introduction to PyTorch ──
  { phaseId, moduleId: m64, lessonId: l64, order: 1, difficulty: 'intermediate',
    title: 'Autograd Genuinely Matches Manual NumPy',
    titleKn: 'Autograd ನಿಜವಾಗಿ Manual NumPy ಗೆ ಹೊಂದಿಕೊಳ್ಳುತ್ತದೆ',
    problem: "The lesson computed the same gradient two ways: PyTorch's loss.backward() gave W.grad = [[-0.0660,0.0676],[0.0396,-0.0405],[-0.1056,0.1081]], and manual NumPy backprop gave [[-0.066,0.0676],[0.0396,-0.0405],[-0.1056,0.1081]] -- essentially identical.\n1. Run both the lesson's exact PyTorch autograd code and its manual NumPy code. Confirm the two gradient matrices match to at least 3 decimal places.\n2. What does requires_grad=True on the tensor W tell PyTorch to do internally that requires_grad=False (used for x) does not?\n3. If you called loss.backward() a SECOND time without first calling opt.zero_grad() or W.grad.zero_(), what would happen to W.grad -- would it overwrite the previous gradient, or accumulate on top of it? Test this and report what you observe.",
    problemKn: "ಪಾಠ ಒಂದೇ gradient ಅನ್ನೂ ಎರಡೂ ವಿಧಾನಗಳಲ್ಲಿ ಲೆಕ್ಕಾಚಾರ ಮಾಡಿತು: PyTorch ya loss.backward() ಮತ್ತು manual NumPy backprop -- ಬಹುತೇಕ identical.\n1. ಪಾಠದ ನಿಖರ PyTorch autograd code ಮತ್ತು ಅದರ manual NumPy code ಎರಡನ್ನೂ ಚಲಾಯಿಸಿ. ಎರಡೂ gradient matrices ಕನಿಷ್ಠ 3 ದಶಮಾಂಶ ಸ್ಥಳಗಳಿಗೆ ಹೊಂದಿಕೊಳ್ಳುತ್ತವೆ ಎಂದು ಖಚಿತಪಡಿಸಿ.\n2. tensor W ಮೇಲೆ requires_grad=True PyTorch ಗೆ ಆಂತರಿಕವಾಗಿ ಏನೂ ಮಾಡಲು ಹೇಳುತ್ತದೆ, requires_grad=False ಮಾಡುವುದಿಲ್ಲ?\n3. opt.zero_grad() ಕರೆ ಮಾಡದೆ loss.backward() ಅನ್ನೂ ಎರಡನೇ ಬಾರಿ ಕರೆ ಮಾಡಿದರೆ, W.grad ಗೆ ಏನಾಗುತ್ತದೆ -- ಇದೂ ಹಿಂದಿನ gradient ಅನ್ನೂ overwrite ಮಾಡುತ್ತದೆಯೇ, ಅಥವಾ ಅದರ ಮೇಲೆ ಸಂಗ್ರಹಗೊಳ್ಳುತ್ತದೆಯೇ? ಪರೀಕ್ಷಿಸಿ." },
  { phaseId, moduleId: m64, lessonId: l64, order: 2, difficulty: 'intermediate',
    title: 'Re-Solving Two Moons in PyTorch',
    titleKn: 'Two Moons ಅನ್ನೂ PyTorch ನಲ್ಲಿ ಮರುಪರಿಹರಿಸುವುದೂ',
    problem: "The lesson's PyTorch nn.Sequential model, trained with Adam and BCELoss for 500 epochs, genuinely reached train_acc=1.0 by epoch 100 and final test accuracy 0.9750000238418579 -- matching the mini framework's 0.975 from Module 63.\n1. Run the lesson's exact PyTorch model and training loop. Confirm your test accuracy is close to 0.975.\n2. Why is the final test accuracy printed as 0.9750000238418579 rather than a clean 0.975? What does this tell you about float32 precision in PyTorch tensors compared to Python's native floats?\n3. Compare the amount of code needed for the PyTorch version (using nn.Sequential, nn.Linear, torch.optim.Adam) versus the from-scratch mini framework in Module 63. List two things PyTorch handles automatically that Module 63's framework had to implement by hand.",
    problemKn: "ಪಾಠದ PyTorch nn.Sequential model, Adam ಮತ್ತು BCELoss ಜೊತೆ 500 epochs ತರಬೇತಿ ಪಡೆದು, ಅಂತಿಮ test accuracy 0.975 ತಲುಪಿತು -- Module 63 ya mini framework ya 0.975 ಗೆ ಹೊಂದಿಕೊಳ್ಳುತ್ತದೆ.\n1. ಪಾಠದ ನಿಖರ PyTorch model ಮತ್ತು training loop ಚಲಾಯಿಸಿ. ನಿಮ್ಮ test accuracy 0.975 ಗೆ ಹತ್ತಿರವಾಗಿದೆ ಎಂದು ಖಚಿತಪಡಿಸಿ.\n2. ಅಂತಿಮ test accuracy ಶುಭ್ರ 0.975 ಬದಲಿಗೆ 0.9750000238418579 ಆಗಿ ಏಕೆ ಮುದ್ರಿತವಾಗಿದೆ?\n3. PyTorch version ಗೆ ಬೇಕಾದ code ya ಪ್ರಮಾಣವನ್ನೂ Module 63 ya from-scratch mini framework ಜೊತೆ ಹೋಲಿಸಿ. Module 63 ya framework ಕೈಯಾರೆ ಜಾರಿಗೊಳಿಸಬೇಕಾದ ಎರಡೂ ವಿಷಯಗಳನ್ನೂ PyTorch ಸ್ವಯಂಚಾಲಿತವಾಗಿ ನಿರ್ವಹಿಸುತ್ತದೆ ಎಂದು ಪಟ್ಟಿ ಮಾಡಿ." },
  { phaseId, moduleId: m64, lessonId: l64, order: 3, difficulty: 'beginner',
    title: 'The with torch.no_grad() Block',
    titleKn: 'with torch.no_grad() Block',
    problem: "1. The lesson wraps its test-time prediction in a with torch.no_grad(): block. Run the test evaluation both WITH and WITHOUT this block and confirm the predicted values and accuracy are identical either way.\n2. What is torch.no_grad() actually disabling, and why does it not affect the numerical RESULT of the forward pass?\n3. Explain why skipping torch.no_grad() during evaluation (leaving gradient tracking on) is wasteful even though it doesn't change the answer -- think about what PyTorch is doing internally during every tensor operation when gradient tracking is active.",
    problemKn: "1. ಪಾಠ ಅದರ test-time prediction ಅನ್ನೂ with torch.no_grad(): block ನಲ್ಲಿ ಸುತ್ತುತ್ತದೆ. test evaluation ಅನ್ನೂ ಈ block ಜೊತೆ ಮತ್ತು ಇಲ್ಲದೆ ಎರಡೂ ಚಲಾಯಿಸಿ ಮತ್ತು predicted ಮೌಲ್ಯಗಳು ಮತ್ತು accuracy ಎರಡೂ ರೀತಿಯಲ್ಲಿಯೂ identical ಎಂದು ಖಚಿತಪಡಿಸಿ.\n2. torch.no_grad() ನಿಜವಾಗಿ ಏನೂ ನಿಷ್ಕ್ರಿಯಗೊಳಿಸುತ್ತದೆ, ಮತ್ತು ಇದೂ forward pass ya ಸಂಖ್ಯಾತ್ಮಕ RESULT ಮೇಲೆ ಏಕೆ ಪರಿಣಾಮ ಬೀರುವುದಿಲ್ಲ?\n3. ಉತ್ತರ ಬದಲಾಗದಿದ್ದರೂ, evaluation ಸಮಯದಲ್ಲಿ torch.no_grad() ಬಿಟ್ಟುಬಿಡುವುದೂ ಏಕೆ ವ್ಯರ್ಥ ಎಂದು ವಿವರಿಸಿ." },

  // ── Module 65: Introduction to JAX ──
  { phaseId, moduleId: m65, lessonId: l65, order: 1, difficulty: 'intermediate',
    title: "JAX's grad() Genuinely Matches PyTorch and NumPy",
    titleKn: "JAX ya grad() ನಿಜವಾಗಿ PyTorch ಮತ್ತು NumPy ಗೆ ಹೊಂದಿಕೊಳ್ಳುತ್ತದೆ",
    problem: "The lesson's JAX grad(loss_fn) on the same W, x, y from Module 64's PyTorch example genuinely produced dW=[[-0.0660076,0.06756114],[0.03960456,-0.04053669],[-0.10561216,0.10809783]] -- matching the PyTorch and NumPy results from that lesson.\n1. Run the lesson's exact JAX grad() code and confirm this dW matrix, then compare it directly to Module 64's PyTorch gradient. Do they agree to at least 3 decimal places?\n2. JAX's loss_fn is a plain Python function (no classes, no .backward() calls) that takes W as its first argument. How does grad(loss_fn) know which argument to differentiate with respect to?\n3. What does this cross-framework agreement (NumPy manual, PyTorch autograd, JAX grad all giving the same numbers) tell you about whether backpropagation math is framework-specific or a universal, well-defined calculation?",
    problemKn: "Module 64 ya PyTorch example ya ಅದೇ W, x, y ಮೇಲೆ ಪಾಠದ JAX grad(loss_fn) ನಿಜವಾಗಿ ಅದೇ dW matrix ಉತ್ಪಾದಿಸಿತು -- PyTorch ಮತ್ತು NumPy ಫಲಿತಾಂಶಗಳಿಗೆ ಹೊಂದಿಕೊಳ್ಳುತ್ತದೆ.\n1. ಪಾಠದ ನಿಖರ JAX grad() code ಚಲಾಯಿಸಿ ಮತ್ತು ಈ dW matrix ಖಚಿತಪಡಿಸಿ, ನಂತರ ಇದನ್ನೂ Module 64 ya PyTorch gradient ಜೊತೆ ನೇರವಾಗಿ ಹೋಲಿಸಿ.\n2. JAX ya loss_fn ಒಂದೂ ಸರಳ Python function (classes ಇಲ್ಲ, .backward() ಕರೆಗಳಿಲ್ಲ). grad(loss_fn) ಯಾವ argument ಸಂಬಂಧಿಸಿ ಬೇರ್ಪಡಿಸಬೇಕು ಎಂದು ಹೇಗೂ ತಿಳಿಯುತ್ತದೆ?\n3. ಈ cross-framework ಒಪ್ಪಿಗೆ backpropagation ಗಣಿತ framework-specific ಅಥವಾ ಒಂದೂ ಸಾರ್ವತ್ರಿಕ, ಸುವ್ಯಾಖ್ಯಾನಿತ ಲೆಕ್ಕಾಚಾರ ಎಂಬುದರ ಬಗ್ಗೆ ಏನೂ ಹೇಳುತ್ತದೆ?" },
  { phaseId, moduleId: m65, lessonId: l65, order: 2, difficulty: 'advanced',
    title: 'Genuinely Measuring the 262x jit() Speedup',
    titleKn: '262x jit() Speedup ಅನ್ನೂ ನಿಜವಾಗಿ ಅಳೆಯುವುದೂ',
    problem: "The lesson genuinely measured: plain grad() took 9.3531s for 2000 calls, while jit(grad()) took only 0.0357s for the same 2000 calls -- a 261.91x speedup.\n1. Run the lesson's exact timing code (including the warmup call that excludes compile time) and report your own measured speedup. Is it in the same ballpark as 260x, even if the exact number differs by hardware?\n2. Why does the lesson explicitly call jit_grad_fn(W,x,y).block_until_ready() ONCE before starting the timed loop, rather than including that first call in the timed measurement?\n3. jit() compiles the function once and reuses the compiled version. If you called jit_grad_fn with an input of a DIFFERENT shape than the one used to warm it up, would you expect a fast call (reusing the compiled version) or a slow one (triggering a new compilation)? Explain your reasoning based on how JIT compilation works.",
    problemKn: "ಪಾಠ ನಿಜವಾಗಿ ಅಳೆಯಿತು: plain grad() 2000 calls ಗೆ 9.3531s ತೆಗೆದುಕೊಂಡಿತು, jit(grad()) ಅದೇ 2000 calls ಗೆ ಕೇವಲ 0.0357s ತೆಗೆದುಕೊಂಡಿತು -- 261.91x speedup.\n1. ಪಾಠದ ನಿಖರ timing code ಚಲಾಯಿಸಿ ಮತ್ತು ನಿಮ್ಮ ಸ್ವಂತ ಅಳೆದ speedup ವರದಿ ಮಾಡಿ.\n2. timed loop ಪ್ರಾರಂಭಿಸುವ ಮೊದಲು ಪಾಠ ಏಕೆ ಸ್ಪಷ್ಟವಾಗಿ jit_grad_fn(...).block_until_ready() ಅನ್ನೂ ಒಮ್ಮೆ ಕರೆ ಮಾಡುತ್ತದೆ?\n3. jit() function ಅನ್ನೂ ಒಮ್ಮೆ compile ಮಾಡುತ್ತದೆ ಮತ್ತು compiled ಆವೃತ್ತಿ ಮರುಬಳಕೆ ಮಾಡುತ್ತದೆ. ಬೇರೆ shape ya input ಜೊತೆ jit_grad_fn ಕರೆ ಮಾಡಿದರೆ, ಇದೂ ವೇಗವಾದ ಕರೆ ಆಗಿರುತ್ತದೆಯೇ ಅಥವಾ ನಿಧಾನವಾದದ್ದೇ?" },
  { phaseId, moduleId: m65, lessonId: l65, order: 3, difficulty: 'intermediate',
    title: 'vmap() Genuinely Matching a Manual Loop',
    titleKn: 'vmap() ನಿಜವಾಗಿ ಒಂದೂ Manual Loop ಗೆ ಹೊಂದಿಕೊಳ್ಳುತ್ತದೆ',
    problem: "The lesson's vmap(predict_one, in_axes=(None,0)) batched over 3 examples and produced predictions IDENTICAL to a manual Python loop calling predict_one 3 times (the lesson confirmed 'are they identical? True').\n1. Run the lesson's exact vmap and manual-loop code and confirm the outputs match exactly.\n2. What does in_axes=(None, 0) tell vmap about how to treat each of predict_one's two arguments (W and x)?\n3. Add a 4th and 5th example to batch_x and rerun both the vmap version and an extended manual loop. Do they still match? What's the main practical advantage of vmap over writing the manual loop yourself, beyond just correctness?",
    problemKn: "ಪಾಠದ vmap(predict_one, in_axes=(None,0)) 3 examples ಮೇಲೆ batch ಮಾಡಿ manual Python loop ಗೆ IDENTICAL predictions ಉತ್ಪಾದಿಸಿತು.\n1. ಪಾಠದ ನಿಖರ vmap ಮತ್ತು manual-loop code ಚಲಾಯಿಸಿ ಮತ್ತು outputs ನಿಖರವಾಗಿ ಹೊಂದಿಕೊಳ್ಳುತ್ತವೆ ಎಂದು ಖಚಿತಪಡಿಸಿ.\n2. in_axes=(None, 0) vmap ಗೆ predict_one ya ಎರಡೂ arguments (W ಮತ್ತು x) ಅನ್ನೂ ಹೇಗೂ ಪರಿಗಣಿಸಬೇಕು ಎಂದು ಹೇಳುತ್ತದೆ?\n3. batch_x ಗೆ 4ನೇ ಮತ್ತು 5ನೇ example ಸೇರಿಸಿ ಮರುಚಲಾಯಿಸಿ. ಇವು ಇನ್ನೂ ಹೊಂದಿಕೊಳ್ಳುತ್ತವೆಯೇ? correctness ಮೀರಿ manual loop ಬರೆಯುವುದಕ್ಕಿಂತ vmap ya ಮುಖ್ಯ ಪ್ರಾಯೋಗಿಕ ಅನುಕೂಲ ಏನೂ?" },

  // ── Module 66: Debugging Neural Networks ──
  { phaseId, moduleId: m66, lessonId: l66, order: 1, difficulty: 'advanced',
    title: 'Genuinely Reproducing Vanishing Gradients Layer by Layer',
    titleKn: 'Vanishing Gradients ಅನ್ನೂ Layer by Layer ನಿಜವಾಗಿ ಮರುಉತ್ಪಾದಿಸುವುದೂ',
    problem: "The lesson's 10-layer sigmoid network genuinely measured gradient norms from layer 0 (0.00000006) to layer 10 (0.14788908) -- a difference of over 6 orders of magnitude across the network's depth.\n1. Run the lesson's exact 10-layer diagnostic code and confirm you see this same pattern of gradient norms shrinking toward the input layer.\n2. Compute the ratio between layer 10's gradient norm and layer 0's gradient norm. Does this match roughly what you'd expect from stacking sigmoid derivatives (each capped at 0.25) across 10 layers?\n3. This diagnostic prints a gradient norm PER LAYER, not just a single final number. Explain why printing per-layer norms is a more useful debugging tool than just checking whether training loss goes down.",
    problemKn: "ಪಾಠದ 10-layer sigmoid network ನಿಜವಾಗಿ layer 0 (0.00000006) ಇಂದ layer 10 (0.14788908) ವರೆಗೆ gradient norms ಅಳೆಯಿತು -- 6 ಕ್ಕೂ ಹೆಚ್ಚು ಪ್ರಮಾಣಗಳ ವ್ಯತ್ಯಾಸ.\n1. ಪಾಠದ ನಿಖರ 10-layer diagnostic code ಚಲಾಯಿಸಿ ಮತ್ತು ಇದೇ ಮಾದರಿ ಕಾಣುತ್ತೀರಿ ಎಂದು ಖಚಿತಪಡಿಸಿ.\n2. layer 10 ya gradient norm ಮತ್ತು layer 0 ya gradient norm ನಡುವಿನ ಅನುಪಾತ ಲೆಕ್ಕಾಚಾರ ಮಾಡಿ. ಇದೂ 10 layers ಆದ್ಯಂತ sigmoid derivatives (ಪ್ರತಿಯೊಂದೂ 0.25 ಕ್ಕೆ ಮಿತಿಗೊಂಡಿದೆ) stack ಮಾಡುವುದರಿಂದ ನೀವೂ ನಿರೀಕ್ಷಿಸುವುದಕ್ಕೆ ಸುಮಾರಾಗಿ ಹೊಂದಿಕೊಳ್ಳುತ್ತದೆಯೇ?\n3. ಈ diagnostic ಕೇವಲ ಒಂದೂ ಅಂತಿಮ ಸಂಖ್ಯೆಯ ಬದಲಿಗೆ PER LAYER gradient norm ಮುದ್ರಿಸುತ್ತದೆ. per-layer norms ಮುದ್ರಿಸುವುದೂ training loss ಕಡಿಮೆಯಾಗುತ್ತದೆಯೇ ಎಂದು ಕೇವಲ ಪರಿಶೀಲಿಸುವುದಕ್ಕಿಂತ ಏಕೆ ಹೆಚ್ಚು ಉಪಯುಕ್ತ debugging ಸಾಧನ?" },
  { phaseId, moduleId: m66, lessonId: l66, order: 2, difficulty: 'intermediate',
    title: 'Genuinely Diagnosing Dead ReLU Units',
    titleKn: 'Dead ReLU Units ಅನ್ನೂ ನಿಜವಾಗಿ ರೋಗನಿರ್ಣಯ ಮಾಡುವುದೂ',
    problem: "The lesson's diagnostic on 200 random inputs found units 0 and 1 were 0.0% active (dead=True, caused by biases -10.0 and -10.0), while units 2, 3, and 4 (biases 0.1, 0.2, -0.1) were active 46-59% of the time.\n1. Run the lesson's exact dead-unit diagnostic and confirm units 0 and 1 show 0.0% activation.\n2. Explain the mechanism: why does a large NEGATIVE bias (like -10.0) combined with typical random-normal inputs (mean 0, std 1) make it nearly impossible for z = X@W+b to ever exceed 0 for that unit, permanently killing its ReLU output?\n3. Change the bias for unit 0 from -10.0 to -0.5 and rerun the diagnostic. Does the fraction of active inputs for that unit increase? At what rough bias value does the unit stop being 'dead' (active on more than 10% of inputs)?",
    problemKn: "200 ಯಾದೃಚ್ಛಿಕ inputs ಮೇಲೆ ಪಾಠದ diagnostic units 0 ಮತ್ತು 1 0.0% ಸಕ್ರಿಯವಾಗಿವೆ ಎಂದು ಕಂಡುಕೊಂಡಿತು (biases -10.0 ಇಂದ ಉಂಟಾಗಿದೆ), ಆದರೆ units 2, 3, ಮತ್ತು 4 46-59% ಸಮಯ ಸಕ್ರಿಯವಾಗಿದ್ದವು.\n1. ಪಾಠದ ನಿಖರ dead-unit diagnostic ಚಲಾಯಿಸಿ ಮತ್ತು units 0 ಮತ್ತು 1 0.0% activation ತೋರಿಸುತ್ತವೆ ಎಂದು ಖಚಿತಪಡಿಸಿ.\n2. ಒಂದೂ ದೊಡ್ಡ ಋಣಾತ್ಮಕ bias (-10.0 ರಂತೆ) ವಿಶಿಷ್ಟ random-normal inputs ಜೊತೆ ಸೇರಿ z = X@W+b ಅನ್ನೂ 0 ಮೀರಲು ಬಹುತೇಕ ಅಸಾಧ್ಯಗೊಳಿಸುತ್ತದೆ, ಆ unit ya ReLU output ಶಾಶ್ವತವಾಗಿ ಕೊಲ್ಲುತ್ತದೆ ಎಂದು ಕಾರ್ಯವಿಧಾನ ವಿವರಿಸಿ.\n3. unit 0 ya bias ಅನ್ನೂ -10.0 ಇಂದ -0.5 ಗೆ ಬದಲಾಯಿಸಿ ಮತ್ತು diagnostic ಮರುಚಲಾಯಿಸಿ. ಆ unit ಗೆ ಸಕ್ರಿಯ inputs ya ಪಾಲು ಹೆಚ್ಚಾಗುತ್ತದೆಯೇ?" },
  { phaseId, moduleId: m66, lessonId: l66, order: 3, difficulty: 'advanced',
    title: 'Genuinely Triggering and Diagnosing Exploding Loss',
    titleKn: 'Exploding Loss ಅನ್ನೂ ನಿಜವಾಗಿ ಪ್ರಚೋದಿಸುವುದೂ ಮತ್ತು ರೋಗನಿರ್ಣಯ ಮಾಡುವುದೂ',
    problem: "The lesson's linear model with lr=0.5 genuinely diverged: loss went from 2.56 (step 0) to 100.0 (step 1) to 3906.25 (step 2) to 5960464.48 (step 4) -- each step roughly 40x worse than the last.\n1. Run the lesson's exact exploding-loss code and confirm this genuinely diverging sequence of losses.\n2. Notice the loss ratio between consecutive steps is roughly constant (about 40x). For this specific quadratic loss landscape, derive (or empirically estimate) the relationship between the ratio and the learning rate that determines whether the optimization converges or diverges.\n3. Binary search for the approximate largest learning rate (to one decimal place) that still lets this exact problem converge instead of diverge within 8 steps. Report the threshold you find and the loss trajectory just below and just above it.",
    problemKn: "ಪಾಠದ lr=0.5 ಇರುವ linear model ನಿಜವಾಗಿ ಡೈವರ್ಜ್ ಆಯಿತು: loss 2.56 (step 0) ಇಂದ 5960464.48 (step 4) ಗೆ ಏರಿತು.\n1. ಪಾಠದ ನಿಖರ exploding-loss code ಚಲಾಯಿಸಿ ಮತ್ತು ಈ ನಿಜವಾಗಿ ಡೈವರ್ಜ್ ಆಗುವ losses ಅನುಕ್ರಮ ಖಚಿತಪಡಿಸಿ.\n2. ಸತತ steps ನಡುವಿನ loss ratio ಸುಮಾರು ಸ್ಥಿರವಾಗಿದೆ (ಸುಮಾರು 40x) ಎಂದು ಗಮನಿಸಿ. ಈ ನಿರ್ದಿಷ್ಟ quadratic loss landscape ಗೆ, ratio ಮತ್ತು convergence/divergence ನಿರ್ಧರಿಸುವ learning rate ನಡುವಿನ ಸಂಬಂಧವನ್ನೂ ಪಡೆಯಿರಿ.\n3. 8 steps ಒಳಗೆ ಈ ನಿಖರ ಸಮಸ್ಯೆ ಇನ್ನೂ ಒಮ್ಮುಖವಾಗಲು ಅನುಮತಿಸುವ ಅಂದಾಜು ಗರಿಷ್ಠ learning rate (ಒಂದೂ ದಶಮಾಂಶ ಸ್ಥಳಕ್ಕೆ) ಗಾಗಿ binary search ಮಾಡಿ." },
];
