const phaseId = '6a369d5666020ed05b321334'; // Phase 9

const m126 = '6a369d5666020ed05b32133d'; // Module 126: Audio Classification
const m127 = '6a369d5666020ed05b321340'; // Module 127: Speech Recognition (ASR)

const l126_1 = '6a6cedb5286e9b902cff4154'; // From MFCCs to k-NN
const l126_2 = '6a6cef0693dd2beee3eb0d17'; // From k-NN on MFCCs to AST and BEATs
const l127_1 = '6a6cf03224b4f55f50fb081a'; // CTC Foundations
const l127_2 = '6a6cf16ae2af02bdd466405f'; // Modern ASR: RNN-T, Attention, Whisper & Parakeet

module.exports = [
  // ── Module 126, Lesson 1: Audio Classification — From MFCCs to k-NN ──
  { phaseId, moduleId: m126, lessonId: l126_1, order: 1, difficulty: 'beginner',
    title: 'Fixed-Length Summarization of MFCC Frames',
    problem: "Using summarize(mfcc_frames) on test_frames = [[1,2,3],[2,3,4],[3,4,5]]:\n1. Compute the mean and variance by hand for the first coefficient (values 1, 2, 3), then run the code and confirm.\n2. What is the length of the returned vector for 3-dimensional MFCC frames? Why does the function concatenate mean and var instead of returning just the mean?\n3. Add a fourth frame [10, 10, 10] (an outlier) to test_frames. How much does it shift the mean vs. how much does it shift the variance? What does this tell you about summary statistics' sensitivity to outlier frames?" },
  { phaseId, moduleId: m126, lessonId: l126_1, order: 2, difficulty: 'intermediate',
    title: 'Cosine Similarity for Audio Embeddings',
    problem: "Using cosine(a, b) from the lesson:\n1. Compute cosine([1,2,3],[1,2,3]) -- confirm it equals 1.0 for identical vectors.\n2. Compute cosine([1,2,3],[-1,-2,-3]) -- what value do you get for exactly opposite vectors, and why does that make sense geometrically?\n3. Compute cosine([1,0,0],[0,1,0]) -- two orthogonal vectors. Why is the result 0, and what would that mean if these were two audio embeddings?\n4. Build two 26-dimensional feature vectors using summarize() on two different toy MFCC sequences (one repeating a low-energy pattern, one repeating a high-energy pattern) and compare their cosine similarity to two summarize() calls on the *same* sequence." },
  { phaseId, moduleId: m126, lessonId: l126_1, order: 3, difficulty: 'intermediate',
    title: 'Implementing k-NN Classification',
    problem: "Complete and run knn_classify(q, bank, labels, k=5) using cosine similarity as the distance metric.\n1. Build a toy bank of 10 feature vectors with 2 classes (5 each, clustered around two different points), and classify a query vector close to class A. Does it predict correctly?\n2. Vary k from 1 to 9 (odd values). Does the prediction ever flip? Under what circumstance would a very large k start misclassifying points near a class boundary?\n3. What happens if you set k larger than len(bank)? Should the function guard against that, and how?" },
  { phaseId, moduleId: m126, lessonId: l126_1, order: 4, difficulty: 'advanced',
    title: 'End-to-End MFCC + k-NN Pipeline',
    problem: "Chain together featurize_mfcc() -> summarize() -> knn_classify() from this lesson (reusing your mel filterbank + log + DCT functions from Module 125 to build featurize_mfcc if you haven't already).\n1. Generate two synthetic 'classes' of audio: sine waves around 300Hz (class A) and sine waves around 3000Hz (class B), 5 examples each with slight frequency jitter.\n2. Extract MFCC-summary features for all 10, hold out 2 (one per class) as queries, and classify them with the rest as the bank.\n3. Report accuracy. Since these two classes are separated by a huge frequency gap, would you expect this simple baseline to do well or poorly? Why might it do worse on two real-world sound classes that share more spectral overlap (e.g. two different dog breeds barking)?" },
  { phaseId, moduleId: m126, lessonId: l126_1, order: 5, difficulty: 'beginner',
    title: 'Why the k-NN Baseline Still Matters',
    problem: "The lesson argues a simple MFCC + k-NN baseline is still useful even in 2026, when transformer-based classifiers (AST, BEATs) exist.\n1. List three reasons a team might reach for this baseline before training or fine-tuning a deep model (think about data requirements, compute, and interpretability).\n2. If a k-NN baseline gets 60% accuracy on a 10-class sound classification task, is that impressive? Compute what a random-guessing baseline would score, and compare.\n3. In your own words, explain why a low-effort, low-accuracy baseline is still valuable for a project even after you know you'll eventually replace it with a stronger model." },

  // ── Module 126, Lesson 2: Audio Classification — From k-NN on MFCCs to AST and BEATs ──
  { phaseId, moduleId: m126, lessonId: l126_2, order: 1, difficulty: 'intermediate',
    title: 'Building and Inspecting an AudioCNN',
    problem: "Instantiate the lesson's AudioCNN(n_mels=80, n_classes=50).\n1. Count its total parameters with sum(p.numel() for p in model.parameters()).\n2. Feed it a random tensor shaped like a batch of log-mel spectrograms, e.g. torch.randn(4, 1, 80, 200) (batch=4, channel=1, mel bins=80, time frames=200). Does the forward pass run without shape errors?\n3. Print the output shape. Does the final dimension equal n_classes=50, as expected for a classifier's logits?\n4. What happens if you pass a spectrogram with a different number of time frames, e.g. (4, 1, 80, 50)? Does the CNN still work? Why can convolutional layers handle variable-length time axes but not variable numbers of mel bins (given how this specific architecture is built)?" },
  { phaseId, moduleId: m126, lessonId: l126_2, order: 2, difficulty: 'intermediate',
    title: 'Attempting AST Fine-Tuning',
    problem: "Attempt the lesson's AST setup: ASTFeatureExtractor.from_pretrained('MIT/ast-finetuned-audioset-10-10-0.4593') and ASTForAudioClassification.from_pretrained(..., num_labels=50, ignore_mismatched_sizes=True).\n1. Does loading succeed in your environment? If it requires downloading a checkpoint, how large is it and how long does it take?\n2. Extract features from a real or synthetic short audio clip with the feature extractor. What shape are the resulting inputs?\n3. Explain what ignore_mismatched_sizes=True is doing here -- why would the classification head's shape mismatch between the pretrained checkpoint (its original number of classes) and your num_labels=50?\n4. If the download or load genuinely fails in your environment, document the exact error honestly rather than assuming it would have worked -- what's the real blocker (network, disk space, missing dependency)?" },
  { phaseId, moduleId: m126, lessonId: l126_2, order: 3, difficulty: 'advanced',
    title: 'CNN vs. Transformer: Parameter and Compute Comparison',
    problem: "Compare your AudioCNN's parameter count (from problem 1) against AST's reported parameter count (check the model card for MIT/ast-finetuned-audioset-10-10-0.4593, or count it directly if it loaded successfully in your environment).\n1. How many times larger is AST than your small CNN?\n2. Given that difference, when would you choose the CNN baseline over AST for a real deployment, and vice versa? Consider latency, accuracy, and available training data.\n3. BEATs is described as 'the 2026 default' in the lesson. Research (or reason from the lesson's description) what makes a self-supervised pretrained audio encoder like BEATs generally preferable to training a CNN from scratch on a small labeled dataset." },
  { phaseId, moduleId: m126, lessonId: l126_2, order: 4, difficulty: 'intermediate',
    title: 'Mixup Data Augmentation',
    problem: "The lesson covers Mixup and SpecAugment as data augmentation techniques.\n1. Implement a simple Mixup function: given two log-mel spectrograms x1, x2 and their one-hot labels y1, y2, and a mixing coefficient lambda sampled from a Beta distribution, return lambda*x1 + (1-lambda)*x2 and lambda*y1 + (1-lambda)*y2.\n2. Apply it to two toy spectrograms (e.g. two different random tensors) with lambda=0.7. Confirm the output is a genuine blend by checking it lies between the two inputs elementwise.\n3. Why does mixing labels (not just inputs) matter for training -- what would happen if you fed the model a blended spectrogram but kept a single hard label?" },
  { phaseId, moduleId: m126, lessonId: l126_2, order: 5, difficulty: 'beginner',
    title: 'SpecAugment: Time and Frequency Masking',
    problem: "SpecAugment masks random blocks of a spectrogram's time and frequency axes during training.\n1. Take a log-mel spectrogram (real or synthesized as np.random.randn(80, 200)) and zero out a random contiguous block of 10 frequency bins (frequency masking).\n2. Now zero out a random contiguous block of 20 time frames (time masking) on the same spectrogram.\n3. Explain why masking chunks of the *input* during training, rather than adding random noise everywhere, forces the model to rely on redundant information across the spectrogram -- and why that redundancy exists in real audio in the first place." },

  // ── Module 127, Lesson 1: Speech Recognition (ASR) — CTC Foundations ──
  { phaseId, moduleId: m127, lessonId: l127_1, order: 1, difficulty: 'beginner',
    title: 'Greedy CTC Decoding by Hand',
    problem: "Using ctc_greedy(frame_logits, blank=0, vocab) with vocab = {0:'_', 1:'A', 2:'B', 3:'C'}:\n1. Construct a toy frame_logits sequence that should decode to 'AB': e.g. frames favoring A, A, blank, B, B (use one-hot-ish probability lists per frame).\n2. Run ctc_greedy and confirm it collapses repeated 'A's into one and removes the blank correctly.\n3. Now construct a sequence for 'AAB' (double-A word) using frame_logits like A, blank, A, B, B -- note the explicit blank between the two A's. Confirm the output is 'AAB', not 'AB'. Why is the blank symbol the *only* way CTC can represent a repeated character?" },
  { phaseId, moduleId: m127, lessonId: l127_1, order: 2, difficulty: 'intermediate',
    title: 'Why Greedy Decoding Can Fail',
    problem: "The lesson explains greedy CTC decoding can pick a locally-best but globally-wrong path.\n1. Construct a toy frame_logits example where, at one frame, two symbols have nearly equal probability (e.g. 0.51 vs 0.49) but picking the lower one would lead to a much more probable overall sequence when combined with later frames. (You'll need to design the surrounding frames deliberately.)\n2. Run ctc_greedy on it and observe it picks the frame-by-frame max regardless of the sequence-level outcome.\n3. In your own words, explain why 'always pick the highest-probability symbol at each frame' isn't the same as 'find the highest-probability full sequence' -- this is exactly the gap beam search is designed to close." },
  { phaseId, moduleId: m127, lessonId: l127_1, order: 3, difficulty: 'advanced',
    title: 'Implementing and Testing Beam Search CTC',
    problem: "Complete the lesson's ctc_beam(frame_logits, beam=8, blank=0) function.\n1. Run it on the same 'AB'-favoring frame_logits from practice 1 above with beam=1. Does it match greedy decoding's output (it should, since beam=1 is equivalent to greedy)?\n2. Run it with beam=8 on the ambiguous example from practice 2. Does beam search recover the globally better sequence that greedy missed?\n3. Increase beam to 50. Does the output change further, or does it converge? At what point does increasing beam width stop mattering, and what does that cost in extra computation?" },
  { phaseId, moduleId: m127, lessonId: l127_1, order: 4, difficulty: 'intermediate',
    title: 'Computing Word Error Rate (WER)',
    problem: "Complete and run wer(ref, hyp) using dynamic programming (edit distance).\n1. Compute WER for ref='the quick brown fox' vs hyp='the quick brown fox' (identical). Confirm it's 0.\n2. Compute WER for ref='the quick brown fox' vs hyp='the quick brown fx' (one word garbled). What's the WER, and does it count as one substitution?\n3. Compute WER for ref='the quick brown fox' vs hyp='the quick brown' (one word dropped). Is a deletion penalized the same as a substitution?\n4. A hypothesis with extra hallucinated words (e.g. hyp='the quick brown fox jumps') -- does WER penalize insertions too? Compute it and confirm." },
  { phaseId, moduleId: m127, lessonId: l127_1, order: 5, difficulty: 'beginner',
    title: 'The Alignment Problem: Why ASR Needs CTC',
    problem: "The lesson frames ASR's core difficulty as the 'alignment problem': audio frames vastly outnumber output characters, and we don't know in advance which frames correspond to which letters.\n1. If an utterance is 2 seconds long at 16kHz with 20ms frames, how many frames does the model see?\n2. If the transcript is 'hello' (5 characters), how many possible ways could 100 frames align to 5 output characters, roughly? (You don't need an exact combinatorial answer -- just argue why brute-force alignment search is intractable.)\n3. In one paragraph, explain how introducing a 'blank' token and defining a collapse rule solves this without requiring frame-level alignment labels during training." },

  // ── Module 127, Lesson 2: Modern ASR: RNN-T, Attention, Whisper & Parakeet ──
  { phaseId, moduleId: m127, lessonId: l127_2, order: 1, difficulty: 'intermediate',
    title: 'WER on Realistic Whisper-Style Output',
    problem: "Reuse the wer() function from the previous lesson.\n1. Simulate three realistic ASR outputs against a fixed reference sentence of your choice (8-10 words): a near-perfect hypothesis (1 minor error), a hypothesis with a dropped word, and a hypothesis with hallucinated extra words.\n2. Compute WER for all three. Rank them from best to worst.\n3. WER treats every word substitution/insertion/deletion equally. Give an example where two errors have very different real-world severity (e.g. a filler-word insertion vs. a number substitution) despite counting the same in WER -- what does this tell you about relying on WER alone to judge an ASR system?" },
  { phaseId, moduleId: m127, lessonId: l127_2, order: 2, difficulty: 'advanced',
    title: 'Genuinely Running Whisper Inference',
    problem: "Following whisper_inference.py: generate audio = np.array(sine(440, 16000, 3), dtype=np.float32) as a stand-in for a real speech clip (since a genuine speech recording likely isn't available in your environment), then model = whisper.load_model('tiny') and transcribe it.\n1. Does the model load successfully? How long does loading take?\n2. What does Whisper transcribe a pure sine tone as? (It's not speech, so expect a nonsensical or empty-ish result -- report exactly what you get, don't guess.)\n3. If you have access to any real short speech clip (even a recorded sentence from your own voice), run the same pipeline on it and compare the transcript's accuracy to the sine-tone result.\n4. Why does substituting a synthetic tone for real speech still let you verify that the *pipeline* (model loading, inference call, output parsing) works, even though it can't verify transcription *accuracy*?" },
  { phaseId, moduleId: m127, lessonId: l127_2, order: 3, difficulty: 'intermediate',
    title: 'RNN-T vs. CTC vs. Attention: Comparing Architectures',
    problem: "The lesson introduces RNN-T (audio + previous tokens) and attention encoder-decoder (Whisper's approach) as alternatives to plain CTC.\n1. In your own words, explain what information CTC decoding lacks that RNN-T explicitly conditions on (the phrase 'previous tokens' is the hint).\n2. Whisper's attention mechanism lets the decoder look at the *entire* audio encoding, not just a local window. Why might that help with long-range disambiguation (e.g. resolving a word based on context from much earlier in the sentence) in a way that streaming CTC cannot?\n3. Given these tradeoffs, which architecture would you expect to have lower first-token latency in a real-time streaming setting: CTC, RNN-T, or full attention? Justify your answer using what you learned about streaming in Module 134." },
  { phaseId, moduleId: m127, lessonId: l127_2, order: 4, difficulty: 'advanced',
    title: 'Attempting Streaming ASR With Parakeet',
    problem: "The lesson's parakeet_streaming.py example uses transformers.pipeline('automatic-speech-recognition', model='nvidia/parakeet-tdt-1.1b').\n1. Genuinely attempt to load this pipeline in your environment (note: this is a large model -- document how long it takes or whether it completes at all within a reasonable time budget).\n2. If loading succeeds, run it against a short real or synthetic audio clip using return_timestamps=True. What does the output structure look like?\n3. If loading fails or times out, document the exact failure honestly (network timeout, disk space, memory) rather than assuming success -- this mirrors the course's established discipline of only claiming what was genuinely verified." },
  { phaseId, moduleId: m127, lessonId: l127_2, order: 5, difficulty: 'beginner',
    title: 'Choosing Between Whisper and Parakeet',
    problem: "Based on this lesson and Module 128, compare Whisper and Parakeet on three axes:\n1. Streaming support -- which is designed for streaming/low-latency use, and which is more naturally a batch/offline model?\n2. Multilingual coverage -- which one is known for broader language support?\n3. Given a hypothetical product requirement ('near-real-time transcription for a voice assistant in English only'), which would you pick and why? Given a different requirement ('offline transcription of podcasts in 50 languages'), does your answer change?" },
];
