const phaseId = '6a369d5e66020ed05b3214c3'; // Phase 16: Tools and Protocols

const m252 = '6a369d5f66020ed05b3214cc';
const m253 = '6a369d5f66020ed05b3214cf';

const l252_1 = '6aa5095d3bc62ea7a12358fe';
const l252_2 = '6aa50a337b58b4fd2492a630';
const l252_3 = '6aa50ae8e52c6069a72f288e';
const l253_1 = '6aa50be0dad4899aeaef8f80';
const l253_2 = '6aa50c9a4dd04940228601ff';
const l253_3 = '6aa50d653d082f1a6c1a0755';

module.exports = [
  // ── Module 252, Lesson 1: Parallel Tool Calls and Streaming (Part 1) ──
  { phaseId, moduleId: m252, lessonId: l252_1, order: 1, difficulty: 'intermediate',
    title: 'Genuinely Measuring the 54.5% Speedup',
    titleKn: 'Genuinely 54.5% Speedup ಅಳೆಯುವುದೂ',
    problem: "The lesson's run_sequential on 3 cities (latencies 0.1s, 0.15s, 0.2s) genuinely took 0.452s, while run_parallel (ThreadPoolExecutor) took only 0.205s -- a 54.5% time reduction.\n1. Run both the lesson's exact run_sequential and run_parallel functions and confirm your own elapsed times show a similar large reduction.\n2. The sequential time (0.452s) is close to the SUM of the three latencies (0.1+0.15+0.2=0.45s). The parallel time (0.205s) is close to the MAX of the three latencies (0.2s). Explain why parallel execution time approaches the max rather than the sum.\n3. If a 4th city with latency 0.5s were added, predict (without running it) what the new sequential and parallel times would roughly be, then run it and check your prediction.",
    problemKn: "ಪಾಠದ run_sequential 3 cities ಮೇಲೆ ನಿಜವಾಗಿ 0.452s ತೆಗೆದುಕೊಂಡಿತು, ಆದರೆ run_parallel ಕೇವಲ 0.205s ತೆಗೆದುಕೊಂಡಿತು -- 54.5% ಸಮಯ ಕಡಿತ.\n1. ಪಾಠದ ನಿಖರ run_sequential ಮತ್ತು run_parallel functions ಚಲಾಯಿಸಿ ಮತ್ತು ನಿಮ್ಮ ಸ್ವಂತ elapsed times ಇದೇ ರೀತಿಯ ದೊಡ್ಡ ಕಡಿತ ತೋರಿಸುತ್ತವೆ ಎಂದು ಖಚಿತಪಡಿಸಿ.\n2. sequential time (0.452s) ಮೂರೂ latencies ya SUM ಗೆ ಹತ್ತಿರವಾಗಿದೆ. parallel time (0.205s) MAX ಗೆ ಹತ್ತಿರವಾಗಿದೆ. parallel execution time sum ಬದಲಿಗೆ max ಕ್ಕೆ ಏಕೆ ಹತ್ತಿರವಾಗುತ್ತದೆ ಎಂದು ವಿವರಿಸಿ.\n3. 0.5s latency ya 4ನೇ city ಸೇರಿಸಿದರೆ, ಹೊಸ sequential ಮತ್ತು parallel times ಏನೂ ಆಗಿರುತ್ತದೆ ಎಂದು (ಚಲಾಯಿಸದೆ) ಊಹಿಸಿ, ನಂತರ ಚಲಾಯಿಸಿ ಪರಿಶೀಲಿಸಿ." },
  { phaseId, moduleId: m252, lessonId: l252_1, order: 2, difficulty: 'beginner',
    title: 'Model-Level Fan-Out vs Host-Level Concurrency',
    titleKn: 'Model-Level Fan-Out vs Host-Level Concurrency',
    problem: "1. In your own words, distinguish between 'model-level fan-out' (the LLM deciding to request multiple tool calls at once) and 'host-level concurrency' (your Python code choosing to execute those calls using a ThreadPoolExecutor). Which one does the LLM control, and which one do YOU control?\n2. Could you have model-level fan-out (multiple tool calls requested) but choose NOT to use host-level concurrency (execute them one at a time anyway)? What would you lose by doing this?\n3. Could you have host-level concurrency infrastructure ready, but the model only ever requests ONE tool call at a time? In that case, is your ThreadPoolExecutor code providing any benefit?",
    problemKn: "1. 'model-level fan-out' ಮತ್ತು 'host-level concurrency' ನಡುವೆ ವ್ಯತ್ಯಾಸ ಗುರುತಿಸಿ. ಯಾವುದನ್ನೂ LLM ನಿಯಂತ್ರಿಸುತ್ತದೆ, ಯಾವುದನ್ನೂ ನೀವೂ ನಿಯಂತ್ರಿಸುತ್ತೀರಿ?\n2. model-level fan-out ಇದ್ದರೆ ಆದರೆ host-level concurrency ಬಳಸದಿದ್ದರೆ (ಒಂದೊಂದಾಗಿ ಚಲಾಯಿಸಿದರೆ) ಏನೂ ಕಳೆದುಕೊಳ್ಳುತ್ತೀರಿ?\n3. host-level concurrency infrastructure ಸಿದ್ಧವಾಗಿದ್ದರೆ ಆದರೆ model ಯಾವಾಗಲೂ ಒಂದೇ tool call ಕೇಳಿದರೆ, ನಿಮ್ಮ ThreadPoolExecutor code ಯಾವುದೇ ಪ್ರಯೋಜನ ನೀಡುತ್ತಿದೆಯೇ?" },
  { phaseId, moduleId: m252, lessonId: l252_1, order: 3, difficulty: 'intermediate',
    title: 'Dependency Chains: When NOT to Parallelize',
    titleKn: 'Dependency Chains: ಯಾವಾಗ Parallelize ಮಾಡಬಾರದು',
    problem: "1. The lesson warns about dependency chains where parallelizing tool calls would be incorrect. Construct a concrete example: a 2-step task where step 2's arguments genuinely DEPEND on step 1's result (e.g. 'look up a user's ID, then fetch that user's order history').\n2. If you naively fired both calls in parallel using ThreadPoolExecutor for your dependency-chain example, what would go wrong?\n3. The lesson also discusses rate limits as a reason parallelism 'is not free'. If you have 10 independent tool calls to make but your API allows only 3 concurrent requests, how would you modify the lesson's ThreadPoolExecutor pattern (specifically the max_workers parameter) to respect that limit?",
    problemKn: "1. ಪಾಠ dependency chains ಬಗ್ಗೆ ಎಚ್ಚರಿಸುತ್ತದೆ, ಅಲ್ಲಿ tool calls parallelize ಮಾಡುವುದೂ ತಪ್ಪಾಗಿರುತ್ತದೆ. ಒಂದೂ ನಿರ್ದಿಷ್ಟ ಉದಾಹರಣೆ ನಿರ್ಮಿಸಿ.\n2. ಈ dependency-chain ಉದಾಹರಣೆಗೆ ThreadPoolExecutor ಬಳಸಿ ಎರಡೂ calls ಅನ್ನೂ ಸರಳವಾಗಿ parallel ಆಗಿ ಚಲಾಯಿಸಿದರೆ ಏನೂ ತಪ್ಪಾಗುತ್ತದೆ?\n3. ನಿಮಗೆ 10 ಸ್ವತಂತ್ರ tool calls ಇದ್ದರೆ ಆದರೆ ನಿಮ್ಮ API ಕೇವಲ 3 concurrent requests ಅನುಮತಿಸಿದರೆ, ಪಾಠದ ThreadPoolExecutor ಮಾದರಿಯನ್ನೂ (max_workers parameter) ಆ ಮಿತಿ ಗೌರವಿಸಲು ಹೇಗೂ ಮಾರ್ಪಡಿಸುತ್ತೀರಿ?" },

  // ── Module 252, Lesson 2: Parallel Tool Calls and Streaming (Part 2) ──
  { phaseId, moduleId: m252, lessonId: l252_2, order: 1, difficulty: 'intermediate',
    title: 'The Parse-Early Trap, Genuinely Triggered',
    titleKn: 'Parse-Early Trap, ನಿಜವಾಗಿ ಪ್ರಚೋದಿಸಲಾಗಿದೆ',
    problem: "The lesson genuinely tried json.loads() on a partial/incomplete streamed chunk ('{\"city\":\"Ben') and got a real JSONDecodeError: 'Unterminated string starting at: line 1 column 9 (char 8)'.\n1. Run this exact code and confirm the same error.\n2. Why does this error happen -- what's structurally incomplete about the string '{\"city\":\"Ben' that makes it invalid JSON?\n3. This is called the 'parse-early trap' because a naive streaming implementation might try to json.loads() every chunk AS it arrives. Why is this a trap rather than just an occasional error -- i.e. why would EVERY intermediate chunk (except the very last one) fail this way?",
    problemKn: "ಪಾಠ ಒಂದೂ ಭಾಗಶಃ streamed chunk ಮೇಲೆ json.loads() ನಿಜವಾಗಿ ಪ್ರಯತ್ನಿಸಿ ಒಂದೂ ನಿಜ JSONDecodeError ಪಡೆಯಿತು.\n1. ಈ ನಿಖರ code ಚಲಾಯಿಸಿ ಮತ್ತು ಅದೇ ದೋಷ ಖಚಿತಪಡಿಸಿ.\n2. ಈ ದೋಷ ಏಕೆ ಸಂಭವಿಸುತ್ತದೆ?\n3. ಇದನ್ನೂ 'parse-early trap' ಎಂದು ಏಕೆ ಕರೆಯಲಾಗುತ್ತದೆ -- ಅಂತಿಮ chunk ಬಿಟ್ಟು ಪ್ರತಿ intermediate chunk ಈ ರೀತಿ ಏಕೆ ವಿಫಲವಾಗುತ್ತದೆ?" },
  { phaseId, moduleId: m252, lessonId: l252_2, order: 2, difficulty: 'advanced',
    title: 'StreamAccumulator Genuinely Handling an Interleaved Stream',
    titleKn: 'StreamAccumulator ನಿಜವಾಗಿ ಒಂದೂ Interleaved Stream ನಿರ್ವಹಿಸುವುದೂ',
    problem: "The lesson's StreamAccumulator genuinely handled 3 tool calls (call_A, call_B, call_C) with their argument chunks INTERLEAVED in the fake stream, correctly buffering each call's chunks separately and only calling json.loads() once each call's finish event arrived -- producing 'Arguments complete for call_A: {city: Bengaluru}' at the right point.\n1. Run the lesson's exact StreamAccumulator and FAKE_STREAM replay. Confirm arguments are correctly reassembled per call_id despite the interleaving.\n2. Why does add_arguments need to buffer chunks in a per-call_id dictionary (self.calls[call_id].arguments_buffer) rather than a single shared buffer?\n3. The lesson also showed tool RESULTS completing in a THIRD different order (call_B, call_C, call_A) from both the request order and the argument-streaming order. Run that example and explain why results can complete in yet another order beyond the two you already saw.",
    problemKn: "ಪಾಠದ StreamAccumulator ನಿಜವಾಗಿ 3 tool calls ಅನ್ನೂ INTERLEAVED chunks ಜೊತೆ ಸರಿಯಾಗಿ ನಿರ್ವಹಿಸಿತು.\n1. ಪಾಠದ ನಿಖರ StreamAccumulator ಮತ್ತು FAKE_STREAM replay ಚಲಾಯಿಸಿ. interleaving ಇದ್ದರೂ arguments ಪ್ರತಿ call_id ಗೆ ಸರಿಯಾಗಿ ಮರುಜೋಡಿಸಲ್ಪಡುತ್ತವೆ ಎಂದು ಖಚಿತಪಡಿಸಿ.\n2. add_arguments ಒಂದೂ ಹಂಚಿದ buffer ಬದಲಿಗೆ per-call_id dictionary ಬಳಸಿ chunks buffer ಮಾಡುವುದೂ ಏಕೆ ಅಗತ್ಯ?\n3. ಪಾಠ tool RESULTS ಮೂರನೇ ಬೇರೆ ಕ್ರಮದಲ್ಲಿ ಪೂರ್ಣಗೊಳ್ಳುವುದೂ ಸಹ ತೋರಿಸಿತು. ಆ ಉದಾಹರಣೆ ಚಲಾಯಿಸಿ ಮತ್ತು results ಇನ್ನೂ ಬೇರೆ ಕ್ರಮದಲ್ಲಿ ಏಕೆ ಪೂರ್ಣಗೊಳ್ಳಬಹುದು ಎಂದು ವಿವರಿಸಿ." },
  { phaseId, moduleId: m252, lessonId: l252_2, order: 3, difficulty: 'beginner',
    title: 'Failing Loudly on an Unknown Call ID',
    titleKn: 'ಅಪರಿಚಿತ Call ID ಮೇಲೆ ಗಟ್ಟಿಯಾಗಿ ವಿಫಲಗೊಳ್ಳುವುದೂ',
    problem: "The lesson's acc2.add_arguments('call_ghost', '{}') genuinely raised KeyError: 'Unknown call id: call_ghost' rather than silently ignoring the unknown call or creating a new entry for it.\n1. Run this exact code and confirm the KeyError.\n2. Why is 'fail loudly with an exception' the correct behavior here, rather than either silently dropping the chunk or silently creating a new call_id entry on the fly?\n3. What real bug in a streaming integration would produce a chunk for a call_id the accumulator never saw a 'start' event for? Name one plausible cause.",
    problemKn: "ಪಾಠದ acc2.add_arguments('call_ghost', '{}') ನಿಜವಾಗಿ KeyError ಎಬ್ಬಿಸಿತು, ಅಪರಿಚಿತ call ಅನ್ನೂ ಮೌನವಾಗಿ ನಿರ್ಲಕ್ಷಿಸುವ ಬದಲಿಗೆ.\n1. ಈ ನಿಖರ code ಚಲಾಯಿಸಿ ಮತ್ತು KeyError ಖಚಿತಪಡಿಸಿ.\n2. ಇಲ್ಲಿ 'exception ಜೊತೆ ಗಟ್ಟಿಯಾಗಿ ವಿಫಲಗೊಳ್ಳುವುದೂ' ಏಕೆ ಸರಿಯಾದ ವರ್ತನೆ?\n3. ಒಂದೂ streaming integration ನಲ್ಲಿ ಯಾವ ನಿಜ bug 'start' event ಎಂದಿಗೂ ಕಾಣದ call_id ಗೆ ಒಂದೂ chunk ಉತ್ಪಾದಿಸಬಹುದು? ಒಂದೂ ಸಂಭವನೀಯ ಕಾರಣ ಹೆಸರಿಸಿ." },

  // ── Module 252, Lesson 3: Parallel Tool Calls and Streaming (Part 3) ──
  { phaseId, moduleId: m252, lessonId: l252_3, order: 1, difficulty: 'intermediate',
    title: 'One Failure Among Independent Calls',
    titleKn: 'ಸ್ವತಂತ್ರ Calls ನಡುವೆ ಒಂದೂ ವೈಫಲ್ಯ',
    problem: "The lesson's execute_batch_with_errors genuinely ran 3 calls where one (call_B) failed while call_A and call_C succeeded, and the function correctly reported all three outcomes individually rather than the whole batch crashing.\n1. Run the lesson's exact execute_batch_with_errors on the 3-job batch and confirm you get {ok:True}, {ok:False}, {ok:True} for A, B, C respectively.\n2. Look at where the try/except is placed inside execute_batch_with_errors (inside the for-loop over as_completed, wrapping each future.result() individually). What would happen to calls A and C if the try/except were instead placed OUTSIDE the loop, around the whole for-loop?\n3. Why does isolating each call's error matter more in a PARALLEL batch than in a sequential one, where you might reasonably let one exception halt the whole sequence?",
    problemKn: "ಪಾಠದ execute_batch_with_errors ನಿಜವಾಗಿ 3 calls ಚಲಾಯಿಸಿತು, ಅಲ್ಲಿ ಒಂದೂ (call_B) ವಿಫಲವಾಯಿತು ಆದರೆ ಪೂರ್ಣ batch ಕ್ರ್ಯಾಶ್ ಆಗಲಿಲ್ಲ.\n1. ಪಾಠದ ನಿಖರ execute_batch_with_errors ಚಲಾಯಿಸಿ ಮತ್ತು ಫಲಿತಾಂಶಗಳನ್ನೂ ಖಚಿತಪಡಿಸಿ.\n2. try/except ಎಲ್ಲಿ ಇರಿಸಲಾಗಿದೆ ಎಂದು ನೋಡಿ (loop ಒಳಗೆ, ಪ್ರತಿ future.result() ಸುತ್ತ). ಇದೂ ಬದಲಿಗೆ ಪೂರ್ಣ loop ಸುತ್ತ ಇದ್ದರೆ calls A ಮತ್ತು C ಗೆ ಏನಾಗುತ್ತದೆ?\n3. PARALLEL batch ನಲ್ಲಿ ಪ್ರತಿ call ya ದೋಷ ಪ್ರತ್ಯೇಕಿಸುವುದೂ sequential batch ಗಿಂತ ಏಕೆ ಹೆಚ್ಚು ಮುಖ್ಯ?" },
  { phaseId, moduleId: m252, lessonId: l252_3, order: 2, difficulty: 'intermediate',
    title: 'Genuinely Measuring the Straggler Problem',
    titleKn: 'Straggler ಸಮಸ್ಯೆ ಅನ್ನೂ ನಿಜವಾಗಿ ಅಳೆಯುವುದೂ',
    problem: "The lesson's batch with 2 fast calls (0.02s, 0.03s) and 1 slow straggler (0.3s) genuinely took 0.305s total -- dominated entirely by the straggler, not the fast calls.\n1. Run the lesson's exact 3-job batch (with the slow_straggler) and confirm your elapsed time is close to the straggler's 0.3s delay, not the sum or average of all three.\n2. Even though this is 'parallel' execution, why does one slow call still determine the total batch time? What does this tell you about the LIMITS of parallelism -- parallelism reduces total time to roughly the MAX individual time, but can't go below that.\n3. Name one production mitigation for the straggler problem (e.g. a timeout that returns partial results, or a fallback default for slow calls) and explain how it would change this specific 0.305s measurement.",
    problemKn: "ಪಾಠದ batch (2 ವೇಗದ calls + 1 ನಿಧಾನ straggler) ನಿಜವಾಗಿ 0.305s ಒಟ್ಟೂ ತೆಗೆದುಕೊಂಡಿತು -- straggler ಇಂದ ಸಂಪೂರ್ಣವಾಗಿ ಪ್ರಾಬಲ್ಯ ಪಡೆದಿದೆ.\n1. ಪಾಠದ ನಿಖರ 3-job batch ಚಲಾಯಿಸಿ ಮತ್ತು ನಿಮ್ಮ elapsed time straggler ya 0.3s ಗೆ ಹತ್ತಿರವಾಗಿದೆ ಎಂದು ಖಚಿತಪಡಿಸಿ.\n2. ಇದೂ 'parallel' execution ಆಗಿದ್ದರೂ, ಒಂದೂ ನಿಧಾನ call ಇನ್ನೂ ಒಟ್ಟೂ batch time ನಿರ್ಧರಿಸುವುದೂ ಏಕೆ?\n3. straggler ಸಮಸ್ಯೆಗೆ ಒಂದೂ production mitigation ಹೆಸರಿಸಿ ಮತ್ತು ಇದೂ ಈ ನಿರ್ದಿಷ್ಟ 0.305s measurement ಅನ್ನೂ ಹೇಗೂ ಬದಲಾಯಿಸುತ್ತದೆ ಎಂದು ವಿವರಿಸಿ." },
  { phaseId, moduleId: m252, lessonId: l252_3, order: 3, difficulty: 'beginner',
    title: 'The Common Bugs Checklist, Applied',
    titleKn: 'Common Bugs Checklist, ಅನ್ವಯಿಸಲಾಗಿದೆ',
    problem: "1. List the specific bugs this Module 252 sequence (all 3 parts) genuinely demonstrated: the parse-early trap, the unknown-call-id crash, and the straggler problem. For each, write one sentence on the SYMPTOM you'd see in production logs if this bug occurred.\n2. Why does the lesson insist that isolation and timeouts are 'not optional in production', connecting back to the straggler and error-isolation examples you just ran?\n3. If you were writing a code review checklist for a teammate's new parallel-tool-calling code, list 3 specific things (based on this lesson's genuine findings) you'd check for.",
    problemKn: "1. Module 252 ya ಎಲ್ಲಾ 3 ಭಾಗಗಳು ನಿಜವಾಗಿ ಪ್ರದರ್ಶಿಸಿದ ನಿರ್ದಿಷ್ಟ bugs ಪಟ್ಟಿ ಮಾಡಿ: parse-early trap, unknown-call-id crash, ಮತ್ತು straggler ಸಮಸ್ಯೆ. ಪ್ರತಿಯೊಂದಕ್ಕೂ, production logs ನಲ್ಲಿ ಕಾಣುವ SYMPTOM ಬಗ್ಗೆ ಒಂದೂ ವಾಕ್ಯ ಬರೆಯಿರಿ.\n2. straggler ಮತ್ತು error-isolation ಉದಾಹರಣೆಗಳಿಗೆ ಹಿಂತಿರುಗಿ, isolation ಮತ್ತು timeouts production ನಲ್ಲಿ 'ಐಚ್ಛಿಕವಲ್ಲ' ಎಂದು ಪಾಠ ಏಕೆ ಒತ್ತಾಯಿಸುತ್ತದೆ?\n3. ಒಂದೂ ಸಹೋದ್ಯೋಗಿಯ ಹೊಸ parallel-tool-calling code ಗಾಗಿ code review checklist ಬರೆಯುತ್ತಿದ್ದರೆ, ಈ ಪಾಠದ ಸಂಶೋಧನೆಗಳ ಆಧಾರದ ಮೇಲೆ 3 ನಿರ್ದಿಷ್ಟ ವಿಷಯಗಳನ್ನೂ ಪಟ್ಟಿ ಮಾಡಿ." },

  // ── Module 253, Lesson 1: Structured Output (Part 1) ──
  { phaseId, moduleId: m253, lessonId: l253_1, order: 1, difficulty: 'intermediate',
    title: 'The Three Outcomes: Success, Parse Failure, Schema Failure',
    titleKn: 'ಮೂರೂ ಫಲಿತಾಂಶಗಳು: Success, Parse Failure, Schema Failure',
    problem: "The lesson's parse_and_validate genuinely produced 3 distinct outcome types on the INVOICE_SCHEMA: a Success for valid JSON matching the schema, a ParseFailure with the exact message 'Illegal trailing comma before end of object at line 1, column 56' for malformed JSON, and a SchemaFailure listing 3 accumulated ValidationErrors (quantity type, negative total, extra field) for well-formed JSON that violates the schema.\n1. Run all three of the lesson's exact examples and confirm you get the same Success, ParseFailure message, and the same 3 SchemaFailure errors.\n2. Why are ParseFailure and SchemaFailure genuinely DIFFERENT failure types rather than one generic 'invalid' error? What different information does each carry that the other doesn't?\n3. For the SchemaFailure example, trace through the INVOICE_SCHEMA and explain, for each of the 3 violations, exactly which schema rule was broken (type, minimum, or additionalProperties).",
    problemKn: "ಪಾಠದ parse_and_validate INVOICE_SCHEMA ಮೇಲೆ ನಿಜವಾಗಿ 3 ವಿಭಿನ್ನ ಫಲಿತಾಂಶ ಪ್ರಕಾರಗಳನ್ನೂ ಉತ್ಪಾದಿಸಿತು: Success, ParseFailure, ಮತ್ತು 3 ValidationErrors ಪಟ್ಟಿ ಮಾಡುವ SchemaFailure.\n1. ಪಾಠದ ಎಲ್ಲಾ ಮೂರೂ ನಿಖರ ಉದಾಹರಣೆಗಳನ್ನೂ ಚಲಾಯಿಸಿ ಮತ್ತು ಅದೇ ಫಲಿತಾಂಶಗಳನ್ನೂ ಖಚಿತಪಡಿಸಿ.\n2. ParseFailure ಮತ್ತು SchemaFailure ಒಂದೂ ಸಾಮಾನ್ಯ 'invalid' ದೋಷ ಬದಲಿಗೆ ನಿಜವಾಗಿ ಏಕೆ ವಿಭಿನ್ನ ವೈಫಲ್ಯ ಪ್ರಕಾರಗಳಾಗಿವೆ?\n3. SchemaFailure ಉದಾಹರಣೆಗೆ, INVOICE_SCHEMA ಮೂಲಕ ಪತ್ತೆಹಚ್ಚಿ ಮತ್ತು 3 ಉಲ್ಲಂಘನೆಗಳಲ್ಲಿ ಪ್ರತಿಯೊಂದೂ ಯಾವ schema ನಿಯಮ ಮುರಿಯಿತು ಎಂದು ವಿವರಿಸಿ." },
  { phaseId, moduleId: m253, lessonId: l253_1, order: 2, difficulty: 'beginner',
    title: 'The bool/int Gotcha, Re-Confirmed for Structured Output',
    titleKn: 'bool/int Gotcha, Structured Output ಗಾಗಿ ಮರುದೃಢಪಡಿಸಲಾಗಿದೆ',
    problem: "The lesson genuinely re-confirmed json_type_matches(True, 'integer') and json_type_matches(True, 'number') both return False, while json_type_matches(5, 'integer') returns True.\n1. Run these exact 3 calls and confirm the results.\n2. This is the SAME bool/int gotcha from Module 250's tool validation, now appearing in Module 253's structured-output validation. Why does this same subtle bug need to be independently guarded against in BOTH tool-argument validation and structured-output schema validation, rather than being fixed once?\n3. Add a field to INVOICE_SCHEMA that's typed 'boolean' (e.g. 'is_paid') and write a test showing json_type_matches correctly ACCEPTS True/False for that field while still rejecting True for 'integer'/'number' fields.",
    problemKn: "ಪಾಠ ನಿಜವಾಗಿ ಮರುದೃಢಪಡಿಸಿತು json_type_matches(True, 'integer') ಮತ್ತು json_type_matches(True, 'number') ಎರಡೂ False ಹಿಂತಿರುಗಿಸುತ್ತವೆ.\n1. ಈ ನಿಖರ 3 ಕರೆಗಳನ್ನೂ ಚಲಾಯಿಸಿ ಮತ್ತು ಫಲಿತಾಂಶಗಳನ್ನೂ ಖಚಿತಪಡಿಸಿ.\n2. ಇದೂ Module 250 ya tool validation ಇಂದ ಅದೇ bool/int gotcha, ಈಗ Module 253 ya structured-output validation ನಲ್ಲಿ ಕಾಣಿಸಿಕೊಳ್ಳುತ್ತದೆ. ಈ ಒಂದೇ ಸೂಕ್ಷ್ಮ bug ಎರಡೂ ಕಡೆಗಳಲ್ಲಿ ಸ್ವತಂತ್ರವಾಗಿ ಏಕೆ ಕಾಪಾಡಬೇಕು?\n3. INVOICE_SCHEMA ಗೆ 'boolean' typed field ಸೇರಿಸಿ ಮತ್ತು json_type_matches ಆ field ಗೆ True/False ಸರಿಯಾಗಿ ಸ್ವೀಕರಿಸುತ್ತದೆ ಎಂದು ತೋರಿಸುವ ಒಂದೂ test ಬರೆಯಿರಿ." },
  { phaseId, moduleId: m253, lessonId: l253_1, order: 3, difficulty: 'intermediate',
    title: 'Building Your Own Schema and Breaking It on Purpose',
    titleKn: 'ನಿಮ್ಮ ಸ್ವಂತ Schema ನಿರ್ಮಿಸಿ ಉದ್ದೇಶಪೂರ್ವಕವಾಗಿ ಮುರಿಯುವುದೂ',
    problem: "1. Design your own JSON schema (similar to INVOICE_SCHEMA) for a simple 'shipping_label' object with at least 3 required fields of different types (string, number, array).\n2. Write 3 test inputs against your schema: one genuinely valid, one that fails to PARSE (malformed JSON), and one that parses but VIOLATES your schema (at least 2 accumulated errors).\n3. Run parse_and_validate (or your own equivalent) on all 3 and confirm you get Success, ParseFailure, and SchemaFailure respectively, matching the lesson's 3-outcome pattern.",
    problemKn: "1. INVOICE_SCHEMA ಗೆ ಹೋಲುವ, ಕನಿಷ್ಠ 3 ವಿಭಿನ್ನ type ya required fields ಹೊಂದಿರುವ ಒಂದೂ 'shipping_label' object ಗಾಗಿ ನಿಮ್ಮ ಸ್ವಂತ JSON schema ವಿನ್ಯಾಸಗೊಳಿಸಿ.\n2. ನಿಮ್ಮ schema ವಿರುದ್ಧ 3 test inputs ಬರೆಯಿರಿ: ಒಂದೂ ನಿಜವಾಗಿ ಮಾನ್ಯ, ಒಂದೂ PARSE ವಿಫಲಗೊಳ್ಳುತ್ತದೆ, ಒಂದೂ parse ಆಗುತ್ತದೆ ಆದರೆ schema ಉಲ್ಲಂಘಿಸುತ್ತದೆ.\n3. ಎಲ್ಲಾ 3 ಮೇಲೆ parse_and_validate ಚಲಾಯಿಸಿ ಮತ್ತು ಪಾಠದ 3-outcome ಮಾದರಿಗೆ ಹೊಂದಿಕೊಳ್ಳುವ Success, ParseFailure, ಮತ್ತು SchemaFailure ಪಡೆಯುತ್ತೀರಿ ಎಂದು ಖಚಿತಪಡಿಸಿ." },

  // ── Module 253, Lesson 2: Structured Output (Part 2) ──
  { phaseId, moduleId: m253, lessonId: l253_2, order: 1, difficulty: 'intermediate',
    title: 'Unconstrained vs Constrained Decoding, Genuinely Compared',
    titleKn: 'Unconstrained vs Constrained Decoding, ನಿಜವಾಗಿ ಹೋಲಿಸಲಾಗಿದೆ',
    problem: "The lesson's simulation genuinely showed unconstrained_choice picking '\"not sure\"' (score 2.6, the highest overall) even though it's NOT a legal enum value, while constrained_choice masked illegal candidates to -inf and correctly picked 'pending' (score 2.4, the highest among LEGAL options).\n1. Run both the lesson's exact unconstrained_choice and constrained_choice on the same candidates list and confirm these two different outcomes.\n2. Why does simply picking the 'highest score' without constraints risk selecting an illegal value, and how does masking with float('-inf') fix this while preserving the relative ranking of the LEGAL candidates?\n3. The lesson ran 5 shuffled trials and found constrained_choice ALWAYS picked a legal value ('all legal: True'). Run this robustness check yourself with a 6th shuffle and confirm the same.",
    problemKn: "ಪಾಠದ simulation ನಿಜವಾಗಿ ತೋರಿಸಿತು unconstrained_choice ಒಂದೂ ಅಕ್ರಮ enum ಮೌಲ್ಯ ಆಯ್ಕೆ ಮಾಡಿತು, ಆದರೆ constrained_choice ಅಕ್ರಮ candidates ಅನ್ನೂ ಮಾಸ್ಕ್ ಮಾಡಿ ಸರಿಯಾಗಿ 'pending' ಆಯ್ಕೆ ಮಾಡಿತು.\n1. ಪಾಠದ ಎರಡೂ ನಿಖರ ಫಂಕ್ಷನ್ಸ್ ಒಂದೇ candidates list ಮೇಲೆ ಚಲಾಯಿಸಿ ಮತ್ತು ಈ ಎರಡೂ ವಿಭಿನ್ನ ಫಲಿತಾಂಶಗಳನ್ನೂ ಖಚಿತಪಡಿಸಿ.\n2. ನಿರ್ಬಂಧಗಳಿಲ್ಲದೆ 'ಅತ್ಯುನ್ನತ ಸ್ಕೋರ್' ಆಯ್ಕೆ ಮಾಡುವುದೂ ಅಕ್ರಮ ಮೌಲ್ಯ ಆಯ್ಕೆ ಮಾಡುವ ಅಪಾಯ ಏಕೆ ಹೊಂದಿದೆ?\n3. ಪಾಠ 5 ಶಫಲ್ ಮಾಡಿದ trials ಚಲಾಯಿಸಿ constrained_choice ಯಾವಾಗಲೂ ಒಂದೂ ಕಾನೂನುಬದ್ಧ ಮೌಲ್ಯ ಆಯ್ಕೆ ಮಾಡಿತು ಎಂದು ಕಂಡುಕೊಂಡಿತು. 6ನೇ shuffle ಜೊತೆ ಈ robustness check ನೀವೇ ಚಲಾಯಿಸಿ." },
  { phaseId, moduleId: m253, lessonId: l253_2, order: 2, difficulty: 'beginner',
    title: 'Pydantic and Zod as Typed Layers',
    titleKn: 'Typed Layers ಆಗಿ Pydantic ಮತ್ತು Zod',
    problem: "1. Based on the lesson's discussion, explain what it means for Pydantic (Python) and Zod (TypeScript) to be 'typed layers over the same schema' -- how do they relate to the JSON Schema concepts from Module 253 Part 1?\n2. If you defined the lesson's INVOICE_SCHEMA as a Pydantic BaseModel instead of a raw dict, what would you gain in terms of catching errors, compared to using parse_and_validate with the raw JSON Schema dict?\n3. Would Pydantic validation catch the SAME bool/int gotcha the lesson demonstrated (True being rejected for an 'int' field)? Reason through this based on how Python's type system and Pydantic's validators typically handle bool vs int.",
    problemKn: "1. ಪಾಠದ ಚರ್ಚೆ ಆಧರಿಸಿ, Pydantic (Python) ಮತ್ತು Zod (TypeScript) ಒಂದೇ schema ಮೇಲೆ 'typed layers' ಆಗಿರುವುದೂ ಎಂದರೇನೂ ಎಂದು ವಿವರಿಸಿ.\n2. INVOICE_SCHEMA ಅನ್ನೂ raw dict ಬದಲಿಗೆ ಒಂದೂ Pydantic BaseModel ಆಗಿ ವ್ಯಾಖ್ಯಾನಿಸಿದರೆ, ದೋಷಗಳನ್ನೂ ಹಿಡಿಯುವ ವಿಷಯದಲ್ಲಿ ಏನೂ ಪಡೆಯುತ್ತೀರಿ?\n3. Pydantic validation ಪಾಠ ಪ್ರದರ್ಶಿಸಿದ ಅದೇ bool/int gotcha ಹಿಡಿಯುತ್ತದೆಯೇ? Python ya type system ಮತ್ತು Pydantic ya validators ಸಾಮಾನ್ಯವಾಗಿ bool vs int ಹೇಗೂ ನಿರ್ವಹಿಸುತ್ತವೆ ಎಂಬುದರ ಆಧಾರದ ಮೇಲೆ ಯೋಚಿಸಿ." },
  { phaseId, moduleId: m253, lessonId: l253_2, order: 3, difficulty: 'intermediate',
    title: 'Extending Constrained Decoding to a New Enum',
    titleKn: 'Constrained Decoding ಅನ್ನೂ ಒಂದೂ ಹೊಸ Enum ಗೆ ವಿಸ್ತರಿಸುವುದೂ',
    problem: "1. Define your own legal_set of 4 string values (different from the lesson's {'pending','paid','cancelled'}) representing some other real-world categorical field (e.g. shipping status: 'processing','shipped','delivered','returned').\n2. Create a candidates_with_scores list of 6 candidates where at least 2 are illegal (not in your legal_set) and at least one illegal candidate has a HIGHER score than any legal one (mirroring the lesson's setup where '\"not sure\"' outscored everything legal).\n3. Run both unconstrained_choice and constrained_choice on your data and confirm constrained_choice correctly avoids the illegal high-scorer, just as the lesson's version did.",
    problemKn: "1. ಪಾಠದ {'pending','paid','cancelled'} ಇಂದ ಭಿನ್ನವಾದ ಒಂದೂ ವಿಭಿನ್ನ ನಿಜ-ಜಗತ್ತಿನ categorical field ಪ್ರತಿನಿಧಿಸುವ 4 string ಮೌಲ್ಯಗಳ ನಿಮ್ಮ ಸ್ವಂತ legal_set ವ್ಯಾಖ್ಯಾನಿಸಿ.\n2. ಕನಿಷ್ಠ 2 ಅಕ್ರಮ ಮತ್ತು ಕನಿಷ್ಠ ಒಂದೂ ಅಕ್ರಮ candidate ಯಾವುದೇ ಕಾನೂನುಬದ್ಧ candidate ಗಿಂತ ಹೆಚ್ಚಿನ ಸ್ಕೋರ್ ಹೊಂದಿರುವ 6 candidates ya candidates_with_scores list ರಚಿಸಿ.\n3. ನಿಮ್ಮ ಡೇಟಾ ಮೇಲೆ unconstrained_choice ಮತ್ತು constrained_choice ಎರಡನ್ನೂ ಚಲಾಯಿಸಿ ಮತ್ತು constrained_choice ಸರಿಯಾಗಿ ಅಕ್ರಮ ಹೆಚ್ಚಿನ-ಸ್ಕೋರರ್ ತಪ್ಪಿಸುತ್ತದೆ ಎಂದು ಖಚಿತಪಡಿಸಿ." },

  // ── Module 253, Lesson 3: Structured Output (Part 3) ──
  { phaseId, moduleId: m253, lessonId: l253_3, order: 1, difficulty: 'intermediate',
    title: 'All Four Outcomes in One Program',
    titleKn: 'ಒಂದೂ Program ನಲ್ಲಿ ಎಲ್ಲಾ ನಾಲ್ಕೂ ಫಲಿತಾಂಶಗಳು',
    problem: "The lesson's process_model_response genuinely handled all 4 outcomes (valid output, parse failure, schema failure, refusal) in one program, each producing its own correctly-typed result.\n1. Run the lesson's exact code covering all 4 cases and confirm each produces the right outcome type (SUCCESS, PARSE ERROR, SCHEMA VIOLATION, and the refusal case).\n2. Look at process_model_response's implementation: refusal is checked FIRST, before content is even inspected. Why does refusal need to take priority over parsing -- what would go wrong if the function tried to json.loads() a refusal message?\n3. Add a 5th case: content=None AND refusal=None (neither provided). Run it through process_model_response and report what happens, based on the lesson's exact implementation.",
    problemKn: "ಪಾಠದ process_model_response ನಿಜವಾಗಿ ಎಲ್ಲಾ 4 ಫಲಿತಾಂಶಗಳನ್ನೂ (valid, parse failure, schema failure, refusal) ಒಂದೂ program ನಲ್ಲಿ ನಿರ್ವಹಿಸಿತು.\n1. ಪಾಠದ ನಿಖರ code ಎಲ್ಲಾ 4 ಪ್ರಕರಣಗಳನ್ನೂ ಒಳಗೊಂಡಂತೆ ಚಲಾಯಿಸಿ ಮತ್ತು ಪ್ರತಿಯೊಂದೂ ಸರಿಯಾದ ಫಲಿತಾಂಶ ಪ್ರಕಾರ ಉತ್ಪಾದಿಸುತ್ತದೆ ಎಂದು ಖಚಿತಪಡಿಸಿ.\n2. process_model_response ya implementation ನೋಡಿ: refusal ಅನ್ನೂ ಮೊದಲು ಪರಿಶೀಲಿಸಲಾಗುತ್ತದೆ. refusal parsing ಗಿಂತ ಏಕೆ ಆದ್ಯತೆ ಪಡೆಯಬೇಕು?\n3. 5ನೇ ಪ್ರಕರಣ ಸೇರಿಸಿ: content=None ಮತ್ತು refusal=None (ಎರಡೂ ಇಲ್ಲ). process_model_response ಮೂಲಕ ಚಲಾಯಿಸಿ ಮತ್ತು ಏನಾಗುತ್ತದೆ ಎಂದು ವರದಿ ಮಾಡಿ." },
  { phaseId, moduleId: m253, lessonId: l253_3, order: 2, difficulty: 'intermediate',
    title: 'Building and Confirming a Real Repair Prompt',
    titleKn: 'ಒಂದೂ ನಿಜ Repair Prompt ನಿರ್ಮಿಸುವುದೂ ಮತ್ತು ಖಚಿತಪಡಿಸುವುದೂ',
    problem: "The lesson's build_repair_prompt genuinely turned a SchemaFailure's 3 errors into a human-readable repair prompt ('Your previous output violated the schema: ... Return a corrected object.'), and then genuinely confirmed a corrected input passes validation (SUCCESS).\n1. Run the lesson's exact build_repair_prompt and the follow-up repaired-input validation. Confirm the repair prompt text and that the repaired JSON now returns SUCCESS.\n2. Why does the repair prompt include the SPECIFIC error paths and messages (e.g. '$.total_usd: value must be >= 0') rather than just saying 'your output was invalid, try again'?\n3. Design your own typed-retry loop: pseudocode a function that calls the model, validates the result, and if it's a SchemaFailure, builds a repair prompt and retries ONCE more before giving up. What should happen if the retry ALSO fails validation?",
    problemKn: "ಪಾಠದ build_repair_prompt ಒಂದೂ SchemaFailure ya 3 ದೋಷಗಳನ್ನೂ ಒಂದೂ ಓದಬಹುದಾದ repair prompt ಆಗಿ ನಿಜವಾಗಿ ಪರಿವರ್ತಿಸಿತು, ನಂತರ ಒಂದೂ ಸರಿಪಡಿಸಿದ input ಮೌಲ್ಯೀಕರಣ ಪಾಸ್ ಆಗುತ್ತದೆ ಎಂದು ನಿಜವಾಗಿ ಖಚಿತಪಡಿಸಿತು.\n1. ಪಾಠದ ನಿಖರ build_repair_prompt ಮತ್ತು ಅನುಸರಣ ಪರಿಶೀಲನೆ ಚಲಾಯಿಸಿ.\n2. repair prompt ನಿರ್ದಿಷ್ಟ error paths ಮತ್ತು messages ಒಳಗೊಂಡಿರುವುದೂ ಏಕೆ, ಕೇವಲ 'ನಿಮ್ಮ output ಅಮಾನ್ಯವಾಗಿತ್ತು' ಎಂದು ಹೇಳುವ ಬದಲಿಗೆ?\n3. ನಿಮ್ಮ ಸ್ವಂತ typed-retry loop ವಿನ್ಯಾಸಗೊಳಿಸಿ: model ಕರೆ ಮಾಡುವ, ಫಲಿತಾಂಶ ಮೌಲ್ಯೀಕರಿಸುವ, ಮತ್ತು SchemaFailure ಆಗಿದ್ದರೆ repair prompt ನಿರ್ಮಿಸಿ ಒಮ್ಮೆ ಮರುಪ್ರಯತ್ನಿಸುವ ಒಂದೂ function ya pseudocode ಬರೆಯಿರಿ." },
  { phaseId, moduleId: m253, lessonId: l253_3, order: 3, difficulty: 'advanced',
    title: 'Why Refusals Should Not Enter the Blind Retry Loop',
    titleKn: 'Refusals ಏಕೆ Blind Retry Loop ಪ್ರವೇಶಿಸಬಾರದು',
    problem: "1. Based on the lesson's discussion and the design of process_model_response (which checks refusal BEFORE parsing), explain why a Refusal outcome should NOT trigger the same repair-and-retry loop that a SchemaFailure does.\n2. If your typed-retry loop from the previous exercise treated a Refusal exactly like a SchemaFailure (building a 'repair prompt' and retrying), what bad outcome could result when the model refuses for a genuine safety reason?\n3. Summarize, in your own words, how all three parts of Module 253 connect: Part 1's outcome types, Part 2's constrained decoding, and Part 3's repair loop that excludes refusals. What's the single overarching lesson about handling structured output reliably in production?",
    problemKn: "1. process_model_response ya ವಿನ್ಯಾಸ (parsing ಗಿಂತ ಮೊದಲು refusal ಪರಿಶೀಲಿಸುವುದೂ) ಆಧರಿಸಿ, ಒಂದೂ Refusal ಫಲಿತಾಂಶ SchemaFailure ಮಾಡುವ ಅದೇ repair-and-retry loop ಅನ್ನೂ ಏಕೆ ಪ್ರಚೋದಿಸಬಾರದು ಎಂದು ವಿವರಿಸಿ.\n2. ನಿಮ್ಮ typed-retry loop Refusal ಅನ್ನೂ SchemaFailure ಯಂತೆ ನಿಖರವಾಗಿ ಪರಿಗಣಿಸಿದರೆ, model ಒಂದೂ ನಿಜ ಸುರಕ್ಷತೆಯ ಕಾರಣಕ್ಕಾಗಿ ನಿರಾಕರಿಸಿದಾಗ ಯಾವ ಕೆಟ್ಟ ಫಲಿತಾಂಶ ಉಂಟಾಗಬಹುದು?\n3. Module 253 ya ಎಲ್ಲಾ ಮೂರೂ ಭಾಗಗಳು ಹೇಗೂ ಸಂಪರ್ಕಿಸುತ್ತವೆ ಎಂದು ನಿಮ್ಮ ಸ್ವಂತ ಪದಗಳಲ್ಲಿ ಸಾರಾಂಶ ಮಾಡಿ. production ನಲ್ಲಿ structured output ವಿಶ್ವಾಸಾರ್ಹವಾಗಿ ನಿರ್ವಹಿಸುವ ಬಗ್ಗೆ ಒಂದೂ ಒಟ್ಟಾರೆ ಪಾಠ ಏನೂ?" },
];
