const phaseId = '6a369d5666020ed05b321334'; // Phase 9

const m130 = '6a369d5666020ed05b321349'; // Module 130: Text-to-Speech (TTS)
const m131 = '6a369d5666020ed05b32134c'; // Module 131: Voice Cloning and Voice Conversion

const l130_1 = '6a6cf9cf52383d0415caf32f'; // TTS Fundamentals — From Tacotron to F5 and Kokoro
const l130_2 = '6a6cfdef0c12e5023dc18ca2'; // TTS — Voice Cloning, HiFi-GAN & Production Pipelines
const l131_1 = '6a6ddb6ba385cb0a395fc93b'; // Voice Cloning & Voice Conversion — Fundamentals
const l131_2 = '6a6dddd412d311d5d9c0adee'; // Voice Cloning & Voice Conversion — Conversion, Watermarking & Production

module.exports = [
  // ── Module 130, Lesson 1: TTS Fundamentals ──
  { phaseId, moduleId: m130, lessonId: l130_1, order: 1, difficulty: 'beginner',
    title: 'The Three-Stage TTS Pipeline',
    problem: "The lesson describes a three-stage pipeline: text -> phonemes -> acoustic features (mel) -> waveform.\n1. Write a one-sentence description of what each of the three stages transforms and produces.\n2. Which stage is responsible for pronunciation (e.g. correctly reading '2026' as 'twenty twenty-six')?\n3. Which stage is where a 'vocoder' operates? Why can't you skip straight from phonemes to waveform without the intermediate mel representation, given what you learned about the mel scale in Module 125?" },
  { phaseId, moduleId: m130, lessonId: l130_1, order: 2, difficulty: 'intermediate',
    title: 'Attempting Phonemization',
    problem: "Attempt phonemize('Hello world', language='en-us', backend='espeak') from the phonemizer library.\n1. Does this succeed in your environment? The phonemizer library's espeak backend depends on the espeak-ng system binary being installed -- check whether that's present.\n2. If it fails, document the exact error. Is it a Python import error, or a runtime error about a missing system dependency?\n3. If it succeeds, print the phonemized output. How does it represent 'Hello world' -- as IPA symbols, or some other phonetic alphabet?\n4. Try phonemizing a word with irregular English spelling, like 'though' or 'colonel'. Does the phonemizer correctly capture the actual pronunciation despite the unusual spelling?" },
  { phaseId, moduleId: m130, lessonId: l130_1, order: 3, difficulty: 'advanced',
    title: 'Attempting Kokoro TTS Inference',
    problem: "Attempt the lesson's Kokoro example: from kokoro import KPipeline; tts = KPipeline(lang_code='a'); audio, sr = tts('Please remind me to water the plants at 6 pm.', voice='af_bella').\n1. Does `pip install kokoro` (or the correct package name for your environment) succeed? Document the exact outcome.\n2. If installation fails, what's the root cause (a missing native dependency, a Cython compile error, something else)? Compare it against any similar dependency-resolution failures you've read about elsewhere in this course.\n3. If it succeeds, report the audio array's shape and the sample rate returned. Does sr match the 24000 the lesson states?" },
  { phaseId, moduleId: m130, lessonId: l130_1, order: 4, difficulty: 'intermediate',
    title: 'The Evolution of TTS Models',
    problem: "The lesson traces TTS evolution from Tacotron through to F5-TTS and Kokoro.\n1. List the models in the order the lesson presents them, and for each, note in one phrase what its key innovation was over the previous generation.\n2. Older models (like Tacotron) typically required a separately-trained vocoder stage; some newer approaches integrate more of the pipeline end to end. What's one advantage and one disadvantage of an end-to-end approach compared to a modular pipeline (text -> phonemes -> mel -> vocoder as separate trained pieces)?\n3. Why does a fast-moving field like TTS make 'the current state of the art' a moving target -- what does that imply about how you should treat any specific model name mentioned in a lesson written at a specific point in time?" },
  { phaseId, moduleId: m130, lessonId: l130_1, order: 5, difficulty: 'beginner',
    title: 'TTS Evaluation Metrics',
    problem: "The lesson covers evaluation metrics for TTS quality.\n1. Name at least two metrics used to judge synthesized speech (e.g. one objective/automated, one subjective/human-rated).\n2. Why can't word error rate (WER) alone -- running the synthesized audio back through an ASR system -- fully judge TTS quality? What aspect of speech does WER completely miss?\n3. Mean Opinion Score (MOS) involves human listeners rating audio naturalness. What's a practical downside of relying on MOS as your primary evaluation metric during rapid model iteration?" },

  // ── Module 130, Lesson 2: TTS — Voice Cloning, HiFi-GAN & Production Pipelines ──
  { phaseId, moduleId: m130, lessonId: l130_2, order: 1, difficulty: 'advanced',
    title: 'Attempting F5-TTS Zero-Shot Cloning',
    problem: "Attempt f5_tts_clone.py: from f5_tts.api import F5TTS; tts = F5TTS(); wav = tts.infer(ref_file='my_voice_5s.wav', ref_text='The quick brown fox jumps over the lazy dog.', gen_text='Please remind me to water the plants.').\n1. Since you likely don't have 'my_voice_5s.wav', substitute a real synthetic 5-second WAV (matching the pattern established elsewhere in this course). Document that substitution honestly.\n2. Does the model download and load successfully? How long does it take, and does it complete within a reasonable session time budget on your hardware?\n3. If inference genuinely starts but doesn't finish (a known, previously-documented finding for F5-TTS on CPU-only hardware in this course), report exactly how far it got before you had to stop it, rather than claiming it completed if it didn't." },
  { phaseId, moduleId: m130, lessonId: l130_2, order: 2, difficulty: 'intermediate',
    title: 'HiFi-GAN Vocoder Shape Reasoning',
    problem: "The lesson's HiFiGAN stub uses upsample_rates=[8, 8, 2, 2], stated to total 256x upsampling from mel-rate to audio-rate.\n1. Verify that 8*8*2*2 = 256.\n2. If a mel spectrogram has 100 time frames, what length waveform (in samples) would a 256x upsampling vocoder produce?\n3. If the target audio sample rate is 24000Hz, what mel frame rate (frames per second) does this 256x upsampling factor imply? Does that match a hop_length of roughly 24000/mel_frame_rate samples?\n4. Why must the vocoder's total upsampling factor exactly match the ratio between the audio sample rate and the mel spectrogram's frame rate -- what would go wrong (in terms of output audio duration or pitch) if it didn't?" },
  { phaseId, moduleId: m130, lessonId: l130_2, order: 3, difficulty: 'intermediate',
    title: 'Neural Codec Vocoders vs. HiFi-GAN',
    problem: "The lesson contrasts traditional GAN-based vocoders (HiFi-GAN) with neural codec vocoders (referencing the EnCodec-style codec family covered in Module 132/136).\n1. In one sentence, describe what a GAN-based vocoder like HiFi-GAN takes as input and outputs.\n2. In one sentence, describe how a neural codec vocoder differs -- what discrete representation does it decode from?\n3. Given what you learned about RVQ (Residual Vector Quantization) in Module 132, why might a codec-based vocoder be easier to combine with a language-model-style generative approach than a continuous-mel-to-waveform GAN?" },
  { phaseId, moduleId: m130, lessonId: l130_2, order: 4, difficulty: 'beginner',
    title: 'Assembling the Full TTS Pipeline Pseudocode',
    problem: "The lesson's full_pipeline_pseudocode.py chains: phonemize(text) -> acoustic_model(phones, speaker=alice) -> vocoder(mel) -> soundfile.write().\n1. For each of the four steps, identify which Module 130 concept it corresponds to (phonemization, acoustic model, vocoder, file I/O).\n2. The acoustic_model() call takes a speaker= argument. What does varying this argument let you do without retraining the whole pipeline, given what Module 131 covers about speaker embeddings?\n3. If you wanted to add emotional tone control (e.g. 'say this happily') to this pipeline, at which stage would you most naturally inject that control signal, and why?" },
  { phaseId, moduleId: m130, lessonId: l130_2, order: 5, difficulty: 'advanced',
    title: 'Comparing Kokoro vs. F5-TTS Deployment Tradeoffs',
    problem: "Based on your genuine install/inference attempts for both Kokoro (Lesson 1) and F5-TTS (this lesson):\n1. Summarize which one was actually usable in your environment, and which had genuine blockers (missing dependency, install failure, inference timeout).\n2. F5-TTS supports zero-shot voice cloning from a reference clip; Kokoro (as covered in this course) does not clone arbitrary voices, only using its built-in voice presets. For a product that needs to let end users clone their own voice, which model is architecturally suited to the task regardless of your local install success?\n3. Write a short honest 'production readiness' note for each model based only on what you genuinely observed in your own testing, not on marketing claims." },

  // ── Module 131, Lesson 1: Voice Cloning & Voice Conversion — Fundamentals ──
  { phaseId, moduleId: m131, lessonId: l131_1, order: 1, difficulty: 'beginner',
    title: 'Cloning vs. Conversion: Input/Output Mapping',
    problem: "1. For voice cloning, what are the two inputs and the one output? For voice conversion, what are the two inputs and the one output?\n2. In cloning, which of {content, speaker} is fixed and which is free to vary? Answer the same question for conversion.\n3. Give one real product example for cloning and one for conversion, and explain in one sentence why each is the right tool for that use case." },
  { phaseId, moduleId: m131, lessonId: l131_1, order: 2, difficulty: 'intermediate',
    title: 'The Content/Speaker/Prosody Decomposition',
    problem: "The lesson decomposes every voice cloning/conversion system into content, speaker, and prosody.\n1. Take a sentence you know well and describe, in your own words, what would change (and what would stay the same) if you altered only its prosody (e.g. said it as a question instead of a statement) while keeping content and speaker fixed.\n2. Using your embed_mfcc_stats() function from Module 129, extract a 'speaker' embedding from two clips of the same synthetic tone spoken at different simulated pitches/rates (vary the sine frequency and duration). Does the embedding change more with speaker-like variation or content-like variation, given that it was designed to capture speaker characteristics?\n3. Why is this three-way decomposition useful even though no real system perfectly separates the three factors in practice?" },
  { phaseId, moduleId: m131, lessonId: l131_1, order: 3, difficulty: 'intermediate',
    title: 'Zero-Shot vs. Few-Shot Cloning Data Requirements',
    problem: "1. According to the lesson, roughly how much reference audio does zero-shot cloning need, versus few-shot cloning?\n2. If a company has 50,000 users and wants each to be able to clone their own voice from a short recording, would zero-shot or few-shot be more practical to offer as a self-serve feature? Justify your answer in terms of user friction.\n3. If a company is building one flagship narrator voice for their product (e.g. an audiobook narrator) and has access to hours of clean studio recordings from one voice actor, would few-shot fine-tuning give a meaningfully better result than zero-shot, and why?" },
  { phaseId, moduleId: m131, lessonId: l131_1, order: 4, difficulty: 'advanced',
    title: 'Recognition-Synthesis vs. Disentanglement Architectures',
    problem: "The lesson contrasts two major voice conversion architecture families.\n1. In your own words, describe the two-stage flow of a recognition-synthesis system (like KNN-VC): what is extracted first, and what happens second?\n2. In your own words, describe how a disentanglement-based system (like AutoVC) differs -- what does it NOT have that recognition-synthesis systems do have?\n3. Which of the two would you expect to be easier to debug when the output sounds wrong (e.g. content is garbled) -- one where you can inspect an explicit intermediate content representation, or one where everything is entangled in a single latent space? Justify your answer." },
  { phaseId, moduleId: m131, lessonId: l131_1, order: 5, difficulty: 'beginner',
    title: 'Neural Codec-Based Cloning: Audio as Tokens',
    problem: "The lesson describes VALL-E-style systems that represent audio as discrete codec tokens rather than continuous mel spectrograms.\n1. In one sentence, describe the full pipeline: audio -> ? -> ? -> generative model -> ? -> ? -> waveform.\n2. Why does representing audio as discrete tokens make voice cloning look architecturally similar to how text-based LLMs generate text (referencing what you know about next-token prediction)?\n3. This same discrete-token idea reappears in Module 132 for music generation. Name the codec-based pattern shared between the two domains in one sentence." },

  // ── Module 131, Lesson 2: Voice Cloning & Voice Conversion — Conversion, Watermarking & Production ──
  { phaseId, moduleId: m131, lessonId: l131_2, order: 1, difficulty: 'advanced',
    title: 'Attempting KNN-VC Voice Conversion',
    problem: "Attempt the lesson's KNNVC.load('wavlm-base-plus') and vc.convert(source=..., target_pool=[...]).\n1. Since real audio files aren't available, substitute real synthetic WAVs for source and target_pool, documenting the substitution honestly.\n2. Does the model load successfully? Report the outcome exactly, including any errors.\n3. KNN-VC works by retrieval (finding the nearest WavLM features in the target pool) rather than a trained decoder. Why might this make it easier to add a brand-new target speaker (just add their clips to target_pool) compared to a system that requires retraining or fine-tuning per speaker?" },
  { phaseId, moduleId: m131, lessonId: l131_2, order: 2, difficulty: 'intermediate',
    title: 'Measuring Voice Similarity With SECS',
    problem: "Using secs_cosine.py's pattern: target_emb = [0.5, 0.2, -0.1, 0.8], generated_emb_close = [0.48, 0.22, -0.09, 0.79], generated_emb_far = [-0.3, 0.9, 0.4, -0.6].\n1. Compute cosine(target_emb, generated_emb_close) and cosine(target_emb, generated_emb_far). Confirm the close embedding scores much higher.\n2. SECS (Speaker Embedding Cosine Similarity) is a standard voice-cloning evaluation metric. What real speaker-embedding model would you use in practice to generate the embeddings being compared, instead of these hand-picked toy vectors?\n3. If two different cloning systems report SECS of 0.85 and 0.72 respectively for the same target voice, is that comparison meaningful on its own, or does it depend on both systems using the exact same speaker embedding model to compute SECS? Explain why." },
  { phaseId, moduleId: m131, lessonId: l131_2, order: 3, difficulty: 'advanced',
    title: 'A Real Watermarking Stand-In and Bit Manipulation',
    problem: "Using watermark_standin.py's embed_watermark(int16_samples, payload_bits) / detect_watermark(int16_samples, n_bits):\n1. Create a toy int16 sample array (e.g. 32 samples of value 1000), embed an 8-bit payload like [1,0,1,1,0,0,1,0], and detect it back. Do you recover the exact same bits?\n2. Print the samples before and after embedding. How much does each sample's value change (in absolute terms) due to the least-significant-bit modification?\n3. This is a real, working least-significant-bit watermark, but it's fragile. If you multiply every sample by 1.01 (simulating light audio processing/re-encoding) before detecting, does the watermark survive? What does this tell you about why production watermarking (like SilentCipher, referenced in the lesson) needs to be far more robust than simple LSB embedding?" },
  { phaseId, moduleId: m131, lessonId: l131_2, order: 4, difficulty: 'intermediate',
    title: 'Building and Verifying a Consent Record',
    problem: "Using consent_gate.py's hash_speaker() and sign_consent():\n1. Create a toy consent record dict with id, speaker_id, and purpose fields, and sign it with sign_consent().\n2. Verify that re-computing the HMAC signature for the same record produces the identical signature (a legitimate verification check).\n3. Now tamper with one field (change purpose) and recompute the HMAC. Does the signature change? Why does this make the consent record tamper-evident?\n4. Why is HMAC (a keyed hash) used here instead of a plain hash like SHA-256 alone -- what could an attacker do with a plain hash that they can't do with HMAC, given they don't know SECRET_KEY?" },
  { phaseId, moduleId: m131, lessonId: l131_2, order: 5, difficulty: 'beginner',
    title: 'The Full Responsible Voice Cloning Pipeline',
    problem: "The lesson describes a production pipeline: consent verification -> generation -> watermarking -> deepfake detection as an additional safety layer.\n1. Draw (or describe in words) the order these four stages run in, and explain why consent verification must come *before* generation, not after.\n2. If deepfake detection is a separate, independent safety layer from watermarking, what failure mode does each protect against that the other doesn't (hint: watermarking traces content *your own system* generated; deepfake detection can flag content from *anywhere*)?\n3. Reusing your hash_speaker()/sign_consent() and watermark_standin.py functions, sketch (in comments or pseudocode) a single function process_cloning_request(ref_audio, text, consent_record) that checks consent, calls a (stub) generation function, and embeds a watermark -- rejecting the request early if consent verification fails." },
];
