const phaseId = '6a369d5666020ed05b321334'; // Phase 9

const m136 = '6a369d5766020ed05b32135b'; // Module 136: Neural Audio Codecs
const m137 = '6a369d5766020ed05b32135e'; // Module 137: Voice Activity Detection and Turn-Taking
const m138 = '6a369d5766020ed05b321361'; // Module 138: Streaming Speech-to-Speech
const m139 = '6a369d5766020ed05b321364'; // Module 139: Voice Anti-Spoofing and Audio Watermarking
const m140 = '6a369d5766020ed05b321367'; // Module 140: Audio Evaluation

const l136_1 = '6a73417b7cf55e2f41b58985'; // Neural Audio Codecs Part 1
const l136_2 = '6a734602441894003c13939e'; // Neural Audio Codecs Part 2
const l137_1 = '6a734783170ece1f14ffa643'; // VAD & Turn-Taking Part 1
const l137_2 = '6a7349e76296605a7d736f95'; // VAD & Turn-Taking Part 2
const l138_1 = '6a734b1cc5a658739d37d696'; // Streaming Speech-to-Speech Part 1
const l138_2 = '6a734c0ebf8d9fa3abbb8c4f'; // Streaming Speech-to-Speech Part 2
const l139_1 = '6a734d74342527d022e564a1'; // Voice Anti-Spoofing & Watermarking Part 1
const l139_2 = '6a734eccbbaad01a3e201209'; // Voice Anti-Spoofing & Watermarking Part 2
const l140_1 = '6a734fde3e9efab069dd45c3'; // Audio Evaluation Part 1
const l140_2 = '6a73513a771456e566a4536a'; // Audio Evaluation Part 2

module.exports = [
  // ── Module 136, Lesson 1: EnCodec, SNAC, Mimi, DAC and the Semantic-Acoustic Split ──
  { phaseId, moduleId: m136, lessonId: l136_1, order: 1, difficulty: 'beginner',
    title: 'Genuinely Running EnCodec Encode-Decode Round Trip',
    titleKn: 'EnCodec Encode-Decode Round Trip ಅನ್ನೂ ನಿಜವಾಗಿ ಚಲಾಯಿಸುವುದೂ',
    problem: "Install and genuinely run an EnCodec model (e.g. via the `transformers` EncodecModel or the original `encodec` package) on a short real or synthetic WAV file.\n1. Encode the audio to discrete codes and print the shape of the resulting code tensor (num_codebooks x sequence_length).\n2. Decode those codes back to audio and measure the reconstructed audio's length against the original -- do they match sample-for-sample, or is there a small discrepancy from framing?\n3. Compute the file size of the raw WAV versus the size needed to store just the discrete codes (num_codebooks * sequence_length * bits_per_code / 8 bytes). Report the genuine compression ratio you measured, not an assumed one.",
    problemKn: "ಒಂದು EnCodec model ಅನ್ನೂ install ಮಾಡಿ ಮತ್ತು ಒಂದು ಚಿಕ್ಕ ನಿಜ ಅಥವಾ synthetic WAV file ಮೇಲೆ ನಿಜವಾಗಿ ಚಲಾಯಿಸಿ.\n1. audio ಅನ್ನೂ discrete codes ಗೆ encode ಮಾಡಿ ಮತ್ತು ಫಲಿತಾಂಶ code tensor ya shape ಪ್ರಿಂಟ್ ಮಾಡಿ.\n2. ಆ codes ಅನ್ನೂ ಮತ್ತೆ audio ಗೆ decode ಮಾಡಿ ಮತ್ತು reconstructed audio ya length ಅನ್ನೂ ಮೂಲದ ವಿರುದ್ಧ ಅಳೆಯಿರಿ -- ಅವು sample-for-sample ಹೊಂದಿಕೆಯಾಗುತ್ತವೆಯೇ, ಅಥವಾ framing ಇಂದ ಒಂದು ಚಿಕ್ಕ ವ್ಯತ್ಯಾಸ ಇದೆಯೇ?\n3. ಕಚ್ಚಾ WAV ya file size ಅನ್ನೂ ಕೇವಲ discrete codes ಸಂಗ್ರಹಿಸಲು ಬೇಕಾದ size ಜೊತೆ ಹೋಲಿಸಿ. ನೀವು ನಿಜವಾಗಿ ಅಳೆದ compression ratio ವರದಿ ಮಾಡಿ, ಊಹಿಸಿದ ಒಂದನ್ನೂ ಅಲ್ಲ." },
  { phaseId, moduleId: m136, lessonId: l136_1, order: 2, difficulty: 'intermediate',
    title: 'Measuring the Semantic-Acoustic Split Across Codebooks',
    titleKn: 'Codebooks ಗಳಾದ್ಯಂತ Semantic-Acoustic Split ಅಳೆಯುವುದೂ',
    problem: "Neural codecs like SNAC and Mimi split their codebooks so early codebooks carry more semantic (phonetic/linguistic) content while later ones carry acoustic (fine timbre) detail.\n1. Using a multi-codebook codec of your choice, decode audio using ONLY the first codebook (zeroing or dropping the rest). Listen to or plot the result -- is speech content still roughly recognizable?\n2. Now decode using ONLY the last codebook (dropping the earlier ones). Does the result sound like meaningful speech, or more like texture/noise?\n3. Based on your two reconstructions, write a one-paragraph genuine assessment (not a textbook restatement) of what information is lost when you drop early vs. late codebooks, grounded in what you actually heard or measured.",
    problemKn: "SNAC ಮತ್ತು Mimi ನಂತಹ neural codecs ತಮ್ಮ codebooks ಅನ್ನೂ ವಿಭಜಿಸುತ್ತವೆ ಆದ್ದರಿಂದ ಮೊದಲಿನ codebooks ಹೆಚ್ಚು semantic content ಹೊಂದಿರುತ್ತವೆ ಆದರೆ ನಂತರದವು acoustic ವಿವರ ಹೊಂದಿರುತ್ತವೆ.\n1. ನಿಮ್ಮ ಆಯ್ಕೆಯ ಒಂದು multi-codebook codec ಬಳಸಿ, ಕೇವಲ ಮೊದಲ codebook ಬಳಸಿ audio decode ಮಾಡಿ. ಫಲಿತಾಂಶ ಆಲಿಸಿ ಅಥವಾ ಪ್ಲಾಟ್ ಮಾಡಿ -- speech content ಇನ್ನೂ ಸುಮಾರಾಗಿ ಗುರುತಿಸಬಹುದೇ?\n2. ಈಗ ಕೇವಲ ಕೊನೆಯ codebook ಬಳಸಿ decode ಮಾಡಿ. ಫಲಿತಾಂಶ ಅರ್ಥಪೂರ್ಣ speech ನಂತೆ ಧ್ವನಿಸುತ್ತದೆಯೇ, ಅಥವಾ texture/noise ನಂತೆ?\n3. ನಿಮ್ಮ ಎರಡು reconstructions ಆಧರಿಸಿ, ಮೊದಲಿನ vs ನಂತರದ codebooks ಬಿಟ್ಟಾಗ ಯಾವ ಮಾಹಿತಿ ಕಳೆದುಹೋಗುತ್ತದೆ ಎಂಬುದರ ಬಗ್ಗೆ ಒಂದು ನಿಜ ಮೌಲ್ಯಮಾಪನ ಬರೆಯಿರಿ, ನೀವು ನಿಜವಾಗಿ ಕೇಳಿದ/ಅಳೆದ ಆಧಾರದ ಮೇಲೆ." },
  { phaseId, moduleId: m136, lessonId: l136_1, order: 3, difficulty: 'advanced',
    title: 'Comparing Codec Bitrates: EnCodec vs. DAC',
    titleKn: 'Codec Bitrates ಹೋಲಿಸುವುದೂ: EnCodec vs. DAC',
    problem: "Genuinely load both an EnCodec model and a DAC (Descript Audio Codec) model at their lowest available bitrate settings.\n1. Encode-decode the same audio clip through both codecs. Measure and report a real objective difference metric (e.g. mean squared error between original and reconstructed waveforms, or a simple SNR calculation) for each.\n2. Report the actual bits-per-second each codec uses at its lowest setting (from the model's codebook count and codebook size).\n3. Based on your measurements, which codec gives a better reconstruction quality per bit spent, in your specific test clip? State the real numbers you found, not an assumption from documentation.",
    problemKn: "ಒಂದು EnCodec model ಮತ್ತು ಒಂದು DAC (Descript Audio Codec) model ಎರಡನ್ನೂ ಅವುಗಳ ಅತ್ಯಂತ ಕಡಿಮೆ bitrate settings ನಲ್ಲಿ ನಿಜವಾಗಿ load ಮಾಡಿ.\n1. ಅದೇ audio clip ಅನ್ನೂ ಎರಡೂ codecs ಮೂಲಕ encode-decode ಮಾಡಿ. ಪ್ರತಿಯೊಂದಕ್ಕೂ ಒಂದು ನಿಜ objective difference metric ಅಳೆಯಿರಿ ಮತ್ತು ವರದಿ ಮಾಡಿ.\n2. ಪ್ರತಿ codec ಅದರ ಕಡಿಮೆ setting ನಲ್ಲಿ ಬಳಸುವ ನಿಜ bits-per-second ವರದಿ ಮಾಡಿ.\n3. ನಿಮ್ಮ ಅಳತೆಗಳ ಆಧಾರದ ಮೇಲೆ, ನಿಮ್ಮ ನಿರ್ದಿಷ್ಟ test clip ನಲ್ಲಿ ಯಾವ codec ಪ್ರತಿ bit ಗೆ ಉತ್ತಮ reconstruction quality ನೀಡುತ್ತದೆ? documentation ಇಂದ ಒಂದು ಊಹೆ ಅಲ್ಲ, ನೀವು ಕಂಡುಕೊಂಡ ನಿಜ ಸಂಖ್ಯೆಗಳನ್ನೂ ಹೇಳಿ." },

  // ── Module 136, Lesson 2: Reconstruction, Token Economics & Codec Selection ──
  { phaseId, moduleId: m136, lessonId: l136_2, order: 1, difficulty: 'beginner',
    title: 'Genuinely Measuring Token Economics',
    titleKn: 'Token Economics ಅನ್ನೂ ನಿಜವಾಗಿ ಅಳೆಯುವುದೂ',
    problem: "For a codec of your choice (e.g. Mimi at its default frame rate), genuinely compute:\n1. How many audio tokens per second of audio does the codec produce (frame rate x number of codebooks)?\n2. For a 60-second audio clip, how many total tokens would an LLM need to process if that audio were fed in as tokens? Compute this as a real number, not a rough estimate.\n3. Compare this to how many text tokens a typical LLM tokenizer would use for the transcript of that same 60 seconds of speech (assume ~150 words per minute, ~1.3 tokens per word). Which representation is more token-expensive, and by what factor?",
    problemKn: "ನಿಮ್ಮ ಆಯ್ಕೆಯ ಒಂದು codec ಗೆ (ಉದಾ Mimi ಅದರ default frame rate ನಲ್ಲಿ), ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಿ:\n1. codec ಪ್ರತಿ ಸೆಕೆಂಡ್ audio ಗೆ ಎಷ್ಟು audio tokens ಉತ್ಪಾದಿಸುತ್ತದೆ?\n2. ಒಂದು 60-second audio clip ಗೆ, ಆ audio tokens ಆಗಿ ಫೀಡ್ ಮಾಡಿದರೆ ಒಂದು LLM ಒಟ್ಟು ಎಷ್ಟು tokens ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಬೇಕಾಗುತ್ತದೆ? ಇದನ್ನೂ ಒಂದು ನಿಜ ಸಂಖ್ಯೆಯಾಗಿ ಲೆಕ್ಕಹಾಕಿ.\n3. ಇದನ್ನೂ ಅದೇ 60 ಸೆಕೆಂಡುಗಳ speech ya transcript ಗೆ ಒಂದು ವಿಶಿಷ್ಟ LLM tokenizer ಬಳಸುವ text tokens ಜೊತೆ ಹೋಲಿಸಿ. ಯಾವ ಪ್ರಾತಿನಿಧ್ಯ ಹೆಚ್ಚು token-ದುಬಾರಿ, ಮತ್ತು ಎಷ್ಟು ಪಟ್ಟು?" },
  { phaseId, moduleId: m136, lessonId: l136_2, order: 2, difficulty: 'intermediate',
    title: 'A Codec Selection Decision Matrix',
    titleKn: 'ಒಂದು Codec Selection Decision Matrix',
    problem: "Build a genuine comparison table (not copied from the lesson) covering at least EnCodec, SNAC, Mimi, and DAC, with columns: typical frame rate, number of codebooks at default settings, and one documented real-world system that uses each codec.\n1. Fill in this table using primary sources (each codec's paper or official repo README) rather than secondhand summaries -- cite where each number came from.\n2. For a real-time voice assistant needing sub-300ms codec latency, which codec's frame rate makes it most suitable, and why does a lower frame rate (fewer frames/sec) not automatically mean lower latency (think about what else affects latency)?\n3. For a music-generation application prioritizing audio fidelity over token efficiency, which codec would you pick and why, based on your table?",
    problemKn: "EnCodec, SNAC, Mimi, ಮತ್ತು DAC ಒಳಗೊಂಡ ಒಂದು ನಿಜ ಹೋಲಿಕೆ table ನಿರ್ಮಿಸಿ, columns: typical frame rate, default settings ನಲ್ಲಿ codebooks ಸಂಖ್ಯೆ, ಮತ್ತು ಪ್ರತಿ codec ಬಳಸುವ ಒಂದು ದಾಖಲಿತ ನಿಜ-ಪ್ರಪಂಚ system.\n1. ಈ table ಅನ್ನೂ primary sources ಬಳಸಿ ತುಂಬಿಸಿ -- ಪ್ರತಿ ಸಂಖ್ಯೆ ಎಲ್ಲಿಂದ ಬಂತು ಎಂದು ಉಲ್ಲೇಖಿಸಿ.\n2. sub-300ms codec latency ಬೇಕಾದ ಒಂದು real-time voice assistant ಗೆ, ಯಾವ codec ya frame rate ಇದನ್ನೂ ಅತ್ಯಂತ ಸೂಕ್ತವಾಗಿಸುತ್ತದೆ, ಮತ್ತು ಒಂದು ಕಡಿಮೆ frame rate ಏಕೆ ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಕಡಿಮೆ latency ಅರ್ಥೈಸುವುದಿಲ್ಲ?\n3. token efficiency ಗಿಂತ audio fidelity ಆದ್ಯತೆ ನೀಡುವ ಒಂದು music-generation application ಗೆ, ನಿಮ್ಮ table ಆಧರಿಸಿ ಯಾವ codec ಆಯ್ಕೆ ಮಾಡುತ್ತೀರಿ ಮತ್ತು ಏಕೆ?" },
  { phaseId, moduleId: m136, lessonId: l136_2, order: 3, difficulty: 'advanced',
    title: 'Genuinely Testing Codec Robustness to Compression Artifacts',
    titleKn: 'Compression Artifacts ಗೆ Codec Robustness ಅನ್ನೂ ನಿಜವಾಗಿ ಪರೀಕ್ಷಿಸುವುದೂ',
    problem: "1. Take a clean audio clip, encode-decode it through a neural codec of your choice, and separately compress-decompress the same original through a lossy classical codec (e.g. MP3 at 64kbps).\n2. Compute a real similarity metric (e.g. spectral distance or correlation) between (a) original vs. neural-codec output and (b) original vs. MP3 output.\n3. Now take the NEURAL CODEC's OUTPUT and feed it through the classical MP3 codec (simulating a real pipeline where neural-codec audio gets re-encoded for transmission/storage). Measure the cascaded degradation. Does the neural codec's reconstruction hold up well under a second lossy compression pass, or does it degrade sharply -- report what you genuinely measured.",
    problemKn: "1. ಒಂದು ಸ್ವಚ್ಛ audio clip ತೆಗೆದುಕೊಂಡು, ಅದನ್ನೂ ನಿಮ್ಮ ಆಯ್ಕೆಯ ಒಂದು neural codec ಮೂಲಕ encode-decode ಮಾಡಿ, ಮತ್ತು ಪ್ರತ್ಯೇಕವಾಗಿ ಅದೇ ಮೂಲವನ್ನೂ ಒಂದು classical codec (ಉದಾ 64kbps ನಲ್ಲಿ MP3) ಮೂಲಕ compress-decompress ಮಾಡಿ.\n2. (a) ಮೂಲ vs. neural-codec output ಮತ್ತು (b) ಮೂಲ vs. MP3 output ನಡುವೆ ಒಂದು ನಿಜ similarity metric ಲೆಕ್ಕಹಾಕಿ.\n3. ಈಗ NEURAL CODEC ya OUTPUT ಅನ್ನೂ classical MP3 codec ಮೂಲಕ ಫೀಡ್ ಮಾಡಿ. cascaded degradation ಅಳೆಯಿರಿ. neural codec ya reconstruction ಎರಡನೇ lossy compression pass ಅಡಿಯಲ್ಲಿ ಚೆನ್ನಾಗಿ ಹಿಡಿದುಕೊಳ್ಳುತ್ತದೆಯೇ, ಅಥವಾ ತೀವ್ರವಾಗಿ ಕುಸಿಯುತ್ತದೆಯೇ -- ನೀವು ನಿಜವಾಗಿ ಅಳೆದದ್ದನ್ನೂ ವರದಿ ಮಾಡಿ." },

  // ── Module 137, Lesson 1: Silero, Cascades & the Turn Detector ──
  { phaseId, moduleId: m137, lessonId: l137_1, order: 1, difficulty: 'beginner',
    title: 'Genuinely Measuring Silero VAD Accuracy on Real Silence',
    titleKn: 'ನಿಜ Silence ಮೇಲೆ Silero VAD Accuracy ಅನ್ನೂ ನಿಜವಾಗಿ ಅಳೆಯುವುದೂ',
    problem: "Load Silero VAD (via torch.hub) genuinely.\n1. Create 10 pure-silence frames (zeros or very low-amplitude noise) at the minimum required frame size, and run Silero VAD on each. Record the speech-probability the model returns for each.\n2. Create 10 real or synthetic speech-like frames (sine sweeps or, better, a real recorded voice clip chunked into frames) and run the same check.\n3. Choose a probability threshold and compute your own confusion matrix (true positive/negative, false positive/negative) across these 20 frames. Report your model's genuine accuracy on this small test set -- do not assume the published benchmark numbers apply directly to your own frames.",
    problemKn: "Silero VAD ಅನ್ನೂ (torch.hub ಮೂಲಕ) ನಿಜವಾಗಿ load ಮಾಡಿ.\n1. ಕನಿಷ್ಠ ಅಗತ್ಯವಿರುವ frame size ನಲ್ಲಿ 10 ಶುದ್ಧ-silence frames ರಚಿಸಿ, ಮತ್ತು ಪ್ರತಿಯೊಂದರ ಮೇಲೂ Silero VAD ಚಲಾಯಿಸಿ. model ಹಿಂತಿರುಗಿಸುವ speech-probability ದಾಖಲಿಸಿ.\n2. 10 ನಿಜ ಅಥವಾ synthetic speech-like frames ರಚಿಸಿ ಮತ್ತು ಅದೇ ಪರಿಶೀಲನೆ ಚಲಾಯಿಸಿ.\n3. ಒಂದು probability threshold ಆಯ್ಕೆ ಮಾಡಿ ಮತ್ತು ಈ 20 frames ಗಳಾದ್ಯಂತ ನಿಮ್ಮ ಸ್ವಂತ confusion matrix ಲೆಕ್ಕಹಾಕಿ. ಈ ಚಿಕ್ಕ test set ಮೇಲೆ ನಿಮ್ಮ model ya ನಿಜ accuracy ವರದಿ ಮಾಡಿ -- ಪ್ರಕಟಿತ benchmark ಸಂಖ್ಯೆಗಳು ನಿಮ್ಮ ಸ್ವಂತ frames ಗೆ ನೇರವಾಗಿ ಅನ್ವಯಿಸುತ್ತವೆ ಎಂದು ಊಹಿಸಬೇಡಿ." },
  { phaseId, moduleId: m137, lessonId: l137_1, order: 2, difficulty: 'intermediate',
    title: 'Building and Timing a Cascaded VAD Pipeline',
    titleKn: 'ಒಂದು Cascaded VAD Pipeline ನಿರ್ಮಿಸುವುದೂ ಮತ್ತು ಸಮಯ ಅಳೆಯುವುದೂ',
    problem: "Implement a two-stage cascade: a cheap energy-based VAD as a fast first-pass filter, followed by Silero VAD only on frames the energy filter marks as 'maybe speech.'\n1. Genuinely time (using time.perf_counter()) how long 1000 frames take to process through the energy filter alone versus through Silero VAD alone versus through your cascade.\n2. Measure what fraction of frames the energy filter successfully screens out before they ever reach Silero VAD, using a real mixed silence/speech test sequence you construct.\n3. Report the real speedup factor your cascade achieves compared to running Silero VAD on every single frame, and explain any accuracy tradeoff you observe (does the cascade ever mislabel something the energy filter wrongly screened out?).",
    problemKn: "ಒಂದು two-stage cascade ಜಾರಿಗೊಳಿಸಿ: ಒಂದು ಅಗ್ಗದ energy-based VAD ಒಂದು ವೇಗದ first-pass filter ಆಗಿ, ನಂತರ Silero VAD ಕೇವಲ energy filter 'ಬಹುಶಃ speech' ಎಂದು ಗುರುತಿಸಿದ frames ಮೇಲೆ ಮಾತ್ರ.\n1. 1000 frames ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲು ಎಷ್ಟು ಸಮಯ ತೆಗೆದುಕೊಳ್ಳುತ್ತದೆ ಎಂದು ಕೇವಲ energy filter ಮೂಲಕ, ಕೇವಲ Silero VAD ಮೂಲಕ, ಮತ್ತು ನಿಮ್ಮ cascade ಮೂಲಕ ನಿಜವಾಗಿ ಅಳೆಯಿರಿ.\n2. ನೀವು ನಿರ್ಮಿಸುವ ಒಂದು ನಿಜ ಮಿಶ್ರ silence/speech test sequence ಬಳಸಿ, energy filter Silero VAD ತಲುಪುವ ಮೊದಲು ಎಷ್ಟು ಭಾಗ frames ಯಶಸ್ವಿಯಾಗಿ ಫಿಲ್ಟರ್ ಮಾಡುತ್ತದೆ ಎಂದು ಅಳೆಯಿರಿ.\n3. ಪ್ರತಿ ಒಂದೇ frame ಮೇಲೆ Silero VAD ಚಲಾಯಿಸುವುದಕ್ಕೆ ಹೋಲಿಸಿದರೆ ನಿಮ್ಮ cascade ಸಾಧಿಸುವ ನಿಜ speedup factor ವರದಿ ಮಾಡಿ." },
  { phaseId, moduleId: m137, lessonId: l137_1, order: 3, difficulty: 'advanced',
    title: 'Genuinely Verifying the Turn Detector Under Noisy Conditions',
    titleKn: 'ಗದ್ದಲದ Conditions ಅಡಿಯಲ್ಲಿ Turn Detector ಅನ್ನೂ ನಿಜವಾಗಿ ಪರಿಶೀಲಿಸುವುದೂ',
    problem: "Implement (or reuse) a turn-detector state machine with min_speech_ms and silence_ms parameters.\n1. Simulate a 'clean' conversation turn (continuous speech, then silence) and confirm the detector correctly identifies the turn boundary.\n2. Now simulate a turn with brief noise spikes injected during what should be a silence gap (e.g. random short energy blips mimicking background noise). Does your detector incorrectly extend or reset the turn because of these spikes?\n3. Tune your silence_ms or add a debounce/hysteresis mechanism to make the detector robust to these injected spikes, and genuinely re-run your simulation to confirm the fix works -- report the before/after behavior with real numbers (index at which the turn completes in each case).",
    problemKn: "min_speech_ms ಮತ್ತು silence_ms parameters ಜೊತೆ ಒಂದು turn-detector state machine ಜಾರಿಗೊಳಿಸಿ (ಅಥವಾ ಮರುಬಳಸಿ).\n1. ಒಂದು 'ಸ್ವಚ್ಛ' conversation turn simulate ಮಾಡಿ ಮತ್ತು detector ಸರಿಯಾಗಿ turn boundary ಗುರುತಿಸುತ್ತದೆ ಎಂದು ಖಚಿತಪಡಿಸಿ.\n2. ಈಗ silence gap ಆಗಿರಬೇಕಾದ ಸಮಯದಲ್ಲಿ ಚಿಕ್ಕ noise spikes ಸೇರಿಸಿದ ಒಂದು turn simulate ಮಾಡಿ. ನಿಮ್ಮ detector ಈ spikes ಇಂದಾಗಿ turn ಅನ್ನೂ ತಪ್ಪಾಗಿ ವಿಸ್ತರಿಸುತ್ತದೆಯೇ ಅಥವಾ ಮರುಹೊಂದಿಸುತ್ತದೆಯೇ?\n3. ಈ ಸೇರಿಸಿದ spikes ಗೆ detector ಅನ್ನೂ ಸದೃಢಗೊಳಿಸಲು ನಿಮ್ಮ silence_ms ಟ್ಯೂನ್ ಮಾಡಿ ಅಥವಾ ಒಂದು debounce/hysteresis ಕಾರ್ಯವಿಧಾನ ಸೇರಿಸಿ, ಮತ್ತು fix ಕೆಲಸ ಮಾಡುತ್ತದೆ ಎಂದು ಖಚಿತಪಡಿಸಲು ನಿಜವಾಗಿ ಮರುಚಲಾಯಿಸಿ -- before/after ವರ್ತನೆಯನ್ನೂ ನಿಜ ಸಂಖ್ಯೆಗಳೊಂದಿಗೆ ವರದಿ ಮಾಡಿ." },

  // ── Module 137, Lesson 2: The Flush Trick & Production VAD ──
  { phaseId, moduleId: m137, lessonId: l137_2, order: 1, difficulty: 'beginner',
    title: 'Genuinely Implementing the Flush Trick',
    titleKn: 'Flush Trick ಅನ್ನೂ ನಿಜವಾಗಿ ಜಾರಿಗೊಳಿಸುವುದೂ',
    problem: "The 'flush trick' forces a streaming VAD/ASR system to finalize its current buffer early (e.g. on an explicit end-of-utterance signal) rather than waiting for its normal timeout.\n1. Implement a simple streaming buffer class with a flush() method that immediately processes and clears whatever partial audio it's holding, bypassing the normal silence-timeout logic.\n2. Genuinely measure the latency difference: feed the same utterance through your pipeline once relying on the normal timeout, and once calling flush() right after the utterance ends. Report the real millisecond difference using time.perf_counter().\n3. What real-world signal would trigger a flush in a production system (e.g. a button release, an explicit 'done speaking' gesture, or a detected question mark in partial ASR text)? Implement one such trigger condition and test it.",
    problemKn: "'flush trick' ಒಂದು streaming VAD/ASR system ಅನ್ನೂ ಅದರ ಸಾಮಾನ್ಯ timeout ಗೆ ಕಾಯುವ ಬದಲು ಅದರ ಪ್ರಸ್ತುತ buffer ಅನ್ನೂ ಮೊದಲೇ ಪೂರ್ಣಗೊಳಿಸುವಂತೆ ಒತ್ತಾಯಿಸುತ್ತದೆ.\n1. ಒಂದು ಸರಳ streaming buffer class ಜಾರಿಗೊಳಿಸಿ, ಇದರ flush() method ತಕ್ಷಣ ಅದು ಹಿಡಿದಿರುವ ಯಾವುದೇ partial audio ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಿ ಖಾಲಿ ಮಾಡುತ್ತದೆ.\n2. ನಿಜ latency ವ್ಯತ್ಯಾಸ ಅಳೆಯಿರಿ: ಅದೇ utterance ಅನ್ನೂ ಒಮ್ಮೆ ಸಾಮಾನ್ಯ timeout ಅವಲಂಬಿಸಿ, ಮತ್ತು ಒಮ್ಮೆ utterance ಮುಗಿದ ತಕ್ಷಣ flush() ಕರೆ ಮಾಡಿ ನಿಮ್ಮ pipeline ಮೂಲಕ ಫೀಡ್ ಮಾಡಿ. ನಿಜ millisecond ವ್ಯತ್ಯಾಸ ವರದಿ ಮಾಡಿ.\n3. ಒಂದು production system ನಲ್ಲಿ ಯಾವ ನಿಜ-ಪ್ರಪಂಚ signal ಒಂದು flush ಪ್ರಚೋದಿಸುತ್ತದೆ? ಅಂತಹ ಒಂದು trigger condition ಜಾರಿಗೊಳಿಸಿ ಮತ್ತು ಪರೀಕ್ಷಿಸಿ." },
  { phaseId, moduleId: m137, lessonId: l137_2, order: 2, difficulty: 'intermediate',
    title: 'Genuinely Load-Testing a Production VAD Setup',
    titleKn: 'ಒಂದು Production VAD Setup ಅನ್ನೂ ನಿಜವಾಗಿ Load-Testing ಮಾಡುವುದೂ',
    problem: "Simulate a production scenario: multiple concurrent 'calls' each needing VAD processing on a stream of frames.\n1. Implement a simple asyncio-based simulation running N concurrent VAD sessions (start with N=10), each processing a queue of frames with your VAD of choice (energy-based or Silero).\n2. Genuinely measure, using real timing, how per-session VAD latency changes as you increase N from 10 to 50 to 200 concurrent sessions on your actual machine.\n3. Identify the real bottleneck (CPU-bound model inference, Python's GIL, or something else) by profiling where time is actually spent as N grows, and report a concrete number for the maximum concurrent sessions your setup can sustain while keeping per-frame latency under a target you choose (e.g. 50ms).",
    problemKn: "ಒಂದು production ಸನ್ನಿವೇಶ simulate ಮಾಡಿ: ಪ್ರತಿಯೊಂದೂ frames ya ಒಂದು stream ಮೇಲೆ VAD processing ಬೇಕಾದ ಬಹು ಏಕಕಾಲಿಕ 'calls'.\n1. N=10 ಏಕಕಾಲಿಕ VAD sessions ಚಲಾಯಿಸುವ ಒಂದು ಸರಳ asyncio-based simulation ಜಾರಿಗೊಳಿಸಿ.\n2. N ಅನ್ನೂ 10 ಇಂದ 50 ಗೆ 200 ಗೆ ಹೆಚ್ಚಿಸಿದಂತೆ ಪ್ರತಿ-session VAD latency ಹೇಗೆ ಬದಲಾಗುತ್ತದೆ ಎಂದು ನಿಜ timing ಬಳಸಿ ನಿಜವಾಗಿ ಅಳೆಯಿರಿ.\n3. N ಬೆಳೆದಂತೆ ಸಮಯ ನಿಜವಾಗಿ ಎಲ್ಲಿ ಖರ್ಚಾಗುತ್ತದೆ ಎಂದು profile ಮಾಡುವ ಮೂಲಕ ನಿಜ bottleneck ಗುರುತಿಸಿ, ಮತ್ತು ಪ್ರತಿ-frame latency ಒಂದು target ಕೆಳಗೆ ಇಡುತ್ತಲೇ ನಿಮ್ಮ setup ಬೆಂಬಲಿಸಬಹುದಾದ ಗರಿಷ್ಠ ಏಕಕಾಲಿಕ sessions ಗೆ ಒಂದು ನಿರ್ದಿಷ್ಟ ಸಂಖ್ಯೆ ವರದಿ ಮಾಡಿ." },
  { phaseId, moduleId: m137, lessonId: l137_2, order: 3, difficulty: 'advanced',
    title: 'Comparing Production VAD Strategies Under Real Barge-In',
    titleKn: 'ನಿಜ Barge-In ಅಡಿಯಲ್ಲಿ Production VAD Strategies ಹೋಲಿಸುವುದೂ',
    problem: "Implement two turn-detection strategies: (a) a simple fixed silence-timeout detector, and (b) a detector that also tracks a rolling energy trend to detect an abrupt user 'barge-in' (interruption) during assistant playback.\n1. Genuinely simulate a barge-in scenario: assistant audio 'playing' (represented as a background signal) with a real user-speech burst injected partway through. Measure how many milliseconds each strategy takes to correctly flag the interruption.\n2. Simulate a false-alarm scenario -- a loud but non-speech noise burst (e.g. a door slam simulated as a sharp transient) during assistant playback. Does strategy (b) correctly avoid triggering a false barge-in, or does it also fire incorrectly?\n3. Based on your two real experiments, report which strategy you'd deploy in production and justify it with the actual latency and false-positive numbers you measured, not a general preference.",
    problemKn: "ಎರಡು turn-detection strategies ಜಾರಿಗೊಳಿಸಿ: (a) ಒಂದು ಸರಳ ಸ್ಥಿರ silence-timeout detector, ಮತ್ತು (b) assistant playback ಸಮಯದಲ್ಲಿ ಒಂದು ಹಠಾತ್ user 'barge-in' ಪತ್ತೆಹಚ್ಚಲು ಒಂದು rolling energy trend ಸಹ ಟ್ರ್ಯಾಕ್ ಮಾಡುವ detector.\n1. ಒಂದು ನಿಜ barge-in ಸನ್ನಿವೇಶ simulate ಮಾಡಿ: 'ಪ್ಲೇ ಆಗುತ್ತಿರುವ' assistant audio, ಅರ್ಧದಲ್ಲಿ ಒಂದು ನಿಜ user-speech burst ಸೇರಿಸಿ. ಪ್ರತಿ strategy ಅಡ್ಡಿಪಡಿಸುವಿಕೆಯನ್ನೂ ಸರಿಯಾಗಿ ಗುರುತಿಸಲು ಎಷ್ಟು milliseconds ತೆಗೆದುಕೊಳ್ಳುತ್ತದೆ ಎಂದು ಅಳೆಯಿರಿ.\n2. ಒಂದು false-alarm ಸನ್ನಿವೇಶ simulate ಮಾಡಿ -- assistant playback ಸಮಯದಲ್ಲಿ ಒಂದು ಜೋರಾದ ಆದರೆ speech ಅಲ್ಲದ noise burst. strategy (b) ಒಂದು false barge-in ಸರಿಯಾಗಿ ತಪ್ಪಿಸುತ್ತದೆಯೇ, ಅಥವಾ ಅದು ಸಹ ತಪ್ಪಾಗಿ ಪ್ರಚೋದಿಸುತ್ತದೆಯೇ?\n3. ನಿಮ್ಮ ಎರಡು ನಿಜ ಪ್ರಯೋಗಗಳ ಆಧಾರದ ಮೇಲೆ, production ನಲ್ಲಿ ಯಾವ strategy deploy ಮಾಡುತ್ತೀರಿ ಎಂದು ವರದಿ ಮಾಡಿ ಮತ್ತು ನೀವು ಅಳೆದ ನಿಜ latency ಮತ್ತು false-positive ಸಂಖ್ಯೆಗಳೊಂದಿಗೆ ಸಮರ್ಥಿಸಿ." },

  // ── Module 138, Lesson 1: Moshi and Full-Duplex Dialogue ──
  { phaseId, moduleId: m138, lessonId: l138_1, order: 1, difficulty: 'beginner',
    title: 'Genuinely Attempting a Moshi Install and Inference Run',
    titleKn: 'Moshi Install ಮತ್ತು Inference Run ಅನ್ನೂ ನಿಜವಾಗಿ ಪ್ರಯತ್ನಿಸುವುದೂ',
    problem: "Genuinely attempt to install and run Kyutai's Moshi (via the moshi PyPI package or the official repo) in your own environment.\n1. Document the exact install command you used and whether it succeeded -- capture the real error message if it failed (e.g. missing GPU, CUDA version mismatch, disk space for the checkpoint download).\n2. If it succeeds, run a short inference session and report what genuinely happened (did you get real-time-ish audio output? What latency did you observe?).\n3. If it fails, research what minimum hardware Moshi requires for real-time full-duplex inference (GPU VRAM, etc.) and compare that against your own machine's specs -- explain concretely why it failed rather than assuming a generic cause.",
    problemKn: "ನಿಮ್ಮ ಸ್ವಂತ environment ನಲ್ಲಿ Kyutai ya Moshi ಅನ್ನೂ ನಿಜವಾಗಿ install ಮತ್ತು ಚಲಾಯಿಸಲು ಪ್ರಯತ್ನಿಸಿ.\n1. ನೀವು ಬಳಸಿದ ನಿಖರ install command ಮತ್ತು ಇದು ಯಶಸ್ವಿಯಾಯಿತೇ ಎಂದು ದಾಖಲಿಸಿ -- ವಿಫಲವಾದರೆ ನಿಜ error message ಸೆರೆಹಿಡಿಯಿರಿ.\n2. ಯಶಸ್ವಿಯಾದರೆ, ಒಂದು ಚಿಕ್ಕ inference session ಚಲಾಯಿಸಿ ಮತ್ತು ನಿಜವಾಗಿ ಏನಾಯಿತು ಎಂದು ವರದಿ ಮಾಡಿ.\n3. ವಿಫಲವಾದರೆ, real-time full-duplex inference ಗೆ Moshi ಗೆ ಕನಿಷ್ಠ ಯಾವ hardware ಬೇಕು ಎಂದು ಸಂಶೋಧಿಸಿ ಮತ್ತು ಅದನ್ನೂ ನಿಮ್ಮ ಸ್ವಂತ machine ya specs ಜೊತೆ ಹೋಲಿಸಿ -- ಒಂದು ಸಾಮಾನ್ಯ ಕಾರಣ ಊಹಿಸುವ ಬದಲು ಇದು ಏಕೆ ವಿಫಲವಾಯಿತು ಎಂದು ನಿರ್ದಿಷ್ಟವಾಗಿ ವಿವರಿಸಿ." },
  { phaseId, moduleId: m138, lessonId: l138_1, order: 2, difficulty: 'intermediate',
    title: 'Simulating Full-Duplex vs. Half-Duplex Turn-Taking',
    titleKn: 'Full-Duplex vs. Half-Duplex Turn-Taking ಸಿಮ್ಯುಲೇಟ್ ಮಾಡುವುದೂ',
    problem: "Build a simple asyncio simulation comparing half-duplex (strict turn-taking: assistant waits for the user to fully stop before responding, and vice versa) versus full-duplex (both streams processed continuously and concurrently, like Moshi's architecture) dialogue handling.\n1. Simulate a user who briefly interjects ('mm-hmm', 'yeah') while the assistant is speaking. In your half-duplex model, what happens to this interjection -- does it get dropped, queued, or does it interrupt the assistant?\n2. In your full-duplex model, allow both 'channels' to be processed as concurrent asyncio tasks. Does the short interjection get correctly captured without disrupting the assistant's ongoing response?\n3. Genuinely measure and report: how many extra lines of coordination code did the full-duplex model need compared to half-duplex, and what specific concurrency bug (race condition, ordering issue) did you have to debug while building it, if any?",
    problemKn: "half-duplex (ಕಟ್ಟುನಿಟ್ಟಾದ turn-taking) ಮತ್ತು full-duplex (ಎರಡೂ streams ಏಕಕಾಲದಲ್ಲಿ ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲಾಗುತ್ತದೆ, Moshi ya architecture ನಂತೆ) dialogue handling ಹೋಲಿಸುವ ಒಂದು ಸರಳ asyncio simulation ನಿರ್ಮಿಸಿ.\n1. assistant ಮಾತನಾಡುತ್ತಿರುವಾಗ ಸಂಕ್ಷಿಪ್ತವಾಗಿ ಮಧ್ಯಪ್ರವೇಶಿಸುವ ('mm-hmm', 'yeah') ಒಬ್ಬ user ಸಿಮ್ಯುಲೇಟ್ ಮಾಡಿ. ನಿಮ್ಮ half-duplex model ನಲ್ಲಿ, ಈ ಮಧ್ಯಪ್ರವೇಶಕ್ಕೆ ಏನಾಗುತ್ತದೆ?\n2. ನಿಮ್ಮ full-duplex model ನಲ್ಲಿ, ಎರಡೂ 'channels' ಅನ್ನೂ ಏಕಕಾಲಿಕ asyncio tasks ಆಗಿ ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲು ಅನುಮತಿಸಿ. ಚಿಕ್ಕ ಮಧ್ಯಪ್ರವೇಶ assistant ya ನಡೆಯುತ್ತಿರುವ response ಅಡ್ಡಿಪಡಿಸದೆ ಸರಿಯಾಗಿ ಸೆರೆಹಿಡಿಯಲ್ಪಡುತ್ತದೆಯೇ?\n3. ನಿಜವಾಗಿ ಅಳೆಯಿರಿ ಮತ್ತು ವರದಿ ಮಾಡಿ: half-duplex ಗೆ ಹೋಲಿಸಿದರೆ full-duplex model ಗೆ ಎಷ್ಟು ಹೆಚ್ಚುವರಿ coordination code ಬೇಕಾಯಿತು, ಮತ್ತು ಇದನ್ನೂ ನಿರ್ಮಿಸುವಾಗ ನೀವು ಯಾವ ನಿರ್ದಿಷ್ಟ concurrency bug ಡೀಬಗ್ ಮಾಡಬೇಕಾಯಿತು." },
  { phaseId, moduleId: m138, lessonId: l138_1, order: 3, difficulty: 'advanced',
    title: "Measuring Moshi's Inner Monologue Mechanism",
    titleKn: 'Moshi ya Inner Monologue Mechanism ಅಳೆಯುವುದೂ',
    problem: "Moshi generates text tokens alongside audio tokens (an 'inner monologue') to improve linguistic quality while still streaming audio.\n1. Research (from Moshi's paper or repo) exactly how the text and audio token streams are interleaved architecturally, and diagram the token layout for a few timesteps in your own notes.\n2. If you have a working Moshi setup, genuinely extract and print both the text tokens and audio tokens generated for a short prompt, aligned by timestep, and confirm they appear in the pattern the paper describes.\n3. If you cannot run Moshi directly, implement a toy simulation: a generator that yields (text_token, audio_token) pairs per timestep with a deliberate delay offset between when a word is 'decided' (text token) and when its audio is 'realized' (audio token), and measure how many timesteps of delay your toy model needs for the text to reliably lead the audio, matching the architectural principle even without the real model.",
    problemKn: "Moshi text tokens ಅನ್ನೂ audio tokens ಜೊತೆಗೆ ಉತ್ಪಾದಿಸುತ್ತದೆ (ಒಂದು 'inner monologue') linguistic quality ಸುಧಾರಿಸಲು.\n1. Moshi ya paper ಅಥವಾ repo ಇಂದ, text ಮತ್ತು audio token streams ಹೇಗೆ architecturally interleave ಆಗುತ್ತವೆ ಎಂದು ಸಂಶೋಧಿಸಿ, ಮತ್ತು ಕೆಲವು timesteps ಗೆ token layout ಅನ್ನೂ ನಿಮ್ಮ ಸ್ವಂತ ಟಿಪ್ಪಣಿಗಳಲ್ಲಿ ರೇಖಾಚಿತ್ರ ಮಾಡಿ.\n2. ನಿಮಗೆ ಒಂದು ಕೆಲಸ ಮಾಡುವ Moshi setup ಇದ್ದರೆ, ಒಂದು ಚಿಕ್ಕ prompt ಗೆ text tokens ಮತ್ತು audio tokens ಎರಡನ್ನೂ ನಿಜವಾಗಿ ಹೊರತೆಗೆದು ಪ್ರಿಂಟ್ ಮಾಡಿ, timestep ಪ್ರಕಾರ ಜೋಡಿಸಿ.\n3. ನೀವು ನೇರವಾಗಿ Moshi ಚಲಾಯಿಸಲಾಗದಿದ್ದರೆ, ಒಂದು toy simulation ಜಾರಿಗೊಳಿಸಿ: ಪ್ರತಿ timestep ಗೆ (text_token, audio_token) ಜೋಡಿಗಳನ್ನೂ ನೀಡುವ ಒಂದು generator, ಒಂದು ಪದ 'ನಿರ್ಧರಿಸಿದಾಗ' ಮತ್ತು ಅದರ audio 'ಸಾಕಾರಗೊಂಡಾಗ' ನಡುವೆ ಒಂದು ಉದ್ದೇಶಪೂರ್ವಕ delay ಆಫ್ಸೆಟ್ ಜೊತೆ." },

  // ── Module 138, Lesson 2: Hibiki, Sesame CSM & Choosing an Architecture ──
  { phaseId, moduleId: m138, lessonId: l138_2, order: 1, difficulty: 'beginner',
    title: 'Genuinely Comparing Hibiki and Sesame CSM Setup Complexity',
    titleKn: 'Hibiki ಮತ್ತು Sesame CSM Setup Complexity ಅನ್ನೂ ನಿಜವಾಗಿ ಹೋಲಿಸುವುದೂ',
    problem: "1. Genuinely attempt to set up both Hibiki (Kyutai's simultaneous speech translation model) and Sesame's CSM (Conversational Speech Model) in your own environment, following each project's official setup instructions exactly.\n2. For each, record the real number of steps, the real total install/download time, and any errors you had to work around.\n3. Based on your genuine hands-on experience (not the projects' marketing pages), which was more straightforward to get running locally, and what specific step caused the most friction for each?",
    problemKn: "1. Hibiki (Kyutai ya simultaneous speech translation model) ಮತ್ತು Sesame ya CSM (Conversational Speech Model) ಎರಡನ್ನೂ ಪ್ರತಿ project ya ಅಧಿಕೃತ setup ಸೂಚನೆಗಳನ್ನೂ ನಿಖರವಾಗಿ ಅನುಸರಿಸಿ ನಿಮ್ಮ ಸ್ವಂತ environment ನಲ್ಲಿ ನಿಜವಾಗಿ ಸ್ಥಾಪಿಸಲು ಪ್ರಯತ್ನಿಸಿ.\n2. ಪ್ರತಿಯೊಂದಕ್ಕೂ, ನಿಜ ಹಂತಗಳ ಸಂಖ್ಯೆ, ನಿಜ ಒಟ್ಟು install/download ಸಮಯ, ಮತ್ತು ನೀವು ಬಗೆಹರಿಸಬೇಕಾದ ಯಾವುದೇ errors ದಾಖಲಿಸಿ.\n3. ನಿಮ್ಮ ನಿಜ ಪ್ರಾಯೋಗಿಕ ಅನುಭವದ ಆಧಾರದ ಮೇಲೆ, ಯಾವುದೂ locally ಚಲಾಯಿಸಲು ಹೆಚ್ಚು ನೇರವಾಗಿತ್ತು, ಮತ್ತು ಪ್ರತಿಯೊಂದಕ್ಕೂ ಯಾವ ನಿರ್ದಿಷ್ಟ ಹಂತ ಅತಿ ಹೆಚ್ಚು ಘರ್ಷಣೆ ಉಂಟುಮಾಡಿತು?" },
  { phaseId, moduleId: m138, lessonId: l138_2, order: 2, difficulty: 'intermediate',
    title: 'Genuinely Measuring Simultaneous Translation Lag',
    titleKn: 'Simultaneous Translation Lag ಅನ್ನೂ ನಿಜವಾಗಿ ಅಳೆಯುವುದೂ',
    problem: "If you have a working Hibiki (or equivalent simultaneous speech-to-speech translation) setup:\n1. Feed it a sentence in the source language and genuinely time (using time.perf_counter()) the delay between when a word is spoken/fed and when its translation is emitted.\n2. Measure this lag for at least 5 different sentences of varying length. Does lag stay roughly constant, or does it grow with sentence length or complexity?\n3. If you cannot run a real model, design and implement a measurement harness (the timing/logging code itself) that WOULD produce this measurement given a real streaming translation function, and test your harness against a stub function with an artificial fixed delay to confirm it correctly reports that delay.",
    problemKn: "ನಿಮಗೆ ಒಂದು ಕೆಲಸ ಮಾಡುವ Hibiki (ಅಥವಾ ಸಮಾನ simultaneous speech-to-speech translation) setup ಇದ್ದರೆ:\n1. ಇದಕ್ಕೆ source language ನಲ್ಲಿ ಒಂದು ವಾಕ್ಯ ಫೀಡ್ ಮಾಡಿ ಮತ್ತು ಒಂದು ಪದ ಹೇಳಿದಾಗ/ಫೀಡ್ ಆದಾಗ ಮತ್ತು ಅದರ translation ಹೊರಬಂದಾಗ ನಡುವಿನ ವಿಳಂಬವನ್ನೂ ನಿಜವಾಗಿ ಸಮಯ ಅಳೆಯಿರಿ.\n2. ಕನಿಷ್ಠ 5 ವಿಭಿನ್ನ ಉದ್ದದ ವಾಕ್ಯಗಳಿಗೆ ಈ lag ಅಳೆಯಿರಿ. lag ಸುಮಾರಾಗಿ ಸ್ಥಿರವಾಗಿ ಉಳಿಯುತ್ತದೆಯೇ, ಅಥವಾ ವಾಕ್ಯ ಉದ್ದ ಅಥವಾ ಸಂಕೀರ್ಣತೆ ಜೊತೆ ಬೆಳೆಯುತ್ತದೆಯೇ?\n3. ನೀವು ಒಂದು ನಿಜ model ಚಲಾಯಿಸಲಾಗದಿದ್ದರೆ, ಒಂದು measurement harness ವಿನ್ಯಾಸಗೊಳಿಸಿ ಮತ್ತು ಜಾರಿಗೊಳಿಸಿ, ಮತ್ತು ಒಂದು ಕೃತಕ ಸ್ಥಿರ delay ಇರುವ ಒಂದು stub function ವಿರುದ್ಧ ನಿಮ್ಮ harness ಪರೀಕ್ಷಿಸಿ ಅದು ಆ delay ಸರಿಯಾಗಿ ವರದಿ ಮಾಡುತ್ತದೆ ಎಂದು ಖಚಿತಪಡಿಸಿ." },
  { phaseId, moduleId: m138, lessonId: l138_2, order: 3, difficulty: 'advanced',
    title: 'Building a Genuine Architecture-Choice Decision Framework',
    titleKn: 'ಒಂದು ನಿಜ Architecture-Choice Decision Framework ನಿರ್ಮಿಸುವುದೂ',
    problem: "Across Moshi (full-duplex, single unified model), Hibiki (simultaneous translation), and Sesame CSM (conversational speech), plus the cascaded pipeline from Module 135 (separate VAD+STT+LLM+TTS stages):\n1. For each architecture, genuinely attempt to find and record its real reported latency-to-first-audio number from its own paper or benchmark, not a secondhand summary.\n2. Build a decision table scoring each architecture on: setup complexity (based on your own genuine install attempts if possible), hardware requirements, and how naturally it supports true full-duplex interruption versus needing an external turn-detector bolted on.\n3. For a specific product scenario you define yourself (e.g. 'a customer-service phone bot that must run on commodity CPU-only servers'), use your table to make and justify a genuine architecture recommendation -- not a generic 'it depends.'",
    problemKn: "Moshi (full-duplex, ಏಕೀಕೃತ model), Hibiki (simultaneous translation), Sesame CSM (conversational speech), ಮತ್ತು Module 135 ya cascaded pipeline (ಪ್ರತ್ಯೇಕ VAD+STT+LLM+TTS stages) ಗಳಾದ್ಯಂತ:\n1. ಪ್ರತಿ architecture ಗೆ, ಅದರ ಸ್ವಂತ paper ಅಥವಾ benchmark ಇಂದ ಅದರ ನಿಜ ವರದಿಯಾದ latency-to-first-audio ಸಂಖ್ಯೆ ಕಂಡುಹಿಡಿಯಲು ಮತ್ತು ದಾಖಲಿಸಲು ನಿಜವಾಗಿ ಪ್ರಯತ್ನಿಸಿ.\n2. ಪ್ರತಿ architecture ಅನ್ನೂ ಇವುಗಳ ಮೇಲೆ score ಮಾಡುವ ಒಂದು decision table ನಿರ್ಮಿಸಿ: setup complexity, hardware requirements, ಮತ್ತು ಇದು ನಿಜ full-duplex interruption ಅನ್ನೂ ಎಷ್ಟು ಸಹಜವಾಗಿ ಬೆಂಬಲಿಸುತ್ತದೆ.\n3. ನೀವೇ ವ್ಯಾಖ್ಯಾನಿಸುವ ಒಂದು ನಿರ್ದಿಷ್ಟ product ಸನ್ನಿವೇಶಕ್ಕೆ, ನಿಮ್ಮ table ಬಳಸಿ ಒಂದು ನಿಜ architecture ಶಿಫಾರಸು ಮಾಡಿ ಮತ್ತು ಸಮರ್ಥಿಸಿ." },

  // ── Module 139, Lesson 1: ASVspoof, AASIST, EER & AudioSeal ──
  { phaseId, moduleId: m139, lessonId: l139_1, order: 1, difficulty: 'beginner',
    title: 'Genuinely Computing Equal Error Rate (EER)',
    titleKn: 'Equal Error Rate (EER) ಅನ್ನೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕುವುದೂ',
    problem: "1. Generate a synthetic dataset of 'genuine' scores (e.g. sampled from a Normal(0.8, 0.1) distribution) and 'spoof' scores (sampled from Normal(0.3, 0.15)), 200 samples each, representing a hypothetical anti-spoofing model's output scores.\n2. Genuinely implement the EER computation from scratch: sweep a threshold across the score range, compute False Acceptance Rate and False Rejection Rate at each threshold, and find the threshold where they cross (or are closest).\n3. Report the EER value and the threshold at which it occurs for your synthetic data. Then shift the spoof distribution's mean closer to the genuine distribution's mean (e.g. Normal(0.6, 0.15)) and recompute EER -- confirm it gets worse (higher), and explain in your own words why increased score overlap between the two classes necessarily increases EER.",
    problemKn: "1. 'genuine' scores (ಉದಾ Normal(0.8, 0.1) ಇಂದ) ಮತ್ತು 'spoof' scores (Normal(0.3, 0.15) ಇಂದ) ya ಒಂದು synthetic dataset ರಚಿಸಿ, ಪ್ರತಿಯೊಂದಕ್ಕೂ 200 samples.\n2. EER computation ಅನ್ನೂ ಮೊದಲಿನಿಂದ ನಿಜವಾಗಿ ಜಾರಿಗೊಳಿಸಿ: score range ಗಳಾದ್ಯಂತ ಒಂದು threshold ಸ್ವೀಪ್ ಮಾಡಿ, ಪ್ರತಿ threshold ನಲ್ಲಿ False Acceptance Rate ಮತ್ತು False Rejection Rate ಲೆಕ್ಕಹಾಕಿ, ಮತ್ತು ಅವು ದಾಟುವ threshold ಕಂಡುಹಿಡಿಯಿರಿ.\n3. ನಿಮ್ಮ synthetic data ಗೆ EER ಮೌಲ್ಯ ಮತ್ತು ಅದು ಸಂಭವಿಸುವ threshold ವರದಿ ಮಾಡಿ. ನಂತರ spoof distribution ya ಸರಾಸರಿಯನ್ನೂ genuine distribution ya ಸರಾಸರಿಗೆ ಹತ್ತಿರ ಬದಲಾಯಿಸಿ ಮತ್ತು EER ಮರುಲೆಕ್ಕಹಾಕಿ -- ಇದು ಕೆಟ್ಟದಾಗುತ್ತದೆ (ಹೆಚ್ಚಾಗುತ್ತದೆ) ಎಂದು ಖಚಿತಪಡಿಸಿ." },
  { phaseId, moduleId: m139, lessonId: l139_1, order: 2, difficulty: 'intermediate',
    title: 'Genuinely Running AASIST on Real vs. Synthetic-Voice Clips',
    titleKn: 'ನಿಜ vs. Synthetic-Voice Clips ಮೇಲೆ AASIST ಅನ್ನೂ ನಿಜವಾಗಿ ಚಲಾಯಿಸುವುದೂ',
    problem: "Genuinely load a pretrained AASIST (or similar anti-spoofing) model checkpoint.\n1. Run it on a real recorded human speech clip and report the genuine spoof-probability score it outputs.\n2. Generate a synthetic voice clip using any TTS system available to you (e.g. from Module 130), and run AASIST on that. Report the score.\n3. Does the model correctly distinguish the two in your genuine test, or does it misclassify either? If it misclassifies, is the TTS system you used simply good enough to fool the detector, or could there be a genuine bug in how you fed the audio to AASIST (sample rate mismatch, wrong preprocessing)? Investigate and report which it actually was.",
    problemKn: "ಒಂದು pretrained AASIST (ಅಥವಾ ಸಮಾನ anti-spoofing) model checkpoint ನಿಜವಾಗಿ load ಮಾಡಿ.\n1. ಇದನ್ನೂ ಒಂದು ನಿಜ ಮಾನವ speech clip ಮೇಲೆ ಚಲಾಯಿಸಿ ಮತ್ತು ಇದು ಔಟ್ಪುಟ್ ಮಾಡುವ ನಿಜ spoof-probability score ವರದಿ ಮಾಡಿ.\n2. ನಿಮಗೆ ಲಭ್ಯವಿರುವ ಯಾವುದೇ TTS system ಬಳಸಿ (ಉದಾ Module 130 ಇಂದ) ಒಂದು synthetic voice clip ರಚಿಸಿ, ಮತ್ತು ಅದರ ಮೇಲೆ AASIST ಚಲಾಯಿಸಿ. score ವರದಿ ಮಾಡಿ.\n3. model ನಿಮ್ಮ ನಿಜ test ನಲ್ಲಿ ಇವೆರಡನ್ನೂ ಸರಿಯಾಗಿ ಪ್ರತ್ಯೇಕಿಸುತ್ತದೆಯೇ, ಅಥವಾ ಒಂದನ್ನೂ ತಪ್ಪಾಗಿ ವರ್ಗೀಕರಿಸುತ್ತದೆಯೇ? ತಪ್ಪಾಗಿ ವರ್ಗೀಕರಿಸಿದರೆ, ಇದು ನಿಜ ಒಂದು bug (sample rate mismatch, ತಪ್ಪು preprocessing) ಇಂದಾಗಿಯೇ ಅಥವಾ TTS system ನಿಜವಾಗಿಯೂ detector ಮೋಸಗೊಳಿಸುವಷ್ಟು ಉತ್ತಮವೇ ಎಂದು ತನಿಖೆ ಮಾಡಿ." },
  { phaseId, moduleId: m139, lessonId: l139_1, order: 3, difficulty: 'advanced',
    title: 'Genuinely Verifying AudioSeal Watermark Robustness',
    titleKn: 'AudioSeal Watermark Robustness ಅನ್ನೂ ನಿಜವಾಗಿ ಪರಿಶೀಲಿಸುವುದೂ',
    problem: "Genuinely install and run Meta's AudioSeal (or an equivalent audio watermarking model).\n1. Watermark a real audio clip and confirm the detector correctly identifies the watermark on the unmodified watermarked audio.\n2. Apply a real, concrete degradation to the watermarked audio -- resave it as MP3 at a lower bitrate, or apply a pitch-shift, or add real background noise -- and re-run the detector. Does the watermark survive each specific degradation you tested?\n3. Report your own genuine robustness table (degradation type vs. detected/not-detected) based on what you actually measured, and identify which specific degradation (if any) defeated the watermark in your tests -- do not rely on the paper's reported numbers without confirming them yourself.",
    problemKn: "Meta ya AudioSeal (ಅಥವಾ ಸಮಾನ audio watermarking model) ಅನ್ನೂ ನಿಜವಾಗಿ install ಮಾಡಿ ಮತ್ತು ಚಲಾಯಿಸಿ.\n1. ಒಂದು ನಿಜ audio clip ಗೆ watermark ಮಾಡಿ ಮತ್ತು detector ಮಾರ್ಪಡಿಸದ watermarked audio ಮೇಲೆ watermark ಸರಿಯಾಗಿ ಗುರುತಿಸುತ್ತದೆ ಎಂದು ಖಚಿತಪಡಿಸಿ.\n2. watermarked audio ಗೆ ಒಂದು ನಿಜ, ನಿರ್ದಿಷ್ಟ degradation ಅನ್ವಯಿಸಿ (ಉದಾ ಕಡಿಮೆ bitrate ನಲ್ಲಿ MP3 ಆಗಿ ಮರುಉಳಿಸಿ, ಅಥವಾ ಒಂದು pitch-shift ಅನ್ವಯಿಸಿ, ಅಥವಾ ನಿಜ background noise ಸೇರಿಸಿ) -- ಮತ್ತು detector ಮರುಚಲಾಯಿಸಿ. watermark ನೀವು ಪರೀಕ್ಷಿಸಿದ ಪ್ರತಿ ನಿರ್ದಿಷ್ಟ degradation ಬದುಕುಳಿಯುತ್ತದೆಯೇ?\n3. ನೀವು ನಿಜವಾಗಿ ಅಳೆದ ಆಧಾರದ ಮೇಲೆ ನಿಮ್ಮ ಸ್ವಂತ ನಿಜ robustness table ವರದಿ ಮಾಡಿ, ಮತ್ತು ಯಾವ ನಿರ್ದಿಷ್ಟ degradation (ಯಾವುದಾದರೂ ಇದ್ದರೆ) ನಿಮ್ಮ ಪರೀಕ್ಷೆಗಳಲ್ಲಿ watermark ಸೋಲಿಸಿತು ಎಂದು ಗುರುತಿಸಿ." },

  // ── Module 139, Lesson 2: WaveVerify, Attacks, C2PA & Production ──
  { phaseId, moduleId: m139, lessonId: l139_2, order: 1, difficulty: 'beginner',
    title: 'Genuinely Comparing Watermark Detection Confidence Across Attacks',
    titleKn: 'Attacks ಗಳಾದ್ಯಂತ Watermark Detection Confidence ಅನ್ನೂ ನಿಜವಾಗಿ ಹೋಲಿಸುವುದೂ',
    problem: "Using a watermarked audio clip from your previous AudioSeal experiment (or a fresh one):\n1. Genuinely apply three distinct simple attacks: (a) additive Gaussian noise at a moderate SNR, (b) time-stretching by a small factor (e.g. 1.05x), and (c) low-pass filtering that removes frequencies above 4kHz.\n2. Run your watermark detector after each attack and record the real confidence score it reports for each.\n3. Rank the three attacks by how much they degraded detection confidence in your genuine test, and explain in your own words, based on how each attack works, why the most damaging one hurt the watermark more than the others (e.g. does it destroy the same frequency band the watermark lives in?).",
    problemKn: "ನಿಮ್ಮ ಹಿಂದಿನ AudioSeal ಪ್ರಯೋಗದ ಒಂದು watermarked audio clip ಬಳಸಿ (ಅಥವಾ ಒಂದು ಹೊಸ ಒಂದನ್ನೂ):\n1. ಮೂರು ವಿಭಿನ್ನ ಸರಳ attacks ಅನ್ವಯಿಸಿ: (a) ಒಂದು ಮಧ್ಯಮ SNR ನಲ್ಲಿ additive Gaussian noise, (b) ಒಂದು ಚಿಕ್ಕ factor ಮೂಲಕ time-stretching, ಮತ್ತು (c) 4kHz ಗಿಂತ ಹೆಚ್ಚಿನ frequencies ತೆಗೆದುಹಾಕುವ low-pass filtering.\n2. ಪ್ರತಿ attack ನಂತರ ನಿಮ್ಮ watermark detector ಚಲಾಯಿಸಿ ಮತ್ತು ಪ್ರತಿಯೊಂದಕ್ಕೂ ಅದು ವರದಿ ಮಾಡುವ ನಿಜ confidence score ದಾಖಲಿಸಿ.\n3. ನಿಮ್ಮ ನಿಜ test ನಲ್ಲಿ ಇವು detection confidence ಅನ್ನೂ ಎಷ್ಟು ಕುಂದಿಸಿದವು ಎಂಬುದರ ಪ್ರಕಾರ ಮೂರು attacks ಶ್ರೇಣೀಕರಿಸಿ, ಮತ್ತು ಪ್ರತಿ attack ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ ಎಂಬುದರ ಆಧಾರದ ಮೇಲೆ ಅತ್ಯಂತ ಹಾನಿಕಾರಕ ಒಂದೂ ಏಕೆ ಇತರರಿಗಿಂತ ಹೆಚ್ಚು ಹಾನಿ ಮಾಡಿತು ಎಂದು ವಿವರಿಸಿ." },
  { phaseId, moduleId: m139, lessonId: l139_2, order: 2, difficulty: 'intermediate',
    title: 'Genuinely Implementing a C2PA-Style Provenance Check',
    titleKn: 'ಒಂದು C2PA-Style Provenance Check ಅನ್ನೂ ನಿಜವಾಗಿ ಜಾರಿಗೊಳಿಸುವುದೂ',
    problem: "C2PA-style provenance embeds cryptographically signed metadata about an asset's origin and edit history.\n1. Implement a simplified version: write a Python function that computes a SHA-256 hash of an audio file, creates a small metadata dict (creation tool, timestamp, hash), and signs that dict using a real cryptographic signature (e.g. Python's `cryptography` library with an RSA or Ed25519 key pair you generate).\n2. Write a corresponding verify function that checks the signature against a public key and confirms the file's current hash matches the one in the signed metadata.\n3. Genuinely test tampering: modify even one byte of the audio file after signing, and confirm your verify function correctly detects the mismatch and rejects it. Report whether your real implementation caught the tampering.",
    problemKn: "C2PA-style provenance ಒಂದು asset ya ಮೂಲ ಮತ್ತು edit history ಬಗ್ಗೆ cryptographically ಸಹಿ ಮಾಡಿದ metadata ಅಳವಡಿಸುತ್ತದೆ.\n1. ಒಂದು ಸರಳೀಕೃತ ಆವೃತ್ತಿ ಜಾರಿಗೊಳಿಸಿ: ಒಂದು audio file ya SHA-256 hash ಲೆಕ್ಕಹಾಕುವ, ಒಂದು ಚಿಕ್ಕ metadata dict ರಚಿಸುವ, ಮತ್ತು ಒಂದು ನಿಜ cryptographic signature ಬಳಸಿ ಆ dict ಗೆ ಸಹಿ ಮಾಡುವ ಒಂದು Python function ಬರೆಯಿರಿ.\n2. ಒಂದು ಅನುಗುಣವಾದ verify function ಬರೆಯಿರಿ, ಇದು signature ಅನ್ನೂ ಒಂದು public key ವಿರುದ್ಧ ಪರಿಶೀಲಿಸುತ್ತದೆ ಮತ್ತು file ya ಪ್ರಸ್ತುತ hash ಸಹಿ ಮಾಡಿದ metadata ಯಲ್ಲಿನ ಒಂದಕ್ಕೆ ಹೊಂದಿಕೆಯಾಗುತ್ತದೆ ಎಂದು ಖಚಿತಪಡಿಸುತ್ತದೆ.\n3. tampering ಅನ್ನೂ ನಿಜವಾಗಿ ಪರೀಕ್ಷಿಸಿ: ಸಹಿ ಮಾಡಿದ ನಂತರ audio file ya ಒಂದೇ byte ಮಾರ್ಪಡಿಸಿ, ಮತ್ತು ನಿಮ್ಮ verify function ಈ ಹೊಂದಾಣಿಕೆಯಿಲ್ಲದಿರುವಿಕೆಯನ್ನೂ ಸರಿಯಾಗಿ ಪತ್ತೆಹಚ್ಚಿ ತಿರಸ್ಕರಿಸುತ್ತದೆ ಎಂದು ಖಚಿತಪಡಿಸಿ." },
  { phaseId, moduleId: m139, lessonId: l139_2, order: 3, difficulty: 'advanced',
    title: 'Building a Production Anti-Spoofing Gate with Real Trade-Off Measurement',
    titleKn: 'ನಿಜ Trade-Off Measurement ಜೊತೆ ಒಂದು Production Anti-Spoofing Gate ನಿರ್ಮಿಸುವುದೂ',
    problem: "Design and implement a production-style gate: incoming audio must pass BOTH a watermark-absence check (real audio shouldn't carry a known TTS system's watermark) AND an anti-spoofing model's genuine/spoof score above threshold to be accepted (e.g. for a voice-authentication system).\n1. Genuinely test your gate against: (a) real human speech, (b) unwatermarked synthetic speech from a TTS system, and (c) watermarked synthetic speech.\n2. Report the real accept/reject outcome for each of your three test categories.\n3. Tune your anti-spoofing threshold to minimize false rejections of real speech while measuring how that same tuning affects your false-acceptance rate on synthetic speech -- report the real numbers at two different threshold settings and explain the genuine trade-off you observed, rather than asserting one exists.",
    problemKn: "ಒಂದು production-style gate ವಿನ್ಯಾಸಗೊಳಿಸಿ ಮತ್ತು ಜಾರಿಗೊಳಿಸಿ: ಬರುವ audio ಸ್ವೀಕರಿಸಲ್ಪಡಲು ಎರಡೂ ಒಂದು watermark-absence check ಮತ್ತು threshold ಮೇಲಿನ ಒಂದು anti-spoofing model ya genuine/spoof score ಪಾಸ್ ಆಗಬೇಕು.\n1. ನಿಮ್ಮ gate ಅನ್ನೂ ಇವುಗಳ ವಿರುದ್ಧ ನಿಜವಾಗಿ ಪರೀಕ್ಷಿಸಿ: (a) ನಿಜ ಮಾನವ speech, (b) ಒಂದು TTS system ಇಂದ unwatermarked synthetic speech, ಮತ್ತು (c) watermarked synthetic speech.\n2. ನಿಮ್ಮ ಮೂರು test categories ಪ್ರತಿಯೊಂದಕ್ಕೂ ನಿಜ accept/reject ಫಲಿತಾಂಶ ವರದಿ ಮಾಡಿ.\n3. ನಿಜ speech ya false rejections ಕಡಿಮೆ ಮಾಡಲು ನಿಮ್ಮ anti-spoofing threshold ಟ್ಯೂನ್ ಮಾಡಿ, ಅದೇ ಸಮಯದಲ್ಲಿ ಅದೇ ಟ್ಯೂನಿಂಗ್ synthetic speech ಮೇಲೆ ನಿಮ್ಮ false-acceptance rate ಅನ್ನೂ ಹೇಗೆ ಬಾಧಿಸುತ್ತದೆ ಎಂದು ಅಳೆಯಿರಿ." },

  // ── Module 140, Lesson 1: WER, CER, RTFx, MOS, UTMOS & SECS ──
  { phaseId, moduleId: m140, lessonId: l140_1, order: 1, difficulty: 'beginner',
    title: 'Genuinely Computing WER and CER From Scratch',
    titleKn: 'WER ಮತ್ತು CER ಅನ್ನೂ ಮೊದಲಿನಿಂದ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕುವುದೂ',
    problem: "1. Implement Word Error Rate (WER) computation from scratch using edit distance (Levenshtein) between a reference transcript and a hypothesis transcript, at the word level, without using a pre-built library like jiwer for this first pass.\n2. Implement Character Error Rate (CER) the same way, at the character level.\n3. Test both functions on at least 3 genuine reference/hypothesis pairs you construct yourself (including one with substitutions, one with insertions, and one with deletions), and confirm your computed WER/CER values match what you'd get from the `jiwer` library on the same pairs -- report any discrepancy and debug it rather than assuming your implementation is correct.",
    problemKn: "1. ಒಂದು reference transcript ಮತ್ತು ಒಂದು hypothesis transcript ನಡುವೆ, word level ನಲ್ಲಿ, edit distance (Levenshtein) ಬಳಸಿ Word Error Rate (WER) computation ಅನ್ನೂ ಮೊದಲಿನಿಂದ ಜಾರಿಗೊಳಿಸಿ, ಈ ಮೊದಲ ಪ್ರಯತ್ನಕ್ಕೆ jiwer ನಂತಹ ಒಂದು pre-built library ಬಳಸದೆ.\n2. Character Error Rate (CER) ಅನ್ನೂ ಅದೇ ರೀತಿ, character level ನಲ್ಲಿ ಜಾರಿಗೊಳಿಸಿ.\n3. ನೀವೇ ನಿರ್ಮಿಸುವ ಕನಿಷ್ಠ 3 ನಿಜ reference/hypothesis ಜೋಡಿಗಳ ಮೇಲೆ ಎರಡೂ functions ಪರೀಕ್ಷಿಸಿ, ಮತ್ತು ನಿಮ್ಮ ಲೆಕ್ಕಹಾಕಿದ WER/CER ಮೌಲ್ಯಗಳು ಅದೇ ಜೋಡಿಗಳ ಮೇಲೆ jiwer library ಇಂದ ಸಿಗುವುದಕ್ಕೆ ಹೊಂದಿಕೆಯಾಗುತ್ತವೆ ಎಂದು ಖಚಿತಪಡಿಸಿ." },
  { phaseId, moduleId: m140, lessonId: l140_1, order: 2, difficulty: 'intermediate',
    title: 'Genuinely Measuring RTFx on Your Own Hardware',
    titleKn: 'ನಿಮ್ಮ ಸ್ವಂತ Hardware ಮೇಲೆ RTFx ಅನ್ನೂ ನಿಜವಾಗಿ ಅಳೆಯುವುದೂ',
    problem: "Real-Time Factor (RTFx) measures how many seconds of audio a model can process per second of wall-clock compute time.\n1. Genuinely time a real ASR or TTS model (any you've used earlier in this course) processing a batch of audio clips with known total duration, using time.perf_counter() around the actual inference call, not including model-loading time.\n2. Compute RTFx = (total audio duration) / (total processing time). Report your real measured value on your own hardware (CPU or GPU, state which).\n3. Re-run the same measurement with a larger batch size (if your model/pipeline supports batching) and report whether RTFx improves, stays the same, or gets worse -- and explain the real bottleneck you observed (e.g. did GPU utilization increase, or did you hit a memory/CPU ceiling?).",
    problemKn: "Real-Time Factor (RTFx) ಒಂದು model ಪ್ರತಿ ಸೆಕೆಂಡ್ wall-clock compute time ಗೆ ಎಷ್ಟು ಸೆಕೆಂಡುಗಳ audio ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಬಹುದು ಎಂದು ಅಳೆಯುತ್ತದೆ.\n1. ಒಂದು ನಿಜ ASR ಅಥವಾ TTS model (ಈ course ನಲ್ಲಿ ಮೊದಲು ಬಳಸಿದ ಯಾವುದಾದರೂ) ಒಂದು known total duration ಇರುವ audio clips ya ಒಂದು batch ಪ್ರಕ್ರಿಯೆಗೊಳಿಸುವುದನ್ನೂ ನಿಜವಾಗಿ ಸಮಯ ಅಳೆಯಿರಿ.\n2. RTFx = (ಒಟ್ಟು audio duration) / (ಒಟ್ಟು processing time) ಲೆಕ್ಕಹಾಕಿ. ನಿಮ್ಮ ಸ್ವಂತ hardware ಮೇಲೆ ನಿಮ್ಮ ನಿಜ ಅಳೆದ ಮೌಲ್ಯ ವರದಿ ಮಾಡಿ.\n3. ಅದೇ ಅಳತೆಯನ್ನೂ ಒಂದು ದೊಡ್ಡ batch size ಜೊತೆ ಮರುಚಲಾಯಿಸಿ ಮತ್ತು RTFx ಸುಧಾರಿಸುತ್ತದೆಯೇ, ಅದೇ ಆಗಿ ಉಳಿಯುತ್ತದೆಯೇ, ಅಥವಾ ಕೆಟ್ಟದಾಗುತ್ತದೆಯೇ ಎಂದು ವರದಿ ಮಾಡಿ -- ಮತ್ತು ನೀವು ಗಮನಿಸಿದ ನಿಜ bottleneck ವಿವರಿಸಿ." },
  { phaseId, moduleId: m140, lessonId: l140_1, order: 3, difficulty: 'advanced',
    title: 'Genuinely Running UTMOS and Comparing to Real Human MOS Judgment',
    titleKn: 'UTMOS ಅನ್ನೂ ನಿಜವಾಗಿ ಚಲಾಯಿಸುವುದೂ ಮತ್ತು ನಿಜ Human MOS Judgment ಜೊತೆ ಹೋಲಿಸುವುದೂ',
    problem: "1. Genuinely install and run UTMOS (an automatic MOS-prediction model) on 5 audio clips of varying quality (e.g. clean TTS output, a degraded/noisy version of the same, and a real human recording).\n2. Independently, listen to the same 5 clips yourself and assign your own 1-5 MOS-style quality rating to each, before looking at UTMOS's scores.\n3. Compare your own human ratings to UTMOS's predicted scores for all 5 clips. Compute the correlation (even a simple rank correlation by hand) between the two. Report where UTMOS's automatic score agreed with your genuine human judgment and where it diverged, and speculate concretely (based on the specific clips where they disagreed) about why an automatic MOS predictor might miss what a human notices.",
    problemKn: "1. UTMOS (ಒಂದು automatic MOS-prediction model) ಅನ್ನೂ ವಿಭಿನ್ನ quality ya 5 audio clips ಮೇಲೆ ನಿಜವಾಗಿ install ಮಾಡಿ ಮತ್ತು ಚಲಾಯಿಸಿ.\n2. ಸ್ವತಂತ್ರವಾಗಿ, UTMOS ya scores ನೋಡುವ ಮೊದಲು ಅದೇ 5 clips ಸ್ವತಃ ಆಲಿಸಿ ಮತ್ತು ಪ್ರತಿಯೊಂದಕ್ಕೂ ನಿಮ್ಮ ಸ್ವಂತ 1-5 MOS-style quality rating ನೀಡಿ.\n3. ನಿಮ್ಮ ಸ್ವಂತ ಮಾನವ ratings ಅನ್ನೂ ಎಲ್ಲಾ 5 clips ಗೆ UTMOS ya ಊಹಿಸಿದ scores ಜೊತೆ ಹೋಲಿಸಿ. ಎರಡರ ನಡುವೆ correlation ಲೆಕ್ಕಹಾಕಿ. UTMOS ya automatic score ನಿಮ್ಮ ನಿಜ ಮಾನವ ತೀರ್ಪಿನೊಂದಿಗೆ ಎಲ್ಲಿ ಒಪ್ಪಿಗೆ ಪಡೆಯಿತು ಮತ್ತು ಎಲ್ಲಿ ಭಿನ್ನವಾಯಿತು ಎಂದು ವರದಿ ಮಾಡಿ." },

  // ── Module 140, Lesson 2: Speaker Verification, Diarization, Music, Audio-LMs & Leaderboards ──
  { phaseId, moduleId: m140, lessonId: l140_2, order: 1, difficulty: 'beginner',
    title: 'Genuinely Computing Speaker Verification EER on Your Own Voice Pairs',
    titleKn: 'ನಿಮ್ಮ ಸ್ವಂತ Voice Pairs ಮೇಲೆ Speaker Verification EER ಅನ್ನೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕುವುದೂ',
    problem: "Using a pretrained speaker-embedding model (e.g. from a speaker recognition library you used in Module 129):\n1. Record or collect at least 2 clips each from 3 different speakers (or use a public dataset if you can't record real audio), and compute pairwise embedding similarity (cosine similarity) for every same-speaker pair and every different-speaker pair.\n2. Genuinely compute Speaker Verification EER using these real similarity scores, following the same threshold-sweep procedure as your anti-spoofing EER exercise.\n3. Report the real EER for your specific small dataset, and explain concretely (based on which pairs had confusingly similar or dissimilar scores) which speaker pairs were hardest for the embedding model to distinguish, and speculate on a concrete reason (similar vocal pitch, similar accent, recording condition differences).",
    problemKn: "ಒಂದು pretrained speaker-embedding model ಬಳಸಿ:\n1. 3 ವಿಭಿನ್ನ speakers ಇಂದ ಪ್ರತಿಯೊಂದಕ್ಕೂ ಕನಿಷ್ಠ 2 clips ರೆಕಾರ್ಡ್ ಅಥವಾ ಸಂಗ್ರಹಿಸಿ, ಮತ್ತು ಪ್ರತಿ same-speaker ಜೋಡಿ ಮತ್ತು ಪ್ರತಿ ವಿಭಿನ್ನ-speaker ಜೋಡಿಗೆ pairwise embedding similarity ಲೆಕ್ಕಹಾಕಿ.\n2. ಈ ನಿಜ similarity scores ಬಳಸಿ Speaker Verification EER ಅನ್ನೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕಿ, ನಿಮ್ಮ anti-spoofing EER ವ್ಯಾಯಾಮದಂತೆ ಅದೇ threshold-sweep ವಿಧಾನ ಅನುಸರಿಸಿ.\n3. ನಿಮ್ಮ ನಿರ್ದಿಷ್ಟ ಚಿಕ್ಕ dataset ಗೆ ನಿಜ EER ವರದಿ ಮಾಡಿ, ಮತ್ತು embedding model ಗೆ ಪ್ರತ್ಯೇಕಿಸಲು ಯಾವ speaker ಜೋಡಿಗಳು ಅತ್ಯಂತ ಕಷ್ಟಕರವಾಗಿದ್ದವು ಎಂದು ನಿರ್ದಿಷ್ಟವಾಗಿ ವಿವರಿಸಿ." },
  { phaseId, moduleId: m140, lessonId: l140_2, order: 2, difficulty: 'intermediate',
    title: 'Genuinely Computing Diarization Error Rate (DER)',
    titleKn: 'Diarization Error Rate (DER) ಅನ್ನೂ ನಿಜವಾಗಿ ಲೆಕ್ಕಹಾಕುವುದೂ',
    problem: "1. Construct a genuine ground-truth speaker timeline for a short (30-60 second) multi-speaker audio clip you create yourself (e.g. record or simulate two people alternating), specifying exact start/end times for each speaker turn.\n2. Run a real diarization pipeline (e.g. pyannote.audio) on this clip and extract its predicted speaker segments.\n3. Genuinely implement DER computation (or use pyannote's metric tools) comparing your ground truth to the prediction, accounting for missed speech, false alarm speech, and speaker confusion separately. Report the real DER and break down which of the three error components contributed most in your specific test clip.",
    problemKn: "1. ನೀವೇ ರಚಿಸುವ ಒಂದು ಚಿಕ್ಕ (30-60 ಸೆಕೆಂಡ್) multi-speaker audio clip ಗೆ ಒಂದು ನಿಜ ground-truth speaker timeline ನಿರ್ಮಿಸಿ, ಪ್ರತಿ speaker turn ಗೆ ನಿಖರ start/end times ನಿರ್ದಿಷ್ಟಪಡಿಸಿ.\n2. ಈ clip ಮೇಲೆ ಒಂದು ನಿಜ diarization pipeline (ಉದಾ pyannote.audio) ಚಲಾಯಿಸಿ ಮತ್ತು ಅದರ ಊಹಿಸಿದ speaker segments ಹೊರತೆಗೆಯಿರಿ.\n3. ನಿಮ್ಮ ground truth ಅನ್ನೂ ಊಹೆಯೊಂದಿಗೆ ಹೋಲಿಸುವ DER computation ಅನ್ನೂ ನಿಜವಾಗಿ ಜಾರಿಗೊಳಿಸಿ (ಅಥವಾ pyannote ya metric tools ಬಳಸಿ), missed speech, false alarm speech, ಮತ್ತು speaker confusion ಪ್ರತ್ಯೇಕವಾಗಿ ಲೆಕ್ಕಹಾಕಿ. ನಿಜ DER ವರದಿ ಮಾಡಿ." },
  { phaseId, moduleId: m140, lessonId: l140_2, order: 3, difficulty: 'advanced',
    title: 'Building a Genuine Multi-Metric Evaluation Report Across This Phase',
    titleKn: 'ಈ Phase ಗಳಾದ್ಯಂತ ಒಂದು ನಿಜ Multi-Metric Evaluation Report ನಿರ್ಮಿಸುವುದೂ',
    problem: "Pick any one real model you've genuinely run somewhere in this phase (an ASR model, a TTS model, a music generator, or an audio-language model).\n1. Identify at least 3 distinct evaluation metrics from this module (e.g. for ASR: WER, CER, RTFx; for TTS: UTMOS, SECS, RTFx; for an audio-LM: MMAU-Pro-style accuracy plus latency) that are actually appropriate for that model's task.\n2. Genuinely run all 3 metrics on a real, consistent test set you construct (even a small one, e.g. 10 clips), and report the real numbers for each metric.\n3. Write a one-paragraph genuine evaluation summary of your chosen model based ONLY on the numbers you actually measured -- explicitly state which of the 3 metrics agreed with each other in their verdict on quality and which, if any, told a different story, and explain why relying on a single metric would have given an incomplete picture for this specific model.",
    problemKn: "ಈ phase ನಲ್ಲಿ ಎಲ್ಲೋ ನೀವು ನಿಜವಾಗಿ ಚಲಾಯಿಸಿದ ಯಾವುದಾದರೂ ಒಂದು ನಿಜ model ಆಯ್ಕೆ ಮಾಡಿ.\n1. ಆ model ya ಕಾರ್ಯಕ್ಕೆ ನಿಜವಾಗಿ ಸೂಕ್ತವಾದ ಈ module ಇಂದ ಕನಿಷ್ಠ 3 ವಿಭಿನ್ನ evaluation metrics ಗುರುತಿಸಿ.\n2. ನೀವು ನಿರ್ಮಿಸುವ ಒಂದು ನಿಜ, ಸ್ಥಿರ test set ಮೇಲೆ (ಒಂದು ಚಿಕ್ಕ ಒಂದಾದರೂ, ಉದಾ 10 clips) ಎಲ್ಲಾ 3 metrics ನಿಜವಾಗಿ ಚಲಾಯಿಸಿ, ಮತ್ತು ಪ್ರತಿ metric ಗೆ ನಿಜ ಸಂಖ್ಯೆಗಳನ್ನೂ ವರದಿ ಮಾಡಿ.\n3. ನೀವು ನಿಜವಾಗಿ ಅಳೆದ ಸಂಖ್ಯೆಗಳ ಆಧಾರದ ಮೇಲೆ ಮಾತ್ರ ನಿಮ್ಮ ಆಯ್ಕೆಯ model ya ಒಂದು ನಿಜ evaluation ಸಾರಾಂಶ ಬರೆಯಿರಿ -- 3 metrics ಗಳಲ್ಲಿ ಯಾವುದೂ quality ಬಗ್ಗೆ ಪರಸ್ಪರ ಒಪ್ಪಿಗೆ ಪಡೆಯಿತು ಮತ್ತು ಯಾವುದಾದರೂ ಭಿನ್ನ ಕಥೆ ಹೇಳಿತು ಎಂದು ಸ್ಪಷ್ಟವಾಗಿ ಹೇಳಿ." },
];
