const phaseId = '6a369d6066020ed05b32150b'; // Phase 17: Agent Engineering

const m273 = '6a369d6066020ed05b32150e';
const m274 = '6a369d6066020ed05b321511';
const m275 = '6a369d6066020ed05b321514';
const m276 = '6a369d6066020ed05b321517';
const m277 = '6a369d6066020ed05b32151a';
const m278 = '6a369d6066020ed05b32151d';

const l273 = '6aaaff764a89d5bb289a0413';
const l274 = '6aab00239335ff8b8b28aaae';
const l275 = '6aab00aa6090a3233946cbc4';
const l276 = '6aab016d81eef229a1888f76';
const l277 = '6aab0260015dcd30791cf05d';
const l278 = '6aab02eb6107a8dced194311';

module.exports = [
  // ── Module 273: The Agent Loop ──
  { phaseId, moduleId: m273, lessonId: l273, order: 1, difficulty: 'intermediate',
    title: 'Genuinely Tracing Thought-Action-Observation',
    titleKn: 'Thought-Action-Observation ಅನ್ನೂ ನಿಜವಾಗಿ ಪತ್ತೆಹಚ್ಚುವುದೂ',
    problem: "The lesson's policy genuinely ran a 5-step trace: THOUGHT, ACTION lookup('capital of France')->Paris, THOUGHT, ACTION calculator('len(\"Paris\") * 6')->30, then FINAL.\n1. Run the lesson's exact policy and run_agent_loop and confirm the same 5-step trace ending with the answer 30.\n2. Trace the arithmetic: 'Paris' has 5 letters, so len('Paris')*6 = 30. Modify the task to use 'largest planet' (Jupiter, 7 letters) multiplied by 6 instead, and predict the new final answer before running it.\n3. Why does the loop alternate strictly between THOUGHT, ACTION, and OBSERVATION rather than, say, taking two actions in a row? What would be lost if a policy skipped straight from one action to another without an intervening thought?",
    problemKn: "ಪಾಠದ policy ನಿಜವಾಗಿ ಒಂದೂ 5-step trace ಚಲಾಯಿಸಿತು: THOUGHT, ACTION lookup->Paris, THOUGHT, ACTION calculator->30, FINAL.\n1. ಪಾಠದ ನಿಖರ policy ಮತ್ತು run_agent_loop ಚಲಾಯಿಸಿ ಮತ್ತು ಅದೇ 5-step trace ಖಚಿತಪಡಿಸಿ.\n2. ಅಂಕಗಣಿತ ಪತ್ತೆಹಚ್ಚಿ: 'Paris' 5 ಅಕ್ಷರಗಳು, ಆದ್ದರಿಂದ len('Paris')*6 = 30. task ಅನ್ನೂ 'largest planet' (Jupiter, 7 ಅಕ್ಷರಗಳು) ಬಳಸುವಂತೆ ಮಾರ್ಪಡಿಸಿ ಮತ್ತು ಹೊಸ ಅಂತಿಮ ಉತ್ತರ ಊಹಿಸಿ.\n3. loop ಏಕೆ THOUGHT, ACTION, ಮತ್ತು OBSERVATION ನಡುವೆ ಕಟ್ಟುನಿಟ್ಟಾಗಿ ಪರ್ಯಾಯವಾಗಿ ಬದಲಾಗುತ್ತದೆ?" },
  { phaseId, moduleId: m273, lessonId: l273, order: 2, difficulty: 'intermediate',
    title: "Genuinely Hitting the Missing-Builtin Bug",
    titleKn: "Missing-Builtin Bug ಅನ್ನೂ ನಿಜವಾಗಿ ಎದುರಿಸುವುದೂ",
    problem: "The lesson's calculator_broken (which omits 'len' from the eval() builtins dict) genuinely raised NameError: name 'len' is not defined when trying to compute len(\"Paris\") * 6.\n1. Run the lesson's exact calculator_broken and confirm the NameError.\n2. Compare calculator_broken's builtins dict to the working calculator's ({'__builtins__': {}, 'len': len}). What's the exact one-item difference that causes the bug?\n3. eval() with a restricted builtins dict is a genuine security pattern (limiting what code run via eval can access). Given that, is REMOVING len from the sandbox a design choice error or a security feature working as intended for a tool that shouldn't need len? Argue both sides.",
    problemKn: "ಪಾಠದ calculator_broken (eval() builtins dict ಇಂದ 'len' ಬಿಟ್ಟುಬಿಡುತ್ತದೆ) ನಿಜವಾಗಿ NameError ಎಬ್ಬಿಸಿತು.\n1. ಪಾಠದ ನಿಖರ calculator_broken ಚಲಾಯಿಸಿ ಮತ್ತು NameError ಖಚಿತಪಡಿಸಿ.\n2. calculator_broken ya builtins dict ಅನ್ನೂ ಕೆಲಸ ಮಾಡುವ calculator ya ಜೊತೆ ಹೋಲಿಸಿ. ನಿಖರ ಒಂದೂ-ಐಟಂ ವ್ಯತ್ಯಾಸ ಏನೂ?\n3. eval() ಸೀಮಿತ builtins dict ಜೊತೆ ಒಂದೂ ನಿಜ ಭದ್ರತಾ ಮಾದರಿ. len ಅನ್ನೂ sandbox ಇಂದ ತೆಗೆಯುವುದೂ ಒಂದೂ ವಿನ್ಯಾಸ ದೋಷವೇ ಅಥವಾ ಉದ್ದೇಶಪೂರ್ವಕ ಭದ್ರತಾ ವೈಶಿಷ್ಟ್ಯವೇ? ಎರಡೂ ಬದಿಗಳನ್ನೂ ವಾದಿಸಿ." },
  { phaseId, moduleId: m273, lessonId: l273, order: 3, difficulty: 'advanced',
    title: 'The Runaway Loop, Genuinely Reproduced',
    titleKn: 'Runaway Loop, ನಿಜವಾಗಿ ಮರುಉತ್ಪಾದಿಸಲಾಗಿದೆ',
    problem: "The lesson's broken_policy genuinely re-issued the identical action (calculator('1 + 1') -> 2) on EVERY step, never reaching a final state, for all 6 max_steps before the loop was forced to stop.\n1. Run the lesson's exact broken_policy through run_agent_loop(max_steps=6) and confirm all 6 steps produce the identical action/observation pair.\n2. Why does the loop need an explicit max_steps safety limit? What would happen to a real production agent (running against a real API, potentially costing money per call) if this limit didn't exist and the policy genuinely never terminated?\n3. Design a genuine fix for broken_policy: modify it so that after seeing the SAME observation twice in a row, it forces a 'final' response instead of repeating. Implement and test your fix.",
    problemKn: "ಪಾಠದ broken_policy ಪ್ರತಿ step ನಲ್ಲಿ ನಿಖರ identical action ಅನ್ನೂ ನಿಜವಾಗಿ ಮರುಜಾರಿಗೊಳಿಸಿತು, ಎಂದಿಗೂ ಒಂದೂ final state ತಲುಪಲಿಲ್ಲ.\n1. ಪಾಠದ ನಿಖರ broken_policy ಅನ್ನೂ run_agent_loop(max_steps=6) ಮೂಲಕ ಚಲಾಯಿಸಿ.\n2. loop ಗೆ ಒಂದೂ ಸ್ಪಷ್ಟ max_steps safety limit ಏಕೆ ಬೇಕು?\n3. broken_policy ಗೆ ಒಂದೂ ನಿಜ ಪರಿಹಾರ ವಿನ್ಯಾಸಗೊಳಿಸಿ: ಅದೇ observation ಸತತವಾಗಿ ಎರಡು ಬಾರಿ ಕಂಡ ನಂತರ ಒಂದೂ 'final' response ಒತ್ತಾಯಿಸುವಂತೆ ಮಾರ್ಪಡಿಸಿ." },

  // ── Module 274: ReWOO and Plan-and-Execute ──
  { phaseId, moduleId: m274, lessonId: l274, order: 1, difficulty: 'intermediate',
    title: "Genuinely Cutting Policy Calls From 5 to 1",
    titleKn: "Policy Calls ಅನ್ನೂ 5 ಇಂದ 1 ಗೆ ನಿಜವಾಗಿ ಕಡಿಮೆಗೊಳಿಸುವುದೂ",
    problem: "The lesson genuinely confirmed ReAct-style (Module 273) needed 5 policy calls for a comparable task, while ReWOO's plan (#E1 lookup, #E2 lookup, #E3 calculator on len(#E1)+len(#E2)) needed only 1 planning LLM call, then executed all 3 tool steps with ZERO further LLM calls, reaching final answer 12.\n1. Run the lesson's exact PLAN and run_rewoo, confirming #E1=Paris, #E2=Jupiter, #E3=12 (len('Paris')=5 + len('Jupiter')=7 = 12).\n2. Why does planning everything upfront in ONE call save so many LLM calls compared to ReAct's interleaved thought-action-observation? What's the fundamental tradeoff being made?\n3. Verify the arithmetic yourself: is 5+7=12 correct? Modify the plan to add a 4th evidence variable that also depends on #E3, and confirm the reference-substitution logic correctly plugs in #E3's computed value.",
    problemKn: "ಪಾಠ ನಿಜವಾಗಿ ಖಚಿತಪಡಿಸಿತು ReAct-style (Module 273) ಗೆ 5 policy calls ಬೇಕಾಗಿತ್ತು, ಆದರೆ ReWOO ya plan ಕೇವಲ 1 planning LLM call ಬೇಕಾಯಿತು, ನಂತರ ಎಲ್ಲಾ 3 tool steps ಶೂನ್ಯ ಹೆಚ್ಚುವರಿ LLM calls ಜೊತೆ ಚಲಾಯಿಸಿತು.\n1. ಪಾಠದ ನಿಖರ PLAN ಮತ್ತು run_rewoo ಚಲಾಯಿಸಿ, #E1=Paris, #E2=Jupiter, #E3=12 ಖಚಿತಪಡಿಸಿ.\n2. ಎಲ್ಲವೂ ಮುಂಚಿತವಾಗಿ ONE call ನಲ್ಲಿ ಯೋಜಿಸುವುದೂ ReAct ya interleaved loop ಗೆ ಹೋಲಿಸಿದರೆ ಎಷ್ಟೂ LLM calls ಉಳಿಸುತ್ತದೆ?\n3. ಅಂಕಗಣಿತ ನೀವೇ ಪರಿಶೀಲಿಸಿ: 5+7=12 ಸರಿಯೇ? #E3 ಮೇಲೆ ಅವಲಂಬಿಸಿರುವ 4ನೇ evidence variable ಸೇರಿಸಿ plan ಮಾರ್ಪಡಿಸಿ." },
  { phaseId, moduleId: m274, lessonId: l274, order: 2, difficulty: 'advanced',
    title: 'The Real Cost: A Plan That Cannot Adapt',
    titleKn: 'ನಿಜ ವೆಚ್ಚ: Adapt ಆಗಲಾಗದ ಒಂದೂ Plan',
    problem: "The lesson's PLAN_BAD genuinely computed on a bad value: lookup('capital of atlantis') returned 'unknown', but the plan blindly proceeded to calculate len('unknown')*2=14 as if 'unknown' were a real answer -- a genuinely wrong final result the plan never caught because it can't adapt mid-execution.\n1. Run the lesson's exact PLAN_BAD through run_rewoo and confirm the wrong final answer of 14.\n2. Why is this specifically a consequence of ReWOO's 'plan everything upfront, then execute blindly' design, rather than a bug in the lookup or calculator tools themselves?\n3. Run the lesson's guarded fix (run_rewoo_guarded) and confirm it correctly halts at #E2 instead of computing on the bad 'unknown' value. What's the tradeoff of adding this guard -- does it bring back any of ReAct's per-step flexibility?",
    problemKn: "ಪಾಠದ PLAN_BAD ಒಂದೂ ಕೆಟ್ಟ ಮೌಲ್ಯದ ಮೇಲೆ ನಿಜವಾಗಿ ಲೆಕ್ಕಾಚಾರ ಮಾಡಿತು: lookup('capital of atlantis') 'unknown' ಹಿಂತಿರುಗಿಸಿತು, ಆದರೆ plan ಕುರುಡಾಗಿ len('unknown')*2=14 ಲೆಕ್ಕಾಚಾರ ಮಾಡಿತು.\n1. ಪಾಠದ ನಿಖರ PLAN_BAD ಅನ್ನೂ run_rewoo ಮೂಲಕ ಚಲಾಯಿಸಿ ಮತ್ತು ತಪ್ಪಾದ ಅಂತಿಮ ಉತ್ತರ 14 ಖಚಿತಪಡಿಸಿ.\n2. ಇದೂ ನಿರ್ದಿಷ್ಟವಾಗಿ ReWOO ya 'ಮುಂಚಿತವಾಗಿ ಎಲ್ಲವೂ ಯೋಜಿಸಿ, ನಂತರ ಕುರುಡಾಗಿ ಚಲಾಯಿಸಿ' ವಿನ್ಯಾಸದ ಪರಿಣಾಮ ಏಕೆ?\n3. ಪಾಠದ guarded fix (run_rewoo_guarded) ಚಲಾಯಿಸಿ ಮತ್ತು ಇದೂ ಸರಿಯಾಗಿ #E2 ನಲ್ಲಿ ನಿಲ್ಲುತ್ತದೆ ಎಂದು ಖಚಿತಪಡಿಸಿ. ಈ guard ಸೇರಿಸುವುದೂ ReAct ya ಯಾವುದೇ flexibility ಮರಳಿ ತರುತ್ತದೆಯೇ?" },
  { phaseId, moduleId: m274, lessonId: l274, order: 3, difficulty: 'beginner',
    title: 'Choosing ReAct vs ReWOO for a New Task',
    titleKn: 'ಒಂದೂ ಹೊಸ Task ಗೆ ReAct vs ReWOO ಆಯ್ಕೆ ಮಾಡುವುದೂ',
    problem: "1. Based on Module 273 (ReAct, 5 calls, but able to adapt after every observation) and Module 274 (ReWOO, 1 call, but can't adapt mid-plan), design a decision rule: given a new task, what property of the task would push you toward ReAct, and what property would push you toward ReWOO?\n2. For a task like 'book a flight, then based on the price, either book a hotel or suggest cheaper flight dates', which pattern is more appropriate? Justify using the genuine PLAN_BAD failure you just reproduced.\n3. For a task like 'look up 5 independent facts and compute their total word count', which pattern is more appropriate, and would ReWOO's inability to adapt actually cost you anything for THIS particular task?",
    problemKn: "1. Module 273 (ReAct, 5 calls, ಪ್ರತಿ observation ನಂತರ adapt ಆಗಬಹುದು) ಮತ್ತು Module 274 (ReWOO, 1 call, mid-plan adapt ಆಗಲಾಗುವುದಿಲ್ಲ) ಆಧರಿಸಿ, ಒಂದೂ ನಿರ್ಧಾರ ನಿಯಮ ವಿನ್ಯಾಸಗೊಳಿಸಿ.\n2. 'ಒಂದೂ flight book ಮಾಡಿ, ನಂತರ ಬೆಲೆ ಆಧರಿಸಿ ಒಂದೂ hotel book ಮಾಡಿ ಅಥವಾ ಅಗ್ಗದ flight dates ಸೂಚಿಸಿ' ಎಂಬ task ಗೆ ಯಾವ ಮಾದರಿ ಹೆಚ್ಚು ಸೂಕ್ತ?\n3. '5 ಸ್ವತಂತ್ರ facts ನೋಡಿ ಅವುಗಳ ಒಟ್ಟೂ word count ಲೆಕ್ಕಾಚಾರ ಮಾಡಿ' ಎಂಬ task ಗೆ, ReWOO ya adapt ಮಾಡಲಾಗದಿರುವಿಕೆ ಈ ನಿರ್ದಿಷ್ಟ task ಗೆ ನಿಜವಾಗಿ ಯಾವುದೇ ವೆಚ್ಚ ತರುತ್ತದೆಯೇ?" },

  // ── Module 275: Reflexion ──
  { phaseId, moduleId: m275, lessonId: l275, order: 1, difficulty: 'intermediate',
    title: 'Genuinely Fixing a Wrong Answer With a Self-Written Critique',
    titleKn: 'ಒಂದೂ Self-Written Critique ಜೊತೆ ತಪ್ಪಾದ ಉತ್ತರ ನಿಜವಾಗಿ ಸರಿಪಡಿಸುವುದೂ',
    problem: "The lesson genuinely solved '2 + 3 * 4' with target=20: attempt 1 (no hint) got 14 (standard precedence), the agent wrote its own reflection about needing parentheses, and attempt 2 (using hint='use_parens', computing (2+3)*4) got exactly 20, succeeding.\n1. Run the lesson's exact solve_attempt, reflect, and 2-attempt sequence and confirm attempt 1 fails with 14 and attempt 2 succeeds with 20.\n2. Verify the arithmetic by hand: 2+3*4=14 (standard precedence) vs (2+3)*4=20. Why does the reflection specifically suggest parentheses rather than some other fix, given the target value 20 and the wrong value 14?\n3. The reflection text becomes a HINT fed into attempt 2. In a real LLM-based Reflexion system, the reflection would be natural language fed back into the model's next prompt rather than a hardcoded string match. What genuine failure mode could arise if the LLM's self-written reflection were vague or unhelpful?",
    problemKn: "ಪಾಠ ನಿಜವಾಗಿ '2 + 3 * 4' ಅನ್ನೂ target=20 ಜೊತೆ ಪರಿಹರಿಸಿತು: attempt 1 14 ಪಡೆಯಿತು, agent ಒಂದೂ ಸ್ವಂತ reflection ಬರೆಯಿತು, attempt 2 ನಿಖರವಾಗಿ 20 ಪಡೆಯಿತು.\n1. ಪಾಠದ ನಿಖರ solve_attempt, reflect, ಮತ್ತು 2-attempt ಅನುಕ್ರಮ ಚಲಾಯಿಸಿ.\n2. ಕೈಯಾರೆ ಅಂಕಗಣಿತ ಪರಿಶೀಲಿಸಿ: 2+3*4=14 vs (2+3)*4=20. reflection ನಿರ್ದಿಷ್ಟವಾಗಿ parentheses ಸೂಚಿಸುವುದೂ ಏಕೆ?\n3. ಒಂದೂ ನಿಜ LLM-based Reflexion system ನಲ್ಲಿ, LLM ya ಸ್ವಂತ-ಬರೆದ reflection ಅಸ್ಪಷ್ಟ ಅಥವಾ ಸಹಾಯಕವಲ್ಲದಿದ್ದರೆ ಯಾವ ನಿಜ ವೈಫಲ್ಯ ಮಾದರಿ ಉಂಟಾಗಬಹುದು?" },
  { phaseId, moduleId: m275, lessonId: l275, order: 2, difficulty: 'beginner',
    title: 'Without Reflection, the Same Wrong Answer Forever',
    titleKn: 'Reflection ಇಲ್ಲದೆ, ಅದೇ ತಪ್ಪಾದ ಉತ್ತರ ಶಾಶ್ವತವಾಗಿ',
    problem: "The lesson genuinely ran 5 attempts with hint=None every time (never reflecting), and got result=14 (failure) all 5 times identically -- proving without reflection, an agent can repeat the exact same mistake indefinitely.\n1. Run the lesson's exact 5-attempt no-reflection loop and confirm all 5 attempts produce the identical wrong result.\n2. Why is 'trying again' without any change to the approach fundamentally different from Reflexion's 'trying again WITH a stored critique'? What's the minimal ingredient reflection adds that pure retrying lacks?\n3. Run the lesson's bounded run_reflexion(max_attempts=3) and confirm it reports 'success at attempt 2', connecting the reflection mechanism you traced in the previous exercise to this bounded-loop wrapper.",
    problemKn: "ಪಾಠ ನಿಜವಾಗಿ 5 attempts ಅನ್ನೂ hint=None ಜೊತೆ ಚಲಾಯಿಸಿ (ಎಂದಿಗೂ reflect ಮಾಡದೆ), ಎಲ್ಲಾ 5 ಬಾರಿ ಒಂದೇ result=14 (ವೈಫಲ್ಯ) ಪಡೆಯಿತು.\n1. ಪಾಠದ ನಿಖರ 5-attempt no-reflection loop ಚಲಾಯಿಸಿ ಮತ್ತು ಎಲ್ಲಾ 5 attempts ಒಂದೇ ತಪ್ಪಾದ ಫಲಿತಾಂಶ ಉತ್ಪಾದಿಸುತ್ತವೆ ಎಂದು ಖಚಿತಪಡಿಸಿ.\n2. ವಿಧಾನಕ್ಕೆ ಯಾವುದೇ ಬದಲಾವಣೆ ಇಲ್ಲದೆ 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸುವುದೂ' Reflexion ya 'ಸಂಗ್ರಹಿಸಿದ critique ಜೊತೆ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸುವುದೂ' ಗಿಂತ ಮೂಲಭೂತವಾಗಿ ಏಕೆ ಭಿನ್ನ?\n3. ಪಾಠದ ಬೌಂಡೆಡ್ run_reflexion(max_attempts=3) ಚಲಾಯಿಸಿ ಮತ್ತು 'success at attempt 2' ವರದಿ ಮಾಡುತ್ತದೆ ಎಂದು ಖಚಿತಪಡಿಸಿ." },
  { phaseId, moduleId: m275, lessonId: l275, order: 3, difficulty: 'intermediate',
    title: 'Where Reflexion Fits Among This Phase\'s Patterns',
    titleKn: 'ಈ Phase ya Patterns ನಡುವೆ Reflexion ಎಲ್ಲಿ ಹೊಂದಿಕೊಳ್ಳುತ್ತದೆ',
    problem: "1. Compare Reflexion (Module 275) to ReWOO (Module 274): ReWOO plans once and executes blindly, while Reflexion retries with accumulated critiques. Could you combine them -- e.g. a ReWOO plan that, upon failure, triggers a Reflexion-style retry with a new plan informed by what went wrong? Sketch this hybrid.\n2. Reflexion's memory (the list of past reflections) grows across attempts. What would happen to run_reflexion's behavior if max_attempts were set very high (e.g. 100) for a task that's fundamentally unsolvable by this approach -- would memory accumulation help or just waste calls?\n3. Design your own small failing task (different from '2+3*4') where a single wrong attempt plus a well-written reflection would genuinely fix the mistake on attempt 2, similar to the lesson's example.",
    problemKn: "1. Reflexion (Module 275) ಅನ್ನೂ ReWOO (Module 274) ಜೊತೆ ಹೋಲಿಸಿ: ReWOO ಒಮ್ಮೆ ಯೋಜಿಸಿ ಕುರುಡಾಗಿ ಚಲಾಯಿಸುತ್ತದೆ, Reflexion ಸಂಗ್ರಹಿಸಿದ critiques ಜೊತೆ ಮರುಪ್ರಯತ್ನಿಸುತ್ತದೆ. ಇವೆರಡನ್ನೂ ಸಂಯೋಜಿಸಬಹುದೇ?\n2. run_reflexion ya max_attempts ಬಹಳ ಹೆಚ್ಚಾಗಿದ್ದರೆ (ಉದಾ 100) ಒಂದೂ ಮೂಲಭೂತವಾಗಿ ಪರಿಹರಿಸಲಾಗದ task ಗೆ ಏನಾಗುತ್ತದೆ?\n3. ಒಂದೂ ತಪ್ಪಾದ ಪ್ರಯತ್ನ ಮತ್ತು ಒಂದೂ ಚೆನ್ನಾಗಿ ಬರೆದ reflection attempt 2 ರಲ್ಲಿ ತಪ್ಪನ್ನೂ ನಿಜವಾಗಿ ಸರಿಪಡಿಸುವ ನಿಮ್ಮ ಸ್ವಂತ ಚಿಕ್ಕ ವಿಫಲಗೊಳ್ಳುವ task ವಿನ್ಯಾಸಗೊಳಿಸಿ." },

  // ── Module 276: Tree of Thoughts and LATS ──
  { phaseId, moduleId: m276, lessonId: l276, order: 1, difficulty: 'intermediate',
    title: 'Genuinely Finding an Exact Answer a Greedy Search Misses',
    titleKn: 'Greedy Search ತಪ್ಪಿಸಿಕೊಳ್ಳುವ ಒಂದೂ ನಿಖರ ಉತ್ತರ ನಿಜವಾಗಿ ಕಂಡುಕೊಳ್ಳುವುದೂ',
    problem: "The lesson's greedy_single_branch (always taking the single best-scoring move) genuinely reached final=13 (NOT an exact match to the target), while tree_of_thoughts (keeping the top-3 beam alive at each depth) genuinely reached final=14 (an EXACT match), following the different path [1,6,7,14] instead of greedy's [1,6,12,13].\n1. Run both the lesson's exact greedy_single_branch and tree_of_thoughts and confirm greedy misses (13) while beam search succeeds exactly (14).\n2. Trace through WHY greedy takes a locally-optimal step at depth 2 (choosing 12, since score favors it) that turns out to be a dead end, while beam search's wider frontier kept the (7, -7) branch alive even though it scored worse at that intermediate step, letting it later reach the exact target.\n3. What does this prove about greedy (single-branch) search's fundamental limitation -- it can get stuck in a LOCAL optimum. Why does keeping multiple candidates alive (beam search) help escape this, even at the cost of exploring more paths?",
    problemKn: "ಪಾಠದ greedy_single_branch ನಿಜವಾಗಿ final=13 ತಲುಪಿತು (target ಗೆ ನಿಖರ ಹೊಂದಾಣಿಕೆ ಅಲ್ಲ), ಆದರೆ tree_of_thoughts ನಿಜವಾಗಿ final=14 (ನಿಖರ ಹೊಂದಾಣಿಕೆ) ತಲುಪಿತು.\n1. ಪಾಠದ ಎರಡೂ ನಿಖರ ಫಂಕ್ಷನ್ಸ್ ಚಲಾಯಿಸಿ ಮತ್ತು greedy 13 ಗೆ ತಪ್ಪುವುದೂ ಆದರೆ beam search ನಿಖರವಾಗಿ 14 ಪಡೆಯುವುದೂ ಖಚಿತಪಡಿಸಿ.\n2. greedy depth 2 ನಲ್ಲಿ ಸ್ಥಳೀಯವಾಗಿ-ಅತ್ಯುತ್ತಮ ಹೆಜ್ಜೆ ಏಕೆ ತೆಗೆದುಕೊಳ್ಳುತ್ತದೆ, ಇದೂ ಒಂದೂ dead end ಆಗಿ ಪರಿಣಮಿಸುತ್ತದೆ, ಆದರೆ beam search ya ಅಗಲವಾದ frontier ಕೆಟ್ಟ ಸ್ಕೋರ್ ಇರುವ branch ಇಟ್ಟುಕೊಂಡು ನಂತರ ನಿಖರ target ತಲುಪುತ್ತದೆ ಎಂದು ಪತ್ತೆಹಚ್ಚಿ.\n3. ಇದೂ greedy search ya ಮೂಲಭೂತ ಮಿತಿ ಬಗ್ಗೆ ಏನೂ ಸಾಬೀತುಪಡಿಸುತ್ತದೆ -- ಇದೂ ಒಂದೂ LOCAL optimum ನಲ್ಲಿ ಸಿಲುಕಿಕೊಳ್ಳಬಹುದು." },
  { phaseId, moduleId: m276, lessonId: l276, order: 2, difficulty: 'intermediate',
    title: 'Does a Wider Beam Always Help?',
    titleKn: 'ಅಗಲವಾದ Beam ಯಾವಾಗಲೂ ಸಹಾಯ ಮಾಡುತ್ತದೆಯೇ?',
    problem: "The lesson genuinely tested beam_width=2 (narrower than the default 3) and got final=13 (NOT exact) -- the SAME failure as pure greedy search, showing that a too-narrow beam degenerates back toward greedy's mistake.\n1. Run the lesson's exact beam_width=2 test and confirm it fails to reach the exact target, unlike beam_width=3.\n2. Why does narrowing the beam from 3 to 2 reintroduce the same local-optimum trap that pure greedy search (beam_width=1, effectively) fell into? Trace through the depth-1 frontier with beam_width=2 vs 3 and identify which candidate got dropped that mattered.\n3. Try beam_width=4 or 5 (wider than the lesson's default). Does it still find the exact answer? At what point (if any) does widening the beam stop mattering for THIS specific problem, and why might an even wider beam not help further?",
    problemKn: "ಪಾಠ ನಿಜವಾಗಿ beam_width=2 ಪರೀಕ್ಷಿಸಿ final=13 ಪಡೆಯಿತು -- pure greedy search ya ಅದೇ ವೈಫಲ್ಯ.\n1. ಪಾಠದ ನಿಖರ beam_width=2 test ಚಲಾಯಿಸಿ ಮತ್ತು ಇದೂ ನಿಖರ target ತಲುಪಲು ವಿಫಲಗೊಳ್ಳುತ್ತದೆ ಎಂದು ಖಚಿತಪಡಿಸಿ.\n2. beam ಅನ್ನೂ 3 ಇಂದ 2 ಗೆ ಕಿರಿದುಗೊಳಿಸುವುದೂ ಅದೇ local-optimum trap ಅನ್ನೂ ಏಕೆ ಮರುಪರಿಚಯಿಸುತ್ತದೆ?\n3. beam_width=4 ಅಥವಾ 5 ಪ್ರಯತ್ನಿಸಿ. ಇದೂ ಇನ್ನೂ ನಿಖರ ಉತ್ತರ ಕಂಡುಕೊಳ್ಳುತ್ತದೆಯೇ? ಈ ನಿರ್ದಿಷ್ಟ ಸಮಸ್ಯೆಗೆ beam ಅಗಲಗೊಳಿಸುವುದೂ ಮುಖ್ಯವಲ್ಲದಾಗುವ ಬಿಂದು ಯಾವುದೂ?" },
  { phaseId, moduleId: m276, lessonId: l276, order: 3, difficulty: 'advanced',
    title: 'The Real Cost of Tree Search',
    titleKn: 'Tree Search ya ನಿಜ ವೆಚ್ಚ',
    problem: "1. Based on candidate_moves() returning 3 possible moves at each state, and the lesson's beam_width=3 keeping the top 3 candidates at each depth, calculate how many total (state, score) evaluations happen at each depth level across the whole search (frontier_size * moves_per_state). Sum this across all 3 depths.\n2. Compare this total evaluation count to greedy_single_branch's evaluation count for the same depth. How many TIMES more evaluation work does beam search do, and does this match the intuition that tree search 'costs more' than greedy?\n3. If each 'move evaluation' represented a real LLM call (as it would in a genuine LLM-based Tree of Thoughts system, not this lesson's toy scoring function), would the accuracy gain (exact match vs missing by 1) be worth the extra cost, in your judgment? Justify considering both the magnitude of the accuracy gain and the magnitude of the cost increase.",
    problemKn: "1. candidate_moves() ಪ್ರತಿ state ಗೆ 3 ಸಂಭಾವ್ಯ moves ಹಿಂತಿರುಗಿಸುತ್ತದೆ, ಮತ್ತು beam_width=3 ಪ್ರತಿ depth ನಲ್ಲಿ ಟಾಪ್ 3 candidates ಇಟ್ಟುಕೊಳ್ಳುತ್ತದೆ ಎಂಬುದನ್ನೂ ಆಧರಿಸಿ, ಪ್ರತಿ depth level ನಲ್ಲಿ ಎಷ್ಟೂ ಒಟ್ಟೂ evaluations ಸಂಭವಿಸುತ್ತವೆ ಎಂದು ಲೆಕ್ಕಾಚಾರ ಮಾಡಿ.\n2. ಇದನ್ನೂ greedy_single_branch ya ಅದೇ depth ಗೆ evaluation count ಜೊತೆ ಹೋಲಿಸಿ. beam search ಎಷ್ಟೂ ಪಟ್ಟು ಹೆಚ್ಚು evaluation ಕೆಲಸ ಮಾಡುತ್ತದೆ?\n3. ಪ್ರತಿ 'move evaluation' ಒಂದೂ ನಿಜ LLM call ಪ್ರತಿನಿಧಿಸಿದರೆ, accuracy ಲಾಭ ಹೆಚ್ಚುವರಿ ವೆಚ್ಚಕ್ಕೆ ಯೋಗ್ಯವಾಗಿರುತ್ತದೆಯೇ ಎಂದು ನಿಮ್ಮ ತೀರ್ಪಿನಲ್ಲಿ ಸಮರ್ಥಿಸಿ." },

  // ── Module 277: Self-Refine and CRITIC ──
  { phaseId, moduleId: m277, lessonId: l277, order: 1, difficulty: 'intermediate',
    title: 'Self-Refine Genuinely Converging in One Iteration',
    titleKn: 'Self-Refine ನಿಜವಾಗಿ ಒಂದೂ Iteration ನಲ್ಲಿ ಒಮ್ಮುಖವಾಗುವುದೂ',
    problem: "The lesson's Self-Refine loop genuinely converged after 1 refinement: iter 0's draft ('This library is good.') had 2 issues (too short, unsupported claim), and iter 1's refined draft ('This library is effective because it reduces boilerplate...') had ZERO issues, genuinely converging.\n1. Run the lesson's exact generate_draft, critique, and refine functions through 2 iterations and confirm iter 0 has 2 issues while iter 1 has none.\n2. Look at the refine() function's logic: how does it specifically address BOTH issues found (too short AND unsupported claim) in a single refinement pass, rather than needing 2 separate refinement iterations (one per issue)?\n3. Design a draft that would need 2 GENUINE refinement iterations to converge (i.e. iter 1 still has at least 1 issue, and only iter 2 has none), based on critique()'s exact rules.",
    problemKn: "ಪಾಠದ Self-Refine loop 1 refinement ನಂತರ ನಿಜವಾಗಿ ಒಮ್ಮುಖವಾಯಿತು: iter 0 ya draft 2 issues ಹೊಂದಿತ್ತು, iter 1 ya refined draft ಶೂನ್ಯ issues ಹೊಂದಿತ್ತು.\n1. ಪಾಠದ ನಿಖರ generate_draft, critique, ಮತ್ತು refine functions ಅನ್ನೂ 2 iterations ಗೆ ಚಲಾಯಿಸಿ.\n2. refine() function ya logic ನೋಡಿ: ಇದೂ ಒಂದೂ ಏಕ refinement pass ನಲ್ಲಿ ಎರಡೂ issues ಅನ್ನೂ ಹೇಗೂ ಪರಿಹರಿಸುತ್ತದೆ?\n3. critique() ya ನಿಖರ ನಿಯಮಗಳ ಆಧಾರದ ಮೇಲೆ, ಒಮ್ಮುಖವಾಗಲು 2 ನಿಜ refinement iterations ಬೇಕಾಗುವ ಒಂದೂ draft ವಿನ್ಯಾಸಗೊಳಿಸಿ." },
  { phaseId, moduleId: m277, lessonId: l277, order: 2, difficulty: 'advanced',
    title: 'What Self-Refine Genuinely Cannot Catch',
    titleKn: 'Self-Refine ನಿಜವಾಗಿ ಏನೂ ಹಿಡಿಯಲಾಗುವುದಿಲ್ಲ',
    problem: "The lesson genuinely proved self_critique_only found ZERO issues in 'The capital of France is Lyon.' (a factually WRONG claim -- the real capital is Paris) since it only checks style/length, while critic_with_tool (verifying against GROUND_TRUTH) genuinely caught it: ['factual error: tool says capital of France is Paris, draft says otherwise'].\n1. Run both the lesson's exact self_critique_only and critic_with_tool on the Lyon claim and confirm self-critique misses it while CRITIC catches it.\n2. Why can self-critique (the model critiquing its own output using only its own knowledge/reasoning) never reliably catch factual errors about specific facts, while a TOOL-VERIFIED critique can? What's the fundamental limitation being demonstrated here?\n3. Run the lesson's combined pipeline (style_issues + fact_issues on 'France capital Lyon.') and note that fact_issues came back EMPTY even though the claim is wrong. Then run critic_with_tool_v2 and observe it DOES catch the error. What's different about critic_with_tool_v2's trigger condition that makes it more robust?",
    problemKn: "ಪಾಠ ನಿಜವಾಗಿ ಸಾಬೀತುಪಡಿಸಿತು self_critique_only 'The capital of France is Lyon.' (ವಾಸ್ತವಿಕವಾಗಿ ತಪ್ಪಾದ ಹೇಳಿಕೆ) ನಲ್ಲಿ ಶೂನ್ಯ issues ಕಂಡುಕೊಂಡಿತು, ಆದರೆ critic_with_tool ಅದನ್ನೂ ನಿಜವಾಗಿ ಹಿಡಿಯಿತು.\n1. ಪಾಠದ ಎರಡೂ ನಿಖರ functions ಅನ್ನೂ Lyon claim ಮೇಲೆ ಚಲಾಯಿಸಿ.\n2. self-critique ನಿರ್ದಿಷ್ಟ facts ಬಗ್ಗೆ ವಾಸ್ತವಿಕ ದೋಷಗಳನ್ನೂ ಏಕೆ ಎಂದಿಗೂ ವಿಶ್ವಾಸಾರ್ಹವಾಗಿ ಹಿಡಿಯಲಾಗುವುದಿಲ್ಲ, tool-verified critique ಹಿಡಿಯುತ್ತಿರುವಾಗ?\n3. ಪಾಠದ combined pipeline ಚಲಾಯಿಸಿ ('France capital Lyon.' ಮೇಲೆ) ಮತ್ತು fact_issues ಖಾಲಿ ಬಂದದ್ದನ್ನೂ ಗಮನಿಸಿ. ನಂತರ critic_with_tool_v2 ಚಲಾಯಿಸಿ ಮತ್ತು ಇದೂ ದೋಷ ಹಿಡಿಯುತ್ತದೆ ಎಂದು ಗಮನಿಸಿ. v2 ya trigger condition ಹೇಗೂ ಹೆಚ್ಚು ದೃಢವಾಗಿದೆ?" },
  { phaseId, moduleId: m277, lessonId: l277, order: 3, difficulty: 'intermediate',
    title: 'Combining Style Critique and Fact-Checking',
    titleKn: 'Style Critique ಮತ್ತು Fact-Checking ಸಂಯೋಜಿಸುವುದೂ',
    problem: "The lesson's combined pipeline on 'France capital Lyon.' genuinely found 1 style issue ('too short') and 0 fact issues (using the ORIGINAL, less robust critic_with_tool trigger), totaling 1 distinct problem -- even though the claim is ALSO factually wrong.\n1. Run the lesson's exact combined pipeline and confirm the 1 style issue + 0 fact issues result.\n2. Now substitute critic_with_tool_v2 (the more robust version from later in the lesson) into the combined pipeline. Does the total distinct-problems count change? What does this reveal about how the QUALITY of your fact-checking trigger affects the whole pipeline's usefulness?\n3. Design a genuine 'best of both' critique function that runs style checks AND the more robust v2 fact-check together, and test it on 3 different draft claims of your own (one with only a style issue, one with only a factual issue, one with both).",
    problemKn: "ಪಾಠದ combined pipeline 'France capital Lyon.' ಮೇಲೆ ನಿಜವಾಗಿ 1 style issue ಮತ್ತು 0 fact issues ಕಂಡುಕೊಂಡಿತು (ಮೂಲ, ಕಡಿಮೆ ದೃಢ trigger ಬಳಸಿ).\n1. ಪಾಠದ ನಿಖರ combined pipeline ಚಲಾಯಿಸಿ.\n2. ಈಗ critic_with_tool_v2 ಅನ್ನೂ pipeline ಗೆ ಬದಲಿಸಿ. ಒಟ್ಟೂ distinct-problems count ಬದಲಾಗುತ್ತದೆಯೇ?\n3. style checks ಮತ್ತು v2 fact-check ಎರಡನ್ನೂ ಒಟ್ಟಿಗೆ ಚಲಾಯಿಸುವ ನಿಮ್ಮ ಸ್ವಂತ 'best of both' critique function ವಿನ್ಯಾಸಗೊಳಿಸಿ ಮತ್ತು 3 ವಿಭಿನ್ನ draft claims ಮೇಲೆ ಪರೀಕ್ಷಿಸಿ." },

  // ── Module 278: Tool Use and Function Calling ──
  { phaseId, moduleId: m278, lessonId: l278, order: 1, difficulty: 'intermediate',
    title: 'Genuinely Validating a Schema Before Executing',
    titleKn: 'Execute ಮಾಡುವ ಮೊದಲು Schema ಅನ್ನೂ ನಿಜವಾಗಿ ಮೌಲ್ಯೀಕರಿಸುವುದೂ',
    problem: "The lesson's TOOL_SCHEMA-validated get_weather genuinely EXECUTED for a valid call ({'city':'Tokyo','units':'celsius'} -> temp=18) but genuinely REJECTED an invalid call ({'units':'kelvin'}) with two specific errors: missing required 'city' AND 'kelvin' not in the allowed enum ['celsius','fahrenheit'].\n1. Run the lesson's exact validate_call on both calls and confirm the execution succeeds for the valid one and produces exactly these 2 errors for the invalid one.\n2. Why does the validator report BOTH errors at once (missing city AND bad units) rather than stopping at the first one found? How does this help an LLM fix its tool call faster in a single retry?\n3. Design a THIRD test call that has neither error alone but combines a different pair of problems (e.g. valid units but a numeric city value). Predict what validate_call would report, then test it.",
    problemKn: "ಪಾಠದ TOOL_SCHEMA-ಮೌಲ್ಯೀಕರಿಸಿದ get_weather ಒಂದೂ ಮಾನ್ಯ call ಗೆ ನಿಜವಾಗಿ EXECUTED ಆಯಿತು ಆದರೆ ಒಂದೂ ಅಮಾನ್ಯ call ಅನ್ನೂ ಎರಡೂ ನಿರ್ದಿಷ್ಟ ದೋಷಗಳೊಂದಿಗೆ ನಿಜವಾಗಿ ತಿರಸ್ಕರಿಸಿತು.\n1. ಪಾಠದ ನಿಖರ validate_call ಅನ್ನೂ ಎರಡೂ calls ಮೇಲೆ ಚಲಾಯಿಸಿ.\n2. validator ಎರಡೂ ದೋಷಗಳನ್ನೂ ಏಕೆ ಒಂದೇ ಬಾರಿ ವರದಿ ಮಾಡುತ್ತದೆ, ಮೊದಲನೆಯದರಲ್ಲಿ ನಿಲ್ಲುವ ಬದಲಿಗೆ?\n3. ಬೇರೆ ಎರಡೂ ಸಮಸ್ಯೆಗಳ ಸಂಯೋಜನೆ ಇರುವ ಮೂರನೇ test call ವಿನ್ಯಾಸಗೊಳಿಸಿ. validate_call ಏನೂ ವರದಿ ಮಾಡುತ್ತದೆ ಎಂದು ಊಹಿಸಿ, ನಂತರ ಪರೀಕ್ಷಿಸಿ." },
  { phaseId, moduleId: m278, lessonId: l278, order: 2, difficulty: 'intermediate',
    title: 'What Happens Without Validation, Genuinely Crashed',
    titleKn: 'Validation ಇಲ್ಲದೆ ಏನಾಗುತ್ತದೆ, ನಿಜವಾಗಿ Crashed',
    problem: "The lesson genuinely showed that skipping validation and calling get_weather(**args) directly with the malformed {'units':'kelvin'} call genuinely crashed with TypeError: get_weather() missing 1 required positional argument: 'city' -- a raw Python exception instead of a structured, retry-friendly error message.\n1. Run the lesson's exact unvalidated call and confirm the TypeError.\n2. Compare this TypeError's message to the validated version's structured error list from the previous exercise. Which would be more useful for an LLM trying to fix its own tool call on retry, and why?\n3. This connects to Module 254's 'errors as retry guidance' principle. Rewrite the raw TypeError as a good_error-style message (specific, example-driven) that would help an LLM retry correctly.",
    problemKn: "ಪಾಠ ನಿಜವಾಗಿ ತೋರಿಸಿತು validation ಬಿಟ್ಟುಬಿಟ್ಟು get_weather(**args) ಅನ್ನೂ ನೇರವಾಗಿ ಕರೆ ಮಾಡುವುದೂ ನಿಜವಾಗಿ TypeError ಜೊತೆ ಕ್ರ್ಯಾಶ್ ಆಯಿತು.\n1. ಪಾಠದ ನಿಖರ unvalidated call ಚಲಾಯಿಸಿ ಮತ್ತು TypeError ಖಚಿತಪಡಿಸಿ.\n2. ಈ TypeError ya ಸಂದೇಶವನ್ನೂ ಮೌಲ್ಯೀಕರಿಸಿದ ಆವೃತ್ತಿಯ structured error list ಜೊತೆ ಹೋಲಿಸಿ. ಒಂದೂ LLM ಗೆ retry ಮಾಡಲು ಯಾವುದೂ ಹೆಚ್ಚು ಉಪಯುಕ್ತ?\n3. ಇದನ್ನೂ Module 254 ya 'errors as retry guidance' ತತ್ವಕ್ಕೆ ಸಂಪರ್ಕಿಸಿ. raw TypeError ಅನ್ನೂ ಒಂದೂ good_error-style ಸಂದೇಶವಾಗಿ ಮರುಬರೆಯಿರಿ." },
  { phaseId, moduleId: m278, lessonId: l278, order: 3, difficulty: 'intermediate',
    title: 'Extending the Schema to Catch Type Mismatches',
    titleKn: 'Type Mismatches ಹಿಡಿಯಲು Schema ವಿಸ್ತರಿಸುವುದೂ',
    problem: "The lesson's extended validate_call genuinely caught a type mismatch: bad_type_call={'city': 12345} produced ['city: expected string, got int'], even though 'city' was PRESENT (just the wrong type).\n1. Run the lesson's exact bad_type_call example and confirm the type-mismatch error.\n2. This is a DIFFERENT kind of validation than 'missing required field' or 'not in enum' from the earlier exercises. Why does a schema validator need explicit TYPE checking as a third distinct category of validation, beyond presence and enum-membership checks?\n3. What does the lesson's final heading 'What Validation Does Not Cover' likely refer to, based on everything you've learned in this module about self-critique's limits (Module 277) not catching factual errors? Name one thing schema validation genuinely CANNOT catch about a tool call, even with perfect type/enum/required checking.",
    problemKn: "ಪಾಠದ ವಿಸ್ತೃತ validate_call ನಿಜವಾಗಿ ಒಂದೂ type mismatch ಹಿಡಿಯಿತು: bad_type_call={'city': 12345} ['city: expected string, got int'] ಉತ್ಪಾದಿಸಿತು.\n1. ಪಾಠದ ನಿಖರ bad_type_call ಉದಾಹರಣೆ ಚಲಾಯಿಸಿ.\n2. ಇದೂ 'missing required field' ಅಥವಾ 'not in enum' ಗಿಂತ ಭಿನ್ನ ರೀತಿಯ validation ಆಗಿದೆ. ಒಂದೂ schema validator ಗೆ ಸ್ಪಷ್ಟ TYPE checking ಒಂದೂ ಮೂರನೇ ಪ್ರತ್ಯೇಕ validation ವರ್ಗವಾಗಿ ಏಕೆ ಬೇಕು?\n3. ಪಾಠದ ಅಂತಿಮ ಶೀರ್ಷಿಕೆ 'What Validation Does Not Cover' ಬಹುಶಃ ಏನನ್ನೂ ಉಲ್ಲೇಖಿಸುತ್ತದೆ, Module 277 ya self-critique ya ಮಿತಿಗಳ ಆಧಾರದ ಮೇಲೆ? schema validation ಒಂದೂ tool call ಬಗ್ಗೆ ನಿಜವಾಗಿ ಹಿಡಿಯಲಾಗದ ಒಂದೂ ವಿಷಯ ಹೆಸರಿಸಿ." },
];
