module.exports = {
  lessonId: '6a4e5e37f581c004106313d7',
  outFile: './lesson-defs/lesson311.js',
  fills: {
    b3: { headingKn: 'ಒಂದು condition True ಅಥವಾ False ಗೆ evaluate ಆಗುತ್ತದೆ', descKn: 'Condition True ಆಗಿರುವುದರಿಂದ, program ಒಂದು action ನಿರ್ವಹಿಸಬಹುದು.' },
    b8: { headingKn: 'ಉದಾಹರಣೆ 1 — ಮತದಾನ ಅರ್ಹತೆ', descKn: 'age >= 18 True ಆಗಿರುವುದರಿಂದ, Python print() statement execute ಮಾಡುತ್ತದೆ.' },
    b10: { headingKn: 'ಉದಾಹರಣೆ 2 — pass ಪರಿಶೀಲನೆ' },
    b12: { headingKn: 'ಉದಾಹರಣೆ 3 — ಬಿಸಿಲಿನ ದಿನ ಪರಿಶೀಲನೆ' },
    b15: { headingKn: 'ಒಂದು false condition ಯಾವುದೇ output ಉತ್ಪಾದಿಸುವುದಿಲ್ಲ' },
    b18: { headingKn: 'ನಿಮ್ಮ Handbook ನ ಒಂದು ಉದಾಹರಣೆ', descKn: '22 > 9 True ಆಗಿರುವುದರಿಂದ, print("greater") execute ಆಗುತ್ತದೆ ಮತ್ತು else block ನಿರ್ಲಕ್ಷಿಸಲಾಗುತ್ತದೆ.' },
    b20: { headingKn: 'ಒಂದು False Condition ಜೊತೆ ಉದಾಹರಣೆ', descKn: '5 > 9 False ಆಗಿರುವುದರಿಂದ, Python else block execute ಮಾಡುತ್ತದೆ.' },
    b22: { textKn: 'balance = 5000\nwithdraw = 7000\n\nif withdraw <= balance:\n    print("Transaction Successful")\nelse:\n    print("Insufficient Balance")' },
    b24: { textKn: 'age = 17\n\nif age >= 18:\n    print("Eligible to Vote")\nelse:\n    print("Not Eligible")' },
    b27: { headingKn: 'ಉದಾಹರಣೆ — ವಿದ್ಯಾರ್ಥಿ Grades', descKn: '82 >= 90 False, 82 >= 75 True, ಆದ್ದರಿಂದ Python Grade A ಮುದ್ರಿಸುತ್ತದೆ ಮತ್ತು ಉಳಿದದ್ದನ್ನು ಬಿಟ್ಟುಬಿಡುತ್ತದೆ.' },
    b30: { captionKn: 'Conditions ನಲ್ಲಿ ಬಳಸುವ Comparison Operators' },
    b32: { headingKn: 'ಒಂದು nested if ಉದಾಹರಣೆ' },
    b34: { textKn: 'ನಿಜ-ಜಗತ್ತಿನ ಉದಾಹರಣೆಗಳು' },
    b35: { headingKn: 'ಉದಾಹರಣೆ 1 — Weather' },
    b37: { headingKn: 'ಉದಾಹರಣೆ 2 — Sunday' },
    b39: { headingKn: "ಉದಾಹರಣೆ 3 — ಪೋಷಕರ ಅನುಮತಿ" },
    b41: { headingKn: 'ಉದಾಹರಣೆ 4 — Login System' },
    b43: { headingKn: 'ಸಂಪೂರ್ಣ ಉದಾಹರಣೆ Program — ವಿದ್ಯಾರ್ಥಿ Grade Calculator' },
    b45: { headingKn: 'Mini Project – Movie Ticket ಬೆಲೆ' },
  },
  quizKn: [
    { qKn: 'ಒಂದು conditional statement ಎಂದರೇನು?', optsKn: ['ಯಾವುದೇ condition ಲೆಕ್ಕಿಸದೆ ಯಾವಾಗಲೂ execute ಆಗುವ ಒಂದು statement', 'ಒಂದು condition True ಅಥವಾ False ಎಂಬುದರ ಆಧಾರದ ಮೇಲೆ ಒಂದು program ನಿರ್ಧಾರಗಳನ್ನು ತೆಗೆದುಕೊಳ್ಳಲು ಅನುಮತಿಸುವ ಒಂದು statement', 'ಕೇವಲ variables ಘೋಷಿಸಲು ಬಳಸುವ ಒಂದು statement', 'ಕೋಡ್ ಅನ್ನು ಅನೇಕ ಬಾರಿ ಪುನರಾವರ್ತಿಸುವ ಒಂದು loop'] },
    { qKn: 'if statement ಏನು ಮಾಡುತ್ತದೆ?', optsKn: ['Condition True ಆಗಿದ್ದರೆ ಮಾತ್ರ ಇದು ಕೋಡ್ ನ ಒಂದು block execute ಮಾಡುತ್ತದೆ', 'Condition False ಆಗುವವರೆಗೆ ಇದು ಕೋಡ್ ನ ಒಂದು block ಪುನರಾವರ್ತಿತವಾಗಿ execute ಮಾಡುತ್ತದೆ', 'Condition ಇರಲಿ ಇಲ್ಲದಿರಲಿ ಇದು ಯಾವಾಗಲೂ ತನ್ನ block execute ಮಾಡುತ್ತದೆ', 'ಇದು condition ಬಿಟ್ಟುಬಿಟ್ಟು ಬದಲಿಗೆ else block ಓಡಿಸುತ್ತದೆ'] },
    { qKn: 'else block ಯಾವಾಗ execute ಆಗುತ್ತದೆ?', optsKn: ['if condition True ಆಗಿದ್ದಾಗ ಮಾತ್ರ', 'if (ಮತ್ತು ಎಲ್ಲಾ elif, ಇದ್ದರೆ) conditions False ಗೆ evaluate ಆದಾಗ', 'ಪ್ರತಿ ಬಾರಿ, if block ಜೊತೆಗೆ', 'ಕೋಡ್ ನಲ್ಲಿ ಯಾವುದೇ elif ಇಲ್ಲದಿದ್ದಾಗ ಮಾತ್ರ'] },
    { qKn: 'elif ಎಂದರೆ ಏನು ಮತ್ತು ಇದನ್ನು ಯಾವಾಗ ಬಳಸಲಾಗುತ್ತದೆ?', optsKn: ['"Else if" — ಒಂದು if ನಂತರ ಹೆಚ್ಚುವರಿ conditions ಪರೀಕ್ಷಿಸಲು ಬಳಸಲಾಗುತ್ತದೆ', '"End if" — ಒಂದು if block ಮುಚ್ಚಲು ಬಳಸಲಾಗುತ್ತದೆ', '"Either if" — OR ಜೊತೆ ಎರಡು conditions ಸಂಯೋಜಿಸಲು ಬಳಸಲಾಗುತ್ತದೆ', 'ಯಾವುದೇ functional ವ್ಯತ್ಯಾಸವಿಲ್ಲದ else ನ ಒಂದು ಸಮಾನಾರ್ಥಕ'] },
    { qKn: 'ಇದರ output ಏನು: a = 22; if a > 9: print("greater") else: print("lesser")', optsKn: ['lesser', 'greater', 'ಯಾವುದೇ output ಇಲ್ಲ', 'Error'] },
    { qKn: 'ಇದರ output ಏನು: marks = 80; if marks >= 90: print("A+") elif marks >= 75: print("A") elif marks >= 60: print("B") else: print("Fail")', optsKn: ['A+', 'A', 'B', 'Fail'] },
  ],
};
