module.exports = {
  lessonId: '6a4e5940ed9825cd02b43dbe',
  outFile: './lesson-defs/lesson309.js',
  fills: {
    b2: { captionKn: 'Key → Value, ಒಂದು ನಿಜ dictionary ನಂತೆ' },
    b3: { headingKn: 'Python ನಲ್ಲಿ ಒಂದು dictionary', descKn: '"name" key, "Rahul" ಮೌಲ್ಯ.' },
    b5: { headingKn: 'ಒಂದು dictionary ರಚಿಸುವುದು ಮತ್ತು ಮುದ್ರಿಸುವುದು' },
    b8: { headingKn: 'Key ಮೂಲಕ ಪ್ರವೇಶಿಸುವುದು' },
    b11: { headingKn: 'ಒಂದು dictionary ನಲ್ಲಿ ಮಿಶ್ರ data types' },
    b13: { textKn: 'Python Dictionaries ನ Properties' },
    b15: { headingKn: 'ಒಂದು ಮೌಲ್ಯ ಬದಲಾಯಿಸುವುದು' },
    b17: { textKn: 'ಒಬ್ಬ ವಿದ್ಯಾರ್ಥಿಯ ವಯಸ್ಸು ಪ್ರತಿ ವರ್ಷ ಬದಲಾಗುತ್ತದೆ.' },
    b19: { headingKn: 'List ಒಂದು numeric index ಬಳಸುತ್ತದೆ' },
    b21: { headingKn: 'Dictionary ಒಂದು key ಬಳಸುತ್ತದೆ' },
    b24: { headingKn: 'ಒಂದು duplicate key ಬರೆಯುವುದು' },
    b28: { headingKn: 'ಸರಿ' },
    b29: { headingKn: 'ತಪ್ಪು', descKn: 'ಕೊನೆಯ ಮೌಲ್ಯ ಮಾತ್ರ ಸಂಗ್ರಹವಾಗುತ್ತದೆ.' },
    b31: { textKn: 'Dictionary Methods' },
    b32: { headingKn: 'ನಾವು ಈ ಕೆಳಗಿನ dictionary ಹೊಂದಿದ್ದೇವೆ ಎಂದು ಭಾವಿಸೋಣ' },
    b34: { headingKn: 'items() ಬಳಸುವುದು' },
    b36: { textKn: 'ಒಂದು ಶಾಲೆ ಪ್ರತಿ ವಿದ್ಯಾರ್ಥಿಯ ವಿವರ ಮುದ್ರಿಸುತ್ತದೆ.' },
    b38: { headingKn: 'keys() ಬಳಸುವುದು' },
    b41: { headingKn: 'values() ಬಳಸುವುದು' },
    b44: { headingKn: 'ಉದಾಹರಣೆ 1 — Add' },
    b46: { headingKn: 'ಉದಾಹರಣೆ 2 — Update' },
    b48: { textKn: 'ಒಬ್ಬ ವಿದ್ಯಾರ್ಥಿಯ ವಿಳಾಸ ಬದಲಾಗುತ್ತದೆ.' },
    b50: { headingKn: 'get() ಬಳಸುವುದು' },
    b52: { headingKn: 'Key ಅಸ್ತಿತ್ವದಲ್ಲಿ ಇಲ್ಲದಿದ್ದರೆ' },
    b55: { headingKn: '[ ] ಬಳಸುವುದು' },
    b57: { headingKn: 'get() ಬಳಸುವುದು' },
    b59: { headingKn: 'ಸಂಪೂರ್ಣ ಉದಾಹರಣೆ Program' },
    b61: { headingKn: 'ನಿಜ-ಜಗತ್ತಿನ ಉದಾಹರಣೆ: Employee Database' },
    b63: { captionKn: 'Dictionary vs List vs Tuple' },
  },
  quizKn: [
    { qKn: 'Python ನಲ್ಲಿ ಒಂದು dictionary ಎಂದರೇನು?', optsKn: ['ಕೇವಲ numeric index ಮೂಲಕ ಪ್ರವೇಶಿಸುವ ಒಂದು ಕ್ರಮಬದ್ಧ ಸಂಗ್ರಹ', 'key-value ಜೋಡಿಗಳ ಒಂದು mutable ಸಂಗ್ರಹ', 'ಅಕ್ಷರಗಳ ಒಂದು immutable sequence', 'ಕೇವಲ duplicate ಮೌಲ್ಯಗಳನ್ನು ಸಂಗ್ರಹಿಸುವ ಒಂದು ಸಂಗ್ರಹ'] },
    { qKn: 'ಒಂದು dictionary ನಲ್ಲಿ key ಮತ್ತು value ನಡುವಿನ ವ್ಯತ್ಯಾಸ ಏನು?', optsKn: ['ಯಾವುದೇ ವ್ಯತ್ಯಾಸವಿಲ್ಲ, ಅವು ಒಂದೇ ವಿಷಯ', 'ಒಂದು key ಡೇಟಾವನ್ನು ಗುರುತಿಸುತ್ತದೆ, ಮತ್ತು value ಆ key ಗಾಗಿ ಸಂಗ್ರಹಿಸಿದ ಮಾಹಿತಿ', 'ಒಂದು key ಯಾವಾಗಲೂ ಒಂದು ಸಂಖ್ಯೆ, ಮತ್ತು ಒಂದು value ಯಾವಾಗಲೂ ಒಂದು string', 'ಒಂದು value ವಿಶಿಷ್ಟವಾಗಿರಬೇಕು, ಆದರೆ ಒಂದು key ಪುನರಾವರ್ತಿಸಬಹುದು'] },
    { qKn: 'ಒಂದು dictionary duplicate keys ಹೊಂದಬಹುದೇ?', optsKn: ['ಹೌದು, ಮತ್ತು ಎರಡೂ ಮೌಲ್ಯಗಳು ಪ್ರತ್ಯೇಕವಾಗಿ ಸಂಗ್ರಹವಾಗುತ್ತವೆ', 'ಹೌದು, ಆದರೆ ಕೇವಲ numeric keys ಗಳಿಗೆ', 'ಇಲ್ಲ, keys ವಿಶಿಷ್ಟವಾಗಿರಬೇಕು — ಕೊನೆಯ ಮೌಲ್ಯ ಮೊದಲಿನವುಗಳನ್ನು overwrite ಮಾಡುತ್ತದೆ', 'ಇಲ್ಲ, ಮತ್ತು ನೀವು ಪ್ರಯತ್ನಿಸಿದರೆ Python ತಕ್ಷಣ ಒಂದು error ಎಸೆಯುತ್ತದೆ'] },
    { qKn: 'ಯಾವ method ಒಂದು dictionary ನ keys ಅನ್ನು ಮಾತ್ರ ಹಿಂತಿರುಗಿಸುತ್ತದೆ?', optsKn: ['values()', 'items()', 'get()', 'keys()'] },
    { qKn: 'ಯಾವ method ಒಂದು dictionary ನ ಎಲ್ಲಾ key-value ಜೋಡಿಗಳನ್ನು ಹಿಂತಿರುಗಿಸುತ್ತದೆ?', optsKn: ['items()', 'keys()', 'values()', 'update()'] },
    { qKn: '"age" ಒಂದು dictionary ನಲ್ಲಿ ಅಸ್ತಿತ್ವದಲ್ಲಿ ಇಲ್ಲದಿದ್ದರೆ, student["age"] ಮತ್ತು student.get("age") ನಡುವಿನ ವ್ಯತ್ಯಾಸ ಏನು?', optsKn: ['ಎರಡೂ None ಹಿಂತಿರುಗಿಸುತ್ತವೆ', 'student["age"] ಒಂದು KeyError ಎಸೆಯುತ್ತದೆ, ಆದರೆ student.get("age") None ಹಿಂತಿರುಗಿಸುತ್ತದೆ', 'ಎರಡೂ ಒಂದು KeyError ಎಸೆಯುತ್ತವೆ', 'student["age"] None ಹಿಂತಿರುಗಿಸುತ್ತದೆ, ಆದರೆ student.get("age") ಒಂದು KeyError ಎಸೆಯುತ್ತದೆ'] },
  ],
};
